---
sidebar: sidebar 
permalink: ontap-security-hardening/autosupport.html 
keywords: tr-4569, ontap hardening guide, security, proactively monitor, NetApp Digital Advisor, logs, context-sensitive data, configuration and status data, performance data, use https 
summary: ONTAP의 AutoSupport 기능을 사용하여 시스템 상태를 사전에 모니터링할 수 있습니다. 
---
= NetApp AutoSupport를 참조하십시오
:hardbreaks:
:allow-uri-read: 
:icons: font
:linkattrs: 
:imagesdir: ../media


[role="lead"]
ONTAP의 AutoSupport 기능을 사용하면 시스템의 상태를 사전에 모니터링하고 메시지와 세부 정보를 NetApp 기술 지원, 조직의 내부 지원 팀 또는 지원 파트너에게 자동으로 보낼 수 있습니다. 기본적으로 스토리지 시스템을 처음 구성하면 NetApp 기술 지원에 보내는 AutoSupport 메시지가 사용하도록 설정됩니다. 또한 AutoSupport는 NetApp 기술 지원이 활성화된 후 24시간 후에 메시지를 보내기 시작합니다. 이 24시간 기간은 구성 가능합니다. 조직의 내부 지원 팀과의 통신을 활용하려면 메일 호스트 구성을 완료해야 합니다.

클러스터 관리자만 AutoSupport 관리(구성)를 수행할 수 있습니다. SVM 관리자는 AutoSupport에 액세스할 수 없습니다. AutoSupport 기능을 비활성화할 수 있습니다. 하지만 NetApp 스토리지 시스템에서 문제가 발생하는 경우 AutoSupport가 문제를 더 빠르게 식별하고 해결할 수 있도록 이 기능을 사용하도록 설정하는 것이 좋습니다. 기본적으로 시스템은 AutoSupport 정보를 수집하여 사용자가 AutoSupport를 사용하지 않도록 설정한 경우에도 로컬에 저장합니다.

다양한 메시지에 포함된 내용 및 다양한 유형의 메시지가 전송되는 위치를 비롯하여 AutoSupport 메시지에 대한 자세한 내용은 설명서를 참조하십시오. link:https://activeiq.netapp.com/custom-dashboard/search["NetApp Active IQ 디지털 자문업체"^]

AutoSupport 메시지에는 다음 항목을 포함하되 이에 국한되지 않는 중요한 데이터가 포함됩니다.

* 로그 파일
* 특정 하위 시스템과 관련된 상황에 맞는 데이터입니다
* 구성 및 상태 데이터
* 성능 데이터


AutoSupport는 전송 프로토콜을 위해 HTTPS, HTTP 및 SMTP를 지원합니다. AutoSupport 메시지는 기본적으로 민감하므로 NetApp 지원에 AutoSupport 메시지를 보낼 때 HTTPS를 기본 전송 프로토콜로 사용하는 것이 좋습니다.

또한 명령을 활용하여 `system node autosupport modify` AutoSupport 데이터의 타겟을 지정해야 합니다(예: NetApp 기술 지원, 조직의 내부 운영, 파트너). 이 명령을 사용하여 보낼 특정 AutoSupport 세부 정보(예: 성능 데이터, 로그 파일 등)를 지정할 수도 있습니다.

AutoSupport를 완전히 해제하려면 `system node autosupport modify -state disable` 명령을 사용합니다.
