---
sidebar: sidebar 
permalink: ontap-security-hardening/system-auditing.html 
keywords: tr-4569, ontap hardening guide, security, log forwarding, log encryption, events, syslog, audit, event notification 
summary: ONTAP 이벤트를 원격 syslog 서버로 오프로드하여 이벤트 감사의 무결성을 보장합니다. 
---
= 스토리지 관리 시스템 감사
:hardbreaks:
:allow-uri-read: 
:icons: font
:linkattrs: 
:imagesdir: ../media


[role="lead"]
ONTAP 이벤트를 원격 syslog 서버로 오프로드하여 이벤트 감사의 무결성을 보장합니다. 이 서버는 Splunk와 같은 보안 정보 이벤트 관리 시스템이 될 수 있습니다.



== syslog를 보냅니다

로그 및 감사 정보는 지원 및 가용성의 관점에서 조직에 매우 중요합니다. 또한 로그(syslog) 및 감사 보고서/출력에 포함된 정보와 세부 정보는 일반적으로 민감한 특성입니다. 보안 제어 및 상태를 유지하려면 조직에서 로그 및 감사 데이터를 안전하게 관리해야 합니다.

syslog 정보의 오프로드는 침입의 범위 또는 설치 공간을 단일 시스템 또는 솔루션으로 제한하는 데 필요합니다. 따라서 syslog 정보를 안전한 스토리지 또는 보존 위치로 안전하게 오프로딩하는 것이 좋습니다.



=== 로그 전달 대상을 생성합니다

명령을 사용하여 `cluster log-forwarding create` 원격 로깅을 위한 로그 전달 대상을 생성할 수 있습니다.

.매개 변수
다음 매개 변수를 사용하여 `cluster log-forwarding create` 명령을 구성합니다.

* * 대상 호스트. * 이 이름은 로그를 전달할 서버의 호스트 이름 또는 IPv4 또는 IPv6 주소입니다.
+
[listing]
----
-destination <Remote InetAddress>
----
* * 대상 포트. * 대상 서버가 수신 대기하는 포트입니다.
+
[listing]
----
[-port <integer>]
----
* * 로그 전달 프로토콜. * 이 프로토콜은 메시지를 대상으로 보내는 데 사용됩니다.
+
[listing]
----
[-protocol \{udp-unencrypted|tcp-unencrypted|tcp-encrypted}]
----
+
로그 전달 프로토콜은 다음 값 중 하나를 사용할 수 있습니다.

+
** `udp-unencrypted`.. 보안이 없는 사용자 데이터그램 프로토콜.
** `tcp-unencrypted`.. 보안 기능이 없는 TCP.
** `tcp-encrypted`.. TLS(Transport Layer Security)를 사용하는 TCP.


* * 대상 서버 ID를 확인하십시오. * 이 매개 변수를 true로 설정하면 해당 인증서의 유효성을 확인하여 로그 전달 대상의 ID를 확인합니다. 프로토콜 필드에서 값을 선택한 경우에만 이 값을 TRUE로 설정할 수 `tcpencrypted` 있습니다.
+
[listing]
----
[-verify-server \{true|false}]
----
* * Syslog 기능. * 이 값은 전달된 로그에 사용할 syslog 기능입니다.
+
[listing]
----
[-facility <Syslog Facility>]
----
* * 연결 테스트를 건너뜁니다. * 일반적으로 이 `cluster log-forwarding create` 명령은 ICMP(Internet Control Message Protocol) ping을 보내 대상에 연결할 수 있는지 확인하고 도달할 수 없는 경우 실패합니다. 이 값을 설정하면 `true` Ping 검사를 무시하여 대상에 도달할 수 없을 때 구성할 수 있습니다.
+
[listing]
----
[-force [true]]
----



NOTE: NetApp에서는 명령을 사용하여 유형에 강제로 연결하는 것이 `cluster log-forwarding` `-tcp-encrypted` 좋습니다.



== 이벤트 알림

시스템에서 나가는 정보와 데이터의 보호는 시스템의 보안 상태를 유지하고 관리하는 데 있어 매우 중요합니다. ONTAP 솔루션에 의해 생성되는 이벤트는 솔루션이 마주치는 내용, 처리되는 정보 등에 대한 풍부한 정보를 제공합니다. 데이터가 활발하게 사용됨에 따라 데이터를 안전하게 관리하고 마이그레이션해야 할 필요성이 대두되었습니다.

이 `event notification create` 명령은 이벤트 필터로 정의된 일련의 이벤트에 대한 새 알림을 하나 이상의 알림 대상으로 보냅니다. 다음 예에서는 구성된 이벤트 알림 필터 및 대상을 표시하는 이벤트 알림 구성 및 `event notification show` 명령을 보여 줍니다.

[listing]
----
cluster1::> event notification create -filter-name filter1 -destinations
 email_dest,syslog_dest,snmp-traphost

cluster1::> event notification show
ID     Filter Name       Destinations
-----  ----------------  -----------------
1 filter1 email_dest, syslog_dest, snmp-traphost
----