---
permalink: s3-config/assess-networking-requirements-task.html 
sidebar: sidebar 
keywords: assess, networking, requirements 
summary: S3 스토리지를 클라이언트에 제공하기 전에 네트워킹이 S3 프로비저닝 요구사항을 충족하도록 올바르게 구성되었는지 확인해야 합니다. 
---
= 네트워킹 요구 사항을 평가합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
S3 스토리지를 클라이언트에 제공하기 전에 네트워킹이 S3 프로비저닝 요구사항을 충족하도록 올바르게 구성되었는지 확인해야 합니다.

.필요한 것
다음과 같은 클러스터 네트워킹 객체를 구성해야 합니다.

* 물리적 및 논리적 포트
* 브로드캐스트 도메인
* 서브넷(필요한 경우)
* IPspace(기본 IPspace 외에 필요 시)
* 페일오버 그룹(필요에 따라 각 브로드캐스트 도메인의 기본 페일오버 그룹 추가)
* 외부 방화벽


.이 작업에 대해
원격 FabricPool 용량(클라우드) 계층 및 원격 S3 클라이언트의 경우 데이터 SVM을 사용하고 데이터 LIF를 구성해야 합니다. FabricPool 클라우드 계층의 경우 클러스터 피어링이 필요하지 않으므로 인터클러스터 LIF도 구성해야 합니다.

로컬 FabricPool 용량 계층의 경우 시스템 SVM("클러스터")을 사용해야 하지만 LIF 구성을 위한 두 가지 옵션이 있습니다.

* 클러스터 LIF를 사용할 수 있습니다.
+
이 옵션을 선택하면 더 이상 LIF 구성이 필요하지 않지만 클러스터 LIF의 트래픽이 증가합니다. 또한 로컬 계층은 다른 클러스터에서 액세스할 수 없습니다.

* 데이터 및 인터클러스터 LIF를 사용할 수 있습니다.
+
이 옵션을 사용하려면 S3 프로토콜에 LIF를 설정하는 등 추가 구성이 필요합니다. 하지만 로컬 계층도 다른 클러스터에 대한 원격 FabricPool 클라우드 계층으로 액세스할 수 있습니다.



.단계
. 사용 가능한 물리적 포트 및 가상 포트를 표시합니다.
+
네트워크 포트 쇼

+
** 가능하면 데이터 네트워크에 대해 최고 속도의 포트를 사용해야 합니다.
** 최상의 성능을 얻으려면 데이터 네트워크의 모든 구성 요소에 동일한 MTU 설정이 있어야 합니다.


. 서브넷 이름을 사용하여 LIF에 대한 IP 주소 및 네트워크 마스크 값을 할당하려는 경우, 서브넷이 존재하고 사용 가능한 충분한 주소가 있는지 확인합니다.
+
네트워크 서브넷 쇼

+
서브넷에는 동일한 계층 3 서브넷에 속하는 IP 주소 풀이 포함되어 있습니다. 서브넷은 network subnet create 명령을 사용하여 생성된다.

. 사용 가능한 IPspace 표시:
+
네트워크 IPspace 쇼

+
기본 IPspace 또는 사용자 지정 IPspace를 사용할 수 있습니다.

. IPv6 주소를 사용하려면 클러스터에서 IPv6이 활성화되어 있는지 확인합니다.
+
네트워크 옵션 IPv6 쇼

+
필요한 경우 'network options ipv6 modify' 명령을 사용하여 IPv6을 사용하도록 설정할 수 있습니다.


