---
permalink: s3-config/create-bucket-task.html 
sidebar: sidebar 
keywords: s3, bucket, system manager, 
summary: S3 오브젝트는 _ bucket _ 에 유지됩니다. 다른 디렉터리 내의 디렉터리 안에 파일로 중첩되지 않습니다. 
---
= ONTAP S3 버킷을 생성합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
S3 오브젝트는 _ bucket _ 에 유지됩니다. 다른 디렉터리 내의 디렉터리 안에 파일로 중첩되지 않습니다.

.시작하기 전에
S3 서버가 포함된 스토리지 VM이 이미 존재해야 합니다.

.이 작업에 대해
* ONTAP 9.14.1부터는 S3 FlexGroup 볼륨에 버킷이 생성되면 자동 크기 조정이 활성화되었습니다. 따라서 기존 및 새 FlexGroup 볼륨에서 버킷 생성 중에 과도한 용량 할당이 필요 없습니다. FlexGroup 볼륨의 크기는 다음 지침에 따라 최소 필요한 크기로 조정됩니다. 필요한 최소 크기는 FlexGroup 볼륨에 있는 모든 S3 버킷의 총 크기입니다.
+
** ONTAP 9.14.1부터 새 버킷 생성 시 S3 FlexGroup 볼륨이 생성되는 경우 필요한 최소 크기로 FlexGroup 볼륨이 생성됩니다.
** ONTAP 9.14.1 전에 S3 FlexGroup 볼륨을 생성한 경우, ONTAP 9.14.1 이후 생성되거나 삭제된 첫 번째 버킷이 FlexGroup 볼륨의 크기를 필요한 최소 크기로 조정합니다.
** ONTAP 9.14.1 전에 S3 FlexGroup 볼륨이 생성되었고 이미 필요한 최소 크기가 있는 경우, ONTAP 9.14.1 이후 버킷 생성 또는 삭제에 의해 S3 FlexGroup 볼륨의 크기가 유지됩니다.


* 스토리지 서비스 수준은 _value_, _performance_ 및 _extreme_default 수준으로 사전 정의된 QoS(Adaptive Quality of Service) 정책 그룹입니다. 기본 스토리지 서비스 수준 대신 맞춤형 QoS 정책 그룹을 정의하여 버킷에 적용할 수도 있습니다. 스토리지 서비스 정의에 대한 자세한 내용은 을 link:storage-service-definitions-reference.html["스토리지 서비스 정의"]참조하십시오. 성능 관리에 대한 자세한 내용은 을 link:../performance-admin/index.html["성능 관리"]참조하십시오. ONTAP 9.8부터는 스토리지 용량 할당 시 QoS가 기본적으로 사용하도록 설정됩니다. 프로비저닝 프로세스 도중 또는 나중에 QoS를 사용하지 않도록 설정하거나 사용자 지정 QoS 정책을 선택할 수 있습니다.


* 로컬 용량 계층화를 구성하는 경우, S3 서버가 있는 시스템 스토리지 VM이 아닌 데이터 스토리지 VM에 버킷 및 사용자를 생성합니다.
* 원격 클라이언트 액세스의 경우 S3 지원 스토리지 VM에서 버킷을 구성해야 합니다. S3이 활성화되지 않은 스토리지 VM에서 버킷을 생성하는 경우 로컬 계층화에만 사용할 수 있습니다.
* ONTAP 9.14.1부터 가능합니다 link:create-bucket-mcc-task.html["MetroCluster 구성의 경우 미러링된 또는 미러링되지 않은 애그리게이트에 버킷을 생성합니다"].
* CLI의 경우 버킷을 생성할 때 두 가지 프로비저닝 옵션이 있습니다.
+
** ONTAP Select에서 기본 애그리게이트와 FlexGroup 구성 요소 사용(기본값)
+
*** ONTAP는 애그리게이트를 자동으로 선택하여 첫 번째 버킷에 대한 FlexGroup 볼륨을 생성 및 구성합니다. 플랫폼에 사용할 수 있는 가장 높은 서비스 수준이 자동으로 선택되거나 스토리지 서비스 수준을 지정할 수 있습니다. 스토리지 VM에서 나중에 추가하는 모든 추가 버킷은 동일한 기본 FlexGroup 볼륨을 갖게 됩니다.
*** 또는 버킷이 계층화에 사용되는지 여부를 지정할 수 있습니다. 이 경우 ONTAP는 계층형 데이터에 대해 최적의 성능을 제공하는 경제적인 미디어를 선택하려고 합니다.


** 기본 애그리게이트 및 FlexGroup 구성요소 선택(고급 권한 명령 옵션 필요): 버킷과 FlexGroup 볼륨을 생성해야 하는 애그리게이트를 수동으로 선택한 다음, 각 애그리게이트에서 구성요소 수를 지정할 수 있습니다. 추가 버킷 추가 시:
+
*** 새 버킷에 대해 Aggregate 및 구성요소를 지정하는 경우 새 FlexGroup가 새 버킷에 대해 생성됩니다.
*** 새 버킷의 Aggregate 및 구성요소를 지정하지 않을 경우 새 버킷이 기존 FlexGroup에 추가됩니다. 을 참조하십시오 xref:../flexgroup/index.html[FlexGroup 볼륨 관리] 를 참조하십시오.
+
버킷을 생성할 때 Aggregate 및 구성요소를 지정하면 QoS 정책 그룹, 기본값 또는 사용자 지정이 적용되지 않습니다. 나중에 'vserver object-store-server bucket modify' 명령을 사용하여 이 작업을 수행할 수 있습니다.

+
ONTAP 명령 참조에서 https://docs .NetApp.com/us-en/ONTAP-cli/vserver-object-store-server-show.html 명령 링크에 대해 자세히[`vserver object-store-server bucket modify` 알아보십시오.

+
* 참고: * Cloud Volumes ONTAP에서 버킷을 제공하는 경우 CLI 절차를 사용해야 합니다. 기본 애그리게이트는 한 노드만 사용하는지 확인하기 위해 수동으로 선택하는 것이 좋습니다. 두 노드의 애그리게이트를 사용하면 지리적으로 서로 분리되어 있는 가용성 영역에 노드가 있기 때문에 지연 시간 문제가 발생하기 때문에 성능에 영향을 미칠 수 있습니다.









== ONTAP CLI로 S3 버킷을 생성합니다

. Aggregate 및 FlexGroup 구성 요소를 직접 선택하려면 권한 수준을 Advanced(고급)로 설정하십시오. 그렇지 않으면 admin 권한 수준이 Advanced(고급)로 설정됩니다
. 버킷 생성:
+
'vserver object-store-server bucket create-vserver_svm_name_-bucket_bucket_name_[-size integer[KB|MB|GB|TB|PB][-comment text] [Additional_options]'

+
스토리지 VM 이름은 데이터 스토리지 VM 또는 일 수 있습니다 `Cluster` 로컬 계층화를 구성하는 경우 (시스템 스토리지 VM 이름)

+
옵션을 지정하지 않을 경우 ONTAP는 800GB 버킷을 생성하고 서비스 레벨이 시스템에서 사용 가능한 최대 레벨로 설정합니다.

+
ONTAP에서 성능 또는 사용량을 기준으로 버킷을 생성하려면 다음 옵션 중 하나를 사용하십시오.

+
** 서비스 레벨
+
가치, 성능, 익스트림 등의 가치 중 하나로 스토리지 서비스 수준 옵션을 포함시키십시오.

** 계층화
+
사용된 용량 계층 TRUE 옵션을 포함합니다.



+
기본 FlexGroup 볼륨을 생성할 애그리게이트를 지정하려면 다음 옵션을 사용하십시오.

+
** '-aggr-list' 매개 변수는 FlexGroup 볼륨 구성요소에 사용할 애그리게이트 목록을 지정합니다.
+
목록의 각 항목은 지정된 애그리게이트에 구성요소를 생성합니다. Aggregate를 여러 번 지정하여 Aggregate에 여러 구성요소를 생성할 수 있습니다.

+
FlexGroup 볼륨 전체에서 일관된 성능을 위해서는 모든 애그리게이트에서 동일한 디스크 유형과 RAID 그룹 구성을 사용해야 합니다.

** '-aggr-list-multiplier' 매개 변수는 FlexGroup 볼륨을 생성할 때 '-aggr-list' 매개 변수로 나열된 애그리게이트를 반복하는 횟수를 지정합니다.
+
'-aggr-list-multiplier' 파라미터의 기본값은 4이다.



. 필요한 경우 QoS 정책 그룹을 추가합니다.
+
'vserver object-store-server bucket modify -bucket_bucket_name_-qos-policy-group_qos_policy_group_'

. 버킷 생성 확인:
+
'vserver object-store-server bucket show[-instance]'



.예
다음 예에서는 스토리지 VM용 버킷을 생성합니다 `vs1` 있습니다 `1TB` 집계 지정:

이 절차에서 설명하는 명령에 대한 자세한 내용은 를 link:https://docs.netapp.com/us-en/ontap-cli/["ONTAP 명령 참조입니다"^]참조하십시오.

[listing]
----
cluster-1::*> vserver object-store-server bucket create -vserver svm1.example.com -bucket testbucket -aggr-list aggr1 -size 1TB
----


== System Manager로 S3 버킷을 생성합니다

. S3 지원 스토리지 VM에 새 버킷을 추가합니다.
+
.. 스토리지 > 버킷 * 을 클릭한 다음 * 추가 * 를 클릭합니다.
.. 이름을 입력하고 스토리지 VM을 선택한 다음 크기를 입력합니다.
+
*** 이 지점에서 * Save * (저장 *)를 클릭하면 다음 기본 설정으로 버킷이 생성됩니다.
+
**** 그룹 정책이 이미 적용되어 있지 않으면 버킷에 대한 액세스 권한이 사용자에게 부여되지 않습니다.
+

NOTE: 오브젝트 저장소에 대한 무제한 액세스 권한이 있으므로 S3 루트 사용자를 사용하여 ONTAP 오브젝트 스토리지를 관리하고 권한을 공유해서는 안 됩니다. 대신 할당한 관리 권한이 있는 사용자 또는 그룹을 만듭니다.

**** 시스템에서 가장 높은 수준의 서비스 품질(성능) 수준입니다.


*** 이 기본값으로 버킷을 만들려면 * 저장 * 을 클릭합니다.








=== 추가 권한 및 제한 사항을 구성합니다

버킷을 구성할 때 * 추가 옵션 * 을 클릭하여 오브젝트 잠금, 사용자 권한 및 성능 수준에 대한 설정을 구성하거나 나중에 이 설정을 수정할 수 있습니다.

FabricPool 계층화에 S3 오브젝트 저장소를 사용하려는 경우 성능 서비스 수준이 아닌 * 계층화에 사용 * (계층 데이터에 최적의 성능을 제공하는 저비용 미디어 사용)을 선택하는 것이 좋습니다.

나중에 복구할 수 있도록 개체의 버전 관리를 활성화하려면 * 버전 관리 활성화 * 를 선택합니다. 버킷에서 오브젝트 잠금을 사용하도록 설정하는 경우 버전 관리가 기본적으로 활성화됩니다. 개체 버전 관리에 대한 자세한 내용은 를 참조하십시오 https://docs.aws.amazon.com/AmazonS3/latest/userguide/Versioning.html["Amazon용 S3 버킷에서 버전 관리 사용"].

9.14.1부터 S3 버킷에서 오브젝트 잠금이 지원됩니다. S3 오브젝트 잠금에는 표준 SnapLock 라이센스가 필요합니다. 이 라이센스는 에 link:../system-admin/manage-licenses-concept.html["ONTAP 1 을 참조하십시오"]포함되어 있습니다. ONTAP One 이전에는 SnapLock 라이센스가 보안 및 규정 준수 번들에 포함되어 있었습니다. 보안 및 규정 준수 번들은 더 이상 제공되지 않지만 여전히 유효합니다. 현재는 필요하지 않지만 기존 고객은 선택할 수 https://docs.netapp.com/us-en/ontap/system-admin/download-nlf-task.html["ONTAP One으로 업그레이드하십시오"] 있습니다. 버킷에서 물체 잠금을 사용하도록 설정하는 경우 다음을 수행해야 https://docs.netapp.com/us-en/ontap/system-admin/manage-license-task.html["SnapLock 라이센스가 설치되어 있는지 확인합니다"]합니다. SnapLock 라이센스가 설치되어 있지 않은 경우 https://docs.netapp.com/us-en/ontap/system-admin/install-license-task.html["설치합니다"] 개체 잠금을 활성화하려면 먼저 라이센스를 설치해야 합니다. SnapLock 라이센스가 설치되어 있음을 확인한 후 버킷의 객체가 삭제되거나 덮어쓰지 않도록 보호하려면 * 개체 잠금 활성화 * 를 선택합니다. 잠금은 모든 오브젝트 또는 특정 버전에서 활성화될 수 있으며 클러스터 노드에 대해 SnapLock 컴플라이언스 클록이 초기화된 경우에만 활성화됩니다. 다음 단계를 수행하십시오.

. 클러스터의 어떤 노드에서도 SnapLock 컴플라이언스 클록이 초기화되지 않으면 * SnapLock 규정 준수 클록 초기화 * 버튼이 나타납니다. Initialize SnapLock Compliance Clock * 을 클릭하여 클러스터 노드에서 SnapLock 컴플라이언스 클록을 초기화합니다.
. 오브젝트에 대해 _WORM(Write Once, Read Many)_ 권한을 허용하는 시간 기반 잠금을 활성화하려면 * Governance * mode를 선택하십시오. _Governance_mode에서도 특정 권한을 가진 관리자 사용자가 객체를 삭제할 수 있습니다.
. 객체에 대해 보다 엄격한 삭제 규칙을 지정하고 업데이트하려면 * 규정 준수 * 모드를 선택하십시오. 이 오브젝트 잠금 모드에서는 지정된 보존 기간이 완료된 후에만 오브젝트를 만료시킬 수 있습니다. 보존 기간을 지정하지 않으면 객체는 무기한으로 잠긴 상태로 유지됩니다.
. 특정 기간 동안 잠금을 적용하려면 잠금 보존 기간을 일 또는 년 단위로 지정합니다.
+

NOTE: 잠금은 버전 및 비버전 S3 버킷에 적용할 수 있습니다. NAS 객체에는 객체 잠금을 적용할 수 없습니다.



버킷에 대한 보호 및 권한 설정 및 성능 서비스 수준을 구성할 수 있습니다.


NOTE: 사용 권한을 구성하기 전에 사용자 및 그룹을 이미 만들어야 합니다.

자세한 내용은 을 link:../s3-snapmirror/create-remote-mirror-new-bucket-task.html["새 버킷을 위한 거울을 작성합니다"]참조하십시오.



=== 버킷에 대한 접근을 확인합니다

S3 클라이언트 애플리케이션(ONTAP S3 또는 외부 타사 애플리케이션)에서 다음을 입력하여 새로 생성된 버킷에 대한 액세스를 확인할 수 있습니다.

* S3 서버 CA 인증서입니다.
* 사용자의 액세스 키와 비밀 키입니다.
* S3 서버 FQDN 이름 및 버킷 이름입니다.

