---
permalink: s3-config/create-bucket-task.html 
sidebar: sidebar 
keywords: create, bucket 
summary: S3 오브젝트는 버킷에 보관되므로 다른 디렉토리 내의 파일 안으로 중첩되지 않습니다. 
---
= 버킷을 만듭니다
:icons: font
:imagesdir: ../media/


[role="lead"]
S3 오브젝트는 _bucket_- 에 보관되며 다른 디렉토리 내의 디렉토리 내에 파일로 중첩되지 않습니다.

S3 서버를 포함하는 SVM이 이미 존재해야 합니다.

버킷을 생성할 때 두 가지 프로비저닝 옵션이 있습니다.

* ONTAP Select에서 기본 애그리게이트와 FlexGroup 구성 요소 사용(기본값)
+
** ONTAP는 애그리게이트를 자동으로 선택하여 첫 번째 버킷에 대한 FlexGroup 볼륨을 생성 및 구성합니다. 플랫폼에 사용할 수 있는 가장 높은 서비스 수준이 자동으로 선택되거나 스토리지 서비스 수준을 지정할 수 있습니다. 나중에 SVM에 추가할 수 있는 추가 버킷은 기본 FlexGroup 볼륨이 동일합니다.
** 또는 버킷이 계층화에 사용되는지 여부를 지정할 수 있습니다. 이 경우 ONTAP는 계층형 데이터에 대해 최적의 성능을 제공하는 경제적인 미디어를 선택하려고 합니다.


* 기본 애그리게이트 및 FlexGroup 구성요소를 선택할 수 있습니다(고급 권한 명령 옵션 필요).
+
** 버킷과 포함된 FlexGroup 볼륨을 생성해야 하는 애그리게이트를 수동으로 선택한 다음, 각 애그리게이트의 구성요소 수를 지정할 수 있습니다. 추가 버킷 추가 시:
+
*** 새 버킷에 대해 Aggregate 및 구성요소를 지정하는 경우 새 FlexGroup가 새 버킷에 대해 생성됩니다.
*** 새 버킷의 Aggregate 및 구성요소를 지정하지 않을 경우 새 버킷이 기존 FlexGroup에 추가됩니다. 자세한 내용은 FlexGroup 설명서를 참조하십시오.


+
link:../flexgroup/index.html["FlexGroup 볼륨 관리"]



+
버킷을 생성할 때 Aggregate 및 구성요소를 지정하면 QoS 정책 그룹, 기본값 또는 사용자 지정이 적용되지 않습니다. 나중에 'vserver object-store-server bucket modify' 명령을 사용하여 이 작업을 수행할 수 있습니다.



스토리지 서비스 수준은 _value_, _performance_ 및 _extreme_default 수준으로 사전 정의된 QoS(Adaptive Quality of Service) 정책 그룹입니다. 기본 스토리지 서비스 수준 대신 맞춤형 QoS 정책 그룹을 정의하여 버킷에 적용할 수도 있습니다.

link:storage-service-definitions-reference.html["스토리지 서비스 정의"]

로컬 용량 계층화를 구성하는 경우, S3 서버가 있는 시스템 SVM이 아니라 데이터 SVM에서 버킷 및 사용자를 생성합니다.

link:../performance-admin/index.html["성능 관리"]

추가 구성 및 표시 옵션은 'vserver object-store-server bucket' man 페이지를 참조하십시오.

.단계
. Aggregate 및 FlexGroup 구성 요소를 직접 선택하려면 권한 수준을 Advanced(고급)로 설정하십시오. 그렇지 않으면 admin 권한 수준이 Advanced(고급)로 설정됩니다
. 버킷 생성:
+
'vserver object-store-server bucket create-vserver_svm_name_-bucket_bucket_name_[-size integer[KB|MB|GB|TB|PB][-comment text] [Additional_options]'

+
로컬 계층화를 구성하는 경우 SVM 이름은 데이터 SVM이나 '클러스터'(시스템 SVM 이름)일 수 있습니다.

+
옵션을 지정하지 않으면 ONTAP에서 5GB 버킷이 생성되고 서비스 수준은 시스템에서 사용 가능한 가장 높은 수준으로 설정됩니다.

+
ONTAP에서 성능 또는 사용량을 기준으로 버킷을 생성하려면 다음 옵션 중 하나를 사용하십시오.

+
** 서비스 레벨
+
가치, 성능, 익스트림 등의 가치 중 하나로 스토리지 서비스 수준 옵션을 포함시키십시오.

** 계층화
+
사용된 용량 계층 TRUE 옵션을 포함합니다.



+
기본 FlexGroup 볼륨을 생성할 애그리게이트를 지정하려면 다음 옵션을 사용하십시오.

+
** '-aggr-list' 매개 변수는 FlexGroup 볼륨 구성요소에 사용할 애그리게이트 목록을 지정합니다.
+
목록의 각 항목은 지정된 애그리게이트에 구성요소를 생성합니다. Aggregate를 여러 번 지정하여 Aggregate에 여러 구성요소를 생성할 수 있습니다.

+
FlexGroup 볼륨 전체에서 일관된 성능을 위해서는 모든 애그리게이트에서 동일한 디스크 유형과 RAID 그룹 구성을 사용해야 합니다.

** '-aggr-list-multiplier' 매개 변수는 FlexGroup 볼륨을 생성할 때 '-aggr-list' 매개 변수로 나열된 애그리게이트를 반복하는 횟수를 지정합니다.
+
'-aggr-list-multiplier' 파라미터의 기본값은 4이다.



. 필요한 경우 QoS 정책 그룹을 추가합니다.
+
'vserver object-store-server bucket modify -bucket_bucket_name_-qos-policy-group_qos_policy_group_'

. 버킷 생성 확인:
+
'vserver object-store-server bucket show[-instance]'



다음 예에서는 1TB 크기의 SVM VS1 용 버킷과 Aggregate를 지정합니다.

[listing]
----
cluster-1::*> vserver object-store-server bucket create -vserver svm1.example.com -bucket testbucket -aggr-list aggr1 -size 1TB
----