---
permalink: s3-config/create-s3-object-store-server-task.html 
sidebar: sidebar 
keywords: create, s3 object, store, server 
summary: ONTAP 오브젝트 저장소 서버는 ONTAP NAS 및 SAN 서버에서 제공하는 파일 또는 블록 스토리지가 아니라 데이터를 S3 오브젝트로 관리합니다. 
---
= S3 오브젝트 저장소 서버를 생성합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 오브젝트 저장소 서버는 ONTAP NAS 및 SAN 서버에서 제공하는 파일 또는 블록 스토리지가 아니라 데이터를 S3 오브젝트로 관리합니다.

자체 서명된 CA 인증서(이전 단계에서 만든 인증서) 또는 외부 CA 공급업체에서 서명한 인증서가 있어야 합니다. IP 트래픽이 클러스터 LIF만 통과하는 로컬 계층화 사용 사례에는 CA 인증서가 필요하지 않습니다.

오브젝트 저장소 서버가 생성되면 UID 0의 루트 사용자가 생성됩니다. 이 루트 사용자에 대해 액세스 키 또는 암호 키가 생성되지 않았습니다. ONTAP 관리자는 'object-store-server users Regenerate-keys' 명령을 실행하여 이 사용자의 액세스 키와 비밀 키를 설정해야 합니다.

[NOTE]
====
NetApp 모범 사례로서 이 루트 사용자를 사용하지 마십시오. 루트 사용자의 액세스 키 또는 암호 키를 사용하는 모든 클라이언트 애플리케이션은 오브젝트 저장소의 모든 버킷과 개체에 대한 모든 액세스 권한을 가집니다.

====
추가 구성 및 표시 옵션은 'vserver object-store-server' man 페이지를 참조하십시오.

.단계
. S3 서버 생성:
+
'vserver object-store-server create-vserver_svm_name_-object-store-server_s3_server_name_-certificate-name_ca_cert_name_-comment_text_[additional_options]'

+
S3 서버를 생성할 때 또는 나중에 언제든지 추가 옵션을 지정할 수 있습니다.

+
** 로컬 계층화를 구성하는 경우 SVM 이름은 데이터 SVM이나 '클러스터'(시스템 SVM 이름)일 수 있습니다.
** HTTPS는 기본적으로 포트 443에서 활성화됩니다. '-secure-listener-port' 옵션을 사용하여 포트 번호를 변경할 수 있습니다.
+
HTTPS가 활성화된 경우 SSL/TLS와의 올바른 통합을 위해 CA 인증서가 필요합니다.

** HTTP는 기본적으로 사용되지 않으며, 이 옵션을 설정하면 서버가 포트 80에서 수신 대기합니다. is-is-http-enabled(is-is-http 사용) 옵션을 사용하여 활성화하거나 '-listener-port(리스너-포트)' 옵션을 사용하여 포트 번호를 변경할 수 있습니다.
+
HTTP가 활성화되면 모든 요청과 응답이 일반 텍스트로 네트워크를 통해 전송됩니다.



. S3이 원하는 대로 구성되었는지 확인합니다.
+
'vserver object-store-server show'를 선택합니다



다음 명령은 모든 오브젝트 스토리지 서버의 구성 값을 확인합니다.

[listing]
----
cluster1::> vserver object-store-server show

            Vserver: vs1

                      Object Store Server Name: s3.example.com
                          Administrative State: up
                        Listener Port For HTTP: 80
                Secure Listener Port For HTTPS: 443
                                  HTTP Enabled: false
                                 HTTPS Enabled: true
             Certificate for HTTPS Connections: svm1_ca
                                       Comment: Server comment
----