---
permalink: s3-config/enable-ontap-s3-access-local-fabricpool-task.html 
sidebar: sidebar 
keywords: enable, ontap, s3 access, local, fabricpool, tiering 
summary: ONTAP S3를 로컬 FabricPool 용량 계층으로 사용하려면 생성한 버킷을 기반으로 오브젝트 저장소를 정의한 다음 오브젝트 저장소를 성능 계층 애그리게이트에 연결하여 FabricPool를 생성해야 합니다. 
---
= 로컬 FabricPool 계층화에 대해 ONTAP S3 액세스를 설정합니다
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP S3를 로컬 FabricPool 용량 계층으로 사용하려면 생성한 버킷을 기반으로 오브젝트 저장소를 정의한 다음 오브젝트 저장소를 성능 계층 애그리게이트에 연결하여 FabricPool를 생성해야 합니다.

ONTAP S3 서버 이름과 버킷 이름이 있어야 하며, 클러스터 LIF("-vserver Cluster" 매개 변수)를 사용하여 S3 서버를 생성해야 합니다.

오브젝트 저장소 구성에는 S3 서버, 버킷 이름 및 인증 요구사항을 비롯한 로컬 용량 계층에 대한 정보가 포함됩니다.

생성한 오브젝트 저장소 구성은 다른 오브젝트 저장소 또는 버킷과 다시 연관해서는 안 됩니다. 로컬 계층에 대해 여러 개의 버킷을 생성할 수 있지만, 단일 버킷에 여러 오브젝트 저장소를 생성할 수는 없습니다.

로컬 용량 계층에는 FabricPool 라이센스가 필요하지 않습니다.

.단계
. 로컬 용량 계층에 대한 객체 저장소 생성:
+
'Storage aggregate object-store config create-object-store-name store_name-IPSpace Cluster-provider-type ONTAP_S3-server_name-container-name bucket_name-access-key access-key-secret-password password password'

+
** container-name은 사용자가 만든 S3 버킷입니다.
** '-access-key' 파라미터는 ONTAP S3 서버에 대한 요청을 승인한다.
** secret-password 매개 변수(secret access key)는 ONTAP S3 서버에 대한 요청을 인증합니다.
** '-is-certificate-validation-enabled' 매개 변수를 'false'로 설정하여 ONTAP S3에 대한 인증서 확인을 비활성화할 수 있습니다.


+
[listing]
----
cluster1::> storage aggregate object-store config create
-object-store-name MyLocalObjStore -ipspace Cluster -provider-type ONTAP_S3 -server s3.example.com
-container-name bucket1 -access-key myS3key -secret-password myS3pass
----
. 오브젝트 저장소 구성 정보를 표시하고 확인합니다.
+
'Storage aggregate object-store config show'를 선택합니다

. 선택 사항: 볼륨의 비활성 데이터 양을 확인하려면 의 단계를 따릅니다 http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-mgng-stor-tier-fp/GUID-78C09B0C-9508-4CEC-96FE-7ED73F7F5120.html["비활성 데이터 보고를 사용하여 볼륨의 비활성 데이터 양을 결정합니다"].
+
볼륨의 비활성 데이터 양을 보면 FabricPool 로컬 계층화에 사용할 애그리게이트를 결정할 수 있습니다.

. 오브젝트 저장소를 Aggregate에 연결합니다.
+
'STORAGE 집계 객체 저장소 연결 집계 aggr_name-object-store-name store_name'입니다

+
"allow-flexgroup" * true *" 옵션을 사용하여 FlexGroup 볼륨 구성요소를 포함하는 애그리게이트를 연결할 수 있습니다.

+
[listing]
----
cluster1::> storage aggregate object-store attach
-aggregate aggr1 -object-store-name MyLocalObjStore
----
. 오브젝트 저장소 정보를 표시하고 첨부된 오브젝트 저장소를 사용할 수 있는지 확인합니다.
+
'스토리지 골재 오브젝트 저장소 쇼'

+
[listing]
----
cluster1::> storage aggregate object-store show

Aggregate    Object Store Name    Availability State
---------    -----------------    ------------------
aggr1        MyLocalObjStore      available
----

