---
permalink: s3-config/enable-client-access-from-s3-app-task.html 
sidebar: sidebar 
keywords: enable, client, access, s3 app 
summary: S3 클라이언트 애플리케이션에서 ONTAP S3 서버에 액세스하려면 ONTAP S3 관리자가 S3 사용자에게 구성 정보를 제공해야 합니다. 
---
= S3 애플리케이션에서 클라이언트 액세스 설정
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
S3 클라이언트 애플리케이션에서 ONTAP S3 서버에 액세스하려면 ONTAP S3 관리자가 S3 사용자에게 구성 정보를 제공해야 합니다.

.시작하기 전에
S3 클라이언트 앱은 다음 AWS 서명 버전을 사용하여 ONTAP S3 서버를 인증할 수 있어야 합니다.

* 서명 버전 4, ONTAP 9.8 이상
* 서명 버전 2, ONTAP 9.11.1 이상


다른 서명 버전은 ONTAP S3에서 지원되지 않습니다.

ONTAP S3 관리자는 버킷 정책 또는 오브젝트 스토리지 서버 정책에서 S3 사용자를 생성하고 개별 사용자 또는 그룹 구성원으로 액세스 권한을 부여해야 합니다.

S3 클라이언트 앱은 ONTAP S3 서버 이름을 확인할 수 있어야 합니다. 이 경우 ONTAP S3 관리자가 S3 서버 LIF의 S3 서버 이름(FQDN) 및 IP 주소를 제공해야 합니다.

.이 작업에 대해
ONTAP S3 버킷에 액세스하려면 S3 클라이언트 애플리케이션의 사용자가 ONTAP S3 관리자가 제공하는 정보를 입력합니다.

ONTAP 9.9.1부터 ONTAP S3 서버는 다음 AWS 클라이언트 기능을 지원합니다.

* 사용자 정의 개체 메타데이터
+
PUT(또는 POST)를 사용하여 개체를 만들 때 키 값 쌍 집합을 메타데이터로 할당할 수 있습니다. 개체에 대해 가져오기/헤드 작업을 수행하면 사용자 정의 메타데이터가 시스템 메타데이터와 함께 반환됩니다.

* 개체 태그 지정
+
객체 분류에 대한 태그로 별도의 키 값 쌍 세트를 할당할 수 있습니다. 메타데이터와 달리 태그는 오브젝트와 독립적으로 REST API를 사용하여 생성되고 읽혀지며, 오브젝트가 만들어지거나 그 이후에 언제든지 구현됩니다.

+
[NOTE]
====
클라이언트가 태그 정보를 가져오고 넣을 수 있도록 하려면 버킷 또는 그룹 정책을 사용하여 GetObjectTagging, PutObjectTagging, DeleteObjectTagging 등의 작업을 허용해야 합니다.

====


자세한 내용은 AWS S3 설명서를 참조하십시오.

.단계
. S3 서버 이름과 CA 인증서를 입력하여 ONTAP S3 서버로 S3 클라이언트 앱을 인증합니다.
. 다음 정보를 입력하여 S3 클라이언트 앱에서 사용자를 인증합니다.
+
** S3 서버 이름(FQDN) 및 버킷 이름입니다
** 사용자의 액세스 키 및 암호 키입니다



