---
permalink: s3-config/ontap-version-support-s3-concept.html 
sidebar: sidebar 
keywords: ontap, version, support, s3, object, storage, AWS S3, Azure S3, cloud volumes ontap, aws, azure 
summary: ONTAP는 ONTAP 9.8부터 사내 환경을 위한 S3 오브젝트 스토리지를 지원합니다. Cloud Volumes ONTAP는 ONTAP 9.9.1부터 클라우드 환경을 위한 S3 오브젝트 스토리지를 지원합니다. 
---
= S3 오브젝트 스토리지를 위한 ONTAP 버전 지원
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP는 ONTAP 9.8부터 사내 환경을 위한 S3 오브젝트 스토리지를 지원합니다. Cloud Volumes ONTAP는 ONTAP 9.9.1부터 클라우드 환경을 위한 S3 오브젝트 스토리지를 지원합니다.



== MetroCluster를 통해 S3 지원

ONTAP 9.14.1부터 MetroCluster IP 및 FC 구성의 미러링된 애그리게이트에서 SVM에 S3 오브젝트 스토리지 서버를 사용하도록 설정할 수 있습니다.

ONTAP 9.12.1부터 MetroCluster IP 구성의 미러링되지 않은 Aggregate에서 SVM에서 S3 오브젝트 스토리지 서버를 활성화할 수 있습니다. MetroCluster IP 구성에서 미러링되지 않은 애그리게이트의 제한에 대한 자세한 내용은 를 참조하십시오. link:https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/considerations_unmirrored_aggrs.html["미러링되지 않은 애그리게이트의 고려 사항"^]



== Cloud Volumes ONTAP로 S3 지원

ONTAP S3는 Cloud Volumes ONTAP에서 사내 환경과 동일하게 구성 및 작동합니다. 단 한 가지 예외가 있습니다.

* 기본 애그리게이트는 한 노드에서만 사용해야 함 에 대해 자세히 알아보십시오 link:create-svm-s3-task.html["CVO 환경에서 버킷 생성"].


|===
| 클라우드 공급자 | ONTAP 버전 


| Azure를 지원합니다 | ONTAP 9.9.1 이상 


| 설치하고 | ONTAP 9.11.0 이상 


| Google 클라우드 | ONTAP 9.12.1 이상 
|===


== S3 ONTAP 9.7의 공용 미리 보기

ONTAP 9.7에서는 S3 오브젝트 스토리지가 공용 미리 보기로 도입되었습니다. 이 버전은 프로덕션 환경을 위한 것이 아니며 ONTAP 9.8을 통해 더 이상 업데이트되지 않습니다. ONTAP 9.8 이상 릴리즈에서만 운영 환경에서 S3 오브젝트 스토리지를 지원합니다.

9.7 공용 미리 보기로 생성된 S3 버킷은 ONTAP 9.8 이상에서 사용할 수 있지만 향상된 기능을 활용할 수는 없습니다. 9.7 공용 미리 보기로 만든 버킷이 있는 경우 이러한 버킷의 내용을 9.8 버킷으로 마이그레이션하여 기능 지원, 보안 및 성능 향상을 지원해야 합니다.
