---
permalink: snaplock/autocommit-files-worm-task.html 
sidebar: sidebar 
keywords: snaplock, autocommit, commit, files, worm, automatically 
summary: SnapLock 자동 커밋 기능을 사용하면 파일을 WORM에 자동으로 커밋할 수 있습니다. 
---
= WORM에 파일을 자동 커밋합니다
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapLock 자동 커밋 기능을 사용하면 파일을 WORM에 자동으로 커밋할 수 있습니다.

.무엇을 &#8217;필요로 할거야
* 자동 커밋하려는 파일이 SnapLock 볼륨에 있어야 합니다.
* SnapLock 볼륨이 온라인 상태여야 합니다.
* SnapLock 볼륨은 읽기-쓰기 볼륨이어야 합니다.


[NOTE]
====
SnapLock 자동 커밋 기능은 볼륨에 있는 모든 파일을 검사하여 자동 커밋 요구 사항을 충족하는 경우 파일을 커밋합니다. 파일이 자동 커밋될 준비가 된 시점과 SnapLock 자동 커밋 스캐너에서 실제로 커밋된 시점 사이에 시간 간격이 있을 수 있습니다. 그러나 파일이 자동 커밋될 수 있는 즉시 파일 시스템에 의해 수정 및 삭제로부터 보호됩니다.

====
autocommit period _ 는 파일이 자동 커밋되기 전에 변경되지 않은 상태로 유지해야 하는 시간을 지정합니다. 자동 커밋 기간이 경과하기 전에 파일을 변경하면 파일의 자동 커밋 기간이 다시 시작됩니다.

다음 표에는 자동 커밋 기간에 대해 가능한 값이 나와 있습니다.

|===
| 값 | 단위 | 참고 


 a| 
없음
 a| 
-
 a| 
기본값입니다.



 a| 
5-5256000
 a| 
분
 a| 
-



 a| 
1-87600)을 참조하십시오
 a| 
시간
 a| 
-



 a| 
1-3650
 a| 
일
 a| 
-



 a| 
1-120으로 설정합니다
 a| 
개월
 a| 
-



 a| 
1-10
 a| 
년
 a| 
-

|===
[NOTE]
====
최소값은 5분이고 최대값은 10년입니다.

====
.단계
. SnapLock 볼륨의 파일을 WORM에 자동 커밋:
+
'* volume SnapLock modify -vserver_SVM_name_-volume_volume_name_-autos커밋 -period_autosit_period_ *'

+
전체 옵션 목록은 명령에 대한 man 페이지를 참조하십시오.

+
다음 명령은 파일이 5시간 동안 변경되지 않는 한 SVM VS1 볼륨 'vol1'에 있는 파일을 자동으로 커밋합니다.

+
[listing]
----
cluster1::>volume snaplock modify -vserver vs1 -volume vol1 -autocommit-period 5hours
----

