---
permalink: snaplock/commit-files-worm-state-manual-task.html 
sidebar: sidebar 
keywords: commit, file, worm, manually, nfs, cifs, read, only, automatically, program, appendable, nfs, cifs, chunk, vam 
summary: '파일을 수동으로 커밋하거나 자동으로 커밋하여 WORM(Write Once, Read Many)에 커밋할 수 있습니다. WORM 추가 가능 파일을 생성할 수도 있습니다.' 
---
= WORM에 파일을 커밋합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
파일을 수동으로 커밋하거나 자동으로 커밋하여 WORM(Write Once, Read Many)에 커밋할 수 있습니다. WORM 추가 가능 파일을 생성할 수도 있습니다.



== WORM에 파일을 수동으로 커밋합니다

파일을 읽기 전용으로 만들어 WORM에 파일을 수동으로 커밋합니다. NFS 또는 CIFS를 통해 적합한 명령 또는 프로그램을 사용하여 파일의 읽기-쓰기 속성을 읽기 전용으로 변경할 수 있습니다. 응용 프로그램이 파일에 대한 쓰기를 완료했는지 확인하여 파일이 너무 일찍 커밋되지 않았는지 또는 많은 볼륨 때문에 자동 커밋 스캐너에 대한 배율 조정 문제가 있는지 확인하려면 파일을 수동으로 커밋하도록 선택할 수 있습니다.

.필요한 것
* 커밋하려는 파일이 SnapLock 볼륨에 있어야 합니다.
* 파일에 쓸 수 있어야 합니다.


.이 작업에 대해
볼륨 ComplianceClock 시간은 명령이나 프로그램이 실행될 때 파일의 ctime 필드에 기록됩니다. ComplianceClock 시간은 파일의 보존 시간에 도달한 시점을 결정합니다.

.단계
. 적합한 명령 또는 프로그램을 사용하여 파일의 읽기-쓰기 속성을 읽기 전용으로 변경합니다.
+
UNIX 셸에서 다음 명령을 사용하여 "document.txt"라는 파일을 읽기 전용으로 만듭니다.

+
[listing]
----
chmod -w document.txt
----
+
Windows 셸에서 다음 명령을 사용하여 "document.txt"라는 파일을 읽기 전용으로 만듭니다.

+
[listing]
----
attrib +r document.txt
----




== 파일을 WORM에 자동으로 커밋합니다

SnapLock 자동 커밋 기능을 사용하면 파일을 WORM에 자동으로 커밋할 수 있습니다. 자동 커밋 기능은 자동 커밋 기간 동안 파일이 변경되지 않은 경우 SnapLock 볼륨에서 파일을 WORM 상태로 커밋합니다. 자동 커밋 기능은 기본적으로 비활성화되어 있습니다.

.필요한 것
* 자동 커밋하려는 파일이 SnapLock 볼륨에 있어야 합니다.
* SnapLock 볼륨이 온라인 상태여야 합니다.
* SnapLock 볼륨은 읽기-쓰기 볼륨이어야 합니다.


[NOTE]
====
SnapLock 자동 커밋 기능은 볼륨에 있는 모든 파일을 검사하여 자동 커밋 요구 사항을 충족하는 경우 파일을 커밋합니다. 파일이 자동 커밋될 준비가 된 시점과 SnapLock 자동 커밋 스캐너에서 실제로 커밋된 시점 사이에 시간 간격이 있을 수 있습니다. 그러나 파일이 자동 커밋될 수 있는 즉시 파일 시스템에 의해 수정 및 삭제로부터 보호됩니다.

====
.이 작업에 대해
autocommit period _ 는 파일이 자동 커밋되기 전에 변경되지 않은 상태로 유지해야 하는 시간을 지정합니다. 자동 커밋 기간이 경과하기 전에 파일을 변경하면 파일의 자동 커밋 기간이 다시 시작됩니다.

다음 표에는 자동 커밋 기간에 대해 가능한 값이 나와 있습니다.

|===
| 값 | 단위 | 참고 


 a| 
없음
 a| 
-
 a| 
기본값입니다.



 a| 
5-5256000
 a| 
분
 a| 
-



 a| 
1-87600)을 참조하십시오
 a| 
시간
 a| 
-



 a| 
1-3650
 a| 
일
 a| 
-



 a| 
1-120으로 설정합니다
 a| 
개월
 a| 
-



 a| 
1-10
 a| 
년
 a| 
-

|===
[NOTE]
====
최소값은 5분이고 최대값은 10년입니다.

====
.단계
. SnapLock 볼륨의 파일을 WORM에 자동 커밋:
+
'* volume SnapLock modify -vserver_SVM_name_-volume_volume_name_-autos커밋 -period_autosit_period_ *'

+
전체 옵션 목록은 명령에 대한 man 페이지를 참조하십시오.

+
다음 명령은 파일이 5시간 동안 변경되지 않는 한 SVM VS1 볼륨 'vol1'에 있는 파일을 자동으로 커밋합니다.

+
[listing]
----
cluster1::>volume snaplock modify -vserver vs1 -volume vol1 -autocommit-period 5hours
----




== WORM 추가 가능 파일을 생성합니다

WORM 추가 가능 파일은 로그 항목과 같이 점진적으로 기록된 데이터를 유지합니다. 적합한 명령 또는 프로그램을 사용하여 WORM 추가 가능 파일을 생성하거나 SnapLock_VOLUME append mode_feature를 사용하여 기본적으로 WORM 추가 가능 파일을 생성할 수 있습니다.



== 명령 또는 프로그램을 사용하여 WORM 추가 가능 파일을 생성합니다

NFS 또는 CIFS를 통해 적합한 명령 또는 프로그램을 사용하여 WORM 추가 가능 파일을 생성할 수 있습니다. WORM 추가 가능 파일은 로그 항목과 같이 점진적으로 기록된 데이터를 유지합니다. 데이터는 256KB 청크로 파일에 추가됩니다. 각 청크가 쓰일 때 이전 청크는 WORM으로 보호됩니다. 보존 기간이 경과할 때까지 파일을 삭제할 수 없습니다.

.필요한 것
WORM 추가 가능 파일이 SnapLock 볼륨에 있어야 합니다.

.이 작업에 대해
데이터는 활성 256KB 청크에 순차적으로 쓸 필요가 없습니다. 파일의 n×256KB+1 바이트에 데이터를 쓸 때 이전 256KB 세그먼트는 WORM으로 보호됩니다.

현재 활성 256KB 청크를 초과하는 순서가 없는 쓰기는 활성 256KB 청크가 최신 오프셋으로 재설정되고 이전 오프셋에 대한 쓰기가 실패하고 'ROFS(읽기 전용 파일 시스템)' 오류가 발생합니다. 쓰기 오프셋은 클라이언트 애플리케이션에 따라 다릅니다. WORM 추가 파일 쓰기 의미를 준수하지 않는 클라이언트는 쓰기 콘텐츠가 잘못 종료될 수 있습니다. 따라서 클라이언트가 순서가 지정되지 않은 쓰기에 대한 오프셋 제한을 따르는지 확인하거나 파일 시스템을 동기식 모드로 마운트하여 동기식 쓰기를 보장하는 것이 좋습니다.

.단계
. 적합한 명령 또는 프로그램을 사용하여 원하는 보존 시간으로 길이가 0인 파일을 생성합니다.
+
UNIX 셸에서 다음 명령을 사용하여 2020년 11월 21일 오전 6:00의 보존 시간을 설정합니다 길이가 0인 파일에서 document.txt:

+
[listing]
----
touch -a -t 202011210600 document.txt
----
. 적합한 명령 또는 프로그램을 사용하여 파일의 읽기-쓰기 속성을 읽기 전용으로 변경합니다.
+
UNIX 셸에서 다음 명령을 사용하여 "document.txt"라는 파일을 읽기 전용으로 만듭니다.

+
[listing]
----
chmod 444 document.txt
----
. 적합한 명령 또는 프로그램을 사용하여 파일의 읽기-쓰기 속성을 다시 쓰기 가능으로 변경합니다.
+
[NOTE]
====
파일에 데이터가 없기 때문에 이 단계는 규정 준수 위험으로 간주되지 않습니다.

====
+
UNIX 셸에서 다음 명령을 사용하여 "document.txt"라는 파일을 쓰기 가능하게 만듭니다.

+
[listing]
----
chmod 777 document.txt
----
. 적절한 명령 또는 프로그램을 사용하여 파일에 데이터 쓰기를 시작합니다.
+
UNIX 셸에서 다음 명령을 사용하여 데이터를 document.txt에 씁니다.

+
[listing]
----
echo test data >> document.txt
----
+
[NOTE]
====
파일에 데이터를 더 이상 추가할 필요가 없는 경우 파일 권한을 다시 읽기 전용으로 변경합니다.

====




== 볼륨 추가 모드를 사용하여 WORM 추가 가능 파일을 생성합니다

ONTAP 9.3부터는 SnapLock_VOLUME APPEND MODE_(VAM) 기능을 사용하여 기본적으로 WORM 추가 가능 파일을 생성할 수 있습니다. WORM 추가 가능 파일은 로그 항목과 같이 점진적으로 기록된 데이터를 유지합니다. 데이터는 256KB 청크로 파일에 추가됩니다. 각 청크가 쓰일 때 이전 청크는 WORM으로 보호됩니다. 보존 기간이 경과할 때까지 파일을 삭제할 수 없습니다.

.필요한 것
* WORM 추가 가능 파일이 SnapLock 볼륨에 있어야 합니다.
* SnapLock 볼륨은 마운트 해제되고 스냅샷 복사본과 사용자 생성 파일이 비어 있어야 합니다.


.이 작업에 대해
데이터는 활성 256KB 청크에 순차적으로 쓸 필요가 없습니다. 파일의 n×256KB+1 바이트에 데이터를 쓸 때 이전 256KB 세그먼트는 WORM으로 보호됩니다.

볼륨에 대해 자동 커밋 기간을 지정하면 자동 커밋 기간보다 긴 기간 동안 수정되지 않은 WORM 추가 가능 파일이 WORM에 커밋됩니다.

[NOTE]
====
VAM은 SnapLock 감사 로그 볼륨에서 지원되지 않습니다.

====
.단계
. VAM 활성화:
+
'* volume SnapLock modify -vserver_SVM_name_-volume_volume_name_-is-volume-append-mode-enabled true|false *

+
전체 옵션 목록은 명령에 대한 man 페이지를 참조하십시오.

+
다음 명령을 실행하면 SVM의 볼륨 'vol1'에서 VAM이 활성화됩니다.

+
[listing]
----
cluster1::>volume snaplock modify -vserver vs1 -volume vol1 -is-volume-append-mode-enabled true
----
. 적합한 명령 또는 프로그램을 사용하여 쓰기 권한이 있는 파일을 만듭니다.
+
파일은 기본적으로 WORM-appendable입니다.


