---
permalink: snaplock/create-snaplock-volume-task.html 
sidebar: sidebar 
keywords: snaplock, volume, shanpshot, copy, create, complianceclock, file, worm, compliance, enterprise 
summary: 'WORM 상태로 커밋하려는 파일 또는 스냅샷 복사본에 대한 SnapLock 볼륨을 생성해야 합니다. ONTAP 9.10.1.1부터 애그리게이트 유형에 관계없이 생성한 모든 볼륨은 기본적으로 비 SnapLock 볼륨으로 생성됩니다. "-snaplock-type" 옵션을 사용하여 준수 또는 엔터프라이즈 를 SnapLock 유형으로 지정하여 SnapLock 볼륨을 명시적으로 생성해야 합니다. 기본적으로 SnapLock 유형은 비 SnapLock으로 설정됩니다.' 
---
= SnapLock 볼륨을 생성하고 마운트합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
WORM 상태로 커밋하려는 파일 또는 스냅샷 복사본에 대한 SnapLock 볼륨을 생성해야 합니다. ONTAP 9.10.1.1부터 애그리게이트 유형에 관계없이 생성한 모든 볼륨은 기본적으로 비 SnapLock 볼륨으로 생성됩니다. '-snaplock-type' 옵션을 사용하여 준수 또는 엔터프라이즈 를 SnapLock 유형으로 지정하여 SnapLock 볼륨을 명시적으로 생성해야 합니다. 기본적으로 SnapLock 유형은 비 SnapLock으로 설정됩니다.

.시작하기 전에
* SnapLock 애그리게이트는 온라인 상태여야 합니다.
* 당신은 해야 한다 https://docs.netapp.com/us-en/ontap/system-admin/manage-license-task.html["SnapLock 라이센스가 설치되어 있는지 확인합니다"]. 노드에 SnapLock 라이센스가 설치되어 있지 않으면 을 수행해야 합니다 https://docs.netapp.com/us-en/ontap/system-admin/install-license-task.html["설치합니다"] 있습니다. 이 라이센스는 에 포함되어 있습니다 https://docs.netapp.com/us-en/ontap/system-admin/manage-licenses-concept.html["ONTAP 1 을 참조하십시오"]. ONTAP One 이전에는 SnapLock 라이센스가 보안 및 규정 준수 번들에 포함되어 있었습니다. 보안 및 규정 준수 번들은 더 이상 제공되지 않지만 여전히 유효합니다. 현재는 필요하지 않지만 기존 고객은 선택할 수 있습니다 https://docs.netapp.com/us-en/ontap/system-admin/download-nlf-task.html["ONTAP One으로 업그레이드하십시오"].
* link:https://docs.netapp.com/us-en/ontap/snaplock/initialize-complianceclock-task.html["노드의 규정 준수 클록을 초기화해야 합니다"].


.이 작업에 대해
적절한 SnapLock 권한을 사용하여 언제든지 엔터프라이즈 볼륨을 삭제하거나 이름을 바꿀 수 있습니다. 보존 기간이 경과하기 전에는 Compliance 볼륨을 폐기할 수 없습니다. Compliance 볼륨의 이름은 변경할 수 없습니다.

SnapLock 볼륨의 클론을 생성할 수는 있지만 SnapLock 볼륨의 파일은 복제할 수 없습니다. 클론 볼륨은 상위 볼륨과 동일한 SnapLock 유형이 됩니다.

[NOTE]
====
LUN은 SnapLock 볼륨에서 지원되지 않습니다. LUN은 비 SnapLock 볼륨에서 생성된 스냅샷 복사본이 SnapLock 볼트 관계의 일부로 보호를 위해 SnapLock 볼륨으로 전송되는 경우에만 SnapLock 볼륨에서 지원됩니다. LUN은 읽기/쓰기 SnapLock 볼륨에서 지원되지 않습니다. 그러나 SnapMirror 소스 볼륨과 LUN이 포함된 타겟 볼륨 모두에서 무단 스냅샷 복사본이 지원됩니다.

====
ONTAP 시스템 관리자 또는 ONTAP CLI를 사용하여 이 작업을 수행합니다.

[role="tabbed-block"]
====
.시스템 관리자
--
ONTAP 9.12.1부터 시스템 관리자를 사용하여 SnapLock 볼륨을 생성할 수 있습니다.

.단계
. Storage > Volumes * 로 이동한 다음 * Add * 를 클릭합니다.
. 볼륨 추가 * 창에서 * 추가 옵션 * 을 클릭합니다.
. 볼륨의 이름과 크기를 포함하여 새 볼륨 정보를 입력합니다.
. SnapLock 사용 * 을 선택하고 SnapLock 유형(준수 또는 엔터프라이즈)을 선택합니다.
. 자동 커밋 파일 * 섹션에서 * 수정 * 을 선택하고 파일이 자동으로 커밋되기 전에 변경되지 않은 상태로 유지되는 시간을 입력합니다. 최소값은 5분이고 최대값은 10년입니다.
. Data Retention * 섹션에서 최소 및 최대 보존 기간을 선택합니다.
. 기본 보존 기간을 선택합니다.
. 저장 * 을 클릭합니다.
. 볼륨 * 페이지에서 새 볼륨을 선택하여 SnapLock 설정을 확인합니다.


--
.CLI를 참조하십시오
--
. SnapLock 볼륨 생성:
+
[source, cli]
----
volume create -vserver <SVM_name> -volume <volume_name> -aggregate <aggregate_name> -snaplock-type <compliance|enterprise>
----
+
전체 옵션 목록은 명령에 대한 man 페이지를 참조하십시오. SnapLock 볼륨에는 '-nvfail', '-atime-update', '-is-AutoBalance-eligible', '-space-mgmt-try-first', ' vmalign' 옵션이 없습니다.

+
다음 명령을 실행하면 vs1에 vol1이라는 SnapLock "Compliance" 볼륨이 생성됩니다.

+
[listing]
----
cluster1::> volume create -vserver vs1 -volume vol1 -aggregate aggr1 -snaplock-type compliance
----


--
====


== SnapLock 볼륨을 마운트합니다

NAS 클라이언트 액세스를 위해 SVM 네임스페이스의 접합 경로에 SnapLock 볼륨을 마운트할 수 있습니다.

.필요한 것
SnapLock 볼륨이 온라인 상태여야 합니다.

.이 작업에 대해
* SnapLock 볼륨은 SVM의 루트 아래에서만 마운트할 수 있습니다.
* SnapLock 볼륨 아래에 일반 볼륨을 마운트할 수 없습니다.


.단계
. SnapLock 볼륨 마운트:
+
'* 볼륨 마운트 - vserver_SVM_name_-volume_volume_name_-junction-path_path_*'

+
전체 옵션 목록은 명령에 대한 man 페이지를 참조하십시오.

+
다음 명령을 실행하면 이름이 vol1인 SnapLock 볼륨이 VS1 네임스페이스에서 junction path/sales에 마운트됩니다.

+
[listing]
----
cluster1::> volume mount -vserver vs1 -volume vol1 -junction-path /sales
----

