---
permalink: snaplock/create-snaplock-volume-task.html 
sidebar: sidebar 
keywords: snaplock, volume, shanpshot, copy, create, complianceclock, file, worm, compliance, enterprise 
summary: WORM 상태로 커밋하려는 파일 또는 스냅샷 복사본에 대한 SnapLock 볼륨을 생성해야 합니다. ONTAP 9.10.1.1부터 애그리게이트 유형에 관계없이 생성한 모든 볼륨은 기본적으로 비 SnapLock 볼륨으로 생성됩니다. \'-snaplock-type\' 옵션을 사용하여 준수 또는 엔터프라이즈 를 SnapLock 유형으로 지정하여 SnapLock 볼륨을 명시적으로 생성해야 합니다. 기본적으로 SnapLock 유형은 비 SnapLock으로 설정됩니다. 
---
= SnapLock 볼륨을 생성합니다
:icons: font
:imagesdir: ../media/


[role="lead"]
WORM 상태로 커밋하려는 파일 또는 스냅샷 복사본에 대한 SnapLock 볼륨을 생성해야 합니다. ONTAP 9.10.1.1부터 애그리게이트 유형에 관계없이 생성한 모든 볼륨은 기본적으로 비 SnapLock 볼륨으로 생성됩니다. '-snaplock-type' 옵션을 사용하여 준수 또는 엔터프라이즈 를 SnapLock 유형으로 지정하여 SnapLock 볼륨을 명시적으로 생성해야 합니다. 기본적으로 SnapLock 유형은 비 SnapLock으로 설정됩니다.

.무엇을 &#8217;필요로 할거야
* SnapLock 애그리게이트는 온라인 상태여야 합니다.
* SnapLock 라이센스가 노드에 설치되어 있어야 합니다.
* 노드의 ComplianceClock을 초기화해야 합니다.


적절한 SnapLock 권한을 사용하여 언제든지 엔터프라이즈 볼륨을 삭제하거나 이름을 바꿀 수 있습니다. 보존 기간이 경과하기 전에는 Compliance 볼륨을 폐기할 수 없습니다. Compliance 볼륨의 이름은 변경할 수 없습니다.

SnapLock 볼륨의 클론을 생성할 수는 있지만 SnapLock 볼륨의 파일은 복제할 수 없습니다. 클론 볼륨은 상위 볼륨과 동일한 SnapLock 유형이 됩니다.

[NOTE]
====
LUN은 SnapLock 볼륨에서 지원되지 않습니다. 기존 기술을 사용하여 SnapLock 볼륨으로 LUN을 이동할 수는 있지만 이 작업은 지원되지 않으며 SnapLock 볼륨에 LUN을 포함하는 다른 작업은 지원되지 않습니다.

====
.단계
. SnapLock 볼륨 생성:
+
'* 볼륨 생성 - vserver_SVM_name_-volume_volume_name_-aggregate_aggregate_name_*-snaplock-type compliance|enterprise'

+
전체 옵션 목록은 명령에 대한 man 페이지를 참조하십시오. SnapLock 볼륨에는 '-nvfail', '-atime-update', '-is-AutoBalance-eligible', '-space-mgmt-try-first', ' vmalign' 옵션이 없습니다.

+
다음 명령을 실행하면 vs1에 vol1이라는 SnapLock "Compliance" 볼륨이 생성됩니다.

+
[listing]
----
cluster1::> volume create -vserver vs1 -volume vol1 -aggregate aggr1 -snaplock-type compliance
----

