---
permalink: snaplock/create-audit-log-task.html 
sidebar: sidebar 
keywords: create, audit, log, snaplock, protected, administrator, accounts 
summary: 권한 있는 삭제 또는 SnapLock 볼륨 이동을 수행하기 전에 SnapLock으로 보호되는 감사 로그를 생성해야 합니다. 감사 로그는 SnapLock 관리자 계정의 생성 및 삭제, 로그 볼륨 수정, 권한 있는 삭제 활성화 여부, 권한 있는 삭제 작업 및 SnapLock 볼륨 이동 작업을 기록합니다. 
---
= 감사 로그를 생성합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
권한 있는 삭제 또는 SnapLock 볼륨 이동을 수행하기 전에 SnapLock으로 보호되는 감사 로그를 생성해야 합니다. 감사 로그는 SnapLock 관리자 계정의 생성 및 삭제, 로그 볼륨 수정, 권한 있는 삭제 활성화 여부, 권한 있는 삭제 작업 및 SnapLock 볼륨 이동 작업을 기록합니다.

.필요한 것
SnapLock 애그리게이트를 생성하려면 클러스터 관리자여야 합니다.

.이 작업에 대해
로그 파일 보존 기간이 경과할 때까지 감사 로그를 삭제할 수 없습니다. 보존 기간이 경과한 후에도 감사 로그를 수정할 수 없습니다. 이는 SnapLock 규정 준수 모드와 엔터프라이즈 모드 모두에서 마찬가지입니다.

[NOTE]
====
ONTAP 9.4 이하 버전에서는 감사 로깅을 위해 SnapLock 엔터프라이즈 볼륨을 사용할 수 없습니다. SnapLock 준수 볼륨을 사용해야 합니다. ONTAP 9.5 이상에서는 감사 로깅을 위해 SnapLock 엔터프라이즈 볼륨 또는 SnapLock 규정 준수 볼륨을 사용할 수 있습니다. 모든 경우에 감사 로그 볼륨은 교차점 경로 '/snaplock_audit_log'에 마운트되어야 합니다. 다른 볼륨은 이 접합 경로를 사용할 수 없습니다.

====
SnapLock Audit 로그는 감사 로그 볼륨의 루트 아래의 '/sSnapLock_log' 디렉토리에서 privdel_log'(권한 삭제 작업) 및 'system_log'(기타 모든 것)라는 하위 디렉토리에 있습니다. 감사 로그 파일 이름에는 첫 번째 기록 작업의 타임스탬프가 포함되어 있어 작업이 실행된 대략적인 시간만큼 레코드를 쉽게 검색할 수 있습니다.

* 'SnapLock log file show' 명령을 사용하여 감사 로그 볼륨에서 로그 파일을 볼 수 있습니다.
* 'SnapLock log file archive' 명령을 사용하여 현재 로그 파일을 보관하고 새 로그 파일을 만들 수 있습니다. 이 명령은 별도의 파일에 감사 로그 정보를 기록해야 하는 경우에 유용합니다.


자세한 내용은 명령에 대한 man 페이지를 참조하십시오.

[NOTE]
====
데이터 보호 볼륨은 SnapLock 감사 로그 볼륨으로 사용할 수 없습니다.

====
.단계
. SnapLock Aggregate를 생성합니다.
+
xref:create-snaplock-aggregate-task.adoc[SnapLock Aggregate를 생성합니다]

. 감사 로깅을 위해 구성하려는 SVM에서 SnapLock 볼륨을 생성합니다.
+
xref:create-snaplock-volume-task.adoc[SnapLock 볼륨을 생성합니다]

. 감사 로깅을 위해 SVM 구성:
+
`*snaplock log create -vserver _SVM_name_ -volume _snaplock_volume_name_ -max-log-size _size_ -retention-period _default_retention_period_*`

+
[NOTE]
====
감사 로그 파일의 최소 기본 보존 기간은 6개월입니다. 영향을 받는 파일의 보존 기간이 감사 로그의 보존 기간보다 긴 경우 로그의 보존 기간이 파일의 보존 기간을 상속합니다. 따라서 권한이 있는 삭제를 사용하여 삭제된 파일의 보존 기간이 10개월이고 감사 로그의 보존 기간이 8개월인 경우 로그 보존 기간은 10개월로 연장됩니다. 보존 시간 및 기본 보존 기간에 대한 자세한 내용은 을 참조하십시오 link:https://docs.netapp.com/us-en/ontap/snaplock/set-retention-period-task.html["보존 시간을 설정합니다"].

====
+
다음 명령어는 SnapLock volume logVol을 이용하여 Audit logging을 위한 'VM1'을 설정한다. 감사 로그의 최대 크기는 20GB이며 8개월 동안 유지됩니다.

+
[listing]
----
SVM1::> snaplock log create -vserver SVM1 -volume logVol -max-log-size 20GB -retention-period 8months
----
. 감사 로깅을 위해 구성한 SVM에서 SnapLock 볼륨을 연결 경로 '/sSnapLock_audit_log'에 마운트합니다.
+
xref:mount-snaplock-volume-task.adoc[SnapLock 볼륨을 마운트합니다]


