---
permalink: snaplock/create-worm-appendable-file-task.html 
sidebar: sidebar 
keywords: command, program, create, worm, appendable, file, nfs, cifs, chunk 
summary: NFS 또는 CIFS를 통해 적합한 명령 또는 프로그램을 사용하여 WORM 추가 가능 파일을 생성할 수 있습니다. WORM 추가 가능 파일은 로그 항목과 같이 점진적으로 기록된 데이터를 유지합니다. 데이터는 256KB 청크로 파일에 추가됩니다. 각 청크가 쓰일 때 이전 청크는 WORM으로 보호됩니다. 보존 기간이 경과할 때까지 파일을 삭제할 수 없습니다. 
---
= 명령 또는 프로그램을 사용하여 WORM 추가 가능 파일을 생성합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NFS 또는 CIFS를 통해 적합한 명령 또는 프로그램을 사용하여 WORM 추가 가능 파일을 생성할 수 있습니다. WORM 추가 가능 파일은 로그 항목과 같이 점진적으로 기록된 데이터를 유지합니다. 데이터는 256KB 청크로 파일에 추가됩니다. 각 청크가 쓰일 때 이전 청크는 WORM으로 보호됩니다. 보존 기간이 경과할 때까지 파일을 삭제할 수 없습니다.

.필요한 것
WORM 추가 가능 파일이 SnapLock 볼륨에 있어야 합니다.

.이 작업에 대해
데이터는 활성 256KB 청크에 순차적으로 쓸 필요가 없습니다. 파일의 n×256KB+1 바이트에 데이터를 쓸 때 이전 256KB 세그먼트는 WORM으로 보호됩니다.

.단계
. 적합한 명령 또는 프로그램을 사용하여 원하는 보존 시간으로 길이가 0인 파일을 생성합니다.
+
UNIX 셸에서 다음 명령을 사용하여 2020년 11월 21일 오전 6:00의 보존 시간을 설정합니다 길이가 0인 파일에서 document.txt:

+
[listing]
----
touch -a -t 202011210600 document.txt
----
. 적합한 명령 또는 프로그램을 사용하여 파일의 읽기-쓰기 속성을 읽기 전용으로 변경합니다.
+
UNIX 셸에서 다음 명령을 사용하여 "document.txt"라는 파일을 읽기 전용으로 만듭니다.

+
[listing]
----
chmod 444 document.txt
----
. 적합한 명령 또는 프로그램을 사용하여 파일의 읽기-쓰기 속성을 다시 쓰기 가능으로 변경합니다.
+
[NOTE]
====
파일에 데이터가 없기 때문에 이 단계는 규정 준수 위험으로 간주되지 않습니다.

====
+
UNIX 셸에서 다음 명령을 사용하여 "document.txt"라는 파일을 쓰기 가능하게 만듭니다.

+
[listing]
----
chmod 777 document.txt
----
. 적절한 명령 또는 프로그램을 사용하여 파일에 데이터 쓰기를 시작합니다.
+
UNIX 셸에서 다음 명령을 사용하여 데이터를 document.txt에 씁니다.

+
[listing]
----
echo test data >> document.txt
----
+
[NOTE]
====
파일에 데이터를 더 이상 추가할 필요가 없는 경우 파일 권한을 다시 읽기 전용으로 변경합니다.

====

