---
permalink: snaplock/create-locked-snapshot-task.html 
sidebar: sidebar 
keywords: snaplock, snapshot copy, lock, tamperproof, enable, retention, policy 
summary: ONTAP 9.12.1부터 스냅샷 복사본 보존 기간을 적용하기 위한 스냅샷 복사본 정책을 생성하고 이 정책을 볼륨에 적용하여 지정된 기간 동안 스냅샷 복사본을 잠글 수 있습니다. 보존 기간을 수동으로 설정하여 스냅샷 복사본을 잠글 수도 있습니다. 
---
= 잠긴 스냅샷 복사본을 생성합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9.12.1부터 스냅샷 복사본 보존 기간을 적용하기 위한 스냅샷 복사본 정책을 생성하고 이 정책을 볼륨에 적용하여 지정된 기간 동안 스냅샷 복사본을 잠글 수 있습니다. 보존 기간을 수동으로 설정하여 스냅샷 복사본을 잠글 수도 있습니다.



== 스냅샷 복사본 잠금 정책을 생성합니다

. 스냅샷 복사본 정책을 생성하려면 다음 명령을 입력합니다.
+
`volume snapshot policy create -policy policy_name -enabled true -schedule1 _schedule1_name_ -count1 _maximum_Snapshot_copies -retention-period1 _retention_period_`

+
다음 명령을 실행하면 스냅샷 복사본 잠금 정책이 생성됩니다.

+
[listing]
----
cluster1> volume snapshot policy create -policy policy_name -enabled true -schedule1 5min -count1 5 -retention-period1 "1 months"
----




== 볼륨에 잠금 정책을 적용합니다

. 기존 볼륨에 스냅샷 복사본 잠금 정책을 적용하려면 다음 명령을 입력합니다.
+
`volume modify -volume volume_name -vserver vserver_name -snapshot-policy policy_name`





== 수동 스냅샷 복사본 생성 중에 보존 기간을 적용합니다

. 스냅샷 복사본을 수동으로 생성하고 잠금 보존 기간을 적용하려면 다음 명령을 입력합니다.
+
`volume snapshot create -volume _volume_name_ -snapshot _snapshot_copy_name_ -expiry-time _expiration_date_time_`

+
다음 명령을 실행하면 새 스냅샷 복사본이 생성되고 보존 기간이 설정됩니다.

+
[listing]
----
cluster1> volume snapshot create -vserver vs1 -volume vol1 -snapshot snap1 -snaplock-expiry-time "11/10/2022 09:00:00"
----




== 기존 스냅샷 복사본에 보존 기간을 적용합니다

. 기존 스냅샷 복사본에 보존 기간을 수동으로 적용하려면 다음 명령을 입력합니다.
+
`volume snapshot modify-snaplock-expiry-time -volume _volume_name_ -snapshot _snapshot_copy_name_ -expiry-time _expiration_date_time_`

+
다음 예에서는 기존 스냅샷 복사본에 보존 기간을 적용합니다.

+
[listing]
----
cluster1> volume snapshot modify-snaplock-expiry-time -volume vol1 -snapshot snap2 -expiry-time "11/10/2022 09:00:00"
----

