---
permalink: snaplock/delete-worm-files-concept.html 
sidebar: sidebar 
keywords: delete, worm, file, privileged, delete, enterprise, mode, retention, period, overview 
summary: 권한 있는 삭제 기능을 사용하여 보존 기간 동안 엔터프라이즈 모드 WORM 파일을 삭제할 수 있습니다. 이 기능을 사용하려면 먼저 SnapLock 관리자 계정을 만든 다음 계정을 사용하여 기능을 활성화해야 합니다. 
---
= WORM 파일 삭제 개요
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
권한 있는 삭제 기능을 사용하여 보존 기간 동안 엔터프라이즈 모드 WORM 파일을 삭제할 수 있습니다. 이 기능을 사용하려면 먼저 SnapLock 관리자 계정을 만든 다음 계정을 사용하여 기능을 활성화해야 합니다.



== SnapLock 관리자 계정을 만듭니다

권한 있는 삭제를 수행하려면 SnapLock 관리자 권한이 있어야 합니다. 이러한 권한은 vsadmin-SnapLock 역할에 정의되어 있습니다. 해당 역할이 아직 할당되지 않은 경우 클러스터 관리자에게 SnapLock 관리자 역할을 가진 SVM 관리자 계정을 만들도록 요청할 수 있습니다.

.필요한 것
* 이 작업을 수행하려면 클러스터 관리자여야 합니다.
* 보안 연결(SSH, 콘솔 또는 ZAPI)에 로그인해야 합니다.


.단계
. SnapLock 관리자 역할을 사용하여 SVM 관리자 계정을 생성합니다.
+
'* 보안 로그인 create-vserver_SVM_name_-user-or-group-name_user_or_group_name_-application_application_-AuthMethod_authentication_method_-role_role_-comment_comment_*'

+
다음 명령을 실행하면 사전 정의된 "vsadmin-snaplock" 역할을 사용하여 SVM 관리자 계정 'napLockAdmin'에서 암호를 사용하여 'VM1'에 액세스할 수 있습니다.

+
[listing]
----
cluster1::> security login create -vserver SVM1 -user-or-group-name SnapLockAdmin -application ssh -authmethod password -role vsadmin-snaplock
----




== 권한 있는 삭제 기능을 활성화합니다

삭제하려는 WORM 파일이 포함된 엔터프라이즈 볼륨에서 권한 있는 삭제 기능을 명시적으로 활성화해야 합니다.

.이 작업에 대해
'-privileged-delete' 옵션의 값은 권한 있는 삭제 활성화 여부를 결정합니다. 가능한 값은 '사용', '사용 안 함', '영구 사용 안 함'입니다.

[NOTE]
====
영구 불활성 상태가 단자다. 상태를 "영구 비활성화"로 설정한 후에는 볼륨에 대한 권한 있는 삭제를 활성화할 수 없습니다.

====
.단계
. SnapLock 엔터프라이즈 볼륨에 대한 권한 있는 삭제 활성화:
+
'* volume SnapLock modify -vserver_SVM_name_-volume_volume_name_-privileged-delete disabled|enabled|permanently-disabled *

+
다음 명령을 실행하면 'VM1'의 엔터프라이즈 볼륨 'dataVol'에 대한 권한 있는 삭제 기능이 활성화됩니다.

+
[listing]
----
SVM1::> volume snaplock modify -vserver SVM1 -volume dataVol -privileged-delete enabled
----




== 엔터프라이즈 모드 WORM 파일을 삭제합니다

권한이 있는 삭제 기능을 사용하여 보존 기간 동안 엔터프라이즈 모드 WORM 파일을 삭제할 수 있습니다.

.필요한 것
* 이 작업을 수행하려면 SnapLock 관리자여야 합니다.
* SnapLock 감사 로그를 생성하고 엔터프라이즈 볼륨에서 권한 있는 삭제 기능을 활성화해야 합니다.


.이 작업에 대해
만료된 WORM 파일을 삭제하려면 권한이 있는 삭제 작업을 사용할 수 없습니다. 'volume file retention show' 명령을 사용하여 삭제할 WORM 파일의 보존 시간을 확인할 수 있습니다. 자세한 내용은 명령에 대한 man 페이지를 참조하십시오.

.단계
. 엔터프라이즈 볼륨에서 WORM 파일 삭제:
+
'* 볼륨 파일 권한이 있는-삭제-vserver_SVM_name_-file_file_path_*'

+
다음 명령을 실행하면 SVM 'sVM1'에서 파일 '/vol/dataVol/F1'이 삭제됩니다.

+
[listing]
----
SVM1::> volume file privileged-delete -file /vol/dataVol/f1
----

