---
permalink: snaplock/index.html 
sidebar: sidebar 
keywords: decide, about, archive, compliance, snaplock, unmodified, file, worm, storage, snap lock, mirror, unmirror. license, compliance clock, regulatory, governance, rules, govern, MAV, multi-admin verification, supported, unsupported 
summary: NetApp SnapLock 기술을 사용하면 규정 및 거버넌스 목적으로 수정되지 않은 형식으로 파일을 보존할 수 있습니다. 
---
= SnapLock란
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapLock는 WORM 스토리지를 사용하여 규정 및 거버넌스 목적으로 수정되지 않은 형태로 파일을 유지하는 조직을 위한 고성능 규정 준수 솔루션입니다.

SnapLock는 SEC 17a-4(f), HIPAA, FINRA, CFTC, GDPR과 같은 규정을 충족하도록 데이터의 삭제, 변경 또는 이름을 바꾸는 것을 방지합니다. SnapLock를 사용하면 파일을 저장한 후 지정된 보존 기간 또는 무기한으로 삭제할 수 없고 쓸 수 없는 상태로 커밋하는 특수한 용도의 볼륨을 생성할 수 있습니다. SnapLock에서는 CIFS 및 NFS와 같은 표준 개방형 파일 프로토콜을 통해 파일 레벨에서 이 보존을 수행할 수 있습니다. SnapLock에서 지원되는 개방형 파일 프로토콜은 NFS(버전 2, 3 및 4) 및 CIFS(SMB 1.0, 2.0 및 3.0)입니다.

SnapLock를 사용하면 파일 및 스냅샷 복사본을 WORM 스토리지에 커밋하고 WORM 보호 데이터에 대한 보존 기간을 설정할 수 있습니다. SnapLock WORM 스토리지는 NetApp 스냅샷 기술을 사용하고 SnapMirror 복제 및 SnapVault 백업을 데이터에 대한 백업 복구 보호를 제공하는 기본 기술로 활용할 수 있습니다.
WORM 스토리지에 대한 자세한 내용: link:https://www.netapp.com/pdf.html?item=/media/6158-tr4526pdf.pdf["NetApp SnapLock-TR-4526을 사용하여 WORM 스토리지를 준수합니다"^].

애플리케이션을 사용하여 NFS 또는 CIFS를 통해 WORM에 파일을 커밋하거나 SnapLock 자동 커밋 기능을 사용하여 파일을 WORM에 자동으로 커밋할 수 있습니다. _WORM 추가 가능 파일_을 사용하여 로그 정보와 같이 점증적으로 기록된 데이터를 보존할 수 있습니다. 자세한 내용은 을 참조하십시오 link:commit-files-worm-state-manual-task.html#create-a-worm-appendable-file["볼륨 추가 모드를 사용하여 WORM 추가 가능 파일을 생성합니다"].

SnapLock는 대부분의 규정 준수 요구사항을 충족하는 데이터 보호 방법을 지원합니다.

* SnapLock for SnapVault를 사용하여 2차 스토리지에서 WORM 상태로 스냅샷 복사본을 보호할 수 있습니다. 을 참조하십시오 link:commit-snapshot-copies-worm-concept.html["WORM에 스냅샷 복사본 커밋"].
* SnapMirror를 사용하여 재해 복구를 위해 WORM 파일을 다른 지리적 위치에 복제할 수 있습니다. 을 참조하십시오 link:mirror-worm-files-task.html["WORM 파일 미러링"].


SnapLock는 NetApp ONTAP의 라이센스 기반 기능입니다. 단일 라이센스를 통해 SnapLock를 엄격한 규정 준수 모드로 사용하고 SEC Rule 17a-4(f) 및 느슨한 엔터프라이즈 모드와 같은 외부 규정을 충족하여 디지털 자산 보호를 위해 내부적으로 요구되는 규정을 준수할 수 있습니다. SnapLock 라이센스는 link:../system-admin/manage-licenses-concept.html#licenses-included-with-ontap-one["ONTAP 1 을 참조하십시오"]소프트웨어 제품군의 일부입니다.

SnapLock는 모든 AFF 및 FAS 시스템과 ONTAP Select에서 지원됩니다. SnapLock는 소프트웨어 전용 솔루션이 아니라 통합 하드웨어 및 소프트웨어 솔루션입니다. 이러한 차이는 통합 하드웨어 및 소프트웨어 솔루션이 필요한 SEC 17a-4(f)와 같은 엄격한 WORM 규정에서 중요합니다. 자세한 내용은 을 link:https://www.sec.gov/rules/interp/34-47806.htm["전자 저장 매체 사용에 대한 중개 딜러에 대한 SEC 지침"^]참조하십시오.



== SnapLock로 할 수 있는 일

SnapLock를 구성한 후 다음 작업을 수행할 수 있습니다.

* link:commit-files-worm-state-manual-task.html["WORM에 파일을 커밋합니다"]
* link:commit-snapshot-copies-worm-concept.html["2차 스토리지를 위해 WORM에 스냅샷 복사본 커밋"]
* link:mirror-worm-files-task.html["재해 복구를 위해 WORM 파일을 미러링합니다"]
* link:hold-tamper-proof-files-indefinite-period-task.html["법적 증거 자료 보관 을 사용하여 소송 중에 WORM 파일을 보관하십시오"]
* link:delete-worm-files-concept.html["권한 있는 삭제 기능을 사용하여 WORM 파일을 삭제합니다"]
* link:set-retention-period-task.html["파일 보존 기간을 설정합니다"]
* link:move-snaplock-volume-concept.html["SnapLock 볼륨을 이동합니다"]
* link:snapshot-lock-concept.html["랜섬웨어 공격을 차단하려면 스냅샷 복사본을 잠그십시오"]
* link:create-audit-log-task.html["감사 로그와 함께 SnapLock 사용을 검토합니다"]
* link:snaplock-apis-reference.html["SnapLock API 사용"]




== SnapLock 규정 준수 및 엔터프라이즈 모드

SnapLock 규정 준수 및 엔터프라이즈 모드는 각 모드에서 WORM 파일을 보호하는 수준에 따라 크게 다릅니다.

|===


| SnapLock 모드 | 보호 수준 | WORM 파일 보존 중 삭제 


 a| 
준수 모드
 a| 
디스크 레벨에서 복구
 a| 
삭제할 수 없습니다



 a| 
엔터프라이즈 모드
 a| 
파일 레벨에서
 a| 
감사된 "권한 삭제" 절차를 사용하여 규정 준수 관리자가 삭제할 수 있습니다

|===
보존 기간이 경과하면 더 이상 필요하지 않은 파일을 삭제할 책임이 있습니다. 파일이 규정 준수 모드이든 엔터프라이즈 모드이든 WORM에 커밋되면 보존 기간이 만료된 후에도 수정할 수 없습니다.

보존 기간 중 또는 이후에 WORM 파일을 이동할 수 없습니다. WORM 파일을 복사할 수 있지만 WORM 특성이 유지되지 않습니다.

다음 표에는 SnapLock 규정 준수 및 엔터프라이즈 모드에서 지원하는 기능의 차이가 나와 있습니다.

|===


| 제공합니다 | SnapLock 규정 준수 | SnapLock 엔터프라이즈 


 a| 
권한 있는 삭제를 사용하여 파일을 활성화 및 삭제합니다
 a| 
아니요
 a| 
예



 a| 
디스크를 다시 초기화합니다
 a| 
아니요
 a| 
예



 a| 
보존 기간 동안 SnapLock 애그리게이트 및 볼륨을 제거합니다
 a| 
아니요
 a| 
예. SnapLock 감사 로그 볼륨을 제외하고 가능합니다



 a| 
Aggregate 또는 볼륨의 이름을 바꿉니다
 a| 
아니요
 a| 
예



 a| 
비NetApp 디스크를 사용합니다
 a| 
아니요
 a| 
예(와 함께 link:https://docs.netapp.com/us-en/ontap-flexarray/index.html["FlexArray 가상화"^])



 a| 
감사 로깅을 위해 SnapLock 볼륨을 사용합니다
 a| 
예
 a| 
예, ONTAP 9.5부터 시작합니다

|===


== SnapLock에서 지원 및 지원되지 않는 기능

다음 표에는 SnapLock 규정 준수 모드, SnapLock 엔터프라이즈 모드 또는 둘 다에서 지원되는 기능이 나와 있습니다.

|===


| 피처 | SnapLock 규정 준수 지원 | SnapLock Enterprise에서 지원됩니다 


 a| 
일관성 그룹
 a| 
아니요
 a| 
아니요



 a| 
암호화된 볼륨
 a| 
예, ONTAP 9.2부터 시작합니다. 에 대해 자세히 알아보십시오 xref:Encryption[암호화 및 SnapLock].
 a| 
예, ONTAP 9.2부터 시작합니다. 에 대해 자세히 알아보십시오 xref:Encryption[암호화 및 SnapLock].



 a| 
SnapLock 애그리게이트에서 Fabric으로 구성
 a| 
아니요
 a| 
예, ONTAP 9.8부터 시작합니다. 에 대해 자세히 알아보십시오 xref:FabricPool on SnapLock Enterprise aggregates[FabricPool on SnapLock 엔터프라이즈 애그리게이트].



 a| 
Flash Pool 애그리게이트로 전환 가능
 a| 
예, ONTAP 9.1부터 사용 가능합니다.
 a| 
예, ONTAP 9.1부터 사용 가능합니다.



 a| 
플랙스클론
 a| 
SnapLock 볼륨의 클론을 생성할 수는 있지만 SnapLock 볼륨의 파일은 복제할 수 없습니다.
 a| 
SnapLock 볼륨의 클론을 생성할 수는 있지만 SnapLock 볼륨의 파일은 복제할 수 없습니다.



 a| 
FlexGroup 볼륨
 a| 
예, ONTAP 9.11.1부터 시작합니다. 에 대해 자세히 알아보십시오 <<flexgroup>>.
 a| 
예, ONTAP 9.11.1부터 시작합니다. 에 대해 자세히 알아보십시오 <<flexgroup>>.



 a| 
LUN을 클릭합니다
 a| 
아니요 에 대해 자세히 알아보십시오 xref:LUN support[LUN 지원] SnapLock와 함께.
 a| 
아니요 에 대해 자세히 알아보십시오 xref:LUN support[LUN 지원] SnapLock와 함께.



 a| 
MetroCluster 구성
 a| 
예, ONTAP 9.3부터 시작합니다. 에 대해 자세히 알아보십시오 xref:MetroCluster support[MetroCluster 지원].
 a| 
예, ONTAP 9.3부터 시작합니다. 에 대해 자세히 알아보십시오 xref:MetroCluster support[MetroCluster 지원].



 a| 
MAV(Multi-admin verification)
 a| 
예, ONTAP 9.13.1. 에 대해 자세히 알아보십시오 xref:Multi-admin verification (MAV) support[MAV 지원].
 a| 
예, ONTAP 9.13.1. 에 대해 자세히 알아보십시오 xref:Multi-admin verification (MAV) support[MAV 지원].



 a| 
산
 a| 
아니요
 a| 
아니요



 a| 
단일 파일 SnapRestore
 a| 
아니요
 a| 
예



 a| 
SnapMirror 활성 동기화
 a| 
아니요
 a| 
아니요



 a| 
SnapRestore
 a| 
아니요
 a| 
예



 a| 
SMTape
 a| 
아니요
 a| 
아니요



 a| 
SnapMirror Synchronous
 a| 
아니요
 a| 
아니요



 a| 
SSD를 지원합니다
 a| 
예, ONTAP 9.1부터 사용 가능합니다.
 a| 
예, ONTAP 9.1부터 사용 가능합니다.



 a| 
스토리지 효율성 기능
 a| 
예, ONTAP 9.9.1부터 시작합니다. 에 대해 자세히 알아보십시오 xref:Storage efficiency[스토리지 효율성 지원].
 a| 
예, ONTAP 9.9.1부터 시작합니다. 에 대해 자세히 알아보십시오 xref:Storage efficiency[스토리지 효율성 지원].

|===


== FabricPool on SnapLock 엔터프라이즈 애그리게이트

FabricPool은 ONTAP 9.8부터 SnapLock 엔터프라이즈 애그리게이트에서 지원됩니다. 그러나 클라우드 관리자가 해당 데이터를 삭제할 수 있으므로 FabricPool 데이터를 퍼블릭 또는 프라이빗 클라우드로 계층화하면 SnapLock에서 더 이상 보호되지 않는다는 사실을 NetApp 어카운트 팀이 설명하는 제품 분산 요청을 개설해야 합니다.

[NOTE]
====
FabricPool에서 퍼블릭 또는 프라이빗 클라우드로 계층화하는 데이터는 클라우드 관리자가 삭제할 수 있으므로 SnapLock에서 더 이상 보호되지 않습니다.

====


== FlexGroup 볼륨

SnapLock는 ONTAP 9.11.1부터 FlexGroup 볼륨을 지원하지만 다음 기능은 지원되지 않습니다.

* 법적 증거 자료 보관
* 이벤트 기반 보존
* SnapLock for SnapVault(ONTAP 9.12.1부터 지원됨)


또한 다음과 같은 행동을 인지해야 합니다.

* FlexGroup 볼륨의 VCC(Volume Compliance Clock)는 루트 구성 요소 VCC에 의해 결정됩니다. 모든 비루트 구성 요소들은 VCC를 루트 VCC와 긴밀히 동기화하게 됩니다.
* SnapLock 구성 속성은 FlexGroup 전체에 대해서만 설정됩니다. 개별 구성 요소마다 기본 보존 시간 및 자동 커밋 기간과 같은 서로 다른 구성 속성을 사용할 수 없습니다.




== LUN 지원

LUN은 비 SnapLock 볼륨에서 생성된 스냅샷 복사본이 SnapLock 볼트 관계의 일부로 보호를 위해 SnapLock 볼륨으로 전송되는 경우에만 SnapLock 볼륨에서 지원됩니다. LUN은 읽기/쓰기 SnapLock 볼륨에서 지원되지 않습니다. 그러나 SnapMirror 소스 볼륨과 LUN이 포함된 타겟 볼륨 모두에서 무단 스냅샷 복사본이 지원됩니다.



== MetroCluster 지원

MetroCluster 구성에서 SnapLock 지원은 SnapLock 규정 준수 모드와 SnapLock 엔터프라이즈 모드 간에 다릅니다.

.SnapLock 규정 준수
* ONTAP 9.3부터 SnapLock 규정 준수는 미러링되지 않은 MetroCluster 애그리게이트에서 지원됩니다.
* ONTAP 9.3부터 SnapLock 규정 준수는 미러링된 애그리게이트에서 SnapLock 감사 로그 볼륨을 호스팅하는 데 사용되는 경우에만 지원됩니다.
* MetroCluster를 사용하여 SVM별 SnapLock 구성을 운영 사이트 및 2차 사이트에 복제할 수 있습니다.


.SnapLock 엔터프라이즈
* ONTAP 9부터 SnapLock 엔터프라이즈 애그리게이트가 지원됩니다.
* ONTAP 9.3부터는 권한이 있는 삭제 기능이 있는 SnapLock 엔터프라이즈 애그리게이트가 지원됩니다.
* MetroCluster를 사용하여 SVM별 SnapLock 구성을 두 사이트 모두에 복제할 수 있습니다.


.MetroCluster 구성 및 규정 준수 클럭
MetroCluster 구성에는 VCC(Volume Compliance Clock)와 SCC(System Compliance Clock)라는 두 가지 준수 클록 메커니즘이 사용됩니다. VCC 및 SCC는 모든 SnapLock 구성에 사용할 수 있습니다. 노드에 새 볼륨을 생성할 때 해당 노드에 있는 SCC의 현재 값으로 VCC가 초기화됩니다. 볼륨이 생성된 후에는 항상 VCC를 통해 볼륨 및 파일 보존 시간을 추적합니다.

볼륨이 다른 사이트에 복제되면 해당 VCC도 복제됩니다. 예를 들어, 사이트 A에서 사이트 B로 볼륨 전환이 발생하면 사이트 A의 SCC가 사이트 A가 오프라인이 되면 사이트 B에서 VCC가 계속 업데이트됩니다.

사이트 A가 다시 온라인 상태가 되고 볼륨 스위치백을 수행하면 볼륨의 VCC가 계속 업데이트되는 동안 사이트 A SCC 클록이 다시 시작됩니다. 스위치오버 및 스위치백 작업과 관계없이 VCC가 지속적으로 업데이트되기 때문에 파일 보존 시간은 SCC 클럭에 의존하지 않고 늘어나지 않습니다.



== MAV(Multi-admin verification) 지원

ONTAP 9.13.1 부터는 클러스터 관리자가 일부 SnapLock 작업을 실행하기 전에 쿼럼을 승인해야 하는 클러스터에서 다중 관리 검증을 명시적으로 활성화할 수 있습니다. MAV가 활성화되면 기본 보존 시간, 최소 보존 시간, 최대 보존 시간, 볼륨 추가 모드, 자동 커밋 기간 및 권한 삭제 등의 SnapLock 볼륨 속성에 쿼럼이 승인되어야 합니다. 에 대해 자세히 알아보십시오 link:../multi-admin-verify/index.html#how-multi-admin-verification-works["5일"].



== 스토리지 효율성

ONTAP 9.9.1부터 SnapLock은 데이터 컴팩션, 볼륨 간 중복제거, SnapLock 볼륨 및 애그리게이트를 위한 적응형 압축과 같은 스토리지 효율성 기능을 지원합니다. 스토리지 효율성에 대한 자세한 내용은 를 참조하십시오 link:../concepts/storage-efficiency-overview.html["ONTAP 스토리지 효율성 개요"].



== 암호화

ONTAP는 스토리지 미디어의 용도 변경, 반환, 잘못된 위치 변경 또는 도난 시 유휴 데이터를 읽을 수 없도록 소프트웨어 및 하드웨어 기반 암호화 기술을 모두 제공합니다.

* 법적 고지 사항: * NetApp은 자체 암호화 드라이브 또는 볼륨의 SnapLock 보호 WORM 파일이 인증 키가 손실되거나 실패한 인증 시도 횟수가 지정된 제한을 초과하여 드라이브가 영구적으로 잠기는 경우 이를 복구할 수 있다고 보장할 수 없습니다. 인증 실패에 대한 책임은 사용자에게 있습니다.

[NOTE]
====
ONTAP 9.2부터는 SnapLock 애그리게이트에서 암호화된 볼륨이 지원됩니다.

====


== 7-Mode 전환

7-Mode 전환 도구의 CBT(Copy-Based Transition) 기능을 사용하여 SnapLock 볼륨을 7-Mode에서 ONTAP로 마이그레이션할 수 있습니다. 대상 볼륨의 SnapLock 모드인 Compliance 또는 Enterprise는 소스 볼륨의 SnapLock 모드와 일치해야 합니다. CFT(Copy-Free Transition)를 사용하여 SnapLock 볼륨을 마이그레이션할 수는 없습니다.
