---
permalink: snaplock/initialize-complianceclock-task.html 
sidebar: sidebar 
keywords: snaplock, complianceclock, compliance clock, initialize, worm, retention, period, node, ntp, reset, resynchronize 
summary: SnapLock ComplianceClock은 WORM 파일의 보존 기간을 변경할 수 있는 변조를 방지합니다. SnapLock 애그리게이트를 호스팅하는 각 노드에서 시스템 규정 준수 클록을 초기화해야 합니다.  
---
= 준수 시계를 초기화합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapLock는 _ volume Compliance Clock _ 을(를) 사용하여 WORM 파일의 보존 기간을 변경할 수 있는 변조를 방지합니다. 먼저 SnapLock 애그리게이트를 호스팅하는 각 노드에서 _SYSTEM ComplianceClock_을 초기화해야 합니다.

ONTAP 9.14.1부터는 SnapLock 볼륨이 없거나 스냅샷 복사본 잠금이 설정된 볼륨이 없을 때 시스템 규정 준수 클록을 초기화하거나 다시 초기화할 수 있습니다. 시스템 관리자는 재초기화 기능을 사용하여 시스템 규정 준수 클록이 잘못 초기화되었을 수 있는 경우에 시스템 규정 준수 클록을 재설정하거나 시스템의 클럭 편차를 수정할 수 있습니다. ONTAP 9.13.1 이하 릴리즈에서는 노드에서 규정 준수 클록을 초기화한 후 다시 초기화할 수 없습니다.

.시작하기 전에
규정 준수 클록을 다시 초기화하려면 다음을 수행합니다.

* 클러스터의 모든 노드가 정상 상태여야 합니다.
* 모든 볼륨이 온라인 상태여야 합니다.
* 복구 큐를 표시할 볼륨이 없습니다.
* SnapLock 볼륨이 없을 수 있습니다.
* 스냅샷 복사본 잠금이 설정된 볼륨을 사용할 수 없습니다.


규정 준수 시계 초기화를 위한 일반 요구 사항:

* 이 작업을 수행하려면 클러스터 관리자여야 합니다.
* SnapLock 라이센스가 노드에 설치되어 있어야 합니다.


.이 작업에 대해
시스템 Compliance Clock의 시간은 _ VOLUME Compliance Clock _ 에 의해 상속되며, 이 시간 중 후자는 볼륨에 있는 WORM 파일의 보존 기간을 제어합니다. 볼륨 준수 시계는 새 SnapLock 볼륨을 생성할 때 자동으로 초기화됩니다.

[NOTE]
====
시스템 규정 준수 클럭의 초기 설정은 현재 하드웨어 시스템 클록을 기반으로 합니다. 따라서 각 노드에서 시스템 규정 준수 클록을 초기화하기 전에 시스템 시간과 시간대가 올바른지 확인해야 합니다. 노드에서 시스템 규정 준수 클록을 초기화하고 나면 SnapLock 볼륨 또는 잠금이 설정된 볼륨이 존재할 때 이를 다시 초기화할 수 없습니다.

====
.단계
ONTAP CLI를 사용하여 규정 준수 클록을 초기화하거나 ONTAP 9.12.1부터 System Manager를 사용하여 규정 준수 클록을 초기화할 수 있습니다.

[role="tabbed-block"]
====
.시스템 관리자
--
. 클러스터 > 개요 * 로 이동합니다.
. 노드 * 섹션에서 * SnapLock 준수 클럭 초기화 * 를 클릭합니다.
. 규정 준수 시계 * 열을 표시하고 규정 준수 시계가 초기화되었는지 확인하려면 * 클러스터 > 개요 > 노드 * 섹션에서 * 표시/숨기기 * 를 클릭하고 * SnapLock 규정 준수 시계 * 를 선택합니다.


--
--
.CLI를 참조하십시오
. 시스템 규정 준수 클록을 초기화합니다.
+
' * SnapLock compliance-clock initialize-node_node_name_ * '

+
다음 명령을 실행하면 시스템 Compliance Clock On이 초기화됩니다 `node1`:

+
[listing]
----
cluster1::> snaplock compliance-clock initialize -node node1
----
. 메시지가 표시되면 시스템 클록이 올바른지, 규정 준수 클록을 초기화할지 확인합니다.
+
[listing]
----
Warning: You are about to initialize the secure ComplianceClock of
the node "node1" to the current value of the node's system clock.
This procedure can be performed only once on a given node, so you
should ensure that the system time is set correctly before proceeding.

The current node's system clock is: Mon Apr 25 06:04:10 GMT 2016

Do you want to continue? (y|n): y
----
. SnapLock 애그리게이트를 호스팅하는 각 노드에 대해 이 절차를 반복합니다.


--
====


== NTP 구성 시스템에 대해 규정 준수 클럭 재동기화를 설정합니다

NTP 서버가 구성되어 있을 때 SnapLock 준수 클럭 시간 동기화 기능을 활성화할 수 있습니다.

.필요한 것
* 이 기능은 고급 권한 수준에서만 사용할 수 있습니다.
* 이 작업을 수행하려면 클러스터 관리자여야 합니다.
* SnapLock 라이센스가 노드에 설치되어 있어야 합니다.
* 이 기능은 Cloud Volumes ONTAP, ONTAP Select 및 VIM 플랫폼에서만 사용할 수 있습니다.


.이 작업에 대해
SnapLock 보안 클럭 데몬이 임계값을 초과하는 편중을 감지하면 ONTAP는 시스템 시간을 사용하여 시스템 및 볼륨 규정 준수 클럭을 모두 재설정합니다. 24시간이 기울기 임계값으로 설정됩니다. 즉, 편중이 하루 이상 지난 경우에만 시스템 규정 준수 클록이 시스템 클록과 동기화됩니다.

SnapLock 보안 클록 데몬은 편중을 감지하고 규정 준수 클럭을 시스템 시간으로 변경합니다. 시스템 시간이 NTP 시간과 동기화되는 경우에만 규정 준수 클록이 시스템 시간과 동기화되기 때문에 규정 준수 클록이 시스템 시간과 동기화되도록 시스템 시간을 수정하려는 시도가 실패합니다.

.단계
. NTP 서버가 구성된 경우 SnapLock 규정 준수 클럭 시간 동기화 기능을 활성화합니다.
+
`* SnapLock 컴플라이언스-클록 NTP * '

+
다음 명령을 실행하면 시스템 규정 준수 클럭 시간 동기화 기능이 설정됩니다.

+
[listing]
----
cluster1::*> snaplock compliance-clock ntp modify -is-sync-enabled true
----
. 메시지가 표시되면 구성된 NTP 서버가 신뢰할 수 있고 통신 채널이 보안 상태인지 확인합니다.
. 기능이 활성화되어 있는지 확인합니다.
+
``SnapLock compliance-clock NTP 쇼 *’

+
다음 명령은 시스템 규정 준수 클럭 시간 동기화 기능이 설정되어 있는지 확인합니다.

+
[listing]
----
cluster1::*> snaplock compliance-clock ntp show

Enable clock sync to NTP system time: true
----

