---
permalink: snaplock/initialize-complianceclock-task.html 
sidebar: sidebar 
keywords: snaplock, complianceclock, initialize, worm, retention, period, node 
summary: SnapLock ComplianceClock은 WORM 파일의 보존 기간을 변경할 수 있는 변조를 방지합니다. SnapLock 애그리게이트를 호스팅하는 각 노드에서 ComplianceClock 시스템을 초기화해야 합니다. 노드에서 ComplianceClock을 초기화하면 다시 초기화할 수 없습니다. 
---
= ComplianceClock을 초기화합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapLock ComplianceClock은 WORM 파일의 보존 기간을 변경할 수 있는 변조를 방지합니다. SnapLock 애그리게이트를 호스팅하는 각 노드에서 _system ComplianceClock_을 초기화해야 합니다. 노드에서 ComplianceClock을 초기화하면 다시 초기화할 수 없습니다.

.무엇을 &#8217;필요로 할거야
* 이 작업을 수행하려면 클러스터 관리자여야 합니다.
* SnapLock 라이센스가 노드에 설치되어 있어야 합니다.


ComplianceClock 시스템의 시간은 볼륨의 WORM 파일에 대한 보존 기간을 제어하는 _volume ComplianceClock_에 의해 상속됩니다. 볼륨 ComplianceClock은 새 SnapLock 볼륨을 생성할 때 자동으로 초기화됩니다.

[NOTE]
====
ComplianceClock의 초기 설정은 현재 시스템 클록을 기반으로 합니다. 따라서 ComplianceClock을 초기화하기 전에 시스템 시간 및 시간대가 올바른지 확인해야 합니다. 노드에서 ComplianceClock을 초기화하면 다시 초기화할 수 없습니다.

====
[role="tabbed-block"]
====
.시스템 관리자
--
ONTAP 9.12.1부터 시스템 관리자를 사용하여 SnapLock 준수 시계를 초기화할 수 있습니다.

.단계
. 클러스터 > 개요 * 로 이동합니다.
. 노드 * 섹션에서 * SnapLock 준수 클럭 초기화 * 를 클릭합니다.
. 준수 클럭 열을 표시하고 준수 시계가 초기화되었는지 확인하려면 * 클러스터 > 개요 > 노드 * 섹션에서 * 표시/숨기기 * 를 클릭하고 * SnapLock 준수 시계 * 를 선택합니다.


--
--
.CLI를 참조하십시오
. 시스템 초기화 ComplianceClock:
+
' * SnapLock compliance-clock initialize-node_node_name_ * '

+
다음 명령을 실행하면 노드1의 ComplianceClock 시스템이 초기화됩니다.

+
[listing]
----
cluster1::> snaplock compliance-clock initialize -node node1
----
. 메시지가 표시되면 시스템 클럭이 올바른지, ComplianceClock을 초기화할지 확인합니다.
+
[listing]
----
Warning: You are about to initialize the secure ComplianceClock of
the node "node1" to the current value of the node's system clock.
This procedure can be performed only once on a given node, so you
should ensure that the system time is set correctly before proceeding.

The current node's system clock is: Mon Apr 25 06:04:10 GMT 2016

Do you want to continue? (y|n): y
----
. SnapLock 애그리게이트를 호스팅하는 각 노드에 대해 이 절차를 반복합니다.


--
====