---
permalink: snaplock/reset-complianceclock-ntp-task.html 
sidebar: sidebar 
keywords: snaplock, reset, complianceclock, ntp, configured, system 
summary: SnapLock 보안 클록 데몬이 임계값을 초과하는 기울기를 감지하면 시스템 시간을 사용하여 시스템과 볼륨 ComplianceClock을 모두 재설정합니다. 
---
= NTP 구성 시스템의 ComplianceClock을 재설정합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapLock 보안 클록 데몬이 임계값을 초과하는 기울기를 감지하면 시스템 시간을 사용하여 시스템과 볼륨 ComplianceClock을 모두 재설정합니다.

.무엇을 &#8217;필요로 할거야
* 이 기능은 고급 권한 수준에서만 사용할 수 있습니다.
* 이 작업을 수행하려면 클러스터 관리자여야 합니다.
* SnapLock 라이센스가 노드에 설치되어 있어야 합니다.
* 이 기능은 Cloud Volumes ONTAP, ONTAP Select 및 VIM 플랫폼에서만 사용할 수 있습니다.


SnapLock 보안 클록 데몬이 임계값을 초과하는 기울기를 감지하면 시스템 시간을 사용하여 시스템과 볼륨 ComplianceClock을 모두 재설정합니다. 24시간이 기울기 임계값으로 설정됩니다. 즉, 편중이 하루 이상 지난 경우에만 시스템 ComplianceClock이 시스템 클록과 동기화됩니다.

SnapLock 보안 클록 데몬은 기울기를 감지하고 ComplianceClock을 시스템 시간으로 변경합니다. ComplianceClock은 시스템 시간이 NTP 시간과 동기화된 경우에만 시스템 시간과 동기화되므로 ComplianceClock을 강제로 시스템 시간에 동기화하기 위해 시스템 시간을 수정하는 시도가 실패합니다.

.단계
. NTP 서버가 구성된 경우 SnapLock ComplianceClock 시간 동기화 기능을 활성화합니다.
+
`* SnapLock 컴플라이언스-클록 NTP * '

+
다음 명령을 실행하면 시스템 ComplianceClock 시간 동기화 기능이 설정됩니다.

+
[listing]
----
cluster1::*> snaplock compliance-clock ntp modify -is-sync-enabled true
----
. 메시지가 표시되면 구성된 NTP 서버가 신뢰할 수 있고 통신 채널이 보안 상태인지 확인합니다.
. 기능이 활성화되어 있는지 확인합니다.
+
``SnapLock compliance-clock NTP 쇼 *’

+
다음 명령을 실행하면 시스템 ComplianceClock 시간 동기화 기능이 활성화되어 있는지 확인합니다.

+
[listing]
----
cluster1::*> snaplock compliance-clock ntp show

Enable clock sync to NTP system time: true
----

