---
permalink: snaplock/snapshot-lock-concept.html 
sidebar: sidebar 
keywords: snaplock, snapshot copy, lock, tamperproof 
summary: ONTAP 9.12.1부터 비 SnapLock 볼륨에 Snapshot 복사본을 잠가 랜섬웨어 공격으로부터 보호할 수 있습니다. 스냅샷 복사본을 잠그면 실수로 또는 악의적으로 삭제할 수 없습니다. 
---
= 스냅샷 복사본의 무단 잠금 개요를 제공합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9.12.1부터 비 SnapLock 볼륨에 Snapshot 복사본을 잠가 랜섬웨어 공격으로부터 보호할 수 있습니다. 스냅샷 복사본을 잠그면 실수로 또는 악의적으로 삭제할 수 없습니다.

SnapLock 컴플라이언스 클록 기능을 사용하면 만료 시간에 도달할 때까지 스냅샷 복사본을 삭제할 수 없도록 지정된 기간 동안 스냅샷 복사본을 잠글 수 있습니다. Snapshot 복사본을 잠그면 무단 변경 방지 기능이 되어 랜섬웨어 위협으로부터 보호됩니다. 잠겨 있는 Snapshot 복사본을 사용하여 랜섬웨어 공격으로 볼륨이 손상된 경우 데이터를 복구할 수 있습니다.



== 스냅샷 복사본의 요구 사항 및 고려 사항을 무단 변경 방지

* 클러스터의 모든 노드에서 ONTAP 9.12.1 이상이 실행되고 있어야 합니다.
* SnapLock 라이센스가 클러스터에 설치되어 있어야 합니다.
+
자세한 내용은 을 참조하십시오 link:https://docs.netapp.com/us-en/ontap/snaplock/install-license-task.html["SnapLock 라이센스 설치"]

* 클러스터의 규정 준수 클록을 초기화해야 합니다.
+
자세한 내용은 을 참조하십시오 link:https://docs.netapp.com/us-en/ontap/snaplock/initialize-complianceclock-task.html["준수 시계를 초기화합니다"]

* 볼륨에서 스냅샷 잠금이 활성화된 경우 클러스터를 ONTAP 9.12.1 이후 버전의 ONTAP로 업그레이드할 수 있습니다. 그러나 잠긴 스냅샷 복사본의 만료 날짜가 모두 만료되어 삭제되고 스냅샷 복사본 잠금이 비활성화되기 전에는 이전 버전의 ONTAP로 되돌릴 수 없습니다.
* 스냅샷이 잠기면 볼륨 만료 시간이 스냅샷 복사본의 만료 시간으로 설정됩니다. 둘 이상의 스냅샷 복사본이 잠겨 있는 경우 볼륨 만료 시간은 모든 스냅샷 복사본 중에서 가장 큰 만료 시간을 반영합니다.
* 잠긴 스냅샷 복사본의 보존 기간이 스냅샷 복사본 보존 기간보다 우선적으로 적용됩니다. 즉, 잠긴 스냅샷 복사본의 보존 기간이 만료되지 않은 경우 유지 수 제한이 적용되지 않습니다.
* SnapMirror 관계에서 미러 소산 정책 규칙에 보존 기간을 설정할 수 있으며, 타겟 볼륨에 스냅샷 복사본 잠금이 활성화된 경우 타겟에 복제된 스냅샷 복사본에 보존 기간이 적용됩니다. 보존 기간이 keep 카운트보다 우선합니다. 예를 들어, 만료일이 경과하지 않은 Snapshot 복사본은 keep 카운트가 초과되더라도 보존됩니다.
* 비 SnapLock 볼륨의 스냅샷 복사본 이름을 바꿀 수 있습니다. SnapMirror 관계의 운영 볼륨에 대한 스냅샷 이름 바꾸기 작업은 정책이 MirrorAllSnapshots인 경우에만 보조 볼륨에 반영됩니다. 다른 정책 유형의 경우 업데이트 중에는 이름이 변경된 스냅샷 복사본이 전파되지 않습니다.
* 로 잠긴 스냅샷 복사본을 복원할 수 있습니다 `volume snapshot restore` 잠긴 스냅샷 복사본이 최신 상태인 경우에만 명령 복원 중인 스냅샷 복사본 이외의 만료되지 않은 스냅샷 복사본이 있는 경우 스냅샷 복사본 복원 작업이 실패합니다.




== 무단 스냅샷 복사본으로 지원되는 기능

* FlexGroup 볼륨
+
스냅샷 복사본 잠금은 FlexGroup 볼륨에서 지원됩니다. 스냅샷 잠금은 루트 구성 요소 스냅샷 복사본에만 적용됩니다. FlexGroup 볼륨은 루트 구성 요소 만료 시간이 경과한 경우에만 삭제할 수 있습니다.

* FlexVol에서 FlexGroup로의 변환
+
잠긴 스냅샷 복사본이 있는 FlexVol 볼륨을 FlexGroup 볼륨으로 변환할 수 있습니다. 스냅샷 복사본은 변환 후에도 잠겨 있습니다.

* FabricPool
+
스냅샷 복사본 잠금은 볼륨에 클라우드로 계층화된 블록이 없고 계층화 정책이 "없음"으로 설정된 경우에만 FabricPool 볼륨에서 지원됩니다. 스냅샷 복사본 잠금 기능이 설정된 경우 볼륨에 대한 계층화 정책을 "없음"이 아닌 정책으로 설정할 수 없습니다.





== 지원되지 않는 기능입니다

다음 기능은 현재 무단 스냅샷 복사본에서는 지원되지 않습니다.

* 정합성 보장 그룹
* FlexCache 볼륨
* SMTape
* SnapCenter
* SnapMirror 비즈니스 연속성(SM-BC)
* SnapMirror Synchronous

