---
permalink: nfs-trunking/create-server-task.html 
sidebar: sidebar 
keywords: NFS, servers, create, NFS trunking, enabled, multipathing, svm 
summary: ONTAP 9.14.1부터 v4.1 이상을 실행하는 NFS 서버에서 트렁킹을 활성화할 수 있습니다. NFSv4.1 이상은 NFS 서버가 생성될 때 기본적으로 사용하도록 설정됩니다. 
---
= 트렁킹 사용 NFS 서버를 생성합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9.14.1부터 NFS 서버에서 트렁킹을 활성화할 수 있습니다. NFSv4.1은 NFS 서버가 생성될 때 기본적으로 사용하도록 설정됩니다.

.시작하기 전에
트렁킹 지원 NFS 서버를 생성하려면 SVM이 필요합니다. SVM은 다음과 같아야 합니다.

* 클라이언트 데이터 요구 사항을 충족할 수 있는 충분한 저장소 지원.
* NFS에 대해 설정되었습니다.


기존 SVM을 사용할 수 있지만 트렁킹을 활성화하려면 모든 NFSv4.x 클라이언트를 다시 마운트해야 하므로 시스템이 중단될 수 있습니다. 다시 마운트할 수 없는 경우, NFS 서버에 대한 새 SVM을 생성하십시오.

.단계
. 적합한 SVM이 없는 경우 다음을 생성합니다.
+
`vserver create -vserver _svm_name_ -rootvolume _root_volume_name_ -aggregate _aggregate_name_ -rootvolume-security-style unix -language C.UTF-8`

. 새로 생성한 SVM의 구성 및 상태 확인:
+
'vserver show -vserver_svm_name_'

+
에 대해 자세히 알아보십시오 link:../nfs-config/create-svms-data-access-task.html["SVM 생성"].

. NFS 서버 생성:
+
`vserver nfs create -vserver _svm_name_ -v3 disabled -v4.0 disabled -v4.1 enabled -v4.1-trunking enabled -v4-id-domain _my_domain.com_`

. NFS가 실행 중인지 확인합니다.
+
`vserver nfs status -vserver _svm_name_`

. NFS가 원하는 대로 구성되었는지 확인합니다.
+
`vserver nfs show -vserver _svm_name_`

+
에 대해 자세히 알아보십시오 link:../nfs-config/create-server-task.html["NFS 서버 구성"]



.작업을 마친 후
필요에 따라 다음 서비스를 구성합니다.

* link:../nfs-config/configure-dns-host-name-resolution-task.html["DNS"]
* link:../nfs-config/using-ldap-concept.html["LDAP를 지원합니다"]
* link:../nfs-config/kerberos-nfs-strong-security-concept.html["Kerberos"]

