---
permalink: nfs-trunking/modify-exports-task.html 
sidebar: sidebar 
keywords: NFS, servers, network, NFS trunking, NIC, export, policies, rule, Linux, VMware, datastores, client 
summary: 클라이언트가 기존 데이터 공유에 대해 트렁킹을 활용할 수 있도록 하려면 엑스포트 정책과 규칙 및 규칙이 연결되는 볼륨을 수정해야 할 수 있습니다. 
---
= ONTAP 볼륨 엑스포트 정책을 수정합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
클라이언트가 기존 데이터 공유에 대해 트렁킹을 활용할 수 있도록 하려면 엑스포트 정책과 규칙 및 규칙이 연결되는 볼륨을 수정해야 할 수 있습니다. Linux 클라이언트 및 VMware 데이터 저장소에는 서로 다른 내보내기 요구 사항이 있습니다.

클라이언트 내보내기 요구 사항:

* Linux 클라이언트는 트렁킹 연결(즉, 각 LIF)에 대해 별도의 마운트 및 마운트 지점을 가져야 합니다.
+
ONTAP 9.14.1로 업그레이드할 때 이미 볼륨을 내보낸 경우에는 트렁킹 그룹에서 해당 볼륨을 계속 사용할 수 있습니다.

* VMware 클라이언트에는 여러 LIF가 지정된, 내보낸 볼륨에 대해 단일 마운트 지점만 필요합니다.
+
VMware 클라이언트는 엑스포트 정책에서 루트 액세스 권한이 필요합니다.



.단계
. 기존 엑스포트 정책이 있는지 확인:
+
vserver export-policy show를 참조하십시오

. 기존 내보내기 정책 규칙이 트렁킹 구성에 적합한지 확인합니다.
+
'vserver export-policy rule show-policyname_policy_name_'

+
특히 를 확인합니다 `-clientmatch` 매개 변수는 내보내기를 마운트할 트렁킹 가능 Linux 또는 VMware 클라이언트를 올바르게 식별합니다.

+
조정이 필요한 경우 를 사용하여 규칙을 수정합니다 `vserver export-policy rule modify` 명령을 실행하거나 새 규칙을 만듭니다.

+
`vserver export-policy rule create -vserver _svm_name_ -policyname _policy_name_ -ruleindex integer -protocol nfs4 -clientmatch { text | "text,text,…" } -rorule _security_type_ -rwrule _security_type_ -superuser _security_type_ -anon _user_ID_`

+
에 대해 자세히 알아보십시오 link:../nfs-config/add-rule-export-policy-task.html["내보내기 규칙을 만드는 중입니다."]

. 내보낸 기존의 볼륨이 온라인 상태인지 확인합니다.
+
`volume show -vserver _svm_name_`


