---
permalink: nfs-trunking/prepare-network-task.html 
sidebar: sidebar 
keywords: NFS, servers, network, prepare, NFS trunking, LIF, trunking group, NIC 
summary: NFSv4.1 트렁킹을 활용하려면 트렁킹 그룹의 LIF가 동일한 노드에 있어야 하고 동일한 노드에 홈 포트가 있어야 합니다. . 
---
= 트렁킹을 위해 네트워크를 준비합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NFSv4.1 트렁킹을 활용하려면 트렁킹 그룹의 LIF가 동일한 노드에 있어야 하고 동일한 노드에 홈 포트가 있어야 합니다. LIF는 같은 노드의 페일오버 그룹에서 구성되어야 합니다.

.이 작업에 대해
LIF 및 NIC의 일대일 매핑은 최고의 성능 향상을 생성하지만 트렁킹은 활성화하지 않아도 됩니다. NIC가 2개 이상 설치되어 있으면 성능상의 이점을 얻을 수 있지만 반드시 필요한 것은 아닙니다.

여러 페일오버 그룹을 가질 수 있지만 트렁킹용 페일오버 그룹에는 트렁킹 그룹에 있는 LIFS만 포함되어야 합니다.

페일오버 그룹에서 접속(및 기본 NIC)을 추가하거나 제거할 때마다 트렁킹 페일오버 그룹을 조정해야 합니다.

.시작하기 전에
* 페일오버 그룹을 생성하려는 경우 NIC와 연결된 포트 이름을 알아야 합니다.
* 포트는 모두 같은 노드에 있어야 합니다.


.단계
. 사용할 네트워크 포트의 이름 및 상태를 확인합니다.
+
`network port status`

. 페일오버 그룹을 생성합니다.
+
`network interface failover-groups create -vserver _svm_name_ -failover-group _failover_group_name_ -targets _ports_list_`

+

NOTE: 페일오버 그룹이 반드시 있어야 하는 것은 아니지만 이 그룹이 반드시 권장됩니다.

+
** `_svm_name_` 은 NFS 서버가 포함된 SVM의 이름입니다.
** `_ports_list_` 은 페일오버 그룹에 추가될 포트의 목록입니다.
+
포트는 node_name:port_number_ 형식에 추가됩니다. 예를 들어 node1:e0c 와 같습니다.

+
다음 명령을 실행하면 SVM VS1에 대한 페일오버 그룹 fg3이 생성되고 포트 3개가 추가됩니다.

+
`network interface failover-groups create -vserver vs1 -failover-group fg3 -targets cluster1-01:e0c,cluster1-01:e0d,cluster1-01:e0e`

+
에 대해 자세히 알아보십시오 link:../networking/configure_failover_groups_and_policies_for_lifs_overview.html["페일오버 그룹:"]



. 필요한 경우 트렁킹 그룹 구성원에 대한 LIF를 생성합니다.
+
`network interface create -vserver _svm_name_ -lif _lif_name_ -home-node _node_name_ -home-port _port_name_ -address _IP_address_ -netmask _IP_address_ [-service-policy _policy_] [-auto-revert {true|false}]`

+
** `-home-node` - LIF에서 네트워크 인터페이스 되돌리기 명령을 실행할 때 LIF가 반환되는 노드입니다.
+
또한 LIF가 '-auto-revert' 옵션을 사용하여 홈 노드 및 홈 포트로 자동으로 되돌아가는지 여부를 지정할 수도 있습니다.

** `-home-port` LIF에서 네트워크 인터페이스 되돌리기 명령을 실행할 때 LIF가 반환되는 물리적 포트 또는 논리 포트입니다.
** 를 사용하여 IP 주소를 지정할 수 있습니다 `-address` 및 `-netmask` 옵션이 아닌 옵션 `-subnet` 옵션을 선택합니다.
** IP 주소를 할당할 때 다른 IP 서브넷에 클라이언트 또는 도메인 컨트롤러가 있는 경우 게이트웨이에 대한 기본 경로를 구성해야 할 수 있습니다. 를 클릭합니다 `network route create` man 페이지에는 SVM 내에서 정적 라우트를 생성하는 방법에 대한 정보가 포함되어 있습니다.
** `-service-policy` - LIF에 대한 서비스 정책. 정책을 지정하지 않으면 기본 정책이 자동으로 할당됩니다. 를 사용합니다 `network interface service-policy show` 명령을 사용하여 사용 가능한 서비스 정책을 검토합니다.
** `-auto-revert` - 시작, 관리 데이터베이스 상태 변경 또는 네트워크 연결이 이루어질 때 데이터 LIF가 홈 노드로 자동 복구되는지 여부를 지정합니다. 기본 설정은 false 이지만 환경의 네트워크 관리 정책에 따라 true로 설정할 수 있습니다.
+
트렁킹 그룹의 모든 LIF에 대해 이 단계를 반복합니다.

+
다음 명령을 실행하면 이 생성됩니다 `lif-A` SVM을 위해 `vs1`, 포트에 있습니다 `e0c` 노드 `cluster1_01`:

+
`network interface create -vserver vs1 -lif lif-A -service-policy *???* -home-node cluster1_01 -home-port e0c -address 192.0.2.0`

+
에 대해 자세히 알아보십시오 link:../networking/create_lifs.html["LIF 생성:"]



. LIF가 생성되었는지 확인:
+
네트워크 인터페이스 쇼

. 구성된 IP 주소에 연결할 수 있는지 확인합니다.
+
[cols="25,75"]
|===
| 다음을 확인하려면... | 사용... 


| IPv4 주소입니다 | 네트워크 핑 


| IPv6 주소입니다 | 네트워크 핑6 
|===

