---
permalink: cloud/data-sovereignty-concept.html 
sidebar: sidebar 
keywords: data sovereignty 
summary: '데이터 주권은 데이터의 수집, 저장 및 전송에 관한 국가 법률을 의미합니다. 유럽의 GDPR(General Data Protection Regulation)과 미국의 HIPAA(Health Insurance Portability and Accountability Act)는 이러한 법률의 예입니다. 데이터 상주 는 데이터가 물리적으로 저장되어 있으며 데이터 주권 법률에 의해 지정되는 경우를 말합니다. 개인에 대한 개인 정보는 주요 규제 대상이지만 다른 데이터도 규제할 수 있습니다.' 
---
= 데이터 주권
:icons: font
:imagesdir: ../media/


[role="lead"]
데이터 주권은 데이터의 수집, 저장 및 전송에 관한 국가 법률을 의미합니다. 유럽의 GDPR(General Data Protection Regulation)과 미국의 HIPAA(Health Insurance Portability and Accountability Act)는 이러한 법률의 예입니다. 데이터 상주 는 데이터가 물리적으로 저장되어 있으며 데이터 주권 법률에 의해 지정되는 경우를 말합니다. 개인에 대한 개인 정보는 주요 규제 대상이지만 다른 데이터도 규제할 수 있습니다.

자체 데이터 센터에 데이터를 저장할 때 데이터의 저장 방법과 위치를 완벽하게 제어할 수 있습니다. 클라우드에 데이터를 저장할 때 데이터가 물리적으로 저장되는 방법 및 위치를 파악해야 하는 책임이 있으며, 사용자는 해당 데이터 주권 법률을 준수해야 할 책임이 있습니다. 하이브리드 클라우드 구성의 경우, 온프레미스 계층과 클라우드 계층이 저장된 위치에 주의를 기울여야 합니다.

다행히도 모든 주요 클라우드 공급자는 법률을 잘 알고 있으며 이를 준수하는 데 도움이 되는 절차 및 정보를 가지고 있습니다. 그러나 특정 요구에 맞는 적절한 제품 및 절차를 선택하는 것은 여전히 중요합니다.

대부분의 경우 데이터를 클라우드에 저장하면 기업이 물리적으로 존재하지 않는 국가의 내에서 데이터를 보관할 수 있습니다.

다음은 NetApp과 클라우드 공급자의 규정 준수 정보에 대한 몇 가지 예입니다.

* https://cloud.netapp.com/blog/blg-gdpr-and-hipaa-compliant-storage-systems-with-cloud-tiering["GDPR 및 HIPAA 준수 스토리지 설계"]
* https://azure.microsoft.com/en-us/blog/questions-on-data-residency-and-compliance-in-azure-we-got-answers/["Microsoft Azure의 데이터 상주 및 규정 준수에 대한 질문"]
* https://aws.amazon.com/compliance/gdpr-center/["Amazon Web Services를 위한 GDPR(General Data Protection Regulation) Center 에서 이용할 수 있습니다"]
* https://cloud.google.com/security/compliance["Google Cloud용 규정 준수 리소스 센터"]
* https://www.alibabacloud.com/trust-center["Alibaba Cloud Security & amp; Compliance Center 를 참조하십시오"]

