---
permalink: flexcache/audit-flexcache-volumes-concept.html 
sidebar: sidebar 
keywords: considerations, auditing, flexcache, volumes 
summary: ONTAP 9.7부터는 기본 ONTAP 감사 및 FPolicy를 사용한 파일 정책 관리를 통해 FlexCache 관계에서 NFS 파일 액세스 이벤트를 감사할 수 있습니다. CIFS가 있는 FlexCache 볼륨에는 FPolicy가 지원되지 않습니다. 기본 감사 및 FPolicy는 FlexVol 볼륨에 사용되는 동일한 CLI 명령으로 구성 및 관리됩니다. 그러나 FlexCache 볼륨에는 몇 가지 다른 동작이 있습니다. 
---
= FlexCache 볼륨을 감사할 때의 고려 사항
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9.7부터는 기본 ONTAP 감사 및 FPolicy를 사용한 파일 정책 관리를 통해 FlexCache 관계에서 NFS 파일 액세스 이벤트를 감사할 수 있습니다. CIFS가 있는 FlexCache 볼륨에는 FPolicy가 지원되지 않습니다. 기본 감사 및 FPolicy는 FlexVol 볼륨에 사용되는 동일한 CLI 명령으로 구성 및 관리됩니다. 그러나 FlexCache 볼륨에는 몇 가지 다른 동작이 있습니다.

* * 기본 감사 *
+
** FlexCache 볼륨을 감사 로그의 대상으로 사용할 수 없습니다.
** FlexCache 볼륨의 읽기 및 쓰기를 감사하려면 캐시 SVM과 원본 SVM 모두에 대해 감사를 구성해야 합니다.
+
이는 파일 시스템 작업이 처리되는 곳에서 감사되기 때문입니다. 즉, 캐시 SVM에서 읽기를 감사하고 원본 SVM에서 쓰기를 감사합니다.

** 쓰기 작업의 출처를 추적하기 위해 SVM UUID 및 MSID가 감사 로그에 추가되어 쓰기 작업이 시작된 FlexCache 볼륨을 식별합니다.
** NFSv4 또는 SMB 프로토콜을 사용하여 파일에서 SACL(시스템 액세스 제어 목록)을 설정할 수 있지만 FlexCache 볼륨은 NFSv3만 지원합니다. 따라서 SACL은 원본 볼륨에만 설정할 수 있습니다.


* FPolicy * 를 사용합니다
+
** FlexCache 볼륨에 대한 쓰기가 원본 볼륨에서 커밋되더라도 FPolicy 구성은 캐시 볼륨의 쓰기를 모니터링합니다. 이는 원본 볼륨에서 쓰기를 감사하는 네이티브 감사와는 다릅니다.
** ONTAP는 캐시 및 원본 SVM에 동일한 FPolicy 구성을 요구하지 않지만, 유사한 구성을 두 개 구축하는 것이 좋습니다. 원래 SVM과 같이 구성된 캐시에 대한 새로운 FPolicy 정책을 생성하지만, 새 정책 범위는 캐시 SVM으로 제한됩니다.



