---
permalink: flexcache/delete-relationship-task.html 
sidebar: sidebar 
keywords: deleting, flexcache, relationship 
summary: 더 이상 FlexCache 볼륨이 필요하지 않은 경우 FlexCache 관계 및 FlexCache 볼륨을 삭제할 수 있습니다. 
---
= FlexCache 관계를 삭제합니다
:icons: font
:imagesdir: ../media/


[role="lead"]
더 이상 FlexCache 볼륨이 필요하지 않은 경우 FlexCache 관계 및 FlexCache 볼륨을 삭제할 수 있습니다.

.단계
. FlexCache 볼륨이 있는 클러스터에서 FlexCache 볼륨을 오프라인으로 설정합니다.
+
'volume offline-vserver svm_name-volume volume volume_name'

. FlexCache 볼륨을 삭제합니다.
+
'볼륨 FlexCache 삭제 - vserver svm_name - volume volume volume_name'

+
FlexCache 관계 세부 정보가 원본 볼륨 및 FlexCache 볼륨에서 제거됩니다.

+
[NOTE]
====
'volume FlexCache delete' 명령이 오리진 측 구성을 정리하지 못하면 'volume FlexCache origin cleanup-cache-relationship' 명령을 실행하라는 메시지가 표시됩니다. 이 시나리오에서는 3단계로 이동합니다.

====
. 원본 클러스터에서 원본 볼륨에서 FlexCache 관계 세부 정보를 정리합니다.
+
'volume FlexCache origin cleanup-cache-relationship-origin-volume origin-vserver origin_svm-cache-vserver flexcache_svm-cache-volume flexcache_vol'

+
[NOTE]
====
'volume FlexCache origin cleanup-cache-relationship' 명령을 실행하면 FlexCache 관계가 삭제되고 다시 설정할 수 없습니다.

====
+
[listing]
----
cluster1::> volume flexcache origin cleanup-cache-relationship -origin-volume origin1 -origin-vserver vs34 -cache-vserver vs56 -cache-volume fc1

Warning: This command only needs to be run if "volume flexcache delete" fails on
         the FlexCache cluster and prompts you to run this command. The cache
         configuration will be deleted and cannot be reestablished for the
         cache relationship between origin of a FlexCache volume
         "origin1" in Vserver "vs34" and FlexCache volume
         "fc1" in Vserver "vs56".
Do you want to continue? {y|n}: y
----

