---
permalink: volumes/aggregate-fullness-overallocation-alerts-concept.html 
sidebar: sidebar 
keywords: how to, address, aggregate, fullness, overallocation, alerts 
summary: ONTAP는 Aggregate의 공간이 부족할 때 EMS 메시지를 발행하므로 전체 애그리게이트에 더 많은 공간을 제공하여 수정 조치를 취할 수 있습니다. 알림의 유형과 해결 방법을 알면 데이터 가용성을 보장하는 데 도움이 됩니다. 
---
= 애그리게이트 전체도 및 초과 할당 경고를 처리합니다
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP는 Aggregate의 공간이 부족할 때 EMS 메시지를 발행하므로 전체 애그리게이트에 더 많은 공간을 제공하여 수정 조치를 취할 수 있습니다. 알림의 유형과 해결 방법을 알면 데이터 가용성을 보장하는 데 도움이 됩니다.

Aggregate가 _FULL_으로 설명되면 볼륨에서 사용할 수 있는 애그리게이트의 공간 백분율이 사전 정의된 임계값 아래로 떨어졌다는 의미입니다. Aggregate가 _overallocated_가 되면 ONTAP에서 메타데이터에 사용하고 기본 데이터 액세스를 지원하는 데 사용되는 공간이 소진되었습니다. 경우에 따라 다른 목적으로 일반적으로 예약된 공간을 사용하여 애그리게이트의 기능을 유지할 수 있지만, 애그리게이트 또는 데이터 가용성과 연결된 볼륨의 볼륨 보장이 위험에 노출될 수 있습니다.

초과 할당은 논리적 또는 물리적 할당일 수 있습니다. _논리적 초과 할당_은 볼륨 보증과 같은 향후 공간 약속을 지키기 위해 예약된 공간이 다른 용도로 사용되었음을 의미합니다. _physical overallocation_은 사용할 물리적 블록이 Aggregate에 부족함을 의미합니다. 이 상태의 애그리게이트는 쓰기 작업을 거부하거나, 오프라인 상태가 되거나, 컨트롤러 중단을 일으킬 위험이 있습니다.

다음 표에서는 전체 및 초과 할당 알림, 문제 해결을 위해 수행할 수 있는 작업 및 조치를 취하지 않을 경우의 위험에 대해 설명합니다.

[cols="5%,5%,5%,35%,25%,25%"]
|===
| 경고 유형 | EMS 레벨 | 구성 가능? | 정의 | 해결 방법 | 조치를 취하지 않을 경우 위험이 있습니다 


 a| 
거의 꽉 찼습니다
 a| 
디버그
 a| 
해당 없음
 a| 
볼륨에 할당된 공간(보장 포함)이 이 알림에 대해 설정된 임계값(95%)을 초과했습니다. 이 비율은 사용된 총합에서 스냅숏 예비 공간의 크기를 뺀 값입니다.
 a| 
* Aggregate에 스토리지 추가
* 볼륨 축소 또는 삭제
* 공간을 더 많이 확보한 다른 애그리게이트로 볼륨 이동
* 볼륨 보장 제거('없음'으로 설정)

 a| 
아직 쓰기 작업 또는 데이터 가용성에 대한 위험이 없습니다.



 a| 
가득 참
 a| 
디버그
 a| 
해당 없음
 a| 
파일 시스템이 이 알림에 대해 설정된 임계값(98%)을 초과했습니다. 이 비율은 사용된 총합에서 스냅숏 예비 공간의 크기를 뺀 값입니다.
 a| 
* Aggregate에 스토리지 추가
* 볼륨 축소 또는 삭제
* 공간을 더 많이 확보한 다른 애그리게이트로 볼륨 이동
* 볼륨 보장 제거('없음'으로 설정)

 a| 
볼륨에 대한 쓰기 작업뿐만 아니라 애그리게이트에서 볼륨에 대한 볼륨 보증이 위험에 노출될 수 있습니다.



 a| 
논리적으로 초과 할당됨
 a| 
SVC 오류입니다
 a| 
해당 없음
 a| 
볼륨이 꽉 찼을 때 예약된 공간 외에 메타데이터에 사용되는 애그리게이트의 공간이 소진되었습니다.
 a| 
* Aggregate에 스토리지 추가
* 볼륨 축소 또는 삭제
* 공간을 더 많이 확보한 다른 애그리게이트로 볼륨 이동
* 볼륨 보장 제거('없음'으로 설정)

 a| 
볼륨에 대한 쓰기 작업뿐만 아니라 애그리게이트의 볼륨이 위험에 노출됩니다.



 a| 
물리적으로 초과 할당되었습니다
 a| 
노드 오류입니다
 a| 
해당 없음
 a| 
aggregate에 쓸 수 있는 물리적 블록이 부족하고 있습니다.
 a| 
* Aggregate에 스토리지 추가
* 볼륨 축소 또는 삭제
* 공간을 더 많이 확보한 다른 애그리게이트로 볼륨 이동

 a| 
애그리게이트에서 볼륨에 대한 쓰기 작업이 위험에 처하고 데이터 가용성이 향상됩니다. 애그리게이트는 오프라인 상태가 될 수 있습니다. 극단적인 경우 노드가 중단될 수 있습니다.

|===
전체 백분율 상승 또는 하강 여부와 관계없이 집계에 대해 임계값을 초과할 때마다 EMS 메시지가 생성됩니다. 전체 레벨의 전체도가 임계치 이하로 내려가면 집계 ok EMS 메시지가 생성된다.
