---
permalink: volumes/change-maximum-number-files-allowed-concept.html 
sidebar: sidebar 
keywords: considerations, changing, maximum number of files, allowed, flexvol volume 
summary: FlexVol 볼륨에는 포함할 수 있는 최대 파일 수가 있습니다. 볼륨에 대한 최대 파일 수를 변경할 수 있지만 변경하기 전에 이 변경이 볼륨에 미치는 영향을 이해해야 합니다. 
---
= FlexVol 볼륨에서 허용되는 최대 파일 수를 변경하기 위한 고려 사항
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
FlexVol 볼륨에는 포함할 수 있는 최대 파일 수가 있습니다. 볼륨에 대한 최대 파일 수를 변경할 수 있지만 변경하기 전에 이 변경이 볼륨에 미치는 영향을 이해해야 합니다.

데이터에 많은 수의 파일 또는 매우 큰 디렉토리가 필요한 경우 ONTAP 파일 또는 디렉토리 용량을 확장할 수 있습니다. 그러나 계속하기 전에 이 작업에 대한 제한 사항과 주의사항을 이해해야 합니다.

볼륨에 포함할 수 있는 파일 수는 포함된 inode 수에 따라 결정됩니다. inode_는 파일에 대한 정보가 포함된 데이터 구조입니다. 볼륨에는 프라이빗 및 퍼블릭 inode가 모두 있습니다. 공용 inode는 사용자에게 표시되는 파일에 사용되며, 전용 inode는 ONTAP에서 내부적으로 사용되는 파일에 사용됩니다. 볼륨에 대한 최대 공용 inode 수만 변경할 수 있습니다. 개인 inode 수는 변경할 수 없습니다.

ONTAP는 32KB의 볼륨 크기당 1개의 inode에 따라 새로 생성된 볼륨의 최대 공용 inode 수를 자동으로 설정합니다. 관리자가 직접 볼륨을 늘리거나 자동 크기 조정 기능을 통해 ONTAP에 의해 자동으로 볼륨의 크기를 늘릴 경우 ONTAP는 또한 최대 공용 inode 수를 늘이므로 32KB의 볼륨 크기당 최소 inode가 1개 이상 존재하게 됩니다. 볼륨을 약 680GB에 도달할 때까지

9.13.1 이전 버전의 ONTAP에서는 ONTAP가 자동으로 22,369,621개 이상의 inode를 생성하지 않기 때문에 크기가 680GB보다 큰 볼륨은 자동으로 더 많은 inode를 생성하지 않습니다. 모든 크기 볼륨에 기본 수보다 많은 파일이 필요한 경우 볼륨 수정 명령을 사용하여 볼륨에 대한 최대 inode 수를 늘릴 수 있습니다.

ONTAP 9.13.1부터 최대 inode 수가 계속 증가하므로 볼륨이 680GB보다 크더라도 32KB 볼륨당 inode가 1개 있습니다. 이러한 증가는 볼륨이 inode 최대 2,147,483,632에 도달할 때까지 계속됩니다

최대 공용 inode 수를 줄일 수도 있습니다. 이렇게 해도 inode에 현재 할당된 공간은 변경되지 않지만 공용 inode 파일에서 사용할 수 있는 최대 공간은 줄어듭니다. 그러나 inode에 할당된 공간은 볼륨에 반환되지 않습니다. 따라서 현재 할당된 inode 수보다 최대 inode 수를 낮추면 할당되었지만 사용되지 않은 inode에서 사용하는 공간이 볼륨에 반환되지 않습니다.

.추가 정보
* xref:display-file-inode-usage-task.html[파일 또는 inode 사용량을 표시합니다]

