---
permalink: volumes/change-existing-quota-limits-task.html 
sidebar: sidebar 
keywords: modify, resize, quota limits 
summary: 기존 할당량의 크기를 변경하면 영향을 받는 모든 볼륨에서 할당량의 크기를 조정할 수 있으므로 해당 볼륨에서 할당량을 다시 초기화하는 것보다 빠릅니다. 
---
= 할당량 제한을 수정(또는 크기 조정)합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
기존 할당량의 크기를 변경하면 영향을 받는 모든 볼륨에서 할당량의 크기를 조정할 수 있으므로 해당 볼륨에서 할당량을 다시 초기화하는 것보다 빠릅니다.

.이 작업에 대해
스토리지 가상 머신(SVM, 이전 명칭 Vserver)에 강제 할당량이 있고, 기존 할당량의 크기 제한을 변경하거나, 이미 파생 할당량이 있는 타겟에 할당량을 추가하거나 삭제할 수 있습니다.

.단계
. '-instance' 매개 변수와 함께 'vserver show' 명령을 사용하여 현재 SVM에 할당된 정책의 이름을 확인합니다.
. 다음 작업을 수행하여 할당량 규칙을 수정합니다.
+
** 'volume quota policy rule modify' 명령을 사용하여 기존 할당량 규칙의 디스크 또는 파일 제한을 수정합니다.
** "volume quota policy rule create" 명령을 사용하여 현재 파생 할당량이 있는 타겟(사용자, 그룹 또는 qtree)에 대한 명시적 할당량 규칙을 생성합니다.
** "volume quota policy rule delete" 명령을 사용하여 기본 할당량이 있는 타겟(사용자, 그룹 또는 qtree)에 대한 명시적 할당량 규칙을 삭제합니다.


. 'volume quota policy rule show' 명령을 사용하여 할당량 규칙이 올바르게 구성되었는지 확인합니다.
. 할당량을 변경한 각 볼륨에 대해 '볼륨 할당량 크기 조정' 명령을 사용하여 각 볼륨의 변경 사항을 활성화합니다.
+
다음 방법 중 하나를 사용하여 크기 조정 프로세스를 모니터링할 수 있습니다.

+
** 'volume quota resize' 명령어를 사용할 때 foreground' 파라미터를 추가하여 foreground에서 resize 작업을 실행할 수 있다. (기본적으로 작업은 백그라운드에서 실행됩니다.)
+
작업이 백그라운드에서 실행되면 job show 명령을 사용하여 진행 상황을 모니터링할 수 있습니다.

** 'volume quota show' 명령을 사용하여 크기 조정 상태를 모니터링할 수 있습니다.


. 'volume quota show-instance' 명령을 사용하여 크기를 조정하지 못한 할당량 규칙과 같은 크기 조정 오류를 확인합니다.
+
특히 파생 할당량이 아직 없는 타겟에 대해 명시적 할당량을 추가한 후 할당량의 크기를 조정할 때 발생하는 ""새 정의" 오류를 확인하십시오.

. "volume quota report" 명령을 사용하여 할당량 보고서를 표시하여 사용자 요구 사항에 맞게 적용된 할당량을 설정할 수 있습니다.

