---
permalink: volumes/configure-automatic-provide-space-when-full-task.html 
sidebar: sidebar 
keywords: configure, volumes, automatically, provide, more, space, when, full 
summary: FlexVol 볼륨이 꽉 차면 ONTAP는 다양한 방법을 사용하여 볼륨에 사용 가능한 공간을 자동으로 더 많이 제공할 수 있습니다. ONTAP에서 사용할 수 있는 방법과 애플리케이션 및 스토리지 아키텍처의 요구사항에 따라 사용할 순서를 선택할 수 있습니다. 
---
= 볼륨이 꽉 차면 자동으로 더 많은 공간을 제공하도록 볼륨을 구성합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
FlexVol 볼륨이 꽉 차면 ONTAP는 다양한 방법을 사용하여 볼륨에 사용 가능한 공간을 자동으로 더 많이 제공할 수 있습니다. ONTAP에서 사용할 수 있는 방법과 애플리케이션 및 스토리지 아키텍처의 요구사항에 따라 사용할 순서를 선택할 수 있습니다.

ONTAP는 다음 방법 중 하나 또는 모두를 사용하여 전체 볼륨에 더 많은 여유 공간을 자동으로 제공할 수 있습니다.

* 볼륨의 크기를 늘립니다(_자동 증가_).
+
이 방법은 Aggregate가 포함된 볼륨에 더 큰 볼륨을 지원할 수 있는 충분한 공간이 있는 경우에 유용합니다. 볼륨에 대한 최대 크기를 설정하도록 ONTAP를 구성할 수 있습니다. 증가값은 사용된 공간의 현재 양과 설정된 임계값을 기준으로 볼륨에 기록되는 데이터의 양을 기준으로 자동으로 트리거됩니다.

+
자동 확장 기능은 스냅샷 복사본 생성을 지원하도록 트리거되지 않습니다. 스냅샷 복사본을 생성하려고 할 때 공간이 부족하면 자동 확장 기능을 설정해도 스냅샷 복사본 생성이 실패합니다.

* 스냅샷 복사본, FlexClone 파일 또는 FlexClone LUN을 삭제합니다.
+
예를 들어, 클론 복제된 볼륨 또는 LUN의 스냅샷 복사본에 연결되지 않은 스냅샷 복사본을 자동으로 삭제하도록 ONTAP를 구성하거나, ONTAP에서 가장 오래되거나 최신 스냅샷 복사본인 첫 번째 복사본을 삭제할 스냅샷 복사본을 정의할 수 있습니다. 또한 ONTAP에서 스냅샷 복사본 삭제를 시작해야 하는 시기를 결정할 수 있습니다. 예를 들어, 볼륨이 거의 꽉 찼거나 볼륨의 스냅샷 예약 공간이 거의 꽉 찬 경우 등이 있습니다.



이 두 방법을 모두 사용하면 볼륨이 거의 꽉 찼을 때 ONTAP에서 먼저 시도하는 방법을 지정할 수 있습니다. 첫 번째 방법이 볼륨에 충분한 추가 공간을 제공하지 않으면 ONTAP는 다음 방법을 시도합니다.

기본적으로 ONTAP에서는 볼륨의 크기를 먼저 늘리려고 합니다. 대부분의 경우 스냅샷 복사본을 삭제할 때는 복원할 수 없기 때문에 기본 구성이 더 좋습니다. 그러나 볼륨 크기가 항상 커지는 것을 피해야 하는 경우, 볼륨의 크기를 늘리기 전에 ONTAP에서 스냅샷 복사본을 삭제하도록 구성할 수 있습니다.

.단계
. ONTAP가 꽉 차면 볼륨 크기를 늘리려고 시도하면 '볼륨 자동 크기 조정' 명령과 함께 '확대' 모드를 사용하여 볼륨에 대한 자동 확장 기능을 활성화합니다.
+
볼륨이 증가할수록 연결된 애그리게이트로부터 더 많은 여유 공간이 소모된다는 점을 기억하십시오. 필요할 때마다 볼륨의 확장 능력에 따라 관련 애그리게이트의 여유 공간을 모니터링하고 필요 시 추가 를 추가해야 합니다.

. ONTAP에서 볼륨이 가득 찰 때 스냅샷 복사본, FlexClone 파일 또는 FlexClone LUN을 삭제하려면 해당 개체 유형에 대해 자동 삭제를 활성화하십시오.
. 볼륨 자동 확장 기능과 하나 이상의 자동 삭제 기능을 모두 활성화한 경우 '-space-mgmt-try-first' 옵션과 함께 'volume modify' 명령을 사용하여 볼륨에 여유 공간을 제공하기 위해 ONTAP에서 사용해야 하는 첫 번째 방법을 선택합니다.
+
먼저 볼륨의 크기를 증가하도록 지정하려면(기본값) volume_grow를 사용합니다. 스냅샷 복사본 삭제를 먼저 지정하려면 Snap_delete를 사용합니다.


