---
permalink: volumes/create-volume-task.html 
sidebar: sidebar 
keywords: create, volume 
summary: 볼륨 생성 명령을 사용하여 볼륨을 생성하고 해당 접합 지점 및 기타 속성을 지정할 수 있습니다. 
---
= 볼륨을 생성합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
볼륨을 생성하고 "volume create" 명령을 사용하여 해당 접합 지점 및 기타 속성을 지정할 수 있습니다.

.이 작업에 대해
클라이언트에서 데이터를 사용할 수 있도록 하려면 볼륨에 _junction path_가 포함되어야 합니다. 새 볼륨을 생성할 때 접합 경로를 지정할 수 있습니다. 접합 경로를 지정하지 않고 볼륨을 생성하는 경우, "volume mount" 명령을 사용하여 SVM 네임스페이스에서 볼륨을 _mount_해야 합니다.

.시작하기 전에
* 새 볼륨용 SVM과 볼륨에 스토리지를 제공할 애그리게이트가 이미 존재해야 합니다.
* SVM에 관련 애그리게이트 목록이 있는 경우, 애그리게이트를 목록에 포함해야 합니다.
* ONTAP 9.13.1 부터는 용량 분석 및 활동 추적 기능이 활성화된 볼륨을 생성할 수 있습니다. 용량 또는 활동 추적을 활성화하려면 을 실행합니다 `volume create` 명령을 사용합니다 `-analytics-state` 또는 `-activity-tracking-state` 를 로 설정합니다 `on`.
+
용량 분석 및 활동 추적에 대한 자세한 내용은 을 참조하십시오 https://docs.netapp.com/us-en/ontap/task_nas_file_system_analytics_enable.html["파일 시스템 분석 설정"].



.단계
. 볼륨 생성:
+
`volume create -vserver _svm_name_ -volume _volume_name_ -aggregate _aggregate_name_ -size {integer[KB|MB|GB|TB|PB]} -security-style {ntfs|unix|mixed} -user _user_name_or_number_ -group _group_name_or_number_ -junction-path _junction_path_ [-policy _export_policy_name_]`

+
보안스타일, 사용자 그룹, 교차경로, 정책 옵션은 NAS 네임스페이스에만 사용됩니다.

+
'-junction-path'의 선택 항목은 다음과 같습니다.

+
** 루트 바로 아래, 예: '/new_vol'
+
새 볼륨을 생성하고 SVM 루트 볼륨에 직접 마운트하도록 지정할 수 있습니다.

** 기존 디렉토리 아래에 '/existing_dir/new_vol' 등이 있습니다
+
새 볼륨을 생성하고 기존 계층 구조에서 기존 볼륨에 마운트하도록 지정할 수 있습니다. 이 볼륨은 디렉토리로 표시됩니다.



+
새 볼륨 아래의 새 계층 구조에서 "/new_dir/new_vol"과 같은 새 디렉토리에 볼륨을 생성하려면 먼저 SVM 루트 볼륨에 대한 분기인 새 상위 볼륨을 생성해야 합니다. 그런 다음 새 상위 볼륨(새 디렉토리)의 접합 경로에 새 하위 볼륨을 생성합니다.

. 볼륨이 원하는 접합 지점으로 생성되었는지 확인합니다.
+
`volume show -vserver _svm_name_ -volume _volume_name_ -junction`



.예
다음 명령을 실행하면 SVM에 user1이라는 새 볼륨이 생성됩니다 `vs1.example.com` 집계 `aggr1`. 새 볼륨은 에서 사용할 수 있습니다 `/users`. 볼륨의 크기는 750GB이고 볼륨 유형은 볼륨 유형입니다(기본값).

[listing]
----
cluster1::> volume create -vserver vs1.example.com -volume users1 -aggregate aggr1 -size 750g -junction-path /users
[Job 1642] Job succeeded: Successful

cluster1::> volume show -vserver vs1.example.com -volume users1 -junction
                          Junction                 Junction
Vserver           Volume  Active   Junction Path   Path Source
----------------- ------- -------- --------------- -----------
vs1.example.com   users1  true     /users          RW_volume
----
다음 명령을 실행하면 SVM의 ""home4" vs1.example.com`""와 애그리게이트 ""aggr1""에 새 볼륨이 생성됩니다. VS1 SVM은 이름 공간에 /ENG/ 디렉토리가 이미 있으며, '/ENG/' 네임스페이스의 홈 디렉토리가 되는 '/ENG/HOME'에서 새 볼륨을 사용할 수 있습니다. 볼륨 크기는 750GB이고 볼륨 보장은 볼륨 유형입니다(기본값).

[listing]
----
cluster1::> volume create -vserver vs1.example.com -volume home4 -aggregate aggr1 -size 750g -junction-path /eng/home
[Job 1642] Job succeeded: Successful

cluster1::> volume show -vserver vs1.example.com -volume home4 -junction
                         Junction                 Junction
Vserver          Volume  Active   Junction Path   Path Source
---------------- ------- -------- --------------- -----------
vs1.example.com  home4   true     /eng/home       RW_volume
----