---
permalink: volumes/create-flexclone-snapmirror-concept.html 
sidebar: sidebar 
keywords: considerations, creating, flexclone volume, from snapmirror, source, destination, volume, flexclone, snapmirror, future 
summary: 기존 SnapMirror 관계에서 소스 또는 타겟 볼륨에서 FlexClone 볼륨을 생성할 수 있지만, 그렇게 할 경우 향후 SnapMirror 복제 작업에 영향을 미칠 수 있습니다. 
---
= SnapMirror 소스 또는 타겟 볼륨에서 FlexClone 볼륨을 생성할 때의 고려 사항
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
기존 볼륨 SnapMirror 관계의 소스 또는 타겟 볼륨에서 FlexClone 볼륨을 생성할 수 있습니다. 그러나 이렇게 하면 이후의 SnapMirror 복제 작업이 성공적으로 완료되지 못할 수 있습니다.

FlexClone 볼륨을 생성할 때 SnapMirror에서 사용하는 스냅샷 복사본을 잠글 수 있으므로 복제가 작동하지 않을 수 있습니다. 이 경우 SnapMirror는 FlexClone 볼륨이 제거되거나 부모로부터 분리될 때까지 대상 볼륨에 대한 복제를 중지합니다. 이 문제를 해결할 수 있는 두 가지 옵션이 있습니다.

* FlexClone 볼륨이 일시적으로 필요하고 SnapMirror 복제가 일시적으로 중단될 수 있는 경우, FlexClone 볼륨을 생성하여 이를 삭제하거나 상위 볼륨에서 분할할 수 있습니다.
+
FlexClone 볼륨이 삭제되거나 부모에서 분할될 때 SnapMirror 복제가 정상적으로 계속됩니다.

* SnapMirror 복제가 일시적으로 중단되는 것이 허용되지 않는 경우 SnapMirror 소스 볼륨에서 스냅샷 복사본을 생성한 다음 해당 스냅샷 복사본을 사용하여 FlexClone 볼륨을 생성할 수 있습니다. 타겟 볼륨에서 FlexClone 볼륨을 생성하는 경우 해당 스냅샷 복사본이 SnapMirror 타겟 볼륨으로 복제할 때까지 기다려야 합니다.
+
SnapMirror 소스 볼륨에서 스냅샷 복사본을 생성하는 이 방법을 사용하면 SnapMirror에서 사용 중인 스냅샷 복사본을 잠그지 않고도 클론을 생성할 수 있습니다.


