---
permalink: volumes/create-flexclone-task.html 
sidebar: sidebar 
keywords: create, flexclone volume, flexclone, flexgroup, snapmirror, volume 
summary: SnapMirror 타겟 볼륨 또는 SnapVault 2차 볼륨인 상위 FlexVol 볼륨에서 데이터 보호 FlexClone 볼륨을 생성할 수 있습니다. 
---
= FlexClone 볼륨을 생성합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapMirror 타겟 볼륨 또는 SnapVault 2차 볼륨인 상위 FlexVol 볼륨에서 데이터 보호 FlexClone 볼륨을 생성할 수 있습니다. ONTAP 9.7부터 FlexGroup 볼륨으로부터 FlexClone 볼륨을 생성할 수 있습니다. FlexClone 볼륨을 생성한 후에는 FlexClone 볼륨이 있는 동안에는 상위 볼륨을 삭제할 수 없습니다.

.시작하기 전에
* FlexClone 라이센스가 클러스터에 설치되어 있어야 합니다. 이 라이센스는 에 포함되어 있습니다 link:https://docs.netapp.com/us-en/ontap/system-admin/manage-licenses-concept.html#licenses-included-with-ontap-one["ONTAP 1 을 참조하십시오"].
* 복제할 볼륨이 온라인 상태여야 합니다.



NOTE: 볼륨을 다른 SVM에서 FlexClone 볼륨으로 클론 복제하는 것은 MetroCluster 구성에서 지원되지 않습니다.



== FlexVol 또는 FlexGroup의 FlexClone 볼륨을 생성합니다

.단계
. FlexClone 볼륨 생성:
+
'볼륨 클론 생성'

+

NOTE: 읽기-쓰기 상위 볼륨에서 읽기-쓰기 FlexClone 볼륨을 생성하는 동안에는 기본 스냅샷 복사본을 지정할 필요가 없습니다. 클론의 기본 스냅샷 복사본으로 사용될 특정 스냅샷 복사본의 이름을 지정하지 않은 경우 ONTAP에서 스냅샷 복사본을 생성합니다. 상위 볼륨이 데이터 보호 볼륨일 때 FlexClone 볼륨을 생성하기 위한 기본 스냅샷 복사본을 지정해야 합니다.



.예
* 다음 명령을 실행하면 상위 볼륨 vol1에서 읽기-쓰기 FlexClone 볼륨 vol1_clone이 생성됩니다.
+
'볼륨 클론 생성 - vserver vs0-FlexClone vol1_clone-type rw-parent-volume vol1'

* 다음 명령을 실행하면 기본 스냅샷 복사본 snap1을 사용하여 상위 볼륨 DP_vol에서 데이터 보호 FlexClone 볼륨 vol_DP_clone을 생성합니다.
+
'볼륨 클론 생성 - vserver vs1-FlexClone vol_DP_clone-type DP-parent-volume DP_vol-parent-snap1'





== 모든 SnapLock 유형의 FlexClone을 생성합니다

ONTAP 9.13.1 부터는 세 가지 SnapLock 유형 중 하나를 지정할 수 있습니다. `compliance`, `enterprise`, `non-snaplock`, RW 볼륨의 FlexClone을 만들 때. 기본적으로 FlexClone 볼륨은 상위 볼륨과 동일한 SnapLock 유형으로 생성됩니다. 그러나 을 사용하여 기본값을 재정의할 수 있습니다 `snaplock-type` 옵션을 사용하여 FlexClone 볼륨을 생성할 수 있습니다.

를 사용합니다 `non-snaplock` 매개 변수 `snaplock-type` SnapLock 상위 볼륨에서 비 SnapLock 유형의 FlexClone 볼륨을 생성하여 필요한 경우 데이터를 다시 온라인 상태로 전환하는 더 빠른 방법을 제공할 수 있습니다.

에 대해 자세히 알아보십시오 link:https://docs.netapp.com/us-en/ontap/snaplock/index.html["SnapLock"].

.시작하기 전에
SnapLock 유형이 상위 볼륨과 다른 경우 다음 FlexClone 볼륨 제한에 대해 알고 있어야 합니다.

* RW 유형의 클론만 지원됩니다. SnapLock 유형이 상위 볼륨과 다른 DP 유형의 클론은 지원되지 않습니다.
* SnapLock 볼륨이 LUN을 지원하지 않으므로 SnapLock 유형 옵션을 '비 SnapLock' 이외의 값으로 설정하여 LUN이 있는 볼륨을 복제할 수 없습니다.
* SnapLock 규정 준수 볼륨이 MetroCluster 미러링된 애그리게이트에서 지원되지 않으므로 MetroCluster 미러링된 Aggregate의 볼륨은 Compliance SnapLock 유형으로 복제할 수 없습니다.
* 법적 증거 자료 보관 기능이 있는 SnapLock 준수 볼륨은 다른 SnapLock 유형으로 복제할 수 없습니다. Legal-Hold는 SnapLock 준수 볼륨에서만 지원됩니다.
* SVM DR은 SnapLock 볼륨을 지원하지 않습니다. SVM DR 관계의 일부인 SVM의 볼륨에서 SnapLock 클론을 생성하려고 하면 실패합니다.
* FabricPool 모범 사례에서는 클론이 상위 항목과 같은 계층화 정책을 유지할 것을 권장합니다. 하지만 FabricPool 지원 볼륨의 SnapLock 규정 준수 클론은 상위 볼륨과 동일한 계층화 정책을 가질 수 없습니다. 계층화 정책을 로 설정해야 합니다 `none`. 이외의 계층화 정책을 사용하는 상위 항목에서 SnapLock 규정 준수 클론을 생성하려고 합니다 `none` 실패할 것입니다.


.단계
. SnapLock 유형으로 FlexClone 볼륨 생성: `volume clone create -vserver _svm_name_ -flexclone _flexclone_name_ -type RW [ -snaplock-type {non-snaplock|compliance|enterprise} ]`
+
예:

+
[listing]
----
> volume clone create -vserver vs0 -flexclone vol1_clone -type RW -snaplock-type enterprise -parent-volume vol1
----

