---
permalink: volumes/default-quotas-concept.html 
sidebar: sidebar 
keywords: default quotas, quotas, quota, default 
summary: 기본 할당량을 사용하여 지정된 할당량 유형의 모든 인스턴스에 할당량을 적용할 수 있습니다. 기본 할당량을 사용하면 할당량을 쉽게 수정할 수도 있습니다. 
---
= 기본 할당량의 작동 방식
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
기본 할당량을 사용하여 지정된 할당량 유형의 모든 인스턴스에 할당량을 적용할 수 있습니다. 예를 들어, 기본 사용자 할당량은 지정된 FlexVol 볼륨 또는 qtree의 시스템 모든 사용자에게 영향을 미칩니다. 또한 기본 할당량을 통해 할당량을 쉽게 수정할 수 있습니다.

기본 할당량을 사용하면 각 타겟에 대해 별도의 할당량을 생성하지 않고 대규모 할당량 타겟 세트에 제한을 자동으로 적용할 수 있습니다. 예를 들어 대부분의 사용자를 10GB의 디스크 공간으로 제한하려면 각 사용자에 대한 할당량을 생성하는 대신 10GB의 디스크 공간으로 기본 사용자 할당량을 지정할 수 있습니다. 다른 제한을 적용할 특정 사용자가 있는 경우 해당 사용자에 대해 명시적 할당량을 생성할 수 있습니다. (명시적 할당량 -- 특정 타겟 또는 타겟 목록이 있는 할당량 -- 기본 할당량을 재정의합니다.)

또한 기본 할당량을 사용하면 할당량 변경 사항을 적용하려는 경우 다시 초기화하는 대신 크기 조정을 사용할 수 있습니다. 예를 들어 기본 사용자 할당량이 이미 있는 볼륨에 명시적 사용자 할당량을 추가하는 경우 크기를 조정하여 새 할당량을 활성화할 수 있습니다.

기본 할당량은 세 가지 유형의 할당량 대상(사용자, 그룹 및 qtree)에 모두 적용될 수 있습니다.

기본 할당량에 지정된 제한이 없을 필요는 없습니다. 기본 할당량은 추적 할당량일 수 있습니다.

할당량은 컨텍스트에 따라 빈 문자열("") 또는 별표(*)로 표시됩니다.

* 'volume quota policy rule create' 명령을 사용하여 할당량을 생성할 때 '-target' 매개 변수를 빈 문자열("")로 설정하면 기본 할당량이 생성됩니다.
* 'volume quota policy rule create' 명령에서 '-qtree' 매개 변수는 할당량 규칙이 적용되는 qtree의 이름을 지정합니다. 트리 유형 규칙에는 이 매개 변수를 사용할 수 없습니다. 볼륨 레벨의 사용자 또는 그룹 유형 규칙의 경우 이 매개 변수에 ""가 포함되어야 합니다.
* 'volume quota policy rule show' 명령의 출력에서 기본 할당량이 빈 문자열("")과 함께 타겟으로 표시됩니다.
* 'volume quota report' 명령의 출력에서 기본 할당량은 ID 및 할당량 지정자로 별표(*)와 함께 표시됩니다.




== 기본 사용자 할당량의 예

다음 할당량 규칙은 기본 사용자 할당량을 사용하여 vol1의 각 사용자에 50MB 제한을 적용합니다.

[listing]
----
cluster1::> volume quota policy rule create -vserver vs0 -volume vol1 -policy-name default -type user -target "" -qtree "" -disk-limit 50m

cluster1::> volume quota policy rule show -vserver vs0 -volume vol1

Vserver: vs0               Policy: default           Volume: vol1
                                               Soft             Soft
                         User         Disk     Disk   Files    Files
Type   Target    Qtree   Mapping     Limit    Limit   Limit    Limit  Threshold
-----  --------  ------- -------  --------  -------  ------  -------  ---------
user   ""        ""      off          50MB        -       -        -          -
----
시스템의 사용자가 사용자의 데이터가 vol1에서 50MB 이상(예: 편집기에서 파일에 쓰기)을 이용하도록 하는 명령을 입력하면 명령이 실패합니다.
