---
permalink: volumes/default-user-group-quotas-derived-concept.html 
sidebar: sidebar 
keywords: how, default, user, group quotas, create, derived, quotas 
summary: 기본 사용자 또는 그룹 할당량을 생성하면 동일한 레벨의 파일을 소유한 모든 사용자 또는 그룹에 대해 해당 파생 사용자 또는 그룹 할당량이 자동으로 생성됩니다. 
---
= 기본 사용자 및 그룹 할당량이 파생 할당량을 생성하는 방법
:icons: font
:imagesdir: ../media/


[role="lead"]
기본 사용자 또는 그룹 할당량을 생성하면 동일한 레벨의 파일을 소유한 모든 사용자 또는 그룹에 대해 해당 파생 사용자 또는 그룹 할당량이 자동으로 생성됩니다.

파생된 사용자 및 그룹 할당량은 다음과 같은 방식으로 생성됩니다.

* FlexVol 볼륨의 기본 사용자 할당량은 볼륨의 어느 곳에서든 파일을 소유하는 모든 사용자에 대해 파생된 사용자 할당량을 생성합니다.
* qtree의 기본 사용자 할당량은 qtree의 파일을 소유한 모든 사용자에 대해 파생 사용자 할당량을 생성합니다.
* FlexVol 볼륨의 기본 그룹 할당량은 볼륨의 어느 곳에서든 파일을 소유하는 모든 그룹에 대해 파생된 그룹 할당량을 생성합니다.
* qtree의 기본 그룹 할당량은 qtree에 있는 파일을 소유한 모든 그룹에 대해 파생 그룹 할당량을 생성합니다.


사용자 또는 그룹이 기본 사용자 또는 그룹 할당량 수준의 파일을 소유하지 않으면 사용자 또는 그룹에 대해 파생 할당량이 생성되지 않습니다. 예를 들어, qtree proj1에 대해 기본 사용자 할당량이 생성되고 사용자 jsmith가 다른 qtree에 있는 파일을 소유하는 경우 jsmith에 대해 파생된 사용자 할당량이 생성되지 않습니다.

파생 할당량은 제한 및 사용자 매핑을 포함하여 기본 할당량과 동일한 설정을 가집니다. 예를 들어 기본 사용자 할당량에 50MB 디스크 제한이 있고 사용자 매핑이 설정되어 있는 경우 결과 파생 할당량에도 50MB 디스크 제한이 있고 사용자 매핑이 설정되어 있습니다.

그러나 세 가지 특수 사용자 및 그룹에 대한 파생 할당량에는 제한이 없습니다. 다음 사용자 및 그룹이 기본 사용자 또는 그룹 할당량 수준에서 파일을 소유하는 경우 기본 사용자 또는 그룹 할당량과 동일한 사용자 매핑 설정을 사용하여 파생 할당량이 생성되지만 할당량 추적만 가능합니다(제한 없음).

* Unix 루트 사용자(UID 0)
* UNIX 루트 그룹(GID 0)
* Windows BUILTIN\Administrators 그룹입니다
+
Windows 그룹의 할당량은 사용자 할당량으로 추적되므로 이 그룹의 파생 할당량은 기본 그룹 할당량이 아닌 기본 사용자 할당량에서 파생된 사용자 할당량입니다.



루트, jsmith, bob-own 파일 등 세 명의 사용자가 있는 볼륨이 있고 볼륨에 기본 사용자 할당량을 생성하면 ONTAP는 자동으로 세 개의 파생 사용자 할당량을 생성합니다. 따라서 볼륨에 대해 할당량을 다시 초기화하면 할당량 보고서에 네 개의 새 할당량이 나타납니다.

[listing]
----
cluster1::> volume quota report
  Vserver: vs1
                                     ----Disk----  ----Files-----   Quota
Volume   Tree      Type    ID        Used  Limit    Used   Limit   Specifier
-------  --------  ------  -------  -----  -----  ------  ------   ---------
vol1               user    *           0B   50MB       0       -   *
vol1               user    root        5B      -       1       -
vol1               user    jsmith     30B   50MB      10       -   *
vol1               user    bob        40B   50MB      15       -   *
4 entries were displayed.
----
첫 번째 새 줄은 사용자가 생성한 기본 사용자 할당량이며, 이 할당량은 별표(*)를 ID로 식별할 수 있습니다. 다른 새로운 행은 파생된 사용자 할당량입니다. jsmith 및 bob의 파생 할당량은 기본 할당량과 50MB 디스크 제한이 동일합니다. 루트 사용자의 파생 할당량은 제한 없는 추적 할당량입니다.
