---
permalink: volumes/delete-snapshot-copies-automatic-task.html 
sidebar: sidebar 
keywords: delete, snapshot, copies, automatically, flexclone luns, automatic, lun, luns 
summary: 스냅샷 및 FlexClone LUN을 자동으로 삭제하는 정책을 정의하여 공간 활용률을 관리할 수 있습니다. 
---
= 공간을 관리하기 위해 자동 스냅샷 및 LUN 삭제를 활성화합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
스냅샷 및 FlexClone LUN을 자동으로 삭제하는 정책을 정의하고 설정할 수 있습니다. 스냅샷 및 FlexClone LUN을 자동으로 삭제하면 공간 활용도를 관리하는 데 도움이 됩니다.

.이 작업에 대해
읽기-쓰기 볼륨의 스냅숏과 읽기-쓰기 상위 볼륨의 FlexClone LUN을 자동으로 삭제할 수 있습니다. 읽기 전용 볼륨(예: SnapMirror 대상 볼륨)에서 스냅샷 자동 삭제를 설정할 수 없습니다.

.단계
. 명령을 사용하여 스냅샷을 자동으로 삭제하는 정책을 정의하고 `volume snapshot autodelete modify` 설정합니다.
+
이 명령으로 요구사항에 맞는 정책을 정의하는 데 사용할 수 있는 매개 변수에 대한 자세한 내용은 '볼륨 스냅샷 자동 삭제 수정' man 페이지를 참조하십시오.

+
다음 명령을 실행하면 스냅샷을 자동으로 삭제할 수 있고 vs0.example.com SVM(스토리지 가상 머신)의 일부인 vol3 볼륨에 대한 트리거를 로 설정합니다 `snap_reserve`.

+
[listing]
----
cluster1::> volume snapshot autodelete modify -vserver vs0.example.com
-volume vol3 -enabled true -trigger snap_reserve
----
+
다음 명령을 실행하면 vs0.example.com SVM(스토리지 가상 머신)의 일부인 vol3 볼륨에 대해 자동 삭제하도록 표시된 FlexClone LUN과 스냅샷의 자동 삭제가 활성화됩니다.

+
[listing]
----
cluster1::> volume snapshot autodelete modify -vserver vs0.example.com
-volume vol3 -enabled true -trigger volume -commitment try -delete-order
oldest_first -destroy-list lun_clone,file_clone
----
+
[NOTE]
====
애그리게이트 레벨 스냅샷은 볼륨 레벨 스냅샷과 다르게 작동하며 ONTAP을 통해 자동으로 관리됩니다. 애그리게이트 스냅샷을 삭제하는 옵션은 항상 활성화되어 공간 활용률을 관리하는 데 도움이 됩니다.

애그리게이트에 대해 트리거 매개 변수가 (으)로 설정된 `snap_reserve` 경우 예약된 공간이 임계값 용량을 넘어설 때까지 스냅샷이 유지됩니다. 따라서 trigger 매개 변수가 로 설정되지 않은 경우에도 `snap_reserve` 이러한 스냅샷이 자동으로 삭제되기 때문에 명령에서 스냅샷 복사본이 사용하는 공간이 로 `0` 나열됩니다. 또한 애그리게이트에서 스냅샷이 사용하는 공간은 사용 가능한 공간으로 간주되며 명령의 가용 공간 매개 변수에 포함됩니다.

====

