---
permalink: volumes/derived-quotas-concept.html 
sidebar: sidebar 
keywords: how, derived, quotas, work 
summary: '명시적 할당량(특정 대상을 가진 할당량)이 아닌 기본 할당량의 결과로 적용되는 할당량을 파생 할당량이라고 합니다.' 
---
= 파생 할당량의 작동 방식
:icons: font
:imagesdir: ../media/


[role="lead"]
명시적 할당량(특정 대상을 가진 할당량)이 아닌 기본 할당량의 결과로 적용되는 할당량을 _ 파생 할당량 _ 이라고 합니다.

파생된 할당량의 수와 위치는 할당량 유형에 따라 다릅니다.

* 볼륨의 기본 트리 할당량은 볼륨의 모든 qtree에 대해 파생된 트리 할당량을 생성합니다.
* 기본 사용자 또는 그룹 할당량은 동일한 레벨(볼륨 또는 qtree)의 파일을 소유한 모든 사용자 또는 그룹에 대해 파생된 사용자 또는 그룹 할당량을 생성합니다.
* 볼륨의 기본 사용자 또는 그룹 할당량은 트리 할당량도 있는 모든 qtree에 기본 사용자 또는 그룹 할당량을 생성합니다.


파생 할당량의 제한 및 사용자 매핑 포함 설정은 해당 기본 할당량의 설정과 동일합니다. 예를 들어, 볼륨에 20GB 디스크 제한이 있는 기본 트리 할당량은 볼륨의 qtree에서 20GB의 디스크 제한으로 유도된 트리 할당량을 생성합니다. 기본 할당량이 할당량 추적(제한 없음)인 경우 파생 할당량도 할당량을 추적합니다.

파생된 할당량을 보려면 할당량 보고서를 생성할 수 있습니다. 보고서에서 파생된 사용자 또는 그룹 할당량은 비어 있거나 별표(*)인 할당량 지정자로 표시됩니다. 그러나 파생된 트리 할당량에는 할당량 지정자가 있습니다. 파생 트리 할당량을 식별하려면 동일한 제한값을 가진 볼륨에서 기본 트리 할당량을 찾아야 합니다.

명시적 할당량은 다음과 같은 방식으로 파생 할당량과 상호 작용합니다.

* 동일한 타겟에 대해 명시적 할당량이 이미 있는 경우에는 파생 할당량이 생성되지 않습니다.
* 대상에 대한 명시적 할당량을 생성할 때 파생 할당량이 있는 경우 전체 할당량 초기화를 수행하지 않고 크기를 조정하여 명시적 할당량을 활성화할 수 있습니다.

