---
permalink: volumes/determine-space-usage-volume-aggregate-concept.html 
sidebar: sidebar 
keywords: determine, space usage, volume, aggregate 
summary: ONTAP를 사용하면 볼륨, 애그리게이트 내 볼륨 설치 공간 및 애그리게이트를 기준으로 공간 소비를 결정할 수 있습니다. 
---
= 볼륨 또는 애그리게이트의 공간 사용량을 확인합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
경우에 따라 ONTAP에서 기능을 사용하도록 설정하는 데 예상보다 많은 공간이 필요할 수 있습니다. ONTAP은 공간을 볼 수 있는 세 가지 관점, 즉 볼륨, 애그리게이트 내 볼륨 공간 및 애그리게이트의 공간을 제공하여 공간이 얼마나 소비되는지를 결정하도록 지원합니다.



== 공간 할당을 봅니다

볼륨, 애그리게이트 또는 둘 모두의 조합 내에 공간 소비나 공간이 부족하여 볼륨이 공간 부족 으로 인해 실행될 수 있습니다. 다양한 관점에서 공간 사용량을 기능 중심으로 분석함으로써 어떤 기능을 조정하거나 해제할지 또는 다른 작업을 수행해야 하는지(예: 집계 또는 볼륨 크기 증가) 평가할 수 있습니다.

다음과 같은 관점에서 공간 사용 세부 정보를 볼 수 있습니다.

* 볼륨의 공간 사용량입니다
+
이 관점은 스냅샷 복사본별 사용을 비롯하여 볼륨 내의 공간 사용에 대한 세부 정보를 제공합니다.

+
를 사용합니다 `volume show-space` 볼륨의 공간 사용량을 확인하는 명령입니다.

+
ONTAP 9.14.1부터, 를 포함한 볼륨에서 실행됩니다 xref:enable-temperature-sensitive-efficiency-concept.html[온도에 민감한 스토리지 효율성(TSSE)] Enabled(사용) - 에서 보고한 볼륨에서 사용된 공간의 크기입니다 `volume show-space -physical used` 명령에는 TSSE를 통해 실현된 공간 절약 효과가 포함됩니다.

* 애그리게이트 내 볼륨의 설치 공간
+
이 관점에서는 볼륨의 메타데이터를 포함하여 각 볼륨이 포함하는 애그리게이트에서 사용하는 공간의 양에 대한 자세한 정보를 제공합니다.

+
를 사용합니다 `volume show-footprint` 명령을 사용하여 애그리게이트와 함께 볼륨의 설치 공간을 확인합니다.

* 애그리게이트의 공간 사용
+
이 관점에는 애그리게이트에 포함된 모든 볼륨의 볼륨 설치 공간, 애그리게이트 스냅샷 복사본을 위해 예약된 공간 및 기타 애그리게이트 메타데이터의 합계가 포함됩니다.

+
WAFL는 애그리게이트 레벨의 메타데이터 및 성능을 위해 전체 디스크 공간의 10%를 예약합니다. Aggregate에서 볼륨을 유지 관리하는 데 사용되는 공간은 WAFL 예비 공간에서 나오며 변경할 수 없습니다.

+
ONTAP 9.12.1부터는 AFF 플랫폼 및 FAS500f 플랫폼에 대해 30TB 이상의 애그리게이트에 대한 WAFL 예비 공간이 10%에서 5%로 줄어듭니다.  ONTAP 9.14.1부터는 이 동일한 축소 기능이 모든 FAS 플랫폼의 애그리게이트에 적용되어 애그리게이트에서 사용 가능한 공간이 5% 더 많아집니다.

+
를 사용합니다 `storage aggregate show-space` 명령을 사용하여 애그리게이트의 공간 사용량을 확인합니다.



테이프 백업 및 중복 제거와 같은 특정 기능은 메타데이터의 공간을 볼륨과 애그리게이트에서 직접 사용합니다. 이러한 기능은 볼륨 및 볼륨 풋프린트의 관점에서 다양한 공간 사용을 보여줍니다.

.관련 정보
* link:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/Space_Usage["Knowledge Base 문서: 공간 사용"^]
* link:https://www.netapp.com/blog/free-up-storage-capacity-upgrade-ontap/["ONTAP 9.12.1로 업그레이드하여 스토리지 용량의 5%를 확보하십시오"^]




== 볼륨 메타데이터 및 데이터 메트릭 보고

일반적으로 여러 볼륨 공간 메트릭에서 메타데이터와 사용자 데이터라는 두 가지 메트릭의 조합으로 사용된 총 데이터를 보고했습니다. ONTAP 9.15.1부터 메타데이터와 사용자 데이터 메트릭이 별도로 보고됩니다. 이를 지원하기 위해 두 개의 새로운 메타데이터 카운터가 도입되었습니다.

* 총 메타데이터
+
이 카운터는 볼륨 내의 총 메타데이터 크기를 제공합니다. 애그리게이트 상주 볼륨 메타데이터는 포함되지 않습니다. 별도로 보고하면 사용자가 할당한 논리적 데이터를 확인하는 데 도움이 됩니다.

* 총 메타데이터 설치 공간
+
이 카운터는 볼륨 상주 메타데이터와 애그리게이트 상주 볼륨 메타데이터의 합계입니다. 애그리게이트 내 볼륨의 총 메타데이터 사용 공간을 제공합니다. 별도로 보고하면 사용자가 할당한 물리적 데이터를 확인하는 데 도움이 됩니다.



또한 메타데이터 구성 요소를 제거하고 사용자 데이터만 표시하도록 몇 개의 기존 카운터가 업데이트되었습니다.

* 사용자 데이터
* 볼륨 데이터 공간


이러한 변경 사항을 통해 사용자가 소비한 데이터를 보다 정확하게 볼 수 있습니다. 이를 통해 보다 정확한 비용 청구 결정을 내릴 수 있는 기능 등 여러 가지 이점을 얻을 수 있습니다.
