---
permalink: volumes/enable-inline-data-compaction-fas-systems-task.html 
sidebar: sidebar 
keywords: enable, inline, data, compaction, fas systems 
summary: 'WAFL 컴팩션 enable 노드 셸 명령을 사용하여 볼륨 또는 애그리게이트 레벨에서 Flash Pool(하이브리드) 애그리게이트 또는 HDD 애그리게이트가 포함된 FAS 시스템에서 인라인 데이터 컴팩션을 제어할 수 있습니다. FAS 시스템의 경우 데이터 컴팩션은 기본적으로 비활성화되어 있습니다.' 
---
= FAS 시스템에 대해 인라인 데이터 컴팩션을 사용하도록 설정합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
'볼륨 효율성' 클러스터 셸 명령을 사용하여 볼륨 또는 애그리게이트 레벨에서 Flash Pool(하이브리드) 애그리게이트 또는 HDD 애그리게이트가 포함된 FAS 시스템에서 인라인 데이터 컴팩션을 제어할 수 있습니다. FAS 시스템의 경우 데이터 컴팩션은 기본적으로 비활성화되어 있습니다.

.이 작업에 대해
애그리게이트 레벨에서 데이터 컴팩션을 사용하도록 설정하면 애그리게이트에서 볼륨 공간 보장이 생성된 새 볼륨에 대해 데이터 컴팩션이 활성화됩니다. HDD 애그리게이트의 볼륨에 데이터 컴팩션을 활성화하면 추가 CPU 리소스가 사용됩니다.

.단계
. 고급 권한 수준: + 'Set-Privilege advanced'로 변경합니다
. 원하는 노드에 대해 볼륨 및 애그리게이트의 데이터 컴팩션 상태를 확인합니다. + 'volume Efficiency show -volume_volume_name_'+
. 볼륨에 대해 데이터 컴팩션을 사용하도록 설정합니다. + 'volume Efficiency modify -volume_volume_name_-data-다짐 true'
+
[NOTE]
====
데이터 컴팩션이 애그리게이트 또는 볼륨에 대해 으로 설정된 경우 `false` 컴팩션이 실패합니다. 컴팩션을 사용하도록 설정하면 기존 데이터가 압축되지 않고 시스템에 대한 새로운 쓰기만 컴팩션됩니다. 이 `volume efficiency start` 명령에는 기존 데이터를 압축하는 방법에 대한 자세한 정보가 포함되어 있습니다(ONTAP 9.1 이상). + 자세한 내용은 를 https://docs.netapp.com/us-en/ontap-cli["ONTAP 명령 참조입니다"^]참조하십시오.

====
. 다짐 통계 'volume Efficiency show -volume_volume_name_'을 봅니다

