---
permalink: volumes/enable-logical-space-reporting-enforcement-task.html 
sidebar: sidebar 
keywords: enable, logical, space, reporting, enforcement 
summary: ONTAP 9.4부터 논리 공간 보고를 활성화합니다. 9.5부터 논리적 공간 적용 또는 보고 및 적용을 활성화합니다. 
---
= 논리적 공간 보고 및 적용을 설정합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9.4부터 논리 공간 보고를 활성화할 수 있습니다. 9.5부터 논리 공간 적용 또는 보고와 적용을 함께 사용할 수 있습니다.

.이 작업에 대해
개별 볼륨 레벨에서 논리적 공간 보고 및 적용을 활성화할 뿐만 아니라 기능을 지원하는 모든 볼륨에서 SVM 레벨에서 활성화할 수 있습니다. 전체 SVM에 대해 논리적 공간 기능을 활성화할 경우 개별 볼륨에 대해 LUN을 비활성화할 수도 있습니다.

ONTAP 9.8부터 SnapMirror 소스 볼륨에서 논리적 공간 리포팅을 활성화하면 전송 후에 타겟 볼륨에서 자동으로 활성화됩니다.

ONTAP 9.13.1 부터 SnapMirror 소스 볼륨에서 적용 옵션이 활성화된 경우, 타겟은 논리적 공간 소비를 보고하고 성능 적용을 존중하여 더 나은 용량 계획을 수립합니다.


NOTE: ONTAP 9.13.1 이전의 ONTAP 릴리즈를 실행 중인 경우 적용 설정이 SnapMirror 대상 볼륨으로 전송되지만 대상 볼륨은 적용을 지원하지 않는다는 점을 이해해야 합니다. 따라서 대상은 논리 공간 소비를 보고하지만 해당 적용을 존중하지 않습니다.

에 대해 자세히 link:../volumes/logical-space-reporting-enforcement-concept.html["논리적 공간 보고를 위한 ONTAP 릴리즈 지원"]알아보십시오.

.단계
다음 중 하나 이상을 활성화합니다.

* 볼륨에 대한 논리 공간 보고 활성화:
+
`volume modify -vserver _svm_name_ -volume _volume_name_ -size _volume_size_ -is-space-reporting-logical true`

* 볼륨에 대한 논리적 공간 적용 활성화:
+
`volume modify -vserver _svm_name_ -volume _volume_name_ -size _volume_size_ -is-space-enforcement-logical true`

* 볼륨에 대한 논리적 공간 보고 및 적용을 함께 활성화합니다.
+
`volume modify -vserver _svm_name_ -volume _volume_name_ -size _volume_size_ -is-space-reporting-logical true -is-space-enforcement-logical true`

* 새로운 SVM에 대한 논리적 공간 보고 또는 적용 지원
+
`+vserver create -vserver _svm_name_ -rootvolume root-_volume_name_ -rootvolume-security-style unix -data-services {desired-data-services} [-is-space-reporting-logical true] [-is-space-enforcement-logical true]+`

* 기존 SVM에 대해 논리 공간 보고 또는 적용 지원
+
`+vserver modify -vserver _svm_name_ {desired-data-services} [-is-space-reporting-logical true] [-is-space-enforcement-logical true]+`


