---
permalink: volumes/enable-data-compression-volume-task.html 
sidebar: sidebar 
keywords: enable, data compression, FlexVol, space, volume, volume efficiency modify 
summary: ' `volume efficiency modify`명령을 사용하여 데이터 압축을 활성화하고 FlexVol volume에 압축 유형을 할당하여 절약 공간을 확보합니다.' 
---
= 볼륨에 대해 데이터 압축을 설정합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
'볼륨 효율성 수정' 명령을 사용하여 FlexVol 볼륨의 데이터 압축을 활성화하여 공간을 절약할 수 있습니다. 기본 압축 유형을 사용하지 않으려면 볼륨에 압축 유형을 할당할 수도 있습니다.

.시작하기 전에
볼륨에 대해 중복 제거를 설정해야 합니다.

[NOTE]
====
* 중복 제거는 활성화만 필요하며 볼륨에서는 실행할 필요가 없습니다.
* 압축 스캐너는 AFF 플랫폼에 있는 볼륨의 기존 데이터를 압축하는 데 사용해야 합니다.


====
link:enable-deduplication-volume-task.html["볼륨에 대해 중복 제거를 설정합니다"]

.이 작업에 대해
* HDD 애그리게이트 및 Flash Pool 애그리게이트에서는 인라인 압축과 사후 처리 압축을 모두 활성화하거나 볼륨에 대해 사후 처리 압축만 활성화할 수 있습니다.
+
둘 다 설정하는 경우 인라인 압축을 활성화하기 전에 볼륨에 대해 사후 처리 압축을 활성화해야 합니다.

* AFF 플랫폼에서는 인라인 압축만 지원됩니다.
+
인라인 압축을 활성화하기 전에 볼륨에 대해 사후 처리 압축을 활성화해야 합니다. 그러나 후처리 압축은 AFF 플랫폼에서 지원되지 않으므로 사후 처리 압축은 해당 볼륨에 대해 발생하지 않으며 EMS 메시지가 생성되어 사후 처리 압축을 건너뛰었음을 알립니다.

* 온도에 민감한 스토리지 효율성은 ONTAP 9.8에 도입되었습니다. 이 기능을 사용하면 데이터가 핫 데이터인지 콜드 데이터인지에 따라 스토리지 효율성이 적용됩니다. 콜드 데이터의 경우 대용량 데이터 블록이 압축되며, 자주 덮어쓰는 핫 데이터의 경우 작은 데이터 블록이 압축되어 프로세스가 더 효율적입니다. 온도에 민감한 스토리지 효율성은 새로 생성된 씬 프로비저닝된 AFF 볼륨에서 자동으로 활성화됩니다.
* 압축 유형은 애그리게이트의 플랫폼을 기반으로 자동으로 할당됩니다.
+
[cols="2*"]
|===
| 플랫폼/애그리게이트 | 압축 유형입니다 


 a| 
AFF
 a| 
적응형 압축



 a| 
Flash Pool 애그리게이트로 전환 가능
 a| 
적응형 압축



 a| 
HDD 애그리게이트
 a| 
보조 압축

|===


.선택
* 기본 압축 유형을 사용하여 데이터 압축을 활성화하려면 '볼륨 효율성 수정' 명령을 사용하십시오.
+
다음 명령을 실행하면 SVM VS1 볼륨의 사후 처리 압축이 활성화됩니다.

+
'볼륨 효율성 수정 - vserver vs1-volume vola-compression TRUE'

+
다음 명령을 실행하면 SVM VS1 볼륨의 볼륨 VolA에서 사후 처리 및 인라인 압축이 모두 활성화됩니다.

+
'볼륨 효율성 수정 - vserver vs1-volume vola-compression true-inline-compression true'

* 고급 권한 수준에서 '볼륨 효율성 수정' 명령을 사용하여 특정 압축 유형의 데이터 압축을 활성화할 수 있습니다.
+
.. Set-Privilege advanced 명령을 사용하여 권한 수준을 Advanced로 변경합니다.
.. 'volume Efficiency modify' 명령을 사용하여 볼륨에 압축 유형을 할당합니다.
+
다음 명령은 사후 처리 압축을 활성화하고 SVM VS1 의 볼륨 볼에 적응형 압축 유형을 할당합니다.

+
'볼륨 효율성 수정 - vserver vs1-volume vola-compression true-compression-type adaptive'

+
다음 명령을 실행하면 사후 처리 및 인라인 압축이 모두 설정되고 적응형 압축 유형이 SVM VS1 볼륨의 VolA에 할당됩니다.

+
'볼륨 효율성 수정 - vserver vs1-volume vola-compression true-compression-type adaptive-inline-compression true'

.. 권한 수준을 admin으로 변경하려면 'Set-Privilege admin' 명령을 사용합니다.



