---
permalink: volumes/enable-temperature-sensitive-efficiency-concept.html 
sidebar: sidebar 
keywords: enable, temperature, sensitive, storage, efficiency, sequential packing 
summary: 온도에 민감한 스토리지 효율성은 ONTAP 9.8에 도입되었으며 새롭게 생성된 씬 프로비저닝된 AFF 볼륨에서 자동으로 활성화됩니다. 기존 AFF 볼륨 및 씬 프로비저닝된 비 AFF DP 볼륨에서 온도에 민감한 스토리지 효율성을 수동으로 활성화할 수 있습니다. 
---
= 온도에 민감한 스토리지 효율성 개요
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP는 볼륨의 데이터 액세스 빈도를 평가하고 해당 데이터에 적용되는 압축 수준에 해당 빈도를 매핑함으로써 온도에 민감한 스토리지 효율성의 이점을 제공합니다. 자주 액세스하지 않는 콜드 데이터의 경우 대용량 데이터 블록이 압축되고, 자주 액세스되고 덮어쓰는 핫 데이터의 경우 작은 데이터 블록이 압축되어 프로세스의 효율성이 높아집니다.

온도 감지 스토리지 효율성(TSSE)은 ONTAP 9.8에 도입되었으며 새로 생성된 씬 프로비저닝된 AFF 볼륨에서 자동으로 활성화됩니다. 기존 AFF 볼륨 및 씬 프로비저닝된 비 AFF DP 볼륨에서 온도에 민감한 스토리지 효율성을 활성화할 수 있습니다.

."기본" 및 "효율적인" 모드 도입
ONTAP 9.10.1부터 AFF 시스템에만 _default_와 _Efficient_라는 두 가지 볼륨 레벨 스토리지 효율성 모드가 도입되었습니다. 두 가지 모드에서는 파일 압축(기본값) 중에서 선택할 수 있습니다. 기본 모드는 새 AFF 볼륨을 생성할 때 기본 모드이고, 온도에 민감한 스토리지 효율성(효율성)으로 온도에 민감한 스토리지 효율성을 지원합니다. ONTAP 9.10.1 포함, link:https://docs.netapp.com/us-en/ontap/volumes/set-efficiency-mode-task.html["온도에 민감한 스토리지 효율성을 명시적으로 설정해야 합니다"] 자동 적응형 압축 활성화 하지만 AFF 플랫폼에서 데이터 컴팩션, 자동 중복제거 일정, 인라인 중복제거, 볼륨 간 인라인 중복제거, 볼륨 간 백그라운드 중복제거 등과 같은 기타 스토리지 효율성 기능은 기본 모드와 효율적인 모드 모두에서 기본적으로 사용됩니다.

FabricPool 지원 애그리게이트 및 모든 계층화 정책 유형에서 스토리지 효율성 모드(기본값 및 효율성)가 모두 지원됩니다.

.C-Series 플랫폼에서 온도에 민감한 스토리지 효율성을 지원합니다
온도에 민감한 스토리지 효율성은 AFF C 시리즈 플랫폼에서 기본적으로 활성화되어 있으며, 볼륨 이동 또는 대상에 다음 릴리스가 설치된 SnapMirror를 사용하여 비 TSSE 플랫폼에서 TSSE 지원 C 시리즈 플랫폼으로 볼륨을 마이그레이션할 때 활성화됩니다.

* ONTAP 9.12.1P4 이상
* ONTAP 9.13.1 이상


자세한 내용은 을 참조하십시오 link:https://docs.netapp.com/us-en/ontap/volumes/storage-efficiency-behavior-snapmirror-reference.html["볼륨 이동 및 SnapMirror 작업에 대한 스토리지 효율성 동작"].

하지만 기존 볼륨의 경우 온도에 민감한 스토리지 효율성이 자동으로 활성화되지 않습니다 link:https://docs.netapp.com/us-en/ontap/volumes/change-efficiency-mode-task.html["스토리지 효율성 모드를 수정합니다"] 수동으로 를 선택하여 효율적 모드로 변경합니다.


NOTE: 스토리지 효율성 모드를 효율적으로 변경한 후에는 다시 변경할 수 없습니다.

.인접한 물리적 블록을 순차적으로 압축하여 스토리지 효율성 향상
ONTAP 9.13.1 을 시작으로, 온도에 민감한 스토리지 효율성이 인접한 물리적 블록을 순차적으로 압축하여 스토리지 효율성을 더욱 향상합니다. 온도에 민감한 스토리지 효율성을 사용하는 볼륨은 시스템을 ONTAP 9.13.1 로 업그레이드할 때 자동으로 순차적 패킹을 지원합니다. 순차적 패킹이 활성화된 후에는 반드시 필요합니다 link:https://docs.netapp.com/us-en/ontap/volumes/run-efficiency-operations-manual-task.html["기존 데이터를 수동으로 다시 압축합니다"].



== 업그레이드 고려 사항

ONTAP 9.10.1 이상으로 업그레이드할 때 볼륨에 현재 활성화된 압축 유형을 기준으로 기존 볼륨에 스토리지 효율성 모드가 할당됩니다. 업그레이드하는 동안 압축이 활성화된 볼륨에 기본 모드가 할당되고, 온도에 민감한 스토리지 효율성을 활성화한 볼륨에 효율적인 모드가 할당됩니다. 압축이 사용되지 않을 경우 스토리지 효율성 모드는 빈 상태로 유지됩니다.
