---
permalink: volumes/explicit-quotas-concept.html 
sidebar: sidebar 
keywords: how to, use, explicit, quotas 
summary: 명시적 할당량을 사용하여 특정 할당량 타겟의 할당량을 지정하거나 특정 타겟의 기본 할당량을 재정의할 수 있습니다. 
---
= 명시적 할당량을 사용하는 방법
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
명시적 할당량을 사용하여 특정 할당량 타겟의 할당량을 지정하거나 특정 타겟의 기본 할당량을 재정의할 수 있습니다.

명시적 할당량은 특정 사용자, 그룹 또는 qtree에 대한 제한을 지정합니다. 명시적 할당량은 동일한 타겟에 대해 설정된 기본 할당량을 대체합니다.

파생된 사용자 할당량이 있는 사용자에 대해 명시적 사용자 할당량을 추가할 때는 기본 사용자 할당량으로 동일한 사용자 매핑 설정을 사용해야 합니다. 그렇지 않으면 할당량의 크기를 조정할 때 명시적 사용자 할당량이 새 할당량으로 간주되므로 거부됩니다.

명시적 할당량은 동일한 레벨(볼륨 또는 qtree)의 기본 할당량에만 영향을 줍니다. 예를 들어, qtree에 대한 명시적 사용자 할당량은 해당 qtree가 포함된 볼륨의 기본 사용자 할당량에 영향을 주지 않습니다. 그러나 qtree에 대한 명시적 사용자 할당량이 해당 qtree에 대한 기본 사용자 할당량보다 우선합니다(에 정의된 제한 대체).

다음 할당량 파일에는 vol1의 모든 사용자를 50MB로 제한하는 기본 사용자 할당량이 포함되어 있습니다. 그러나 jsmith 사용자 한 명은 명시적 할당량(굵은 글꼴로 표시됨)으로 인해 80MB의 공간이 허용됩니다.

[listing]
----
#Quota target type            disk  files  thold  sdisk  sfile
#-----------  ----            ----  -----  -----  -----  -----
*             user@/vol/vol1  50M
**jsmith      user@/vol/vol1  80M**
----
다음 할당량 항목은 4개의 ID로 표시되는 지정된 사용자를 vol1 볼륨에서 500MB의 디스크 공간 및 10,240개의 파일로 제한합니다.

[listing]
----
jsmith,corp\jsmith,engineering\”john smith”,
S-1-5-32-544   user@/vol/vol1         500M      10K
----
다음 할당량 항목을 사용하면 ENG1 그룹이 150MB의 디스크 공간과 /vol/vol2/proj1 qtree의 파일 수를 무제한으로 제한할 수 있습니다.

[listing]
----
eng1        group@/vol/vol2/proj1  150M
----
다음 할당량 항목은 vol2 볼륨에서 proj1 qtree를 750MB의 디스크 공간과 76,800개의 파일로 제한합니다.

[listing]
----
/vol/vol2/proj1   tree                750M      75K
----