---
permalink: volumes/flexvol-fullness-overallocation-alerts-concept.html 
sidebar: sidebar 
keywords: how, address, flexvol, volume, fullness, overallocation, alerts 
summary: ONTAP는 FlexVol 볼륨 공간이 부족할 때 EMS 메시지를 발행하므로 전체 볼륨에 더 많은 공간을 제공하여 수정 조치를 취할 수 있습니다. 
---
= FlexVol 볼륨 충만 및 초과 할당 경고를 해결합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP는 FlexVol 볼륨 공간이 부족할 때 EMS 메시지를 발행하므로 전체 볼륨에 더 많은 공간을 제공하여 수정 조치를 취할 수 있습니다. 알림의 유형과 해결 방법을 알면 데이터 가용성을 보장하는 데 도움이 됩니다.

볼륨이 _FULL_으로 설명되면 활성 파일 시스템(사용자 데이터)에서 사용할 수 있는 볼륨의 공간 백분율이 (구성 가능) 임계값 아래로 떨어졌다는 의미입니다. 볼륨이 _overallocated_가 되면 ONTAP에서 메타데이터에 사용하고 기본 데이터 액세스를 지원하는 데 사용하는 공간이 소진되었습니다. 경우에 따라 다른 목적으로 일반적으로 예약된 공간을 사용하여 볼륨 기능을 유지할 수 있지만, 공간 예약 또는 데이터 가용성이 위험할 수 있습니다.

초과 할당은 논리적 또는 물리적 할당일 수 있습니다. _논리적 초과 할당_은 공간 예약과 같은 향후 공간 약속을 지키기 위해 예약된 공간이 다른 용도로 사용되었음을 의미합니다. _physical overallocation_은 볼륨에서 사용할 물리적 블록이 부족함을 의미합니다. 이 상태의 볼륨은 쓰기를 거부하거나, 오프라인 상태가 되거나, 컨트롤러 중단을 일으킬 위험이 있습니다.

메타데이터에서 사용되거나 예약된 공간이 있기 때문에 볼륨에는 100% 이상의 공간이 부족할 수 있습니다. 그러나 100% 이상의 꽉 찬 볼륨은 초과 할당되거나 할당되지 않을 수 있습니다. qtree 레벨 및 볼륨 레벨 공유가 동일한 FlexVol 또는 SCVMM 풀에 있을 경우 qtree가 FlexVol 공유의 디렉토리로 표시됩니다. 따라서 실수로 삭제하지 않도록 주의해야 합니다.

다음 표는 볼륨 충만 및 초과 할당 알림, 문제 해결을 위해 취할 수 있는 조치 및 조치를 취하지 않을 경우의 위험에 대해 설명합니다.

[cols="6*"]
|===
| 경고 유형 | EMS 레벨 | 구성 가능? | 정의 | 해결 방법 | 조치를 취하지 않을 경우 위험이 있습니다 


 a| 
거의 꽉 찼습니다
 a| 
디버그
 a| 
예
 a| 
파일 시스템이 이 알림에 대해 설정된 임계값을 초과했습니다(기본값은 95%). 이 비율은 사용된 총합에서 스냅숏 예비 공간의 크기를 뺀 값입니다.
 a| 
* 볼륨 크기를 늘리는 중입니다
* 사용자 데이터 감소

 a| 
아직 쓰기 작업 또는 데이터 가용성에 대한 위험이 없습니다.



 a| 
가득 참
 a| 
디버그
 a| 
예
 a| 
파일 시스템이 이 알림에 대해 설정된 임계값을 초과했습니다(기본값은 98%). 이 비율은 사용된 총합에서 스냅숏 예비 공간의 크기를 뺀 값입니다.
 a| 
* 볼륨 크기를 늘리는 중입니다
* 사용자 데이터 감소

 a| 
아직 쓰기 작업 또는 데이터 가용성에 대한 위험이 없지만 쓰기 작업이 위험한 단계에 볼륨이 접근하고 있습니다.



 a| 
논리적으로 초과 할당됨
 a| 
SVC 오류입니다
 a| 
해당 없음
 a| 
파일 시스템이 꽉 찬 것 외에도 메타데이터에 사용된 볼륨의 공간이 소진되었습니다.
 a| 
* 볼륨 크기를 늘리는 중입니다
* 스냅샷 복사본 삭제
* 사용자 데이터 감소
* 파일 또는 LUN에 대한 공간 예약을 사용하지 않도록 설정합니다

 a| 
예약되지 않은 파일에 대한 쓰기 작업이 실패할 수 있습니다.



 a| 
물리적으로 초과 할당되었습니다
 a| 
노드 오류입니다
 a| 
해당 없음
 a| 
볼륨에 쓸 수 있는 물리적 블록이 부족하고 있습니다.
 a| 
* 볼륨 크기를 늘리는 중입니다
* 스냅샷 복사본 삭제
* 사용자 데이터 감소

 a| 
쓰기 작업이 위험에 처하고 데이터 가용성이 향상됩니다. 볼륨이 오프라인 상태가 될 수 있습니다.

|===
전체 백분율 상승 또는 하강 여부와 관계없이 볼륨에 대한 임계값을 초과할 때마다 EMS 메시지가 생성됩니다. 전체 볼륨 레벨이 임계값 아래로 떨어지면 'volume ok' EMS 메시지가 생성됩니다.
