---
permalink: volumes/flexvol-reclaim-free-space-autodelete-concept.html 
sidebar: sidebar 
keywords: how, flexvol, volume, reclaim, free, space, autodelete, setting 
summary: FlexVol 볼륨의 자동 삭제 설정을 사용하여 FlexClone 파일 및 FlexClone LUN을 자동으로 삭제할 수 있습니다. 자동 삭제를 사용하면 볼륨이 거의 꽉 찼을 때 볼륨에서 사용 가능한 타겟 공간을 재확보할 수 있습니다. 
---
= FlexVol 볼륨이 자동 삭제 설정을 통해 사용 가능한 공간을 재확보하는 방법 개요
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
FlexVol 볼륨의 자동 삭제 설정을 사용하여 FlexClone 파일 및 FlexClone LUN을 자동으로 삭제할 수 있습니다. 자동 삭제를 사용하면 볼륨이 거의 꽉 찼을 때 볼륨에서 사용 가능한 타겟 공간을 재확보할 수 있습니다.

볼륨의 사용 가능한 공간이 특정 임계값 아래로 감소할 경우 FlexClone 파일 및 FlexClone LUN 삭제를 자동으로 시작하도록 볼륨을 구성한 다음, 볼륨의 사용 가능한 타겟 공간이 회수될 때 클론 삭제를 자동으로 중지할 수 있습니다. 클론 자동 삭제를 시작하는 임계값을 지정할 수는 없지만, 클론을 삭제할 수 있는지 여부를 지정하고 볼륨에 사용할 수 있는 가용 공간의 타겟 크기를 지정할 수 있습니다.

볼륨의 사용 가능한 공간이 특정 임계값 아래로 감소하거나 다음 요구 사항 중 _both_가 충족되면 볼륨은 FlexClone 파일과 FlexClone LUN을 자동으로 삭제합니다.

* 자동 삭제 기능은 FlexClone 파일과 FlexClone LUN이 포함된 볼륨에 대해 활성화됩니다.
+
'volume snapshot Autodelete modify' 명령을 사용하여 FlexVol 볼륨에 대한 자동 삭제 기능을 설정할 수 있습니다. FlexClone 파일 및 FlexClone LUN을 자동으로 삭제하려면 볼륨에 대해 '-trigger' 매개 변수를 'volume' 또는 'snap_reserve'로 설정해야 합니다.

* FlexClone 파일 및 FlexClone LUN에 대해 자동 삭제 기능이 활성화됩니다.
+
'-Autodelete' 매개 변수와 함께 'file clone create' 명령을 사용하여 FlexClone 파일 또는 FlexClone LUN에 대한 자동 삭제를 활성화할 수 있습니다. 따라서 클론에 대한 자동 삭제를 사용하지 않도록 설정하고 다른 볼륨 설정이 클론 설정을 재정의하지 않도록 하여 특정 FlexClone 파일 및 FlexClone LUN을 보존할 수 있습니다.


