---
permalink: volumes/move-volume-concept.html 
sidebar: sidebar 
keywords: how, move, flexvol, volume, works 
summary: FlexVol 볼륨의 이동 방법을 알면 볼륨 이동이 서비스 수준 계약을 충족하는지 확인하고 볼륨 이동 프로세스에서 볼륨 이동이 어느 단계에 있는지 파악하는 데 도움이 됩니다. 
---
= FlexVol 볼륨 개요 이동
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
용량 활용률, 성능 향상, 서비스 수준 계약 충족을 위해 볼륨을 이동 또는 복사할 수 있습니다.

FlexVol 볼륨의 이동 방법을 알면 볼륨 이동이 서비스 수준 계약을 충족하는지 확인하고 볼륨 이동 프로세스에서 볼륨 이동이 어느 단계에 있는지 파악하는 데 도움이 됩니다.

FlexVol 볼륨은 동일한 SVM(스토리지 가상 머신) 내에서 하나의 애그리게이트 또는 노드에서 다른 애그리게이트로 이동됩니다. 볼륨 이동이 이동 중에 클라이언트 액세스를 방해하지 않습니다.

볼륨 이동에는 여러 단계가 있습니다.

* 대상 애그리게이트에 새 볼륨이 작성되고
* 원래 볼륨의 데이터가 새 볼륨으로 복사됩니다.
+
이 시간 동안 원래 볼륨은 온전하며 클라이언트가 액세스할 수 있습니다.

* 이동 프로세스가 끝나면 클라이언트 액세스가 일시적으로 차단됩니다.
+
이 시간 동안 시스템은 소스 볼륨에서 대상 볼륨으로 최종 복제를 수행하고 소스 볼륨과 대상 볼륨의 ID를 스왑하며 대상 볼륨을 소스 볼륨으로 변경합니다.

* 이동을 완료하면 시스템은 클라이언트 트래픽을 새 소스 볼륨으로 라우팅하고 클라이언트 액세스를 재개합니다.


클라이언트가 중단 및 시간 초과를 인지하기 전에 클라이언트 액세스가 차단되므로 이동이 클라이언트 액세스에 영향을 주지 않습니다. 클라이언트 액세스는 기본적으로 35초 동안 차단됩니다. 액세스가 거부된 시간에 볼륨 이동 작업을 완료할 수 없는 경우, 시스템은 볼륨 이동 작업의 이 마지막 단계를 중단하고 클라이언트 액세스를 허용합니다. 시스템은 기본적으로 최종 단계를 세 번 시도합니다. 세 번째 시도 후 시스템은 1시간을 기다린 후 최종 단계 시퀀스를 다시 시도합니다. 시스템은 볼륨 이동이 완료될 때까지 볼륨 이동 작업의 마지막 단계를 실행합니다.
