---
permalink: volumes/move-volume-task.html 
sidebar: sidebar 
keywords: move, volume 
summary: '스토리지 용량 불균형이 있다고 판단된 후 FlexVol 볼륨을 동일한 스토리지 가상 시스템(SVM) 내에서 다른 애그리게이트, 노드 또는 둘 모두로 이동하여 스토리지 용량의 균형을 조정할 수 있습니다.' 
---
= 볼륨을 이동합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
스토리지 용량 불균형이 있다고 판단된 후 FlexVol 볼륨을 동일한 스토리지 가상 시스템(SVM) 내에서 다른 애그리게이트, 노드 또는 둘 모두로 이동하여 스토리지 용량의 균형을 조정할 수 있습니다.

.이 작업에 대해
기본적으로 컷오버 작업이 30초 이내에 완료되지 않으면 다시 시도합니다. '-cutover-window' 및 '-cutover-action' 매개 변수를 사용하여 기본 동작을 조정할 수 있습니다. 두 매개 변수 모두 고급 권한 수준 액세스가 필요합니다. 자세한 내용은 볼륨 이동 시작 man 페이지를 참조하십시오.

.단계
. 데이터 보호 미러를 이동하고 미러 관계를 초기화하지 않은 경우 'napmirror initialize' 명령을 사용하여 미러 관계를 초기화합니다.
+
볼륨 중 하나를 이동하려면 먼저 데이터 보호 미러 관계를 초기화해야 합니다.

. 'volume move target-aggr show' 명령을 사용하여 볼륨을 이동할 수 있는 애그리게이트를 결정합니다.
+
선택하는 Aggregate는 볼륨에 충분한 공간을 가져야 합니다. 즉, 사용 가능한 용량이 이동 중인 볼륨보다 큽니다.

+
다음 예에서는 VS2 볼륨을 나열된 Aggregate 중 한 곳으로 이동할 수 있음을 보여 줍니다.

+
[listing]
----
cluster1::> volume move target-aggr show -vserver vs2 -volume user_max
Aggregate Name   Available Size   Storage Type
--------------   --------------   ------------
aggr2            467.9GB          hdd
node12a_aggr3    10.34GB          hdd
node12a_aggr2    10.36GB          hdd
node12a_aggr1    10.36GB          hdd
node12a_aggr4    10.36GB          hdd
5 entries were displayed.
----
. 'volume move start-perform-validation-only' 명령을 사용하여 유효성 검사를 실행하여 볼륨을 원하는 Aggregate로 이동할 수 있는지 확인합니다.
. 'volume move start' 명령을 사용하여 볼륨을 이동합니다.
+
다음 명령을 실행하면 VS2 SVM의 user_max 볼륨이 node12a_aggr3 애그리게이트로 이동합니다. 이동은 백그라운드 프로세스로 실행됩니다.

+
[listing]
----
cluster1::> volume move start -vserver vs2 -volume user_max
-destination-aggregate node12a_aggr3
----
. 'volume move show' 명령을 사용하여 볼륨 이동 작업의 상태를 확인합니다.
+
다음 예에서는 복제 단계를 완료하고 컷오버 단계에 있는 볼륨 이동 상태를 보여줍니다.

+
[listing]
----

cluster1::> volume move show
Vserver   Volume     State    Move Phase  Percent-Complete Time-To-Complete
--------- ---------- -------- ----------  ---------------- ----------------
vs2       user_max   healthy  cutover     -                -
----
+
볼륨 이동은 'volume move show' 명령 출력에 더 이상 나타나지 않으면 완료됩니다.


