---
permalink: volumes/move-between-secondary-adaptive-compression-task.html 
sidebar: sidebar 
keywords: move, secondary compression, adaptive compression 
summary: 데이터 읽기의 양에 따라 보조 압축과 적응형 압축 간에 전환할 수 있습니다. 시스템에서 대량의 랜덤 읽기가 수행되는 경우 적응형 압축이 더 높은 성능이 필요합니다. 2차 압축은 데이터를 순차적으로 쓸 때 더 높은 압축 절약 효과가 필요한 경우에 적합합니다. 
---
= 보조 압축과 적응형 압축 간에 이동
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
데이터 읽기의 양에 따라 보조 압축과 적응형 압축 간에 전환할 수 있습니다. 시스템에서 대량의 랜덤 읽기가 수행되는 경우 적응형 압축이 더 높은 성능이 필요합니다. 2차 압축은 데이터를 순차적으로 쓸 때 더 높은 압축 절약 효과가 필요한 경우에 적합합니다.

.이 작업에 대해
기본 압축 유형은 애그리게이트 및 플랫폼을 기반으로 선택됩니다.

.단계
. 볼륨에 대한 데이터 압축 해제:
+
볼륨 효율성 수정

+
다음 명령을 실행하면 볼륨 vol1에 대한 데이터 압축이 해제됩니다.

+
'볼륨 효율성 수정 - 압축 거짓 - 인라인 - 압축 잘못된 볼륨 vol1'

. 고급 권한 레벨로 변경:
+
세트 프리빌리지 고급

. 압축 데이터의 압축을 풉니다.
+
볼륨 효율성 실행 취소

+
다음 명령을 실행하면 볼륨 vol1에서 압축된 데이터가 압축 해제됩니다.

+
'볼륨 효율성 실행 취소 - vserver vs1-volume vol1-compression TRUE'

+
[NOTE]
====
압축 해제된 데이터를 수용할 수 있는 충분한 공간이 볼륨에 있는지 확인해야 합니다.

====
. 작업 상태가 IDLE인지 확인합니다.
+
볼륨 효율성 쇼

+
다음 명령을 실행하면 볼륨 vol1에 대한 효율성 작업의 상태가 표시됩니다.

+
'볼륨 효율성 표시 - vserver vs1-volume vol1'

. 데이터 압축을 사용하도록 설정한 다음 압축 유형을 설정합니다.
+
볼륨 효율성 수정

+
다음 명령을 실행하면 데이터 압축이 활성화되며 볼륨 vol1에 대한 보조 압축으로 압축 유형을 설정합니다.

+
'볼륨 효율성 수정 - vserver vs1-volume vol1-compression true-compression-type secondary'

+
[NOTE]
====
이 단계에서는 볼륨에 대한 보조 압축만 활성화합니다. 볼륨의 데이터는 압축되지 않습니다.

** AFF 시스템에서 기존 데이터를 압축하려면 백그라운드 압축 검사기를 실행해야 합니다.
** Flash Pool 애그리게이트 또는 HDD 애그리게이트에서 기존 데이터를 압축하려면 백그라운드 압축을 실행해야 합니다.


====
. 관리자 권한 레벨로 변경:
+
'Set-Privilege admin'입니다

. 선택 사항: 인라인 압축 사용:
+
볼륨 효율성 수정

+
다음 명령을 실행하면 볼륨 vol1에 대해 인라인 압축이 설정됩니다.

+
'볼륨 효율성 수정 - vserver vs1-volume vol1-inline-compression TRUE'


