---
permalink: volumes/quotas-activated-concept.html 
sidebar: sidebar 
keywords: quotas, how quotas are activated, quota activation 
summary: 새 할당량 및 기존 할당량에 대한 변경 사항을 활성화해야 효과를 적용할 수 있습니다. 활성화는 볼륨 레벨에서 수행됩니다. 할당량 활성화의 작동 방식을 알면 업무 중단을 최소화하면서 할당량을 관리하는 데 도움이 됩니다. 
---
= 할당량 활성화 방법에 대한 개요입니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
새 할당량 및 기존 할당량에 대한 변경 사항을 활성화해야 효과를 적용할 수 있습니다. 활성화는 볼륨 레벨에서 수행됩니다. 할당량 활성화의 작동 방식을 알면 업무 중단을 최소화하면서 할당량을 관리하는 데 도움이 됩니다.

할당량은 _initializing_(설정 중) 또는 _refizing_에 의해 활성화됩니다. 할당량을 해제했다가 다시 설정하는 것을 다시 초기화 중이라고 합니다.

활성화 프로세스의 길이와 할당량 적용에 미치는 영향은 활성화 유형에 따라 달라집니다.

* 초기화 프로세스에는 두 가지 부분, 즉 "할당량" 작업과 볼륨의 전체 파일 시스템에 대한 할당량 검사가 포함됩니다. 할당량 설정 작업이 성공적으로 완료된 후 검사가 시작됩니다. 할당량 검사에는 시간이 걸릴 수 있습니다. 볼륨에 파일이 많을수록 더 오래 걸립니다. 검사가 완료될 때까지 할당량 활성화가 완료되지 않으며 할당량이 적용되지 않습니다.
* 크기 조정 프로세스에는 만 포함됩니다 `quota resize` 작업. 크기 조정에는 할당량 검사가 필요하지 않으므로 할당량 초기화보다 시간이 적게 걸립니다. 크기 조정 프로세스 중에 할당량이 계속 적용됩니다.


기본적으로 "할당량 설정" 및 "할당량 크기 조정" 작업은 백그라운드에서 실행되므로 다른 명령을 동시에 사용할 수 있습니다.

활성화 프로세스의 오류 및 경고가 이벤트 관리 시스템으로 전송됩니다. 볼륨 할당량 설정 또는 볼륨 할당량 크기 조정 명령과 함께 '-foreground' 매개 변수를 사용하면 작업이 완료될 때까지 명령이 반환되지 않으므로 스크립트에서 다시 초기화하는 경우에 유용합니다. 나중에 오류와 경고를 표시하려면 '-instance' 매개 변수와 함께 'volume quota show' 명령을 사용할 수 있습니다.

할당량 활성화는 중지 및 재부팅 후에도 유지됩니다. 할당량 활성화 프로세스는 스토리지 시스템 데이터의 가용성에 영향을 주지 않습니다.
