---
permalink: volumes/quotas-applied-concept.html 
sidebar: sidebar 
keywords: quotas, how quotas are applied 
summary: 할당량이 적용되는 방식을 이해하면 할당량을 올바르게 구성하고 예상 한도를 설정할 수 있습니다. 
---
= 할당량을 적용하는 방법
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
할당량이 적용되는 방식을 이해하면 할당량을 올바르게 구성하고 예상 한도를 설정할 수 있습니다.

할당량을 설정한 FlexVol 볼륨의 파일에 파일을 생성하거나 데이터를 쓰려고 할 때마다 작업이 진행되기 전에 할당량 제한이 확인됩니다. 작업이 디스크 제한이나 파일 제한을 초과하면 작업이 금지됩니다.

할당량 제한은 다음 순서로 확인됩니다.

. 해당 qtree의 트리 할당량(파일이 qtree0에 생성 또는 기록되는 경우에는 이 검사가 적용되지 않음)
. 볼륨의 파일을 소유하는 사용자의 사용자 할당량
. 볼륨의 파일을 소유하는 그룹의 그룹 할당량입니다
. qtree에 있는 파일을 소유한 사용자의 할당량(파일이 qtree0에 생성 또는 기록되는 경우에는 이 검사가 적합하지 않음)
. Qtree에서 파일을 소유한 그룹의 그룹 할당량(파일이 qtree0에 생성 또는 기록되는 경우에는 이 검사가 적합하지 않음)


가장 작은 제한을 가진 할당량이 먼저 초과되는 할당량이 아닐 수도 있습니다. 예를 들어 볼륨 vol1의 사용자 할당량이 100GB인 경우 볼륨 vol1에 포함된 Q2의 사용자 할당량은 20GB이며, 해당 사용자가 이미 볼륨 vol1에 80GB 이상의 데이터를 기록한 경우 볼륨 제한에 먼저 도달할 수 있습니다(단, Q2가 아닌 경우).

.관련 정보
* link:../volumes/quotas-applied-root-user-concept.html["루트 사용자에게 할당량을 적용하는 방법"]
* link:../volumes/quotas-applied-users-multiple-ids-concept.html["ID가 여러 개인 사용자에게 할당량을 적용하는 방법"]

