---
permalink: volumes/quota-reports-policy-rule-show-command-concept.html 
sidebar: sidebar 
keywords: when to use, volume quota policy rule show, volume quota report, commands 
summary: 두 명령 모두 할당량에 대한 정보를 표시하지만 볼륨 할당량 정책 규칙은 구성된 할당량 규칙을 빠르게 표시하는 반면, 볼륨 할당량 보고서 명령은 시간과 리소스를 더 많이 소모하며 강제 적용된 할당량과 리소스 사용량을 표시합니다. 
---
= 볼륨 할당량 정책 규칙 표시 및 볼륨 할당량 보고서 명령을 사용하는 경우
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
두 명령 모두 할당량에 대한 정보를 표시하지만 볼륨 할당량 정책 규칙은 구성된 할당량 규칙을 빠르게 표시하고, 시간과 리소스를 더 많이 사용하는 볼륨 할당량 보고서 명령은 적용된 할당량과 리소스 사용량을 표시합니다.

'volume quota policy rule show' 명령은 다음과 같은 용도로 유용합니다.

* 할당량 규칙을 활성화하기 전에 구성을 확인하십시오
+
이 명령은 할당량이 초기화되었는지 또는 크기가 조정되었는지 여부에 관계없이 구성된 모든 할당량 규칙을 표시합니다.

* 시스템 리소스에 영향을 주지 않고 할당량 규칙을 빠르게 봅니다
+
이 명령은 디스크 및 파일 사용량을 표시하지 않으므로 할당량 보고서만큼 리소스를 많이 사용하지 않습니다.

* SVM에 할당되지 않은 할당량 정책에 할당량 규칙을 표시합니다.


볼륨 할당량 보고서 명령은 다음과 같은 용도로 유용합니다.

* 파생 할당량을 비롯한 적용된 할당량을 봅니다
* 파생 할당량의 영향을 받는 대상을 포함하여 모든 할당량이 사용하는 디스크 공간 및 파일 수를 확인합니다
+
기본 할당량의 경우, 결과 파생 할당량에 대해 사용량이 추적되므로 사용량이 "0"으로 표시됩니다.

* 파일에 대한 쓰기가 허용되는 경우 어떤 할당량 제한이 영향을 미치는지 확인합니다
+
볼륨 할당량 보고서 명령에 '-path' 매개 변수를 추가합니다.



[NOTE]
====
할당량 보고서는 리소스를 많이 사용하는 작업입니다. 클러스터의 많은 FlexVol 볼륨에서 실행하는 경우 완료하는 데 오랜 시간이 걸릴 수 있습니다. 더 효율적인 방법은 SVM의 특정 볼륨에 대한 할당량 보고서를 보는 것입니다.

====