---
permalink: volumes/recommendations-moving-concept.html 
sidebar: sidebar 
keywords: considerations, recommendations, when, moving, volumes, flexclone volume, metroCluster configuration 
summary: 볼륨 이동에는 이동할 볼륨 또는 MetroCluster 구성과 같은 시스템 구성에 따라 영향을 받는 다양한 고려 사항과 권장 사항이 있습니다. 볼륨 이동과 관련된 고려 사항과 권장 사항을 이해해야 합니다. 
---
= 볼륨 이동 시 고려 사항 및 권장 사항
:icons: font
:imagesdir: ../media/


[role="lead"]
볼륨 이동에는 이동할 볼륨 또는 MetroCluster 구성과 같은 시스템 구성에 따라 영향을 받는 다양한 고려 사항과 권장 사항이 있습니다. 볼륨 이동과 관련된 고려 사항과 권장 사항을 이해해야 합니다.



== 일반 고려 사항 및 권장 사항

* 클러스터의 릴리즈 제품군을 업그레이드하는 경우, 클러스터의 모든 노드를 업그레이드하기 전에 볼륨을 이동하지 마십시오.
+
이 권장 사항을 사용하면 실수로 볼륨을 새 릴리즈 제품군에서 이전 릴리즈 제품군으로 이동하려고 하는 것을 방지할 수 있습니다.

* 소스 볼륨은 정합성이 보장되어야 합니다.
* 하나 이상의 애그리게이트를 관련 SVM(스토리지 가상 머신)에 할당한 경우, 대상 애그리게이트는 할당된 애그리게이트 중 하나여야 합니다.
* 대신 가져온 CFO 애그리게이트로 또는 CFO 애그리게이트로 볼륨을 이동할 수 없습니다.
* LUN이 포함된 볼륨이 이동 전에 NVFAIL이 활성화되지 않은 경우 볼륨을 이동한 후 NVFAIL이 활성화됩니다.
* Flash Pool 애그리게이트에서 다른 Flash Pool 애그리게이트로 볼륨을 이동할 수 있습니다.
+
** 해당 볼륨의 캐싱 정책도 이동됩니다.
** 이동은 볼륨 성능에 영향을 미칠 수 있습니다.


* Flash Pool 애그리게이트와 비 Flash Pool 애그리게이트 간에 볼륨을 이동할 수 있습니다.
+
** Flash Pool 애그리게이트에서 비 Flash Pool 애그리게이트로 볼륨을 이동하는 경우, ONTAP에서 볼륨 성능에 영향을 줄 수 있으며 계속할 것인지 묻는 메시지가 표시됩니다.
** 비 Flash Pool 애그리게이트에서 Flash Pool 애그리게이트로 볼륨을 이동하는 경우 ONTAP는 '자동' 캐싱 정책을 할당합니다.


* 볼륨은 유휴 상태의 데이터 보호를 통해 애그리게이트로 안전하게 보호합니다. NSE 드라이브가 포함된 Aggregate에서 NSE 드라이브가 아닌 볼륨으로 볼륨을 이동하면 볼륨에 NSE 데이터 -유휴 보호 기능이 없습니다.




== FlexClone 볼륨 고려 사항 및 권장 사항

* FlexClone 볼륨은 이동 중에 오프라인 상태가 될 수 없습니다.
* FlexClone 볼륨을 분할하지 않고 동일한 노드 또는 동일한 SVM의 다른 노드에 있는 한 Aggregate에서 다른 aggregate로 이동할 수 있습니다.
* FlexClone 볼륨 스냅샷 복사본은 클론 이동 후 손실되지 않습니다.
* FlexClone 상위 볼륨을 한 Aggregate에서 다른 aggregate로 이동할 수 있습니다.
+
FlexClone 상위 볼륨을 이동할 때 임시 볼륨은 모든 FlexClone 볼륨의 상위 볼륨으로 작동하는 상태로 남아 있습니다. 임시 볼륨을 오프라인 상태로 만들거나 삭제하는 경우를 제외하고는 해당 볼륨에 대한 작업이 허용되지 않습니다. 모든 FlexClone 볼륨이 분할되거나 제거된 후에는 임시 볼륨이 자동으로 지워집니다.

* FlexClone 하위 볼륨을 이동하면 볼륨은 더 이상 FlexClone 볼륨이 아닙니다.
* FlexClone 이동 작업은 FlexClone 복사본 또는 분할 작업에서만 사용할 수 있습니다.
* 클론 분할 작업이 진행 중인 경우 볼륨을 이동하지 못할 수 있습니다.
+
클론 분할 작업이 완료될 때까지 볼륨을 이동하면 안 됩니다.





== MetroCluster 구성 고려 사항

* MetroCluster 구성에서 볼륨을 이동하는 동안 소스 클러스터의 대상 애그리게이트에 임시 볼륨이 생성되면 미러링된 볼륨의 볼륨에 해당하는 임시 볼륨에 대한 기록이나 흡수되지 않은 aggregate가 나머지 클러스터에도 생성됩니다.
* 컷오버가 발생하기 전에 MetroCluster 전환이 발생하면 대상 볼륨에 레코드가 있고 임시 볼륨(TMP 유형의 볼륨)이 됩니다.
+
남아 있는(재해 복구) 클러스터에서 작업 재시작을 이동하고, 오류를 보고하고, 임시 볼륨을 비롯한 이동 관련 항목을 모두 정리합니다. 정리가 제대로 수행되지 않는 경우 시스템 관리자에게 필요한 정리가 수행되도록 알리는 EMS가 생성됩니다.

* 컷오버 단계가 시작된 후 이동 작업이 완료되기 전에(즉, 대상 애그리게이트를 가리키도록 클러스터를 업데이트할 수 있는 단계에 도달한 이동) MetroCluster 전환이 작동 가능(재해 복구)에서 다시 시작됩니다. 클러스터 및 가 완료까지 실행됩니다.
+
임시 볼륨(원본 소스)을 포함하여 모든 이동 관련 항목이 정리됩니다. 정리가 제대로 수행되지 않는 경우 시스템 관리자에게 필요한 정리가 수행되도록 알리는 EMS가 생성됩니다.

* Switched over Site에 속한 볼륨에 대해 진행 중인 볼륨 이동 작업이 있는 경우 강제 또는 비강제 MetroCluster 전환이 허용되지 않습니다.
+
남아 있는 사이트에 로컬로 있는 볼륨의 볼륨 이동 작업이 진행 중일 때는 스위치백이 차단되지 않습니다.

* 강제 적용 안 된 MetroCluster 전환이 차단되지만 진행 중인 볼륨 이동 작업이 있으면 강제 MetroCluster 전환이 차단되지 않습니다.

