---
permalink: volumes/rehost-nfs-volumes-task.html 
sidebar: sidebar 
keywords: rehost, nfs, volumes 
summary: NFS 프로토콜을 통해 데이터를 제공하는 볼륨을 재호스팅할 수 있습니다. NFS 볼륨을 재호스팅한 후 NFS 프로토콜을 통해 데이터에 계속 액세스하려면 볼륨을 호스팅 SVM의 엑스포트 정책과 연결하고 정책 및 관련 규칙을 수동으로 구성해야 합니다. 
---
= NFS 볼륨을 다시 호스트합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NFS 프로토콜을 통해 데이터를 제공하는 볼륨을 재호스팅할 수 있습니다. NFS 볼륨을 재호스팅한 후 NFS 프로토콜을 통해 데이터에 계속 액세스하려면 볼륨을 호스팅 SVM의 엑스포트 정책과 연결하고 정책 및 관련 규칙을 수동으로 구성해야 합니다.

.이 작업에 대해
* 재호스팅은 중단을 야기하는 작업입니다.
* 재호스팅 작업이 실패하면 소스 볼륨에서 볼륨 정책 및 관련 규칙을 다시 구성해야 할 수 있습니다.
* ONTAP 9.8부터는 NVE(NetApp Volume Encryption)로 볼륨을 재호스팅할 수 있습니다. 온보드 키 관리자를 사용하는 경우 재호스팅 작업 중에 암호화된 메타데이터가 수정됩니다. 사용자 데이터는 변경되지 않습니다.
+
ONTAP 9.8 이상을 사용하는 경우 재호스트 작업을 수행하기 전에 볼륨을 암호화해야 합니다.



* 재호스팅 작업 후에는 소스 볼륨에서 다음 볼륨 정책, 정책 규칙 및 구성이 손실되며 재호스트된 볼륨에서 수동으로 재구성해야 합니다.
+
** 볼륨 및 qtree 엑스포트 정책
** 안티바이러스 정책
** 볼륨 효율성 정책
** QoS(서비스 품질) 정책
** 스냅샷 정책
** 할당량 규칙
** NS-SWITCH 및 NAME SERVICES 구성 엑스포트 정책 및 규칙
** 사용자 및 그룹 ID




.시작하기 전에
* 볼륨이 온라인 상태여야 합니다.
* 볼륨 이동 또는 LUN 이동과 같은 볼륨 관리 작업이 실행되지 않아야 합니다.
* 재호스팅 중인 볼륨에 대한 데이터 액세스를 중지해야 합니다.
* 대상 SVM의 ns-switch 및 name 서비스 구성은 재호스팅 볼륨의 데이터 액세스를 지원하도록 구성해야 합니다.
* 볼륨의 사용자 ID 및 그룹 ID는 타겟 SVM에서 사용하거나 호스팅 볼륨에서 변경해야 합니다.


.단계
. 볼륨 재호스트 작업이 실패할 경우 NFS 정책에 대한 정보가 손실되지 않도록 NFS 엑스포트 정책에 대한 정보를 기록합니다.
. 상위 볼륨에서 볼륨을 마운트 해제합니다.
+
'볼륨 마운트 해제'

. 고급 권한 레벨로 전환합니다.
+
세트 프리빌리지 고급

. 대상 SVM에서 볼륨 재호스팅:
+
`volume rehost -vserver _source_svm_ -volume _volume_name_ -destination-vserver _destination_svm_`

+
대상 SVM의 기본 엑스포트 정책이 재호스팅 볼륨에 적용됩니다.

. 엑스포트 정책 생성:
+
'vserver export-policy create'

. 재호스트된 볼륨의 내보내기 정책을 사용자 정의 엑스포트 정책으로 업데이트합니다.
+
볼륨 수정

. 대상 SVM의 적절한 접합 경로 아래에 볼륨을 마운트합니다.
+
'볼륨 마운트'입니다

. NFS 서비스가 대상 SVM에서 실행되고 있는지 확인합니다.
. 재호스트된 볼륨에 대한 NFS 액세스를 재개합니다.
. 대상 SVM LIF를 반영하도록 NFS 클라이언트 자격 증명 및 LIF 구성을 업데이트합니다.
+
볼륨 액세스 경로(LIF 및 접합 경로)가 변경되었기 때문입니다.



.작업을 마친 후
재호스트된 볼륨에서 정책 및 관련 규칙을 수동으로 재구성해야 합니다.

https://docs.netapp.com/us-en/ontap-sm-classic/nfs-config/index.html["NFS 구성"]
