---
permalink: volumes/reinitialize-quotas-after-changes-task.html 
sidebar: sidebar 
keywords: reinitialize, quotas, after making, extensive, changes 
summary: 기존 할당량 정의를 크게 변경한 후에는 영향을 받는 모든 볼륨에서 할당량을 다시 초기화해야 합니다. 
---
= 대대적인 변경 작업을 수행한 후 할당량을 다시 초기화합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
기존 할당량 정의를 크게 변경한 후에는 영향을 받는 모든 볼륨에서 할당량을 다시 초기화해야 합니다. 이러한 유형의 변경은 적용된 할당량이 없는 대상에 대한 할당량을 추가하거나 삭제하는 경우를 예로 들 수 있습니다.

.이 작업에 대해
할당량을 강제 적용한 SVM(스토리지 가상 시스템)이 있으며, 할당량을 완전히 재초기화해야 하는 변경 작업을 수행할 수 있습니다.

.단계
. '-instance' 매개 변수와 함께 'vserver show' 명령을 사용하여 현재 SVM에 할당된 정책의 이름을 확인합니다.
. 다음 작업을 수행하여 할당량 규칙을 수정합니다.
+
[cols="2*"]
|===
| 원하는 작업 | 그러면... 


 a| 
새 할당량 규칙을 생성합니다
 a| 
볼륨 할당량 정책 규칙 생성 명령을 사용합니다



 a| 
기존 할당량 규칙 설정을 수정합니다
 a| 
볼륨 할당량 정책 규칙 수정 명령을 사용합니다



 a| 
기존 할당량 규칙을 삭제합니다
 a| 
'volume quota policy rule delete' 명령어를 사용한다

|===
. 'volume quota policy rule show' 명령을 사용하여 할당량 규칙이 올바르게 구성되었는지 확인합니다.
. 할당량을 해제한 다음 해당 볼륨에 대해 할당량을 설정하면 할당량을 변경한 각 볼륨에서 할당량을 다시 초기화합니다.
+
.. 영향을 받는 각 볼륨에서 'volume quota off' 명령을 사용하여 해당 볼륨에 대한 할당량을 해제하십시오.
.. 영향을 받는 각 볼륨에 대해 'volume quota on' 명령을 사용하여 해당 볼륨에 대한 할당량을 활성화합니다.
+
[NOTE]
====
"volume quota off" 명령을 실행한 후 거의 즉시 할당량을 활성화하려고 하면 오류가 발생할 수 있으므로 영향을 받는 각 볼륨에서 할당량을 다시 활성화하기 전에 약 5분 정도 기다려야 합니다.

또는 명령을 실행하여 특정 볼륨이 포함된 노드에서 볼륨에 대한 할당량을 다시 초기화할 수 있습니다.

====
+
다음 방법 중 하나를 사용하여 초기화 프로세스를 모니터링할 수 있습니다.

+
*** 'volume quota on' 명령을 사용하면 포그라운드에 있는 작업에서 할당량을 실행하기 위해 '-foreground' 매개 변수를 추가할 수 있습니다. (기본적으로 작업은 백그라운드에서 실행됩니다.)
+
작업이 백그라운드에서 실행되면 job show 명령을 사용하여 진행 상황을 모니터링할 수 있습니다.

*** 'volume quota show' 명령을 사용하여 할당량 초기화 상태를 모니터링할 수 있습니다.




. "volume quota show -instance" 명령을 사용하여 초기화에 실패한 할당량 규칙과 같은 초기화 오류를 확인합니다.
. "volume quota report" 명령을 사용하여 할당량 보고서를 표시하면 적용된 할당량이 기대에 맞는지 확인할 수 있습니다.

