---
permalink: volumes/resizing-concept.html 
sidebar: sidebar 
keywords: when to, use, resizing 
summary: 할당량 크기 조정이 할당량 초기화보다 빠르기 때문에 가능하면 크기 조정을 사용해야 합니다. 그러나 크기 조정은 특정 유형의 할당량 변경에만 적용됩니다. 
---
= 크기 조정을 사용할 수 있는 경우
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
할당량 크기 조정이 할당량 초기화보다 빠르기 때문에 가능하면 크기 조정을 사용해야 합니다. 그러나 크기 조정은 특정 유형의 할당량 변경에만 적용됩니다.

할당량 규칙을 다음과 같이 변경할 때 할당량 크기를 조정할 수 있습니다.

* 기존 할당량 변경.
+
예를 들어, 기존 할당량의 제한을 변경합니다.

* 기본 할당량 또는 기본 추적 할당량이 있는 할당량 타겟에 대한 할당량 추가
* 기본 할당량 또는 기본 추적 할당량 항목이 지정된 할당량을 삭제합니다.
* 개별 사용자 할당량을 하나의 다중 사용자 할당량으로 결합합니다.


[NOTE]
====
할당량을 광범위하게 변경한 후에는 전체 재초기화를 수행하여 모든 변경 사항이 적용되도록 해야 합니다.

====
[NOTE]
====
크기 조정 작업을 사용하여 모든 할당량 변경 사항을 통합할 수 없는 경우 ONTAP에서 경고를 표시합니다. 할당량 보고서를 통해 스토리지 시스템이 특정 사용자, 그룹 또는 qtree의 디스크 사용량을 추적하는지 확인할 수 있습니다. 할당량 보고서에 할당량이 표시되는 경우, 이는 스토리지 시스템이 디스크 공간과 할당량 대상이 소유한 파일 수를 추적하고 있음을 의미합니다.

====
.할당량 변경 예제 크기를 조정하여 효과적으로 변경할 수 있습니다
일부 할당량 규칙 변경은 크기 조정을 통해 적용할 수 있습니다. 다음 할당량을 고려해 보십시오.

[listing]
----

#Quota Target type             disk  files thold sdisk sfile
#------------ ----             ----  ----- ----- ----- -----
*             user@/vol/vol2    50M   15K
*             group@/vol/vol2  750M   85K
*             tree@/vol/vol2      -     -
jdoe          user@/vol/vol2/  100M   75K
kbuck         user@/vol/vol2/  100M   75K
----
다음과 같이 변경한다고 가정합니다.

* 기본 사용자 대상의 파일 수를 늘립니다.
* 기본 사용자 할당량보다 더 많은 디스크 제한이 필요한 새 사용자 할당량인 Boris를 추가합니다.
* kbuck 사용자의 명시적 할당량 항목을 삭제합니다. 이제 새 사용자는 기본 할당량 제한만 필요합니다.


이러한 변경 사항으로 인해 다음과 같은 할당량이 발생합니다.

[listing]
----

#Quota Target type             disk  files thold sdisk sfile
#------------ ----             ----  ----- ----- ----- -----
*             user@/vol/vol2    50M   25K
*             group@/vol/vol2  750M   85K
*             tree@/vol/vol2      -     -
jdoe          user@/vol/vol2/  100M   75K
boris         user@/vol/vol2/  100M   75K
----
크기를 조정하면 이러한 모든 변경 사항이 활성화되지만 전체 할당량을 다시 초기화할 필요는 없습니다.
