---
permalink: volumes/resume-efficiency-operation-checkpoint-task.html 
sidebar: sidebar 
keywords: resume, halted, efficiency, operation 
summary: 시스템 중지, 시스템 중단 또는 재부팅으로 인해 효율성 작업이 중단되면 체크포인트 옵션과 함께 볼륨 효율성 시작 명령을 사용하여 동일한 지점에서 효율성 작업을 재개할 수 있습니다. 따라서 처음부터 효율성 작업을 다시 시작할 필요가 없어 시간과 리소스를 절약할 수 있습니다. 
---
= 중단된 효율성 작업을 다시 시작합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
시스템 중지, 시스템 중단 또는 재부팅으로 인해 효율성 작업이 중단되면 체크포인트 옵션과 함께 'volume Efficiency start' 명령을 사용하여 동일한 지점에서 효율성 작업을 재개할 수 있습니다. 따라서 처음부터 효율성 작업을 다시 시작할 필요가 없어 시간과 리소스를 절약할 수 있습니다.

볼륨에 대해서만 중복 제거를 활성화하면 데이터가 중복 제거를 실행합니다. 볼륨에 대해 중복제거 및 데이터 압축을 둘 다 설정한 경우 데이터 압축이 먼저 실행된 후 중복제거가 실행됩니다.

'volume Efficiency show' 명령을 사용하여 볼륨에 대한 체크포인트의 세부 정보를 볼 수 있습니다.

기본적으로 효율성 작업은 체크포인트에서 다시 시작됩니다. 그러나 이전 효율성 작업에 해당하는 체크포인트('볼륨 효율성 시작'-scan-old-data' 명령이 실행되는 단계)가 24시간 이상 오래된 경우에는 이전 체크포인트에서 효율성 작업이 자동으로 다시 시작되지 않습니다. 이 경우 효율성 작업은 처음부터 시작됩니다. 그러나 마지막 스캔 이후 볼륨에 상당한 변화가 일어나지 않았다면 '-use-checkpoint' 옵션을 사용하여 이전 체크포인트에서 강제로 계속할 수 있습니다.

.단계
. 효율성 작업을 재개하려면 '-use-checkpoint' 옵션과 함께 'volume Efficiency start' 명령을 사용하십시오.
+
다음 명령을 사용하여 볼륨 VolA의 새 데이터에 대한 효율성 작업을 재개할 수 있습니다.

+
'볼륨 효율성 시작 - vserver vs1-volume vola-use-checkpoint true'

+
다음 명령을 사용하여 볼륨 VolA의 기존 데이터에 대한 효율성 작업을 다시 시작할 수 있습니다.

+
'볼륨 효율성 시작 - vserver vs1-volume vola-scan-old-data TRUE-use-checkpoint true'


