---
permalink: volumes/run-efficiency-operations-manual-existing-data-task.html 
sidebar: sidebar 
keywords: run, efficiency, operations, manually, existing, data 
summary: 중복제거, 데이터 압축 또는 데이터 컴팩션을 활성화하기 전에 온도에 민감하지 않은 스토리지 효율성 볼륨에 있는 데이터에 대해 수동으로 효율성 작업을 실행합니다. 
---
= 기존 데이터에 대해 수동으로 효율성 작업 실행
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
온도에 민감하지 않은 스토리지 효율성 볼륨에 있는 데이터에 대해 중복제거, 데이터 압축 또는 데이터 컴팩션을 활성화하기 전에 효율성 작업을 수동으로 실행할 수 있습니다. ONTAP 9.8 이전 버전의 ONTAP에서 이러한 작업을 실행할 수 있습니다.

.이 작업에 대해
이 작업은 `volume efficiency start` 명령을 `-scan-old-data` 매개 변수와 함께 사용하여 수행됩니다. 이 `-compression` 옵션은 온도에 민감한 스토리지 효율성 볼륨에 대해서는 작동하지 `-scan-old-data` 않습니다. 비활성 데이터 압축은 기존 데이터에 대해 자동으로 실행되어 ONTAP 9.8 이상에서는 온도에 민감한 스토리지 효율성을 높입니다.

볼륨에 대해 중복 제거만 사용하도록 설정하면 데이터에서 중복제거가 실행됩니다. 볼륨에 중복제거, 데이터 압축 및 데이터 컴팩션을 사용하도록 설정하면 데이터 압축이 먼저 실행된 후 중복제거가 실행되고 데이터 컴팩션이 적용됩니다.

기존 데이터에 대해 데이터 압축을 실행하면 기본적으로 데이터 압축 작업에서는 중복 제거가 공유하는 데이터 블록과 스냅샷 복사본에 의해 잠겨진 데이터 블록을 건너뜁니다. 공유 블록에 대해 데이터 압축을 실행하도록 선택하면 최적화가 꺼지고 지문 정보가 캡처되어 다시 공유용으로 사용됩니다. 기존 데이터를 압축할 때 데이터 압축의 기본 동작을 변경할 수 있습니다.

노드당 최대 8개의 중복제거, 데이터 압축 또는 데이터 컴팩션 작업을 동시에 실행할 수 있습니다. 나머지 작업은 대기열에 추가됩니다.

[NOTE]
====
AFF 플랫폼에서는 사후 처리 압축이 실행되지 않습니다. 이 작업을 건너뛰었음을 알리는 EMS 메시지가 생성됩니다.

====
.단계
. 'volume Efficiency start-scan-old-data' 명령을 사용하여 기존 데이터에서 중복제거, 데이터 압축 또는 데이터 컴팩션을 수동으로 실행하십시오.
+
다음 명령을 사용하면 볼륨 VolA의 기존 데이터에 대해 이러한 작업을 수동으로 실행할 수 있습니다.

+
'볼륨 효율성 시작 - vserver vs1-volume vola-scan-old-data TRUE[-compression|-dedupe|-다짐] TRUE'



.관련 정보
* link:run-efficiency-operations-manual-task.html["효율성 작업을 수동으로 실행합니다"]

