---
permalink: volumes/san-volumes-concept.html 
sidebar: sidebar 
keywords: understand, san volumes 
summary: ONTAP는 일반 프로비저닝, 씬 프로비저닝 및 반일반 프로비저닝의 세 가지 기본 볼륨 프로비저닝 옵션을 제공합니다. 각 옵션은 볼륨 공간과 ONTAP 블록 공유 기술의 공간 요구 사항을 관리하는 다양한 방법을 사용합니다. 옵션의 작동 방식을 이해하면 환경에 가장 적합한 옵션을 선택할 수 있습니다. 
---
= SAN 볼륨 정보
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP는 일반 프로비저닝, 씬 프로비저닝 및 반일반 프로비저닝의 세 가지 기본 볼륨 프로비저닝 옵션을 제공합니다. 각 옵션은 볼륨 공간과 ONTAP 블록 공유 기술의 공간 요구 사항을 관리하는 다양한 방법을 사용합니다. 옵션의 작동 방식을 이해하면 환경에 가장 적합한 옵션을 선택할 수 있습니다.

[NOTE]
====
SAN LUN과 NAS 공유를 동일한 FlexVol 볼륨에 배치하는 것은 권장되지 않습니다. SAN LUN을 위해 특별히 별도의 FlexVol 볼륨을 프로비저닝해야 하며 NAS 공유에 별도의 FlexVol 볼륨을 프로비저닝해야 합니다. 이렇게 하면 관리 및 복제 구축이 간소화되고 FlexVol 볼륨이 Active IQ Unified Manager(이전의 OnCommand Unified Manager)에서 지원되는 방식과 유사점이 있습니다.

====


== 볼륨에 대한 씬 프로비저닝

씬 프로비저닝된 볼륨이 생성된 경우 ONTAP는 볼륨이 생성될 때 추가 공간을 예약하지 않습니다. 볼륨에 데이터가 기록될 때 볼륨은 쓰기 작업을 수용하기 위해 Aggregate에서 필요한 스토리지를 요청합니다. 씬 프로비저닝된 볼륨을 사용하면 애그리게이트를 오버 커밋할 수 있으므로 애그리게이트에 여유 공간이 부족할 때 볼륨이 필요한 공간을 확보할 수 없게 됩니다.

'-space-보증' 옵션을 '없음'으로 설정하여 씬 프로비저닝된 FlexVol 볼륨을 만듭니다.



== 볼륨에 대한 일반 프로비저닝입니다

씩 프로비저닝된 볼륨이 생성되면 ONTAP는 언제든지 볼륨의 블록을 쓸 수 있도록 애그리게이트에 충분한 스토리지를 남겨 둡니다. 일반 프로비저닝을 사용하도록 볼륨을 구성할 경우 압축 및 중복제거와 같은 ONTAP 스토리지 효율성 기능을 사용하여 대규모 초기 스토리지 요구사항을 상쇄할 수 있습니다.

'-space-slo'(서비스 수준 목표) 옵션을 'thick'으로 설정하여 씩 프로비저닝된 FlexVol 볼륨을 만듭니다.



== 볼륨에 반씩 프로비저닝

반씩 프로비저닝을 사용하는 볼륨이 생성된 경우 ONTAP에서는 애그리게이트에서 볼륨 크기를 고려하여 스토리지 공간을 별도로 설정합니다. 블록 공유 기술이 블록이 사용 중이기 때문에 볼륨에 여유 공간이 부족한 경우 ONTAP은 보호 데이터 오브젝트(스냅샷 복사본 및 FlexClone 파일, LUN)를 삭제하여 보유 공간을 확보하도록 합니다. ONTAP가 덮어쓰기 작업에 필요한 공간과 보조를 맞출 수 있을 만큼 보호 데이터 객체를 빠르게 삭제할 수 있는 한 쓰기 작업은 계속 성공합니다. 이를 '최선 노력'이라고 합니다.

[NOTE]
====
반씩 프로비저닝을 사용하는 볼륨에는 중복제거, 압축, 컴팩션과 같은 스토리지 효율성 기술을 사용할 수 없습니다.

====
semi-thick-provisioned FlexVol 볼륨은 '-space-slo'(서비스 수준 목표) 옵션을 'sEMI-thick'으로 설정하여 생성합니다.



== 공간 예약 파일 및 LUN과 함께 사용

공간 예약 파일 또는 LUN은 생성 시 스토리지가 할당되는 파일입니다. 역사적으로 NetApp은 공간 예약이 사용되지 않는 LUN(비공간 예약 LUN)을 지칭하기 위해 ""씬 프로비저닝된 LUN"이라는 용어를 사용했습니다.

[NOTE]
====
공간이 예약되지 않은 파일은 일반적으로 ""씬 프로비저닝 파일"이라고 하지 않습니다.

====
다음 표에는 세 가지 볼륨 프로비저닝 옵션을 공간 예약 파일 및 LUN과 함께 사용하는 방법의 주요 차이점이 요약되어 있습니다.

[cols="5*"]
|===
| 볼륨 프로비저닝 | LUN/파일 공간 예약 | 덮어쓰기 | 보호 데이터 ^2^ | 스토리지 효율성 ^3^ 


 a| 
두껍게
 a| 
지원
 a| 
^1^을(를) 보장합니다
 a| 
NetApp이 보장합니다
 a| 
지원



 a| 
얇음
 a| 
효과 없음
 a| 
없음
 a| 
NetApp이 보장합니다
 a| 
지원



 a| 
약간 두껍습니다
 a| 
지원
 a| 
최선의 노력 ^1^
 a| 
최선을 다하세요
 a| 
지원되지 않습니다

|===
* 참고 *

. 덮어쓰기 보장 또는 최선의 덮어쓰기 보장을 제공하려면 LUN 또는 파일에 공간 예약을 설정해야 합니다.
. 보호 데이터에는 스냅샷 복사본과 FlexClone 파일, 자동 삭제 표시된 LUN(백업 클론)이 포함됩니다.
. 스토리지 효율성에는 중복제거, 압축, 자동 삭제로 표시되지 않은 모든 FlexClone 파일 및 LUN(활성 클론), FlexClone 하위 파일(복사본 오프로드로 사용)이 포함됩니다.




== SCSI 씬 프로비저닝된 LUN 지원

ONTAP는 T10 SCSI 씬 프로비저닝 LUN과 NetApp 씬 프로비저닝 LUN을 지원합니다. T10 SCSI 씬 프로비저닝을 사용하면 호스트 애플리케이션에서 LUN 공간 재확보, 블록 환경의 LUN 공간 모니터링 기능 등 SCSI 기능을 지원할 수 있습니다. T10 SCSI 씬 프로비저닝은 SCSI 호스트 소프트웨어에서 지원해야 합니다.

ONTAP의 pace-allocation 설정을 사용하면 LUN에서 T10 씬 프로비저닝 지원을 활성화/비활성화할 수 있습니다. ONTAP의 pace-allocation enable 설정을 사용하여 LUN에 T10 SCSI 씬 프로비저닝을 활성화합니다.

ONTAP 명령 참조 설명서 의 [-space-allocation{enabled|disabled}] 명령에 T10 씬 프로비저닝 지원을 설정/해제하고 LUN에 T10 SCSI 씬 프로비저닝을 설정하는 데 필요한 자세한 정보가 나와 있습니다.

.관련 정보
* link:http://docs.netapp.com/us-en/ontap-cli["ONTAP 9 명령 참조"^]

