---
permalink: volumes/set-fractional-reserve-concept.html 
sidebar: sidebar 
keywords: considerations, setting, fractional, reserve, lun overwrite reserve 
summary: 부분 예약을 사용하면 FlexVol volume에서 공간 예약 LUN 및 파일에 대한 덮어쓰기 예약 기능을 해제하여 스토리지 활용률을 극대화할 수 있습니다. 
---
= 분할 예약 설정 시 고려 사항
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
lun 덮어쓰기 예약 _ 이라고도 하는 분할 예약을 통해 FlexVol 볼륨의 공간 예약 LUN 및 파일에 대한 덮어쓰기 예약 기능을 해제할 수 있습니다. 이를 통해 스토리지 활용도를 극대화할 수 있습니다.


CAUTION: 공간 부족으로 인해 쓰기 작업 실패로 인해 환경이 부정적인 영향을 받는 경우 이 구성이 적용할 수 있는 요구사항을 이해해야 합니다.

분수 예약 설정은 백분율로 표시되며 유효한 값은 `0` 및 `100` 백분율뿐입니다. 분할 예약 설정은 볼륨의 속성입니다.  `0`스토리지 활용률을 높이기 위해 부분 예약을 설정합니다. 하지만 볼륨에 여유 공간이 부족할 경우, 볼륨 보장이 로 설정된 경우에도 볼륨에 상주하는 데이터에 액세스하는 애플리케이션에서 데이터가 중단될 수 있습니다. `volume` 그러나 적절한 볼륨 구성 및 사용을 통해 쓰기 실패 가능성을 최소화할 수 있습니다. ONTAP는 `0` 다음 요구 사항 중 _ALL_로 설정된 부분 예비 공간이 있는 볼륨에 대해 ""최선의 노력"" 쓰기 보증을 제공합니다.

* 중복 제거가 사용되지 않습니다
* 압축이 사용되지 않습니다
* FlexClone 하위 파일을 사용하지 않습니다
* 모든 FlexClone 파일과 FlexClone LUN이 자동으로 삭제됩니다
+
이 설정은 기본 설정이 아닙니다. 생성 시 또는 FlexClone 파일 또는 FlexClone LUN을 생성한 후에 이를 수정하여 자동 삭제를 명시적으로 설정해야 합니다.

* ODX 및 FlexClone 복사 오프로드가 사용되지 않습니다
* 볼륨 보장이 '볼륨'으로 설정되어 있습니다
* 파일 또는 LUN 공간 예약이 '사용'되었습니다
* 볼륨 스냅숏 예비 공간이 '0'으로 설정되어 있습니다
* 볼륨 스냅샷 복사본 자동 삭제는 'destroy', 'lun_clone, vol_clone, cifs_share, file_clone, sfsr' 제거 목록, 'volume' 트리거로 'enabled'입니다
+
이 설정은 필요한 경우 FlexClone 파일 및 FlexClone LUN도 삭제되도록 합니다.



[NOTE]
====
* 위의 모든 요구사항이 충족되지만 변화율 이 높은 경우 스냅샷 복사본 자동 삭제가 지연되어 볼륨 공간이 부족할 수 있습니다.
* 위의 모든 요구사항이 충족되고 스냅샷 복사본이 사용되지 않는 경우 볼륨 쓰기에 공간이 부족하지 않게 됩니다.


====
또한 선택적으로 볼륨 자동 확장 기능을 사용하여 볼륨 스냅샷 복사본을 자동으로 삭제해야 할 가능성을 줄일 수 있습니다. 자동 확장 기능을 사용하도록 설정한 경우 연결된 애그리게이트의 여유 공간을 모니터링해야 합니다. Aggregate가 꽉 차서 볼륨 증가를 막을 수 없을 경우 볼륨의 여유 공간이 고갈되면 더 많은 Snapshot 복사본이 삭제될 수 있습니다.

위 구성 요구사항을 모두 충족하지 못할 경우 볼륨에서 공간이 부족하지 않도록 해야 하는 경우 볼륨의 분할 예약 설정을 '100'으로 설정해야 합니다. 이를 위해서는 공간을 미리 확보해야 하지만, 위에 나열된 기술이 사용 중일 때도 데이터 수정 작업이 성공하도록 보장합니다.

분할 예약 설정의 기본값 및 허용되는 값은 볼륨의 보장에 따라 다릅니다.

[cols="3*"]
|===
| 볼륨 보장 | 기본 분할 예약 | 허용되는 값 


 a| 
볼륨
 a| 
100
 a| 
0, 100



 a| 
없음
 a| 
0
 a| 
0, 100

|===