---
permalink: volumes/setup-quotas-svm-task.html 
sidebar: sidebar 
keywords: set up, quotas on svm 
summary: '새 스토리지 가상 시스템(SVM, 이전의 Vserver)에서 할당량을 설정하려면 할당량 정책을 생성하고, 정책에 할당량 정책 규칙을 추가하고, SVM에 정책을 할당하고, SVM의 각 FlexVol 볼륨에서 할당량을 초기화해야 합니다.' 
---
= SVM에서 할당량 설정
:icons: font
:imagesdir: ../media/


[role="lead"]
새 스토리지 가상 시스템(SVM, 이전의 Vserver)에서 할당량을 설정하려면 할당량 정책을 생성하고, 정책에 할당량 정책 규칙을 추가하고, SVM에 정책을 할당하고, SVM의 각 FlexVol 볼륨에서 할당량을 초기화해야 합니다.

.단계
. SVM이 생성될 때 자동으로 생성된 기본 할당량 정책의 이름을 표시하려면 '-instance' 옵션과 함께 'vserver show' 명령을 사용하십시오.
+
SVM을 생성할 때 이름을 지정하지 않은 경우 이름이 "기본값"이 됩니다. 'vserver quota policy rename' 명령을 사용하여 기본 정책에 이름을 지정할 수도 있습니다.

+
[NOTE]
====
볼륨 할당량 정책 생성 명령을 사용하여 새 정책을 생성할 수도 있습니다.

====
. "volume quota policy rule create" 명령을 사용하여 SVM의 각 볼륨에 대해 다음 할당량 규칙 중 _any_를 생성합니다.
+
** 모든 사용자에 대한 기본 할당량 규칙입니다
** 특정 사용자에 대한 명시적 할당량 규칙
** 모든 그룹에 대한 기본 할당량 규칙입니다
** 특정 그룹에 대한 명시적 할당량 규칙을 나타냅니다
** 모든 qtree에 대한 기본 할당량 규칙
** 특정 qtree에 대한 명시적 할당량 규칙


. 'volume quota policy rule show' 명령을 사용하여 할당량 규칙이 올바르게 구성되었는지 확인합니다.
. 새 정책을 작업 중인 경우 "vserver modify" 명령을 사용하여 SVM에 새 정책을 할당합니다.
. "volume quota on" 명령을 사용하여 SVM의 각 볼륨에 대한 할당량을 초기화합니다.
+
다음과 같은 방법으로 초기화 프로세스를 모니터링할 수 있습니다.

+
** 'volume quota on' 명령을 사용하면 포그라운드에 있는 작업에서 할당량을 실행하기 위해 '-foreground' 매개 변수를 추가할 수 있습니다. (기본적으로 작업은 백그라운드에서 실행됩니다.)
+
작업이 백그라운드에서 실행되면 job show 명령을 사용하여 진행 상황을 모니터링할 수 있습니다.

** 'volume quota show' 명령을 사용하여 할당량 초기화 상태를 모니터링할 수 있습니다.


. "volume quota show -instance" 명령을 사용하여 초기화에 실패한 할당량 규칙과 같은 초기화 오류를 확인합니다.
. "volume quota report" 명령을 사용하여 할당량 보고서를 표시하면 적용된 할당량이 기대에 맞는지 확인할 수 있습니다.

