---
permalink: volumes/space-display-quota-report-unix-client-concept.html 
sidebar: sidebar 
keywords: difference, space usage, displayed, quota report, unix client 
summary: FlexVol 볼륨 또는 qtree에 대한 할당량 보고서에 표시되는 사용된 디스크 공간의 값은 동일한 볼륨 또는 qtree에 대해 UNIX 클라이언트가 표시하는 값과 다를 수 있습니다. 사용 값의 차이는 볼륨 또는 qtree의 데이터 블록을 계산하기 위한 할당량 보고서 및 UNIX 명령이 이어지는 방법의 차이로 인해 나타납니다. 
---
= 할당량 보고서 및 UNIX 클라이언트 개요로 표시되는 공간 사용량 차이
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
FlexVol 볼륨 또는 qtree에 대한 할당량 보고서에 표시되는 사용된 디스크 공간의 값은 동일한 볼륨 또는 qtree에 대해 UNIX 클라이언트가 표시하는 값과 다를 수 있습니다. 사용 값의 차이는 볼륨 또는 qtree의 데이터 블록을 계산하기 위한 할당량 보고서 및 UNIX 명령이 이어지는 방법의 차이로 인해 나타납니다.

예를 들어, 볼륨에 데이터가 기록되지 않은 빈 데이터 블록이 있는 파일이 포함된 경우 볼륨에 대한 할당량 보고서에서 공간 사용량을 보고하는 동안 빈 데이터 블록이 계산되지 않습니다. 그러나 볼륨이 UNIX 클라이언트에 마운트되어 있고 파일이 "ls" 명령의 출력으로 표시되면 빈 데이터 블록도 공간 사용량에 포함됩니다. 따라서 "ls" 명령은 할당량 보고서에 표시되는 공간 사용량과 비교하여 더 큰 파일 크기를 표시합니다.

마찬가지로 할당량 보고서에 표시되는 공간 사용량 값도 "df", "du"와 같은 UNIX 명령의 결과로 표시되는 값과 다를 수 있습니다.



== 할당량 보고서에서 디스크 공간 및 파일 사용량을 확인하는 방법

FlexVol 볼륨 또는 qtree에 대해 할당량 보고서에 지정된 파일 수와 디스크 공간 크기는 볼륨 또는 qtree의 모든 inode에 해당하는 사용된 데이터 블록의 수에 따라 달라집니다.

블록 수에는 일반 및 스트림 파일에 사용되는 직접 및 간접 블록이 모두 포함됩니다. 디렉토리, ACL(액세스 제어 목록), 스트림 디렉토리 및 메타파일에 사용되는 블록이 할당량 보고서에 고려되지 않습니다. UNIX 스파스 파일의 경우 빈 데이터 블록이 할당량 보고서에 포함되지 않습니다.

할당량 하위 시스템은 사용자가 제어할 수 있는 파일 시스템 측면만 고려하고 포함하도록 설계되었습니다. 디렉토리, ACL 및 스냅샷 공간은 모두 할당량 계산에서 제외된 공간의 예입니다. 할당량은 보장이 아닌 제한을 적용하는 데 사용되며 활성 파일 시스템에서만 작동합니다. 할당량 계산에서는 특정 파일 시스템 구문을 계산하지 않으며 압축 또는 중복 제거와 같은 스토리지 효율성을 고려하지 않습니다.
