---
permalink: volumes/split-flexclone-from-parent-task.html 
sidebar: sidebar 
keywords: split, flexclone, volume, parent, volume 
summary: 상위 볼륨의 FlexClone 볼륨을 사용하지 않고 읽기-쓰기 FlexClone 볼륨을 자체 디스크 공간을 사용하려면 상위 볼륨에서 FlexClone 볼륨을 분할할 수 있습니다. 이 작업을 수행하면 상위 볼륨과 FlexClone 볼륨 간에 현재 공유되는 데이터의 복사본이 생성되므로 작업을 완료하는 데 약간의 시간이 걸릴 수 있습니다. 
---
= 상위 볼륨에서 FlexClone 볼륨을 분할합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
상위 볼륨의 FlexClone 볼륨을 사용하지 않고 읽기-쓰기 FlexClone 볼륨을 자체 디스크 공간을 사용하려면 상위 볼륨에서 FlexClone 볼륨을 분할할 수 있습니다. 이 작업을 수행하면 상위 볼륨과 FlexClone 볼륨 간에 현재 공유되는 데이터의 복사본이 생성되므로 작업을 완료하는 데 약간의 시간이 걸릴 수 있습니다.

.이 작업에 대해
FlexClone 볼륨을 상위 볼륨에서 분산하면 포함된 애그리게이트에 더 많은 공간이 예약될 수 있습니다. Aggregate에서 사용 가능한 공간을 볼 수 있는 권한이 없는 경우 스토리지 관리자에게 문의하여 분할 작업을 완료할 수 있는 충분한 공간이 있는지 확인해야 합니다.

ONTAP 9.4부터 AFF 시스템의 보장되지 않는 볼륨의 경우 FlexClone 볼륨의 분할 작업은 물리적 블록을 공유하며 데이터를 복사하지 않습니다. 따라서 AFF 시스템에서 FlexClone 볼륨을 분할하는 것이 ONTAP 9.4의 다른 FAS 시스템에서 FlexClone 분할 작업보다 빠릅니다. AFF 시스템에서 향상된 FlexClone 분할 작업은 다음과 같은 이점을 제공합니다.

* 상위 클론에서 클론을 분할한 후에는 스토리지 효율성이 유지됩니다.
* 기존 스냅샷 복사본은 삭제되지 않습니다.
* 작업이 더 빠릅니다.
* FlexClone 볼륨은 클론 계층 구조의 모든 지점에서 분할할 수 있습니다.


.단계
. 분할 작업을 완료하는 데 필요한 여유 공간을 결정합니다.
+
'volume clone show-estimate-vserver vserver_name-FlexClone clone_volume_name-parent-volume parent_vol_name'

+
다음 예제에서는 FlexClone 볼륨 clone1을 상위 볼륨 vol1에서 분할하는 데 필요한 여유 공간에 대한 정보를 제공합니다.

+
[listing]
----
cluster1::> volume clone show -estimate -vserver vs1 -flexclone clone1 -parent-volume volume1
                             Split
Vserver   FlexClone       Estimate
--------- ------------- ----------
vs1       clone1           40.73MB
----
. FlexClone 볼륨과 상위 항목이 포함된 애그리게이트에 충분한 공간이 있는지 확인합니다.
+
.. FlexClone 볼륨과 상위 항목이 들어 있는 애그리게이트의 여유 공간 크기를 확인합니다.
+
'스토리지 집계 쇼'

.. 포함된 Aggregate에 사용 가능한 여유 공간이 충분하지 않은 경우 스토리지를 Aggregate에 추가합니다.
+
'스토리지 집계 추가 디스크'



. 분할 작업을 시작합니다.
+
'볼륨 클론 분할 시작 - vserver_vserver_name_-FlexClone_clone_volume_name_'

+
다음 예에서는 FlexClone 볼륨 clone1을 상위 볼륨 vol1에서 분리하는 프로세스를 시작하는 방법을 보여줍니다.

+
[listing]
----
cluster1::> volume clone split start -vserver vs1 -flexclone clone1

Warning: Are you sure you want to split clone volume clone1 in Vserver vs1 ?
{y|n}: y
[Job 1617] Job is queued: Split clone1.
----
. FlexClone 분할 작업의 상태를 모니터링합니다.
+
'볼륨 클론 분할 표시 - vserver_vserver_name_-FlexClone_clone_volume_name_'

+
다음 예제는 AFF 시스템에서 FlexClone 분할 작업의 상태를 보여줍니다.

+
[listing]
----
cluster1::> volume clone split show -vserver vs1 -flexclone clone1
                                              Inodes                   Blocks
                                     ---------------------    ---------------------
Vserver   FlexClone    Processed Total    Scanned  Updated      % Inode   % Block
                                                                 Complete  Complete
vs1       clone1        0         0       411247   153600         0        37
----
. 분할 볼륨이 더 이상 FlexClone 볼륨이 아닌지 확인합니다.
+
'volume show-volume_volume_name_-fields_clone-volume_'

+
FlexClone 볼륨이 아닌 볼륨에 대해 "clone-volume" 옵션의 값은 "false"입니다.

+
다음 예제에서는 부모로부터 분할된 볼륨 clone1이 FlexClone 볼륨이 아닌지 여부를 확인하는 방법을 보여 줍니다.

+
[listing]
----
cluster1::> volume show -volume clone1 -fields clone-volume
vserver volume **clone-volume**
------- ------ **------------**
vs1     clone1 **false**
----

