---
permalink: encryption-at-rest/assign-fips-140-2-authentication-key-task.html 
sidebar: sidebar 
keywords: assigning, fips 140-2, authentication key, fips drive 
summary: FIPS-key-id 옵션과 함께 스토리지 암호화 디스크 수정 명령을 사용하여 FIPS 140-2 인증 키를 FIPS 드라이브에 할당할 수 있습니다. 클러스터 노드는 드라이브에 대한 서비스 거부 공격을 방지하는 것과 같이 데이터 액세스 이외의 드라이브 작업에 이 키를 사용합니다. 
---
= FIPS 140-2 인증 키를 FIPS 드라이브에 할당합니다
:allow-uri-read: 


[role="lead"]
'-FIPS-key-id' 옵션과 함께 'storage encryption disk modify' 명령을 사용하여 FIPS 140-2 인증 키를 FIPS 드라이브에 할당할 수 있습니다. 클러스터 노드는 드라이브에 대한 서비스 거부 공격을 방지하는 것과 같이 데이터 액세스 이외의 드라이브 작업에 이 키를 사용합니다.

드라이브 펌웨어는 FIPS 140-2 규정 준수를 지원해야 합니다. 를 클릭합니다 https://mysupport.netapp.com/matrix["NetApp 상호 운용성 매트릭스 툴"^] 지원되는 드라이브 펌웨어 버전에 대한 정보를 제공합니다.

보안 설정에서 데이터 인증과 FIPS 140-2 인증을 위해 다른 키를 사용해야 할 수 있습니다. 그렇지 않은 경우 데이터 액세스에 사용하는 FIPS 준수에 동일한 인증 키를 사용할 수 있습니다.

.단계
. 먼저 데이터 인증 키를 할당했는지 확인해야 합니다. 이 작업은 를 사용하여 수행할 수 있습니다 xref:assign-authentication-keys-seds-external-task.html[외부 키 관리자] 또는 을 누릅니다 xref:assign-authentication-keys-seds-onboard-task.html[Onboard Key Manager(온보드 키 관리자]. 'storage encryption disk show' 명령을 사용하여 키가 할당되었는지 확인합니다.
. SED에 FIPS 140-2 인증 키 할당:
+
'Storage encryption disk modify -disk_disk_id_-FIPS-key-id_FIPS_authentication_key_id_'

+
'보안 키 관리자 쿼리' 명령을 사용하여 키 ID를 볼 수 있습니다.

+
[source]
----
cluster1::> storage encryption disk modify -disk 2.10.* -fips-key-id 6A1E21D80000000001000000000000005A1FB4EE8F62FD6D8AE6754C9019F35A

Info: Starting modify on 14 disks.
      View the status of the operation by using the
      storage encryption disk show-status command.
----
. 인증 키가 할당되었는지 확인합니다.
+
스토리지 암호화 디스크 show-FIPS

+
전체 명령 구문은 man 페이지를 참조하십시오.

+
[listing]
----
cluster1::> storage encryption disk show -fips
Disk    Mode FIPS-Compliance Key ID
------  ---- ----------------------------------------------------------------
2.10.0  full 6A1E21D80000000001000000000000005A1FB4EE8F62FD6D8AE6754C9019F35A
2.10.1  full 6A1E21D80000000001000000000000005A1FB4EE8F62FD6D8AE6754C9019F35A
[...]
----

