---
permalink: encryption-at-rest/change-key-management-passphrase-task.html 
sidebar: sidebar 
keywords: changing, onboard, key, management, passphrase 
summary: 온보드 키 관리 암호를 정기적으로 변경하는 것이 가장 좋습니다. 나중에 사용할 수 있도록 새로운 온보드 키 관리 암호를 스토리지 시스템 외부의 안전한 위치에 복사해야 합니다. 
---
= 온보드 키 관리 암호를 변경합니다
:allow-uri-read: 


[role="lead"]
온보드 키 관리 암호를 정기적으로 변경하는 것이 가장 좋습니다. 나중에 사용할 수 있도록 새로운 온보드 키 관리 암호를 스토리지 시스템 외부의 안전한 위치에 복사해야 합니다.

.필요한 것
* 이 작업을 수행하려면 클러스터 또는 SVM 관리자여야 합니다.
* 이 작업에는 고급 권한이 필요합니다.


.단계
. 고급 권한 레벨로 변경:
+
세트 프리빌리지 고급

. 온보드 키 관리 암호를 변경합니다.
+
[cols="25,75"]
|===


| 이 ONTAP 버전의 경우... | 이 명령 사용... 


 a| 
ONTAP 9.6 이상
 a| 
보안 키 관리자 온보드 업데이트 암호문



 a| 
ONTAP 9.5 이하
 a| 
보안 키 관리자 업데이트 암호문

|===
+
전체 명령 구문은 man 페이지를 참조하십시오.

+
다음 ONTAP 9.6 명령을 사용하면 'cluster1'의 온보드 키 관리 암호를 변경할 수 있습니다.

+
[listing]
----
clusterl::> security key-manager onboard update-passphrase
Warning: This command will reconfigure the cluster passphrase for onboard key management for Vserver "cluster1".
Do you want to continue? {y|n}: y
Enter current passphrase:
Enter new passphrase:
----
. 프롬프트에 y를 입력하여 온보드 키 관리 암호를 변경합니다.
. 현재 암호 프롬프트에 현재 암호를 입력합니다.
. 새 암호문 프롬프트에서 32자에서 256자 사이의 암호문을 입력하거나 64에서 256자 사이의 암호문을 "cc-mode"로 입력합니다.
+
지정된 ""cc-mode"" 암호가 64자 미만이면 키 관리자 설정 작업에 암호 프롬프트가 다시 표시되기 전에 5초의 지연이 발생합니다.

. 암호 확인 프롬프트에서 암호를 다시 입력합니다.


.작업을 마친 후
MetroCluster 환경에서는 파트너 클러스터의 암호를 업데이트해야 합니다.

* ONTAP 9.5 이전 버전에서는 파트너 클러스터에서 동일한 암호로 보안 키 관리자 업데이트 암호를 실행해야 합니다.
* ONTAP 9.6 이상에서는 파트너 클러스터에서 동일한 암호로 '보안 키 관리자 온보드 동기화'를 실행하라는 메시지가 표시됩니다.


나중에 사용할 수 있도록 온보드 키 관리 암호를 스토리지 시스템 외부의 안전한 위치에 복사해야 합니다.

온보드 키 관리 암호를 변경할 때마다 키 관리 정보를 수동으로 백업해야 합니다.

link:backup-key-management-information-manual-task.html["온보드 키 관리 정보를 수동으로 백업합니다"]
