---
permalink: encryption-at-rest/create-authentication-keys-93-later-task.html 
sidebar: sidebar 
keywords: creating, authentication keys, ontap 9.5, earlier 
summary: security key-manager create-key 명령을 사용하여 노드의 인증 키를 생성한 다음 구성된 KMIP 서버에 저장할 수 있습니다. 
---
= ONTAP 9.5 이전 버전에서 인증 키를 만듭니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
'Security key-manager create-key' 명령을 사용하여 노드의 인증 키를 생성한 후 구성된 KMIP 서버에 저장할 수 있습니다.

.필요한 것
이 작업을 수행하려면 클러스터 관리자여야 합니다.

.이 작업에 대해
보안 설정에서 데이터 인증과 FIPS 140-2 인증을 위해 다른 키를 사용해야 하는 경우 각각에 대해 별도의 키를 만들어야 합니다. 그렇지 않은 경우 데이터 액세스에 사용하는 FIPS 준수에 동일한 인증 키를 사용할 수 있습니다.

ONTAP은 클러스터의 모든 노드에 대해 인증 키를 생성합니다.

* 온보드 키 관리가 활성화된 경우 이 명령은 지원되지 않습니다.
* 구성된 키 관리 서버가 이미 128개 이상의 인증 키를 저장하고 있으면 경고가 표시됩니다.
+
키 관리 서버 소프트웨어를 사용하여 사용하지 않는 키를 삭제한 다음 명령을 다시 실행할 수 있습니다.



.단계
. 클러스터 노드의 인증 키를 생성합니다.
+
보안 키 관리자 만들기 키

+
전체 명령 구문은 명령에 대한 man 페이지를 참조하십시오.

+
[NOTE]
====
출력에 표시되는 키 ID는 인증 키를 참조하는 데 사용되는 식별자입니다. 실제 인증 키 또는 데이터 암호화 키가 아닙니다.

====
+
다음 예제에서는 "cluster1"에 대한 인증 키를 만듭니다.

+
[listing]
----
cluster1::> security key-manager create-key
   (security key-manager create-key)
Verifying requirements...

Node: cluster1-01
Creating authentication key...
Authentication key creation successful.
Key ID: F1CB30AFF1CB30B00101000000000000A68B167F92DD54196297159B5968923C

Node: cluster1-01
Key manager restore operation initialized.
Successfully restored key information.

Node: cluster1-02
Key manager restore operation initialized.
Successfully restored key information.
----
. 인증 키가 생성되었는지 확인합니다.
+
보안 키 관리자 쿼리

+
전체 명령 구문은 man 페이지를 참조하십시오.

+
다음 예제에서는 "cluster1"에 대해 인증 키가 생성되었는지 확인합니다.

+
[listing]
----
cluster1::> security key-manager query

  (security key-manager query)

          Node: cluster1-01
   Key Manager: 20.1.1.1
 Server Status: available

Key Tag        Key Type  Restored
-------------  --------  --------
cluster1-01    NSE-AK    yes
       Key ID: F1CB30AFF1CB30B00101000000000000A68B167F92DD54196297159B5968923C


          Node: cluster1-02
   Key Manager: 20.1.1.1
 Server Status: available

Key Tag        Key Type  Restored
-------------  --------  --------
cluster1-02    NSE-AK    yes
       Key ID: F1CB30AFF1CB30B00101000000000000A68B167F92DD54196297159B5968923C
----

