---
permalink: encryption-at-rest/emergency-shred-data-disks-storage-encryption-task.html 
sidebar: sidebar 
keywords: sanitize, fips, drive, sed, psid, physical secure ID, nrd plus, emergency 
summary: 보안 비상 시에 스토리지 시스템이나 KMIP 서버에서 전원을 사용할 수 없는 경우에도 FIPS 드라이브 또는 SED에 대한 액세스를 즉시 차단할 수 있습니다. 
---
= FIPS 드라이브 또는 SED의 긴급 데이터 삭제
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
보안 비상 시에 스토리지 시스템이나 KMIP 서버에서 전원을 사용할 수 없는 경우에도 FIPS 드라이브 또는 SED에 대한 액세스를 즉시 차단할 수 있습니다.

.시작하기 전에
* KMIP 서버를 사용할 때 전원이 공급되지 않는 경우, 쉽게 파괴되는 인증 항목(예: 스마트 카드 또는 USB 드라이브)으로 KMIP 서버를 구성해야 합니다.
* 이 작업을 수행하려면 클러스터 관리자여야 합니다.


.단계
. FIPS 드라이브 또는 SED에서 긴급 데이터 파쇄 수행:
+
|===


| 만약... 2+| 그러면... 


 a| 
스토리지 시스템에서 전원을 사용할 수 있으며 스토리지 시스템을 오프라인으로 전환할 수 있는 시간이 있습니다
 a| 
.. 스토리지 시스템이 HA 쌍으로 구성된 경우 Takeover를 해제합니다.
.. 모든 애그리게이트를 오프라인 상태로 전환하고 삭제합니다.
.. 권한 수준을 advanced:+'et-Privilege advanced로 설정합니다
.. 드라이브가 FIPS 준수 모드에 있는 경우 노드에 대한 FIPS 인증 키 ID를 기본 MSID(+'STorage encryption disk modify -disk * -FIPS-key -id 0x0'로 다시 설정합니다
.. 스토리지 시스템을 중단합니다.
.. 유지보수 모드로 부팅합니다.
.. 디스크를 완전 삭제 또는 폐기:
+
*** 디스크의 데이터에 액세스할 수 없도록 하고 디스크를 다시 사용할 수 있도록 하려면 + 디스크 암호화 sanitize-all을 선택합니다
*** 디스크에 있는 데이터에 액세스할 수 없도록 하고 디스크를 저장할 필요가 없으면 + 디스크 암호화 destroy disk_id1 disk_id2…"를 삭제합니다


+

NOTE: 디스크 암호화 삭제 및 디스크 암호화 삭제 명령은 유지 보수 모드에만 사용됩니다. 이러한 명령은 각 HA 노드에서 실행해야 하며 깨진 디스크에는 사용할 수 없습니다.

.. 파트너 노드에 대해 이 단계를 반복합니다. 이렇게 하면 스토리지 시스템이 영구적으로 비활성화되며 모든 데이터가 지워집니다. 시스템을 다시 사용하려면 다시 구성해야 합니다.




 a| 
스토리지 시스템에서 전원을 사용할 수 있으며 데이터를 즉시 제거해야 합니다
 a| 
.. * 디스크에 있는 데이터에 액세스할 수 없도록 만들고 디스크를 다시 사용하려면 디스크를 삭제해야 합니다. *
.. 스토리지 시스템이 HA 쌍으로 구성된 경우 Takeover를 해제합니다.
.. 권한 수준을 고급으로 설정합니다.
+
세트 프리빌리지 고급

.. 드라이브가 FIPS 준수 모드인 경우 노드의 FIPS 인증 키 ID를 다시 기본 MSID로 설정합니다.
+
'Storage encryption disk modify -disk * -FIPS-key-id 0x0'

.. 디스크 완전 삭제:
+
스토리지 암호화 디스크 완전 삭제 -disk * -force -all -states true


 a| 
.. * 디스크에 있는 데이터에 액세스할 수 없도록 하고 디스크를 저장할 필요가 없는 경우, 다음 디스크를 파기하십시오: *
.. 스토리지 시스템이 HA 쌍으로 구성된 경우 Takeover를 해제합니다.
.. 권한 수준을 고급으로 설정합니다.
+
세트 프리빌리지 고급

.. 디스크 폐기: 스토리지 암호화 디스크 destroy-disk * -force-all-states true




 a| 
스토리지 시스템에서 패닉이 발생하고 모든 데이터가 지워져 시스템이 영구적으로 비활성화된 상태로 유지됩니다. 시스템을 다시 사용하려면 다시 구성해야 합니다.



 a| 
KMIP 서버에서 전원을 사용할 수 있지만 스토리지 시스템은 사용할 수 없습니다
 a| 
.. KMIP 서버에 로그인합니다.
.. 액세스를 방지하려는 데이터가 포함된 FIPS 드라이브 또는 SED와 연결된 모든 키를 제거합니다. 이렇게 하면 스토리지 시스템에서 디스크 암호화 키에 액세스할 수 없습니다.




 a| 
KMIP 서버 또는 스토리지 시스템에서 전원을 사용할 수 없습니다
 a| 
KMIP 서버용 인증 항목(예: 스마트 카드)을 제거합니다. 이렇게 하면 스토리지 시스템에서 디스크 암호화 키에 액세스할 수 없습니다.

|===
+
전체 명령 구문은 man 페이지를 참조하십시오.


