---
permalink: encryption-at-rest/enable-encryption-new-volume-task.html 
sidebar: sidebar 
keywords: encryption, new volume, NAE, NVE, volume create 
summary: 볼륨 생성 명령을 사용하여 새 볼륨에서 암호화를 활성화할 수 있습니다. 
---
= 새 볼륨에서 암호화를 활성화합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
'volume create' 명령을 사용하여 새 볼륨에서 암호화를 활성화할 수 있습니다.

.이 작업에 대해
NVE(NetApp Volume Encryption)를 사용하여 볼륨을 암호화하고 ONTAP 9.6, NetApp Aggregate Encryption(NAE)로 시작할 수 있습니다. NAE와 NVE에 대한 자세한 내용은 를 참조하십시오 xref:configure-netapp-volume-encryption-concept.html[볼륨 암호화 개요].

ONTAP에서 새 볼륨에 대한 암호화를 활성화하는 절차는 사용 중인 ONTAP 버전과 특정 구성에 따라 다릅니다.

* ONTAP 9.4부터 시작합니다(사용하는 경우) `cc-mode` Onboard Key M anager(온보드 키 관리자)를 설정할 때 로 생성한 볼륨입니다 `volume create` 명령은 사용자가 지정하든 관계없이 자동으로 암호화됩니다 `-encrypt true`.
* ONTAP 9.6 및 이전 버전에서는 을 사용해야 합니다 `-encrypt true` 와 함께 `volume create` 암호화를 활성화하는 명령(사용하지 않은 경우 `cc-mode`)를 클릭합니다.
* ONTAP 9.6에서 NAE 볼륨을 작성하려면 집계 수준에서 NAE를 활성화해야 합니다. 을 참조하십시오 xref:enable-aggregate-level-encryption-nve-license-task.html[VE 라이센스로 애그리게이트 레벨 암호화를 설정합니다] 를 참조하십시오.
* ONTAP 9.7부터는 VE 라이센스 및 온보드 키 또는 외부 키 관리 기능이 있는 경우 새로 생성된 볼륨이 기본적으로 암호화됩니다. 기본적으로 NAE 애그리게이트에서 생성된 새 볼륨은 NVE가 아닌 NAE 유형이 됩니다.
+
** ONTAP 9.7 이상 릴리즈에서 추가하는 경우 `-encrypt true` 를 누릅니다 `volume create` NAE 애그리게이트에서 볼륨을 생성하는 명령은 볼륨에 NAE 대신 NVE 암호화가 있습니다. NAE 애그리게이트의 모든 볼륨은 NVE 또는 NAE로 암호화되어야 합니다.





NOTE: NAE 애그리게이트에서는 일반 텍스트 볼륨이 지원되지 않습니다.

.단계
. 새 볼륨을 생성하고 볼륨에 암호화가 활성화되어 있는지 여부를 지정합니다. 새 볼륨이 NAE 애그리게이트에 있는 경우 기본적으로 볼륨은 다음 NAE 볼륨이 됩니다.
+
[cols="25,75"]
|===


| 생성 방법... | 이 명령 사용... 


 a| 
NAE 볼륨
 a| 
`volume create -vserver _SVM_name_ -volume _volume_name_ -aggregate _aggregate_name_`



 a| 
NVE 볼륨
 a| 
`volume create -vserver _SVM_name_ -volume _volume_name_ -aggregate _aggregate_name_ -encrypt true` 를 누릅니다


NOTE: NAE가 지원되지 않는 ONTAP 9.6 및 이전 버전에서는 `-encrypt true` NVE를 사용하여 볼륨을 암호화하도록 지정합니다. NAE 애그리게이트에서 볼륨이 생성되는 ONTAP 9.7 이상에서는 `-encrypt true` 대신 NAE의 기본 암호화 유형을 재정의하여 NVE 볼륨을 생성합니다.



 a| 
일반 텍스트 볼륨입니다
 a| 
`volume create -vserver _SVM_name_ -volume _volume_name_ -aggregate _aggregate_name_ -encrypt false`

|===
+
전체 명령 구문은 https://docs.netapp.com/us-en/ontap-cli-9131/volume-create.html 링크에 대한 명령 참조 페이지를 참조하십시오[`volume create`^].

. 볼륨에 암호화가 설정되어 있는지 확인합니다.
+
볼륨 쇼는 암호화된 사실이다

+
전체 명령 구문은 을 참조하십시오 link:https://docs.netapp.com/us-en/ontap-cli-9131/volume-show.html["명령 참조"^].



.결과
KMIP 서버를 사용하여 노드의 암호화 키를 저장하는 경우, ONTAP는 볼륨을 암호화할 때 암호화 키를 서버에 자동으로 "푸시" 합니다.
