---
permalink: encryption-at-rest/enable-aggregate-level-encryption-nve-license-task.html 
sidebar: sidebar 
keywords: enabling, aggregate-level, encryption, nve, ve license, license 
summary: ONTAP 9.7부터 VE 라이센스 및 온보드 키 관리 기능이 있는 경우 새로 생성된 애그리게이트 및 볼륨은 기본적으로 암호화됩니다. ONTAP 9.6부터 애그리게이트 레벨 암호화를 사용하여 암호화할 볼륨에 포함된 애그리게이트에 키를 할당할 수 있습니다. Aggregate에서 생성한 볼륨은 기본적으로 암호화됩니다. 볼륨을 암호화할 때 기본값을 재정의할 수 있습니다. 
---
= VE 라이센스로 애그리게이트 레벨 암호화를 설정합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9.7부터 VE 라이센스 및 온보드 키 관리 기능이 있는 경우 새로 생성된 애그리게이트 및 볼륨은 기본적으로 암호화됩니다. ONTAP 9.6부터 애그리게이트 레벨 암호화를 사용하여 암호화할 볼륨에 포함된 애그리게이트에 키를 할당할 수 있습니다. Aggregate에서 생성한 볼륨은 기본적으로 암호화됩니다. 볼륨을 암호화할 때 기본값을 재정의할 수 있습니다.

이 작업을 수행하려면 클러스터 관리자여야 합니다.

인라인 또는 백그라운드 애그리게이트 레벨 중복제거를 수행하려는 경우 애그리게이트 레벨 암호화를 사용해야 합니다. 그 외에는 NVE에서 애그리게이트 레벨의 중복제거가 지원되지 않습니다.

애그리게이트 레벨 암호화를 위해 활성화된 애그리게이트를 _NAE aggregate_(NetApp 애그리게이트 암호화의 경우)라고 합니다. NAE 애그리게이트에서는 일반 텍스트 볼륨이 지원되지 않습니다.

.단계
. 애그리게이트 레벨 암호화 활성화 또는 비활성화:
+
[cols="40,60"]
|===


| 대상... | 이 명령 사용... 


 a| 
ONTAP 9.7 이상을 사용하여 NAE 애그리게이트를 생성합니다
 a| 
'Storage aggregate create-aggregate aggregate_name-node node_name'



 a| 
ONTAP 9.6으로 NAE 애그리게이트를 생성합니다
 a| 
'storage aggregate create-aggregate aggregate_name-node_name-encrypt-with-aggr-key true'



 a| 
NAE가 아닌 집계를 NAE 집계로 변환합니다
 a| 
'STORAGE AGGREGATE - AGGATE AGGATE_NAME - NODE_NAME - encrypt - with - aggr - key true'



 a| 
NAE 집계를 NAE가 아닌 집집합으로 변환합니다
 a| 
'STORAGE AGGREGATE-AGGATE AGGATE_NAME-NODE_NAME-ENCREMY-with-aggr-KEY FALSE'

|===
+
전체 명령 구문은 man 페이지를 참조하십시오.

+
다음 명령을 실행하면 "aggr1"에서 집계 수준 암호화가 활성화됩니다.

+
** ONTAP 9.7 이상:
+
[listing]
----
cluster1::> storage aggregate create -aggregate aggr1
----
** ONTAP 9.6 이하:
+
[listing]
----
cluster1::> storage aggregate create -aggregate aggr1 -encrypt-with-aggr-key true
----


. Aggregate가 암호화를 사용하도록 설정되어 있는지 확인합니다.
+
'스토리지 집계 표시 필드 암호화 - 집계 키 사용'

+
전체 명령 구문은 man 페이지를 참조하십시오.

+
다음 명령을 실행하면 "aggr1"이 암호화에 대해 활성화되어 있는지 확인합니다.

+
[listing]
----
cluster1::> storage aggregate show -fields encrypt-with-aggr-key
aggregate            encrypt-aggr-key
-------------------- ----------------
aggr0_vsim4          false
aggr1                true
2 entries were displayed.
----


'volume create' 명령을 실행하여 암호화된 볼륨을 생성합니다.

KMIP 서버를 사용하여 노드의 암호화 키를 저장하는 경우, ONTAP는 볼륨을 암호화할 때 암호화 키를 서버에 자동으로 "푸시"(푸시)"합니다.
