---
permalink: encryption-at-rest/enable-cluster-fips-compliant-mode-task.html 
sidebar: sidebar 
keywords: enabling, cluster-wide, fips-compliant mode, kmip, server, connections 
summary: 보안 구성 수정 명령을 -is-FIPS 지원 옵션과 함께 사용하여 사용 중인 데이터에 대해 클러스터 차원의 FIPS 호환 모드를 설정할 수 있습니다. 이렇게 하면 클러스터가 KMIP 서버에 연결할 때 FIPS 모드에서 OpenSSL을 사용하게 됩니다. 
---
= KMIP 서버 연결을 위해 클러스터 차원의 FIPS 호환 모드를 지원합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
'보안 구성 수정' 명령을 -FIPS 사용' 옵션과 함께 사용하면 전송 중인 데이터에 대해 클러스터 차원의 FIPS 호환 모드를 사용할 수 있습니다. 이렇게 하면 클러스터가 KMIP 서버에 연결할 때 FIPS 모드에서 OpenSSL을 사용하게 됩니다.

.시작하기 전에
* 스토리지 컨트롤러는 FIPS 호환 모드로 구성해야 합니다.
* 모든 KMIP 서버는 TLSv1.2를 지원해야 합니다. TLSv1.2는 클러스터 차원의 FIPS 호환 모드가 활성화된 경우 KMIP 서버에 대한 연결을 완료해야 합니다.


클러스터 전반의 FIPS 호환 모드를 사용하도록 설정하면 클러스터에서 TLS1.2 및 FIPS 인증 암호 그룹만 자동으로 사용됩니다. 클러스터 차원의 FIPS 호환 모드는 기본적으로 해제되어 있습니다.

클러스터 전체 보안 구성을 수정한 후에는 클러스터 노드를 수동으로 재부팅해야 합니다.



== ONTAP 9.11.1 RC1 고려 사항

ONTAP 버전 9.11.1RC1의 변경으로 인해 FIPS 140-2 규정 준수 관리 모드는 더 이상 FIPS 140-2 검증 소프트웨어 모듈을 사용하지 않습니다.

ONTAP 9.11.1 RC1은 HTTPS용 관리 및 컨트롤 플레인 연결에 사용되는 OpenSSL 버전을 업그레이드했습니다. 이 버전의 OpenSSL(OpenSSL 3.x FIPS Provider)은 FIPS 140-2 CMVP(Cryptographic Module Validation Program) 검증 프로세스를 아직 완료하지 않았습니다.

FIPS 준수 모드가 활성화되면 HTTPS 연결에 사용되는 암호화 알고리즘은 CAVP(Cryptographic Algorithm Validation Program) 인증서 A1938에서 발급된 OpenSSL Project OpenSSL 3.x FIPS Provider 알고리즘과 동일합니다. * 이 변경은 FIPS 준수 모드로 구성된 ONTAP 시스템에만 영향을 줍니다. *

ONTAP 9.11.1 RC1에 있는 업그레이드된 OpenSSL 모듈이 NIST와 함께 FIPS 140-2 검증을 완료하면 이 문제가 해결됩니다. FIPS 140-2 CMVP 검증 모듈을 사용하여 ONTAP 클러스터 관리 컨트롤 플레인을 실행해야 하는 환경에서는 9.11.1 RC1로 업그레이드하지 않는 것이 좋습니다.

NSE, NVE, NAE와 같은 유휴 데이터의 NetApp 암호화 기술에는 영향을 미치지 않습니다. 이러한 기능이 ONTAP의 OpenSSL에서 제공하는 암호화 모듈과 다른 암호화 모듈을 사용하기 때문입니다.

자세한 내용은 을 참조하십시오 link:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/Upgrading_to_ONTAP_9.11.1RC1_results_in_FIPS_140-2_compliance_management_configuration_that_is_not_validated["ONTAP 9.11.1 RC1로 업그레이드하면 FIPS 140-2 규정 준수 관리 구성이 확인되지 않습니다"^]

.단계
. 권한 수준을 고급으로 설정합니다.
+
세트 프리빌리지 고급

. TLSv1.2가 지원되는지 확인합니다.
+
'보안 설정 표시 - 지원 - 프로토콜'

+
전체 명령 구문은 man 페이지를 참조하십시오.

+
[listing]
----
cluster1::> security config show
          Cluster                                              Cluster Security
Interface FIPS Mode  Supported Protocols     Supported Ciphers Config Ready
--------- ---------- ----------------------- ----------------- ----------------
SSL       false      TLSv1.2, TLSv1.1, TLSv1 ALL:!LOW:         yes
                                             !aNULL:!EXP:
                                             !eNULL
----
. 클러스터 전체 FIPS 호환 모드 사용:
+
보안 설정 수정 - FIPS 활성화 True-Interface SSL

+
전체 명령 구문은 man 페이지를 참조하십시오.

. 클러스터 노드를 수동으로 재부팅합니다.
. 클러스터 차원에서 FIPS 호환 모드가 활성화되어 있는지 확인합니다.
+
'보안 구성 쇼'

+
[listing]
----
cluster1::> security config show
          Cluster                                              Cluster Security
Interface FIPS Mode  Supported Protocols     Supported Ciphers Config Ready
--------- ---------- ----------------------- ----------------- ----------------
SSL       true       TLSv1.2, TLSv1.1        ALL:!LOW:         yes
                                             !aNULL:!EXP:
                                             !eNULL:!RC4
----

