---
permalink: encryption-at-rest/encrypt-existing-volume-task.html 
sidebar: sidebar 
keywords: enabling, encryption, existing, volume, volume move start, command 
summary: 볼륨 이동 시작 명령을 사용하여 기존 볼륨을 이동하여 암호화를 활성화할 수 있습니다. ONTAP 9.2 이하에서는 볼륨 이동 시작을 사용해야 합니다. 동일한 애그리게이트 또는 다른 애그리게이트를 사용할 수 있습니다. 
---
= 볼륨 이동 시작 명령을 사용하여 기존 볼륨에서 암호화를 활성화합니다
:icons: font
:imagesdir: ../media/


[role="lead"]
'volume move start' 명령을 사용하여 기존 볼륨을 이동하여 암호화를 활성화할 수 있습니다. ONTAP 9.2 이하에서는 볼륨 이동 시작을 사용해야 합니다. 동일한 애그리게이트 또는 다른 애그리게이트를 사용할 수 있습니다.

이 작업을 수행하려면 클러스터 관리자이거나 클러스터 관리자가 권한을 위임한 SVM 관리자여야 합니다.

link:delegate-volume-encryption-svm-administrator-task.html["볼륨 이동 명령을 실행하는 위임 권한"]

ONTAP 9.8부터 볼륨 이동 시작을 사용하여 SnapLock 또는 FlexGroup 볼륨에서 암호화를 활성화할 수 있습니다.

ONTAP 9.4부터 Onboard Key Manager를 설정할 때 ""cc-mode""를 활성화하면 "volume move start" 명령으로 생성한 볼륨이 자동으로 암호화됩니다. `-encrypt-destination true'는 지정하지 않아도 됩니다.

ONTAP 9.6부터는 Aggregate 수준의 암호화를 사용하여 이동할 볼륨의 포함된 Aggregate에 키를 할당할 수 있습니다. 고유 키로 암호화된 볼륨을 _NVE 볼륨 _ 이라고 합니다. 애그리게이트 레벨 키로 암호화된 볼륨을 _NAE 볼륨 _ (NetApp 애그리게이트 암호화의 경우)이라고 합니다. NAE 애그리게이트에서는 일반 텍스트 볼륨이 지원되지 않습니다.

.단계
. 기존 볼륨을 이동하고 볼륨에 암호화가 활성화되어 있는지 여부를 지정합니다.
+
[cols="35,65"]
|===


| 변환... | 이 명령 사용... 


 a| 
NVE 볼륨에 대한 일반 텍스트 볼륨입니다
 a| 
'volume move start -vserver SVM_name -volume volume_name -destination -aggregate aggregate_name -encrypt -destination TRUE'



 a| 
NAE 볼륨에 대한 NVE 또는 일반 텍스트 볼륨(대상에 애그리게이트 레벨 암호화가 사용되는 것으로 가정)
 a| 
'volume move start -vserver SVM_name -volume volume_name -destination -aggregate aggregate_name -encrypt -with -aggr-key true'



 a| 
NVE 볼륨에 대한 NAE 볼륨
 a| 
'volume move start -vserver SVM_name -volume volume_name -destination -aggregate aggregate_name -encrypt -with -aggr -key false'



 a| 
Nae 볼륨을 일반 텍스트 볼륨으로
 a| 
'volume move start -vserver SVM_name -volume volume_name -destination -aggregate_name -encrypt -destination false-encrypt -with-aggr-key false'



 a| 
NVE 볼륨을 일반 텍스트 볼륨으로
 a| 
'volume move start-vserver SVM_name-volume volume_name-destination-aggregate aggregate_name-encrypt-destination false'

|===
+
전체 명령 구문은 명령에 대한 man 페이지를 참조하십시오.

+
다음 명령을 실행하면 이름이 vol1인 일반 텍스트 볼륨이 NVE 볼륨으로 변환됩니다.

+
[listing]
----
cluster1::> volume move start -vserver vs1 -volume vol1 -destination-aggregate aggr2 -encrypt-destination true
----
+
대상에서 애그리게이트 레벨 암호화를 사용하도록 설정한 경우 다음 명령을 실행하면 NVE 볼륨이나 일반 텍스트 볼륨 vol1이 NAE 볼륨으로 변환됩니다.

+
[listing]
----
cluster1::> volume move start -vserver vs1 -volume vol1 -destination-aggregate aggr2 -encrypt-with-aggr-key true
----
+
다음 명령을 실행하면 이름이 vol2인 NAE 볼륨이 NVE 볼륨으로 변환됩니다.

+
[listing]
----
cluster1::> volume move start -vserver vs1 -volume vol2 -destination-aggregate aggr2 -encrypt-with-aggr-key false
----
+
다음 명령을 실행하면 이름이 vol2인 NAE 볼륨이 일반 텍스트 볼륨으로 변환됩니다.

+
[listing]
----
cluster1::> volume move start -vserver vs1 -volume vol2 -destination-aggregate aggr2 -encrypt-destination false -encrypt-with-aggr-key false
----
+
다음 명령을 실행하면 이름이 vol2인 NVE 볼륨이 일반 텍스트 볼륨으로 변환됩니다.

+
[listing]
----
cluster1::> volume move start -vserver vs1 -volume vol2 -destination-aggregate aggr2 -encrypt-destination false
----
. 클러스터 볼륨의 암호화 유형을 확인합니다.
+
'볼륨 표시 필드 암호화 - 없음|볼륨|집계'를 입력합니다

+
암호화 유형 필드는 ONTAP 9.6 이상에서 사용할 수 있습니다.

+
전체 명령 구문은 명령에 대한 man 페이지를 참조하십시오.

+
다음 명령을 실행하면 'cluster2'의 볼륨 암호화 유형이 표시됩니다.

+
[listing]
----
cluster2::> volume show -fields encryption-type

vserver  volume  encryption-type
-------  ------  ---------------
vs1      vol1    none
vs2      vol2    volume
vs3      vol3    aggregate
----
. 볼륨에 암호화가 설정되어 있는지 확인합니다.
+
볼륨 쇼는 암호화된 사실이다

+
전체 명령 구문은 명령에 대한 man 페이지를 참조하십시오.

+
다음 명령을 실행하면 암호화된 볼륨이 'cluster2'에 표시됩니다.

+
[listing]
----
cluster2::> volume show -is-encrypted true

Vserver  Volume  Aggregate  State  Type  Size  Available  Used
-------  ------  ---------  -----  ----  -----  --------- ----
vs1      vol1    aggr2     online    RW  200GB    160.0GB  20%
----


KMIP 서버를 사용하여 노드의 암호화 키를 저장하는 경우, ONTAP는 볼륨을 암호화할 때 암호화 키를 서버에 자동으로 "푸시"(푸시)"합니다.
