---
permalink: encryption-at-rest/key-management-servers-not-reachable-boot-concept.html 
sidebar: sidebar 
keywords: what, happens, key management servers, not reachable, boot, process 
summary: ONTAP는 NSE에 구성된 스토리지 시스템이 부팅 프로세스 중 지정된 키 관리 서버에 연결할 수 없는 경우 원치 않는 동작을 방지하기 위해 특정 예방 조치를 취합니다. 
---
= 부팅 프로세스 중에 키 관리 서버에 연결할 수 없는 경우 발생하는 현상
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP는 NSE에 구성된 스토리지 시스템이 부팅 프로세스 중 지정된 키 관리 서버에 연결할 수 없는 경우 원치 않는 동작을 방지하기 위해 특정 예방 조치를 취합니다.

스토리지 시스템이 NSE에 맞게 구성되고 SED가 리키 입력 및 잠겨 있고 SED의 전원이 켜져 있는 경우, 스토리지 시스템은 SED에 액세스하기 전에 키 관리 서버에서 필요한 인증 키를 검색하여 SED에 대한 자체 인증을 해야 합니다.

스토리지 시스템은 지정된 키 관리 서버에 최대 3시간 동안 접속을 시도합니다. 이 시간 이후에 스토리지 시스템이 해당 시스템에 연결할 수 없는 경우 부팅 프로세스가 중지되고 스토리지 시스템이 중지됩니다.

스토리지 시스템이 지정된 키 관리 서버에 성공적으로 접속하면 최대 15분 동안 SSL 연결을 시도합니다. 스토리지 시스템이 지정된 키 관리 서버와 SSL 연결을 설정할 수 없는 경우 부팅 프로세스가 중지되고 스토리지 시스템이 중지됩니다.

스토리지 시스템이 키 관리 서버에 연결하여 연결을 시도하는 동안 CLI에서 실패한 연결 시도에 대한 자세한 정보가 표시됩니다. Ctrl+C를 누르면 언제든지 연결 시도를 중단할 수 있습니다

보안 조치로서 SED는 제한된 수의 무단 액세스 시도만 허용하며, 그 이후에는 기존 데이터에 대한 액세스를 차단합니다. 스토리지 시스템이 지정된 키 관리 서버에 연결할 수 없어 적절한 인증 키를 얻을 수 없는 경우 기본 키로만 인증을 시도하여 시도 실패 및 패닉이 발생할 수 있습니다. 패닉이 발생할 경우 스토리지 시스템이 자동으로 재부팅되도록 구성된 경우 부팅 루프로 진입하여 SED에서 지속적인 인증 실패를 초래하게 됩니다.

이러한 시나리오에서 스토리지 시스템을 중단하는 것은 스토리지 시스템이 부팅 루프에 진입하지 못하도록 하는 것으로, SED가 영구적으로 잠기면 특정 횟수의 연속 인증 실패 횟수를 초과하여 의도하지 않은 데이터가 손실될 수 있습니다. 잠금 보호의 제한 및 유형은 제조 사양 및 SED 유형에 따라 다릅니다.

[cols="30,15,55"]
|===


| SED 유형 | 연속 실패한 인증 시도 횟수로 인해 잠금이 발생합니다 | 안전 한도에 도달하면 잠금 보호 유형입니다 


 a| 
HDD
 a| 
1024
 a| 
영구. 적절한 인증 키를 다시 사용할 수 있는 경우에도 데이터를 복구할 수 없습니다.



 a| 
펌웨어 버전 NA00 또는 NA01이 있는 X440_PHM2800MCTO 800GB NSE SSD
 a| 
5
 a| 
임시. 잠금 기능은 디스크 전원을 껐다가 다시 켤 때까지만 적용됩니다.



 a| 
펌웨어 버전 NA00 또는 NA01이 있는 X577_PHM2800MCTO 800GB NSE SSD
 a| 
5
 a| 
임시. 잠금 기능은 디스크 전원을 껐다가 다시 켤 때까지만 적용됩니다.



 a| 
더 높은 펌웨어 버전의 X440_PHM2800MCTO 800GB NSE SSD
 a| 
1024
 a| 
영구. 적절한 인증 키를 다시 사용할 수 있는 경우에도 데이터를 복구할 수 없습니다.



 a| 
펌웨어 버전이 더 높은 X577_PHM2800MCTO 800GB NSE SSD
 a| 
1024
 a| 
영구. 적절한 인증 키를 다시 사용할 수 있는 경우에도 데이터를 복구할 수 없습니다.



 a| 
그 외 모든 SSD 모델
 a| 
1024
 a| 
영구. 적절한 인증 키를 다시 사용할 수 있는 경우에도 데이터를 복구할 수 없습니다.

|===
모든 SED 유형의 경우 인증에 성공하면 시도 횟수가 0으로 재설정됩니다.

지정된 키 관리 서버에 도달하지 못해 스토리지 시스템이 중단된 경우 스토리지 시스템 부팅을 계속 시도하기 전에 먼저 통신 장애의 원인을 파악하고 수정해야 합니다.
