---
permalink: encryption-at-rest/move-encrypted-volume-task.html 
sidebar: sidebar 
keywords: moving, encrypted, volume 
summary: 볼륨 이동 시작 명령을 사용하여 암호화된 볼륨을 이동할 수 있습니다. 이동된 볼륨은 동일한 애그리게이트 또는 다른 애그리게이트에 있을 수 있습니다. 
---
= 암호화된 볼륨을 이동합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
'volume move start' 명령을 사용하여 암호화된 볼륨을 이동할 수 있습니다. 이동된 볼륨은 동일한 애그리게이트 또는 다른 애그리게이트에 있을 수 있습니다.

.이 작업에 대해
대상 노드 또는 대상 볼륨이 볼륨 암호화를 지원하지 않으면 이동이 실패합니다.

를 클릭합니다 `-encrypt-destination` 의 옵션입니다 `volume move start` 암호화된 볼륨의 경우 기본적으로 true입니다. 대상 볼륨을 암호화하지 않도록 지정해야 하는 요구 사항은 볼륨의 데이터를 실수로 암호화 해제하지 않도록 합니다.

.시작하기 전에
이 작업을 수행하려면 클러스터 관리자여야 합니다. 또는 클러스터 관리자가 권한을 위임한 SVM 관리자일 수 있습니다. 자세한 내용은 을 참조하십시오 link:delegate-volume-encryption-svm-administrator-task.html["볼륨 이동 명령을 실행할 수 있는 권한을 위임합니다"].

.단계
. 암호화된 기존 볼륨을 이동하고 볼륨의 데이터를 암호화된 상태로 유지:
+
`volume move start -vserver _SVM_name_ -volume _volume_name_ -destination-aggregate _aggregate_name_`

+
전체 명령 구문은 명령에 대한 man 페이지를 참조하십시오.

+
다음 명령을 실행하면 이름이 "vol1"인 기존 볼륨이 대상 애그리게이트 "aggr3"으로 이동하고 볼륨의 데이터가 암호화된 상태로 유지됩니다.

+
[listing]
----
cluster1::> volume move start -vserver vs1 -volume vol1 -destination-aggregate aggr3
----
. 볼륨에 암호화가 활성화되어 있는지 확인합니다.
+
볼륨 쇼는 암호화된 사실이다

+
전체 명령 구문은 명령에 대한 man 페이지를 참조하십시오.

+
다음 명령을 실행하면 암호화된 볼륨이 'cluster1'에 표시됩니다.

+
[listing]
----
cluster1::> volume show -is-encrypted true

Vserver  Volume  Aggregate  State  Type  Size  Available  Used
-------  ------  ---------  -----  ----  -----  --------- ----
vs1      vol1    aggr3     online    RW  200GB    160.0GB  20%
----

