---
permalink: encryption-at-rest/purge-data-encrypted-volume-synchronous-snapmirror-task.html 
sidebar: sidebar 
keywords: secure, purge, scrub, data, encrypted, volume, nve, netapp, volume encryption, snapmirror, synchronous 
summary: 'ONTAP 9.8부터는 SnapMirror 동기식 관계를 통해 NVE 지원 볼륨에서 보안 퍼지를 사용하여 중단 없이 데이터를 "스크럽"할 수 있습니다.' 
---
= SnapMirror 동기식 관계를 통해 암호화된 볼륨의 데이터를 스크럽합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9.8부터 SnapMirror 동기식 관계를 통해 NVE 지원 볼륨에서 보안 삭제를 사용하여 중단 없이 데이터를 "스크럽"할 수 있습니다.

.이 작업에 대해
삭제된 파일의 데이터 양에 따라 보안 제거를 완료하는 데 몇 분에서 몇 시간까지 걸릴 수 있습니다. 'volume encryption secure-purge show' 명령을 사용하여 작업 상태를 볼 수 있습니다. 'volume encryption secure-purge abort' 명령을 사용하여 작업을 종료할 수 있습니다.


NOTE: SAN 호스트에서 보안 제거를 수행하려면 제거할 파일이 포함된 전체 LUN을 삭제하거나 제거할 파일에 속한 블록에 대해 LUN에서 구멍을 뚫을 수 있어야 합니다. LUN을 삭제할 수 없거나 호스트 운영 체제에서 LUN의 구멍을 뚫을 수 없는 경우 보안 제거를 수행할 수 없습니다.

.시작하기 전에
* 이 작업을 수행하려면 클러스터 관리자여야 합니다.
* 이 작업에는 고급 권한이 필요합니다.


.단계
. 스토리지 시스템에서 고급 권한 레벨로 변경합니다.
+
세트 프리빌리지 고급

. 안전하게 제거할 파일 또는 LUN을 삭제합니다.
+
** NAS 클라이언트에서 안전하게 제거할 파일을 삭제합니다.
** SAN 호스트에서 제거할 파일에 속한 블록에 대해 LUN에서 안전하게 지우거나 구멍을 뚫을 LUN을 삭제합니다.


. 안전하게 제거할 비동기 관계의 대상 볼륨을 준비합니다.
+
`volume encryption secure-purge start -vserver <SVM_name> -volume <volume_name> -prepare true`

+
SnapMirror 동기식 관계의 다른 볼륨에 대해 이 단계를 반복합니다.

. 안전하게 제거할 파일이 스냅샷 복사본에 있는 경우 다음과 같이 스냅샷 복사본을 삭제합니다.
+
`snapshot delete -vserver <SVM_name> -volume <volume_name> -snapshot <snapshot>`

. 보안 제거 파일이 기본 스냅샷 복사본 또는 공통 스냅샷 복사본에 있는 경우 SnapMirror를 업데이트하여 공통 스냅샷 복사본을 다음으로 이동합니다.
+
`snapmirror update -source-snapshot <snapshot_name> -destination-path <destination_path>`

+
두 개의 공통 스냅샷 복사본이 있으므로 이 명령을 두 번 실행해야 합니다.

. 보안 제거 파일이 애플리케이션 정합성이 보장된 스냅샷 복사본에 있는 경우 SnapMirror 동기식 관계의 두 볼륨 모두에서 스냅샷 복사본을 삭제합니다.
+
`snapshot delete -vserver <SVM_name> -volume <volume_name> -snapshot <snapshot>`

+
두 볼륨에서 이 단계를 수행합니다.

. 삭제된 파일을 안전하게 삭제:
+
`volume encryption secure-purge start -vserver <SVM_name> -volume <volume_name>`

+
SnapMirror 동기식 관계의 각 볼륨에 대해 이 단계를 반복합니다.

+
다음 명령을 실행하면 삭제된 파일이 SVM ""VS1""의 ""vol1""에서 안전하게 삭제됩니다.

+
[listing]
----
cluster1::> volume encryption secure-purge start -vserver vs1 -volume vol1
----
. 안전한 퍼지 작업의 상태를 확인합니다.
+
볼륨 암호화 보안 제거 쇼


