---
permalink: encryption-at-rest/restore-onboard-key-management-encryption-keys-task.html 
sidebar: sidebar 
keywords: restoring, onboard, key management encryption 
summary: 경우에 따라 온보드 키 관리 암호화 키를 복원해야 할 수도 있습니다. 키를 복원해야 한다는 것을 확인한 후에는 Onboard Key Manager를 설정하여 키를 복원할 수 있습니다. 
---
= 온보드 키 관리 암호화 키를 복원합니다
:icons: font
:imagesdir: ../media/


[role="lead"]
온보드 키 관리 암호화 키를 복원해야 하는 경우 먼저 키를 복원해야 하는지 확인한 다음 Onboard Key Manager를 설정하여 키를 복원할 수 있습니다.

.무엇을 &#8217;필요로 할거야
* NSE를 외부 키 관리(KMIP) 서버와 함께 사용할 경우 외부 키 관리자 데이터베이스를 삭제해야 합니다.
+
link:delete-key-management-database-task.html["외부 키 관리에서 온보드 키 관리로 전환"]

* 이 작업을 수행하려면 클러스터 관리자여야 합니다.




== ONTAP 9.6 이상에 대한 단계

. 키를 복원해야 하는지 확인합니다. +'보안 키 관리자 키 쿼리 - node_node_'
. ONTAP 9.8 이상을 실행 중이고 루트 볼륨이 암호화된 경우 이 작업이 완료됩니다 <<root_volume_encrypted>>.
+
ONTAP 9.6 또는 9.7을 실행 중이거나 ONTAP 9.8 이상을 실행 중이고 루트 볼륨이 암호화되지 않은 경우 이 단계를 건너뜁니다.

. 키 복원: + '보안 키 관리자 온보드 동기화
+
전체 명령 구문은 man 페이지를 참조하십시오.

+
다음 ONTAP 9.6 명령은 온보드 키 계층의 키를 동기화합니다.

+
[listing]
----
cluster1::> security key-manager onboard sync

Enter the cluster-wide passphrase for onboard key management in Vserver "cluster1"::    <32..256 ASCII characters long text>
----
. 암호 프롬프트에서 클러스터의 온보드 키 관리 암호를 입력합니다.




== ONTAP 9.5 이전 버전에 대한 단계

. 키를 복원해야 하는지 확인합니다. + '보안 키 관리자 키 쇼'
. ONTAP 9.8 이상을 실행 중이고 루트 볼륨이 암호화된 경우 다음 단계를 완료합니다.
+
ONTAP 9.6 또는 9.7을 실행 중이거나 ONTAP 9.8 이상을 실행 중이고 루트 볼륨이 암호화되지 않은 경우 이 단계를 건너뜁니다.

. 키 복원: + S/S Security Key-manager setup -node_node_
+
전체 명령 구문은 man 페이지를 참조하십시오.

. 암호 프롬프트에서 클러스터의 온보드 키 관리 암호를 입력합니다.




== 루트 볼륨이 암호화된 경우 단계를 수행합니다

ONTAP 9.8 이상을 실행 중이고 루트 볼륨이 암호화된 경우 부팅 메뉴를 사용하여 온보드 키 관리 복구 암호를 설정해야 합니다.

. 노드를 부팅 메뉴로 부팅하고 '(10) 온보드 키 관리 복구 비밀 설정' 옵션을 선택합니다.
. 이 옵션을 사용하려면 'y'를 입력합니다.
. 프롬프트에서 클러스터의 온보드 키 관리 암호를 입력합니다.
. 프롬프트에서 백업 키 데이터를 입력합니다.
+
노드가 부팅 메뉴로 돌아갑니다.

. 부팅 메뉴에서 '(1) Normal Boot' 옵션을 선택합니다.

