---
permalink: encryption-at-rest/return-self-encrypting-disks-keys-not-available-task.html 
sidebar: sidebar 
keywords: returning, fips, drive, sed, service, authentication, keys, lost 
summary: FIPS 드라이브 또는 SED가 영구적으로 인증 키를 분실하여 KMIP 서버에서 검색할 수 없는 경우, 시스템은 FIPS 드라이브 또는 SED를 파손된 것으로 처리합니다. 디스크의 데이터에 액세스하거나 복구할 수 없지만 SED의 미사용 공간을 데이터에 다시 사용할 수 있도록 하는 단계를 수행할 수 있습니다. 
---
= 인증 키가 손실되었을 때 ONTAP를 사용하여 FIPS 드라이브 또는 SED를 서비스 상태로 되돌립니다
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
FIPS 드라이브 또는 SED가 영구적으로 인증 키를 분실하여 KMIP 서버에서 검색할 수 없는 경우, 시스템은 FIPS 드라이브 또는 SED를 파손된 것으로 처리합니다. 디스크의 데이터에 액세스하거나 복구할 수 없지만 SED의 미사용 공간을 데이터에 다시 사용할 수 있도록 하는 단계를 수행할 수 있습니다.

.시작하기 전에
이 작업을 수행하려면 클러스터 관리자여야 합니다.

.이 작업에 대해
FIPS 드라이브 또는 SED의 인증 키가 영구적으로 손실되어 복구할 수 없는 경우에만 이 프로세스를 사용해야 합니다.

디스크가 분할되어 있는 경우 이 프로세스를 시작하기 전에 먼저 분할되지 않아야 합니다.


NOTE: 디스크 파티션 해제를 위한 명령은 diag 수준에서만 사용할 수 있으며 NetApp 지원 부서의 감독 하에 수행해야 합니다. ** 계속하기 전에 NetApp Support에 문의하는 것이 좋습니다. ** 기술 자료 문서를 참조할 수도 있습니다 link:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Systems/FAS_Systems/How_to_unpartition_a_spare_drive_in_ONTAP["ONTAP에서 스페어 드라이브의 파티션을 해제하는 방법"^].

.단계
. FIPS 드라이브 또는 SED를 서비스 상태로 되돌리기:
+
[cols="25,75"]
|===


| SED가 다음과 같은 경우 | 다음 단계 사용... 


 a| 
FIPS 호환 모드가 아니거나 FIPS 호환 모드에서는 FIPS 키를 사용할 수 없습니다
 a| 
.. 권한 수준을 Advanced:'Set-Privilege advanced'로 설정합니다
.. FIPS 키를 기본 제조 보안 ID 0x0:'스토리지 암호화 디스크 수정 - FIPS-key-id 0x0-DISK_DISK_id_'로 재설정합니다
.. 작업이 성공했는지 확인합니다. '스토리지 암호화 디스크 표시 상태' 작업이 실패하면 이 항목의 PSID 프로세스를 사용합니다.
.. 깨진 디스크 정리:'storage encryption disk sanitize -disk_disk_id_' 다음 단계로 진행하기 전에 'storage encryption disk show-status' 명령으로 작업이 성공했는지 확인합니다.
.. 삭제된 디스크:'storage disk unfail-spare true-disk_disk_id_'의 장애를 해제합니다
.. 디스크에 소유자가 있는지 확인합니다.
`storage disk show -disk _disk_id_`
 를 누릅니다
 디스크에 소유자가 없는 경우 하나를 할당합니다.
`storage disk assign -owner node -disk _disk_id_`
+
... 삭제할 디스크를 소유하는 노드에 대한 노드 선택을 입력합니다.
+
'system node run-node_node_name_'

+
를 실행합니다 `disk sanitize release` 명령.



.. 노드 쉘을 종료합니다. 디스크 장애 복구 다시 취소:
`storage disk unfail -spare true -disk _disk_id_`
.. 디스크가 이제 스페어이고 'storage disk show -disk_disk_id_'라는 Aggregate에서 재사용할 준비가 되었는지 확인합니다




 a| 
FIPS 준수 모드에서는 FIPS 키를 사용할 수 없으며 SED에는 레이블에 인쇄된 PSID가 있습니다
 a| 
.. 디스크 레이블에서 디스크의 PSID를 가져옵니다.
.. 권한 수준을 Advanced:'Set-Privilege advanced'로 설정합니다
.. 디스크를 출고 시 구성된 설정으로 재설정합니다. '스토리지 암호화 디스크 복원 - 원본-디스크_디스크_id_-psid_disk_physical_secure_id_' 다음 단계로 진행하기 전에 '저장소 암호화 디스크 표시-상태' 명령으로 작업이 성공했는지 확인합니다.
.. ONTAP 9.8P5 이하를 실행 중인 경우 다음 단계로 건너뜁니다. ONTAP 9.8P6 이상을 실행 중인 경우 살균된 디스크의 오류를 해제하십시오.
`storage disk unfail -disk _disk_id_`
.. 디스크에 소유자가 있는지 확인합니다.
`storage disk show -disk _disk_id_`
 를 누릅니다
 디스크에 소유자가 없는 경우 하나를 할당합니다.
`storage disk assign -owner node -disk _disk_id_`
+
... 삭제할 디스크를 소유하는 노드에 대한 노드 선택을 입력합니다.
+
'system node run-node_node_name_'

+
를 실행합니다 `disk sanitize release` 명령.



.. 노드 쉘을 종료합니다. 디스크 장애 복구 다시 취소:
`storage disk unfail -spare true -disk _disk_id_`
.. 디스크가 이제 스페어이고 'storage disk show -disk_disk_id_'라는 Aggregate에서 재사용할 준비가 되었는지 확인합니다


|===


이 절차에서 설명하는 명령에 대한 자세한 내용은 를 link:https://docs.netapp.com/us-en/ontap-cli/["ONTAP 명령 참조입니다"^]참조하십시오.
