---
permalink: encryption-at-rest/sanitize-fips-drive-sed-task.html 
sidebar: sidebar 
keywords: sanitizing, fips, drive, sed 
summary: FIPS 드라이브 또는 SED에 있는 데이터를 영구적으로 액세스할 수 없도록 만들고 새 데이터에 드라이브를 사용하려면 스토리지 암호화 디스크 완전 삭제 명령을 사용하여 드라이브를 삭제할 수 있습니다. 
---
= FIPS 드라이브 또는 SED를 살균합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
FIPS 드라이브 또는 SED에 있는 데이터를 영구적으로 액세스할 수 없도록 만들고 새 데이터에 드라이브를 사용하려면 'Storage encryption disk sanitize' 명령을 사용하여 드라이브를 삭제할 수 있습니다.

이 작업을 수행하려면 클러스터 관리자여야 합니다.

자체 암호화 드라이브를 삭제할 때 시스템은 디스크 암호화 키를 새 임의 값으로 변경하고, 전원 켜짐 잠금 상태를 false로 재설정하고, 키 ID를 기본값으로 설정합니다(제조업체 보안 ID 0x0(SAS 드라이브) 또는 null 키(NVMe 드라이브)). 이렇게 하면 디스크의 데이터에 액세스할 수 없게 되고 데이터를 검색할 수 없게 됩니다. 삭제된 디스크를 제로화되지 않은 스페어 디스크로 다시 사용할 수 있습니다.

.단계
. 보존해야 하는 데이터를 다른 디스크의 Aggregate로 마이그레이션합니다.
. FIPS 드라이브 또는 SED에서 삭제되는 애그리게이트를 삭제합니다.
+
'Storage aggregate delete-aggregate_aggregate_name_'

+
전체 명령 구문은 man 페이지를 참조하십시오.

+
[listing]
----
cluster1::> storage aggregate delete -aggregate aggr1
----
. 삭제할 FIPS 드라이브 또는 SED의 디스크 ID 식별:
+
스토리지 암호화 디스크 데이터 필드 데이터 키 ID, FIPS 키 ID, 소유자

+
전체 명령 구문은 man 페이지를 참조하십시오.

+
[listing]
----
cluster1::> storage encryption disk show
Disk    Mode Data Key ID
-----   ---- ----------------------------------------------------------------
0.0.0   data F1CB30AFF1CB30B00101000000000000A68B167F92DD54196297159B5968923C
0.0.1   data F1CB30AFF1CB30B00101000000000000A68B167F92DD54196297159B5968923C
1.10.2  data F1CB30AFF1CB30B00101000000000000CF0EFD81EA9F6324EA97B369351C56AC
[...]
----
. FIPS 드라이브가 FIPS 준수 모드에서 실행 중인 경우 노드에 대한 FIPS 인증 키 ID를 기본 MSID 0x0으로 다시 설정합니다.
+
'Storage encryption disk modify -disk_disk_id_-FIPS-key-id 0x0'

+
'보안 키 관리자 쿼리' 명령을 사용하여 키 ID를 볼 수 있습니다.

+
[listing]
----
cluster1::> storage encryption disk modify -disk 1.10.2 -fips-key-id 0x0

Info: Starting modify on 1 disk.
      View the status of the operation by using the
      storage encryption disk show-status command.
----
. 드라이브 완전 삭제:
+
'Storage encryption disk sanitize -disk_disk_id_'

+
이 명령을 사용하여 핫 스페어 또는 파손된 디스크만 삭제할 수 있습니다. 유형에 관계없이 모든 디스크를 삭제하는 방법은 '-force-all-state' 옵션을 사용하십시오. 전체 명령 구문은 man 페이지를 참조하십시오.

+
[NOTE]
====
계속하기 전에 확인 문구를 입력하라는 메시지가 표시됩니다. 화면에 표시된 대로 정확하게 구문을 입력합니다.

====
+
[listing]
----
cluster1::> storage encryption disk sanitize -disk 1.10.2

Warning: This operation will cryptographically sanitize 1 spare or broken self-encrypting disk on 1 node.
         To continue, enter sanitize disk: sanitize disk

Info: Starting sanitize on 1 disk.
      View the status of the operation using the
      storage encryption disk show-status command.
----

