---
sidebar: sidebar 
permalink: s3-snapshots/create-s3-snapshot.html 
keywords: s3 snapshots, snapshot create 
summary: S3 스냅샷을 수동으로 생성하거나 스냅샷 정책을 설정하여 S3 스냅샷을 자동으로 생성할 수 있습니다. 
---
= S3 스냅샷을 생성합니다
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
S3 스냅샷을 수동으로 생성하거나 스냅샷 정책을 설정하여 S3 스냅샷을 자동으로 생성할 수 있습니다. 스냅샷은 데이터 백업 및 복구에 사용하는 개체의 정적 복사본 역할을 합니다. 스냅샷 보존 기간을 결정하기 위해 지정된 간격으로 자동 스냅샷 생성을 지원하는 스냅샷 정책을 생성할 수 있습니다.

S3 스냅샷은 오브젝트 버전 관리를 사용 또는 사용하지 않고 S3 버킷에서 오브젝트 데이터를 보호하는 데 도움이 됩니다.


TIP: 스냅샷은 S3 버킷에서 오브젝트 버전 관리를 사용하지 않는 경우, 이전 오브젝트 버전을 사용할 수 없는 경우 복원 작업에 사용할 수 있는 시점 레코드의 역할을 하기 때문에 데이터 보호를 설정하는 데 특히 유용합니다.

.이 작업에 대해
* 다음 명명 규칙이 스냅샷에 적용됩니다(수동 및 자동 스냅샷 모두).
+
** S3 스냅샷 이름은 최대 30자까지 지정할 수 있습니다
** S3 스냅샷 이름은 소문자, 숫자, 점(.) 및 하이픈(-)만 구성할 수 있습니다.
** S3 스냅샷 이름은 문자 또는 숫자로 끝나야 합니다
** S3 스냅샷 이름에는 하위 문자열이 포함될 수 없습니다 `s3snap`


* S3 프로토콜의 컨텍스트에서 버킷 명명 제한으로 인해 버킷 이름이 63자로 제한됩니다. ONTAP S3 스냅샷은 S3 프로토콜을 통해 버킷으로 표시되므로 스냅샷 버킷 이름에 유사한 제한이 적용됩니다. 기본적으로 원래 버킷 이름이 기본 버킷 이름으로 사용됩니다.
* 어떤 버킷에 속하는 스냅샷을 보다 쉽게 식별할 수 있도록 스냅샷 버킷 이름은 기본 버킷 이름과 스냅샷 이름 앞에 붙는 특수 문자열로 `-s3snap-` 구성됩니다. 스냅샷 버킷 이름의 형식은 로 `<base_bucket_name>-s3snap-<snapshot_name>`지정됩니다.
+
예를 들어, 다음 명령을 실행하여 `snap1` 에서 을 `bucket-a` 생성하면 기본 버킷에 액세스 권한이 있는 경우, S3 클라이언트를 통해 액세스할 수 있는 이름으로 스냅샷 버킷이 `bucket-a-s3snap-snap1` 생성됩니다.

+
[listing]
----
vserver object-store-server bucket snapshot create -bucket bucket-a -snapshot snap1
----
* 63자를 초과하는 스냅샷 버킷 이름을 생성하는 스냅샷을 생성할 수 없습니다.
* 자동 스냅샷 이름에는 기존 볼륨 스냅샷의 명명 규칙과 유사한 정책 일정 이름과 타임스탬프가 포함됩니다. 예를 들어 예약된 스냅샷 이름은 및 `hourly-2024-05-22-1105` 일 수 `daily-2024-01-01-0015` 있습니다.




== S3 스냅샷을 수동으로 생성합니다

ONTAP CLI를 사용하여 S3 스냅샷을 수동으로 생성할 수 있습니다. 이 절차는 로컬 클러스터에만 스냅샷을 생성합니다.

.단계
. S3 스냅샷 생성:
+
[listing]
----
vserver object-store-server bucket snapshot create -vserver <svm_name> -bucket <bucket_name> -snapshot <snapshot_name>
----
+
다음 예에서는 `vs0` 스토리지 VM 및 `website-data` 버킷에 이라는 스냅샷을 `pre-update` 생성합니다.

+
[listing]
----
vserver object-store-server bucket snapshot create -vserver vs0 -bucket website-data -snapshot pre-update
----




== 버킷에 S3 스냅샷 정책을 할당합니다

S3 버킷 수준에서 스냅샷 정책을 구성하면 ONTAP가 예약된 S3 스냅샷을 자동으로 생성합니다. 기존 스냅샷 정책과 마찬가지로 S3 스냅샷에 대해 최대 5개의 일정을 구성할 수 있습니다.

스냅샷 정책은 일반적으로 스냅샷을 생성할 스케줄, 각 스케줄에 대해 보존할 복제본 수 및 스케줄 접두사를 지정합니다. 예를 들어 정책은 매일 오전 12시 10분에 S3 스냅샷 하나를 생성하고 가장 최근의 복제본 두 개를 보존하고 이름을 지정할 수 `daily-<timestamp>` 있습니다.

기본 스냅샷 정책은 다음을 보존합니다.

* 시간별 스냅샷 6개
* 일일 스냅샷 2개
* 주간 스냅샷 2개


.시작하기 전에
* S3 버킷에 할당하기 전에 스냅샷 정책을 생성해야 합니다.



NOTE: S3 스냅샷에 대한 정책은 다른 ONTAP 스냅샷 정책과 동일한 규칙을 따릅니다. 하지만 스냅샷 스케줄에 보존 기간이 구성된 스냅샷 정책은 S3 버킷에 할당할 수 없습니다.

스냅샷 자동 생성을 위한 스냅샷 정책 생성에 대한 자세한 내용은 을 참조하십시오link:../data-protection/configure-custom-snapshot-policies-concept.html["사용자 지정 스냅샷 정책 구성 개요"].

.단계
. 버킷에 스냅샷 정책을 할당합니다.
+
[listing]
----
vserver object-store-server bucket create -vserver <svm_name> -bucket <bucket_name> -snapshot-policy <policy_name>
----
+
또는

+
[listing]
----
vserver object-store-server bucket modify -vserver <svm_name> -bucket <bucket_name> -snapshot-policy <policy_name>
----



NOTE: 클러스터를 ONTAP 9.16.1 이전 버전의 ONTAP로 되돌려야 하는 경우 모든 버킷의 값이 (또는 `-`)로 설정되어 `none` 있는지 확인하십시오 `snapshot-policy`.

.관련 정보
link:../s3-snapshots/index.html["S3 스냅샷 개요"]
