---
sidebar: sidebar 
permalink: s3-snapshots/delete-s3-snapshot.html 
keywords: s3 snapshots, delete S3 snapshots 
summary: 더 이상 필요하지 않은 S3 스냅샷을 삭제하고 버킷에서 스토리지 공간을 확보할 수 있습니다. 
---
= S3 스냅샷을 삭제합니다
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
더 이상 필요하지 않은 S3 스냅샷을 삭제하고 버킷의 스토리지 공간을 확보할 수 있습니다. S3 스냅샷을 수동으로 제거하거나 S3 버킷에 연결된 스냅샷 정책을 수정하여 일정에 대해 보존할 스냅샷 수를 변경할 수 있습니다.

S3 버킷에 대한 스냅샷 정책은 기존 ONTAP 스냅샷 정책과 동일한 삭제 규칙을 따릅니다. 스냅샷 정책 생성에 대한 자세한 내용은 을 link:../data-protection/create-snapshot-policy-task.html["스냅샷 정책을 생성합니다"]참조하십시오.

.이 작업에 대해
* 여러 스냅숏에서 객체 버전(버전 버킷의 경우) 또는 객체(버전이 지정되지 않은 버킷의 경우)가 캡처된 경우 마지막으로 보호된 스냅샷이 삭제된 후에만 파일 시스템에서 객체가 제거됩니다.
* 스냅샷이 있는 오브젝트가 포함된 S3 버킷을 삭제해야 하는 경우 해당 버킷에 있는 모든 오브젝트의 모든 스냅샷을 삭제했는지 확인하십시오.
* 클러스터를 ONTAP 9.16.1 이전 버전의 ONTAP로 되돌려야 하는 경우 모든 버킷에 대해 모든 S3 스냅샷을 삭제했는지 확인하십시오. S3 버킷의 스냅샷 메타데이터를 제거하기 위해 명령을 실행해야 할 수도 `vserver object-store-server bucket clear-snapshot-metadata` 있습니다. 자세한 내용은 을 link:../s3-snapshots/delete-s3-snapshot.html#clear-s3-snapshots-metadata["S3 스냅샷 메타데이터를 지웁니다"]참조하십시오.
* 스냅샷을 일괄적으로 삭제할 때 여러 스냅샷에 캡처된 많은 수의 개체를 제거하여 개별 스냅샷을 삭제할 때보다 더 많은 공간을 효율적으로 확보할 수 있습니다. 따라서 스토리지 오브젝트를 위해 더 많은 공간을 재확보할 수 있습니다.


.단계
. 특정 S3 스냅샷을 삭제하려면 다음 명령을 실행합니다.
+
[listing]
----
vserver object-store-server bucket snapshot delete -vserver <svm_name> -bucket <bucket_name> -snapshot <snapshot_name>
----
. 버킷에서 모든 S3 스냅샷을 제거하려면 다음 명령을 실행합니다.
+
[listing]
----
vserver object-store-server bucket snapshot delete -vserver <svm_name> -bucket <bucket_name> -snapshot *
----




== S3 스냅샷 메타데이터를 지웁니다

S3 스냅샷을 사용하면 스냅샷 메타데이터도 버킷에서 생성됩니다. 스냅샷 메타데이터는 모든 스냅샷이 해당 스냅샷에서 제거되더라도 계속해서 버킷에 있게 됩니다. 스냅샷 메타데이터가 있으면 다음 작업이 차단됩니다.

* 클러스터를 ONTAP 9.16.1 이전 버전의 ONTAP로 되돌립니다
* 버킷에 S3 SnapMirror 구성


이러한 작업을 수행하기 전에 버킷에서 모든 스냅샷 메타데이터를 지워야 합니다.

.시작하기 전에
메타데이터 지우기를 시작하기 전에 버킷에서 모든 S3 스냅샷을 제거했는지 확인합니다.

.단계
. 버킷에서 스냅샷 메타데이터를 지우려면 다음 명령을 실행합니다.


[listing]
----
vserver object-store-server bucket clear-snapshot-metadata -vserver <svm_name> -bucket <bucket_name>
----