---
sidebar: sidebar 
permalink: s3-snapshots/index.html 
keywords: s3 snapshots, S3 Snapshot copy overview, what is S3 snapshot, can you create S3 snapshots 
summary: S3 Snapshot 기술을 사용하여 S3 버킷의 시점 백업을 생성합니다. 
---
= S3 스냅샷 개요
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
ONTAP 9.16.1부터 ONTAP 스냅샷 기술을 사용하여 ONTAP S3 버킷의 읽기 전용 시점 이미지를 생성할 수 있습니다.

S3 스냅샷 기능을 사용하면 스냅샷을 수동으로 생성하거나 스냅샷 정책을 통해 스냅샷을 자동으로 생성할 수 있습니다. S3 스냅샷은 S3 클라이언트에 S3 버킷으로 제공됩니다. S3 클라이언트를 통해 스냅샷에서 콘텐츠를 찾아보고 복원할 수 있습니다.

ONTAP 9.16.1에서 S3 스냅샷은 S3 버킷의 현재 버전만 캡처합니다. 최신 버전이 아닌 버킷을 S3 스냅샷에서 캡처하지 않습니다. 또한 스냅샷 생성 후 객체 태그가 수정되면 시점 객체 태그가 스냅샷에 캡처되지 않습니다.


TIP: S3 스냅샷은 클러스터 시간을 기준으로 합니다. 시간을 동기화하려면 클러스터에서 NTP 서버를 구성해야 합니다. 자세한 내용은 을 link:../system-admin/manage-cluster-time-concept.html["클러스터 시간을 관리합니다"]참조하십시오.

.할당량 및 공간 사용량
할당량은 S3 버킷에 사용되는 오브젝트 수와 논리적 크기를 추적합니다. S3 스냅샷이 생성될 때 스냅샷이 파일 시스템에서 삭제될 때까지 S3 스냅샷에서 캡처된 오브젝트는 사용된 버킷 오브젝트 수 및 크기에 계산됩니다.

.다중 파트 개체
멀티 파트 객체의 경우 최종 객체만 스냅샷에 캡처됩니다. 다중 부분 객체의 부분 업로드는 스냅샷에 캡처되지 않습니다.



== 버전 및 비버전 버킷의 스냅샷

버전 및 비버전 버킷 모두에서 스냅샷을 생성할 수 있습니다. 스냅숏은 스냅숏이 캡처될 때 현재 개체 버전만 포함합니다.

.버전 관리된 버킷 및 스냅샷
오브젝트 버전 관리가 활성화된 버킷에서 스냅샷은 스냅샷이 생성된 후 가장 최근의 오브젝트 버전의 콘텐츠를 유지합니다. 버킷에서 비최신 버전은 제외됩니다.

이 예에서는 오브젝트 버전 관리가 활성화된 버킷에서 오브젝트에 `obj1` v1, v2, v3, v4, v5가 있습니다. v3(캡처 시점에 가장 최근 버전)에서 `obj1` 스냅샷을 `snap1` 생성했습니다. 브라우징 시 `snap1` `obj1` v3에 생성된 컨텐츠가 있는 객체로 표시됩니다. 이전 버전의 콘텐츠는 반환되지 않습니다.


NOTE: 스냅샷이 삭제될 때까지 현재 버전이 아닌 버전은 파일 시스템에 유지됩니다.

.비버전 버킷 및 스냅샷
버전이 지정되지 않은 버킷에서 S3 스냅샷은 스냅샷 생성 전에 최신 커밋의 내용을 유지합니다.

다음 예를 들어 개체 버전 관리를 사용할 수 없는 버킷에서 (T1, T2, T3, T4 및 T5)에서 개체를 `obj1` 여러 번 덮어썼습니다. T3와 T4 사이에 S3 스냅샷을 `snap1` 생성했습니다. 브라우징 시 `snap1` `obj1` T3에서 생성된 컨텐츠와 함께 가 나타납니다.



== 개체 만료 및 스냅샷

ONTAP S3 오브젝트 만료 및 S3 스냅샷 기능은 서로 독립적으로 작동합니다. ONTAP 오브젝트 만료 기능은 S3 버킷에 정의된 라이프사이클 관리 규칙에 따라 오브젝트 버전을 만료한다. S3 스냅샷은 스냅샷이 생성된 시점의 버킷 객체의 정적 복사본입니다.

버킷에서 오브젝트 버전 관리를 사용하는 경우, 해당 버킷에 정의된 만료 규칙으로 인해 특정 버전의 오브젝트가 삭제되면 만료된 오브젝트 버전의 콘텐츠가 하나 이상의 S3 스냅샷에서 현재 버전으로 캡처된 경우 파일 시스템에 계속 남아 있습니다. 해당 객체 버전은 해당 스냅샷이 삭제될 때만 파일 시스템에 더 이상 존재하지 않습니다.

마찬가지로, 버전 관리가 비활성화된 버킷에서 만료 규칙에 따라 오브젝트가 삭제되지만 일부 기존 S3 스냅샷에서 오브젝트가 캡처된 경우 해당 오브젝트는 파일 시스템에 유지됩니다. 객체를 캡처하는 스냅샷이 삭제되면 객체가 파일 시스템에서 영구적으로 제거됩니다.

S3 오브젝트 만료 및 라이프사이클 관리에 대한 자세한 내용은 을 참조하십시오link:../s3-config/create-bucket-lifecycle-rule-task.html["버킷 수명 주기 관리 규칙을 생성합니다"].



== S3 스냅샷의 제한 사항

ONTAP 9.16.1에서 다음 기능 제외 및 시나리오를 참고하십시오.

* S3 버킷에 대해 최대 1023개의 스냅샷을 생성할 수 있습니다.
* 클러스터를 ONTAP 9.16.1 이전 버전의 ONTAP로 되돌리려면 먼저 클러스터의 모든 버킷에서 모든 S3 스냅샷과 메타데이터를 삭제해야 합니다.
* 스냅샷이 있는 오브젝트가 포함된 S3 버킷을 삭제해야 하는 경우 해당 버킷에 있는 모든 오브젝트의 해당 스냅샷을 모두 삭제했는지 확인하십시오.
* S3 스냅샷은 다음 구성에서 지원되지 않습니다.
+
** 완전히 새로운 차원의 제휴가 이루어질 수 있습니다 SnapMirror
** 물체 잠금이 활성화된 버킷
** On NetApp BlueXP (활성 상태)
** On System Manager 를 참조하십시오
** ONTAP MetroCluster 구성에서



