---
sidebar: sidebar 
permalink: s3-snapshots/list-restore-s3-snapshot.html 
keywords: s3 snapshots, list, restore, browse S3 snapshots 
summary: ONTAP S3 스냅샷 기능을 사용하면 S3 클라이언트에서 버킷의 S3 스냅샷 콘텐츠를 확인, 탐색 및 복원할 수 있습니다. 
---
= S3 스냅샷을 보고 복원합니다
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
ONTAP S3 스냅샷 기능을 사용하면 S3 클라이언트에서 버킷에 대한 S3 스냅샷 콘텐츠를 확인하고 탐색할 수 있습니다. 또한, S3 스냅샷에서 단일 오브젝트, 오브젝트 세트 또는 전체 버킷을 S3 클라이언트에서 복원할 수 있습니다.

.시작하기 전에
버킷에서 ONTAP S3 스냅샷을 확인, 탐색 및 복원하려면 스냅샷이 생성되어야 하며, S3 기본 버킷이 S3 프로토콜 클라이언트를 통해 액세스할 수 있어야 합니다.



== S3 스냅샷 나열 및 보기

S3 스냅샷 세부 정보를 보고, 비교하고, 오류를 식별할 수 있습니다. ONTAP CLI를 사용하면 S3 버킷에서 생성된 모든 스냅샷을 나열할 수 있습니다.

.단계
. S3 스냅샷 목록:
+
[listing]
----
vserver object-store-server bucket snapshot show
----
+
클러스터에 있는 모든 버킷에 대해 생성된 S3 스냅샷의 스냅샷 이름, 스토리지 VM, 버킷, 생성 시간 및 을 볼 수 `instance-uuid` 있습니다.

. 버킷 이름을 지정하여 해당 특정 버킷에 대해 생성된 모든 S3 스냅샷의 이름, 생성 시간 및 이름을 볼 수도 `instance-uuid` 있습니다.
+
[listing]
----
vserver object-store-server bucket snapshot show -vserver <svm_name> -bucket <bucket_name>
----




== S3 스냅샷 콘텐츠를 찾아봅니다

환경에서 장애나 문제가 발견되면 S3 버킷 스냅샷의 콘텐츠를 탐색하여 오류를 식별할 수 있습니다. 또한 S3 스냅샷을 탐색하여 오류 없는 콘텐츠를 복원할 수도 있습니다.

S3 스냅샷은 S3 클라이언트에 스냅샷 버킷으로 표시됩니다. 스냅샷 버킷 이름의 형식이 `<base_bucket_name>-s3snap-<snapshot_name>` 다음과 같습니다. S3 API 작업을 통해 스토리지 VM의 모든 스냅샷 버킷을 볼 수 있습니다 `ListBuckets`.

S3 스냅샷 버킷은 기본 버킷의 액세스 정책을 상속하며 읽기 전용 작업만 지원합니다. 기본 버킷에 액세스할 수 있는 권한이 있는 경우 `GetObject`, , `GetObjectTagging` `ListObjects`, 등의 읽기 전용 S3 API 작업을 S3 스냅샷 버킷에서 수행할 수도 있습니다 `HeadObject`. `ListObjectVersions`, `GetObjectAcl`, 및 `CopyObject`.


NOTE: 이 `CopyObject` 작업은 S3 스냅샷 버킷이 소스 버킷의 스냅샷 복사본인 경우에만 지원되며, 스냅샷의 스토리지 타겟인 경우에는 지원되지 않습니다.

이러한 작업에 대한 자세한 내용은 을 link:../s3-config/ontap-s3-supported-actions-reference.html["ONTAP S3가 지원되는 작업"]참조하십시오.



== S3 스냅샷에서 콘텐츠를 복원합니다

S3 클라이언트에서 복원 작업을 수행하여 스냅샷 버킷의 콘텐츠를 원래 또는 다른 버킷으로 복사함으로써 단일 오브젝트, 오브젝트 세트 또는 전체 버킷을 복구할 수 있습니다. 스냅샷을 탐색하여 복사할 스냅샷 컨텐츠를 결정할 수 있습니다.

명령을 사용하여 전체 버킷, 접두사가 있는 오브젝트 또는 단일 오브젝트를 `aws s3 cp` 복원합니다.

.단계
. 기본 S3 버킷의 스냅샷을 생성합니다.
+
[listing]
----
vserver object-store-server bucket snapshot create -vserver <svm_name> -bucket <base_bucket_name> -snapshot <snapshot_name>
----
. 스냅샷을 사용하여 기본 버킷을 복원합니다.
+
** 전체 버킷을 복원합니다. 스냅샷 버킷 이름을 형식으로 `<base_bucket_name>-s3snap-<snapshot_name>` 사용합니다.
+
[listing]
----
aws --endpoint http://<IP> s3 cp s3://<snapshot-bucket-name> s3://<base-bucket>  --recursive
----
** 다음 접두사를 사용하여 디렉터리의 개체를 `dir1` 복원합니다.
+
[listing]
----
aws --endpoint http://<IP> s3 cp s3://<snapshot-bucket-name>/dir1 s3://<base_bucket_name>/dir1 --recursive
----
** 이름이 인 단일 개체 복원 `web.py`:
+
[listing]
----
aws --endpoint http://<IP> s3 cp s3:// <snapshot-bucket-name>/web.py s3://<base_bucket_name>/web.py
----



