---
permalink: s3-multiprotocol/index.html 
sidebar: sidebar 
keywords: multiprotocol, s3, configuration, overview, nfs, smb 
summary: ONTAP 9.12.1부터는 S3 프로토콜을 실행하는 클라이언트가 다시 포맷하지 않고 NFS 및 SMB 프로토콜을 사용하는 클라이언트에 제공되는 동일한 데이터에 액세스할 수 있도록 설정할 수 있습니다. 
---
= S3 멀티 프로토콜 개요
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9.12.1부터는 S3 프로토콜을 실행하는 클라이언트가 다시 포맷하지 않고 NFS 및 SMB 프로토콜을 사용하는 클라이언트에 제공되는 동일한 데이터에 액세스할 수 있도록 설정할 수 있습니다. 이 기능을 사용하면 NAS 클라이언트에서 NAS 데이터를 계속 처리하는 동시에 S3 애플리케이션(예: 데이터 마이닝 및 인공 지능)을 실행하는 S3 클라이언트에 오브젝트 데이터를 제공할 수 있습니다.

S3 멀티 프로토콜 기능은 다음과 같은 두 가지 사용 사례를 해결합니다.

. S3 클라이언트를 사용하여 기존 NAS 데이터에 액세스
+
기존 데이터가 기존 NAS 클라이언트(NFS 또는 SMB)를 사용하여 생성되었고 NAS 볼륨(FlexVol 또는 FlexGroup 볼륨)에 있는 경우, 이제 S3 클라이언트에서 분석 툴을 사용하여 이 데이터에 액세스할 수 있습니다.

. NAS 및 S3 프로토콜을 모두 사용하여 I/O를 수행할 수 있는 최신 클라이언트를 위한 백엔드 스토리지
+
이제 NAS 및 S3 프로토콜을 모두 사용하여 동일한 데이터를 읽고 쓸 수 있는 Spark 및 Kafka와 같은 애플리케이션에 통합 액세스를 제공할 수 있습니다.





== S3 멀티 프로토콜의 작동 방식

ONTAP 멀티 프로토콜을 사용하면 동일한 데이터 세트를 파일 계층으로 또는 버킷의 객체로 제공할 수 있습니다. 이를 위해 ONTAP는 S3 클라이언트가 S3 오브젝트 요청을 사용하여 NAS 스토리지에 파일을 생성, 읽기, 삭제 및 열거할 수 있도록 "S3 NAS 버킷"을 생성합니다. 이 매핑은 NAS 보안 구성, 파일 및 디렉터리 액세스 권한 감시 및 필요에 따라 보안 감사 추적에 대한 쓰기 작업을 따릅니다.

이 매핑은 지정된 NAS 디렉토리 계층을 S3 버킷으로 제공하여 수행됩니다. 디렉토리 계층의 각 파일은 이름이 매핑된 디렉토리에서 상대적으로 아래로 내려가는 S3 오브젝트로 표시되며 디렉토리 경계는 슬래시 문자('/')로 표시됩니다.

일반 ONTAP 정의 S3 사용자는 NAS 디렉토리에 매핑되는 버킷에 정의된 버킷 정책에 따라 이 스토리지에 액세스할 수 있습니다. 이를 위해서는 S3 사용자와 SMB/NFS 사용자 간에 매핑을 정의해야 합니다. SMB/NFS 사용자의 자격 증명은 NAS 권한 확인에 사용되며 이러한 액세스로 인해 발생하는 모든 감사 레코드에 포함됩니다.

SMB 또는 NFS 클라이언트가 파일을 생성하면 파일이 디렉토리에 즉시 배치되므로 데이터가 쓰기 전에 클라이언트에 표시됩니다. S3 클라이언트는 모든 데이터가 기록될 때까지 새 오브젝트가 네임스페이스에 표시되지 않는 다른 의미를 기대합니다. S3를 NAS 스토리지에 매핑하는 방식은 S3 의미를 사용하여 파일을 생성하므로 S3 생성 명령이 완료될 때까지 파일을 외부적으로 볼 수 없습니다.



== S3 NAS 버킷 용 데이터 보호

S3 NAS “버킷”은 S3 클라이언트용 NAS 데이터의 단순한 매핑이며 표준 S3 버킷이 아닙니다. 따라서 NetApp S3 SnapMirror 기능을 사용하여 S3 NAS 버킷을 보호할 필요가 없습니다. 대신 비동기식 SnapMirror 볼륨 복제를 사용하여 S3 NAS 버킷을 포함하는 볼륨을 보호할 수 있습니다. SnapMirror Synchronous 및 SVM 재해 복구는 지원되지 않습니다.

ONTAP 9.14.1부터, MetroCluster IP 및 FC 구성을 위한 미러링된 애그리게이트 및 미러링되지 않은 애그리게이트에서 S3 NAS 버킷이 지원됩니다.

에 대해 자세히 link:../data-protection/snapmirror-disaster-recovery-concept.html#data-protection-relationships["비동기식 SnapMirror입니다"]알아보십시오.



== S3 NAS 버킷에 대한 감사

S3 NAS 버킷은 기존의 S3 버킷이 아니므로 액세스 감사를 위해 S3 감사를 구성할 수 없습니다. 에 대해 자세히 알아보십시오 link:../s3-audit/index.html["S3 감사"].

그럼에도 불구하고 S3 NAS 버킷에 매핑된 NAS 파일 및 디렉토리는 기존의 ONTAP 감사 절차를 사용하여 액세스 이벤트에 대한 감사를 수행할 수 있습니다. 따라서 S3 작업은 다음과 같은 예외를 제외하고 NAS 감사 이벤트를 트리거할 수 있습니다.

* S3 정책 구성(그룹 또는 버킷 정책)에 의해 S3 클라이언트 액세스가 거부되면 이벤트에 대한 NAS 감사가 시작되지 않습니다. 이는 SVM 감사 점검을 수행하기 전에 S3 권한을 확인하기 때문입니다.
* S3 GET 요청의 타겟 파일이 0 크기인 경우 0개의 콘텐츠가 GET 요청으로 반환되고 읽기 액세스가 기록되지 않습니다.
* S3 GET 요청의 타겟 파일이 사용자에게 통과 권한이 없는 폴더에 있는 경우 액세스 시도가 실패하고 이벤트가 기록되지 않습니다.


에 대해 자세히 알아보십시오 link:../nas-audit/index.html["SVM에서 NAS 이벤트 감사"].



== S3 및 NAS 상호 운용성

ONTAP S3 NAS 버킷은 여기에 나열된 기능을 제외한 표준 NAS 및 S3 기능을 지원합니다.



=== NAS 기능은 현재 S3 NAS 버킷에서 지원되지 않습니다

FabricPool 용량 계층입니다:: S3 NAS 버킷은 FabricPool의 용량 계층으로 구성할 수 없습니다.




=== S3 기능은 현재 S3 NAS 버킷에서 지원되지 않습니다

AWS 사용자 메타데이터::
+
--
* S3 사용자 메타데이터의 일부로 수신된 키 값 쌍은 현재 릴리즈의 오브젝트 데이터와 함께 디스크에 저장되지 않습니다.
* 접두사 "x-amz-meta"가 있는 요청 헤더는 무시됩니다.


--
AWS 태그::
+
--
* Put 객체와 Multitpart initiate 요청에서 접두사 "x-amz-tagging"이 있는 헤더는 무시됩니다.
* 기존 파일의 태그 업데이트 요청(예: "tagging query-string"으로 PUT, GET 및 Delete 요청)은 오류로 거부됩니다.


--
버전 관리:: 버킷 매핑 구성에서는 버전 관리를 지정할 수 없습니다.
+
--
* null이 아닌 버전 사양(versionId=xyz 쿼리 문자열)이 포함된 요청은 오류 응답을 받습니다.
* 버킷의 버전 관리 상태에 영향을 주는 요청은 오류와 함께 거부됩니다.


--
다중 파트 작업:: 다음 작업은 지원되지 않습니다.
+
--
* AbortMultipartUpload 를 클릭합니다
* CompleteMultipartUpload를 클릭합니다
* CreateMultptUpload 를 클릭합니다
* ListMultipartUpload 를 클릭합니다


--

