---
permalink: ndmp/enable-node-scoped-ndmp-cluster-task.html 
sidebar: sidebar 
keywords: enable, node, scope, ndmp, cluster 
summary: 클러스터의 모든 노드에서 NDMP 서비스와 클러스터에서 노드 범위 NDMP를 설정하여 노드 범위 NDMP를 구성할 수 있습니다. NDMP 서비스를 설정할 때는 NDMP에 대한 루트 사용자도 구성해야 합니다. 
---
= 클러스터에서 노드 범위의 NDMP를 사용하도록 설정합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
노드 범위 NDMP를 설정하고, NDMP 서비스를 사용하도록 설정하고, 데이터 및 제어 연결을 위해 LIF를 구성하여 단일 노드에서 호스팅되는 볼륨을 백업할 수 있습니다. 이 작업은 클러스터의 모든 노드에 대해 수행할 수 있습니다.


NOTE: 노드 범위 NDMP는 ONTAP 9에서 더 이상 사용되지 않습니다.

노드 범위 모드에서 NDMP를 사용하는 경우 노드 단위로 인증을 구성해야 합니다. 자세한 내용은 을 참조하십시오 link:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/NDMP/How_to_configure_NDMP_authentication_in_the_%E2%80%98node-scope%E2%80%99_mode["기술 자료 문서 "'노드 범위' 모드에서 NDMP 인증을 구성하는 방법""^].

.단계
. 'node-scope-mode' 매개 변수와 함께 'system services ndmp' 명령을 사용하여 노드 범위 NDMP 모드를 설정합니다.
+
[listing]
----
cluster1::> system services ndmp node-scope-mode on
NDMP node-scope-mode is enabled.
----
. 'system services ndmp on' 명령을 사용하여 클러스터의 모든 노드에서 NDMP 서비스를 설정합니다.
+
와일드카드 "" * ""를 사용하면 모든 노드에서 동시에 NDMP 서비스를 사용할 수 있습니다.

+
백업 애플리케이션에서 NDMP 접속을 인증할 암호를 지정해야 합니다.

+
[listing]
----
cluster1::> system services ndmp on -node *

Please enter password:
Confirm password:
2 entries were modified.
----
. 'system services ndmp modify' 명령을 사용하여 NDMP 암호의 보안 통신을 위해 '-clear-text' 옵션을 해제합니다.
+
와일드카드 "" * "를 사용하면 모든 노드에서 "-clear-text" 옵션을 동시에 사용할 수 없습니다.

+
[listing]
----
cluster1::> system services ndmp modify -node * -clear-text false
2 entries were modified.
----
. 'system services ndmp show' 명령을 사용하여 NDMP 서비스가 설정되어 있고 '-clear-text' 옵션이 비활성화되어 있는지 확인합니다.
+
[listing]
----
cluster1::> system services ndmp show
Node                  Enabled   Clear text  User Id
--------------------- --------- ----------- ---------
cluster1-1            true      false        root
cluster1-2            true      false        root
2 entries were displayed.
----

