---
permalink: ndmp/index.html 
sidebar: sidebar 
keywords: decide, ndmp, configuration, network, data, management, protocol, backup, back up 
summary: '타사 백업 애플리케이션을 사용하여 데이터를 테이프에 직접 백업하기 위해 NDMP(네트워크 데이터 관리 프로토콜)를 사용하도록 ONTAP 9 클러스터를 빠르게 구성할 수 있습니다.' 
---
= NDMP 구성 개요
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
타사 백업 애플리케이션을 사용하여 데이터를 테이프에 직접 백업하기 위해 NDMP(네트워크 데이터 관리 프로토콜)를 사용하도록 ONTAP 9 클러스터를 빠르게 구성할 수 있습니다.

백업 애플리케이션이 CAB(Cluster Aware Backup)를 지원하는 경우 NDMP를 _SVM-scope_or_node-scope_로 구성할 수 있습니다.

* 클러스터(admin SVM) 레벨에서 SVM 범위가 지정되므로 클러스터의 서로 다른 노드에 호스팅된 모든 볼륨을 백업할 수 있습니다. 가능한 경우 SVM 범위의 NDMP를 사용하는 것이 좋습니다.
* 노드 범위 NDMP에서는 해당 노드에서 호스팅되는 모든 볼륨을 백업할 수 있습니다.


백업 애플리케이션이 CAB를 지원하지 않는 경우 노드 범위 NDMP를 사용해야 합니다.

SVM 범위 및 노드 범위 NDMP는 상호 배타적이므로 동일한 클러스터에서 구성할 수 없습니다.


NOTE: 노드 범위 NDMP는 ONTAP 9에서 더 이상 사용되지 않습니다.

에 대해 자세히 link:../tape-backup/cluster-aware-backup-extension-concept.html["운전실(Cluster Aware Backup)"]알아보십시오.

NDMP를 구성하기 전에 다음을 확인하십시오.

* 타사 백업 애플리케이션(DMA라고도 함)이 있습니다.
* 클러스터 관리자입니다.
* 테이프 장치 및 옵션 미디어 서버가 설치됩니다.
* 테이프 디바이스는 직접 연결되지 않고 FC(Fibre Channel) 스위치를 통해 클러스터에 연결됩니다.
* 하나 이상의 테이프 디바이스에 LUN(Logical Unit Number)이 0인 경우

