---
permalink: ndmp/prepare-ndmp-config-task.html 
sidebar: sidebar 
keywords: prepare, ndmp, configuration 
summary: 'NDMP(Network Data Management Protocol)를 통해 테이프 백업 액세스를 구성하기 전에 계획된 구성이 지원되는지 확인하고, 테이프 드라이브가 각 노드의 적격 드라이브로 나열되는지 확인하고, 모든 노드에 인터클러스터 LIF가 있는지 확인해야 합니다. 백업 애플리케이션이 CAB(Cluster Aware Backup) 확장을 지원하는지 여부를 확인합니다.' 
---
= NDMP 구성을 준비합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NDMP(Network Data Management Protocol)를 통해 테이프 백업 액세스를 구성하기 전에 계획된 구성이 지원되는지 확인하고, 테이프 드라이브가 각 노드의 적격 드라이브로 나열되는지 확인하고, 모든 노드에 인터클러스터 LIF가 있는지 확인해야 합니다. 백업 애플리케이션이 CAB(Cluster Aware Backup) 확장을 지원하는지 여부를 확인합니다.

.단계
. 상호 운용성 매트릭스(IMT)를 사용하여 계획된 구성이 지원되는지 확인하십시오.
+
https://mysupport.netapp.com/matrix["NetApp 상호 운용성 매트릭스 툴"^]

+
다음 구성 요소가 호환되는지 확인해야 합니다.

+
** 클러스터에서 실행 중인 ONTAP 9 버전입니다.
** 백업 애플리케이션 공급업체 및 애플리케이션 버전: 예: Symantec NetBackup 7.6 또는 CommVault Simpana 10 SP8.
** 테이프 드라이브의 제조업체, 모델 및 인터페이스(예: IBM Ultrium-TD4 FC 또는 HP Ultrium-5 SAS)와 같은 테이프 디바이스의 세부 정보입니다.
** 클러스터의 노드 플랫폼: FAS3260, FAS6280 등


. 테이프 드라이브가 각 노드의 내장 테이프 구성 파일에 검증된 드라이브로 나열되어 있는지 확인합니다.
+
.. CLI에서 Storage tape show-supported-status 명령을 사용하여 내장 테이프 구성 파일을 봅니다.
+
[listing]
----
cluster1::> storage tape show-supported-status

Node: cluster1-1
                                Is
Tape Drives                     Supported  Support Status
------------------------------  ---------  -------------------------------
Certance Ultrium 2              true       Dynamically Qualified
Certance Ultrium 3              true       Dynamically Qualified
Digital DLT2000                 true       Qualified
....
----
.. 테이프 드라이브를 출력의 적격 드라이브 목록과 비교합니다.
+
[NOTE]
====
출력에 표시되는 테이프 디바이스의 이름은 디바이스 레이블 또는 상호 운용성 매트릭스의 이름과 약간 다를 수 있습니다. 예를 들어 디지털 DLT2000은 DLT2K라고도 합니다. 이러한 사소한 이름 차이는 무시할 수 있습니다.

====
.. 장치가 상호 운용성 매트릭스에 따라 적격 장치임에도 불구하고 출력에 적격 장치로 표시되지 않는 경우, NetApp Support 사이트의 지침에 따라 장치에 대한 업데이트된 구성 파일을 다운로드하여 설치하십시오.
+
http://mysupport.netapp.com/NOW/download/tools/tape_config["NetApp 다운로드: 테이프 장치 구성 파일"]

+
노드를 제공한 후 테이프 장치가 검증된 경우, 내장 테이프 구성 파일에 검증된 장치가 나열되지 않을 수 있습니다.



. 클러스터의 모든 노드에 인터클러스터 LIF가 있는지 확인합니다.
+
.. 'network interface show-role 인터클러스터' 명령을 사용하여 노드의 인터클러스터 LIF를 봅니다.
+
[listing]
----
cluster1::> network interface show -role intercluster

            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
cluster1    IC1        up/up      192.0.2.65/24      cluster1-1    e0a     true
----
.. 인터클러스터 LIF가 노드에 없으면 '네트워크 인터페이스 만들기' 명령을 사용하여 인터클러스터 LIF를 만듭니다.
+
[listing]
----
cluster1::> network interface create -vserver cluster1 -lif IC2 -role intercluster
-home-node cluster1-2 -home-port e0b -address 192.0.2.68 -netmask 255.255.255.0
-status-admin up -failover-policy local-only -firewall-policy intercluster

cluster1::> network interface show -role intercluster

            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
cluster1    IC1        up/up      192.0.2.65/24      cluster1-1    e0a     true
cluster1    IC2        up/up      192.0.2.68/24      cluster1-2    e0b     true
----
+
link:../networking/index.html["네트워크 관리"]



. 백업 애플리케이션과 함께 제공된 설명서를 사용하여 백업 애플리케이션이 CAB(Cluster Aware Backup)를 지원하는지 여부를 확인합니다.
+
CAB 지원은 수행할 수 있는 백업 유형을 결정하는 핵심 요소입니다.


