---
permalink: consistency-groups/clone-task.html 
sidebar: sidebar 
keywords: consistency groups, consistency group, clone 
summary: ONTAP 9.12.1부터 일관성 그룹을 클론 복제하여 일관성 그룹 구성 및 볼륨의 복사본을 생성할 수 있습니다. 
---
= 일관성 그룹의 클론을 생성합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9.12.1부터는 일관성 그룹을 클론 복제하여 일관성 그룹 및 해당 콘텐츠의 복사본을 생성할 수 있습니다. 일관성 그룹을 클론 복제하면 일관성 그룹 구성의 복사본, 애플리케이션 유형과 같은 메타데이터, 파일, 디렉토리, LUN 또는 NVMe 네임스페이스와 같은 모든 볼륨과 해당 콘텐츠의 복사본이 생성됩니다.

.이 작업에 대해
일관성 그룹을 클론 복제할 때 현재 구성뿐 아니라 기존 일관성 그룹 Snapshot을 기반으로 볼륨 콘텐츠를 복제할 수 있습니다.

일관성 그룹의 클론은 전체 일관성 그룹에 대해서만 지원됩니다. 계층적 관계에서 개별 하위 일관성 그룹을 클론 복제할 수 없습니다. 전체 일관성 그룹 구성만 클론 복제할 수 있습니다.

일관성 그룹을 클론 복제할 때 다음 구성 요소는 클론 복제되지 않습니다.

* iGroup
* LUN 매핑
* NVMe 하위 시스템
* NVMe 네임스페이스 서브시스템 맵


.시작하기 전에
* 일관성 그룹을 클론 복제할 때 공유 이름이 지정되지 않은 경우 ONTAP은 클론 복제된 볼륨에 대한 SMB 공유를 생성하지 않습니다. * 접합 경로가 지정되지 않은 경우 클론 생성된 정합성 보장 그룹이 마운트되지 않습니다.
* 일관성 그룹의 현재 구성 볼륨이 반영되지 않은 스냅샷을 기반으로 일관성 그룹을 클론 복제하려고 하면 작업이 실패합니다.
* 일관성 그룹의 클론을 생성한 후에는 적절한 매핑 작업을 수행해야 합니다.
+
을 참조하십시오 xref:../task_san_map_igroups_to_multiple_luns.html[여러 LUN에 igroup 매핑] 또는 xref:../san-admin/map-nvme-namespace-subsystem-task.html[NVMe 네임스페이스를 하위 시스템에 매핑합니다] 를 참조하십시오.

* SnapMirror 비즈니스 연속성 관계 또는 관련 DP 볼륨의 일관성 그룹에 대해서는 일관성 그룹 클론 복제가 지원되지 않습니다.


[role="tabbed-block"]
====
.시스템 관리자
--
.단계
. 스토리지 > 정합성 보장 그룹 * 을 선택합니다.
. 일관성 그룹 * 메뉴에서 클론 복제할 일관성 그룹을 선택합니다.
. 일관성 그룹의 개요 페이지 오른쪽 위에서 * Clone * 을 선택합니다.
. 클론 복제된 새 일관성 그룹의 이름을 입력하거나 기본 이름을 그대로 사용합니다.
+
.. 활성화 여부를 선택합니다 link:../concepts/thin-provisioning-concept.html["* 씬 프로비저닝 *"^].
.. 소스에서 정합성 보장 그룹을 분리시키고 클론 정합성 보장 그룹에 추가 디스크 공간을 할당하려면 * 클론 분할 * 을 선택합니다.


. 현재 상태의 일관성 그룹을 클론 복제하려면 * 새 스냅샷 복사본 추가 * 를 선택합니다.
+
스냅샷을 기반으로 일관성 그룹을 클론 복제하려면 * 기존 스냅샷 복사본 사용 * 을 선택합니다. 이 옵션을 선택하면 새 하위 메뉴가 열립니다. 클론 작업의 기반으로 사용할 스냅샷을 선택합니다.

. 클론 * 을 선택합니다.
. 정합성 보장 그룹 * 메뉴로 돌아가 정합성 보장 그룹의 클론이 생성되었는지 확인합니다.


--
.CLI를 참조하십시오
--
ONTAP 9.14.1부터 CLI를 사용하여 일관성 그룹을 클론 복제할 수 있습니다.

.일관성 그룹의 클론을 생성합니다
. 를 클릭합니다 `consistency-group clone create` 명령은 현재 시점 상태의 일관성 그룹에 클론을 생성합니다. 스냅샷을 기반으로 클론 작업의 기본 설정을 지정하려면 을 포함합니다 `-source-snapshot` 매개 변수.
+
`consistency-group clone create -vserver _svm_name_ -consistency-group _clone_name_ -source-consistency-group _consistency_group_name_ [-source-snapshot _snapshot_name_]`



--
====
.다음 단계
* xref:../task_san_map_igroups_to_multiple_luns.html[여러 LUN에 igroup 매핑]
* xref:../san-admin/map-nvme-namespace-subsystem-task.html[NVMe 네임스페이스를 하위 시스템에 매핑합니다]

