---
permalink: consistency-groups/configure-task.html 
sidebar: sidebar 
keywords: consistency groups, consistency group, application protection, parent, child, configure 
summary: 애플리케이션 워크로드 관리 및 데이터 보호를 위한 단일 일관성 그룹 생성 
---
= 단일 일관성 그룹을 구성합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
일관성 그룹은 ONTAP 버전에 따라 기존 볼륨 또는 새 LUN이나 볼륨으로 생성할 수 있습니다. 볼륨 또는 LUN은 한 번에 하나의 일관성 그룹에만 연결할 수 있습니다.

.시작하기 전에
* ONTAP 9.10.1 ~ 9.11.1에서는 일관성 그룹이 생성된 후 해당 그룹의 구성원 볼륨을 수정할 수 없습니다.
+
ONTAP 9.12.1부터 정합성 보장 그룹의 구성원 볼륨을 수정할 수 있습니다. 이 프로세스에 대한 자세한 내용은 을 참조하십시오 xref:modify-task.html[일관성 그룹 수정].





== 새 LUN 또는 볼륨이 있는 일관성 그룹을 생성합니다

ONTAP 9.10.1 ~ 9.12.1에서는 새 LUN을 사용하여 일관성 그룹을 생성할 수 있습니다. ONTAP 9.13.1 부터 System Manager에서는 새 NVMe 네임스페이스 또는 새 NAS 볼륨을 사용하는 일관성 그룹을 생성할 수도 있습니다. (ONTAP 9.12.1부터 시작되는 ONTAP REST API에서도 지원됩니다.)

.단계
. 스토리지 > 정합성 보장 그룹 * 을 선택합니다.
. Add * 를 선택한 다음 스토리지 객체에 대한 프로토콜을 선택합니다.
+
ONTAP 9.10.1 ~ 9.12.1에서 새 스토리지 객체에 대한 유일한 옵션은 ** 새 LUN 사용** 입니다. ONTAP 9.13.1 부터 System Manager는 새로운 NVMe 네임스페이스와 새로운 NAS 볼륨을 통해 일관성 그룹을 생성할 수 있도록 지원합니다.

. 일관성 그룹의 이름을 지정합니다. 볼륨 또는 LUN의 수와 볼륨 또는 LUN당 용량을 지정합니다.
+
.. ** 응용 프로그램 유형**: ONTAP 9.12.1 이상을 사용하는 경우 응용 프로그램 유형을 선택합니다. 값을 선택하지 않으면 기본적으로 정합성 보장 그룹에 ** 기타** 유형이 할당됩니다. 에서 일관성 태그 지정에 대해 자세히 알아보십시오 xref:index.html#application-and-component-tags[응용 프로그램 및 구성 요소 태그]. 원격 보호 정책을 사용하여 정합성 보장 그룹을 생성하려면 * 기타 * 를 사용해야 합니다.
.. 새 LUN**: 호스트 운영 체제와 LUN 형식을 선택합니다. 호스트 이니시에이터 정보를 입력합니다.
.. ** 새 NAS 볼륨**: SVM의 NAS 구성에 따라 적절한 내보내기 옵션(NFS 또는 SMB/CIFS)을 선택합니다.
.. 새 NVMe 네임스페이스**: 호스트 운영 체제와 NVMe 하위 시스템을 선택합니다.


. 보호 정책을 구성하거나 하위 일관성 그룹을 추가하거나 액세스 권한을 부여하려면 * 추가 옵션 * 을 선택합니다.
. 저장 * 을 선택합니다.
. 작업이 완료되면 표시되는 기본 정합성 보장 그룹 메뉴로 돌아가 정합성 보장 그룹이 생성되었는지 확인합니다. 보호 정책을 설정하면 해당 정책, 원격 또는 로컬 아래에 녹색 방패 가 표시될 때 해당 정책이 적용되었음을 알 수 있습니다.




== 기존 볼륨이 있는 일관성 그룹을 생성합니다

기존 볼륨을 사용하여 일관성 그룹을 생성할 수 있습니다.

.단계
. 스토리지 > 정합성 보장 그룹 * 을 선택합니다.
. * + 추가 * 를 선택한 다음 * 기존 볼륨 사용 * 을 선택합니다.
. 일관성 그룹의 이름을 지정하고 스토리지 VM을 선택합니다.
+
.. ** 응용 프로그램 유형**: ONTAP 9.12.1 이상을 사용하는 경우 응용 프로그램 유형을 선택합니다. 값을 선택하지 않으면 기본적으로 정합성 보장 그룹에 ** 기타** 유형이 할당됩니다. 에서 일관성 태그 지정에 대해 자세히 알아보십시오 xref:index.html#application-and-component-tags[응용 프로그램 및 구성 요소 태그]. 정합성 보장 그룹에 SM-BC 관계가 있는 경우 * Other * 를 사용해야 합니다.


. 포함할 기존 볼륨을 선택합니다. 정합성 보장 그룹에 아직 포함되지 않은 볼륨만 선택할 수 있습니다.
+

NOTE: 기존 볼륨으로 일관성 그룹을 생성하는 경우 일관성 그룹은 FlexVol 볼륨을 지원합니다. 비동기식 또는 동기식 SnapMirror 관계가 있는 볼륨을 일관성 그룹에 추가할 수 있지만 일관성 그룹을 인식하는 것은 아닙니다. 일관성 그룹은 S3 버킷 또는 SVM DR 관계가 있는 스토리지 VM을 지원하지 않습니다.

. 저장 * 을 선택합니다.
. ONTAP 작업이 완료되면 표시되는 기본 일관성 그룹 메뉴로 돌아가 일관성 그룹이 생성되었는지 확인합니다. 보호 정책을 선택한 경우 메뉴에서 일관성 그룹을 선택하여 정책이 올바르게 설정되었는지 확인합니다. 보호 정책을 설정하면 해당 정책, 원격 또는 로컬 아래에 녹색 방패 가 표시될 때 해당 정책이 적용되었음을 알 수 있습니다.


.다음 단계
* xref:protect-task.html[일관성 그룹 보호]
* xref:modify-task.html[일관성 그룹 수정]
* xref:clone-task.html[일관성 그룹의 클론을 생성합니다]

