---
permalink: consistency-groups/configure-hierarchy-task.html 
sidebar: sidebar 
keywords: consistency groups, application protection, parent, child, hierarchy 
summary: 대규모 애플리케이션 워크로드 관리 및 데이터 보호를 위한 계층적 일관성 그룹을 생성합니다. 
---
= 계층적 일관성 그룹을 구성합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
애플리케이션 워크로드가 두 개 이상의 볼륨 하위 세트로 구성되어 있고, 각 하위 세트가 자체 연결된 볼륨 전체에서 일관성을 유지할 경우, ONTAP을 통해 계층적 일관성 그룹을 생성할 수 있습니다. 계층적 일관성 그룹에는 최대 5개의 개별 일관성 그룹을 포함할 수 있는 부모가 있습니다. 계층적 일관성 그룹은 일관성 그룹 또는 개별 볼륨에서 서로 다른 로컬 스냅샷 정책을 지원할 수 있습니다. 원격 SM-BC 정책을 사용하는 경우 전체 정합성 보장 그룹에 적용됩니다.

일관성 그룹의 개체 제한은 를 참조하십시오 xref:index.adoc#consistency-group-object-limits[일관성 그룹에 대한 개체 제한].



== 새 볼륨으로 계층적 일관성 그룹을 생성합니다

.단계
. 스토리지 > 정합성 보장 그룹 * 을 선택합니다.
. 추가 * 를 선택한 다음 * 새 LUN 사용 * 을 선택합니다.
. 일관성 그룹의 이름을 지정합니다. LUN당 LUN 수와 용량을 지정합니다.
. 호스트 운영 체제 및 LUN 형식을 선택합니다. 호스트 이니시에이터 정보를 입력합니다.
. 보호 정책을 구성하거나, 하위 일관성 그룹을 추가하거나, 호스트 이니시에이터에 대한 추가 옵션을 표시하려면 * 추가 옵션 * 을 선택합니다.
. 하위 일관성 그룹을 추가하려면 * + 하위 일관성 그룹 추가 * 를 선택합니다.
. 성능 레벨, LUN 수 및 LUN당 용량을 선택합니다. 호스트 운영 체제, LUN 형식을 지정하고 새 호스트 이니시에이터 그룹 또는 기존 호스트 이니시에이터 그룹을 선택합니다.
. * 선택 사항 *: 로컬 스냅샷 정책을 선택합니다.
. 최대 5개의 하위 일관성 그룹에 대해 반복합니다.
. 저장 * 을 선택합니다.
. ONTAP 작업이 완료되면 표시되는 기본 일관성 그룹 메뉴로 돌아가 일관성 그룹이 생성되었는지 확인합니다. 보호 정책을 설정하는 경우 해당 정책, 원격 또는 로컬 아래에서 녹색 차폐가 체크 표시와 함께 표시되어야 합니다.




== 기존 볼륨을 포함하는 계층적 일관성 그룹을 생성합니다

.단계
. 스토리지 > 정합성 보장 그룹 * 을 선택합니다.
. 추가 * 를 선택한 다음 * 기존 볼륨 사용 * 을 선택합니다.
. 스토리지 VM을 선택합니다.
. 포함할 기존 볼륨을 선택합니다. 정합성 보장 그룹에 아직 포함되지 않은 볼륨만 선택할 수 있습니다.
. 하위 일관성 그룹을 추가하려면 * + 하위 일관성 그룹 추가 * 를 선택합니다. 필요한 일관성 그룹을 생성합니다. 이 그룹의 이름은 자동으로 지정됩니다.
. 각 일관성 그룹에 기존 볼륨을 할당합니다.
. * 선택 사항 *: 로컬 스냅샷 정책을 선택합니다.
. 최대 5개의 하위 일관성 그룹에 대해 반복합니다.
. 저장 * 을 선택합니다.
. ONTAP 작업이 완료되면 표시되는 기본 일관성 그룹 메뉴로 돌아가 일관성 그룹이 생성되었는지 확인합니다. 보호 정책을 선택한 경우 메뉴에서 일관성 그룹을 선택하여 정책이 올바르게 설정되었는지 확인합니다. 보호 정책을 설정하는 경우 해당 정책, 원격 또는 로컬 아래에서 녹색 차폐가 체크 표시와 함께 표시되어야 합니다.

