---
sidebar: sidebar 
permalink: consistency-groups/modify-geometry-task.html 
keywords: consistency group geometry, promote consistency group, demote, add consistency group 
summary: ONTAP 9.13.1부터 입출력 작업이 중단되는 정합성 보장 그룹의 구조를 수정할 수 있습니다. 
---
= 정합성 보장 그룹 지오메트리를 수정합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9.13.1부터 정합성 보장 그룹의 지오메트리를 수정할 수 있습니다. 정합성 보장 그룹의 구조를 수정하면 지속적인 입출력 작업을 중단하지 않고 하위 또는 상위 정합성 보장 그룹의 구성을 변경할 수 있습니다.

일관성 그룹 형상을 수정하면 일관성 그룹의 기존 스냅샷 복사본에 영향을 미칩니다. 자세한 내용은 수행하려는 지오메트리의 특정 수정 사항을 참조하십시오.


NOTE: 원격 보호 정책으로 구성된 정합성 보장 그룹의 구조는 수정할 수 없습니다. 먼저 보호 관계를 끊은 후 지오메트리를 수정한 다음 원격 보호를 복원해야 합니다.



== 새 하위 일관성 그룹을 추가합니다

ONTAP 9.13.1부터 새 하위 일관성 그룹을 기존 부모 일관성 그룹에 추가할 수 있습니다.

.이 작업에 대해
* 부모 일관성 그룹에는 최대 5개의 자식 일관성 그룹이 포함될 수 있습니다. 을 참조하십시오 xref:limits.html[정합성 보장 그룹 제한] 기타 제한.
* 단일 일관성 그룹에는 하위 일관성 그룹을 추가할 수 없습니다. 먼저 해야 합니다 <<승격>> 그러면 일관성 그룹을 자식 일관성 그룹에 추가할 수 있습니다.
* 확장 작업 전에 캡처된 일관성 그룹의 기존 스냅샷 복사본은 부분적으로 간주됩니다. 스냅샷 복사본을 기반으로 하는 모든 복원 작업은 스냅샷 복사본 시점의 일관성 그룹을 반영합니다.


.단계
[role="tabbed-block"]
====
.시스템 관리자
--
ONTAP 9.13.1부터 System Manager로 이 작업을 수행할 수 있습니다.

.새 하위 일관성 그룹을 추가합니다
. 스토리지 > 정합성 보장 그룹 * 을 선택합니다.
. 하위 일관성 그룹을 추가할 상위 일관성 그룹을 선택합니다.
. 부모 일관성 그룹의 이름 옆에 있는 ** 자세히** 를 선택한 다음 ** 새 자식 일관성 그룹 추가** 를 선택합니다.
. 일관성 그룹의 이름을 입력합니다.
. 새 볼륨이나 기존 볼륨을 추가할지 여부를 선택합니다.
+
.. 기존 볼륨을 추가하는 경우** existing volumes** 를 선택한 다음 드롭다운 메뉴에서 볼륨을 선택합니다.
.. 새 볼륨을 추가하는 경우 ** 새 볼륨** 을 선택한 다음 볼륨 수와 해당 크기를 지정합니다.


. ** 추가** 를 선택합니다.


--
.CLI를 참조하십시오
--
ONTAP 9.14.1부터 ONTAP CLI를 사용하여 하위 정합성 보장 그룹을 추가할 수 있습니다.

.시작하기 전에
* 이 작업을 수행하려면 admin 권한 수준이어야 합니다.
* ONTAP 9.14.1에서 이 작업을 수행하려면 클러스터 또는 SVM 관리자여야 합니다. ONTAP 9.15.1부터 admin 권한 수준의 모든 사용자가 이 작업을 수행할 수 있습니다.


.새 볼륨이 포함된 하위 정합성 보장 그룹을 추가합니다
. 새 일관성 그룹을 생성합니다. 일관성 그룹 이름, 볼륨 접두사, 볼륨 수, 볼륨 크기, 스토리지 서비스 등의 값을 입력합니다. 및 엑스포트 정책 이름:
+
`consistency-group create -vserver _SVM_name_ -consistency-group _consistency_group_ -parent-consistency-group _parent_consistency_group_ -volume-prefix _prefix_ -volume-count _number_ -size _size_ -storage-service _service_ -export-policy _policy_name_`



.기존 볼륨이 있는 하위 정합성 보장 그룹을 추가합니다
. 새 일관성 그룹을 생성합니다. 를 클릭합니다 `volumes` 매개 변수에는 쉼표로 구분된 볼륨 이름 목록을 사용할 수 있습니다.
+
`consistency-group create -vserver _SVM_name_ -consistency-group _new_consistency_group_ -parent-consistency-group _parent_consistency_group_ -volumes _volume_`



--
====


== 하위 일관성 그룹을 분리합니다

ONTAP 9.13.1부터 부모 일관성 그룹을 제거하여 개별 일관성 그룹으로 변환할 수 있습니다.

.이 작업에 대해
* 하위 일관성 그룹을 분리하면 부모 일관성 그룹의 스냅샷 복사본이 유효하지 않게 되고 액세스할 수 없게 됩니다. 볼륨 세분화 스냅샷 복사본은 그대로 유효합니다.
* 개별 일관성 그룹의 기존 스냅샷 복사본이 계속 유효합니다.
* 분리할 하위 정합성 보장 그룹과 이름이 같은 기존 단일 정합성 보장 그룹이 있는 경우 이 작업이 실패합니다. 이 시나리오가 발생한 경우 일관성 그룹을 분리할 때 일관성 그룹의 이름을 변경해야 합니다.


.단계
[role="tabbed-block"]
====
.시스템 관리자
--
ONTAP 9.13.1부터 System Manager로 이 작업을 수행할 수 있습니다.

.하위 일관성 그룹을 분리합니다
. 스토리지 > 정합성 보장 그룹 * 을 선택합니다.
. 분리할 자식이 포함된 부모 일관성 그룹을 선택합니다.
. 분리하려는 하위 일관성 그룹 옆에 있는 ** 자세히 ** 를 선택한 다음 ** 부모에서 분리** 를 선택합니다.
. 선택적으로 일관성 그룹의 이름을 바꾸고 애플리케이션 유형을 선택합니다.
. ** 분리** 를 선택합니다.


--
.CLI를 참조하십시오
--
ONTAP 9.14.1부터 ONTAP CLI를 사용하여 하위 정합성 보장 그룹을 분리할 수 있습니다.

.시작하기 전에
* 이 작업을 수행하려면 admin 권한 수준이어야 합니다.
* ONTAP 9.14.1에서 이 작업을 수행하려면 클러스터 또는 SVM 관리자여야 합니다. ONTAP 9.15.1부터 admin 권한 수준의 모든 사용자가 이 작업을 수행할 수 있습니다.


.하위 일관성 그룹을 분리합니다
. 정합성 보장 그룹을 분리합니다. 필요한 경우 분리된 정합성 보장 그룹의 이름을 로 변경합니다 `-new-name` 매개 변수.
+
`consistency-group detach -vserver _SVM_name_ -consistency-group _child_consistency_group_ -parent-consistency-group _parent_consistency_group_ [-new-name _new_name_]`



--
====


== 부모 일관성 그룹 아래에서 기존 단일 일관성 그룹을 이동합니다

ONTAP 9.13.1부터 기존 단일 일관성 그룹을 하위 일관성 그룹으로 변환할 수 있습니다. 이동 작업 중에 일관성 그룹을 기존 부모 일관성 그룹 아래로 이동하거나 새 부모 일관성 그룹을 생성할 수 있습니다.

.이 작업에 대해
* 상위 일관성 그룹의 하위 항목이 4개 이하가 되어야 합니다. 부모 일관성 그룹에는 최대 5개의 자식 일관성 그룹이 포함될 수 있습니다. 을 참조하십시오 xref:limits.html[정합성 보장 그룹 제한] 기타 제한.
* 이 작업을 수행하기 전에 캡처한 _parent_consistency 그룹의 기존 스냅샷 복사본이 부분 복사본으로 간주됨 이러한 스냅샷 복사본 중 하나를 기반으로 하는 복원 작업은 스냅샷 복사본 시점의 일관성 그룹을 반영합니다.
* 단일 일관성 그룹의 기존 일관성 그룹의 스냅샷 복사본은 그대로 유효합니다.


.단계
[role="tabbed-block"]
====
.시스템 관리자
--
ONTAP 9.13.1부터 System Manager로 이 작업을 수행할 수 있습니다.

.부모 일관성 그룹 아래에서 기존 단일 일관성 그룹을 이동합니다
. 스토리지 > 정합성 보장 그룹 * 을 선택합니다.
. 변환할 일관성 그룹을 선택합니다.
. 더 보기** 를 선택한 다음 ** 다른 정합성 보장 그룹 아래로 이동** 을 선택합니다.
. 선택적으로 일관성 그룹의 새 이름을 입력하고 구성요소 유형을 선택합니다. 기본적으로 부품 유형은 다른 유형입니다.
. 기존 부모 일관성 그룹으로 마이그레이션하거나 새 부모 일관성 그룹을 생성할지 선택합니다.
+
.. 기존 부모 일관성 그룹으로 마이그레이션하려면 ** 기존 일관성 그룹**을 선택한 다음 드롭다운 메뉴에서 일관성 그룹을 선택합니다.
.. 새 부모 일관성 그룹을 생성하려면 ** 새 일관성 그룹**을 선택한 다음 새 일관성 그룹의 이름을 제공합니다.


. ** 이동**을 선택합니다.


--
.CLI를 참조하십시오
--
ONTAP 9.14.1부터는 ONTAP CLI를 사용하여 단일 일관성 그룹을 부모 일관성 그룹 아래로 이동할 수 있습니다.

.시작하기 전에
* 이 작업을 수행하려면 admin 권한 수준이어야 합니다.
* ONTAP 9.14.1에서 이 작업을 수행하려면 클러스터 또는 SVM 관리자여야 합니다. ONTAP 9.15.1부터 admin 권한 수준의 모든 사용자가 이 작업을 수행할 수 있습니다.


.일관성 그룹을 새 부모 일관성 그룹 아래로 이동합니다
. 새 부모 일관성 그룹을 생성합니다. 를 클릭합니다 `-consistency-groups` 매개 변수는 기존 일관성 그룹을 새 부모로 마이그레이션합니다.
+
`consistency-group attach -vserver _svm_name_ -consistency-group _parent_consistency_group_ -consistency-groups _child_consistency_group_`



.기존 일관성 그룹 아래에서 일관성 그룹을 이동합니다
. 정합성 보장 그룹 이동:
+
`consistency-group add -vserver _SVM_name_ -consistency-group _consistency_group_ -parent-consistency-group _parent_consistency_group_`



--
====


== 하위 일관성 그룹을 승격합니다

ONTAP 9.13.1부터 단일 일관성 그룹을 부모 일관성 그룹으로 승격할 수 있습니다. 단일 일관성 그룹을 상위 일관성 그룹으로 승격하면 원래의 단일 일관성 그룹에 있는 모든 볼륨을 상속하는 새 하위 일관성 그룹도 생성됩니다.

.이 작업에 대해
* 하위 일관성 그룹을 부모 일관성 그룹으로 변환하려면 먼저 해야 합니다 <<detach>> 그런 다음 하위 일관성 그룹을 이 절차에 따릅니다.
* 일관성 그룹을 프로모션한 후에도 일관성 그룹의 기존 스냅샷 복사본은 계속 유효합니다.


[role="tabbed-block"]
====
.시스템 관리자
--
ONTAP 9.13.1부터 System Manager로 이 작업을 수행할 수 있습니다.

.하위 일관성 그룹을 승격합니다
. 스토리지 > 정합성 보장 그룹 * 을 선택합니다.
. 상향 이동할 정합성 보장 그룹을 선택합니다.
. 더 보기** 를 선택한 다음 ** 부모 일관성 그룹으로 승격** 을 선택합니다.
. ** 이름** 을 입력하고 자식 일관성 그룹에 대한** 구성 요소 형식** 을 선택합니다.
. ** 승격**을 선택합니다.


--
.CLI를 참조하십시오
--
ONTAP 9.14.1부터는 ONTAP CLI를 사용하여 단일 일관성 그룹을 부모 일관성 그룹 아래로 이동할 수 있습니다.

.시작하기 전에
* 이 작업을 수행하려면 admin 권한 수준이어야 합니다.
* ONTAP 9.14.1에서 이 작업을 수행하려면 클러스터 또는 SVM 관리자여야 합니다. ONTAP 9.15.1부터 admin 권한 수준의 모든 사용자가 이 작업을 수행할 수 있습니다.


.하위 일관성 그룹을 승격합니다
. 정합성 보장 그룹을 승격합니다. 이 명령은 부모 정합성 보장 그룹 하나와 자식 정합성 보장 그룹 하나를 생성합니다.
+
`consistency-group promote -vserver _SVM_name_ -consistency-group _existing_consistency_group_ -new-name _new_child_consistency_group_`



--
====


== 상위 항목을 단일 일관성 그룹으로 강등합니다

ONTAP 9.13.1부터 부모 일관성 그룹을 단일 일관성 그룹으로 강등할 수 있습니다. 모체를 강등하면 정합성 보장 그룹의 계층 구조가 평평하여 연결된 모든 자식 일관성 그룹이 제거됩니다. 일관성 그룹의 모든 볼륨은 새로운 단일 일관성 그룹에 유지됩니다.

.이 작업에 대해
* 단일 정합성 보장으로 강등한 후에도 _parent_consistency 그룹의 기존 스냅샷 복사본은 유효한 상태로 유지됩니다. 해당 부모에 대한 associated_child_consistency 그룹의 기존 스냅샷 복사본이 강등 시 유효하지 않게 됩니다. 하위 일관성 그룹 내의 개별 볼륨 스냅샷 복사본에 볼륨별 스냅샷 복사본으로 계속 액세스할 수 있습니다.


.단계
[role="tabbed-block"]
====
.시스템 관리자
--
ONTAP 9.13.1부터 System Manager로 이 작업을 수행할 수 있습니다.

.일관성 그룹을 강등합니다
. 스토리지 > 정합성 보장 그룹 * 을 선택합니다.
. 강등할 상위 일관성 그룹을 선택합니다.
. 더 보기** 를 선택한 다음 ** 단일 정합성 보장 그룹으로 하향 이동** 을 선택합니다.
. 연결된 모든 하위 정합성 보장 그룹이 삭제되고 해당 볼륨이 새 단일 정합성 보장 그룹 아래로 이동된다는 경고 메시지가 표시됩니다. ** 하향 이동** 을 선택하여 충격 이해 여부를 확인합니다.


--
.CLI를 참조하십시오
--
ONTAP 9.14.1부터 ONTAP CLI를 사용하여 일관성 그룹을 강등할 수 있습니다.

.시작하기 전에
* 이 작업을 수행하려면 admin 권한 수준이어야 합니다.
* ONTAP 9.14.1에서 이 작업을 수행하려면 클러스터 또는 SVM 관리자여야 합니다. ONTAP 9.15.1부터 admin 권한 수준의 모든 사용자가 이 작업을 수행할 수 있습니다.


.일관성 그룹을 강등합니다
. 정합성 보장 그룹을 강등합니다. 옵션 을 사용합니다 `-new-name` 일관성 그룹의 이름을 바꾸는 매개 변수입니다.
+
`consistency-group demote -vserver _SVM_name_ -consistency-group _parent_consistency_group_ [-new-name _new_consistency_group_name_]`



--
====