---
sidebar: sidebar 
permalink: concept_object_provision_overview.html 
keywords: StorageGRID, Amazon Simple Storage Service, S3, storage, object, object storage, object storage server, object provision, overview, on-premises, FabricPool, AFF, tier, tiering, bucket, remote, local, cluster, clusters, cloud tier, self-tiering, deployments, performance, throughput, capacity, latency, QoS 
summary: 'ONTAP 9.8부터 ONTAP 클러스터에서 Amazon S3(Simple Storage Service) 오브젝트 스토리지 서버를 활성화할 수 있습니다.' 
---
= System Manager를 사용한 ONTAP S3 구성 개요
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
이 섹션의 항목에서는 ONTAP 9.8 이상 릴리즈의 System Manager에서 S3 오브젝트 스토리지 서비스를 구성 및 관리하는 방법을 보여 줍니다.

ONTAP 9.8부터 ONTAP 클러스터에서 ONTAP S3(Simple Storage Service) 오브젝트 스토리지 서버를 활성화할 수 있습니다. 자세한 내용은 을 참조하십시오 link:s3-config/s3-support-concept.html["ONTAP 9에서 S3 지원"].

System Manager는 S3 오브젝트 스토리지를 지원하기 위한 두 가지 사내 사용 사례 시나리오를 지원합니다.

* 로컬 클러스터(로컬 버킷에 계층화) 또는 원격 클러스터(클라우드 계층)의 버킷에 대한 FabricPool 계층
* S3 클라이언트 애플리케이션이 로컬 클러스터 또는 원격 클러스터의 버킷에 액세스합니다.


FabricPool 계층화에 대한 자세한 내용은 를 참조하십시오 link:concept_cloud_overview.html["System Manager를 이용한 FabricPool 계층 관리 개요"].


NOTE: ONTAP S3는 추가 하드웨어 및 관리 없이 기존 클러스터에서 S3 기능을 원하는 경우에 적합합니다. 300TB 이상의 배포를 위해 NetApp StorageGRID 소프트웨어는 계속해서 오브젝트 스토리지를 위한 NetApp의 대표적인 솔루션입니다. 자세한 내용은 를 참조하십시오 link:https://docs.netapp.com/sgws-114/index.jsp["StorageGRID 설명서"^].

System Manager를 사용하여 S3 버킷을 생성하는 경우, ONTAP은 시스템에서 가장 가용성이 높은 기본 성능 서비스 수준을 구성합니다. 예를 들어, AFF 시스템에서 기본 설정은 * Extreme * 입니다. 성능 서비스 수준은 사전 정의된 QoS(Quality of Service) 정책 그룹입니다. 기본 서비스 수준 대신 사용자 지정 QoS 정책 그룹 또는 정책 그룹을 지정할 수 있습니다.

사전 정의된 적응형 QoS 정책 그룹은 다음과 같습니다.

* * Extreme *: 가장 낮은 지연 시간과 최고의 성능을 기대하는 애플리케이션에 사용됩니다.
* * 성능 *: 성능 요구사항 및 지연 시간이 중간 정도인 애플리케이션에 사용됩니다.
* * 가치 *: 처리량과 용량이 지연 시간보다 더 중요한 애플리케이션에 사용됩니다.
* * 사용자 정의 *: 사용자 정의 QoS 정책을 지정하거나 QoS 정책을 지정하지 않습니다.


계층화에 * 사용을 선택하면 성능 서비스 수준이 선택되지 않으며 시스템은 계층형 데이터에 대해 최적의 성능을 갖춘 저비용 미디어를 선택합니다.

참고 항목: link:./performance-admin/adaptive-qos-policy-groups-task.html["적응형 QoS 정책 그룹을 사용합니다"].

ONTAP는 가장 적합한 디스크가 있는 로컬 계층에서 이 버킷을 프로비저닝하려고 시도하여 선택한 서비스 수준을 충족시킵니다. 그러나 버킷에 포함할 디스크를 지정해야 하는 경우 로컬 계층(애그리게이트)을 지정하여 CLI에서 S3 오브젝트 스토리지를 구성하는 것이 좋습니다. CLI에서 S3 서버를 구성할 경우에도 원할 경우 System Manager로 관리할 수 있습니다. 자세한 내용은 의 설명서를 참조하십시오 xref:s3-config/index.adoc[CLI를 사용한 S3 구성].



== Cloud Volumes ONTAP에서 S3 버킷 구성

Cloud Volumes ONTAP에서 버킷 서비스를 제공하려면 기본 애그리게이트를 수동으로 선택하여 해당 애그리게이트가 하나의 노드만 사용하는지 확인하는 것이 좋습니다. 두 노드의 애그리게이트를 사용하면 지리적으로 서로 분리되어 있는 가용성 영역에 노드가 있기 때문에 지연 시간 문제가 발생하기 때문에 성능에 영향을 미칠 수 있습니다. 따라서 Cloud Volumes ONTAP 환경에서는 이 작업을 수행해야 합니다 link:s3config/create-bucket-task.html["CLI에서 S3 버킷을 구성합니다"].

그렇지 않으면 Cloud Volumes ONTAP의 S3 서버가 사내 환경과 Cloud Volumes ONTAP에서 동일하게 구성 및 관리됩니다
