---
sidebar: sidebar 
permalink: concept_security_overview.html 
keywords: netapp, ontap, security, overview, secure data, data, cluster, access, storage, virus scanning, encryption, WORM storage, client authentication, client authorization, administrator authentication, RBAC, role-based access control, login, log in, antivirus, anti-virus, Vscan, SnapLock, regulation 
summary: ONTAP 9.7부터 System Manager를 사용하여 클러스터 보안을 관리할 수 있습니다. 
---
= System Manager의 보안 관리 개요
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
ONTAP 9.7부터 System Manager를 사용하여 클러스터 보안을 관리할 수 있습니다.

System Manager를 사용하면 ONTAP 표준 방법을 통해 클라이언트 및 관리자의 스토리지 액세스 권한을 보호하고 바이러스로부터 보호할 수 있습니다. 사용되지 않는 데이터의 암호화 및 WORM 스토리지의 고급 기술을 사용할 수 있습니다.

클래식 시스템 관리자(ONTAP 9.7 이전에서만 사용 가능)를 사용하는 경우 를 참조하십시오  https://docs.netapp.com/us-en/ontap-sm-classic/index.html["System Manager Classic(ONTAP 9.0 ~ 9.7)"^]



== 클라이언트 인증 및 권한 부여

ONTAP는 신뢰할 수 있는 소스로 ID를 확인하여 클라이언트 시스템과 사용자를 인증합니다. ONTAP는 사용자의 자격 증명을 파일 또는 디렉터리에 구성된 권한과 비교하여 사용자가 파일 또는 디렉터리에 액세스할 수 있도록 승인합니다.



== 관리자 인증 및 RBAC

관리자는 로컬 또는 원격 로그인 계정을 사용하여 클러스터 및 스토리지 VM에 대한 자체 인증을 수행합니다. 역할 기반 액세스 제어(RBAC)는 관리자가 액세스할 수 있는 명령을 결정합니다.



== 바이러스 검사

스토리지 시스템에서 통합 바이러스 백신 기능을 사용하여 바이러스나 기타 악성 코드에 의해 데이터가 손상되는 것을 방지할 수 있습니다. ONTAP 바이러스 검사(_Vscan_)는 동급 최강의 타사 바이러스 백신 소프트웨어와 ONTAP 기능을 결합하여 언제 어떤 파일을 스캔할지 제어하는 데 필요한 유연성을 제공합니다.



== 암호화

ONTAP는 스토리지 미디어의 용도 변경, 반환, 잘못된 위치 변경 또는 도난 시 유휴 데이터를 읽을 수 없도록 소프트웨어 및 하드웨어 기반 암호화 기술을 모두 제공합니다.



== WORM 스토리지

_SnapLock_는 규정 및 거버넌스 목적을 위해 중요한 파일을 수정되지 않은 형태로 유지하기 위해 _write once_, _read many(WORM)_ 스토리지를 사용하는 조직을 위한 고성능 규정 준수 솔루션입니다.
