---
sidebar: sidebar 
permalink: concept_administration_overview.html 
keywords: netapp, system manager, ontap, administration, overview, cluster, node, local tier, aggregate, svm, storage vm, service level, volume, qtree, LUN, automatic aggregate selection, vserver, protocol, quota, disk, HA pair, dashboard, subnet, domain, interface, mirroring, vaulting, storage, html5 
summary: System Manager를 사용하면 스토리지 시스템과 스토리지 객체를 관리하고 웹 브라우저에서 스토리지 시스템과 관련된 공통 관리 작업을 수행할 수 있습니다. 
---
= System Manager의 관리 개요
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
System Manager는 HTML5 기반의 그래픽 관리 인터페이스로, 웹 브라우저를 사용하여 스토리지 시스템과 스토리지 객체(예: 디스크, 볼륨 및 스토리지 계층)를 관리하고 스토리지 시스템과 관련된 일반적인 관리 작업을 수행할 수 있습니다.

이 섹션의 절차를 사용하면 ONTAP 9.7 이상 릴리즈의 System Manager에서 클러스터를 관리할 수 있습니다.

[NOTE]
====
* System Manager는 ONTAP 소프트웨어에 웹 서비스로 포함되어 있으며, 기본적으로 활성화되어 있으며 브라우저를 통해 액세스할 수 있습니다.
* System Manager의 이름이 ONTAP 9.6부터 변경되었습니다. ONTAP 9.5 이전 버전에서는 OnCommand 시스템 관리자라고 했습니다. ONTAP 9.6 이상에서는 시스템 관리자라고 합니다.
* 클래식 시스템 관리자(ONTAP 9.7 이전에서만 사용 가능)를 사용하는 경우 를 참조하십시오  https://docs.netapp.com/us-en/ontap-sm-classic/index.html["System Manager Classic(ONTAP 9.0 ~ 9.7)"^]


====
System Manager 대시보드를 사용하면 중요한 경고 및 알림, 스토리지 계층 및 볼륨의 효율성 및 용량, 클러스터에서 사용 가능한 노드, HA 쌍의 노드 상태, 가장 활성화된 애플리케이션 및 객체 등에 대한 정보를 한 눈에 확인할 수 있습니다. 클러스터 또는 노드의 성능 메트릭과

System Manager를 사용하면 다음과 같은 일반적인 작업을 수행할 수 있습니다.

* 클러스터를 생성하고, 네트워크를 구성하고, 클러스터에 대한 지원 세부 정보를 설정합니다.
* 디스크, 로컬 계층, 볼륨, Qtree, 디스크 등의 스토리지 오브젝트 구성 및 관리 있습니다.
* SMB 및 NFS와 같은 프로토콜을 구성하고 파일 공유를 프로비저닝합니다.
* 블록 액세스를 위해 FC, FCoE, NVMe 및 iSCSI와 같은 프로토콜을 구성합니다.
* 서브넷, 브로드캐스트 도메인, 데이터 및 관리 인터페이스, 인터페이스 그룹 등의 네트워크 구성 요소를 만들고 구성합니다.
* 미러링 및 보관 관계 설정 및 관리
* 클러스터 관리, 스토리지 노드 관리 및 스토리지 가상 머신(스토리지 VM) 관리 작업을 수행합니다.
* 스토리지 VM 생성 및 구성, 스토리지 VM과 연결된 스토리지 객체 관리, 스토리지 VM 서비스 관리
* 클러스터의 고가용성(HA) 구성 모니터링 및 관리
* 노드의 상태에 관계없이 노드를 원격으로 로그인, 관리, 모니터링 및 관리하도록 서비스 프로세서를 구성합니다.




== System Manager 용어

System Manager에서는 일부 ONTAP 키 기능에 CLI와 다른 용어를 사용합니다.

* * 로컬 계층 * – 데이터를 저장하는 물리적 솔리드 스테이트 드라이브 또는 하드 디스크 드라이브 세트입니다. 이런 것을 Aggregate으로 알고 계실 것입니다. 실제로 ONTAP CLI를 사용하는 경우 로컬 계층을 나타내는 데 사용되는 _aggregate_라는 용어가 계속 표시됩니다.
* * 클라우드 계층 * – 여러 가지 이유 중 하나로 일부 데이터를 오프프레미스로 사용하려는 경우 ONTAP에서 사용하는 클라우드의 스토리지입니다. FabricPool의 클라우드 부분을 생각한다면 이미 그 사실을 알아냈을 것입니다. 또한 StorageGRID 시스템을 사용하는 경우 클라우드가 사외 환경에 있지 않을 수 있습니다. (온프레미스의 클라우드형 경험을 _ 프라이빗 클라우드라고 합니다.)
* * 스토리지 VM * – ONTAP 내에서 실행되는 가상 시스템으로, 고객에게 스토리지 및 데이터 서비스를 제공합니다. 이를 _SVM_ 또는 _vserver_로 알고 있을 수 있습니다.
* * 네트워크 인터페이스 * - 물리적 네트워크 포트에 할당된 주소 및 속성입니다. 이를 LIF(논리 인터페이스) _ 로 알고 있을 수 있습니다.
* * 일시 중지 * - 작업을 정지하는 작업입니다. ONTAP 9.8 이전에는 다른 버전의 System Manager에서 _quiesce_를 참조했습니다.

