---
sidebar: sidebar 
permalink: concept_key_ontap.html 
keywords: netapp, ontap, cluster, node, local tier, cloud tier, aggregate, SVM, storage VM, service level, volume, qtree, LUN, automatic aggregate selection, tier selection, vserver, ONTAP concepts, terms, Snapshot copy, data protection, mirroring, HA pair, storage efficiency, compression, deduplication, compaction, multifactor authentication, client, LUN, NVMe, quiesce, quiescing, pause, namespace, flash storage 
summary: ONTAP에 대한 간략한 소개와 현재 고객을 위한 몇 가지 용어 변경 사항 
---
= 주요 개념
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
NetApp ONTAP는 NetApp의 검증된 데이터 관리 소프트웨어입니다. 데이터 센터에서 ONTAP 엔지니어링 하드웨어, 일반 하드웨어 또는 주요 퍼블릭 클라우드를 기반으로 실행할 수 있습니다.



== System Manager 정보

System Manager(이전의 OnCommand System Manager)는 ONTAP 클러스터를 쉽게 구성 및 관리할 수 있는 단순하고 유연한 제품입니다. System Manager는 볼륨, LUN, Qtree, 공유 및 엑스포트 생성과 같은 공통 스토리지 작업을 간소화합니다. 시간을 절약하고 오류를 방지할 수 있습니다.

ONTAP 9.7부터 완전히 재설계된 System Manager는 다음과 같은 기능을 제공하는 직관적인 그래픽 사용자 인터페이스를 통해 ONTAP 관리를 간소화합니다.

* 빠르고 간단한 구성
+
공통 작업의 ONTAP 설정 및 관리를 위한 워크플로우 간소화

* 스마트 기본값
+
검증된 구축을 기반으로 최적의 구성을 구축할 수 있습니다.

* 폭넓은 관리 기능
+
파일 공유, 애플리케이션 및 데이터베이스 워크로드를 위한 스토리지를 손쉽게 구성 및 프로비저닝할 수 있습니다.

* 통합 관리 System Manager는 ONTAP 9 플랫폼과 함께 번들로 제공되므로 별도로 설치할 필요가 없습니다. 한 화면에 주요 클러스터 상태 및 성능을 보여주는 새로운 대시보드


System Manager를 사용하면 클러스터의 상태를 정확하게 파악하고 스토리지 목표를 달성할 수 있는 최상의 방법을 찾을 수 있습니다.

이전 버전의 ONTAP에 익숙하다면 집에 있는 듯한 느낌이 들 것입니다. System Manager에서 몇 가지 용어에 대한 변경 사항은 알고 있어야 합니다.

* * 로컬 계층 * – 데이터를 저장하는 물리적 솔리드 스테이트 드라이브 또는 하드 디스크 드라이브 세트입니다. 이런 것을 Aggregate으로 알고 계실 것입니다. 실제로 ONTAP CLI를 사용하는 경우 로컬 계층을 나타내는 데 사용되는 _aggregate_라는 용어가 계속 표시됩니다.
* * 클라우드 계층 * – 여러 가지 이유 중 하나로 일부 데이터를 오프프레미스로 사용하려는 경우 ONTAP에서 사용하는 클라우드의 스토리지입니다. FabricPool의 클라우드 부분을 생각한다면 이미 그 사실을 알아냈을 것입니다. 또한 StorageGRID 시스템을 사용하는 경우 클라우드가 사외 환경에 있지 않을 수 있습니다. (온프레미스의 클라우드형 경험을 _ 프라이빗 클라우드라고 합니다.)
* * 스토리지 VM * – ONTAP 내에서 실행되는 가상 시스템으로, 고객에게 스토리지 및 데이터 서비스를 제공합니다. 이를 _SVM_ 또는 _vserver_로 알고 있을 수 있습니다.
* * 네트워크 인터페이스 * - 물리적 네트워크 포트에 할당된 주소 및 속성입니다. 이를 LIF(논리 인터페이스) _ 로 알고 있을 수 있습니다.
* * 일시 중지 * - 작업을 정지하는 작업입니다. ONTAP 9.8 이전에는 다른 버전의 System Manager에서 _quiesce_를 참조했습니다.


ONTAP를 처음 사용하는 경우, 다음과 같은 몇 가지 다른 개념을 빠르게 이해할 수 있습니다.

* * 클러스터 * – 큰 그림입니다. 클러스터는 하나 이상의 노드로 구성됩니다. 노드를 데이터 관리 및 스토리지 전문 컴퓨터로 생각하면 됩니다. 필요에 따라 클러스터에 노드를 추가하거나 더 작은 노드를 더 큰 노드로 바꿀 수 있습니다. 물론 데이터 액세스를 중단하지 않고 수행할 수 있습니다.
* * 스냅샷 복사본 * – 실수를 실행 취소하거나 클라우드로 이동하거나 백업하거나 다른 클러스터에 미러링하거나 테이프에 복사하는 데 사용할 수 있는 즉각적인 데이터 복사본입니다. 고객 서비스 중단 없음 그리고 누가 다운타임을 허용할 수 있습니까?
* * 데이터 보호 * - 사용하는 보호 기능은 보호해야 할 사항 및 문제가 발생할 경우 복구를 대기하는 기간에 따라 달라집니다. ONTAP은 동기식 및 비동기식 미러링 등을 제공합니다.
* * HA 쌍 * – 다운타임을 방지하기 위한 한 가지 방법은 고가용성 쌍이 ONTAP 클러스터의 기본 단위입니다. 이 노드는 서로 인수할 수 있는 두 개의 파트너 노드로 구성되어 있습니다. 최신 버전의 ONTAP로 업그레이드하여 새로운 데이터 관리 기능을 사용해 보십시오. 파트너가 노드의 클라이언트 로드를 인계받아 해당 클라이언트를 업그레이드한 다음 로드를 다시 제공하도록 합니다. 파트너 노드에 대해 이 단계를 반복하면 운영 중단 없이 방금 업그레이드됩니다.
* * 스토리지 효율성 * – 디스크 비용은 비용(실제 비용)이지만 스토리지 효율성을 통해 더 적은 공간에 더 많은 데이터를 저장할 수 있습니다. 또한 실제 비용을 절감하고 데이터 영웅이 될 수 있습니다. ONTAP의 압축, 중복제거 및 컴팩션 기능을 일부 또는 모두 사용할 수 있습니다. 압축에 대해 이미 알고 계시겠지만, 중복 제거는 동일한 데이터의 여러 복사본을 식별하여 단일 복사본을 가리키는 포인터로 대체합니다. 컴팩션에서는 작은 파일 여러 개를 단일 스토리지 블록에 넣어 낭비하는 공간을 채웁니다.
* * 보안 * – 보안은 ONTAP 데이터 관리 소프트웨어에 필수적인 요소입니다. ONTAP는 관리자를 위한 다단계 인증 사용, 디스크 및 전송 중 데이터 암호화, 바이러스 백신 도구를 사용하여 Windows 파일을 보호하는 등 다양한 방법을 지원합니다.
* * 볼륨 * – 볼륨이 정확하다고 생각하는 것과 같습니다. 파일을 저장할 컨테이너입니다. Linux 클라이언트로 볼륨을 내보내고, Windows 클라이언트와 볼륨을 공유하거나, 동일한 파일을 사용하여 동시에 두 작업을 수행할 수도 있습니다.
* * LUNs * – SAN의 기본 단위입니다. 이것이 바로 파이버 채널과 iSCSI입니다. SAN 환경에서 ONTAP는 파일 대신 클라이언트에 가상 디스크를 제공합니다. 데이터베이스 관리자는 종종 가상 디스크를 낮은 수준에서 관리하거나 특수한 파일 시스템을 에 적용할 수 있기를 원합니다. 모든 시스템이 아닌 많은 ONTAP 시스템이 SAN 클라이언트에 데이터를 제공할 수 있습니다.
* * NVMe 네임스페이스 * – 플래시 스토리지의 미래 NVMe 프로토콜은 SSD 기반 스토리지를 위해 최적화되어 있으며 매우 빠릅니다. NVMe는 SAN의 한 가지 취향이지만 LUN 대신 기본 스토리지 단위를 _namespace_라고 합니다.


ONTAP에 대한 자세한 내용은 ONTAP를 참조하십시오 link:./concepts/index.html["개념 개요"].



== System Manager 사용 사례 비디오

video::PrpfVnN3dyk[youtube,width=848,height=480]