---
sidebar: sidebar 
permalink: concept_metrocluster_manage_nodes.html 
keywords: system manager, manage, metrocluster, clusters, nodes, mcc, HA, config, peering, peers, pairing, pairs 
summary: ONTAP 9.8부터 System Manager로 MetroCluster 운영을 관리할 수 있습니다. 
---
= System Manager를 사용한 MetroCluster IP 사이트 관리
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
MetroCluster 구성은 별도의 위치에 있는 두 ONTAP 클러스터 간에 데이터와 구성을 동기식으로 미러링합니다. ONTAP 9.8부터 System Manager를 사용하여 MetroCluster IP 구성을 간편하게 관리할 수 있습니다.


NOTE: MetroCluster IP 구성에서 System Manager를 통해서만 MetroCluster 작업을 수행할 수 있습니다. MetroCluster FC 구성에서는 System Manager를 사용하여 MetroCluster 구성의 각 노드를 관리할 수 있지만 MetroCluster 관련 작업은 수행할 수 없습니다.

일반적으로, 별도의 두 지리적 사이트에서 MetroCluster 구성으로 클러스터를 설정하고 구성합니다. 그런 다음 클러스터 간에 피어링을 설정하여 데이터가 동기화되고 공유되도록 합니다. 피어링된 네트워크에 있는 두 클러스터는 양방향 DR(재해 복구)을 제공하며, 각 클러스터가 다른 클러스터의 소스와 백업될 수 있습니다. 8노드 또는 4노드 MetroCluster IP 구성에서 각 사이트는 하나 또는 두 개의 고가용성(HA) 쌍으로 구성된 스토리지 컨트롤러로 구성됩니다.

세 번째 위치에서 노드와 해당 DR 파트너의 상태를 모니터링할 수 link:https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/concept_mediator_requirements.html["ONTAP 중재자 서비스를 설치합니다"^]있습니다. ONTAP 중재자 서비스는 재해 발생 시 MAUSO(mediator-assisted unplanned switchover)를 구현할 수 있습니다.

협상된 스위치오버를 수행하여 계획된 유지 관리를 위해 클러스터 중 하나를 가져올 수도 있습니다. 파트너 클러스터는 유지보수 작업을 수행한 클러스터를 불러와서 스위치백 작업을 수행할 때까지 두 클러스터에 대한 모든 데이터 I/O 작업을 처리합니다.

에서 System Manager를 사용하여 MetroCluster IP 구성을 설정 및 관리하는 절차를 찾을 수 link:https://docs.netapp.com/us-en/ontap-metrocluster/index.html["MetroCluster 설명서"^]있습니다.
