---
sidebar: sidebar 
permalink: task_san_configure_protection_for_business_continuity.html 
keywords: SM-BC, snapmirror business continuity, consistency group, remote protection, 9.8, 9.9.1, destination 
summary: 비즈니스 연속성을 위해 보호를 구성하려면 ONTAP 소스 클러스터에서 LUN을 선택하고 일관성 그룹에 추가해야 합니다. 
---
= SnapMirror Business Continuity를 통해 보호
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
SnapMirror 비즈니스 연속성을 사용하여 보호를 구성하려면 ONTAP 소스 클러스터에서 LUN을 선택하고 일관성 그룹에 추가해야 합니다.

.시작하기 전에
* SnapMirror Synchronous 라이센스가 있어야 합니다.
* 클러스터 또는 스토리지 VM 관리자여야 합니다.
* 일관성 그룹의 모든 구성 볼륨은 단일 스토리지 VM(SVM)에 있어야 합니다.
+
** LUN은 서로 다른 볼륨에 상주할 수 있습니다.


* 소스 클러스터와 대상 클러스터는 같을 수 없습니다.
* ASA 클러스터와 비 ASA 클러스터 간에 SM-BC 정합성 보장 그룹 관계를 설정할 수 없습니다.
* 클러스터 피어 관계를 위해 SM-BC에서 기본 IPspace가 필요합니다. 사용자 지정 IPspace는 지원되지 않습니다.
* 일관성 그룹의 이름은 고유해야 합니다.
* 보조(대상) 클러스터의 볼륨은 DP 유형이어야 합니다.
* 운영 SVM과 2차 SVM은 피어링된 관계에 있어야 합니다.


.단계
ONTAP CLI 또는 System Manager를 사용하여 일관성 그룹을 구성할 수 있습니다.

ONTAP 9.10.1부터 ONTAP은 추가 관리 유틸리티를 제공하는 일관성 그룹 엔드포인트 및 메뉴를 시스템 관리자에 제공합니다. ONTAP 9.10.1 이상을 사용하는 경우 를 참조하십시오 link:../consistency-groups/configure-task.html["일관성 그룹을 구성합니다"] 그런 다음 link:../consistency-groups/protect-task.html["보호 구성"] SM-BC 관계를 생성합니다.

[role="tabbed-block"]
====
.시스템 관리자
--
. 운영 클러스터에서 * 보호 > 개요 > 무중단 업무 운영 보호 > LUN 보호 * 로 이동합니다.
. 보호할 LUN을 선택하고 보호 그룹에 추가합니다.
. 대상 클러스터와 SVM을 선택합니다.
. 기본적으로 * 관계 초기화 * 가 선택됩니다. 보호를 시작하려면 * 저장 * 을 클릭합니다.
. 대시보드 > 성능 * 으로 이동하여 LUN의 IOPS 활동을 확인합니다.
. 대상 클러스터에서 System Manager를 사용하여 비즈니스 연속성 관계에 대한 보호가 동기화 상태인지 확인합니다. * 보호 > 관계 *.


--
.CLI를 참조하십시오
--
. 타겟 클러스터에서 일관성 그룹 관계를 생성합니다.
대상::> SnapMirror create-source-path_source-path_-destination-path_destination-path_-cg-item-mapping_volume-path_-policy_policy-name _
+
를 사용하여 구성 볼륨을 최대 12개까지 매핑할 수 있습니다 `cg-item-mappings` 의 매개 변수입니다 `snapmirror create` 명령.

+
다음 예에서는 두 개의 일관성 그룹을 생성합니다. `cg_src_ on the source with `vol1` 및 `vol2` 미러링된 타겟 정합성 보장 그룹, `cg_dst`.

+
대상 경로 VS1_DST:/CG/CG_DST-item-mapping-vol_src1:@vol_dst1, vol_src2:@vol_srst2:@vol_dst2 - policy AutomatedFailOver

. 대상 클러스터에서 일관성 그룹을 초기화합니다.
+
`destination::>snapmirror initialize -destination-path _destination-consistency-group_`

. 초기화 작업이 성공적으로 완료되었는지 확인하십시오. 상태는 InSync가 되어야 합니다.
+
스냅미러 쇼

. 각 클러스터에서 igroup을 생성하여 애플리케이션 호스트의 이니시에이터에 LUN을 매핑할 수 있습니다.
`lun igroup create -igroup _name_ -protocol _fcp|iscsi_ -ostype _os_ -initiator _initiator_name_`
. 각 클러스터에서 LUN을 igroup에 매핑합니다.
+
`lun map -path _path_name_ -igroup _igroup_name_`

. 에서 LUN 매핑이 성공적으로 완료되었는지 확인합니다 `lun map` 명령. 그런 다음 애플리케이션 호스트에서 새 LUN을 검색할 수 있습니다.


--
====