---
sidebar: sidebar 
permalink: task_cloud_tier_data.html 
keywords: netapp, ontap, FabricPool, tier, tiers, cloud data, tiering, aggregate, local tier, primary, cloud tier, storing data in tiers, storage efficiency, FabricPool, Fabric Pool, FabricPool license, volume tiering policy 
summary: 데이터를 계층에 저장하면 스토리지 시스템의 효율성이 향상됩니다. 
---
= 데이터를 클라우드에 계층화
:toc: macro
:hardbreaks:
:toclevels: 1
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
데이터를 계층에 저장하면 스토리지 시스템의 효율성이 향상됩니다. 액세스 빈도에 따라 FabricPool를 사용하여 데이터를 계층에 저장하여 스토리지 계층을 관리할 수 있습니다.

이 절차에서는 FabricPool의 클라우드 계층으로 오브젝트 저장소를 설정합니다. 로컬 계층(aggr)에 연결한 후에는 클라우드 계층을 연결 해제할 수 없습니다.

2021년 8월 21일부터 Cloud Tiering 서비스를 사용하여 Cloud Manager에서 지원하는 계층화 구성에 새로운 Cloud Tiering BYOL 라이센스가 도입되었습니다. link:cloud-install-fabricpool-task.html["FabricPool 라이센스 설치에 대해 자세히 알아보십시오"].

ONTAP S3에 계층화하는 경우 추가 요구사항이 있습니다.

* 네트워크 인터페이스의 S3 서버 FQDN 이름 및 IP 주소를 포함하여 관리 스토리지 VM에 대해 구성된 DNS 서버에 원격 ONTAP S3 서버의 호스트 이름에 대한 항목이 있어야 합니다.
* link:task_dp_prepare_mirror.html["인터클러스터 네트워크 인터페이스"] 클러스터 피어링이 필요하지 않더라도 로컬 및 원격 클러스터 모두에서 구성해야 합니다.


System Manager에서 볼륨 계층화 정책을 생성할 수도 있습니다.

.단계
. 스토리지 > 계층 > 클라우드 계층 추가 * 를 클릭하고 사용할 오브젝트 저장소 공급자를 선택합니다.
. 클라우드 미러를 생성하려면 * FabricPool 미러로 추가 * 를 클릭합니다.


FabricPool 미러는 데이터 저장소를 원활하게 대체할 수 있는 방법을 제공하므로 재해 발생 시 데이터를 사용할 수 있습니다.



== 데이터를 계층화하여 비용 절감 비디오

video::92-cSP7M_5I[youtube, width=848,height=480]