---
sidebar: sidebar 
permalink: task_nas_provision_flexgroup.html 
keywords: netapp, ontap, provision, provisioning, nas, large file systems, using, FlexGroup, windows, servers, cifs, smb, FlexVol volume limits, load distribution, work load, workload, balancing, data 
summary: FlexGroup 볼륨은 자동 로드 분산과 함께 고성능을 제공하는 확장 가능한 NAS 컨테이너입니다. FlexGroup 볼륨은 관리 오버헤드를 추가하지 않고 FlexVol 볼륨 제한을 크게 초과하는 페타바이트급 용량을 제공합니다. 
---
= FlexGroup 볼륨을 사용하여 대용량 파일 시스템용 NAS 스토리지를 프로비저닝합니다
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
FlexGroup 볼륨은 자동 로드 분산과 함께 고성능을 제공하는 확장 가능한 NAS 컨테이너입니다. FlexGroup 볼륨은 관리 오버헤드를 추가하지 않고 FlexVol 볼륨 제한을 크게 초과하는 페타바이트급 용량을 제공합니다.

이 섹션의 항목에서는 ONTAP 9.7 이상 릴리즈의 System Manager에서 FlexGroup 볼륨을 관리하는 방법을 보여 줍니다. 클래식 시스템 관리자(ONTAP 9.7 이전에서만 사용 가능)를 사용하는 경우 다음 항목을 참조하십시오.

* https://docs.netapp.com/us-en/ontap-system-manager-classic/online-help-96-97/task_creating_flexgroup_volumes.html["FlexGroup 볼륨을 생성합니다"^]


ONTAP 9.9.1부터 2개 이상의 FlexGroup 볼륨에 대한 SnapMirror 팬아웃 관계가 지원되며 최대 8개의 팬아웃 레그를 지원합니다. System Manager는 계단식 SnapMirror FlexGroup 볼륨 관계를 지원하지 않습니다.

ONTAP는 FlexGroup 볼륨을 생성하는 데 필요한 로컬 계층을 자동으로 선택합니다.

ONTAP 9.8부터는 스토리지 용량 할당 시 QoS가 기본적으로 사용하도록 설정됩니다. 프로비저닝 프로세스 도중 또는 나중에 QoS를 사용하지 않도록 설정하거나 사용자 지정 QoS 정책을 선택할 수 있습니다.

.단계
. 스토리지 > 볼륨 * 을 클릭합니다.
. 추가 * 를 클릭합니다.
. 추가 옵션 * 을 클릭한 다음 * 클러스터 전체에 볼륨 데이터 배포 * 를 선택합니다.
+

NOTE: ONTAP 9.8 이상을 실행 중인 경우 QoS를 비활성화하거나 사용자 지정 QoS 정책을 선택하려면 * 추가 옵션 * 을 클릭한 다음 * 스토리지 및 최적화 * 에서 * 성능 서비스 수준 * 을 선택합니다.





== 비디오



=== FlexGroup 볼륨을 생성하고 관리합니다

video::gB-yF1UTv2I[youtube,width=848,height=480]


=== FlexGroup 볼륨 - 더 적은 리소스로 더 많은 작업 수행

video::0B4nlChf0b4[youtube,width=848,height=480]