---
sidebar: sidebar 
permalink: task_metrocluster_troubleshooting.html 
keywords: system manager, troubleshoot, error, event, problem, metrocluster, maintenance, fix, correction, health, check 
summary: 한 MetroCluster 사이트에서 다른 사이트로 전환하여 유지 관리를 수행하거나 문제를 복구할 수 있습니다. 
---
= IP MetroCluster 구성 관련 문제를 해결합니다
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
ONTAP 9.8부터 System Manager는 IP MetroCluster 구성의 상태를 모니터링하여 발생할 수 있는 문제를 식별하고 해결할 수 있도록 지원합니다.



== MetroCluster 상태 점검 개요

System Manager는 IP MetroCluster 구성의 상태를 정기적으로 확인합니다. 대시보드에서 MetroCluster 섹션을 볼 때 일반적으로 "MetroCluster system are healthy"라는 메시지가 표시됩니다.

그러나 문제가 발생하면 메시지에 이벤트 수가 표시됩니다. 해당 메시지를 클릭하고 다음 구성 요소에 대한 상태 점검 결과를 볼 수 있습니다.

* 노드
* 네트워크 인터페이스
* 계층(스토리지)
* 클러스터
* 연결
* 볼륨
* 구성 복제


Status* 열은 문제가 있는 구성 요소를 식별하며 * Details* 열은 문제를 해결하는 방법을 제안합니다.



== MetroCluster 문제 해결

.단계
. System Manager에서 * 대시보드 * 를 선택합니다.
. MetroCluster * 섹션에서 메시지를 확인합니다.
+
.. 메시지가 MetroCluster 구성이 정상이고 클러스터와 ONTAP 중재자 사이의 연결이 양호하다는 것을 나타내면(확인 표시와 함께 표시됨) 수정할 문제가 없는 것입니다.
.. 메시지에 이벤트 수가 나열되거나 연결이 중단된 경우("X"로 표시됨) 다음 단계를 계속합니다.


. 이벤트 수를 표시하는 메시지를 클릭합니다.
+
MetroCluster 상태 보고서가 표시됩니다.

. 세부 정보 * 열의 제안을 사용하여 보고서에 나타나는 문제를 해결합니다.
. 모든 문제가 해결되면 * MetroCluster 상태 확인 * 을 클릭합니다.
+

NOTE: MetroCluster 상태 점검은 많은 양의 리소스를 사용하므로 검사를 실행하기 전에 모든 문제 해결 작업을 수행하는 것이 좋습니다.

+
MetroCluster 상태 점검은 백그라운드에서 실행됩니다. 작업이 완료될 때까지 기다리는 동안 다른 작업을 수행할 수 있습니다.


