---
sidebar: sidebar 
permalink: task_san_provision_linux.html 
keywords: netapp, ontap, san, provisioning, linux, servers, provision, storage, create lun, fc, iscsi, zone switches, scsi disk, iscsi 
summary: LUN을 생성하여 FC 또는 iSCSI SAN 프로토콜을 사용하여 Linux 서버의 스토리지를 제공합니다. LUN은 Linux에 SCSI 디스크 디바이스로 나타납니다. 
---
= Linux 서버용 SAN 스토리지 용량 할당
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
이 절차를 수행하면 FC 또는 iSCSI 프로토콜이 이미 구성된 기존 스토리지 VM에 새 LUN이 생성됩니다.

새 스토리지 VM을 생성하고 FC 또는 iSCSI 프로토콜을 구성해야 하는 경우 를 참조하십시오 link:san-admin/configure-svm-fc-task.html["FC용 SVM 구성"] 또는 link:san-admin/configure-svm-iscsi-task.html["iSCSI용 SVM을 구성합니다"].

LUN은 Linux에 SCSI 디스크 디바이스로 나타납니다.


NOTE: ALUA(Asymmetric Logical Unit Access)는 LUN 생성 중에 항상 사용하도록 설정됩니다. ALUA 설정은 변경할 수 없습니다.

FC 라이센스가 있어야 하며 활성화해야 합니다. FC 라이센스가 활성화되어 있지 않으면 LIF 및 SVM이 온라인 상태로 나타나지만 운영 상태는 다운입니다. LIF 및 SVM이 작동할 수 있도록 FC 서비스를 설정해야 합니다. SVM의 모든 FC LIF에서 이니시에이터를 호스팅하려면 단일 이니시에이터 조닝을 사용해야 합니다.

Linux 서버의 이니시에이터 식별자(FC WWPN 또는 iSCSI iqn)를 알아야 합니다.

ONTAP 9.8부터는 스토리지 용량 할당 시 QoS가 기본적으로 사용하도록 설정됩니다. 프로비저닝 프로세스 중에 또는 나중에 QoS를 비활성화하거나 사용자 지정 QoS 정책을 선택할 수 있습니다.

.단계
[role="tabbed-block"]
====
.시스템 관리자
--
ONTAP System Manager(9.7 이상)와 함께 FC 또는 iSCSI SAN 프로토콜을 사용하여 Linux 서버용 스토리지를 제공할 LUN을 생성합니다.

System Manager Classic(9.7 이하에서 사용 가능)을 사용하여 이 작업을 완료하려면 을 참조하십시오 https://docs.netapp.com/us-en/ontap-sm-classic/iscsi-config-rhel/index.html["Red Hat Enterprise Linux용 iSCSI 구성"^]

. Linux 서버에 를 설치합니다 link:https://docs.netapp.com/us-en/ontap-sanhost/hu_luhu_71.html#installing-linux-unified-host-utilities["NetApp Linux 호스트 유틸리티"] 패키지.
. System Manager에서 * 스토리지 > LUN * 을 클릭한 다음 * 추가 * 를 클릭합니다.
. LUN을 생성하는 데 필요한 정보를 입력합니다.
. ONTAP 버전에 따라 * 추가 옵션 * 을 클릭하여 다음 중 하나를 수행할 수 있습니다.
+
[cols="80,20"]
|===


| 옵션을 선택합니다 | 부터 사용할 수 있습니다 


 a| 
** 상위 볼륨 대신 LUN에 QoS 정책을 할당합니다
+
*** * 추가 옵션 > 스토리지 및 최적화 * 를 선택합니다
*** 성능 서비스 수준 * 을 선택합니다.
*** 전체 볼륨 대신 개별 LUN에 QoS 정책을 적용하려면 * Apply these performance limits enforcement to each LUN * 을 선택합니다.
+
기본적으로 성능 제한은 볼륨 레벨에 적용됩니다.




| ONTAP 9.10.1 


 a| 
** 기존 이니시에이터 그룹을 사용하여 새 이니시에이터 그룹을 생성합니다
+
*** 추가 옵션 > 호스트 정보 *
*** 기존 이니시에이터 그룹을 사용하여 새 이니시에이터 그룹 * 을 선택합니다.
+
* 참고 *: 다른 igroup을 포함하고 있는 igroup의 OS 유형은 생성 후 변경할 수 없습니다.




| ONTAP 9.9.1 


 a| 
** igroup 또는 호스트 이니시에이터에 설명을 추가합니다
+
이 설명은 igroup 또는 호스트 이니시에이터의 별칭으로 사용됩니다.

+
*** 추가 옵션 > 호스트 정보 *



| ONTAP 9.9.1 


 a| 
** 기존 볼륨에 LUN을 생성합니다
+
기본적으로 새 LUN은 새 볼륨에 생성됩니다.

+
*** 추가 옵션 > LUN 추가 * 를 선택합니다
*** Group related LUNs * 를 선택합니다.



| ONTAP 9.9.1 


 a| 
** QoS를 비활성화하거나 사용자 지정 QoS 정책을 선택합니다
+
*** * 추가 옵션 > 스토리지 및 최적화 * 를 선택합니다
*** 성능 서비스 수준 * 을 선택합니다.
+
* 참고 *: ONTAP 9.9.1 이상에서는 사용자 지정 QoS 정책을 선택한 경우 지정된 로컬 계층에 수동으로 배치할 수도 있습니다.




| ONTAP 9.8 
|===


. FC의 경우 WWPN으로 FC 스위치를 조닝(Zoning)하십시오. 이니시에이터당 하나의 존을 사용하고 각 존에 모든 타겟 포트를 포함합니다.
. Linux 서버에서 새 LUN을 검색합니다.
+
"/usr/bin/rescan-scsi-bus.sh"를 참조하십시오

+

NOTE: 필요에 따라 LUN을 파티셔닝하고 파일 시스템을 생성합니다.

. Linux 서버가 LUN에 데이터를 쓰고 읽을 수 있는지 확인합니다.


--
.CLI를 참조하십시오
--
ONTAP CLI에서 FC 또는 iSCSI SAN 프로토콜을 사용하여 Linux 서버의 스토리지를 제공할 LUN을 생성합니다.

. 'system license show' 명령을 사용하여 FC 또는 iSCSI 라이센스가 있는지 확인합니다.
+
'시스템 사용권 프로그램'

+
[listing]
----

Package           Type    Description           Expiration
 ----------------- ------- --------------------- --------------------
 Base              site    Cluster Base License  -
 NFS               site    NFS License           -
 CIFS              site    CIFS License          -
 iSCSI             site    iSCSI License         -
 FCP               site    FCP License           -
----
. FC 또는 iSCSI 라이센스가 없는 경우 'license add' 명령을 사용합니다.
+
'license add-license-code_your_license_code_'

. SVM에서 프로토콜 서비스 지원:
+
iSCSI의 경우: * 'vserver iSCSI create-vserver_vserver_name_-target-alias_vserver_name_'

+
FC: * 의 경우 * 'vserver FCP create-vserver_vserver_name_-status-admin up'

. 각 노드에서 SVM에 대해 2개의 LIF를 생성합니다.
+
'network interface create-vserver_vserver_name_-lif_lif_name_-role data-protocol iscsi|fc-home-node_node_name_-home-port_port_name_-address_netmask-mask'

+
NetApp은 각 SVM에서 데이터를 제공할 수 있도록 노드당 최소 하나의 iSCSI 또는 FC LIF를 지원합니다. 그러나 이중화를 위해서는 노드당 두 개의 LIF가 필요합니다.

. LIF가 생성되었으며 운영 상태가 '온라인'인지 확인합니다.
+
'network interface show -vserver_vserver_name__lif_name_'

. LUN 생성:
+
'lun create - vserver vserver_name - volume_volume_name_-lun_lun_name_-size_lun_size_-OSType linux-space-reserve enabled|disabled'

+
LUN 이름은 255자를 초과할 수 없으며 공백을 포함할 수 없습니다.

+

NOTE: NVFAIL 옵션은 볼륨에 LUN이 생성될 때 자동으로 활성화됩니다.

. Igroup 생성:
+
'igroup create-vserver_vserver_name_-igroup_name_-protocol fcp|iscsi|mixed-OSType linux-initiator_initiator_name_'

. LUN을 igroup에 매핑:
+
'LUN 매핑 create-vserver_vserver_name_-volume_volume_name_-lun_lun_name_-igroup_igroup_name_'

. LUN이 올바르게 구성되었는지 확인합니다.
+
'lun show -vserver_vserver_name _'

. link:san-admin/create-port-sets-binding-igroups-task.html["포트 세트를 생성하고 igroup에 바인딩합니다"] (선택 사항).
. 호스트 설명서의 단계를 따라 특정 호스트에서 블록 액세스를 설정합니다.
. Host Utilities를 사용하여 FC 또는 iSCSI 매핑을 완료하고 호스트에서 LUN을 검색할 수 있습니다.


--
====
.관련 정보
link:./san-admin/index.html["SAN 관리 개요"]
https://docs.netapp.com/us-en/ontap-sanhost/index.html["ONTAP SAN 호스트 구성"]
https://docs.netapp.com/us-en/ontap/san-admin/manage-san-initiators-task.html["System Manager에서 SAN 이니시에이터 그룹을 보고 관리합니다"]
http://www.netapp.com/us/media/tr-4017.pdf["NetApp 기술 보고서 4017: 파이버 채널 SAN 모범 사례"]
