---
sidebar: sidebar 
permalink: task_nas_file_system_analytics_enable.html 
keywords: capacity analytics, data visualization, File System Analytics, System Manager, storage, explorer 
summary: 용량 분석과 같은 사용 데이터를 수집하고 표시하려면 파일 시스템 분석을 설정해야 합니다. 
---
= 파일 시스템 분석 설정
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
용량 분석과 같은 사용 데이터를 수집하고 표시하려면 볼륨에 대해 File System Analytics를 활성화해야 합니다.

ONTAP 9.8부터 새 볼륨이나 기존 볼륨에서 파일 시스템 분석을 활성화할 수 있습니다. 시스템을 ONTAP 9.8 이상으로 업그레이드하는 경우 파일 시스템 분석을 활성화하기 전에 모든 업그레이드 프로세스가 완료되었는지 확인하십시오.

.이 작업에 대해
볼륨의 크기와 내용에 따라 분석을 사용하는 데 시간이 걸릴 수 있으며 ONTAP에서는 볼륨의 기존 데이터를 처리합니다. System Manager에서 진행 상황을 표시하고 완료되면 분석 데이터를 표시합니다. 초기화 진행률에 대한 보다 정확한 정보가 필요한 경우 ONTAP CLI 명령 'volume analytics show'를 사용할 수 있습니다.

초기화 스캔과 관련된 추가 고려 사항은 를 참조하십시오 xref:./file-system-analytics/considerations-concept.html#scan-considerations[스캔 고려 사항].

.단계
ONTAP System Manager 또는 CLI를 사용하여 파일 시스템 분석을 활성화할 수 있습니다.

[role="tabbed-block"]
====
.시스템 관리자
--
|===
| ONTAP 9.8 및 9.9.1 | ONTAP 9.10.1에서 시작합니다 


| 스토리지 > 볼륨 * 을 선택합니다. 원하는 볼륨을 선택한 다음 * 탐색기 * 를 선택합니다. 분석 활성화 * 또는 * 분석 비활성화 * 를 선택합니다. | 스토리지 > 볼륨 * 을 선택합니다. 원하는 볼륨을 선택합니다. 개별 볼륨 메뉴에서 * 파일 시스템 > 탐색기 * 를 선택합니다. 분석 활성화 * 또는 * 분석 비활성화 * 를 선택합니다. 
|===
--
.CLI를 참조하십시오
--
.CLI를 사용하여 파일 시스템 분석을 설정하려면 다음을 따르십시오.
. 다음 명령을 실행합니다. 'volume analytics on-vserver_svm_name_-volume_volume_name_[-foreground{true|false}]' 명령은 기본적으로 포그라운드에서 실행되며, ONTAP는 진행률을 표시하고 완료되면 분석 데이터를 표시합니다. 보다 정확한 정보가 필요한 경우 '-foreground false' 옵션을 사용하여 백그라운드에서 명령을 실행한 다음 'volume analytics show' 명령을 사용하여 CLI에서 초기화 진행률을 표시할 수 있습니다.
. 파일 시스템 분석을 성공적으로 사용하도록 설정한 후 ONTAP System Manager를 사용하여 분석 데이터를 표시합니다.


--
====