---
sidebar: sidebar 
permalink: task_admin_monitor_risks.html 
keywords: system manager, monitor, risk, risks, suggestion, suggestions, mitigate, active iq, category, categories, mitigation, impact, impacts, corrections, corrective action, corrective actions, acknowledge risk, dismiss, undismiss, restore, unacknowledge 
summary: ONTAP 9.10.0 이상의 시스템 관리자를 사용하여 Active IQ 디지털 어드바이저가 보고한 위험을 모니터링할 수 있습니다. 
---
= 위험 모니터링
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
ONTAP 9.10.0부터 시스템 관리자를 사용하여 Active IQ 디지털 어드바이저가 보고한 위험을 모니터링할 수 있습니다. ONTAP 9.10.1부터 System Manager를 사용하여 위험을 확인할 수도 있습니다.

NetApp Active IQ Digital Advisor는 위험을 줄이고 스토리지 환경의 성능과 효율성을 향상할 수 있는 기회를 보고합니다. System Manager를 사용하면 Active IQ에서 보고하는 위험에 대해 알아보고 실행 가능한 인텔리전스를 확보하여 스토리지를 관리하고 가용성을 높이고 보안을 강화하고 스토리지 성능을 향상할 수 있습니다.



== Active IQ 계정에 대한 링크입니다

Active IQ의 위험에 대한 정보를 수신하려면 먼저 시스템 관리자에서 Active IQ 계정에 연결해야 합니다.

.단계
. System Manager에서 * 클러스터 > 설정 * 을 클릭합니다.
. Active IQ 등록 * 에서 * 등록 * 을 클릭합니다.
. Active IQ에 대한 자격 증명을 입력합니다.
. 자격 증명이 인증되면 * 확인을 클릭하여 Active IQ를 System Manager*와 연결합니다.




== 위험 수를 확인합니다

ONTAP 9.10.0부터 System Manager의 대시보드에서 Active IQ가 보고한 위험 수를 확인할 수 있습니다.

System Manager와 Active IQ 계정 간의 연결을 설정해야 합니다. 을 참조하십시오 <<link_active_iq,Active IQ 계정에 대한 링크입니다>>.

.단계
. System Manager에서 * 대시보드 * 를 클릭합니다.
. 상태 * 섹션에서 보고된 위험 수를 확인합니다.
+

NOTE: 위험 수를 보여 주는 메시지를 클릭하여 각 위험에 대한 자세한 정보를 볼 수 있습니다. 을 참조하십시오 <<view_risk_details,위험에 대한 세부 정보를 봅니다>>.





== 위험에 대한 세부 정보를 봅니다

ONTAP 9.10.0부터 Active IQ에서 보고한 위험이 영향 영역별로 분류되는 방식을 시스템 관리자에서 확인할 수 있습니다. 또한 보고된 각 위험, 시스템에 미치는 잠재적 영향 및 취할 수 있는 수정 조치에 대한 자세한 정보를 볼 수 있습니다.

System Manager와 Active IQ 계정 간의 연결을 설정해야 합니다. 을 참조하십시오 <<link_active_iq,Active IQ 계정에 대한 링크입니다>>.

.단계
. 이벤트 > 모든 이벤트 * 를 클릭합니다.
. 개요 * 섹션의 * Active IQ 제안 * 아래에서 각 영향 영역 범주의 위험 수를 봅니다. 위험 범주는 다음과 같습니다.
+
** 성능 및 효율성
** 가용성 및 보호
** 용량
** 구성
** 보안


. Active IQ 제안 * 탭을 클릭하여 다음을 포함한 각 위험에 대한 정보를 확인하십시오.
+
** 시스템에 미치는 영향 수준
** 위험의 범주입니다
** 영향을 받는 노드입니다
** 필요한 완화 조치 유형
** 수행할 수 있는 수정 조치






== 위험을 인정합니다

ONTAP 9.10.1부터 System Manager를 사용하여 열려 있는 위험을 확인할 수 있습니다.

.단계
. System Manager에서 의 절차를 수행하여 위험 목록을 표시합니다 <<view_risk_details,위험에 대한 세부 정보를 봅니다>>.
. 승인하려는 공개 위험의 위험 이름을 클릭합니다.
. 다음 필드에 정보를 입력합니다.
+
** 미리 알림(날짜)
** 양쪽 맞춤
** 설명


. 확인 * 을 클릭합니다.
+

NOTE: 위험을 인지한 후 Active IQ 제안 목록에 변경이 반영되려면 몇 분 정도 걸립니다.





== 위험 확인 취소

ONTAP 9.10.1부터 System Manager를 사용하여 이전에 승인되었던 모든 위험을 확인할 수 있습니다.

.단계
. System Manager에서 의 절차를 수행하여 위험 목록을 표시합니다 <<view_risk_details,위험에 대한 세부 정보를 봅니다>>.
. 확인 취소할 확인된 위험의 위험 이름을 클릭합니다.
. 다음 필드에 정보를 입력합니다.
+
** 양쪽 맞춤
** 설명


. 승인 취소 * 를 클릭합니다.
+

NOTE: 위험을 인지하지 못한 후 Active IQ 제안 목록에 변경이 반영되려면 몇 분 정도 걸립니다.


