---
sidebar: sidebar 
permalink: task_nvme_provision_suse_linux.html 
keywords: netapp, ontap, nvme, SUSE, linux, servers, Provision NVMe storage, namespace, SCSI disk service 
summary: NVMe 프로토콜을 사용하여 SUSE Linux 서버의 스토리지를 제공하기 위한 네임스페이스를 생성합니다. 네임스페이스는 Linux에 SCSI 디스크 디바이스로 나타납니다. 
---
= SUSE Linux용 NVMe 스토리지 프로비저닝
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
NVMe 프로토콜을 사용하여 SUSE Linux 서버의 스토리지를 제공하기 위한 네임스페이스를 생성합니다. 네임스페이스는 Linux에 SCSI 디스크 디바이스로 나타납니다.

이 절차에서는 기존 스토리지 VM에 새 네임스페이스를 만듭니다. 스토리지 VM은 NVMe에 맞게 구성해야 하며 FC 또는 TCP 전송은 이미 설정되어 있어야 합니다.

ONTAP 9.8부터는 스토리지 용량 할당 시 QoS가 기본적으로 사용하도록 설정됩니다. 프로비저닝 프로세스 중에 또는 나중에 QoS를 비활성화하거나 사용자 지정 QoS 정책을 선택할 수 있습니다.

[role="tabbed-block"]
.단계
====
.시스템 관리자
--
ONTAP System Manager(9.7 이상)와 함께 NVMe 프로토콜을 사용하여 스토리지를 제공하기 위한 네임스페이스를 생성합니다.

. System Manager에서 * 스토리지 > NVMe 네임스페이스 * 를 클릭한 다음 * 추가 * 를 클릭합니다.
+
.. 새 하위 시스템을 만들어야 하는 경우 * 추가 옵션 * 을 클릭합니다.
.. ONTAP 9.8 이상을 실행하고 있고 QoS를 비활성화하거나 사용자 지정 QoS 정책을 선택하려면 * 추가 옵션 * 을 클릭한 다음 * 스토리지 및 최적화 * 에서 * 성능 서비스 수준 * 을 선택합니다.




. WWPN을 기준으로 FC 스위치를 조닝(Zoning)하십시오. 이니시에이터당 하나의 존을 사용하고 각 존에 모든 타겟 포트를 포함합니다.
. Linux 서버에서 새 네임스페이스를 검색합니다.
. 네임스페이스를 초기화하고 파일 시스템으로 포맷합니다.
. Linux 서버가 네임스페이스에서 데이터를 쓰고 읽을 수 있는지 확인합니다.


--
.CLI를 참조하십시오
--
ONTAP CLI에서 NVMe 프로토콜을 사용하여 스토리지를 제공하기 위한 네임스페이스를 생성합니다.

이 절차에서는 NVMe 프로토콜용으로 이미 구성된 기존 스토리지 VM에 NVMe 네임스페이스 및 서브시스템을 생성한 다음, 네임스페이스를 서브시스템에 매핑하여 호스트 시스템에서 데이터에 액세스할 수 있도록 합니다.

NVMe용 스토리지 VM을 구성해야 하는 경우 를 참조하십시오 link:san-admin/configure-svm-nvme-task.html["NVMe를 위한 SVM 구성"].

.단계
. SVM이 NVMe용으로 구성되었는지 확인합니다.
+
'vserver show -vserver_SVM_name_-fields Allowed-protocols'

+
"NVMe"는 "허용된 프로토콜" 열 아래에 표시되어야 합니다.

. NVMe 네임스페이스를 생성합니다.
+
'vserver NVMe namespace create-vserver_SVM_name_-path_path_-size_of_namespace_-OSType_OS_type_'

. NVMe 하위 시스템을 생성합니다.
+
'vserver NVMe 하위 시스템 create-vserver_SVM_name_-subsystem_name_of_subsystem_-OSType_OS_type_'

+
NVMe 하위 시스템 이름은 대/소문자를 구분합니다. 1 ~ 96자를 포함해야 합니다. 특수 문자를 사용할 수 있습니다.

. 하위 시스템이 생성되었는지 확인합니다.
+
'vserver NVMe subsystem show -vserver_SVM_name _'

+
NVMe 서브시스템은 Subsystem 열에 표시되어야 한다.

. 호스트에서 NQN을 가져옵니다.
. 호스트 NQN을 하위 시스템에 추가합니다.
+
"vserver NVMe 하위 시스템 호스트 add -vserver_SVM_name_-subsystem_subsystem_name_-host-nqn_Host_NQN_:subsystem._subsystem_name_"

. 네임스페이스를 하위 시스템에 매핑합니다.
+
'vserver NVMe 하위 시스템 맵 add -vserver_SVM_name_-subsystem_subsystem_name_-path_path_'

+
네임스페이스는 단일 하위 시스템에만 매핑할 수 있습니다.

. 네임스페이스가 하위 시스템에 매핑되어 있는지 확인합니다.
+
'vserver NVMe namespace show -vserver_SVM_name_-instance'

+
하위 시스템은 연결된 하위 시스템으로 나열되어야 합니다.



--
====