---
sidebar: sidebar 
permalink: task_nas_flexcache.html 
keywords: flexcache, flexcache volume, offload traffic, work load, workload, access speed 
summary: FlexCache 볼륨을 사용하면 데이터 액세스 속도를 높이거나 자주 액세스하는 볼륨에서 트래픽을 오프로드할 수 있습니다. FlexCache 볼륨은 특히 클라이언트가 동일한 데이터에 반복적으로 액세스해야 하는 읽기 집약적인 워크로드에 적합합니다. 
---
= FlexCache를 사용하여 여러 클라이언트의 성능 향상
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
FlexCache 볼륨을 사용하면 데이터 액세스 속도를 높이거나 자주 액세스하는 볼륨에서 트래픽을 오프로드할 수 있습니다. FlexCache 볼륨은 특히 클라이언트가 동일한 데이터에 반복적으로 액세스해야 하는 읽기 집약적인 워크로드에 적합합니다.

이 섹션의 항목에서는 ONTAP 9.7 이상 릴리즈의 System Manager에서 FlexCache 볼륨을 관리하는 방법을 보여 줍니다. 기존 System Manager(ONTAP 9.7 이하에서만 사용 가능)를 사용하는 경우 다음 항목을 참조하십시오.

* https://docs.netapp.com/us-en/ontap-sm-classic/online-help-96-97/task_creating_flexcache_volumes.html["FlexCache 볼륨을 생성합니다"^]


FlexCache 볼륨은 원격 볼륨과 동일한 클러스터 또는 다른 클러스터에 있을 수 있습니다. 원격 볼륨이 다른 클러스터에 있는 경우 클러스터와 스토리지 VM을 이미 살펴봐야 합니다.


NOTE: HA 쌍이 를 사용 중인 경우 link:https://docs.netapp.com/us-en/ontap/encryption-at-rest/support-storage-encryption-concept.html["SAS 또는 NVMe 드라이브(SED, NSE, FIPS) 암호화"], 항목의 지침을 따라야 합니다 link:https://docs.netapp.com/us-en/ontap/encryption-at-rest/return-seds-unprotected-mode-task.html["FIPS 드라이브 또는 SED를 보호되지 않는 모드로 되돌리는 중입니다"] 시스템을 초기화하기 전에 HA 쌍 내의 모든 드라이브(부팅 옵션 4 또는 9) 이렇게 하지 않을 경우 드라이브를 용도 변경할 경우 향후의 데이터 손실이 발생할 수 있습니다.

.단계
. 스토리지 > 볼륨 * 을 클릭합니다.
. 추가 * 를 클릭합니다.
. 추가 옵션 * 을 클릭한 다음 * 원격 볼륨의 캐시로 추가 * 를 선택합니다.
+
.. ONTAP 9.8 이상을 실행하고 있고 QoS를 비활성화하거나 사용자 지정 QoS 정책을 선택하려면 * 추가 옵션 * 을 클릭한 다음 * 스토리지 및 최적화 * 에서 * 성능 서비스 수준 * 을 선택합니다.




새로운 데이터 요청의 경우 FlexCache 볼륨은 원격 볼륨에서 데이터를 요청하고 저장합니다. 이후 데이터에 대한 모든 읽기 요청은 FlexCache 볼륨에서 직접 제공됩니다.



== 비디오



=== FlexCache를 통해 글로벌 데이터의 WAN 지연 시간 및 읽기 시간을 줄이는 방법

video::rbbH0l74RWc[youtube, width=848,height=480]


=== ONTAP FlexCache의 성능 이점에 대해 알아보십시오!

video::bWi1-8Ydkpg[youtube, width=848,height=480]