---
permalink: element-replication/create-replication-relationship-task.html 
sidebar: sidebar 
keywords: create, relationship, element, source, ontap, destination 
summary: SnapMirror를 사용하여 Element 볼륨의 스냅샷 복사본을 ONTAP 대상 시스템으로 복제할 수 있습니다. Element 사이트에서 재해가 발생할 경우 ONTAP 시스템에서 클라이언트로 데이터를 제공하고 서비스가 복원되면 Element 소스 볼륨을 다시 활성화할 수 있습니다. 
---
= 요소 소스에서 ONTAP 대상으로 관계를 생성합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
운영 스토리지의 소스 볼륨과 2차 스토리지의 타겟 볼륨 간의 관계를 _ 데이터 보호 관계 _ 라고 합니다. 'napmirror create' 명령을 사용하여 요소 소스에서 ONTAP 대상으로 또는 ONTAP 소스에서 요소 대상으로 데이터 보호 관계를 생성할 수 있습니다.

SnapMirror를 사용하여 Element 볼륨의 스냅샷 복사본을 ONTAP 대상 시스템으로 복제할 수 있습니다. Element 사이트에서 재해가 발생할 경우 ONTAP 시스템에서 클라이언트로 데이터를 제공하고 서비스가 복원되면 Element 소스 볼륨을 다시 활성화할 수 있습니다.

.시작하기 전에
* 복제할 볼륨이 포함된 Element 노드를 ONTAP에서 액세스할 수 있어야 합니다.
* SnapMirror 복제에 대해 Element 볼륨이 활성화되어 있어야 합니다.
* "미러 볼트" 정책 유형을 사용하는 경우, Element 스냅샷 복사본을 복제하기 위해 SnapMirror 레이블을 구성해야 합니다.
+
[NOTE]
====
Element 소프트웨어 웹 UI에서만 이 작업을 수행할 수 있습니다. 자세한 내용은 를 참조하십시오 https://docs.netapp.com/us-en/element-software/index.html["요소 문서"].

====


.이 작업에 대해
요소 소스 경로는 "_hostip:_/lun/_name_" 형식으로 지정해야 합니다. 여기서 ""lun"은 실제 문자열 ""lun""이고 "name"은 요소 볼륨의 이름입니다.

Element 볼륨은 ONTAP LUN과 거의 동일합니다. SnapMirror는 Element 소프트웨어와 ONTAP 간의 데이터 보호 관계가 초기화될 때 Element 볼륨의 이름을 사용하여 LUN을 생성합니다. SnapMirror는 LUN이 Element 소프트웨어에서 ONTAP로 복제 시 요구 사항을 충족하는 경우 데이터를 기존 LUN에 복제합니다.

복제 규칙은 다음과 같습니다.

* ONTAP 볼륨은 하나의 요소 볼륨에서만 데이터를 포함할 수 있습니다.
* ONTAP 볼륨에서 여러 요소 볼륨으로 데이터를 복제할 수는 없습니다.


ONTAP 9.3 이전 버전에서는 타겟 볼륨에 최대 251개의 스냅샷 복사본이 포함될 수 있습니다. ONTAP 9.4 이상에서 타겟 볼륨에는 최대 1019개의 스냅샷 복사본이 포함될 수 있습니다.

.단계
. 대상 클러스터에서 요소 소스에서 ONTAP 대상으로 복제 관계를 생성합니다.
+
's냅미러 create-source-path_hostip:_/lun/name-destination-path_SVM:volume_|_cluster://SVM/volume_-type XDP-schedule schedule -policy_policy_'

+
전체 명령 구문은 man 페이지를 참조하십시오.

+
다음 예에서는 기본 'MirorLatest' 정책을 사용하여 SnapMirror DR 관계를 생성합니다.

+
[listing]
----
cluster_dst::> snapmirror create -source-path 10.0.0.11:/lun/0005 -destination-path svm_backup:volA_dst -type XDP -schedule my_daily -policy MirrorLatest
----
+
다음 예에서는 기본 MirorAndVault 정책을 사용하여 통합 복제 관계를 생성합니다.

+
[listing]
----
cluster_dst:> snapmirror create -source-path 10.0.0.11:/lun/0005 -destination-path svm_backup:volA_dst -type XDP -schedule my_daily -policy MirrorAndVault
----
+
다음 예에서는 'Unified7년' 정책을 사용하여 통합 복제 관계를 생성합니다.

+
[listing]
----
cluster_dst::> snapmirror create -source-path 10.0.0.11:/lun/0005 -destination-path svm_backup:volA_dst -type XDP -schedule my_daily -policy Unified7year
----
+
다음 예에서는 사용자 지정 my_unified" 정책을 사용하여 통합 복제 관계를 생성합니다.

+
[listing]
----
cluster_dst::> snapmirror create -source-path 10.0.0.11:/lun/0005 -destination-path svm_backup:volA_dst -type XDP -schedule my_daily -policy my_unified
----


.작업을 마친 후
'snapmirror show' 명령을 사용하여 SnapMirror 관계가 생성되었는지 확인합니다. 전체 명령 구문은 man 페이지를 참조하십시오.
