---
permalink: element-replication/create-custom-replication-policy-concept.html 
sidebar: sidebar 
keywords: create, custom, replication, policy, policies, relationship, compress data, snapmirror, snap mirror, snapshot 
summary: 관계의 기본 정책이 적합하지 않은 경우 사용자 지정 복제 정책을 생성할 수 있습니다. 예를 들어, 네트워크 전송 시 데이터를 압축하거나 SnapMirror가 스냅샷 복사본을 전송하기 위해 시도하는 횟수를 수정할 수 있습니다. 
---
= 사용자 지정 복제 정책을 생성합니다
:icons: font
:imagesdir: ../media/


[role="lead"]
복제 관계를 생성할 때 기본 또는 사용자 지정 정책을 사용할 수 있습니다. 사용자 지정 통합 복제 정책의 경우 초기화 및 업데이트 중에 전송할 스냅샷 복사본을 결정하는 _rules_을 하나 이상 정의해야 합니다.

관계의 기본 정책이 적합하지 않은 경우 사용자 지정 복제 정책을 생성할 수 있습니다. 예를 들어, 네트워크 전송 시 데이터를 압축하거나 SnapMirror가 스냅샷 복사본을 전송하기 위해 시도하는 횟수를 수정할 수 있습니다.

복제 정책의 _policy type_은 이 정책이 지원하는 관계 유형을 결정합니다. 아래 표에는 사용 가능한 정책 유형이 나와 있습니다.

[cols="2*"]
|===


| 정책 유형입니다 | 관계 유형 


 a| 
비동기식 - 미러
 a| 
SnapMirror DR



 a| 
대칭 복사 - 볼트
 a| 
통합 복제

|===
.단계
. 사용자 지정 복제 정책 생성:
+
'스냅샷 정책 생성 - vserver_SVM_ - 정책 유형 async-mirror|mirror-vault-comment_comment_-rs_transfer_ries_-transfer-priority low|normal-is-network-compression-enabled true|false'

+
전체 명령 구문은 man 페이지를 참조하십시오.

+
ONTAP 9.5부터 '-common-snapshot-schedule' 매개 변수를 사용하여 SnapMirror Synchronous 관계에 대한 공통 스냅샷 복사본 스케줄을 생성할 스케줄을 지정할 수 있습니다. 기본적으로 SnapMirror Synchronous 관계에 대한 일반적인 스냅샷 복사본 일정은 1시간입니다. SnapMirror Synchronous 관계에 대한 스냅샷 복사본 일정의 값을 30분에서 2시간으로 지정할 수 있습니다.

+
다음 예에서는 데이터 전송에 대해 네트워크 압축을 활성화하는 SnapMirror DR에 대한 사용자 지정 복제 정책을 생성합니다.

+
[listing]
----
cluster_dst::> snapmirror policy create -vserver svm1 -policy DR_compressed -type async-mirror -comment “DR with network compression enabled” -is-network-compression-enabled true
----
+
다음 예에서는 통합 복제에 대한 사용자 지정 복제 정책을 생성합니다.

+
[listing]
----
cluster_dst::> snapmirror policy create -vserver svm1 -policy my_unified -type mirror-vault
----


"미러 볼트" 정책 유형의 경우 초기화 및 업데이트 중에 전송할 스냅샷 복사본을 결정하는 규칙을 정의해야 합니다.

'snapmirror policy show' 명령을 사용하여 SnapMirror 정책이 생성되었는지 확인합니다. 전체 명령 구문은 man 페이지를 참조하십시오.
