---
permalink: element-replication/define-rule-policy-task.html 
sidebar: sidebar 
keywords: define, rule, policy 
summary: '"mirror-vault" 정책 유형이 있는 사용자 지정 정책의 경우 초기화 및 업데이트 중에 전송할 스냅샷 복사본을 결정하는 규칙을 하나 이상 정의해야 합니다. "미러 볼트" 정책 유형을 사용하여 기본 정책에 대한 규칙을 정의할 수도 있습니다.' 
---
= 정책에 대한 규칙을 정의합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
"미러 볼트" 정책 유형의 사용자 지정 정책의 경우 초기화 및 업데이트 중에 전송할 스냅샷 복사본을 결정하는 규칙을 하나 이상 정의해야 합니다. "미러 볼트" 정책 유형을 사용하여 기본 정책에 대한 규칙을 정의할 수도 있습니다.

.이 작업에 대해
"미러 볼트" 정책 유형의 모든 정책에는 복제할 스냅샷 복사본을 지정하는 규칙이 있어야 합니다. 예를 들어, ""격월"" 규칙은 SnapMirror 레이블 ""격월""에 할당된 스냅샷 복사본만 복제해야 함을 나타냅니다. Element Snapshot 복사본을 구성할 때 SnapMirror 레이블을 할당합니다.

각 정책 유형은 하나 이상의 시스템 정의 규칙과 연결됩니다. 이러한 규칙은 정책 유형을 지정할 때 정책에 자동으로 할당됩니다. 아래 표에는 시스템 정의 규칙이 나와 있습니다.

|===


| 시스템 정의 규칙 | 정책 유형에 사용됩니다 | 결과 


 a| 
SM_생성됨
 a| 
비동기 미러, 미러 볼트
 a| 
SnapMirror에서 생성된 스냅샷 복사본은 초기화 및 업데이트 시 전송됩니다.



 a| 
매일
 a| 
대칭 복사 - 볼트
 a| 
SnapMirror 레이블 "매일"이 있는 소스의 새 스냅샷 복사본은 초기화 및 업데이트 시 전송됩니다.



 a| 
매주
 a| 
대칭 복사 - 볼트
 a| 
SnapMirror 레이블 ""매주""가 있는 소스의 새 스냅샷 복사본은 초기화 및 업데이트 시 전송됩니다.



 a| 
매월
 a| 
대칭 복사 - 볼트
 a| 
SnapMirror 레이블 "월간"이 있는 소스의 새 스냅샷 복사본은 초기화 및 업데이트 시 전송됩니다.

|===
필요에 따라 기본 또는 사용자 지정 정책에 대한 추가 규칙을 지정할 수 있습니다. 예를 들면 다음과 같습니다.

* 기본 'MirorAndVault' 정책에 대해 원본의 Snapshot 복사본과 "격월" SnapMirror 레이블을 일치시키기 위해 "이중 월"이라는 규칙을 만들 수 있습니다.
* "미러 볼트" 정책 유형의 사용자 지정 정책의 경우 소스의 스냅샷 복사본과 "격주" SnapMirror 레이블을 일치시키기 위해 "격주" 규칙을 만들 수 있습니다.


.단계
. 정책의 규칙 정의:
+
'스냅샷 정책 추가 규칙 -vserver_SVM_-policy_policy_for_rule_-snapmirror-label_snapmirror-label_-keep_retention_count_'

+
전체 명령 구문은 man 페이지를 참조하십시오.

+
다음 예제에서는 기본 MirorAndVault 정책에 SnapMirror 레이블 '격월'이 있는 규칙을 추가합니다.

+
[listing]
----
cluster_dst::> snapmirror policy add-rule -vserver svm1 -policy MirrorAndVault -snapmirror-label bi-monthly -keep 6
----
+
다음 예에서는 사용자 지정 my_SnapVault 정책에 SnapMirror 레이블 "격주"가 포함된 규칙을 추가합니다.

+
[listing]
----
cluster_dst::> snapmirror policy add-rule -vserver svm1 -policy my_snapvault -snapmirror-label bi-weekly -keep 26
----
+
다음 예에서는 사용자 지정 'Sync' 정책에 SnapMirror 레이블 'app_consistent'가 포함된 규칙을 추가합니다.

+
[listing]
----
cluster_dst::> snapmirror policy add-rule -vserver svm1 -policy Sync -snapmirror-label app_consistent -keep 1
----
+
그런 다음 이 SnapMirror 레이블과 일치하는 소스 클러스터에서 스냅샷 복사본을 복제할 수 있습니다.

+
[listing]
----
cluster_src::> snapshot create -vserver vs1 -volume vol1 -snapshot snapshot1 -snapmirror-label app_consistent
----

