---
permalink: element-replication/reactivate-original-source-volume-task.html 
sidebar: sidebar 
keywords: reactivate. original, source, volume 
summary: 대상에서 데이터를 더 이상 제공할 필요가 없을 때 소스 볼륨과 타겟 볼륨 간에 원래 데이터 보호 관계를 다시 설정할 수 있습니다. 
---
= 원본 소스 볼륨을 다시 활성화합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
대상에서 데이터를 더 이상 제공할 필요가 없을 때 소스 볼륨과 타겟 볼륨 간에 원래 데이터 보호 관계를 다시 설정할 수 있습니다.

.이 작업에 대해
아래 절차에서는 원본 소스 볼륨의 기준선이 온전한 것으로 가정합니다. 기준선이 변경되지 않은 경우 절차를 수행하기 전에 데이터를 제공하는 볼륨과 원본 소스 볼륨 간의 관계를 생성하고 초기화해야 합니다.

형태로 Element 소스 경로를 지정해야 `<hostip:>/lun/<name>`합니다. 여기서 ""lun""은 실제 문자열 ""lun""이고 Element 볼륨의 이름입니다. `name`

ONTAP 9.4부터 ONTAP 대상에서 데이터를 제공하는 동안 생성된 LUN의 스냅샷 복사본은 Element 소스가 재활성화되면 자동으로 복제됩니다.

복제 규칙은 다음과 같습니다.

* iSCSI LUN만 지원됩니다.
* ONTAP 볼륨에서 Element 볼륨으로 둘 이상의 LUN을 복제할 수 없습니다.
* ONTAP 볼륨에서 여러 요소 볼륨으로 LUN을 복제할 수는 없습니다.


.단계
. 원본 데이터 보호 관계를 삭제합니다.
+
`snapmirror delete -source-path <SVM:volume>|<cluster://SVM/volume> -destination-path <hostip:>/lun/<name> -policy <policy>`

+
전체 명령 구문은 man 페이지를 참조하십시오.

+
다음 예에서는 IP 주소 10.0.0.11에서 원래 소스 볼륨 0005와 SVM_BACKUP에서 데이터를 제공하고 있는 볼륨 VolA_DST 사이의 관계를 삭제합니다.

+
[listing]
----
cluster_dst::> snapmirror delete -source-path 10.0.0.11:/lun/0005 -policy MirrorLatest -destination-path svm_backup:volA_dst
----
. 원래 데이터 보호 관계를 반대로 전환합니다.
+
`snapmirror resync -source-path <SVM:volume>|<cluster://SVM/volume> -destination-path <hostip:>/lun/<name> -policy <policy>`

+
전체 명령 구문은 man 페이지를 참조하십시오.

+
재동기화에는 기본 전송이 필요하지 않지만 시간이 오래 걸릴 수 있습니다. 사용량이 적은 시간에 재동기화를 실행할 수 있습니다.

+
다음 예에서는 IP 주소 10.0.0.11에서 원래 소스 볼륨 0005와 SVM_BACKUP에서 데이터를 제공하는 볼륨 VolA_DST 사이의 관계를 반전시킵니다.

+
[listing]
----
cluster_dst::> snapmirror resync -source-path svm_backup:volA_dst -destination-path 10.0.0.11:/lun/0005 -policy MirrorLatest
----
. 반대 관계 업데이트:
+
`snapmirror update -source-path <SVM:volume>|<cluster://SVM/volume> -destination-path <hostip:>/lun/<name>`

+
전체 명령 구문은 man 페이지를 참조하십시오.

+
[NOTE]
====
소스 및 타겟에 공통 스냅샷 복사본이 존재하지 않으면 명령이 실패합니다. '스냅샷 초기화'를 사용하여 관계를 다시 초기화합니다.

====
+
다음 예에서는 데이터를 제공하고 있는 볼륨, VM_BACKUP의 VolA_DST, IP 주소 10.0.0.11의 원본 소스 볼륨 0005의 관계를 업데이트합니다.

+
[listing]
----
cluster_dst::> snapmirror update -source-path svm_backup:volA_dst -destination-path 10.0.0.11:/lun/0005
----
. 역방향 관계에 대한 예약된 전송 중지:
+
`snapmirror quiesce -source-path <SVM:volume>|<cluster://SVM/volume> -destination-path <hostip:>/lun/<name>`

+
전체 명령 구문은 man 페이지를 참조하십시오.

+
다음 예에서는 데이터를 제공하고 있는 볼륨 간의 예약된 전송을 중지합니다. SVM_BACKUP의 VolA_DST와 IP 주소 10.0.0.11의 원본 소스 볼륨 0005.

+
[listing]
----
cluster_dst::> snapmirror quiesce -source-path svm_backup:volA_dst -destination-path 10.0.0.11:/lun/0005
----
. 취소된 관계에 대한 진행 중인 전송 중지:
+
`snapmirror abort -source-path <SVM:volume>|<cluster://SVM/volume> -destination-path <hostip:>/lun/<name>`

+
전체 명령 구문은 man 페이지를 참조하십시오.

+
다음 예에서는 데이터를 제공하고 있는 볼륨 간의 지속적인 전송을 중지합니다. 'VM_BACKUP'의 VolA_DST와 IP 주소 10.0의 원본 소스 볼륨 0005. 0.11:

+
[listing]
----
cluster_dst::> snapmirror abort -source-path svm_backup:volA_dst -destination-path 10.0.0.11:/lun/0005
----
. 역관계를 끊는 경우:
+
`snapmirror break -source-path <SVM:volume>|<cluster://SVM/volume> -destination-path <hostip:>/lun/<name>`

+
전체 명령 구문은 man 페이지를 참조하십시오.

+
다음 예에서는 데이터를 제공하고 있는 볼륨, VM_BACKUP의 VolA_DST, IP 주소 10.0.0.11의 원본 소스 볼륨 0005의 관계를 나눕니다.

+
[listing]
----
cluster_dst::> snapmirror break -source-path svm_backup:volA_dst -destination-path 10.0.0.11:/lun/0005
----
. 역방향 데이터 보호 관계를 삭제합니다.
+
`snapmirror delete -source-path <SVM:volume>|<cluster://SVM/volume> -destination-path <hostip:>/lun/<name> -policy <policy>`

+
전체 명령 구문은 man 페이지를 참조하십시오.

+
다음 예에서는 IP 주소 10.0.0.11에서 원래 소스 볼륨 0005와 SVM_BACKUP에서 데이터를 제공하고 있는 볼륨 VolA_DST 사이의 역방향 관계를 삭제합니다.

+
[listing]
----
cluster_src::> snapmirror delete -source-path svm_backup:volA_dst -destination-path 10.0.0.11:/lun/0005 -policy MirrorLatest
----
. 원래 데이터 보호 관계를 다시 설정합니다.
+
`snapmirror resync -source-path <hostip:>/lun/<name> -destination-path <SVM:volume>|<cluster://SVM/volume>`

+
전체 명령 구문은 man 페이지를 참조하십시오.

+
다음 예에서는 IP 주소 10.0.0.11에서 원래 소스 볼륨 0005와 SVM_BACKUP에서 원래 대상 볼륨 VolA_DST 사이의 관계를 다시 설정합니다.

+
[listing]
----
cluster_dst::> snapmirror resync -source-path 10.0.0.11:/lun/0005 -destination-path svm_backup:volA_dst
----


.작업을 마친 후
'snapmirror show' 명령을 사용하여 SnapMirror 관계가 생성되었는지 확인합니다. 전체 명령 구문은 man 페이지를 참조하십시오.
