---
permalink: tape-backup/availability-volumes-tapes-backup-restore-lif-reference.html 
sidebar: sidebar 
keywords: lif, availability, volumes, tape, devices, backup, restore, types, cab, extension, application 
summary: '클러스터의 모든 LIF 유형에서 NDMP 제어 연결을 설정하도록 백업 애플리케이션을 구성할 수 있습니다. SVM(스토리지 가상 시스템) 범위의 NDMP 모드에서는 이러한 LIF 유형과 CAB 확장 상태에 따라 백업 및 복원 작업에 대한 볼륨 및 테이프 장치의 가용성을 결정할 수 있습니다.' 
---
= 다양한 LIF 유형에서 백업 및 복원을 위해 볼륨 및 테이프 장치를 사용할 수 있습니다
:icons: font
:imagesdir: ../media/


[role="lead"]
클러스터의 모든 LIF 유형에서 NDMP 제어 연결을 설정하도록 백업 애플리케이션을 구성할 수 있습니다. SVM(스토리지 가상 시스템) 범위의 NDMP 모드에서는 이러한 LIF 유형과 CAB 확장 상태에 따라 백업 및 복원 작업에 대한 볼륨 및 테이프 장치의 가용성을 결정할 수 있습니다.

다음 표에는 NDMP 제어 연결 LIF 유형에 대한 볼륨 및 테이프 디바이스의 가용성과 CAB 확장의 상태가 나와 있습니다.



== 백업 애플리케이션에서 운전실 확장이 지원되지 않는 경우 볼륨 및 테이프 장치의 가용성을 유지할 수 있습니다

|===
| NDMP 제어 연결 LIF 유형입니다 | 백업 또는 복원에 사용할 수 있는 볼륨입니다 | 백업 또는 복원에 사용할 수 있는 테이프 디바이스입니다 


 a| 
노드 관리 LIF
 a| 
노드에서 호스팅하는 모든 볼륨
 a| 
노드 관리 LIF를 호스팅하는 노드에 연결된 테이프 디바이스입니다



 a| 
데이터 LIF
 a| 
데이터 LIF를 호스팅하는 노드에서 호스팅되는 SVM에 속하는 볼륨만
 a| 
없음



 a| 
클러스터 관리 LIF
 a| 
클러스터 관리 LIF를 호스팅하는 노드에서 호스팅하는 모든 볼륨입니다
 a| 
없음



 a| 
인터클러스터 LIF
 a| 
인터클러스터 LIF를 호스팅하는 노드에 의해 호스팅되는 모든 볼륨입니다
 a| 
인터클러스터 LIF를 호스팅하는 노드에 연결된 테이프 장치

|===


== 백업 애플리케이션에서 CAB 확장을 지원하는 경우 볼륨 및 테이프 장치의 가용성

|===
| NDMP 제어 연결 LIF 유형입니다 | 백업 또는 복원에 사용할 수 있는 볼륨입니다 | 백업 또는 복원에 사용할 수 있는 테이프 디바이스입니다 


 a| 
노드 관리 LIF
 a| 
노드에서 호스팅하는 모든 볼륨
 a| 
노드 관리 LIF를 호스팅하는 노드에 연결된 테이프 디바이스입니다



 a| 
데이터 LIF
 a| 
데이터 LIF를 호스팅하는 SVM에 속한 모든 볼륨
 a| 
없음



 a| 
클러스터 관리 LIF
 a| 
클러스터의 모든 볼륨
 a| 
클러스터의 모든 테이프 디바이스



 a| 
인터클러스터 LIF
 a| 
클러스터의 모든 볼륨
 a| 
클러스터의 모든 테이프 디바이스

|===