---
permalink: tape-backup/before-restoring-data-concept.html 
sidebar: sidebar 
keywords: considerations, restore, file, data, original, path, destination, operation, required, space 
summary: 백업된 데이터를 원래 경로 또는 다른 대상으로 복원할 수 있습니다. 백업된 데이터를 다른 대상으로 복원하는 경우 복원 작업을 위한 대상을 준비해야 합니다. 
---
= 데이터를 복원하기 전에 고려해야 할 사항
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
백업된 데이터를 원래 경로 또는 다른 대상으로 복원할 수 있습니다. 백업된 데이터를 다른 대상으로 복원하는 경우 복원 작업을 위한 대상을 준비해야 합니다.

데이터를 원래 경로 또는 다른 대상으로 복원하기 전에 다음 정보가 있어야 하며 다음 요구 사항을 충족해야 합니다.

* 복구 수준입니다
* 데이터를 복원할 경로입니다
* 백업 중에 사용되는 차단 요소입니다
* 증분 복원을 수행하는 경우 모든 테이프가 백업 체인에 있어야 합니다
* 복원할 테이프와 호환 및 사용 가능한 테이프 드라이브


데이터를 다른 대상으로 복원하기 전에 다음 작업을 수행해야 합니다.

* 볼륨을 복원하는 경우 새 볼륨을 만들어야 합니다.
* qtree 또는 디렉토리를 복원하는 경우, 복원 중인 파일과 이름이 같은 파일을 이동하거나 이름을 변경해야 합니다.


[NOTE]
====
ONTAP 9에서는 qtree 이름이 유니코드 형식을 지원합니다. 이전 버전의 ONTAP에서는 이 형식을 지원하지 않습니다. ONTAP 9의 유니코드 이름이 있는 qtree가 'ndmpcopy' 명령을 사용하여 ONTAP의 이전 릴리즈로 복제되거나 테이프의 백업 이미지에서 복원을 통해 복사되면 qtree가 유니코드 형식이 있는 qtree가 아닌 일반 디렉토리로 복원됩니다.

====
[NOTE]
====
복구된 파일의 이름이 기존 파일과 같으면 복구된 파일이 기존 파일을 덮어씁니다. 그러나 디렉토리는 덮어쓰지 않습니다.

====
DAR를 사용하지 않고 복원 중에 파일, 디렉토리 또는 qtree의 이름을 바꾸려면 추출 환경 변수를 "E"로 설정해야 합니다.



== 대상 스토리지 시스템의 필수 공간입니다

대상 스토리지 시스템에 복원할 데이터 양보다 약 100MB의 공간이 필요합니다.

[NOTE]
====
복구 작업은 복구 작업이 시작될 때 대상 볼륨의 볼륨 공간 및 inode 가용성을 확인합니다. 강제 환경 변수를 'Y'로 설정하면 복원 작업에서 대상 경로의 볼륨 공간 및 inode 가용성 검사를 건너뜁니다. 대상 볼륨에 사용 가능한 볼륨 공간 또는 inode가 충분하지 않은 경우 복구 작업은 대상 볼륨 공간과 inode 가용성에 의해 허용되는 데이터 양을 복구합니다. 볼륨 공간 또는 inode가 더 이상 남아 있지 않으면 복구 작업이 중지됩니다.

====