---
permalink: tape-backup/commands-manage-drives-media-changers-reference.html 
sidebar: sidebar 
keywords: manage, tape, drive, media, changer, operation, cluster, cartridge, position, online, offline, reset, clear 
summary: 클러스터의 테이프 드라이브 및 미디어 체인저에 대한 정보를 보고, 테이프 드라이브를 온라인 상태로 전환하고, 오프라인 상태로 만들고, 테이프 드라이브 카트리지 위치를 수정하고, 테이프 드라이브 별칭 이름을 설정 및 지우고, 테이프 드라이브를 재설정하는 데 사용되는 명령이 있습니다. 또한 테이프 드라이브 통계를 보거나 재설정할 수 있습니다. 
---
= 테이프 드라이브, 미디어 체인저 및 테이프 드라이브 작업을 관리하는 명령입니다
:icons: font
:imagesdir: ../media/


[role="lead"]
클러스터의 테이프 드라이브 및 미디어 체인저에 대한 정보를 보고, 테이프 드라이브를 온라인 상태로 전환하고, 오프라인 상태로 만들고, 테이프 드라이브 카트리지 위치를 수정하고, 테이프 드라이브 별칭 이름을 설정 및 지우고, 테이프 드라이브를 재설정하는 데 사용되는 명령이 있습니다. 또한 테이프 드라이브 통계를 보거나 재설정할 수 있습니다.

|===
| 원하는 작업 | 이 명령 사용... 


 a| 
테이프 드라이브를 온라인 상태로 전환합니다
 a| 
'테이프 온라인 보관'



 a| 
테이프 드라이브 또는 미디어 체인저의 별칭 이름을 지웁니다
 a| 
'테이프 별칭 지우기'



 a| 
테이프 드라이브에 대한 테이프 추적 작업을 활성화하거나 비활성화합니다
 a| 
"테이프 추적 보관"



 a| 
테이프 드라이브 카트리지 위치를 수정합니다
 a| 
'테이프 보관 위치'



 a| 
테이프 드라이브를 재설정합니다
 a| 
'테이프 재설정'을 선택합니다

[NOTE]
====
이 명령은 고급 권한 수준에서만 사용할 수 있습니다.

====


 a| 
테이프 드라이브 또는 미디어 체인저의 별칭 이름을 설정합니다
 a| 
'스토리지 테이프 별칭 세트'



 a| 
테이프 드라이브를 오프라인 상태로 전환합니다
 a| 
'테이프 오프라인 보관'



 a| 
모든 테이프 드라이브 및 미디어 체인저에 대한 정보를 봅니다
 a| 
'스토리지 테이프 쇼'



 a| 
클러스터에 연결된 테이프 드라이브에 대한 정보를 봅니다
 a| 
* '테이프 쇼테이프 드라이브 보관'
* '시스템 노드 하드웨어 테이프 드라이브 표시




 a| 
클러스터에 연결된 미디어 체인저에 대한 정보를 봅니다
 a| 
'스토리지 테이프 쇼 미디어 체인저'



 a| 
클러스터에 연결된 테이프 드라이브에 대한 오류 정보를 봅니다
 a| 
'테이프 저장 표시 오류'입니다



 a| 
클러스터의 각 노드에 연결된 모든 ONTAP 인증 및 지원 테이프 드라이브를 봅니다
 a| 
'Storage tape show-supported-status'를 선택합니다



 a| 
클러스터의 각 노드에 연결된 모든 테이프 드라이브 및 미디어 체인저의 별칭을 봅니다
 a| 
'Storage tape alias show'



 a| 
테이프 드라이브의 통계 판독값을 0으로 재설정합니다
 a| 
'Storage stats tape zero' tape_name

이 명령은 노드 쉘에서 사용해야 합니다.



 a| 
ONTAP에서 지원하는 테이프 드라이브를 봅니다
 a| 
"torage show tape supported[-v]"

이 명령은 노드 쉘에서 사용해야 합니다. 각 테이프 드라이브에 대한 자세한 내용을 보려면 '-v' 옵션을 사용할 수 있습니다.



 a| 
테이프 디바이스 통계를 보고 테이프 성능을 이해하고 사용 패턴을 확인합니다
 a| 
'STORAGE STATS TAPE'TAPE_NAME'입니다

이 명령은 노드 쉘에서 사용해야 합니다.

|===
이러한 명령에 대한 자세한 내용은 man 페이지를 참조하십시오.
