---
permalink: tape-backup/commands-verify-library-connections-reference.html 
sidebar: sidebar 
keywords: commands, verify, tape, library, connections, storage, system 
summary: 스토리지 시스템과 스토리지 시스템에 연결된 테이프 라이브러리 구성 사이의 접속 경로에 대한 정보를 볼 수 있습니다. 이 정보를 사용하여 테이프 라이브러리 구성에 대한 연결 경로를 확인하거나 연결 경로와 관련된 문제를 해결할 수 있습니다. 
---
= 테이프 라이브러리 연결을 확인하는 명령입니다
:icons: font
:imagesdir: ../media/


[role="lead"]
스토리지 시스템과 스토리지 시스템에 연결된 테이프 라이브러리 구성 사이의 접속 경로에 대한 정보를 볼 수 있습니다. 이 정보를 사용하여 테이프 라이브러리 구성에 대한 연결 경로를 확인하거나 연결 경로와 관련된 문제를 해결할 수 있습니다.

새 테이프 라이브러리를 추가하거나 생성한 후 또는 테이프 라이브러리에 대한 단일 경로 또는 다중 경로 액세스에서 장애가 발생한 경로를 복원한 후 테이프 라이브러리 연결을 확인하기 위해 다음 테이프 라이브러리 세부 정보를 볼 수 있습니다. 또한 경로 관련 오류를 해결하거나 테이프 라이브러리에 대한 액세스가 실패하는 경우에도 이 정보를 사용할 수 있습니다.

* 테이프 라이브러리가 연결된 노드입니다
* 장치 ID입니다
* NDMP 경로
* 테이프 라이브러리 이름입니다
* 타겟 포트 및 이니시에이터 포트 ID
* 모든 타겟 또는 FC 이니시에이터 포트를 위한 테이프 라이브러리에 단일 경로 또는 다중 경로 액세스
* ""경로 오류"" 및 ""경로 Qual""와 같은 경로 관련 데이터 무결성 세부 정보
* LUN 그룹 및 LUN 수


|===
| 원하는 작업 | 이 명령 사용... 


 a| 
클러스터의 테이프 라이브러리에 대한 정보를 봅니다
 a| 
'시스템 노드 하드웨어 테이프 라이브러리 표시



 a| 
테이프 라이브러리의 경로 정보를 봅니다
 a| 
'Storage tape library path show'



 a| 
모든 이니시에이터 포트에 대한 테이프 라이브러리의 경로 정보를 봅니다
 a| 
'Storage tape library path show-by-initiator'를 선택합니다



 a| 
스토리지 테이프 라이브러리와 클러스터 간의 접속 정보를 봅니다
 a| 
'Storage tape library config show'를 선택합니다

|===
이러한 명령에 대한 자세한 내용은 man 페이지를 참조하십시오.
