---
permalink: tape-backup/configure-multipath-access-concept.html 
sidebar: sidebar 
keywords: considerations, configuring, multipath, tape, access 
summary: 테이프 라이브러리의 테이프 드라이브를 액세스할 수 있도록 스토리지 시스템에서 두 개의 경로를 구성할 수 있습니다. 한 경로에 장애가 발생할 경우 스토리지 시스템은 다른 경로를 사용하여 장애가 발생한 경로를 즉시 복구하지 않고도 테이프 드라이브를 액세스할 수 있습니다. 이렇게 하면 테이프 작업을 다시 시작할 수 있습니다. 
---
= 다중 경로 테이프 액세스를 구성할 때 고려해야 할 사항입니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
테이프 라이브러리의 테이프 드라이브를 액세스할 수 있도록 스토리지 시스템에서 두 개의 경로를 구성할 수 있습니다. 한 경로에 장애가 발생할 경우 스토리지 시스템은 다른 경로를 사용하여 장애가 발생한 경로를 즉시 복구하지 않고도 테이프 드라이브를 액세스할 수 있습니다. 이렇게 하면 테이프 작업을 다시 시작할 수 있습니다.

스토리지 시스템에서 다중 경로 테이프 액세스를 구성할 때는 다음 사항을 고려해야 합니다.

* LUN 매핑을 지원하는 테이프 라이브러리에서 LUN 그룹에 대한 다중 경로 액세스를 위해 LUN 매핑은 각 경로에서 대칭적이어야 합니다.
+
테이프 드라이브와 미디어 체인저는 테이프 라이브러리의 LUN 그룹(동일한 이니시에이터 경로 세트를 공유하는 LUN 세트)에 할당됩니다. LUN 그룹의 모든 테이프 드라이브를 여러 경로에 대한 백업 및 복원 작업에 사용할 수 있어야 합니다.

* 스토리지 시스템에서 테이프 라이브러리의 테이프 드라이브를 액세스하도록 최대 2개의 경로를 구성할 수 있습니다.
* 다중 경로 테이프 액세스는 로드 밸런싱을 지원합니다. 로드 밸런싱은 기본적으로 비활성화되어 있습니다.


다음 예제에서 스토리지 시스템은 두 개의 이니시에이터 경로 0b 및 0d를 통해 LUN 그룹 0에 액세스합니다. 두 경로 모두에서 LUN 그룹은 LUN 번호, 0 및 LUN 수, 5를 동일하게 갖습니다. 스토리지 시스템은 이니시에이터 경로 1개만을 통해 LUN 그룹 1을 3D로 액세스합니다.

[listing]
----

STSW-3070-2_cluster::> storage tape library config show

Node                    LUN Group   LUN Count  Library Name  Library Target Port  Initiator
----------------------- ----------- ---------- ------------- -------------------- -----
STSW-3070-2_cluster-01        0      5         IBM 3573-TL_1  510a09800000412d     0b
                                                                                  	0d
                              1      2         IBM 3573-TL_2  50050763124b4d6f     3d

3 entries were displayed
----
자세한 내용은 man 페이지를 참조하십시오.
