---
permalink: tape-backup/dump-storage-failover-arl-operations-concept.html 
sidebar: sidebar 
keywords: dump, workd, storage, failover, arl, operations, override, aggregate, relocation, takeover, giveback, cab, extension 
summary: '덤프 백업 또는 복원 작업을 수행하기 전에 이러한 작업이 스토리지 페일오버(테이크오버 및 반환) 또는 애그리게이트 재배치(ARL) 작업과 어떻게 연동되는지 이해해야 합니다. override-vetoes 옵션은 스토리지 페일오버 또는 ARL 작업 중 덤프 엔진의 동작을 결정합니다.' 
---
= 스토리지 페일오버 및 ARL 작업과 덤프 작동 방식
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
덤프 백업 또는 복원 작업을 수행하기 전에 이러한 작업이 스토리지 페일오버(테이크오버 및 반환) 또는 애그리게이트 재배치(ARL) 작업과 어떻게 연동되는지 이해해야 합니다. '-override-vetoes' 옵션은 스토리지 페일오버 또는 ARL 작업 중 덤프 엔진의 동작을 결정합니다.

덤프 백업 또는 복원 작업이 실행되고 '-override-vetoes' 옵션이 'false'로 설정되어 있으면 사용자 실행 스토리지 페일오버 또는 ARL 작업이 중지됩니다. 그러나 '–override-vetoes' 옵션이 true로 설정되어 있으면 스토리지 페일오버 또는 ARL 작업이 계속되고 덤프 백업 또는 복원 작업이 중단됩니다. 스토리지 시스템에 의해 스토리지 페일오버 또는 ARL 작업이 자동으로 시작되면 활성 덤프 백업 또는 복원 작업이 항상 중단됩니다. 스토리지 페일오버 또는 ARL 작업이 완료된 후에도 덤프 백업 및 복원 작업을 다시 시작할 수 없습니다.



== 운전실 확장이 지원되는 경우의 덤프 작업

백업 애플리케이션이 CAB 확장을 지원하는 경우 스토리지 페일오버 또는 ARL 작업 후 백업 정책을 재구성하지 않고 증분 덤프 백업 및 복원 작업을 계속 수행할 수 있습니다.



== 운전실 확장이 지원되지 않을 때 덤프 작업

백업 애플리케이션이 CAB 확장을 지원하지 않는 경우 백업 정책에 구성된 LIF를 대상 애그리게이트를 호스팅하는 노드로 마이그레이션할 경우 증분 덤프 백업 및 복원 작업을 계속 수행할 수 있습니다. 그렇지 않으면 스토리지 페일오버 및 ARL 작업 후에 증분 백업 작업을 수행하기 전에 기본 백업을 수행해야 합니다.

[NOTE]
====
스토리지 페일오버 작업의 경우 백업 정책에 구성된 LIF를 파트너 노드로 마이그레이션해야 합니다.

====
.관련 정보
link:../concepts/index.html["ONTAP 개념"]

https://["고가용성"]
