---
permalink: tape-backup/dump-backup-restore-operations-mcc-config-concept.html 
sidebar: sidebar 
keywords: dump, backup, restore, opartion, metrocluster, configuration, switchback, switchover 
summary: MetroCluster 구성에서 덤프 백업 및 복원 작업을 수행하기 전에 스위치오버 또는 스위치백 작업이 수행될 때 덤프 작업이 어떻게 영향을 받는지 이해해야 합니다. 
---
= MetroCluster 구성에서 덤프 백업 및 복원 작업이 영향을 받는 방법
:icons: font
:imagesdir: ../media/


[role="lead"]
MetroCluster 구성에서 덤프 백업 및 복원 작업을 수행하기 전에 스위치오버 또는 스위치백 작업이 수행될 때 덤프 작업이 어떻게 영향을 받는지 이해해야 합니다.



== 백업 또는 복구 작업을 덤프한 후 전환

클러스터 1과 클러스터 2의 두 클러스터를 고려합니다. 클러스터 1에서 덤프 백업 또는 복원 작업 중에 클러스터 1에서 클러스터 2로 전환이 시작되면 다음이 발생합니다.

* 'override-vetoes' 옵션의 값이 'false'이면 절체가 중단되고 백업 또는 복원 작업이 계속됩니다.
* 옵션 값이 true이면 덤프 백업 또는 복원 작업이 중단되고 전환이 계속됩니다.




== 백업 또는 복원 작업을 덤프한 다음 스위치백을 수행합니다

클러스터 1에서 클러스터 2로 전환이 수행되고 클러스터 2에서 덤프 백업 또는 복원 작업이 시작됩니다. 덤프 작업은 클러스터 2에 있는 볼륨을 백업 또는 복구합니다. 이 시점에서는 클러스터 2에서 클러스터 1로 스위치백을 시작한 경우 다음이 발생합니다.

* 'override-vetoes' 옵션의 값이 'false'인 경우, 스위치백을 취소하고 백업 또는 복원 작업을 계속합니다.
* 옵션 값이 true이면 백업 또는 복원 작업이 중단되고 스위치백이 계속됩니다.




== 스위치오버 또는 스위치백 중에 덤프 백업 또는 복원 작업이 시작되었습니다

클러스터 1에서 클러스터 2로 전환하는 동안 클러스터 1에서 덤프 백업 또는 복원 작업이 시작되면 백업 또는 복원 작업이 실패하고 전환이 계속됩니다.

클러스터 2에서 클러스터 1로 스위치백을 진행하는 동안 클러스터 2에서 덤프 백업 또는 복원 작업이 시작되면 백업 또는 복원 작업이 실패하고 스위치백을 계속합니다.
