---
permalink: tape-backup/environment-variables-supported-concept.html 
sidebar: sidebar 
keywords: environment, variables, ontap, ndmp, restore, operation, backup, default, value, dump, smtape 
summary: 환경 변수는 NDMP 지원 백업 애플리케이션과 스토리지 시스템 간의 백업 또는 복구 작업에 대한 정보를 전달하는 데 사용됩니다. ONTAP는 연결된 기본값을 갖는 환경 변수를 지원합니다. 그러나 이러한 기본값을 수동으로 수정할 수 있습니다. 
---
= ONTAP에서 지원하는 환경 변수입니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
환경 변수는 NDMP 지원 백업 애플리케이션과 스토리지 시스템 간의 백업 또는 복구 작업에 대한 정보를 전달하는 데 사용됩니다. ONTAP는 연결된 기본값을 갖는 환경 변수를 지원합니다. 그러나 이러한 기본값을 수동으로 수정할 수 있습니다.

백업 애플리케이션에서 설정한 값을 수동으로 수정하면 애플리케이션이 예상치 않게 작동할 수 있습니다. 이는 백업 또는 복원 작업에서 백업 애플리케이션이 예상한 작업을 수행하지 못할 수 있기 때문입니다. 그러나 경우에 따라 신중하게 수정하면 문제를 식별하거나 해결하는 데 도움이 될 수 있습니다.

다음 표에는 덤프 및 SMTape에 공통으로 사용되는 환경 변수와 덤프 및 SMTape에만 지원되는 변수가 나와 있습니다. 다음 표에는 ONTAP에서 지원하는 환경 변수가 사용되는 경우 해당 변수가 작동하는 방식이 설명되어 있습니다.

[NOTE]
====
대부분의 경우 Y는 T, N도 F를 받아들입니다.

====


== 덤프 및 SMTape에 대해 지원되는 환경 변수입니다

|===
| 환경 변수 | 유효한 값 | 기본값 | 설명 


 a| 
디버그
 a| 
Y, N
 a| 
N
 a| 
디버깅 정보가 인쇄되도록 지정합니다.



 a| 
파일 시스템
 a| 
'트링'
 a| 
"없음"
 a| 
백업할 데이터의 루트 경로 이름을 지정합니다.



 a| 
NDMP_version
 a| 
RETURN_OVERY'를 선택합니다
 a| 
"없음"
 a| 
NDMP_VERSION 변수를 수정하면 안 됩니다. 백업 작업에 의해 생성된 NDMP_VERSION 변수는 NDMP 버전을 반환합니다.

ONTAP는 내부 사용을 위해 백업 중에 NDMP_VERSION 변수를 설정하고 정보 제공을 위해 백업 애플리케이션에 전달합니다. NDMP 세션의 NDMP 버전이 이 변수로 설정되지 않았습니다.



 a| 
경로 이름_구분 기호입니다
 a| 
RETURN_VALUE'입니다
 a| 
"없음"
 a| 
경로 이름 구분 문자를 지정합니다.

이 문자는 백업되는 파일 시스템에 따라 다릅니다. ONTAP의 경우 문자 ""/"가 이 변수에 할당됩니다. NDMP 서버는 테이프 백업 작업을 시작하기 전에 이 변수를 설정합니다.



 a| 
유형
 a| 
'둔부' 또는 '스머테이프'
 a| 
둔부
 a| 
테이프 백업 및 복원 작업을 수행하는 데 지원되는 백업 유형을 지정합니다.



 a| 
자세한 정보
 a| 
Y, N
 a| 
N
 a| 
테이프 백업 또는 복구 작업을 수행하는 동안 로그 메시지를 늘립니다.

|===


== 덤프에 대해 지원되는 환경 변수입니다

|===
| 환경 변수 | 유효한 값 | 기본값 | 설명 


 a| 
acl_start 를 선택합니다
 a| 
RETURN_OVERY'를 선택합니다
 a| 
"없음"
 a| 
백업 작업에 의해 생성된 ACL_START 변수는 직접 액세스 복구 또는 재시작 가능한 NDMP 백업 작업에 사용되는 오프셋 값입니다.

오프셋 값은 덤프 파일에서 ACL 데이터(Pass V)가 시작되고 백업 끝에서 반환되는 바이트 오프셋입니다. 백업된 데이터를 올바르게 복원하기 위한 직접 액세스 복원 작업의 경우 ACL_START 값을 복구 작업이 시작될 때 복구 작업으로 전달해야 합니다. NDMP 재시작 가능 백업 작업에서는 acl_start 값을 사용하여 백업 스트림의 다시 시작 가능한 부분이 시작되는 백업 애플리케이션과 통신합니다.



 a| 
base_date 를 선택합니다
 a| 
0, -1, dump_date 값
 a| 
'-1'
 a| 
증분 백업의 시작 날짜를 지정합니다.

'-1'로 설정하면 base_date 증분 지정자가 비활성화됩니다. 레벨 0 백업에서 '0'으로 설정하면 증분 백업이 활성화됩니다. 초기 백업 후 이전 증분 백업의 dump_date 변수 값이 base_date 변수에 할당됩니다.

이러한 변수는 레벨/업데이트 기반 증분 백업에 대한 대안입니다.



 a| 
직접
 a| 
Y, N
 a| 
N
 a| 
전체 테이프를 스캔하는 대신 복구가 파일 데이터가 상주하는 테이프 위치로 직접 빠르게 전달되도록 지정합니다.

직접 액세스 복구가 작동하려면 백업 애플리케이션이 위치 정보를 제공해야 합니다. 이 변수가 Y로 설정되어 있으면 백업 응용 프로그램에서 파일 또는 디렉터리 이름과 위치 지정 정보를 지정합니다.



 a| 
dmp_name입니다
 a| 
'트링'
 a| 
"없음"
 a| 
여러 하위 트리 백업의 이름을 지정합니다.

여러 하위 트리 백업에는 이 변수가 필수입니다.



 a| 
dump_date 를 참조하십시오
 a| 
RETURN_VALUE'입니다
 a| 
"없음"
 a| 
이 변수를 직접 변경하지 않습니다. base_date 변수가 '-1'이 아닌 값으로 설정된 경우 백업에 의해 생성됩니다.

dump_date 변수는 32비트 레벨 값을 덤프 소프트웨어에서 계산된 32비트 시간 값에 미리 추가하여 파생됩니다. 수준은 base_date 변수에 전달된 마지막 수준 값에서 증가합니다. 결과 값은 후속 증분 백업에서 base_date 값으로 사용됩니다.



 a| 
Enhanced_DAR_ENABLED입니다
 a| 
Y, N
 a| 
N
 a| 
향상된 DAR 기능의 사용 여부를 지정합니다. 향상된 DAR 기능은 NT 스트림이 있는 파일의 DAR 및 DAR 디렉토리를 지원합니다. 향상된 성능을 제공합니다.

복원 중 향상된 DAR는 다음 조건이 충족되는 경우에만 가능합니다.

* ONTAP는 향상된 DAR를 지원합니다.
* 백업 중에 파일 기록이 활성화됩니다(HIST=Y).
* ndmpd.offset_map.enable 옵션이 on으로 설정되어 있습니다.
* Enhanced_DAR_ENABLED 변수가 복원 중에 'Y'로 설정됩니다.




 a| 
제외
 a| 
pattern_string
 a| 
"없음"
 a| 
데이터를 백업할 때 제외되는 파일 또는 디렉토리를 지정합니다.

제외 목록은 쉼표로 구분된 파일 또는 디렉토리 이름 목록입니다. 파일 또는 디렉토리의 이름이 목록의 이름 중 하나와 일치하면 백업에서 제외됩니다.

제외 목록에서 이름을 지정할 때 다음 규칙이 적용됩니다.

* 파일 또는 디렉토리의 정확한 이름을 사용해야 합니다.
* 와일드카드 문자인 별표(*)는 문자열의 첫 번째 문자 또는 마지막 문자여야 합니다.
+
각 문자열은 최대 2개의 별표를 포함할 수 있습니다.

* 파일 또는 디렉터리 이름의 쉼표 앞에는 백슬래시가 있어야 합니다.
* 제외 목록에는 최대 32개의 이름이 포함될 수 있습니다.


[NOTE]
====
non_quota_tree를 동시에 Y로 설정하면 백업 대상에서 제외되도록 지정된 파일 또는 디렉토리가 제외되지 않습니다.

====


 a| 
압축 풀기
 a| 
Y, N, E
 a| 
N
 a| 
백업된 데이터 집합의 하위 트리를 복원하도록 지정합니다.

백업 응용 프로그램은 추출할 하위 트리의 이름을 지정합니다. 지정된 파일이 콘텐츠가 백업된 디렉토리와 일치하면 디렉토리의 압축이 재귀적으로 풀립니다.

DAR를 사용하지 않고 복원 중에 파일, 디렉토리 또는 qtree의 이름을 바꾸려면 추출 환경 변수를 "E"로 설정해야 합니다.



 a| 
extract_acl 을 선택합니다
 a| 
Y, N
 a| 
Y를 누릅니다
 a| 
백업 파일의 ACL이 복구 작업에서 복원되도록 지정합니다.

기본값은 데이터를 복원할 때 ACLS를 복원하는 것입니다. 단, DARs(direct=Y)는 예외입니다.



 a| 
하중
 a| 
Y, N
 a| 
N
 a| 
복구 작업에서 대상 볼륨의 볼륨 공간 및 inode 가용성을 확인해야 하는지 여부를 결정합니다.

이 변수를 'Y'로 설정하면 복원 작업에서 대상 경로의 볼륨 공간 및 inode 가용성 검사를 건너뜁니다.

대상 볼륨에 충분한 볼륨 공간 또는 inode를 사용할 수 없는 경우 복구 작업은 대상 볼륨 공간과 inode 가용성에 의해 허용되는 많은 데이터를 복구합니다. 볼륨 공간 또는 inode를 사용할 수 없는 경우 복구 작업이 중지됩니다.



 a| 
하이스트
 a| 
Y, N
 a| 
N
 a| 
파일 기록 정보가 백업 응용 프로그램으로 전송되도록 지정합니다.

대부분의 상용 백업 애플리케이션은 HIST 변수를 Y로 설정합니다. 백업 작업의 속도를 증가시키거나 파일 기록 수집 문제를 해결하려는 경우 이 변수를 "N"으로 설정할 수 있습니다.

[NOTE]
====
백업 응용 프로그램이 파일 기록을 지원하지 않는 경우 HIST 변수를 'Y'로 설정하지 않아야 합니다.

====


 a| 
ctime 무시
 a| 
Y, N
 a| 
N
 a| 
이전 증분 백업 이후에 ctime 값만 변경된 경우 파일이 증분 백업되지 않도록 지정합니다.

바이러스 검사 소프트웨어와 같은 일부 응용 프로그램은 파일 또는 해당 속성이 변경되지 않았더라도 inode 내의 파일의 ctime 값을 변경합니다. 따라서 증분 백업은 변경되지 않은 파일을 백업할 수 있습니다. ctime 값이 수정되었기 때문에 증분 백업에 허용 가능한 시간 또는 공간이 필요한 경우에만 ignore_ctime 변수를 지정해야 합니다.

[NOTE]
====
NDMP dump 명령은 기본적으로 ignore_ctime을 false로 설정합니다. "참"으로 설정하면 다음과 같은 데이터 손실이 발생할 수 있습니다.

. 볼륨 레벨 증분 ndmpcopy를 사용하여 ignore_ctime을 true로 설정하면 소스의 qtree에서 이동된 파일이 삭제됩니다.
. 볼륨 레벨 증분 덤프 중에 'ignore_ctime'을 true로 설정하면 증분 복원 중에 소스에서 Qtree로 이동된 파일이 삭제됩니다.


이 문제를 방지하려면 볼륨 레벨 NDMP 덤프 또는 ndmpcopy 중에 ignore_ctime을 false로 설정해야 합니다.

====


 a| 
ignore_cQtree
 a| 
Y, N
 a| 
N
 a| 
복구 작업이 백업된 qtree에서 qtree 정보를 복원하지 않음을 지정합니다.



 a| 
레벨
 a| 
0-31입니다
 a| 
0
 a| 
백업 레벨을 지정합니다.

레벨 0은 전체 데이터 세트를 복사합니다. 0보다 높은 값으로 지정된 증분 백업 레벨은 마지막 증분 백업 이후 모든 파일(새 파일 또는 수정된 파일)을 복사합니다. 예를 들어 레벨 1은 레벨 0 백업 이후에 새 파일이나 수정된 파일을 백업하며, 레벨 2는 레벨 1 백업 이후에 새 파일이나 수정된 파일을 백업합니다.



 a| 
목록
 a| 
Y, N
 a| 
N
 a| 
에는 실제로 데이터를 복원하지 않고 백업된 파일 이름 및 inode 번호가 나와 있습니다.



 a| 
list_qtree 를 참조하십시오
 a| 
Y, N
 a| 
N
 a| 
에는 실제로 데이터를 복원하지 않는 백업 qtree가 나와 있습니다.



 a| 
multi_subtree_names를 선택합니다
 a| 
'트링'
 a| 
"없음"
 a| 
백업이 여러 하위 트리 백업임을 지정합니다.

하위 트리 이름의 줄 바꿈, null 종료 목록인 문자열에 여러 개의 하위 트리가 지정됩니다. 하위 트리는 목록의 마지막 요소로 지정해야 하는 공통 루트 디렉터리를 기준으로 경로 이름으로 지정됩니다.

이 변수를 사용하는 경우 dmp_name 변수도 사용해야 합니다.



 a| 
NDMP_Unicode_FH
 a| 
Y, N
 a| 
N
 a| 
파일 기록 정보에 있는 파일의 NFS 이름 외에 유니코드 이름이 포함되도록 지정합니다.

이 옵션은 대부분의 백업 응용 프로그램에서 사용되지 않으며, 이러한 추가 파일 이름을 받도록 백업 응용 프로그램을 설계하지 않는 한 설정해서는 안 됩니다. HIST 변수도 설정해야 합니다.



 a| 
no_acls입니다
 a| 
Y, N
 a| 
N
 a| 
데이터를 백업할 때 ACL을 복제하지 않도록 지정합니다.



 a| 
non_quota_tree
 a| 
Y, N
 a| 
N
 a| 
데이터를 백업할 때 Qtree의 파일 및 디렉토리를 무시하도록 지정합니다.

'Y'로 설정하면 파일 시스템 변수에 의해 지정된 데이터 세트의 qtree에 있는 항목이 백업되지 않습니다. 이 변수는 파일 시스템 변수가 전체 볼륨을 지정하는 경우에만 적용됩니다. non_quota_tree 변수는 레벨 0 백업에서만 작동하며 multi_subtree_names 변수가 지정된 경우에는 작동하지 않습니다.

[NOTE]
====
non_quota_tree를 동시에 Y로 설정하면 백업 대상에서 제외되도록 지정된 파일 또는 디렉토리가 제외되지 않습니다.

====


 a| 
노와이ITE
 a| 
Y, N
 a| 
N
 a| 
복구 작업이 디스크에 데이터를 쓰지 않도록 지정합니다.

이 변수는 디버깅에 사용됩니다.



 a| 
반복
 a| 
Y, N
 a| 
Y를 누릅니다
 a| 
DAR 복원 중에 디렉토리 항목을 확장하도록 지정합니다.

DIRECT 및 Enhanced_DAR_ENABLED 환경 변수('Y'로 설정)도 활성화해야 합니다. 반복 변수가 비활성화된 경우('N'으로 설정), 원본 소스 경로의 모든 디렉토리에 대한 사용 권한과 ACL만 테이프에서 복원되며 디렉토리의 내용은 복구되지 않습니다. recursive 변수가 N으로 설정되어 있거나 recover_full_paths 변수가 Y로 설정되어 있으면 복구 경로가 원래 경로로 끝나야 합니다.

[NOTE]
====
재귀 변수를 사용하지 않도록 설정하고 복구 경로가 둘 이상인 경우 모든 복구 경로가 복구 경로의 가장 긴 경로에 포함되어야 합니다. 그렇지 않으면 오류 메시지가 표시됩니다.

====
예를 들어 모든 복구 경로가 "foo/dir1/딥디르/myfile" 내에 있으므로 다음과 같은 복구 경로가 유효합니다.

* '/foo'
* "/foo/dir"
* '/foo/dir1/딥디더'
* '/foo/dir1/딥디르/myfile'


다음은 잘못된 복구 경로입니다.

* '/foo'
* "/foo/dir"
* '/foo/dir1/myfile'
* '/foo/dir2'
* '/foo/dir2/myfile'




 a| 
RECOVER_FULL_경로
 a| 
Y, N
 a| 
N
 a| 
전체 복구 경로에 DAR 이후에 복구된 해당 권한과 ACL이 포함되도록 지정합니다.

Direct 및 Enhanced_DAR_ENABLED도 활성화('Y'로 설정)해야 합니다. recover_full_paths가 Y로 설정된 경우 복구 경로는 원래 경로로 끝나야 합니다. 대상 볼륨에 디렉토리가 이미 있으면 해당 사용 권한 및 ACL이 테이프에서 복원되지 않습니다.



 a| 
업데이트
 a| 
Y, N
 a| 
Y를 누릅니다
 a| 
레벨 기반 증분 백업을 사용하도록 메타데이터 정보를 업데이트합니다.

|===


== SMTape에 지원되는 환경 변수입니다

|===
| 환경 변수 | 유효한 값 | 기본값 | 설명 


 a| 
base_date 를 선택합니다
 a| 
dump_date를 선택합니다
 a| 
'-1'
 a| 
증분 백업의 시작 날짜를 지정합니다.

base_date는 참조 스냅샷 식별자의 문자열 표현입니다. "base_date" 문자열을 사용하여 SMTape는 참조 스냅샷 복사본을 찾습니다.

기본 백업에는 base_date가 필요하지 않습니다. 증분 백업의 경우 이전 기준 또는 증분 백업의 DUMP_DATE 변수 값이 기본_DATE 변수에 할당됩니다.

백업 애플리케이션은 이전 SMTape 기준 또는 증분 백업에서 DUMP_DATE 값을 할당합니다.



 a| 
dump_date 를 참조하십시오
 a| 
RETURN_VALUE'입니다
 a| 
"없음"
 a| 
SMTape 백업이 끝나면 dump_date에 해당 백업에 사용되는 스냅샷 복사본을 식별하는 문자열 식별자가 포함됩니다. 이 스냅샷 복사본을 후속 증분 백업을 위한 참조 스냅샷 복사본으로 사용할 수 있습니다.

dump_date의 결과 값은 후속 증분 백업의 base_date 값으로 사용됩니다.



 a| 
SMTape_backup_set_ID입니다
 a| 
'트링'
 a| 
"없음"
 a| 
기본 백업과 관련된 증분 백업의 시퀀스를 식별합니다.

백업 세트 ID는 기본 백업 중에 생성되는 128비트 고유 ID입니다. 백업 애플리케이션은 증분 백업 중에 이 ID를 'MTAPE_BACKUP_SET_ID' 변수에 대한 입력으로 할당합니다.



 a| 
SMTape_snapshot_name입니다
 a| 
볼륨에서 사용 가능한 모든 유효한 스냅샷 복사본
 a| 
유효하지 않습니다
 a| 
SMTAPE_SNAPSHOT_NAME 변수가 스냅샷 복사본으로 설정되면 해당 스냅샷 복사본과 이전 스냅샷 복사본이 테이프에 백업됩니다.

증분 백업의 경우 이 변수는 증분 스냅샷 복사본을 지정합니다. base_date 변수는 기본 스냅샷 복사본을 제공합니다.



 a| 
SMTape_delete_snapshot
 a| 
Y, N
 a| 
N
 a| 
SMTape에서 자동으로 생성된 스냅샷 복사본의 경우 SMTAPE_DELETE_SNAPSHOT 변수가 'Y'로 설정되어 있으면 백업 작업이 완료된 후 SMTape에서 이 스냅샷 복사본을 삭제합니다. 그러나 백업 애플리케이션에서 생성한 스냅샷 복사본은 삭제되지 않습니다.



 a| 
SMTape_break_mirror입니다
 a| 
Y, N
 a| 
N
 a| 
SMTAPE_break_mirror 변수가 Y로 설정되면 성공한 복구 후 dP 유형의 볼륨이 RW 볼륨으로 변경됩니다.

|===