---
permalink: tape-backup/ndmp-concept.html 
sidebar: sidebar 
keywords: ncmp, considerations, using, service, storage, system 
summary: 스토리지 시스템에서 NDMP 서비스를 시작할 때는 여러 가지 고려 사항을 고려해야 합니다. 
---
= NDMP를 사용할 때의 고려 사항
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
스토리지 시스템에서 NDMP 서비스를 시작할 때는 여러 가지 고려 사항을 고려해야 합니다.

* 각 노드는 연결된 테이프 드라이브를 사용하여 최대 16개의 동시 백업, 복원 또는 2개의 조합을 지원합니다.
* NDMP 서비스는 NDMP 백업 애플리케이션의 요청에 따라 파일 기록 데이터를 생성할 수 있습니다.
+
파일 기록은 백업 응용 프로그램에서 백업 이미지에서 선택한 데이터 하위 집합을 최적의 상태로 복구하는 데 사용됩니다. 파일 기록 생성 및 처리는 스토리지 시스템과 백업 애플리케이션 모두에 시간이 많이 걸리고 CPU가 많이 사용될 수 있습니다.

+
[NOTE]
====
SMTape는 파일 기록을 지원하지 않습니다.

====
+
전체 백업 이미지가 복구될 재해 복구에 대해 데이터 보호가 구성된 경우 파일 기록 생성을 비활성화하여 백업 시간을 줄일 수 있습니다. NDMP 파일 기록 생성을 해제할 수 있는지 확인하려면 백업 애플리케이션 설명서를 참조하십시오.

* NDMP에 대한 방화벽 정책은 모든 LIF 유형에서 기본적으로 사용하도록 설정됩니다.
* 노드 범위의 NDMP 모드에서 FlexVol 볼륨을 백업하려면 백업 애플리케이션을 사용하여 볼륨을 소유하는 노드에서 백업을 시작해야 합니다.
+
그러나 노드 루트 볼륨은 백업할 수 없습니다.

* 방화벽 정책에서 허용하는 한 모든 LIF에서 NDMP 백업을 수행할 수 있습니다.
+
데이터 LIF를 사용하는 경우 페일오버에 대해 구성되지 않은 LIF를 선택해야 합니다. NDMP 작업 중에 데이터 LIF가 페일오버되면 NDMP 작업이 실패하고 다시 실행해야 합니다.

* NDMP 모드 및 SVM(Storage Virtual Machine) 범위의 NDMP 모드(CAB 확장 지원 안 함)에서는 NDMP 데이터 연결이 NDMP 제어 연결과 동일한 LIF를 사용합니다.
* LIF 마이그레이션 중에는 지속적인 백업 및 복원 작업이 중단됩니다.
+
LIF 마이그레이션 후에 백업 및 복원 작업을 시작해야 합니다.

* NDMP 백업 경로는 '_/vserver_name/volume_name/path_name_' 형식입니다.
+
'_path_name_'은(는) 선택 사항이며 디렉토리, 파일 또는 스냅샷 복사본의 경로를 지정합니다.

* 덤프 엔진을 사용하여 SnapMirror 대상을 테이프에 백업하는 경우 볼륨의 데이터만 백업됩니다.
+
그러나 SMTape를 사용하여 SnapMirror 대상을 테이프에 백업하는 경우 메타데이터도 백업됩니다. SnapMirror 관계 및 관련 메타데이터는 테이프에 백업되지 않습니다. 따라서 복원 중에는 해당 볼륨의 데이터만 복원되지만 연결된 SnapMirror 관계는 복원되지 않습니다.



.관련 정보
xref:cluster-aware-backup-extension-concept.adoc[Cluster Aware Backup 확장의 기능]

link:../concepts/index.html["ONTAP 개념"]

link:../system-admin/index.html["시스템 관리"]
