---
permalink: tape-backup/options-ndmpcopy-command-reference.html 
sidebar: sidebar 
keywords: ndmpcopy, command, tranfer, data, nodeshell 
summary: ndmpcopy 명령에 사용할 수 있는 옵션을 이해하여 데이터를 성공적으로 전송해야 합니다. 
---
= ndmpcopy 명령에 대한 옵션입니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
데이터를 성공적으로 전송하려면 ndmpcopy nodesell 명령에 사용할 수 있는 옵션을 이해해야 합니다.

다음 표에는 사용 가능한 옵션이 나와 있습니다. 자세한 내용은 노데스쉘을 통해 제공되는 ndmpcopy man 페이지를 참조하십시오.

|===
| 옵션을 선택합니다 | 설명 


 a| 
'-sa''사용자 이름:['암호']
 a| 
이 옵션은 소스 스토리지 시스템에 접속할 소스 인증 사용자 이름과 암호를 설정합니다. 필수 옵션입니다.

admin 권한이 없는 사용자의 경우 시스템에서 생성한 NDMP 관련 암호를 지정해야 합니다. admin 및 non-admin 사용자 모두 시스템에서 생성한 암호는 필수입니다.



 a| 
'-da''사용자 이름':['암호']
 a| 
이 옵션은 대상 스토리지 시스템에 접속하기 위한 대상 인증 사용자 이름 및 암호를 설정합니다. 필수 옵션입니다.



 a| 
'-st'{'md5'|'text'}
 a| 
이 옵션은 소스 스토리지 시스템에 접속할 때 사용할 소스 인증 유형을 설정합니다. 이 옵션은 필수 옵션이므로 사용자는 "text" 또는 "md5" 옵션을 제공해야 합니다.



 a| 
``dt’{'md5'|'text'}
 a| 
이 옵션은 대상 스토리지 시스템에 접속할 때 사용할 대상 인증 유형을 설정합니다.



 a| 
'-l'
 a| 
이 옵션은 지정된 레벨 값으로 전송에 사용되는 덤프 레벨을 설정합니다. 유효한 값은 0, 1, 9, 0은 전체 전송을 나타내고 1은 9, 0은 증분 전송을 지정합니다. 기본값은 0입니다.



 a| 
'-d'
 a| 
이 옵션을 사용하면 ndmpcopy 디버그 로그 메시지를 생성할 수 있습니다. ndmpcopy 디버그 로그 파일은 '/mroot/etc/log' 루트 볼륨에 있습니다. ndmpcopy 디버그 로그 파일 이름은 ndmpcopy.yyyymmdd 형식으로 되어 있습니다.



 a| 
"-f"
 a| 
이 옵션은 강제 모드를 활성화합니다. 이 모드에서는 7-Mode 볼륨의 루트에 있는 '/etc' 디렉토리에서 시스템 파일을 덮어쓸 수 있습니다.



 a| 
'-h'
 a| 
이 옵션은 도움말 메시지를 인쇄합니다.



 a| 
'-p'
 a| 
이 옵션은 소스 및 대상 인증에 대한 암호를 입력하라는 메시지를 표시합니다. 이 암호는 '-sa' 및 '-da' 옵션에 지정된 암호보다 우선합니다.

[NOTE]
====
이 옵션은 명령이 대화형 콘솔에서 실행 중인 경우에만 사용할 수 있습니다.

====


 a| 
'-exclude'
 a| 
이 옵션은 데이터 전송에 지정된 경로에서 지정된 파일 또는 디렉토리를 제외합니다. 이 값은 쉼표로 구분된 디렉터리 또는 파일 이름 목록(*.pst 또는 '*.txt')일 수 있습니다.

|===