---
permalink: tape-backup/snapshot-copies-during-smtape-backup-concept.html 
sidebar: sidebar 
keywords: snapshot, copy, smtape, backup, baseline, incremental, snapmirror 
summary: SMTape 기본 백업 및 증분 백업 중에 스냅샷 복사본이 어떻게 사용되는지 이해해야 합니다. 또한 SMTape를 사용하여 백업을 수행하는 동안 유의해야 할 고려 사항도 있습니다. 
---
= SMTape 백업 중에 스냅샷 복사본을 사용합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SMTape 기본 백업 및 증분 백업 중에 스냅샷 복사본이 어떻게 사용되는지 이해해야 합니다. 또한 SMTape를 사용하여 백업을 수행하는 동안 유의해야 할 고려 사항도 있습니다.



== 기본 백업

기본 백업을 수행하는 동안 테이프에 백업할 스냅샷 복사본의 이름을 지정할 수 있습니다. 스냅샷 복사본이 지정되지 않은 경우 볼륨의 액세스 유형(읽기/쓰기 또는 읽기 전용)에 따라 스냅샷 복사본이 자동으로 생성되거나 기존 스냅샷 복사본이 사용됩니다. 백업에 스냅샷 복사본을 지정하면 지정된 스냅샷 복사본 이전의 모든 스냅샷 복사본도 테이프에 백업됩니다.

백업에 대한 스냅샷 복사본을 지정하지 않으면 다음과 같은 작업이 수행됩니다.

* 읽기/쓰기 볼륨의 경우 스냅샷 복사본이 자동으로 생성됩니다.
+
새로 생성된 스냅샷 복사본과 이전 스냅샷 복사본이 모두 테이프에 백업됩니다.

* 읽기 전용 볼륨의 경우 최신 스냅샷 복사본을 포함한 모든 스냅샷 복사본이 테이프에 백업됩니다.
+
백업이 시작된 후 생성된 새 스냅샷 복사본은 백업되지 않습니다.





== 증분 백업

SMTape 증분 또는 차등 백업 작업의 경우 NDMP 호환 백업 애플리케이션이 스냅샷 복사본을 생성하고 관리합니다.

증분 백업 작업을 수행하는 동안에는 항상 스냅샷 복사본을 지정해야 합니다. 증분 백업 작업이 성공적으로 수행되려면 이전 백업 작업(기본 또는 증분)에서 백업된 스냅샷 복사본이 백업이 수행된 볼륨에 있어야 합니다. 이 백업된 스냅샷 복사본을 사용하려면 백업 정책을 구성하는 동안 이 볼륨에 할당된 스냅샷 정책을 고려해야 합니다.



== SnapMirror 대상에 대한 SMTape 백업 고려 사항

* 데이터 보호 미러 관계는 복제할 타겟 볼륨에 임시 스냅샷 복사본을 생성합니다.
+
이러한 Snapshot 복사본을 SMTape 백업에 사용해서는 안 됩니다.

* 동일한 볼륨에서 SMTape 백업 작업 중에 데이터 보호 미러 관계의 대상 볼륨에서 SnapMirror 업데이트가 발생하면 소스 볼륨에서 SMTape에 의해 백업된 스냅샷 복사본을 삭제하지 않아야 합니다.
+
백업 작업 중에 SMTape는 타겟 볼륨의 스냅샷 복사본을 잠그고 소스 볼륨에서 해당 스냅샷 복사본을 삭제하면 후속 SnapMirror 업데이트 작업이 실패합니다.

* 증분 백업 중에는 이러한 스냅샷 복사본을 사용하지 않아야 합니다.

