---
permalink: tape-backup/types-data-dump-engine-restores-concept.html 
sidebar: sidebar 
keywords: types, data, dump, engine, restores, disaster, controller, disruption, file, attribute 
summary: 재해 또는 컨트롤러 중단이 발생할 경우 덤프 엔진은 단일 파일에서 파일 속성, 전체 디렉토리에 이르기까지 백업한 모든 데이터를 여러 가지 방법으로 복구할 수 있습니다. 덤프 엔진이 복구할 수 있는 데이터의 유형과 복구 방법을 언제 사용해야 다운타임을 최소화할 수 있는지 알고 있습니다. 
---
= 덤프 엔진이 복원하는 데이터의 유형입니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
재해 또는 컨트롤러 중단이 발생할 경우 덤프 엔진은 단일 파일에서 파일 속성, 전체 디렉토리에 이르기까지 백업한 모든 데이터를 여러 가지 방법으로 복구할 수 있습니다. 덤프 엔진이 복구할 수 있는 데이터의 유형과 복구 방법을 언제 사용해야 다운타임을 최소화할 수 있는지 알고 있습니다.

데이터를 온라인 매핑된 LUN에 복원할 수 있습니다. 그러나 복구 작업이 완료될 때까지 호스트 애플리케이션이 이 LUN에 액세스할 수 없습니다. 복구 작업이 완료된 후 LUN 데이터의 호스트 캐시를 플러시하여 복구된 데이터에 대한 일관성을 제공해야 합니다.

덤프 엔진은 다음 데이터를 복구할 수 있습니다.

* 파일 및 디렉토리의 컨텐츠
* UNIX 파일 권한
* ACL
+
NTFS qtree 또는 볼륨에 대한 UNIX 파일 권한만 있는 파일을 복원하는 경우 파일에 Windows NT ACL이 없습니다. 스토리지 시스템은 Windows NT ACL을 생성할 때까지 이 파일에 대한 UNIX 파일 권한만 사용합니다.

+
[NOTE]
====
Data ONTAP 8.2를 실행하는 스토리지 시스템에서 백업된 ACL을 ACE 제한이 1,024 이하인 Data ONTAP 8.1.x 및 이전 버전의 스토리지 시스템으로 복원하는 경우 기본 ACL이 복원됩니다.

====
* Qtree 정보
+
qtree 정보는 qtree가 볼륨의 루트에 복원되는 경우에만 사용됩니다. Qtree 정보는 "/vs1/vol1/subdir/lowerdir" 같은 하위 디렉토리로 qtree가 복원되고 qtree가 아닌 경우 사용되지 않습니다.

* 다른 모든 파일 및 디렉토리 속성
* Windows NT 스트림
* LUN을 클릭합니다
+
** LUN을 LUN으로 유지하려면 볼륨 레벨 또는 qtree 레벨로 복원해야 합니다.
+
디렉터리에 복원되면 유효한 메타데이터가 없기 때문에 파일로 복원됩니다.

** 7-Mode LUN은 ONTAP 볼륨에서 LUN으로 복구됩니다.


* 7-Mode 볼륨을 ONTAP 볼륨으로 복원할 수 있습니다.
* 대상 볼륨에 복원된 VM 정렬 파일은 대상 볼륨의 VM 정렬 속성을 상속합니다.
* 복구 작업의 대상 볼륨에 필수 잠금 또는 권장 잠금이 있는 파일이 있을 수 있습니다.
+
이러한 대상 볼륨에 대한 복구 작업을 수행하는 동안 덤프 엔진은 이러한 잠금을 무시합니다.


