---
permalink: tape-backup/workflow-task.html 
sidebar: sidebar 
keywords: perform, tape, backup, restore, flexvol, volume, ndmp, backup, application 
summary: NDMP 지원 백업 애플리케이션을 사용하여 테이프 백업 및 복구 작업을 수행할 수 있습니다. 
---
= 테이프 백업 및 복원 워크플로우
:icons: font
:imagesdir: ../media/


[role="lead"]
NDMP 지원 백업 애플리케이션을 사용하여 테이프 백업 및 복구 작업을 수행할 수 있습니다.

테이프 백업 및 복원 워크플로우는 테이프 백업 및 복원 작업 수행과 관련된 작업에 대한 개요를 제공합니다. 백업 및 복원 작업 수행에 대한 자세한 내용은 백업 애플리케이션 설명서를 참조하십시오.

.단계
. NDMP 지원 테이프 토폴로지를 선택하여 테이프 라이브러리 구성을 설정합니다.
. 스토리지 시스템에서 NDMP 서비스를 설정합니다.
+
NDMP 서비스는 노드 레벨 또는 SVM(스토리지 가상 시스템) 레벨에서 설정할 수 있습니다. 테이프 백업 및 복구 작업을 수행하도록 선택한 NDMP 모드에 따라 다릅니다.

. NDMP 옵션을 사용하여 스토리지 시스템의 NDMP를 관리합니다.
+
노드 레벨 또는 SVM 레벨에서 NDMP 옵션을 사용할 수 있습니다. 테이프 백업 및 복구 작업을 수행하도록 선택한 NDMP 모드에 따라 다릅니다.

+
'system services ndmp modify' 명령을 사용하거나 SVM 레벨에서 'vserver services ndmp modify' 명령을 사용하여 노드 레벨에서 NDMP 옵션을 수정할 수 있습니다. 이러한 명령에 대한 자세한 내용은 man 페이지를 참조하십시오.

. NDMP 지원 백업 애플리케이션을 사용하여 테이프 백업 또는 복구 작업을 수행합니다.
+
ONTAP는 테이프 백업 및 복구를 위해 덤프 엔진과 SMTape 엔진을 모두 지원합니다.

+
백업 애플리케이션(_Data Management Applications_or_DMA_라고도 함)을 사용하여 백업 또는 복구 작업을 수행하는 방법에 대한 자세한 내용은 백업 애플리케이션 설명서를 참조하십시오.



xref:common-ndmp-topologies-reference.adoc[일반적인 NDMP 테이프 백업 토폴로지]

xref:data-backup-dump-concept.adoc[FlexVol 볼륨에 대한 덤프 엔진 이해]
