---
permalink: software_setup/reference_commands_for_managing_ntp_servers.html 
sidebar: sidebar 
keywords: ontap, software, setup, commands, managing, symmetric, authentication, ntp, servers 
summary: 'ONTAP 9.5부터 NTP(네트워크 시간 프로토콜) 버전 3이 지원됩니다. NTPv3에는 SHA-1 키를 사용한 대칭 인증이 포함되어 있어 네트워크 보안을 강화합니다.' 
---
= NTP 서버에서 대칭 인증을 관리하는 명령입니다
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9.5부터 NTP(네트워크 시간 프로토콜) 버전 3이 지원됩니다. NTPv3에는 SHA-1 키를 사용한 대칭 인증이 포함되어 있어 네트워크 보안을 강화합니다.

[cols="2*"]
|===
| 수행할 작업... | 이 명령 사용... 


 a| 
대칭 인증 없이 NTP 서버를 구성합니다
 a| 
'cluster time-service ntp server create-server server_name



 a| 
대칭 인증을 사용하여 NTP 서버를 구성합니다
 a| 
'cluster time-service ntp server create-server_ip_address-key-id key_id



 a| 
기존 NTP 서버에 대해 대칭 인증을 설정합니다

필요한 키 ID를 추가하여 인증을 사용하도록 기존 NTP 서버를 수정할 수 있습니다
 a| 
'cluster time-service ntp server modify -server server_name -key-id key_id



 a| 
공유 NTP 키를 구성합니다
 a| 
'cluster time-service ntp key create-id shared_key_id-type shared_key_type-value shared_key_value'

* 참고: * 공유 키는 ID로 참조됩니다. ID, 유형 및 값은 노드와 NTP 서버 모두에서 동일해야 합니다



 a| 
알 수 없는 키 ID로 NTP 서버를 구성합니다
 a| 
'cluster time-service ntp server create-server_name-key-id key_id



 a| 
NTP 서버에 키 ID가 구성되지 않은 서버를 구성합니다.
 a| 
'cluster time-service ntp server create-server_name-key-id key_id

* 참고: * 키 ID, 유형 및 값은 NTP 서버에 구성된 키 ID, 유형 및 값과 동일해야 합니다.



 a| 
대칭 인증을 사용하지 않도록 설정합니다
 a| 
'cluster time-service ntp server modify -server server_name -authentication disabled'

|===