---
permalink: software_setup/reference_the_cluster_setup_worksheet.html 
sidebar: sidebar 
keywords: ontap, software, setup, cluster, worksheet, system, default, cluster, node, ntp, information feature, license 
summary: 클러스터 설정 워크시트를 사용하면 클러스터 설정 프로세스 중에 필요한 값을 기록할 수 있습니다. 기본값이 제공되는 경우 해당 값을 사용하거나 직접 입력할 수 있습니다. 
---
= 클러스터 설정 워크시트를 참조하십시오
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
클러스터 설정 워크시트를 사용하면 클러스터 설정 프로세스 중에 필요한 값을 기록할 수 있습니다. 기본값이 제공되는 경우 해당 값을 사용하거나 직접 입력할 수 있습니다.



== 시스템 기본값(네트워크 스위치를 사용하도록 구성된 클러스터의 경우)

시스템 기본값은 프라이빗 클러스터 네트워크의 기본값입니다. 이러한 기본값을 사용하는 것이 가장 좋습니다. 그러나 요구 사항을 충족하지 않는 경우에는 표를 사용하여 값을 기록할 수 있습니다.


NOTE: 각 클러스터 스위치는 9000 MTU 크기를 사용해야 합니다.

네트워크 스위치를 사용하여 연결된 클러스터의 시스템 기본값만 고려해야 합니다.

[cols="3*"]
|===
| 정보 유형 | 기본값 | 당신의 가치 


 a| 
전용 클러스터 네트워크 포트
 a| 
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-nmg/home.html["네트워크 및 LIF 관리"]
 a| 



 a| 
클러스터 네트워크 넷마스크입니다
 a| 
255.255.0.0
 a| 



 a| 
클러스터 인터페이스 IP 주소(각 노드의 각 클러스터 네트워크 포트에 대해) 각 노드의 IP 주소는 같은 서브넷에 있어야 합니다.
 a| 
169.254.x.x
 a| 

|===


== 클러스터 정보

[cols="2*"]
|===
| 정보 유형 | 당신의 가치 


 a| 
클러스터 이름 이름은 문자로 시작해야 하며 44자 미만이어야 합니다. 이름에는 다음과 같은 특수 문자가 포함될 수 있습니다.

'. '-', _'
 a| 



 a| 
클러스터 기본 라이센스 키 클러스터 기본 라이센스 키는 설치를 완료하는 데 필요하지 않습니다. 그러나 기능 라이센스를 설치하려면 먼저 설치해야 합니다.

클러스터 기본 라이센스 키를 찾으려면

. NetApp Support 사이트 로 이동합니다.
+
http://mysupport.netapp.com["NetApp 지원"]

. My Support * > * Software Licenses * 를 클릭합니다.

 a| 

|===


== 기능 라이센스 키

초기 또는 애드온 소프트웨어 주문에 대한 라이센스 키는 NetApp Support 사이트 * My Support * > * Software Licenses * 에서 찾을 수 있습니다.

[cols="2*"]
|===
| 정보 유형 | 당신의 가치 


 a| 
기능 라이센스 키
 a| 

|===


== 관리 스토리지 가상 시스템(SVM)

|===
| 정보 유형 | 당신의 가치 


 a| 
클러스터 관리자 암호입니다

클러스터 관리자에게 콘솔에 대한 액세스 권한을 부여하거나 보안 프로토콜을 통해 액세스하기 전에 클러스터가 필요로 하는 admin 계정의 암호입니다.

암호의 기본 규칙은 다음과 같습니다.

* 암호는 8자 이상이어야 합니다.
* 암호는 하나 이상의 문자와 숫자를 포함해야 합니다.

 a| 



 a| 
클러스터 관리 인터페이스 포트입니다

데이터 네트워크에 연결되어 클러스터 관리자가 클러스터를 관리할 수 있도록 하는 물리적 포트입니다.
 a| 



 a| 
클러스터 관리 인터페이스 IP 주소입니다

클러스터 관리 인터페이스의 고유 IPv4 또는 IPv6 주소입니다. 클러스터 관리자는 이 주소를 사용하여 admin SVM에 액세스하고 클러스터를 관리합니다. 일반적으로 이 주소는 데이터 네트워크에 있어야 합니다.

조직의 IP 주소 할당 담당자로부터 이 IP 주소를 얻을 수 있습니다.

예: 192.0.2.66
 a| 



 a| 
클러스터 관리 인터페이스 넷마스크(IPv4)

클러스터 관리 네트워크에서 유효한 IPv4 주소 범위를 정의하는 서브넷 마스크입니다.

예: 255.255.255.0
 a| 



 a| 
클러스터 관리 인터페이스 넷마스크 길이(IPv6)

클러스터 관리 인터페이스에서 IPv6 주소를 사용하는 경우 이 값은 클러스터 관리 네트워크에서 유효한 IPv6 주소 범위를 정의하는 접두사 길이를 나타냅니다.

예: 64
 a| 



 a| 
클러스터 관리 인터페이스의 기본 게이트웨이입니다

클러스터 관리 네트워크의 라우터에 대한 IP 주소입니다.
 a| 



 a| 
DNS 도메인 이름입니다

네트워크 DNS 도메인의 이름입니다.

도메인 이름은 영숫자로 구성되어야 합니다. 여러 DNS 도메인 이름을 입력하려면 각 이름을 쉼표 또는 공백으로 구분합니다.
 a| 



 a| 
네임 서버 IP 주소

DNS 이름 서버의 IP 주소입니다. 각 주소를 쉼표 또는 공백으로 구분합니다.
 a| 

|===


== 노드 정보(클러스터의 각 노드에 대해)

[cols="2*"]
|===
| 정보 유형 | 당신의 가치 


 a| 
컨트롤러의 물리적 위치입니다

컨트롤러의 물리적 위치에 대한 설명입니다. 클러스터에서 이 노드를 찾을 위치를 식별하는 설명을 사용하십시오(예: "'Lab 5, Row 7, Rack B').
 a| 



 a| 
노드 관리 인터페이스 포트입니다

노드 관리 네트워크에 연결되어 있고 클러스터 관리자가 노드를 관리할 수 있도록 하는 물리적 포트입니다.
 a| 



 a| 
노드 관리 인터페이스 IP 주소 관리 네트워크의 노드 관리 인터페이스에 대한 고유한 IPv4 또는 IPv6 주소입니다. 노드 관리 인터페이스 포트를 데이터 포트로 정의한 경우 이 IP 주소는 데이터 네트워크에서 고유한 IP 주소여야 합니다.

조직의 IP 주소 할당 담당자로부터 이 IP 주소를 얻을 수 있습니다.

예: 192.0.2.66
 a| 



 a| 
노드 관리 인터페이스 넷마스크(IPv4) 노드 관리 네트워크에서 유효한 IP 주소 범위를 정의하는 서브넷 마스크입니다.

노드 관리 인터페이스 포트를 데이터 포트로 정의한 경우 넷마스크는 데이터 네트워크의 서브넷 마스크입니다.

예: 255.255.255.0
 a| 



 a| 
노드 관리 인터페이스 넷마스크 길이(IPv6) 노드 관리 인터페이스에서 IPv6 주소를 사용하는 경우 이 값은 노드 관리 네트워크에서 유효한 IPv6 주소 범위를 정의하는 접두사 길이를 나타냅니다.

예: 64
 a| 



 a| 
노드 관리 인터페이스의 기본 게이트웨이입니다

노드 관리 네트워크의 라우터에 대한 IP 주소입니다.
 a| 

|===


== NTP 서버 정보입니다

[cols="2*"]
|===
| 정보 유형 | 당신의 가치 


 a| 
NTP 서버 주소입니다

사이트에 있는 NTP(Network Time Protocol) 서버의 IP 주소입니다. 이러한 서버는 클러스터 전체에서 시간을 동기화하는 데 사용됩니다.
 a| 

|===