---
permalink: software_setup/task_join_remaining_nodes_to_the_cluster.html 
sidebar: sidebar 
keywords: ontap, software, setup, join, remaining, nodes, cluster, HA, high availability, autosupport 
summary: 새 클러스터를 생성한 후 클러스터 설정 마법사를 사용하여 나머지 각 노드를 한 번에 하나씩 클러스터에 결합할 수 있습니다. 이 마법사를 사용하면 각 노드의 노드 관리 인터페이스를 구성할 수 있습니다. 
---
= 나머지 노드를 클러스터에 연결합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
새 클러스터를 생성한 후 클러스터 설정 마법사를 사용하여 나머지 각 노드를 한 번에 하나씩 클러스터에 결합할 수 있습니다. 이 마법사를 사용하면 각 노드의 노드 관리 인터페이스를 구성할 수 있습니다.


NOTE: 이 절차는 FAS, AFF 및 현재 ASA 시스템에 적용됩니다. ASA R2 시스템(ASA A1K, ASA A70 또는 ASA A90)이 있는 경우 에 따라 link:https://docs.netapp.com/us-en/asa-r2/install-setup/initialize-ontap-cluster.html["수행할 수 있습니다"^]시스템 관리자를 사용하여 ONTAP 클러스터를 설정합니다. ASA R2 시스템은 SAN 전용 고객을 대상으로 단순화된 ONTAP 환경을 제공합니다.

하나의 클러스터에 두 개의 노드를 결합할 경우 고가용성(HA) 쌍이 생성됩니다. 4개의 노드를 결합하는 경우 2개의 HA 쌍을 생성합니다. HA에 대한 자세한 내용은 를 link:../high-availability/index.html["HA에 대해 알아보십시오"]참조하십시오.

한 번에 하나의 노드만 클러스터에 결합할 수 있습니다. 클러스터에 노드를 연결하려면 해당 노드에 대해 연결 작업을 완료해야 하며, 다음 노드에 가입하기 전에 노드가 클러스터의 일부여야 합니다.

* 모범 사례: * 24개 이하의 NL-SAS 드라이브에 FAS2720을 사용하는 경우 스토리지 구성 기본값이 Active/Passive로 설정되어 성능을 최적화할 수 있는지 확인해야 합니다. 자세한 내용은 의 설명서를 link:../disks-aggregates/setup-active-passive-config-root-data-task.html["루트 데이터 파티셔닝을 사용하여 노드에 대한 액티브-패시브 구성을 설정합니다"]참조하십시오.

. 클러스터에 참여하려는 노드에 로그인합니다.
+
콘솔에서 클러스터 설정 마법사가 시작됩니다.

+
[listing]
----
Welcome to the cluster setup wizard....
----
. AutoSupport 설명을 확인합니다.
+

NOTE: AutoSupport는 기본적으로 사용하도록 설정되어 있습니다.

+
[listing]
----
Type yes to confirm and continue {yes}: yes
----
. 화면의 지침에 따라 노드에 IP 주소를 할당합니다.
+
ONTAP 9.13.1 부터는 A800 및 FAS8700 플랫폼에서 관리 LIF에 IPv6 주소를 할당할 수 있습니다. ONTAP 9.13.1 이전 릴리즈 또는 다른 플랫폼에서 9.13.1 이상인 경우 관리 LIF에 IPv4 주소를 할당한 다음 클러스터 설정을 완료한 후 IPv6로 변환해야 합니다.

. 계속하려면 * Enter * 를 누르십시오.
+
[listing]
----
Do you want to create a new cluster or join an existing cluster? {create, join}:
----
. 클러스터에 노드를 가입시킵니다
. 화면의 지침에 따라 노드를 설정하고 클러스터에 연결합니다.
. 설치가 완료된 후 노드가 정상 상태이며 클러스터에 참여할 자격이 있는지 'cluster show'인지 확인합니다
+
다음 예에서는 두 번째 노드(cluster1-02)가 클러스터에 결합된 후의 클러스터를 보여 줍니다.

+
[listing]
----
cluster1::> cluster show
Node                  Health  Eligibility
--------------------- ------- ------------
cluster1-01           true    true
cluster1-02           true    true
----
+
클러스터 설정 마법사를 사용하면 클러스터 설정 명령을 사용하여 admin SVM 또는 node SVM에 대해 입력한 값을 변경할 수 있습니다.

. 나머지 각 노드에 대해 이 작업을 반복합니다.


.작업을 마친 후
필요한 경우 link:convert-ipv4-to-ipv6-task.html["IPv4에서 IPv6로 변환"].
