---
permalink: asa/overview.html 
sidebar: sidebar 
keywords: all san array, asa, san, array, software, configuration, configure, configuring, setup, set up, limitations, restrictions, nvme, mcc ip, persistent ports, host, settings, utilities, ways to identify 
summary: 다음 절차에 따라 System Manager를 사용하여 모든 SAN 어레이를 구성하십시오. 
---
= 모든 SAN 어레이 소프트웨어 구성 개요
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
ONTAP 9.7부터 NetApp All SAN 어레이(ASA)를 사용할 수 있습니다. ASA는 검증된 AFF NetApp 플랫폼을 기반으로 하는 All-Flash SAN 전용 솔루션입니다.

ASA 플랫폼은 2노드 스위치 클러스터 또는 스위치가 없는 클러스터에서 사용할 수 있으며 FC 또는 iSCSI에 맞게 구성할 수 있으며 다중 경로에 대칭 액티브-액티브를 사용할 수 있습니다. 모든 경로가 액티브/최적화되어 있으므로 스토리지 페일오버 시 호스트는 I/O를 재개하기 위해 페일오버 경로의 ALUA 전환을 기다릴 필요가 없습니다 그러면 페일오버 시간이 단축됩니다.

link:http://www.netapp.com/us/media/tr-4515.pdf["NetApp 기술 보고서 4515: ONTAP AFF All SAN 어레이 시스템"^]
 link:http://www.netapp.com/us/media/tr-4080.pdf["NetApp 기술 보고서 4080: 확장형 SAN ONTAP 9에 대한 모범 사례"^]



== ASA를 설정합니다

모든 SAN 어레이(ASA)는 비 ASA 시스템과 동일한 설정 절차를 따릅니다.

System Manager는 클러스터를 초기화하고, 로컬 계층을 생성하고, 프로토콜을 구성하고, ASA에 대한 스토리지를 프로비저닝하는 데 필요한 절차를 안내합니다. 의 단계를 참조하십시오 xref:task_configure_ontap.html[ONTAP를 구성합니다].



== ASA 호스트 설정 및 유틸리티

모든 SAN 어레이(ASA)를 설정하기 위한 호스트 설정은 다른 모든 SAN 호스트의 호스트 설정과 동일합니다.

를 다운로드할 수 있습니다 link:https://mysupport.netapp.com/NOW/cgi-bin/software["NetApp 호스트 유틸리티 소프트웨어"^] 지원 사이트의 특정 호스트에 대해.



== ASA 시스템을 식별하는 방법

ASA 시스템은 System Manager를 사용하거나 CLI(ONTAP Command Line Interface)를 사용하여 식별할 수 있습니다.

System Manager 대시보드에서 * 클러스터 > 개요 * 를 클릭한 다음 시스템 노드를 선택합니다. Personality * 는 * All SAN Array * 로 표시됩니다.

CLI에서 'config show' 명령어를 사용할 수 있다. "All SAN Array" 값은 ASA 시스템의 경우 TRUE를 반환합니다.
