---
sidebar: sidebar 
permalink: high-availability/ha_automatic_giveback_commands.html 
keywords: ontap, high, availability, ha, pair, automatic, giveback, commands 
summary: 자동 반환 명령 
---
= 자동 반환 명령
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
경우에 따라 ONTAP 명령을 사용하여 자동 반환 설정을 관리해야 할 수도 있습니다.

|===


| 원하는 작업 | 이 명령 사용... 


 a| 
반환 노드가 부팅되고, Giveback 대기 상태에 도달하고, Auto Giveback 기간이 만료되기 전에 지연이 발생하는 즉시 반환이 발생하도록 자동 반환 설정

기본 설정은 TRUE입니다.
 a| 
'Storage failover modify‑node_nodename_‑auto-반환 true'



 a| 
자동 반환 비활성화 기본 설정은 TRUE입니다.

* 참고: * 이 매개 변수를 false로 설정하면 패닉 시 테이크오버 후 자동 반환이 비활성화되지 않습니다. 패닉 시 테이크오버 후 자동 반환은 ``auto-반환-after-패닉" 매개 변수를 false로 설정하여 비활성화해야 합니다.
 a| 
'Storage failover modify‑node_nodename_‑auto-반환 false'



 a| 
패닉 상태에서 테이크오버 후 자동 반환을 사용하지 않도록 설정합니다(이 설정은 기본적으로 활성화됨).
 a| 
'Storage failover modify‑node_nodename_‑auto‑반환‑after‑panic false'



 a| 
지정된 시간(초) 동안 자동 반환 지연(기본값 600) 이 옵션은 자동 반환을 수행하기 전에 노드가 테이크오버 상태로 유지되는 최소 시간을 결정합니다.
 a| 
'Storage failover modify‑node_nodename_‑delay‑seconds_seconds_'

|===


== 스토리지 페일오버 수정 명령의 변화가 자동 반환에 미치는 영향

자동 반환 작업은 스토리지 페일오버 수정 명령의 매개 변수를 구성하는 방법에 따라 달라집니다.

다음 표에는 패닉이 발생하지 않는 테이크오버 이벤트에 적용되는 스토리지 페일오버 수정 명령 매개 변수가 나와 있습니다.

|===


| 매개 변수 | 기본 설정 


 a| 
'-auto-반환_true_|_false_'
 a| 
'_TRUE_'



 a| 
'-delay-seconds_integer_(초)'
 a| 
600



 a| 
'-onreboot_true_|_false_'
 a| 
'_TRUE_'

|===
다음 표에서는 '-onreboot' 및 '-auto-반환' 매개 변수의 조합이 패닉으로 인해 발생하지 않은 테이크오버 이벤트의 자동 반환에 미치는 영향을 설명합니다.

|===


| '스토리지 페일오버 수정' 매개 변수가 사용됩니다 | 테이크오버 원인 | 자동 반환이 발생합니까? 


 a| 
'-onreboot_true_'

'-auto-반환_true_'
| reboot 명령 | 예 


| 서비스 프로세서에서 실행된 중지 명령 또는 전원 사이클 작업입니다 | 예 


 a| 
'-onreboot_true_'

'-auto-반환_false_'
| reboot 명령 | 예 


| 서비스 프로세서에서 실행된 중지 명령 또는 전원 사이클 작업입니다 | 예 


 a| 
'-onreboot_false_'

'-auto-반환_true_'
| reboot 명령 | 해당 없음 이 경우 테이크오버 발생하지 않습니다 


| 서비스 프로세서에서 실행된 중지 명령 또는 전원 사이클 작업입니다 | 예 


 a| 
'-onreboot_false_'

'-auto-반환_false_'
| reboot 명령 | 아니요 


| 서비스 프로세서에서 실행된 중지 명령 또는 전원 사이클 작업입니다 | 아니요 
|===
'-auto-반환' 매개 변수는 패닉 후 반환과 다른 모든 자동 테이크오버 후 반환을 제어합니다. 만약 `-onreboot' 매개변수가 'true'로 설정되어 있고 재부팅으로 인해 테이크오버가 발생하는 경우 '-auto-반환' 매개 변수가 'true'로 설정되었는지 여부에 상관없이 자동 반환이 항상 수행됩니다.

'-onreboot' 매개 변수는 ONTAP에서 실행된 재부팅 및 중지 명령에 적용됩니다. `-onreboot' 매개 변수가 false로 설정되면 노드 재부팅의 경우 테이크오버가 발생하지 않습니다. 따라서 '-auto-반환' 매개 변수가 true로 설정되었는지 여부에 관계없이 자동 반환이 발생할 수 없습니다. 클라이언트 중단이 발생합니다.



== 패닉 상황에 적용되는 자동 반환 매개 변수 조합의 효과

다음 표에는 패닉 상황에 적용되는 '스토리지 페일오버 수정' 명령 매개 변수가 나와 있습니다.

|===


| 매개 변수 | 기본 설정 


 a| 
'-onpanic_true|false_'
 a| 
'_TRUE_'



 a| 
'-auto-반환-after-panic_true|false_'

(권한: 고급)
 a| 
'_TRUE_'



 a| 
'-auto-반환_true|false_'
 a| 
'_TRUE_'

|===
다음 표에서는 '스토리지 페일오버 수정' 명령의 매개 변수 조합이 패닉 상황에서 자동 반환에 미치는 영향에 대해 설명합니다.


NOTE: 노드 패닉이 발생하는 다른 이유로 인해 테이크오버 발생할 수 있음을 유의하십시오. 예를 들어 노드에서 패닉이 발생하지만 파트너가 패닉 패킷을 수신하지 못하는 경우 파트너는 하트비트 손실 테이크오버를 수행할 수 있습니다. 이 경우 '-auto-반환-after-패닉' 매개 변수에 의해 반환이 제어되지 않고 대신 '-onfailure' 매개 변수에 의해 제어될 수 있습니다.

[cols="60,40"]
|===


| '스토리지 페일오버' 매개 변수가 사용됩니다 | 패닉 후 자동 반환이 발생합니까? 


| `-onpanic true '-auto-반환 true '-auto-반환-after-panic true' | 예 


| `-on패닉 true '-auto-반환 true '-auto-반환-after-panic false' | 아니요 


| `-on패닉 true '- auto-반환 false '- auto-반환-after-panic true' | 예 


| '-on패닉 true'- 자동 반환 false'- 자동 반환 -패닉 후 false | 아니요 


| '-on패닉 false' -onpanic이 false로 설정되어 있으면 '-auto-반환' 또는 '-auto-반환-after-패닉'에 설정된 값에 관계없이 Takeover/Giveback이 수행되지 않습니다 | 아니요 
|===
[NOTE]
====
기본 설정을 수정할 경우 위의 표와 같이 '-on패닉' 매개 변수가 자동 반환을 재정의할 수 있습니다.

* '-on패닉' 매개 변수가 'true'로 설정되어 있으면 '-auto-반환' 및 '-auto-반환-after-패닉' 매개 변수의 기본 설정을 변경하지 않은 경우 패닉이 발생하면 자동 반환이 항상 수행됩니다. 이 두 매개 변수가 모두 기본 매개 변수('true')에서 'false'로 변경되면 '-onpanic' 매개 변수가 'true'로 설정되어 있어도 패닉 후에 자동 반환이 발생하지 않습니다.
* onpanic 매개 변수가 false로 설정되어 있으면 테이크오버가 발생하지 않고 클라이언트가 ONTAP 데이터 서비스에 지장을 줍니다. 따라서 '-auto-반환-after-panic' 매개 변수가 'true'로 설정되어 있어도 자동 반환이 발생할 수 없습니다.


====
[NOTE]
====
* 노드 패닉 중에 다른 이유로 테이크오버 발생할 수 있습니다. 이 경우 '자동 반환 후 - 패닉' 설정으로 인해 반환이 제어되지 않습니다.
* '-on패닉' 매개 변수가 'true'로 설정되어 있으면 '-auto-반환' 및 '-auto-반환-after-패닉' 매개 변수의 기본 설정을 변경하지 않은 경우 패닉이 발생하면 자동 반환이 항상 수행됩니다. 이 두 매개 변수가 모두 기본 매개 변수('true')에서 'false'로 변경되면 '-onpanic' 매개 변수가 'true'로 설정되어 있어도 패닉 후에 자동 반환이 발생하지 않습니다.
* on패닉 매개변수가 false로 설정되어 있으면 테이크오버가 수행되지 않습니다. 따라서 '-auto-반환-after-panic' 매개 변수가 'true'로 설정되어 있어도 자동 반환이 발생할 수 없습니다. 클라이언트 중단이 발생합니다.


====