---
sidebar: sidebar 
permalink: high-availability/ha_manual_giveback.html 
keywords: ontap, high, availability, ha, pair, manual, giveback, interrupted, vetoed, veto, commands, performing, perform 
summary: 정상적인 반환, 파트너 노드에서 프로세스를 종료하는 반환 또는 강제 반환을 수행할 수 있습니다. 
---
= 수동 반환 명령
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
정상적인 반환, 파트너 노드에서 프로세스를 종료하는 반환 또는 강제 반환을 수행할 수 있습니다.


NOTE: 기브백을 수행하기 전에 에 설명된 대로 페일오버된 시스템에서 장애가 발생한 드라이브를 제거해야 합니다 link:../disks-aggregates/index.html["디스크 및 애그리게이트 관리"].



== 반환이 중단된 경우

반환 프로세스 중 테이크오버 노드에 장애 또는 정전이 발생하는 경우 해당 프로세스가 중지되고 테이크오버 노드가 테이크오버 모드로 되돌아가 장애가 복구되거나 전원이 복원됩니다.

그러나 오류가 발생한 반환 단계에 따라 다릅니다. 루트 애그리게이트를 반환한 후 부분 반환 상태 중에 노드에서 장애가 발생하거나 정전이 발생한 경우 테이크오버 모드로 돌아오지 않습니다. 대신 노드가 부분 반환 모드로 돌아갑니다. 이 경우 반환 작업을 반복하여 프로세스를 완료합니다.



== Giveback에 거부되는 경우

기브백이 거부되면 EMS 메시지를 점검하여 원인을 확인해야 합니다. 이유나 이유에 따라, 거부권을 안전하게 무시할 수 있는지 여부를 결정할 수 있습니다.

'Storage failover show-반환' 명령은 반환 진행률을 표시하고 반환에 거부된 하위 시스템이 있는 경우 이를 표시합니다. 소프트 베인을 무시할 수 있지만, 하드 베인을 강제해도 무시할 수 없습니다. 다음 표에는 재지정할 수 없는 소프트 베트레인이 권장 해결 방법과 함께 요약되어 있습니다.

다음 명령을 사용하여 반환 거부의 EMS 세부 정보를 검토할 수 있습니다.

'이벤트 로그 show-node * -event gb *'



== 루트 애그리게이트의 반환

이러한 거부는 집계 재배치 작업에 적용되지 않습니다.

[cols="35,65"]
|===


| 하위 시스템 모듈을 확인합니다 | 해결 방법 


 a| 
vFiler_low_level입니다
 a| 
거부권을 유발한 SMB 세션을 종료하거나, 열려 있는 세션을 설정한 SMB 애플리케이션을 종료합니다.

이 거부권을 무시하면 SMB를 사용하는 응용 프로그램이 갑자기 연결을 끊고 데이터를 잃게 될 수 있습니다.



 a| 
디스크 검사
 a| 
반환하기 전에 모든 오류 또는 바이패스된 디스크를 제거해야 합니다. 디스크가 삭제 중이면 작업이 완료될 때까지 기다려야 합니다.

이 거부권을 덮어쓰면 예약 충돌 또는 액세스할 수 없는 디스크로 인해 애그리게이트 또는 볼륨이 오프라인 상태가 되어 정전이 발생할 수 있습니다.

|===


== SFO 애그리게이트의 반환

이러한 거부는 집계 재배치 작업에 적용되지 않습니다.

[cols="35,65"]
|===


| 하위 시스템 모듈을 확인합니다 | 해결 방법 


 a| 
잠금 관리자
 a| 
열린 파일이 있는 SMB 애플리케이션을 우아하게 종료하거나 이러한 볼륨을 다른 애그리게이트로 이동하십시오.

이 거부권을 무시하면 SMB 잠금 상태가 손실되어 중단 및 데이터 손실이 발생합니다.



 a| 
매니저 NDO 잠금
 a| 
잠금이 미러링될 때까지 기다립니다.

이 거부권을 무시하면 Microsoft Hyper-V 가상 시스템이 중단됩니다.



| RAID  a| 
EMS 메시지를 확인하여 거부의 원인을 파악합니다.

nvfile로 인해 거부권을 행사하는 경우 오프라인 볼륨과 애그리게이트를 온라인으로 전환합니다.

디스크 추가 또는 디스크 소유권 재할당 작업이 진행 중인 경우 완료될 때까지 기다립니다.

거부권이 애그리게이트 이름 또는 UUID 충돌로 인해 발생한 경우 문제를 해결하고 해결합니다.

거부권이 미러 재동기화, 미러 확인 또는 오프라인 디스크에 의한 것이라면 거부권을 무효화할 수 있으며 반환 후 작업이 다시 시작됩니다.



| 디스크 인벤토리  a| 
문제 해결을 통해 문제의 원인을 파악하고 해결합니다.

대상 노드에서 마이그레이션 중인 애그리게이트에 속한 디스크를 볼 수 없습니다.

액세스할 수 없는 디스크로 인해 애그리게이트 또는 볼륨에 액세스할 수 없습니다.



| 볼륨 이동 작업  a| 
문제 해결을 통해 문제의 원인을 파악하고 해결합니다.

이 거부권은 중요한 컷오버 단계에서 볼륨 이동 작업이 중단되는 것을 방지합니다. 컷오버 중에 작업이 중단되면 볼륨에 액세스할 수 없게 될 수 있습니다.

|===


=== 수동 반환을 수행하기 위한 명령입니다

유지 관리를 완료하거나 테이크오버 발생하는 문제를 해결한 후 HA 쌍의 노드에서 반환을 수동으로 시작하여 스토리지를 원래 소유자에게 반환할 수 있습니다.

|===


| 원하는 작업 | 이 명령 사용... 


 a| 
스토리지를 파트너 노드로 다시 제공합니다
| 'Storage failover 반환‑ofnode_nodename_' 


 a| 
파트너가 반환 모드를 대기 중인 상태가 아닌 경우에도 스토리지를 제공합니다
 a| 
'Storage failover sofnode_nodename_''‑Require‑PARTNER‑waiting false'

더 긴 클라이언트 중단을 허용할 수 없는 한 이 옵션을 사용하지 마십시오.



| 프로세스가 반환 작업을 거부하더라도 스토리지를 반환(강제 반환)  a| 
'Storage failover votmover-ofnode_nodename_''‑override‑vetoes true

이 옵션을 사용하면 클라이언트 중단 시간이 길어지거나, 반환 후 애그리게이트와 볼륨이 온라인으로 전환되지 않을 수 있습니다.



| CFO 애그리게이트(루트 애그리게이트)만 돌려줍니다.  a| 
'Storage failover 반환‑ofnode_nodename_'

``유일한 CFO”는 진실이라고 말했습니다



| 반환 명령을 실행한 후 반환 진행률을 모니터링합니다 | 'Storage failover show‑반환'을 참조하십시오 
|===