---
sidebar: sidebar 
permalink: high-availability/ha_monitor_an_ha_pair_overview.html 
keywords: ontap, high availability, ha, pair, monitor, hwassist 
summary: ONTAP 명령을 사용하여 HA 쌍의 상태를 모니터링할 수 있습니다. 
---
= HA 쌍 모니터링을 위한 명령입니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ONTAP 명령을 사용하여 HA 쌍의 상태를 모니터링할 수 있습니다. Takeover가 발생하는 경우 Takeover의 원인도 파악할 수 있습니다.

|===


| 확인합니다 | 이 명령을 사용합니다 


| 장애 조치가 설정되었는지 또는 발생했는지 여부 또는 장애 조치가 현재 가능하지 않은 이유 | '스토리지 페일오버 쇼' 


| 스토리지 페일오버 HA-모드 설정이 활성화된 노드를 확인합니다
노드가 스토리지 페일오버(HA 쌍) 구성에 참여하려면 이 값을 ha로 설정해야 합니다. | '스토리지 페일오버 표시 필드 모드' 


| 하드웨어 지원 테이크오버가 설정되었는지 여부 | 스토리지 페일오버 hwassist show 


| 발생한 하드웨어 지원 테이크오버 이벤트의 기록 | 스토리지 페일오버 hwassist 통계 표시 


| 파트너의 애그리게이트가 테이크오버 실행 노드로 이동될 때 테이크오버 작업의 진행률이 | '스토리지 페일오버 표시 - 테이크오버 


| 파트너 노드로 애그리게이트를 반환하는 반환 반환 작업의 진행률 | 'Storage failover show‑반환'을 참조하십시오 


| Takeover 또는 Giveback 작업 중 Aggregate가 홈인지 여부 | '집계 표시 필드 홈 ID, 소유자 ID, 집 이름, 소유자 이름'은 집입니다 


| 클러스터 HA 설정 여부(2노드 클러스터에만 적용) | 군산쇼 


| HA Pair의 구성 요소(HA 상태를 사용하는 시스템에서)의 HA 상태 | ha-config show 이것은 유지 관리 모드 명령이다. 
|===


== 스토리지 페일오버 show-type 명령으로 표시되는 노드 상태입니다

다음 목록은 'Storage failover show' 명령이 표시되는 노드에 대해 설명합니다.

|===


| 노드 상태 | 설명 


 a| 
PARTNER_NAME에 연결되었고 자동 테이크오버 비활성화됨
 a| 
HA 인터커넥트는 활성 상태이며 데이터를 파트너 노드로 전송할 수 있습니다. 파트너의 자동 테이크오버 기능이 해제됩니다.



 a| 
partner_name, Giveback of partner spare 디스크를 기다리는 중입니다.
 a| 
로컬 노드는 HA 인터커넥트를 통해 파트너 노드와 정보를 교환할 수 없습니다. 파트너에 대한 SFO 애그리게이트의 기브백이 완료되지만 파트너 스페어 디스크는 로컬 노드가 소유합니다.

* 자세한 내용은 'storage failover show-반환' 명령을 실행합니다.




 a| 
PARTNER_NAME을 기다리는 중입니다. 파트너 잠금 동기화를 기다리는 중입니다.
 a| 
로컬 노드는 HA 인터커넥트를 통해 파트너 노드와 정보를 교환할 수 없으며 파트너 잠금 동기화가 수행되기를 기다리고 있습니다.



 a| 
PARTNER_NAME을 기다리는 중입니다. 로컬 노드에서 클러스터 애플리케이션이 온라인 상태가 될 때까지 기다리는 중입니다.
 a| 
로컬 노드는 HA 인터커넥트를 통해 파트너 노드와 정보를 교환할 수 없으며 클러스터 애플리케이션이 온라인 상태로 전환되기를 기다리고 있습니다.



 a| 
Takeover 예약됨. 테이크오버 준비 과정에서 타겟 노드가 SFO 애그리게이트를 재배치하고,
 a| 
인수 처리가 시작되었습니다. 타겟 노드가 테이크오버 준비 과정에서 SFO 애그리게이트의 소유권을 재배치하고 있습니다.



 a| 
Takeover 예약됨. 타겟 노드가 테이크오버 준비 과정에서 SFO 애그리게이트를 재배치했습니다.
 a| 
인수 처리가 시작되었습니다. 타겟 노드가 테이크오버에 대비하여 SFO 애그리게이트의 소유권을 재배치했습니다.



 a| 
Takeover 예약됨. 로컬 노드에서 백그라운드 디스크 펌웨어 업데이트를 비활성화하기 위해 기다리는 중입니다. 노드에서 펌웨어 업데이트가 진행 중입니다.
 a| 
인수 처리가 시작되었습니다. 시스템에서 로컬 노드의 백그라운드 디스크 펌웨어 업데이트 작업이 완료될 때까지 기다리는 중입니다.



 a| 
테이크오버 준비 시 SFO 애그리게이트를 테이크오버로 재배치
 a| 
테이크오버에 대비하여 로컬 노드가 SFO 애그리게이트의 소유권을 테이크오버노드로 재배치하고 있습니다.



 a| 
SFO 애그리게이트를 재배치하여 노드를 인수했습니다. 노드가 테이크오버될 때까지 기다리는 중입니다.
 a| 
로컬 노드에서 페일오버된 노드로 SFO 애그리게이트의 소유권 재배치가 완료되었습니다. 테이크오버가 수행되는 동안 시스템이 테이크오버 대기 중입니다.



 a| 
SFO 애그리게이트를 partner_name에 재배치 중입니다. 로컬 노드에서 백그라운드 디스크 펌웨어 업데이트를 비활성화하기 위해 기다리는 중입니다. 노드에서 펌웨어 업데이트가 진행 중입니다.
 a| 
로컬 노드에서 페일오버된 노드로 SFO 애그리게이트의 소유권 재배치가 진행 중입니다. 시스템에서 로컬 노드의 백그라운드 디스크 펌웨어 업데이트 작업이 완료될 때까지 기다리는 중입니다.



 a| 
SFO 애그리게이트를 partner_name에 재배치 중입니다. PARTNER_NAME에서 백그라운드 디스크 펌웨어 업데이트를 비활성화하기 위해 기다리는 중입니다. 노드에서 펌웨어 업데이트가 진행 중입니다.
 a| 
로컬 노드에서 페일오버된 노드로 SFO 애그리게이트의 소유권 재배치가 진행 중입니다. 시스템에서 파트너 노드의 백그라운드 디스크 펌웨어 업데이트 작업이 완료되기를 기다리는 중입니다.



 a| 
PARTNER_NAME에 연결되었습니다. 이유 때문에 이전 테이크오버 시도가 중단되었습니다. 로컬 노드가 파트너의 일부 SFO 애그리게이트를 소유합니다. 나머지 애그리게이트를 테이크오버하려면 true로 설정된 ``우회 최적화' 매개 변수를 사용하여 파트너의 테이크오버 재발행하거나, 파트너 반환을 제출하십시오.
 a| 
HA 인터커넥트는 활성 상태이며 데이터를 파트너 노드로 전송할 수 있습니다. 이유 아래에 표시된 원인으로 인해 이전 테이크오버 시도가 중단되었습니다. 로컬 노드는 파트너의 SFO 애그리게이트 중 일부를 소유합니다.

* 파트너 노드의 테이크오버를 다시 발행하고‑Bypass‑optimization 매개 변수를 true 로 설정하여 나머지 SFO 애그리게이트를 테이크오버하거나, 파트너 반환에 대한 반환을 수행하십시오.




 a| 
PARTNER_NAME에 연결되었습니다. 이전 테이크오버 시도가 중단되었습니다. 로컬 노드가 파트너의 일부 SFO 애그리게이트를 소유합니다. 나머지 애그리게이트를 테이크오버하려면 true로 설정된 ``우회 최적화' 매개 변수를 사용하여 파트너의 테이크오버 재발행하거나, 파트너 반환을 제출하십시오.
 a| 
HA 인터커넥트는 활성 상태이며 데이터를 파트너 노드로 전송할 수 있습니다. 이전 테이크오버 시도가 중단되었습니다. 로컬 노드는 파트너의 SFO 애그리게이트 중 일부를 소유합니다.

* 파트너 노드의 테이크오버를 다시 발행하고‑Bypass‑optimization 매개 변수를 true 로 설정하여 나머지 SFO 애그리게이트를 테이크오버하거나, 파트너 반환에 대한 반환을 수행하십시오.




 a| 
PARTNER_NAME을 기다리는 중입니다. 이유 때문에 이전 테이크오버 시도가 중단되었습니다. 로컬 노드가 파트너의 일부 SFO 애그리게이트를 소유합니다. 나머지 애그리게이트를 테이크오버하려면 "‑Bypass-optimization" 매개 변수를 true로 설정하여 파트너의 테이크오버 또는 파트너의 반환을 발행하십시오.
 a| 
로컬 노드는 HA 인터커넥트를 통해 파트너 노드와 정보를 교환할 수 없습니다. 이유 아래에 표시된 원인으로 인해 이전 테이크오버 시도가 중단되었습니다. 로컬 노드는 파트너의 SFO 애그리게이트 중 일부를 소유합니다.

* 파트너 노드의 테이크오버를 다시 발행하고‑Bypass‑optimization 매개 변수를 true 로 설정하여 나머지 SFO 애그리게이트를 테이크오버하거나, 파트너 반환에 대한 반환을 수행하십시오.




 a| 
PARTNER_NAME을 기다리는 중입니다. 이전 테이크오버 시도가 중단되었습니다. 로컬 노드가 파트너의 일부 SFO 애그리게이트를 소유합니다. 나머지 애그리게이트를 테이크오버하려면 "‑Bypass-optimization" 매개 변수를 true로 설정하여 파트너의 테이크오버 또는 파트너의 반환을 발행하십시오.
 a| 
로컬 노드는 HA 인터커넥트를 통해 파트너 노드와 정보를 교환할 수 없습니다. 이전 테이크오버 시도가 중단되었습니다. 로컬 노드는 파트너의 SFO 애그리게이트 중 일부를 소유합니다.

* 파트너 노드의 테이크오버를 다시 발행하고‑Bypass‑optimization 매개 변수를 true 로 설정하여 나머지 SFO 애그리게이트를 테이크오버하거나, 파트너 반환에 대한 반환을 수행하십시오.




 a| 
PARTNER_NAME에 연결되었습니다. 로컬 노드에서 백그라운드 디스크 펌웨어 업데이트(BDFU)를 해제하지 못해 이전 테이크오버 시도가 중단되었습니다.
 a| 
HA 인터커넥트는 활성 상태이며 데이터를 파트너 노드로 전송할 수 있습니다. 로컬 노드의 백그라운드 디스크 펌웨어 업데이트가 비활성화되지 않아 이전 테이크오버 시도가 중단되었습니다.



 a| 
PARTNER_NAME에 연결되었습니다. 이유 때문에 이전 테이크오버 시도가 중단되었습니다.
 a| 
HA 인터커넥트는 활성 상태이며 데이터를 파트너 노드로 전송할 수 있습니다. 이유 아래에 표시된 원인으로 인해 이전 테이크오버 시도가 중단되었습니다.



 a| 
PARTNER_NAME을 기다리는 중입니다. 이유 때문에 이전 테이크오버 시도가 중단되었습니다.
 a| 
로컬 노드는 HA 인터커넥트를 통해 파트너 노드와 정보를 교환할 수 없습니다. 이유 아래에 표시된 원인으로 인해 이전 테이크오버 시도가 중단되었습니다.



 a| 
PARTNER_NAME에 연결되었습니다. PARTNER_NAME에 의한 이전 테이크오버 시도가 이유로 중단되었습니다.
 a| 
HA 인터커넥트는 활성 상태이며 데이터를 파트너 노드로 전송할 수 있습니다. 이유 아래에 표시된 이유로 파트너 노드에서 이전 테이크오버 시도가 중단되었습니다.



 a| 
PARTNER_NAME에 연결되었습니다. PARTNER_NAME에 의한 이전 테이크오버 시도가 중단되었습니다.
 a| 
HA 인터커넥트는 활성 상태이며 데이터를 파트너 노드로 전송할 수 있습니다. 파트너 노드에서 이전 테이크오버 시도가 중단되었습니다.



 a| 
PARTNER_NAME을 기다리는 중입니다. PARTNER_NAME에 의한 이전 테이크오버 시도가 이유로 중단되었습니다.
 a| 
로컬 노드는 HA 인터커넥트를 통해 파트너 노드와 정보를 교환할 수 없습니다. 이유 아래에 표시된 이유로 파트너 노드에서 이전 테이크오버 시도가 중단되었습니다.



 a| 
모듈:모듈 이름에서 이전 반환이 실패했습니다. 자동 반환은 초 후에 시작됩니다.
 a| 
module_name 모듈에서 이전 반환 시도가 실패했습니다. 자동 반환은 초 후에 시작됩니다.

* 자세한 내용은 'storage failover show-반환' 명령을 실행합니다.




 a| 
노드가 무중단 컨트롤러 업그레이드 절차의 일부로 파트너 애그리게이트를 소유합니다.
 a| 
현재 진행 중인 무중단 컨트롤러 업그레이드 절차로 인해 노드에 파트너 애그리게이트가 있습니다.



 a| 
PARTNER_NAME에 연결되었습니다. 노드가 클러스터의 다른 노드에 속한 애그리게이트를 소유합니다.
 a| 
HA 인터커넥트는 활성 상태이며 데이터를 파트너 노드로 전송할 수 있습니다. 이 노드는 클러스터의 다른 노드에 속한 애그리게이트를 소유합니다.



 a| 
PARTNER_NAME에 연결되었습니다. 파트너 잠금 동기화를 기다리는 중입니다.
 a| 
HA 인터커넥트는 활성 상태이며 데이터를 파트너 노드로 전송할 수 있습니다. 시스템에서 파트너 잠금 동기화가 완료될 때까지 기다리는 중입니다.



 a| 
PARTNER_NAME에 연결되었습니다. 로컬 노드에서 클러스터 애플리케이션이 온라인 상태가 될 때까지 기다리는 중입니다.
 a| 
HA 인터커넥트는 활성 상태이며 데이터를 파트너 노드로 전송할 수 있습니다. 시스템이 로컬 노드에서 클러스터 애플리케이션이 온라인 상태로 전환되기를 기다리고 있습니다.



 a| 
비 HA 모드, 전체 NVRAM을 사용하려면 재부팅하십시오.
 a| 
스토리지 페일오버가 가능하지 않습니다. HA 모드 옵션은 non_ha로 구성됩니다.

* 모든 NVRAM을 사용하려면 노드를 재부팅해야 합니다.




 a| 
비 HA 모드: HA를 활성화하려면 노드를 재부팅합니다.
 a| 
스토리지 페일오버가 가능하지 않습니다.

* HA 기능을 사용하려면 노드를 재부팅해야 합니다.




 a| 
비 HA 모드:
 a| 
스토리지 페일오버가 가능하지 않습니다. HA 모드 옵션은 non_ha로 구성됩니다.

* HA 쌍의 두 노드에서 'Storage failover modify‑mode ha-node nodename' 명령을 실행한 다음 노드를 재부팅하여 HA 기능을 활성화해야 합니다.


|===