---
sidebar: sidebar 
permalink: high-availability/ha_manual_takeover.html 
keywords: ontap, high, availability, ha, pair, manual, takeover, moving, move, epislon, manually, initiated 
summary: 파트너의 유지 관리가 필요한 상황이나 기타 유사한 상황에서 수동으로 테이크오버 수행 가능 
---
= 수동 테이크오버 명령
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
파트너의 유지 관리가 필요한 상황이나 기타 유사한 상황에서 수동으로 테이크오버 수행 가능 파트너 상태에 따라 테이크오버 수행에 사용하는 명령이 달라집니다.

|===


| 원하는 작업 | 이 명령 사용... 


| 파트너 노드를 인수합니다 | 스토리지 페일오버 인수 


| 파트너 애그리게이트가 테이크오버 실행 노드로 이동될 때 테이크오버 진행 상황을 모니터링합니다 | '스토리지 페일오버 표시 - 테이크오버 


| 클러스터의 모든 노드에 대한 스토리지 페일오버 상태를 표시합니다 | '스토리지 페일오버 쇼' 


| LIF를 마이그레이션하지 않고 파트너 노드를 테이크오버합니다 | 'Storage failover takeover‑skip‑lif‑migration‑before‑takeover true' 


| 디스크 불일치가 있더라도 파트너 노드를 인수하십시오 | 'Storage failover takeover‑skip‑lif‑migration‑before‑takeover true' 


| ONTAP 버전이 일치하지 않더라도 파트너 노드를 인수하십시오. * 참고: * 이 옵션은 무중단 ONTAP 업그레이드 프로세스 중에만 사용됩니다. | 'Storage failover takeover-option allow‑version‑mismatch'를 참조하십시오 


| 애그리게이트 재배치를 수행하지 않고 파트너 노드를 인수합니다 | '스토리지 페일오버 테이크오버가 무시가 최적화 true'입니다 


| 파트너가 스토리지 리소스를 올바르게 종료할 시간이 되기 전에 파트너 노드를 테이크오버합니다 | '스토리지 페일오버 테이크오버옵션 즉시 
|===
[NOTE]
====
즉시 옵션을 사용하여 스토리지 페일오버 명령을 실행하기 전에 'network interface migrate -all -node_node_' 명령을 사용하여 데이터 LIF를 다른 노드로 마이그레이션해야 합니다

데이터 LIF를 먼저 마이그레이션하지 않고 '스토리지 페일오버 테이크오버하기 옵션 즉시' 명령을 지정하면 'ip‑lif‑migration‑before‑Takeover' 옵션을 지정하지 않아도 노드에서 데이터 LIF 마이그레이션이 크게 지연됩니다.

마찬가지로 즉시 옵션을 지정하면 바이패스 최적화 옵션이 _false_로 설정되어 있어도 협상된 테이크오버 최적화가 무시됩니다.

====


== 수동으로 시작된 특정 테이크오버에 대한 epsilon 이동

수동으로 시작된 테이크오버로 인해 스토리지 시스템에서 예기치 않은 노드 장애가 발생할 수 있으므로 클러스터 전체의 쿼럼 손실로 인한 손실이 발생할 수 있다고 생각되면 epsilon을 이동해야 합니다.

.이 작업에 대해
계획된 유지 관리를 수행하려면 HA 쌍 중 하나를 페일오버해야 합니다. 나머지 노드에 대해 계획되지 않은 클라이언트 데이터 중단을 방지하기 위해 클러스터 전체 쿼럼을 유지해야 합니다. 경우에 따라 Takeover를 수행하면 클러스터 전체의 쿼럼 손실에서 예기치 않은 노드 장애 1개가 발생하는 클러스터를 생성할 수 있습니다.

이 문제는 인수되는 노드가 epsilon을 보유하고 있거나 epsilon이 있는 노드가 정상이 아닌 경우 발생할 수 있습니다. 보다 탄력적인 클러스터를 유지하기 위해 epsilon을 인수되지 않은 정상 노드로 전송할 수 있습니다. 일반적으로 HA 파트너가 될 것입니다.

정상 및 자격을 갖춘 노드만 쿼럼 투표에 참여합니다. 클러스터 전체 쿼럼을 유지하려면 N/2 이상의 표가 필요합니다. 여기서 _N_은 자격이 있는 정상 온라인 노드의 합을 나타냅니다. 온라인 노드의 수가 짝수인 클러스터에서 epsilon은 할당된 노드에 대한 쿼럼을 유지 관리하기 위해 추가 투표 가중치를 추가합니다.


NOTE: 'cluster modify -eligibility false' 명령을 사용하여 클러스터 형성 투표를 수정할 수 있지만 노드 구성 복원이나 노드 유지 보수 연장 같은 상황을 제외하고는 이러한 상황을 피해야 합니다. 노드를 부적격 노드로 설정한 경우 노드가 적격으로 재설정되고 재부팅될 때까지 SAN 데이터 제공을 중단합니다. 노드에 대한 NAS 데이터 액세스는 노드가 부적격 상태일 때도 영향을 받을 수 있습니다.

.단계
. 클러스터 상태를 확인하고 epsilon이 인수되지 않은 정상 노드에 보관되어 있는지 확인합니다.
+
.. 고급 권한 수준으로 변경하여 고급 모드 프롬프트가 나타나면 계속 진행할지 확인합니다(*>).
+
세트 프리빌리지 고급

.. 어떤 노드에 epsilon가 있는지 확인합니다.
+
'클러스터 쇼'

+
다음 예제에서 Node1은 epsilon을 보유합니다.

+
|===


| 노드 | 상태 | 자격 | Epsilon의 


 a| 
노드1 노드2
 a| 
참입니다
 a| 
참입니다
 a| 
참 거짓

|===
+
인수하려는 노드에 epsilon이 없는 경우 4단계를 진행합니다.



. 인수하려는 노드에서 epsilon을 제거합니다.
+
'cluster modify-node Node1-epsilon FALSE'

. 파트너 노드에 epsilon 할당(이 예에서는 Node2):
+
'cluster modify-node Node2-epsilon TRUE'

. 테이크오버 작업 수행:
+
'storage failover takeover-ofnode_name_'

. 관리자 권한 레벨로 돌아갑니다.
+
'Set-Privilege admin'입니다


