---
sidebar: sidebar 
permalink: high-availability/halt-reboot-node-wo-takeover-task.html 
keywords: high availability pair, hair, inhibit-takeover, reboot, epsilon, HA 
summary: '노드 또는 쉘프에 대해 특정 하드웨어 유지 관리를 수행할 때 테이크오버 없이 2노드 클러스터의 노드를 중단하거나 재부팅하는 경우 파트너 노드를 가동하여 중단 시간을 제한하려는 경우 또는 수동 테이크오버(takeover)에 방해가 되는 문제가 있고 파트너 노드의 집계를 유지하고 데이터를 서비스하려는 경우 또한 기술 지원 부서에서 문제 해결을 지원하는 경우 이러한 작업의 일부로 이 절차를 수행할 수 있습니다.' 
---
= 2노드 클러스터에서 테이크오버 시작 없이 노드를 중단 또는 재부팅합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
노드 또는 쉘프에 대해 특정 하드웨어 유지 관리를 수행할 때 테이크오버 없이 2노드 클러스터의 노드를 중단하거나 재부팅하는 경우 파트너 노드를 가동하여 중단 시간을 제한하려는 경우 또는 수동 테이크오버(takeover)에 방해가 되는 문제가 있고 파트너 노드의 집계를 유지하고 데이터를 서비스하려는 경우 또한 기술 지원 부서에서 문제 해결을 지원하는 경우 이러한 작업의 일부로 이 절차를 수행할 수 있습니다.

.이 작업에 대해
* Takeover를 금지('-inhibit-takeover TRUE' 매개 변수 사용)하기 전에 클러스터 HA를 비활성화합니다.


[CAUTION]
====
* 2노드 클러스터에서 클러스터 HA는 노드 1개의 장애가 클러스터를 비활성화하지 않도록 보장합니다. 하지만 '-inhibit-takeover true' 매개 변수를 사용하기 전에 클러스터 HA를 해제하지 않으면 두 노드 모두 데이터 제공을 중단합니다.
* 클러스터 HA를 해제하기 전에 노드를 중단 또는 재부팅하려고 시도하면 ONTAP는 경고를 표시하고 클러스터 HA를 비활성화하라는 메시지를 표시합니다.


====
* LIF(논리 인터페이스)를 온라인 상태로 유지하려는 파트너 노드로 마이그레이션합니다.
* 중단하거나 재부팅하는 노드에서 유지할 애그리게이트가 있는 경우 온라인 상태로 유지하려는 노드로 이동합니다.


.단계
. 두 노드가 모두 정상 상태인지 확인하십시오. 'cluster show'
+
두 노드 모두 '건강' 칼럼에 '참'이 나타납니다.

+
[listing]
----
cluster::> cluster show
Node         Health  Eligibility
------------ ------- ------------
node1        true     true
node2        true     true
----
. 중단하거나 재부팅될 노드의 모든 LIF를 'network interface migrate-all-node_node_name_' 파트너 노드로 마이그레이션합니다
. 노드에서 중단하거나 재부팅하는 경우 노드가 다운될 때 온라인 상태로 유지하려는 애그리게이트가 있는 경우, 해당 애그리게이트를 파트너 노드로 재배치하고, 그렇지 않으면 다음 단계로 이동하십시오.
+
.. 중단하거나 재부팅할 노드에 있는 애그리게이트를 표시합니다. 'storage aggregate show -node_name_'
+
예를 들어, node1은 중단되거나 재부팅될 노드입니다.

+
[listing]
----
cluster::> storage aggregates show -node node1
Aggregate  Size  Available  Used%  State  #Vols   Nodes   RAID  Status
---------  ----  ---------  -----  -----  -----   -----   ----  ------
aggr0_node_1_0
           744.9GB   32.68GB   96% online       2 node1    raid_dp,
                                                                normal
aggr1       2.91TB    2.62TB   10% online       8 node1    raid_dp,
                                                                normal
aggr2
            4.36TB    3.74TB   14% online      12 node1    raid_dp,
                                                                normal
test2_aggr  2.18TB    2.18TB    0% online       7 node1    raid_dp,
                                                                normal
4 entries were displayed.
----
.. 파트너 노드로 애그리게이트를 이동합니다. 'storage aggregate Relocation start -node_node_name_-destination_node_name_-aggregate-list_aggregate_name_'
+
예를 들어, aggr1, aggr2 및 test2_aggr 애그리게이트를 노드 1에서 노드 2로 이동하는 경우:

+
'Storage aggregate relocation start -node_node1_-destination_node2_-aggregate-list_aggr1_,_aggr2_,_test2_aggr_'



. Cluster HA:'cluster ha modify-configured false'를 비활성화합니다
+
반환 출력에서는 HA가 비활성화 되어 Notice:HA가 disabled로 확인된다

+

NOTE: 이 작업을 수행해도 스토리지 페일오버가 비활성화되지 않습니다.

. 적절한 명령을 사용하여 대상 노드의 테이크오버를 중지하거나 재부팅하지 않고 인수를 금지합니다.
+
** 'system node halt-node_node_name_-inhibit-takeover TRUE
** 'system node reboot -node_node_name_-inhibit-takeover TRUE
+

NOTE: 명령 출력에 계속할 것인지 묻는 경고가 표시됩니다. y를 입력합니다.



. 아직 온라인 상태인 노드가 정상 상태(파트너가 다운된 상태)인 클러스터 쇼(cluster show)인지 확인합니다
+
온라인 노드의 경우 "참"이 "상태" 열에 나타납니다.

+

NOTE: 명령 출력에 클러스터 HA가 구성되지 않았다는 경고가 표시됩니다. 지금은 경고를 무시할 수 있습니다.

. 노드를 중지하거나 재부팅하는 데 필요한 작업을 수행합니다.
. LOADER 프롬프트에서 오프라인 노드를 부팅합니다. boot_ONTAP입니다
. 두 노드가 모두 정상 상태인지 확인하십시오. 'cluster show'
+
두 노드 모두 '건강' 칼럼에 '참'이 나타납니다.

+

NOTE: 명령 출력에 클러스터 HA가 구성되지 않았다는 경고가 표시됩니다. 지금은 경고를 무시할 수 있습니다.

. 클러스터 HA 재활성화: '클러스터 ha 수정 - 구성됨 true'
. 이 절차의 앞부분에서 애그리게이트를 파트너 노드로 재배치한 경우 해당 애그리게이트를 홈 노드로 다시 이동하거나, 그렇지 않은 경우 'Storage aggregate Relocation start -node_name_-destination_node_name_-aggregate-list_aggregate_name_'으로 이동합니다
+
예를 들어, aggr1, aggr2 및 test2_aggr을 노드 node2에서 노드 node1로 이동하는 경우:'storage aggregate relocation start -node_node2_-destination_node1_-aggregate-list_aggr1_,_aggr2_,_test2_aggr_'입니다

. LIF를 홈 포트로 되돌리기:
+
.. 집에 없는 LIF를 보면 네트워크 인터페이스 show-is-home false를 알 수 있습니다
.. 다운 노드에서 마이그레이션되지 않은 비홈 LIF가 있는 경우 되돌리기 전에 LIF를 이동해도 되는지 확인하십시오.
.. 안전한 경우 모든 LIF를 홈으로 되돌리십시오. '네트워크 인터페이스 복원 *'



