---
sidebar: sidebar 
permalink: high-availability/index.html 
keywords: high availability, ha, overview 
summary: 테이크오버는 노드가 파트너의 스토리지를 제어하는 프로세스입니다. 반환 프로세스는 스토리지가 파트너에게 반환되는 프로세스입니다. 
---
= 고가용성 관리 개요
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
클러스터 노드는 내결함성 및 무중단 운영을 위해 고가용성(HA) 쌍으로 구성됩니다. 노드에 장애가 발생할 경우 또는 정기적인 유지보수를 위해 노드를 구축해야 하는 경우 파트너는 스토리지를 인계받아 노드에서 데이터를 계속 제공할 수 있습니다. 파트너가 노드를 온라인 상태로 되돌릴 때 스토리지를 제공합니다.

HA 쌍 컨트롤러 구성은 일치하는 FAS/AFF 스토리지 컨트롤러 쌍(로컬 노드 및 파트너 노드)으로 구성됩니다. 각 노드는 다른 노드의 디스크 쉘프에 연결됩니다. HA 2노드에서 하나의 노드에 오류가 발생하여 데이터 처리가 중단되면 파트너는 파트너의 장애 상태를 감지하여 해당 컨트롤러에서 모든 데이터 처리를 인계받습니다.

_테이크오버는 노드가 파트너의 스토리지를 제어하는 프로세스입니다.

_Giveback_은 스토리지를 파트너에게 반환하는 프로세스입니다.

기본적으로 테이크오버는 다음과 같은 상황에서 자동으로 수행됩니다.

* 소프트웨어 또는 시스템 장애가 노드에서 발생하고 패닉이 발생합니다. HA 쌍 컨트롤러는 자동으로 해당 파트너 노드로 페일오버됩니다. 파트너가 패닉 상태에서 복구되고 부팅된 후에 노드가 자동으로 반환을 수행하고 파트너를 정상 운영으로 반환합니다.
* 노드에서 시스템 장애가 발생하고 노드를 재부팅할 수 없습니다. 예를 들어, 전원 손실로 인해 노드에 장애가 발생할 경우 HA 쌍 컨트롤러가 자동으로 파트너 노드로 페일오버되고 정상적인 스토리지 컨트롤러에서 데이터를 제공합니다.



NOTE: 노드의 스토리지 파워도 동시에 손실되면 표준 테이크오버가 가능하지 않습니다.

* 하트비트 메시지는 노드의 파트너로부터 수신되지 않습니다. 파트너가 하드웨어 또는 소프트웨어 장애(예: 상호 연결 장애)를 겪어 패닉이 발생하지 않지만 제대로 작동하지 않는 경우 이러한 문제가 발생할 수 있습니다.
* '-f' 또는 '-inhibit-takeover true' 매개 변수를 사용하지 않고 노드 중 하나를 중단시킵니다.



NOTE: 클러스터 HA가 활성화된 2노드 클러스터에서 '‑inhibit‑Takeover true' 매개변수를 사용하여 노드를 중단 또는 재부팅하면 먼저 클러스터 HA를 비활성화한 다음 온라인 상태를 유지할 노드에 epsilon을 할당하지 않는 한 두 노드가 데이터 제공을 중지합니다.

* '‑INHIBIT‑Takeover TRUE' 매개 변수를 사용하지 않고 노드 중 하나를 재부팅합니다. (Storage failover 명령의 '‑ONBOOT' 매개변수는 기본적으로 설정되어 있습니다.)
* 원격 관리 장치(서비스 프로세서)가 파트너 노드의 장애를 감지합니다. 하드웨어 지원 테이크오버를 사용하지 않도록 설정한 경우에는 적용되지 않습니다.


'Storage failover' 명령을 사용하여 수동으로 테이크오버를 시작할 수도 있습니다.
