---
permalink: nas-audit/basic-auditing-concept.html 
sidebar: sidebar 
keywords: basic audit concepts 
summary: ONTAP의 감사를 이해하려면 몇 가지 기본적인 감사 개념을 알고 있어야 합니다. 
---
= 기본 감사 개념
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP의 감사를 이해하려면 몇 가지 기본적인 감사 개념을 알고 있어야 합니다.

* * 스테이징 파일 *
+
통합 및 변환 전에 감사 레코드가 저장되는 개별 노드의 중간 바이너리 파일입니다. 스테이징 파일은 스테이징 볼륨에 포함되어 있습니다.

* * 스테이징 볼륨 *
+
ONTAP에서 스테이징 파일을 저장하기 위해 생성한 전용 볼륨입니다. 애그리게이트당 하나의 스테이징 볼륨이 있습니다. 스테이징 볼륨은 모든 감사 가능 스토리지 가상 시스템(SVM)에서 공유되며, 해당 애그리게이트 내 데이터 볼륨의 데이터 액세스 감사 레코드를 저장합니다. 각 SVM의 감사 레코드는 스테이징 볼륨 내의 개별 디렉토리에 저장됩니다.

+
클러스터 관리자는 스테이징 볼륨에 대한 정보를 볼 수 있지만 다른 대부분의 볼륨 작업은 허용되지 않습니다. ONTAP만 스테이징 볼륨을 생성할 수 있습니다. ONTAP는 스테이징 볼륨에 이름을 자동으로 할당합니다. 모든 스테이징 볼륨 이름은 mdv_AUD_ 로 시작하고 그 스테이징 볼륨을 포함하는 애그리게이트의 UUID로 시작합니다(예: mdv_AUD_1d0131843d4811e296fc123478563412).

* * 시스템 볼륨 *
+
파일 서비스 감사 로그의 메타데이터와 같은 특수 메타데이터가 포함된 FlexVol 볼륨입니다. admin SVM은 시스템 볼륨을 소유하며 클러스터 전체에서 볼 수 있습니다. 스테이징 볼륨은 시스템 볼륨의 유형입니다.

* * 통합 작업 *
+
감사가 설정되어 있을 때 생성되는 작업입니다. 각 SVM에서 장기적으로 실행되는 이 작업은 SVM 구성원 노드 전체의 스테이징 파일에서 감사 레코드를 가져갑니다. 이 작업은 감사 레코드를 날짜순으로 정렬하여 병합한 다음, evtx 또는 XML 파일 형식으로 감사 구성에 지정된 사용자 판독 가능한 이벤트 로그 형식으로 변환합니다. 변환된 이벤트 로그는 SVM 감사 구성에 지정된 감사 이벤트 로그 디렉토리에 저장됩니다.


