---
permalink: nas-audit/cli-change-events-concept.html 
sidebar: sidebar 
keywords: cli change events, audited 
summary: ONTAP는 특정 SMB 공유 이벤트, 특정 감사 정책 이벤트, 특정 로컬 보안 그룹 이벤트, 로컬 사용자 그룹 이벤트 및 인증 정책 이벤트를 비롯한 특정 CLI 변경 이벤트를 감사할 수 있습니다. 감사할 수 있는 변경 이벤트를 이해하면 이벤트 로그의 결과를 해석할 때 도움이 됩니다. 
---
= 감사할 수 있는 CLI 변경 이벤트 개요
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP는 특정 SMB 공유 이벤트, 특정 감사 정책 이벤트, 특정 로컬 보안 그룹 이벤트, 로컬 사용자 그룹 이벤트 및 인증 정책 이벤트를 비롯한 특정 CLI 변경 이벤트를 감사할 수 있습니다. 감사할 수 있는 변경 이벤트를 이해하면 이벤트 로그의 결과를 해석할 때 도움이 됩니다.

감사 로그를 수동으로 회전하고, 감사를 설정 또는 비활성화하고, 변경 이벤트 감사 정보를 표시하고, 변경 이벤트 감사 및 감사 변경 이벤트를 수정하여, CLI 변경 이벤트를 감사하여 스토리지 가상 시스템(SVM) 감사 CLI 변경 이벤트를 관리할 수 있습니다.

관리자 권한으로 SMB-share, 로컬 사용자 그룹, 로컬 보안 그룹, 인증 정책 및 감사 정책 이벤트와 관련된 구성을 변경하기 위해 명령을 실행하는 경우 레코드가 생성되고 해당 이벤트가 감사됩니다.

|===


| 감사 범주 | 이벤트 | 이벤트 ID입니다 | 이 명령 실행... 


 a| 
Mhost 감사
 a| 
정책 변경
 a| 
[4719] 감사 구성이 변경되었습니다
 a| 
'vserver audit disable | enable | modify'



 a| 
파일 공유
 a| 
[5142] 네트워크 공유가 추가되었습니다
 a| 
'vserver cifs share create



 a| 
[5143] 네트워크 공유가 수정되었습니다
 a| 
'vserver cifs share modify''vserver cifs share create | modify | delete''vserver cifs share add | remove'



 a| 
[5144] 네트워크 공유가 삭제되었습니다
 a| 
'vserver cifs share delete



 a| 
감사
 a| 
사용자 계정
 a| 
[4720] 로컬 사용자가 생성되었습니다
 a| 
'vserver cifs users-and-groups local-user create''vserver services name-service unix-user create'를 참조하십시오



 a| 
[4722] 로컬 사용자가 활성화되었습니다
 a| 
'vserver cifs users-and-groups local-user create | modify'를 참조하십시오



 a| 
[4724] 로컬 사용자 암호 재설정
 a| 
'vserver cifs users-and-groups local-user set-password



 a| 
[4725] 로컬 사용자가 비활성화되었습니다
 a| 
'vserver cifs users-and-groups local-user create | modify'를 참조하십시오



 a| 
[4726] 로컬 사용자가 삭제되었습니다
 a| 
'vserver cifs users-and-groups local-user delete''vserver services name-service unix-user delete''를 선택합니다



 a| 
[4738] 로컬 사용자 변경
 a| 
'vserver cifs users-and-groups local-user modify''vserver services name-service unix-user modify''를 선택합니다



 a| 
[4781] 로컬 사용자 이름 바꾸기
 a| 
'vserver cifs users-and-groups local-user rename'을 선택합니다



 a| 
보안 그룹
 a| 
[4731] 로컬 보안 그룹이 생성되었습니다
 a| 
'vserver cifs users-and-groups local-group create''vserver services name-service unix-group create'를 참조하십시오



 a| 
[4734] 로컬 보안 그룹이 삭제되었습니다
 a| 
SVM CIFS 사용자-그룹 로컬-그룹 삭제 SVM 서비스 이름-서비스 UNIX-그룹 삭제



 a| 
[4735] 로컬 보안 그룹이 수정되었습니다
 a| 
vserver cifs users-and-groups local-group rename | modify ``vserver services name-service unix-group modify’’라는 이름의 가상 서버 사용자 및 그룹 로컬 그룹 이름 변경



 a| 
[4732] 사용자가 로컬 그룹에 추가되었습니다
 a| 
가상 CIFS 사용자 및 그룹 로컬 그룹 추가 멤버 가상 서버 서비스 이름 서비스 unix 그룹 추가 사용자



 a| 
[4733] 사용자가 로컬 그룹에서 제거되었습니다
 a| 
SVM CIFS 사용자-그룹 local-group remove-멤버들 vserver services name-service unix-group deluser



 a| 
authorization-policy-change를 참조하십시오
 a| 
[4704] 사용자 권한이 할당되었습니다
 a| 
'vserver cifs users-and-groups Privilege add-privilege'



 a| 
[4705] 사용자 권한이 제거되었습니다
 a| 
'vserver cifs users-and-groups Privilege remove-Privilege|reset-Privilege

|===