---
permalink: nas-audit/create-persistent-stores.html 
sidebar: sidebar 
keywords: create, persistent store, fpolicy, asynchronous, non, mandatory 
summary: ONTAP 9.14.1부터 FPolicy를 사용하면 비동기적 정책에 대한 파일 액세스 이벤트를 캡처하는 영구 저장소를 설정할 수 있습니다. 
---
= FPolicy 영구 저장소를 생성합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
영구 저장소는 클라이언트 I/O 처리를 FPolicy 알림 처리와 분리하여 클라이언트 지연 시간을 줄여 줍니다. ONTAP 9.14.1부터 FPolicy를 설정할 수 있습니다 link:persistent-stores.html["영구 저장소"] SVM에서 비동기적 정책에 대한 파일 액세스 이벤트를 캡처합니다. 동기(필수 또는 비필수) 및 비동기 필수 구성은 지원되지 않습니다.

ONTAP 9.15.1부터 FPolicy 영구 저장소 구성이 단순화됩니다. 를 클릭합니다 `persistent-store create` 명령은 SVM에 대한 볼륨 생성을 자동화하고 영구 저장소에 대한 볼륨을 구성합니다.

ONTAP 릴리즈에 따라 영구 저장소를 만드는 방법에는 두 가지가 있습니다.

* ONTAP 9.15.1 이상: 영구 저장소를 만들면 ONTAP에서 자동으로 볼륨을 만들고 동시에 구성합니다. FPolicy 영구 저장소 구성을 간소화하고 모든 모범 사례를 구현합니다.
* ONTAP 9.14.1: 볼륨을 수동으로 생성 및 구성한 다음 새로 생성된 볼륨에 대한 영구 저장소를 생성합니다.


각 SVM에 하나의 영구 저장소만 설정할 수 있습니다. 서로 다른 파트너의 정책이 있는 경우에도 이 단일 영구 저장소를 해당 SVM의 모든 FPolicy 구성에 사용해야 합니다.



== 영구 저장소 만들기(ONTAP 9.15.1 이상)

ONTAP 9.15.1부터 를 사용합니다 `fpolicy persistent-store create` 인라인 볼륨 생성 및 구성으로 FPolicy 영구 저장소를 생성하는 명령 ONTAP는 외부 사용자 프로토콜 액세스(CIFS/NFS)에서 볼륨을 자동으로 차단합니다.

.시작하기 전에
* 영구 저장소를 생성하려는 SVM에 애그리게이트가 하나 이상 있어야 합니다.
* SVM에서 사용할 수 있는 애그리게이트에 액세스할 수 있어야 하고, 볼륨을 생성할 수 있는 충분한 권한이 있어야 합니다.


.단계
. 볼륨을 자동으로 생성 및 구성하는 영구 저장소를 생성합니다.
+
`vserver fpolicy persistent-store create -vserver <vserver> -persistent-store <name> -volume <volume_name> -size <size> -autosize-mode <off|grow|grow_shrink>`

+
** 를 클릭합니다 `vserver` 매개 변수는 SVM의 이름입니다.
** 를 클릭합니다 `persistent-store` 매개 변수는 영구 저장소의 이름입니다.
** 를 클릭합니다 `volume` 매개 변수는 영구 저장소 볼륨의 이름입니다.
+

NOTE: 기존의 빈 볼륨을 사용하려면 를 사용합니다 `volume show` 명령을 사용하여 찾아서 volume 매개 변수에 지정합니다.

** 를 클릭합니다 `size` 매개 변수는 외부 서버(파트너 응용 프로그램)에 전달되지 않은 이벤트를 유지할 기간을 기반으로 합니다.
+
예를 들어, 초당 30,000개의 알림이 있는 클러스터에서 30분 이벤트를 지속하려는 경우:

+
필요한 볼륨 크기 = 30000 x 30 x 60 x 0.6KB(평균 알림 레코드 크기) = 32400000KB = ~32GB

+
대략적인 알림 비율을 확인하려면 FPolicy 파트너 애플리케이션에 문의하거나 FPolicy 카운터를 활용하십시오 `requests_dispatched_rate`.

+

NOTE: 기존 볼륨을 사용하는 경우 size 매개 변수는 선택 사항입니다. size 매개 변수에 값을 입력하면 지정한 크기로 볼륨이 수정됩니다.

** 를 클릭합니다 `autosize-mode` 매개 변수는 볼륨의 자동 크기 조정 모드를 지정합니다. 지원되는 자동 크기 조정 모드는 다음과 같습니다.
+
*** 꺼짐 - 사용된 공간의 양에 대응하여 볼륨이 증가하거나 축소되지 않습니다.
*** 확장 - 볼륨의 사용된 공간이 확장 임계값을 초과할 때 볼륨이 자동으로 증가합니다.
*** grow_shrink - 사용된 공간의 양에 따라 볼륨이 증가하거나 축소됩니다.




. FPolicy 정책을 생성하고 영구 저장소 이름을 해당 정책에 추가합니다. 자세한 내용은 을 참조하십시오 link:create-fpolicy-policy-task.html["FPolicy 정책을 생성합니다"].




== 영구 저장소 생성(ONTAP 9.14.1)

볼륨을 생성한 다음 해당 볼륨을 사용할 영구 저장소를 만들 수 있습니다. 그런 다음 외부 사용자 프로토콜 액세스(CIFS/NFS)에서 새로 생성된 볼륨을 차단할 수 있습니다.

.단계
. 영구 저장소용으로 프로비저닝할 수 있는 SVM에 빈 볼륨을 생성합니다.
+
`volume create -vserver <SVM Name> -volume <volume> -state <online> -policy <default> -unix-permissions <777> -size <value> -aggregate <aggregate name> -snapshot-policy <none>`

+
볼륨을 생성할 충분한 RBAC 권한을 가진 관리자 사용자가 volume CLI 명령 또는 REST API를 사용하여 원하는 크기의 볼륨을 생성하고 해당 볼륨의 이름을 로 제공해야 합니다 `-volume` 영구 저장소에서 CLI 명령 또는 REST API를 생성합니다.

+
** 를 클릭합니다 `vserver` 매개 변수는 SVM의 이름입니다.
** 를 클릭합니다 `volume` 매개 변수는 영구 저장소 볼륨의 이름입니다.
** 를 클릭합니다 `state` 볼륨을 사용할 수 있도록 매개 변수를 온라인으로 설정해야 합니다.
** 를 클릭합니다 `policy` 이미 구성된 경우 매개 변수는 FPolicy 서비스 정책으로 설정됩니다. 그렇지 않은 경우 를 사용할 수 있습니다 `volume modify` 나중에 명령을 사용하여 정책을 추가합니다.
** 를 클릭합니다 `unix-permissions` 매개 변수는 선택 사항입니다.
** 를 클릭합니다 `size` 매개 변수는 외부 서버(파트너 응용 프로그램)에 전달되지 않은 이벤트를 유지할 기간을 기반으로 합니다.
+
예를 들어, 초당 30,000개의 알림이 있는 클러스터에서 30분 이벤트를 지속하려는 경우:

+
필요한 볼륨 크기 = 30000 x 30 x 60 x 0.6KB(평균 알림 레코드 크기) = 32400000KB = ~32GB

+
대략적인 알림 비율을 확인하려면 FPolicy 파트너 애플리케이션에 문의하거나 FPolicy 카운터를 활용하십시오 `requests_dispatched_rate`.

** FlexVol 볼륨에 애그리게이트 매개 변수가 필요하며, 그렇지 않으면 필요하지 않습니다.
** 를 클릭합니다 `snapshot-policy` 매개 변수는 none으로 설정해야 합니다. 이렇게 하면 스냅샷이 실수로 복구되지 않아 현재 이벤트가 손실되고 중복 이벤트 처리가 방지됩니다.
+
기존의 빈 볼륨을 사용하려면 를 사용합니다 `volume show` 명령을 사용하여 찾을 수 있으며 `volume modify` 명령을 사용하여 필요한 사항을 변경합니다. 정책, 크기 및 를 확인합니다 `snapshot-policy` 영구 저장소에 대한 매개 변수가 올바르게 설정되어 있습니다.



. 영구 저장소 만들기:
+
`vserver fpolicy persistent store create -vserver <SVM> -persistent-store <PS_name> -volume <volume>`

+
** 를 클릭합니다 `vserver` 매개 변수는 SVM의 이름입니다.
** 를 클릭합니다 `persistent-store` 매개 변수는 영구 저장소의 이름입니다.
** 를 클릭합니다 `volume` 매개 변수는 영구 저장소 볼륨의 이름입니다.


. FPolicy 정책을 생성하고 영구 저장소 이름을 해당 정책에 추가합니다. 자세한 내용은 을 참조하십시오 link:create-fpolicy-policy-task.html["FPolicy 정책을 생성합니다"].

