---
permalink: nas-audit/create-security-traces-concept.html 
sidebar: sidebar 
keywords: considerations, create, security traces 
summary: 'SVM(스토리지 가상 머신)에 보안 추적을 생성할 때는 몇 가지 사항을 염두에 두어야 합니다. 예를 들어 추적을 만들 수 있는 프로토콜, 지원되는 보안 스타일 및 최대 활성 트레이스 수를 알아야 합니다.' 
---
= 보안 추적을 만들 때 고려해야 할 사항입니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SVM(스토리지 가상 머신)에 보안 추적을 생성할 때는 몇 가지 사항을 염두에 두어야 합니다. 예를 들어 추적을 만들 수 있는 프로토콜, 지원되는 보안 스타일 및 최대 활성 트레이스 수를 알아야 합니다.

* SVM에서는 보안 추적만 생성할 수 있습니다.
* 각 보안 추적 필터 항목은 SVM에 따라 다릅니다.
+
트레이스를 실행할 SVM을 지정해야 합니다.

* SMB 및 NFS 요청에 대한 권한 추적 필터를 추가할 수 있습니다.
* 추적 필터를 생성할 SVM에서 SMB 또는 NFS 서버를 설정해야 합니다.
* NTFS, UNIX, 혼합 보안 스타일 볼륨 및 Qtree에 상주하는 파일 및 폴더에 대한 보안 추적을 만들 수 있습니다.
* SVM당 최대 10개의 권한 추적 필터를 추가할 수 있습니다.
* 필터를 만들거나 수정할 때는 필터 인덱스 번호를 지정해야 합니다.
+
필터는 인덱스 번호 순으로 간주됩니다. 인덱스 번호가 더 높은 필터의 조건은 인덱스 번호가 더 낮은 기준 앞에 고려됩니다. 추적 중인 요청이 활성화된 여러 필터의 조건과 일치하면 인덱스 번호가 가장 높은 필터만 트리거됩니다.

* 보안 추적 필터를 만들고 활성화한 후에는 클라이언트 시스템에서 일부 파일 또는 폴더 요청을 수행하여 추적 필터가 추적 결과 로그를 캡처하고 기록할 수 있는 활동을 생성해야 합니다.
* 파일 액세스 확인 또는 문제 해결 목적으로만 권한 추적 필터를 추가해야 합니다.
+
권한 추적 필터를 추가하면 컨트롤러 성능에 약간의 영향을 줄 수 있습니다.

+
확인 또는 문제 해결 작업을 완료하면 모든 권한 추적 필터를 비활성화하거나 제거해야 합니다. 또한 ONTAP에서 로그에 많은 수의 추적 결과를 전송하지 않도록 선택한 필터링 조건은 가능한 한 구체해야 합니다.


