---
permalink: nas-audit/create-security-trace-filters-task.html 
sidebar: sidebar 
keywords: create, security trace filters 
summary: 'SVM(스토리지 가상 머신)에서 SMB 및 NFS 클라이언트 작업을 감지하고 필터와 일치하는 모든 액세스 검사를 추적하는 보안 추적 필터를 생성할 수 있습니다. 보안 추적의 결과를 사용하여 구성을 확인하거나 액세스 문제를 해결할 수 있습니다.' 
---
= 보안 추적 필터를 만듭니다
:icons: font
:imagesdir: ../media/


[role="lead"]
SVM(스토리지 가상 머신)에서 SMB 및 NFS 클라이언트 작업을 감지하고 필터와 일치하는 모든 액세스 검사를 추적하는 보안 추적 필터를 생성할 수 있습니다. 보안 추적의 결과를 사용하여 구성을 확인하거나 액세스 문제를 해결할 수 있습니다.

vserver security trace filter create 명령에는 두 가지 필수 매개 변수가 있습니다.

[cols="35,65"]
|===


| 필수 매개변수 | 설명 


 a| 
'-vserver''vserver_name'
 a| 
_SVM 이름 _

보안 추적 필터를 적용할 파일 또는 폴더가 포함된 SVM의 이름입니다.



 a| 
인덱스 인덱스 인덱스 인덱스 번호
 a| 
_필터 인덱스 번호 _

필터에 적용할 인덱스 번호입니다. SVM당 최대 10개의 추적 필터로 제한됩니다. 이 매개 변수에 허용되는 값은 1 ~ 10입니다.

|===
여러 선택적 필터 매개 변수를 사용하여 보안 추적 필터를 사용자 지정하여 보안 추적에서 생성된 결과를 좁힐 수 있습니다.

[cols="35,65"]
|===


| 필터 매개 변수 | 설명 


 a| 
'-client-ip''ip_Address'
 a| 
이 필터는 사용자가 SVM에 액세스하는 데 사용할 IP 주소를 지정합니다.



 a| 
길의 길
 a| 
이 필터는 권한 추적 필터를 적용할 경로를 지정합니다. '-path'의 값은 다음 형식 중 하나를 사용할 수 있습니다.

* 공유 또는 내보내기의 루트에서 시작하는 전체 경로입니다
* 공유의 루트에 상대적인 부분 경로입니다


경로 값에 NFS 스타일 디렉토리 UNIX 스타일 디렉토리 구분 기호를 사용해야 합니다.



 a| 
'-windows-name''win_user_name' 또는 '-unix-name''unix_user_name'
 a| 
추적할 액세스 요청의 Windows 사용자 이름 또는 UNIX 사용자 이름을 지정할 수 있습니다. 사용자 이름 변수는 대/소문자를 구분하지 않습니다. 동일한 필터에 Windows 사용자 이름과 UNIX 사용자 이름을 모두 지정할 수는 없습니다.

[NOTE]
====
SMB 및 NFS 액세스 이벤트를 추적할 수 있더라도 UNIX 보안 스타일 데이터가 혼합된 데이터에 대한 액세스 검사를 수행할 때 매핑된 UNIX 사용자 및 매핑된 UNIX 사용자 그룹이 사용될 수 있습니다.

====


 a| 
'-trace-allow'{'yes'|'no'}
 a| 
거부 이벤트 추적은 항상 보안 추적 필터에 대해 활성화됩니다. 선택적으로 허용 이벤트를 추적할 수 있습니다. 허용 이벤트를 추적하려면 이 매개변수를 "예"로 설정합니다.



 a| 
``사용’{'사용'|'사용 안 함'}
 a| 
보안 추적 필터를 사용하거나 사용하지 않도록 설정할 수 있습니다. 기본적으로 보안 추적 필터는 활성화되어 있습니다.



 a| 
시간 사용 정수
 a| 
필터 시간 초과를 지정하면 필터 시간 초과가 해제됩니다.

|===
.단계
. 보안 추적 필터 만들기:
+
'vserver security trace filter create-vserver vserver_name-index index_numberfilter_parameters'

+
filter_parameters는 선택 필터 매개변수 목록입니다.

+
자세한 내용은 명령에 대한 man 페이지를 참조하십시오.

. 보안 추적 필터 항목을 확인합니다.
+
'vserver security trace filter show -vserver vserver_name -index index index_number'



다음 명령을 실행하면 IP 주소 10.10.7에서 공유 경로 '\\server\share1\dir1\dir2\file.txt'를 사용하여 파일에 액세스하는 모든 사용자에 대한 보안 추적 필터가 생성됩니다. 이 필터는 '-path' 옵션을 위한 전체 경로를 사용합니다. 데이터에 액세스하는 데 사용되는 클라이언트의 IP 주소는 10.10.7입니다. 필터는 30분 후에 시간 초과됩니다.

[listing]
----
cluster1::> vserver security trace filter create -vserver vs1 -index 1 -path /dir1/dir2/file.txt -time-enabled 30 -client-ip 10.10.10.7
cluster1::> vserver security trace filter show -index 1
Vserver  Index   Client-IP            Path            Trace-Allow  Windows-Name
-------- -----  -----------  ----------------------   -----------  -------------
vs1        1    10.10.10.7   /dir1/dir2/file.txt          no       -
----
다음 명령을 실행하면 '-path' 옵션에 대한 상대 경로를 사용하여 보안 추적 필터를 만듭니다. 이 필터는 ""Joe""라는 이름의 Windows 사용자에 대한 액세스를 추적합니다. Joe가 공유 경로 '\\server\share1\dir1\dir2\file.txt'를 사용하여 파일에 액세스하고 있습니다. 필터 추적은 이벤트를 허용 및 거부합니다.

[listing]
----
cluster1::> vserver security trace filter create -vserver vs1 -index 2 -path /dir1/dir2/file.txt -trace-allow yes -windows-name mydomain\joe

cluster1::> vserver security trace filter show -vserver vs1 -index 2
                                 Vserver: vs1
                            Filter Index: 2
              Client IP Address to Match: -
                                    Path: /dir1/dir2/file.txt
                       Windows User Name: mydomain\joe
                          UNIX User Name: -
                      Trace Allow Events: yes
                          Filter Enabled: enabled
               Minutes Filter is Enabled: 60
----