---
permalink: nas-audit/create-persistent-stores.html 
sidebar: sidebar 
keywords: create, persistent store, fpolicy 
summary: ONTAP 9.14.1부터 FPolicy를 사용하면 SVM의 비동기적 정책에 대한 파일 액세스 이벤트를 캡처하는 영구 저장소를 설정할 수 있습니다. 영구 저장소는 클라이언트 I/O 처리를 FPolicy 알림 처리와 분리하여 클라이언트 지연 시간을 줄여 줍니다. 동기 및 비동기 필수 구성은 지원되지 않습니다. 
---
= 영구 저장소를 만듭니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9.14.1부터 FPolicy를 통해 를 설정할 수 있습니다 link:persistent-stores.html["영구 저장소"] SVM에서 비동기적 정책에 대한 파일 액세스 이벤트를 캡처합니다. 영구 저장소는 클라이언트 I/O 처리를 FPolicy 알림 처리와 분리하여 클라이언트 지연 시간을 줄여 줍니다. 동기(필수 또는 비필수) 및 비동기 필수 구성은 지원되지 않습니다.

.모범 사례
* 영구 저장소 기능을 사용하기 전에 파트너 응용 프로그램이 이 구성을 지원하는지 확인하십시오.
* 영구 저장소 볼륨은 SVM별로 설정됩니다. 각 FPolicy가 활성화된 SVM에 대해 영구 저장소 볼륨이 필요합니다.
* 영구 저장소 볼륨 이름과 볼륨 생성 시 지정된 접합 경로가 일치해야 합니다.
* Fpolicy에서 최대 트래픽을 모니터링할 것으로 예상되는 LIF로 노드에 영구 저장소 볼륨을 생성합니다.
* 스냅샷 정책을 로 설정합니다 `none` 에 대해 이야기해 보려고 합니다 `default`. 이는 스냅샷을 실수로 복구하여 현재 이벤트가 손실되지 않도록 하고 중복 이벤트 처리를 방지하기 위한 것입니다.
* 영구 저장소 볼륨을 외부 사용자 프로토콜 액세스(CIFS/NFS)에 액세스할 수 없도록 하여 영구 이벤트 레코드가 실수로 손상되거나 삭제되지 않도록 합니다. 이를 위해 FPolicy를 활성화한 후 ONTAP에서 볼륨을 마운트 해제하여 접합 경로를 제거하면 사용자 프로토콜 액세스에 액세스할 수 없게 됩니다.


.단계
. 영구 저장소용으로 프로비저닝할 수 있는 SVM에 빈 볼륨을 생성합니다.
+
`volume create -vserver <SVM Name> -volume <volume> -state <online> -junction-path <path> -policy <default> -unix-permissions <777> -size <value> -aggregate <aggregate name> -snapshot-policy <none>`

+
** 영구 저장소 볼륨의 크기는 외부 서버(파트너 응용 프로그램)에 전달되지 않은 이벤트를 유지할 기간을 기준으로 합니다.
+
예를 들어, 초당 30,000개의 알림이 있는 클러스터에서 30분 이벤트를 지속하려는 경우:

+
필요한 볼륨 크기 = 30000 x 30 x 60 x 0.6KB(평균 알림 레코드 크기) = 32400000KB = ~32GB

+
대략적인 알림 비율을 확인하려면 FPolicy 파트너 애플리케이션에 문의하거나 FPolicy 카운터를 활용하십시오 `requests_dispatched_rate`.

** 충분한 RBAC 권한(볼륨을 생성하기 위해)을 가진 관리자가 원하는 크기의 볼륨(volume CLI 명령 또는 REST API 사용)을 생성하고 해당 볼륨의 이름을 로 제공해야 합니다 `-volume` 영구 저장소에서 CLI 명령 또는 REST API를 생성합니다.


. 영구 저장소 만들기:
+
`vserver fpolicy persistent store create -vserver <SVM> -persistent-store <PS_name> -volume <volume>`

+
** 영구 저장소: 영구 저장소 이름입니다
** 볼륨: 영구 저장소 볼륨입니다


. 영구 저장소를 생성한 후 FPolicy 정책을 생성하고 영구 저장소 이름을 해당 정책에 추가할 수 있습니다.
자세한 내용은 을 참조하십시오 link:https://docs.netapp.com/us-en/ontap/nas-audit/create-fpolicy-policy-task.html["FPolicy 정책을 생성합니다"].

