---
permalink: nas-audit/display-audit-policies-windows-security-tab-task.html 
sidebar: sidebar 
keywords: display, information, audit policies, windows security tab 
summary: Windows 속성 창의 보안 탭을 사용하여 파일 및 디렉터리에 적용된 감사 정책에 대한 정보를 표시할 수 있습니다. 이는 Windows 서버에 있는 데이터에 사용되는 것과 동일한 방법으로, 고객이 익숙한 GUI 인터페이스를 사용할 수 있습니다. 
---
= Windows 보안 탭을 사용하여 감사 정책에 대한 정보를 표시합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Windows 속성 창의 보안 탭을 사용하여 파일 및 디렉터리에 적용된 감사 정책에 대한 정보를 표시할 수 있습니다. 이는 Windows 서버에 있는 데이터에 사용되는 것과 동일한 방법으로, 고객이 익숙한 GUI 인터페이스를 사용할 수 있습니다.

파일 및 디렉터리에 적용된 감사 정책에 대한 정보를 표시하면 지정된 파일 및 폴더에 적절한 SACL(시스템 액세스 제어 목록)이 설정되어 있는지 확인할 수 있습니다.

NTFS 파일 및 폴더에 적용된 SACL에 대한 정보를 표시하려면 Windows 호스트에서 다음 단계를 수행하십시오.

.단계
. Windows 탐색기의 * Tools * 메뉴에서 * Map network drive * 를 선택합니다.
. 네트워크 드라이브 연결 * 대화 상자를 완료합니다.
+
.. 드라이브 * 문자를 선택합니다.
.. 폴더 * 상자에 감사할 데이터와 공유 이름을 둘 다 포함하는 공유가 포함된 SVM(스토리지 가상 시스템)의 IP 주소 또는 SMB 서버 이름을 입력합니다.
+
SMB 서버 이름이 "smb_server"이고 공유 이름이 "hay1"인 경우 \\smb_server\share1"을 입력해야 합니다.

+
[NOTE]
====
SMB 서버 이름 대신 SMB 서버에 대한 데이터 인터페이스의 IP 주소를 지정할 수 있습니다.

====
.. 마침 * 을 클릭합니다.


+
선택한 드라이브가 마운트되고 공유 내에 포함된 파일 및 폴더를 표시하는 Windows 탐색기 창이 준비됩니다.

. 감사 정보를 표시할 파일 또는 디렉터리를 선택합니다.
. 파일 또는 디렉토리를 마우스 오른쪽 버튼으로 클릭하고 * 속성 * 을 선택합니다.
. 보안 * 탭을 선택합니다.
. 고급 * 을 클릭합니다.
. 감사 * 탭을 선택합니다.
. 계속 * 을 클릭합니다.
+
감사 상자가 열립니다. 감사 항목 * 상자에는 SACL이 적용된 사용자 및 그룹의 요약이 표시됩니다.

. 감사 항목 * 상자에서 SACL 항목을 표시할 사용자 또는 그룹을 선택합니다.
. 편집 * 을 클릭합니다.
+
object>에 대한 감사 항목이 열립니다.

. Access* 상자에서 선택한 개체에 적용된 현재 SACL을 확인합니다.
. 객체> * 에 대한 * 감사 항목을 닫으려면 * 취소 * 를 클릭합니다.
. 취소 * 를 클릭하여 * 감사 * 상자를 닫습니다.

