---
permalink: nas-audit/display-connections-external-fpolicy-servers-task.html 
sidebar: sidebar 
keywords: display, information, connections, external fpolicy servers 
summary: '클러스터의 외부 FPolicy 서버(FPolicy 서버) 또는 지정된 SVM(스토리지 가상 머신)에 대한 연결에 대한 상태 정보를 표시할 수 있습니다. 이 정보는 어떤 FPolicy 서버가 연결되어 있는지 확인하는 데 도움이 될 수 있습니다.' 
---
= 외부 FPolicy 서버 연결에 대한 정보를 표시합니다
:allow-uri-read: 


[role="lead"]
클러스터의 외부 FPolicy 서버(FPolicy 서버) 또는 지정된 SVM(스토리지 가상 머신)에 대한 연결에 대한 상태 정보를 표시할 수 있습니다. 이 정보는 어떤 FPolicy 서버가 연결되어 있는지 확인하는 데 도움이 될 수 있습니다.

매개 변수를 지정하지 않으면 다음 정보가 표시됩니다.

* SVM 이름
* 노드 이름
* FPolicy 정책 이름입니다
* FPolicy 서버 IP 주소입니다
* FPolicy 서버 상태입니다
* FPolicy 서버 유형입니다


클러스터 또는 특정 SVM에서 FPolicy 연결에 대한 정보를 표시하는 것 외에도 명령 매개 변수를 사용하여 명령 출력을 다른 기준으로 필터링할 수 있습니다.

나열된 정책에 대한 자세한 정보를 표시하려면 '-instance' 매개 변수를 지정할 수 있습니다. 또는 '-fields' 매개 변수를 사용하여 명령 출력에 표시된 필드만 표시할 수 있습니다. 당신은 `?'를 입력할 수 있습니다 '-fields' 매개 변수 뒤에 사용할 수 있는 필드를 찾습니다.

.단계
. 적절한 명령을 사용하여 노드와 FPolicy 서버 사이의 연결 상태에 대한 필터링된 정보를 표시합니다.
+
[cols="35,65"]
|===


| FPolicy 서버에 대한 연결 상태 정보를 표시하려면... | 입력... 


 a| 
지정할 수 있습니다
 a| 
'vserver FPolicy show -engine-server ip_address'



 a| 
특정 SVM용
 a| 
'vserver FPolicy show -engine -vserver vserver_name'



 a| 
지정된 정책에 첨부되어 있습니다
 a| 
'vserver FPolicy show-engine-policy-name policy_name'입니다



 a| 
지정한 서버 상태를 사용합니다
 a| 
'vserver FPolicy show-engine-server-status'

서버 상태는 다음 중 하나일 수 있습니다.

** '연결됨'
** "연결 안 됨"
** 연결 중
** 연결 중




 a| 
지정된 유형의 경우
 a| 
'vserver FPolicy show-engine-server-type type'

FPolicy 서버 유형은 다음 중 하나일 수 있습니다.

** 1차
** 2차




 a| 
지정된 이유로 연결이 끊어졌습니다
 a| 
'vserver FPolicy show-engine-disconnect-reason text'를 참조하십시오

연결 해제는 여러 가지 이유로 인해 발생할 수 있습니다. 연결을 끊는 일반적인 이유는 다음과 같습니다.

** CLI로부터 dissconnect 명령을 받았습니다
** FPolicy 서버에서 알림 응답을 구문 분석하는 동안 오류가 발생했습니다
** FPolicy 핸드셰이크를 실패했습니다
** SL 핸드셰이크가 실패했습니다
** FPolicy 서버에 대한 TCP 연결이 실패했습니다
** FPolicy 서버로부터 받은 화면 응답 메시지가 유효하지 않습니다


|===


이 예는 SVM의 FPolicy 서버에 대한 외부 엔진 연결 정보를 표시합니다. vs1.example.com:

[listing]
----
cluster1::> vserver fpolicy show-engine -vserver vs1.example.com
FPolicy                                              Server-       Server-
Vserver         Policy    Node         Server        status        type
--------------- --------- ------------ ------------- ------------- ---------
vs1.example.com policy1   node1        10.1.1.2      connected     primary
vs1.example.com policy1   node1        10.1.1.3      disconnected  primary
vs1.example.com policy1   node2        10.1.1.2      connected     primary
vs1.example.com policy1   node2        10.1.1.3      disconnected  primary
----
이 예는 연결된 FPolicy 서버에 대한 정보만 표시합니다.

[listing]
----
cluster1::> vserver fpolicy show-engine -fields server -server-status connected
node       vserver         policy-name server
---------- --------------- ----------- -------
node1      vs1.example.com policy1     10.1.1.2
node2      vs1.example.com policy1     10.1.1.2
----