---
permalink: nas-audit/display-fpolicy-policy-status-task.html 
sidebar: sidebar 
keywords: display, information, fpolicy, policy status 
summary: 'FPolicy 정책 상태에 대한 정보를 표시하여 정책이 사용되는지 여부, 외부 엔진이 사용하도록 구성되었는지, 정책의 시퀀스 번호가 무엇인지, FPolicy 정책이 어떤 스토리지 가상 머신(SVM)과 연결되어 있는지 확인할 수 있습니다.' 
---
= FPolicy 정책 상태에 대한 정보를 표시합니다
:allow-uri-read: 


[role="lead"]
FPolicy 정책 상태에 대한 정보를 표시하여 정책이 사용되는지 여부, 외부 엔진이 사용하도록 구성되었는지, 정책의 시퀀스 번호가 무엇인지, FPolicy 정책이 어떤 스토리지 가상 머신(SVM)과 연결되어 있는지 확인할 수 있습니다.

매개 변수를 지정하지 않으면 다음 정보가 표시됩니다.

* SVM 이름
* 정책 이름입니다
* 정책 시퀀스 번호입니다
* 정책 상태입니다


클러스터 또는 특정 SVM에 구성된 FPolicy 정책의 정책 상태에 대한 정보를 표시할 뿐만 아니라 명령 매개 변수를 사용하여 명령 출력을 다른 기준으로 필터링할 수 있습니다.

나열된 정책에 대한 자세한 정보를 표시하려면 '-instance' 매개 변수를 지정할 수 있습니다. 또는 '-fields' 매개 변수를 사용하여 명령 출력 또는 '-fields?'에 표시된 필드만 표시할 수 있습니다 사용할 수 있는 필드를 결정합니다.

.단계
. 적절한 명령을 사용하여 FPolicy 정책 상태에 대한 필터링된 정보를 표시합니다.
+
[cols="35,65"]
|===


| 정책에 대한 상태 정보를 표시하려면... | 명령 입력... 


 a| 
클러스터에서
 a| 
'vserver FPolicy show'



 a| 
지정한 상태를 가진 사용자
 a| 
'vserver FPolicy show -status{on|off}'



 a| 
SVM을 지정합니다
 a| 
'vserver FPolicy show -vserver vserver_name'을 선택합니다



 a| 
지정된 정책 이름을 가진
 a| 
'vserver FPolicy show-policy-name policy_name'입니다



 a| 
지정된 외부 엔진을 사용합니다
 a| 
'vserver FPolicy show - engine engine_name'

|===


다음 예는 클러스터의 FPolicy 정책에 대한 정보를 표시합니다.

[listing]
----

cluster1::> vserver fpolicy show
                                        Sequence
Vserver             Policy Name           Number  Status      Engine
------------------- ------------------- --------  ---------   ---------
FPolicy             cserver_policy      -         off         eng1
vs1.example.com     v1p1                -         off         eng2
vs1.example.com     v1p2                -         off         native
vs1.example.com     v1p3                -         off         native
vs1.example.com     cserver_policy      -         off         eng1
vs2.example.com     v1p1                3         on          native
vs2.example.com     v1p2                1         on          eng3
vs2.example.com     cserver_policy      2         on          eng1
----