---
permalink: nas-audit/fpolicy-external-engine-config-worksheet-reference.html 
sidebar: sidebar 
keywords: complete, fpolicy, external engine, configuration, worksheet 
summary: 이 워크시트를 사용하여 FPolicy 외부 엔진 구성 프로세스 중에 필요한 값을 기록할 수 있습니다. 매개 변수 값이 필요한 경우 외부 엔진을 구성하기 전에 해당 매개 변수에 사용할 값을 결정해야 합니다. 
---
= FPolicy 외부 엔진 구성 워크시트를 작성합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
이 워크시트를 사용하여 FPolicy 외부 엔진 구성 프로세스 중에 필요한 값을 기록할 수 있습니다. 매개 변수 값이 필요한 경우 외부 엔진을 구성하기 전에 해당 매개 변수에 사용할 값을 결정해야 합니다.



== 기본 외부 엔진 구성에 대한 정보

각 매개 변수 설정을 외부 엔진 구성에 포함할지 여부를 기록한 다음 포함하려는 매개 변수의 값을 기록해야 합니다.

[cols="40,20,20,20"]
|===


| 정보 유형입니다 | 필수 요소입니다 | 포함 | 당신의 가치 


 a| 
스토리지 가상 시스템(SVM) 이름
 a| 
예
 a| 
예
 a| 



 a| 
엔진 이름입니다
 a| 
예
 a| 
예
 a| 



 a| 
기본 FPolicy 서버
 a| 
예
 a| 
예
 a| 



 a| 
포트 번호입니다
 a| 
예
 a| 
예
 a| 



 a| 
2차 FPolicy 서버
 a| 
아니요
 a| 
 a| 



 a| 
외부 엔진 유형
 a| 
아니요
 a| 
 a| 



 a| 
외부 FPolicy 서버와의 통신에 사용되는 SSL 옵션입니다
 a| 
예
 a| 
예
 a| 



 a| 
인증서 FQDN 또는 사용자 지정 일반 이름입니다
 a| 
아니요
 a| 
 a| 



 a| 
인증서 일련 번호입니다
 a| 
아니요
 a| 
 a| 



 a| 
인증 기관
 a| 
아니요
 a| 
 a| 



 a| 
외부 엔진 형식

ONTAP 9.11.1부터 기본 XML이 아닌 '프로토타입'을 지정할 수 있습니다.
 a| 
아니요
 a| 
 a| 

|===


== 고급 외부 엔진 매개 변수에 대한 정보입니다

고급 매개 변수를 사용하여 외부 엔진을 구성하려면 고급 권한 모드에서 구성 명령을 입력해야 합니다.

[cols="40,20,20,20"]
|===


| 정보 유형입니다 | 필수 요소입니다 | 포함 | 당신의 가치 


 a| 
요청 취소 시간이 초과되었습니다
 a| 
아니요
 a| 
 a| 



 a| 
요청 중단 시간 초과
 a| 
아니요
 a| 
 a| 



 a| 
상태 요청 전송 간격입니다
 a| 
아니요
 a| 
 a| 



 a| 
FPolicy 서버에서 최대 미해결 요청을 사용합니다
 a| 
아니요
 a| 
 a| 



 a| 
응답하지 않는 FPolicy 서버의 연결을 끊는 데 시간이 초과되었습니다
 a| 
아니요
 a| 
 a| 



 a| 
FPolicy 서버에 연결 유지 메시지를 보내는 간격
 a| 
아니요
 a| 
 a| 



 a| 
최대 재연결 시도 횟수
 a| 
아니요
 a| 
 a| 



 a| 
수신 버퍼 크기입니다
 a| 
아니요
 a| 
 a| 



 a| 
전송 버퍼 크기입니다
 a| 
아니요
 a| 
 a| 



 a| 
다시 연결하는 동안 세션 ID를 제거하는 데 시간이 초과되었습니다
 a| 
아니요
 a| 
 a| 

|===