---
permalink: nas-audit/fpolicy-manages-policy-processing-concept.html 
sidebar: sidebar 
keywords: fpolicy, manages, policy process 
summary: '스토리지 가상 시스템(SVM)에 여러 FPolicy 정책이 할당될 수 있으며 각 정책은 서로 다른 우선순위를 갖습니다. SVM에 적절한 FPolicy 구성을 생성하려면 FPolicy에서 정책 처리를 관리하는 방법을 이해하는 것이 중요합니다.' 
---
= FPolicy가 정책 처리를 관리하는 방법입니다
:icons: font
:imagesdir: ../media/


[role="lead"]
스토리지 가상 시스템(SVM)에 여러 FPolicy 정책이 할당될 수 있으며 각 정책은 서로 다른 우선순위를 갖습니다. SVM에 적절한 FPolicy 구성을 생성하려면 FPolicy에서 정책 처리를 관리하는 방법을 이해하는 것이 중요합니다.

각 파일 액세스 요청은 처음에 평가하여 이 이벤트를 모니터링하는 정책을 결정합니다. 모니터링되는 이벤트인 경우 관심 있는 정책과 함께 모니터링되는 이벤트에 대한 정보가 FPolicy로 전달되어 FPolicy가 평가됩니다. 각 정책은 할당된 우선 순위에 따라 평가됩니다.

정책을 구성할 때는 다음 권장 사항을 고려해야 합니다.

* 다른 정책보다 먼저 정책을 항상 평가하려면 우선 순위가 더 높은 정책을 구성합니다.
* 모니터링되는 이벤트에 대해 요청된 파일 액세스 작업의 성공이 다른 정책에 대해 평가된 파일 요청에 대한 사전 요구 사항이면 첫 번째 파일 작업의 성공 또는 실패를 보다 높은 우선 순위로 제어하는 정책을 지정합니다.
+
예를 들어, 하나의 정책이 FPolicy 파일 아카이빙 및 복원 기능을 관리하고 두 번째 정책이 온라인 파일의 파일 액세스 작업을 관리하는 경우, 파일 복원을 관리하는 정책은 우선 순위가 더 높아야 두 번째 정책에 의해 관리되는 작업을 허용하기 전에 파일을 복원할 수 있습니다.

* 파일 액세스 작업에 적용할 수 있는 모든 정책을 평가하려면 동기 정책을 낮은 우선 순위로 지정합니다.


정책 시퀀스 번호를 수정하여 기존 정책에 대한 정책 우선 순위를 다시 정렬할 수 있습니다. 하지만 FPolicy에서 수정된 우선 순위 순서에 따라 정책을 평가하도록 하려면 수정된 시퀀스 번호를 사용하여 정책을 사용하지 않도록 설정하고 다시 활성화해야 합니다.
