---
permalink: nas-audit/fpolicy-passthrough-read-enhances-usability-concept.html 
sidebar: sidebar 
keywords: fpolicy, passthrough-read, enhances, usability, hierarchical, storage management 
summary: '패스스루 읽기를 통해 FPolicy 서버(계층적 스토리지 관리(HSM) 서버로 작동)가 보조 스토리지 시스템에서 기본 스토리지 시스템으로 파일을 리콜하지 않고 오프라인 파일에 대한 읽기 액세스를 제공할 수 있습니다.' 
---
= FPolicy 패스스루 읽기를 통해 어떻게 계층적 스토리지 관리의 사용성을 개선합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
패스스루 읽기를 통해 FPolicy 서버(계층적 스토리지 관리(HSM) 서버로 작동)가 보조 스토리지 시스템에서 기본 스토리지 시스템으로 파일을 리콜하지 않고 오프라인 파일에 대한 읽기 액세스를 제공할 수 있습니다.

FPolicy 서버가 SMB 서버에 상주하는 파일에 HSM을 제공하도록 구성된 경우, 파일이 보조 스토리지에 오프라인으로 저장되고 스텁 파일만 운영 스토리지에 남아 있는 경우 정책 기반 파일 마이그레이션이 발생합니다. 스텁 파일이 클라이언트에 일반 파일로 나타나지만 실제로는 원본 파일의 크기가 같은 스파스 파일입니다. 스파스 파일에는 SMB 오프라인 비트 세트가 있고 보조 스토리지로 마이그레이션된 실제 파일을 가리킵니다.

일반적으로 오프라인 파일에 대한 읽기 요청이 수신되면 요청된 콘텐츠를 운영 스토리지로 다시 리콜한 다음 운영 스토리지를 통해 액세스해야 합니다. 데이터를 기본 스토리지로 다시 불러내야 할 경우 좋지 않은 영향을 몇 가지 일으킬 수 있습니다. 원치 않는 결과 중 하나는 요청에 응답하기 전에 콘텐츠를 다시 불러와야 하는 필요성과 기본 스토리지의 리콜 대상 파일에 필요한 공간 소비가 증가했기 때문에 발생하는 클라이언트 요청에 대한 지연 시간이 늘어난 것입니다.

FPolicy 패스스루 읽기를 사용하면 HSM 서버(FPolicy 서버)에서 2차 스토리지 시스템에서 1차 스토리지 시스템으로 파일을 리콜하지 않고 마이그레이션된 오프라인 파일에 대한 읽기 액세스를 제공할 수 있습니다. 파일을 운영 스토리지로 다시 호출하는 대신 읽기 요청을 보조 스토리지에서 직접 처리할 수 있습니다.

[NOTE]
====
ODX(복사 오프로드)는 FPolicy 패스스루 읽기 작업에서 지원되지 않습니다.

====
PassThrough-read는 다음과 같은 이점을 제공하여 유용성을 향상시킵니다.

* 운영 스토리지에 요청된 데이터를 운영 스토리지로 다시 불러올 공간이 충분하지 않은 경우에도 읽기 요청을 처리할 수 있습니다.
* 스크립트 또는 백업 솔루션에서 많은 오프라인 파일에 액세스해야 하는 경우와 같이 데이터 리콜이 급증할 수 있는 경우 용량과 성능을 더욱 효과적으로 관리할 수 있습니다.
* 스냅샷 복사본의 오프라인 파일에 대한 읽기 요청을 처리할 수 있습니다.
+
스냅샷 복사본은 읽기 전용이므로 스텁 파일이 스냅샷 복사본에 있는 경우 FPolicy 서버가 원래 파일을 복원할 수 없습니다. 패스스루 읽기를 사용하면 이 문제가 해결됩니다.

* 보조 스토리지의 파일에 대한 액세스를 통해 읽기 요청을 처리하고 오프라인 파일을 운영 스토리지로 리콜해야 하는 시기를 제어하는 정책을 설정할 수 있습니다.
+
예를 들어, HSM 서버에서 파일을 운영 스토리지로 다시 마이그레이션하기 전에 지정된 시간 내에 오프라인 파일에 액세스할 수 있는 횟수를 지정하는 정책을 생성할 수 있습니다. 이 유형의 정책은 거의 액세스하지 않는 파일을 리콜하지 않습니다.





== FPolicy 패스스루 읽기가 활성화된 경우 읽기 요청이 관리되는 방법입니다

FPolicy 패스스루 읽기를 사용하도록 설정한 경우 스토리지 가상 시스템(SVM)과 FPolicy 서버 간의 연결을 최적으로 구성할 수 있도록 읽기 요청이 관리되는 방식을 이해해야 합니다.

FPolicy 패스스루 읽기를 사용하고 SVM이 오프라인 파일에 대한 요청을 받으면 FPolicy가 표준 연결 채널을 통해 FPolicy 서버(HSM 서버)에 알림을 보냅니다.

알림을 수신한 FPolicy 서버는 알림에 전송된 파일 경로에서 데이터를 읽고, SVM과 FPolicy 서버 사이에 설정된 패스스루 읽기 전용 데이터 연결을 통해 SVM으로 요청된 데이터를 보냅니다.

데이터가 전송된 후 FPolicy 서버는 읽기 요청에 대해 허용 또는 거부로 응답합니다. 읽기 요청의 허용 또는 거부 여부에 따라 ONTAP는 요청된 정보를 보내거나 클라이언트에 오류 메시지를 보냅니다.
