---
permalink: nas-audit/plan-fpolicy-external-engine-config-concept.html 
sidebar: sidebar 
keywords: plan, fpolicy, external engine, configuration 
summary: 'FPolicy 외부 엔진(외부 엔진)을 구성하기 전에 외부 엔진을 생성하는 것이 무엇을 의미하는지 및 사용 가능한 구성 매개 변수를 이해해야 합니다. 이 정보는 각 매개변수에 대해 설정할 값을 결정하는 데 도움이 됩니다.' 
---
= FPolicy 외부 엔진 구성을 계획하십시오
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
FPolicy 외부 엔진(외부 엔진)을 구성하기 전에 외부 엔진을 생성하는 것이 무엇을 의미하는지 및 사용 가능한 구성 매개 변수를 이해해야 합니다. 이 정보는 각 매개변수에 대해 설정할 값을 결정하는 데 도움이 됩니다.



== FPolicy 외부 엔진을 생성할 때 정의되는 정보입니다

외부 엔진 구성에서는 FPolicy가 다음 정보를 포함하여 외부 FPolicy 서버(FPolicy 서버)에 연결하고 관리하는 데 필요한 정보를 정의합니다.

* SVM 이름
* 엔진 이름입니다
* 기본 및 보조 FPolicy 서버의 IP 주소와 FPolicy 서버에 연결할 때 사용할 TCP 포트 번호입니다
* 엔진 유형이 비동기식인지 동기식인지 여부
* 노드와 FPolicy 서버 간의 연결을 인증하는 방법
+
상호 SSL 인증을 구성하도록 선택한 경우 SSL 인증서 정보를 제공하는 매개 변수도 구성해야 합니다.

* 다양한 고급 권한 설정을 사용하여 연결을 관리하는 방법
+
여기에는 시간 초과 값, 재시도 값, 연결 유지 값, 최대 요청 값, 전송 및 수신 버퍼 크기 값, 세션 시간 초과 값 등을 정의하는 매개 변수가 포함됩니다.

* 외부 엔진에 전송된 Fpolicy notification 메시지의 형식입니다


'vserver FPolicy policy external-engine create' 명령은 FPolicy 외부 엔진을 생성하는 데 사용됩니다.



== 기본 외부 엔진 매개 변수는 무엇입니까

다음 기본 FPolicy 구성 매개 변수 표를 사용하여 구성을 계획할 수 있습니다.

[cols="70,30"]
|===


| 정보 유형입니다 | 옵션을 선택합니다 


 a| 
SVM _

이 외부 엔진과 연결할 SVM 이름을 지정합니다.

각 FPolicy 구성은 단일 SVM 내에서 정의됩니다. FPolicy 정책 구성을 생성하기 위해 함께 조합되는 외부 엔진, 정책 이벤트, 정책 범위 및 정책은 모두 동일한 SVM과 연결되어야 합니다.
 a| 
'-vserver''vserver_name'



 a| 
_ 엔진 이름 _

외부 엔진 구성에 할당할 이름을 지정합니다. 나중에 FPolicy 정책을 생성할 때 외부 엔진 이름을 지정해야 합니다. 이렇게 하면 외부 엔진이 정책에 연결됩니다.

이름은 최대 256자까지 입력할 수 있습니다.

[NOTE]
====
MetroCluster 또는 SVM 재해 복구 구성에서 외부 엔진 이름을 구성하는 경우 최대 200자의 이름을 입력해야 합니다.

====
이름에는 다음 ASCII 범위 문자의 조합을 사용할 수 있습니다.

* "A" ~ "z"
* A부터 Z까지
* 0에서 9까지
* ""_","-",""."

 a| 
엔진-이름 엔진_이름



 a| 
_1차 FPolicy 서버 _

노드가 특정 FPolicy 정책에 대한 알림을 보내는 기본 FPolicy 서버를 지정합니다. 값은 쉼표로 구분된 IP 주소 목록으로 지정됩니다.

둘 이상의 기본 서버 IP 주소가 지정된 경우 SVM이 참여하는 모든 노드에서 정책이 활성화된 시점에 지정된 모든 기본 FPolicy 서버에 대한 제어 연결을 생성합니다. 여러 기본 FPolicy 서버를 구성하는 경우 라운드 로빈 방식으로 FPolicy 서버에 알림이 전송됩니다.

외부 엔진이 MetroCluster 또는 SVM 재해 복구 구성에 사용되는 경우 소스 사이트에 있는 FPolicy 서버의 IP 주소를 1차 서버로 지정해야 합니다. 대상 사이트에 있는 FPolicy 서버의 IP 주소를 2차 서버로 지정해야 합니다.
 a| 
'-primary-servers''ip_address',...



 a| 
_ 포트 번호 _

FPolicy 서비스의 포트 번호를 지정합니다.
 a| 
'-port' 정수



 a| 
_보조 FPolicy 서버 _

지정된 FPolicy 정책에 대해 파일 액세스 이벤트를 보낼 보조 FPolicy 서버를 지정합니다. 값은 쉼표로 구분된 IP 주소 목록으로 지정됩니다.

보조 서버는 운영 서버에 연결할 수 없는 경우에만 사용됩니다. 정책이 활성화되면 보조 서버에 대한 연결이 설정되지만, 운영 서버에 연결할 수 있는 서버가 없는 경우에만 보조 서버로 알림이 전송됩니다. 여러 2차 서버를 구성하는 경우 통지는 라운드 로빈 방식으로 FPolicy 서버로 전송됩니다.
 a| 
'-secondary-servers''ip_address',...



 a| 
_외부 엔진 유형 _

외부 엔진이 동기식 또는 비동기식 모드로 작동할지 여부를 지정합니다. 기본적으로 FPolicy는 동기식 모드에서 작동합니다.

'동기식'으로 설정하면 파일 요청 처리가 FPolicy 서버에 알림을 전송하고 FPolicy 서버로부터 응답을 받을 때까지 계속되지 않습니다. 이 시점에서 FPolicy 서버의 응답이 요청된 작업을 허용하는지 여부에 따라 요청 흐름이 계속 진행되거나 처리 결과가 거부됩니다.

'비동기'로 설정하면 파일 요청 처리가 FPolicy 서버에 알림을 보낸 다음 계속됩니다.
 a| 
'-extern-engine-type ''external_engine_type' 이 파라미터의 값은 다음 중 하나일 수 있습니다.

* '동기식'
* 비동기식




 a| 
_FPolicy 서버와 통신하기 위한 _SSL 옵션 _

FPolicy 서버와의 통신에 사용되는 SSL 옵션을 지정합니다. 필수 매개 변수입니다. 다음 정보를 기반으로 옵션 중 하나를 선택할 수 있습니다.

* no-auth로 설정하면 인증이 발생하지 않습니다.
+
통신 링크는 TCP를 통해 설정됩니다.

* 'server-auth'로 설정하면 SVM은 SSL 서버 인증을 사용하여 FPolicy 서버를 인증합니다.
* '이중 인증'으로 설정하면 SVM과 FPolicy 서버 간에 상호 인증이 수행됩니다. SVM은 FPolicy 서버를 인증하고 FPolicy 서버는 SVM을 인증합니다.
+
상호 SSL 인증을 구성하려면 '-certificate-common-name', '-certificate-serial', '-certificate-ca' 매개 변수도 구성해야 합니다.


 a| 
'-ssl-option'{'no-auth'|'server-auth'|'mutual-auth'}



 a| 
_인증서 FQDN 또는 사용자 정의 일반 이름 _

SVM과 FPolicy 서버 간의 SSL 인증이 구성된 경우 사용되는 인증서 이름을 지정합니다. 인증서 이름을 FQDN 또는 사용자 지정 일반 이름으로 지정할 수 있습니다.

'-ssl-option' 파라미터에 대해 'mutual-auth'를 지정하면 '-certificate-common-name' 파라미터에 대한 값을 지정해야 합니다.
 a| 
'-certificate-common-name' text'입니다



 a| 
_인증서 일련 번호 _

SVM과 FPolicy 서버 간의 SSL 인증이 구성된 경우 인증에 사용되는 인증서의 일련 번호를 지정합니다.

'-ssl-option' 파라미터에 대해 'mutual-auth'를 지정하면 '-certificate-serial' 파라미터에 대한 값을 지정해야 합니다.
 a| 
'-certificate-serial' text'입니다



 a| 
_인증 기관 _

SVM과 FPolicy 서버 간의 SSL 인증이 구성된 경우 인증에 사용되는 인증서의 CA 이름을 지정합니다.

'-ssl-option' 파라미터에 대해 'mutual-auth'를 지정하면 '-certificate-ca' 파라미터에 대한 값을 지정해야 합니다.
 a| 
``인증서-카’’’ 텍스트



 a| 
_외부 엔진 형식 _

외부 엔진에 전송되는 Fpolicy notification 메시지의 형식을 지정한다. 이 매개 변수의 기본값은 XML입니다.

ONTAP 9.11.1부터, 알림 메시지는 '프로토콜'이 지정되면 Google Prototupf를 사용하여 바이너리 형태로 인코딩될 수 있습니다. '프로토콜'을 설정하기 전에 Fpolicy 서버가 Prototupf deserialization도 지원하는지 확인하십시오.
 a| 
'[-extern-engine-format{xml|프로토콜}]'

|===


== 고급 외부 엔진 옵션은 무엇입니까

고급 매개 변수를 사용하여 구성을 사용자 지정할지 여부를 계획할 때 다음 고급 FPolicy 구성 매개 변수 테이블을 사용할 수 있습니다. 다음 매개 변수를 사용하여 클러스터 노드와 FPolicy 서버 간의 통신 동작을 수정합니다.

[cols="70,30"]
|===


| 정보 유형입니다 | 옵션을 선택합니다 


 a| 
요청 취소에 대한 시간 초과 _

FPolicy 서버에서 응답을 대기하는 시간 간격(시, 분, 초)을 지정합니다.

시간 초과 간격이 경과하면 노드가 FPolicy 서버로 취소 요청을 보냅니다. 그런 다음 노드가 대체 FPolicy 서버로 알림을 보냅니다. 이 시간 초과는 응답하지 않는 FPolicy 서버를 처리하는 데 도움이 되며 SMB/NFS 클라이언트 응답을 개선할 수 있습니다. 또한, 알림 요청이 다운/불량 FPolicy 서버에서 대체 FPolicy 서버로 이동되었기 때문에 시간 초과 후 요청을 취소하면 시스템 리소스를 해제하는 데 도움이 됩니다.

이 값의 범위는 0에서 100까지입니다. 값이 '0'으로 설정되어 있으면 이 옵션이 비활성화되고 요청 취소 메시지가 FPolicy 서버로 전송되지 않습니다. 기본값은 20입니다.
 a| 
'-reqs-cancel-timeout''integer'[h|m|s]



 a| 
_요청 중단을 위한 시간 초과 _

요청 중단 시 시간 제한(시), 분(분) 또는 초(초)을 지정합니다.

이 값의 범위는 0에서 200까지입니다.
 a| 
``reqs-abort-timeout''''integer'[h|m|s]



 a| 
_ 상태 요청 전송 간격 _

상태 요청을 FPolicy 서버로 전송한 후 시간('h'), 분(') 또는 초('') 단위로 간격을 지정합니다.

이 값의 범위는 0에서 50까지입니다. 이 값이 '0'으로 설정되어 있으면 옵션이 비활성화되고 상태 요청 메시지가 FPolicy 서버로 전송되지 않습니다. 기본값은 10입니다.
 a| 
'-status-req-interval''integer'[h|m|s]



 a| 
_FPolicy 서버의 최대 대기 요청 수 _

FPolicy 서버에서 대기할 수 있는 최대 대기 요청 수를 지정합니다.

이 값의 범위는 1부터 10000까지입니다. 기본값은 50입니다.
 a| 
'-max-server-reqs' 정수



 a| 
_응답하지 않는 FPolicy 서버 연결을 끊는 데 시간이 초과되었습니다

FPolicy 서버와의 연결이 종료된 후 시간 간격(시, 분, 초)을 지정합니다.

FPolicy 서버의 대기열에 허용되는 최대 요청이 포함되어 있고 제한 시간 내에 응답이 수신되지 않는 경우에만 제한 시간 이후에 연결이 종료됩니다. 허용되는 최대 요청 수는 '50'(기본값) 또는 'max-server-reqs-' 매개 변수에 지정된 숫자입니다.

이 값의 범위는 1에서 100까지입니다. 기본값은 60입니다.
 a| 
'-server-progress-timeout''integer'[h|m|s]



 a| 
_FPolicy server_에 연결 유지 메시지를 보내는 간격

FPolicy 서버에 연결 유지 메시지가 전송되는 시간 간격(시), 분(분) 또는 초(초)을 지정합니다.

연결 유지 메시지는 반개방 연결을 감지합니다.

이 값의 범위는 10에서 600까지입니다. 이 값이 '0'으로 설정되어 있으면 이 옵션이 비활성화되고 Keep-alive 메시지가 FPolicy 서버로 전송되지 않습니다. 기본값은 120입니다.
 a| 
'-keep-alive-interval -''integer'[h|m|s]



 a| 
_최대 재연결 시도 횟수 _

연결이 끊어진 후 SVM이 FPolicy 서버에 다시 연결하려고 시도하는 최대 횟수를 지정합니다.

이 값의 범위는 0에서 20까지입니다. 기본값은 5입니다.
 a| 
'-max-connection-retries' 정수



 a| 
수신 버퍼 크기 _

FPolicy 서버에 대해 연결된 소켓의 수신 버퍼 크기를 지정합니다.

기본값은 256KB(킬로바이트)로 설정됩니다. 이 값을 0으로 설정하면 수신 버퍼의 크기가 시스템에서 정의한 값으로 설정됩니다.

예를 들어, 소켓의 기본 수신 버퍼 크기가 65536바이트인 경우 조정 가능한 값을 0으로 설정하면 소켓 버퍼 크기는 65536바이트로 설정됩니다. 기본값이 아닌 값을 사용하여 수신 버퍼의 크기(바이트)를 설정할 수 있습니다.
 a| 
'-recv-buffer-size' 정수



 a| 
_ 버퍼 크기 전송 _

FPolicy 서버에 대해 연결된 소켓의 전송 버퍼 크기를 지정합니다.

기본값은 256KB(킬로바이트)로 설정됩니다. 이 값을 0으로 설정하면 전송 버퍼의 크기가 시스템에서 정의한 값으로 설정됩니다.

예를 들어, 조정 가능한 값을 0으로 설정하여 소켓의 기본 전송 버퍼 크기가 65536바이트로 설정된 경우 소켓 버퍼 크기는 65536바이트로 설정됩니다. 기본값이 아닌 값을 사용하여 전송 버퍼의 크기(바이트)를 설정할 수 있습니다.
 a| 
send-buffer-size 정수



 a| 
_재연결 중 세션 ID를 제거하는 데 시간이 초과되었습니다

재연결 시도 중에 새 세션 ID가 FPolicy 서버로 전송되는 시간(시), 분(분) 또는 초(초) 단위로 지정합니다.

스토리지 컨트롤러와 FPolicy 서버 간의 연결이 종료되고 '-session-timeout' 간격 내에 다시 연결되면 이전 세션 ID가 FPolicy 서버로 전송되어 이전 알림에 대한 응답을 보낼 수 있습니다.

기본값은 10초로 설정됩니다.
 a| 
'- session-timeout'['integer' h]['integer' m.]['integer''seger']

|===