---
permalink: nas-audit/plan-fpolicy-policy-config-concept.html 
sidebar: sidebar 
keywords: plan, fpolicy, policy, configuration 
summary: FPolicy 정책을 구성하기 전에 정책을 생성할 때 어떤 매개 변수가 필요한지, 그리고 특정 선택적 매개 변수를 구성해야 하는 이유를 이해해야 합니다. 이 정보는 각 매개변수에 대해 설정할 값을 결정하는 데 도움이 됩니다. 
---
= FPolicy 정책 구성 개요를 계획하십시오
:icons: font
:imagesdir: ../media/


[role="lead"]
FPolicy 정책을 구성하기 전에 정책을 생성할 때 어떤 매개 변수가 필요한지, 그리고 특정 선택적 매개 변수를 구성해야 하는 이유를 이해해야 합니다. 이 정보는 각 매개변수에 대해 설정할 값을 결정하는 데 도움이 됩니다.

FPolicy 정책을 생성할 때 정책을 다음과 연계합니다.

* 스토리지 가상 시스템(SVM)
* 하나 이상의 FPolicy 이벤트입니다
* FPolicy 외부 엔진


또한 몇 가지 선택적 정책 설정을 구성할 수도 있습니다.



== FPolicy 정책 구성에 포함되는 내용

다음 사용 가능한 FPolicy 정책 목록과 선택적 매개 변수를 사용하여 구성을 계획할 수 있습니다.

[cols="40,20,20,20"]
|===


| 정보 유형입니다 | 옵션을 선택합니다 | 필수 요소입니다 | 기본값 


 a| 
_SVM 이름 _

FPolicy 정책을 생성할 SVM의 이름을 지정합니다.
 a| 
'-vserver''vserver_name'
 a| 
예
 a| 
없음



 a| 
_정책 이름 _

FPolicy 정책의 이름을 지정합니다.

이름은 최대 256자까지 입력할 수 있습니다.

[NOTE]
====
MetroCluster 또는 SVM 재해 복구 구성에서 정책을 구성하는 경우 이름은 최대 200자가 되어야 합니다.

====
이름에는 다음 ASCII 범위 문자의 조합을 사용할 수 있습니다.

* "A" ~ "z"
* A부터 Z까지
* 0에서 9까지
* ""_","-",""."

 a| 
정책-이름 정책_이름
 a| 
예
 a| 
없음



 a| 
_ 이벤트 이름 _

FPolicy 정책에 연결할 쉼표로 구분된 이벤트 목록을 지정합니다.

* 둘 이상의 이벤트를 정책에 연결할 수 있습니다.
* 이벤트는 프로토콜에 따라 다릅니다.
* 단일 정책을 사용하여 정책이 모니터링할 각 프로토콜에 대한 이벤트를 생성한 다음 이벤트를 정책에 연결하여 둘 이상의 프로토콜에 대한 파일 액세스 이벤트를 모니터링할 수 있습니다.
* 이벤트가 이미 있어야 합니다.

 a| 
'-events''event_name',...
 a| 
예
 a| 
없음



 a| 
_외부 엔진 이름 _

FPolicy 정책에 연결할 외부 엔진의 이름을 지정합니다.

* 외부 엔진에는 FPolicy 서버로 알림을 보내는 데 필요한 정보가 노드에 포함되어 있습니다.
* FPolicy를 구성하여 단순한 파일 차단에 ONTAP 기본 외부 엔진을 사용하거나 외부 FPolicy 서버(FPolicy 서버)를 사용하여 보다 정교한 파일 차단 및 파일 관리를 위해 구성된 외부 엔진을 사용할 수 있습니다.
* 네이티브 외부 엔진을 사용하려면 이 매개 변수의 값을 지정하지 않거나 값으로 'native'를 지정할 수 있습니다.
* FPolicy 서버를 사용하려면 외부 엔진에 대한 구성이 이미 있어야 합니다.

 a| 
엔진 엔진 엔진 이름
 a| 
예(정책에서 내부 ONTAP 기본 엔진을 사용하지 않는 경우)
 a| 
네이티브입니다



 a| 
_ 은(는) 필수 스크리닝 필수 항목입니다. _

필수 파일 액세스 스크리닝이 필요한지 여부를 지정합니다.

* 필수 선별 설정은 기본 및 보조 서버가 모두 중단되거나 지정된 시간 제한 시간 내에 FPolicy 서버로부터 응답이 없을 경우 파일 액세스 이벤트에 대해 수행되는 작업을 결정합니다.
* true로 설정하면 파일 액세스 이벤트가 거부됩니다.
* false로 설정하면 파일 액세스 이벤트가 허용됩니다.

 a| 
'-is-mandatory'{'true'|'false'}
 a| 
아니요
 a| 
"참"입니다



 a| 
권한 있는 액세스 허용 _

FPolicy 서버에서 권한이 있는 데이터 연결을 사용하여 모니터링되는 파일 및 폴더에 대한 액세스 권한을 부여할지 여부를 지정합니다.

구성된 경우 FPolicy 서버는 권한 있는 데이터 연결을 사용하여 모니터링되는 데이터가 포함된 SVM의 루트에서 파일에 액세스할 수 있습니다.

특별 권한 데이터 액세스를 위해서는 클러스터에서 CIFS 라이센스가 있어야 하며 FPolicy 서버에 연결하는 데 사용되는 모든 데이터 LIF는 허용되는 프로토콜 중 하나로 'CIFS'를 사용하도록 구성해야 합니다.

특별 권한 액세스를 허용하도록 정책을 구성하려면 FPolicy 서버가 권한 액세스에 사용할 계정의 사용자 이름도 지정해야 합니다.
 a| 
'-allow-privileged-access' {'yes'|'no'}
 a| 
아니요(패스스루 읽기가 활성화되지 않은 경우)
 a| 
아니



 a| 
_특별 권한 사용자 이름 _

FPolicy 서버가 권한 있는 데이터 액세스에 사용하는 계정의 사용자 이름을 지정합니다.

* 이 매개 변수의 값은 "domain\user name" 형식을 사용해야 합니다.
* '-allow-privileged-access'가 no로 설정되어 있으면 이 파라미터에 설정된 값이 무시됩니다.

 a| 
'-privileged-user-name' user_name
 a| 
아니요(권한 있는 액세스가 활성화되지 않은 경우)
 a| 
없음



 a| 
통과 허용 - 읽기 _

FPolicy 서버가 FPolicy 서버에서 2차 스토리지(오프라인 파일)에 아카이빙된 파일에 대해 패스스루 읽기 서비스를 제공할 수 있는지 여부를 지정합니다.

* 패스스루 읽기는 데이터를 운영 스토리지로 복원하지 않고 오프라인 파일의 데이터를 읽는 방법입니다.
+
PassThrough-read는 읽기 요청에 응답하기 전에 파일을 운영 스토리지에 다시 호출할 필요가 없기 때문에 응답 대기 시간을 줄입니다. 또한 패스스루 읽기를 통해 읽기 요청을 충족하기 위해 리콜된 파일에만 운영 스토리지 공간을 사용할 필요가 없으므로 스토리지 효율성을 최적화합니다.

* 이 기능을 사용하도록 설정하면 FPolicy 서버에서 통과 읽기를 위해 특별히 연 별도의 권한 데이터 채널을 통해 파일에 대한 데이터를 제공합니다.
* 패스스루 읽기를 구성하려면 권한 있는 액세스를 허용하도록 정책도 구성해야 합니다.

 a| 
'-is-passstrough-read-enabled'{'true'|'false'}
 a| 
아니요
 a| 
거짓입니다

|===