---
permalink: nas-audit/plan-auditing-config-concept.html 
sidebar: sidebar 
keywords: plan, audit, configuration, svm, rotate, logs, size, schedule, rotation, dr, disaster recovery 
summary: 'SVM(스토리지 가상 시스템)에 대한 감사를 구성하기 전에 사용 가능한 구성 옵션을 파악하고 각 옵션에 설정할 값을 계획해야 합니다. 이 정보는 비즈니스 요구 사항에 맞는 감사 구성을 구성하는 데 도움이 됩니다.' 
---
= 감사 구성을 계획합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SVM(스토리지 가상 시스템)에 대한 감사를 구성하기 전에 사용 가능한 구성 옵션을 파악하고 각 옵션에 설정할 값을 계획해야 합니다. 이 정보는 비즈니스 요구 사항에 맞는 감사 구성을 구성하는 데 도움이 됩니다.

모든 감사 구성에 공통적으로 적용되는 특정 구성 매개 변수가 있습니다.

또한 통합 및 변환된 감사 로그를 회전할 때 사용할 메서드를 지정하는 데 사용할 수 있는 특정 매개 변수가 있습니다. 감사를 구성할 때 다음 세 가지 방법 중 하나를 지정할 수 있습니다.

* 로그 크기에 따라 로그를 회전합니다
+
로그를 회전시키는 데 사용되는 기본 방법입니다.

* 일정에 따라 로그를 회전합니다
* 로그 크기 및 일정에 따라 로그 회전(먼저 발생하는 이벤트)


[NOTE]
====
로그 회전 방법 중 하나 이상이 항상 설정되어야 합니다.

====


== 모든 감사 구성에 공통으로 사용되는 매개 변수입니다

감사 구성을 만들 때 지정해야 하는 필수 매개 변수는 두 가지입니다. 다음 세 가지 옵션 매개 변수도 지정할 수 있습니다.

[cols="40,30,10,10,10"]
|===


| 정보 유형입니다 | 옵션을 선택합니다 | 필수 요소입니다 | 포함 | 당신의 가치 


 a| 
_SVM 이름 _

감사 구성을 생성할 SVM의 이름입니다. SVM이 이미 존재해야 합니다.
 a| 
'-vserver''vserver_name'
 a| 
예
 a| 
예
 a| 



 a| 
_로그 대상 경로 _

변환된 감사 로그가 저장되는 디렉토리, 일반적으로 전용 볼륨 또는 qtree를 지정합니다. 경로는 SVM 네임스페이스에 이미 존재해야 합니다.

경로는 최대 864자까지 가능하며 읽기-쓰기 권한이 있어야 합니다.

경로가 유효하지 않으면 감사 구성 명령이 실패합니다.

SVM이 SVM 재해 복구 소스인 경우 로그 타겟 경로가 루트 볼륨에 있을 수 없습니다. 루트 볼륨 컨텐츠가 재해 복구 대상에 복제되지 않기 때문입니다.

FlexCache 볼륨은 로그 대상(ONTAP 9.7 이상)으로 사용할 수 없습니다.
 a| 
목적지 텍스트
 a| 
예
 a| 
예
 a| 



 a| 
_ 감사할 이벤트의 범주 _

감사할 이벤트의 범주를 지정합니다. 다음 이벤트 범주를 감사할 수 있습니다.

* 파일 액세스 이벤트(SMB 및 NFSv4 모두)
* SMB 로그온 및 로그오프 이벤트
* 중앙 액세스 정책 스테이징 이벤트입니다
+
중앙 액세스 정책 스테이징 이벤트는 Windows 2012 Active Directory 도메인부터 사용할 수 있습니다.

* 비동기식 - 삭제
* 파일 공유 범주 이벤트입니다
* 정책 변경 이벤트를 감사합니다
* 로컬 사용자 계정 관리 이벤트입니다
* 보안 그룹 관리 이벤트입니다
* 인증 정책 변경 이벤트입니다


기본값은 파일 액세스 및 SMB 로그온 및 로그오프 이벤트를 감사하는 것입니다.

* 참고: * "cap-staging"을 이벤트 범주로 지정하려면 SVM에 SMB 서버가 있어야 합니다. SMB 서버에서 동적 액세스 제어를 사용하지 않고 감사 구성에서 중앙 액세스 정책 스테이징을 설정할 수 있지만, 동적 액세스 제어를 설정한 경우에만 중앙 액세스 정책 스테이징 이벤트가 생성됩니다. 동적 액세스 제어는 SMB 서버 옵션을 통해 활성화됩니다. 기본적으로 활성화되어 있지 않습니다.
 a| 
`-events` {`file-ops`|`cifs-logon-logoff`|`cap-staging`|`file-share`|`audit-policy-change`|`user-account`|`security-group`|`authorization-policy-change`|`async-delete`}
 a| 
아니요
 a| 
 a| 



 a| 
_로그 파일 출력 형식 _

감사 로그의 출력 형식을 결정합니다. 출력 형식은 ONTAP 관련 'XML' 또는 Microsoft Windows 'evtx' 로그 형식일 수 있습니다. 기본적으로 출력 형식은 evtx입니다.
 a| 
'-format '{'xml'|'evtx'}
 a| 
아니요
 a| 
 a| 



 a| 
_ 로그 파일 회전 제한 _

가장 오래된 로그 파일을 회전하기 전에 유지할 감사 로그 파일 수를 결정합니다. 예를 들어 5를 입력하면 마지막 5개의 로그 파일이 유지됩니다.

0 값은 모든 로그 파일이 보존됨을 나타냅니다. 기본값은 0입니다.
 a| 
회전한계 정수
 a| 
아니요
 a| 
 a| 

|===


== 감사 이벤트 로그를 회전할 시기를 결정하는 데 사용되는 매개 변수입니다

* 로그 크기에 따라 로그를 회전합니다 *

기본값은 크기에 따라 감사 로그를 회전하는 것입니다.

* 기본 로그 크기는 100MB입니다
* 기본 로그 회전 방법과 기본 로그 크기를 사용하려면 로그 회전을 위한 특정 매개 변수를 구성할 필요가 없습니다.
* 로그 크기만을 기준으로 감사 로그를 회전하려면 다음 명령을 사용하여 '-rotate-schedule-minute' 매개 변수를 'vserver audit modify -vs0 -destination/-rotate-schedule -minute-'로 설정하십시오


기본 로그 크기를 사용하지 않으려면 '-rotate-size' 매개 변수를 구성하여 사용자 지정 로그 크기를 지정할 수 있습니다.

[cols="40,30,10,10,10"]
|===


| 정보 유형입니다 | 옵션을 선택합니다 | 필수 요소입니다 | 포함 | 당신의 가치 


 a| 
_로그 파일 크기 제한 _

감사 로그 파일 크기 제한을 결정합니다.
 a| 
'-rotate-size'{'integer'[KB|MB|GB|TB|PB]}
 a| 
아니요
 a| 
 a| 

|===
* 일정에 따라 로그를 회전합니다 *

일정에 따라 감사 로그를 회전하도록 선택한 경우 시간 기반 회전 매개 변수를 조합하여 로그 회전을 예약할 수 있습니다.

* 시간 기반 회전을 사용하는 경우 '-rotate-schedule-minute' 매개변수는 필수입니다.
* 다른 모든 시간 기반 회전 매개변수는 옵션입니다.
* 회전 일정은 모든 시간 관련 값을 사용하여 계산됩니다.
+
예를 들어, '-rotate-schedule-minute' 매개 변수만 지정하면 감사 로그 파일은 모든 연도의 모든 월에 지정된 모든 요일에 지정된 분을 기준으로 회전합니다.

* 시간 기반 회전 매개 변수(예: '-rotate-schedule-month' 및 '-rotate-schedule-minutes')를 하나 또는 두 개만 지정하는 경우 모든 시간 동안 모든 요일에 지정한 분 값을 기준으로 로그 파일이 회전되며 지정된 개월 동안에만 회전됩니다.
+
예를 들어 월요일, 수요일 및 토요일은 오전 10시 30분에 월, 3월, 8월 중 감사 로그를 회전하도록 지정할 수 있습니다

* '-rotate-schedule-dayOfWeek' 및 '-rotate-schedule-day' 값을 모두 지정하면 독립적으로 간주됩니다.
+
예를 들어, `-rotate-schedule-dayOfWeek'를 금요일로 지정하고 '-rotate-schedule-day'를 13일로 지정하면 13일에 금요일이 아니라 지정한 달의 13일에 감사 로그가 회전합니다.

* 일정에 따라 감사 로그를 회전하려면 다음 명령을 사용하여 '-rotate-size' 매개 변수를 unset한다. 'vserver audit modify -vs0 -destination/-rotate -size-


다음 사용 가능한 감사 매개 변수 목록을 사용하여 감사 이벤트 로그 순환에 대한 일정을 구성하는 데 사용할 값을 결정할 수 있습니다.

[cols="40,30,10,10,10"]
|===


| 정보 유형입니다 | 옵션을 선택합니다 | 필수 요소입니다 | 포함 | 당신의 가치 


 a| 
_로그 순환 스케줄: 월 _

감사 로그 순환에 대한 월별 일정을 결정합니다.

유효한 값은 '1월'과 '모두'를 통해 '1월'입니다. 예를 들어 월 1월, 3월 및 8월 동안 감사 로그를 회전하도록 지정할 수 있습니다.
 a| 
'-rotate-schedule-month' chron_month'입니다
 a| 
아니요
 a| 
 a| 



 a| 
_Log 순환 스케줄: 요일 _

감사 로그 회전에 대한 일별(요일) 일정을 결정합니다.

유효한 값은 '어타데이', '올데이'입니다. 예를 들어 감사 로그를 화요일과 금요일 또는 모든 요일에 회전하도록 지정할 수 있습니다.
 a| 
'-rotate-schedule-dayOfWeek''chron_DayOfWeek'
 a| 
아니요
 a| 
 a| 



 a| 
_ 로그 순환 스케줄: 일 _

감사 로그 회전에 대한 월 일정 날짜를 결정합니다.

유효한 값은 1부터 31까지입니다. 예를 들어 감사 로그가 한 달의 10일과 20일 또는 한 달의 모든 일에 회전되도록 지정할 수 있습니다.
 a| 
'-rotate-schedule-day''chron_dayofmonth'
 a| 
아니요
 a| 
 a| 



 a| 
_ 로그 순환 스케줄: 시간 _

감사 로그를 회전하기 위한 시간별 스케줄을 결정합니다.

유효한 값의 범위는 0(자정)에서 23(오후 11:00)까지입니다. All을 지정하면 감사 로그가 1시간마다 회전합니다. 예를 들어 감사 로그를 6(오전 6) 및 18(오후 6:00)에 회전하도록 지정할 수 있습니다.
 a| 
'-rotate-schedule-hour''chron_hour'
 a| 
아니요
 a| 
 a| 



 a| 
_ 로그 회전 스케줄: 분 _

감사 로그를 회전하기 위한 분 일정을 결정합니다.

유효한 값의 범위는 0에서 59까지입니다. 예를 들어 30분에 감사 로그를 회전하도록 지정할 수 있습니다.
 a| 
'-rotate-schedule-minute''chron_minute'
 a| 
예, 스케줄 기반 로그 회전을 구성하는 경우, 그렇지 않으면 아니요
 a| 
 a| 

|===
* 로그 크기 및 일정에 따라 로그 회전 *

'-rotate-size' 매개변수와 시간 기반 회전 매개변수를 조합하여 로그 크기와 일정에 따라 로그 파일을 회전하도록 선택할 수 있습니다. 예를 들어, '-rotate-size'를 10MB로 설정하고 '-rotate-schedule-minute'를 15로 설정하면 로그 파일 크기가 10MB에 도달하거나 매 시간 15분(둘 중 먼저 발생하는 이벤트)에 도달할 때 로그 파일이 회전합니다.
