---
permalink: nas-audit/plan-fpolicy-event-config-concept.html 
sidebar: sidebar 
keywords: plan, fpolicy event configuration 
summary: FPolicy 이벤트를 구성하기 전에 FPolicy 이벤트가 생성하는 것이 무엇을 의미하는지 이해해야 합니다. 이벤트를 모니터링할 프로토콜, 모니터링할 이벤트 및 사용할 이벤트 필터를 결정해야 합니다. 이 정보는 설정할 값을 계획하는 데 도움이 됩니다. 
---
= FPolicy 이벤트 구성 개요를 계획하십시오
:icons: font
:imagesdir: ../media/


[role="lead"]
FPolicy 이벤트를 구성하기 전에 FPolicy 이벤트가 생성하는 것이 무엇을 의미하는지 이해해야 합니다. 이벤트를 모니터링할 프로토콜, 모니터링할 이벤트 및 사용할 이벤트 필터를 결정해야 합니다. 이 정보는 설정할 값을 계획하는 데 도움이 됩니다.



== FPolicy 이벤트를 생성하는 것은 의미입니다

FPolicy 이벤트를 생성한다는 것은 FPolicy 프로세스에서 모니터링할 파일 액세스 작업과 모니터링되는 이벤트 알림 중 외부 FPolicy 서버로 보내야 하는 정보를 정의하는 것입니다. FPolicy 이벤트 구성은 다음 구성 정보를 정의합니다.

* 스토리지 가상 시스템(SVM) 이름
* 이벤트 이름입니다
* 모니터링할 프로토콜
+
FPolicy는 SMB, NFSv3 및 NFSv4 파일 액세스 작업을 모니터링할 수 있습니다.

* 모니터링할 파일 작업
+
모든 파일 작업이 각 프로토콜에 유효한 것은 아닙니다.

* 구성할 파일 필터
+
특정 파일 작업 및 필터 조합만 유효합니다. 각 프로토콜에는 지원되는 고유한 조합 세트가 있습니다.

* 볼륨 마운트 및 마운트 해제 작업을 모니터링할지 여부


[NOTE]
====
세 가지 매개 변수(-protocol, -file-operations, -filters)에 대한 종속성이 있습니다. 다음 조합은 세 가지 매개 변수에 대해 유효합니다.

* '-protocol' 및 '-file-operations' 매개변수를 지정할 수 있습니다.
* 세 가지 매개 변수를 모두 지정할 수 있습니다.
* 매개 변수를 지정할 수 없습니다.


====


== FPolicy 이벤트 구성에 포함되는 내용

다음 가용 FPolicy 이벤트 구성 매개 변수 목록을 사용하여 구성을 계획할 수 있습니다.

[cols="70,30"]
|===


| 정보 유형입니다 | 옵션을 선택합니다 


 a| 
SVM _

이 FPolicy 이벤트와 연결할 SVM 이름을 지정합니다.

각 FPolicy 구성은 단일 SVM 내에서 정의됩니다. FPolicy 정책 구성을 생성하기 위해 함께 조합되는 외부 엔진, 정책 이벤트, 정책 범위 및 정책은 모두 동일한 SVM과 연결되어야 합니다.
 a| 
'-vserver''vserver_name'



 a| 
_ 이벤트 이름 _

FPolicy 이벤트에 할당할 이름을 지정합니다. FPolicy 정책을 생성할 때 FPolicy 이벤트를 이벤트 이름을 사용하여 정책에 연결합니다.

이름은 최대 256자까지 입력할 수 있습니다.

[NOTE]
====
MetroCluster 또는 SVM 재해 복구 구성에서 이벤트를 구성하는 경우 최대 200자의 이름을 입력해야 합니다.

====
이름에는 다음 ASCII 범위 문자의 조합을 사용할 수 있습니다.

* "A" ~ "z"
* A부터 Z까지
* 0에서 9까지
* ""_","-",""."

 a| 
이벤트-이름 이벤트_이름



 a| 
프로토콜 _

FPolicy 이벤트에 구성할 프로토콜을 지정합니다. '-protocol' 목록은 다음 값 중 하나를 포함할 수 있습니다.

* 'CIFS'입니다
* 'NFSv3'
* 'NFSv4


[NOTE]
====
'-protocol'을 지정하면 '-file-operations' 파라미터에 유효한 값을 지정해야 합니다. 프로토콜 버전이 변경되면 유효한 값이 변경될 수 있습니다.

==== a| 
프로토콜



 a| 
_ 파일 작업 _

FPolicy 이벤트에 대한 파일 작업 목록을 지정합니다.

이 이벤트는 '-protocol' 매개 변수에 지정된 프로토콜을 사용하여 모든 클라이언트 요청에서 이 목록에 지정된 작업을 확인합니다. 쉼표로 구분된 목록을 사용하여 하나 이상의 파일 작업을 나열할 수 있습니다. '-file-operations' 목록에는 다음 값 중 하나 이상이 포함될 수 있습니다.

* 파일 닫기 작업을 위해 '닫기'를 선택합니다
* 파일 작성 작업을 위한 '작성'입니다
* 디렉토리 생성 작업을 위한 'create-dir'
* 파일 삭제 작업의 경우 '삭제'를 선택합니다
* 디렉토리 삭제 작업의 경우 'Delete_dir'
* Get 특성 연산에 대한 GetAttr 입니다
* 링크 작동을 위한 링크
* 조회 연산에 대한 조회
* 파일 열기 작업을 위해 '열기'를 선택합니다
* 파일 읽기 작업에 대한 READ
* 파일 쓰기 작업에 대한 '쓰기'
* 파일 이름 바꾸기 작업에 대한 이름'입니다
* 디렉터리 이름 바꾸기 작업의 경우 RENAME_DIR입니다
* 셋트 특성 연산에 대한 '셋트'입니다
* 심볼 링크 작업을 위한 '대칭 링크'입니다


[NOTE]
====
'-file-operations'를 지정하면 '-protocol' 파라미터에 유효한 프로토콜을 지정해야 합니다.

==== a| 
'-파일-작업''파일_작업',...



 a| 
필터 _

지정된 프로토콜에 대해 지정된 파일 작업에 대한 필터 목록을 지정합니다. '-filters' 매개 변수의 값은 클라이언트 요청을 필터링하는 데 사용됩니다. 목록에는 다음 중 하나 이상이 포함될 수 있습니다.

[NOTE]
====
'-filters' 파라미터를 지정할 경우 '-file-operations' 및 '-protocol' 파라미터에 대한 유효한 값을 지정해야 합니다.

====
* 대체 데이터 스트림에 대한 클라이언트 요청을 필터링하는 모니터 광고 옵션
* 수정과 함께 닫기 위해 클라이언트 요청을 필터링하는 '수정 종료' 옵션.
* 수정하지 않고 클라이언트 요청을 필터링하는 '수정 없이 종료' 옵션.
* 첫 번째 읽기에 대한 클라이언트 요청을 필터링하는 '첫 번째 읽기' 옵션.
* 첫 번째 쓰기를 위해 클라이언트 요청을 필터링하는 '첫 번째 쓰기' 옵션.
* 오프라인 비트 세트에 대한 클라이언트 요청을 필터링하는 오프라인 비트 옵션입니다.
+
이 필터를 설정하면 FPolicy 서버에서 오프라인 파일에 액세스할 때만 알림을 받습니다.

* 삭제 의도로 개설된 클라이언트 요청을 필터링하는 'open-with-delete-intent' 옵션.
+
이 필터를 설정하면 FPolicy 서버에서 파일을 삭제하려고 할 때만 FPolicy 서버가 알림을 받게 됩니다. 'file_delete_on_close' 플래그가 지정된 경우 파일 시스템에서 사용됩니다.

* 클라이언트 요청을 쓰기 의도로 필터링하기 위한 "쓰기 의도로 열기" 옵션.
+
이 필터를 설정하면 FPolicy 서버에서 파일을 열려고 할 때만 알림을 받습니다.

* 크기 변경으로 클라이언트 쓰기 요청을 필터링하기 위한 Write-with-size-change 옵션.

 a| 
'-filters' 필터,...



 a| 
_Filters_continued

* 'SetAttr-with-owner-change' 옵션을 사용하여 파일 또는 디렉터리의 소유자 변경을 위한 클라이언트 SetAttr 요청을 필터링합니다.
* 파일 또는 디렉토리의 그룹을 변경하기 위한 클라이언트 SetAttr 요청을 필터링하는 'Setattr-with-group-change' 옵션
* 파일 또는 디렉터리에서 SACL을 변경하기 위한 클라이언트 SetAttr 요청을 필터링하는 'Setattr-with-SACL-change' 옵션입니다.
+
이 필터는 CIFS 및 NFSv4 프로토콜에만 사용할 수 있습니다.

* 파일 또는 디렉토리의 DACL 변경을 위한 클라이언트 SetAttr 요청을 필터링하는 'Setattr-with-DACL-change' 옵션.
+
이 필터는 CIFS 및 NFSv4 프로토콜에만 사용할 수 있습니다.

* 파일 또는 디렉토리의 수정 시간을 변경하기 위해 클라이언트 SetAttr 요청을 필터링하는 'Setattr-with-modify-time-change' 옵션.
* 파일 또는 디렉터리의 액세스 시간 변경을 위한 클라이언트 SetAttr 요청을 필터링하는 'Setattr-with-access-time-change' 옵션.
* 'Setattr-with-creation-time-change' 옵션을 사용하여 파일 또는 디렉토리의 생성 시간을 변경하기 위해 클라이언트 SetAttr 요청을 필터링합니다.
+
이 옵션은 CIFS 프로토콜에만 사용할 수 있습니다.

* 파일 또는 디렉토리의 모드 비트 변경을 위한 클라이언트 SetAttr 요청을 필터링하는 'Setattr-with-mode-change' 옵션.
* 파일 크기 변경에 대한 클라이언트 SetAttr 요청을 필터링하기 위한 'Metattr-with-size-change' 옵션입니다.
* 'etattr-with-allocation-size-change' 옵션을 사용하여 파일의 할당 크기를 변경하기 위해 클라이언트 SetAttr 요청을 필터링합니다.
+
이 옵션은 CIFS 프로토콜에만 사용할 수 있습니다.

* 디렉토리 작업에 대한 클라이언트 요청을 필터링하기 위한 'exclude-directory' 옵션입니다.
+
이 필터를 지정하면 디렉터리 작업이 모니터링되지 않습니다.


 a| 
'-filters' 필터,...



 a| 
_ 은(는) 볼륨 작업이 필요합니다. _

볼륨 마운트 및 마운트 해제 작업에 모니터링이 필요한지 여부를 지정합니다. 기본값은 false 입니다.
 a| 
'-볼륨-작동'{'참'|'거짓'}

|===