---
permalink: nas-audit/plan-fpolicy-scope-config-concept.html 
sidebar: sidebar 
keywords: plan, fpolicy, scope, configuration 
summary: FPolicy 범위를 구성하기 전에 범위를 생성하는 것이 무엇을 의미하는지 이해해야 합니다. 범위 구성에 포함된 내용을 이해해야 합니다. 또한 우선 순위 범위 규칙이 무엇인지 이해해야 합니다. 이 정보는 설정할 값을 계획하는 데 도움이 될 수 있습니다. 
---
= FPolicy 범위 구성 개요를 계획하십시오
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
FPolicy 범위를 구성하기 전에 범위를 생성하는 것이 무엇을 의미하는지 이해해야 합니다. 범위 구성에 포함된 내용을 이해해야 합니다. 또한 우선 순위 범위 규칙이 무엇인지 이해해야 합니다. 이 정보는 설정할 값을 계획하는 데 도움이 될 수 있습니다.



== FPolicy 범위를 생성하는 것은 의미입니다

FPolicy 범위를 만들려면 FPolicy 정책이 적용되는 경계를 정의해야 합니다. SVM(스토리지 가상 시스템)은 기본 경계입니다. FPolicy 정책의 범위를 생성할 때 적용되는 FPolicy 정책을 정의해야 하며 범위를 적용할 SVM을 지정해야 합니다.

지정된 SVM 내에서 범위를 더욱 제한하는 다양한 매개 변수가 있습니다. 범위에 포함할 항목을 지정하거나 범위에서 제외할 항목을 지정하여 범위를 제한할 수 있습니다. 설정된 정책에 범위를 적용하면 이 명령에 의해 정의된 범위에 정책 이벤트 검사가 적용됩니다.

""포함" 옵션에서 일치하는 파일 액세스 이벤트에 대한 알림이 생성됩니다. ""제외" 옵션에서 일치하는 파일 액세스 이벤트에 대한 알림이 생성되지 않습니다.

FPolicy 범위 구성은 다음 구성 정보를 정의합니다.

* SVM 이름
* 정책 이름입니다
* 모니터링되는 항목을 포함하거나 제외할 공유입니다
* 모니터링할 항목을 포함하거나 제외할 내보내기 정책입니다
* 모니터링되는 항목을 포함하거나 제외할 볼륨입니다
* 모니터링되는 항목을 포함하거나 제외할 파일 확장입니다
* 디렉토리 객체에 대한 파일 확장자 검사 수행 여부


[NOTE]
====
클러스터 FPolicy 정책 범위에는 특별히 고려해야 할 사항이 있습니다. 클러스터 FPolicy 정책은 클러스터 관리자가 admin SVM에 대해 생성하는 정책입니다. 클러스터 관리자가 해당 클러스터 FPolicy 정책의 범위도 생성한 경우 SVM 관리자는 동일한 정책의 범위를 생성할 수 없습니다. 그러나 클러스터 관리자가 클러스터 FPolicy 정책의 범위를 생성하지 않는 경우 SVM 관리자는 해당 클러스터 정책의 범위를 생성할 수 있습니다. SVM 관리자가 해당 클러스터 FPolicy 정책의 범위를 생성하는 경우, 클러스터 관리자가 이후에 동일한 클러스터 정책에 대한 클러스터 범위를 생성할 수 없습니다. 이는 클러스터 관리자가 동일한 클러스터 정책의 범위를 재정의할 수 없기 때문입니다.

====


== 우선 순위 범위 규칙은 무엇입니까

범위 구성에 적용되는 우선 순위 규칙은 다음과 같습니다.

* 공유가 '-공유-포함' 매개 변수에 포함되어 있고 공유의 상위 볼륨이 '-볼륨-제외' 매개 변수에 포함된 경우 '-볼륨-제외가 '-공유-포함'보다 우선합니다.
* 수출 정책이 '-export-policies-to-include' 매개 변수에 포함되어 있고 수출 정책의 상위 볼륨이 '-volumes-to-exclude' 매개 변수에 포함된 경우 '-volumes-to-exclude'가 '-export-policies-to-include'보다 우선합니다.
* 관리자는 '-file-extensions-to-include' 및 '-file-extensions-to-exclude' 목록을 모두 지정할 수 있습니다.
+
'-file-extensions-to-exclude' 매개 변수가 검사되기 전에 '-file-extensions-to-include' 매개 변수가 선택됩니다.





== FPolicy 범위 구성에 포함되는 내용

다음 가용 FPolicy 범위 구성 매개 변수 목록을 사용하여 구성을 계획할 수 있습니다.

[NOTE]
====
범위에 포함하거나 제외할 공유, 내보내기 정책, 볼륨 및 파일 확장명을 구성할 때 포함 및 제외 매개 변수는 정규식을 포함할 수 있으며 ""?" 등의 메타문자도 포함할 수 있습니다. "*"".

====
[cols="70,30"]
|===


| 정보 유형입니다 | 옵션을 선택합니다 


 a| 
SVM _

FPolicy 범위를 생성할 SVM 이름을 지정합니다.

각 FPolicy 구성은 단일 SVM 내에서 정의됩니다. FPolicy 정책 구성을 생성하기 위해 함께 조합되는 외부 엔진, 정책 이벤트, 정책 범위 및 정책은 모두 동일한 SVM과 연결되어야 합니다.
 a| 
'-vserver''vserver_name'



 a| 
_정책 이름 _

범위를 연결할 FPolicy 정책의 이름을 지정합니다. FPolicy 정책이 이미 존재해야 합니다.
 a| 
정책-이름 정책_이름



 a| 
_ 을(를) 포함할 공유 _

범위가 적용되는 FPolicy 정책을 모니터링할 쉼표로 구분된 공유 목록을 지정합니다.
 a| 
'-공유-포함''사어_이름',...



 a| 
제외할 공유 _

범위가 적용되는 FPolicy 정책에 대해 모니터링에서 제외할 쉼표로 구분된 공유 목록을 지정합니다.
 a| 
'-공유-제외''사어_이름',...



 a| 
_Volumes to Include_범위가 적용되는 FPolicy 정책을 모니터링할 쉼표로 구분된 볼륨 목록을 지정합니다.
 a| 
'-볼륨-포함''볼륨_이름',...



 a| 
제외할 볼륨 _

범위가 적용되는 FPolicy 정책에 대해 모니터링에서 제외할 쉼표로 구분된 볼륨 목록을 지정합니다.
 a| 
'-볼륨-제외''볼륨_이름',...



 a| 
_ 포함할 정책 내보내기 _

범위가 적용되는 FPolicy 정책을 모니터링할 쉼표로 구분된 엑스포트 정책 목록을 지정합니다.
 a| 
'-export-policies-to-include' export_policy_name',...



 a| 
_ 제외할 정책 내보내기 _

범위가 적용되는 FPolicy 정책에 대해 모니터링에서 제외할 내보내기 정책의 쉼표로 구분된 목록을 지정합니다.
 a| 
'-export-policies-to-exclude' export_policy_name',...



 a| 
_ 포함할 파일 확장자 _

범위가 적용되는 FPolicy 정책을 모니터링할 쉼표로 구분된 파일 확장자 목록을 지정합니다.
 a| 
'-file-extensions-to-include''file_extensions',...



 a| 
_ 제외할 파일 확장자 _

범위가 적용되는 FPolicy 정책에 대해 모니터링에서 제외할 파일 확장명 목록을 쉼표로 구분하여 지정합니다.
 a| 
'-file-extensions-to-exclude''file_extensions',...



 a| 
_ 디렉토리에 대한 파일 확장자 확인이 활성화되었습니까? _

파일 이름 확장명 검사를 디렉터리 개체에도 적용할지 여부를 지정합니다. 이 매개 변수를 "true"로 설정하면 디렉터리 개체는 일반 파일과 동일한 확장 검사를 받습니다. 이 매개 변수가 false로 설정되어 있으면 이름 확장명이 일치하지 않아도 디렉터리 이름이 확장명에 일치하지 않고 디렉터리에 대한 알림이 전송됩니다.

범위가 할당된 FPolicy 정책이 기본 엔진을 사용하도록 구성된 경우 이 매개 변수를 'true'로 설정해야 합니다.
 a| 
'-is-file-extension-check-on-directories-enabled'{'true'|'false'|}

|===