---
permalink: nas-audit/requirements-best-practices-fpolicy-concept.html 
sidebar: sidebar 
keywords: requirements, considerations, best practices, configure, fpolicy 
summary: '스토리지 가상 시스템(SVM)에서 FPolicy 구성을 생성하고 구성하기 전에 FPolicy를 구성하기 위한 특정 요구사항, 고려 사항 및 모범 사례를 알고 있어야 합니다.' 
---
= FPolicy를 구성하기 위한 요구사항, 고려 사항 및 모범 사례
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
스토리지 가상 시스템(SVM)에서 FPolicy 구성을 생성하고 구성하기 전에 FPolicy를 구성하기 위한 특정 요구사항, 고려 사항 및 모범 사례를 알고 있어야 합니다.



== FPolicy 구성 방법

FPolicy 기능은 CLI(명령줄 인터페이스) 또는 API를 통해 구성됩니다. 이 가이드에서는 CLI를 사용하여 클러스터에서 FPolicy 구성을 생성, 관리 및 모니터링합니다.



== FPolicy 설정 요구 사항

SVM(스토리지 가상 머신)에서 FPolicy를 구성하고 사용하기 전에 특정 요구사항을 알고 있어야 합니다.

* 클러스터의 모든 노드는 FPolicy를 지원하는 ONTAP 버전을 실행하고 있어야 합니다.
* ONTAP 기본 FPolicy 엔진을 사용하지 않는 경우 외부 FPolicy 서버(FPolicy 서버)가 설치되어 있어야 합니다.
* FPolicy 정책은 사용되는 SVM의 데이터 LIF에서 액세스할 수 있는 서버에 FPolicy 서버를 설치해야 합니다.
+

NOTE: ONTAP 9.8부터 ONTAP은 아웃바운드 FPolicy 연결을 위한 클라이언트 LIF 서비스를 제공하며 이 서비스를 추가할 수 있습니다 `data-fpolicy-client` 서비스. https://docs.netapp.com/us-en/ontap/networking/lifs_and_service_policies96.html["LIF 및 서비스 정책에 대해 자세히 알아보십시오"].

* FPolicy 서버의 IP 주소는 FPolicy 정책 외부 엔진 구성에서 1차 또는 2차 서버로 구성해야 합니다.
* FPolicy 서버가 권한 있는 데이터 채널을 통해 데이터에 액세스하는 경우 다음과 같은 추가 요구사항이 충족되어야 합니다.
+
** SMB는 클러스터에서 라이센스가 있어야 합니다.
+
권한 있는 데이터 액세스는 SMB 연결을 사용하여 수행됩니다.

** 권한이 있는 데이터 채널을 통해 파일에 액세스하기 위한 사용자 자격 증명을 구성해야 합니다.
** FPolicy 서버는 FPolicy 구성에 구성된 자격 증명에서 실행해야 합니다.
** FPolicy 서버와 통신하는 데 사용되는 모든 데이터 LIF는 허용되는 프로토콜 중 하나로 'CIFS'를 사용하도록 구성해야 합니다.
+
패스스루 읽기 연결에 사용되는 LIF가 포함됩니다.







== FPolicy를 설정할 때의 모범 사례와 권장 사항입니다

SVM(스토리지 가상 머신)에서 FPolicy를 설정할 때는 구성 모범 사례와 권장 사항을 잘 알고 있어야 FPolicy 구성이 요구사항을 충족하는 강력한 모니터링 성능과 결과를 제공할 수 있습니다.

* 외부 FPolicy 서버(FPolicy 서버)는 최소한의 지연 시간과 고대역폭 연결을 제공하기 위해 클러스터 근처에 배치해야 합니다.
* FPolicy 외부 엔진은 둘 이상의 FPolicy 서버로 구성되어 FPolicy 서버 알림 처리의 복원력과 고가용성을 제공해야 합니다. 특히 정책이 동기식 선별에 맞게 구성된 경우 더욱 그렇습니다.
* 구성을 변경하기 전에 FPolicy 정책을 사용하지 않는 것이 좋습니다.
+
예를 들어, 활성화된 정책에 구성된 FPolicy 외부 엔진에서 IP 주소를 추가하거나 수정하려는 경우 먼저 정책을 비활성화해야 합니다.

* 클러스터 노드-FPolicy 서버 비율은 FPolicy 서버가 과부하되지 않도록 최적화되어야 하며, 이는 SVM이 클라이언트 요청에 응답할 때 지연 시간을 유발할 수 있습니다.
+
최적의 비율은 FPolicy 서버가 사용되는 애플리케이션에 따라 다릅니다.





== 통과 연결 - 읽기 업그레이드 및 되돌리기 고려 사항

패스스루 읽기를 지원하는 ONTAP 릴리즈로 업그레이드하기 전에 또는 패스스루 읽기를 지원하지 않는 릴리즈로 되돌리기 전에 반드시 알아야 하는 특정 업그레이드 및 되돌리기 고려 사항이 있습니다.



=== 업그레이드 중

모든 노드가 FPolicy 패스스루 읽기를 지원하는 ONTAP 버전으로 업그레이드된 후 클러스터는 패스스루 읽기 기능을 사용할 수 있습니다. 하지만 기존 FPolicy 구성에서는 패스스루 읽기가 기본적으로 비활성화됩니다. 기존 FPolicy 구성에서 패스스루 읽기를 사용하려면 FPolicy 정책을 비활성화하고 구성을 수정한 다음 구성을 다시 활성화해야 합니다.



=== 되돌리기

FPolicy 패스스루 읽기를 지원하지 않는 ONTAP 버전으로 되돌리기 전에 다음 조건을 충족해야 합니다.

* 패스스루 읽기를 사용하는 모든 정책을 비활성화한 다음 패스스루 읽기를 사용하지 않도록 영향을 받는 구성을 수정해야 합니다.
* 클러스터에서 FPolicy 정책을 사용하지 않도록 설정하여 FPolicy 기능을 클러스터에서 해제해야 합니다.

