---
permalink: nas-audit/requirements-considerations-concept.html 
sidebar: sidebar 
keywords: audit, requirements, considerations 
summary: 'SVM(스토리지 가상 시스템)에 대한 감사를 구성 및 설정하기 전에 특정 요구사항과 고려 사항을 숙지해야 합니다.' 
---
= 감사 요구 사항 및 고려 사항
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SVM(스토리지 가상 시스템)에 대한 감사를 구성 및 설정하기 전에 특정 요구사항과 고려 사항을 숙지해야 합니다.

* 클러스터에서 지원되는 감사 가능 SVM의 최대 수는 50개입니다.
* 감사는 SMB 또는 NFS 라이센스와 관련이 없습니다.
+
클러스터에 SMB 및 NFS 라이센스가 설치되어 있지 않은 경우에도 감사를 구성 및 활성화할 수 있습니다.

* NFS 감사는 보안 ACE(U형)를 지원합니다.
* NFS 감사의 경우 모드 비트와 감사 ACE 사이에 매핑이 없습니다.
+
ACL을 모드 비트로 변환할 때 감사 ACE는 건너뜁니다. 모드 비트를 ACL로 변환할 때 감사 ACE가 생성되지 않습니다.

* 감사 구성에 지정된 디렉토리가 있어야 합니다.
+
이 명령이 없으면 감사 구성을 만드는 명령이 실패합니다.

* 감사 구성에 지정된 디렉토리는 다음 요구 사항을 충족해야 합니다.
+
** 디렉토리에는 심볼 링크가 포함되어 있지 않아야 합니다.
+
감사 구성에 지정된 디렉터리에 심볼 링크가 포함된 경우 감사 구성을 생성하는 명령이 실패합니다.

** 절대 경로를 사용하여 디렉토리를 지정해야 합니다.
+
예를 들어, '/vs1/.../'와 같은 상대 경로를 지정하면 안 됩니다.



* 감사는 스테이징 볼륨에 사용 가능한 공간이 있는 경우에 따라 달라집니다.
+
감사된 볼륨이 포함된 애그리게이트에서 스테이징 볼륨에 충분한 공간이 있는지 확인하고 계획을 세워야 합니다.

* 감사는 변환된 이벤트 로그가 저장되는 디렉토리가 포함된 볼륨에 사용 가능한 공간이 있는지 여부에 따라 달라집니다.
+
이벤트 로그를 저장하는 데 사용되는 볼륨에 충분한 공간이 있는지 확인하고 계획을 세워야 합니다. 감사 구성을 생성할 때 '-rotate-limit' 매개 변수를 사용하여 감사 디렉토리에 유지할 이벤트 로그 수를 지정할 수 있습니다. 감사 구성은 볼륨에 이벤트 로그에 사용할 수 있는 충분한 공간이 있는지 확인하는 데 도움이 됩니다.

* SMB 서버에서 동적 액세스 제어를 설정하지 않고 감사 구성에서 중앙 액세스 정책 스테이징을 설정할 수 있지만 동적 액세스 제어를 활성화하여 중앙 액세스 정책 스테이징 이벤트를 생성해야 합니다.
+
동적 액세스 제어는 기본적으로 사용되지 않습니다.





== 감사를 설정할 때 애그리게이트 공간 고려 사항

감사 구성이 생성되고 클러스터에서 하나 이상의 SVM(스토리지 가상 머신)에 감사가 활성화되어 있으면 감사 서브시스템이 모든 기존 애그리게이트 및 생성되는 모든 새 애그리게이트에 스테이징 볼륨을 생성합니다. 클러스터에서 감사를 활성화할 때는 애그리게이트 공간의 특정 고려 사항을 알아야 합니다.

애그리게이트에서 사용할 수 없는 공간으로 인해 스테이징 볼륨 생성이 실패할 수 있습니다. 감사 구성을 생성할 때 기존 애그리게이트에 스테이징 볼륨을 포함할 충분한 공간이 없는 경우 이러한 문제가 발생할 수 있습니다.

SVM에 대한 감사를 활성화하기 전에 스테이징 볼륨에 대한 기존 애그리게이트에 충분한 공간이 있는지 확인해야 합니다.
