---
permalink: nas-audit/restrictions-fpolicy-mcc-svm-disaster-recovery-concept.html 
sidebar: sidebar 
keywords: restrictions, cluster-scoped, fpolicy, external engines, metrocluster, svm disaster recovery configurations 
summary: '클러스터 스토리지 가상 시스템(SVM)을 외부 엔진에 할당하여 클러스터 범위 FPolicy 외부 엔진을 생성할 수 있습니다. 하지만 MetroCluster 또는 SVM 재해 복구 구성에서 클러스터 범위 외부 엔진을 만들 때는 SVM이 FPolicy 서버와의 외부 통신에 사용하는 인증 방법을 선택할 때 특정 제한이 있습니다.' 
---
= MetroCluster 및 SVM 재해 복구 구성의 클러스터 범위 FPolicy 외부 엔진에 대한 제한 사항
:icons: font
:imagesdir: ../media/


[role="lead"]
클러스터 스토리지 가상 시스템(SVM)을 외부 엔진에 할당하여 클러스터 범위 FPolicy 외부 엔진을 생성할 수 있습니다. 하지만 MetroCluster 또는 SVM 재해 복구 구성에서 클러스터 범위 외부 엔진을 만들 때는 SVM이 FPolicy 서버와의 외부 통신에 사용하는 인증 방법을 선택할 때 특정 제한이 있습니다.

외부 FPolicy 서버를 생성할 때 인증 없음, SSL 서버 인증 및 SSL 상호 인증이라는 세 가지 인증 옵션을 선택할 수 있습니다. 외부 FPolicy 서버가 데이터 SVM에 할당되는 인증 옵션을 선택할 때는 제한이 없지만 클러스터 범위 FPolicy 외부 엔진을 생성할 때는 제한이 있습니다.

[cols="75,25"]
|===


| 구성 | 허용됩니까? 


 a| 
인증 없이 MetroCluster 또는 SVM 재해 복구 및 클러스터 범위 FPolicy 외부 엔진(SSL이 구성되지 않음)
 a| 
예



 a| 
MetroCluster 또는 SVM 재해 복구, SSL 서버 또는 SSL 상호 인증을 사용하는 클러스터 범위 FPolicy 외부 엔진
 a| 
아니요

|===
* SSL 인증을 사용하는 클러스터 범위 FPolicy 외부 엔진이 있고 MetroCluster 또는 SVM 재해 복구 구성을 생성하려는 경우, MetroCluster 또는 SVM 재해 복구 구성을 생성하기 전에 이 외부 엔진을 수정하거나 외부 엔진을 제거하지 않아야 합니다.
* MetroCluster 또는 SVM 재해 복구 구성이 이미 있는 경우 ONTAP는 클러스터 범위 FPolicy 외부 엔진을 SSL 인증으로 생성하지 못합니다.

