---
permalink: nas-audit/security-traces-work-concept.html 
sidebar: sidebar 
keywords: security traces, work 
summary: '보안 추적을 사용하면 SVM(Storage Virtual Machine)에서 SMB 및 NFS를 통해 클라이언트 작업을 감지하고 해당 필터와 일치하는 모든 액세스 검사를 추적하는 필터를 구성할 수 있습니다. 그런 다음 액세스가 허용되거나 거부된 이유를 간단히 요약할 수 있는 추적 결과를 볼 수 있습니다.' 
---
= 보안 추적 작동 방식
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP에 SVM(스토리지 가상 머신)의 SMB 및 NFS 서버가 작업 수행을 위한 클라이언트 또는 사용자의 요청을 허용하거나 거부하는 이유에 대한 정보를 기록하도록 권한 추적 필터를 추가할 수 있습니다. 이 기능은 파일 액세스 보안 체계가 적절한지 확인하거나 파일 액세스 문제를 해결하려는 경우에 유용합니다.

보안 추적을 사용하면 SVM에서 SMB 및 NFS를 통해 클라이언트 작업을 감지하는 필터를 구성하고 해당 필터와 일치하는 모든 액세스 검사를 추적할 수 있습니다. 그런 다음 액세스가 허용되거나 거부된 이유를 간단히 요약할 수 있는 추적 결과를 볼 수 있습니다.

SVM의 파일 및 폴더에서 SMB 또는 NFS 액세스에 대한 보안 설정을 확인하거나 액세스 문제가 발생한 경우 필터를 빠르게 추가하여 권한 추적을 설정할 수 있습니다.

다음 목록에서는 보안 추적 작동 방식에 대한 중요한 사실을 간략하게 설명합니다.

* ONTAP는 SVM 레벨에서 보안 추적을 적용합니다.
* 각 수신 요청이 활성화된 보안 추적의 필터링 기준과 일치하는지 확인합니다.
* 추적은 파일 및 폴더 액세스 요청 모두에 대해 수행됩니다.
* 트레이스는 다음 기준에 따라 필터링할 수 있습니다.
+
** 클라이언트 IP입니다
** SMB 또는 NFS 경로입니다
** Windows 이름입니다
** Unix 이름입니다


* 요청은 _allowed_and_Denied_access 응답 결과에 대해 스크리닝됩니다.
* 활성화된 추적의 필터링 기준과 일치하는 각 요청은 추적 결과 로그에 기록됩니다.
* 스토리지 관리자는 필터의 시간 초과를 구성하여 필터를 자동으로 해제할 수 있습니다.
* 요청이 여러 필터와 일치하면 가장 높은 인덱스 번호를 가진 필터의 결과가 기록됩니다.
* 스토리지 관리자는 추적 결과 로그의 결과를 인쇄하여 액세스 요청이 허용 또는 거부된 이유를 확인할 수 있습니다.

