---
permalink: nas-audit/show-commands-work-concept.html 
sidebar: sidebar 
keywords: show commands, work 
summary: FPolicy 구성에 대한 정보를 표시하여 show 명령의 작동 방식을 이해하는 데 도움이 됩니다. 
---
= show 명령이 작동하는 방식
:icons: font
:imagesdir: ../media/


[role="lead"]
FPolicy 구성에 대한 정보를 표시하여 '방법' 명령의 작동 방식을 이해하는 것이 좋습니다.

추가 매개 변수 없이 'show' 명령을 실행하면 요약 형식으로 정보가 표시됩니다. 또한 모든 'show' 명령은 'instance', '-fields'라는 상호 배타적인 두 개의 선택적 매개 변수를 갖습니다.

'-instance' 매개 변수를 'show' 명령과 함께 사용하면 명령 출력에 자세한 정보가 목록 형식으로 표시됩니다. 경우에 따라 상세 출력 시간이 오래 걸리고 필요한 것보다 많은 정보를 포함할 수 있습니다. '-fields''fieldname[,fieldname...]' 파라미터를 사용하면 지정한 필드에 대한 정보만 표시하도록 출력을 사용자 정의할 수 있습니다. '?'를 입력하여 지정할 수 있는 필드를 식별할 수 있습니다 '-fields' 파라미터 뒤에

[NOTE]
====
필드 매개 변수가 있는 'show' 명령의 출력에는 요청된 필드와 관련된 다른 관련 필드와 필수 필드가 표시될 수 있습니다.

====
모든 'show' 명령에는 출력을 필터링하고 명령 출력에 표시되는 정보의 범위를 좁힐 수 있도록 하는 하나 이상의 선택적 매개 변수가 있습니다. '?'를 입력하여 명령에 사용할 수 있는 선택적 매개 변수를 식별할 수 있습니다 'show' 명령 뒤에.

'show' 명령은 UNIX 스타일 패턴과 와일드카드를 지원하여 명령 매개 변수 인수의 여러 값을 일치시킬 수 있습니다. 예를 들어 값을 지정할 때 와일드카드 연산자(*), NOT 연산자(!), OR 연산자(|), 범위 연산자(integer...integer), 보다 작음 연산자(<), 보다 큼 연산자(>), 보다 작거나 같음 연산자(\<=) 및 보다 크거나 같음 연산자(>=)를 사용할 수 있습니다.

UNIX 스타일 패턴 및 와일드카드 사용에 대한 자세한 내용은 SVM 관리자를 위한 _시스템 관리 안내서의 "ONTAP 명령줄 인터페이스 사용" 섹션을 참조하십시오.
