---
permalink: nas-audit/synchronous-asynchronous-notifications-concept.html 
sidebar: sidebar 
keywords: synchronous, asynchronous, notifications 
summary: FPolicy는 FPolicy 인터페이스를 통해 외부 FPolicy 서버에 알림을 보냅니다. 알림은 동기 또는 비동기 모드로 전송됩니다. 알림 모드는 FPolicy 서버에 알림을 보낸 후 ONTAP에서 수행하는 작업을 결정합니다. 
---
= 동기식 및 비동기식 알림입니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
FPolicy는 FPolicy 인터페이스를 통해 외부 FPolicy 서버에 알림을 보냅니다. 알림은 동기 또는 비동기 모드로 전송됩니다. 알림 모드는 FPolicy 서버에 알림을 보낸 후 ONTAP에서 수행하는 작업을 결정합니다.

* * 비동기 알림 *
+
비동기 알림을 사용할 경우 노드는 FPolicy 서버의 응답을 기다리지 않으므로 시스템의 전반적인 처리량이 향상됩니다. 이 유형의 알림은 FPolicy 서버에서 알림 평가의 결과로 어떤 작업도 수행할 필요가 없는 애플리케이션에 적합합니다. 예를 들어, 스토리지 가상 시스템(SVM) 관리자가 파일 액세스 활동을 모니터링하고 감사하려고 할 때 비동기 알림이 사용됩니다.

+
비동기 모드에서 작동하는 FPolicy 서버에서 네트워크 중단이 발생하는 경우, 정전 중에 생성된 FPolicy 알림은 스토리지 노드에 저장됩니다. FPolicy 서버가 온라인 상태로 돌아오면 저장된 알림에 대한 알림이 표시되고 스토리지 노드에서 가져올 수 있습니다. 정전 중에 알림을 저장할 수 있는 시간은 최대 10분까지 구성할 수 있습니다.

* * 동기식 알림 *
+
동기식 모드에서 실행하도록 구성된 경우 FPolicy 서버는 클라이언트 작업을 계속하기 전에 모든 알림을 확인해야 합니다. 이 유형의 알림은 알림 평가 결과에 따라 조치가 필요한 경우에 사용됩니다. 예를 들어, SVM 관리자가 외부 FPolicy 서버에 지정된 기준에 따라 요청을 허용하거나 거부하려는 경우 동기식 알림이 사용됩니다.





== 동기 및 비동기 애플리케이션

FPolicy 애플리케이션은 비동기식 및 동기식 모두에서 사용할 수 있습니다.

비동기식 애플리케이션은 외부 FPolicy 서버가 파일 또는 디렉토리에 대한 액세스를 변경하거나 SVM(스토리지 가상 머신)의 데이터를 수정하지 않는 애플리케이션입니다. 예를 들면 다음과 같습니다.

* 파일 액세스 및 감사 로깅
* 스토리지 리소스 관리


동기식 애플리케이션은 데이터 액세스가 변경되거나 외부 FPolicy 서버에 의해 데이터가 수정된 애플리케이션입니다. 예를 들면 다음과 같습니다.

* 할당량 관리
* 파일 액세스 차단
* 파일 아카이빙 및 계층적 스토리지 관리
* 암호화 및 암호 해독 서비스
* 압축 및 압축 해제 서비스

