---
permalink: nas-audit/troubleshoot-auditing-staging-volume-concept.html 
sidebar: sidebar 
keywords: troubleshoot, audit, stage, volume space, issues 
summary: 스테이징 볼륨 또는 감사 이벤트 로그가 포함된 볼륨에 공간이 부족할 때 문제가 발생할 수 있습니다. 공간이 부족하면 새 감사 레코드를 생성할 수 없으므로 클라이언트가 데이터에 액세스하지 못하게 되고 액세스 요청이 실패합니다. 이러한 볼륨 공간 문제를 해결하고 해결하는 방법을 알아야 합니다. 
---
= 감사 및 스테이징 볼륨 공간 문제를 해결합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
스테이징 볼륨 또는 감사 이벤트 로그가 포함된 볼륨에 공간이 부족할 때 문제가 발생할 수 있습니다. 공간이 부족하면 새 감사 레코드를 생성할 수 없으므로 클라이언트가 데이터에 액세스하지 못하게 되고 액세스 요청이 실패합니다. 이러한 볼륨 공간 문제를 해결하고 해결하는 방법을 알아야 합니다.



== 이벤트 로그 볼륨과 관련된 공간 문제를 해결합니다

이벤트 로그 파일이 포함된 볼륨의 공간이 부족한 경우 감사 기능은 로그 레코드를 로그 파일로 변환할 수 없습니다. 이로 인해 클라이언트 액세스 장애가 발생합니다. 이벤트 로그 볼륨과 관련된 공간 문제를 해결하는 방법을 알고 있어야 합니다.

* 스토리지 가상 머신(SVM) 및 클러스터 관리자는 볼륨 및 애그리게이트의 사용 및 구성에 대한 정보를 표시하여 볼륨 공간이 부족한지 여부를 확인할 수 있습니다.
* 이벤트 로그가 포함된 볼륨에 공간이 부족하면 SVM 및 클러스터 관리자가 이벤트 로그 파일 중 일부를 제거하거나 볼륨 크기를 늘려 공간 문제를 해결할 수 있습니다.
+
[NOTE]
====
이벤트 로그 볼륨이 포함된 애그리게이트는 가득 찬 경우, 볼륨의 크기를 늘리려면 애그리게이트의 크기를 늘려야 합니다. 클러스터 관리자만 집계 크기를 늘릴 수 있습니다.

====
* 감사 구성을 수정하여 이벤트 로그 파일의 대상 경로를 다른 볼륨의 디렉토리로 변경할 수 있습니다.
+
[NOTE]
====
다음과 같은 경우 데이터 액세스가 거부됩니다.

** 대상 디렉토리가 삭제됩니다.
** 대상 디렉토리를 호스팅하는 볼륨에 대한 파일 제한이 최대 레벨에 도달합니다.


====


자세히 알아보기:

* link:../volumes/index.html["볼륨에 대한 정보를 보고 볼륨 크기를 늘리는 방법"].
* link:../disks-aggregates/index.html["Aggregate에 대한 정보를 보고 애그리게이트를 관리하는 방법"].




== 스테이징 볼륨과 관련된 공간 문제를 해결합니다

SVM(Storage Virtual Machine)에 대한 스테이징 파일이 포함된 볼륨 중 공간이 부족한 경우 감사를 통해 로그 레코드를 스테이징 파일에 쓸 수 없습니다. 이로 인해 클라이언트 액세스 장애가 발생합니다. 이 문제를 해결하려면 SVM에 사용된 스테이징 볼륨이 볼륨 사용에 대한 정보를 표시하여 가득 찼는지 여부를 확인해야 합니다.

통합된 이벤트 로그 파일이 포함된 볼륨에 충분한 공간이 있지만 공간 부족으로 인해 여전히 클라이언트 액세스 장애가 발생하는 경우 스테이징 볼륨의 공간이 부족할 수 있습니다. SVM 관리자는 SVM을 위한 스테이징 파일이 포함된 스테이징 볼륨의 공간이 부족한지 여부를 확인하기 위해 여러분에게 연락해야 합니다. 감사 하위 시스템은 스테이징 볼륨의 공간이 부족하여 감사 이벤트를 생성할 수 없는 경우 EMS 이벤트를 생성합니다. 장치에 남은 공간이 없습니다 라는 메시지가 표시됩니다. 스테이징 볼륨에 대한 정보는 사용자만 볼 수 있으며 SVM 관리자는 볼 수 없습니다.

모든 스테이징 볼륨 이름은 mdv_AUD_ 로 시작하고 그 스테이징 볼륨을 포함하는 애그리게이트의 UUID로 시작합니다. 다음 예에서는 클러스터 내의 데이터 SVM에 대한 파일 서비스 감사 구성을 생성할 때 자동으로 생성되는 admin SVM의 시스템 볼륨 4개를 보여 줍니다.

[listing]
----
cluster1::> volume show -vserver cluster1
Vserver   Volume       Aggregate    State      Type       Size  Available Used%
--------- ------------ ------------ ---------- ---- ---------- ---------- -----
cluster1  MDV_aud_1d0131843d4811e296fc123478563412
                       aggr0        online     RW          5GB     4.75GB    5%
cluster1  MDV_aud_8be27f813d7311e296fc123478563412
                       root_vs0     online     RW          5GB     4.75GB    5%
cluster1  MDV_aud_9dc4ad503d7311e296fc123478563412
                       aggr1        online     RW          5GB     4.75GB    5%
cluster1  MDV_aud_a4b887ac3d7311e296fc123478563412
                       aggr2        online     RW          5GB     4.75GB    5%
4 entries were displayed.
----
스테이징 볼륨에 공간이 부족하면 볼륨 크기를 늘려 공간 문제를 해결할 수 있습니다.

[NOTE]
====
스테이징 볼륨이 포함된 aggregate가 가득 찬 경우 볼륨의 크기를 늘리려면 애그리게이트의 크기를 늘려야 합니다. 애그리게이트의 크기를 늘릴 수 있는 것은 없으며 SVM 관리자는 불가능합니다.

====
하나 이상의 애그리게이트에서 사용 가능한 공간이 2GB 미만(ONTAP 9.14.1 이하) 또는 5GB(ONTAP 9.15.1부터 시작)인 경우 SVM 감사 생성이 실패합니다. SVM 감사 생성에 실패하면 생성된 스테이징 볼륨이 삭제됩니다.
