---
permalink: nas-audit/view-audit-event-logs-concept.html 
sidebar: sidebar 
keywords: view, audit event logs 
summary: 감사 이벤트 로그를 사용하여 적절한 파일 보안이 있는지 여부와 잘못된 파일 및 폴더 액세스 시도가 있는지 여부를 확인할 수 있습니다. evtx 또는 XML 파일 형식으로 저장된 감사 이벤트 로그를 보고 처리할 수 있습니다. 
---
= 감사 이벤트 로그를 봅니다
:icons: font
:imagesdir: ../media/


[role="lead"]
감사 이벤트 로그를 사용하여 적절한 파일 보안이 있는지 여부와 잘못된 파일 및 폴더 액세스 시도가 있는지 여부를 확인할 수 있습니다. evtx 또는 XML 파일 형식으로 저장된 감사 이벤트 로그를 보고 처리할 수 있습니다.

* evtx 파일 형식
+
Microsoft 이벤트 뷰어를 사용하여 변환된 'evtx' 감사 이벤트 로그를 저장된 파일로 열 수 있습니다.

+
이벤트 뷰어를 사용하여 이벤트 로그를 볼 때 사용할 수 있는 두 가지 옵션이 있습니다.

+
** 일반 보기
+
모든 이벤트에 공통되는 정보는 이벤트 레코드에 대해 표시됩니다. 이 버전의 ONTAP에서는 이벤트 레코드에 대한 이벤트 관련 데이터가 표시되지 않습니다. 상세도를 사용하여 이벤트 관련 데이터를 표시할 수 있습니다.

** 상세보기
+
친숙한 뷰와 XML 뷰를 사용할 수 있습니다. 보기 및 XML 보기에는 모든 이벤트에 공통되는 정보와 이벤트 레코드에 대한 이벤트 관련 데이터가 모두 표시됩니다.



* 'xml' 파일 형식
+
XML 파일 형식을 지원하는 타사 응용 프로그램에서 XML 감사 이벤트 로그를 보고 처리할 수 있습니다. XML 스키마와 XML 필드 정의에 대한 정보가 있는 경우 XML 보기 도구를 사용하여 감사 로그를 볼 수 있습니다. XML 스키마 및 정의에 대한 자세한 내용은 을 참조하십시오 https://library.netapp.com/ecm/ecm_get_file/ECMLP2875022["ONTAP 감사 스키마 참조"].





== 이벤트 뷰어를 사용하여 활성 감사 로그를 보는 방법

클러스터에서 감사 통합 프로세스가 실행 중인 경우 통합 프로세스에서 감사 사용 스토리지 가상 시스템(SVM)에 대한 새 레코드를 활성 감사 로그 파일에 추가합니다. 이 활성 감사 로그는 Microsoft 이벤트 뷰어에서 SMB 공유를 통해 액세스하고 열 수 있습니다.

이벤트 뷰어에는 기존 감사 레코드를 보는 것 외에도 콘솔 창에서 콘텐츠를 새로 고칠 수 있는 새로 고침 옵션이 있습니다. 새로 추가된 로그를 이벤트 뷰어에서 볼 수 있는지 여부는 활성 감사 로그에 액세스하는 데 사용된 공유에 oplocks가 설정되어 있는지 여부에 따라 달라집니다.

[cols="30,70"]
|===


| 공유에 oplocks 설정을 지정합니다 | 동작 


 a| 
활성화됨
 a| 
이벤트 뷰어는 해당 시점까지 기록된 이벤트가 포함된 로그를 엽니다. 새로 고침 작업은 통합 프로세스에 추가된 새 이벤트로 로그를 새로 고치지 않습니다.



 a| 
사용 안 함
 a| 
이벤트 뷰어는 해당 시점까지 기록된 이벤트가 포함된 로그를 엽니다. 새로 고침 작업은 통합 프로세스에 추가된 새 이벤트로 로그를 새로 고칩니다.

|===
[NOTE]
====
이 정보는 evtx 이벤트 로그에만 적용됩니다. XML 이벤트 로그는 브라우저에서 SMB를 통해 보거나 XML 편집기나 뷰어를 사용하여 NFS를 통해 볼 수 있습니다.

====