---
permalink: san-config/benefits-vlans-iscsi-concept.html 
sidebar: sidebar 
keywords: benefits, vlans, iscsi, configurations, static, dynamic, security, limit, available, paths 
summary: VLAN은 브로드캐스트 도메인으로 그룹화된 스위치 포트 그룹으로 구성됩니다. VLAN은 단일 스위치에 있거나 여러 스위치 섀시에 걸쳐 있을 수 있습니다. 정적 및 동적 VLAN을 사용하면 IP 네트워크 인프라 내에서 보안을 강화하고, 문제를 격리하고, 사용 가능한 경로를 제한할 수 있습니다. 
---
= iSCSI 구성에서 VLAN을 사용할 때의 이점
:icons: font
:imagesdir: ../media/


[role="lead"]
VLAN은 브로드캐스트 도메인으로 그룹화된 스위치 포트 그룹으로 구성됩니다. VLAN은 단일 스위치에 있거나 여러 스위치 섀시에 걸쳐 있을 수 있습니다. 정적 및 동적 VLAN을 사용하면 IP 네트워크 인프라 내에서 보안을 강화하고, 문제를 격리하고, 사용 가능한 경로를 제한할 수 있습니다.

대규모 IP 네트워크 인프라에서 VLAN을 구현할 경우 다음과 같은 이점을 얻을 수 있습니다.

* 보안 강화:
+
VLAN을 사용하면 이더넷 네트워크 또는 IP SAN의 여러 노드 간 액세스를 제한하므로 기존 인프라를 활용하는 동시에 보안을 강화할 수 있습니다.

* 문제를 격리하여 이더넷 네트워크 및 IP SAN 안정성 향상
* 문제 공간을 제한하여 문제 해결 시간 단축
* 특정 iSCSI 타겟 포트에 대한 사용 가능한 경로 수 감소
* 호스트에서 사용하는 최대 경로 수 감소
+
경로가 너무 많으면 재연결 시간이 느려집니다. 호스트에 다중 경로 솔루션이 없는 경우 VLAN을 사용하여 하나의 경로만 허용할 수 있습니다.





== 동적 VLAN

동적 VLAN은 MAC 주소를 기반으로 합니다. 포함할 멤버의 MAC 주소를 지정하여 VLAN을 정의할 수 있습니다.

동적 VLAN은 유연성을 제공하며 장치가 물리적으로 스위치에 연결되어 있는 물리적 포트에 매핑하지 않아도 됩니다. VLAN을 재구성하지 않고도 한 포트에서 다른 포트로 케이블을 이동할 수 있습니다.



== 정적 VLAN

정적 VLAN은 포트 기반입니다. 스위치 및 스위치 포트는 VLAN 및 해당 구성원을 정의하는 데 사용됩니다.

정적 VLAN은 MAC(Media Access Control) 스푸핑을 사용하여 VLAN을 위반할 수 없기 때문에 보안이 향상됩니다. 그러나 다른 사람이 스위치에 물리적으로 액세스할 수 있는 경우 케이블을 교체하고 네트워크 주소를 다시 구성하면 액세스가 허용됩니다.

일부 환경에서는 동적 VLAN보다 정적 VLAN을 쉽게 생성하고 관리할 수 있습니다. 정적 VLAN은 48비트 MAC 주소 대신 스위치 및 포트 식별자만 지정할 수 있기 때문입니다. 또한 스위치 포트 범위에 VLAN 식별자를 사용하여 레이블을 지정할 수 있습니다.
