---
permalink: san-config/change-fc-adapter-speed-task.html 
sidebar: sidebar 
keywords: change, fc adapter, speed 
summary: 자동 협상을 사용하는 대신, 어댑터가 연결되는 장치의 속도에 맞게 어댑터 타겟 포트 속도를 설정해야 합니다. autonegotiation으로 설정된 포트는 Takeover/Giveback 또는 기타 중단 후 다시 연결하는 데 더 오랜 시간이 걸릴 수 있습니다. 
---
= FC 어댑터의 속도를 변경합니다
:icons: font
:imagesdir: ../media/


[role="lead"]
자동 협상을 사용하는 대신, 어댑터가 연결되는 장치의 속도에 맞게 어댑터 타겟 포트 속도를 설정해야 합니다. autonegotiation으로 설정된 포트는 Takeover/Giveback 또는 기타 중단 후 다시 연결하는 데 더 오랜 시간이 걸릴 수 있습니다.

이 어댑터를 홈 포트로 사용하는 모든 LIF는 오프라인 상태여야 합니다.

이 작업에는 클러스터의 모든 SVM(Storage Virtual Machine)과 모든 LIF가 포함되므로 이 작업의 범위를 제한하려면 '-home-port' 및 '-home-lif' 매개 변수를 사용해야 합니다. 이러한 매개 변수를 사용하지 않으면 클러스터에 있는 모든 LIF에 작업이 적용되며, 이는 바람직하지 않을 수 있습니다.

.단계
. 이 어댑터의 모든 LIF를 오프라인 상태로 전환:
+
'network interface modify -vserver * -lif * {-home-node node1 -home-port 0c} -status-admin down'

. 어댑터를 오프라인 상태로 전환:
+
'network fcp adapter modify-node node1 - adapter 0c-state down'

+
어댑터가 오프라인 상태가 되지 않으면 시스템의 해당 어댑터 포트에서 케이블을 분리할 수도 있습니다.

. 포트 어댑터의 최대 속도를 확인합니다.
+
FCP 어댑터 show-instance(FCP 어댑터 show-instance)

+
어댑터 속도를 최대 속도 이상으로 수정할 수 없습니다.

. 어댑터 속도를 변경합니다.
+
'network fcp adapter modify-node node1-adapter 0c-speed 16'

. 어댑터를 온라인으로 전환합니다.
+
'network fcp adapter modify-node node1 - adapter 0c-state up

. 어댑터에 있는 모든 LIF를 온라인으로 전환합니다.
+
'network interface modify -vserver * -lif * {-home-node node1 -home-port 0c} -status-admin up'


