---
permalink: san-config/fc-target-port-config-recommendations-concept.html 
sidebar: sidebar 
keywords: fc, target, port, configuration, recommendations 
summary: 최상의 성능과 가용성을 얻으려면 권장되는 FC 타겟 포트 구성을 사용해야 합니다. 
---
= FC 타겟 포트 구성 권장 사항
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
FC 타겟 포트는 FC 프로토콜에 대해 구성 및 사용되는 것과 정확히 동일한 방법으로 FC-NVMe 프로토콜에 대해 구성하고 사용할 수 있습니다. FC-NVMe 프로토콜에 대한 지원은 사용하는 플랫폼과 ONTAP 버전에 따라 다릅니다. NetApp Hardware Universe를 사용하여 지원을 확인합니다.

최상의 성능과 가용성을 얻으려면 특정 플랫폼에 대해 에 나와 있는 권장 대상 포트 구성을 사용해야 https://hwu.netapp.com["NetApp Hardware Universe를 참조하십시오"^] 합니다.



== 공유 ASIC를 통한 FC 타겟 포트 구성

다음 플랫폼에는 공유 ASIC(Application-Specific Integrated Circuits)와 포트 쌍이 있습니다. 확장 어댑터를 이러한 플랫폼에 사용할 경우 연결에 동일한 ASIC를 사용하지 않도록 FC 포트를 구성해야 합니다.

[cols="3*"]
|===
| 컨트롤러 | 공유 ASIC가 있는 포트 쌍 | 대상 포트 수: 권장 포트 수 


 a| 
* FAS8200를 참조하십시오
* AFF A300

 a| 
0g + 0h
 a| 
1:0g 2:0g, 0h



 a| 
* FAS2720
* FAS2750
* AFF A220

 a| 
0C+0d 0e+0f
 a| 
1:0c 2:0c, 0e 3:0c, 0e, 0d 4:0c, 0e, 0d, 0f

|===


== FC 타겟 포트의 지원 속도입니다

FC 타겟 포트는 다른 속도로 실행되도록 구성할 수 있습니다. 지정된 호스트에서 사용하는 모든 타겟 포트는 동일한 속도로 설정되어야 합니다. 대상 포트 속도를 연결할 장치의 속도와 일치하도록 설정해야 합니다. 포트 속도에 자동 협상을 사용하지 마십시오. autonegotiation으로 설정된 포트는 Takeover/Giveback 또는 기타 중단 후 다시 연결하는 데 더 오래 걸릴 수 있습니다.

다음과 같은 속도로 실행되도록 온보드 포트 및 확장 어댑터를 구성할 수 있습니다. 필요에 따라 각 컨트롤러 및 확장 어댑터 포트를 각기 다른 속도로 구성할 수 있습니다.

[cols="4*"]
|===
| 4Gb 포트 | 8Gb 포트 | 16Gb 포트 | 32 Gb 포트 


 a| 
* 4Gb
* 2Gb
* 1Gb

 a| 
* 8Gb
* 4Gb
* 2Gb

 a| 
* 16Gb
* 8Gb
* 4Gb

 a| 
* 32Gb
* 16Gb
* 8Gb


|===
[NOTE]
====
UTA2 포트는 8Gb SFP+ 어댑터를 사용하여 8Gb, 4 및 2Gb 속도를 지원할 수 있습니다.

====