---
permalink: san-config/set-queue-depth-task.html 
sidebar: sidebar 
keywords: calculate, queue depth 
summary: 노드별 및 FC 포트 팬인 당 ITNs의 최대 값을 얻으려면 호스트에서 FC 큐 길이를 조정해야 할 수 있습니다. FC 포트에 연결할 수 있는 HBA의 수와 LUN의 최대 수는 FC 타겟 포트에서 사용 가능한 큐 깊이로 제한됩니다. 
---
= SAN 호스트에 대기열 깊이를 설정합니다
:icons: font
:imagesdir: ../media/


[role="lead"]
노드 및 FC 포트 팬인 당 ITNs의 최대 값을 얻으려면 호스트의 대기열 깊이를 변경해야 할 수 있습니다.



== AIX 호스트

"chdev" 명령을 사용하여 AIX 호스트의 대기열 길이를 변경할 수 있습니다. "chdev" 명령을 사용하여 변경한 사항은 재부팅 후에도 유지됩니다.

예:

* hdisk7 디바이스의 대기열 길이를 변경하려면 다음 명령을 사용합니다.
+
chdev -l hdisk7 -a queue_depth=32

* fcs0 HBA의 대기열 길이를 변경하려면 다음 명령을 사용하십시오.
+
"chdev -l fcs0 -a num_cmd_elems=128"

+
num_cmd_elems의 기본값은 200입니다. 최대값은 2,048입니다.

+
[NOTE]
====
num_cmd_elems를 변경하려면 HBA를 오프라인 상태로 전환한 다음 rmdev-l fcs0-R 및 makdev-l fcs0-P 명령을 사용하여 다시 온라인 상태로 전환해야 할 수도 있습니다.

====




== HP-UX 호스트

커널 매개 변수 'scsi_max_qdepth'를 사용하여 HP-UX 호스트에서 LUN 또는 디바이스 대기열 길이를 변경할 수 있습니다. 커널 매개 변수 max_fcp_reqs를 사용하여 HBA 대기열 길이를 변경할 수 있습니다.

* 'scsi_max_qdepth'의 기본값은 8입니다. 최대값은 255입니다.
+
'kmtune' 명령의 '-u' 옵션을 사용하면 실행 중인 시스템에서 'scsi_max_qdepth'를 동적으로 변경할 수 있습니다. 이 변경 사항은 시스템의 모든 장치에 적용됩니다. 예를 들어, 다음 명령을 사용하여 LUN 대기열 길이를 64로 늘릴 수 있습니다.

+
"kmtune -u -s scsi_max_qdepth=64"

+
'csictl' 명령어를 이용하여 개별 장치 파일의 대기열 길이를 변경할 수 있다. 'csictl' 명령을 사용한 변경 사항은 시스템 재부팅 시에도 지속되지 않습니다. 특정 장치 파일의 대기열 길이를 보고 변경하려면 다음 명령을 실행합니다.

+
'csictl -a /dev/rdsk/c2t2d0'

+
'csictl -m queue_depth=16/dev/rdsk/c2t2d0'

* max_fcp_reqs의 기본값은 512입니다. 최대값은 1024입니다.
+
'max_fcp_reqs'의 변경 사항을 적용하려면 커널을 재구축하고 시스템을 재부팅해야 합니다. 예를 들어 HBA 대기열 길이를 256으로 변경하려면 다음 명령을 사용합니다.

+
"kmtune -u -s max_fcp_reqs=256"





== Solaris 호스트

Solaris 호스트에 대한 LUN 및 HBA 대기열 길이를 설정할 수 있습니다.

* LUN 큐 깊이의 경우: 호스트에서 사용 중인 LUN 수에 LUN당 스로틀(LUN-대기열-깊이)을 곱한 값은 호스트의 tgt-queue-depth 값보다 작거나 같아야 합니다.
* Sun 스택의 대기열 깊이의 경우: 기본 드라이버는 HBA 레벨에서 LUN 단위 또는 대상 max_throttle에 대한 설정을 허용하지 않습니다. 기본 드라이버에 대해 max_throttle 값을 설정하는 데 권장되는 방법은 '/kernel/drv/sd.conf' 및 '/kernel/drv/ssd.conf' 파일의 장치별 유형(VID_PID) 수준에 있습니다. 호스트 유틸리티는 MPxIO 구성의 경우 이 값을 64로, Veritas DMP 구성의 경우 8로 설정합니다.


.단계
. '#cd/kernel/drv'
. `#vi lpfc.conf'
. '/TFT-queue(/tgt-queue)'를 검색합니다
+
tgt-queue-depth=32

+
[NOTE]
====
기본값은 설치 시 32로 설정됩니다.

====
. 환경 구성에 따라 원하는 값을 설정합니다.
. 파일을 저장합니다.
. '+sync;sync;sync;reboot---r+' 명령을 사용하여 호스트를 재부팅합니다.




== QLogic HBA의 VMware 호스트입니다

'esxcfg-module' 명령을 사용하여 HBA 시간 제한 설정을 변경합니다. ESX.conf 파일을 수동으로 업데이트하는 것은 권장되지 않습니다.

.단계
. 서비스 콘솔에 루트 사용자로 로그온합니다.
. 현재 로드된 Qlogic HBA 모듈을 확인하려면 '#vmkload_mod -l' 명령을 사용합니다.
. Qlogic HBA의 단일 인스턴스의 경우 다음 명령을 실행합니다.
+
'#esxcfg-module-s ql2xmaxqdepth=64 qla2300_707'

+
[NOTE]
====
이 예에서는 qla2300_707 모듈을 사용합니다. "vmkload_mod -l"의 출력에 따라 적절한 모듈을 사용합니다.

====
. 다음 명령을 사용하여 변경 내용을 저장합니다.
+
'#/usr/sbin/esxcfg-boot -b'

. 다음 명령을 사용하여 서버를 재부팅합니다.
+
'#reboot'

. 다음 명령을 사용하여 변경 사항을 확인합니다.
+
.. '#esxcfg-module-g qla2300_707'
.. ``qla2300_707 활성화됨 = 1 옵션 = 'ql2xmaxqdepth=64''






== Emulex HBA용 VMware 호스트

'esxcfg-module' 명령을 사용하여 HBA 시간 제한 설정을 변경합니다. ESX.conf 파일을 수동으로 업데이트하는 것은 권장되지 않습니다.

.단계
. 서비스 콘솔에 루트 사용자로 로그온합니다.
. 현재 어떤 Emulex HBA가 로드되었는지 확인하려면 '#vmkload_mod -l grep lpfc' 명령을 사용합니다.
. Emulex HBA의 단일 인스턴스의 경우 다음 명령을 입력합니다.
+
'#esxcfg-module-s lpfc0_lun_queue_depth=16 lpfcdd_7xx'

+
[NOTE]
====
HBA 모델에 따라 모듈은 lpfcdd_7xx 또는 lpfcdd_732일 수 있습니다. 위 명령은 lpfcdd_7xx 모듈을 사용합니다. vmkload_mod-l의 결과에 따라 적절한 모듈을 사용해야 합니다.

====
+
이 명령을 실행하면 LUN 대기열 길이가 lpfc0으로 표시된 HBA에 대해 16으로 설정됩니다.

. Emulex HBA의 여러 인스턴스의 경우 다음 명령을 실행합니다.
+
"a esxcfg-module-s" lpfc0_lun_queue_depth=16 lpfc1_lun_queue_depth=16"lpfcdd_7xx"

+
lpfc0에 대한 LUN 큐 길이 및 lpfc1에 대한 LUN 큐 크기는 16으로 설정됩니다.

. 다음 명령을 입력합니다.
+
'#esxcfg-boot-b'

. reboot를 사용하여 재부팅합니다.




== Emulex HBA용 Windows 호스트

Windows 호스트에서는 "LPUTILNT" 유틸리티를 사용하여 Emulex HBA의 대기열 길이를 업데이트할 수 있습니다.

.단계
. C:\WINNT\system32 디렉토리에 있는 LPUTILNT 유틸리티를 실행합니다.
. 오른쪽의 메뉴에서 * Drive Parameters * 를 선택합니다.
. 아래로 스크롤하여 * QueueDepth * 를 두 번 클릭합니다.
+
[NOTE]
====
QueueDepth * 를 150보다 크게 설정하는 경우 다음 Windows 레지스트리 값도 적절하게 늘려야 합니다.

'HKEY_LOCAL_MACHINE\System\CurrentControlSet\Services\lpxnds\Parameters\Device\NumberOfRequests'를 선택합니다

====




== Qlogic HBA에 대한 Windows 호스트입니다

Windows 호스트에서는 및 'sansurfer' HBA 관리자 유틸리티를 사용하여 Qlogic HBA의 대기열 깊이를 업데이트할 수 있습니다.

.단계
. '서퍼' HBA 매니저 유틸리티를 실행합니다.
. HBA 포트 * > * 설정 * 을 클릭합니다.
. 목록 상자에서 * 고급 HBA 포트 설정 * 을 클릭합니다.
. Execution Throttle 파라미터를 업데이트한다.




== Emulex HBA용 Linux 호스트

Linux 호스트에서 Emulex HBA의 대기열 깊이를 업데이트할 수 있습니다. 재부팅 후에도 업데이트가 지속되도록 하려면 새 RAM 디스크 이미지를 생성하고 호스트를 재부팅해야 합니다.

.단계
. 수정할 대기열 길이 매개 변수를 식별합니다.
+
Modinfo lpfc | grep queue_depth(Modinfo lpfc | grep queue_depth

+
설명이 포함된 대기열 길이 매개 변수 목록이 표시됩니다. 운영 체제 버전에 따라 다음 대기열 길이 매개 변수 중 하나 이상을 수정할 수 있습니다.

+
** 'lpfc_lun_queue_depth': 특정 LUN에 대기할 수 있는 최대 FC 명령어 수(uint)
** 'lpfc_hba_queue_depth': lpfc HBA(uint)에 대기할 수 있는 최대 FC 명령어 수
** 'lpfc_tgt_queue_depth': 특정 대상 포트에 대기할 수 있는 최대 FC 명령어 수(uint)
+
"lpfc_tgt_queue_depth" 매개변수는 Red Hat Enterprise Linux 7.x 시스템, SUSE Linux Enterprise Server 11 SP4 시스템 및 12.x 시스템에만 적용됩니다.



. Red Hat Enterprise Linux 5.x 시스템에 대한 '/etc/modprobe.conf' 파일과 Red Hat Enterprise Linux 6.x 또는 7.x 시스템에 대한 '/etc/modprobe.d/scsi.conf' 파일 또는 SUSE Linux Enterprise Server 11.x 또는 12.x 시스템에 대기열 길이 매개 변수를 추가하여 대기열 깊이를 업데이트합니다.
+
운영 체제 버전에 따라 다음 명령 중 하나 이상을 추가할 수 있습니다.

+
** 'options lpfc lpfc_hba_queue_depth=new_queue_depth'
** 'options lpfc lpfc_lun_queue_depth=new_queue_depth'
** 'options lpfc_tgt_queue_depth=new_queue_depth'


. 새 RAM 디스크 이미지를 만든 다음 호스트를 재부팅하여 재부팅 후에도 업데이트가 지속되도록 합니다.
+
자세한 내용은 를 참조하십시오 link:../system-admin/index.html["시스템 관리"] Linux 운영 체제 버전용.

. 수정한 각 대기열 길이 매개 변수에 대해 대기열 길이 값이 업데이트되었는지 확인합니다.
+
'cat/sys/class/scsi_host/host_number/lpfc_lun_queue_depth''cat/sys/class/scsi_host/host_number/lpfc_tgt_queue_depth''cat/sys/class/scsi_host/host_number/lpfc_hba_queue_depth'

+
[listing]
----
root@localhost ~]#cat /sys/class/scsi_host/host5/lpfc_lun_queue_depth
      30
----
+
대기열 깊이의 현재 값이 표시됩니다.





== QLogic HBA용 Linux 호스트

Linux 호스트에서 QLogic 드라이버의 장치 대기열 길이를 업데이트할 수 있습니다. 재부팅 후에도 업데이트가 지속되도록 하려면 새 RAM 디스크 이미지를 생성하고 호스트를 재부팅해야 합니다. QLogic HBA 관리 GUI 또는 CLI(명령줄 인터페이스)를 사용하여 QLogic HBA 대기열 길이를 수정할 수 있습니다.

이 작업은 QLogic HBA CLI를 사용하여 QLogic HBA 대기열 길이를 수정하는 방법을 보여줍니다

.단계
. 수정할 장치 대기열 길이 매개 변수를 식별합니다.
+
'modinfo qla2xxx | grep ql2xmaxqdepth'

+
각 LUN에 대해 설정할 수 있는 최대 대기열 길이를 나타내는 "ql2xmaxqdepth" 대기열 길이 매개변수만 수정할 수 있습니다. RHEL 7.5 이상의 경우 기본값은 64입니다. 기본값은 RHEL 7.4 이전 버전의 경우 32입니다.

+
[listing]
----
root@localhost ~]# modinfo qla2xxx|grep ql2xmaxqdepth
parm:       ql2xmaxqdepth:Maximum queue depth to set for each LUN. Default is 64. (int)
----
. 장치 대기열 깊이 값 업데이트:
+
** 수정 사항을 영구적으로 만들려면 다음 단계를 수행하십시오.
+
... Red Hat Enterprise Linux 5.x 시스템에 대한 '/etc/modprobe.conf' 파일과 Red Hat Enterprise Linux 6.x 또는 7.x 시스템에 대한 '/etc/modprobe.d/scsi.conf' 파일에 대기열 깊이 매개 변수를 추가하거나 SUSE Linux Enterprise Server 11.x 또는 12.x 시스템에 대한 '/etc/modprobe.conf' 파일에 대기열 길이를 업데이트합니다. laq2xxx.options
... 새 RAM 디스크 이미지를 만든 다음 호스트를 재부팅하여 재부팅 후에도 업데이트가 지속되도록 합니다.
+
자세한 내용은 를 참조하십시오 link:../system-admin/index.html["시스템 관리"] Linux 운영 체제 버전용.



** 현재 세션에 대해서만 매개 변수를 수정하려면 다음 명령을 실행합니다.
+
'echo new_queue_depth>/sys/module/qla2xxx/parameters/ql2xmaxqdepth'

+
다음 예제에서 대기열 길이는 128로 설정됩니다.

+
[listing]
----
echo 128 > /sys/module/qla2xxx/parameters/ql2xmaxqdepth
----


. 대기열 길이 값이 업데이트되었는지 확인합니다.
+
'cat/sys/module/qla2xxx/parameters/ql2xmaxqdepth'

+
대기열 깊이의 현재 값이 표시됩니다.

. QLogic HBA BIOS에서 펌웨어 매개변수 "실행 스로틀"을 업데이트하여 QLogic HBA 대기열 길이를 수정합니다.
+
.. QLogic HBA 관리 CLI에 로그인합니다.
+
'/opt/QLogic_Corporation/QConvergConsoleCLI/qaucli'

.. 주 메뉴에서 "어댑터 구성" 옵션을 선택합니다.
+
[listing]
----
[root@localhost ~]# /opt/QLogic_Corporation/QConvergeConsoleCLI/qaucli
Using config file: /opt/QLogic_Corporation/QConvergeConsoleCLI/qaucli.cfg
Installation directory: /opt/QLogic_Corporation/QConvergeConsoleCLI
Working dir: /root

QConvergeConsole

        CLI - Version 2.2.0 (Build 15)

    Main Menu

    1:  Adapter Information
    **2:  Adapter Configuration**
    3:  Adapter Updates
    4:  Adapter Diagnostics
    5:  Monitoring
    6:  FabricCache CLI
    7:  Refresh
    8:  Help
    9:  Exit


        Please Enter Selection: 2
----
.. 어댑터 구성 매개 변수 목록에서 'HBA Parameters' 옵션을 선택합니다.
+
[listing]
----
1:  Adapter Alias
    2:  Adapter Port Alias
    **3:  HBA Parameters**
    4:  Persistent Names (udev)
    5:  Boot Devices Configuration
    6:  Virtual Ports (NPIV)
    7:  Target Link Speed (iiDMA)
    8:  Export (Save) Configuration
    9:  Generate Reports
   10:  Personality
   11:  FEC
(p or 0: Previous Menu; m or 98: Main Menu; ex or 99: Quit)
        Please Enter Selection: 3
----
.. HBA 포트 목록에서 필요한 HBA 포트를 선택합니다.
+
[listing]
----
Fibre Channel Adapter Configuration

    HBA Model QLE2562 SN: BFD1524C78510
      1: Port   1: WWPN: 21-00-00-24-FF-8D-98-E0 Online
      2: Port   2: WWPN: 21-00-00-24-FF-8D-98-E1 Online
    HBA Model QLE2672 SN: RFE1241G81915
      3: Port   1: WWPN: 21-00-00-0E-1E-09-B7-62 Online
      4: Port   2: WWPN: 21-00-00-0E-1E-09-B7-63 Online


        (p or 0: Previous Menu; m or 98: Main Menu; ex or 99: Quit)
        Please Enter Selection: 1
----
+
HBA 포트의 세부 정보가 표시됩니다.

.. HBA Parameters(HBA 매개변수) 메뉴에서 Display HBA Parameters(HBA 매개변수 표시) 옵션을 선택하여 "Execution Throttle(실행 스로틀)" 옵션의 현재 값을 확인합니다.
+
실행 스로틀 옵션의 기본값은 65535입니다.

+
[listing]
----
HBA Parameters Menu

=======================================================
HBA           : 2 Port: 1
SN            : BFD1524C78510
HBA Model     : QLE2562
HBA Desc.     : QLE2562 PCI Express to 8Gb FC Dual Channel
FW Version    : 8.01.02
WWPN          : 21-00-00-24-FF-8D-98-E0
WWNN          : 20-00-00-24-FF-8D-98-E0
Link          : Online
=======================================================

    1:  Display HBA Parameters
    2:  Configure HBA Parameters
    3:  Restore Defaults


        (p or 0: Previous Menu; m or 98: Main Menu; x or 99: Quit)
        Please Enter Selection: 1
--------------------------------------------------------------------------------
HBA Instance 2: QLE2562 Port 1 WWPN 21-00-00-24-FF-8D-98-E0 PortID 03-07-00
Link: Online
--------------------------------------------------------------------------------
Connection Options             : 2 - Loop Preferred, Otherwise Point-to-Point
Data Rate                      : Auto
Frame Size                     : 2048
Hard Loop ID                   : 0
Loop Reset Delay (seconds)     : 5
Enable Host HBA BIOS           : Enabled
Enable Hard Loop ID            : Disabled
Enable FC Tape Support         : Enabled
Operation Mode                 : 0 - Interrupt for every I/O completion
Interrupt Delay Timer (100us)  : 0
**Execution Throttle             : 65535**
Login Retry Count              : 8
Port Down Retry Count          : 30
Enable LIP Full Login          : Enabled
Link Down Timeout (seconds)    : 30
Enable Target Reset            : Enabled
LUNs Per Target                : 128
Out Of Order Frame Assembly    : Disabled
Enable LR Ext. Credits         : Disabled
Enable Fabric Assigned WWN     : N/A

Press <Enter> to continue:
----
.. 계속하려면 * Enter * 를 누르십시오.
.. HBA Parameters(HBA 매개변수) 메뉴에서 Configure HBA Parameters(HBA 매개변수 구성) 옵션을 선택하여 HBA 매개변수를 수정합니다.
.. Configure Parameters 메뉴에서 'Execute Throttle' 옵션을 선택하고 이 매개 변수의 값을 업데이트합니다.
+
[listing]
----
Configure Parameters Menu

=======================================================
HBA           : 2 Port: 1
SN            : BFD1524C78510
HBA Model     : QLE2562
HBA Desc.     : QLE2562 PCI Express to 8Gb FC Dual Channel
FW Version    : 8.01.02
WWPN          : 21-00-00-24-FF-8D-98-E0
WWNN          : 20-00-00-24-FF-8D-98-E0
Link          : Online
=======================================================

    1:  Connection Options
    2:  Data Rate
    3:  Frame Size
    4:  Enable HBA Hard Loop ID
    5:  Hard Loop ID
    6:  Loop Reset Delay (seconds)
    7:  Enable BIOS
    8:  Enable Fibre Channel Tape Support
    9:  Operation Mode
   10:  Interrupt Delay Timer (100 microseconds)
   11:  Execution Throttle
   12:  Login Retry Count
   13:  Port Down Retry Count
   14:  Enable LIP Full Login
   15:  Link Down Timeout (seconds)
   16:  Enable Target Reset
   17:  LUNs per Target
   18:  Enable Receive Out Of Order Frame
   19:  Enable LR Ext. Credits
   20:  Commit Changes
   21:  Abort Changes


        (p or 0: Previous Menu; m or 98: Main Menu; x or 99: Quit)
        Please Enter Selection: 11
Enter Execution Throttle [1-65535] [65535]: 65500
----
.. 계속하려면 * Enter * 를 누르십시오.
.. Configure Parameters 메뉴에서 'Commit Changes' 옵션을 선택하여 변경 사항을 저장합니다.
.. 메뉴를 종료합니다.



