---
permalink: san-config/support-shared-san-config-concept.html 
sidebar: sidebar 
keywords: requirements, shared, san, configurations 
summary: 공유 SAN 구성은 ONTAP 스토리지 시스템과 다른 공급업체의 스토리지 시스템에 모두 연결된 호스트로 정의됩니다. 여러 요구 사항이 충족될 경우 단일 호스트에서 ONTAP 스토리지 시스템 및 다른 공급업체의 스토리지 시스템에 액세스할 수 있습니다. 
---
= 공유 SAN 구성에 대한 요구사항
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
공유 SAN 구성은 ONTAP 스토리지 시스템과 다른 공급업체의 스토리지 시스템에 모두 연결되는 호스트로 정의됩니다. 여러 요구사항을 충족할 경우, 단일 호스트에서 ONTAP 스토리지 시스템 및 다른 공급업체의 스토리지 시스템에 액세스할 수 있습니다.

모든 호스트 운영 체제에서 별도의 어댑터를 사용하여 각 공급업체의 스토리지 시스템에 연결하는 것이 좋습니다. 별도의 어댑터를 사용하면 드라이버와 설정이 충돌할 가능성이 줄어듭니다. ONTAP 스토리지 시스템에 연결하려면 어댑터 모델, BIOS, 펌웨어 및 드라이버가 NetApp 상호 운용성 매트릭스 툴에 지원되는 것으로 표시되어야 합니다.

호스트에 대해 필수 또는 권장 시간 초과 값과 기타 스토리지 매개 변수를 설정해야 합니다. 항상 NetApp 소프트웨어를 설치하거나 NetApp 설정을 마지막에 적용해야 합니다.

* AIX의 경우 구성의 상호 운용성 매트릭스 툴에 나열된 AIX Host Utilities 버전의 값을 적용해야 합니다.
* ESX의 경우 VMware vSphere용 Virtual Storage Console을 사용하여 호스트 설정을 적용해야 합니다.
* HP-UX의 경우 HP-UX 기본 스토리지 설정을 사용해야 합니다.
* Linux의 경우 구성의 상호 운용성 매트릭스 툴에 나열된 Linux Host Utilities 버전의 값을 적용해야 합니다.
* Solaris의 경우, 구성의 상호 운용성 매트릭스 툴에 나열된 Solaris Host Utilities 버전의 값을 적용해야 합니다.
* Windows의 경우 구성의 상호 운용성 매트릭스 툴에 나열된 Windows Host Utilities 버전을 설치해야 합니다.


.관련 정보
https://["NetApp 상호 운용성 매트릭스 툴"^]
