---
permalink: upgrade/concept_considerations_for_session_oriented_protocols.html 
sidebar: sidebar 
keywords: ontap, upgrade, update, considerations, session-oriented, protocols 
summary: 클러스터 및 세션 중심 프로토콜은 업그레이드 중 특정 영역의 클라이언트 및 애플리케이션에 부정적인 영향을 미칠 수 있습니다. 
---
= 세션 지향 프로토콜에 대한 고려 사항
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
클러스터 및 세션 중심 프로토콜은 업그레이드 중 특정 영역의 클라이언트 및 애플리케이션에 부정적인 영향을 미칠 수 있습니다.

세션 지향 프로토콜을 사용하는 경우 다음 사항을 고려하십시오.

* 중소기업
+
SMBv3에서 지속적으로 사용 가능한(CA) 공유를 제공하는 경우 System Manager 또는 CLI를 통해 자동화된 무중단 업그레이드 방법을 사용할 수 있으며 클라이언트에서 중단이 발생하지 않습니다.

+
SMBv1 또는 SMBv2와 함께 공유 또는 SMBv3과 비 CA 공유를 제공하는 경우 업그레이드 테이크오버 및 재부팅 작업 중에 클라이언트 세션이 중단됩니다. 업그레이드하기 전에 사용자에게 세션을 종료하도록 안내해야 합니다.

+
자세한 내용은 을 참조하십시오 link:https://www.netapp.com/pdf.html?item=/media/16338-tr-4100pdf.pdf["TR-4100: SMB 파일 공유를 통한 무중단 운영 ONTAP 9.x"^].

+
SMB를 통한 Hyper-V 및 SQL Server는 무중단 운영(NDO)을 지원합니다. SMB 솔루션을 통해 Hyper-V 또는 SQL Server를 구성한 경우, 애플리케이션 서버와 포함된 가상 머신 또는 데이터베이스는 ONTAP 업그레이드 중에 온라인 상태를 유지하고 지속적인 가용성을 제공합니다.

* NFSv4.x
+
NFSv4.x 클라이언트는 정상 NFSv4.x 복구 절차를 사용하여 업그레이드 중에 발생한 연결 손실로부터 자동으로 복구합니다. 이 프로세스 중에 애플리케이션이 일시적으로 I/O 지연을 겪을 수 있습니다.

* NDMP
+
상태가 손실되었으며 클라이언트 사용자가 작업을 재시도해야 합니다.

* 백업 및 복원
+
상태가 손실되었으며 클라이언트 사용자가 작업을 재시도해야 합니다.

+

IMPORTANT: 업그레이드 도중이나 업그레이드 직전에 백업 또는 복원을 시작하지 마십시오. 이렇게 하면 데이터가 손실될 수 있습니다.

* 애플리케이션(예: Oracle 또는 Exchange)
+
효과는 애플리케이션에 따라 다릅니다. 시간 초과 기반 응용 프로그램의 경우 시간 초과 설정을 ONTAP 재부팅 시간보다 길게 변경하여 부작용을 최소화할 수 있습니다.


