---
permalink: upgrade/concept_mixed_version_requirements.html 
sidebar: sidebar 
keywords: ontap, upgrade, mixed, version, requirements 
summary: ONTAP 9.3부터는 기본적으로 기존 노드에서 실행 중인 버전과 다른 ONTAP 버전을 실행 중인 클러스터에 새 노드를 추가할 수 없습니다. 
---
= 혼합 버전 요구 사항
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9.3부터는 기본적으로 기존 노드에서 실행 중인 버전과 다른 ONTAP 버전을 실행 중인 클러스터에 새 노드를 추가할 수 없습니다.

기존 클러스터의 노드 수보다 늦은 ONTAP 버전을 실행 중인 클러스터에 새 노드를 추가하려는 경우, 먼저 클러스터의 노드를 최신 버전으로 업그레이드한 다음 새 노드를 추가해야 합니다.

혼합 버전 클러스터는 권장되지 않지만 경우에 따라 일시적으로 혼합 버전 상태를 입력해야 할 수도 있습니다. 예를 들어, 기존 클러스터의 특정 노드에서 지원되지 않는 최신 버전의 ONTAP로 업그레이드하는 경우 혼합 버전 상태를 입력해야 합니다. 이 경우 최신 버전의 ONTAP를 지원하는 노드를 업그레이드한 다음, 고급 권한 'cluster unjoin-skip-lastlow-version-node check' 명령을 사용하여 업그레이드하려는 ONTAP 버전을 지원하지 않는 노드의 가입을 해제해야 합니다.

또한 기술 업데이트나 중단된 업그레이드를 위해 혼합 버전 상태를 입력해야 할 수도 있습니다. 이러한 경우 다음 고급 권한 명령을 사용하여 ONTAP 9.3 기본 동작을 재정의하고 다른 버전의 노드를 결합할 수 있습니다.

* '클러스터 결합-허용-혼합-버전-조인'
* 'cluster add-node-allow-mixed-version-join'


혼합 버전 상태를 입력해야 하는 경우 가능한 한 빨리 업그레이드를 완료해야 합니다. HA 쌍이 클러스터에서 다른 HA 쌍과 다른 ONTAP 버전을 7일 이상 실행하면 안 됩니다. 올바른 클러스터 작동을 위해 클러스터가 혼합 버전 상태에 있는 기간은 가능한 짧아야 합니다.

클러스터가 혼합 버전 상태인 경우, 업그레이드 요구사항을 충족하는 데 필요한 경우를 제외하고 클러스터 작업 또는 구성을 변경하는 명령을 입력할 수 없습니다.
