---
permalink: upgrade/concept_upgrade_requirements_for_snapmirror.html 
sidebar: sidebar 
keywords: ontap, upgrade, requirements, snapmirror 
summary: SnapMirror를 실행 중인 클러스터를 성공적으로 업그레이드하려면 특정 작업을 수행해야 합니다. 
---
= SnapMirror의 업그레이드 요구 사항
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapMirror를 실행 중인 클러스터를 성공적으로 업그레이드하려면 특정 작업을 수행해야 합니다.

* DP SnapMirror 관계로 클러스터를 업그레이드하는 경우 소스 클러스터/노드를 업그레이드하기 전에 대상 클러스터/노드를 업그레이드해야 합니다.
* SnapMirror를 실행 중인 클러스터를 업그레이드하기 전에 대상 볼륨이 포함된 각 노드에 대해 SnapMirror 작업을 중지해야 합니다. 피어링된 각 SVM은 클러스터 전체에서 고유한 이름을 가져야 합니다.
+
SnapMirror 전송이 실패하지 않도록 하려면 SnapMirror 작업을 일시 중단하고 경우에 따라 소스 노드를 업그레이드하기 전에 대상 노드를 업그레이드해야 합니다. 다음 표에서는 SnapMirror 작업을 일시 중단하는 두 가지 옵션을 설명합니다.

+
[cols="3*"]
|===
| 옵션을 선택합니다 | 설명 | 소스 노드 전에 대상 노드를 업그레이드하시겠습니까? 


 a| 
NDU(무중단 업그레이드) 동안 SnapMirror 작업을 일시 중단합니다.
 a| 
SnapMirror 환경에서 가장 간단한 업그레이드 방법은 모든 SnapMirror 작업을 일시 중지하고 업그레이드를 수행한 다음 SnapMirror 작업을 다시 시작하는 것입니다. 하지만 전체 NDU 중에는 SnapMirror 전송이 수행되지 않습니다. 볼륨에 볼륨을 미러링하는 노드가 클러스터에 포함된 경우 이 방법을 사용해야 합니다.
 a| 
아니요. 노드를 어떤 순서로든 업그레이드할 수 있습니다.



 a| 
한 번에 하나의 대상 볼륨에 SnapMirror 작업을 일시 중단합니다.
 a| 
특정 대상 볼륨에 대한 SnapMirror 전송을 일시 중지하고, 대상 볼륨이 포함된 노드(또는 HA 쌍)를 업그레이드하고, 소스 볼륨이 포함된 노드(또는 HA 쌍)를 업그레이드한 다음, 대상 볼륨에 대한 SnapMirror 전송을 다시 시작할 수 있습니다. 이 방법을 사용하면 원본 대상 및 소스 볼륨이 포함된 노드가 업그레이드되는 동안 다른 모든 대상 볼륨에 대한 SnapMirror 전송이 계속됩니다.
 a| 
예.

|===


SVM 피어링을 사용하려면 클러스터 전체에서 SVM 이름이 고유해야 합니다. "dataVerser.HQ" 또는 "mirorVserver.오프사이트"와 같이 고유한 FQDN(정규화된 도메인 이름)으로 SVM을 명명하는 것이 좋습니다. FQDN 명명 스타일을 사용하면 고유성을 더욱 쉽게 확인할 수 있습니다.

link:../concepts/index.html["ONTAP 개념"]
