---
permalink: upgrade/concept_upgrade_paths.html 
sidebar: sidebar 
keywords: ontap, upgrade, paths 
summary: 업그레이드할 수 있는 ONTAP 버전은 현재 노드에서 실행 중인 ONTAP 버전에 따라 다릅니다. 
---
= 업그레이드할 수 있는 ONTAP 버전은 무엇입니까?
:hardbreaks:
:icons: font
:imagesdir: ../media/


[role="lead"]
업그레이드할 수 있는 ONTAP 버전은 하드웨어 플랫폼 및 현재 노드에서 실행 중인 ONTAP 버전에 따라 다릅니다. 을 참조하십시오 https://hwu.netapp.com["NetApp Hardware Universe를 참조하십시오"^] 대상 업그레이드 릴리스에 대해 플랫폼이 지원되는지 확인하려면 다음을 수행합니다.

* 참고: * 이 지침은 온프레미스 ONTAP 릴리스에만 적용됩니다. 클라우드에서 ONTAP 업그레이드에 대한 자세한 내용은 를 참조하십시오 https://docs.netapp.com/us-en/occm/task_updating_ontap_cloud.html["Cloud Volumes ONTAP 소프트웨어 업그레이드 중"^].

현재 ONTAP 버전을 확인하려면:

* System Manager에서 * Cluster > Overview * 를 클릭합니다.
* CLI(Command Line Interface)에서 cluster image show 명령을 사용합니다. +고급 권한 수준에서 'system node image show' 명령을 사용하여 세부 정보를 표시할 수도 있습니다.


가능하면 항상 자동 무중단 업그레이드(ANDU)가 권장됩니다. 현재 릴리즈와 타겟 릴리즈별로 업그레이드 경로는 _DIRECT_, _DIRECT 멀티 홉_ 또는 _다단계_입니다. 달리 명시되지 않은 한, 이 경로는 모두 적용됩니다 link:concept_upgrade_methods.html["업그레이드 방법"]무중단 또는 운영, 자동화 또는 수동

* _Direct_+ 단일 소프트웨어 이미지를 사용하여 항상 인접한 다음 ONTAP 릴리스 제품군으로 직접 업그레이드할 수 있습니다. 또한 대부분의 릴리스의 경우 소프트웨어 이미지를 설치하여 실행 중인 릴리즈보다 두 릴리즈 높은 릴리스로 직접 업그레이드할 수 있습니다. 예를 들어 직접 업데이트 경로를 9.8 - 9.9.1 또는 9.8 - 9.10.1로 사용할 수 있습니다.
* _Direct 다중 홉_+ 비인접 릴리스에 대한 일부 자동 무중단 업그레이드(ANDU)의 경우 중간 릴리즈와 대상 릴리스에 대한 소프트웨어 이미지를 설치할 수 있습니다. 자동 업그레이드 프로세스는 백그라운드에서 중간 이미지를 사용하여 대상 릴리스에 대한 업데이트를 완료합니다. 프로세스 중에 여러 테이크오버/반환 작업 및 관련 재부팅이 예상되어야 합니다. +이 업데이트 경로는 9.3에서 9.6 또는 9.7로, 9.5에서 9.8 또는 9.9.1로 ANDU 업데이트에만 해당됩니다. 예를 들어, 클러스터에서 9.3을 실행 중이고 9.7로 업그레이드하려는 경우 9.5와 9.7 모두에 대해 ONTAP 설치 패키지를 로드한 다음 9.7로 ANDU를 시작합니다. 그런 다음 ONTAP가 먼저 클러스터를 9.5로 업그레이드한 다음 9.7로 자동 업그레이드합니다.
* _multi-stage_+ 인접하지 않은 타겟 릴리즈에서 직접 또는 직접 멀티 홉 경로를 사용할 수 없는 경우 먼저 지원되는 중간 릴리즈로 업그레이드한 다음 대상 릴리즈로 업그레이드해야 합니다. 예를 들어, 현재 9.7을 실행 중이고 9.10.1로 업그레이드하려면 먼저 9.7 에서 9.9.1 로, 9.9.1 에서 9.10.1 로 업그레이드하는 다단계 업그레이드를 완료해야 합니다. 이전 릴리즈에서 업그레이드하려면 중간 업그레이드가 몇 차례 포함된 3개 이상의 단계가 필요할 수 있습니다. + * 참고: * 다단계 업그레이드를 시작하기 전에 하드웨어 플랫폼에서 타겟 릴리스가 지원되는지 확인하십시오.


이전 ONTAP 버전(예: 9.3)에서 ONTAP 업그레이드를 계획하는 경우, 동일한 ONTAP 릴리스 제품군의 최신 패치 릴리즈로 먼저 업그레이드한 다음 다음으로 지원되는 주요 릴리즈로 업그레이드하는 것이 좋습니다. 이렇게 하면 업그레이드하기 전에 이전 버전의 모든 문제가 해결됩니다.

예를 들어, 시스템에서 ONTAP 9.3P9를 실행 중이고 9.9.1로 업그레이드할 계획인 경우 모든 주요 ONTAP 버전에서 9.3P9 -> 9.3P21 -> 9.7 -> 9.9.1 업그레이드 경로를 따라 최신 패치 릴리스를 사용하십시오.



== ONTAP 9 릴리즈 제품군 내의 업그레이드 경로입니다

다음 표에는 지원되는 모든 업그레이드 경로가 나와 있습니다. 중단이 필요한 특정 시스템 구성을 제외하고, 표에 명시된 대로, 자동화된 수동 무중단 업그레이드 방법을 모든 경로에 사용할 수 있습니다. 일부 이전 릴리스의 업그레이드 이미지는 더 이상 사용할 수 없습니다.

[cols="3*"]
|===
| 현재 ONTAP 릴리스를 사용하는 경우… | 대상 ONTAP 릴리스는 다음과 같습니다. | 업그레이드 경로: 


| 9.9.1 | 9.10.1 | 직접 


.2+| 9.8 | 9.10.1 | 직접 


| 9.9.1 | 직접 


.3+| 9.7 | 9.10.1 | 다단계(9.9.1을 통해) 


| 9.9.1 | 직접 


| 9.8 | 직접 


.4+| 9.6 | 9.10.1 | 다단계(9.8을 통해) 


| 9.9.1 | 다단계(9.8을 통해) 


| 9.8 | 직접 


| 9.7 | 직접 


.5+| 9.5 | 9.10.1 | 다단계(9.8을 통해) 


| 9.9.1 | 직접 멀티 홉(ANDU만 해당, 9.7 및 9.9.1용 이미지 필요) + 기타 다중 단계(9.7을 통해) 


| 9.8 | 직접 멀티 홉(ANDU만 해당, 9.7 및 9.8용 이미지 필요) + 기타 다단계(9.7을 통해) 


| 9.7 | 직접 


| 9.6 | 직접 


.6+| 9.4 | 9.10.1 | 다단계(9.5 및 9.8을 통해) 


| 9.9.1 | 다단계(9.5 및 9.8을 통해) 


| 9.8 | 다단계(9.5 사용) 


| 9.7 | 다단계(9.5 사용) 


| 9.6 | 다단계(9.5 사용) 


| 9.5 | 직접 


.7+| 9.3 | 9.10.1 | 다단계(9.7 및 9.9.1을 통해) 


| 9.9.1 | 다단계(9.8을 통해) 


| 9.8 | 다단계(9.7을 통해) 


| 9.7 | 직접 멀티 홉(ANDU만 해당, 9.5 및 9.7용 이미지 필요) + 기타 멀티 스테이지(9.5 사용) 


| 9.6 | 직접 멀티 홉, ANDU 전용(9.5 및 9.6의 경우 이미지 필요) + 기타 다단계(9.5를 통해) 


| 9.5 | 직접 


| 9.4 | 사용할 수 없습니다 


.8+| 9.2 | 9.10.1 | 다단계(9.3, 9.7 및 9.9.1을 통해) 


| 9.9.1 | 다단계(9.3 및 9.7을 통해) 


| 9.8 | 다단계(9.7을 통해) 


| 9.7 | 다단계(9.3을 통해) 


| 9.6 | 다단계(9.3을 통해) 


| 9.5 | 다단계(9.3을 통해) 


| 9.4 | 사용할 수 없습니다 


| 9.3 | 직접 


.9+| 9.1 | 9.10.1 | 다단계(9.3, 9.7 및 9.9.1을 통해) 


| 9.9.1 | 다단계(9.3 및 9.7을 통해) 


| 9.8 | 다단계(9.3 및 9.7을 통해) 


| 9.7 | 다단계(9.3을 통해) 


| 9.6 | 다단계(9.3을 통해) 


| 9.5 | 다단계(9.3을 통해) 


| 9.4 | 사용할 수 없습니다 


| 9.3 | 직접 


| 9.2 | 사용할 수 없습니다 


.10+| 9.0 | 9.10.1 | 다단계(9.1, 9.3, 9.7 및 9.9.1을 통해) 


| 9.9.1 | 다단계(9.1, 9.3 및 9.7을 통해) 


| 9.8 | 다단계(9.1, 9.3 및 9.7을 통해) 


| 9.7 | 다단계(9.1 및 9.3을 통해) 


| 9.6 | 다단계(9.1 및 9.3을 통해) 


| 9.5 | 다단계(9.1 및 9.3을 통해) 


| 9.4 | 사용할 수 없습니다 


| 9.3 | 다단계(9.1을 통해) 


| 9.2 | 사용할 수 없습니다 


| 9.1 | 직접 
|===


== Data ONTAP 8. * 릴리즈에서 ONTAP 9 릴리즈로 업그레이드 경로 제공

NetApp Hardware Universe 참조 를 사용하여 플랫폼에서 타겟 ONTAP 릴리즈를 실행할 수 있는지 확인하십시오.

* 참고: * Data ONTAP 8.3 업그레이드 가이드에 4노드 클러스터의 경우 epsilon을 마지막으로 보유하는 노드를 업그레이드할 계획이라는 오류 메시지가 표시됩니다. Data ONTAP 8.2.3부터 계속 업그레이드할 필요는 없습니다. 자세한 내용은 을 참조하십시오 https://mysupport.netapp.com/site/bugs-online/product/ONTAP/BURT/805277["NetApp 버그 온라인 버그 ID 805277"^].

Data ONTAP 8.3.x에서:: ONTAP 9.1로 직접 업그레이드한 다음 에 설명된 대로 이후 릴리즈로 업그레이드할 수 있습니다 <<ontap9_paths>>.
8.2.x를 포함한 Data ONTAP 8.3.x 이전 버전에서:: 먼저 Data ONTAP 8.3.x로 업그레이드한 다음 ONTAP 9.1로 업그레이드한 다음, 에 설명된 대로 최신 릴리즈로 업그레이드해야 합니다 <<ontap9_paths>>.

