---
permalink: upgrade/concept_mixed_version_requirements.html 
sidebar: sidebar 
keywords: ontap, upgrade, mixed, version, clusters, mixed-version nodes, requirements 
summary: 혼합 버전 ONTAP 클러스터는 ONTAP 9.8 및 9.12.1과 같이 두 가지 주요 ONTAP 릴리스를 실행하는 노드로 구성됩니다. 혼합 버전 ONTAP 클러스터는 특정 시나리오에서 NetApp에서만 지원됩니다. 
---
= 혼합 버전 ONTAP 클러스터
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
혼합 버전 ONTAP 클러스터는 ONTAP 9.8 및 9.12.1, ONTAP 9.9.1 및 9.13.1 등 두 가지 주요 ONTAP 릴리즈를 실행하는 노드로 구성됩니다. 혼합 버전 ONTAP 클러스터는 특정 시나리오에서 NetApp에서만 지원됩니다.

가장 일반적인 두 가지 시나리오는 다음과 같습니다.

* 대규모 클러스터에서 ONTAP 소프트웨어 업그레이드
* 클러스터에 새 컨트롤러를 추가할 계획이라면 ONTAP 소프트웨어 업그레이드가 필요합니다


이 콘텐츠는 AFF, ASA, FAS, C-Series 시스템과 같은 NetApp 플랫폼 시스템을 지원하는 ONTAP 버전에 적용됩니다.  이 정보는 9.12.0과 같은 ONTAP 클라우드 릴리스(9.x.0)에는 적용되지 않습니다.



== 혼합 버전 ONTAP 클러스터의 요구 사항

클러스터에서 혼합 ONTAP 버전 상태를 입력해야 하는 모든 시나리오에서는 중요한 요구사항과 제한 사항을 알아야 합니다.

* 한 클러스터에 다른 주요 ONTAP 버전은 항상 두 개 이상 존재할 수 없습니다. ONTAP 9.9.1P1 및 9.9.1P5와 같이 동일한 ONTAP 릴리스의 서로 다른 P 또는 D 패치 수준에서 실행되는 노드가 있는 클러스터는 혼합 버전 ONTAP 클러스터로 간주되지 않습니다.
* 클러스터가 혼합 버전 상태일 때 업그레이드 요구사항을 충족하는 데 필요한 경우를 제외하고 클러스터 작업 또는 구성을 변경하는 명령을 입력할 수 없습니다. 컨트롤러 업그레이드 활동을 지원하기 위해 혼합 버전의 ONTAP 클러스터에서 볼륨 이동 작업이 지원됩니다.
* 최적의 클러스터 운영을 위해서는 클러스터가 혼합 버전 상태에 있는 시간이 최대한 짧아야 합니다.  클러스터가 혼합 버전 상태로 유지될 수 있는 최대 기간은 클러스터에서 가장 낮은 ONTAP 버전에 따라 다릅니다.
+
[cols="2*"]
|===
| 혼합 버전 클러스터에서 실행 중인 ONTAP의 최하위 버전이 다음과 같은 경우: | 그런 다음 최대 의 혼합 버전 상태를 유지할 수 있습니다 


| ONTAP 9.8 이상 | 90일 


| ONTAP 9.7 이하 | 7일 
|===
* ONTAP 9.8부터 혼합 버전의 ONTAP 클러스터는 최대 4개의 주요 릴리즈를 포괄할 수 있습니다. 예를 들어 혼합 버전의 ONTAP 클러스터에는 ONTAP 9.8과 9.12.1을 실행하는 노드가 있거나 ONTAP 9.9.1 및 9.13.1 노드를 실행하는 노드가 있을 수 있습니다. 그러나 ONTAP 9.8 및 9.13.1 노드를 실행하는 혼합 버전 ONTAP 클러스터는 5개의 주요 릴리스에 걸쳐 있으므로 지원되지 않습니다.




== 대규모 클러스터의 ONTAP 버전 업데이트

각 버전의 ONTAP는 보다 강력한 기능 세트를 제공합니다. 더 큰 클러스터의 ONTAP 버전을 업그레이드하여 최신 버전의 ONTAP로 업그레이드해야 하는 경우, 클러스터의 각 노드를 업그레이드할 때 일정 기간 동안 혼합 버전 클러스터 상태를 입력해야 합니다.



== 클러스터에 새 노드 추가

새 노드를 클러스터에 추가하여 용량을 확장하거나 컨트롤러를 완전히 교체할 수 있습니다. 어느 경우든 이전 컨트롤러에서 새 시스템으로 데이터를 마이그레이션할 수 있어야 합니다.

클러스터에 새 노드를 추가할 계획이고 해당 노드에 클러스터의 기존 노드 수보다 늦은 ONTAP 버전이 필요한 경우 클러스터의 모든 기존 노드를 먼저 최신 ONTAP 버전으로 업그레이드한 다음 새 노드를 추가해야 합니다. 그러나 기존 노드 중 일부가 최신 버전의 ONTAP를 지원하지 않기 때문에 이 작업을 수행할 수 없는 경우에는 업그레이드 프로세스의 일부로 제한된 시간 동안 혼합 버전 상태를 입력해야 합니다.
새 컨트롤러에 필요한 최저 ONTAP 버전을 지원하지 않는 노드가 있는 경우 다음을 수행해야 합니다.

. link:https://docs.netapp.com/us-en/ontap/upgrade/concept_upgrade_methods.html["업그레이드"] 새 컨트롤러의 ONTAP 버전을 지원하는 클러스터의 노드입니다.
. 클러스터에 새 노드를 추가합니다.
+
고급 권한 수준에서 ONTAP 명령 cluster add-node-allow-mixed-version-join을 사용하여 새 노드를 조인합니다.

. 업그레이드할 수 없는 노드에서 상위 ONTAP 버전을 실행하는 노드로 데이터를 마이그레이션합니다.
. link:https://docs.netapp.com/us-en/ontap/system-admin/remov-nodes-cluster-concept.html["클러스터에서 지원되지 않는 노드를 제거합니다"^].
+
ONTAP 명령 cluster remove-node-skip-last-low-version-node-check를 사용하여 이러한 노드를 제거합니다. (ONTAP 9.3 이전 버전에서는 cluster unjoin-skip-last-low-version-node-check 명령을 사용합니다.)



데이터 마이그레이션에 대한 자세한 내용은 다음을 참조하십시오.

* link:https://docs.netapp.com/us-en/ontap-systems-upgrade/upgrade/upgrade-create-aggregate-move-volumes.html["애그리게이트를 생성하고 볼륨을 새 노드로 이동합니다"^]
* link:https://docs.netapp.com/us-en/ontap-metrocluster/transition/task_move_linux_iscsi_hosts_from_mcc_fc_to_mcc_ip_nodes.html#setting-up-new-iscsi-connections["SAN 볼륨 이동에 대한 새 iSCSI 연결을 설정합니다"^]
* link:https://docs.netapp.com/us-en/ontap/encryption-at-rest/encrypt-existing-volume-task.html["암호화를 사용하여 볼륨 이동"^]

