---
permalink: upgrade/concept_upgrade_requirements_for_metrocluster_configurations.html 
sidebar: sidebar 
keywords: ontap, upgrade, update, requirements, metrocluster, mcc, general, normal, operations, switchover 
summary: MetroCluster 구성을 업그레이드해야 하는 경우 몇 가지 중요한 요구 사항을 알고 있어야 합니다. 
---
= MetroCluster 구성에 대한 업그레이드 요구 사항
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
MetroCluster 구성을 업그레이드해야 하는 경우 몇 가지 중요한 요구 사항을 알고 있어야 합니다.



== MetroCluster 구성의 주요 업그레이드와 부수적인 업그레이드를 수행하는 데 필요한 방법입니다

MetroCluster 구성에 대한 패치 업그레이드는 자동 NDU(무중단 업그레이드) 절차를 통해 수행할 수 있습니다.

ONTAP 9.3부터 MetroCluster 구성에 대한 주요 업그레이드는 자동 NDU(무중단 업그레이드) 절차를 통해 수행할 수 있습니다. ONTAP 9.2 이하를 실행하는 시스템에서 MetroCluster 구성에 대한 주요 업그레이드는 MetroCluster 구성별 NDU 절차를 통해 수행해야 합니다.



== 일반 요구 사항

* 두 클러스터 모두 동일한 버전의 ONTAP를 실행해야 합니다.
+
version 명령을 사용하여 ONTAP 버전을 확인할 수 있습니다.

* MetroCluster 구성은 정상 또는 절체 모드여야 합니다.
+

NOTE: 전환 모드의 업그레이드는 사소한 패치 업그레이드에서만 지원됩니다.

* 2노드 클러스터를 제외한 모든 구성에서 두 클러스터를 중단 없이 업그레이드할 수 있습니다.
+
2노드 클러스터에서 무중단 업그레이드를 위해서는 클러스터를 한 번에 하나의 노드씩 업그레이드해야 합니다.

* 두 클러스터의 애그리게이트는 RAID 상태를 재동기화하지 않아야 합니다.
+
MetroCluster 복구 중에 미러링된 애그리게이트가 재동기화됩니다. 'Storage aggregate plex show-in-progress true' 명령을 사용하여 MetroCluster 구성이 이 상태인지 확인할 수 있습니다. 동기화 중인 애그리게이트가 있는 경우 재동기화가 완료될 때까지 업그레이드를 수행하면 안 됩니다.

* 업그레이드 진행 중에는 협상된 전환 작업이 실패합니다.
+
업그레이드 또는 복원 작업 관련 문제를 방지하려면 두 클러스터의 모든 노드가 동일한 버전의 ONTAP를 실행하지 않는 한 업그레이드 또는 복원 작업 중에 계획되지 않은 전환을 시도하지 마십시오.





== 정상 작동을 위한 구성 요구 사항

* 소스 SVM LIF가 홈 노드에 위치해야 합니다.
+
타겟 SVM에 대한 데이터 LIF는 홈 노드에 있을 필요가 없습니다.

* 로컬 사이트의 모든 애그리게이트는 온라인 상태여야 합니다.
* 로컬 클러스터의 SVM이 소유하는 모든 루트 및 데이터 볼륨은 온라인 상태여야 합니다.




== 전환을 위한 구성 요구사항

* 모든 LIF는 홈 노드에 위치해야 합니다.
* DR 사이트의 루트 애그리게이트를 제외하고 모든 애그리게이트는 온라인 상태여야 합니다.
+
DR 사이트의 루트 애그리게이트는 특정 전환 단계 중에 오프라인 상태입니다.

* 모든 볼륨이 온라인 상태여야 합니다.


.관련 정보
link:task_verifying_the_networking_and_storage_status_for_metrocluster_cluster_is_ready.html["MetroCluster 구성에 대한 네트워킹 및 스토리지 상태 확인"]
