---
permalink: upgrade/create-upgrade-plan.html 
sidebar: sidebar 
keywords: ontap, upgrade, plan, planning, upgrade advisor, advisor, digital advisor, active iq, create an upgrade plan, estimate upgrade, 
summary: Digital Advisor의 Upgrade Advisor 서비스는 업그레이드를 계획하고 불확실성과 위험을 최소화할 수 있는 인텔리전스를 제공합니다. 
---
= 업그레이드 관리자를 통해 ONTAP 업그레이드 계획을 세우십시오
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
에 대한 활성  계약이 있는 경우 link:https://www.netapp.com/us/services/support-edge.aspx["SupportEdge 서비스"^]link:https://docs.netapp.com/us-en/active-iq/upgrade_advisor_overview.html["디지털 자문업체"^]Upgrade Advisor를 사용하여 업그레이드 계획을 생성하는 것이 좋습니다.

Digital Advisor의 Upgrade Advisor 서비스는 업그레이드를 계획하고 불확실성과 위험을 최소화할 수 있는 인텔리전스를 제공합니다.

Digital Advisor는 최신 버전의 ONTAP로 업그레이드하여 해결할 수 있는 환경 문제를 식별합니다. 업그레이드 관리자 서비스는 성공적인 업그레이드를 계획하는 데 도움이 되며, 업그레이드하는 ONTAP 버전에서 알아야 할 문제에 대한 보고서를 제공합니다.


NOTE: Upgrade Advisor를 사용하려면 보고서를 생성하려면 전체 AutoSupport 번들이 필요합니다.

Digital Advisor에 대해 유효한 Support Edge Services 계약이 없는 경우, 해야 link:prepare.html["Upgrade Advisor 없이 업그레이드를 준비합니다"]합니다.

.단계
. https://aiq.netapp.com/["Active IQ Digital Advisor를 시작합니다"^]
. 디지털 자문link:https://docs.netapp.com/us-en/active-iq/task_view_risk_and_take_action.html["클러스터와 관련된 모든 위험을 확인하고 수동으로 수정 조치를 취할 수 있습니다"^].
+
ONTAP 업그레이드를 수행하기 전에 * 소프트웨어 구성 변경 *, * 하드웨어 구성 변경 * 및 * 하드웨어 교체 * 범주에 포함된 위험을 해결해야 합니다.

. 권장 업그레이드 경로 및 를 검토합니다 link:https://docs.netapp.com/us-en/active-iq/upgrade_advisor_overview.html["업그레이드 계획을 생성합니다"^].


.다음 단계
* 를 검토해야 합니다 link:../release-notes/index.html["ONTAP 릴리즈 노트"] Upgrade Advisor가 클러스터에 권장하는 타겟 ONTAP 릴리즈의 경우 Upgrade Advisor에서 생성한 계획에 따라 클러스터를 업그레이드해야 합니다.
* 당신은 해야 한다 link:reboot-sp-bmc.html["SP 또는 BMC를 재부팅합니다"] 업그레이드 시작 전.


.관련 정보
* https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/How_to_manually_upload_AutoSupport_messages_to_NetApp_in_ONTAP_9["AutoSupport 메시지를 NetApp에 수동으로 업로드하는 방법"^]

