---
permalink: upgrade/download-software-image.html 
sidebar: sidebar 
keywords: ontap, software, image, download, downloading, upgrade 
summary: ONTAP를 업그레이드하기 전에 먼저 NetApp Support 사이트에서 ONTAP 소프트웨어를 다운로드해야 합니다. 
---
= ONTAP 소프트웨어 이미지 다운로드
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP를 업그레이드하기 전에 먼저 NetApp Support 사이트에서 대상 ONTAP 소프트웨어 이미지를 다운로드해야 합니다. ONTAP 릴리스에 따라 ONTAP 소프트웨어를 네트워크의 HTTPS, HTTP 또는 FTP 서버 또는 로컬 폴더에 다운로드할 수 있습니다.

[cols="2"]
|===
| 실행 중인 경우... | 이 위치로 이미지를 다운로드할 수 있습니다... 


| ONTAP 9.6 이상  a| 
* HTTPS 서버 + 서버의 CA 인증서가 로컬 시스템에 설치되어 있어야 합니다.
* 로컬 폴더입니다
* HTTP 또는 FTP 서버




| ONTAP 9.4 이상  a| 
* 로컬 폴더입니다
* HTTP 또는 FTP 서버




| ONTAP 9.0 이상 | HTTP 또는 FTP 서버 
|===
.이 작업에 대해
* 를 사용하여 무중단 자동 업그레이드를 수행하는 경우 link:concept_upgrade_paths.html#types-of-upgrade-paths["직접 멀티 홉 업그레이드 경로"], 업그레이드에 필요한 중간 ONTAP 버전과 대상 ONTAP 버전에 대한 소프트웨어 패키지를 다운로드해야 합니다.  예를 들어, ONTAP 9.8에서 ONTAP 9.13.1로 업그레이드하는 경우 ONTAP 9.12.1용 소프트웨어 패키지와 ONTAP 9.13.1용 소프트웨어 패키지를 다운로드해야 합니다.  을 참조하십시오 link:concept_upgrade_paths.html#supported-upgrade-paths-for-on-premises-ontap-and-ontap-select["지원되는 업그레이드 경로"] 특정 업그레이드에 중간 소프트웨어 패키지를 다운로드해야 하는지 확인하려면
* NetApp 볼륨 암호화가 있는 시스템을 ONTAP 9.5 이상으로 업그레이드할 경우 NetApp 볼륨 암호화를 포함하는 비제한 국가의 ONTAP 소프트웨어 이미지를 다운로드해야 합니다.
+
제한된 국가에서 ONTAP 소프트웨어 이미지를 사용하여 NetApp 볼륨 암호화를 사용하는 시스템을 업그레이드하면 시스템 패닉이 발생하고 볼륨에 대한 액세스가 손실됩니다.

* 펌웨어에 대해 별도의 소프트웨어 패키지를 다운로드할 필요가 없습니다. 클러스터에 대한 펌웨어 업데이트는 ONTAP 소프트웨어 업그레이드 패키지에 포함되어 있으며 각 노드의 부팅 장치에 복사됩니다. 그런 다음 새 펌웨어가 업그레이드 프로세스의 일부로 설치됩니다.


.단계
. 에서 대상 ONTAP 소프트웨어를 찾습니다 link:https://mysupport.netapp.com/site/products/all/details/ontap9/downloads-tab["소프트웨어 다운로드"] NetApp Support 사이트의 영역입니다.
+
ONTAP Select 업그레이드의 경우 * ONTAP Select 노드 업그레이드 * 를 선택합니다.

. 소프트웨어 이미지(예: 97_q_image.tgz)를 적절한 위치에 복사합니다.
+
ONTAP 릴리스에 따라 이미지는 로컬 시스템 또는 스토리지 시스템의 로컬 폴더에 서비스될 HTTP, HTTPS 또는 FTP 서버 디렉토리입니다.


