---
permalink: upgrade/index.html 
sidebar: sidebar 
keywords: upgrade overview, upgrade, digital advisor, summary, upgrade ontap, upgrading ontap, upgrade, upgrading, ontap, software, on-premise, prepare, preparation, major upgrade, minor upgrade, patch upgrade, upgrade assistance, upgrade help, upgrade technical support 
summary: ONTAP 업그레이드를 통해 새롭고 향상된 기능을 활용할 수 있습니다. 시작하기 전에 권장 단계에 따라 업그레이드를 준비합니다. 
---
= ONTAP 업그레이드 개요
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 소프트웨어를 업그레이드할 때 새롭고 개선된 ONTAP 기능을 활용하여 비용 절감, 중요한 워크로드 가속화, 보안 향상, 조직에 제공되는 데이터 보호 범위 확장에 도움이 됩니다.

주요 ONTAP 업그레이드는 ONTAP 번호가 낮은 릴리즈에서 상위 릴리즈로 이전하는 작업으로 구성됩니다. 예를 들어 ONTAP 9.8에서 ONTAP 9.12.1로 클러스터를 업그레이드할 수 있습니다.  부(또는 패치) 업그레이드는 동일한 번호가 지정된 릴리스 내에서 낮은 ONTAP 버전에서 상위 ONTAP 버전으로 이동하는 것으로 구성됩니다. 예를 들어, ONTAP 9.12.1P1에서 9.12.1P4로 클러스터를 업그레이드할 수 있습니다.

시작하려면 업그레이드를 준비해야 합니다. Active IQ Digital Advisor(디지털 어드바이저)에 대해 유효한 SupportEdge 계약을 보유한 경우 해야 link:create-upgrade-plan.html["Upgrade Advisor로 업그레이드 준비"]합니다. Upgrade Advisor는 클러스터를 평가하고 구성에 맞는 업그레이드 계획을 생성하여 불확실성과 위험을 최소화하는 데 도움이 되는 인텔리전스를 제공합니다. Active IQ 디지털 어드바이저에 대해 유효한 SupportEdge 계약이 없는 경우, 해야 link:prepare.html["Upgrade Advisor 없이 업그레이드 준비"]합니다.

업그레이드를 준비하고 나면 을 사용하여 업그레이드를 수행하는 것이 좋습니다 link:task_upgrade_andu_sm.html["System Manager에서 자동 무중단 업그레이드(ANDU"].  ANDU는 ONTAP의 고가용성(HA) 페일오버 기술을 활용하여 업그레이드 중에 클러스터가 중단 없이 데이터를 지속적으로 제공할 수 있도록 보장합니다.


NOTE: ONTAP 9.12.1부터 시스템 관리자는 BlueXP와 완벽하게 통합됩니다. 시스템에 BlueXP가 구성된 경우 BlueXP 작업 환경을 통해 업그레이드할 수 있습니다.

ONTAP 소프트웨어 업그레이드에 도움이 필요한 경우 NetApp 프로페셔널 서비스는 을 제공합니다 link:https://www.netapp.com/pdf.html?item=/media/8144-sd-managed-upgrade-service.pdf["관리형 업그레이드 서비스"^]. 이 서비스를 사용하는 데 관심이 있는 경우 NetApp 세일즈 담당자 또는 에게 문의하십시오 link:https://www.netapp.com/forms/sales-contact/["NetApp의 영업 문의 양식 제출"^]. Managed Upgrade Service 및 기타 유형의 업그레이드 지원은 를 사용하는 고객에게 제공됩니다 link:https://www.netapp.com/pdf.html?item=/media/8845-supportedge-expert-service.pdf["SupportEdge Expert 서비스"^] 추가 비용 없음.
