---
permalink: upgrade/install-software-manual-upgrade.html 
sidebar: sidebar 
keywords: ontap, software, image, download, downloading, install, installing. manual, manually 
summary: 수동 업그레이드를 위해 ONTAP 소프트웨어 패키지를 다운로드한 후에는 업그레이드를 시작하기 전에 로컬로 설치해야 합니다 
---
= 수동 업그레이드를 위해 ONTAP 소프트웨어 패키지를 설치합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
수동 업그레이드를 위해 ONTAP 소프트웨어 패키지를 다운로드한 후에는 업그레이드를 시작하기 전에 로컬로 설치해야 합니다.

.단계
. "Set-Privilege advanced"라는 메시지가 나타나면 * y * 를 입력하여 권한 수준을 advanced로 설정합니다
+
고급 프롬프트('*>')가 나타납니다.

. 이미지를 설치합니다.
+
[cols="2"]
|===
| 다음과 같은 구성이 있는 경우... | 이 명령 사용... 


 a| 
** MetroCluster가 아닙니다
** 2노드 MetroCluster입니다

 a| 
[source, cli]
----
system node image update -node * -package _location_ -replace-package true -setdefault true -background true
----
_location_은 ONTAP 버전에 따라 웹 서버 또는 로컬 폴더일 수 있습니다. 자세한 내용은 '시스템 노드 이미지 업데이트' man 페이지를 참조하십시오.

이 명령은 모든 노드에 소프트웨어 이미지를 동시에 설치합니다. 각 노드에 이미지를 한 번에 하나씩 설치하려면 를 지정하지 마십시오 `-background` 매개 변수.



 a| 
** 4노드 MetroCluster입니다
** 8노드 MetroCluster 구성

 a| 
[source, cli]
----
system node image update -node * -package location -replace-package true -background true -setdefault false
----
두 클러스터 모두에서 이 명령을 실행해야 합니다.

이 명령은 확장 쿼리를 사용하여 각 노드에 대체 이미지로 설치된 대상 소프트웨어 이미지를 변경합니다.

|===
. 메시지가 나타나면 y를 입력하여 계속합니다.
. 각 노드에 소프트웨어 이미지가 설치되어 있는지 확인합니다.
+
[source, cli]
----
system node image show-update-progress -node *
----
+
이 명령은 소프트웨어 이미지 설치의 현재 상태를 표시합니다. 모든 노드에서 * 종료 * 의 * 실행 상태 * 와 * 성공 * 의 * 종료 상태 * 가 보고될 때까지 이 명령을 계속 실행해야 합니다.

+
시스템 노드 이미지 업데이트 명령이 실패하고 오류 또는 경고 메시지가 표시될 수 있습니다. 오류 또는 경고를 해결한 후에는 명령을 다시 실행할 수 있습니다.

+
이 예에서는 두 노드에 소프트웨어 이미지가 성공적으로 설치된 2노드 클러스터를 보여줍니다.

+
[listing]
----
cluster1::*> system node image show-update-progress -node *
There is no update/install in progress
Status of most recent operation:
        Run Status:     Exited
        Exit Status:    Success
        Phase:          Run Script
        Exit Message:   After a clean shutdown, image2 will be set as the default boot image on node0.
There is no update/install in progress
Status of most recent operation:
        Run Status:     Exited
        Exit Status:    Success
        Phase:          Run Script
        Exit Message:   After a clean shutdown, image2 will be set as the default boot image on node1.
2 entries were acted on.
----

