---
sidebar: sidebar 
permalink: upgrade/task_upgrade_disruptive_automated_cli.html 
keywords: netapp, ontap, upgrade, nondisruptive, nondisruptively, non-disruptive update, nondisruptive upgrade, upgrade a cluster, shift workload between clusters, hardware platform, configuration, software image, update, update ONTAP, update software, ndu 
summary: ONTAP 9.2부터는 ONTAP CLI를 사용하여 단일 노드 클러스터에 대한 자동 업데이트를 수행할 수 있습니다. 단일 노드 클러스터에는 이중화가 없으므로 업그레이드 시 중단이 발생합니다. 
---
= 자동화된 중단 ONTAP 업그레이드(단일 노드 클러스터만 해당)
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ONTAP 9.2부터는 ONTAP CLI를 사용하여 단일 노드 클러스터에 대한 자동 업데이트를 수행할 수 있습니다. 단일 노드 클러스터에는 중복성이 없으므로 업데이트가 항상 중단될 수 있습니다. System Manager를 사용하여 운영 중단 업그레이드를 수행할 수 없습니다.

* 업그레이드를 만족해야 합니다 link:prepare.html["준비"] 요구사항.


.단계
. 이전 ONTAP 소프트웨어 패키지를 삭제합니다.
+
[source, cli]
----
cluster image package delete -version previous_package_version
----
. 대상 ONTAP 소프트웨어 패키지를 다운로드합니다.
+
[source, cli]
----
cluster image package get -url location
----
+
[listing]
----
cluster1::> cluster image package get -url http://www.example.com/software/9.7/image.tgz

Package download completed.
Package processing completed.
----
. 소프트웨어 패키지를 클러스터 패키지 리포지토리에서 사용할 수 있는지 확인합니다.
+
[source, cli]
----
cluster image package show-repository
----
+
[listing]
----
cluster1::> cluster image package show-repository
Package Version  Package Build Time
---------------- ------------------
9.7              M/DD/YYYY 10:32:15
----
. 클러스터를 업그레이드할 준비가 되었는지 확인합니다.
+
[source, cli]
----
cluster image validate -version package_version_number
----
+
[listing]
----
cluster1::> cluster image validate -version 9.7

WARNING: There are additional manual upgrade validation checks that must be performed after these automated validation checks have completed...
----
. 검증 진행 상황 모니터링:
+
[source, cli]
----
cluster image show-update-progress
----
. 검증에서 식별된 모든 필수 조치를 완료하십시오.
. 필요한 경우 소프트웨어 업그레이드 예상치를 생성합니다.
+
[source, cli]
----
cluster image update -version package_version_number -estimate-only
----
+
소프트웨어 업그레이드 추정치는 업데이트할 각 구성 요소에 대한 세부 정보와 예상 업그레이드 기간을 표시합니다.

. 소프트웨어 업그레이드 수행:
+
[source, cli]
----
cluster image update -version package_version_number
----
+

NOTE: 문제가 발생하면 업데이트가 일시 중지되고 수정 조치를 취하라는 메시지가 표시됩니다. 클러스터 image show-update-progress 명령을 사용하여 문제 및 업데이트 진행 상황에 대한 세부 정보를 볼 수 있습니다. 문제를 해결한 후 cluster image resume-update 명령을 사용하여 업데이트를 다시 시작할 수 있습니다.

. 클러스터 업데이트 진행률을 표시합니다.
+
[source, cli]
----
cluster image show-update-progress
----
+
노드가 업데이트의 일부로 재부팅되며 재부팅 중에 액세스할 수 없습니다.

. 알림 트리거:
+
[source, cli]
----
autosupport invoke -node * -type all -message "Finishing_Upgrade"
----
+
클러스터가 메시지를 전송하도록 구성되지 않은 경우 알림 복사본이 로컬에 저장됩니다.


