---
permalink: upgrade/task_preparing_snapmirror_relationships_for_a_nondisruptive_upgrade_or_downgrade.html 
sidebar: sidebar 
keywords: ontap, upgrade, snapmirror, operations, quisce 
summary: ONTAP를 업그레이드하기 전에 SnapMirror 작업을 중지해야 하며 피어링된 각 SVM에는 클러스터 전체에서 고유한 이름이 있어야 합니다 
---
= ONTAP 업그레이드를 위한 SnapMirror 관계 준비
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapMirror를 실행하는 클러스터에서 ONTAP를 업그레이드하기 전에 대상 볼륨이 포함된 각 노드에 대해 SnapMirror 작업을 중지해야 하며 피어링된 각 SVM은 클러스터 전체에서 고유한 이름을 가져야 합니다. SVM별로 고유한 FQDN(정규화된 도메인 이름)을 사용하는 것이 좋습니다. 예를 들어 "'dataVerser.HQ" 또는 "'mirorSVM.오프사이트"" 등이 있습니다.

또한 DP SnapMirror 관계가 있는 클러스터를 업그레이드하는 경우 소스 노드를 업그레이드하기 전에 대상 노드를 업그레이드해야 합니다.



== ONTAP를 업그레이드하기 전에 SnapMirror 작업을 중단합니다

SnapMirror 전송 오류가 발생하지 않도록 하려면 ONTAP를 업그레이드하기 전에 SnapMirror 작업을 중지해야 합니다. 또는 특정 타겟 볼륨에서 SnapMirror 전송을 중지하고 소스 노드를 업그레이드하기 전에 소유 대상 노드를 업그레이드하여 다른 모든 대상 볼륨에 대한 SnapMirror 전송을 계속할 수 있습니다. 다음 표에서는 SnapMirror 작업을 일시 중단하는 두 가지 옵션을 설명합니다.

[cols="3*"]
|===
| 옵션을 선택합니다 | 설명 | 소스 노드 전에 대상 노드를 업그레이드하시겠습니까? 


 a| 
NDU(무중단 업그레이드) 동안 SnapMirror 작업을 일시 중단합니다.
 a| 
SnapMirror 환경에서 가장 간단한 업그레이드 방법은 모든 SnapMirror 작업을 일시 중지하고 업그레이드를 수행한 다음 SnapMirror 작업을 다시 시작하는 것입니다. 하지만 전체 NDU 중에는 SnapMirror 전송이 수행되지 않습니다. 볼륨에 볼륨을 미러링하는 노드가 클러스터에 포함된 경우 이 방법을 사용해야 합니다.
 a| 
아니요. 노드를 어떤 순서로든 업그레이드할 수 있습니다.



 a| 
한 번에 하나의 대상 볼륨에 SnapMirror 작업을 일시 중단합니다.
 a| 
특정 대상 볼륨에 대한 SnapMirror 전송을 일시 중지하고, 대상 볼륨이 포함된 노드(또는 HA 쌍)를 업그레이드하고, 소스 볼륨이 포함된 노드(또는 HA 쌍)를 업그레이드한 다음, 대상 볼륨에 대한 SnapMirror 전송을 다시 시작할 수 있습니다. 이 방법을 사용하면 원본 대상 및 소스 볼륨이 포함된 노드가 업그레이드되는 동안 다른 모든 대상 볼륨에 대한 SnapMirror 전송이 계속됩니다.
 a| 
예.

|===
.단계
. 각 SnapMirror 관계의 타겟 경로를 결정합니다.
+
[source, cli]
----
snapmirror show
----
. 각 타겟 볼륨에 대해 향후 SnapMirror 전송을 일시 중단합니다.
+
[source, cli]
----
snapmirror quiesce -destination-path destination
----
+
SnapMirror 관계에 대한 활성 전송이 없는 경우 이 명령은 상태를 "중지됨"으로 설정합니다. 관계에 활성 전송이 있는 경우 전송이 완료될 때까지 상태가 "정지 중"으로 설정되고 상태가 "중지"로 됩니다.

+
이 예에서는 "SVMvs0.example.com": 에서 대상 볼륨 "vol1"과 관련된 전송을 중지시킵니다

+
[listing]
----
cluster1::> snapmirror quiesce -destination-path vs0.example.com:vol1
----
. 모든 SnapMirror 관계가 중지되었는지 확인:
+
[source, cli]
----
snapmirror show -status !Quiesced
----
+
이 명령은 _not_quiesced 인 SnapMirror 관계를 표시합니다.

+
이 예에서는 모든 SnapMirror 관계가 정지된 상태를 보여줍니다.

+
[listing]
----
cluster1::> snapmirror show -status !Quiesced
There are no entries matching your query.
----
. 현재 SnapMirror 관계가 전송 중인 경우 다음 옵션 중 하나를 수행합니다.
+
[cols="2*"]
|===
| 옵션을 선택합니다 | 설명 


 a| 
ONTAP 업그레이드를 수행하기 전에 전송이 완료될 때까지 기다립니다.
 a| 
전송이 완료될 때마다 관계는 "정지됨" 상태로 변경됩니다.



 a| 
전송 중지:

`snapmirror abort -destination-path destination -h`

* 참고: * 을 사용해야 합니다 `-foreground true` 로드 공유 미러 전송을 종료하는 경우 매개 변수입니다.
 a| 
이 명령은 SnapMirror 전송을 중지하고 대상 볼륨을 성공적으로 전송된 마지막 스냅샷 복사본으로 복원합니다. 관계가 "정지됨" 상태로 설정됩니다.

|===

