---
permalink: upgrade/task_enabling_and_reverting_lifs_to_home_ports_preparing_the_ontap_software_for_the_update.html 
sidebar: sidebar 
keywords: ontap, upgrade, enabling, enable, revert, reverting, lifs, home, ports, 
summary: 재부팅 중 일부 LIF는 할당된 페일오버 포트로 마이그레이션되었을 수 있습니다. 클러스터를 업그레이드하기 전과 업그레이드한 후에는 홈 포트에 없는 LIF를 사용하고 되돌려야 합니다. 
---
= 업그레이드하기 전에 모든 LIFS가 홈 포트에 있는지 확인합니다
:icons: font
:imagesdir: ../media/


[role="lead"]
재부팅 중 일부 LIF는 할당된 페일오버 포트로 마이그레이션되었을 수 있습니다. 클러스터를 업그레이드하기 전과 업그레이드한 후에는 홈 포트에 없는 LIF를 사용하고 되돌려야 합니다.

네트워크 인터페이스 되돌리기 명령은 홈 포트가 작동하고 있을 경우 홈 포트에 없는 LIF를 홈 포트로 되돌립니다. LIF의 홈 포트는 LIF가 생성될 때 지정됩니다. 네트워크 인터페이스 show 명령을 사용하여 LIF의 홈 포트를 확인할 수 있습니다.

. 모든 LIF의 상태를 'network interface show'로 표시합니다
+
이 예는 SVM(스토리지 가상 머신)에 대한 모든 LIF의 상태를 표시합니다.

+
[listing]
----
cluster1::> network interface show -vserver vs0
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
vs0
            data001    down/down  192.0.2.120/24     node0         e0e     true
            data002    down/down  192.0.2.121/24     node0         e0f     true
            data003    down/down  192.0.2.122/24     node0         e2a     true
            data004    down/down  192.0.2.123/24     node0         e2b     true
            data005    down/down  192.0.2.124/24     node0         e0e     false
            data006    down/down  192.0.2.125/24     node0         e0f     false
            data007    down/down  192.0.2.126/24     node0         e2a     false
            data008    down/down  192.0.2.127/24     node0         e2b     false
8 entries were displayed.
----
+
Status Admin 상태가 DOWN 이거나 is home 상태가 false인 LIF가 나타나면 다음 단계를 계속 진행합니다.

. 데이터 LIF를 활성화합니다. 'network interface modify {-role data}-status-admin up'
+
[listing]
----
cluster1::> network interface modify {-role data} -status-admin up
8 entries were modified.
----
. LIF를 홈 포트인 '네트워크 인터페이스 되돌리기 *'로 되돌립니다
+
이 명령은 모든 LIF를 홈 포트로 되돌립니다.

+
[listing]
----
cluster1::> network interface revert *
8 entries were acted on.
----
. 모든 LIF가 홈 포트인 'network interface show'에 있는지 확인합니다
+
이 예에서는 SVM vs0용 모든 LIF가 홈 포트에 있음을 보여 줍니다.

+
[listing]
----
cluster1::> network interface show -vserver vs0
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
vs0
            data001      up/up    192.0.2.120/24     node0         e0e     true
            data002      up/up    192.0.2.121/24     node0         e0f     true
            data003      up/up    192.0.2.122/24     node0         e2a     true
            data004      up/up    192.0.2.123/24     node0         e2b     true
            data005      up/up    192.0.2.124/24     node1         e0e     true
            data006      up/up    192.0.2.125/24     node1         e0f     true
            data007      up/up    192.0.2.126/24     node1         e2a     true
            data008      up/up    192.0.2.127/24     node1         e2b     true
8 entries were displayed.
----

