---
permalink: upgrade/task_requesting_notification_of_issues_encountered_in_nondisruptive_upgrades.html 
sidebar: sidebar 
keywords: ontap, upgrade, requesting, notification, issues, encountered, ndu, andu, nondisruptive, upgrades 
summary: 업그레이드 프로세스의 진행 상황을 모니터링할 계획이 없는 경우 EMS에 수동 개입이 필요할 수 있는 오류 알림을 요청하는 것이 좋습니다. 또는 AutoSupport 메시지를 구성하여 내부 지원 조직에 보낼 수도 있습니다. 
---
= 무중단 업그레이드 중 발생한 문제에 대한 알림 요청
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
업그레이드 프로세스의 진행 상황을 모니터링할 계획이 없는 경우 EMS에 수동 개입이 필요할 수 있는 오류 알림을 요청하는 것이 좋습니다. 또는 AutoSupport 메시지를 구성하여 내부 지원 조직에 보낼 수도 있습니다.

이 작업을 수행하려면 클러스터 관리자여야 합니다.

업그레이드 프로세스 중에 문제가 발생할 경우 알림을 보내도록 설정하는 것이 좋습니다. 특히 callhome.andu.pausederr 메시지에는 유용한 문제 해결 정보가 포함되어 있습니다.

AutoSupport noteto 매개 변수가 이메일 주소로 구성된 경우, ONTAP 9 또는 9.1로 업그레이드할 때 EMS 알림 대상으로 자동 복사됩니다. 중요 이벤트 필터를 이러한 주소에 매핑하는 새 EMS 알림도 생성됩니다. 따라서 AutoSupport noteto 매개 변수에서 전자 메일 주소를 제거할 때까지 각 callhome 이벤트에 대해 두 개의 전자 메일 알림을 받기 시작합니다. 또한 원래 구성된 다른 중요한 이벤트에 대한 이메일 알림도 받게 됩니다.


NOTE: 클러스터가 AutoSupport 메시지를 전송하도록 구성되지 않은 경우 알림 복사본이 로컬에 저장됩니다.

. 무중단 업그레이드 중 발생한 문제에 대한 요청 알림
+
link:../error-messages/index.html["EMS 구성"]

. 무중단 업그레이드를 시작하기 전에 이 클러스터에서 AutoSupport가 활성화되어 있으면 AutoSupport 메시지를 호출하여 자동 케이스 생성을 억제합니다. 이 클러스터에서 AutoSupport가 활성화되어 있지 않으면 'system node AutoSupport invoke -node * -type all-message maINT=xh'를 무시하십시오
+
x 는 유지 보수 기간(시간)입니다.

+

NOTE: 이 메시지는 유지보수 작업 중에 자동 케이스 생성이 억제되도록 이 유지보수 작업의 기술 지원 부서에 알립니다.

+
이 명령을 실행하면 2시간 동안 자동 케이스가 생성되지 않습니다.

+
[listing]
----
cluster::*> system node autosupport invoke -node * -type all -message MAINT=2h
----
. 무중단 업그레이드 후 'system node AutoSupport invoke -node * -type all-message maINT=end' AutoSupport 메시지를 호출하여 자동 케이스 생성을 다시 활성화합니다
+
명령을 실행하면 자동 케이스 생성이 다시 설정됩니다.

+
[listing]
----
cluster::*> system node autosupport invoke -node * -type all -message MAINT=END
----


http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-cmpr/GUID-5CB10C70-AC11-41C0-8C16-B4D0DF916E9B.html["ONTAP 9 명령"]

link:../error-messages/index.html["EMS 구성"]
