---
permalink: upgrade/task_verify_status.html 
sidebar: sidebar 
keywords: ontap, upgrade, upgrade, verify, status, ha, ldap, dns, networking, storage, metrocluster 
summary: 다양한 구성 설정이 클러스터 업그레이드 준비에 영향을 미칠 수 있습니다. 
---
= 상태를 확인합니다
:icons: font
:imagesdir: ../media/


[role="lead"]
업그레이드하기 전에 다음을 확인해야 합니다.

* HA 쌍 상태
* LDAP 상태(ONTAP 9.2 이상)
* DNS 서버 상태(ONTAP 9.2 이상),
* 네트워킹 및 스토리지 상태(MetroCluster 구성의 경우)




== HA 상태를 확인하는 중입니다

무중단 업그레이드를 수행하기 전에 각 HA 쌍에 대해 스토리지 페일오버가 활성화되어 있는지 확인해야 합니다. 클러스터가 2노드로만 구성된 경우 클러스터 HA가 활성화되었는지 확인해야 합니다.

시스템 중단을 야기하려는 업그레이드를 수행할 경우 스토리지 페일오버가 필요하지 않으므로 HA 상태를 확인할 필요가 없습니다.

. 각 HA 쌍에 대해 스토리지 페일오버가 설정되어 있고 가능한지 확인합니다. 'Storage failover show'
+
이 예에서는 Node0 및 node1에서 스토리지 페일오버가 설정 및 가능함을 보여 줍니다.

+
[listing]
----
cluster1::> storage failover show
                              Takeover
Node           Partner        Possible State
-------------- -------------- -------- -------------------------------------
node0          node1          true     Connected to node1
node1          node0          true     Connected to node0
2 entries were displayed.
----
+
필요한 경우 스토리지 페일오버 수정 명령을 사용하여 스토리지 페일오버를 설정할 수 있습니다.

. 클러스터가 2개 노드(단일 HA 쌍)로만 구성된 경우 클러스터 HA가 "cluster ha show" 로 구성되었는지 확인합니다
+
이 예에서는 클러스터 HA가 구성되어 있음을 보여 줍니다.

+
[listing]
----
cluster1::> cluster ha show
High Availability Configured: true
----
+
필요한 경우 cluster ha modify 명령을 사용하여 클러스터 HA를 사용하도록 설정할 수 있습니다.





== LDAP 상태 확인(ONTAP 9.2 이상)

ONTAP 9.2부터 스토리지 가상 시스템(SVM)에서 LDAP를 사용하는 경우 무중단 업그레이드를 수행하려면 LDAP 연결을 설정해야 합니다. 업그레이드를 시작하기 전에 LDAP 연결을 확인해야 합니다.

ONTAP 9.1 이하 버전에서 업그레이드하는 경우에는 작업이 적용되지 않습니다.

. LDAP 상태 'ldap check-vserver vserver_name'을 확인하십시오
. LDAP 상태가 DOWN인 경우 'LDAP client modify -client -config ldap_client -ldap -servers ip_address'를 수정합니다
. LDAP 상태가 'LDAP CHECK - vserver vserver_name'인지 확인합니다




== DNS 서버 상태 확인(ONTAP 9.2 이상)

ONTAP 9.2 이상부터는 무중단 업그레이드를 수행하기 전과 후에 DNS(도메인 이름 서비스) 서버의 상태를 확인해야 합니다.

ONTAP 9.1 이하 버전에서 업그레이드하는 경우에는 작업이 적용되지 않습니다.

. DNS 서버의 상태를 확인합니다. dns check-vserver vserver_name'
+
가동 상태는 서비스가 실행 중임을 나타냅니다. 다운 상태는 서비스가 실행되고 있지 않음을 나타냅니다.

. DNS 서버가 다운된 경우 다음과 같이 수정합니다. dns modify -vserver vserver_name -domain domain domain_name -servers name_server_ipaddress
. DNS 서버의 상태가 가동 상태인지 확인합니다.




== MetroCluster 구성에 대한 네트워킹 및 스토리지 상태 확인

MetroCluster 구성에서 업데이트를 수행하기 전과 후에 각 클러스터의 LIF, 애그리게이트 및 볼륨 상태를 확인해야 합니다.

. LIF 상태를 'network interface show'로 확인한다
+
정상 운영 시 소스 SVM에 대한 LIF의 관리 상태가 가동이고 홈 노드에 있어야 합니다. 타겟 SVM을 위한 LIF는 홈 노드에 배치하거나 설치할 필요가 없습니다. 스위치오버에서 모든 LIF는 관리 상태가 Up 이지만 홈 노드에 있을 필요가 없습니다.

+
[listing]
----
cluster1::> network interface show
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            cluster1-a1_clus1
                         up/up    192.0.2.1/24       cluster1-01
                                                                   e2a     true
            cluster1-a1_clus2
                         up/up    192.0.2.2/24       cluster1-01
                                                                   e2b     true


cluster1-01
            clus_mgmt    up/up    198.51.100.1/24    cluster1-01
                                                                   e3a     true
            cluster1-a1_inet4_intercluster1
                         up/up    198.51.100.2/24    cluster1-01
                                                                   e3c     true
            ...

27 entries were displayed.
----
. 'Storage aggregate show-state! online'이라는 집계 상태를 확인합니다
+
이 명령은 _not_online 상태인 모든 애그리게이트를 표시합니다. 정상 운영 시 로컬 사이트에 있는 모든 애그리게이트는 온라인 상태여야 합니다. 하지만 MetroCluster 구성이 전환 중인 경우 재해 복구 사이트의 루트 애그리게이트를 오프라인 상태로 전환할 수 있습니다.

+
이 예는 정상 작동 중인 클러스터를 보여줍니다.

+
[listing]
----
cluster1::> storage aggregate show -state !online
There are no entries matching your query.
----
+
이 예에서는 재해 복구 사이트의 루트 애그리게이트가 오프라인 상태인 전환 클러스터를 보여 줍니다.

+
[listing]
----
cluster1::> storage aggregate show -state !online
Aggregate     Size Available Used% State   #Vols  Nodes            RAID Status
--------- -------- --------- ----- ------- ------ ---------------- ------------
aggr0_b1
                0B        0B    0% offline      0 cluster2-01      raid_dp,
                                                                   mirror
                                                                   degraded
aggr0_b2
                0B        0B    0% offline      0 cluster2-02      raid_dp,
                                                                   mirror
                                                                   degraded
2 entries were displayed.
----
. 볼륨 상태 확인: 볼륨 표시 상태! 온라인
+
이 명령은 _not_online 상태인 모든 볼륨을 표시합니다.

+
MetroCluster 구성이 정상 작동 중인 경우(스위치오버 상태가 아님), 클러스터에 있는 보조 SVM이 소유한 모든 볼륨(SVM 이름이 "-mc"로 추가된 볼륨)이 출력에 표시되어야 합니다.

+
전환 시에만 볼륨은 온라인 상태가 됩니다.

+
이 예에서는 재해 복구 사이트의 볼륨이 온라인 상태가 아닌 정상적인 상태의 클러스터를 보여 줍니다.

+
[listing]
----
cluster1::> volume show -state !online
  (volume show)
Vserver   Volume       Aggregate    State      Type       Size  Available Used%
--------- ------------ ------------ ---------- ---- ---------- ---------- -----
vs2-mc    vol1         aggr1_b1     -          RW            -          -     -
vs2-mc    root_vs2     aggr0_b1     -          RW            -          -     -
vs2-mc    vol2         aggr1_b1     -          RW            -          -     -
vs2-mc    vol3         aggr1_b1     -          RW            -          -     -
vs2-mc    vol4         aggr1_b1     -          RW            -          -     -
5 entries were displayed.
----
. '볼륨 표시 - 불일치 true'라는 일관성 없는 볼륨이 없는지 확인합니다
+
일관되지 않은 볼륨이 반환되는 경우 업그레이드를 시작하기 전에 NetApp Support에 문의해야 합니다.


