---
sidebar: sidebar 
permalink: upgrade/task_upgrade_andu_cli.html 
keywords: netapp, ontap, automate, automatic, automated, upgrade, nondisruptive, nondisruptively, non-disruptive update, nondisruptive upgrade, upgrade a cluster, shift workload between clusters, hardware platform, configuration, software image, update, update ONTAP, update software, ndu 
summary: 클러스터에서 ONTAP 버전을 중단 없이 업데이트할 수 있습니다. 
---
= CLI를 통한 무중단 업그레이드 자동화
:toc: macro
:hardbreaks:
:toclevels: 1
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
CLI(Command Line Interface)를 사용하여 클러스터를 중단 없이 업그레이드할 수 있는지 확인하고, 각 노드에 타겟 ONTAP 이미지를 설치한 다음 백그라운드에서 업그레이드를 실행할 수 있습니다.

업그레이드 프로세스의 진행 상황을 모니터링할 계획이 없는 경우 을 사용하는 것이 좋습니다 link:task_requesting_notification_of_issues_encountered_in_nondisruptive_upgrades.html["수동 개입이 필요할 수 있는 오류에 대한 EMS 알림을 요청합니다"].

.시작하기 전에
* Active IQ 디지털 어드바이저를 실행해야 합니다.
+
Active I의 Upgrade Advisor 구성 요소 Digital Advisor는 성공적인 업그레이드를 계획하는 데 도움이 됩니다.

+
SupportEdge Digital Advisor의 데이터 중심 인사이트와 권장사항은 활성 * Active IQ * 계약을 체결한 모든 NetApp 고객에게 제공됩니다(기능은 제품 및 지원 티어에 따라 다름).

* 업그레이드 준비 요구 사항을 충족해야 합니다.
* 각 HA 쌍에 대해 각 노드에는 동일한 브로드캐스트 도메인에 하나 이상의 포트가 있어야 합니다.
+
일괄 업그레이드 중에 노드 세트가 업그레이드되면 LIF가 HA 파트너 노드로 마이그레이션됩니다. 파트너가 동일한 브로드캐스트 도메인에 포트가 없는 경우 LIF 마이그레이션이 실패합니다.

* ONTAP 9.3에서 9.7로 업그레이드하는 경우 9.5 및 9.7용 소프트웨어 이미지를 획득해야 합니다.
* ONTAP 9.5에서 9.9.1로 업그레이드하는 경우 9.7 및 9.9.1용 소프트웨어 이미지를 획득해야 합니다.


클러스터 이미지 검증 명령은 클러스터 구성 요소를 점검하여 업그레이드를 중단 없이 완료할 수 있는지 확인한 다음, 소프트웨어 업그레이드를 수행하기 전에 수행해야 하는 각 검사 및 필수 작업의 상태를 제공합니다.


NOTE: 자동 무중단 업그레이드(ANDU)를 시작하기 전에 스토리지 페일오버 modify -auto-반환 명령 옵션의 설정을 수정해도 업그레이드 프로세스는 영향을 받지 않습니다. ANDU 프로세스는 업데이트에 필요한 Takeover/Giveback 중 이 옵션의 사전 설정 값을 무시합니다. 예를 들어, -aut자동 백업을 시작하기 전에 -automiveback을 false로 설정하면 반환 전에 자동 업그레이드가 중단되지 않습니다.

. 이전 ONTAP 소프트웨어 패키지인 'cluster image package delete - version previous_ontap_Version'을 삭제합니다
. 대상 ONTAP 소프트웨어 패키지 '클러스터 이미지 패키지 Get-URL 위치'를 다운로드합니다
+

NOTE: ONTAP 9.3에서 9.7로 업그레이드하는 경우 ONTAP 9.5용 소프트웨어 패키지를 다운로드한 다음 동일한 명령을 사용하여 9.7용 소프트웨어 패키지를 다운로드합니다. ONTAP 9.5에서 9.9.1로 업그레이드하는 경우 ONTAP 9.7용 소프트웨어 패키지를 다운로드한 다음 동일한 명령을 사용하여 9.9.1용 소프트웨어 패키지를 다운로드합니다.

+
[listing]
----
cluster1::> cluster image package get -url http://www.example.com/software/9.7/image.tgz

Package download completed.
Package processing completed.
----
. 소프트웨어 패키지가 클러스터 패키지 리포지토리인 클러스터 이미지 패키지 show-repository에서 사용 가능한지 확인합니다
+
[listing]
----
cluster1::> cluster image package show-repository
Package Version  Package Build Time
---------------- ------------------
9.7              MM/DD/YYYY 10:32:15
----
. 클러스터가 중단 없이 업그레이드될 준비가 되었는지 확인합니다. 'cluster image validate-version package_version_number'
+
** 2노드 또는 4노드 MetroCluster 구성을 업그레이드할 경우 계속하기 전에 두 클러스터 모두에서 이 명령을 실행해야 합니다.
** ONTAP 9.3에서 9.7로 업그레이드하는 경우 9.7 패키지를 사용하여 확인하십시오. 9.5 패키지를 별도로 검증할 필요는 없습니다.
** ONTAP 9.5에서 9.9.1로 업그레이드하는 경우 확인을 위해 9.9.1 패키지를 사용합니다. 9.7 패키지를 개별적으로 확인할 필요는 없습니다.


+
[listing]
----
cluster1::> cluster image validate -version 9.7

WARNING: There are additional manual upgrade validation checks that must be performed after these automated validation checks have completed...
----
. 검증의 진행 상황 모니터링: 클러스터 이미지 보기 - 업데이트 진행 상황
. 검증에서 식별된 모든 필수 조치를 완료하십시오.
. 'cluster image update-version package_version_number-estimate-only' 소프트웨어 업그레이드 견적을 생성합니다
+
소프트웨어 업그레이드 추정치는 업데이트할 각 구성 요소에 대한 세부 정보와 예상 업그레이드 기간을 표시합니다.

. 'cluster image update-version package_version_number' 소프트웨어 업그레이드를 수행한다
+
** ONTAP 9.3에서 9.7로 업그레이드하는 경우 위의 명령에서 9.7 package_version_number를 사용하십시오.
** ONTAP 9.5에서 9.9.1로 업그레이드하는 경우 위의 명령에서 9.9.1 package_version_number를 사용하십시오.
** 2노드 MetroCluster 시스템을 제외한 모든 MetroCluster 구성의 경우, 사용자가 명령줄을 시작하고 확인하면 ONTAP 업그레이드 프로세스가 두 사이트(로컬 사이트 및 재해 복구 사이트)의 HA 쌍에서 동시에 시작됩니다. 2노드 MetroCluster 시스템의 경우 먼저 재해 복구 사이트, 즉 업그레이드가 시작되지 않은 사이트에서 업데이트가 시작됩니다. 재해 복구 사이트에서 업데이트가 완전히 완료되면 로컬 사이트에서 업그레이드가 시작됩니다.
** 클러스터가 2~6개 노드로 구성된 경우 롤링 업그레이드가 수행됩니다. 클러스터가 8개 이상의 노드로 구성된 경우 기본적으로 일괄 업그레이드가 수행됩니다. 필요한 경우 -force-rolling 매개 변수를 사용하여 대신 롤링 업그레이드를 지정할 수 있습니다.
** 각각의 테이크오버 및 반환을 완료한 후, 업데이트는 클라이언트 애플리케이션이 테이크오버 및 반환 중에 발생하는 I/O의 일시 중지에서 복구될 수 있도록 8분 동안 대기합니다. 클라이언트 안정화 시간이 필요한 환경의 경우 -안정화 시간(minutes) 매개 변수를 사용하여 다른 안정화 시간을 지정할 수 있습니다.
+
[listing]
----
cluster1::> cluster image update -version 9.7

Starting validation for this update. Please wait..

It can take several minutes to complete validation...

WARNING: There are additional manual upgrade validation checks...

Pre-update Check      Status     Error-Action
--------------------- ---------- --------------------------------------------
...
20 entries were displayed

Would you like to proceed with update ? {y|n}: y
Starting update...

cluster-1::>
----


. 클러스터 업데이트 진행률 표시: 클러스터 이미지 표시-업데이트-진행률
+

NOTE: 4노드 또는 8노드 MetroCluster 구성을 업그레이드할 경우 'cluster image show-update-progress' 명령은 명령을 실행하는 노드의 진행진만 표시합니다. 개별 노드의 진행률을 보려면 각 노드에서 명령을 실행해야 합니다.

. 각 노드에서 업그레이드가 성공적으로 완료되었는지 확인합니다.
+
[listing]
----
cluster1::> cluster image show-update-progress

                                             Estimated         Elapsed
Update Phase         Status                   Duration        Duration
-------------------- ----------------- --------------- ---------------
Pre-update checks    completed                00:10:00        00:02:07
Data ONTAP updates   completed                01:31:00        01:39:00
Post-update checks   completed                00:10:00        00:02:00
3 entries were displayed.

Updated nodes: node0, node1.

cluster1::>
----
. AutoSupport 알림 'AutoSupport invoke-node * -type all-message 'finishing_NDU''를 트리거합니다
+
클러스터가 AutoSupport 메시지를 전송하도록 구성되지 않은 경우 알림 복사본이 로컬에 저장됩니다





== 자동 업그레이드 프로세스에서 오류가 발생한 후 CLI를 사용하여 업그레이드를 다시 시작합니다

[role="lead"]
오류로 인해 자동 업그레이드가 일시 중지되는 경우 오류를 해결하고 자동 업그레이드를 다시 시작하거나 자동 업그레이드를 취소하고 프로세스를 수동으로 완료할 수 있습니다. 자동 업그레이드를 계속하도록 선택한 경우 업그레이드 단계를 수동으로 수행하지 마십시오.

수동으로 업그레이드를 완료하려면 cluster image cancel-update 명령을 사용하여 자동화된 프로세스를 취소하고 수동으로 계속 진행합니다. 자동 업그레이드를 계속하려면 다음 단계를 완료하십시오.

. 'cluster image show-update-progress' 업그레이드 오류를 봅니다
. 오류를 해결합니다.
. 클러스터 이미지 다시 시작-업데이트 업데이트를 다시 시작합니다


https://aiq.netapp.com/["Active IQ를 시작합니다"]

https://docs.netapp.com/us-en/active-iq/["Active IQ 설명서"]
