---
permalink: upgrade/task_setting_the_desired_nt_acl_permissions_display_level_for_nfs_clients.html 
sidebar: sidebar 
keywords: ontap, upgrade, setting, set, desired, nt, acl, permissions, display, level, nfs, clients 
summary: ONTAP 8.3.0에서 업그레이드한 후 NFS 클라이언트에 대한 NT ACL 권한을 표시하는 기본 처리가 변경되었습니다. 설정을 확인하고 필요한 경우 해당 환경에 맞는 설정으로 변경해야 합니다. ONTAP 8.3.1 이상에서 업그레이드하는 경우에는 이 작업이 적용되지 않습니다. 
---
= NFS 클라이언트에 대해 원하는 NT ACL 권한 표시 수준을 설정합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 8.3.0에서 업그레이드한 후 NFS 클라이언트에 대한 NT ACL 권한을 표시하는 기본 처리가 변경되었습니다. 설정을 확인하고 필요한 경우 해당 환경에 맞는 설정으로 변경해야 합니다. ONTAP 8.3.1 이상에서 업그레이드하는 경우에는 이 작업이 적용되지 않습니다.

다중 프로토콜 환경에서 ONTAP는 NT ACL이 사용자에게 부여한 액세스를 기반으로 NTFS 보안 스타일 파일 및 디렉토리의 권한을 NFS 클라이언트에 표시합니다. ONTAP 8.3.0에서는 ONTAP가 NT ACL에서 부여한 최대 액세스 권한에 따라 기본적으로 NFS 클라이언트에 표시됩니다. 업그레이드 후 기본 설정은 NT ACL에서 부여한 최소 액세스 권한에 따라 사용 권한을 표시하도록 변경됩니다. 이러한 변경은 새로운 SVM(스토리지 가상 머신) 및 기존 SVM(스토리지 가상 머신)에 적용됩니다.

. 권한 수준을 Advanced:'Set-Privilege advanced'로 설정합니다
. NFS 클라이언트에 대한 NT ACL 권한 표시 설정을 확인합니다. 'vserver nfs show -vserver vserver_name -fields ntacl -display -permissive -perms'
+
8.3.0에서 업그레이드한 후에는 이 새 매개 변수의 값이 사용되지 않습니다. 즉, ONTAP에 최소 권한이 표시됩니다.

. 최대 권한을 표시하려면 각 SVM에 대해 'vserver nfs modify -vserver vserver_name -ntacl -display -permissive -perms enabled'라는 설정을 개별적으로 변경합니다
. 변경이 적용되었는지 확인합니다. 'vserver nfs show -vserver vserver_name -fields ntacl -display -permissive -perms'
. admin 권한 수준으로 복귀:'et-Privilege admin'입니다

