---
sidebar: sidebar 
permalink: upgrade/task_upgrade_andu_cli.html 
keywords: netapp, ontap, automate, automatic, automated, upgrade, nondisruptive, nondisruptively, non-disruptive update, nondisruptive upgrade, upgrade a cluster, shift workload between clusters, hardware platform, configuration, software image, update, update ONTAP, update software, ndu 
summary: 클러스터에서 ONTAP 버전을 중단 없이 업데이트할 수 있습니다. 
---
= CLI를 통한 무중단 ONTAP 업그레이드 자동화
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
자동화된 업그레이드를 위해 ONTAP는 각 노드에 타겟 ONTAP 이미지를 자동으로 설치하고 클러스터 구성 요소를 확인하여 클러스터를 중단 없이 업그레이드할 수 있는지 확인한 다음 를 실행합니다 xref:concept_upgrade_methods.html[일괄 또는 롤링 업그레이드] 노드 수를 기준으로 하는 배경입니다.

CLI(Command Line Interface)를 사용하여 클러스터를 중단 없이 업그레이드할 수 있는지 확인하고, 각 노드에 타겟 ONTAP 이미지를 설치한 다음 백그라운드에서 업그레이드를 실행할 수 있습니다.


NOTE: 업그레이드 프로세스의 진행 상황을 모니터링할 계획이 없는 경우 을 사용하는 것이 좋습니다 link:task_requesting_notification_of_issues_encountered_in_nondisruptive_upgrades.html["수동 개입이 필요할 수 있는 오류에 대한 EMS 알림을 요청합니다"].

.시작하기 전에
* 당신은 해야 한다 link:prepare.html["업그레이드를 준비합니다"].
* 당신은 해야 한다 link:download-software-image.html["ONTAP 소프트웨어 이미지 다운로드"] 대상 ONTAP 릴리스의 경우
* 각 HA 쌍에 대해 각 노드에는 동일한 브로드캐스트 도메인에 하나 이상의 포트가 있어야 합니다.
+
노드가 8개 이상인 경우 자동 무중단 업그레이드에 배치 업그레이드 방법이 사용됩니다. ONTAP 9.7 이하에서 배치 방법을 사용하면 LIF가 업그레이드 중인 노드의 HA 파트너로 마이그레이션됩니다. 파트너가 동일한 브로드캐스트 도메인에 포트가 없는 경우 LIF 마이그레이션이 실패합니다.

+
ONTAP 9.8 이상에서는 일괄 처리 방법을 사용하면 LIF가 다른 일괄 그룹으로 마이그레이션됩니다.

* 를 수행하는 경우 link:https://docs.netapp.com/us-en/ontap/upgrade/concept_upgrade_paths.html#types-of-upgrade-paths["직접 멀티 홉 업그레이드"]에 따라 필요한 올바른 ONTAP 이미지를 모두 획득해야 합니다 link:https://docs.netapp.com/us-en/ontap/upgrade/concept_upgrade_paths.html#supported-upgrade-paths["업그레이드 경로"].
* MetroCluster FC 구성에서 ONTAP를 업그레이드하려면 클러스터가 비계획 자동 전환을 위해 활성화되어야 합니다.



NOTE: 자동 무중단 업그레이드(ANDU)를 시작하기 전에 '스토리지 페일오버 수정-자동 반환' 명령 옵션의 설정을 수정해도 업그레이드 프로세스에 영향을 미치지 않습니다. ANDU 프로세스는 업데이트에 필요한 Takeover/Giveback 중 이 옵션의 사전 설정 값을 무시합니다. 예를 들어, ANDU를 시작하기 전에 '-automiveback'을 false로 설정하면 반환 전에 자동 업그레이드가 중단되지 않습니다.



== 1단계: 타겟 ONTAP 소프트웨어 이미지를 클러스터 패키지 저장소에 로드합니다

ONTAP 소프트웨어 업그레이드 프로세스를 시작하려면 클러스터 패키지 저장소에서 대상 ONTAP 소프트웨어 이미지를 사용할 수 있도록 해야 합니다.

.단계
. 이전 ONTAP 소프트웨어 패키지를 삭제합니다.
+
[source, cli]
----
cluster image package delete -version previous_ONTAP_Version
----
. 타겟 ONTAP 소프트웨어 이미지를 클러스터 패키지 저장소에 로드합니다.
+
[source, cli]
----
cluster image package get -url location
----
+
[listing]
----
cluster1::> cluster image package get -url http://www.example.com/software/9.13.1/image.tgz

Package download completed.
Package processing completed.
----
+
를 수행하는 경우 link:https://docs.netapp.com/us-en/ontap/upgrade/concept_upgrade_paths.html#types-of-upgrade-paths["직접 멀티 홉 업그레이드"]또한 업그레이드에 필요한 중간 버전의 ONTAP용 소프트웨어 패키지를 로드해야 합니다. 예를 들어 9.8에서 9.13.1로 업그레이드하는 경우 ONTAP 9.12.1용 소프트웨어 패키지를 로드한 다음 같은 명령을 사용하여 9.13.1용 소프트웨어 패키지를 로드해야 합니다.

. 소프트웨어 패키지를 클러스터 패키지 리포지토리에서 사용할 수 있는지 확인합니다.
+
[source, cli]
----
cluster image package show-repository
----
+
[listing]
----
cluster1::> cluster image package show-repository
Package Version  Package Build Time
---------------- ------------------
9.13.1              MM/DD/YYYY 10:32:15
----




== 2단계: 자동화된 업그레이드 사전 검사 실행

선택적으로 ONTAP 소프트웨어의 자동 업그레이드를 수행하기 전에 를 사용할 수 있습니다 `cluster image validate` 명령을 사용하여 클러스터를 업그레이드할 수 있는지 확인합니다.  를 클릭합니다 `cluster image validate` 명령은 클러스터 구성 요소에 대해 일련의 검사를 실행한 다음, 수행된 특정 유효성 검사 목록과 업그레이드를 진행하기 전에 수행해야 하는 수정 조치 목록을 제공합니다.

. 자동화된 업그레이드 사전 검사 실행:
+
[source, cli]
----
cluster image validate -version package_version_number
----
+
** 를 수행하는 경우 link:https://docs.netapp.com/us-en/ontap/upgrade/concept_upgrade_paths.html#types-of-upgrade-paths["직접 멀티 홉 업그레이드"]에서 확인할 대상 ONTAP 패키지를 사용합니다.  중간 업그레이드 이미지를 별도로 검증할 필요는 없습니다.  예를 들어 9.8에서 9.13.1 로 업그레이드하는 경우 9.13.1 패키지를 사용하여 확인해야 합니다. 9.12.1 패키지를 별도로 확인할 필요는 없습니다.
** 2노드 또는 4노드 MetroCluster 구성을 업그레이드할 경우 계속하기 전에 두 클러스터 모두에서 이 명령을 실행해야 합니다.
+
[listing]
----
cluster1::> cluster image validate -version 9.13.1

WARNING: There are additional manual upgrade validation checks that must be performed after these automated validation checks have completed...
----


. 검증 진행 상황 모니터링:
+
[source, cli]
----
cluster image show-update-progress
----
. 검증에서 식별된 모든 필수 조치를 완료하십시오.




== 3단계: ONTAP 소프트웨어를 업그레이드합니다

. 소프트웨어 업그레이드 예상 생성:
+
[source, cli]
----
cluster image update -version package_version_number -estimate-only
----
+
소프트웨어 업그레이드 추정치는 업데이트할 각 구성 요소에 대한 세부 정보와 예상 업그레이드 기간을 표시합니다.

. 소프트웨어 업그레이드 수행:
+
[source, cli]
----
cluster image update -version package_version_number
----
+
** 를 수행하는 경우 link:https://docs.netapp.com/us-en/ontap/upgrade/concept_upgrade_paths.html#types-of-upgrade-paths["직접 멀티 홉 업그레이드"]에서 package_version_number 의 대상 ONTAP 버전을 사용합니다. 예를 들어 ONTAP 9.8에서 9.13.1 로 업그레이드하는 경우 package_version_number 로 9.13.1 을 사용합니다.
** 클러스터가 2~6개 노드로 구성된 경우 롤링 업그레이드가 수행됩니다. 클러스터가 8개 이상의 노드로 구성된 경우 기본적으로 일괄 업그레이드가 수행됩니다. 원하는 경우 '-force-rolling' 매개 변수를 사용하여 롤링 업그레이드를 대신 지정할 수 있습니다.
** 각각의 테이크오버 및 반환을 완료한 후, 업데이트는 클라이언트 애플리케이션이 테이크오버 및 반환 중에 발생하는 I/O의 일시 중지에서 복구될 수 있도록 8분 동안 대기합니다. 고객 안정화에 필요한 시간이 환경에 더 많이 또는 더 적게 필요한 경우 '-안정화-분' 매개변수를 사용하여 다른 안정화 시간을 지정할 수 있습니다.
** 2노드 MetroCluster 시스템을 제외한 모든 MetroCluster 구성의 경우, 사용자가 명령줄을 시작하고 확인하면 ONTAP 업그레이드 프로세스가 두 사이트(로컬 사이트 및 재해 복구 사이트)의 HA 쌍에서 동시에 시작됩니다. 2노드 MetroCluster 시스템의 경우 먼저 재해 복구 사이트, 즉 업그레이드가 시작되지 않은 사이트에서 업데이트가 시작됩니다. 재해 복구 사이트에서 업데이트가 완전히 완료되면 로컬 사이트에서 업그레이드가 시작됩니다.
+
[listing]
----
cluster1::> cluster image update -version 9.13.1

Starting validation for this update. Please wait..

It can take several minutes to complete validation...

WARNING: There are additional manual upgrade validation checks...

Pre-update Check      Status     Error-Action
--------------------- ---------- --------------------------------------------
...
20 entries were displayed

Would you like to proceed with update ? {y|n}: y
Starting update...

cluster-1::>
----


. 클러스터 업데이트 진행률을 표시합니다.
+
[source, cli]
----
cluster image show-update-progress
----
+
4노드 또는 8노드 MetroCluster 구성을 업그레이드할 경우 'cluster image show-update-progress' 명령은 명령을 실행하는 노드의 진행진만 표시합니다. 개별 노드의 진행률을 보려면 각 노드에서 명령을 실행해야 합니다.

. 각 노드에서 업그레이드가 성공적으로 완료되었는지 확인합니다.
+
[source, cli]
----
cluster image show-update-progress
----
+
[listing]
----
cluster1::> cluster image show-update-progress

                                             Estimated         Elapsed
Update Phase         Status                   Duration        Duration
-------------------- ----------------- --------------- ---------------
Pre-update checks    completed                00:10:00        00:02:07
Data ONTAP updates   completed                01:31:00        01:39:00
Post-update checks   completed                00:10:00        00:02:00
3 entries were displayed.

Updated nodes: node0, node1.
----
. AutoSupport 알림 트리거:
+
[source, cli]
----
autosupport invoke -node * -type all -message "Finishing_NDU"
----
+
클러스터가 AutoSupport 메시지를 전송하도록 구성되지 않은 경우 알림 복사본이 로컬에 저장됩니다.

. 클러스터가 자동 비계획 스위치오버에 대해 설정되었는지 확인합니다.
+

NOTE: 이 단계는 MetroCluster FC 구성에만 수행됩니다.  MetroCluster IP 구성을 사용하는 경우 이 단계를 수행할 필요가 없습니다.

+
.. 예기치 않은 자동 전환이 활성화되어 있는지 확인합니다.
+
[source, cli]
----
metrocluster show
----
+
자동 비계획 전환이 활성화된 경우 명령 출력에 다음 설명이 표시됩니다.

+
....
AUSO Failure Domain    auso-on-cluster-disaster
....
.. 명령문이 출력에 표시되지 않으면 예기치 않은 자동 전환을 설정합니다.
+
[source, cli]
----
metrocluster modify -auto-switchover-failure-domain auso-on-cluster-disaster -overide-vetoes true
----
+

NOTE: 자동 무중단 업그레이드가 완료될 때까지는 스위치백 작업을 수행할 수 없습니다.

.. 예기치 않은 자동 전환이 활성화되어 있는지 확인:
+
[source, cli]
----
metrocluster show
----




.관련 정보
* https://aiq.netapp.com/["Active IQ를 시작합니다"]
* https://docs.netapp.com/us-en/active-iq/["Active IQ 설명서"]

