---
permalink: upgrade/task_resuming_snapmirror_operations.html 
sidebar: sidebar 
keywords: ontap, upgrade, resuming, resume, snapmirror 
summary: 무중단 업그레이드를 완료한 후에는 일시 중단된 SnapMirror 관계를 모두 다시 시작해야 합니다. 
---
= SnapMirror 작업을 다시 시작합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
무중단 업그레이드를 완료한 후에는 일시 중단된 SnapMirror 관계를 모두 다시 시작해야 합니다.

SnapMirror quiesce 명령을 사용하여 기존 SnapMirror 관계를 일시 중지해야 하며 클러스터가 중단 없이 업그레이드되어야 합니다.

. 이전에 중지된 각 SnapMirror 관계에 대해 '스냅샷 재시작 *'을 다시 시작합니다
+
이 명령은 중지된 모든 SnapMirror 관계에 대한 전송을 재개합니다.

. SnapMirror 작업이 다시 시작되었는지 확인합니다. '스냅샷 표시'입니다
+
[listing]
----
cluster1::> snapmirror show

Source            Destination  Mirror  Relationship  Total             Last
Path        Type  Path         State   Status        Progress  Healthy Updated
----------- ---- ------------ ------- -------------- --------- ------- --------
cluster1-vs1:dp_src1
            DP   cluster1-vs2:dp_dst1
                              Snapmirrored
                                      Idle           -         true    -
cluster1-vs1:xdp_src1
            XDP  cluster1-vs2:xdp_dst1
                              Snapmirrored
                                      Idle           -         true    -
cluster1://cluster1-vs1/ls_src1
            LS   cluster1://cluster1-vs1/ls_mr1
                              Snapmirrored
                                      Idle           -         true    -
                 cluster1://cluster1-vs1/ls_mr2
                              Snapmirrored
                                      Idle           -         true    -
4 entries were displayed.
----
+
각 SnapMirror 관계에 대해 관계 상태가 * 유휴 * 인지 확인합니다. 상태가 * TRANSFing * 인 경우 SnapMirror 전송이 완료될 때까지 기다린 다음 명령을 다시 입력하여 상태가 * Idle * 로 변경되었는지 확인합니다.



일정에 따라 실행되도록 구성된 각 SnapMirror 관계에 대해 첫 번째 예약된 SnapMirror 전송이 성공적으로 완료되었는지 확인해야 합니다.
