---
permalink: upgrade/task_verify_cluster_after_upgrade.html 
sidebar: sidebar 
keywords: ontap, upgrade, upgrade, verify, status, health, post, after 
summary: 업그레이드 후에는 클러스터를 확인해야 합니다. 
---
= 업그레이드 후 클러스터 검증
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
업그레이드 후에는 클러스터 버전, 클러스터 상태 및 스토리지 상태를 확인해야 합니다.

.시작하기 전에

NOTE: MetroCluster FC 구성을 사용하는 경우 비계획 자동 스위치오버가 활성화되어 있는지도 확인해야 합니다.



== 클러스터 버전을 확인합니다

모든 HA 쌍을 업그레이드한 후에는 version 명령을 사용하여 모든 노드가 타겟 릴리즈를 실행하고 있는지 확인해야 합니다.

클러스터 버전은 클러스터의 모든 노드에서 실행되는 ONTAP의 가장 낮은 버전입니다. 클러스터 버전이 타겟 ONTAP 릴리즈가 아닌 경우 클러스터를 업그레이드할 수 있습니다.

. 클러스터 버전이 타겟 ONTAP 릴리즈인지 확인합니다.
+
'내전'

. 클러스터 버전이 타겟 ONTAP 릴리즈가 아닌 경우 모든 노드의 업그레이드 상태를 확인할 수 있습니다.
+
'system node upgrade-revert show'를 선택합니다





== 클러스터 상태를 확인합니다

[role="lead"]
클러스터를 업그레이드한 후 노드가 정상 상태이며 클러스터에 참여할 수 있고 클러스터가 쿼럼에 있는지 확인해야 합니다.

. 클러스터의 노드가 온라인 상태이며 클러스터에 참여할 자격이 있는지 확인합니다.
+
'클러스터 쇼'

+
[listing]
----
cluster1::> cluster show
Node                  Health  Eligibility
--------------------- ------- ------------
node0                 true    true
node1                 true    true
----
+
노드가 정상 상태가 아니거나 적합하지 않은 경우 EMS 로그에서 오류를 확인하고 수정 조치를 취합니다.

. 권한 수준을 고급으로 설정합니다.
+
세트 프리빌리지 고급

+
계속하려면 "y"를 입력하십시오.

. 각 RDB 프로세스에 대한 구성 세부 정보를 확인합니다.
+
** 관계형 데이터베이스 epoch 및 데이터베이스 epoch는 각 노드에 대해 일치해야 합니다.
** 링당 쿼럼 마스터는 모든 노드에 대해 동일해야 합니다.
+
각 링에는 다른 쿼럼 마스터가 있을 수 있습니다.

+
|===


| 이 RDB 프로세스를 표시하려면... | 이 명령을 입력하십시오... 


 a| 
기능과
 a| 
클러스터 링 쇼-unitname 관리



 a| 
볼륨 위치 데이터베이스
 a| 
클러스터 링 쇼-언이트네임 VLDB



 a| 
Virtual-Interface Manager를 참조하십시오
 a| 
클러스터 링 쇼-unitname vifmgr



 a| 
SAN 관리 데몬
 a| 
'클러스터 링 쇼-언이트네임 bcomd'

|===
+
이 예에서는 볼륨 위치 데이터베이스 프로세스를 보여 줍니다.



+
[listing]
----
cluster1::*> cluster ring show -unitname vldb
Node      UnitName Epoch    DB Epoch DB Trnxs Master    Online
--------- -------- -------- -------- -------- --------- ---------
node0     vldb     154      154      14847    node0     master
node1     vldb     154      154      14847    node0     secondary
node2     vldb     154      154      14847    node0     secondary
node3     vldb     154      154      14847    node0     secondary
4 entries were displayed.
----
. SAN 환경에서 작동 중인 경우 각 노드가 SAN quorum에 있는지 확인합니다. '이벤트 로그 show-severity Informational-message-name scsibeBlade. *
+
각 노드에 대한 가장 최근의 scsib블레이드 이벤트 메시지는 SCSI 블레이드가 quorum에 있음을 나타내야 합니다.

+
[listing]
----
cluster1::*> event log show  -severity informational -message-name scsiblade.*
Time             Node       Severity       Event
---------------  ---------- -------------- ---------------------------
MM/DD/YYYY TIME  node0      INFORMATIONAL  scsiblade.in.quorum: The scsi-blade ...
MM/DD/YYYY TIME  node1      INFORMATIONAL  scsiblade.in.quorum: The scsi-blade ...
----


link:../system-admin/index.html["시스템 관리"]



== 예기치 않은 자동 전환이 활성화되어 있는지 확인합니다

클러스터를 업그레이드한 후에는 예정되지 않은 자동 전환이 활성화되어 있는지 확인해야 합니다.

.이 작업에 대해

NOTE: 이 절차는 MetroCluster FC 구성에만 수행됩니다. MetroCluster IP 구성을 사용하는 경우 이 절차를 건너뜁니다.

.단계
. 예기치 않은 자동 전환이 활성화되어 있는지 확인합니다.
+
MetroCluster 쇼

+
자동 비계획 전환이 활성화된 경우 명령 출력에 다음 설명이 표시됩니다.

+
[listing]
----
AUSO Failure Domain  auso-on-cluster-disaster
----
. 명령문이 나타나지 않으면 예기치 않은 자동 전환을 설정합니다.
+
'MetroCluster modify-auto-switchover-failure-domain auso-on-cluster-disaster

. 1단계를 반복하여 예기치 않은 자동 전환을 활성화했는지 확인합니다.




== 스토리지 상태를 확인합니다

클러스터를 업그레이드한 후에는 디스크, 애그리게이트, 볼륨의 상태를 확인해야 합니다.

. 디스크 상태 확인:
+
|===


| 확인하려면... | 수행할 작업... 


 a| 
손상된 디스크
 a| 
.. 손상된 디스크를 표시합니다.
+
스토리지 디스크 표시 상태 중단됨

.. 손상된 디스크를 제거하거나 교체합니다.




 a| 
유지보수 또는 재구성이 진행 중인 디스크
 a| 
.. 유지 보수, 보류 또는 재구성 상태의 디스크를 표시합니다.
+
'스토리지 디스크 상태 유지 관리 | 보류 중 | 재구성 중'

.. 유지보수 또는 재구성 작업이 완료될 때까지 기다린 후 계속 진행하십시오.


|===
. 스토리지 애그리게이트를 포함하여 물리적 스토리지와 논리적 스토리지의 상태를 표시하여 모든 애그리게이트가 온라인 상태인지 확인합니다.
+
'스토리지 집계 쇼-스테이트! 온라인'

+
이 명령은 _not_online 인 애그리게이트를 표시합니다. 주요 업그레이드 또는 리버전을 수행하기 전과 후의 모든 애그리게이트는 온라인 상태여야 합니다.

+
[listing]
----
cluster1::> storage aggregate show -state !online
There are no entries matching your query.
----
. _NOT_ONLINE 상태인 볼륨을 표시하여 모든 볼륨이 온라인 상태인지 확인합니다.
+
'볼륨 쇼-스테이트! 온라인'

+
주요 업그레이드 또는 재버전을 수행하기 전과 후에 모든 볼륨이 온라인 상태여야 합니다.

+
[listing]
----
cluster1::> volume show -state !online
There are no entries matching your query.
----
. 일치하지 않는 볼륨이 없는지 확인합니다.
+
'볼륨 쇼-is-inconsistent true'

+
기술 자료 문서를 참조하십시오 link:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/Volume_Showing_WAFL_Inconsistent["WAFL가 일치하지 않는 볼륨으로 표시됩니다"] 정합성이 보장되지 않는 볼륨을 처리하는 방법에 대해 설명합니다.



link:../disks-aggregates/index.html["디스크 및 애그리게이트 관리"]
