---
permalink: upgrade/task_verifying_that_deduplicated_volumes_and_aggregates_contain_sufficient_free_space.html 
sidebar: sidebar 
keywords: ontap, upgrade, verify, verifying, deduplication, deduplicated, volumes, aggregates, sufficient, enough, free, space 
summary: ONTAP를 업그레이드하기 전에 중복제거된 볼륨 및 볼륨이 포함된 애그리게이트에 중복제거 메타데이터를 위한 여유 공간이 있는지 확인해야 합니다. 사용 가능한 공간이 부족하면 ONTAP 업그레이드가 완료될 때 중복 제거가 비활성화됩니다. 
---
= 중복제거된 볼륨 및 애그리게이트에 충분한 가용 공간이 있는지 확인합니다
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP를 업그레이드하기 전에 중복제거된 볼륨 및 볼륨이 포함된 애그리게이트에 중복제거 메타데이터를 위한 여유 공간이 있는지 확인해야 합니다. 사용 가능한 공간이 부족하면 ONTAP 업그레이드가 완료될 때 중복 제거가 비활성화됩니다.

중복제거된 각 볼륨의 사용 가능한 공간은 4% 이상이어야 합니다. 중복제거된 볼륨이 포함된 각 애그리게이트에는 3% 이상의 여유 공간이 포함되어야 합니다.

. 볼륨 효율성 표시 등 어느 볼륨에 중복이 제거되는지 확인합니다
. 식별된 각 볼륨에서 사용 가능한 여유 공간을 확인하십시오. 'vol show -vserver Vserver_name -volume_name -fields volume, size, used, available, percent-used, junction-path'입니다
+
중복 제거된 각 볼륨에는 사용된 용량이 96% 이상 포함되어서는 안 됩니다. 필요한 경우 이 용량을 초과하는 볼륨의 크기를 늘릴 수 있습니다.

+
link:../volumes/index.html["논리적 스토리지 관리"]

+
이 예에서 사용된 비율 필드에는 중복제거된 볼륨의 사용된 공간 백분율이 표시됩니다.

+
[listing]
----
vserver    volume size    junction-path available used   percent-used
----------- ------ ------- -------------
cluster1-01 vol0   22.99GB -             14.11GB      7.73GB 35%
cluster1-02 vol0   22.99GB -             12.97GB      8.87GB    40%
2 entries were displayed.
----
. 중복 제거된 볼륨이 포함된 각 Aggregate에서 사용 가능한 여유 공간('aggr show-aggregate aggregate_name-fields aggregate, size, usedsize, available size, percent-used')을 식별합니다
+
각 애그리게이트에는 97% 이상의 사용된 용량이 포함되어서는 안 됩니다. 필요한 경우 이 용량을 초과하는 애그리게이트의 크기를 늘릴 수 있습니다.

+
link:../disks-aggregates/index.html["디스크 및 애그리게이트 관리"]

+
이 예에서 사용된 비율 필드에는 중복제거된 볼륨(aggr_2)이 포함된 애그리게이트에서 사용된 공간의 비율이 표시됩니다.

+
[listing]
----
aggr show -aggregate aggregate_name -fields aggregate,size,usedsize,availsize,percent-used
aggregate         availsize percent-used size    usedsize
----------------- --------- ------------    ------- --------
aggr0_cluster1_01    1.11GB    95%          24.30GB 23.19GB
aggr0_cluster1_02 1022MB    96%          24.30GB    23.30GB
2 entries were displayed.
----

