---
permalink: zero-trust/zero-trust-automation-orchestration.html 
sidebar: sidebar 
keywords: tr-4829, zero trust, ontap, netapp, security, automation, orchestration, control, ansible 
summary: 조직은 자동화를 통해 제로 트러스트 구축을 수동 절차를 넘어 확장할 수 있으므로 자동화되는 악의적인 활동을 방지할 수 있습니다 
---
= ONTAP 외부 NetApp 보안 자동화 및 오케스트레이션 제어
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
자동화를 통해 최소한의 인적 지원만으로 프로세스 또는 절차를 수행할 수 있습니다. 조직은 자동화를 통해 제로 트러스트 구축을 수동 절차를 훨씬 넘어 확장할 수 있으므로 자동화되는 악의적인 활동을 방지할 수 있습니다.

Ansible은 오픈 소스 소프트웨어 프로비저닝, 구성 관리 및 애플리케이션 배포 툴입니다. 많은 유닉스와 유사한 시스템에서 실행되며, 유닉스와 유사한 시스템과 Microsoft Windows를 모두 구성할 수 있습니다. 시스템 구성을 설명하는 고유한 선언적 언어가 포함되어 있습니다. Ansible은 Michael DeHaan이 작성했으며 2015년에 Red Hat에 인수되었습니다. Ansible은 에이전트가 없습니다. SSH 또는 Windows 원격 관리를 통해 일시적으로 원격으로 연결하여 원격 PowerShell 실행 허용 을 수행할 수 있습니다. NetApp은 그 이상을 개발했으며 https://www.netapp.com/us/getting-started-with-netapp-approved-ansible-modules/index.aspx["ONTAP 소프트웨어용 Ansible 모듈 150개"^]Ansible 자동화 프레임워크와 추가적인 통합을 가능하게 했습니다. NetApp용 Ansible 모듈은 원하는 상태를 정의하고 타겟 NetApp 환경에 전달하는 방법에 관한 일련의 지침을 제공합니다. 이들 모듈은 라이센스 설정, 애그리게이트 및 스토리지 가상 머신 생성, 볼륨 생성, 스냅샷 복원 등의 작업을 지원할 목적으로 개발되었습니다. Ansible 역할은 NetApp DoD UC(Unified Capabilities https://github.com/NetApp/ansible/tree/master/nar_ontap_security_ucd_guide["GitHub에 게시되었습니다"^] ) 배포 가이드에 따라 다릅니다.

사용자는 사용 가능한 모듈 라이브러리를 통해 쉽게 Ansible 플레이북을 개발하고 고유한 애플리케이션 및 비즈니스 요구사항에 맞게 맞춤화하여 일상적인 작업을 자동화할 수 있습니다. 플레이북을 작성한 후 특정 작업을 수행하도록 실행하면 시간이 절약되고 생산성이 향상됩니다. NetApp은 직접 사용하거나 필요에 맞게 맞춤화할 수 있는 샘플 플레이북을 마련하여 공유했습니다.

Cloud Insights는 전체 인프라에 대한 가시성을 제공하는 인프라 모니터링 툴입니다. Cloud Insights를 사용하면 퍼블릭 클라우드 인스턴스 및 프라이빗 데이터 센터를 비롯한 모든 리소스에 대한 모니터링, 문제 해결 및 최적화 작업을 수행할 수 있습니다. Cloud Insights는 평균 해결 시간을 90% 단축하고 최종 사용자에게 영향을 미치는 클라우드 문제를 80% 예방합니다. 또한, 실행 가능한 인텔리전스로 데이터를 보호하여 클라우드 인프라 비용을 평균 33% 절감하고 내부자 위협에 대한 노출을 줄일 수 있습니다. Cloud Insights의 스토리지 워크로드 보안 기능을 사용하면 내부자 위협으로 인해 비정상적인 사용자 행동이 발생할 경우 AI 및 ML을 통한 사용자 행동 분석을 수행할 수 있습니다. ONTAP의 경우 스토리지 워크로드 보안은 제로 트러스트 FPolicy 엔진을 사용합니다.
