---
permalink: performance-admin/adaptive-policy-template-task.html 
sidebar: sidebar 
keywords: qos, throughput floor, throughput ceiling, adaptive policy group template 
summary: 적응형 정책 그룹 템플릿을 사용하여 SVM 레벨에서 처리량 플로어 및 상한을 적용합니다. 
---
= 적응형 정책 그룹 템플릿을 설정합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9.13.1 부터는 적응형 정책 그룹 템플릿을 사용하여 SVM 레벨에서 처리량 플로와 천장을 적용할 수 있습니다.

.이 작업에 대해
* 적응형 정책 그룹 템플릿은 기본 정책입니다 `apg1`. 정책은 언제든지 수정할 수 있습니다. CLI 또는 ONTAP REST API에서만 설정할 수 있고 기존 SVM에만 적용할 수 있습니다.
* 적응형 정책 그룹 템플릿은 정책을 설정한 후 SVM에서 생성되거나 SVM으로 마이그레이션된 볼륨에만 영향을 줍니다. SVM의 기존 볼륨은 기존 상태를 유지합니다.
+
적응형 정책 그룹 템플릿을 비활성화하면 SVM의 볼륨은 기존 정책을 그대로 유지합니다. 이후에 SVM에서 생성하거나 SVM으로 마이그레이션한 볼륨만 지원 해제에 의해 영향을 받습니다.

* QoS 정책 그룹을 갖는 SVM에서는 적응형 정책 그룹 템플릿을 설정할 수 없습니다.
* 적응형 정책 그룹 템플릿은 AFF 플랫폼용으로 설계되었습니다. 적응형 정책 그룹 템플릿은 다른 플랫폼에 설정할 수 있지만 정책이 최소 처리량을 적용하지 않을 수 있습니다. 마찬가지로, FabricPool 애그리게이트 또는 최소 처리량을 지원하지 않는 애그리게이트에서 SVM에 적응형 정책 그룹 템플릿을 추가할 수 있지만 처리량 플로어가 적용되지 않습니다.
* SVM이 MetroCluster 구성 또는 SnapMirror 관계에 있는 경우 적응형 정책 그룹 템플릿이 미러링된 SVM에 적용됩니다.


.단계
. SVM을 수정하여 적응형 정책 그룹 템플릿을 적용합니다.
`vserver modify -qos-adaptive-policy-group-template apg1`
. 정책이 설정되었는지 확인합니다.
`vserver show -fields qos-adaptive-policy-group`

