---
permalink: performance-admin/measure-latency-throughput-nodes-task.html 
sidebar: sidebar 
keywords: check, throughput, latency, between, nodes 
summary: network test-path 명령을 사용하여 네트워크 병목 현상을 식별하거나 노드 간 네트워크 경로를 사전 평가할 수 있습니다. 클러스터 간 노드 또는 클러스터 내 노드 간에 명령을 실행할 수 있습니다. 
---
= 노드 간 처리량과 지연 시간을 확인합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
'network test-path' 명령을 사용하여 네트워크 병목 현상을 식별하거나 노드 간 네트워크 경로를 다시 확인할 수 있습니다. 클러스터 간 노드 또는 클러스터 내 노드 간에 명령을 실행할 수 있습니다.

.시작하기 전에
* 이 작업을 수행하려면 클러스터 관리자여야 합니다.
* 이 작업에는 고급 권한 레벨 명령이 필요합니다.
* 인터클러스터 경로의 경우 소스 클러스터와 대상 클러스터를 피어링해야 합니다.


.이 작업에 대해
노드 간 네트워크 성능이 경로 구성에 대한 기대치를 충족하지 못하는 경우가 있습니다. 예를 들어, SnapMirror 복제 작업에서 볼 수 있는 대규모 데이터 전송 유형에 대한 1Gbps의 전송 속도는 소스 클러스터와 대상 클러스터 간의 10GbE 링크와 일치하지 않습니다.

network test-path 명령을 사용하여 노드 간 처리량과 대기 시간을 측정할 수 있습니다. 클러스터 간 노드 또는 클러스터 내 노드 간에 명령을 실행할 수 있습니다.

[NOTE]
====
이 테스트는 데이터가 네트워크 경로를 포화시키기 때문에, 시스템이 사용 중이 아닐 때나 노드 간 네트워크 트래픽이 과도하지 않을 때는 명령을 실행해야 합니다. 10초 후 테스트 시간이 초과됩니다. 명령은 ONTAP 9 노드 간에만 실행할 수 있습니다.

====
'세션 유형' 옵션은 네트워크 경로를 통해 실행 중인 작업 유형을 식별합니다(예: 원격 대상에 대한 SnapMirror 복제를 위한 "AsyncMirrorRemote"). 유형은 테스트에 사용되는 데이터의 양을 나타냅니다. 다음 표에서는 세션 유형을 정의합니다.

|===


| 세션 유형 | 설명 


 a| 
AsyncMirrorLocal 을 선택합니다
 a| 
동일한 클러스터의 노드 간에 SnapMirror가 사용하는 설정입니다



 a| 
AsyncMirrorRemote 를 참조하십시오
 a| 
서로 다른 클러스터 노드 간에 SnapMirror가 사용하는 설정(기본 유형)



 a| 
RemoteDataTransfer를 참조하십시오
 a| 
ONTAP에서 동일한 클러스터의 노드 간 원격 데이터 액세스를 위해 사용하는 설정(예: 다른 노드의 볼륨에 저장된 파일에 대해 노드에 NFS 요청)

|===
.단계
. 고급 권한 레벨로 변경:
+
세트 프리빌리지 고급

. 노드 간 처리량 및 지연 시간 측정:
+
'network test-path-source-node_source_nodename_|local-destination-cluster_destination_clustername_-destination-node_destination_nodename_-session-type Default|AsyncMirrorLocal|AsyncMirrorRemote|SyncMirrorRemote|RemoteDataTransfer'

+
소스 노드는 로컬 클러스터에 있어야 합니다. 대상 노드는 로컬 클러스터 또는 피어링된 클러스터에 있을 수 있습니다. '-source-node'의 "local" 값은 명령을 실행하는 노드를 지정합니다.

+
다음 명령을 실행하면 로컬 클러스터의 노드1과 클러스터2의 노드3의 SnapMirror 유형 복제 작업에 대한 처리량과 지연 시간이 측정됩니다.

+
[listing]
----
cluster1::> network test-path -source-node node1 -destination-cluster cluster2 -destination-node node3 -session-type AsyncMirrorRemote
----
+
샘플 출력(출력 세부 사항은 사용 중인 ONTAP 버전에 따라 다를 수 있음):

+
[listing]
----
Test Duration:      10.88 secs
Send Throughput:    18.23 MB/sec
Receive Throughput: 18.23 MB/sec
MB sent:            198.31
MB received:        198.31
Avg latency in ms:  2301.47
----
. 관리 권한으로 돌아가기:
+
'Set-Privilege admin'입니다



.작업을 마친 후
성능이 경로 구성에 대한 기대를 충족하지 않는 경우 노드 성능 통계를 확인하고, 사용 가능한 툴을 사용하여 네트워크에서 문제를 격리하고, 스위치 설정을 확인하는 등의 작업을 수행해야 합니다.
