---
permalink: performance-config/specify-clusters-monitor-task.html 
sidebar: sidebar 
keywords: specify, clusters, monitored 
summary: 클러스터를 모니터링하고, 클러스터 검색 상태를 확인하고, 성능을 모니터링하려면 Active IQ Unified Manager 서버에 클러스터를 추가해야 합니다. 
---
= 모니터링할 클러스터를 지정합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
클러스터를 모니터링하고, 클러스터 검색 상태를 확인하고, 성능을 모니터링하려면 Active IQ Unified Manager 서버에 클러스터를 추가해야 합니다.

.무엇을 &#8217;필요로 할거야
* 다음 정보가 있어야 합니다.
+
** 호스트 이름 또는 클러스터 관리 IP 주소입니다
+
호스트 이름은 Unified Manager에서 클러스터에 연결하는 데 사용하는 FQDN(정규화된 도메인 이름) 또는 짧은 이름입니다. 이 호스트 이름은 클러스터 관리 IP 주소로 확인되어야 합니다.

+
클러스터 관리 IP 주소는 관리 스토리지 가상 시스템(SVM)의 클러스터 관리 LIF여야 합니다. 노드 관리 LIF를 사용하면 작업이 실패합니다.

** ONTAP 관리자 사용자 이름 및 암호
** 클러스터에서 구성할 수 있는 프로토콜 유형(HTTP 또는 HTTPS) 및 클러스터의 포트 번호입니다


* 애플리케이션 관리자 또는 스토리지 관리자 역할이 있어야 합니다.
* ONTAP 관리자는 ONTAPI 및 SSH 관리자 역할이 있어야 합니다.
* Unified Manager FQDN이 ONTAP을 ping할 수 있어야 합니다.
+
ONTAP 명령 'ping-node_name-destination Unified_Manager_FQDN'을 사용하여 이를 확인할 수 있습니다.



MetroCluster 구성의 경우 로컬 클러스터와 원격 클러스터를 모두 추가해야 하며 클러스터가 올바르게 구성되어야 합니다.

.단계
. 구성 * > * 클러스터 데이터 소스 * 를 클릭합니다.
. 클러스터 페이지에서 * 추가 * 를 클릭합니다.
. 클러스터 추가 * 대화 상자에서 클러스터의 호스트 이름 또는 IP 주소(IPv4 또는 IPv6), 사용자 이름, 암호, 통신 프로토콜 및 포트 번호와 같은 필수 값을 지정합니다.
+
기본적으로 HTTPS 프로토콜이 선택됩니다.

+
클러스터 관리 IP 주소를 IPv6에서 IPv4로, 또는 IPv4에서 IPv6로 변경할 수 있습니다. 새 IP 주소는 다음 모니터링 주기가 완료된 후 클러스터 그리드 및 클러스터 구성 페이지에 반영됩니다.

. 추가 * 를 클릭합니다.
. HTTPS를 선택한 경우 다음 단계를 수행하십시오.
+
.. 호스트 인증 * 대화 상자에서 * 인증서 보기 * 를 클릭하여 클러스터에 대한 인증서 정보를 봅니다.
.. 예 * 를 클릭합니다.
+
Unified Manager는 처음에 클러스터가 추가된 경우에만 인증서를 검사하지만 ONTAP에 대한 각 API 호출에서는 인증서를 확인하지 않습니다.

+
인증서가 만료된 경우 클러스터를 추가할 수 없습니다. SSL 인증서를 갱신한 다음 클러스터를 추가해야 합니다.



. * 선택 사항 *: 클러스터 검색 상태 보기:
+
.. Cluster Setup * 페이지에서 클러스터 검색 상태를 검토합니다.


+
기본 모니터링 간격 약 15분이 지나면 클러스터가 Unified Manager 데이터베이스에 추가됩니다.


