---
permalink: peering/create-cluster-relationship-92-earlier-task.html 
sidebar: sidebar 
keywords: create, cluster, peer, relationship 
summary: 클러스터 피어 생성 명령을 사용하여 로컬 클러스터와 원격 클러스터 간의 피어링 관계에 대한 요청을 시작할 수 있습니다. 로컬 클러스터에서 피어 관계를 요청한 후에는 원격 클러스터에서 클러스터 피어 생성을 실행하여 관계를 수락할 수 있습니다. 
---
= 클러스터 피어 관계 생성(ONTAP 9.2 이하)
:icons: font
:imagesdir: ../media/


[role="lead"]
'cluster peer create' 명령을 사용하여 로컬 클러스터와 원격 클러스터 간의 피어링 관계에 대한 요청을 시작할 수 있습니다. 로컬 클러스터에서 피어 관계를 요청한 후에는 원격 클러스터에서 '클러스터 피어 생성'을 실행하여 관계를 수락할 수 있습니다.

.무엇을 &#8217;필요로 할거야
* 피어링된 클러스터의 모든 노드에 대한 인터클러스터 LIF를 생성해야 합니다.
* 클러스터 관리자는 각 클러스터가 다른 클러스터에 자신을 인증하는 데 사용할 암호에 동의해야 합니다.


.단계
. 데이터 보호 대상 클러스터에서 데이터 보호 소스 클러스터와의 피어 관계를 생성합니다.
+
'cluster peer create-peer-addrs_peer_LIF_ips_-IPSpace_IPSpace_'

+
사용자 지정 IPspace를 사용하지 않는 경우 '-IPSpace' 옵션을 무시할 수 있습니다. 전체 명령 구문은 man 페이지를 참조하십시오.

+
다음 예에서는 인터클러스터 LIF IP 주소 192.168.2.201 및 192.168.2.202에서 원격 클러스터와 클러스터 피어 관계를 생성합니다.

+
[listing]
----
cluster02::> cluster peer create -peer-addrs 192.168.2.201,192.168.2.202
Enter the passphrase:
Please enter the passphrase again:
----
+
메시지가 나타나면 피어 관계에 대한 암호를 입력합니다.

. 데이터 보호 소스 클러스터에서 소스 클러스터를 대상 클러스터에 인증합니다.
+
'cluster peer create-peer-addrs_peer_LIF_ips_-IPSpace_IPSpace_'

+
전체 명령 구문은 man 페이지를 참조하십시오.

+
다음 예에서는 인터클러스터 LIF IP 주소 192.140.112.203 및 192.140.112.204에서 원격 클러스터에 대한 로컬 클러스터를 인증합니다.

+
[listing]
----
cluster01::> cluster peer create -peer-addrs 192.168.2.203,192.168.2.204
Please confirm the passphrase:
Please confirm the passphrase again:
----
+
메시지가 나타나면 피어 관계에 대한 암호를 입력합니다.

. 클러스터 피어 관계가 생성되었는지 확인합니다.
+
'클러스터 피어 쇼 – 인스턴스'

+
전체 명령 구문은 man 페이지를 참조하십시오.

+
[listing]
----
cluster01::> cluster peer show –instance
Peer Cluster Name: cluster01
Remote Intercluster Addresses: 192.168.2.201,192.168.2.202
Availability: Available
Remote Cluster Name: cluster02
Active IP Addresses: 192.168.2.201,192.168.2.202
Cluster Serial Number: 1-80-000013
----
. 피어 관계에서 노드의 접속 상태와 상태를 확인합니다.
+
클러스터 피어 상태 쇼

+
전체 명령 구문은 man 페이지를 참조하십시오.

+
[listing]
----
cluster01::> cluster peer health show
Node       cluster-Name                Node-Name
             Ping-Status               RDB-Health Cluster-Health  Avail…
---------- --------------------------- ---------  --------------- --------
cluster01-01
           cluster02                   cluster02-01
             Data: interface_reachable
             ICMP: interface_reachable true       true            true
                                       cluster02-02
             Data: interface_reachable
             ICMP: interface_reachable true       true            true
cluster01-02
           cluster02                   cluster02-01
             Data: interface_reachable
             ICMP: interface_reachable true       true            true
                                       cluster02-02
             Data: interface_reachable
             ICMP: interface_reachable true       true            true
----

