---
permalink: peering/create-intercluster-svm-peer-relationship-93-later-task.html 
sidebar: sidebar 
keywords: create, intercluster, svm, peer, relationship 
summary: SVM 피어 생성 명령을 사용하여 로컬 및 원격 클러스터에서 SVM 간에 피어 관계를 생성할 수 있습니다. 
---
= 인터클러스터 SVM 피어 관계 생성(ONTAP 9.3 이상)
:icons: font
:imagesdir: ../media/


[role="lead"]
'vserver peer create' 명령을 사용하여 로컬 및 원격 클러스터의 SVM 간에 피어 관계를 생성할 수 있습니다.

.무엇을 &#8217;필요로 할거야
* 소스 및 타겟 클러스터를 내다봐야 합니다.
* 클러스터는 ONTAP 9.3을 실행해야 합니다.
* 원격 클러스터의 SVM에 대해 "사전 승인된" 피어 관계가 있어야 합니다.
+
자세한 내용은 을 참조하십시오 link:create-cluster-relationship-93-later-task.html["클러스터 피어 관계 생성(ONTAP 9.3 이상)"].



ONTAP의 이전 릴리즈에서는 한 번에 하나의 SVM에 대해서만 피어 관계를 승인할 수 있습니다. 보류 중인 SVM 피어 관계를 승인할 때마다 'vserver peer accept' 명령을 실행해야 했습니다.

ONTAP 9.3부터는 클러스터 피어 관계를 생성할 때 '-initial-allowed-vserver' 옵션에 SVM을 나열하여 여러 SVM에 대한 피어 관계를 "사전 승인"할 수 있습니다. 자세한 내용은 을 참조하십시오 link:create-cluster-relationship-93-later-task.html["클러스터 피어 관계 생성(ONTAP 9.3 이상)"].

.단계
. 데이터 보호 대상 클러스터에서 피어링을 위해 사전 승인된 SVM을 표시합니다.
+
'vserver peer permission show'

+
[listing]
----
cluster02::> vserver peer permission show
Peer Cluster         Vserver               Applications
-------------------  --------------------  --------------------
cluster02            vs1,vs2               snapmirror
----
. 데이터 보호 소스 클러스터에서 데이터 보호 대상 클러스터의 사전 승인된 SVM과 피어 관계를 생성합니다.
+
'vserver peer create-vserver_local_SVM_-peer-vserver_remote_SVM_'

+
전체 명령 구문은 man 페이지를 참조하십시오.

+
다음 예에서는 로컬 SVM 'pvs1'과 사전 승인된 원격 SVM 'VS1' 간에 피어 관계를 생성합니다.

+
[listing]
----
cluster01::> vserver peer create -vserver pvs1 -peer-vserver vs1
----
. SVM 피어 관계 확인:
+
'vserver peer show'

+
[listing]
----
cluster01::> vserver peer show
            Peer        Peer                           Peering        Remote
Vserver     Vserver     State        Peer Cluster      Applications   Vserver
----------- ----------- ------------ ----------------- -------------- ---------
pvs1        vs1         peered       cluster02         snapmirror     vs1
----

