---
permalink: peering/peering-basics-concept.html 
sidebar: sidebar 
keywords: peer, basics 
summary: '피어 관계의 클러스터와 SVM은 인터클러스터 논리 인터페이스(LIF)를 사용하여 인터클러스터 네트워크를 통해 통신합니다. 인터클러스터 LIF는 '인터클러스터 코어' 네트워크 인터페이스 서비스를 지원하는 LIF로, 일반적으로 '기본 인터클러스터' 네트워크 인터페이스 서비스 정책을 사용하여 만들어집니다. 피어링된 클러스터의 모든 노드에 대한 인터클러스터 LIF를 생성해야 합니다.' 
---
= 피어링 기본
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapMirror를 사용하여 스냅샷 복사본을 복제하려면 먼저 소스 및 타겟 클러스터 간에, 소스 및 타겟 SVM 간에 _피어 관계_를 생성해야 합니다. 피어 관계는 클러스터와 SVM이 데이터를 안전하게 교환할 수 있도록 네트워크 연결을 정의합니다.

피어 관계의 클러스터와 SVM은 _인터클러스터 논리 인터페이스(LIF)를 사용하여 인터클러스터 네트워크를 통해 통신합니다. _ 인터클러스터 LIF는 일반적으로 "기본 인터클러스터 코어" 네트워크 인터페이스 서비스 정책을 사용하여 생성되는 LIF입니다. 피어링된 클러스터의 모든 노드에 대한 인터클러스터 LIF를 생성해야 합니다.

인터클러스터 LIF는 해당 LIF가 할당된 시스템 SVM에 속하는 경로를 사용합니다. ONTAP에서 IPspace 내에서 클러스터 레벨 통신을 위한 시스템 SVM을 자동으로 생성합니다.

팬아웃 및 캐스케이드 토폴로지가 모두 지원됩니다. 계단식 토폴로지에서는 1차 클러스터와 2차 클러스터 간에 그리고 2차 클러스터와 3차 클러스터 간에 인터클러스터 네트워크만 만들어야 합니다. 1차 클러스터와 3차 클러스터 간에 인터클러스터 네트워크를 생성할 필요가 없습니다.

[NOTE]
====
관리자가 기본 인터클러스터 서비스 정책에서 인터클러스터 코어 서비스를 제거할 수 있지만 권장하지는 않습니다. 이 경우 "default-인터클러스터"를 사용하여 만든 LIF는 실제로 인터클러스터 LIF가 아닙니다. 기본 인터클러스터 서비스 정책에 인터클러스터 코어 서비스가 포함되어 있는지 확인하려면 다음 명령을 사용합니다.

네트워크 인터페이스 서비스 정책 표시 정책 기본값 - 인터클러스터

====