---
permalink: peering/prerequisites-cluster-peering-reference.html 
sidebar: sidebar 
keywords: prerequisites, cluster, peering. connectivity, requirements, port, firewall 
summary: 클러스터 피어링을 설정하기 전에 연결, 포트, IP 주소, 서브넷, 방화벽, 클러스터 명명 요구사항이 충족됩니다. 
---
= 클러스터 피어링을 위한 사전 요구사항
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
클러스터 피어링을 설정하기 전에 연결, 포트, IP 주소, 서브넷, 방화벽, 클러스터 명명 요구사항이 충족됩니다.



== 연결 요구 사항

로컬 클러스터의 모든 인터클러스터 LIF는 원격 클러스터의 모든 인터클러스터 LIF와 통신할 수 있어야 합니다.

반드시 필요한 것은 아니지만 일반적으로 동일한 서브넷에 있는 인터클러스터 LIF에 사용되는 IP 주소를 구성하는 것이 더 간단합니다. IP 주소는 데이터 LIF와 동일한 서브넷 또는 다른 서브넷에 상주할 수 있습니다. 각 클러스터에 사용되는 서브넷은 다음 요구사항을 충족해야 합니다.

* 서브넷은 인터클러스터 통신에 사용되는 포트를 포함하는 브로드캐스트 도메인에 속해야 합니다.
* 서브넷에는 노드당 하나의 인터클러스터 LIF에 할당할 수 있는 충분한 IP 주소가 있어야 합니다.
+
예를 들어, 4노드 클러스터에서 인터클러스터 통신에 사용되는 서브넷에는 사용 가능한 IP 주소 4개가 있어야 합니다. 각 노드에는 인터클러스터 네트워크의 IP 주소를 사용하는 인터클러스터 LIF가 있어야 합니다.



인터클러스터 LIF는 IPv4 주소 또는 IPv6 주소를 가질 수 있습니다.

[NOTE]
====
ONTAP 9를 사용하면 두 프로토콜을 모두 인터클러스터 LIF에 동시에 표시할 수 있도록 선택적으로 허용함으로써 피어링 네트워크를 IPv4에서 IPv6로 마이그레이션할 수 있습니다. 이전 릴리즈에서는 전체 클러스터에 대한 모든 인터클러스터 관계가 IPv4 또는 IPv6였습니다. 이는 프로토콜 변경이 잠재적으로 운영 중단이 발생할 수 있음을 의미합니다.

====


== 포트 요구 사항

인터클러스터 통신에 전용 포트를 사용하거나 데이터 네트워크에서 사용하는 포트를 공유할 수 있습니다. 포트는 다음 요구 사항을 충족해야 합니다.

* 지정된 원격 클러스터와 통신하는 데 사용되는 모든 포트는 동일한 IPspace에 있어야 합니다.
+
여러 클러스터를 사용하여 다른 IPspace를 사용할 수 있습니다. IPspace 내에서만 쌍방향 전체 메시 연결이 필요합니다.

* 인터클러스터 통신에 사용되는 브로드캐스트 도메인에는 한 포트에서 다른 포트로 인터클러스터 통신이 페일오버할 수 있도록 노드당 두 개 이상의 포트가 포함되어야 합니다.
+
브로드캐스트 도메인에 추가된 포트는 물리적 네트워크 포트, VLAN 또는 인터페이스 그룹(ifgrp)일 수 있습니다.

* 모든 포트는 케이블로 연결되어야 합니다.
* 모든 포트가 정상 상태여야 합니다.
* 포트의 MTU 설정이 일치해야 합니다.




== 방화벽 요구 사항

방화벽과 인터클러스터 방화벽 정책은 다음 프로토콜을 허용해야 합니다.

* ICMP 서비스
* TCP - 포트 10000, 11104 및 11105를 통해 모든 인터클러스터 LIF의 IP 주소에 연결
* 인터클러스터 LIF 간 양방향 HTTPS
+
CLI를 사용하여 클러스터 피어링을 설정할 때는 HTTPS가 필요하지 않지만 나중에 System Manager를 사용하여 데이터 보호를 구성하면 HTTPS가 필요합니다.



기본 '인터클러스터' 방화벽 정책은 HTTPS 프로토콜을 통해 모든 IP 주소(0.0.0.0/0)에서 액세스할 수 있도록 합니다. 필요한 경우 정책을 수정하거나 대체할 수 있습니다.


NOTE: ONTAP 9.10.1.1부터 방화벽 정책이 사용되지 않으며 LIF 서비스 정책으로 완전히 대체됩니다. 자세한 내용은 을 참조하십시오 link:../networking/configure_firewall_policies_for_lifs.html["LIF의 방화벽 정책을 구성합니다"].



== 클러스터 요구사항

클러스터는 다음 요구사항을 충족해야 합니다.

* 클러스터는 255개 이상의 클러스터와 피어 관계에 있을 수 없습니다.

