---
permalink: peering/shared-dedicated-ports-intercluster-concept.html 
sidebar: sidebar 
keywords: use, shared, dedicated, ports, network, bandwidth, replication, interval, availability 
summary: 인터클러스터 통신에 전용 포트를 사용하거나 데이터 네트워크에서 사용하는 포트를 공유할 수 있습니다. 포트 공유 여부를 결정할 때는 네트워크 대역폭, 복제 간격 및 포트 가용성을 고려해야 합니다. 
---
= 공유 또는 전용 포트를 사용합니다
:icons: font
:imagesdir: ../media/


[role="lead"]
인터클러스터 통신에 전용 포트를 사용하거나 데이터 네트워크에서 사용하는 포트를 공유할 수 있습니다. 포트 공유 여부를 결정할 때는 네트워크 대역폭, 복제 간격 및 포트 가용성을 고려해야 합니다.

[NOTE]
====
다른 피어링된 클러스터 중 전용 포트를 사용하여 포트 하나를 공유할 수 있습니다.

====


== 네트워크 대역폭

10GbE 같은 고속 네트워크가 있는 경우 데이터 액세스에 사용되는 것과 동일한 10GbE 포트를 사용하여 복제를 수행할 수 있는 충분한 로컬 LAN 대역폭이 있을 수 있습니다.

또한 사용 가능한 WAN 대역폭을 LAN 대역폭과 비교해야 합니다. 사용 가능한 WAN 대역폭이 10GbE보다 훨씬 작은 경우 전용 포트를 사용해야 할 수 있습니다.

[TIP]
====
이 규칙의 한 가지 예외는 클러스터의 전체 또는 여러 노드에서 데이터를 복제하는 경우입니다. 이 경우 대역폭 사용률을 일반적으로 노드 전체에 분산합니다.

====
전용 포트를 사용하지 않는 경우 복제 네트워크의 MTU(Maximum Transmission Unit) 크기는 일반적으로 데이터 네트워크의 MTU 크기와 같아야 합니다.



== 복제 간격입니다

사용량이 적은 시간에 복제가 수행되면 10GbE LAN 연결이 없어도 복제에 데이터 포트를 사용할 수 있습니다.

정상 업무 시간 중에 복제가 수행되는 경우 복제할 데이터의 양과 데이터 프로토콜 경합을 유발할 수 있는 대역폭이 너무 많이 필요한지 여부를 고려해야 합니다. 데이터 프로토콜(SMB, NFS, iSCSI)의 네트워크 활용률이 50%를 넘는 경우, 노드 페일오버가 발생할 경우 성능이 저하되지 않도록 인터클러스터 통신에 전용 포트를 사용해야 합니다.



== 포트 가용성

복제 트래픽이 데이터 트래픽을 방해한다고 판단할 경우 인터클러스터 LIF를 동일한 노드의 다른 인터클러스터 지원 공유 포트로 마이그레이션할 수 있습니다.

복제에 VLAN 포트를 전용으로 지정할 수도 있습니다. 포트의 대역폭은 모든 VLAN과 기본 포트 간에 공유됩니다.
