---
permalink: san-admin/access-read-only-lun-copy-backup-vault-task.html 
sidebar: sidebar 
keywords: access, read-only, lun, copy, snapvault, backup 
summary: SnapVault 백업의 최신 스냅샷 복사본에서 LUN의 읽기 전용 복사본에 액세스할 수 있습니다. LUN ID, 경로 및 일련 번호는 소스 LUN과 다르며 먼저 매핑해야 합니다. 영구 예약, LUN 매핑 및 igroup은 SnapVault 2차 볼륨에 복제되지 않습니다. 
---
= SnapVault 백업에서 읽기 전용 LUN 복사본을 액세스합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapVault 백업의 최신 스냅샷 복사본에서 LUN의 읽기 전용 복사본에 액세스할 수 있습니다. LUN ID, 경로 및 일련 번호는 소스 LUN과 다르며 먼저 매핑해야 합니다. 영구 예약, LUN 매핑 및 igroup은 SnapVault 2차 볼륨에 복제되지 않습니다.

.필요한 것
* SnapVault 관계를 초기화해야 하며 SnapVault 2차 볼륨의 최신 스냅샷 복사본에 원하는 LUN을 포함해야 합니다.
* SnapVault 백업을 포함하는 SVM(스토리지 가상 머신)에는 LUN 복사본에 액세스하는 데 사용되는 호스트에서 액세스할 수 있는 원하는 SAN 프로토콜을 갖춘 하나 이상의 LIF가 있어야 합니다.
* SnapVault 2차 볼륨에서 LUN 복사본에 직접 액세스할 계획이라면 미리 SnapVault SVM에 igroup을 생성해야 합니다.
+
먼저 LUN이 포함된 볼륨을 복원하거나 클론 복제하지 않고도 SnapVault 2차 볼륨에서 LUN에 직접 액세스할 수 있습니다.



.이 작업에 대해
이전 스냅샷 복사본에서 매핑된 LUN이 있는 동안 새 스냅샷 복사본이 SnapVault 보조 볼륨에 추가되면 매핑된 LUN의 콘텐츠가 변경됩니다. LUN은 여전히 같은 식별자를 사용하여 매핑되지만 새 스냅샷 복사본에서 데이터를 가져옵니다. LUN 크기가 변경되면 일부 호스트는 자동으로 크기 변경을 감지합니다. 크기 변경을 확인하려면 Windows 호스트에서 디스크를 재검색해야 합니다.

.단계
. 'lun show' 명령을 실행하여 SnapVault 보조 볼륨에서 사용 가능한 LUN을 나열합니다.
+
이 예에서는 운영 볼륨의 원래 LUN과 SnapVault 보조 볼륨 dstvolB의 복제본을 모두 볼 수 있습니다.

+
[listing]
----
cluster::> lun show

Vserver   Path                State   Mapped   Type          Size
--------  ------------------  ------  -------  --------      -------
vserverA  /vol/srcvolA/lun_A  online  mapped   windows  300.0GB
vserverA  /vol/srcvolA/lun_B  online  mapped   windows  300.0GB
vserverA  /vol/srcvolA/lun_C  online  mapped   windows  300.0GB
vserverB  /vol/dstvolB/lun_A  online  unmapped windows  300.0GB
vserverB  /vol/dstvolB/lun_B  online  unmapped windows  300.0GB
vserverB  /vol/dstvolB/lun_C  online  unmapped windows  300.0GB

6 entries were displayed.
----
. 원하는 호스트에 대한 igroup이 SnapVault 2차 볼륨을 포함하는 SVM에 이미 없으면 "igroup create" 명령을 실행하여 igroup을 생성합니다.
+
이 명령은 iSCSI 프로토콜을 사용하는 Windows 호스트에 대한 igroup을 생성합니다.

+
[listing]
----
cluster::> igroup create -vserver vserverB -igroup temp_igroup
  -protocol iscsi -ostype windows
  -initiator iqn.1991-05.com.microsoft:hostA
----
. 'lun mapping create' 명령을 실행하여 원하는 LUN 복사본을 igroup에 매핑합니다.
+
[listing]
----
cluster::> lun mapping create -vserver vserverB -path /vol/dstvolB/lun_A
  -igroup temp_igroup
----
. 호스트를 LUN에 연결하고 필요에 따라 LUN의 컨텐츠를 액세스합니다.

