---
permalink: san-admin/asa-iscsi-lif-fo-task.html 
sidebar: sidebar 
keywords: failover, iscsi, all san array, cli, system manager, auto-revert, revert network interface 
summary: ONTAP 9.11.1 이상으로 업그레이드한 후에는 ONTAP 9.10.1 이전 버전에서 생성된 모든 iSCSI LIF에서 자동 LIF 페일오버를 수동으로 사용하도록 설정해야 합니다. 
---
= 자동 iSCSI LIF 페일오버를 사용 또는 사용하지 않도록 설정합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9.11.1 이상으로 업그레이드한 후에는 ONTAP 9.10.1 이전 버전에서 생성된 모든 iSCSI LIF에서 자동 LIF 페일오버를 수동으로 사용하도록 설정해야 합니다.

ONTAP 9.11.1부터 All-Flash SAN 어레이 플랫폼에서 iSCSI LIF에 대한 자동 LIF 페일오버를 활성화할 수 있습니다. 스토리지 페일오버가 발생하는 경우 iSCSI LIF가 홈 노드나 포트에서 HA 파트너 노드 또는 포트로 자동으로 마이그레이션된 다음, 페일오버가 완료되면 다시 뒤로 마이그레이션됩니다.  또는 iSCSI LIF의 포트가 정상 상태가 아닐 경우 LIF는 자동으로 현재 홈 노드의 정상 포트로 마이그레이션된 다음, 포트가 다시 정상 상태가 되면 원래 포트로 다시 돌아갑니다.  를 사용하면 iSCSI에서 실행되는 SAN 워크로드가 페일오버가 발생한 후 I/O 서비스를 더 빠르게 재개할 수 있습니다.

ONTAP 9.11.1 이상에서는 기본적으로 새로 생성된 iSCSI LIF가 다음 조건 중 하나에 해당할 경우 자동 LIF 페일오버에 사용하도록 설정됩니다.

* SVM에 iSCSI LIF가 없습니다
* SVM의 모든 iSCSI LIF는 자동 LIF 페일오버에 사용할 수 있습니다




== 자동 iSCSI LIF 페일오버를 사용합니다

기본적으로 ONTAP 9.10.1 이전 버전에서 생성된 iSCSI LIF는 자동 LIF 페일오버에 사용되지 않습니다.  자동 LIF 페일오버에 사용되지 않는 SVM에 iSCSI LIF가 있으면 새로 생성한 LIF가 자동 LIF 페일오버 중에 사용할 수 없습니다.  자동 LIF 페일오버가 사용되도록 설정되어 있지 않고 페일오버 이벤트가 발생하면 iSCSI LIF가 마이그레이션되지 않습니다.

에 대해 자세히 알아보십시오 link:../networking/configure_lifs_@cluster_administrators_only@_overview.html#lif-failover-and-giveback["LIF 페일오버 및 반환"].

.단계
. iSCSI LIF에 대해 자동 페일오버 활성화:
+
[source, cli]
----
network interface modify -vserver <SVM_name> -lif <iscsi_lif> -failover-policy sfo-partner-only -auto-revert true
----
+
SVM에서 모든 iSCSI LIF를 업데이트하려면 를 사용하십시오 `-lif*` 대신 `lif`.





== 자동 iSCSI LIF 페일오버를 해제합니다

이전에 ONTAP 9.10.1 이하 버전에서 생성된 iSCSI LIF에서 자동 iSCSI LIF 페일오버를 사용하도록 설정한 경우 이 기능을 사용하지 않도록 설정할 수 있습니다.

.단계
. iSCSI LIF에 대한 자동 페일오버 비활성화:
+
[source, cli]
----
network interface modify -vserver <SVM_name> -lif <iscsi_lif> -failover-policy disabled -auto-revert false
----
+
SVM에서 모든 iSCSI LIF를 업데이트하려면 를 사용하십시오 `-lif*` 대신 `lif`.



.관련 정보
* link:../networking/create_a_lif.html["LIF를 생성합니다"]
* 수동 link:../networking/migrate_a_lif.html["LIF를 마이그레이션합니다"]
* 수동 link:../networking/revert_a_lif_to_its_home_port.html["LIF를 홈 포트로 되돌립니다"]
* link:../networking/configure_failover_settings_on_a_lif.html["LIF에서 페일오버 설정을 구성합니다"]

