---
permalink: san-admin/chap-authentication-concept.html 
sidebar: sidebar 
keywords: what, chap, authentication, challenge handshake authentication protocol 
summary: 'CHAP(Challenge Handshake Authentication Protocol)는 iSCSI 이니시에이터와 타겟 간의 인증된 통신을 활성화합니다. CHAP 인증을 사용하는 경우 이니시에이터와 스토리지 시스템 모두에서 CHAP 사용자 이름 및 암호를 정의합니다.' 
---
= CHAP 인증입니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
CHAP(Challenge Handshake Authentication Protocol)는 iSCSI 이니시에이터와 타겟 간의 인증된 통신을 활성화합니다. CHAP 인증을 사용하는 경우 이니시에이터와 스토리지 시스템 모두에서 CHAP 사용자 이름 및 암호를 정의합니다.

iSCSI 세션의 초기 단계 중에 이니시에이터는 스토리지 시스템에 로그인 요청을 보내 세션을 시작합니다. 로그인 요청에는 이니시에이터의 CHAP 사용자 이름 및 CHAP 알고리즘이 포함됩니다. 스토리지 시스템이 CHAP 챌린지에 응답합니다. 이니시에이터는 CHAP 응답을 제공합니다. 스토리지 시스템에서 응답을 확인하고 이니시에이터를 인증합니다. CHAP 암호는 응답을 계산하는 데 사용됩니다.



== CHAP 인증 사용에 대한 지침입니다

CHAP 인증을 사용할 때는 특정 지침을 따라야 합니다.

* 스토리지 시스템에서 인바운드 사용자 이름과 암호를 정의하는 경우 이니시에이터에서 아웃바운드 CHAP 설정에 동일한 사용자 이름과 암호를 사용해야 합니다. 양방향 인증을 사용하도록 스토리지 시스템에 아웃바운드 사용자 이름과 암호도 정의한 경우, 이니시에이터에서 인바운드 CHAP 설정에 동일한 사용자 이름과 암호를 사용해야 합니다.
* 스토리지 시스템의 인바운드 및 아웃바운드 설정에 동일한 사용자 이름과 암호를 사용할 수 없습니다.
* CHAP 사용자 이름은 1 ~ 128바이트일 수 있습니다.
+
null 사용자 이름은 허용되지 않습니다.

* CHAP 암호(암호)는 1 ~ 512바이트입니다.
+
암호는 16진수 값 또는 문자열일 수 있습니다. 16진수 값의 경우 접두사 "0x" 또는 "0x"로 값을 입력해야 합니다. null 암호는 허용되지 않습니다.

* 추가 제한 사항은 이니시에이터의 설명서를 참조하십시오.
+
예를 들어, Microsoft iSCSI 소프트웨어 초기자는 IPsec 암호화가 사용되지 않는 경우 초기자 및 대상 CHAP 암호를 모두 12바이트 이상 필요로 합니다. 최대 암호 길이는 IPsec의 사용 여부에 관계없이 16바이트입니다.


