---
permalink: san-admin/configure-svm-fc-task.html 
sidebar: sidebar 
keywords: configure, svm, for fc 
summary: 'FC용 SVM(Storage Virtual Machine)을 구성하려면 SVM용 LIF를 생성하고 이러한 LIF에 FC 프로토콜을 할당해야 합니다.' 
---
= FC용 SVM 구성
:icons: font
:imagesdir: ../media/


[role="lead"]
FC용 SVM(Storage Virtual Machine)을 구성하려면 SVM용 LIF를 생성하고 이러한 LIF에 FC 프로토콜을 할당해야 합니다.

FC 라이센스가 있어야 하며 활성화해야 합니다. FC 라이센스가 설정되어 있지 않으면 LIF 및 SVM이 온라인 상태로 표시되지만 운영 상태는 'down'입니다. LIF 및 SVM이 작동할 수 있도록 FC 서비스를 설정해야 합니다. SVM의 모든 FC LIF에서 이니시에이터를 호스팅하려면 단일 이니시에이터 조닝을 사용해야 합니다.

NetApp은 각 SVM에서 FC 프로토콜을 통해 데이터를 제공하는 FC LIF를 노드당 1개 이상 지원합니다. 노드당 LIF 2개와 Fabric 2개를 사용해야 하며, 연결된 노드당 LIF 1개가 있어야 합니다. 이는 노드 계층과 패브릭에서 이중화를 제공합니다.

.단계
. SVM에서 FC 서비스 활성화:
+
'vserver fcp create-vserver_vserver_name_-status-admin up'

. FC를 지원하는 각 노드에서 SVM에 대해 2개의 LIF를 생성합니다.
+
'network interface create-vserver_vserver_name_-lif_lif_name_-role data-protocol fcp-home-node_node_name_-home-port_port_'

+
role 매개 변수는 data로, data-protocol 매개 변수는 fcp로 지정해야 합니다.

. LIF가 생성되었으며 운영 상태가 '온라인'인지 확인합니다.
+
'network interface show -vserver_vserver_name__lif_name_'



https://mysupport.netapp.com/site/global/dashboard["NetApp 지원"]

https://mysupport.netapp.com/matrix["NetApp 상호 운용성 매트릭스 툴"]

xref:life-cluster-concept.adoc[클러스터 SAN 환경의 LIF 고려 사항]
