---
permalink: san-admin/configure-fc-adapters-task.html 
sidebar: sidebar 
keywords: configure, fc, adapters, target, initiator, mode 
summary: 각 온보드 FC 포트는 이니시에이터 또는 타겟으로 개별적으로 구성할 수 있습니다. 특정 FC 어댑터의 포트는 온보드 FC 포트와 마찬가지로 타겟 포트 또는 이니시에이터 포트로 개별적으로 구성할 수도 있습니다. 
---
= FC 어댑터를 구성합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
각 온보드 FC 포트는 이니시에이터 또는 타겟으로 개별적으로 구성할 수 있습니다. 특정 FC 어댑터의 포트는 온보드 FC 포트와 마찬가지로 타겟 포트 또는 이니시에이터 포트로 개별적으로 구성할 수도 있습니다. 대상 모드에 대해 구성할 수 있는 어댑터 목록은 에서 확인할 수 있습니다 link:https://hwu.netapp.com["NetApp Hardware Universe를 참조하십시오"^].

타겟 모드는 포트를 FC 이니시에이터에 연결하는 데 사용됩니다. 이니시에이터 모드는 FlexArray 가상화 또는 FLI(Foreign LUN Import)를 사용하여 포트를 테이프 드라이브, 테이프 라이브러리 또는 타사 스토리지에 연결하는 데 사용됩니다.

FC 프로토콜과 FC-NVMe 프로토콜을 위해 FC 어댑터를 구성할 때도 동일한 단계가 사용됩니다. 하지만 특정 FC 어댑터만 FC-NVMe를 지원합니다. 를 참조하십시오 link:https://hwu.netapp.com["NetApp Hardware Universe를 참조하십시오"^] FC-NVMe 프로토콜을 지원하는 어댑터 목록을 확인하십시오.



== FC 어댑터를 타겟 모드로 구성합니다

.단계
. 어댑터를 오프라인 상태로 전환:
+
'node run-node_node_name_storage disable adapter_adapter_name_'

+
어댑터가 오프라인 상태가 되지 않으면 시스템의 해당 어댑터 포트에서 케이블을 분리할 수도 있습니다.

. 어댑터를 이니시에이터에서 타겟으로 변경합니다.
+
'system hardware unified-connect modify -t target-node_node_name_adapter_adapter_name_'

. 변경한 어댑터를 호스팅하는 노드를 재부팅합니다.
. 타겟 포트의 구성이 올바른지 확인합니다.
+
'network fcp adapter show-node_name _'

. 어댑터를 온라인으로 전환합니다.
+
'network fcp adapter modify -node_node_name_-adapter_adapter_port_-state up





== 이니시에이터 모드에 맞게 FC 어댑터를 구성합니다

.필요한 것
* 어댑터에 있는 LIF는 해당 LIF가 구성원인 포트 세트에서 제거해야 합니다.
* 물리적 포트의 속성을 타겟에서 이니시에이터로 변경하기 전에 수정할 물리적 포트를 사용하는 모든 SVM(스토리지 가상 머신)의 모든 LIF를 마이그레이션 또는 제거해야 합니다.


[NOTE]
====
NVMe/FC는 이니시에이터 모드를 지원합니다.

====
.단계
. 어댑터에서 모든 LIF를 제거합니다.
+
'네트워크 인터페이스 삭제 - vserver_SVM_name_-lif_LIF_name, LIF_name_'

. 어댑터를 오프라인 상태로 전환:
+
'network fcp adapter modify -node_node_name_-adapter_adapter_port_-status-admin down'

+
어댑터가 오프라인 상태가 되지 않으면 시스템의 해당 어댑터 포트에서 케이블을 분리할 수도 있습니다.

. 어댑터를 타겟에서 이니시에이터로 변경합니다.
+
'System hardware unified-connect modify -t initiator_adapter_port_

. 변경한 어댑터를 호스팅하는 노드를 재부팅합니다.
. FC 포트가 구성에 맞는 올바른 상태로 구성되었는지 확인합니다.
+
'시스템 하드웨어 통합 접속 쇼

. 어댑터를 다시 온라인으로 전환합니다.
+
'node run-node_node_name_storage enable adapter_adapter_port_'


