---
permalink: san-admin/configure-return-fqdn-host-iscsi-discovery-task.html 
sidebar: sidebar 
keywords: configure, iscsi, lifs, return, fqdn, host, sendtargets discovery operation 
summary: 'ONTAP 9부터 호스트 OS가 iSCSI SendTargets 검색 작업을 전송할 때 FQDN(정규화된 도메인 이름)을 반환하도록 iSCSI LIF를 구성할 수 있습니다. FQDN은 호스트 OS와 스토리지 서비스 사이에 NAT(Network Address Translation) 디바이스가 있는 경우에 유용합니다.' 
---
= 호스트 iSCSI SendTargets 검색 작업에 FQDN을 반환하도록 iSCSI LIF를 구성합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9부터 호스트 OS가 iSCSI SendTargets 검색 작업을 전송할 때 FQDN(정규화된 도메인 이름)을 반환하도록 iSCSI LIF를 구성할 수 있습니다. FQDN은 호스트 OS와 스토리지 서비스 사이에 NAT(Network Address Translation) 디바이스가 있는 경우에 유용합니다.

NAT 장치의 한 쪽에 있는 IP 주소는 다른 쪽에는 의미가 없지만 FQDN은 양쪽에서 의미를 가질 수 있습니다.

[NOTE]
====
FQDN 값 상호 운용성 제한은 모든 호스트 OS에서 128자입니다.

====
.단계
. 권한 설정을 고급으로 변경합니다.
+
세트 프리빌리지 고급

. FQDN을 반환하도록 iSCSI LIF 구성:
+
"vserver iSCSI interface modify -vserver_SVM_name_-lif_iscsi_LIF_name_-SendTargets_FQDN"

+
다음 예에서는 iSCSI LIF가 storagehost-005.example.com 를 FQDN으로 반환하도록 구성되어 있습니다.

+
'vserver iscsi interface modify -vserver vs1 -lif vs1_iSCSI1-SendTargets-FQDN storagehost-005.example.com'

. SendTargets가 FQDN인지 확인합니다.
+
'vserver iscsi interface show -vserver_SVM_name_-fields SendTargets-FQDN'

+
이 예제에서 storagehost-005.example.com 은 SendTargets-FQDN 출력 필드에 표시됩니다.

+
[listing]
----
cluster::vserver*> vserver iscsi interface show -vserver vs1 -fields sendtargets-fqdn
vserver lif        sendtargets-fqdn
------- ---------- ---------------------------
vs1     vs1_iscsi1 storagehost-005.example.com
vs1     vs1_iscsi2 storagehost-006.example.com
----


http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-cmpr/GUID-5CB10C70-AC11-41C0-8C16-B4D0DF916E9B.html["ONTAP 9 명령"]
