---
permalink: san-admin/configure-fc-adapters-target-mode-task.html 
sidebar: sidebar 
keywords: configure, fc, adapters, target mode 
summary: 온보드 어댑터의 개별 FC 포트와 대상 모드의 특정 FC 어댑터 카드를 구성할 수 있습니다. 타겟 모드는 포트를 FC 이니시에이터에 연결하는 데 사용됩니다. 
---
= FC 어댑터를 타겟 모드로 구성합니다
:icons: font
:imagesdir: ../media/


[role="lead"]
온보드 어댑터의 개별 FC 포트와 대상 모드의 특정 FC 어댑터 카드를 구성할 수 있습니다. 타겟 모드는 포트를 FC 이니시에이터에 연결하는 데 사용됩니다.

각 온보드 FC 포트는 이니시에이터 또는 타겟으로 개별적으로 구성할 수 있습니다. 특정 FC 어댑터의 포트는 온보드 FC 포트와 마찬가지로 타겟 포트 또는 이니시에이터 포트로 개별적으로 구성할 수도 있습니다. 대상 모드에 대해 구성할 수 있는 어댑터 목록은 _Hardware Universe_에서 확인할 수 있습니다.

FC 프로토콜과 FC-NVMe 프로토콜을 위해 FC 어댑터를 구성할 때도 동일한 단계가 사용됩니다. 하지만 특정 FC 어댑터만 FC-NVMe를 지원합니다. FC-NVMe 프로토콜을 지원하는 어댑터 목록은 _Hardware Universe_를 참조하십시오.

.단계
. 어댑터를 오프라인 상태로 전환:
+
'node run-node_node_name_storage disable adapter-d_adapter_port_'

+
어댑터가 오프라인 상태가 되지 않으면 시스템의 해당 어댑터 포트에서 케이블을 분리할 수도 있습니다.

. 어댑터를 이니시에이터에서 타겟으로 변경합니다.
+
'System hardware unified-connect modify -t target_adapter_port_

. 변경한 어댑터를 호스팅하는 노드를 재부팅합니다.
. 타겟 포트의 구성이 올바른지 확인합니다.
+
'network fcp adapter show-node_name _'

. 어댑터를 온라인으로 전환합니다.
+
'network fcp adapter modify -node_node_name_-adapter_adapter_port_-state up



https://hwu.netapp.com["NetApp Hardware Universe를 참조하십시오"]
