---
permalink: san-admin/configure-svm-nvme-task.html 
sidebar: sidebar 
keywords: configure, svm, nvme 
summary: 노드에서 NVMe 프로토콜을 사용하려면 NVMe용으로 특수 SVM을 구성해야 합니다. 
---
= NVMe를 위한 SVM 구성
:icons: font
:imagesdir: ../media/


[role="lead"]
노드에서 NVMe 프로토콜을 사용하려면 NVMe용으로 특수 SVM을 구성해야 합니다.

FC 또는 이더넷 어댑터는 NVMe를 지원해야 합니다. 지원되는 어댑터가 에 나열되어 있습니다 https://hwu.netapp.com["NetApp Hardware Universe를 참조하십시오"^].

.단계
. 기존 SVM을 사용하지 않으려면 다음을 생성합니다.
+
'vserver create-vserver_SVM_name_'

+
.. SVM이 생성되었는지 확인:
+
'vserver show'



. 클러스터에 NVMe 또는 TCP 가능 어댑터가 설치되어 있는지 확인합니다.
+
NVMe의 경우: 'network fcp adapter show-data-protocols-supported fc-NVMe'

+
TCP의 경우 'network port show'

. ONTAP 9.7 이하를 실행 중인 경우 SVM에서 프로토콜을 모두 제거하십시오.
+
'vserver remove-protocols-vserver_SVM_name_-protocols iSCSI, FCP, NFS, CIFS, NDMP'

+
ONTAP 9.8부터는 NVMe를 추가할 때 다른 프로토콜을 제거할 필요가 없습니다.

. SVM에 NVMe 프로토콜을 추가합니다.
+
'vserver add-protocols-vserver_SVM_name_-protocols NVMe'

. ONTAP 9.7 이하를 실행 중인 경우, NVMe가 SVM에서 허용되는 유일한 프로토콜인지 확인하십시오.
+
'vserver show -vserver_SVM_name_-fields Allowed-protocols'

+
NVMe는 허용된 프로토콜 칼럼 아래에 표시되는 유일한 프로토콜이어야 합니다.

. NVMe 서비스를 생성합니다.
+
'vserver NVMe create-vserver_SVM_name_'

. NVMe 서비스가 생성되었는지 확인하십시오.
+
'vserver NVMe show -vserver_SVM_name _'

+
SVM의 관리 상태는 Up으로 표시되어야 합니다.

. NVMe/FC LIF 생성:
+
[cols="3*"]
|===
| ONTAP 버전입니다 | 적용 가능한 프로토콜 | 명령 


 a| 
ONTAP 9.9.1 이하
 a| 
FC
 a| 
'network interface create-vserver SVM_name-lif lif_name-role data-protocol fc-NVMe-home-node home_node-home-port home_port'



 a| 
ONTAP 9.10.1
 a| 
FC 또는 TCP입니다
 a| 
'network interface create-vserver SVM_name-lif lif_name-service-policy{default-data-NVMe-tcp|default-data-NVMe-fc}-home-node home_node-home-port home_port-status admin up-failover-policy disabled-firewall-failover false-failover-group-is-dns-update-false

|===
. HA 파트너 노드에 NVMe/FC LIF 생성:
+
[cols="3*"]
|===
| ONTAP 버전입니다 | 적용 가능한 프로토콜 | 명령 


 a| 
ONTAP 9.9.1 이하
 a| 
FC
 a| 
'network interface create -vserver_SVM_name_-lif_lif_name_-role data-protocol fc-NVMe-HOME-node_home_node_-home-port_port_'



 a| 
ONTAP 9.10.1 이상
 a| 
FC 또는 TCP입니다
 a| 
'network interface create-vserver SVM_name-lif lif_name-service-policy{default-data-NVMe-tcp|default-data-NVMe-fc}-home-node home_node-home-port home_port-status admin up-failover-policy disabled-firewall-failover false-failover-group-is-dns-update-false

|===
. NVMe/FC LIF가 생성되었는지 확인:
+
'network interface show -vserver_SVM_name _'

. LIF와 동일한 노드에서 볼륨 생성:
+
'vol create-vserver_SVM_name_-volume_vol_name_-aggregate_aggregate_name_-size_volume_size_'

+
자동 효율성 정책에 대한 경고 메시지가 표시되면 무시해도 됩니다.


