---
permalink: san-admin/copy-luns-concept.html 
sidebar: sidebar 
keywords: considerations, copying, luns 
summary: LUN을 복제할 때 고려해야 할 사항이 있습니다. 
---
= LUN을 복제할 때의 고려 사항
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
LUN을 복제할 때 고려해야 할 사항이 있습니다.

클러스터 관리자는 'lun copy' 명령을 사용하여 클러스터 내의 SVM(스토리지 가상 머신)에서 LUN을 복제할 수 있습니다. 클러스터 관리자는 SVM 간 LUN 복사 작업을 수행하기 전에 'vserver peer create' 명령을 사용하여 SVM(스토리지 가상 시스템) 피어링 관계를 설정해야 합니다. 소스 볼륨에 SIS 클론에 대한 충분한 공간이 있어야 합니다.

스냅샷 복사본의 LUN은 'LUN copy' 명령의 소스 LUN으로 사용할 수 있습니다. 'lun copy' 명령을 사용하여 LUN을 복제하는 경우 LUN 복제본은 읽기 및 쓰기 액세스에 즉시 사용할 수 있습니다. LUN 복제본을 생성해도 소스 LUN은 변경되지 않습니다. 소스 LUN과 LUN 복제본은 모두 LUN 일련 번호가 서로 다른 고유한 LUN으로 존재합니다. 소스 LUN에 대한 변경 내용은 LUN 복제본에 반영되지 않으며 LUN 복제본에 대한 변경 내용은 소스 LUN에 반영되지 않습니다. 소스 LUN의 LUN 매핑은 새 LUN에 복제되지 않으므로 LUN 복제본을 매핑해야 합니다.

Snapshot 복사본을 통한 데이터 보호는 볼륨 레벨에서 발생합니다. 따라서 LUN을 소스 LUN의 볼륨과 다른 볼륨으로 복제하는 경우 대상 LUN은 대상 볼륨의 데이터 보호 체계에 따라 달라집니다. 타겟 볼륨에 대해 설정된 스냅샷 복사본이 없는 경우 LUN 복사본의 스냅샷 복사본이 생성되지 않습니다.

LUN을 복사하는 것은 무중단 운영입니다.

다음 유형의 LUN은 복제할 수 없습니다.

* 파일에서 생성된 LUN입니다
* NVFAIL 상태에 있는 LUN
* 로드 공유 관계에 있는 LUN입니다
* 프로토콜 엔드포인트 클래스 LUN

