---
permalink: san-admin/create-nvme-namespace-subsystem-task.html 
sidebar: sidebar 
keywords: create, nvme, namespace, subsystem 
summary: NVMe 프로토콜을 사용하는 시스템의 경우 하나 이상의 NVMe 네임스페이스 및 서브시스템을 생성해야 합니다. 그런 다음 각 네임스페이스를 NVMe 하위 시스템에 매핑하여 호스트 시스템에서 데이터에 액세스할 수 있습니다. 
---
= NVMe 네임스페이스 및 하위 시스템을 작성합니다
:icons: font
:imagesdir: ../media/


[role="lead"]
NVMe 프로토콜을 사용하는 시스템의 경우 하나 이상의 NVMe 네임스페이스 및 서브시스템을 생성해야 합니다. 그런 다음 각 네임스페이스를 NVMe 하위 시스템에 매핑하여 호스트 시스템에서 데이터에 액세스할 수 있습니다.

SVM은 NVMe용으로 이미 구성되어 있어야 합니다.

.단계
. SVM이 NVMe용으로 구성되었는지 확인합니다.
+
'vserver show -vserver_SVM_name_-fields Allowed-protocols'

+
"NVMe"는 "허용된 프로토콜" 열 아래에 표시되어야 합니다.

. NVMe 네임스페이스를 생성합니다.
+
'vserver NVMe namespace create-vserver_SVM_name_-path_path_-size_of_namespace_-OSType_OS_type_'

. NVMe 하위 시스템을 생성합니다.
+
'vserver NVMe 하위 시스템 create-vserver_SVM_name_-subsystem_name_of_subsystem_-OSType_OS_type_'

. 하위 시스템이 생성되었는지 확인합니다.
+
'vserver NVMe subsystem show -vserver_SVM_name _'

+
NVMe 서브시스템은 Subsystem 열에 표시되어야 한다.





== NVMe 하위 시스템 정보

NVMe 하위 시스템에는 하나 이상의 컨트롤러, 하나 이상의 네임스페이스, 하나 이상의 비휘발성 메모리(NVM) 하위 시스템 포트(FC-NVMe 또는 RDMA 전송 포트), NVM 스토리지 미디어, 컨트롤러와 NVM 스토리지 미디어 간의 인터페이스가 포함됩니다. 컨트롤러 매핑 및 관리를 위해 NVM 하위 시스템은 ONTAP의 가상 서버에 매핑됩니다.

NVMe over Fabric(NVMeoF) 하위 시스템은 FreeBSD 커널에 상주하는 별도의 커널 개체입니다. NVMeoF 서브시스템은 다음 구성 요소와 연결됩니다.

* BCOMKA, FCT 및 VDOM과 같은 SAN 구성 요소
* WAFL
* CM, ASUP, EMS 등의 RAS 구성 요소


NVMeoF 서브시스템이 있는 모든 인터페이스는 ONTAP에 있는 현재 정의 및 패턴을 따릅니다.
