---
permalink: san-admin/create-luns-mapping-igroups-task.html 
sidebar: sidebar 
keywords: create, luns, mapping, igroups 
summary: 'SAN 환경을 구성하려면 LUN을 생성하고 이니시에이터 그룹(igroup)을 생성한 후 LUN을 igroup에 매핑해야 합니다.' 
---
= LUN을 생성하고 igroup에 매핑합니다
:icons: font
:imagesdir: ../media/


[role="lead"]
SAN 환경을 구성하려면 LUN을 생성하고 이니시에이터 그룹(igroup)을 생성한 후 LUN을 igroup에 매핑해야 합니다.

.무엇을 &#8217;필요로 할거야
* 애그리게이트, 볼륨 및 SVM(스토리지 가상 머신)을 생성한 상태여야 합니다.
* FC 또는 iSCSI에서 블록 액세스를 설정해야 합니다.
* 클러스터의 모든 노드에 SAN LIF가 생성되어 있어야 합니다.


LUN을 생성할 때 LUN OS 유형을 지정해야 합니다. LUN의 실제 크기는 LUN의 OS 유형에 따라 약간 다를 수 있습니다. LUN을 생성한 후에는 LUN OS 유형을 수정할 수 없습니다.

각 LUN의 메타데이터는 포함하는 애그리게이트에서 약 64KB의 공간을 필요로 합니다. LUN을 생성할 때 포함하는 애그리게이트에 LUN의 메타데이터를 위한 충분한 공간이 있는지 확인해야 합니다. Aggregate에 LUN의 메타데이터를 위한 충분한 공간이 없을 경우 일부 호스트에서 LUN에 액세스하지 못할 수 있습니다.

ONTAP 9.4 이하 버전에서 필요한 경우 LUN을 원래 크기의 10배까지 늘릴 수 있습니다. 예를 들어 100GB LUN을 생성하는 경우 해당 LUN을 1,000GB로 확장할 수 있습니다. 최대 LUN 크기인 16TB를 초과할 수 없습니다. 이 제한은 ONTAP 9.5 이상에는 적용되지 않습니다.

[NOTE]
====
LUN의 실제 최대 크기가 정확히 16TB가 아닐 수 있습니다. ONTAP는 한계치를 약간 낮추어 줍니다.

====
ALUA(Asymmetric Logical Unit Access)는 LUN 생성 중에 항상 사용하도록 설정됩니다. ALUA 설정은 변경할 수 없습니다.

.단계
. LUN 생성:
+
'lun create - vserver vserver_name - volume_volume_name_-lun_lun_name_-size_lun_size_-OSType_lun_OSType_-space-reserve enabled|disabled'

+
LUN 이름은 255자를 초과할 수 없으며 공백을 포함할 수 없습니다.

+
호스트 운영 체제가 Windows 2008 이상인 경우 Windows_2008 OSType을 사용하십시오. '예약 속도' 옵션은 기본적으로 활성화되어 있습니다. 공간이 예약되지 않은 LUN을 사용하려면 '예약 속도' 옵션을 '사용 안 함'으로 설정해야 합니다.

+
[NOTE]
====
NVFAIL 옵션은 볼륨에 LUN이 생성될 때 자동으로 활성화됩니다.

====
. Igroup 생성:
+
'igroup create-vserver_vserver_name_-igroup_name_-protocol fcp|iscsi|mixed-OSType_lun_OSType_-initiator_initiator_name_'

+
호스트 운영 체제가 Windows 2008 이상인 경우 Windows_2008 OSType을 사용하십시오.

. LUN을 igroup에 매핑:
+
'LUN 매핑 create-vserver_vserver_name_-volume_volume_name_-lun_lun_name_-igroup_igroup_name_'

. LUN이 올바르게 구성되었는지 확인합니다.
+
'lun show -vserver_vserver_name _'



link:../disks-aggregates/index.html["디스크 및 애그리게이트 관리"]

link:../volumes/index.html["논리적 스토리지 관리"]

link:../networking/index.html["네트워크 관리"]
