---
permalink: san-admin/enable-space-allocation-scsi-thin-provisioned-luns-task.html 
sidebar: sidebar 
keywords: enable, space, allocation, scsi, thinly, provisioned luns 
summary: 공간 할당 옵션을 Enabled로 설정하면 ONTAP는 볼륨에 공간이 부족하고 볼륨의 LUN이 쓰기를 허용할 수 없을 때 호스트에 알립니다. 또한 이 옵션을 사용하면 호스트가 데이터를 삭제할 때 ONTAP에서 자동으로 공간을 재확보할 수 있습니다. 
---
= SCSI 씬 프로비저닝된 LUN에 대한 공간 할당을 설정합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
호스트에서 SCSI 씬 프로비저닝을 지원하는 경우 ONTAP에서 씬 프로비저닝된 SCSI LUN에 대한 공간 할당을 설정할 수 있습니다.  공간 할당이 설정되면 ONTAP가 볼륨에 공간이 부족해지면 호스트에 알리고 볼륨의 LUN이 쓰기를 수락할 수 없습니다. 또한 ONTAP는 호스트에서 데이터를 삭제하면 공간을 자동으로 재확보합니다.

SCSI 씬 프로비저닝을 지원하지 않는 호스트에서 LUN이 포함된 볼륨의 공간이 부족하고 자동으로 확장할 수 없는 경우 ONTAP는 LUN을 오프라인 상태로 전환합니다. SCSI 씬 프로비저닝을 지원하는 호스트에서 ONTAP는 공간이 부족할 때 LUN을 오프라인 상태로 전환하지 않습니다. LUN은 읽기 전용 모드로 온라인 상태를 유지하고 LUN이 더 이상 쓰기를 수락할 수 없음을 호스트에 알립니다.

또한 SCSI 씬 프로비저닝을 지원하는 호스트에서 데이터가 삭제되면 호스트 측 공간 관리가 호스트 파일 시스템에서 삭제된 데이터의 블록을 식별하여 하나 이상의 블록을 자동으로 발급합니다 `SCSI UNMAP` 스토리지 시스템에서 해당 블록을 해제하는 명령입니다.

.시작하기 전에
공간 할당을 설정하려면 호스트에서 SCSI 씬 프로비저닝을 지원해야 합니다. SCSI 씬 프로비저닝은 SCSI SBC-3 표준에 정의된 논리적 블록 프로비저닝을 사용합니다. 이 표준을 지원하는 호스트만 ONTAP에서 SCSI 씬 프로비저닝을 사용할 수 있습니다.

다음 호스트는 공간 할당을 설정할 때 현재 SCSI 씬 프로비저닝을 지원합니다.

* Citrix XenServer 6.5 이상
* ESXi 5.0 이상
* Oracle Linux 6.2 UEK 커널 이상
* RHEL 6.2 이상
* SLES11 이상
* Solaris 11.1 이상
* Windows


.이 작업에 대해
기본적으로 모든 LUN에 대해 공간 할당이 해제되어 있습니다. LUN을 오프라인으로 전환하여 공간을 할당해야 합니다. 그런 다음 호스트에서 공간 할당이 설정되어 있음을 인식하기 전에 호스트에서 검색을 수행해야 합니다.

.단계
. LUN을 오프라인 상태로 전환합니다.
+
[source, cli]
----
lun modify -vserver vserver_name -volume volume_name -lun lun_name -state offline
----
. 공간 할당 활성화:
+
[source, cli]
----
lun modify -vserver _vserver_name_ -volume _volume_name_ -lun _lun_name_ -space-allocation enabled
----
. 공간 할당이 설정되었는지 확인합니다.
+
[source, cli]
----
lun show -vserver _vserver_name_ -volume _volume_name_ -lun _lun_name_ -fields space-allocation
----
. LUN을 온라인 상태로 전환:
+
[source, cli]
----
lun modify -vserver _vserver_name_ -volume _volume_name_ -lun _lun_name_ -state online
----
. 호스트에서 모든 디스크를 재검색하여 '-space-allocation' 옵션의 변경 사항이 올바르게 검색되었는지 확인합니다.

