---
permalink: san-admin/host-side-management-concept.html 
sidebar: sidebar 
keywords: understand, host-side, space, management 
summary: 씬 프로비저닝된 환경에서 호스트 측 공간 관리는 호스트 파일 시스템에서 확보된 스토리지 시스템의 공간 관리 프로세스를 완료합니다. 
---
= SAN 호스트측 공간 관리
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
씬 프로비저닝된 환경에서 호스트 측 공간 관리는 호스트 파일 시스템에서 확보된 스토리지 시스템의 공간 관리 프로세스를 완료합니다.

호스트 파일 시스템에는 새 데이터를 저장하는 데 사용할 수 있는 블록과 덮어쓰지 않아야 하는 유효한 데이터가 들어 있는 블록을 추적하는 메타데이터가 포함되어 있습니다. 이 메타데이터는 LUN 내에 저장됩니다. 호스트 파일 시스템에서 파일이 삭제되면 파일 시스템 메타데이터가 업데이트되어 해당 파일의 블록을 여유 공간으로 표시합니다. 그런 다음 새로 확보된 블록을 포함하도록 총 파일 시스템 여유 공간이 다시 계산됩니다. 스토리지 시스템에서 이러한 메타데이터 업데이트는 호스트에서 수행하는 다른 쓰기와 다르지 않습니다. 따라서 스토리지 시스템에서 삭제된 내용이 있는지 인식하지 못합니다.

이렇게 하면 호스트에서 보고된 사용 가능한 공간의 양과 기본 스토리지 시스템에서 보고하는 사용 가능한 공간의 양이 서로 일치하지 않습니다. 예를 들어, 스토리지 시스템에서 호스트에 할당된 새로 프로비저닝된 200GB LUN이 있다고 가정합니다. 호스트와 스토리지 시스템 모두 200GB의 사용 가능한 공간을 보고합니다. 그런 다음 호스트는 100GB 데이터를 씁니다. 이때 호스트 및 스토리지 시스템 모두 100GB 사용 공간과 100GB 사용 안 된 공간을 보고합니다.

그런 다음 호스트에서 50GB의 데이터를 삭제합니다. 이때 호스트는 50GB의 사용된 공간과 150GB의 사용되지 않은 공간을 보고합니다. 그러나 스토리지 시스템은 100GB 사용 공간과 100GB의 미사용 공간을 보고합니다.

호스트 측 공간 관리는 다양한 방법을 사용하여 호스트와 스토리지 시스템 간의 공간 차이를 조정합니다.



== SnapCenter를 통한 호스트 관리 단순화

SnapCenter 소프트웨어를 사용하면 iSCSI 및 FC 스토리지와 관련된 일부 관리 및 데이터 보호 작업을 단순화할 수 있습니다. SnapCenter는 Windows 및 UNIX 호스트용 선택적 관리 패키지입니다.

SnapCenter 소프트웨어를 사용하면 여러 스토리지 시스템 간에 분산될 수 있는 스토리지 풀에서 가상 디스크를 쉽게 생성하고 스토리지 프로비저닝 작업을 자동화하며 호스트 데이터에 일치하는 스냅샷 복사본에서 스냅샷 복사본 및 클론을 생성하는 프로세스를 단순화할 수 있습니다.

에 대한 자세한 내용은 NetApp 제품 설명서를 참조하십시오 https://docs.netapp.com/us-en/snapcenter/index.html["SnapCenter"].

.관련 링크
link:enable-space-allocation-scsi-thin-provisioned-luns-task.html["SCSI 씬 프로비저닝된 LUN에 대한 공간 할당을 설정합니다"]
