---
permalink: san-admin/host-side-management-concept.html 
sidebar: sidebar 
keywords: understand, host-side, space, management 
summary: 씬 프로비저닝된 환경에서 호스트 측 공간 관리는 호스트 파일 시스템에서 확보된 스토리지 시스템의 공간 관리 프로세스를 완료합니다. 
---
= 호스트측 공간 관리 개요
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
씬 프로비저닝된 환경에서 호스트 측 공간 관리는 호스트 파일 시스템에서 확보된 스토리지 시스템의 공간 관리 프로세스를 완료합니다.

호스트 파일 시스템에는 새 데이터를 저장하는 데 사용할 수 있는 블록과 덮어쓰지 않아야 하는 유효한 데이터가 들어 있는 블록을 추적하는 메타데이터가 포함되어 있습니다. 이 메타데이터는 LUN 내에 저장됩니다. 호스트 파일 시스템에서 파일이 삭제되면 파일 시스템 메타데이터가 업데이트되어 해당 파일의 블록을 여유 공간으로 표시합니다. 그런 다음 새로 확보된 블록을 포함하도록 총 파일 시스템 여유 공간이 다시 계산됩니다. 스토리지 시스템에서 이러한 메타데이터 업데이트는 호스트에서 수행하는 다른 쓰기와 다르지 않습니다. 따라서 스토리지 시스템에서 삭제된 내용이 있는지 인식하지 못합니다.

이렇게 하면 호스트에서 보고된 사용 가능한 공간의 양과 기본 스토리지 시스템에서 보고하는 사용 가능한 공간의 양이 서로 일치하지 않습니다. 예를 들어, 스토리지 시스템에서 호스트에 할당된 새로 프로비저닝된 200GB LUN이 있다고 가정합니다. 호스트와 스토리지 시스템 모두 200GB의 사용 가능한 공간을 보고합니다. 그런 다음 호스트는 100GB 데이터를 씁니다. 이때 호스트 및 스토리지 시스템 모두 100GB 사용 공간과 100GB 사용 안 된 공간을 보고합니다.

그런 다음 호스트에서 50GB의 데이터를 삭제합니다. 이때 호스트는 50GB의 사용된 공간과 150GB의 사용되지 않은 공간을 보고합니다. 그러나 스토리지 시스템은 100GB 사용 공간과 100GB의 미사용 공간을 보고합니다.

호스트 측 공간 관리는 다양한 방법을 사용하여 호스트와 스토리지 시스템 간의 공간 차이를 조정합니다.
