---
permalink: san-admin/igroups-concept.html 
sidebar: sidebar 
keywords: understand, igroups 
summary: '이니시에이터 그룹(igroup)은 FC 프로토콜 호스트 WWPN 또는 iSCSI 호스트 노드 이름의 테이블입니다. igroup을 정의하고 LUN에 매핑하여 LUN에 액세스할 수 있는 이니시에이터를 제어할 수 있습니다.' 
---
= Igroup 정보
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
이니시에이터 그룹(igroup)은 FC 프로토콜 호스트 WWPN 또는 iSCSI 호스트 노드 이름의 테이블입니다. igroup을 정의하고 LUN에 매핑하여 LUN에 액세스할 수 있는 이니시에이터를 제어할 수 있습니다.

일반적으로 호스트의 모든 이니시에이터 포트 또는 소프트웨어 이니시에이터가 LUN에 액세스할 수 있도록 합니다. 다중 경로 소프트웨어를 사용하거나 클러스터 호스트를 사용하는 경우, 각 클러스터 호스트의 각 이니시에이터 포트 또는 소프트웨어 이니시에이터는 동일한 LUN에 대한 이중 경로를 필요로 합니다.

LUN을 생성하기 전이나 후에 LUN에 액세스할 수 있는 이니시에이터를 지정하는 igroup을 생성할 수 있지만 LUN을 igroup에 매핑하기 전에 igroup을 생성해야 합니다.

이니시에이터 그룹에 여러 이니시에이터가 있을 수 있으며, 여러 igroup이 동일한 이니시에이터를 포함할 수 있습니다. 그러나 동일한 이니시에이터가 있는 여러 igroup에 LUN을 매핑할 수 없습니다. 이니시에이터는 서로 다른 상치성 igroup의 구성원일 수 없습니다.



== igroup에서 LUN 액세스를 제공하는 방법의 예

여러 igroup을 생성하여 호스트에 사용할 수 있는 LUN을 정의할 수 있습니다. 예를 들어, 호스트 클러스터가 있는 경우 igroup을 사용하여 특정 LUN이 클러스터의 한 호스트에만 또는 클러스터의 모든 호스트에 표시되는지 확인할 수 있습니다.

다음 표에서는 4개의 igroup이 스토리지 시스템에 액세스하는 4개의 서로 다른 호스트에 대한 LUN에 액세스하는 방법을 보여 줍니다. 클러스터 호스트(Host3 및 Host4)는 모두 동일한 igroup(Group3)의 구성원이며 이 igroup에 매핑된 LUN에 액세스할 수 있습니다. group4라는 igroup에는 파트너가 볼 수 없는 로컬 정보를 저장하기 위한 Host4의 WWPN이 포함되어 있습니다.

[cols="4*"]
|===
| HBA WWPN, IQN 또는 EUI가 포함된 호스트 | Igroup | WWPN, IQN, EUI가 igroup에 추가되었습니다 | LUN이 igroup에 매핑되어 있습니다 


 a| 
호스트1, 단일 경로(iSCSI 소프트웨어 이니시에이터)

iqn.1991-05.com.microsoft:host1
 a| 
그룹1
 a| 
iqn.1991-05.com.microsoft:host1
 a| 
'/vol/vol2/lun1'



 a| 
Host2, 다중 경로(HBA 2개)

10:00:00:00:C9:2b:6b:3c

10:00:00:00:C9:2b:02:3c
 a| 
그룹2
 a| 
10:00:00:00:C9:2b:6b:3c

10:00:00:00:C9:2b:02:3c
 a| 
'/vol/vol2/lun2'



 a| 
호스트 3, 다중 경로, 호스트 4로 클러스터링되었습니다

10:00:00:00:C9:2b:32:1b

10:00:00:00:C9:2b:41:02
 a| 
그룹3
 a| 
10:00:00:00:C9:2b:32:1b

10:00:00:00:C9:2b:41:02

10:00:00:00:C9:2b:51:2c

10:00:00:00:C9:2b:47:A2
 a| 
'/vol/vol2/qtree1/lun3'



 a| 
Host4, multipath, 클러스터링됨(Host3에는 표시되지 않음)

10:00:00:00:C9:2b:51:2c

10:00:00:00:C9:2b:47:A2
 a| 
그룹4
 a| 
10:00:00:00:C9:2b:51:2c

10:00:00:00:C9:2b:47:A2
 a| 
'/vol/vol2/qtree2/lun4''/vol/vol2/qtree1/lun5'

|===