---
permalink: san-admin/improve-vmware-vaai-performance-esx-hosts-concept.html 
sidebar: sidebar 
keywords: improve, vmware, vaai, performance, esx, hosts 
summary: 'ONTAP는 ESX 호스트가 ESX 4.1 이상을 실행하는 경우 특정 VMware VAAI(vStorage APIs for Array Integration) 기능을 지원합니다. 이러한 기능은 ESX 호스트에서 스토리지 시스템으로 작업을 오프로드하고 네트워크 처리량을 늘리는 데 도움이 됩니다. ESX 호스트는 올바른 환경에서 자동으로 기능을 활성화합니다.' 
---
= ESX 호스트의 VMware VAAI 성능을 향상시킵니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP는 ESX 호스트가 ESX 4.1 이상을 실행하는 경우 특정 VMware VAAI(vStorage APIs for Array Integration) 기능을 지원합니다. 이러한 기능은 ESX 호스트에서 스토리지 시스템으로 작업을 오프로드하고 네트워크 처리량을 늘리는 데 도움이 됩니다. ESX 호스트는 올바른 환경에서 자동으로 기능을 활성화합니다.

VAAI 기능은 다음 SCSI 명령을 지원합니다.

* "extended_copy"
+
이 기능을 사용하면 호스트가 데이터 전송에 참여하지 않고도 LUN 간 또는 LUN 내에서 데이터 전송을 시작할 수 있습니다. 따라서 ESX CPU 주기가 단축되고 네트워크 처리량이 증가합니다. "복사 오프로드"라고도 하는 확장된 복사 기능은 가상 머신의 클론 생성과 같은 시나리오에서 사용됩니다. ESX 호스트에서 호출하면 복제 오프로드 기능은 호스트 네트워크를 통해 이동하는 대신 스토리지 시스템 내의 데이터를 복제합니다. Copy Offload는 다음과 같은 방법으로 데이터를 전송합니다.

+
** 하나의 LUN 내에서
** 볼륨 내의 LUN 간
** 스토리지 가상 시스템(SVM) 내의 서로 다른 볼륨에 있는 LUN 간
** 클러스터 내의 서로 다른 SVM에 있는 LUN 간에 이 기능을 호출할 수 없는 경우 ESX 호스트는 복사 작업에 표준 읽기 및 쓰기 명령을 자동으로 사용합니다.


* 같은 글씨를 쓰십시오
+
이 기능은 0과 같은 반복된 패턴을 스토리지 배열에 쓰는 작업을 오프로드합니다. ESX 호스트는 파일 채우기 0과 같은 작업에서 이 기능을 사용합니다.

* 비교 및 쓰기
+
이 기능은 특정 파일 액세스 동시 접속 제한을 우회하여 가상 머신 부팅 등의 작업을 가속화합니다.





== VAAI 환경 사용에 대한 요구 사항

VAAI 기능은 ESX 운영 체제의 일부이며 올바른 환경을 설정한 경우 ESX 호스트에서 자동으로 호출됩니다.

환경 요구 사항은 다음과 같습니다.

* ESX 호스트는 ESX 4.1 이상을 실행해야 합니다.
* VMware 데이터 저장소를 호스팅하는 NetApp 스토리지 시스템은 ONTAP를 실행 중이어야 합니다.
* (복제 오프로딩만 해당) VMware 복제 작업의 소스 및 대상은 동일한 클러스터 내의 동일한 스토리지 시스템에서 호스팅되어야 합니다.
+
[NOTE]
====
현재 복제 오프로드 기능은 다른 스토리지 시스템에서 호스팅되는 VMware 데이터 저장소 간에 데이터 복제를 지원하지 않습니다.

====




== VAAI 기능이 ESX에서 지원되는지 확인합니다

ESX 운영 체제에서 VAAI 기능을 지원하는지 확인하려면 vSphere Client를 확인하거나 호스트에 액세스하는 다른 방법을 사용할 수 있습니다. ONTAP는 기본적으로 SCSI 명령을 지원합니다.

ESX 호스트 고급 설정을 확인하여 VAAI 기능이 설정되었는지 여부를 확인할 수 있습니다. 표에는 ESX 제어 이름에 해당하는 SCSI 명령이 나와 있습니다.

[cols="2*"]
|===
| scsi 명령 | ESX 제어 이름(VAAI 기능) 


 a| 
Extended_copy(확장 복사)
 a| 
하드하드웨어가속한이동



 a| 
같은 쓰기
 a| 
하드wareAcceleratedInit



 a| 
Compare_and_write(비교 및 쓰기)
 a| 
하드wareAcceleratedLocking

|===