---
permalink: san-admin/isns-concept.html 
sidebar: sidebar 
keywords: what, isns 
summary: 'iSNS(Internet Storage Name Service)는 TCP/IP 스토리지 네트워크에서 iSCSI 디바이스를 자동으로 검색하고 관리할 수 있도록 하는 프로토콜입니다. iSNS 서버는 IP 주소, iSCSI 노드 이름 IQN 및 포털 그룹을 포함하여 네트워크의 활성 iSCSI 장치에 대한 정보를 유지 관리합니다.' 
---
= iSNS란 무엇입니까
:icons: font
:imagesdir: ../media/


[role="lead"]
iSNS(Internet Storage Name Service)는 TCP/IP 스토리지 네트워크에서 iSCSI 디바이스를 자동으로 검색하고 관리할 수 있도록 하는 프로토콜입니다. iSNS 서버는 IP 주소, iSCSI 노드 이름 IQN 및 포털 그룹을 포함하여 네트워크의 활성 iSCSI 장치에 대한 정보를 유지합니다.

타사 공급업체에서 iSNS 서버를 가져올 수 있습니다. 네트워크에 iSNS 서버가 구성되어 이니시에이터 및 타겟에 사용하도록 설정되어 있는 경우 SVM(스토리지 가상 머신)에 관리 LIF를 사용하여 iSNS 서버에 해당 SVM에 대한 모든 iSCSI LIF를 등록할 수 있습니다. 등록이 완료되면 iSCSI 이니시에이터가 iSNS 서버를 쿼리하여 해당 SVM에 대한 모든 LIF를 검색할 수 있습니다.

iSNS 서비스를 사용하려는 경우 iSNS(Internet Storage Name Service) 서버에 스토리지 가상 시스템(SVM)이 올바르게 등록되어 있는지 확인해야 합니다.

네트워크에 iSNS 서버가 없는 경우 호스트에 표시되도록 각 타겟을 수동으로 구성해야 합니다.



== iSNS 서버의 기능

iSNS 서버는 iSNS(Internet Storage Name Service) 프로토콜을 사용하여 IP 주소, iSCSI 노드 이름(IQN) 및 포털 그룹을 포함하여 네트워크의 활성 iSCSI 장치에 대한 정보를 유지합니다.

iSNS 프로토콜을 사용하면 IP 스토리지 네트워크에서 iSCSI 디바이스를 자동으로 검색하고 관리할 수 있습니다. iSCSI 이니시에이터는 iSNS 서버를 쿼리하여 iSCSI 타겟 디바이스를 검색할 수 있습니다.

NetApp은 iSNS 서버를 제공하거나 재판매하지 않습니다. NetApp에서 지원하는 공급업체로부터 이러한 서버를 받을 수 있습니다.
