---
permalink: san-admin/lun-san-environments-concept.html 
sidebar: sidebar 
keywords: lun, guidelines, assigning, assign, ids, mapping, map, igroups 
summary: 클러스터에서 LUN을 설정하기 전에 LUN 지침을 검토해야 합니다. 
---
= LUN을 생성하기 전에 알아야 할 사항
:allow-uri-read: 
:icons: font
:imagesdir: ../media/




== 실제 LUN 크기가 약간 다른 이유

LUN의 크기와 관련하여 다음 사항에 유의하십시오.

* LUN을 생성할 때 LUN의 실제 크기는 LUN의 OS 유형에 따라 약간 다를 수 있습니다. LUN을 생성한 후에는 LUN OS 유형을 수정할 수 없습니다.
* 최대 16TB 크기의 LUN을 생성하는 경우 LUN의 실제 크기는 약간 더 적을 수 있습니다. ONTAP는 한계치를 약간 낮추어 줍니다.
* 각 LUN의 메타데이터는 포함하는 애그리게이트에서 약 64KB의 공간을 필요로 합니다. LUN을 생성할 때 포함하는 애그리게이트에 LUN의 메타데이터를 위한 충분한 공간이 있는지 확인해야 합니다. Aggregate에 LUN의 메타데이터를 위한 충분한 공간이 없을 경우 일부 호스트에서 LUN에 액세스하지 못할 수 있습니다.




== LUN ID 할당 지침

일반적으로 기본 LUN ID는 0으로 시작하고 각 추가 매핑된 LUN에 대해 1씩 증분식으로 할당됩니다. 호스트는 LUN ID를 LUN의 위치 및 경로 이름과 연결합니다. 유효한 LUN ID 번호의 범위는 호스트에 따라 다릅니다. 자세한 내용은 Host Utilities와 함께 제공된 설명서를 참조하십시오.



== LUN을 igroup에 매핑하기 위한 지침

* LUN을 igroup에 한 번만 매핑할 수 있습니다.
* igroup을 통해 하나의 특정 이니시에이터에 LUN을 매핑할 수 있습니다.
* 한 개의 이니시에이터를 여러 igroup에 추가할 수 있지만 이니시에이터는 하나의 LUN에만 매핑할 수 있습니다.
* 동일한 igroup에 매핑된 두 LUN에 대해 동일한 LUN ID를 사용할 수 없습니다.
* Igroup 및 포트 세트에 동일한 프로토콜 유형을 사용해야 합니다.

