---
permalink: san-admin/manage-nvme-concept.html 
sidebar: sidebar 
keywords: manage, nvme, overview, license 
summary: ONTAP 9.4부터는 NVMe/FC가 지원됩니다. ONTAP 9.5부터 NVMe를 지원하려면 라이센스가 필요합니다. ONTAP 9.4에서 NVMe를 사용하는 경우 ONTAP 9.5로 업그레이드한 후 라이센스를 취득하기 위한 90일 유예 기간이 제공됩니다. 
---
= NVMe 개요
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9.4부터는 비 MetroCluster AFF 구성에서 NVMe/FC가 지원됩니다. ONTAP 9.9.1 NVMe/FC로 시작하는 것은 MetroCluster가 아닌 모든 AFF ASA(All SAN 어레이) 구성에서도 지원됩니다

NVMe(Non-Volatile Memory Express) 프로토콜을 사용하여 SAN 환경에 스토리지를 제공할 수 있습니다. NVMe 프로토콜은 솔리드 스테이트 스토리지의 성능을 위해 최적화되어 있습니다.

NVMe의 경우 스토리지 타겟을 네임스페이스라고 합니다. NVMe 네임스페이스는 많은 비휘발성 스토리지로, 논리 블록으로 포맷되고 호스트에 표준 블록 장치로 제공될 수 있습니다. 네임스페이스와 서브시스템을 생성한 다음, 네임스페이스를 서브시스템에 매핑합니다. 이는 LUN이 FC 및 iSCSI용 igroup에 프로비저닝 및 매핑된 방식과 유사합니다.

NVMe 대상은 이더넷 스위치 및 호스트 측 어댑터를 사용하여 FC 스위치 또는 표준 TCP 인프라를 사용하여 표준 FC 인프라를 통해 네트워크에 연결됩니다.

지원되는 NVMe 프로토콜은 다음과 같습니다.

[cols="3*"]
|===


| 프로토콜 | 다음으로 시작... | 허용된 사용자... 


| TCP | ONTAP 9.10.1 | 기본값 


| FCP | ONTAP 9.4 | 기본값 
|===


== NVMe 라이센스 요구 사항

ONTAP 9.5부터 NVMe를 지원하려면 라이센스가 필요합니다. ONTAP 9.4에서 NVMe를 사용하는 경우 ONTAP 9.5로 업그레이드한 후 라이센스를 취득하기 위한 90일 유예 기간이 제공됩니다.

다음 명령을 사용하여 라이센스를 설정할 수 있습니다.

'System license add-license-code_NVMe_license_key_'



== NVMe란 무엇입니까

NVMe(Nonvolatile Memory Express) 프로토콜은 비휘발성 스토리지 미디어에 액세스하는 데 사용되는 전송 프로토콜입니다.

NVMe over Fabrics (NVMeoF)는 PCIe 이외의 연결을 통해 NVMe 기반 통신을 가능하게 하는 NVMe에 대한 사양 정의 확장입니다. 이 인터페이스를 통해 외부 스토리지 인클로저를 서버에 연결할 수 있습니다.

NVMe는 플래시 기술에서 고성능 영구 메모리 기술에 이르기까지 비휘발성 메모리로 구축된 스토리지 장치에 효율적으로 액세스할 수 있도록 설계되었습니다. 따라서 하드 디스크 드라이브용으로 설계된 스토리지 프로토콜과 동일한 제한이 없습니다. 플래시 및 SSD(Solid State Device)는 일종의 비휘발성 메모리(NVM)입니다. NVM은 정전 시 콘텐츠를 보관하는 메모리의 한 유형입니다. NVMe는 해당 메모리에 액세스할 수 있는 방법입니다.

NVMe의 이점으로는 데이터 전송을 위한 속도, 생산성, 처리량 및 용량이 증가합니다. 구체적인 특징은 다음과 같습니다.

* NVMe는 최대 64,000개의 대기열을 지원하도록 설계되었습니다.
+
또한 각 대기열에는 최대 64,000개의 동시 명령이 있을 수 있습니다.

* NVMe는 여러 하드웨어 및 소프트웨어 공급업체에서 지원합니다
* NMVe는 빠른 응답 시간을 지원하는 플래시 기술을 통해 생산성이 더 높습니다
* NVMe를 사용하면 SSD로 전송되는 각 "요청"에 대해 여러 데이터 요청을 처리할 수 있습니다.
+
NVMe는 "재퀘스트"를 디코딩하는 데 시간이 더 적게 걸리며 다중 스레드 프로그램에서 스레드 잠금을 요구하지 않습니다.

* NVMe는 CPU 레벨에서 병목 현상을 방지하고 시스템이 확장됨에 따라 대규모 확장성을 지원하는 기능을 지원합니다


.관련 정보
* link:../task_nvme_provision_suse_linux.html["SUSE Linux용 NVMe 스토리지 프로비저닝"]
* link:san-admin/configure-svm-nvme-task.html["NVMe용 스토리지 VM을 구성합니다"]

