---
permalink: san-admin/microsoft-offloaded-data-transfer-odx-concept.html 
sidebar: sidebar 
keywords: microsoft, offloaded, data, transfer, odx 
summary: '복사 오프로드로 알려진 Microsoft ODX(Offloaded Data Transfer)를 사용하면 호스트 컴퓨터를 통해 데이터를 전송하지 않고도 스토리지 장치 내에서 또는 호환되는 스토리지 장치 간에 직접 데이터를 전송할 수 있습니다.' 
---
= Microsoft ODX(Offloaded Data Transfer)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Microsoft ODX(Offloaded Data Transfer)는 _copy offload_라고도 하며 호스트 컴퓨터를 통해 데이터를 전송하지 않고 스토리지 장치 내에서 또는 호환되는 스토리지 장치 간에 직접 데이터를 전송할 수 있습니다.

ONTAP은 SMB 및 SAN 프로토콜을 모두 지원하는 ODX를 지원합니다.

ODX가 아닌 파일을 전송하면 소스에서 데이터를 읽고 네트워크를 통해 호스트로 전송합니다. 호스트는 네트워크를 통해 데이터를 대상으로 다시 전송합니다. ODX 파일 전송에서는 호스트를 거치지 않고 데이터를 소스에서 대상으로 직접 복사합니다.

ODX로 오프로드된 복사본이 소스와 대상 간에 직접 수행되므로 복사 시간 단축, 클라이언트의 CPU 및 메모리 활용률 감소, 네트워크 I/O 대역폭 사용률 감소 등 상당한 성능 이점이 실현됩니다.

SAN 환경의 경우 ODX는 호스트와 스토리지 시스템 모두에서 지원되는 경우에만 사용할 수 있습니다. ODX를 지원하고 ODX를 사용하는 클라이언트 컴퓨터는 파일을 이동하거나 복사할 때 오프로드된 파일 전송을 자동으로 투명하게 사용합니다. ODX는 Windows 탐색기를 통해 파일을 끌어서 놓을지, 명령줄 파일 복사 명령을 사용하는지, 클라이언트 애플리케이션이 파일 복사 요청을 시작하는지 여부와 관계없이 사용됩니다.



== ODX 사용을 위한 요구사항

복사 오프로드를 위해 ODX를 사용할 계획이라면 볼륨 지원 고려 사항, 시스템 요구 사항 및 소프트웨어 기능 요구 사항을 잘 알고 있어야 합니다.

ODX를 사용하려면 시스템에 다음이 있어야 합니다.

* ONTAP
+
ODX는 지원되는 ONTAP 버전에서 자동으로 활성화됩니다.

* 최소 소스 볼륨 2GB
+
최적의 성능을 위해 소스 볼륨은 260GB보다 커야 합니다.

* 중복 제거
+
ODX는 복사 프로세스의 일부로 중복 제거를 사용합니다. SVM에서 중복 제거를 사용하지 않으려면 해당 SVM에서 ODX를 사용하지 않도록 설정해야 합니다.

* Windows 클라이언트에서 ODX를 지원합니다
+
ODX는 Windows Server 2012 이상 및 Windows 8 이상에서 지원됩니다. 상호 운용성 매트릭스에는 지원되는 Windows 클라이언트에 대한 최신 정보가 포함되어 있습니다.

+
https://mysupport.netapp.com/matrix["NetApp 상호 운용성 매트릭스 툴"^]

* ODX에 대한 복사 애플리케이션 지원
+
데이터 전송을 수행하는 애플리케이션은 ODX를 지원해야 합니다. ODX를 지원하는 애플리케이션 작업은 다음과 같습니다.

+
** VHD(가상 하드 디스크) 생성 및 변환, Snapshot 복사본 관리, 가상 시스템 간 파일 복사와 같은 Hyper-V 관리 작업입니다
** Windows 탐색기 작업
** Windows PowerShell 복사 명령
** Windows 명령 프롬프트 복사 명령 Microsoft TechNet 라이브러리에는 Windows 서버 및 클라이언트에서 지원되는 ODX 응용 프로그램에 대한 자세한 정보가 나와 있습니다.


* 압축된 볼륨을 사용하는 경우 압축 그룹 크기는 8K여야 합니다.
+
32K 압축 그룹 크기가 지원되지 않습니다.



ODX는 다음 볼륨 유형과 함께 작동하지 않습니다.

* 용량이 2GB 미만인 소스 볼륨
* 읽기 전용 볼륨입니다
* link:../flexcache/supported-unsupported-features-concept.html["FlexCache 볼륨"]
+

NOTE:  ODX는 FlexCache 원본 볼륨에서 지원됩니다.

* link:../san-admin/san-volumes-concept.html#semi-thick-provisioning-for-volumes["반씩 프로비저닝된 볼륨"]




== 특수 시스템 파일 요구 사항

qtree에 있는 ODX 파일을 삭제할 수 있습니다. 기술 지원 부서의 지시가 없는 한 다른 ODX 시스템 파일을 제거하거나 수정해서는 안 됩니다.

ODX 기능을 사용하면 시스템의 모든 볼륨에 ODX 시스템 파일이 존재합니다. 이러한 파일을 사용하면 ODX 전송 중에 사용된 데이터를 특정 시점으로 표시할 수 있습니다. 다음 시스템 파일은 데이터가 오프로드된 LUN 또는 파일을 포함하는 각 볼륨의 루트 레벨에 있습니다.

* '.copy-offload'(숨겨진 디렉토리)
* '.tokens'(숨겨진 파일.copy-offload' 디렉토리)


"copy-offload delete-tokens-path dir_path-node_node_name_" 명령을 사용하여 ODX 파일이 포함된 qtree를 삭제할 수 있습니다.



== ODX의 사용 사례

ODX가 성능 이점을 제공하는 상황을 파악할 수 있도록 SVM에서 ODX를 사용하는 사용 사례를 알고 있어야 합니다.

ODX를 지원하는 Windows 서버 및 클라이언트는 원격 서버 간에 데이터를 복사하는 기본 방법으로 복사 오프로드를 사용합니다. Windows 서버 또는 클라이언트가 ODX를 지원하지 않거나 ODX 복사 오프로드가 어느 시점에서든 장애가 발생하면 복사 또는 이동 작업이 복사 또는 이동 작업에 대한 기존 읽기/쓰기로 다시 돌아갑니다.

ODX 복사 및 이동 사용을 지원하는 사용 사례는 다음과 같습니다.

* 체내
+
소스 및 대상 파일 또는 LUN이 동일한 볼륨 내에 있습니다.

* 볼륨 간, 동일한 노드, 동일한 SVM
+
소스 및 대상 파일 또는 LUN이 동일한 노드에 있는 다른 볼륨에 있습니다. 데이터는 동일한 SVM이 소유합니다.

* 볼륨 간, 다른 노드, 동일한 SVM
+
소스 및 대상 파일 또는 LUN이 서로 다른 노드에 있는 서로 다른 볼륨에 있습니다. 데이터는 동일한 SVM이 소유합니다.

* SVM 간, 동일한 노드
+
소스 및 대상 파일 또는 LUN이 동일한 노드에 있는 서로 다른 볼륨에 있습니다. 데이터는 서로 다른 SVM에서 소유합니다.

* SVM 간, 다른 노드
+
소스 및 대상 파일 또는 LUN이 서로 다른 노드에 있는 서로 다른 볼륨에 있습니다. 데이터는 서로 다른 SVM에서 소유합니다.

* 클러스터 간
+
소스 및 타겟 LUN은 클러스터 전반의 서로 다른 노드에 있는 서로 다른 볼륨에 있습니다. 이 기능은 SAN에만 지원되며 SMB에는 적용되지 않습니다.



다음과 같은 몇 가지 특별한 사용 사례가 있습니다.

* ONTAP ODX를 구현하면 ODX를 사용하여 SMB 공유와 FC 또는 iSCSI 연결 가상 드라이브 간에 파일을 복사할 수 있습니다.
+
SMB 공유와 LUN이 동일한 클러스터에 존재하는 경우, ODX를 지원하는 Windows 탐색기, Windows CLI 또는 PowerShell, Hyper-V 또는 기타 애플리케이션을 사용하여 SMB 공유와 연결된 LUN 간에 ODX 복사 오프로드를 사용하여 파일을 원활하게 복사 또는 이동할 수 있습니다.

* Hyper-V는 ODX 복사 오프로드를 위한 몇 가지 추가 사용 사례를 제공합니다.
+
** Hyper-V에서 ODX 복사 오프로드 패스스스루 를 사용하여 VHD(가상 하드 디스크) 파일 내부 또는 VHD 파일 간에 데이터를 복사하거나, 매핑된 SMB 공유와 동일한 클러스터 내에서 연결된 iSCSI LUN 간에 데이터를 복사할 수 있습니다.
+
이렇게 하면 게스트 운영 체제에서 복제본을 기본 스토리지로 전달할 수 있습니다.

** 고정 크기의 VHD를 생성할 때 ODX는 잘 알려진 제로화 토큰을 사용하여 0으로 디스크를 초기화하는 데 사용됩니다.
** 소스 및 타겟 스토리지가 동일한 클러스터에 있는 경우 ODX 복사 오프로드가 가상 머신 스토리지 마이그레이션에 사용됩니다.


+
[NOTE]
====
Hyper-V를 사용한 ODX 복사 오프로드 패스쓰루 사용 사례를 활용하려면 게스트 운영 체제가 ODX를 지원하고, 게스트 운영 체제 디스크는 ODX를 지원하는 스토리지(SMB 또는 SAN)를 통해 지원되는 SCSI 디스크여야 합니다. 게스트 운영 체제의 IDE 디스크는 ODX 패스스스루 를 지원하지 않습니다.

====

