---
permalink: san-admin/modify-slm-reporting-nodes-task.html 
sidebar: sidebar 
keywords: modify, slm, reporting-nodes, list 
summary: 'LUN이 포함된 LUN 또는 볼륨을 동일한 클러스터 내의 다른 고가용성(HA) 쌍으로 이동하는 경우, 이동을 시작하기 전에 선택 LUN 맵(SLM: Selective LUN Map) 보고 노드 목록을 수정하여 최적화된 활성 LUN 경로가 유지되도록 해야 합니다.' 
---
= SLM 보고 노드 목록을 수정합니다
:icons: font
:imagesdir: ../media/


[role="lead"]
LUN이 포함된 LUN 또는 볼륨을 동일한 클러스터 내의 다른 고가용성(HA) 쌍으로 이동하는 경우, 이동을 시작하기 전에 선택 LUN 맵(SLM: Selective LUN Map) 보고 노드 목록을 수정하여 최적화된 활성 LUN 경로가 유지되도록 해야 합니다.

.단계
. 대상 노드와 해당 파트너 노드를 애그리게이트 또는 볼륨의 보고 노드 목록에 추가합니다.
+
'lun mapping add-reporting-nodes-vserver_vserver_name_-path_lun_path_-igroup_name_[-destination-aggregate_aggregate_name_|-destination-volume_volume_name_]'

+
일관된 명명 규칙이 있는 경우, "igroup" 대신 ' * -igroup * '을 사용하여 여러 LUN 매핑을 동시에 수정할 수 있습니다.

. 호스트를 재검색하여 새로 추가된 경로를 검색합니다.
. OS에 필요한 경우 다중 경로 네트워크 I/O(MPIO) 구성에 새 경로를 추가합니다.
. 필요한 이동 작업에 대해 명령을 실행하고 작업이 완료될 때까지 기다립니다.
. Active/Optimized 경로를 통해 입출력이 서비스되고 있는지 확인합니다.
+
LUN 매핑 표시-필드 보고-노드

. 보고 노드 목록에서 이전 LUN 소유자 및 해당 파트너 노드를 제거합니다.
+
'LUN 매핑 제거-보고-노드-vserver_vserver_name_-path_lun_path_-igroup_igroup_name_-remote-nodes'

. LUN이 기존 LUN 맵에서 제거되었는지 확인합니다.
+
LUN 매핑 표시-필드 보고-노드

. 호스트 OS의 오래된 디바이스 항목을 제거합니다.
. 필요한 경우 경로 다중화 구성 파일을 변경합니다.
. 호스트를 재검색하여 이전 경로가 제거되었는지 확인합니다. + 호스트를 재검색하는 특정 단계는 호스트 설명서를 참조하십시오.

