---
permalink: san-admin/nvme-namespaces-considerations-concept.html 
sidebar: sidebar 
keywords: nvme, namespaces, considerations, provisioning 
summary: SAN 환경에서 NVMe 프로토콜을 설정하려면 NVMe용 SVM을 구성하고, 네임스페이스와 서브시스템을 생성하고, NVMe/FC LIF를 구성한 다음, 네임스페이스를 서브시스템에 매핑해야 합니다. 
---
= NVMe 네임스페이스 고려 사항
:icons: font
:imagesdir: ../media/


[role="lead"]
SAN 환경에서 NVMe 프로토콜을 설정하려면 NVMe용 SVM을 구성하고, 네임스페이스와 서브시스템을 생성하고, NVMe/FC LIF를 구성한 다음, 네임스페이스를 서브시스템에 매핑해야 합니다. NVMe 네임스페이스를 사용할 때는 주의해야 할 몇 가지 사항이 있습니다.

* LUN의 데이터가 손실될 경우 네임스페이스에서 또는 그 반대로 LUN을 복원할 수 없습니다.
* 네임스페이스에 대한 공간 보장은 포함하는 볼륨의 공간 보장과 동일합니다.
* ONTAP 9.6부터 네임스페이스는 512바이트 블록과 4096바이트 블록을 지원합니다.
+
기본값은 4096입니다. 512는 호스트 운영 체제가 4096바이트 블록을 지원하지 않는 경우에만 사용해야 합니다.

* 네임스페이스는 다음을 지원하지 않습니다.
+
** 이름 바꾸기
+
이름 공간의 이름은 바꿀 수 없습니다.

** 크기 조정
+
네임스페이스의 크기를 늘리거나 줄일 수는 없습니다.

** 볼륨 간 이동
** 볼륨 간 복사






== NVMe 네임스페이스 정보

NVMe 네임스페이스는 논리 블록으로 포맷될 수 있는 비휘발성 메모리(NVM)의 양입니다. 네임스페이스는 스토리지 가상 머신이 NVMe 프로토콜을 통해 구성되고 FC 및 iSCSI 프로토콜에 대한 LUN과 동등한 경우에 사용됩니다.

하나 이상의 네임스페이스가 프로비저닝되고 NVMe 호스트에 연결됩니다. 각 네임스페이스는 다양한 블록 크기를 지원할 수 있습니다.

NVMe 프로토콜은 여러 컨트롤러를 통해 네임스페이스에 대한 액세스를 제공합니다. 대부분의 운영 체제에서 지원되는 NVMe 드라이버를 사용하면 SSD(Solid State Drive) 네임스페이스가 수정 없이 파일 시스템과 애플리케이션을 구축할 수 있는 표준 블록 장치로 표시됩니다.

네임스페이스 ID(NSID)는 네임스페이스에서 액세스를 제공하기 위해 컨트롤러에서 사용하는 식별자입니다. 호스트 또는 호스트 그룹에 대한 NSID를 설정할 때 호스트가 볼륨에 액세스할 수 있도록 구성할 수도 있습니다. 논리적 블록은 한 번에 하나의 호스트 그룹에만 매핑할 수 있으며, 지정된 호스트 그룹에는 중복된 NSID가 없습니다.



=== NVMe 네임스페이스를 위한 NVMe 하위 시스템 프로비저닝

NVMe 하위 시스템에는 하나 이상의 NVMe 컨트롤러, 네임스페이스, NVM 하위 시스템 포트, NVM 스토리지 미디어 및 컨트롤러와 NVM 스토리지 미디어 간의 인터페이스가 포함되어 있습니다. NVMe 네임스페이스를 생성할 때 다음과 같이 NVMe 서브시스템을 네임스페이스에 매핑할 수 있습니다.

* * 없음(기본값) * + NVMe 서브시스템이 네임스페이스에 매핑되어 있지 않습니다.
* * 기존 하위 시스템 * + 기존 NVMe 하위 시스템을 선택하여 네임스페이스에 매핑할 수 있습니다. NVMe 서브시스템은 호스트 OS 및 SVM 필드를 기반으로 나열됩니다. NVMe 하위 시스템 이름 위로 포인터를 가져가면 하위 시스템에 대한 자세한 정보가 표시됩니다.
* * 새 하위 시스템 * + 새 NVMe 하위 시스템을 만들어 네임스페이스에 매핑할 수 있습니다. 서브시스템은 호스트 OS 및 SVM에서 생성됩니다.


다음 세부 정보를 제공하여 하위 시스템을 프로비저닝합니다.

* * NVMe 하위 시스템 이름 * + NVMe 하위 시스템 이름은 대소문자를 구분합니다. 1 ~ 96자를 포함해야 하며 특수 문자를 사용할 수 있습니다.
* * 호스트 OS * + 하위 시스템이 생성되는 호스트 OS 유형입니다.
* * 호스트 NQN * + 컨트롤러에 연결된 호스트 NVMe 자격 이름입니다. 이 열에는 서브시스템에 연결된 호스트가 1개부터 여러 개일 수 있으므로 쉼표로 구분된 값이 포함될 수 있습니다.

