---
permalink: san-admin/recommended-volume-lun-config-combinations-concept.html 
sidebar: sidebar 
keywords: recommended, volume, file, lun, configuration, combinations, space-reserved, thick volume, thin, semi-thick, provisioning 
summary: 애플리케이션 및 관리 요구사항에 따라 FlexVol 볼륨과 파일 또는 LUN 구성의 특정 조합이 사용할 수 있습니다. 이러한 조합을 통해 얻을 수 있는 이점과 비용을 이해하면 환경에 적합한 볼륨 및 LUN 구성의 조합을 결정하는 데 도움이 됩니다. 
---
= 권장되는 볼륨 및 파일 또는 LUN 구성 조합 개요
:icons: font
:imagesdir: ../media/


[role="lead"]
애플리케이션 및 관리 요구사항에 따라 FlexVol 볼륨과 파일 또는 LUN 구성의 특정 조합이 사용할 수 있습니다. 이러한 조합을 통해 얻을 수 있는 이점과 비용을 이해하면 환경에 적합한 볼륨 및 LUN 구성의 조합을 결정하는 데 도움이 됩니다.

권장되는 볼륨 및 LUN 구성 조합은 다음과 같습니다.

* 일반 볼륨 프로비저닝이 있는 공간 예약 파일 또는 LUN
* 씬 볼륨 프로비저닝이 있는 공간 예약 파일이 아닌 LUN
* 반씩 볼륨 프로비저닝을 사용하는 공간 예약 파일 또는 LUN


이러한 구성 조합과 함께 LUN에서 SCSI 씬 프로비저닝을 사용할 수 있습니다.



== 일반 볼륨 프로비저닝이 있는 공간 예약 파일 또는 LUN

* 이점: *

* 공간 예약 파일 내의 모든 쓰기 작업이 보장되며 공간 부족으로 인해 작업이 실패하지 않습니다.
* 볼륨의 스토리지 효율성 및 데이터 보호 기술에는 제한이 없습니다.


* 비용 및 제한: *

* 전체적으로 프로비저닝된 볼륨을 지원할 수 있도록 충분한 공간을 집합체로부터 충분히 미리 설정해야 합니다.
* LUN 생성 시 볼륨에서 LUN의 2배에 해당하는 공간이 할당됩니다.




== 씬 볼륨 프로비저닝이 있는 공간 예약 파일이 아닌 LUN

* 이점: *

* 볼륨의 스토리지 효율성 및 데이터 보호 기술에는 제한이 없습니다.
* 공간은 사용되는 경우에만 할당됩니다.


* 비용 및 제한: *

* 쓰기 작업은 보장되지 않으며, 볼륨에 여유 공간이 없을 경우 실패할 수 있습니다.
* Aggregate에 여유 공간이 부족하지 않도록 하려면 Aggregate의 여유 공간을 효과적으로 관리해야 합니다.




== 반씩 볼륨 프로비저닝을 사용하는 공간 예약 파일 또는 LUN

* 이점: *

공간을 일반 볼륨 프로비저닝보다 미리 예약하므로 최선의 쓰기 보장이 제공됩니다.

* 비용 및 제한: *

* 이 옵션을 사용하면 쓰기 작업이 실패할 수 있습니다.
+
볼륨의 여유 공간과 데이터 휘발성의 균형을 적절하게 유지하여 이 위험을 완화할 수 있습니다.

* Snapshot 복사본, FlexClone 파일 및 LUN과 같은 데이터 보호 개체의 보존에는 의존할 수 없습니다.
* 중복제거, 압축, ODX/복사 오프로드 등 자동으로 삭제할 수 없는 ONTAP 블록 공유 스토리지 효율성 기능은 사용할 수 없습니다.

