---
permalink: san-admin/restore-all-luns-volume-snapshot-copy-task.html 
sidebar: sidebar 
keywords: restore, all, luns in a volume, from, snapshot copy 
summary: 볼륨 스냅샷 복원 명령을 사용하여 스냅샷 복사본에서 지정된 볼륨의 모든 LUN을 복원할 수 있습니다. 
---
= 스냅샷 복사본에서 볼륨의 모든 LUN을 복원합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
"volume snapshot restore" 명령을 사용하여 스냅샷 복사본에서 지정된 볼륨의 모든 LUN을 복원할 수 있습니다.

.단계
. 호스트에서 LUN에 대한 모든 호스트 액세스를 중지합니다.
+
볼륨에 있는 LUN에 대한 모든 호스트 액세스를 중지하지 않고 SnapRestore를 사용하면 데이터 손상 및 시스템 오류가 발생할 수 있습니다.

. 호스트에서 LUN을 액세스할 수 없도록 해당 호스트에서 LUN을 마운트 해제합니다.
. LUN 매핑 해제:
+
'LUN 매핑 삭제 - vserver_vserver_name_-volume_volume_name_-lun_lun_name_-igroup_igroup_name_'

. 볼륨을 복원할 스냅샷 복사본을 확인합니다.
+
'volume snapshot show -vserver_vserver_name_-volume_volume_name_'

. 권한 설정을 고급으로 변경합니다.
+
세트 프리빌리지 고급

. 데이터 복원:
+
'볼륨 스냅샷 복원 - vserver_vserver_name_-volume_volume_name_-snapshot_snapshot_name_'

. 화면의 지침을 따릅니다.
. LUN을 다시 매핑합니다.
+
'LUN 매핑 create-vserver_vserver_name_-volume_volume_name_-lun_lun_name_-igroup_igroup_name_'

. LUN이 온라인 상태인지 확인합니다.
+
'lun show -vserver_vserver_name_-path_lun_path_-fields state

. LUN이 온라인 상태가 아닌 경우 온라인 상태로 전환합니다.
+
'lun modify -vserver_vserver_name_-path_lun_path_-state online

. 권한 설정을 admin으로 변경합니다.
+
'Set-Privilege admin'입니다

. 호스트에서 LUN을 다시 마운트합니다.
. 호스트에서 LUN에 대한 액세스를 다시 시작합니다.

