---
permalink: san-admin/restore-single-lun-snapshot-copy-task.html 
sidebar: sidebar 
keywords: restore, single lun, snapshot copy 
summary: 단일 LUN이 포함된 전체 볼륨을 복원하지 않고 스냅샷 복사본에서 단일 LUN을 복원할 수 있습니다. LUN을 제자리에서 또는 볼륨의 새 경로로 복원할 수 있습니다. 이 작업은 볼륨의 다른 파일 또는 LUN에 영향을 주지 않고 단일 LUN만 복구합니다. 스트림을 사용하여 파일을 복원할 수도 있습니다. 
---
= 스냅샷 복사본에서 단일 LUN을 복원합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
단일 LUN이 포함된 전체 볼륨을 복원하지 않고 스냅샷 복사본에서 단일 LUN을 복원할 수 있습니다. LUN을 제자리에서 또는 볼륨의 새 경로로 복원할 수 있습니다. 이 작업은 볼륨의 다른 파일 또는 LUN에 영향을 주지 않고 단일 LUN만 복구합니다. 스트림을 사용하여 파일을 복원할 수도 있습니다.

.무엇을 &#8217;필요로 할거야
* 복원 작업을 완료하려면 볼륨에 충분한 공간이 있어야 합니다.
+
** 부분 예약 공간이 0%인 공간 예약 LUN을 복원하는 경우 복원된 LUN 크기의 1배가 필요합니다.
** 부분 예약 공간이 100%인 공간 예약 LUN을 복원하는 경우 복원된 LUN의 크기의 2배가 필요합니다.
** 공간이 예약되지 않은 LUN을 복원하는 경우 복원된 LUN에 사용된 실제 공간만 필요합니다.


* 대상 LUN의 스냅샷 복사본이 생성되었어야 합니다.
+
복구 작업이 실패하면 대상 LUN이 잘릴 수 있습니다. 이 경우 스냅샷 복사본을 사용하여 데이터 손실을 방지할 수 있습니다.

* 소스 LUN의 스냅샷 복사본이 생성되었어야 합니다.
+
드물지만 LUN 복구가 실패하여 소스 LUN을 사용할 수 없게 되는 경우가 있습니다. 이 경우 스냅샷 복사본을 사용하여 복원 시도 직전에 LUN을 상태로 되돌릴 수 있습니다.

* 대상 LUN과 소스 LUN의 OS 유형이 같아야 합니다.
+
대상 LUN의 OS 유형이 소스 LUN과 다른 경우 복구 작업 후 호스트가 대상 LUN에 대한 데이터 액세스를 잃을 수 있습니다.



.단계
. 호스트에서 LUN에 대한 모든 호스트 액세스를 중지합니다.
. 호스트에서 LUN을 액세스할 수 없도록 해당 호스트에서 LUN을 마운트 해제합니다.
. LUN 매핑을 해제합니다.
+
'LUN 매핑 삭제 - vserver_vserver_name_-volume_volume_name_-lun_lun_name_-igroup_igroup_name_'

. LUN을 복원할 스냅샷 복사본을 결정:
+
'volume snapshot show -vserver_vserver_name_-volume_volume_name_'

. LUN을 복원하기 전에 LUN의 스냅샷 복사본을 생성합니다.
+
'볼륨 스냅샷 생성 - vserver_vserver_name_-volume_volume_name_-snapshot_snapshot_name_'

. 볼륨에 지정된 LUN을 복구합니다.
+
'볼륨 스냅샷 복원 - 파일 - vserver_vserver_name_-volume_volume_name_-snapshot_snapshot_name_-path_lun_path_'

. 화면의 단계를 따릅니다.
. 필요한 경우 LUN을 온라인 상태로 전환합니다.
+
'lun modify -vserver_vserver_name_-path_lun_path_-state online

. 필요한 경우 LUN을 다시 매핑합니다.
+
'LUN 매핑 create-vserver_vserver_name_-volume_volume_name_-lun_lun_name_-igroup_igroup_name_'

. 호스트에서 LUN을 다시 마운트합니다.
. 호스트에서 LUN에 대한 액세스를 다시 시작합니다.

