---
permalink: san-admin/san-config-mcc-concept.html 
sidebar: sidebar 
keywords: metrocluster environments, considerations, san configuration, metrocluster, environments, san, configurations, cisco switch, brocade switch, 
summary: MetroCluster 환경에서 SAN 구성을 사용할 때는 몇 가지 고려 사항을 염두에 두어야 합니다. 
---
= MetroCluster 환경의 SAN 구성에 대한 고려 사항
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
MetroCluster 환경에서 SAN 구성을 사용할 때는 몇 가지 고려 사항을 염두에 두어야 합니다.

* MetroCluster 구성은 프런트엔드 FC 패브릭 ""라우팅된" vSAN 구성을 지원하지 않습니다.
* MetroCluster 구성은 프론트 엔드 NVMe 호스트 연결을 지원하지 않습니다.
* 다른 SAN 프로토콜은 MetroCluster 구성에서 지원됩니다.
* SAN 클라이언트 구성을 사용할 때는 상호 운용성 매트릭스 툴(IMT)에 제공된 노트에 MetroCluster 구성과 관련된 특별한 고려 사항이 포함되어 있는지 확인해야 합니다.
* 운영 체제 및 애플리케이션은 MetroCluster의 자동 계획되지 않은 전환 및 Tiebreaker 또는 중재자 시작 전환을 지원하기 위해 120초의 I/O 복원력을 제공해야 합니다.
* MetroCluster는 프런트엔드 SAN의 양쪽에 동일한 WWPN을 사용합니다.



NOTE: 스위치오버 중에 정상적인 사이트의 FC 포트가 패브릭에 로그인한 후 패브릭에서 재해 사이트의 FC 포트가 오프라인이며 이름 및 디렉토리 서비스에서 이 포트를 제거했습니다. 재해의 FC 포트가 아직 제거되지 않은 경우 중복 WWPN으로 인해 정상적인 사이트에서 FC 포트의 패브릭 로그인 시도가 거부될 수 있습니다. FC 스위치의 이러한 동작은 기존 디바이스가 아닌 이전 디바이스의 로그인을 사용하도록 변경할 수 있습니다. 이 동작이 다른 패브릭 디바이스에 미치는 영향을 확인해야 합니다. 자세한 내용은 스위치 공급업체에 문의하십시오.

자세한 내용은 다음을 참조하십시오.

* link:https://docs.netapp.com/us-en/ontap-metrocluster/manage/concept_understanding_mcc_data_protection_and_disaster_recovery.html["MetroCluster 데이터 보호 및 재해 복구 이해"]
* link:https://docs.netapp.com/us-en/ontap-metrocluster/manage/task_perform_switchover_for_tests_or_maintenance.html["테스트 또는 유지 관리를 위한 전환 수행"]


이전 포트가 오프라인이 되고 새 포트가 온라인 상태가 될 때 중첩되지 않도록 하려면 다음 단계를 사용하여 프런트엔드 스위치를 구성합니다.

[cols="20,80"]
|===


| 의 경우... | 다음 단계를 수행합니다. 


 a| 
Cisco 스위치
 a| 
. 스위치에 연결하고 로그인합니다.
. 구성 모드 시작:
+
....
switch# config t
switch(config)#
....
. 이름 서버 데이터베이스의 첫 번째 장치 항목을 새 장치로 덮어씁니다.
+
[listing]
----
switch(config)# no fcns reject-duplicate-pwwn vsan 1
----
. NX-OS 8.x를 실행 중인 스위치에서 flogi 일시 중지 시간 초과가 0으로 설정되었는지 확인합니다.
+
.. 일시 중지 시간 표시:
+
'스위치(config)# show flogi interval info | I quiesce'

+
....
 Stats:  fs flogi quiesce timerval:  0
....
.. 이전 단계의 출력이 시간 간격이 0임을 나타내지 않으면 0으로 설정합니다.
+
'Switch (config)#flogi scale enable'

+
'스위치(config)$flogi 시간 제한 0'







 a| 
Brocade 스위치
 a| 
. 스위치에 연결하고 로그인합니다.
. 'witchDisable' 명령어를 입력한다.
. configure 명령을 입력하고 프롬프트에 y를 누릅니다.
+
....
 F-Port login parameters (yes, y, no, n): [no] y
....
. 설정 1 선택:
+
....
- 0: First login take precedence over the second login (default)
- 1: Second login overrides first login.
- 2: the port type determines the behavior
Enforce FLOGI/FDISC login: (0..2) [0] 1
....
. 나머지 프롬프트에 응답하거나 * Ctrl+D * 를 누릅니다.
. 'witchEnable' 명령어를 입력한다.


|===
MetroCluster 관련 호스트 정보에 대한 자세한 내용은 다음 NetApp 기술 자료 문서를 참조하십시오.

https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/MetroCluster/What_are_AIX_Host_support_considerations_in_a_MetroCluster_configuration%3F["MetroCluster 구성에서 AIX 호스트 지원 고려 사항은 무엇입니까?"]

https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/MetroCluster/Solaris_host_support_considerations_in_a_MetroCluster_configuration["MetroCluster 구성에서 Solaris 호스트 지원 고려 사항"]

https://mysupport.netapp.com/matrix["NetApp 상호 운용성 매트릭스 툴"^]
