---
permalink: san-admin/selective-lun-map-concept.html 
sidebar: sidebar 
keywords: select, selective, lun, map, slm, enabled, modify, reporting, nodes, list 
summary: 'SLM(Selective LUN Map)은 호스트에서 LUN으로의 경로 수를 줄입니다. SLM 기능을 통해 새 LUN 맵이 생성되면 LUN 및 해당 HA 파트너를 소유하는 노드의 경로를 통해서만 LUN에 액세스할 수 있습니다.' 
---
= 선택적 LUN 맵 개요
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SLM(Selective LUN Map)은 호스트에서 LUN으로의 경로 수를 줄입니다. SLM 기능을 통해 새 LUN 맵이 생성되면 LUN 및 해당 HA 파트너를 소유하는 노드의 경로를 통해서만 LUN에 액세스할 수 있습니다.

SLM은 호스트당 단일 igroup을 관리할 수 있도록 하며, 포트셋 조작 또는 LUN 재매핑이 필요하지 않은 무중단 LUN 이동 작업도 지원합니다.

link:create-port-sets-binding-igroups-task.html["포트 세트"] SLM과 함께 사용하여 특정 타겟에 대한 액세스를 특정 이니시에이터에 더 제한할 수 있습니다. 포트 세트와 함께 SLM을 사용하는 경우 LUN을 소유한 노드의 HA 파트너와 해당 노드의 포트셋 LIF 세트에서 LUN에 액세스할 수 있습니다.

SLM은 모든 새로운 LUN 맵에서 기본적으로 활성화됩니다.



== LUN 맵에서 SLM이 설정되었는지 여부를 확인합니다

환경에 ONTAP 9 릴리즈에서 생성된 LUN과 이전 버전에서 전환된 LUN의 조합이 있는 경우, 특정 LUN에 SLM(선택적 LUN 맵)이 활성화되어 있는지 여부를 확인해야 할 수 있습니다.

의 출력에 표시된 정보를 사용할 수 있습니다 `lun mapping show -fields reporting-nodes, node` 명령을 사용하여 LUN 맵에서 SLM이 활성화되어 있는지 여부를 확인합니다. SLM이 활성화되지 않은 경우 명령 출력의 "노드 재이식" 열 아래의 셀에 "-"가 표시됩니다. SLM이 활성화된 경우 ""노드" 열 아래에 표시되는 노드 목록이 "노드 재이식" 열에 복제됩니다.



== SLM 보고 노드 목록을 수정합니다

LUN이 포함된 LUN 또는 볼륨을 동일한 클러스터 내의 다른 고가용성(HA) 쌍으로 이동하는 경우, 이동을 시작하기 전에 선택 LUN 맵(SLM: Selective LUN Map) 보고 노드 목록을 수정하여 최적화된 활성 LUN 경로가 유지되도록 해야 합니다.

.단계
. 대상 노드와 해당 파트너 노드를 애그리게이트 또는 볼륨의 보고 노드 목록에 추가합니다.
+
[source, cli]
----
lun mapping add-reporting-nodes -vserver <vserver_name> -path <lun_path> -igroup <igroup_name> [-destination-aggregate <aggregate_name>|-destination-volume <volume_name>]
----
+
일관된 명명 규칙이 있는 경우 대신 를 사용하여 여러 LUN 매핑을 동시에 수정할 수 있습니다 `igroup_prefix*` `igroup_name`.

. 호스트를 재검색하여 새로 추가된 경로를 검색합니다.
. OS에 필요한 경우 다중 경로 네트워크 I/O(MPIO) 구성에 새 경로를 추가합니다.
. 필요한 이동 작업에 대해 명령을 실행하고 작업이 완료될 때까지 기다립니다.
. Active/Optimized 경로를 통해 입출력이 서비스되고 있는지 확인합니다.
+
[source, cli]
----
lun mapping show -fields reporting-nodes
----
. 보고 노드 목록에서 이전 LUN 소유자 및 해당 파트너 노드를 제거합니다.
+
[source, cli]
----
lun mapping remove-reporting-nodes -vserver <vserver_name> -path <lun_path> -igroup <igroup_name> -remote-nodes
----
. LUN이 기존 LUN 맵에서 제거되었는지 확인합니다.
+
[source, cli]
----
lun mapping show -fields reporting-nodes
----
. 호스트 OS의 오래된 디바이스 항목을 제거합니다.
. 필요한 경우 경로 다중화 구성 파일을 변경합니다.
. 호스트를 재검색하여 이전 경로가 제거되었는지 확인합니다. + 호스트를 재검색하는 특정 단계는 호스트 설명서를 참조하십시오.

