---
permalink: san-admin/space-reserved-luns-semi-thick-provisioning-concept.html 
sidebar: sidebar 
keywords: configuration, settings, space-reserved files, luns, semi-thick, volume, provisioning 
summary: 이 FlexVol 볼륨 및 파일 또는 LUN 구성 조합을 사용하면 완전히 프로비저닝된 조합보다 더 적은 양의 스토리지를 미리 할당할 수 있지만 볼륨에 사용할 수 있는 효율성 기술에 제한이 있습니다. 이러한 구성 조합의 경우 덮어쓰기의 작업이 가장 효율적으로 처리됩니다. 
---
= 반씩 볼륨 프로비저닝을 사용하는 공간 예약 파일 또는 LUN에 대한 구성 설정입니다
:icons: font
:imagesdir: ../media/


[role="lead"]
이 FlexVol 볼륨 및 파일 또는 LUN 구성 조합을 사용하면 완전히 프로비저닝된 조합보다 더 적은 양의 스토리지를 미리 할당할 수 있지만 볼륨에 사용할 수 있는 효율성 기술에 제한이 있습니다. 이러한 구성 조합의 경우 덮어쓰기의 작업이 가장 효율적으로 처리됩니다.

반씩 프로비저닝을 사용하여 볼륨에서 공간 예약 LUN을 구성하려면 다음 설정이 필요합니다.

[cols="2*"]
|===
| 볼륨 설정 | 값 


 a| 
보장
 a| 
볼륨



 a| 
부분 예약
 a| 
0



 a| 
스냅숏 예비 공간입니다
 a| 
0



 a| 
스냅샷 자동 삭제
 a| 
제거 약속 수준에서는 모든 오브젝트, 볼륨으로 설정된 트리거, 자동 삭제를 위해 활성화된 모든 FlexClone LUN 및 FlexClone 파일이 포함된 제거 목록이 있습니다.



 a| 
자동 확장
 a| 
선택 사항: 사용하도록 설정한 경우 애그리게이트 가용 공간을 능동적으로 모니터링해야 합니다.

|===
[cols="2*"]
|===
| 파일 또는 LUN 설정 | 값 


 a| 
공간 예약
 a| 
활성화됨

|===


== 기술 제한

이 구성 조합에는 다음 볼륨 스토리지 효율성 기술을 사용할 수 없습니다.

* 압축
* 중복 제거
* ODX 및 FlexClone 복사 오프로드
* FlexClone LUN 및 FlexClone 파일이 자동 삭제용으로 표시되지 않음(활성 클론)
* FlexClone 하위 파일
* ODX/복사 오프로드




== 추가 고려 사항

이 구성 조합을 사용할 때는 다음 사항을 고려해야 합니다.

* 해당 LUN을 지원하는 볼륨의 공간이 적으면 보호 데이터(FlexClone LUN 및 파일, 스냅샷 복사본)가 제거됩니다.
* 볼륨에 여유 공간이 부족하면 쓰기 작업이 시간 초과되어 실패할 수 있습니다.


압축은 AFF 플랫폼에 대해 기본적으로 사용하도록 설정되어 있습니다. AFF 플랫폼에서 반씩 프로비저닝을 사용하려는 모든 볼륨에 대해 압축을 명시적으로 해제해야 합니다.
