---
permalink: san-admin/volume-config-options-concept.html 
sidebar: sidebar 
keywords: san, volume, configuration, options 
summary: LUN을 포함하는 볼륨에서 다양한 옵션을 설정해야 합니다. 볼륨 옵션을 설정하는 방법에 따라 볼륨의 LUN에서 사용할 수 있는 공간이 결정됩니다. 
---
= SAN 볼륨 구성 옵션
:icons: font
:imagesdir: ../media/


[role="lead"]
LUN을 포함하는 볼륨에서 다양한 옵션을 설정해야 합니다. 볼륨 옵션을 설정하는 방법에 따라 볼륨의 LUN에서 사용할 수 있는 공간이 결정됩니다.



== 자동 확장

자동 행을 활성화 또는 비활성화할 수 있습니다. 이 기능을 사용하도록 설정하면 ONTAP에서 볼륨 크기를 미리 결정한 최대 크기까지 자동으로 늘릴 수 있습니다. 볼륨의 자동 증가를 지원하려면 포함된 애그리게이트에 사용 가능한 공간이 있어야 합니다. 따라서 자동 확장 기능을 사용하도록 설정한 경우 포함된 애그리게이트의 여유 공간을 모니터링하고 필요 시 더 많은 공간을 추가해야 합니다.

스냅샷 생성을 지원하기 위해 자동 증가를 트리거할 수 없습니다. 스냅샷 복사본을 생성하려고 할 때 볼륨에 공간이 부족하면 자동 확장 기능을 설정해도 스냅샷 생성이 실패합니다.

자동 확장 기능을 비활성화하면 볼륨 크기는 동일하게 유지됩니다.



== 자동 축소

자동 축소를 사용하거나 사용하지 않도록 설정할 수 있습니다. 자동 축소를 사용하도록 설정하면 ONTAP에서 볼륨에서 사용된 공간 양이 미리 정해진 임계값을 줄일 때 볼륨의 전체 크기를 자동으로 줄일 수 있습니다. 따라서 볼륨을 트리거하여 사용되지 않는 여유 공간을 자동으로 릴리즈하여 스토리지 효율성이 향상됩니다.



== 스냅샷 자동 삭제

스냅샷 자동 삭제는 다음 중 하나가 발생할 경우 스냅샷 복사본을 자동으로 삭제합니다.

* 볼륨이 거의 꽉 찼습니다.
* 스냅샷 예약 공간이 거의 찼습니다.
* 덮어쓰기 예약 공간이 가득 찼습니다.


스냅샷 자동 삭제를 구성하여 스냅샷 복사본을 가장 오래된 것부터 최신 것까지, 또는 가장 최신 것에서부터 오래된 것까지 삭제할 수 있습니다. 스냅샷 자동 삭제는 클론 복제된 볼륨 또는 LUN의 스냅샷 복사본에 연결된 스냅샷 복사본을 삭제하지 않습니다.

볼륨에 추가 공간이 필요하고 자동 확장 및 스냅샷 자동 삭제를 모두 활성화한 경우, 기본적으로 ONTAP에서는 자동 확장 기능을 먼저 트리거하여 필요한 공간을 자동으로 구입하려고 시도합니다. 자동 삭제를 통해 충분한 공간을 확보하지 못하면 스냅샷 자동 삭제가 트리거됩니다.



== 스냅숏 예비 공간입니다

스냅샷 예약 공간은 스냅샷 복사본을 위해 예약된 볼륨의 공간을 정의합니다. 스냅숏 예비 공간에 할당된 공간은 다른 용도로 사용할 수 없습니다. 스냅샷 예약에 할당된 모든 공간이 사용되는 경우 스냅샷 복사본이 볼륨의 추가 공간을 사용하기 시작합니다.
