---
permalink: smb-config/commands-manage-ntp-servers-reference.html 
sidebar: sidebar 
keywords: ontap, network, time, protocol, ntp, version, support, ntpv3, symmetric, authentication, sha, security, commands for managing symmetric authentication on ntp servers 
summary: 'ONTAP 9.5부터 NTP(네트워크 시간 프로토콜) 버전 3이 지원됩니다. NTPv3에는 SHA-1 키를 사용한 대칭 인증이 포함되어 있어 네트워크 보안을 강화합니다.' 
---
= NTP 서버에서 대칭 인증을 관리하는 명령입니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9.5부터 NTP(네트워크 시간 프로토콜) 버전 3이 지원됩니다. NTPv3에는 SHA-1 키를 사용한 대칭 인증이 포함되어 있어 네트워크 보안을 강화합니다.

|===
| 수행할 작업... | 이 명령 사용... 


 a| 
대칭 인증 없이 NTP 서버를 구성합니다
 a| 
클러스터 시간 서비스 NTP 서버는 서버 서버 서버 서버 이름(server_name)을 만듭니다



 a| 
대칭 인증을 사용하여 NTP 서버를 구성합니다
 a| 
클러스터 시간 서비스 NTP 서버는 '-server''server_ip_address''-key-id''key_id'를 생성합니다



 a| 
기존 NTP 서버에 대칭 인증 사용 기존 NTP 서버는 필요한 키 ID를 추가하여 인증을 사용하도록 수정할 수 있습니다
 a| 
클러스터 시간서비스NTP 서버 수정 서버 서버 서버 서버 서버 서버 서버 서버 이름 키 ID 키 ID



 a| 
공유 NTP 키를 구성합니다
 a| 
클러스터 시간 서비스 NTP 키는 ``id’'sshared_key_id' -type'sshared_key_type' -value'sshared_key_value'를 만듭니다

[NOTE]
====
공유 키는 ID로 참조됩니다. ID, 유형 및 값은 노드와 NTP 서버 모두에서 동일해야 합니다

====


 a| 
알 수 없는 키 ID로 NTP 서버를 구성합니다
 a| 
클러스터 시간 서비스 NTP 서버는 서버 서버 서버 이름 키 ID 키 ID를 만듭니다



 a| 
NTP 서버에 키 ID가 구성되지 않은 서버를 구성합니다.
 a| 
클러스터 시간 서비스 NTP 서버는 서버 서버 서버 이름 키 ID 키 ID를 만듭니다

[NOTE]
====
키 ID, 유형 및 값은 NTP 서버에 구성된 키 ID, 유형 및 값과 동일해야 합니다.

====


 a| 
대칭 인증을 사용하지 않도록 설정합니다
 a| 
클러스터 시간서비스NTP 서버 수정 서버 서버 서버 서버 서버 서버 서버 이름 인증 비활성화

|===