---
permalink: smb-config/configure-ntfs-windows-security-tab-task.html 
sidebar: sidebar 
keywords: enable, file, access, user, group, share, configure, ntfs, permission, directories, directory, share, windows, client, configure ntfs file permissions in a share 
summary: 공유에 대한 액세스 권한이 있는 사용자 또는 그룹에 대한 파일 액세스를 설정하려면 Windows 클라이언트에서 공유하는 파일 및 디렉토리에 대한 NTFS 파일 권한을 구성해야 합니다. 
---
= 공유에서 NTFS 파일 권한을 구성합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
공유에 대한 액세스 권한이 있는 사용자 또는 그룹에 대한 파일 액세스를 설정하려면 Windows 클라이언트에서 공유하는 파일 및 디렉토리에 대한 NTFS 파일 권한을 구성해야 합니다.

이 작업을 수행하는 관리자는 선택한 개체에 대한 권한을 변경할 수 있는 충분한 NTFS 권한이 있어야 합니다.

link:../smb-admin/index.html["SMB 관리"] 및 Windows 설명서에는 표준 및 고급 NTFS 권한을 설정하는 방법에 대한 정보가 포함되어 있습니다.

.단계
. Windows 클라이언트에 관리자로 로그인합니다.
. Windows 탐색기의 * Tools * 메뉴에서 * Map network drive * 를 선택합니다.
. 네트워크 드라이브 매핑 * 상자를 완료합니다.
+
.. 드라이브 * 문자를 선택합니다.
.. 폴더 * 상자에 사용 권한을 적용할 데이터와 공유 이름을 포함하는 공유가 포함된 SMB 서버 이름을 입력합니다.
+
SMB 서버 이름이 smb_SERVER01이고 공유 이름이 "smb_SERVER01"이면 "\\smb_SERVER01\share1"을 입력합니다.

+
[NOTE]
====
SMB 서버 이름 대신 SMB 서버에 대한 데이터 인터페이스의 IP 주소를 지정할 수 있습니다.

====
.. 마침 * 을 클릭합니다.


+
선택한 드라이브가 마운트되고 공유 내에 포함된 파일 및 폴더를 표시하는 Windows 탐색기 창이 준비됩니다.

. NTFS 파일 권한을 설정할 파일 또는 디렉터리를 선택합니다.
. 파일 또는 디렉터리를 마우스 오른쪽 단추로 클릭한 다음 * 속성 * 을 선택합니다.
. 보안 * 탭을 선택합니다.
+
보안 탭에는 NTFS 권한이 설정된 사용자 및 그룹 목록이 표시됩니다. Object>에 대한 권한 상자에는 선택한 사용자 또는 그룹에 적용되는 허용 및 거부 권한 목록이 표시됩니다.

. 편집 * 을 클릭합니다.
+
Object> 사용 권한 상자가 열립니다.

. 원하는 작업을 수행합니다.
+
|===
| 원하는 경우 | 다음을 수행합니다. 


 a| 
새 사용자 또는 그룹에 대한 표준 NTFS 권한을 설정합니다
 a| 
.. 추가 * 를 클릭합니다.
+
사용자, 컴퓨터, 서비스 계정 또는 그룹 선택 창이 열립니다.

.. 선택할 개체 이름 입력 * 상자에 NTFS 권한을 추가할 사용자 또는 그룹의 이름을 입력합니다.
.. 확인 * 을 클릭합니다.




 a| 
사용자 또는 그룹에서 표준 NTFS 권한을 변경하거나 제거합니다
 a| 
그룹 또는 사용자 이름 * 상자에서 변경하거나 제거할 사용자 또는 그룹을 선택합니다.

|===
. 원하는 작업을 수행합니다.
+
|===
| 원하는 작업 | 다음을 수행합니다 


 a| 
새 사용자 또는 기존 사용자 또는 그룹에 대해 표준 NTFS 권한을 설정합니다
 a| 
Object>*에 대한 권한 상자에서 선택한 사용자 또는 그룹에 대해 허용하거나 허용하지 않을 액세스 유형에 대해 * 허용 * 또는 * 거부 * 상자를 선택합니다.



 a| 
사용자 또는 그룹을 제거합니다
 a| 
제거 * 를 클릭합니다.

|===
+
[NOTE]
====
일부 또는 모든 표준 권한 상자를 선택할 수 없는 경우 상위 개체에서 사용 권한이 상속되기 때문입니다. 특수 권한 * 상자는 선택할 수 없습니다. 이 옵션을 선택하면 선택한 사용자 또는 그룹에 대해 하나 이상의 세분화된 고급 권한이 설정되었음을 의미합니다.

====
. 해당 개체에 대한 NTFS 권한을 추가, 제거 또는 편집한 후 * 확인 * 을 클릭합니다.

