---
permalink: smb-config/create-server-workgroup-task.html 
sidebar: sidebar 
keywords: vserver, cifs, create, command, smb, server, workgroup, create an smb server in a workgroup 
summary: vserver cifs create 명령을 사용하여 SVM에 SMB 서버를 생성하고 이 서버가 속한 작업 그룹을 지정할 수 있습니다. 
---
= 워크그룹에 SMB 서버를 생성합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
"vserver cifs create" 명령을 사용하여 SVM에 SMB 서버를 생성하고 해당 서버가 속한 작업 그룹을 지정할 수 있습니다.

.시작하기 전에
데이터 제공을 위해 사용하는 SVM 및 LIF는 SMB 프로토콜을 허용하도록 구성되어 있어야 합니다. LIF는 SVM에 구성된 DNS 서버에 연결할 수 있어야 합니다.

.이 작업에 대해
워크그룹 모드의 SMB 서버는 다음 SMB 기능을 지원하지 않습니다.

* SMB3 Witness 프로토콜
* SMB3 CA 공유
* SMB를 통한 SQL
* 폴더 리디렉션
* 로밍 프로필
* GPO(그룹 정책 개체)
* VSS(볼륨 스냅샷 서비스)


'vserver cifs' man 페이지에는 추가 옵션 구성 매개 변수 및 명명 요구 사항이 포함되어 있습니다.

.단계
. smb 라이센스가 클러스터에 있는지 확인합니다: 'system license show-package cifs'
+
SMB 라이센스는 에 포함되어 link:../system-admin/manage-licenses-concept.html#licenses-included-with-ontap-one["ONTAP 1 을 참조하십시오"]있습니다. ONTAP One이 없고 라이선스가 설치되지 않은 경우 영업 담당자에게 문의하십시오.

+
SMB 서버가 인증용으로만 사용되는 경우에는 CIFS 라이센스가 필요하지 않습니다.

. 워크그룹에서 SMB 서버를 생성합니다. 'vserver cifs create-vserver vserver_name-cifs-server cifs_server_name-workgroup workgroup_name[-comment text]'
+
다음 명령을 실행하면 워크그룹 workgroup01에 SMB 서버 "smb_server01"이 생성됩니다.

+
[listing]
----
cluster1::> vserver cifs create -vserver vs1.example.com -cifs-server SMB_SERVER01 -workgroup workgroup01
----
. 'vserver cifs show' 명령을 사용하여 SMB 서버 구성을 확인합니다.
+
다음 예제에서 명령 출력은 "'workgroup01'" 워크그룹의 SVM vs1.example.com 에서 "'smb_server01'" 이름의 SMB 서버가 생성되었음을 보여 줍니다.

+
[listing]
----
cluster1::> vserver cifs show -vserver vs0

                                          Vserver: vs1.example.com
                         CIFS Server NetBIOS Name: SMB_SERVER01
                    NetBIOS Domain/Workgroup Name: workgroup01
                      Fully Qualified Domain Name: -
                              Organizational Unit: -
Default Site Used by LIFs Without Site Membership: -
                                   Workgroup Name: workgroup01
                             Authentication Style: workgroup
                CIFS Server Administrative Status: up
                          CIFS Server Description:
                          List of NetBIOS Aliases: -
----


.작업을 마친 후
작업 그룹의 CIFS 서버의 경우 SVM에서 로컬 사용자와 로컬 그룹을 생성해야 합니다(선택 사항).

.관련 정보
link:../smb-admin/index.html["SMB 관리"]
