---
permalink: smb-config/create-server-active-directory-domain-task.html 
sidebar: sidebar 
keywords: vserver, cifs, create, command, smb, server, svm, specify, active, directory, ad, domain, create an smb server in an active directory domain 
summary: 'vserver cifs create 명령을 사용하여 SVM에 SMB 서버를 생성하고 이 서버가 속한 AD(Active Directory) 도메인을 지정할 수 있습니다.' 
---
= Active Directory 도메인에서 SMB 서버를 생성합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
"vserver cifs create" 명령을 사용하여 SVM에 SMB 서버를 생성하고 해당 서버가 속한 AD(Active Directory) 도메인을 지정할 수 있습니다.

.시작하기 전에
데이터 제공을 위해 사용하는 SVM 및 LIF는 SMB 프로토콜을 허용하도록 구성되어 있어야 합니다. LIF는 SVM에 구성된 DNS 서버와 SMB 서버에 연결할 도메인의 AD 도메인 컨트롤러에 연결할 수 있어야 합니다.

SMB 서버에 연결할 AD 도메인에서 시스템 계정을 만들 수 있는 권한이 있는 모든 사용자는 SVM에 SMB 서버를 생성할 수 있습니다. 여기에는 다른 도메인의 사용자가 포함될 수 있습니다.

ONTAP 9.7부터 AD 관리자는 권한이 있는 Windows 계정에 이름과 암호를 제공하는 대신 keytab 파일에 대한 URI를 제공할 수 있습니다. URI를 받으면 '-keytab-Uri' 매개 변수에 vserver cifs' 명령을 포함하여 포함시키십시오.

.이 작업에 대해
Activity Directory 도메인에서 SMB 서버를 생성하는 경우:

* 도메인을 지정할 때는 FQDN(정규화된 도메인 이름)을 사용해야 합니다.
* 기본 설정은 Active Directory CN=Computer 개체에 SMB 서버 컴퓨터 계정을 추가하는 것입니다.
* '-ou' 옵션을 사용하여 SMB 서버를 다른 OU(조직 구성 단위)에 추가하도록 선택할 수 있습니다.
* SMB 서버에 대해 쉼표로 구분된 하나 이상의 NetBIOS 별칭 목록(최대 200)을 추가하도록 선택할 수도 있습니다.
+
SMB 서버에 대한 NetBIOS 별칭을 구성하면 다른 파일 서버의 데이터를 SMB 서버로 통합할 때 SMB 서버가 원래 서버의 이름에 응답하도록 할 때 유용합니다.



'vserver cifs' man 페이지에는 추가 옵션 매개 변수 및 명명 요구 사항이 포함되어 있습니다.

[NOTE]
====
ONTAP 9.1부터 SMB 버전 2.0을 사용하여 DC(도메인 컨트롤러)에 연결할 수 있습니다. 도메인 컨트롤러에서 SMB 1.0을 사용하지 않도록 설정한 경우 이 작업이 필요합니다. ONTAP 9.2부터는 SMB 2.0이 기본적으로 사용하도록 설정됩니다.

====
ONTAP 9.8부터 도메인 컨트롤러에 대한 연결이 암호화되도록 지정할 수 있습니다. ONTAP는 `-encryption-required-for-dc-connection' 옵션이 true로 설정되어 있을 때 도메인 컨트롤러 통신을 암호화해야 하며 기본값은 false입니다. SMB3에서만 암호화가 지원되므로 이 옵션을 설정하면 SMB3 프로토콜만 ONTAP-DC 연결에 사용됩니다. .

link:../smb-admin/index.html["SMB 관리"] SMB 서버 구성 옵션에 대한 자세한 내용은 에 나와 있습니다.

.단계
. smb 라이센스가 클러스터에 있는지 확인합니다: 'system license show-package cifs'
+
SMB 라이센스는 에 포함되어 있습니다 link:https://docs.netapp.com/us-en/ontap/system-admin/manage-licenses-concept.html#licenses-included-with-ontap-one["ONTAP 1 을 참조하십시오"]. ONTAP One이 없고 라이선스가 설치되지 않은 경우 영업 담당자에게 문의하십시오.

+
SMB 서버가 인증용으로만 사용되는 경우에는 CIFS 라이센스가 필요하지 않습니다.

. AD 도메인에서 SMB 서버를 생성합니다.(+ vserver cifs create -vserver vserver_name -cifs -server smb_server_name -domain FQDN [-ou 조직_unit] [-NetBIOS-별칭 netbios_name,...] [-keytab -Uri {(ftp | http)://hostname | ip_address}] [-comment text]+'
+
도메인에 참가할 때 이 명령을 완료하는 데 몇 분 정도 걸릴 수 있습니다.

+
다음 명령을 실행하면 도메인 " example.com`": 에 SMB 서버 "'smb_server01'"이 생성됩니다

+
[listing]
----
cluster1::> vserver cifs create -vserver vs1.example.com -cifs-server smb_server01 -domain example.com
----
+
다음 명령을 실행하면 도메인 "mydomain.com`" 에 SMB 서버 "sMB_server02"가 생성되고 keytab 파일을 사용하여 ONTAP 관리자를 인증합니다.

+
[listing]
----
cluster1::> vserver cifs create -vserver vs1.mydomain.com -cifs-server smb_server02 -domain mydomain.com -keytab-uri http://admin.mydomain.com/ontap1.keytab
----
. 'vserver cifs show' 명령을 사용하여 SMB 서버 구성을 확인합니다.
+
이 예제에서 명령 출력은 "'sMB_SERVER01'"이라는 SMB 서버가 SVM vs1.example.com 에서 생성되어 "'example.com`" 도메인에 가입된 것을 보여 줍니다.

+
[listing]
----
cluster1::> vserver cifs show -vserver vs1

                                          Vserver: vs1.example.com
                         CIFS Server NetBIOS Name: SMB_SERVER01
                    NetBIOS Domain/Workgroup Name: EXAMPLE
                      Fully Qualified Domain Name: EXAMPLE.COM
Default Site Used by LIFs Without Site Membership:
                             Authentication Style: domain
                CIFS Server Administrative Status: up
                          CIFS Server Description: -
                          List of NetBIOS Aliases: -
----
. 필요한 경우 도메인 컨트롤러(ONTAP 9.8 이상)와의 암호화된 통신을 활성화합니다. 'vserver cifs security modify -vserver svm_name -encryption -required-for-dc-connection true'


.예
다음 명령을 실행하면 ""example.com`"" 도메인의 SVM vs2.example.com 에 "sMB_server02" 이름의 SMB 서버가 생성됩니다. 컴퓨터 계정은 ""OU=ENG,OU=Corp,DC=example,DC=com" 컨테이너에 생성됩니다. SMB 서버에는 NetBIOS 별칭이 할당됩니다.

[listing]
----
cluster1::> vserver cifs create -vserver vs2.example.com –cifs-server smb_server02 -domain example.com –ou OU=eng,OU=corp -netbios-aliases old_cifs_server01

cluster1::> vserver cifs show -vserver vs1
                                          Vserver: vs2.example.com
                         CIFS Server NetBIOS Name: SMB_SERVER02
                    NetBIOS Domain/Workgroup Name: EXAMPLE
                      Fully Qualified Domain Name: EXAMPLE.COM
Default Site Used by LIFs Without Site Membership:
                             Authentication Style: domain
                CIFS Server Administrative Status: up
                          CIFS Server Description: -
                          List of NetBIOS Aliases: OLD_CIFS_SERVER01
----
다음 명령을 사용하면 다른 도메인의 사용자(이 경우 신뢰할 수 있는 도메인 관리자)가 SVM vs3.example.com 에 "'smb_server03" 이름의 SMB 서버를 생성할 수 있습니다. '-domain' 옵션은 SMB 서버를 생성하려는 홈 도메인(DNS 구성에 지정됨)의 이름을 지정합니다. 사용자 이름 옵션은 신뢰할 수 있는 도메인의 관리자를 지정합니다.

* 홈 도메인: example.com
* 신뢰할 수 있는 도메인: trust.lab.com
* 신뢰할 수 있는 도메인의 사용자 이름: Administrator1


[listing]
----
cluster1::> vserver cifs create -vserver vs3.example.com -cifs-server smb_server03 -domain example.com

Username: Administrator1@trust.lab.com
Password: . . .
----