---
permalink: smb-config/create-local-user-accounts-task.html 
sidebar: sidebar 
keywords: create, local, user, account, authorize, access, data, contain, svm, sb, connection, local, user, authentication, create local user accounts 
summary: SMB 연결을 통해 SVM에 포함된 데이터에 대한 액세스를 승인하는 데 사용할 수 있는 로컬 사용자 계정을 생성할 수 있습니다. SMB 세션을 생성할 때 인증에 로컬 사용자 계정을 사용할 수도 있습니다. 
---
= 로컬 사용자 계정을 생성합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SMB 연결을 통해 SVM에 포함된 데이터에 대한 액세스를 승인하는 데 사용할 수 있는 로컬 사용자 계정을 생성할 수 있습니다. SMB 세션을 생성할 때 인증에 로컬 사용자 계정을 사용할 수도 있습니다.

SVM이 생성되면 로컬 사용자 기능이 기본적으로 활성화됩니다.

로컬 사용자 계정을 생성할 때 사용자 이름을 지정해야 하며 계정을 연결할 SVM을 지정해야 합니다.

'vserver cifs users-and-groups local-user' man 페이지에는 선택적 매개 변수 및 명명 요구 사항에 대한 세부 정보가 포함되어 있습니다.

.단계
. 로컬 사용자:'vserver cifs users-and-groups local-user create-vserver_vserver_name_-user-name_user_name__optional_parameters_'를 생성합니다
+
다음과 같은 선택적 매개 변수가 유용할 수 있습니다.

+
** 이름
+
사용자의 전체 이름입니다.

** ``설명’’
+
로컬 사용자에 대한 설명입니다.

** '-is-account-disabled{true|false}'
+
사용자 계정의 사용 여부를 지정합니다. 이 매개 변수를 지정하지 않으면 기본값은 사용자 계정을 활성화하는 것입니다.



+
명령을 실행하면 로컬 사용자 암호를 묻는 메시지가 표시됩니다.

. 로컬 사용자의 암호를 입력한 다음 암호를 확인합니다.
. 사용자가 성공적으로 생성되었는지 확인합니다. 'vserver cifs users-and-groups local-user show -vserver_vserver_name_'


다음 예에서는 SVM vs1.example.com 과 관련된 "sUE Chang"이라는 전체 이름으로 로컬 사용자 "sMB_SERVER01\sue"를 생성합니다.

[listing]
----
cluster1::> vserver cifs users-and-groups local-user create -vserver vs1.example.com ‑user-name SMB_SERVER01\sue -full-name "Sue Chang"

Enter the password:
Confirm the password:

cluster1::> vserver cifs users-and-groups local-user show
Vserver  User Name                  Full Name  Description
-------- -------------------------- ---------- -------------
vs1      SMB_SERVER01\Administrator            Built-in administrator account
vs1      SMB_SERVER01\sue            Sue Chang
----