---
permalink: smb-config/create-svms-data-access-task.html 
sidebar: sidebar 
keywords: svm, cluster, data, access, smb, client, create, create an svm 
summary: SMB 클라이언트에 데이터 액세스를 제공하기 위해 클러스터에 SVM을 하나 이상 가지고 있지 않은 경우 하나 생성해야 합니다. 
---
= SVM을 생성합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SMB 클라이언트에 데이터 액세스를 제공하기 위해 클러스터에 SVM을 하나 이상 가지고 있지 않은 경우 하나 생성해야 합니다.

.시작하기 전에
* ONTAP 9.13.1 부터는 스토리지 VM의 최대 용량을 설정할 수 있습니다. SVM이 임계값 용량 수준에 도달할 경우에도 경고를 구성할 수 있습니다. 자세한 내용은 을 참조하십시오 xref:../system-admin/manage-svm-capacity.html[SVM 용량 관리].


.단계
. SVM 생성: `vserver create -vserver _svm_name_ -rootvolume _root_volume_name_ -aggregate _aggregate_name_ -rootvolume-security-style ntfs -language C.UTF-8 -ipspace _ipspace_name_`
+
** '-rootvolume-security-style' 옵션에 NTFS 설정을 사용합니다.
** 기본 C. UTF-8 '-language' 옵션을 사용합니다.
** IPSpace 설정은 선택 사항입니다.


. 새로 생성한 SVM의 구성 및 상태 확인: `vserver show -vserver _vserver_name_`
+
허용되는 프로토콜 필드에는 CIFS가 포함되어야 합니다. 나중에 이 목록을 편집할 수 있습니다.

+
'Vserver 작동 상태' 필드에는 '실행 중' 상태가 표시되어야 합니다. 초기화 중 상태가 표시되는 경우 루트 볼륨 생성 등 일부 중간 작업이 실패한 것으로, SVM을 삭제하고 다시 생성해야 합니다.



.예
다음 명령은 IPspace에서 데이터 액세스를 위한 SVM을 생성합니다 `ipspaceA`:

[listing]
----
cluster1::> vserver create -vserver vs1.example.com -rootvolume root_vs1 -aggregate aggr1
-rootvolume-security-style ntfs -language C.UTF-8 -ipspace ipspaceA

[Job 2059] Job succeeded:
Vserver creation completed
----
다음 명령을 실행하면 루트 볼륨 1GB 단위로 SVM이 생성되고 자동으로 시작되어 '실행 중' 상태에 있음을 알 수 있습니다. 루트 볼륨에는 규칙을 포함하지 않는 기본 엑스포트 정책이 있으므로 생성 시 루트 볼륨을 내보내지 않습니다.

[listing]
----
cluster1::> vserver show -vserver vs1.example.com
                                    Vserver: vs1.example.com
                               Vserver Type: data
                            Vserver Subtype: default
                               Vserver UUID: b8375669-19b0-11e5-b9d1-00a0983d9736
                                Root Volume: root_vs1
                                  Aggregate: aggr1
                                 NIS Domain: -
                 Root Volume Security Style: ntfs
                                LDAP Client: -
               Default Volume Language Code: C.UTF-8
                            Snapshot Policy: default
                                    Comment:
                               Quota Policy: default
                List of Aggregates Assigned: -
 Limit on Maximum Number of Volumes allowed: unlimited
                        Vserver Admin State: running
                  Vserver Operational State: running
   Vserver Operational State Stopped Reason: -
                          Allowed Protocols: nfs, cifs, fcp, iscsi, ndmp
                       Disallowed Protocols: -
                           QoS Policy Group: -
                                Config Lock: false
                               IPspace Name: ipspaceA
----

NOTE: ONTAP 9.13.1 부터는 SVM의 볼륨에 처리량 플로어 및 최대 한도를 적용하여 적응형 QoS 정책 그룹 템플릿을 설정할 수 있습니다. SVM을 생성한 후에만 이 정책을 적용할 수 있습니다. 이 프로세스에 대한 자세한 내용은 을 참조하십시오 xref:../performance-admin/adaptive-policy-template-task.html[적응형 정책 그룹 템플릿을 설정합니다].
