---
permalink: smb-config/open-export-policy-svm-root-volume-task.html 
sidebar: sidebar 
keywords: default, export, policy, svm, root, volume, rule, client, smb, rule, open the export policy of the svm root volume 
summary: SVM 루트 볼륨의 기본 엑스포트 정책에는 SMB를 통한 모든 클라이언트의 개방형 액세스를 지원하는 규칙이 포함되어야 합니다. 이러한 규칙이 없으면 모든 SMB 클라이언트가 SVM 및 해당 볼륨에 대한 액세스가 거부됩니다. 
---
= SVM 루트 볼륨의 엑스포트 정책을 엽니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SVM 루트 볼륨의 기본 엑스포트 정책에는 SMB를 통한 모든 클라이언트의 개방형 액세스를 지원하는 규칙이 포함되어야 합니다. 이러한 규칙이 없으면 모든 SMB 클라이언트가 SVM 및 해당 볼륨에 대한 액세스가 거부됩니다.

새 SVM이 생성되면 SVM의 루트 볼륨에 대한 기본 엑스포트 정책(기본값)이 자동으로 생성됩니다. 클라이언트가 SVM에서 데이터에 액세스하려면 기본 엑스포트 정책에 대한 규칙을 하나 이상 생성해야 합니다.

모든 SMB 액세스가 기본 엑스포트 정책에서 열려 있는지 확인하고, 나중에 개별 볼륨 또는 qtree에 대한 사용자 지정 엑스포트 정책을 생성하여 개별 볼륨에 대한 액세스를 제한해야 합니다.

.단계
. 기존 SVM을 사용하는 경우 기본 루트 볼륨 엑스포트 정책('vserver export-policy rule show')을 확인하십시오
+
명령 출력은 다음과 같아야 합니다.

+
[listing]
----

cluster::> vserver export-policy rule show -vserver vs1.example.com -policyname default -instance

                                    Vserver: vs1.example.com
                                Policy Name: default
                                 Rule Index: 1
                            Access Protocol: cifs
Client Match Hostname, IP Address, Netgroup, or Domain: 0.0.0.0/0
                             RO Access Rule: any
                             RW Access Rule: any
User ID To Which Anonymous Users Are Mapped: 65534
                   Superuser Security Types: any
               Honor SetUID Bits in SETATTR: true
                  Allow Creation of Devices: true
----
+
이러한 규칙이 열려 있는 액세스를 허용하는 경우 이 작업은 완료된 것입니다. 그렇지 않은 경우 다음 단계를 진행하십시오.

. SVM 루트 볼륨에 대한 엑스포트 규칙을 생성합니다. 'vserver export-policy rule create-vserver vserver_name-policyname default-ruleindex 1-protocol cifs-clientmatch 0.0.0.0/0 -rorule any-rwrule any-superuser any'입니다
. 'vserver export-policy rule show' 명령을 사용하여 규칙 생성을 확인합니다.


이제 모든 SMB 클라이언트가 SVM에서 생성된 모든 볼륨 또는 qtree에 액세스할 수 있습니다.
