---
permalink: smb-config/verify-enabled-versions-task.html 
sidebar: sidebar 
keywords: ontap, release, smb, version, enable, default, connection, client, domain, controller, controller, verify, support, functionality, environment, verify enabled smb versions, can smb1 be enabled in ontap 9 
summary: ONTAP 9.0 이상에서는 SMB 2.0이 기본적으로 사용됩니다.  SMB 1.0은 사용 중인 ONTAP 버전에 따라 기본적으로 활성화되어 있습니다 
---
= 활성화된 SMB 버전을 확인합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9 릴리즈에서는 클라이언트 및 도메인 컨트롤러와의 연결에 대해 기본적으로 설정되는 SMB 버전을 결정합니다. SMB 서버가 사용자 환경에 필요한 클라이언트 및 기능을 지원하는지 확인해야 합니다.

.이 작업에 대해
클라이언트 및 도메인 컨트롤러 모두에 연결하는 경우 가능하면 SMB 2.0 이상을 활성화해야 합니다. 보안상의 이유로 SMB 1.0은 사용하지 않는 것이 좋습니다. 사용자 환경에서 필요하지 않은 것으로 확인된 경우에는 사용하지 않도록 설정해야 합니다.

ONTAP 9에서는 SMB 버전 2.0 이상이 클라이언트 연결에 대해 기본적으로 활성화되어 있지만 기본적으로 활성화되어 있는 SMB 1.0 버전은 ONTAP 릴리스에 따라 다릅니다.

* ONTAP 9.1 P8부터 SMB 1.0을 SVM에서 비활성화할 수 있습니다.
+
vserver cifs options modify 명령에 대한 '-SMB1-enabled' 옵션은 SMB 1.0을 활성화하거나 비활성화합니다.

* ONTAP 9.3부터는 새 SVM에서 기본적으로 비활성화되어 있습니다.


SMB 서버가 AD(Active Directory) 도메인에 있는 경우 SMB 2.0이 ONTAP 9.1부터 시작하는 DC(도메인 컨트롤러)에 연결되도록 설정할 수 있습니다. DC에서 SMB 1.0을 사용하지 않도록 설정한 경우 이 작업이 필요합니다. ONTAP 9.2부터는 SMB 2.0이 DC 연결에 대해 기본적으로 사용하도록 설정됩니다.

[NOTE]
====
SMB1-enabled-for-dc-connections가 false로 설정되어 있고 -SMB1-enabled가 true로 설정되어 있으면 ONTAP는 SMB 1.0 연결을 클라이언트로 거부하지만 인바운드 SMB 1.0 연결을 서버로 계속 허용합니다.

====
link:../smb-admin/index.html["SMB 관리"] 지원되는 SMB 버전 및 기능에 대한 자세한 내용은 에 나와 있습니다.

.단계
. 권한 수준을 고급으로 설정합니다.
+
[source, cli]
----
set -privilege advanced
----
. 활성화된 SMB 버전을 확인합니다.
+
[source, cli]
----
vserver cifs options show
----
+
목록을 아래로 스크롤하여 클라이언트 연결에 대해 설정된 SMB 버전을 볼 수 있으며 AD 도메인 연결에 대해 AD 도메인에서 SMB 서버를 구성하는 경우

. 필요에 따라 클라이언트 연결에 대해 SMB 프로토콜을 설정하거나 해제합니다.
+
** SMB 버전 활성화하기:
+
[source, cli]
----
vserver cifs options modify -vserver vserver_name smb_version true
----
** SMB 버전을 사용하지 않도록 설정하려면:
+
[source, cli]
----
vserver cifs options modify -vserver vserver_name smb_version false
----
+
에 사용할 수 있는 값 `smb_version`:

+
*** '-SMB1-활성화됨'
*** '-SMB2-ENABLED'입니다
*** '-SMB3-enabled'입니다
*** `-smb31-enabled`




+
다음 명령을 실행하면 SVM vs1.example.com 에서 SMB 3.1이 활성화됩니다.



[listing]
----
cluster1::*> vserver cifs options modify -vserver vs1.example.com -smb31-enabled true
----
. SMB 서버가 Active Directory 도메인에 있는 경우 필요에 따라 DC 연결에 대한 SMB 프로토콜을 설정하거나 해제합니다.
+
** SMB 버전 활성화하기:
+
[source, cli]
----
vserver cifs security modify -vserver vserver_name -smb2-enabled-for-dc-connections true
----
** SMB 버전을 사용하지 않도록 설정하려면:
+
[source, cli]
----
vserver cifs security modify -vserver vserver_name -smb2-enabled-for-dc-connections false
----


. 관리자 권한 레벨로 돌아갑니다.
+
[source, cli]
----
set -privilege admin
----

