---
permalink: smb-config/worksheet-reference.html 
sidebar: sidebar 
keywords: smb, configuration, worksheet, enable, collect, require, information, access, client, worksheet, gather, cifs, worksheet for gathering SMB configuration information 
summary: SMB 구성 워크시트를 사용하면 클라이언트에 대한 SMB 액세스를 설정하는 데 필요한 정보를 수집할 수 있습니다. 
---
= SMB 구성 정보 수집을 위한 워크시트입니다
:icons: font
:imagesdir: ../media/


[role="lead"]
SMB 구성 워크시트를 사용하면 클라이언트에 대한 SMB 액세스를 설정하는 데 필요한 정보를 수집할 수 있습니다.

스토리지 용량 할당 위치에 대한 결정에 따라 워크시트의 섹션 중 하나 또는 두 섹션을 모두 완료해야 합니다.

* SVM에 대한 SMB 액세스를 구성하는 경우 두 섹션을 모두 완료해야 합니다.
+
xref:configure-access-svm-task.adoc[SVM에 대한 SMB 액세스 구성]

+
xref:configure-client-access-shared-storage-concept.adoc[공유 스토리지에 대한 SMB 클라이언트 액세스 구성]

* SMB 지원 SVM에 스토리지 용량을 추가하려면 두 번째 섹션만 완료해야 합니다.
+
xref:configure-client-access-shared-storage-concept.adoc[공유 스토리지에 대한 SMB 클라이언트 액세스 구성]



명령 man 페이지에는 매개 변수에 대한 세부 정보가 포함되어 있습니다.



== SVM에 대한 SMB 액세스 구성

* SVM 생성을 위한 매개 변수 *

새 SVM을 생성하는 경우 이러한 값을 'vserver create' 명령으로 제공합니다.

|===
| 필드에 입력합니다 | 설명 | 귀사의 가치 


 a| 
'-vserver'
 a| 
FQDN(정규화된 도메인 이름)이거나 클러스터 전체에 고유한 SVM 이름을 적용하는 다른 규칙을 따르는 새 SVM에 대해 제공하는 이름입니다.
 a| 



 a| 
'-집계'
 a| 
새 SMB 스토리지 용량을 위한 충분한 공간이 있는 클러스터의 애그리게이트 이름입니다.
 a| 



 a| 
'-rootvolume'
 a| 
SVM 루트 볼륨에 제공하는 고유 이름입니다.
 a| 



 a| 
'-rootvolume-security-style'
 a| 
SVM에 NTFS 보안 스타일을 사용하십시오.
 a| 
NTFS



 a| 
'-언어'
 a| 
이 워크플로의 기본 언어 설정을 사용합니다.
 a| 
C. UTF-8



 a| 
'IPSpace'
 a| 
선택 사항: IPspace는 SVM이 상주하는 별개의 IP 주소 공간입니다.
 a| 

|===
* LIF 생성을 위한 매개 변수 *

LIF를 생성할 때 이러한 값을 'network interface create' 명령으로 제공합니다.

|===
| 필드에 입력합니다 | 설명 | 귀사의 가치 


 a| 
'-lif'
 a| 
새 LIF에 대해 제공한 이름입니다.
 a| 



 a| 
'-역할'
 a| 
이 워크플로우에서 데이터 LIF 역할을 사용합니다.
 a| 
다타



 a| 
'-데이터-프로토콜'
 a| 
이 워크플로우에서는 SMB 프로토콜만 사용합니다.
 a| 
'CIFS'입니다



 a| 
홈 노드
 a| 
LIF에서 '네트워크 인터페이스 되돌리기' 명령을 실행할 때 LIF가 반환되는 노드입니다.
 a| 



 a| 
``홈 포트’’
 a| 
LIF에서 '네트워크 인터페이스 되돌리기' 명령을 실행하면 LIF가 반환되는 포트 또는 인터페이스 그룹입니다.
 a| 



 a| 
주소
 a| 
새 LIF가 데이터 액세스에 사용할 클러스터의 IPv4 또는 IPv6 주소입니다.
 a| 



 a| 
넷마스크입니다
 a| 
LIF의 네트워크 마스크와 게이트웨이입니다.
 a| 



 a| 
'-서브넷'
 a| 
IP 주소 풀입니다. 주소와 넷마스크를 자동으로 할당하기 위해 -address와 -netmask 대신 사용됩니다.
 a| 



 a| 
방화벽 정책
 a| 
이 워크플로우에서 기본 데이터 방화벽 정책을 사용합니다.
 a| 
다타



 a| 
자동 되돌리기
 a| 
선택 사항: 데이터 LIF가 시작 시 또는 다른 상황에서 홈 노드로 자동 전환되는지 여부를 지정합니다. 기본 설정은 false입니다.
 a| 

|===
* DNS 호스트 이름 확인을 위한 매개 변수 *

DNS를 구성할 때 이러한 값을 'vserver services name-service dns create' 명령으로 제공합니다.

|===
| 필드에 입력합니다 | 설명 | 귀사의 가치 


 a| 
``도메인’
 a| 
최대 5개의 DNS 도메인 이름
 a| 



 a| 
이름-서버
 a| 
각 DNS 이름 서버에 대해 최대 3개의 IP 주소를 지정할 수 있습니다.
 a| 

|===


== Active Directory 도메인에서 SMB 서버 설정

시간 서비스 구성에 대한 매개 변수 *

시간 서비스를 구성할 때 이러한 값을 'cluster time-service ntp server create' 명령으로 제공합니다.

|===
| 필드에 입력합니다 | 설명 | 귀사의 가치 


 a| 
'-서버'
 a| 
Active Directory 도메인에 대한 NTP 서버의 호스트 이름 또는 IP 주소입니다.
 a| 

|===
* Active Directory 도메인에서 SMB 서버를 생성하기 위한 매개 변수 *

새 SMB 서버를 생성하고 도메인 정보를 지정할 때 이러한 값을 'vserver cifs create' 명령으로 제공합니다.

|===
| 필드에 입력합니다 | 설명 | 귀사의 가치 


 a| 
'-vserver'
 a| 
SMB 서버를 생성할 SVM의 이름입니다.
 a| 



 a| 
'-cifs-server'
 a| 
SMB 서버의 이름(최대 15자).
 a| 



 a| 
``도메인’
 a| 
SMB 서버와 연결할 Active Directory 도메인의 FQDN(정규화된 도메인 이름)입니다.
 a| 



 a| 
'-ou'
 a| 
선택 사항: SMB 서버와 연결할 Active Directory 도메인 내의 조직 단위입니다. 기본적으로 이 매개 변수는 CN=Computers로 설정됩니다.
 a| 



 a| 
'-NetBIOS-별칭'
 a| 
선택 사항: NetBIOS 별칭 목록으로, SMB 서버 이름에 대한 대체 이름입니다.
 a| 



 a| 
``논평’
 a| 
선택 사항: 서버에 대한 텍스트 설명입니다. Windows 클라이언트는 네트워크에서 서버를 검색할 때 이 SMB 서버 설명을 볼 수 있습니다.
 a| 

|===


== 작업 그룹에서 SMB 서버 설정

* 작업 그룹에서 SMB 서버를 생성하기 위한 매개 변수 *

새 SMB 서버를 생성하고 지원되는 SMB 버전을 지정할 때 이러한 값을 'vserver cifs create' 명령으로 제공합니다.

|===
| 필드에 입력합니다 | 설명 | 귀사의 가치 


 a| 
'-vserver'
 a| 
SMB 서버를 생성할 SVM의 이름입니다.
 a| 



 a| 
'-cifs-server'
 a| 
SMB 서버의 이름(최대 15자).
 a| 



 a| 
``워크그룹’’
 a| 
작업 그룹의 이름(최대 15자).
 a| 



 a| 
``논평’
 a| 
선택 사항: 서버에 대한 텍스트 설명입니다. Windows 클라이언트는 네트워크에서 서버를 검색할 때 이 SMB 서버 설명을 볼 수 있습니다.
 a| 

|===
* 로컬 사용자 생성을 위한 매개 변수 *

'vserver cifs users-and-groups local-user create' 명령을 사용하여 로컬 사용자를 생성할 때 이러한 값을 제공합니다. 이러한 서버는 작업 그룹의 SMB 서버에 필요하며 AD 도메인의 선택적 서버에 필요합니다.

|===
| 필드에 입력합니다 | 설명 | 귀사의 가치 


 a| 
'-vserver'
 a| 
로컬 사용자를 생성할 SVM의 이름입니다.
 a| 



 a| 
'-user-name'입니다
 a| 
로컬 사용자의 이름(최대 20자).
 a| 



 a| 
이름
 a| 
선택 사항: 사용자의 전체 이름입니다. 전체 이름에 공백이 포함된 경우 전체 이름을 큰따옴표로 묶습니다.
 a| 



 a| 
``설명’’
 a| 
선택 사항: 로컬 사용자에 대한 설명입니다. 설명에 공백이 있으면 매개 변수를 따옴표로 묶어야 합니다.
 a| 



 a| 
'-is-account-disabled'
 a| 
선택 사항: 사용자 계정의 사용 여부를 지정합니다. 이 매개 변수를 지정하지 않으면 기본값은 사용자 계정을 활성화하는 것입니다.
 a| 

|===
* 로컬 그룹 생성을 위한 매개 변수 *

'vserver cifs users-and-groups local-group create' 명령을 사용하여 로컬 그룹을 생성할 때 이러한 값을 제공합니다. AD 도메인 및 워크그룹의 SMB 서버에 대해서는 선택 사항입니다.

|===
| 필드에 입력합니다 | 설명 | 귀사의 가치 


 a| 
'-vserver'
 a| 
로컬 그룹을 생성할 SVM의 이름입니다.
 a| 



 a| 
``그룹 이름’’
 a| 
로컬 그룹의 이름입니다(최대 256자).
 a| 



 a| 
``설명’’
 a| 
선택 사항: 로컬 그룹에 대한 설명입니다. 설명에 공백이 있으면 매개 변수를 따옴표로 묶어야 합니다.
 a| 

|===


== SMB 지원 SVM에 스토리지 용량 추가

* 볼륨 생성을 위한 매개 변수 *

Qtree 대신 볼륨을 생성하는 경우 이 값에 'volume create' 명령을 입력합니다.

|===
| 필드에 입력합니다 | 설명 | 귀사의 가치 


 a| 
'-vserver'
 a| 
새 볼륨을 호스팅할 새 SVM 또는 기존 SVM의 이름입니다.
 a| 



 a| 
'- 볼륨'
 a| 
새 볼륨에 제공하는 고유한 설명 이름입니다.
 a| 



 a| 
'-집계'
 a| 
새 SMB 볼륨을 위한 충분한 공간이 있는 클러스터의 애그리게이트 이름입니다.
 a| 



 a| 
'-size'
 a| 
새 볼륨의 크기에 대해 제공하는 정수입니다.
 a| 



 a| 
'-보안-스타일'
 a| 
이 워크플로에 NTFS 보안 스타일을 사용합니다.
 a| 
NTFS



 a| 
``교차점-경로’’
 a| 
새 볼륨을 마운트할 루트(/) 아래의 위치입니다.
 a| 

|===
* qtree 생성을 위한 매개 변수 *

볼륨 대신 qtree를 생성하는 경우 이 값에 'volume qtree create' 명령을 입력합니다.

|===
| 필드에 입력합니다 | 설명 | 귀사의 가치 


 a| 
'-vserver'
 a| 
qtree가 포함된 볼륨이 있는 SVM의 이름입니다.
 a| 



 a| 
'- 볼륨'
 a| 
새 qtree를 포함할 볼륨의 이름입니다.
 a| 



 a| 
'-qtree'
 a| 
새 qtree를 64자 이하로 설명하는 고유한 이름입니다.
 a| 



 a| 
'-qtree-path'
 a| 
볼륨과 qtree를 별도의 인수로 지정하는 대신 '/vol/volume_name/qtree_name\>' 형식의 qtree 경로 인수를 지정할 수 있습니다.
 a| 

|===
* SMB 공유 생성을 위한 매개 변수 *

이러한 값은 'vserver cifs share create' 명령을 사용하여 제공합니다.

|===
| 필드에 입력합니다 | 설명 | 귀사의 가치 


 a| 
'-vserver'
 a| 
SMB 공유를 생성할 SVM의 이름입니다.
 a| 



 a| 
'-공유-이름'
 a| 
생성할 SMB 공유의 이름입니다(최대 256자).
 a| 



 a| 
'-경로'
 a| 
SMB 공유의 경로 이름(최대 256자). 공유를 생성하기 전에 이 경로가 볼륨에 있어야 합니다.
 a| 



 a| 
'-공유-속성'
 a| 
선택 사항: 공유 속성 목록입니다. 기본 설정은 oplocks, 탐색 가능, changentify, swing-previous-versions입니다.
 a| 



 a| 
``논평’
 a| 
선택 사항: 서버에 대한 텍스트 설명입니다(최대 256자). Windows 클라이언트는 네트워크에서 탐색할 때 이 SMB 공유 설명을 볼 수 있습니다.
 a| 

|===
* SMB ACL(공유 액세스 제어 목록) 생성을 위한 매개 변수 *

이러한 값은 'vserver cifs share access-control create' 명령을 사용하여 제공합니다.

|===
| 필드에 입력합니다 | 설명 | 귀사의 가치 


 a| 
'-vserver'
 a| 
SMB ACL을 생성할 SVM의 이름입니다.
 a| 



 a| 
'-share'
 a| 
생성할 SMB 공유의 이름입니다.
 a| 



 a| 
'-user-group-type'입니다
 a| 
공유의 ACL에 추가할 사용자 또는 그룹의 유형입니다. 기본 유형은 Windows입니다
 a| 
"창"



 a| 
'- 사용자 또는 그룹'
 a| 
공유의 ACL에 추가할 사용자 또는 그룹입니다. 사용자 이름을 지정하는 경우 "domain\username" 형식을 사용하여 사용자의 도메인을 포함해야 합니다.
 a| 



 a| 
허락
 a| 
사용자 또는 그룹에 대한 권한을 지정합니다.
 a| 
'[No_access|Read|Change|Full_Control]'

|===