---
permalink: disks-aggregates/add-disks-node-task.html 
sidebar: sidebar 
keywords: add, drives, node, shelf 
summary: 드라이브를 노드나 쉘프에 추가하여 핫 스페어 수를 늘리거나 애그리게이트에 공간을 추가할 수 있습니다. 
---
= 노드 또는 쉘프에 드라이브 추가
:icons: font
:imagesdir: ../media/


[role="lead"]
드라이브를 노드나 쉘프에 추가하여 핫 스페어 수를 늘리거나 애그리게이트에 공간을 추가할 수 있습니다.

추가하려는 드라이브가 플랫폼에서 지원되어야 합니다.

https://hwu.netapp.com/["NetApp Hardware Universe를 참조하십시오"]

단일 절차에서 추가해야 하는 최소 드라이브 수는 6개입니다. 단일 드라이브를 추가하면 성능이 저하될 수 있습니다.

.단계
. 최신 드라이브 및 쉘프 펌웨어, 디스크 검증 패키지 파일은 NetApp Support 사이트에서 확인하십시오.
+
노드나 쉘프에 최신 버전이 없는 경우 새 드라이브를 설치하기 전에 해당 버전을 업데이트하십시오.

+
현재 펌웨어 버전이 없는 새 드라이브에서 드라이브 펌웨어가 중단 없이 자동으로 업데이트됩니다.

. 적절하게 접지합니다.
. 플랫폼 전면에서 베젤을 조심스럽게 분리합니다.
. 새 드라이브에 맞는 슬롯을 확인합니다.
+
[NOTE]
====
드라이브를 추가할 수 있는 올바른 슬롯은 플랫폼 모델과 ONTAP 버전에 따라 다릅니다. 경우에 따라 특정 슬롯에 순서대로 드라이브를 추가해야 할 수도 있습니다. 예를 들어, AFF A800에서는 특정 간격으로 드라이브를 추가하여 빈 슬롯 클러스터를 남겨 둡니다. 반면, AFF A220에서는 외부에서 쉘프 중앙으로 실행되는 다음 빈 슬롯에 새 드라이브를 추가합니다.

====
+
를 참조하십시오 https://hwu.netapp.com/["NetApp Hardware Universe를 참조하십시오"] 구성에 맞는 슬롯을 식별합니다.

. 새 드라이브를 삽입합니다.
+
.. 캠 핸들이 열린 위치에 있는 상태에서 두 손을 사용하여 새 드라이브를 삽입합니다.
.. 드라이브가 멈출 때까지 누릅니다.
.. 드라이브가 중간 평면에 완전히 장착되고 핸들이 제자리에 고정되도록 캠 핸들을 닫습니다. 캠 핸들이 드라이브 면과 올바르게 정렬되도록 캠 핸들을 천천히 닫아야 합니다.


. 드라이브의 작동 LED(녹색)가 켜져 있는지 확인합니다.
+
드라이브의 작동 LED가 고정되어 있으면 드라이브에 전원이 공급되고 있는 것입니다. 드라이브 작동 LED가 깜박이면 드라이브에 전원이 공급되고 I/O가 진행 중임을 의미합니다. 드라이브 펌웨어가 자동으로 업데이트되면 LED가 깜박입니다.

. 다른 드라이브를 추가하려면 4-6단계를 반복합니다.
+
새 드라이브는 노드에 할당될 때까지 인식되지 않습니다. 새 드라이브를 수동으로 할당하거나, 노드가 드라이브 자동 할당 규칙을 따르는 경우 ONTAP에서 새 드라이브를 자동으로 할당할 때까지 기다릴 수 있습니다.

. 새 드라이브를 모두 인식한 후 추가 및 소유권 정보를 확인합니다.
+
'스토리지 집계 show-spare-disks'

+
올바른 노드가 소유하는 새 드라이브가 표시됩니다.

. 새로 추가된 드라이브를 0으로 설정합니다.
+
'스토리지 디스크 제로'

+
이전에 ONTAP 애그리게이트에서 사용되었던 드라이브를 다른 애그리게이트에 추가하려면 먼저 제로화해야 합니다. 이제 드라이브를 제로화하면 애그리게이트의 크기를 빠르게 늘려야 하는 경우 지연이 발생하지 않습니다. 드라이브 제로화 명령은 백그라운드에서 실행되며 노드에 0이 아닌 드라이브의 크기에 따라 완료하는 데 몇 시간이 걸릴 수 있습니다.



새로운 드라이브를 애그리게이트에 추가하거나, 핫 스페어 목록에 배치하거나, 새 애그리게이트를 생성할 수 있습니다.
