---
permalink: disks-aggregates/commands-manage-disks-reference.html 
sidebar: sidebar 
keywords: commands, manage, disks 
summary: 스토리지 디스크 및 스토리지 애그리게이트 명령을 사용하여 디스크를 관리할 수 있습니다. 
---
= 디스크 관리를 위한 명령입니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
'스토리지 디스크' 및 '스토리지 집계' 명령을 사용하여 디스크를 관리할 수 있습니다.

|===


| 원하는 작업 | 이 명령 사용... 


 a| 
분할된 디스크를 포함한 예비 디스크 목록을 소유자별로 표시합니다
 a| 
'스토리지 집계 show-spare-disks'



 a| 
디스크 RAID 유형, 현재 사용량 및 RAID 그룹을 Aggregate 별로 표시합니다
 a| 
'스토리지 집계 표시 상태'



 a| 
스페어 디스크를 포함하여 RAID 유형, 현재 사용, 애그리게이트 및 RAID 그룹을 표시합니다. 물리적 디스크의 경우
 a| 
스토리지 디스크 show-raid



 a| 
오류가 발생한 디스크 목록을 표시합니다
 a| 
스토리지 디스크 고장



 a| 
디스크의 사전 클러스터(notescope) 드라이브 이름을 표시합니다
 a| 
스토리지 디스크 show-primary-paths(고급)



 a| 
특정 디스크 또는 쉘프의 LED를 켭니다
 a| 
'스토리지 디스크 세트 주도'



 a| 
특정 디스크의 체크섬 유형을 표시합니다
 a| 
'스토리지 디스크 표시-필드 체크섬-호환성



 a| 
모든 스페어 디스크의 체크섬 유형을 표시합니다
 a| 
'스토리지 디스크 표시-필드 체크섬-호환성-컨테이너-유형 스페어'



 a| 
디스크 연결 및 배치 정보를 표시합니다
 a| 
'스토리지 디스크 표시 필드 디스크, 운영 포트, 보조 이름, 보조 포트, 쉘프, 베이'



 a| 
특정 디스크의 사전 클러스터 디스크 이름을 표시합니다
 a| 
'스토리지 디스크 표시 - 디스크 디스크 이름 - 필드 diskpathnames'



 a| 
유지보수 센터의 디스크 목록을 표시합니다
 a| 
스토리지 디스크 show-maintenance



 a| 
SSD 마모 수명을 표시합니다
 a| 
'스토리지 디스크 표시-SSD 마모'



 a| 
공유 디스크의 파티션을 해제합니다
 a| 
'스토리지 디스크 파티션 해제'(진단 수준에서 사용 가능)



 a| 
제로화되지 않은 모든 디스크를 제로화하십시오
 a| 
'스토리지 디스크 제로'



 a| 
하나 이상의 지정된 디스크에 대해 지속적인 삭제 프로세스를 중지합니다
 a| 
'system node run-node notdename -command disk sanitize'



 a| 
스토리지 암호화 디스크 정보를 표시합니다
 a| 
스토리지 암호화 디스크 표시



 a| 
연결된 모든 키 관리 서버에서 인증 키를 검색합니다
 a| 
보안 키 관리자 복원

|===
.관련 정보
* https://docs.netapp.com/us-en/ontap-cli["ONTAP 명령 참조입니다"^]

