---
permalink: disks-aggregates/configure-auto-assignment-disk-ownership-task.html 
sidebar: sidebar 
keywords: change, modify, automatic, assignment, disk ownership 
summary: 스토리지 디스크 옵션 수정 명령을 사용하여 자동으로 디스크 소유권을 할당하거나 디스크 소유권을 자동으로 할당하지 않도록 기본 정책이 아닌 정책을 선택할 수 있습니다. 
---
= 디스크 소유권을 자동으로 할당하는 설정을 변경합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
를 사용할 수 있습니다 `storage disk option modify` 디스크 소유권을 자동으로 할당하거나 디스크 소유권을 자동으로 할당하지 않도록 하는 기본 정책이 아닌 정책을 선택하는 명령입니다.

에 대해 자세히 알아보십시오 link:disk-autoassignment-policy-concept.html["디스크 소유권을 자동으로 할당합니다"].

.이 작업에 대해
DS460C 쉘프만 포함된 HA 쌍이 있는 경우, 기본 자동 할당 정책은 1/2 드로어 입니다. 기본 정책이 아닌 정책(베이, 쉘프, 스택)으로 변경할 수 없습니다.

.단계
. 자동 디스크 할당 수정:
+
.. 기본값이 아닌 정책을 선택하려면 다음을 입력합니다.
+
'스토리지 디스크 옵션 modify-autoassign-policy_autoconfigure_policy_-node_node_name_'

+
*** 스택 또는 루프 수준에서 자동 소유권을 구성하려면 '_autoassign_policy_'로 'stack'을 사용합니다.
*** shelf 레벨에서 자동 소유권을 구성하려면 '_autoconfigure_policy_'로 'shelf'를 사용합니다.
*** 베이 수준에서 자동 소유권을 구성하려면 '_autoconfigure_policy_'로 'bay'를 사용합니다.


.. 자동 디스크 소유권 할당을 해제하려면 다음을 입력합니다.
+
`storage disk option modify -autoassign off -node _node_name_`



. 디스크의 자동 할당 설정을 확인합니다.
+
'스토리지 디스크 옵션 표시'

+
[listing]
----
cluster1::> storage disk option show

Node           BKg. FW. Upd.  Auto Copy     Auto Assign    Auto
                                                           Assign Policy
-------------  -------------  ------------  -------------  --------
cluster1-1     on             on            on             default
cluster1-2     on             on            on             default
----

