---
permalink: disks-aggregates/create-aggregates-manual-task.html 
sidebar: sidebar 
keywords: ontap 9, create, aggregates, manually 
summary: 애그리게이트를 수동으로 생성하기 전에 디스크 구성 옵션을 검토하고 생성을 시뮬레이트해야 합니다. 그런 다음 스토리지 애그리게이트 생성을 실행하여 결과를 확인할 수 있습니다. 
---
= 수동으로 애그리게이트 생성
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
애그리게이트를 수동으로 생성하기 전에 디스크 구성 옵션을 검토하고 생성을 시뮬레이트해야 합니다. 그런 다음 '스토리지 집계 생성'을 실행하여 결과를 확인할 수 있습니다.

Aggregate에 필요한 디스크 수와 핫 스페어 디스크의 수를 결정해야 합니다.

루트 데이터 데이터 파티셔닝이 활성화되어 있고 구성에 24개 SSD(Solid State Drive) 이하가 있는 경우 데이터 파티션을 다른 노드에 할당하는 것이 좋습니다.

루트 데이터 파티셔닝과 루트 데이터 파티셔닝이 설정된 시스템에서 애그리게이트를 생성하는 절차는 파티셔닝되지 않은 디스크를 사용하여 시스템에서 애그리게이트를 생성하는 절차와 동일합니다. 시스템에서 루트 데이터 파티셔닝이 활성화되어 있으면 '-diskcount' 옵션에 디스크 파티션 수를 사용해야 합니다. 루트-데이터-데이터 파티셔닝의 경우 '-diskcount' 옵션은 사용할 디스크 수를 지정합니다.

[NOTE]
====
FlexGroups에서 사용할 Aggregate를 여러 개 생성할 경우 Aggregate의 크기가 최대한 근접해야 합니다.

====
'스토리지 애그리게이트 생성' man 페이지에는 집계 생성 옵션 및 요구 사항에 대한 자세한 정보가 나와 있습니다.

.단계
. 스페어 디스크 파티션 목록을 보고 애그리게이트를 만들 수 있을 만큼 충분한지 확인합니다.
+
'Storage aggregate show-spare-disks-original-owner_node_name_'

+
데이터 파티션은 Local Data Usable 아래에 표시됩니다. 루트 파티션은 스페어로 사용할 수 없습니다.

. 애그리게이트 생성 시뮬레이션:
+
'스토리지 집계 create-aggregate_aggregate_name_-node_node_name_-raidtype RAID_DP -diskcount_number_of_disks_or_partitions_-simulate true'

. 시뮬레이트된 명령에서 경고가 표시되는 경우 명령을 조정하고 시뮬레이션을 반복합니다.
. 애그리게이트 생성:
+
'스토리지 집계 create-aggregate_agr_name_-node_node_name_-raidtype RAID_DP-diskcount_number_of_disks_or_partitions_'

. Aggregate가 생성되었는지 확인하기 위해 Aggregate를 표시합니다.
+
'Storage aggregate show-status_aggregate_name_'



http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-cmpr/GUID-5CB10C70-AC11-41C0-8C16-B4D0DF916E9B.html["ONTAP 9 명령"]
