---
permalink: disks-aggregates/create-aggregates-auto-provision-task.html 
sidebar: sidebar 
keywords: ontap 9, create, aggregates, auto-provision 
summary: 사용자 환경에서 자동 프로비저닝 방법이 적합한 경우 스토리지 애그리게이트 자동 프로비저닝을 실행하여 애그리게이트 레이아웃 권장 사항을 생성합니다. 그런 다음 ONTAP 권장사항을 검토하고 승인한 후 애그리게이트를 생성할 수 있습니다. 
---
= 자동 프로비저닝을 사용하여 애그리게이트 생성
:icons: font
:imagesdir: ../media/


[role="lead"]
사용자 환경에서 자동 프로비저닝 방법이 적절한 경우 '스토리지 애그리게이트 자동 프로비저닝'을 실행하여 애그리게이트 레이아웃 권장 사항을 생성합니다. 그런 다음 ONTAP 권장사항을 검토하고 승인한 후 애그리게이트를 생성할 수 있습니다.

ONTAP 9.2 이상이 클러스터에서 실행 중이어야 합니다.

'Storage aggregate auto-provision' 명령을 통해 생성된 기본 요약에는 이름과 사용 가능한 크기를 비롯하여 생성할 권장 애그리게이트가 나열됩니다. 목록을 보고 메시지가 표시될 때 권장 애그리게이트를 만들 것인지 결정할 수 있습니다.

다음 보고서를 표시하는 '-verbose' 옵션을 사용하여 자세한 요약을 표시할 수도 있습니다.

* 애그리게이트를 생성한 후 생성, 검색된 스페어 및 나머지 스페어 디스크와 파티션을 생성할 새 애그리게이트의 노드 요약
* 사용할 디스크 및 파티션 수로 생성할 새로운 데이터 애그리게이트
* 생성할 새 데이터 애그리게이트에서 스페어 디스크 및 파티션을 사용하는 방법을 보여주는 RAID 그룹 레이아웃
* Aggregate 생성 후 남아 있는 스페어 디스크 및 파티션에 대한 세부 정보입니다


자동 프로비저닝 방법에 익숙하고 환경이 제대로 준비되었으면 '-skip-confirmation' 옵션을 사용하여 표시 및 확인 없이 권장 집계를 생성할 수 있습니다. 스토리지 집계 자동 프로비저닝 명령은 CLI 세션 확인 설정의 영향을 받지 않습니다.

'스토리지 집계 자동 프로비저닝' man 페이지에는 집계 레이아웃 권장 사항에 대한 자세한 정보가 나와 있습니다.

.단계
. 원하는 표시 옵션으로 'Storage aggregate auto-provision' 명령을 실행합니다.
+
** 옵션 없음: 표준 요약을 표시합니다
** '-verbose' 옵션: 상세 요약 표시
** '-skip-confirmation' 옵션: 표시 또는 확인 없이 권장 집계를 생성합니다


. 권장 애그리게이트 표시를 검토한 후 프롬프트에 응답하여 권장 애그리게이트를 생성합니다.
+
[listing]
----
Do you want to create recommended aggregates? {y|n}:y

Info: Creating node1_SSD_1 ...
      Creating node2_SSD_1 ...
----


http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-cmpr/GUID-5CB10C70-AC11-41C0-8C16-B4D0DF916E9B.html["ONTAP 9 명령"]
