---
permalink: disks-aggregates/decide-aggregate-creation-method-concept.html 
sidebar: sidebar 
keywords: decide, aggregate, create, add, method, local tier 
summary: 'ONTAP는 로컬 계층(애그리게이트)을 자동으로 생성하는 모범 사례 권장 사항을 제공하지만(자동 프로비저닝 사용) 해당 환경에서 권장 구성이 지원되는지 여부를 확인해야 합니다. 그렇지 않은 경우 RAID 정책 및 디스크 구성에 대한 결정을 내린 다음 로컬 계층을 수동으로 생성해야 합니다.' 
---
= 로컬 계층을 생성하는 데 사용할 방법 결정(애그리게이트)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP는 로컬 계층을 자동으로 추가하기 위한 모범 사례 권장 사항을 제공하지만(자동 프로비저닝을 통해 애그리게이트 생성), 권장 구성이 사용자 환경에서 지원되는지 여부를 확인해야 합니다. 그렇지 않은 경우 RAID 정책 및 디스크 구성에 대한 결정을 내린 다음 로컬 계층을 수동으로 생성해야 합니다.

로컬 계층이 자동으로 생성되면 ONTAP는 클러스터에서 사용 가능한 스페어 디스크를 분석하고 Best Practice에 따라 스페어 디스크를 사용하여 로컬 계층을 추가하는 방법에 대한 권장 사항을 생성합니다. ONTAP에서 권장 구성을 표시합니다. 권장 사항을 수락하거나 로컬 계층을 수동으로 추가할 수 있습니다.



== ONTAP 권장 사항을 수락하기 전에

다음 디스크 조건 중 하나라도 있는 경우 ONTAP의 권장 사항을 수락하기 전에 해결해야 합니다.

* 디스크가 누락되었습니다
* 스페어 디스크 숫자의 변동
* 할당되지 않은 디스크
* 제로화되지 않은 스페어
* 유지 관리 테스트를 진행 중인 디스크


Storage aggregate auto-provision man 페이지에 이러한 요구 사항에 대한 자세한 정보가 나와 있습니다.



== 수동 방법을 사용해야 하는 경우

대부분의 경우 로컬 계층의 권장 레이아웃은 사용자 환경에 가장 적합합니다. 하지만 클러스터에서 ONTAP 9.1 이전 버전이 실행 중이거나 환경에 다음 구성이 포함된 경우 수동 방법을 사용하여 로컬 계층을 생성해야 합니다.


NOTE: ONTAP 9.11.1부터 System Manager를 사용하여 로컬 계층을 수동으로 추가할 수 있습니다.

* 타사 어레이 LUN을 사용하는 Aggregate
* Cloud Volumes ONTAP 또는 ONTAP Select가 있는 가상 디스크
* MetroCluster 시스템
* SyncMirror
* mSATA 디스크
* FlashPool 계층(애그리게이트)
* 노드에 여러 디스크 유형 또는 크기가 접속되어 있습니다




== 로컬 계층 생성 방법 선택(애그리게이트)

사용할 방법 선택:

* link:create-aggregates-auto-provision-task.html["로컬 계층(애그리게이트)을 자동으로 추가(생성)합니다"]
* link:create-aggregates-manual-task.html["로컬 계층(애그리게이트)을 수동으로 추가(생성)합니다"]


http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-cmpr/GUID-5CB10C70-AC11-41C0-8C16-B4D0DF916E9B.html["ONTAP 9 명령"^]
