---
permalink: disks-aggregates/determine-space-usage-aggregate-concept.html 
sidebar: sidebar 
keywords: space, usage, aggregate, local tier, volume 
summary: '하나 이상의 로컬 계층(애그리게이트)에 있는 모든 볼륨에서 사용되는 공간을 확인하여 추가 공간을 확보하는 조치를 취할 수 있습니다.' 
---
= 로컬 계층에서 공간 사용량 확인(애그리게이트)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
하나 이상의 로컬 계층(애그리게이트)에 있는 모든 볼륨에서 사용되는 공간을 확인하여 추가 공간을 확보하는 조치를 취할 수 있습니다.

WAFL는 애그리게이트 레벨 메타데이터 및 성능을 위해 총 디스크 공간의 비율을 예약합니다.  Aggregate에서 볼륨을 유지 관리하는 데 사용되는 공간은 WAFL 예비 공간에서 나오며 변경할 수 없습니다.

30TB 미만의 애그리게이트에서 WAFL는 애그리게이트 레벨 메타데이터 및 성능을 위해 총 디스크 공간의 10%를 예약합니다.

ONTAP 9.12.1부터 30TB 이상의 애그리게이트에서는 애그리게이트 레벨 메타데이터와 성능을 위한 예약 디스크 공간의 양이 감소하므로 애그리게이트에서 사용 가능한 공간이 5% 더 많아집니다. 절약되는 공간의 가용성은 해당 플랫폼 및 ONTAP 버전에 따라 다릅니다.

[cols="30,30,40"]
|===
| ONTAP가 30TB 이상의 애그리게이트에서 예약한 디스크 공간 | 플랫폼에 적용됩니다 | ONTAP 버전 


| 5% | 알아봅니다 AFF FAS | ONTAP 9.14.1 이상 


| 5% | AFF 플랫폼 및 FAS500f 플랫폼 | ONTAP 9.12.1 이상 


| 10% | 모든 플랫폼 | ONTAP 9.11.1 이상 
|===
'aggregate show-space' 명령을 사용하면 하나 이상의 애그리게이트에 있는 모든 볼륨의 공간 사용량을 확인할 수 있습니다. 이렇게 하면 포함된 Aggregate에서 가장 많은 공간을 차지하는 볼륨을 볼 수 있으므로 여유 공간을 확보하기 위해 작업을 수행할 수 있습니다.

Aggregate의 사용된 공간은 이 애그리게이트에 있는 FlexVol 볼륨에 사용된 공간의 직접적인 영향을 받습니다. 볼륨의 공간을 늘리기 위해 취하는 측정도 애그리게이트의 공간에 영향을 미칩니다.


NOTE: ONTAP 9.15.1부터 두 개의 새로운 메타데이터 카운터를 사용할 수 있습니다. 여러 기존 카운터의 변경 사항과 함께 할당된 사용자 데이터의 양을 보다 명확하게 확인할 수 있습니다. 을 참조하십시오 link:../volumes/determine-space-usage-volume-aggregate-concept.html["볼륨 또는 애그리게이트의 공간 사용량을 확인합니다"] 를 참조하십시오.

다음 행은 'aggregate show-space' 명령 출력에 포함됩니다.

* * 볼륨 풋프린트 *
+
애그리게이트 내 모든 볼륨 설치 공간 합계입니다. 포함된 애그리게이트에 있는 모든 볼륨의 모든 데이터와 메타데이터에서 사용되거나 예약된 모든 공간이 여기에 포함됩니다.

* * 집계 메타데이터 *
+
비트맵과 inode 파일 할당 등 Aggregate에 필요한 총 파일 시스템 메타데이터입니다.

* * 스냅숏 예비 공간 *
+
볼륨 크기에 따라 애그리게이트 Snapshot 복사본에 예약된 공간의 양입니다. 사용된 공간으로 간주되어 볼륨 또는 애그리게이트 데이터 또는 메타데이터에 사용할 수 없습니다.

* * Snapshot Reserve Unusable(스냅샷 예비 공간 사용 불가
+
Aggregate 스냅샷 복사본에 원래 할당된 공간 중 Aggregate와 연결된 볼륨에서 사용 중이므로 애그리게이트 스냅샷 복사본에 사용할 수 없는 공간의 양입니다. Aggregate 스냅샷 예약 공간이 0이 아닌 Aggregate에만 발생할 수 있습니다.

* * 총 사용량 *
+
볼륨, 메타데이터 또는 스냅샷 복사본별 애그리게이트에 사용되거나 예약된 모든 공간의 합계입니다.

* * 총 물리적 사용량 *
+
현재 데이터에 사용 중인 공간(향후 사용을 위해 예약되지 않음). Aggregate Snapshot 복사본에서 사용하는 공간을 포함합니다.



다음 예제는 Snapshot 예약 공간이 5%인 애그리게이트의 show-space 집계 명령 출력을 보여줍니다. 스냅숏 예비 공간이 0인 경우 행이 표시되지 않습니다.

....
cluster1::> storage aggregate show-space

						Aggregate : wqa_gx106_aggr1

      Feature                                   Used      Used%
      --------------------------------    ----------     ------
      Volume Footprints                      101.0MB         0%
      Aggregate Metadata                       300KB         0%
      Snapshot Reserve                        5.98GB         5%

      Total Used                              6.07GB         5%
      Total Physical Used                    34.82KB         0%
....
.관련 정보
* link:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/Space_Usage["Knowledge Base 문서: 공간 사용"^]
* link:https://www.netapp.com/blog/free-up-storage-capacity-upgrade-ontap/["ONTAP 9.12.1로 업그레이드하여 스토리지 용량의 5%를 확보하십시오"^]

