---
permalink: disks-aggregates/determine-flash-pool-candidacy-cache-size-task.html 
sidebar: sidebar 
keywords: determine, flash pool, candidacy, optimal cache size 
summary: 기존 애그리게이트를 Flash Pool 애그리게이트로 변환하기 전에 I/O로 바인딩되어 있는지 여부 및 워크로드와 예산에 적합한 Flash Pool 캐시 크기가 무엇인지 결정할 수 있습니다. 또한 기존 Flash Pool 애그리게이트의 캐시 크기가 올바로 조정되는지 확인할 수 있습니다. 
---
= Flash Pool 적합성 및 최적의 캐시 크기를 결정합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
기존 애그리게이트를 Flash Pool 애그리게이트로 변환하기 전에 I/O로 바인딩되어 있는지 여부 및 워크로드와 예산에 적합한 Flash Pool 캐시 크기가 무엇인지 결정할 수 있습니다. 또한 기존 Flash Pool 애그리게이트의 캐시 크기가 올바로 조정되는지 확인할 수 있습니다.

분석 중인 집계가 최대 부하를 경험하는 시기는 대략 알고 있어야 합니다.

.단계
. 고급 모드 진입:
+
진일진일보한 것

. 기존 애그리게이트를 Flash Pool 애그리게이트로 변환할 수 있는지 확인하려면, 최고 로드 기간 동안 애그리게이트의 디스크 사용량이 얼마인지, 지연 시간에 미치는 영향이 있는지 확인하십시오.
+
S tistics show -periodic -object disk:raid_group -instance_raid_group_name _ -counter disk_busy|user_read_latency -interval 1 - iterations 60

+
Flash Pool 캐시를 추가하여 지연 시간을 줄이는지 이 애그리게이트에 맞게 결정할 수 있습니다.

+
다음 명령을 실행하면 aggregate ""aggr1""의 첫 번째 RAID 그룹에 대한 통계가 표시됩니다.

+
S tistics show -periodic -object disk:raid_group -instance/aggr1/plex0/rg0 -counter disk_busy|user_read_latency -interval 1 -iterations 60'

. AWA(Automated Workload Analyzer) 시작:
+
'Storage automated-working-set-analyzer start-node_node_name_-aggregate_aggr_name_'

+
Awa는 지정된 aggregate와 연결된 볼륨의 워크로드 데이터 수집을 시작합니다.

. 고급 모드 종료:
+
'관리자 설정'을 선택합니다

+
최대 부하 간격이 하나 이상 발생할 때까지 AWA가 실행되도록 합니다. Awa는 지정된 집계와 연결된 볼륨에 대한 워크로드 통계를 수집하고 최대 1주 동안 데이터를 분석합니다. 1주일 이상 AWA를 실행하면 가장 최근 주로부터 수집된 데이터만 보고됩니다. 캐시 크기 추정치는 데이터 수집 기간 동안 가장 높은 로드를 기준으로 하며, 전체 데이터 수집 기간 동안 로드가 높을 필요는 없습니다.

. 고급 모드 진입:
+
진일진일보한 것

. 워크로드 분석 표시:
+
'Storage automated-working-set-analyzer show -node_node_name_'

. AWA 중지:
+
'Storage automated-working-set-analyzer stop_node_name_'

+
모든 워크로드 데이터가 플러시되고 더 이상 분석에 사용할 수 없습니다.

. 고급 모드 종료:
+
'관리자 설정'을 선택합니다


