---
permalink: disks-aggregates/determine-control-volume-space-aggregate-concept.html 
sidebar: sidebar 
keywords: determine, control. volume, space usage, aggregate 
summary: Aggregate에서 가장 많은 공간을 사용 중인 FlexVol 볼륨과 볼륨 내의 기능을 확인할 수 있습니다. volume show-footprint 명령은 볼륨의 설치 공간 또는 포함된 애그리게이트 내의 공간 사용에 대한 정보를 제공합니다. 
---
= Aggregate에서 볼륨의 공간 사용을 결정하고 제어하는 방법
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Aggregate에서 가장 많은 공간을 사용 중인 FlexVol 볼륨과 볼륨 내의 기능을 확인할 수 있습니다. 'volume show-footprint' 명령은 볼륨의 설치 공간 또는 포함된 집계 내의 공간 사용에 대한 정보를 제공합니다.

'volume show-footprint' 명령은 오프라인 볼륨을 포함하여 애그리게이트에서 각 볼륨의 공간 사용에 대한 세부 정보를 표시합니다. 이 명령은 볼륨 표시 공간과 집계 표시 공간 명령의 출력 간격을 연결합니다. 모든 백분율은 애그리게이트 크기의 백분율로 계산됩니다.

다음 예에서는 testvol이라는 볼륨에 대한 'volume show-footprint' 명령 출력을 보여 줍니다.

[listing]
----
cluster1::> volume show-footprint testvol

      Vserver : thevs
      Volume  : testvol

      Feature                                   Used    Used%
      --------------------------------    ----------    -----
      Volume Data Footprint                  120.6MB       4%
      Volume Guarantee                        1.88GB      71%
      Flexible Volume Metadata               11.38MB       0%
      Delayed Frees                           1.36MB       0%
      Total Footprint                         2.01GB      76%
----
다음 표에서는 'volume show-footprint' 명령의 출력 중 일부 주요 행과 해당 기능을 통해 공간 사용을 줄이기 위해 수행할 수 있는 작업을 설명합니다.

|===


| 행/피처 이름 | 행의 설명/내용 | 줄일 수 있는 방법이 있습니다 


 a| 
'볼륨 데이터 사용 공간'
 a| 
액티브 파일 시스템에서 볼륨의 데이터에 의해 포함 애그리게이트에 사용된 총 공간 및 볼륨의 스냅샷 복사본에 사용되는 공간입니다. 이 행에는 예약된 공간이 포함되지 않습니다.
 a| 
* 볼륨에서 데이터를 삭제하는 중입니다.
* 볼륨에서 스냅샷 복사본 삭제




 a| 
볼륨 보증
 a| 
나중에 쓸 수 있도록 애그리게이트에서 볼륨에 예약된 공간입니다. 예약된 공간의 양은 볼륨의 보장 유형에 따라 다릅니다.
 a| 
보장 유형을 없음으로 변경합니다.



 a| 
'유연한 볼륨 메타데이터'
 a| 
볼륨의 메타데이터 파일이 Aggregate에 사용하는 총 공간입니다.
 a| 
제어할 직접적인 방법이 없습니다.



 a| 
'해방된'
 a| 
ONTAP이 성능에 사용했으며 즉시 해제할 수 없는 블록입니다. SnapMirror 대상의 경우 이 행의 값은 "0"이며 표시되지 않습니다.
 a| 
제어할 직접적인 방법이 없습니다.



 a| 
파일 작업 메타데이터
 a| 
파일 작업 메타데이터에 예약된 총 공간입니다.
 a| 
제어할 직접적인 방법이 없습니다.



 a| 
토털 풋프린트
 a| 
Aggregate에서 볼륨이 사용하는 총 공간입니다. 모든 행의 합계입니다.
 a| 
볼륨에서 사용하는 공간을 줄이는 데 사용되는 모든 방법

|===
http://www.netapp.com/us/media/tr-3483.pdf["NetApp 기술 보고서 3483: NetApp SAN 또는 IP SAN 엔터프라이즈 환경에서 씬 프로비저닝"]
