---
permalink: disks-aggregates/determine-number-disks-partitions-aggregate-concept.html 
sidebar: sidebar 
keywords: determine, number, disks, partitions, aggregate 
summary: 시스템 및 비즈니스 요구사항을 충족하려면 애그리게이트에 충분한 디스크 또는 디스크 파티션이 있어야 합니다. 또한 데이터 손실 가능성을 최소화하기 위해 권장되는 수의 핫 스페어 디스크 또는 핫 스페어 디스크 파티션이 있어야 합니다. 
---
= Aggregate에 필요한 디스크 또는 디스크 파티션 수를 결정합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
시스템 및 비즈니스 요구사항을 충족하려면 애그리게이트에 충분한 디스크 또는 디스크 파티션이 있어야 합니다. 또한 데이터 손실 가능성을 최소화하기 위해 권장되는 수의 핫 스페어 디스크 또는 핫 스페어 디스크 파티션이 있어야 합니다.

루트 데이터 파티셔닝은 특정 구성에서 기본적으로 활성화되어 있습니다. 루트 데이터 파티셔닝이 설정된 시스템은 디스크 파티션을 사용하여 애그리게이트를 생성합니다. 루트 데이터 파티셔닝이 설정되어 있지 않은 시스템은 분할되지 않은 디스크를 사용합니다.

RAID 정책에 필요한 최소 수와 최소 용량 요구 사항을 충족할 수 있을 만큼 충분한 디스크 또는 디스크 파티션이 있어야 합니다.

[NOTE]
====
ONTAP에서 드라이브의 사용 가능한 공간이 드라이브의 물리적 용량보다 작습니다. 특정 드라이브의 사용 가능한 공간과 각 RAID 정책에 필요한 최소 디스크 또는 디스크 파티션 수는 _Hardware Universe_에서 찾을 수 있습니다. 'storage aggregate show-spare-disks' 명령을 사용하여 특정 디스크의 사용 가능한 공간을 찾을 수도 있습니다.

====
RAID 그룹을 만들고 용량 요구 사항을 충족하는 데 필요한 디스크 또는 디스크 파티션 수 외에도, 애그리게이트에 권장되는 최소 핫 스페어 디스크 또는 핫 스페어 디스크 파티션 수가 있어야 합니다.

* 모든 플래시 애그리게이트에는 적어도 하나의 핫 스페어 디스크 또는 디스크 파티션이 있어야 합니다.
+
[NOTE]
====
AFF C190에는 스페어 드라이브가 기본적으로 없습니다. 이 예외는 완전히 지원됩니다.

====
* 비 플래시 동종 애그리게이트의 경우 최소 2개의 핫 스페어 디스크 또는 디스크 파티션이 있어야 합니다.
* SSD 스토리지 풀의 경우 각 HA 쌍에 대해 하나 이상의 핫 스페어 디스크를 포함해야 합니다.
* Flash Pool 애그리게이트의 경우 각 HA 쌍에 대해 최소 2개의 스페어 디스크가 있어야 합니다. 에서 Flash Pool 애그리게이트에 대해 지원되는 RAID 정책에 대한 자세한 내용을 확인할 수 있습니다 https://hwu.netapp.com["Hardware Universe"].
* 유지보수 센터의 사용을 지원하고 여러 개의 동시 디스크 장애로 인한 문제를 방지하려면 다중 디스크 캐리어에 최소 4개의 핫 스페어가 있어야 합니다.


https://hwu.netapp.com["NetApp Hardware Universe를 참조하십시오"^]

http://www.netapp.com/us/media/tr-3838.pdf["NetApp 기술 보고서 3838: 스토리지 서브시스템 구성 가이드"]
