---
permalink: disks-aggregates/disk-partition-ownership-overview-concept.html 
sidebar: sidebar 
keywords: disk, partition, ownership, overview 
summary: 디스크 및 파티션의 소유권을 관리할 수 있습니다. 
---
= 디스크 및 파티션 소유권
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
디스크 및 파티션의 소유권을 관리할 수 있습니다.

다음 작업을 수행할 수 있습니다.

* *link:display-partition-ownership-task.html["디스크 및 파티션 소유권을 표시합니다"]*
+
디스크 소유권을 확인하여 스토리지를 제어하는 노드를 결정할 수 있습니다. 공유 디스크를 사용하는 시스템에서 파티션 소유권을 볼 수도 있습니다.

* *link:configure-auto-assignment-disk-ownership-task.html["디스크 소유권을 자동으로 할당하는 설정을 변경합니다"]*
+
자동으로 디스크 소유권을 할당하거나 디스크 소유권을 자동으로 할당하지 않도록 기본 정책이 아닌 정책을 선택할 수 있습니다.

* *link:manual-assign-disks-ownership-manage-task.html["분할되지 않은 디스크의 소유권을 수동으로 할당합니다"]*
+
클러스터가 자동 디스크 소유권 할당을 사용하도록 구성되지 않은 경우 소유권을 수동으로 할당해야 합니다.

* *link:manual-assign-ownership-partitioned-disks-task.html["분할된 디스크의 소유권을 수동으로 할당합니다"]*
+
파티션되지 않은 디스크에 대한 것처럼 수동으로 또는 자동 할당을 사용하여 컨테이너 디스크 또는 파티션의 소유권을 설정할 수 있습니다.

* *link:remove-failed-disk-task.html["오류가 발생한 디스크를 제거합니다"]*
+
완전히 장애가 발생한 디스크는 ONTAP에서 더 이상 사용 가능한 디스크로 간주할 수 없으며, 쉘프를 즉시 분리할 수 있습니다.

* *link:remove-ownership-disk-task.html["디스크에서 소유권을 제거합니다"]*
+
ONTAP는 디스크 소유권 정보를 디스크에 씁니다. 노드에서 스페어 디스크 또는 해당 쉘프를 제거하려면 먼저 소유권 정보를 제거하여 다른 노드에 올바르게 통합되도록 해야 합니다.


