---
permalink: disks-aggregates/fast-zeroing-drives-concept.html 
sidebar: sidebar 
keywords: fast, zero, drives 
summary: ONTAP 9.4 이상 버전이 새로 설치된 시스템에서 ONTAP 9.4 이상으로 시스템이 재초기화되는 경우 _fast zeroing_을 사용하여 드라이브를 제로화할 수 있습니다. 
---
= 드라이브 고속 제로화
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9.4 이상 버전이 새로 설치된 시스템에서 ONTAP 9.4 이상으로 시스템이 재초기화되는 경우 _fast zeroing_을 사용하여 드라이브를 제로화할 수 있습니다.

빠른 제로화 _ 를 사용하면 드라이브가 초 내에 제로화됩니다. 프로비저닝 전에 이 작업이 자동으로 수행되므로 스페어 드라이브를 추가할 때 시스템을 초기화하고, 애그리게이트를 생성하거나, 애그리게이트를 확장하는 데 걸리는 시간을 크게 단축할 수 있습니다.

_Fast zeroing_은 SSD와 HDD에서 모두 지원됩니다.


NOTE: _Fast zeroing_은 ONTAP 9.3 이전 버전에서 업그레이드된 시스템에서는 지원되지 않습니다. ONTAP 9.4 이상을 새로 설치하거나 시스템을 다시 초기화해야 합니다. ONTAP 9.3 및 이전 버전에서는 ONTAP에 의해 드라이브가 자동으로 제로화되지만 프로세스가 더 오래 걸립니다.

드라이브를 수동으로 제로화할 필요가 있는 경우 다음 방법 중 하나를 사용할 수 있습니다. ONTAP 9.4 이상에서는 수동으로 드라이브를 제로화하는 데 몇 초 밖에 걸리지 않습니다.

[role="tabbed-block"]
====
.CLI 명령
--
* CLI 명령을 사용하여 드라이브를 빠르게 제로합니다 *

.이 작업에 대해
이 명령을 사용하려면 관리자 권한이 필요합니다.

.단계
. CLI 명령을 입력합니다.
+
'스토리지 디스크 제로'



--
.부팅 메뉴 옵션
--
* 부팅 메뉴에서 옵션을 선택하여 드라이브를 빠르게 제로화 * 합니다

.이 작업에 대해
* 빠른 제로화 기능 향상은 ONTAP 9.4 이전의 릴리즈에서 업그레이드된 시스템을 지원하지 않습니다.
* 클러스터의 노드에 빠른 제로화 드라이브가 있는 로컬 계층(애그리게이트)이 포함된 경우 클러스터를 ONTAP 9.2 이하 버전으로 되돌릴 수 없습니다.


.단계
. 부팅 메뉴에서 다음 옵션 중 하나를 선택합니다.
+
** (4) 구성을 청소하고 모든 디스크를 초기화합니다
** (9a) 모든 디스크의 파티션을 해제하고 해당 소유권 정보를 제거합니다
** (9b) 전체 디스크로 구성 정리 및 노드 초기화




--
====