---
permalink: disks-aggregates/hot-spare-disks-work-concept.html 
sidebar: sidebar 
keywords: hot, spare disks, work 
summary: 핫 스페어 디스크는 스토리지 시스템에 할당되어 사용할 준비가 되었지만 RAID 그룹에서 사용되지 않으며 데이터를 보유하지 않는 디스크입니다. 
---
= 핫 스페어 디스크의 작동 방식
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
핫 스페어 디스크는 스토리지 시스템에 할당되어 사용할 준비가 되었지만 RAID 그룹에서 사용되지 않으며 데이터를 보유하지 않는 디스크입니다.

RAID 그룹 내에서 디스크 장애가 발생하면 장애가 발생한 디스크를 교체하기 위해 핫 스페어 디스크가 RAID 그룹에 자동으로 할당됩니다. 장애가 발생한 디스크의 데이터는 RAID 패리티 디스크의 백그라운드에서 핫 스페어 교체 디스크에 재구성됩니다. 재구성 작업이 '/etc/message' 파일에 기록되고 AutoSupport 메시지가 전송된다.

사용 가능한 핫 스페어 디스크의 크기가 오류 발생 디스크와 동일하지 않은 경우 다음으로 큰 크기의 디스크를 선택한 다음 교체할 디스크의 크기에 맞게 크기를 축소합니다.



== 다중 디스크 캐리어 디스크의 예비 요구 사항

다중 디스크 캐리어의 디스크에 대해 적절한 수의 스페어를 유지하는 것은 스토리지 이중화를 최적화하고 ONTAP가 최적의 디스크 레이아웃을 달성하기 위해 디스크를 복사하는 데 소요되는 시간을 최소화하는 데 매우 중요합니다.

다중 디스크 캐리어 디스크용 핫 스페어를 항상 2개 이상 유지해야 합니다. 유지보수 센터의 사용을 지원하고 여러 번의 동시 디스크 장애로 인한 문제를 방지하려면 정상 상태 작동을 위해 최소 4개의 핫 스페어를 유지하고 장애가 발생한 디스크를 즉시 교체해야 합니다.

두 개의 디스크가 동시에 실패하고 사용 가능한 핫 스페어가 두 개뿐인 경우, ONTAP는 장애가 발생한 디스크와 해당 캐리어 메이트 모두의 내용을 스페어 디스크로 교환하지 못할 수 있습니다. 이 시나리오를 스토밍이라고 합니다. 이 경우 EMS 메시지 및 AutoSupport 메시지를 통해 알림을 받습니다. 교체 배송사를 사용할 수 있게 되면 EMS 메시지에서 제공하는 지침을 따라야 합니다. 자세한 내용은 기술 자료 문서를 참조하십시오 link:++https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Systems/FAS_Systems/Draft_-_RAID_Layout_Cannot_Be_Autocorrected_-_AutoSupport_message++["RAID 레이아웃을 자동 재지정할 수 없습니다 - AutoSupport 메시지"]
