---
permalink: disks-aggregates/manual-assign-ownership-partitioned-disks-task.html 
sidebar: sidebar 
keywords: manual, assign, disk, ownership, partition, disks 
summary: 분할되지 않은 디스크의 경우 그대로 수동으로 또는 자동 할당을 사용하여 컨테이너 디스크 또는 파티션의 소유권을 설정할 수 있습니다. 
---
= 분할된 디스크의 소유권을 수동으로 할당 개요
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
CLI를 사용하면 파티션되지 않은 디스크에 대한 것처럼 수동으로 또는 자동 할당을 사용하여 컨테이너 디스크 또는 파티션의 소유권을 설정할 수 있습니다.

[NOTE]
====
컨테이너의 디스크 중 하나가 채워진 셸프에서 장애가 발생하여 교체된 경우, ONTAP는 소유권을 자동으로 할당하지 않습니다. 이 경우 새 디스크를 수동으로 할당해야 합니다. 절반만 채워진 셸프에서 자동 할당 작업을 하려면 맨 오른쪽 베이에 디스크를 동일하게 놓고 나머지 6개는 맨 오른쪽에 배치합니다. 즉, 베이 0-5의 디스크 6개와 베이 18-23의 디스크 6개가 있습니다. ADP 구성 시스템에 컨테이너 디스크가 할당된 후에는 ONTAP 소프트웨어가 사용자 개입 없이 필요한 모든 파티셔닝 및 파티션 할당을 처리합니다.

====
CLI에서 다음 작업을 수행할 수 있습니다.

.루트 데이터 파티셔닝으로 디스크를 수동으로 할당합니다
[%collapsible]
====
루트 데이터 파티셔닝의 경우 HA 쌍이 소유하는 세 가지 엔터티(컨테이너 디스크 및 두 파티션)가 있습니다.

컨테이너 디스크와 두 파티션이 모두 HA 쌍의 노드 중 하나에 의해 소유되는 한 HA 쌍의 같은 노드에 의해 소유될 필요는 없습니다. 그러나 로컬 계층(집계)에서 파티션을 사용하는 경우 로컬 계층을 소유하는 동일한 노드에 의해 파티션이 소유되어야 합니다.

.단계
. CLI를 사용하여 파티션된 디스크의 현재 소유권을 표시합니다.
+
스토리지 디스크 show-disk_disk_name_-partition-ownership입니다

. CLI 권한 수준을 고급으로 설정합니다.
+
세트 프리빌리지 고급

. 소유권을 할당할 소유권 엔티티에 따라 적절한 명령을 입력합니다.
+
[cols="25,75"]
|===


| 다음에 대한 소유권을 할당하려면... | 이 명령 사용... 


 a| 
컨테이너 디스크
 a| 
'Storage disk assign-disk_name_-owner_owner_name_'



 a| 
데이터 파티션
 a| 
'storage disk assign-disk_name_-owner_owner_name_-data TRUE'



 a| 
루트 파티션입니다
 a| 
'storage disk assign-disk_name_-owner_owner_name_-root true'

|===
+
이미 소유된 소유권 요소가 있는 경우 ""-force" 옵션을 포함해야 합니다.



====
.루트-데이터-데이터 파티셔닝으로 디스크를 수동으로 할당합니다
[%collapsible]
====
루트 데이터 데이터 파티셔닝의 경우 HA 쌍이 통틀어 4개의 소유 엔터티(컨테이너 디스크 및 3개의 파티션)가 있습니다.

루트 데이터 - 데이터 파티셔닝은 루트 파티션으로 작은 파티션 하나를 생성하고 데이터에 대해 크기가 같은 큰 파티션 두 개를 생성합니다.

매개 변수는 disk assign 명령과 함께 사용해야 루트 데이터 분할 디스크의 적절한 파티션을 할당할 수 있습니다. 스토리지 풀의 일부인 디스크에는 이러한 매개 변수를 사용할 수 없습니다. 기본값은 ""false""입니다.

* "-data1 true" 매개 변수는 루트-data1-data2 분할 디스크의 "data1" 파티션을 할당합니다.
* "-data2 true" 매개 변수는 루트-data1-data2 분할 디스크의 "data2" 파티션을 할당합니다.


.단계
. CLI를 사용하여 파티션된 디스크의 현재 소유권을 표시합니다.
+
스토리지 디스크 show-disk_disk_name_-partition-ownership입니다

. CLI 권한 수준을 고급으로 설정합니다.
+
세트 프리빌리지 고급

. 소유권을 할당할 소유권 엔티티에 따라 적절한 명령을 입력합니다.
+
[cols="25,75"]
|===


| 다음에 대한 소유권을 할당하려면... | 이 명령 사용... 


 a| 
컨테이너 디스크
 a| 
'Storage disk assign-disk_name_-owner_owner_name_'



 a| 
Data1 파티션
 a| 
'storage disk assign-disk_name_-owner_owner_name_-data1 TRUE'



 a| 
데이터 2 파티션
 a| 
'storage disk assign-disk_name_-owner_owner_name_-data2 TRUE'



 a| 
루트 파티션입니다
 a| 
'storage disk assign-disk_name_-owner_owner_name_-root true'

|===


이미 소유된 소유권 요소가 있는 경우 ""-force" 옵션을 포함해야 합니다.

====