---
permalink: disks-aggregates/manual-assign-ownership-root-data-data-task.html 
sidebar: sidebar 
keywords: manual, assign, disks, root-data-data partitioning 
summary: '루트 데이터 데이터 파티셔닝의 경우 HA 쌍이 통틀어 4개의 소유 엔터티(컨테이너 디스크 및 3개의 파티션)가 있습니다.' 
---
= 루트-데이터-데이터 파티셔닝으로 디스크를 수동으로 할당합니다
:icons: font
:imagesdir: ../media/


[role="lead"]
루트 데이터 데이터 파티셔닝의 경우 HA 쌍이 통틀어 4개의 소유 엔터티(컨테이너 디스크 및 3개의 파티션)가 있습니다.

루트 데이터 - 데이터 파티셔닝은 루트 파티션으로 작은 파티션 하나를 생성하고 데이터에 대해 크기가 같은 큰 파티션 두 개를 생성합니다.

매개 변수는 disk assign 명령에 사용되어 루트 데이터 분할 디스크의 적절한 파티션을 할당해야 합니다. 스토리지 풀의 일부인 디스크에는 이러한 매개 변수를 사용할 수 없습니다. 기본값은 false 입니다.

* '[-data1[true]]' 매개변수는 루트-data1-data2 분할 디스크의 '_data1_' 파티션을 할당합니다.
* [-data2[true]] 매개변수는 루트-data1-data2 분할된 디스크의 '_data2_' 파티션을 할당합니다.


.단계
. 파티션된 디스크의 현재 소유권을 표시합니다.
+
스토리지 디스크 show-disk_disk_name_-partition-ownership입니다

. CLI 권한 수준을 고급으로 설정합니다.
+
세트 프리빌리지 고급

. 소유권을 할당할 소유권 엔티티에 따라 적절한 명령을 입력합니다.
+
|===


| 다음에 대한 소유권을 할당하려면... | 이 명령 사용... 


 a| 
컨테이너 디스크
 a| 
'스토리지 디스크 할당 - DISK_NAME - owner owner_name'



 a| 
Data1 파티션
 a| 
'storage disk assign-disk disk_name-owner owner_name-data1 true'



 a| 
데이터 2 파티션
 a| 
'storage disk assign-disk disk_name-owner owner_name-data2 TRUE'



 a| 
루트 파티션입니다
 a| 
'storage disk assign-disk disk_name - owner owner_name - root true'

|===


이미 소유된 소유권 요소가 있으면 '-force' 옵션을 포함해야 합니다.
