---
permalink: disks-aggregates/relocate-aggregate-ownership-task.html 
sidebar: sidebar 
keywords: relocate, aggregate, ownership 
summary: HA 쌍 내의 노드 간에만 애그리게이트의 소유권을 변경할 수 있습니다. 
---
= 애그리게이트 소유권을 재배치합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Aggregate의 서비스를 중단하지 않고 HA 쌍에서 노드 사이의 애그리게이트 소유권을 변경할 수 있습니다.

HA 쌍의 두 노드는 서로의 디스크 또는 어레이 LUN에 물리적으로 연결됩니다. 각 디스크 또는 어레이 LUN은 노드 중 하나가 소유합니다. 테이크오버 발생 시 디스크 소유권이 일시적으로 변경되더라도 애그리게이트 재배치 작업은 영구(예: 로드 밸런싱을 위해 수행된 경우) 또는 일시적으로(예: 테이크오버 중에 수행된 경우) 변경됩니다. Aggregate 내의 모든 디스크 또는 어레이 LUN의 소유권을 한 노드에서 다른 노드로 변경합니다. 데이터 복제 프로세스나 디스크 또는 어레이 LUN의 물리적 이동 없이 소유권이 변경됩니다.

.이 작업에 대해
* 애그리게이트 재배치 작업 중에 볼륨 개수 제한값의 유효성을 프로그래밍 방식으로 검사하기 때문에 수동으로 확인할 필요가 없습니다.
+
볼륨 수가 지원되는 제한을 초과하면 관련 오류 메시지와 함께 애그리게이트 재배치 작업이 실패합니다.

* 소스 또는 대상 노드에서 시스템 레벨 작업이 진행 중인 경우에는 애그리게이트 재배치를 시작하지 말아야 합니다. 마찬가지로 애그리게이트 재배치 중에는 이러한 작업을 시작하지 않아야 합니다.
+
이러한 작업에는 다음이 포함될 수 있습니다.

+
** 테이크오버
** 반환
** 종료
** 다른 집계 재배치 작업
** 디스크 소유권이 변경됩니다
** 애그리게이트 또는 볼륨 구성 작업
** 스토리지 컨트롤러 교체
** ONTAP 업그레이드
** ONTAP 복원


* MetroCluster 구성이 있는 경우 재해 복구 작업(_switchover_,_recovery_ 또는_스위치백_)이 진행되는 동안 애그리게이트 재배치를 시작하지 마십시오.
* MetroCluster 구성이 있고 전환된 애그리게이트상에서 애그리게이트 재배치를 시작하는 경우 DR 파트너의 볼륨 제한수를 초과하기 때문에 작업이 실패할 수 있습니다.
* 손상되었거나 유지 보수 중인 애그리게이트에 대해 애그리게이트 재배치를 시작하면 안 됩니다.
* 애그리게이트 재배치를 시작하기 전에 소스 및 대상 노드에 코어 덤프를 저장해야 합니다.


.단계
. 노드에서 애그리게이트를 확인하여 이동할 애그리게이트를 확인하고 온라인 상태이고 상태가 양호한지 확인합니다.
+
'Storage aggregate show -node_source-node_'

+
다음 명령을 실행하면 클러스터의 4개 노드에 있는 6개의 애그리게이트가 표시됩니다. 모든 애그리게이트는 온라인 상태입니다. 노드 1과 노드 3은 HA 쌍을 형성하고 노드 2와 노드 4는 HA 쌍을 형성합니다.

+
[listing]
----
cluster::> storage aggregate show
Aggregate     Size Available Used% State   #Vols  Nodes  RAID Status
--------- -------- --------- ----- ------- ------ ------ -----------
aggr_0     239.0GB   11.13GB   95% online       1 node1  raid_dp,
                                                         normal
aggr_1     239.0GB   11.13GB   95% online       1 node1  raid_dp,
                                                         normal
aggr_2     239.0GB   11.13GB   95% online       1 node2  raid_dp,
                                                         normal
aggr_3     239.0GB   11.13GB   95% online       1 node2  raid_dp,
                                                         normal
aggr_4     239.0GB   238.9GB    0% online       5 node3  raid_dp,
                                                         normal
aggr_5     239.0GB   239.0GB    0% online       4 node4  raid_dp,
                                                         normal
6 entries were displayed.
----
. 명령을 실행하여 애그리게이트 재배치를 시작합니다.
+
'Storage aggregate Relocation start-aggregate-list_aggregate-1_,_aggregate-2_... -node_source-node_-destination_destination-node_'입니다

+
다음 명령을 실행하면 aggr_1 및 aggr_2가 Node1에서 Node3으로 이동합니다. NODE3은 Node1의 HA 파트너입니다. 애그리게이트는 HA 쌍 내에서만 이동할 수 있습니다.

+
[listing]
----
cluster::> storage aggregate relocation start -aggregate-list aggr_1, aggr_2 -node node1 -destination node3
Run the storage aggregate relocation show command to check relocation status.
node1::storage aggregate>
----
. 'storage aggregate relocation show' 명령을 사용하여 애그리게이트 재배치의 진행 상황을 모니터링합니다.
+
'Storage aggregate relocation show -node_source-node_'

+
다음 명령을 실행하면 Node3으로 이동하는 애그리게이트의 진행률이 표시됩니다.

+
[listing]
----
cluster::> storage aggregate relocation show -node node1
Source Aggregate   Destination    Relocation Status
------ ----------- -------------  ------------------------
node1
       aggr_1      node3          In progress, module: wafl
       aggr_2      node3          Not attempted yet
2 entries were displayed.
node1::storage aggregate>
----
+
재배치가 완료되면 이 명령의 출력에 각 애그리게이트와 재배치 상태가 Done 인 이 표시됩니다.


