---
permalink: disks-aggregates/remove-ownership-disk-task.html 
sidebar: sidebar 
keywords: remove, ownership, disk 
summary: ONTAP는 디스크 소유권 정보를 디스크에 씁니다. 노드에서 스페어 디스크 또는 해당 쉘프를 제거하려면 먼저 소유권 정보를 제거하여 다른 노드에 올바르게 통합되도록 해야 합니다. 
---
= 디스크에서 소유권을 제거합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP는 디스크 소유권 정보를 디스크에 씁니다. 노드에서 스페어 디스크 또는 해당 쉘프를 제거하려면 먼저 소유권 정보를 제거하여 다른 노드에 올바르게 통합되도록 해야 합니다.


NOTE: 디스크가 루트 데이터 파티셔닝용으로 분할되어 있고 ONTAP 9.10.1 이상을 실행 중인 경우 NetApp 기술 지원 부서에 소유권 제거에 대한 지원을 요청하십시오. 자세한 내용은 를 참조하십시오 link:https://kb.netapp.com/onprem/ontap/hardware/Error%3A_command_failed%3A_Failed_to_remove_the_owner_of_disk["기술 문서: 디스크 소유자를 제거하지 못했습니다"].

.필요한 것
소유권을 제거할 디스크는 다음 요구 사항을 충족해야 합니다.

* 스페어 디스크여야 합니다.
+
로컬 계층(애그리게이트)에서 사용 중인 디스크에서는 소유권을 제거할 수 없습니다.

* 유지보수 센터에 있을 수 없습니다.
* 완전 삭제를 수행할 수 없습니다.
* 실패했을 수 없습니다.
+
오류가 발생한 디스크에서 소유권을 제거할 필요는 없습니다.



.이 작업에 대해
자동 디스크 할당을 활성화한 경우 ONTAP은 디스크에서 디스크를 제거하기 전에 소유권을 자동으로 재할당할 수 있습니다. 따라서 디스크를 제거할 때까지 자동 소유권 할당을 해제한 다음 다시 사용하도록 설정합니다.

.단계
. 디스크 소유권 자동 할당이 켜져 있는 경우 CLI를 사용하여 다음을 해제합니다.
+
'storage disk option modify -node_node_name_-autoassign off'

. 필요한 경우 노드의 HA 파트너에 대해 이전 단계를 반복합니다.
. 디스크에서 소프트웨어 소유권 정보를 제거합니다.
+
'Storage disk removeowner_disk_name_'

+
여러 디스크에서 소유권 정보를 제거하려면 쉼표로 구분된 목록을 사용합니다.

+
예:

+
....
storage disk removeowner sys1:0a.23,sys1:0a.24,sys1:0a.25
....
. 디스크가 루트 데이터 파티셔닝용으로 분할되어 있고 ONTAP 9.9.1 이하를 실행 중인 경우 파티션에서 소유권을 제거하십시오.
+
--
'storage disk removeowner - disk_disk_name_ - root true'

"스토리지 디스크 원격 소유자 -disk_disk_name_-data 참"

두 파티션은 더 이상 어떤 노드에서도 소유하지 않습니다.

--
. 이전에 디스크 소유권 자동 할당을 해제했다면 디스크를 제거하거나 재할당한 후에 이 기능을 켜십시오.
+
'스토리지 디스크 옵션 modify -node_node_name_-autostassign on'

. 필요한 경우 노드의 HA 파트너에 대해 이전 단계를 반복합니다.

