---
permalink: disks-aggregates/sanitize-disk-maintenance-mode-task.html 
sidebar: sidebar 
keywords: sanitize, disk, maintenance mode, nodeshell, node shell, sanitization 
summary: ONTAP 9.6부터는 유지보수 모드에서 디스크 완전 삭제를 수행할 수 있습니다. 이를 통해 사용 중단되거나 작동 불가능한 시스템의 디스크 또는 디스크 세트에서 데이터를 제거하여 데이터를 복구할 수 없습니다. 
---
= 디스크를 완전 살균합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
디스크를 제거하면 사용 중단되거나 작동 불가능한 시스템의 디스크 또는 디스크 세트에서 데이터를 제거하여 데이터를 복구할 수 없습니다.

CLI를 사용하여 디스크를 삭제하는 방법에는 두 가지가 있습니다.

.&#8220; 유지보수 모드&#8221; 명령(ONTAP 9.6 이상 릴리즈)을 사용하여 디스크 완전 삭제
====
ONTAP 9.6부터는 유지보수 모드에서 디스크 완전 삭제를 수행할 수 있습니다.

.시작하기 전에
* 디스크는 SED(자체 암호화 디스크)가 될 수 없습니다.
+
SED를 살균하려면 '스토리지 암호화 디스크 완전 삭제' 명령을 사용해야 합니다.

+
link:../encryption-at-rest/index.html["유휴 데이터의 암호화"]



.단계
. 유지보수 모드로 부팅합니다.
. 삭제할 디스크가 파티션된 경우 각 디스크의 파티션을 해제합니다.
+

NOTE: 디스크 파티션 해제를 위한 명령은 diag 수준에서만 사용할 수 있으며 NetApp 지원 부서의 감독 하에 수행해야 합니다. 계속하기 전에 NetApp Support에 문의하는 것이 좋습니다. 기술 자료 문서를 참조할 수도 있습니다 link:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Systems/FAS_Systems/How_to_unpartition_a_spare_drive_in_ONTAP["ONTAP에서 스페어 드라이브의 파티션을 해제하는 방법"^]

+
디스크 이름 _ 의 파티션을 해제했습니다

. 지정된 디스크 완전 삭제:
+
"디스크 삭제 시작[-p_Pattern1_|-r[-p_pattern2_|-r[-p_pattern 3_|-r]][-c_cycle_count_]_disk_list_"

+

NOTE: 삭제 중에 노드 전원을 끄거나 스토리지 연결을 중단하거나 타겟 디스크를 제거하지 마십시오. 포맷 단계에서 제거가 중단된 경우 디스크를 삭제하고 스페어 풀로 반환할 준비가 되기 전에 포맷 단계를 다시 시작하고 완료해야 합니다. 완전 삭제 프로세스를 중단해야 하는 경우 "disk sanitize abort" 명령을 사용하여 중단할 수 있습니다. 지정된 디스크가 완전 삭제의 포맷 단계를 진행 중인 경우 단계가 완료될 때까지 중단이 발생하지 않습니다.

+
'-p''_Pattern1_'-p'_pattern2_'-p'_pattern3_'은 삭제 중인 디스크에 연속적으로 적용할 수 있는 사용자 정의 16진수 바이트 덮어쓰기 패턴 1~3개의 주기를 지정합니다. 기본 패턴은 세 단계로, 첫 번째 패스는 0x55, 두 번째 패스는 0xAA, 세 번째 패스는 0x3c를 사용합니다.

+
'-r'은 패스의 일부 또는 전체에 대해 임의 덮어쓰기를 사용하여 패턴 덮어쓰기를 대체합니다.

+
'-c''_cycle_count_'는 지정된 덮어쓰기 패턴이 적용되는 횟수를 지정합니다. 기본값은 한 사이클입니다. 최대값은 7사이클입니다.

+
'_disk_list_'는 삭제할 스페어 디스크의 ID 목록을 공백으로 구분하여 지정합니다.

. 필요한 경우 디스크 삭제 프로세스의 상태를 확인합니다.
+
"DISK sanitize status[_DISK_LIST_]"

. 삭제 프로세스가 완료되면 각 디스크의 스페어 상태로 디스크를 반환합니다.
+
"isk sanitize release_disk_name_"

. 유지보수 모드를 종료합니다.


====
.&#8220;noteswell &#8221;명령(모든 ONTAP 9 릴리스)을 사용하여 디스크 완전 삭제
====
모든 버전의 ONTAP 9에서 notesHell 명령을 사용하여 디스크 완전 삭제를 활성화하면 일부 낮은 레벨의 ONTAP 명령이 비활성화됩니다. 노드에 디스크 삭제가 설정된 후에는 해제할 수 없습니다.

.시작하기 전에
* 디스크는 스페어 디스크여야 하며, 노드가 소유해야 하지만 로컬 계층(애그리게이트)에서는 사용할 수 없습니다.
+
디스크가 파티션된 경우 로컬 계층(집계)에서 두 파티션을 모두 사용할 수 없습니다.

* 디스크는 SED(자체 암호화 디스크)가 될 수 없습니다.
+
SED를 살균하려면 '스토리지 암호화 디스크 완전 삭제' 명령을 사용해야 합니다.

+
link:../encryption-at-rest/index.html["유휴 데이터의 암호화"]

* 디스크는 스토리지 풀에 포함될 수 없습니다.


.단계
. 삭제할 디스크가 파티션된 경우 각 디스크의 파티션을 해제합니다.
+
--

NOTE: 디스크 파티션 해제를 위한 명령은 diag 수준에서만 사용할 수 있으며 NetApp 지원 부서의 감독 하에 수행해야 합니다. ** 계속하기 전에 NetApp Support에 문의하는 것이 좋습니다. ** 기술 자료 문서를 참조할 수도 있습니다 link:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Systems/FAS_Systems/How_to_unpartition_a_spare_drive_in_ONTAP["ONTAP에서 스페어 드라이브의 파티션을 해제하는 방법"^].

--
+
디스크 이름 _ 의 파티션을 해제했습니다

. 삭제할 디스크를 소유하는 노드에 대한 노드 선택을 입력합니다.
+
'system node run-node_node_name_'

. 디스크 삭제 활성화:
+
"options licensed_feature.disk_densure.enable on"

+
명령을 취소할 수 없으므로 확인하라는 메시지가 표시됩니다.

. 노드 쉘의 고급 권한 레벨로 전환합니다.
+
'한자 진일보한

. 지정된 디스크 완전 삭제:
+
DEisk sanitize start [-p Pattern1 | -r [-p pattern 2 | -r [-p pattern 3 | -r]] [-c cycle_count] disk_list'

+

NOTE: 삭제 중에 노드 전원을 끄거나 스토리지 연결을 중단하거나 타겟 디스크를 제거하지 마십시오. 포맷 단계에서 제거가 중단된 경우 디스크를 삭제하고 스페어 풀로 반환할 준비가 되기 전에 포맷 단계를 다시 시작하고 완료해야 합니다. 완전 삭제 프로세스를 중단해야 하는 경우 disk sanitize abort 명령을 사용하여 중단할 수 있습니다. 지정된 디스크가 완전 삭제의 포맷 단계를 진행 중인 경우 단계가 완료될 때까지 중단이 발생하지 않습니다.

+
'-p Pattern1-p pattern2-p pattern 3'은 삭제 중인 디스크에 연속적으로 적용할 수 있는 사용자 정의 16진수 바이트 덮어쓰기 패턴 1-3개의 주기를 지정합니다. 기본 패턴은 세 단계로, 첫 번째 패스는 0x55, 두 번째 패스는 0xAA, 세 번째 패스는 0x3c를 사용합니다.

+
'-r'은 패스의 일부 또는 전체에 대해 임의 덮어쓰기를 사용하여 패턴 덮어쓰기를 대체합니다.

+
'-c cycle_count'는 지정된 덮어쓰기 패턴이 적용되는 횟수를 지정합니다.

+
기본값은 한 사이클입니다. 최대값은 7사이클입니다.

+
disk_list는 삭제할 스페어 디스크의 ID 목록을 공백으로 구분하여 지정합니다.

. 디스크 삭제 프로세스의 상태를 확인하려면 다음과 같이 하십시오.
+
'DISK_LIST' 상태 삭제

. 삭제 프로세스가 완료되면 디스크를 스페어 상태로 되돌립니다.
+
"isk sanitize release_disk_name_"

. 노드 관리자 권한 레벨로 돌아갑니다.
+
'priv set admin'

. ONTAP CLI로 돌아가기:
+
종료

. 모든 디스크가 스페어 상태로 돌아갔는지 확인합니다.
+
'스토리지 집계 show-spare-disks'

+
[cols="1,2"]
|===


| 만약... | 그러면... 


| 삭제된 모든 디스크가 스페어로 나열됩니다 | 완료되었습니다. 디스크가 삭제되었으며 예비 상태입니다. 


| 삭제된 디스크 중 일부는 스페어로 나열되지 않습니다  a| 
다음 단계를 완료합니다.

.. 고급 권한 모드 시작:
+
세트 프리빌리지 고급

.. 할당되지 않은 삭제된 디스크를 각 디스크의 적절한 노드에 할당합니다.
+
'Storage disk assign-disk_name_-owner_node_name_'

.. 디스크를 각 디스크의 예비 상태로 되돌립니다.
+
'storage disk unfail-disk_disk_name_-s-q'

.. 관리 모드로 돌아가기:
+
'Set-Privilege admin'입니다



|===


====
지정된 디스크가 삭제되어 핫 스페어로 지정됩니다. 삭제된 디스크의 일련 번호는 '/etc/log/살균된_disks'에 기록됩니다.

각 디스크에서 완료된 항목을 보여 주는 지정된 디스크의 삭제 로그는 '/mroot/etc/log/anitization.log'에 기록됩니다.
