---
permalink: disks-aggregates/set-cache-data-retention-policy-flash-pool-task.html 
sidebar: sidebar 
keywords: set, cache-retention policy, flash pool 
summary: 'Flash Pool 로컬 계층(애그리게이트)의 볼륨에 캐시 보존 정책을 할당할 수 있습니다. 캐시 보존 정책이 높은 볼륨의 데이터는 더 오랫동안 캐시에 유지되며 캐시 보존 정책이 낮은 볼륨의 데이터는 더 빨리 제거됩니다. 따라서 높은 우선 순위의 정보에 더 빠른 속도로 액세스하여 중요한 워크로드의 성능을 높일 수 있습니다.' 
---
= Flash Pool 로컬 계층(애그리게이트)에 대한 캐시 보존 정책 설정
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Flash Pool 로컬 계층(애그리게이트)의 볼륨에 캐시 보존 정책을 할당할 수 있습니다. 캐시 보존 정책이 높은 볼륨의 데이터는 더 오랫동안 캐시에 유지되며 캐시 보존 정책이 낮은 볼륨의 데이터는 더 빨리 제거됩니다. 따라서 높은 우선 순위의 정보에 더 빠른 속도로 액세스하여 중요한 워크로드의 성능을 높일 수 있습니다.

.필요한 것
시스템에 캐시 보존 정책이 캐시에 있는 데이터의 유지 기간에 영향을 미치지 않도록 하는 조건이 있는지 여부를 확인해야 합니다.

.단계
고급 권한 모드에서 CLI를 사용하여 다음 단계를 수행합니다.

. 권한 설정을 고급으로 변경합니다.
+
세트 프리빌리지 고급

. 볼륨의 캐시 보존 정책을 확인합니다.
+
기본적으로 캐시 보존 정책은 ""정상""입니다.

. 캐시 보존 정책 설정:
+
|===


| ONTAP 버전 | 명령 


 a| 
ONTAP 9.0, 9.1
 a| 
"priority hybrid-cache set volume_name read-cache=read_cache_value write-cache=write_cache_value cache-retention-priority=cache_retention_policy"입니다

캐시에 더 오래 보존하려는 데이터에 대해 cache_retention_policy를 "high"로 설정합니다. 캐시에서 더 빨리 제거할 데이터에 대해 cache_retention_policy를 low로 설정합니다.



 a| 
ONTAP 9.2 이상
 a| 
'volume modify -volume volume_name -vserver vserver_name -caching -policy policy_name.

|===
. 볼륨의 캐시 보존 정책이 선택한 옵션으로 변경되었는지 확인합니다.
. 권한 설정을 admin으로 되돌립니다.
+
'Set-Privilege admin'입니다


