---
permalink: disks-aggregates/sizing-raid-groups-concept.html 
sidebar: sidebar 
keywords: consideration, size, raid groups 
summary: 최적의 RAID 그룹 크기를 구성하려면 인수를 트레이드오프해야 합니다. RAID 재구성 속도, 드라이브 장애로 인한 데이터 손실 위험에 대한 보증, I/O 성능 최적화, 데이터 스토리지 공간 극대화와 같은 요소를 가장 중요하게 고려해야 합니다. 
---
= RAID 그룹의 크기를 조정할 때의 고려 사항
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
최적의 RAID 그룹 크기를 구성하려면 인수를 트레이드오프해야 합니다. RAID 재구성 속도, 드라이브 장애로 인한 데이터 손실 위험에 대한 보증, I/O 성능 최적화, 데이터 스토리지 공간 최대화 등 구성 중인 (로컬 계층) 애그리게이트에 가장 중요한 요소를 결정해야 합니다.

더 큰 RAID 그룹을 생성하면 패리티에 사용되는 것과 동일한 양의 스토리지(""패리티 세금"이라고도 함)에 대해 데이터 스토리지에 사용할 수 있는 공간을 극대화할 수 있습니다. 반면, 더 큰 RAID 그룹의 디스크에 장애가 발생할 경우 재구성 시간이 증가하여 장시간 성능에 영향을 미칩니다. 또한 RAID 그룹에 더 많은 디스크가 있을 경우 동일한 RAID 그룹 내에서 여러 디스크에 오류가 발생할 가능성이 높아집니다.



== HDD 또는 어레이 LUN RAID 그룹

HDD 또는 어레이 LUN으로 구성된 RAID 그룹을 사이징할 때는 다음 지침을 따라야 합니다.

* 로컬 계층(애그리게이트)의 모든 RAID 그룹은 디스크 수가 동일해야 합니다.
+
하나의 로컬 계층에 서로 다른 RAID 그룹의 디스크 수보다 최대 50% 적게 또는 많이 있을 수 있지만, 이로 인해 일부 경우 성능 병목 현상이 발생할 수 있으므로 피하는 것이 좋습니다.

* 권장되는 RAID 그룹 디스크 번호 범위는 12에서 20 사이입니다.
+
성능 디스크의 안정성은 필요한 경우 최대 28개의 RAID 그룹 크기를 지원할 수 있습니다.

* 여러 개의 RAID 그룹 디스크 번호를 사용하여 처음 두 지침을 충족할 수 있는 경우 더 많은 수의 디스크를 선택해야 합니다.




== Flash Pool 로컬 계층(애그리게이트)의 SSD RAID 그룹

SSD RAID 그룹 크기는 Flash Pool 로컬 계층(애그리게이트)에 있는 HDD RAID 그룹의 RAID 그룹 크기와 다를 수 있습니다. 일반적으로, 패리티에 필요한 SSD 수를 최소화하기 위해 Flash Pool 로컬 계층에 SSD RAID 그룹을 하나만 있어야 합니다.



== SSD 로컬 계층(애그리게이트)의 SSD RAID 그룹

SSD로 구성된 RAID 그룹의 크기를 지정할 때 다음 지침을 따라야 합니다.

* 로컬 계층(애그리게이트)의 모든 RAID 그룹에는 비슷한 수의 드라이브가 있어야 합니다.
+
RAID 그룹은 정확히 같은 크기를 가질 필요는 없지만 가능한 경우 동일한 로컬 계층에 있는 다른 RAID 그룹의 크기의 절반보다 작은 RAID 그룹을 가질 필요는 없습니다.

* RAID-DP의 경우 권장되는 RAID 그룹 크기 범위는 20에서 28 사이입니다.

