---
permalink: flexgroup/aggregate-space-requirements-concept.html 
sidebar: sidebar 
keywords: guideline, aggregate, space, provision, flexgroup, volume 
summary: FlexGroup 볼륨 프로비저닝을 위해 애그리게이트를 선택할 때 고려해야 할 사항과 요구사항을 알고 있어야 합니다. 
---
= FlexGroup 볼륨을 프로비저닝할 때 애그리게이트 공간을 위한 지침입니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
FlexGroup 볼륨 프로비저닝을 위해 애그리게이트를 선택할 때 고려해야 할 사항과 요구사항을 알고 있어야 합니다.

FlexGroup 볼륨에서 최상의 성능 결과를 얻으려면 FlexGroup 볼륨을 생성할 때 다음 지침을 고려해야 합니다.

* FlexGroup 볼륨은 동일한 하드웨어 시스템에 있는 애그리게이트에만 분산되어야 합니다.
+
동일한 하드웨어 시스템을 사용하면 FlexGroup 볼륨 전체에서 예측 가능한 성능을 제공할 수 있습니다.

* FlexGroup 볼륨은 디스크 유형과 RAID 그룹 구성이 동일한 애그리게이트로 확장되어야 합니다.
+
일관된 성능을 위해서는 모든 SSD, 모든 HDD 또는 모든 하이브리드 애그리게이트에서 사용할 수 있는지 확인해야 합니다. 또한 애그리게이트는 FlexGroup 볼륨 전체에서 동일한 수의 드라이브 및 RAID 그룹을 가져야 합니다.

* FlexGroup 볼륨은 클러스터의 일부를 포괄할 수 있습니다.
+
FlexGroup 볼륨을 전체 클러스터로 구성할 필요는 없지만 사용할 수 있는 하드웨어 리소스를 더 많이 활용할 수 있습니다.

* FlexGroup 볼륨을 생성할 때 FlexGroup 볼륨이 구축되어 있는 애그리게이트에 다음과 같은 특성을 갖는 것이 가장 좋습니다.
+
** 특히 씬 프로비저닝을 사용할 경우 여러 애그리게이트에서 거의 동일한 양의 여유 공간을 사용할 수 있어야 합니다.
** FlexGroup 볼륨을 생성한 후 여유 공간의 약 3%를 애그리게이트 메타데이터용으로 예약해야 합니다.


* FAS 시스템의 경우 노드당 두 개의 애그리게이트를 가질 수 있으며, AFF 시스템의 경우 FlexGroup 볼륨의 경우 노드당 하나의 애그리게이트를 가져야 합니다.
* 각 FlexGroup 볼륨에 대해 FAS 시스템의 2개 이상의 애그리게이트와 AFF 시스템의 하나 이상의 애그리게이트에 분산되어 있는 최소 8개의 구성요소를 생성해야 합니다.


.관련 정보
http://www.netapp.com/us/media/tr-4571.pdf["NetApp 기술 보고서 4571: NetApp FlexGroup 모범 사례 및 구현 가이드"^]
