---
permalink: flexgroup/convert-flexvol-volume-task.html 
sidebar: sidebar 
keywords: convert, flexvol, volume, flexgroup, conversion, flex vol, flex group, transitioned, 
summary: ONTAP 9.7부터 데이터 복사본이나 추가 디스크 공간 없이 FlexVol 볼륨을 FlexGroup 볼륨으로 데이터 이동 없이 전환할 수 있습니다. 
---
= FlexVol 볼륨을 FlexGroup 볼륨으로 변환합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9.7부터 데이터 복사본이나 추가 디스크 공간 없이 FlexVol 볼륨을 FlexGroup 볼륨으로 데이터 이동 없이 전환할 수 있습니다.

.시작하기 전에
* 전환된 볼륨은 ONTAP 9.8부터 FlexGroup 볼륨으로 변환할 수 있습니다.
* 변환 중인 FlexVol 볼륨은 온라인이어야 합니다.
* FlexVol 볼륨의 작업 및 구성은 변환 프로세스와 호환되어야 합니다.
+
변환이 성공하지 못하게 할 수 있는 다음 조건을 확인합니다.

+
** 7MTT(ONTAP 9.7)를 사용하여 FlexVol 볼륨을 7-Mode에서 전환했습니다.
+
전환된 볼륨은 ONTAP 9.8을 기준으로 변환할 수 있습니다.

** FlexGroup 볼륨에서 아직 지원되지 않는 볼륨(예: SAN LUN, Windows NFS, SMB1, 스냅샷 이름 지정/자동 삭제, 가상 집합, SnapLock, 공간 SLO 또는 논리적 공간 적용/보고 자세한 내용은 을 link:supported-unsupported-config-concept.html["FlexGroup 볼륨에 대해 지원 및 지원되지 않는 구성입니다"]참조하십시오.
** 변환하려는 FlexVol 볼륨이 위치한 SVM이 현재 SVM DR을 사용하고 있습니다.
** NetApp FlexClone 볼륨이 있고 FlexVol 볼륨이 상위 볼륨입니다. 변환 중인 볼륨은 상위 볼륨이거나 클론일 수 없습니다.
** 볼륨이 NetApp FlexCache 원본 볼륨입니다.
** ONTAP 9.7 이하 버전의 경우 NetApp 스냅샷 복사본이 255개를 초과하지 않아야 합니다. ONTAP 9.8 이상에서는 1023개의 스냅샷 복사본이 지원됩니다.
** 스토리지 효율성이 지원됩니다. 이러한 설정은 비활성화해야 하며 변환 후 다시 활성화할 수 있습니다.
** 볼륨이 SnapMirror 관계의 소스이고 타겟이 아직 변환되지 않았습니다.
** 이 볼륨은 활성(정지되지 않음) SnapMirror 관계의 일부입니다.
** 할당량이 설정되었습니다. 이러한 설정은 비활성화해야 하며 변환 후 다시 활성화할 수 있습니다.
** 볼륨 이름은 197자를 초과합니다.
** 볼륨이 애플리케이션에 연결되어 있습니다.
+
이는 ONTAP 9.7에만 적용됩니다. ONTAP 9.8에서는 제한이 제거되었습니다.

** 미러링, 작업, wapliron, ndmp 백업 ONTAP, 및 inode 변환이 진행 중입니다.
** 볼륨이 SVM 루트 볼륨입니다.
** 볼륨이 너무 가득 찼습니다.
+
이러한 비호환성이 존재하는 경우 FlexVol 볼륨이 생성되고 볼륨 변환이 중단되면 오류 메시지가 생성됩니다. 수정 조치를 취하고 변환을 다시 시도할 수 있습니다.



* FlexVol 볼륨의 현재 최대 용량이 80% 이상인 경우 데이터 이동 없이 변환을 수행하는 대신 새로 생성된 FlexGroup 볼륨에 데이터를 복사하는 것이 좋습니다. FlexGroup 구성원 볼륨은 시간이 지남에 따라 자연스럽게 재조정되지만 대용량 FlexVol 볼륨을 FlexGroup 볼륨으로 변환하면 성능 또는 균형 문제가 발생하여 구성원 볼륨 간에 신속하게 재조정되지 않을 수 있습니다.
+
[NOTE]
====
매우 큰 FlexGroup 볼륨을 변환하면 FlexGroup 볼륨 멤버 구성요소가 가득 차서 성능 문제가 발생할 수 있습니다. 자세한 내용은 TR에서 "FlexGroup 볼륨을 생성하지 않을 경우"라는 섹션을 참조하십시오 link:https://www.netapp.com/media/12385-tr4571.pdf["FlexGroup 볼륨 - 모범 사례 및 구현 가이드"].

====


.단계
. FlexVol 볼륨이 온라인 상태인지 확인합니다. `volume show vol_name volume-style-extended,state`
+
[listing]
----
cluster-1::> volume show my_volume -fields volume-style-extended,state
vserver volume    state  volume-style-extended
------- --------- ------ ---------------------
vs0     my_volume online flexvol
----
. FlexVol 볼륨을 문제 없이 변환할 수 있는지 확인합니다.
+
.. 'Set-Privilege advanced'라는 고급 권한 모드로 로그인합니다
.. 변환 프로세스 'volume conversion start - vserver vs1-volume FlexVol - check-only true'를 확인합니다
+
볼륨을 변환하기 전에 모든 오류를 수정해야 합니다.

+
[NOTE]
====
FlexGroup 볼륨을 FlexVol 볼륨으로 다시 변환할 수 없습니다.

====


. 'volume conversion start -vserver svm_name -volume vol_name' 변환을 시작합니다
+
[listing]
----
cluster-1::*> volume conversion start -vserver vs0 -volume my_volume

Warning: Converting flexible volume "my_volume" in Vserver "vs0" to a FlexGroup
         will cause the state of all Snapshot copies from the volume to be set
         to "pre-conversion". Pre-conversion Snapshot copies cannot be
         restored.
Do you want to continue? {y|n}: y
[Job 57] Job succeeded: success
----
. 변환이 성공적인지 확인합니다. `volume show vol_name -fields volume-style-extended,state`
+
[listing]
----
cluster-1::*> volume show my_volume -fields volume-style-extended,state
vserver volume    state  volume-style-extended
------- --------- ------ ---------------------
vs0     my_volume online flexgroup
----


.결과
FlexVol 볼륨은 단일 멤버 FlexGroup 볼륨으로 변환됩니다.

.작업을 마친 후
필요에 따라 FlexGroup 볼륨을 확장할 수 있습니다.
