---
permalink: flexgroup/convert-flexvol-snapmirror-relationship-task.html 
sidebar: sidebar 
keywords: convert, flexvol, volume, snapmirror, relation, flexgroup 
summary: FlexVol 볼륨 SnapMirror 관계를 ONTAP에서 FlexGroup 볼륨 SnapMirror 관계로 변환하려면 먼저 대상 FlexVol 볼륨을 변환한 다음 소스 FlexVol 볼륨을 변환해야 합니다. 
---
= FlexVol 볼륨 SnapMirror 관계를 FlexGroup 볼륨 SnapMirror 관계로 변환합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
FlexVol 볼륨 SnapMirror 관계를 ONTAP에서 FlexGroup 볼륨 SnapMirror 관계로 변환하려면 먼저 대상 FlexVol 볼륨을 변환한 다음 소스 FlexVol 볼륨을 변환해야 합니다.

.이 작업에 대해
* FlexGroup 변환은 SnapMirror 비동기 관계에 대해서만 지원됩니다.
* 변환 시간은 여러 변수에 따라 달라집니다. 일부 변수는 다음과 같습니다.
+
** 컨트롤러의 CPU입니다
** 다른 애플리케이션의 CPU 사용률
** 최초 스냅샷 복사본에 있는 데이터의 양입니다
** 네트워크 대역폭
** 다른 응용 프로그램에서 사용하는 대역폭




.시작하기 전에
* 변환 중인 FlexVol 볼륨은 온라인이어야 합니다.
* SnapMirror 관계의 소스 FlexVol 볼륨은 여러 SnapMirror 관계의 소스 볼륨이 아니어야 합니다.
+
ONTAP 9.9.1부터 팬아웃 SnapMirror 관계가 FlexGroup 볼륨에 대해 지원됩니다. 자세한 내용은 을 link:../flexgroup/create-snapmirror-cascade-fanout-reference.html#considerations-for-creating-cascading-relationships["FlexGroups에 대한 계단식 SnapMirror 및 팬아웃 관계를 생성할 때의 고려 사항"]참조하십시오.

* FlexVol 볼륨의 작업 및 구성은 변환 프로세스와 호환되어야 합니다.
+
FlexVol 볼륨에 비호환성이 있으며 볼륨 변환이 중단된 경우 오류 메시지가 생성됩니다. 수정 조치를 취하고 변환을 다시 시도할 수 있습니다.



.단계
. SnapMirror 관계가 정상 상태인지 확인:
+
[source, cli]
----
snapmirror show
----
+
XDP 유형의 미러 관계만 변환할 수 있습니다.

+
예:

+
[listing]
----
cluster2::> snapmirror show
                                                                       Progress
Source            Destination Mirror  Relationship   Total             Last
Path        Type  Path        State   Status         Progress  Healthy Updated
----------- ---- ------------ ------- -------------- --------- ------- --------
vs0:src_dpv DP   vs2:dst_dpv  Snapmirrored
                                      Idle           -         true    -
vs0:src_xdp XDP  vs2:dst_xdp  Snapmirrored
                                      Idle           -         true    -
----
. 소스 볼륨이 변환에 대해 호환되는지 확인합니다.
+
.. advance 권한 모드로 로그인합니다.
+
[source, cli]
----
set -privilege advanced
----
.. 변환 프로세스를 확인합니다.
+
[source, cli]
----
volume conversion start -vserver <src_svm_name> -volume <src_vol> -check-only true
----
+
예:

+
[listing]
----
volume conversion start -vserver vs1 -volume src_vol -check-only true
----
+
볼륨을 변환하기 전에 모든 오류를 수정해야 합니다.



. 대상 FlexVol 볼륨을 FlexGroup 볼륨으로 변환합니다.
+
.. FlexVol SnapMirror 관계 중지:
+
[source, cli]
----
snapmirror quiesce -destination-path <dest_svm:dest_volume>
----
+
예:

+
[listing]
----
cluster2::> snapmirror quiesce -destination-path vs2:dst_xdp
----
.. 변환 시작:
+
[source, cli]
----
volume conversion start -vserver <dest_svm> -volume <dest_volume>
----
+
예:

+
[listing]
----
cluster-1::> volume conversion start -vserver vs2 -volume dst_xdp

Warning: After the volume is converted to a FlexGroup, it will not be possible
to change it back to a flexible volume.
Do you want to continue? {y|n}: y

[Job 510] Job succeeded: SnapMirror destination volume "dst_xdp" has been successfully converted to a FlexGroup volume.
You must now convert the relationship's source volume, "vs0:src_xdp", to a FlexGroup.
Then, re-establish the SnapMirror relationship using the "snapmirror resync" command.
----


. 소스 FlexVol 볼륨을 FlexGroup 볼륨으로 변환:'
+
[source, cli]
----
volume conversion start -vserver <src_svm_name> -volume <src_vol_name>
----
+
예:

+
[listing]
----
cluster-1::> volume conversion start -vserver vs0 -volume src_xdp

Warning: Converting flexible volume "src_xdp" in Vserver "vs0" to a FlexGroup
         will cause the state of all Snapshot copies from the volume to be set
         to "pre-conversion". Pre-conversion Snapshot copies cannot be
         restored.
Do you want to continue? {y|n}: y
[Job 57] Job succeeded: success
----
. 관계 다시 동기화:
+
[source, cli]
----
snapmirror resync -destination-path dest_svm_name:dest_volume
----
+
예:

+
[listing]
----
cluster2::> snapmirror resync -destination-path vs2:dst_xdp
----


.작업을 마친 후
소스 FlexGroup 볼륨을 확장하여 더 많은 구성 요소까지 포함할 때는 대상 볼륨도 확장되어야 합니다.
