---
permalink: flexgroup/convert-flexvol-volume-task.html 
sidebar: sidebar 
keywords: convert, flexvol, volume, flexgroup, conversion, flex vol, flex group, transitioned, 
summary: ONTAP 9.7부터 데이터 복사본이나 추가 디스크 공간 없이 FlexVol 볼륨을 FlexGroup 볼륨으로 데이터 이동 없이 전환할 수 있습니다. 
---
= FlexVol 볼륨을 FlexGroup 볼륨으로 변환합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9.7부터 데이터 복사본이나 추가 디스크 공간 없이 FlexVol 볼륨을 FlexGroup 볼륨으로 데이터 이동 없이 전환할 수 있습니다.

.무엇을 &#8217;필요로 할거야
* 전환된 볼륨은 FlexGroup 볼륨으로 변환할 수 있습니다.
+
전환된 볼륨을 FlexGroup 볼륨으로 변환하려면 diag 모드가 필요하며 NetApp 지원 부서의 감독 하에 수행해야 합니다. 전환 프로세스를 진행하기 전에 NetApp Support에 먼저 문의하십시오.

* 변환 중인 FlexVol 볼륨은 온라인이어야 합니다.
* FlexVol 볼륨의 작업 및 구성은 변환 프로세스와 호환되어야 합니다.
+
FlexVol 볼륨에 비호환성이 있으며 볼륨 변환이 중단된 경우 오류 메시지가 생성됩니다. 수정 조치를 취하고 변환을 다시 시도할 수 있습니다.



.단계
. FlexVol 볼륨이 온라인인지 확인합니다. volume show vol_name-volume-style-extended, state
+
[listing]
----
cluster-1::> volume show my_volume -fields volume-style-extended,state
vserver volume    state  volume-style-extended
------- --------- ------ ---------------------
vs0     my_volume online flexvol
----
. FlexVol 볼륨을 문제 없이 변환할 수 있는지 확인합니다.
+
.. 'Set-Privilege advanced'라는 고급 권한 모드로 로그인합니다
.. 변환 프로세스 'volume conversion start - vserver vs1-volume FlexVol - check-only true'를 확인합니다
+
볼륨을 변환하기 전에 모든 오류를 수정해야 합니다.

+
[NOTE]
====
FlexGroup 볼륨을 FlexVol 볼륨으로 다시 변환할 수 없습니다. 그러려면 지원 팀에 문의해야 합니다.

====


. 'volume conversion start -vserver svm_name -volume vol_name' 변환을 시작합니다
+
[listing]
----
cluster-1::*> volume conversion start -vserver vs0 -volume my_volume

Warning: Converting flexible volume "my_volume" in Vserver "vs0" to a FlexGroup
         will cause the state of all Snapshot copies from the volume to be set
         to "pre-conversion". Pre-conversion Snapshot copies cannot be
         restored.
Do you want to continue? {y|n}: y
[Job 57] Job succeeded: success
----
. 볼륨 표시 vol_name-fields-volume-style-extended, state가 성공적으로 변환되었는지 확인합니다
+
[listing]
----
cluster-1::*> volume show my_volume -fields volume-style-extended,state
vserver volume    state  volume-style-extended
------- --------- ------ ---------------------
vs0     my_volume online flexgroup
----


FlexVol 볼륨은 단일 멤버 FlexGroup 볼륨으로 변환됩니다.

필요에 따라 FlexGroup 볼륨을 확장할 수 있습니다.
