---
permalink: flexgroup/create-snapmirror-relationship-task.html 
sidebar: sidebar 
keywords: create, snapmirror, relationship, flexgroup, volume, snap mirror, flex group, peered svm, replicate, replicating, disaster 
summary: 재해 복구를 위해 데이터를 복제하기 위해 피어링된 SVM에서 소스 FlexGroup 볼륨과 타겟 FlexGroup 볼륨 간에 SnapMirror 관계를 생성합니다. 
---
= FlexGroup 볼륨에 대한 SnapMirror 관계를 생성합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
재해 복구를 위한 데이터 복제를 위해 소스 FlexGroup 볼륨과 타겟 FlexGroup 볼륨 사이에 SnapMirror 관계를 구축할 수 있습니다. 재해가 발생할 경우 FlexGroup 볼륨의 미러 복사본을 사용하여 데이터를 복구할 수 있습니다.

.시작하기 전에
클러스터 피어링 관계와 SVM 피어링 관계를 생성해야 합니다.

link:../peering/index.html["클러스터 및 SVM 피어링"]

.이 작업에 대해
* ONTAP 9.9.1부터 ONTAP CLI를 사용하여 FlexGroup 볼륨에 대한 SnapMirror 계단식 배열 및 팬아웃 관계를 생성할 수 있습니다. 자세한 내용은 을 참조하십시오 link:create-snapmirror-cascade-fanout-reference.html["FlexGroups에 대한 계단식 SnapMirror 및 팬아웃 관계를 생성할 때의 고려 사항"].
* FlexGroup 볼륨에 대한 인터클러스터 SnapMirror 관계와 클러스터 간 SnapMirror 관계를 모두 생성할 수 있습니다.
* ONTAP 9.3부터 SnapMirror 관계에 있는 FlexGroup 볼륨을 확장할 수 있습니다.
+
ONTAP 9.3 이전 버전의 ONTAP를 사용하는 경우 SnapMirror 관계가 설정된 후에는 FlexGroup 볼륨을 확장해서는 안 되지만, SnapMirror 관계를 설정한 후에는 FlexGroup 볼륨의 용량을 늘릴 수 있습니다. ONTAP 9.3 이전의 릴리즈에서 SnapMirror 관계를 끊은 후 소스 FlexGroup 볼륨을 확장하는 경우 대상 FlexGroup 볼륨에 대한 기본 전송을 수행해야 합니다.



.단계
. 소스 FlexGroup 볼륨과 구성 요소 수가 동일한 dP 유형의 대상 FlexGroup 볼륨을 생성합니다.
+
.. 소스 클러스터에서 소스 FlexGroup 볼륨의 구성요소 수('volume show-volume volume_name * -is-f성분 TRUE')를 결정합니다
+
[listing]
----
cluster1::> volume show  -volume srcFG* -is-constituent true
Vserver   Volume       Aggregate    State      Type       Size  Available Used%
--------- ------------ ------------ ---------- ---- ---------- ---------- -----
vss       srcFG          -            online     RW         400TB   172.86GB  56%
vss       srcFG__0001    Aggr_cmode   online     RW         25GB    10.86TB   56%
vss       srcFG__0002    aggr1        online     RW         25TB    10.86TB   56%
vss       srcFG__0003    Aggr_cmode   online     RW         25TB    10.72TB   57%
vss       srcFG__0004    aggr1        online     RW         25TB    10.73TB   57%
vss       srcFG__0005    Aggr_cmode   online     RW         25TB    10.67TB   57%
vss       srcFG__0006    aggr1        online     RW         25TB    10.64TB   57%
vss       srcFG__0007    Aggr_cmode   online     RW         25TB    10.63TB   57%
...
----
.. 대상 클러스터에서 소스 FlexGroup 볼륨과 동일한 수의 구성 요소와 함께 dP 유형의 대상 FlexGroup 볼륨을 생성합니다.
+
[listing]
----
cluster2::> volume create -vserver vsd -aggr-list aggr1,aggr2 -aggr-list-multiplier 8 -size 400TB -type DP dstFG

Warning: The FlexGroup volume "dstFG" will be created with the following number of constituents of size 25TB: 16.
Do you want to continue? {y|n}: y
[Job 766] Job succeeded: Successful
----
.. 대상 클러스터에서 대상 FlexGroup 볼륨에 있는 구성 요소 수('volume show-volume volume volume_name * -is-f성분 TRUE')를 확인합니다
+
[listing]
----
cluster2::> volume show  -volume dstFG* -is-constituent true
Vserver   Volume        Aggregate    State      Type       Size  Available  Used%
--------- ------------  ------------ ---------- ---- ----------  ---------- -----
vsd       dstFG          -            online     DP         400TB   172.86GB  56%
vsd       dstFG__0001    Aggr_cmode   online     DP         25GB    10.86TB   56%
vsd       dstFG__0002    aggr1        online     DP         25TB    10.86TB   56%
vsd       dstFG__0003    Aggr_cmode   online     DP         25TB    10.72TB   57%
vsd       dstFG__0004    aggr1        online     DP         25TB    10.73TB   57%
vsd       dstFG__0005    Aggr_cmode   online     DP         25TB    10.67TB   57%
vsd       dstFG__0006    aggr1        online     DP         25TB    10.64TB   57%
vsd       dstFG__0007    Aggr_cmode   online     DP         25TB    10.63TB   57%
...
----


. 작업 일정 생성:'작업 일정 cron create-name job_name-month month-DayOfWeek day_of_week-day day_of_month-hour-minute'입니다
+
월-일-일-주-시간 옵션을 선택하면 월, 요일, 시간마다 작업을 실행하도록 모두 를 지정할 수 있습니다.

+
다음 예에서는 토요일 오전 3시에 실행되는 my_weekly라는 작업 일정을 생성합니다.

+
[listing]
----
cluster1::> job schedule cron create -name my_weekly -dayofweek "Saturday" -hour 3 -minute 0
----
. SnapMirror 관계에 대해 '비동기 미러' 유형의 사용자 지정 정책을 생성합니다. '스냅샷 정책 생성 - SVM SVM-정책 SnapMirror_policy-type async-mirror'
+
사용자 지정 정책을 만들지 않는 경우 SnapMirror 관계에 대한 "irrorAllSnapshots" 정책을 지정해야 합니다.

. 대상 클러스터에서 소스 FlexGroup 볼륨과 대상 FlexGroup 볼륨 간에 SnapMirror 관계를 생성합니다. 'sapmirror create-source-path src_svm:src_flexgroup-destination-path dest_svm:dest_flexgroup-type XDP 정책 snapmirror_policy-schedule sched_name'
+
FlexGroup 볼륨의 SnapMirror 관계는 XDP 유형이어야 합니다.

+
FlexGroup 볼륨에 대한 SnapMirror 관계의 스로틀 값을 지정하는 경우 각 구성요소에서 동일한 스로틀 값을 사용합니다. 스로틀 값은 구성 요소별로 나누지 않습니다.

+
[NOTE]
====
FlexGroup 볼륨에 대한 스냅샷 복사본의 SnapMirror 레이블을 사용할 수 없습니다.

====
+
ONTAP 9.4 이하 버전에서는, 정책이 '스냅샷 생성' 명령으로 지정되지 않으면 기본적으로 'irorAllSnapshots' 정책이 사용됩니다. ONTAP 9.5에서는 '스냅샷 생성' 명령으로 정책을 지정하지 않으면 기본적으로 'MirorAndVault' 정책이 사용됩니다.

+
[listing]
----
cluster2::> snapmirror create -source-path vss:srcFG -destination-path vsd:dstFG -type XDP -policy MirrorAllSnapshots -schedule hourly
Operation succeeded: snapmirror create for the relationship with destination "vsd:dstFG".
----
. 대상 클러스터에서 기본 전송인 '스냅샷 초기화 - 대상 경로 dest_svm: dest_flexgroup'을 수행하여 SnapMirror 관계를 초기화합니다
+
기본 전송이 완료되면 SnapMirror 관계의 일정에 따라 대상 FlexGroup 볼륨이 정기적으로 업데이트됩니다.

+
[listing]
----
cluster2::> snapmirror initialize -destination-path vsd:dstFG
Operation is queued: snapmirror initialize of destination "vsd:dstFG".
----
+
[NOTE]
====
ONTAP 9.3을 실행하는 소스 클러스터와 ONTAP 9.2 이하를 실행하는 타겟 클러스터 간에 FlexGroup 볼륨 간에 SnapMirror 관계가 생성되었으며 소스 FlexGroup 볼륨에서 qtree를 생성하는 경우 SnapMirror 업데이트가 실패합니다. 이 상황을 복구하려면 FlexGroup 볼륨에서 기본이 아닌 모든 qtree를 삭제하고 FlexGroup 볼륨에서 qtree 기능을 비활성화한 다음 qtree 기능이 활성화된 모든 스냅샷 복사본을 삭제해야 합니다.

====


.작업을 마친 후
LIF 및 엑스포트 정책과 같은 필수 구성을 설정하여 데이터 액세스를 위한 타겟 SVM을 설정해야 합니다.
