---
permalink: flexgroup/increase-capacity-task.html 
sidebar: sidebar 
keywords: increase, size, flexgroup, volume, flex group 
summary: FlexGroup 볼륨의 기존 구성요소에 용량을 추가하거나 새로운 구성원 볼륨으로 FlexGroup 볼륨을 확장하여 FlexGroup 볼륨의 크기를 늘릴 수 있습니다. 
---
= FlexGroup 볼륨의 크기를 늘립니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
FlexGroup 볼륨의 기존 구성원 볼륨(구성요소)에 용량을 추가하거나 새 구성원 볼륨으로 FlexGroup 볼륨을 확장하여 FlexGroup 볼륨의 크기를 늘릴 수 있습니다. FlexGroup 볼륨은 200개 이상의 구성원 볼륨을 포함할 수 없습니다.

.시작하기 전에
Aggregate에 충분한 공간이 있어야 합니다.

.이 작업에 대해
공간을 더 추가하려면 FlexGroup 볼륨의 전체 크기를 늘릴 수 있습니다. FlexGroup 볼륨의 크기를 늘리면 FlexGroup 볼륨의 기존 구성원 볼륨의 크기가 조정됩니다.

성능을 향상시키려면 FlexGroup 볼륨을 확장할 수 있습니다. 다음과 같은 경우 FlexGroup 볼륨을 확장하고 새 구성원 볼륨을 추가할 수 있습니다.

* 클러스터에 새 노드가 추가되었습니다.
* 기존 노드에서 새 애그리게이트가 생성되었습니다.
* FlexGroup 볼륨의 기존 구성원 볼륨이 하드웨어의 최대 FlexVol 크기(100TB 또는 300TB(가 활성화된 경우)에 도달했으므로 link:../volumes/enable-large-vol-file-support-task.html["대용량 지원"]구성원 볼륨을 추가하지 않으면 FlexGroup 볼륨의 크기를 조정할 수 없습니다.


ONTAP 9.3 이전 릴리즈에서는 SnapMirror 관계가 설정된 후 FlexGroup 볼륨을 확장해서는 안 됩니다. ONTAP 9.3 이전의 릴리즈에서 SnapMirror 관계를 끊은 후 소스 FlexGroup 볼륨을 확장하는 경우 대상 FlexGroup 볼륨에 대한 기본 전송을 다시 수행해야 합니다. ONTAP 9.3부터 SnapMirror 관계에 있는 FlexGroup 볼륨을 확장할 수 있습니다.

.단계
. 필요에 따라 FlexGroup 볼륨의 용량 또는 성능을 늘려서 FlexGroup 볼륨의 크기를 늘립니다.
+
|===


| 를 증가하려면... | 다음을 수행하십시오. 


 a| 
FlexGroup 볼륨의 용량입니다
 a| 
FlexGroup 볼륨의 구성원 볼륨 크기 조정:

'volume modify -vserver vserver_name -volume fg_name -size new_size'



 a| 
FlexGroup 볼륨의 성능입니다
 a| 
새 구성원 볼륨(구성 요소)을 추가하여 FlexGroup 볼륨 확장:

'+volume expand-vserver vserver_name-volume fg_name-aggr-list 집계 이름,... [-aggr-list-multiplier f구성요소_per_aggr]+'

'-aggr-list-multiplier' 파라미터의 기본값은 1이다.

ONTAP 9.5에서 FabricPool용 FlexGroup 볼륨을 확장하려면 사용된 새 애그리게이트는 FabricPool여야 합니다.

|===


가능하면 FlexGroup 볼륨의 용량을 늘려야 합니다. FlexGroup 볼륨을 확장해야 하는 경우 일관된 성능을 보장하기 위해 기존 FlexGroup 볼륨의 구성원 볼륨과 동일한 배수의 구성원 볼륨을 추가해야 합니다. 예를 들어, 기존 FlexGroup 볼륨에 노드당 8개의 구성원 볼륨이 있는 16개의 구성원 볼륨이 있는 경우 기존 FlexGroup 볼륨을 8 또는 16개의 구성원 볼륨까지 확장할 수 있습니다.

.예
* 기존 구성원 볼륨의 용량을 늘리는 예 *

다음 예에서는 FlexGroup 볼륨 volX에 20TB 공간을 추가하는 방법을 보여 줍니다.

[listing]
----
cluster1::> volume modify -vserver svm1 -volume volX -size +20TB
----
FlexGroup 볼륨에 16개의 구성원 볼륨이 있는 경우 각 구성원 볼륨의 공간이 1.25TB씩 증가합니다.

* 새 구성원 볼륨을 추가하여 성능을 향상시키는 예 *

다음 예에서는 FlexGroup 볼륨 volX에 두 개의 구성원 볼륨을 추가하는 방법을 보여 줍니다.

[listing]
----
cluster1::> volume expand -vserver vs1 -volume volX -aggr-list aggr1,aggr2
----
새 구성원 볼륨의 크기는 기존 구성원 볼륨의 크기와 동일합니다.
