---
permalink: flexgroup/monitor-snapmirror-data-transfers-task.html 
sidebar: sidebar 
keywords: monitor, snapmirror, data, transfer, flexgroup, volumes 
summary: FlexGroup 볼륨 SnapMirror 관계의 상태를 주기적으로 모니터링하여 대상 FlexGroup 볼륨이 지정된 일정에 따라 정기적으로 업데이트되는지 확인해야 합니다. 
---
= FlexGroup 볼륨에 대한 SnapMirror 데이터 전송을 모니터링합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
FlexGroup 볼륨 SnapMirror 관계의 상태를 주기적으로 모니터링하여 대상 FlexGroup 볼륨이 지정된 일정에 따라 정기적으로 업데이트되는지 확인해야 합니다.

.이 작업에 대해
대상 클러스터에서 이 작업을 수행해야 합니다.

.단계
. '스냅미러 show-relationship-group-type FlexGroup'와 같은 모든 FlexGroup 볼륨 관계의 SnapMirror 관계 상태를 봅니다
+
[listing]
----
cluster2::> snapmirror show -relationship-group-type flexgroup
                                                                       Progress
Source            Destination Mirror  Relationship   Total             Last
Path        Type  Path        State   Status         Progress  Healthy Updated
----------- ---- ------------ ------- -------------- --------- ------- --------
vss:s       XDP  vsd:d        Snapmirrored
                                      Idle           -         true    -
vss:s2      XDP  vsd:d2       Uninitialized
                                      Idle           -         true    -
2 entries were displayed.
----
. FlexGroup volume의 각 구성요소에 대한 SnapMirror 관계 상태 '스냅샷 표시-확장'을 확인하십시오
+
[listing]
----
cluster2::> snapmirror show -expand
                                                                       Progress
Source            Destination Mirror  Relationship   Total             Last
Path        Type  Path        State   Status         Progress  Healthy Updated
----------- ---- ------------ ------- -------------- --------- ------- --------
vss:s       XDP  vsd:d        Snapmirrored
                                      Idle           -         true    -
vss:s__0001 XDP  vsd:d__0001  Snapmirrored
                                      Idle           -         true    -
vss:s__0002 XDP  vsd:d__0002  Snapmirrored
                                      Idle           -         true    -
vss:s__0003 XDP  vsd:d__0003  Snapmirrored
                                      Idle           -         true    -
vss:s__0004 XDP  vsd:d__0004  Snapmirrored
                                      Idle           -         true    -
vss:s__0005 XDP  vsd:d__0005  Snapmirrored
                                      Idle           -         true    -
vss:s__0006 XDP  vsd:d__0006  Snapmirrored
                                      Idle           -         true    -
vss:s__0007 XDP  vsd:d__0007  Snapmirrored
                                      Idle           -         true    -
vss:s__0008 XDP  vsd:d__0008  Snapmirrored
                                      Idle           -         true    -
...
----
. SnapMirror 전송이 실패한 경우 전송에 실패한 FlexGroup 볼륨 구성요소와 '스냅샷 표시-필드 마지막 전송-오류-확장'이라는 오류 원인을 식별합니다
+
[listing]
----
cluster2::> snapmirror show -fields last-transfer-error -expand
source-path destination-path last-transfer-error
----------- ---------------- -----------------------------------------------
vss:s       vsd:d            Group Update failed (Failed to complete update operation on one or more item relationships.)
vss:s__0001 vsd:d__0001      -
vss:s__0002 vsd:d__0002      -
vss:s__0003 vsd:d__0003      Failed to get information for source volume "vss:s__0003" for setup of transfer. (Failed to get volume attributes for e2de028c-8049-11e6-96ea-005056851ca2:s__0003. (Volume is offline))
vss:s__0004 vsd:d__0004      -
vss:s__0005 vsd:d__0005      -
vss:s__0006 vsd:d__0006      -
vss:s__0007 vsd:d__0007      -
vss:s__0008 vsd:d__0008      -
9 entries were displayed.
----
+
문제를 해결한 후에는 SnapMirror 작업을 다시 실행해야 합니다.


