---
permalink: flexgroup/perform-snapmirror-single-file-restore-task.html 
sidebar: sidebar 
keywords: perform, snapmirror, single, file, restore, flexgroup, volume, snap mirror, flex group, vault, udp, destination, transfer 
summary: ONTAP 9.8부터 FlexGroup SnapMirror 볼트 또는 UDP 대상에서 단일 파일을 복원할 수 있습니다. 
---
= FlexGroup 볼륨에서 SnapMirror 단일 파일 복원을 수행합니다
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9.8부터 FlexGroup SnapMirror 볼트 또는 UDP 대상에서 단일 파일을 복원할 수 있습니다.

.이 작업에 대해
* 모든 지오메트리의 FlexGroup 볼륨에서 모든 지오메트리의 FlexGroup 볼륨으로 복원할 수 있습니다
* 복구 작업당 하나의 파일만 지원됩니다
* 원래 소스 FlexGroup 볼륨이나 새 FlexGroup 볼륨으로 복원할 수 있습니다
* 원격 펜싱된 파일 조회는 지원되지 않습니다.
+
소스 파일이 펜싱된 경우 단일 파일 복구가 실패합니다.

* 중단된 단일 파일 복원을 다시 시작하거나 정리할 수 있습니다
* '스냅샷 복구' 명령의 '정리 실패' 옵션을 사용하여 실패한 단일 파일 복원 전송을 정리해야 합니다
* FlexGroup 볼륨 확장은 FlexGroup 단일 파일 복원이 진행 중이거나 중단된 상태일 때 지원됩니다


.단계
. FlexGroup 볼륨에서 파일 복원: ''스냅샷 미러 복원 - 대상 - 경로 destination_path - source-path source_path - file-list/F1-throttle throttle-source-snapshot'
+
다음은 FlexGroup 볼륨 단일 파일 복원 작업의 예입니다.

+
[listing]
----
vserverA::> snapmirror restore -destination-path vs0:fg2 -source-path vs0:fgd -file-list /f1 -throttle 5 -source-snapshot snapmirror.81072ce1-d57b-11e9-94c0-005056a7e422_2159190496.2019-09-19_062631
[Job 135] Job is queued: snapmirror restore from source "vs0:fgd" for the snapshot snapmirror.81072ce1-d57b-11e9-94c0-005056a7e422_2159190496.2019-09-19_062631.
vserverA::> snapmirror show
                                                                                         Source              Destination Mirror   Relationship                   Total Last
Path       Type   Path            State    Status           Progress Healthy Updated
----------- ----      ------------     -------    ---------          ----- --------- ------- --------
vs0:v1d RST    vs0:v2          -           Transferring Idle 83.12KB true 09/19 11:38:42

vserverA::*> snapmirror show vs0:fg2

Source Path: vs0:fgd
Source Cluster: -
Source Vserver: vs0
Source Volume: fgd
Destination Path: vs0:fg2
Destination Cluster: -
Destination Vserver: vs0
Destination Volume: fg2
Relationship Type: RST
Relationship Group Type: none
Managing Vserver: vs0
SnapMirror Schedule: -
SnapMirror Policy Type: -
SnapMirror Policy: -
Tries Limit: -
Throttle (KB/sec): unlimited
Current Transfer Throttle (KB/sec): 2
Mirror State: -
Relationship Status: Transferring
File Restore File Count: 1
File Restore File List: f1
Transfer Snapshot: snapmirror.81072ce1-d57b-11e9-94c0-005056a7e422_2159190496.2019-09-19_062631
Snapshot Progress: 2.87MB
Total Progress: 2.87MB
Network Compression Ratio: 1:1
Snapshot Checkpoint: 2.97KB
Newest Snapshot: -
Newest Snapshot Timestamp: -
Exported Snapshot: -
Exported Snapshot Timestamp: -
Healthy: true
Physical Replica: -
Relationship ID: e6081667-dacb-11e9-94c0-005056a7e422
Source Vserver UUID: 81072ce1-d57b-11e9-94c0-005056a7e422
Destination Vserver UUID: 81072ce1-d57b-11e9-94c0-005056a7e422
Current Operation ID: 138f12e6-dacc-11e9-94c0-005056a7e422
Transfer Type: cg_file_restore
Transfer Error: -
Last Transfer Type: -
Last Transfer Error: -
Last Transfer Error Codes: -
Last Transfer Size: -
Last Transfer Network Compression Ratio: -
Last Transfer Duration: -
Last Transfer From: -
Last Transfer End Timestamp: -
Unhealthy Reason: -
Progress Last Updated: 09/19 07:07:36
Relationship Capability: 8.2 and above
Lag Time: -
Current Transfer Priority: normal
SMTape Operation: -
Constituent Relationship: false
Destination Volume Node Name: vserverA
Identity Preserve Vserver DR: -
Number of Successful Updates: 0
Number of Failed Updates: 0
Number of Successful Resyncs: 0
Number of Failed Resyncs: 0
Number of Successful Breaks: 0
Number of Failed Breaks: 0
Total Transfer Bytes: 0
Total Transfer Time in Seconds: 0
Source Volume MSIDs Preserved: -
OpMask: ffffffffffffffff
Is Auto Expand Enabled: -
Source Endpoint UUID: -
Destination Endpoint UUID: -
Is Catalog Enabled: false
----

