---
permalink: flexgroup/quota-reporting-task.html 
sidebar: sidebar 
keywords: quota, flexgroup, volume, flex group, limit, snap mirror, snapmirror, qtree, user, group 
summary: ONTAP 9.4 이하 버전에서는 할당량 제한을 적용하는 것이 아니라 보고 목적으로만 FlexGroup 볼륨에 할당량 규칙을 적용할 수 있습니다. ONTAP 9.5부터 FlexGroup 볼륨에 적용되는 할당량 규칙에 제한을 적용할 수 있습니다. 
---
= FlexGroup 볼륨에 할당량을 사용합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9.4 이하 버전에서는 할당량 제한을 적용하는 것이 아니라 보고 목적으로만 FlexGroup 볼륨에 할당량 규칙을 적용할 수 있습니다. ONTAP 9.5부터 FlexGroup 볼륨에 적용되는 할당량 규칙에 제한을 적용할 수 있습니다.

.이 작업에 대해
* ONTAP 9.5부터 FlexGroup 볼륨에 대한 하드, 소프트 및 임계값 제한 할당량을 지정할 수 있습니다.
+
이러한 제한을 지정하여 공간, 특정 사용자, 그룹 또는 qtree에서 생성할 수 있는 파일 수 또는 둘 다를 제한할 수 있습니다. 할당량 제한에서는 다음과 같은 경우에 경고 메시지가 생성됩니다.

+
** 사용량이 설정된 소프트 제한값을 초과하면 ONTAP에서 경고 메시지를 발생하지만 추가 트래픽은 여전히 허용됩니다.
+
나중에 사용량이 설정된 소프트 제한값 아래로 다시 떨어지면 메시지가 모두 표시됩니다.

** 사용량이 구성된 임계값 제한을 초과하면 ONTAP에서 두 번째 경고 메시지를 표시합니다.
+
사용량이 나중에 구성된 임계값 제한 아래로 떨어지면 모든 지우기 관리 메시지가 표시되지 않습니다.

** 사용량이 구성된 하드 제한에 도달하면 ONTAP는 트래픽을 거부하여 추가 리소스 소비를 방지합니다.


* ONTAP 9.5에서는 SnapMirror 관계의 대상 FlexGroup 볼륨에서 할당량 규칙을 생성하거나 활성화할 수 없습니다.
* 할당량 초기화 중에는 할당량이 적용되지 않으며 할당량 초기화 후 위반된 할당량에 대한 알림이 없습니다.
+
할당량 초기화 중에 할당량이 위반되었는지 확인하려면 'volume quota report' 명령을 사용합니다.





== 할당량 대상 및 유형

할당량은 사용자, 그룹 또는 트리일 수 있습니다. 할당량 지정 대상은 할당량 제한이 적용되는 사용자, 그룹 또는 qtree를 지정합니다.

다음 표에는 할당량 타겟의 종류, 각 할당량 목표와 연결된 할당량 유형, 각 할당량 대상이 표시되는 방식이 나와 있습니다.

|===


| 할당량 대상 | 할당량 유형입니다 | 대상 표시 방법 | 참고 


 a| 
사용자
 a| 
사용자 할당량
 a| 
UNIX 사용자 이름 UNIX UID입니다

Windows 2000 이전 형식의 Windows 사용자 이름입니다

Windows SID
 a| 
사용자 할당량은 특정 볼륨 또는 qtree에 적용할 수 있습니다.



 a| 
그룹
 a| 
그룹 할당량
 a| 
UNIX 그룹 이름 UNIX GID입니다
 a| 
그룹 할당량은 특정 볼륨 또는 qtree에 적용할 수 있습니다.

[NOTE]
====
ONTAP는 Windows ID를 기준으로 그룹 할당량을 적용하지 않습니다.

====


 a| 
qtree입니다
 a| 
트리 할당량
 a| 
qtree 이름입니다
 a| 
트리 할당량은 특정 볼륨에 적용되며 다른 볼륨의 qtree에 영향을 주지 않습니다.



 a| 
 a| 
사용자 quotagrop 할당량입니다

트리 할당량
 a| 
큰따옴표("")
 a| 
""의 할당량 대상은 _ 기본 할당량 _ 을(를) 나타냅니다. 기본 할당량의 경우 할당량 유형은 유형 필드의 값에 의해 결정됩니다.

|===


== 할당량 제한을 초과할 때 FlexGroup 볼륨의 동작

ONTAP 9.5부터 FlexGroup 볼륨에서 할당량 제한이 지원됩니다. FlexGroup 볼륨과 비교할 때 FlexVol 볼륨에 할당량 제한이 적용되는 방식은 몇 가지 차이가 있습니다.

FlexGroup 볼륨은 할당량 제한을 초과할 때 다음과 같은 동작을 표시할 수 있습니다.

* FlexGroup 볼륨의 공간 및 파일 사용은 추가 트래픽을 거부하여 할당량 제한을 적용하기 전에 구성된 하드 제한보다 최대 5% 높을 수 있습니다.
+
최상의 성능을 제공하기 위해 ONTAP에서는 할당량 적용이 시작되기 전에 공간 소비가 구성된 하드 제한값을 약간 초과할 수 있습니다. 이 추가 공간 소비는 구성된 하드 제한값, 1GB 또는 65536 파일 중 더 낮은 쪽의 5%를 초과하지 않습니다.

* 할당량 제한에 도달한 후 사용자 또는 관리자가 할당량 사용이 현재 제한 아래로 내려갈 수 있도록 일부 파일 또는 디렉토리를 삭제하면 이후의 할당량 사용 파일 작업이 지연되어 다시 시작될 수 있습니다(다시 시작하는 데 최대 5초가 걸릴 수 있음).
* FlexGroup 볼륨의 총 공간 및 파일 사용량이 구성된 할당량 제한을 초과하면 이벤트 로그 메시지 로깅이 약간 지연될 수 있습니다.
* FlexGroup 볼륨의 일부 구성 요소로는 꽉 찼지만 할당량 제한에 도달하지 않으면 ""공간 없음" 오류가 발생할 수 있습니다.
* 할당량 하드 제한값이 구성된 할당량 타겟의 경우 파일 또는 디렉토리 이름을 바꾸거나 qtree 간에 파일을 이동하는 등의 작업은 FlexVol 볼륨의 유사 작업에 비해 시간이 더 오래 걸릴 수 있습니다.


[role="lead"]
이 예제를 사용하여 ONTAP 9.5 이상에서 할당량을 제한하는 방법을 이해할 수 있습니다.

.예 1: 디스크 제한으로 할당량 규칙 적용
. 달성 가능한 소프트 디스크 제한과 하드 디스크 제한을 모두 사용하여 'user' 유형의 할당량 정책 규칙을 만들어야 합니다.
+
[listing]
----
cluster1::> volume quota policy rule create -vserver vs0 -policy-name default -volume FG -type user -target "" -qtree "" -disk-limit 1T -soft-disk-limit 800G
----
. 할당량 정책 규칙을 볼 수 있습니다.
+
[listing]
----
cluster1::> volume quota policy rule show -vserver vs0 -policy-name default -volume FG

Vserver: vs0               Policy: default           Volume: FG

                                               Soft             Soft
                         User         Disk     Disk   Files    Files
Type   Target    Qtree   Mapping     Limit    Limit   Limit    Limit  Threshold
-----  --------  ------- -------  --------  -------  ------  -------  ---------
user   ""        ""      off           1TB    800GB       -        -          -
----
. 새 할당량 규칙을 활성화하려면 볼륨에 대해 할당량을 초기화해야 합니다.
+
[listing]
----
cluster1::> volume quota on -vserver vs0 -volume FG -foreground true
[Job 49] Job succeeded: Successful
----
. 할당량 보고서를 사용하여 FlexGroup 볼륨의 디스크 사용량 및 파일 사용량 정보를 볼 수 있습니다.
+
[listing]
----
cluster1::> volume quota report -vserver vs0 -volume FG
Vserver: vs0

                                    ----Disk----  ----Files-----   Quota
Volume   Tree      Type    ID        Used  Limit    Used   Limit   Specifier
-------  --------  ------  -------  -----  -----  ------  ------   ---------
FG                 user    root      50GB      -       1       -
FG                 user    *         800GB    1TB      0       -   *
2 entries were displayed.
----


하드 디스크 제한에 도달하면 할당량 정책 규칙 대상(이 경우 사용자)이 파일에 더 많은 데이터를 쓸 수 없도록 차단됩니다.

.예 2: 여러 사용자에 대해 할당량 규칙 적용
. 할당량 대상(UNIX 사용자, SMB 사용자 또는 둘 다 조합)에 여러 사용자가 지정되어 있고 규칙에 달성 가능한 소프트 디스크 제한과 하드 디스크 제한이 모두 있는 할당량 정책 규칙 유형을 'user' 유형으로 생성해야 합니다.
+
[listing]
----
cluster1::> quota policy rule create -vserver vs0 -policy-name default -volume FG -type user -target "rdavis,ABCCORP\RobertDavis" -qtree "" -disk-limit 1TB -soft-disk-limit  800GB
----
. 할당량 정책 규칙을 볼 수 있습니다.
+
[listing]
----
cluster1::> quota policy rule show -vserver vs0 -policy-name default -volume FG

Vserver: vs0               Policy: default           Volume: FG

                                               Soft             Soft
                         User         Disk     Disk   Files    Files
Type   Target    Qtree   Mapping     Limit    Limit   Limit    Limit  Threshold
-----  --------  ------- -------  --------  -------  ------  -------  ---------
user   "rdavis,ABCCORP\RobertDavis"  "" off  1TB  800GB  -  -
----
. 새 할당량 규칙을 활성화하려면 볼륨에 대해 할당량을 초기화해야 합니다.
+
[listing]
----
cluster1::> volume quota on -vserver vs0 -volume FG -foreground true
[Job 49] Job succeeded: Successful
----
. 할당량 상태가 활성 상태인지 확인할 수 있습니다.
+
[listing]
----
cluster1::> volume quota show -vserver vs0 -volume FG
              Vserver Name: vs0
               Volume Name: FG
               Quota State: on
               Scan Status: -
          Logging Messages: on
          Logging Interval: 1h
          Sub Quota Status: none
  Last Quota Error Message: -
Collection of Quota Errors: -
----
. 할당량 보고서를 사용하여 FlexGroup 볼륨의 디스크 사용량 및 파일 사용량 정보를 볼 수 있습니다.
+
[listing]
----
cluster1::> quota report -vserver vs0 -volume FG
Vserver: vs0

                                    ----Disk----  ----Files-----   Quota
Volume   Tree      Type    ID        Used  Limit    Used   Limit   Specifier
-------  --------  ------  -------  -----  -----  ------  ------   ---------
FG                 user    rdavis,ABCCORP\RobertDavis  0B  1TB  0  -   rdavis,ABCCORP\RobertDavis
----
+
할당량 제한값은 할당량 대상에 나열된 모든 사용자 간에 공유됩니다.



하드 디스크 제한에 도달하면 할당량 대상에 나열된 사용자가 파일에 더 많은 데이터를 쓸 수 없도록 차단됩니다.

.예 3: 사용자 매핑을 사용하여 할당량 적용
. 'user' 유형의 할당량 정책 규칙을 생성하고, 'user-mapping'을 'on'으로 설정한 할당량 타겟으로 UNIX 사용자나 Windows 사용자를 지정하고, 달성 가능한 소프트 디스크 제한과 하드 디스크 제한을 모두 사용하여 규칙을 생성해야 합니다.
+
UNIX 사용자와 Windows 사용자 간의 매핑은 "vserver name-mapping create" 명령을 사용하여 미리 구성해야 합니다.

+
[listing]
----
cluster1::> quota policy rule create -vserver vs0 -policy-name default -volume FG -type user -target rdavis -qtree "" -disk-limit 1TB -soft-disk-limit  800GB -user-mapping on
----
. 할당량 정책 규칙을 볼 수 있습니다.
+
[listing]
----
cluster1::> quota policy rule show -vserver vs0 -policy-name default -volume FG

Vserver: vs0               Policy: default           Volume: FG

                                               Soft             Soft
                         User         Disk     Disk   Files    Files
Type   Target    Qtree   Mapping     Limit    Limit   Limit    Limit  Threshold
-----  --------  ------- -------  --------  -------  ------  -------  ---------
user   rdavis    ""      on           1TB    800GB       -        -          -
----
. 새 할당량 규칙을 활성화하려면 볼륨에 대해 할당량을 초기화해야 합니다.
+
[listing]
----
cluster1::> volume quota on -vserver vs0 -volume FG -foreground true
[Job 49] Job succeeded: Successful
----
. 할당량 상태가 활성 상태인지 확인할 수 있습니다.
+
[listing]
----
cluster1::> volume quota show -vserver vs0 -volume FG
              Vserver Name: vs0
               Volume Name: FG
               Quota State: on
               Scan Status: -
          Logging Messages: on
          Logging Interval: 1h
          Sub Quota Status: none
  Last Quota Error Message: -
Collection of Quota Errors: -
----
. 할당량 보고서를 사용하여 FlexGroup 볼륨의 디스크 사용량 및 파일 사용량 정보를 볼 수 있습니다.
+
[listing]
----
cluster1::> quota report -vserver vs0 -volume FG
Vserver: vs0

                                    ----Disk----  ----Files-----   Quota
Volume   Tree      Type    ID        Used  Limit    Used   Limit   Specifier
-------  --------  ------  -------  -----  -----  ------  ------   ---------
FG                 user    rdavis,ABCCORP\RobertDavis  0B  1TB  0  -   rdavis
----
+
할당량 제한은 할당량 대상에 나열된 사용자와 해당 Windows 또는 UNIX 사용자 간에 공유됩니다.



하드 디스크 제한에 도달하면 할당량 대상에 나열된 사용자와 해당 Windows 또는 UNIX 사용자가 파일에 더 많은 데이터를 쓸 수 없도록 차단됩니다.

.예 4: 할당량이 설정된 경우 qtree 크기 확인
. "트리" 유형의 할당량 정책 규칙을 생성하고 규칙에 달성 가능한 소프트 디스크 제한과 하드 디스크 제한이 모두 있는 규칙을 만들어야 합니다.
+
[listing]
----
cluster1::> quota policy rule create -vserver vs0 -policy-name default -volume FG -type tree -target tree_4118314302 -qtree "" -disk-limit 48GB -soft-disk-limit 30GB
----
. 할당량 정책 규칙을 볼 수 있습니다.
+
[listing]
----
cluster1::> quota policy rule show -vserver vs0

Vserver: vs0               Policy: default           Volume: FG

                                               Soft             Soft
                         User         Disk     Disk   Files    Files
Type   Target    Qtree   Mapping     Limit    Limit   Limit    Limit  Threshold
-----  --------  ------- -------  --------  -------  ------  -------  ---------
tree   tree_4118314302  "" -          48GB        -      20        -
----
. 새 할당량 규칙을 활성화하려면 볼륨에 대해 할당량을 초기화해야 합니다.
+
[listing]
----
cluster1::> volume quota on -vserver vs0 -volume FG -foreground true
[Job 49] Job succeeded: Successful
----
+
.. 할당량 보고서를 사용하여 FlexGroup 볼륨의 디스크 사용량 및 파일 사용량 정보를 볼 수 있습니다.
+
[listing]
----
cluster1::> quota report -vserver vs0
Vserver: vs0
----Disk---- ----Files----- Quota
Volume Tree Type ID Used Limit Used Limit Specifier
------- -------- ------ ------- ----- ----- ------ ------ ---------
FG tree_4118314302 tree 1 30.35GB 48GB 14 20 tree_4118314302
----
+
할당량 제한은 할당량 대상에 나열된 사용자와 해당 Windows 또는 UNIX 사용자 간에 공유됩니다.



. NFS 클라이언트에서 df 명령을 사용하여 총 공간 사용량, 사용 가능한 공간 및 사용된 공간을 확인합니다.
+
[listing]
----
scsps0472342001# df -m /t/10.53.2.189/FG-3/tree_4118314302
Filesystem 1M-blocks Used Available Use% Mounted on
10.53.2.189/FG-3 49152 31078 18074 63% /t/10.53.2.189/FG-3
----
+
하드 제한에서는 NFS 클라이언트에서 다음과 같이 공간 사용량이 계산됩니다.

+
** 총 공간 사용량 = 트리의 하드 제한입니다
** 여유 공간 = 하드 제한에서 qtree 공간 사용을 뺀 값 하드 제한값은 다음과 같이 NFS 클라이언트에서 공간 사용을 계산합니다.
** 공간 사용 = 할당량 사용
** 총 공간 = 할당량 사용 및 볼륨의 물리적 사용 가능한 공간의 합계입니다


. SMB 공유에서 Windows 탐색기를 사용하여 전체 공간 사용량, 사용 가능한 공간 및 사용된 공간을 확인합니다.
+
SMB 공유에서는 공간 사용량을 계산할 때 다음 사항을 고려해야 합니다.

+
** 사용자 및 그룹에 대한 사용자 할당량 하드 제한값을 고려하여 총 사용 가능한 공간을 계산합니다.
** 트리 할당량 규칙, 사용자 할당량 규칙 및 그룹 할당량 규칙의 사용 가능한 공간 중 최소값은 SMB 공유의 사용 가능한 공간으로 간주됩니다.
** 전체 공간 사용은 SMB의 경우 가변적이며 트리, 사용자 및 그룹 간의 최소 사용 가능 공간에 해당하는 하드 제한값에 따라 달라집니다.






== FlexGroups 볼륨에 규칙 및 제한을 적용합니다

.단계
. 대상에 대한 할당량 규칙 생성: ' 볼륨 할당량 정책 규칙 create -vserver vs0 -policy -name quota_policy_of_the_rule -volume flexgroup_vol -type {tree | user | group} -target target_for_rule -qtree_name [-disk -limit hard_disk_limit_number] 소프트 제한값 [-file_limit_soft_file
+
** ONTAP 9.2 및 ONTAP 9.1에서 할당량 대상 유형은 FlexGroup 볼륨에 대한 "사용자" 또는 "그룹"일 수 있습니다.
+
FlexGroup 9.2 및 ONTAP 9.1의 ONTAP 볼륨에는 트리 할당량 유형이 지원되지 않습니다.

** ONTAP 9.3 이상에서는 FlexGroup 볼륨에 대한 할당량 대상 유형이 사용자 그룹 트리 일 수 있습니다.
** FlexGroup 볼륨에 대한 할당량 규칙을 생성할 때 경로는 타겟으로 지원되지 않습니다.
** ONTAP 9.5부터 FlexGroup 볼륨에 대한 하드 디스크 제한, 하드 파일 제한, 소프트 디스크 제한, 소프트 파일 제한 및 임계값 제한 할당량을 지정할 수 있습니다.
+
ONTAP 9.4 이하 버전에서는 FlexGroup 볼륨에 대한 할당량 규칙을 생성할 때 디스크 제한, 파일 제한, 디스크 한계 임계값, 소프트 디스크 한계 또는 소프트 파일 제한을 지정할 수 없습니다.





다음 예에서는 사용자 타겟 유형에 대해 생성되는 기본 할당량 규칙을 보여 줍니다.

[listing]
----
cluster1::> volume quota policy rule create -vserver vs0 -policy-name quota_policy_vs0_1 -volume fg1 -type user -target "" -qtree ""
----
다음 예에서는 qtree1 이라는 qtree에 대해 생성되는 트리 할당량 규칙을 보여 줍니다.

[listing]
----
cluster1::> volume quota policy rule create -policy-name default -vserver vs0 -volume fg1 -type tree -target "qtree1"
----
. 지정된 FlexGroup 볼륨에 대한 할당량을 활성화합니다. 'volume quota on-vserver svm_name -volume flexgroup_vol-foreground true'


[listing]
----
cluster1::> volume quota on -vserver vs0 -volume fg1 -foreground true
----
. 할당량 초기화 상태 'volume quota show -vserver svm_name'을 모니터링합니다


FlexGroup 볼륨은 모든 구성 볼륨이 아직 동일한 상태가 아님을 나타내는 '혼합' 상태를 표시할 수 있습니다.

[listing]
----
cluster1::> volume quota show -vserver vs0
                                          Scan
Vserver    Volume        State            Status
---------  ------------  ---------------  ------
vs0        fg1           initializing         95%
vs0        vol1          off                   -
2 entries were displayed.
----
. 활성 할당량이 있는 FlexGroup 볼륨에 대한 할당량 보고서('volume quota report-vserver svm_name-volume flexgroup_vol')를 봅니다
+
FlexGroup 볼륨에 대한 'volume quota report' 명령을 사용하여 경로를 지정할 수 없습니다.

+
다음 예에서는 FlexGroup 볼륨 fg1에 대한 사용자 할당량을 보여 줍니다.

+
[listing]
----
cluster1::> volume quota report -vserver vs0 -volume fg1
  Vserver: vs0
                                      ----Disk----  ----Files-----   Quota
  Volume   Tree      Type    ID        Used  Limit    Used   Limit   Specifier
  -------  --------  ------  -------  -----  -----  ------  ------   ---------
  fg1                user    *           0B      -       0       -   *
  fg1                user    root       1GB      -       1       -   *
  2 entries were displayed.
----
+
다음 예에서는 FlexGroup 볼륨 fg1에 대한 트리 할당량을 보여 줍니다.

+
[listing]
----
cluster1::> volume quota report -vserver vs0 -volume fg1
Vserver: vs0

                                    ----Disk----  ----Files-----   Quota
Volume   Tree      Type    ID        Used  Limit    Used   Limit   Specifier
-------  --------  ------  -------  -----  -----  ------  ------   ---------
fg1      qtree1  tree      1         68KB      -      18       -   qtree1
fg1              tree      *           0B      -       0       -   *
2 entries were displayed.
----


할당량 규칙 및 제한은 FlexGroups 볼륨에 적용됩니다.

ONTAP에서 추가 트래픽을 거부하여 할당량을 적용하기 전에 사용량이 구성된 하드 제한보다 최대 5% 높을 수 있습니다.

http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-cmpr/GUID-5CB10C70-AC11-41C0-8C16-B4D0DF916E9B.html["ONTAP 9 명령"]
