---
permalink: flexgroup/snapvault-backup-concept.html 
sidebar: sidebar 
keywords: consider, create, snapvault, backup, relation, unified, data, protection, flexgroup, volume 
summary: SnapVault 볼륨에 대한 FlexGroup 백업 관계 및 통합 데이터 보호 관계를 생성할 때 고려해야 할 사항에 대해 알고 있어야 합니다. 
---
= SnapVault 백업 관계를 생성할 때의 고려 사항 및 FlexGroup 볼륨에 대한 통합 데이터 보호 관계
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapVault 볼륨에 대한 FlexGroup 백업 관계 및 통합 데이터 보호 관계를 생성할 때 고려해야 할 사항에 대해 알고 있어야 합니다.

* 최신 공통 스냅샷 복사본보다 최신 버전인 타겟 볼륨에 Snapshot 복사본을 유지할 수 있도록 하는 '-preserve' 옵션을 사용하여 SnapVault 백업 관계 및 통합 데이터 보호 관계를 재동기화할 수 있습니다.
* FlexGroup 볼륨에서는 장기 보존이 지원되지 않습니다.
+
장기 보존을 통해 소스 볼륨에 스냅샷 복사본을 저장할 필요 없이 타겟 볼륨에 Snapshot 복사본을 직접 생성할 수 있습니다.

* SnapVault 백업 관계 및 통합 데이터 보호 관계의 대상 FlexGroup 볼륨에서는 스토리지 효율성을 구성할 수 없습니다.
* SnapVault 백업 관계의 스냅샷 복사본과 FlexGroup 볼륨에 대한 통합 데이터 보호 관계의 이름은 변경할 수 없습니다.
* FlexGroup 볼륨은 하나의 백업 관계나 복구 관계의 소스 볼륨일 수 있습니다.
+
FlexGroup 볼륨은 두 SnapVault 관계, 두 개의 복구 관계 또는 SnapVault 백업 관계 및 복구 관계의 소스가 될 수 없습니다.

* 소스 FlexGroup 볼륨에서 스냅샷 복사본을 삭제하고 같은 이름의 스냅샷 복사본을 다시 생성하는 경우, 타겟 볼륨에 동일한 이름의 스냅샷 복사본이 있으면 다음 업데이트가 대상 FlexGroup 볼륨으로 전송되지 않습니다.
+
이는 FlexGroup 볼륨에 대한 스냅샷 복사본의 이름을 변경할 수 없기 때문입니다.


