---
permalink: flexcache-writeback/flexcache-write-back-overview.html 
sidebar: sidebar 
keywords: tr-4743, flexcache writeback, flexcache write-back, overview, technical report, netapp tr, ontap tr 
summary: ONTAP 9.15.1에 도입된 FlexCache Write-Back은 캐시에서 쓰는 대체 작업 모드입니다. 
---
= FlexCache 후기입 개요
:allow-uri-read: 


[role="lead"]
ONTAP 9.15.1에 도입된 FlexCache Write-Back은 캐시에서 쓰는 대체 작업 모드입니다. 쓰기 저장을 사용하면 데이터가 오리진으로 전달될 때까지 기다리지 않고 캐시의 안정적인 스토리지에 쓰기를 커밋하고 클라이언트에서 이를 확인할 수 있습니다. 데이터는 비동기적으로 오리진으로 다시 플러시됩니다. 그 결과, 특정 워크로드 및 환경에서 거의 로컬에 가까운 속도로 쓰기를 수행할 수 있는 전 세계적으로 분산된 파일 시스템이 탄생하여 탁월한 성능 이점을 제공합니다.


NOTE: ONTAP 9.12.1에서는 공개 미리 보기로 쓰기 저장 기능을 도입했습니다. 이 기능을 다시 쓰기 버전 1(wbv1)이라고 하며, ONTAP 9.15.1에서 다시 쓰기 버전 2(wbv2)라고 하는 Write-back과 동일하다고 간주해서는 안 됩니다.



== 쓰기 저장 대 쓰기 주위

FlexCache는 ONTAP 9.5에 도입된 이후 읽기 쓰기 가능한 캐시였지만 write-around 모드로 작동했습니다. 캐시의 쓰기가 안정적인 스토리지로 커밋되도록 오리진으로 전송되었습니다. 오리진에서 쓰기 작업을 안정적인 스토리지에 커밋한 후 캐시에 대한 쓰기를 확인했습니다. 그러면 캐시는 클라이언트에 대한 쓰기를 승인합니다. 이로 인해 모든 쓰기는 캐시와 오리진 사이에서 네트워크를 통과해야 하는 페널티가 발생합니다. FlexCache WRITE-Back(후기입)


NOTE: ONTAP 9.15.1로 업그레이드한 후 기존의 write-around 캐시를 write-back 캐시로 변환하고 필요한 경우 다시 write-around로 변환할 수 있습니다. 그러나 이로 인해 문제가 발생할 경우 진단 로그를 읽기가 더 어려워질 수 있습니다.

|===
|  | 쓰기 | 다시 쓰기 


| ONTAP 버전 | 9.6 이상 | 9.15.1 이상 


| 사용 사례 | 읽기 집약적 워크로드 | 쓰기 집약적 워크로드 


| 데이터가 에 커밋되었습니다 | 원점 | 캐시 


| 고객 경험 | WAN과 유사합니다 | LAN-lke 를 선택합니다 


| 제한 | 오리진당 100개 | 오리진당 10개 


| https://en.wikipedia.org/wiki/CAP_theorem["CAP 정리"^] | 파티션에 사용할 수 있으며 허용 가능합니다 | 사용 가능하고 일관적입니다 
|===


== FlexCache Write-Back 용어

FlexCache Write-Back과 관련된 주요 개념 및 용어 이해

[cols="12%,88%"]
|===
| 기간 | 정의 


| [[dirty-data]] * 더티 데이터 * | 캐시의 안정적인 스토리지에 커밋되었지만 오리진으로 플러시되지 않은 데이터 


| * 독점 잠금 위임(XLD) * | 캐시에 파일 단위로 부여된 프로토콜 수준 잠금 권한입니다. 이 권한을 통해 캐시는 오리진에 접속하지 않고 클라이언트에 전용 쓰기 잠금을 제공할 수 있습니다. 


| * 공유 잠금 위임(SLD) * | 캐시에 파일 단위로 부여된 프로토콜 수준 잠금 권한입니다. 이 권한을 통해 캐시는 오리진에 접속하지 않고 공유 읽기 잠금을 클라이언트에 배포할 수 있습니다. 


| * 쓰기 저장 * | 캐시에 대한 쓰기가 해당 캐시의 안정적인 스토리지에 커밋되어 클라이언트에 즉시 인식되는 FlexCache 작업 모드입니다. 데이터는 원본에 비동기적으로 다시 기록됩니다. 


| * 기입 * | 캐시에 대한 쓰기가 오리진으로 전달되어 안정적인 스토리지에 커밋되는 FlexCache 작업 모드입니다. 커밋되면 오리진에서 캐시에 대한 쓰기를 승인하고 캐시가 클라이언트에 대한 쓰기를 확인합니다. 


| * DDR(Dirty Data Record System) * | 파일별로 다시 쓰기 가능 캐시에서 더티 데이터를 추적하는 독점 메커니즘입니다. 


| * 원점 * | 모든 FlexCache 캐시 볼륨의 소스 데이터를 포함하는 FlexGroup 또는 FlexVol 단일 데이터 소스로서 잠금을 오케스트레이션하고 100% 데이터 일관성, 통화 및 일관성을 보장합니다. 


| * 캐시 * | FlexCache 오리진의 스파스 캐시 볼륨인 FlexGroup입니다. 
|===


=== 정합성 보장, 전류 및 일관성

FlexCache는 언제 어디서나 원하는 데이터를 사용할 수 있는 NetApp의 솔루션입니다. FlexCache는 100% 일관된, 전류 및 일관적인 시간입니다.

* * 정합성: * 데이터는 액세스 위치에 관계없이 동일합니다.
* * 현재: * 데이터는 항상 최신 상태입니다.
* * Coherent : * 데이터가 올바르거나 손상되지 않았습니다.

