---
permalink: smbc/resume-protection-fan-out-configuration.html 
sidebar: sidebar 
keywords: fan out, asynchronous, restore, third site 
summary: SM-BC는 팬아웃 구성을 지원합니다. SM-BC 엔드포인트에서 페일오버 후 비동기 팬아웃 엔드포인트와의 연결을 다시 시작해야 합니다. 
---
= SM-BC를 사용하여 팬아웃 구성에서 보호를 재개합니다
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SM-BC 지원 xref:../data-protection/supported-deployment-config-concept.html[팬아웃 구성]. MirorAllSnapshots 정책을 사용하면 소스 볼륨을 SM-BC 대상 끝점과 하나 이상의 비동기식 SnapMirror 관계에 미러링할 수 있습니다.

SM-BC 대상에서 페일오버가 발생하면 비동기식 SnapMirror 타겟이 정상 상태가 되고 비동기식 SnapMirror 엔드포인트와의 관계를 삭제 및 다시 생성하여 보호를 수동으로 복구해야 합니다.

.팬아웃 구성에서 보호를 재개합니다
. 페일오버 작업이 성공적으로 완료되었는지 확인합니다. '스냅샷 페일오버 표시'입니다
. 비동기식 SnapMirror 엔드포인트에서 팬아웃 엔드포인트 'sapmirror delete-destination-path_destination_path_'를 삭제합니다
. 세 번째 사이트에서 새 SM-BC 운영 볼륨과 비동기 팬아웃 대상 볼륨('napmirror create-source-path_source_path_-destination-path_destination_path_-policy MirrorAllSnapshots-schedule_schedule_')에 대한 비동기 SnapMirror 관계를 생성합니다
. 'snapMirror resync-destination-path_destination_path_' 관계를 재동기화합니다
. 관계 상태 및 상태 확인: '스냅샷 표시

