---
sidebar: sidebar 
permalink: smbc/smbc_admin_removing_an_smbc_configuration.html 
keywords: SM-BC, SMBC, removing, protection relationship 
summary: 제로 RTO 동기식 SnapMirror 보호를 제거하고 SM-BC 관계 구성을 삭제할 수 있습니다. 
---
= SM-BC 구성을 제거합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
제로 RTO 동기식 SnapMirror 보호를 제거하고 SM-BC 관계 구성을 삭제할 수 있습니다.

SM-BC 관계를 삭제하기 전에 대상 클러스터의 모든 LUN이 매핑 해제되어야 합니다. LUN이 매핑 해제되었고 호스트가 다시 스캔되면 SCSI 타겟은 LUN 인벤토리가 변경되었음을 호스트에 알립니다. 제로 RTO 2차 볼륨의 기존 LUN은 제로 RTO 관계가 삭제된 후 새 ID를 반영하도록 변경됩니다. 호스트는 소스 볼륨 LUN과 관계가 없는 새 LUN으로 보조 볼륨 LUN을 검색합니다. 관계가 삭제된 후 보조 볼륨은 DP 볼륨으로 유지됩니다. SnapMirror break 명령을 실행하여 읽기/쓰기로 변환할 수 있습니다. 관계가 반대로 설정되지 않은 경우 페일오버된 상태에서는 관계를 삭제할 수 없습니다.

.단계
. 소스 끝점과 대상 끝점 간의 SM-BC 정합성 보장 그룹 관계를 삭제합니다.
+
대상 경로 VS1_DST:/CG/CG_DST'의 경우, "대상 경로:::> SnapMirror delete-destination-path VS1_DST:/CG/CG_DST"

. 소스 클러스터에서 일관성 그룹 관계와 관계에 대해 생성된 스냅샷 복사본을 릴리즈합니다.
+
'소스::> SnapMirror release-destination-path vs1_dst:/cg/cg_dst'

. 호스트 재검색을 수행하여 LUN 인벤토리를 업데이트합니다.
. ONTAP 9.10.1부터 SnapMirror 관계를 삭제해도 일관성 그룹은 삭제되지 않습니다. 일관성 그룹을 삭제하려면 시스템 관리자 또는 ONTAP REST API를 사용해야 합니다. 을 참조하십시오 xref:../consistency-groups/delete-task.adoc[일관성 그룹을 삭제합니다] 를 참조하십시오.

