---
sidebar: sidebar 
permalink: smbc/smbc_plan_additional_restrictions_and_limitations.html 
keywords: SM-BC, SMBC, restrictions, consistency group, endpoint limits, solaris 
summary: SnapMirror 비즈니스 연속성 솔루션을 사용할 때는 몇 가지 추가 제한 사항과 제한이 있습니다. 
---
= 추가 제한 및 제한 사항
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
SnapMirror 비즈니스 연속성 솔루션을 사용할 때는 몇 가지 추가 제한 사항과 제한이 있습니다.



=== 정합성 보장 그룹

ONTAP 9.8 ~ 9.9.1에서 클러스터 내 SM-BC 정합성 보장 그룹 관계의 최대 개수는 5개이며, 이는 플랫폼과 무관한 제한입니다. ONTAP 9.10.1부터 클러스터 내 SM-BC 정합성 보장 그룹 관계의 최대 수는 20개입니다.



=== 정합성 보장 그룹당 볼륨

ONTAP 9.8 ~ 9.9.1에서 SM-BC 정합성 보장 그룹 관계당 지원되는 최대 볼륨 수는 12개이며, 이는 플랫폼과 무관한 제한입니다. ONTAP 9.10.1부터 SM-BC 관계당 지원되는 최대 볼륨 수는 16개입니다.



=== 볼륨

SM-BC의 제한은 관계 수가 아닌 끝점 수를 기준으로 계산됩니다. 12개의 볼륨이 있는 정합성 보장 그룹은 소스와 대상 모두에 12개의 엔드포인트를 제공합니다. SM-BC 및 SnapMirror Synchronous 관계는 총 엔드포인트 수에 기여합니다.

플랫폼당 최대 엔드포인트는 다음 표에 나와 있습니다.

|===


| S. 아니요 | 플랫폼 2+| SM-BC의 HA당 엔드포인트 2+| HA당 전체 동기식 및 SM-BC 엔드포인트 


|  |  | ONTAP 9.8-9.9.1 | ONTAP 9.10.1 | ONTAP 9.8-9.9.1 | ONTAP 9.10.1 


| 1 | AFF | 60 | 200 | 80 | 200 


| 2 | ASA | 60 | 200 | 80 | 200 
|===


=== SAN 오브젝트 제한

다음 표에는 플랫폼에 관계없이 적용되는 다음과 같은 SAN 오브젝트 제한사항이 나와 있습니다.

|===
| SM-BC 관계에서 개체의 제한 | 카운트 


| 볼륨당 LUN | 256 


| LUN은 노드당 매핑된다 | 2048 


| LUN은 클러스터당 매핑되며 | 4096 


| SVM당 LIF(SM-BC 관계에 하나 이상의 볼륨 포함) | 256 


| 노드당 클러스터 간 LIF | 4 


| 클러스터당 클러스터 간 LIF | 8 
|===


=== NTFS 보안 스타일

NTFS 보안 스타일은 SM-BC 볼륨에서 지원되지 않습니다.



=== SM-BC 구성에 대한 Solaris 호스트 설정 권장 사항

ONTAP 9.10.1부터 SM-BC는 Solaris 11.4를 지원합니다. SM-BC 환경에서 계획되지 않은 사이트 장애 조치 전환이 발생할 때 Solaris 클라이언트 응용 프로그램이 중단되지 않도록 하려면 Solaris 11.4 호스트에 다음 설정을 구성해야 합니다. 이 설정은 모순을 감지하는 코드 경로가 실행되지 않도록 페일오버 모듈 f_tpgs를 재정의합니다.

다음 지침에 따라 override 매개변수를 구성합니다.

. 호스트에 연결된 NetApp 스토리지 유형에 대해 다음과 유사한 항목을 사용하여 구성 파일 '/etc/driver/drv/scsi_vhci.conf'를 생성합니다.
+
[listing]
----
scsi-vhci-failover-override =
"NETAPP  LUN","f_tpgs"
----
. 재정의가 성공적으로 적용되었는지 확인하려면 devprop 및 mdb 명령을 사용합니다.
+
[listing]
----
root@host-A:~# devprop -v -n /scsi_vhci scsi-vhci-failover-override scsi-vhci-failover-override=NETAPP  LUN + f_tpgs
root@host-A:~# echo "*scsi_vhci_dip::print -x struct dev_info devi_child | ::list struct dev_info devi_sibling| ::print struct dev_info devi_mdi_client| ::print mdi_client_t ct_vprivate| ::print struct scsi_vhci_lun svl_lun_wwn svl_fops_name"| mdb -k`
----
+
[listing]
----
svl_lun_wwn = 0xa002a1c8960 "600a098038313477543f524539787938"
svl_fops_name = 0xa00298d69e0 "conf f_tpgs"
----



NOTE: scsi-vhci-failover-override가 적용되면 conf는 sVL_FOPS_NAME에 추가된다. 기본 설정에 대한 추가 정보 및 권장 변경 사항은 NetApp KB 문서 를 참조하십시오 https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapMirror/Solaris_Host_support_recommended_settings_in_SnapMirror_Business_Continuity_(SM-BC)_configuration["Solaris 호스트 지원 SM-BC(SnapMirror Business Continuity) 구성에서 권장되는 설정입니다"].
