---
sidebar: sidebar 
permalink: smbc/smbc_plan_additional_restrictions_and_limitations.html 
keywords: SM-BC, SMBC, restrictions, consistency group, endpoint limits, solaris, aix 
summary: SnapMirror 비즈니스 연속성 솔루션을 사용할 때는 몇 가지 추가 제한 사항과 제한이 있습니다. 
---
= 추가 제한 및 제한 사항
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
SnapMirror 비즈니스 연속성 솔루션을 사용할 때는 몇 가지 추가 제한 사항과 제한이 있습니다.



== 클러스터의 일관성 그룹

SM-BC가 포함된 클러스터의 정합성 보장 그룹 제한은 관계를 기준으로 계산되며 사용되는 ONTAP 버전에 따라 달라집니다. 제한은 플랫폼에 독립적입니다.

|===
| ONTAP 버전입니다 | 최대 관계 수 


| ONTAP 9.8-9.9.1 | 5 


| ONTAP 9.10.1 | 20 


| ONTAP 9.11.1 | 50 
|===


== 정합성 보장 그룹당 볼륨

ONTAP 9.8 ~ 9.9.1에서 SM-BC 정합성 보장 그룹 관계당 지원되는 최대 볼륨 수는 12개이며, 이는 플랫폼과 무관한 제한입니다. ONTAP 9.10.1부터 SM-BC 관계당 지원되는 최대 볼륨 수는 16개입니다.



== 볼륨

SM-BC의 제한은 관계 수가 아닌 끝점 수를 기준으로 계산됩니다. 12개의 볼륨이 있는 정합성 보장 그룹은 소스와 대상 모두에 12개의 엔드포인트를 제공합니다. SM-BC 및 SnapMirror Synchronous 관계는 총 엔드포인트 수에 기여합니다.

플랫폼당 최대 엔드포인트는 다음 표에 나와 있습니다.

|===
| S. 아니요 | 플랫폼 3+| SM-BC의 HA당 엔드포인트 3+| HA당 전체 동기식 및 SM-BC 엔드포인트 


|  |  | ONTAP 9.8-9.9.1 | ONTAP 9.10.1 | ONTAP 9.11.1 | ONTAP 9.8-9.9.1 | ONTAP 9.10.1 | ONTAP 9.11.1 


| 1 | AFF | 60 | 200 | 400 | 80 | 200 | 400 


| 2 | ASA | 60 | 200 | 400 | 80 | 200 | 400 
|===


== SAN 오브젝트 제한

다음 표에는 플랫폼에 관계없이 적용되는 다음과 같은 SAN 오브젝트 제한사항이 나와 있습니다.

|===
| SM-BC 관계에서 개체의 제한 | 카운트 


| 볼륨당 LUN | 256 


| LUN은 노드당 매핑된다 | 2048 


| LUN은 클러스터당 매핑되며 | 4096 


| SVM당 LIF(SM-BC 관계에 하나 이상의 볼륨 포함) | 256 


| 노드당 클러스터 간 LIF | 4 


| 클러스터당 클러스터 간 LIF | 8 
|===


== NTFS 보안 스타일

NTFS 보안 스타일은 SM-BC 볼륨에서 지원되지 않습니다.



== 팬아웃 구성

SM-BC 지원 xref:../data-protection/supported-deployment-config-concept.html[팬아웃 구성] ONTAP 9.11.1부터 무르안볼트(MirorAllSnapshots) 정책과 함께. 팬아웃 구성은 XDPDefault 정책으로 지원되지 않습니다.

팬아웃 구성의 SM-BC 대상에서 페일오버가 발생하면 수동으로 페일오버해야 합니다 xref:resume-protection-fan-out-configuration.html[팬아웃 구성에서 보호를 재개합니다].



== AIX

ONTAP 9.11.1부터 AIX는 SM-BC에서 지원됩니다. AIX 구성에서 운영 클러스터는 "활성" 클러스터입니다.

AIX 구성에서 페일오버는 중단을 야기합니다. 각 페일오버 시 호스트에서 재검색을 수행하여 I/O 작업을 재개해야 합니다.

SM-BC를 사용하는 AIX 호스트에 대해 구성하려면 기술 자료 문서를 참조하십시오 link:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapMirror/How_to_configure_an_AIX_host_for_SnapMirror_Business_Continuity_(SM-BC)["SnapMirror 비즈니스 연속성(SM-BC)에 대한 AIX 호스트를 구성하는 방법"].



== SM-BC 구성에 대한 Solaris 호스트 설정 권장 사항

ONTAP 9.10.1부터 SM-BC는 Solaris 11.4를 지원합니다. SM-BC 환경에서 계획되지 않은 사이트 페일오버 전환이 발생할 때 Solaris 클라이언트 애플리케이션이 중단되지 않도록 Solaris 11.4 호스트에 다음 설정을 구성해야 합니다. 이 설정은 모순을 감지하는 코드 경로가 실행되지 않도록 페일오버 모듈('f_tpgs')을 재정의합니다.

다음 단계에 따라 override 매개 변수를 구성합니다.

. 호스트에 연결된 NetApp 스토리지 유형에 대해 다음과 유사한 항목을 사용하여 구성 파일 '/etc/driver/drv/scsi_vhci.conf'를 생성합니다.
+
[listing]
----
scsi-vhci-failover-override =
"NETAPP  LUN","f_tpgs"
----
. 재정의가 성공적으로 적용되었는지 확인하려면 devprop 및 mdb 명령을 사용합니다.
+
[listing]
----
root@host-A:~# devprop -v -n /scsi_vhci scsi-vhci-failover-override scsi-vhci-failover-override=NETAPP  LUN + f_tpgs
root@host-A:~# echo "*scsi_vhci_dip::print -x struct dev_info devi_child | ::list struct dev_info devi_sibling| ::print struct dev_info devi_mdi_client| ::print mdi_client_t ct_vprivate| ::print struct scsi_vhci_lun svl_lun_wwn svl_fops_name"| mdb -k`
----
+
[listing]
----
svl_lun_wwn = 0xa002a1c8960 "600a098038313477543f524539787938"
svl_fops_name = 0xa00298d69e0 "conf f_tpgs"
----



NOTE: scsi-vhci-failover-override가 적용되면 conf는 sVL_FOPS_NAME에 추가된다. 기본 설정에 대한 추가 정보 및 권장 변경 사항은 NetApp KB 문서 를 참조하십시오 https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapMirror/Solaris_Host_support_recommended_settings_in_SnapMirror_Business_Continuity_(SM-BC)_configuration["Solaris 호스트 지원 SM-BC(SnapMirror Business Continuity) 구성에서 권장되는 설정입니다"].



== HP-UX SM-BC 구성에 대해 알려진 문제 및 제한 사항

ONTAP 9.10.1부터 HP-UX용 SM-BC가 지원됩니다. SM-BC 구성의 격리된 마스터 클러스터에서 자동 비계획 페일오버(AUFO) 이벤트가 발생하면 HP-UX 호스트에서 입출력이 재개되는 데 120초 이상이 걸릴 수 있습니다. 실행 중인 애플리케이션에 따라 I/O 중단 또는 오류 메시지가 발생할 수 없습니다. 격리된 마스터 클러스터에서 AUFO 이벤트가 발생하면 HP-UX 호스트에서 중단 허용 시간이 120초 미만인 애플리케이션을 재시작해야 합니다.

격리된 마스터 클러스터의 AUFO 이벤트는 운영 클러스터와 보조 클러스터 간의 연결이 끊겼고 기본 클러스터와 중재자 사이의 연결도 끊어졌을 때 이중 이벤트 장애를 일으킬 수 있습니다. 이것은 다른 AUFO 이벤트와 달리 드문 사건으로 간주됩니다.
