---
sidebar: sidebar 
permalink: smbc/smbc_admin_upgrade_and_revert_considerations.html 
keywords: upgrade, revert, ONTAP 
summary: ONTAP를 업그레이드하거나 되돌리면 특히 ONTAP 9.8 이상 또는 9.7 이전 버전으로 전환할 때 SM-BC 관계에 영향을 미칩니다. 
---
= SM-BC를 사용하여 ONTAP를 업그레이드하고 복구합니다
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
ONTAP 9.8부터 SM-BC(SnapMirror 비즈니스 연속성)가 지원됩니다. ONTAP 클러스터를 업그레이드하고 되돌리면 업그레이드 또는 되돌리려고 하는 ONTAP 버전에 따라 SM-BC 관계에 영향을 미칩니다.



== ONTAP를 업그레이드합니다

SM-BC를 구성하고 사용하려면 먼저 소스 및 대상 클러스터의 모든 노드를 ONTAP 9.8 이상으로 업그레이드해야 합니다.
link:link:../upgrade/index.html["ONTAP 클러스터에서 소프트웨어 업그레이드"]


NOTE: 를 클릭합니다 `snapmirror quiesce` 및 `snampirror resume` SM-BC에서는 명령어가 지원되지 않습니다.

클러스터를 9.8 또는 9.9.1에서 9.10.1로 업그레이드할 경우 ONTAP는 SM-BC 관계의 소스와 대상 모두에 새 정합성 보장 그룹을 생성합니다. 이러한 구성 요소는 시스템 관리자의** 정합성 보장 그룹** 옵션 또는 ONTAP REST API와 정합성 보장 그룹 엔드포인트를 함께 사용하여 관리할 수 있습니다.



== ONTAP 9.10.1에서 ONTAP 9.9.1로 되돌립니다

관계를 9.10.1에서 9.9.1로 되돌리려면 SM-BC 관계를 삭제한 다음 9.10.1 정합성 보장 그룹 인스턴스를 삭제해야 합니다. SM-BC 관계가 활성 상태인 정합성 보장 그룹은 삭제할 수 없습니다. 9.9.1 이전 버전에서 다른 스마트 컨테이너 또는 엔터프라이즈 앱과 이전에 연결된 9.10.1로 업그레이드된 FlexVol 볼륨은 더 이상 복원 시 연결되지 않습니다. 일관성 그룹을 삭제해도 구성 볼륨 또는 볼륨 세부 스냅샷은 삭제되지 않습니다. 을 참조하십시오 link:../consistency-groups/delete-task.html["일관성 그룹을 삭제합니다"] ONTAP 9.10.1 이상에서 이 작업에 대한 자세한 내용을 확인하십시오.



== ONTAP 9.8에서 ONTAP 9.7로 되돌립니다


NOTE: SM-BC는 ONTAP 9.7과 ONTAP 9.8 클러스터가 혼합된 경우에는 지원되지 않습니다.

ONTAP 9.8에서 ONTAP 9.7로 되돌릴 때 다음 사항을 염두에 두어야 합니다.

* 클러스터 호스트가 SM-BC 대상인 경우 관계가 끊기거나 삭제될 때까지 ONTAP 9.7로 되돌릴 수 없습니다.
* 클러스터에서 SM-BC 소스를 호스팅하는 경우 관계가 릴리즈될 때까지 ONTAP 9.7로 되돌릴 수 없습니다.
* 사용자가 생성한 모든 맞춤형 SM-BC SnapMirror 정책을 ONTAP 9.7로 되돌리기 전에 반드시 삭제해야 합니다.


이러한 요구 사항을 충족하려면 를 참조하십시오 link:smbc_admin_removing_an_smbc_configuration.html["SM-BC 구성을 제거합니다"].

.단계
. SM-BC 관계에 있는 클러스터 중 하나에서 되돌리기 검사를 수행합니다.
+
'cluster::: * > 시스템 노드를 버전 9.7 검사로만 되돌리기

+
예:

+
....
cluster::*> system node revert-to -version 9.7 -check-only
Error: command failed: The revert check phase failed. The following issues must be resolved before revert can be completed. Bring the data LIFs down on running vservers. Command to list the running vservers: vserver show -admin-state running Command to list the data LIFs that are up: network interface show -role data -status-admin up Command to bring all data LIFs down: network interface modify {-role data} -status-admin down
Disable snapshot policies.
    Command to list snapshot policies: "snapshot policy show".
    Command to disable snapshot policies: "snapshot policy modify -vserver
   * -enabled false"

   Break off the initialized online data-protection (DP) volumes and delete
   Uninitialized online data-protection (DP) volumes present on the local
   node.
    Command to list all online data-protection volumes on the local node:
   volume show -type DP -state online -node <local-node-name>
    Before breaking off the initialized online data-protection volumes,
   quiesce and abort transfers on associated SnapMirror relationships and
   wait for the Relationship Status to be Quiesced.
    Command to quiesce a SnapMirror relationship: snapmirror quiesce
    Command to abort transfers on a SnapMirror relationship: snapmirror
   abort
    Command to see if the Relationship Status of a SnapMirror relationship
   is Quiesced: snapmirror show
    Command to break off a data-protection volume: snapmirror break
    Command to break off a data-protection volume which is the destination
   of a SnapMirror relationship with a policy of type "vault": snapmirror
   break -delete-snapshots
    Uninitialized data-protection volumes are reported by the "snapmirror
   break" command when applied on a DP volume.
    Command to delete volume: volume delete

   Delete current version snapshots in advanced privilege level.
    Command to list snapshots: "snapshot show -fs-version 9.8"
    Command to delete snapshots: "snapshot prepare-for-revert -node
   <nodename>"

   Delete all user-created policies of the type active-strict-sync-mirror
   and active-sync-mirror.
   The command to see all active-strict-sync-mirror and active-sync-mirror
   type policies is:
    snapmirror policy show -type
   active-strict-sync-mirror,active-sync-mirror
   The command to delete a policy is :
    snapmirror policy delete -vserver <SVM-name> -policy <policy-name>
....


클러스터 되돌리기에 대한 자세한 내용은 을 참조하십시오 link:../revert/index.html["ONTAP를 되돌립니다"].
