---
sidebar: sidebar 
permalink: smbc/smbc_admin_converting_existing_relationships_to_smbc.html 
keywords: SM-BC, SMBC, convert, Synchronous SnapMirror, zero RPO, zero recovery time objective, zero RTO, existing 
summary: '기존 제로 복구 지점 보호(제로 RPO) 동기식 SnapMirror 관계를 SM-BC 제로 RTO 동기식 SnapMirror 정합성 보장 그룹 관계로 변환할 수 있습니다.' 
---
= 기존 관계를 SM-BC 관계로 전환
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
기존 제로 복구 지점 보호(제로 RPO) 동기식 SnapMirror 관계를 SM-BC 제로 RTO 동기식 SnapMirror 정합성 보장 그룹 관계로 변환할 수 있습니다.

.시작하기 전에
* RPO가 0인 동기식 SnapMirror 관계가 1차 및 2차 사이트 간에 존재합니다.
* 제로 RTO SnapMirror 관계가 생성되기 전에 대상 볼륨의 모든 LUN이 매핑 해제됩니다.
* SM-BC는 SAN 프로토콜(NFS/CIFS 아님)만 지원합니다. NAS 액세스를 위해 정합성 보장 그룹의 구성 요소 가 마운트되지 않았는지 확인합니다.


.이 작업에 대해
* 소스 및 대상에서 클러스터 및 SVM 관리자여야 합니다.
* SnapMirror 정책을 변경하여 제로 RPO를 제로 RTO 동기화로 변환할 수 없습니다.
* 2차 볼륨의 기존 LUN이 매핑된 경우 AutomatedFailover 정책을 사용하여 스냅샷 생성 시 오류가 발생합니다. 'napmirror create' 명령을 실행하기 전에 LUN이 매핑 해제되었는지 확인해야 합니다.


.단계
. 기존 관계에서 SnapMirror 업데이트 작업을 수행합니다.
+
대상 경로 VS1_DST:vol1'을 선택합니다

. SnapMirror 업데이트가 성공적으로 완료되었는지 확인합니다.
+
목적지::> SnapMirror 쇼

. 제로 RPO 동기식 관계 각각 중지:
+
대상 경로 VS1_DST:vol1'을 선택합니다

+
목적지:::> SnapMirror quiesce-destination-path vs1_dst:vol2"로 설정합니다

. 각 제로 RPO 동기식 관계 삭제:
+
목적지 경로 VS1_DST:vol1'을(를) 삭제합니다

+
대상 경로 VS1_DST:vol2'를 선택합니다

. 소스 SnapMirror 관계를 릴리즈하고 공통 스냅샷 복사본을 유지합니다.
+
'source::> snapmirror release-relationship-info-only true-destination-path vs1_dst:vol1'

+
'source::> snapmirror release-relationship-info-only true-destination-path vs1_dst:vol2'를 참조하십시오

. 그룹 제로 RTO 동기식 SnapMirror 관계 생성:
+
대상 경로 VS1_src:/cg/cg_src-destination-path vs1_dst:/cg/cg_dst-item-volmapping 1:@vol1, vol2:@vol2-policy AutomatedFailover"

. 제로 RTO 정합성 보장 그룹을 재동기화합니다.
+
대상 경로 VS1_DST:/CG/CG_DST'를 다시 동기화하십시오

. 호스트 LUN 입출력 경로를 재검색하여 LUN에 대한 모든 경로를 복구합니다.

