---
sidebar: sidebar 
permalink: smbc/smbc_intro_terminology.html 
keywords: SM-BC, SMBC, Mediator, terminology 
summary: ONTAP SnapMirror 비즈니스 연속성을 살펴보고 구축을 계획하기 시작할 때 핵심 용어와 개념을 이해하는 것이 좋습니다. 
---
= 주요 개념
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
ONTAP SnapMirror 비즈니스 연속성을 살펴보고 구축을 계획하기 시작할 때 핵심 용어와 개념을 이해하는 것이 좋습니다.

ONTAP 9.8 이상에서 사용할 수 있는 SnapMirror 비즈니스 연속성(SM-BC) 솔루션의 약어입니다.

ONTAP 9.10.1부터 정합성 보장 그룹은 첫 번째 주문 관리 유닛이 되었습니다. 일관성 그룹에 대한 자세한 내용은 을 참조하십시오 link:../consistency-groups/index.html["일관성 그룹 개요"].

일관성 그룹(CG)은 비즈니스 연속성을 위해 보호해야 하는 애플리케이션 워크로드에 대해 쓰기 순서 정합성을 보장하는 FlexVol 볼륨의 모음입니다. 일관성 그룹의 목적은 한 번에 볼륨 컬렉션 중 충돌 시에도 정합성이 보장되는 Snapshot 복사본을 동시에 생성하는 것입니다. 일반 구축에서 CG의 일부로 선택된 볼륨 그룹이 애플리케이션 인스턴스에 매핑됩니다. CG 관계라고도 하는 SnapMirror 관계는 소스 CG와 대상 CG 간에 설정됩니다. 소스 및 타겟 CG의 볼륨 수와 유형이 동일해야 합니다.

일관성 그룹에 포함되는 개별 FlexVol 볼륨

ONTAP 중재자가 다른 상태 경로를 제공하는 인터클러스터 LIF를 사용하여 피어 클러스터에 대한 대체 상태 경로를 제공합니다. 중재자의 상태 정보를 사용하여 클러스터가 인터클러스터 LIF 장애와 사이트 장애를 구분할 수 있습니다. 사이트가 다운되면 중재자가 필요에 따라 피어 클러스터에 상태 정보를 전달하여 피어 클러스터가 장애 조치되도록 합니다. 중재자가 제공한 정보와 인터클러스터 LIF 상태 점검 정보를 사용하여 ONTAP는 자동 페일오버를 수행할 수 없는 경우 페일오버를 계속 또는 중지할지 여부를 결정합니다.

중재자는 SM-BC 쿼럼의 3개 당사자 중 하나로, 합의를 도출하기 위해 1차 클러스터 및 2차 클러스터와 함께 일합니다. 합의는 정족수에 있는 최소한 두 당사자가 작업에 합의하도록 요구합니다.

애플리케이션 I/O가 보조 스토리지 시스템으로 복제되지 않습니다. SnapMirror 복제가 발생하지 않으므로 대상 볼륨이 소스 볼륨과 동기화되지 않습니다. 미러 상태가 Snapmirrored인 경우 지원되지 않는 작업으로 인한 전송 실패나 실패를 나타냅니다.

복구 시점 목표가 없습니다. 이는 가동 중지의 허용되는 데이터 손실입니다.

호스트 MPIO(다중 경로 I/O) 소프트웨어 기반 경로 페일오버를 사용하여 스토리지에 대한 무중단 액세스를 제공하여 복구 시간 목표 또는 투명한 애플리케이션 페일오버를 실현합니다.

SM-BC 관계에서 복제본의 역할을 변경하는 수동 작업입니다. 1차 사이트가 2차 사이트가 되고 2차 사이트가 1차 사이트가 됩니다. ALUA 보고도 변경됩니다.

미러 복제본에 대한 페일오버를 수행하는 자동 작업입니다. 기본 복사본을 사용할 수 없음을 감지하려면 중재자의 도움이 필요합니다.
