---
permalink: s3-audit/show-config-task.html 
sidebar: sidebar 
keywords: s3 audit, show, display 
summary: 이 작업은 CLI에서 S3 감사에 대한 정보를 표시하는 방법을 설명합니다. 
---
= S3 감사 구성을 표시합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
감사 구성을 완료한 후 감사가 올바르게 구성되어 있고 활성화되어 있는지 확인할 수 있습니다. 또한 클러스터의 모든 오브젝트 저장소 감사 구성에 대한 정보를 표시할 수도 있습니다.

.이 작업에 대해
버킷 및 SVM 감사 구성에 대한 정보를 표시할 수 있습니다.

* 버킷 - 'vserver object-store-server audit event-selector show' 명령어를 사용한다
+
매개 변수 없이 명령을 실행하면 오브젝트 저장소 감사 구성이 포함된 클러스터의 모든 SVM에 있는 버킷에 대한 다음 정보가 표시됩니다.

+
** SVM 이름
** 버킷 이름
** 액세스 및 권한 값


* SVM – 'vserver object-store-server audit show' 명령을 사용합니다
+
매개 변수 없이 명령을 실행하면 오브젝트 저장소 감사 구성이 포함된 클러스터의 모든 SVM에 대한 다음 정보가 표시됩니다.

+
** SVM 이름
** 감사 상태
** 대상 디렉토리




'-fields' 파라미터를 지정하여 표시할 감사 구성 정보를 지정할 수 있습니다.

.절차를 참조하십시오
S3 감사 구성에 대한 정보 표시:

[cols="2,4"]
|===
| 에 대한 구성을 수정하려면... | 입력... 


| 버킷 | 'vserver object-store-server audit event-selector show[-vserver_svm_name_][_parameters_]' 


| SVM  a| 
'vserver object-store-server audit show[-vserver_svm_name_][_parameters_]'

|===
.예
다음 예는 단일 버킷에 대한 정보를 표시합니다.

[listing]
----
cluster1::> vserver object-store-server audit event-selector show -vserver vs1 -bucket test-bucket
     Vserver     Bucket     Access          Permission
     ----------- ---------- --------------- ----------
     vs1         bucket1    read-only       allow-only
----
다음 예는 SVM의 모든 버킷에 대한 정보를 표시합니다.

[listing]
----
cluster1::> vserver object-store-server audit event-selector show -vserver vs1

     Vserver           :vs1
     Bucket            :test-bucket
     Access            :all
     Permission        :all
----
다음 예에서는 모든 SVM에 대한 이름, 감사 상태, 이벤트 유형, 로그 형식, 타겟 디렉토리를 표시합니다.

[listing]
----
cluster1::> vserver object-store-server audit show

Vserver     State  Event Types Log Format Target Directory
----------- ------ ----------- ---------- --------------------
vs1         false  data        json       /audit_log
----
다음 예에서는 SVM 이름과 모든 SVM의 감사 로그에 대한 세부 정보를 표시합니다.

[listing]
----
cluster1::> vserver object-store-server audit show -log-save-details

                  Rotation                           Rotation
      Vserver     File Size Rotation Schedule        Limit
      ----------- --------- ------------------------ --------
      vs1         100MB     -                        0
----
다음 예제는 모든 SVM에 대한 모든 감사 구성 정보를 목록 형식으로 표시합니다.

[listing]
----
cluster1::> vserver object-store-server audit show -instance

                             Vserver: vs1
                      Auditing state: true
                Log Destination Path: /audit_log
       Categories of Events to Audit: data
                          Log Format: json
                 Log File Size Limit: 100MB
        Log Rotation Schedule: Month: -
  Log Rotation Schedule: Day of Week: -
          Log Rotation Schedule: Day: -
         Log Rotation Schedule: Hour: -
       Log Rotation Schedule: Minute: -
                  Rotation Schedules: -
            Log Files Rotation Limit: 0
                  Log Retention Time: 0s
----