---
sidebar: sidebar 
permalink: s3-snapmirror/requirements-cloud-targets-concept.html 
keywords: requirements for cloud target relationships 
summary: 소스 및 타겟 환경이 클라우드 타겟에 대한 SnapMirror S3 백업 보호 요구사항을 충족하는지 확인하십시오. 
---
= 클라우드 타겟 관계에 대한 요구사항
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
소스 및 타겟 환경이 클라우드 타겟에 대한 SnapMirror S3 백업 보호 요구사항을 충족하는지 확인하십시오.

데이터 버킷에 액세스하려면 오브젝트 저장소 공급자의 유효한 계정 자격 증명이 있어야 합니다.

클러스터를 클라우드 오브젝트 저장소에 연결하려면 먼저 클러스터에서 인터클러스터 LIF 및 IPspace를 구성해야 합니다. 로컬 스토리지의 데이터를 클라우드 오브젝트 저장소로 원활하게 전송하려면 각 노드에 대한 인터클러스터 LIF를 생성해야 합니다.

StorageGRID 대상의 경우 다음 정보를 알아야 합니다.

* FQDN(정규화된 도메인 이름) 또는 IP 주소로 표시되는 서버 이름입니다
* 버킷 이름. 버킷이 이미 있어야 합니다
* 액세스 키
* 비밀 키


또한 StorageGRID 서버 인증서를 서명하는 데 사용되는 CA 인증서를 를 사용하여 ONTAP S3 클러스터의 관리 스토리지 VM에 `security certificate install command` 설치해야 합니다. 자세한 내용은 link:../fabricpool/install-ca-certificate-storagegrid-task.html["CA 인증서를 설치하는 중입니다"]StorageGRID 사용 여부 를 참조하십시오.

AWS S3 타겟의 경우 다음 정보를 알아야 합니다.

* FQDN(정규화된 도메인 이름) 또는 IP 주소로 표시되는 서버 이름입니다
* 버킷 이름. 버킷이 이미 있어야 합니다
* 액세스 키
* 비밀 키


ONTAP 클러스터의 관리 스토리지 VM용 DNS 서버는 FQDN(사용되는 경우)을 IP 주소로 확인할 수 있어야 합니다.
