---
permalink: nvme/support-limitations.html 
sidebar: sidebar 
keywords: nvme, namespaces, considerations, provisioning 
summary: NVMe 지원은 ONTAP 버전, 플랫폼 및 구성에 따라 다릅니다. 
---
= NVMe 지원 및 제한 사항
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NVMe 지원 및 제한 사항은 사용 중인 ONTAP 버전, 플랫폼 및 구성에 따라 다릅니다.



== 프로토콜 지원

[cols="3*"]
|===


| 프로토콜 | 다음으로 시작... | 허용된 사용자... 


| TCP | ONTAP 9.10.1 | 기본값 


| FCP | ONTAP 9.4 | 기본값 
|===


== 플랫폼 및 구성 지원 및 제한 사항

NVMe-oF 프로토콜 지원은 플랫폼 및 구성에 따라 다릅니다. 특정 구성에 대한 자세한 내용은 를 참조하십시오 link:https://imt.netapp.com/matrix/["NetApp 상호 운용성 매트릭스 툴"].


NOTE: ONTAP 9.12.1부터 4노드 MetroCluster IP 구성이 NVMe/FC에서 지원됩니다. MetroCluster 구성은 9.12.1 이전의 NVMe에 대해서는 지원되지 않습니다.

[cols="2*"]
|===


| ONTAP로 시작하는 중... | 플랫폼 


| 9.12.1  a| 
* FAS
* AFF(All Flash FAS)
* ASA(All SAN Array) 플랫폼




| 9.9.1  a| 
* AFF
* ASA




| 9.4 | AFF 플랫폼 전용입니다 
|===


== 네임스페이스 지원 및 제한 사항

SAN 환경에서 NVMe 프로토콜을 설정하려면 NVMe용 SVM을 구성하고, 네임스페이스와 서브시스템을 생성하고, NVMe/FC LIF를 구성한 다음, 네임스페이스를 서브시스템에 매핑해야 합니다. NVMe 네임스페이스로 작업할 때 다음 사항을 염두에 두어야 합니다.

* ONTAP 9.10.1부터 가능합니다 xref:../nvme/resize-namespace-task.html[네임스페이스 크기 조정]. ONTAP 9.10.1 이전 버전에서는 네임스페이스 크기 조정이 지원되지 않습니다.
* ONTAP 9.6부터 네임스페이스는 512바이트 블록과 4096바이트 블록을 지원합니다.
+
기본값은 4096입니다. 512는 호스트 운영 체제가 4096바이트 블록을 지원하지 않는 경우에만 사용해야 합니다.

* LUN의 데이터가 손실될 경우 네임스페이스에서 또는 그 반대로 LUN을 복원할 수 없습니다.
* 네임스페이스에 대한 공간 보장은 포함하는 볼륨의 공간 보장과 동일합니다.
* 네임스페이스는 다음을 지원하지 않습니다.
+
** 이름 바꾸기
+
이름 공간의 이름은 바꿀 수 없습니다.

** 볼륨 간 이동
** 볼륨 간 복사



