---
sidebar: sidebar 
permalink: networking/add_or_remove_ip_addresses_from_a_subnet.html 
keywords: adding, add, create, creating, remove, removing, delete, deleting, ip, internet, protocol, address, addresses, subnet, add or remove ip addresses from a subnet, force update lif associations, network subnet add ranges, network subnet remove ranges 
summary: 서브넷을 생성할 때 IP 주소를 추가하거나 기존 서브넷에 IP 주소를 추가하거나 제거합니다 
---
= 서브넷에서 IP 주소를 추가하거나 제거합니다
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
처음에 서브넷을 생성할 때 IP 주소를 추가하거나 이미 존재하는 서브넷에 IP 주소를 추가할 수 있습니다. 기존 서브넷에서 IP 주소를 제거할 수도 있습니다. 따라서 SVM에 필요한 IP 주소만 할당할 수 있습니다.

IP 주소를 추가할 때 서비스 프로세서 또는 네트워크 인터페이스가 추가되는 범위의 IP 주소를 사용하는 경우 오류가 발생합니다. 수동으로 주소를 지정한 인터페이스를 현재 서브넷에 연결하려면 "-force-update-lif-associations" 옵션을 true로 설정합니다.

IP 주소를 제거할 때 서비스 프로세서 또는 네트워크 인터페이스에서 제거 중인 IP 주소를 사용하는 경우 오류가 발생합니다. 서브넷에서 IP 주소를 제거한 후에도 인터페이스가 계속 사용하도록 하려면 "-force-update-lif-associations" 옵션을 true 로 설정합니다.

서브넷에서 IP 주소 추가 또는 제거:

[cols="30,70"]
|===


| 원하는 작업 | 이 명령 사용... 


 a| 
IP 주소를 서브넷에 추가합니다
 a| 
네트워크 서브넷 추가 범위



 a| 
서브넷에서 IP 주소를 제거합니다
 a| 
네트워크 서브넷 remove-range

|===
이러한 명령에 대한 자세한 내용은 man 페이지를 참조하십시오.

다음 명령을 실행하면 서브넷 sub1에 IP 주소 192.0.2.82 ~ 192.0.2.85 가 추가됩니다.

....
network subnet add-ranges -subnet-name <sub1> -ip-ranges <192.0.2.82-192.0.2.85>
....
다음 명령을 실행하면 서브넷 하위 3에서 IP 주소 198.51.100.9가 제거됩니다.

....
network subnet remove-ranges -subnet-name <sub3> -ip-ranges <198.51.100.9>
....
현재 범위에 1 ~ 10 및 20 ~ 40이 포함되어 있고 11 ~ 19 및 41 ~ 50(기본적으로 1 ~ 50을 허용)을 추가하려는 경우 다음 명령을 사용하여 기존 주소 범위와 겹칠 수 있습니다. 이 명령은 새 주소만 추가하며 기존 주소에는 영향을 주지 않습니다.

....
network subnet add-ranges -subnet-name <sub3> -ip-ranges <198.51.10.1-198.51.10.50>
....