---
sidebar: sidebar 
permalink: networking/configure_snmpv3_users_in_a_cluster.html 
keywords: configure, configuration, configuring, setup, setting, set, up, snmp, snmpv3, users, user, cluster, security, secure, configure an snmpv3 user to run the snmp utilities from the snmp manager, security login create command, configure snmpv3 users in a cluster, snmpv3 security parameters, examples for different security levels, security level authpriv, fips mode, snmpwalk test, security level authnopriv 
summary: SNMP 관리자에서 SNMP 유틸리티를 실행하도록 SNMPv3 사용자를 구성합니다 
---
= 클러스터에서 SNMPv3 사용자를 구성합니다
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
SNMPv3는 SNMPv1 및 SNMPv2c와 비교할 때 보안 프로토콜입니다. SNMPv3을 사용하려면 SNMP 관리자에서 SNMP 유틸리티를 실행하도록 SNMPv3 사용자를 구성해야 합니다.

"security login create command"를 사용하여 SNMPv3 사용자를 생성합니다.

다음 정보를 제공하라는 메시지가 표시됩니다.

* 엔진 ID: 기본값과 권장 값은 로컬 엔진 ID입니다
* 인증 프로토콜
* 인증 암호입니다
* 개인 정보 보호 프로토콜
* 개인 정보 프로토콜 암호


SNMPv3 사용자는 사용자 이름 및 암호를 사용하여 SNMP 관리자에서 로그인하고 SNMP 유틸리티 명령을 실행할 수 있습니다.



== SNMPv3 보안 매개 변수

SNMPv3에는 사용자가 명령을 호출할 때 이름, 인증 프로토콜, 인증 키 및 원하는 보안 수준을 입력해야 하는 인증 기능이 포함되어 있습니다.

다음 표에는 SNMPv3 보안 매개 변수가 나열되어 있습니다.

[cols="25,25,50"]
|===


| 매개 변수 | 명령줄 옵션입니다 | 설명 


 a| 
엔진 ID
 a| 
-e 엔지니어링 ID
 a| 
SNMP 에이전트의 엔진 ID입니다. 기본값은 Local EngineID(권장)입니다.



 a| 
보안 이름
 a| 
-u 이름
 a| 
사용자 이름은 32자를 초과할 수 없습니다.



 a| 
authProtocol의 약어입니다
 a| 
-a {none|MD5|SHA|SHA-256}
 a| 
인증 유형은 없음, MD5, SHA 또는 SHA-256일 수 있습니다.



 a| 
인증 키
 a| 
- 암호문
 a| 
최소 8자의 암호 구문



 a| 
보안 수준
 a| 
-l {authNo암호화 | Auth암호화 | noAuthNo암호화}
 a| 
보안 수준은 인증, 개인 정보 보호 없음, 인증, 개인 정보 보호 또는 인증 없음일 수 있습니다. 개인 정보 보호.



 a| 
개인 프로토콜
 a| 
-x{none|des|aes128}
 a| 
개인 정보 보호 프로토콜은 없음, des 또는 aes128일 수 있습니다



 a| 
privPassword(비밀 번호)
 a| 
-X 암호
 a| 
최소 8자의 암호입니다.

|===


== 다양한 보안 수준에 대한 예

이 예에서는 서로 다른 보안 수준으로 생성된 SNMPv3 사용자가 'snmpwalk'와 같은 SNMP 클라이언트 측 명령을 사용하여 클러스터 객체를 쿼리하는 방법을 보여 줍니다.

성능을 향상시키려면 테이블에서 단일 개체나 몇 개의 개체를 검색하는 대신 테이블의 모든 개체를 검색해야 합니다.


NOTE: 인증 프로토콜이 SHA 인 경우 'snmpwalk' 5.3.1 이상을 사용해야 합니다.



=== 보안 수준: auth암호화

다음 출력에서는 auth암호화 보안 수준으로 SNMPv3 사용자를 생성하는 방법을 보여 줍니다.

....
security login create -username snmpv3user -application snmp -authmethod usm
Enter the authoritative entity's EngineID [local EngineID]:
Which authentication protocol do you want to choose  (none, md5, sha) [none]:sha
....


==== FIPS 모드

....
Which authentication protocol do you want to choose (sha, sha2-256) [sha]

Enter authentication protocol password (minimum 8 characters long):
Enter authentication protocol password again:
Which privacy protocol do you want to choose  (none, des) [none]: des
Enter privacy protocol password (minimum 8 characters long):
Enter privacy protocol password again:
....


==== snmpwalk 테스트

다음 출력에서는 snmpwalk 명령을 실행하는 SNMPv3 사용자를 보여 줍니다.

성능을 향상시키려면 테이블에서 단일 개체나 몇 개의 개체를 검색하는 대신 테이블의 모든 개체를 검색해야 합니다.

....
$ snmpwalk -v 3 -u snmpv3user -a SHA -A password1! -x DES -X password1! -l authPriv 192.0.2.62 .1.3.6.1.4.1.789.1.5.8.1.2
Enterprises.789.1.5.8.1.2.1028 = "vol0"
Enterprises.789.1.5.8.1.2.1032 = "vol0"
Enterprises.789.1.5.8.1.2.1038 = "root_vs0"
Enterprises.789.1.5.8.1.2.1042 = "root_vstrap"
Enterprises.789.1.5.8.1.2.1064 = "vol1"
....


=== 보안 수준: authNo암호화

다음 출력에서는 authNo암호화 보안 수준으로 SNMPv3 사용자를 생성하는 방법을 보여 줍니다.

....
security login create -username snmpv3user1 -application snmp -authmethod usm -role admin
Enter the authoritative entity's EngineID [local EngineID]:
Which authentication protocol do you want to choose (none, md5, sha) [none]: md5
....


==== FIPS 모드

....
Which privacy protocol do you want to choose (aes128) [aes128]

Enter authentication protocol password (minimum 8 characters long):
Enter authentication protocol password again:
Which privacy protocol do you want to choose (none, des) [none]: none
....


==== snmpwalk 테스트

다음 출력에서는 snmpwalk 명령을 실행하는 SNMPv3 사용자를 보여 줍니다.

성능을 향상시키려면 테이블에서 단일 개체나 몇 개의 개체를 검색하는 대신 테이블의 모든 개체를 검색해야 합니다.

....
$ snmpwalk -v 3 -u snmpv3user1 -a MD5 -A password1!  -l authNoPriv 192.0.2.62 .1.3.6.1.4.1.789.1.5.8.1.2
Enterprises.789.1.5.8.1.2.1028 = "vol0"
Enterprises.789.1.5.8.1.2.1032 = "vol0"
Enterprises.789.1.5.8.1.2.1038 = "root_vs0"
Enterprises.789.1.5.8.1.2.1042 = "root_vstrap"
Enterprises.789.1.5.8.1.2.1064 = "vol1"
....


=== 보안 수준: noAuthNo암호화

다음 출력에서는 NOAuthNo암호화 보안 수준으로 SNMPv3 사용자를 생성하는 방법을 보여 줍니다.

....
security login create -username snmpv3user2 -application snmp -authmethod usm -role admin
Enter the authoritative entity's EngineID [local EngineID]:
Which authentication protocol do you want to choose (none, md5, sha) [none]: none
....


==== FIPS 모드

FIPS에서는 사용자가 없음을 선택할 수 없습니다



==== snmpwalk 테스트

다음 출력에서는 snmpwalk 명령을 실행하는 SNMPv3 사용자를 보여 줍니다.

성능을 향상시키려면 테이블에서 단일 개체나 몇 개의 개체를 검색하는 대신 테이블의 모든 개체를 검색해야 합니다.

....
$ snmpwalk -v 3 -u snmpv3user2 -l noAuthNoPriv 192.0.2.62 .1.3.6.1.4.1.789.1.5.8.1.2
Enterprises.789.1.5.8.1.2.1028 = "vol0"
Enterprises.789.1.5.8.1.2.1032 = "vol0"
Enterprises.789.1.5.8.1.2.1038 = "root_vs0"
Enterprises.789.1.5.8.1.2.1042 = "root_vstrap"
Enterprises.789.1.5.8.1.2.1064 = "vol1"
....