---
sidebar: sidebar 
permalink: networking/configure_network_ports_@cluster_administrators_only@_overview.html 
keywords: introducing, introduction, overview, network, port, port type, type, physical, interface group, vlan, vip, virtual, naming, convention, configure network ports overview, introducing physical and virtual network ports 
summary: 물리적 및 가상 네트워크 포트 소개 
---
= 개요
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
포트는 물리적 포트(NIC) 또는 인터페이스 그룹 또는 VLAN과 같은 가상 포트입니다.

VLAN(Virtual Local Area Network) 및 인터페이스 그룹은 가상 포트를 구성합니다. 인터페이스 그룹은 여러 물리적 포트를 단일 포트로 취급하며 VLAN은 물리적 포트를 여러 개의 개별 논리 포트로 세분화합니다.

* 물리적 포트: LIF는 물리적 포트에서 직접 구성할 수 있습니다.
* 인터페이스 그룹: 단일 트렁크 포트로 작동하는 2개 이상의 물리적 포트를 포함하는 포트 애그리게이트. 인터페이스 그룹은 단일 모드, 다중 모드 또는 동적 다중 모드일 수 있습니다.
* VLAN: VLAN 태그 지정(IEEE 802.1Q 표준) 트래픽을 수신 및 전송하는 논리 포트입니다. VLAN 포트 특성에는 포트의 VLAN ID가 포함됩니다. 기본 물리적 포트 또는 인터페이스 그룹 포트는 VLAN 트렁크 포트로 간주되며 연결된 스위치 포트는 VLAN ID를 트렁킹하도록 구성해야 합니다.
+
VLAN 포트의 기본 물리적 포트 또는 인터페이스 그룹 포트는 태그 없는 트래픽을 전송 및 수신하는 LIF를 계속 호스팅할 수 있습니다.

* 가상 IP(VIP) 포트: VIP LIF의 홈 포트로 사용되는 논리 포트입니다. VIP 포트는 시스템에서 자동으로 생성되며 제한된 수의 작업만 지원합니다. VIP 포트는 ONTAP 9.5부터 지원됩니다.


포트 명명 규칙은 _ enumberletter _ 입니다.

* 첫 번째 문자는 포트 유형을 나타냅니다. "e"는 이더넷을 나타냅니다.
* 두 번째 문자는 포트 어댑터가 있는 번호가 매겨진 슬롯을 나타냅니다.
* 세 번째 문자는 다중 포트 어댑터의 포트 위치를 나타냅니다. "a"는 첫 번째 포트를 나타내고, "b"는 두 번째 포트를 나타냅니다.


예를 들어, "e0b"은 이더넷 포트가 노드 마더보드의 두 번째 포트임을 나타냅니다.

VLAN은 'port_name-vlan-id' 구문을 사용하여 이름을 지정해야 합니다.

port_name은 물리적 포트 또는 인터페이스 그룹을 지정합니다.

VLAN-id는 네트워크의 VLAN 식별을 지정합니다. 예를 들어, "e1c-80"은 유효한 VLAN 이름입니다.
