---
permalink: networking/convert-uta2-port-cna-fc.html 
sidebar: sidebar 
keywords: change, uta2, port, cna mode, fc mode 
summary: 포트를 네트워크에 연결하거나 FC 이니시에이터 및 타겟을 지원하는 물리적 미디어를 변경해야 하는 경우 UTA2 속성을 CNA 모드에서 FC 모드로 변경합니다. 
---
= ONTAP의 UTA2 포트를 숨깁니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
UTA2 포트를 CNA(Converged Network Adapter) 모드에서 파이버 채널(FC) 모드로 전환하거나 그 반대로 전환할 수 있습니다.

포트를 네트워크에 연결하거나 FC 이니시에이터 및 타겟을 지원하는 물리적 미디어를 변경해야 하는 경우 UTA2 속성을 CNA 모드에서 FC 모드로 변경해야 합니다.

[role="tabbed-block"]
====
.CNA 모드에서 FC 모드로 전환
--
.단계
. 어댑터를 오프라인 상태로 전환:
+
[source, cli]
----
network fcp adapter modify -node <node_name> -adapter <adapter_name> -status-admin down
----
. 포트 모드를 변경합니다.
+
[source, cli]
----
ucadmin modify -node <node_name> -adapter <adapter_name> -mode fcp
----
. 노드를 재부팅한 다음 어댑터를 온라인 상태로 전환합니다.
+
[source, cli]
----
network fcp adapter modify -node <node_name> -adapter <adapter_name> -status-admin up
----
. 필요에 따라 관리자 또는 VIF 관리자에게 포트를 삭제하거나 제거하도록 알립니다.
+
** 포트가 LIF의 홈 포트로 사용되고, 인터페이스 그룹(ifgrp) 또는 호스트 VLAN의 구성원인 경우 관리자는 다음을 수행해야 합니다.
+
*** LIF를 이동하거나, ifgrp에서 포트를 제거하거나, VLAN을 각각 삭제합니다.
*** 명령을 실행하여 포트를 수동으로 삭제합니다 `network port delete`. 명령이 실패하면 `network port delete` 관리자가 오류를 해결한 다음 명령을 다시 실행해야 합니다.


** 포트가 LIF의 홈 포트로 사용되지 않고, ifgrp의 구성원이 아니며 VLAN을 호스팅하지 않는 경우, VIF 관리자는 재부팅 시 기록에서 포트를 제거해야 합니다. VIF 관리자가 포트를 제거하지 않는 경우, 관리자는 재부팅 후 명령을 사용하여 수동으로 포트를 제거해야 `network port delete` 합니다.


. 올바른 SFP+가 설치되었는지 확인합니다.
+
[source, cli]
----
network fcp adapter show -instance -node -adapter
----
+
CNA의 경우 10Gb 이더넷 SFP를 사용해야 합니다. FC의 경우 노드에서 구성을 변경하기 전에 8Gb SFP 또는 16Gb SFP를 사용해야 합니다.



--
.FC 모드에서 CNA 모드로 전환합니다
--
.단계
. 어댑터를 오프라인 상태로 전환:
+
[source, cli]
----
network fcp adapter modify -node <node_name> -adapter <adapter_name> -status-admin down
----
. 포트 모드를 변경합니다.
+
[source, cli]
----
ucadmin modify -node <node_name> -adapter <adapter_name> -mode cna
----
. 노드를 재부팅합니다
. 올바른 SFP+가 설치되었는지 확인합니다.
+
CNA의 경우 10Gb 이더넷 SFP를 사용해야 합니다.



--
====