---
sidebar: sidebar 
permalink: networking/create_a_dns_load_balancing_zone.html 
keywords: create, creation, creating, add, adding, dns, naming, name, service, load, balancing, balance, zone, lif, create a dns load balancing zone, improve lif performance 
summary: DNS 로드 밸런싱 영역을 생성하여 LIF 성능을 개선합니다 
---
= DNS 부하 분산 영역을 만듭니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
DNS 로드 밸런싱 영역을 생성하여 LIF에 마운트된 클라이언트 수, 즉 로드를 기반으로 LIF를 동적으로 선택할 수 있습니다. 데이터 LIF를 생성하는 동안 로드 밸런싱 존을 생성할 수 있습니다.

.시작하기 전에
로드 밸런싱 존에 대한 모든 요청을 구성된 LIF로 전달하도록 사이트 전체 DNS 서버의 DNS 전달자를 구성해야 합니다.

기술 자료 문서 link:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/How_to_set_up_DNS_load_balancing_in_clustered_Data_ONTAP["Cluster-Mode에서 DNS 로드 밸런싱을 설정하는 방법"^] 조건부 전달을 사용하여 DNS 로드 밸런싱을 구성하는 방법에 대한 자세한 내용은 NetApp Support 사이트 를 참조하십시오.

.이 작업에 대해
* 모든 데이터 LIF는 DNS 로드 밸런싱 존 이름에 대한 DNS 쿼리에 응답할 수 있습니다.
* DNS 로드 밸런싱 존은 클러스터에서 고유한 이름을 가져야 하며 영역 이름은 다음 요구 사항을 충족해야 합니다.
+
** 256자를 초과하면 안 됩니다.
** 최소 하나의 기간을 포함해야 합니다.
** 첫 번째 문자와 마지막 문자는 마침표 또는 기타 특수 문자여야 합니다.
** 문자 사이에 공백을 포함할 수 없습니다.
** DNS 이름의 각 레이블은 63자를 초과할 수 없습니다.
+
레이블은 기간 전후에 나타나는 텍스트입니다. 예를 들어 storage.company.com 이라는 DNS 영역에는 세 개의 레이블이 있습니다.





.단계
DNS load balancing zone을 생성하려면 dns-zone 옵션과 함께 network interface create 명령을 사용한다.

로드 밸런싱 영역이 이미 존재하는 경우 LIF가 이 영역에 추가됩니다. 명령에 대한 자세한 내용은 를 참조하십시오 link:http://docs.netapp.com/us-en/ontap-cli["ONTAP 9 명령 참조"^].

다음 예제에서는 LIF 'lif1'을 생성하는 동안 storage.company.com 이라는 DNS 로드 밸런싱 존을 생성하는 방법을 보여 줍니다.

....
network interface create -vserver vs0 -lif lif1 -home-node node1
-home-port e0c -address 192.0.2.129 -netmask 255.255.255.128 -dns-zone storage.company.com
....