---
sidebar: sidebar 
permalink: networking/create_lifs.html 
keywords: create, creation, creating, add, adding, lifs, logical, interface, create lifs 
summary: 클라이언트에 SVM 데이터를 제공할 LIF를 생성합니다 
---
= LIF를 생성합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
SVM은 하나 이상의 네트워크 논리 인터페이스(LIF)를 통해 클라이언트에 데이터를 제공합니다. 데이터에 액세스하는 데 사용할 포트에 LIF를 생성해야 합니다.

.시작하기 전에
이 작업을 수행하려면 클러스터 관리자여야 합니다.

.이 작업에 대해
ONTAP 9.7부터 ONTAP는 해당 IPspace의 동일한 서브넷에 이미 있는 LIF가 하나 이상 있으면 LIF의 홈 포트를 자동으로 선택합니다. ONTAP은 해당 서브넷에 있는 다른 LIF와 동일한 브로드캐스트 도메인에서 홈 포트를 선택합니다. 홈 포트는 여전히 지정할 수 있지만 더 이상 필요하지 않습니다(지정된 IPspace의 해당 서브넷에 LIF가 아직 없는 경우).

SMB 트래픽이 있는 LIF가 홈 노드로 자동 복구되도록 구성하지 않아야 합니다. SMB를 통해 Hyper-V 또는 SQL Server의 무중단 운영을 지원하는 솔루션을 호스팅하려는 SMB 서버의 경우 이 권장 사항이 필수입니다.

.단계
. LIF에 사용할 브로드캐스트 도메인 포트를 결정합니다.
+
'네트워크 포트 브로드캐스트-도메인 쇼-IPSpace_ipspace1_'

+
....
IPspace     Broadcast                       Update
Name        Domain name   MTU   Port List   Status Details
ipspace1
            default       1500
                                node1:e0d   complete
                                node1:e0e   complete
                                node2:e0d   complete
                                node2:e0e   complete
....
. LIF에 사용할 서브넷에 사용되지 않는 IP 주소가 충분히 있는지 확인합니다.
+
'network subnet show - IPSpace_ipspace1_'

. 데이터에 액세스하는 데 사용할 포트에 하나 이상의 LIF를 생성합니다.
+
"네트워크 인터페이스 create-vserver_vs1_-lif_lif1_-home-node_node1_-home-port_e0d_-service-policy_default-data-files_-subnet-name_ipspace1_"

. LIF 인터페이스 구성이 올바른지 확인합니다.
+
네트워크 인터페이스 show-vserver vs1

+
....
          Logical    Status     Network         Current   Current Is
Vserver   Interface  Admin/Oper Address/Mask    Node      Port    Home
--------- ---------- ---------- --------------- --------- ------- ----
vs1
           lif1       up/up      10.0.0.128/24   node1     e0d     true
....
. 페일오버 그룹 구성이 원하는 대로 되어 있는지 확인합니다.
+
'network interface show-failover-vserver_vs1_'

+
....
         Logical    Home       Failover        Failover
Vserver  interface  Node:Port  Policy          Group
-------- ---------- ---------  ---------       --------
vs1
         lif1       node1:e0d  system-defined  ipspace1
Failover Targets: node1:e0d, node1:e0e, node2:e0d, node2:e0e
....

