---
sidebar: sidebar 
permalink: networking/determine_which_ports_can_be_used_for_a_broadcast_domains.html 
keywords: move, moving, broadcast, domain, ipspace, determining which ports can be used for a broadcast domain, before you can configure a broadcast domain to add to the new ipspace, you must determine what ports are available for the broadcast domain 
summary: 새 IPspace에 추가할 브로드캐스트 도메인을 구성하려면 먼저 브로드캐스트 도메인에 사용할 수 있는 포트를 결정해야 합니다 
---
= 브로드캐스트 도메인에 사용할 수 있는 포트 결정
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
새 IPspace에 추가할 브로드캐스트 도메인을 구성하려면 먼저 브로드캐스트 도메인에 사용할 수 있는 포트를 결정해야 합니다.


NOTE: 이 작업은 ONTAP 9.8이 아닌 ONTAP 9.0-9.7에 적합합니다.

이 작업을 수행하려면 클러스터 관리자여야 합니다.

.이 작업에 대해
* 포트는 물리적 포트, VLAN 또는 인터페이스 그룹(ifgroup)일 수 있습니다.
* 새 브로드캐스트 도메인에 추가할 포트는 기존 브로드캐스트 도메인에 할당할 수 없습니다.
* 브로드캐스트 도메인에 추가할 포트가 이미 다른 브로드캐스트 도메인에 있는 경우(예: 기본 IPspace의 기본 브로드캐스트 도메인) 새 브로드캐스트 도메인에 포트를 할당하기 전에 해당 브로드캐스트 도메인에서 포트를 제거해야 합니다.
* LIF가 할당된 포트는 브로드캐스트 도메인에서 제거할 수 없습니다.
* 클러스터 관리 및 노드 관리 LIF가 기본 IPspace의 기본 브로드캐스트 도메인에 할당되기 때문에 이러한 LIF에 할당된 포트를 기본 브로드캐스트 도메인에서 제거할 수 없습니다.


.단계
. 현재 포트 할당을 확인합니다.
+
네트워크 포트 쇼

+
[listing]
----
Node   Port IPspace  Broadcast Domain Link   MTU  Admin/Oper
------ ---- -------  ---------------- ----- ----  ------------
node1
       e0a  Cluster  Cluster          up    9000  auto/1000
       e0b  Cluster  Cluster          up    9000  auto/1000
       e0c  Default  Default          up    1500  auto/1000
       e0d  Default  Default          up    1500  auto/1000
       e0e  Default  Default          up    1500  auto/1000
       e0f  Default  Default          up    1500  auto/1000
       e0g  Default  Default          up    1500  auto/1000
node2
       e0a  Cluster  Cluster          up    9000  auto/1000
       e0b  Cluster  Cluster          up    9000  auto/1000
       e0c  Default  Default          up    1500  auto/1000
       e0d  Default  Default          up    1500  auto/1000
       e0e  Default  Default          up    1500  auto/1000
       e0f  Default  Default          up    1500  auto/1000
       e0g  Default  Default          up    1500  auto/1000
----
+
이 예제에서 명령의 출력은 다음 정보를 제공합니다.

+
** 각 노드의 포트 e0c e0d e0e e0e e0f e0g e0g 등이 Default broadcast domain에 할당된다.
** 이러한 포트는 생성하려는 IPspace의 브로드캐스트 도메인에서 사용할 수 있습니다.


. 기본 브로드캐스트 도메인의 포트가 LIF 인터페이스에 할당되므로 새 브로드캐스트 도메인으로 이동할 수 없습니다.
+
네트워크 인터페이스 쇼

+
[listing]
----
         Logical      Status     Network         Current   Current Is
Vserver  Interface    Admin/Oper Address/Mask    Node      Port    Home
-------  ----------   ---------- ------------   --------- -------  ----
Cluster
         node1_clus1  up/up       10.0.2.40/24   node1     e0a     true
         node1_clus2  up/up       10.0.2.41/24   node1     e0b     true
         node2_clus1  up/up       10.0.2.42/24   node2     e0a     true
         node2_clus2  up/up       10.0.2.43/24   node2     e0b     true

cluster1
         cluster_mgmt up/up       10.0.1.41/24   node1     e0c     true
         node1_mgmt   up/up       10.0.1.42/24   node1     e0c     true
         node2_mgmt   up/up       10.0.1.43/24   node2     e0c     true
----
+
다음 예제에서 명령의 출력은 다음 정보를 제공합니다.

+
** 노드 포트는 각 노드의 포트 e0c에 할당되고 클러스터 관리 LIF의 홈 노드는 노드1의 포트 e0c에 있습니다.
** 각 노드의 포트 e0d, e0e, e0f, e0g 등이 LIF를 호스팅하지 않고 기본 브로드캐스트 도메인에서 제거한 다음 새 IPspace용 새 브로드캐스트 도메인에 추가할 수 있습니다.



