---
sidebar: sidebar 
permalink: networking/display_lifs_in_a_load_balancing_zone.html 
keywords: display, view, show, lif, logical, interface, load, balancing, zone, balance, performance, display lifs in a load balancing zone, verify whether a load balancing zone is configured correctly by displaying all of the lifs that belong to it, examples of displaying load balancing zones for lifs 
summary: 로드 밸런싱 존에 속하는 모든 LIF를 표시하여 로드 밸런싱 존이 올바르게 구성되었는지 확인합니다 
---
= 로드 밸런싱 영역에 LIF를 표시합니다
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
로드 밸런싱 영역이 올바르게 구성되었는지 확인하려면 해당 LIF에 속하는 모든 LIF를 표시할 수 있습니다. 또한 특정 LIF의 로드 밸런싱 존 또는 모든 LIF의 로드 밸런싱 존(Zone)을 볼 수도 있습니다.

다음 명령 중 하나를 사용하여 원하는 LIF 및 로드 밸런싱 세부 정보를 표시합니다

[cols="30,70"]
|===


| 표시 방법 | 입력... 


 a| 
특정 로드 밸런싱 구역에 있는 LIF입니다
 a| 
네트워크 인터페이스 show-dns-zone zone zone_name

zone_name은 load balancing zone의 이름을 지정한다.



 a| 
특정 LIF의 로드 밸런싱 존
 a| 
네트워크 인터페이스 show-lif lif_name-fields DNS-zone



 a| 
모든 LIF의 로드 밸런싱 존
 a| 
네트워크 인터페이스 보기 필드 DNS-존

|===


== LIF의 로드 밸런싱 존 표시 예

다음 명령을 실행하면 SVM vs0에 대한 로드 밸런싱 존 storage.company.com 에 있는 모든 LIF의 세부 정보가 표시됩니다.

....
net int show -vserver vs0 -dns-zone storage.company.com

         Logical    Status     Network           Current   Current Is
Vserver  Interface  Admin/Oper Address/Mask      Node      Port    Home
-------- ---------- ---------- ----------------- --------- ------- ----
vs0
         lif3         up/up    10.98.226.225/20  ndeux-11  e0c     true
         lif4         up/up    10.98.224.23/20   ndeux-21  e0c     true
         lif5         up/up    10.98.239.65/20   ndeux-11  e0c     true
         lif6         up/up    10.98.239.66/20   ndeux-11  e0c     true
         lif7         up/up    10.98.239.63/20   ndeux-21  e0c     true
         lif8         up/up    10.98.239.64/20   ndeux-21  e0c     true
....
다음 명령을 실행하면 LIF 데이터의 DNS 존 세부 정보가 표시됩니다.3

....
network interface show -lif data3 -fields dns-zone
Vserver  lif    dns-zone
-------  -----  --------
vs0      data3  storage.company.com
....
다음 명령을 실행하면 클러스터에 있는 모든 LIF와 해당 DNS 존 목록이 표시됩니다.

....
network interface show -fields dns-zone
Vserver   lif          dns-zone
-------   ------------ --------
cluster   cluster_mgmt none
ndeux-21  clus1        none
ndeux-21  clus2        none
ndeux-21  mgmt1        none
vs0       data1        storage.company.com
vs0       data2        storage.company.com
....