---
sidebar: sidebar 
permalink: networking/display_network_port_information_@cluster_administrators_only@.html 
keywords: 'display, view, show, network, port, information, display network port information (cluster administrators only), view information about a specific port, or about all ports on all nodes in the cluster, network port show' 
summary: 특정 포트에 대한 정보 또는 클러스터의 모든 노드에 있는 모든 포트에 대한 정보를 봅니다 
---
= 네트워크 포트 정보를 표시합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
클러스터의 모든 노드에 있는 특정 포트 또는 모든 포트에 대한 정보를 표시할 수 있습니다.

.이 작업에 대해
다음 정보가 표시됩니다.

* 노드 이름
* 포트 이름입니다
* IPspace 이름입니다
* 브로드캐스트 도메인 이름
* 링크 상태(위 또는 아래)
* MTU 설정
* 포트 속도 설정 및 작동 상태(초당 1기가비트 또는 10기가비트)
* 자동 협상 설정(참 또는 거짓)
* 이중 모드 및 작동 상태(반이중 또는 전이중)
* 해당되는 경우 포트의 인터페이스 그룹입니다
* 해당되는 경우 포트의 VLAN 태그 정보입니다
* 포트의 상태(상태 또는 성능 저하)
* 포트가 성능 저하로 표시된 이유


필드에 대한 데이터를 사용할 수 없는 경우(예: 비활성 포트에 대한 작동 이중화 및 속도를 사용할 수 없음) 필드 값이 로 표시됩니다 `-`.

.단계
network port show 명령을 사용하여 네트워크 포트 정보를 표시합니다.

instance 매개변수를 지정하여 각 포트에 대한 상세 정보를 표시하거나 '-fields' 매개변수를 사용하여 필드 이름을 지정하여 특정 정보를 가져올 수 있습니다.

....
network port show
Node: node1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/1000  healthy  false
e0b       Cluster      Cluster          up   9000  auto/1000  healthy  false
e0c       Default      Default          up   1500  auto/1000  degraded false
e0d       Default      Default          up   1500  auto/1000  degraded true
Node: node2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/1000  healthy  false
e0b       Cluster      Cluster          up   9000  auto/1000  healthy  false
e0c       Default      Default          up   1500  auto/1000  healthy  false
e0d       Default      Default          up   1500  auto/1000  healthy  false
8 entries were displayed.
....