---
sidebar: sidebar 
permalink: networking/display_routing_information.html 
keywords: display, view, show, route, svm, storage, virtual, machine, display routing information, view information about the routing configuration for each svm on your cluster, network route show, network route show-lifs, network route active-entry show 
summary: 클러스터의 각 SVM에 대한 라우팅 구성 정보를 봅니다 
---
= 라우팅 정보를 표시합니다
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
클러스터의 각 SVM에 대한 라우팅 구성 정보를 표시할 수 있습니다. 이를 통해 클라이언트 애플리케이션 또는 서비스 간 연결 문제와 클러스터의 노드 LIF 간 연결 문제를 진단할 수 있습니다.

.단계
. "network route show" 명령을 사용하여 하나 이상의 SVM 내에 경로를 표시합니다. 다음 예는 vs0 SVM에 구성된 경로를 보여줍니다.
+
....
network route show
  (network route show)
Vserver             Destination     Gateway         Metric
------------------- --------------- --------------- ------
vs0
                    0.0.0.0/0       172.17.178.1    20
....
. "network route show -lifs" 명령을 사용하여 하나 이상의 SVM 내에 있는 경로 및 LIF의 연결을 표시합니다.
+
다음 예에서는 vs0 SVM이 소유하는 라우트가 있는 LIF를 보여 줍니다.

+
....
network route show-lifs
  (network route show-lifs)

Vserver: vs0
Destination             Gateway                 Logical Interfaces
----------------------  --------------          --------------------
0.0.0.0/0               172.17.178.1            cluster_mgmt,
                                                LIF-b-01_mgmt1,
                                                LIF-b-02_mgmt1
....
. "network route active-entry show" 명령을 사용하여 하나 이상의 노드, SVM, 서브넷 또는 지정된 목적지를 가진 경로에 설치된 경로를 표시할 수 있습니다.
+
다음 예는 특정 SVM에 설치된 모든 경로를 보여줍니다.

+
....
network route active-entry show -vserver Data0

Vserver: Data0
Node: node-1
Subnet Group: 0.0.0.0/0
Destination             Gateway              Interface   Metric  Flags
----------------------  -------------------  ---------   ------  -----
127.0.0.1               127.0.0.1            lo              10  UHS
127.0.10.1              127.0.20.1           losk            10  UHS
127.0.20.1              127.0.20.1           losk            10  UHS

Vserver: Data0
Node: node-1
Subnet Group: fd20:8b1e:b255:814e::/64
Destination             Gateway              Interface   Metric  Flags
----------------------  -------------------  ---------   ------  -----
default                 fd20:8b1e:b255:814e::1
                                             e0d             20  UGS
fd20:8b1e:b255:814e::/64
                        link#4               e0d              0  UC

Vserver: Data0
Node: node-2
Subnet Group: 0.0.0.0/0
Destination             Gateway              Interface   Metric  Flags
----------------------  -------------------  ---------   ------  -----
127.0.0.1               127.0.0.1            lo              10  UHS

Vserver: Data0
Node: node-2
Subnet Group: 0.0.0.0/0
Destination             Gateway              Interface   Metric  Flags
----------------------  -------------------  ---------   ------  -----
127.0.10.1              127.0.20.1           losk            10  UHS
127.0.20.1              127.0.20.1           losk            10  UHS

Vserver: Data0
Node: node-2
Subnet Group: fd20:8b1e:b255:814e::/64
Destination             Gateway              Interface   Metric  Flags
----------------------  -------------------  ---------   ------  -----
default                 fd20:8b1e:b255:814e::1
                                             e0d             20  UGS
fd20:8b1e:b255:814e::/64
                        link#4               e0d              0  UC
fd20:8b1e:b255:814e::1  link#4               e0d              0  UHL
11 entries were displayed.
....

