---
sidebar: sidebar 
permalink: networking/display_network_connectivity_with_neighbor_discovery_protocols.html 
keywords: display, view, show, network, connectivity, neighbor, discovery, protocol, ndp, cdp, cisco, link, layer, lldp, display network connectivity with neighbor discovery protocols, use neighbor discovery protocols to view network connectivity between a pair of physical or virtual systems and their network interfaces, use cdp to detect network connectivity, considerations for using cdp, enable or disable cdp, view cdp neighbor information, example of showing and clearing statistics, use lldp to detect network connectivity, enable or disable lldp, view lldp neighbor information, adjust the interval for transmitting lldp advertisements 
summary: 인접 검색 프로토콜을 사용하여 물리적 또는 가상 시스템 쌍과 해당 네트워크 인터페이스 간의 네트워크 연결을 볼 수 있습니다 
---
= 인접 검색 프로토콜과의 네트워크 연결을 표시합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
데이터 센터에서 인접 검색 프로토콜을 사용하여 물리적 또는 가상 시스템 쌍과 해당 네트워크 인터페이스 간의 네트워크 연결을 볼 수 있습니다. ONTAP는 CDP(Cisco Discovery Protocol) 및 LLDP(Link Layer Discovery Protocol)라는 두 개의 인접 검색 프로토콜을 지원합니다.

인접 검색 프로토콜을 사용하면 네트워크에서 직접 연결된 프로토콜 지원 장치에 대한 정보를 자동으로 검색하고 볼 수 있습니다. 각 장치는 ID, 용량 및 연결 정보를 네트워크에 알립니다. 이 정보는 이더넷 프레임에서 멀티캐스트 MAC 주소로 전송되며, 인접한 모든 프로토콜 지원 장치에서 수신됩니다.

두 개의 장치가 이웃이 되려면 각각 프로토콜이 활성화되어 있고 올바르게 구성되어 있어야 합니다. 검색 프로토콜 기능은 직접 연결된 네트워크로 제한됩니다. 이웃에는 스위치, 라우터, 브리지 등과 같은 프로토콜 지원 장치가 포함될 수 있습니다. ONTAP는 개별적으로 또는 함께 사용할 수 있는 두 개의 인접 검색 프로토콜을 지원합니다.

* CDP(Cisco Discovery Protocol) *

CDP는 Cisco Systems에서 개발한 독점 링크 계층 프로토콜입니다. 이 기능은 클러스터 포트에 대해 ONTAP에서 기본적으로 활성화되지만 데이터 포트에 대해 명시적으로 설정해야 합니다.

LLDP(Link Layer Discovery Protocol) *

LLDP는 표준 문서 IEEE 802.1AB에 지정된 공급업체 중립적인 프로토콜입니다. 모든 포트에 대해 명시적으로 활성화해야 합니다.



== CDP를 사용하여 네트워크 연결을 감지합니다

CDP를 사용하여 네트워크 연결을 감지하는 것은 배포 고려 사항 검토, 데이터 포트에서 활성화, 인접 장치 보기 및 필요에 따라 CDP 구성 값 조정으로 구성됩니다. CDP는 클러스터 포트에서 기본적으로 사용하도록 설정됩니다.

인접 장치에 대한 정보를 표시하려면 모든 스위치 및 라우터에서 CDP를 사용하도록 설정해야 합니다.

CDP는 클러스터 스위치 상태 모니터에서 클러스터 및 관리 네트워크 스위치를 자동으로 검색하는 데 사용됩니다.

link:../system-admin/index.html["시스템 관리"^]



=== CDP 사용 시 고려 사항

기본적으로 CDP 호환 장치는 CDPv2 광고를 보냅니다. CDP 호환 장치는 CDPv1 광고를 수신할 때만 CDPv1 광고를 보냅니다. ONTAP는 CDPv1만 지원합니다. 따라서 ONTAP 노드가 CDPv1 광고를 전송할 때 CDP 호환 인접 장치는 CDPv1 광고를 다시 보냅니다.

노드에서 CDP를 사용하도록 설정하기 전에 다음 정보를 고려해야 합니다.

* CDP는 클러스터 포트에서 항상 사용하도록 설정됩니다.
* CDP는 기본적으로 모든 비클러스터 포트에서 사용할 수 없습니다.
* CDP는 모든 포트에서 지원됩니다.
* CDP 광고는 UP 상태인 포트를 통해 송수신합니다.
* CDP 광고를 보내고 받으려면 전송 및 수신 장치 모두에서 CDP를 사용하도록 설정해야 합니다.
* CDP 광고는 일정한 간격으로 전송되며 시간 간격을 구성할 수 있습니다.
* LIF의 IP 주소가 변경되면 노드는 다음 CDP 광고에서 업데이트된 정보를 보냅니다.



NOTE: 노드에서 LIF가 변경되는 경우 CDP 정보는 수신 디바이스 측(예: 스위치)에서 업데이트되지 않는 경우가 있습니다. 이러한 문제가 발생하는 경우 노드의 네트워크 인터페이스를 DOWN 상태로 구성한 다음 UP 상태로 구성해야 합니다.

* CDP 광고에서는 IPv4 주소만 보급됩니다.
* VLAN이 있는 물리적 네트워크 포트의 경우 해당 포트의 VLAN에 구성된 모든 LIF가 보급됩니다.
* 인터페이스 그룹에 속한 물리적 포트의 경우 해당 인터페이스 그룹에 구성된 모든 IP 주소가 각 물리적 포트에 공고됩니다.
* VLAN을 호스팅하는 인터페이스 그룹의 경우 인터페이스 그룹과 VLAN에 구성된 모든 LIF가 각 네트워크 포트에 공고됩니다.
* MTU 크기가 1,500바이트 이상인 패킷의 경우, 1500 MTU 크기 패킷에 들어갈 수 있는 LIF 수만 광고됩니다.




=== CDP를 사용하거나 사용하지 않도록 설정합니다

CDP를 준수하는 인접 장치를 검색하고 알림을 보내려면 클러스터의 각 노드에서 CDP를 사용하도록 설정해야 합니다. 기본적으로 CDP는 노드의 모든 클러스터 포트에서 활성화되고 노드의 클러스터가 아닌 모든 포트에서 비활성화됩니다.

CDPD.ENABLE 옵션은 노드 포트에서 CDP가 활성화 또는 비활성화되는지 여부를 제어합니다.

* On은 비 클러스터 포트에서 CDP를 사용하도록 설정합니다.
* Off 클러스터 포트가 아닌 경우 CDP를 사용하지 않도록 설정하고, 클러스터 포트에서 CDP를 사용하지 않도록 설정할 수는 없습니다.


CDP 호환 장치에 연결된 포트에서 CDP가 비활성화되어 있으면 네트워크 트래픽이 최적화되지 않을 수 있습니다.

.단계
. 노드 또는 클러스터의 모든 노드에 대한 현재 CDP 설정을 표시합니다.
+
[cols="30,70"]
|===


| CDP 설정을 보려면... | 입력... 


 a| 
노드
 a| 
'run-node <node_name> options CDPD.enable'



 a| 
클러스터의 모든 노드
 a| 
옵션 CDPD.ENABLE

|===
. 노드의 모든 포트 또는 클러스터의 모든 노드 포트에서 CDP를 사용하거나 사용하지 않도록 설정:
+
[cols="30,70"]
|===


| 에서 CDP를 활성화 또는 비활성화하려면... | 입력... 


 a| 
노드
 a| 
'run-node node_name options CDPD.enable{on or off}'



 a| 
클러스터의 모든 노드
 a| 
'options CDPD.enable{on or off}'

|===




=== CDP 인접 항목 정보를 봅니다

포트가 CDP 호환 장치에 연결되어 있는 경우, 클러스터 노드의 각 포트에 연결된 인접 장치에 대한 정보를 볼 수 있습니다. Network device-discovery show-protocol CDP 명령어를 이용하여 네이버 정보를 볼 수 있다.

클러스터 포트에 대해 CDP가 항상 사용하도록 설정되므로 해당 포트에 대해 CDP 인접 항목 정보가 항상 표시됩니다. 해당 포트에 대한 인접 정보가 표시되도록 비 클러스터 포트에서 CDP를 사용하도록 설정해야 합니다.

클러스터의 노드의 포트에 연결된 모든 CDP 호환 디바이스에 대한 정보를 표시합니다.

....
network device-discovery show -node node -protocol cdp
....
다음 명령을 실행하면 노드 cluster-1_01의 포트에 연결된 인접 항목이 표시됩니다.

....
network device-discovery show -node sti2650-212 -protocol cdp
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
sti2650-212/cdp
            e0M    RTP-LF810-510K37.gdl.eng.netapp.com(SAL1942R8JS)
                                             Ethernet1/14      N9K-C93120TX
            e0a    CS:RTP-CS01-510K35        0/8               CN1610
            e0b    CS:RTP-CS01-510K36        0/8               CN1610
            e0c    RTP-LF350-510K34.gdl.eng.netapp.com(FDO21521S76)
                                             Ethernet1/21      N9K-C93180YC-FX
            e0d    RTP-LF349-510K33.gdl.eng.netapp.com(FDO21521S4T)
                                             Ethernet1/22      N9K-C93180YC-FX
            e0e    RTP-LF349-510K33.gdl.eng.netapp.com(FDO21521S4T)
                                             Ethernet1/23      N9K-C93180YC-FX
            e0f    RTP-LF349-510K33.gdl.eng.netapp.com(FDO21521S4T)
                                             Ethernet1/24      N9K-C93180YC-FX
....
출력에는 지정된 노드의 각 포트에 연결된 Cisco 장치가 나열됩니다.



=== CDP 메시지의 보류 시간을 구성합니다

보류 시간은 CDP 광고가 인접한 CDP 준수 장치의 캐시에 저장되는 기간입니다. 보류 시간은 각 CDPv1 패킷에 공고되며 노드에서 CDPv1 패킷을 수신할 때마다 업데이트됩니다.

* 'CDPD.HoldTime' 옵션의 값은 HA 쌍의 양쪽 노드에서 동일한 값으로 설정해야 합니다.
* 기본 유지 시간 값은 180초이지만 10초에서 255초 사이의 값을 입력할 수 있습니다.
* 보류 시간이 만료되기 전에 IP 주소를 제거하면 보류 시간이 만료될 때까지 CDP 정보가 캐싱됩니다.


.단계
. 노드 또는 클러스터의 모든 노드에 대한 현재 CDP 보류 시간을 표시합니다.
+
[cols="30,70"]
|===


| 보류 시간을 보려면... | 입력... 


 a| 
노드
 a| 
'run-node node_name options CDPD.HoldTime'



 a| 
클러스터의 모든 노드
 a| 
옵션 CDPD.HoldTime

|===
. 클러스터의 모든 포트 또는 클러스터의 모든 노드에 있는 모든 포트에 대해 CDP 보류 시간을 구성합니다.
+
[cols="30,70"]
|===


| 보류 시간을 설정하려면... | 입력... 


 a| 
노드
 a| 
'run-node node_name options CDPD.HoldTime HoldTime'



 a| 
클러스터의 모든 노드
 a| 
옵션 CDPD.HoldTime HoldTime

|===




=== CDP 광고 전송 간격을 설정합니다

CDP 광고는 CDP 이웃에게 정기적으로 전송됩니다. 네트워크 트래픽과 네트워크 토폴로지의 변경 내용에 따라 CDP 광고 전송 간격을 늘리거나 줄일 수 있습니다.

* "cdpd.interval` 옵션 값은 HA 쌍의 두 노드에서 같은 값으로 설정해야 합니다.
* 기본 간격은 60초이지만 5초에서 900초 사이의 값을 입력할 수 있습니다.


.단계
. 노드 또는 클러스터의 모든 노드에 대한 현재 CDP 광고 시간 간격을 표시합니다.
+
[cols="30,70"]
|===


| 간격을 보려면... | 입력... 


 a| 
노드
 a| 
'run-node node_name options cdpd.interval`



 a| 
클러스터의 모든 노드
 a| 
옵션 cdpd.interval`

|===
. 노드의 모든 포트 또는 클러스터의 모든 노드 포트에 대해 CDP 알림을 보내는 간격을 구성합니다.
+
[cols="30,70"]
|===


| 간격을 설정하려면... | 입력... 


 a| 
노드
 a| 
'run-node node_name options cdpd.interval interval



 a| 
클러스터의 모든 노드
 a| 
옵션 cdpd.interval 간격

|===




=== CDP 통계를 보거나 지웁니다

각 노드의 클러스터 및 비클러스터 포트에 대한 CDP 통계를 보고 잠재적인 네트워크 연결 문제를 감지할 수 있습니다. CDP 통계는 마지막 삭제 시점으로부터 누적됩니다.

CDP는 클러스터 포트에 대해 항상 설정되어 있으므로 해당 포트의 트래픽에 대해 CDP 통계가 항상 표시됩니다. 해당 포트에 대한 통계가 표시되도록 비 클러스터 포트에서 CDP를 사용하도록 설정해야 합니다.

노드의 모든 포트에 대한 현재 CDP 통계를 표시하거나 지웁니다.

[cols="30,70"]
|===


| 원하는 작업 | 입력... 


 a| 
CDP 통계를 봅니다
 a| 
'run-node_name CDPD show-stats'



 a| 
CDP 통계를 지웁니다
 a| 
'run-node_name CDPD zero-stats'

|===


==== 통계 표시 및 지우기 예

다음 명령을 실행하면 CDP 통계가 지워지기 전에 표시됩니다. 마지막 통계 삭제 이후 송수신된 총 패킷 수가 출력에 표시됩니다.

....
run -node node1 cdpd show-stats

RECEIVE
 Packets:         9116  | Csum Errors:       0  | Unsupported Vers:  4561
 Invalid length:     0  | Malformed:         0  | Mem alloc fails:      0
 Missing TLVs:       0  | Cache overflow:    0  | Other errors:         0

TRANSMIT
 Packets:         4557  | Xmit fails:        0  | No hostname:          0
 Packet truncated:   0  | Mem alloc fails:   0  | Other errors:         0

OTHER
 Init failures:      0
....
다음 명령을 실행하면 CDP 통계가 지워집니다.

....
run -node node1 cdpd zero-stats
....
....
run -node node1 cdpd show-stats

RECEIVE
 Packets:            0  | Csum Errors:       0  | Unsupported Vers:     0
 Invalid length:     0  | Malformed:         0  | Mem alloc fails:      0
 Missing TLVs:       0  | Cache overflow:    0  | Other errors:         0

TRANSMIT
 Packets:            0  | Xmit fails:        0  | No hostname:          0
 Packet truncated:   0  | Mem alloc fails:   0  | Other errors:         0

OTHER
 Init failures:      0
....
통계를 지운 후에는 다음 CDP 보급 알림이 전송되거나 수신된 후에 누적되기 시작합니다.



== LLDP를 사용하여 네트워크 연결을 감지합니다

LLDP를 사용하여 네트워크 연결을 탐지하는 작업은 배포 고려 사항을 검토하고, 모든 포트에서 활성화하고, 인접 장치를 보고, 필요에 따라 LLDP 구성 값을 조정하는 것으로 구성됩니다.

인접 장치에 대한 정보를 표시하려면 모든 스위치 및 라우터에서 LLDP를 활성화해야 합니다.

ONTAP는 현재 다음과 같은 TLV(type-length-value structures)를 보고합니다.

* 섀시 ID입니다
* 포트 ID입니다
* TTL(Time-to-Live)
* 시스템 이름입니다
+
시스템 이름 TLV는 CNA 장치에서 전송되지 않습니다.



X1143 어댑터 및 UTA2 온보드 포트와 같은 특정 통합 네트워크 어댑터(CNA)에는 LLDP에 대한 오프로드 지원 기능이 포함되어 있습니다.

* LLDP 오프로드는 DCB(데이터 센터 브리징)에 사용됩니다.
* 표시된 정보는 클러스터와 스위치 간에 다를 수 있습니다.
+
예를 들어, 스위치에 표시되는 섀시 ID 및 포트 ID 데이터는 CNA 및 비 CNA 포트에 대해 다를 수 있지만, 클러스터에서 표시하는 데이터는 이러한 포트 유형에 대해 일관적입니다.




NOTE: LLDP 사양은 SNMP MIB를 통해 수집된 정보에 대한 액세스를 정의합니다. 그러나 ONTAP는 현재 LLDP MIB를 지원하지 않습니다.



=== LLDP를 활성화 또는 비활성화합니다

LLDP 호환 인접 장치를 검색하고 보급을 보내려면 클러스터의 각 노드에서 LLDP를 활성화해야 합니다. ONTAP 9.7부터 LLDP는 기본적으로 노드의 모든 포트에서 활성화됩니다.

Ll DP.enable 옵션은 노드의 포트에서 LLDP가 활성화 또는 비활성화되는지 여부를 제어합니다.

* On은 모든 포트에서 LLDP를 활성화합니다.
* OFF는 모든 포트에서 LLDP를 비활성화합니다.


.단계
. 노드 또는 클러스터의 모든 노드에 대한 현재 LLDP 설정을 표시합니다.
+
** 단일 노드: 'run-node_name options lldp.enable'
** 모든 노드: 옵션 ll dp.enable


. 노드의 모든 포트 또는 클러스터의 모든 노드 포트에서 LLDP를 사용하거나 사용하지 않도록 설정합니다.
+
[cols="30,70"]
|===


| 에서 LLDP를 활성화 또는 비활성화하려면... | 입력... 


 a| 
노드
 a| 
'run-node node_name options lldp.enable{on|off}'



 a| 
클러스터의 모든 노드
 a| 
'options lldp.enable{on|off}'

|===
+
** 단일 노드:
+
....
run -node node_name options lldp.enable {on|off}
....
** 모든 노드:
+
....
options lldp.enable {on|off}
....






=== LLDP 인접 정보를 봅니다

포트가 LLDP 호환 장치에 연결되어 있는 경우, 클러스터 노드의 각 포트에 연결된 인접 장치에 대한 정보를 볼 수 있습니다. network device-discovery show 명령을 사용하여 인접 항목 정보를 볼 수 있습니다.

.단계
. 클러스터의 노드의 포트에 연결된 모든 LLDP 호환 장치에 대한 정보를 표시합니다.
+
....
network device-discovery show -node node -protocol lldp
....
+
다음 명령을 실행하면 노드 클러스터-1_01의 포트에 연결된 인접 항목이 표시됩니다. 출력에는 지정된 노드의 각 포트에 연결된 LLDP 지원 디바이스가 나열됩니다. '-protocol' 옵션을 생략하면 출력에 CDP 지원 디바이스도 나열됩니다.

+
....
network device-discovery show -node cluster-1_01 -protocol lldp
Node/       Local  Discovered
Protocol    Port   Device                    Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
cluster-1_01/lldp
            e2a    0013.c31e.5c60            GigabitEthernet1/36
            e2b    0013.c31e.5c60            GigabitEthernet1/35
            e2c    0013.c31e.5c60            GigabitEthernet1/34
            e2d    0013.c31e.5c60            GigabitEthernet1/33
....




=== LLDP 광고 전송 간격을 조정합니다

LLDP 광고는 주기적으로 LLDP 이웃에게 전송됩니다. 네트워크 트래픽과 네트워크 토폴로지의 변경 내용에 따라 LLDP 광고 전송 간격을 늘리거나 줄일 수 있습니다.

IEEE에서 권장하는 기본 간격은 30초이지만 5초에서 300초까지 값을 입력할 수 있습니다.

.단계
. 노드 또는 클러스터의 모든 노드에 대한 현재 LLDP 광고 시간 간격을 표시합니다.
+
** 단일 노드:
+
....
run -node <node_name> options lldp.xmit.interval
....
** 모든 노드:
+
....
options lldp.xmit.interval
....


. 노드의 모든 포트 또는 클러스터의 모든 노드에 대해 LLDP 광고를 전송하는 간격을 조정합니다.
+
** 단일 노드:
+
....
run -node <node_name> options lldp.xmit.interval <interval>
....
** 모든 노드:
+
....
options lldp.xmit.interval <interval>
....






=== LLDP 광고의 실시간 값을 조정합니다

TTL(Time-to-Live)은 인접 LLDP 호환 장치의 캐시에 LLDP 광고가 저장되는 기간입니다. TTL은 각 LLDP 패킷에서 공고되며 LLDP 패킷이 노드에 수신될 때마다 업데이트됩니다. TTL은 나가는 LLDP 프레임에서 수정할 수 있습니다.

.이 작업에 대해
* TTL은 전송 간격(모든 dp.xmit.interval`) 및 보류 승수(모든 dP.xmit.hold)에 1을 더한 계산된 값입니다.
* 기본 보압 승수 값은 4이지만 1에서 100 사이의 값을 입력할 수 있습니다.
* 따라서 기본 TTL은 IEEE에서 권장하는 121초이지만 전송 간격 및 고정 승수 값을 조정하여 발신 프레임의 값을 6초에서 30001초로 지정할 수 있습니다.
* TTL이 만료되기 전에 IP 주소를 제거하면 TTL이 만료될 때까지 LLDP 정보가 캐싱됩니다.


.단계
. 노드 또는 클러스터의 모든 노드에 대한 현재 보류 승수 값을 표시합니다.
+
** 단일 노드:
+
....
run -node <node_name> options lldp.xmit.hold
....
** 모든 노드:
+
....
options lldp.xmit.hold
....


. 노드의 모든 포트 또는 클러스터의 모든 노드 포트에서 고정 승수 값을 조정합니다.
+
** 단일 노드:
+
....
run -node <node_name> options lldp.xmit.hold <hold_value>
....
** 모든 노드:
+
....
options lldp.xmit.hold <hold_value>
....



