---
sidebar: sidebar 
permalink: networking/modify_a_lif.html 
keywords: lif attributes, fc lifs, ip lifs, change lifs, change, changing, logical, interface, lif, modify a lif, modify a lif by changing its attributes 
summary: 특성을 변경하여 LIF를 수정합니다 
---
= LIF를 수정합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
홈 노드 또는 현재 노드, 관리 상태, IP 주소, 넷마스크, 페일오버 정책 등의 특성을 변경하여 LIF를 수정할 수 있습니다. 방화벽 정책 및 서비스 정책을 참조하십시오. LIF의 주소 제품군을 IPv4에서 IPv6로 변경할 수도 있습니다.

.이 작업에 대해
* LIF의 관리 상태를 중지 상태로 수정할 때 LIF의 관리 상태가 위로 돌아갈 때까지 진행 중인 모든 NFSv4 잠금이 유지됩니다.
+
다른 LIF가 잠긴 파일에 액세스하려고 할 때 발생할 수 있는 잠금 충돌을 방지하려면 관리 상태를 낮춤 으로 설정하기 전에 NFSv4 클라이언트를 다른 LIF로 이동해야 합니다.

* FC LIF에서 사용되는 데이터 프로토콜은 수정할 수 없습니다. 하지만 서비스 정책에 할당된 서비스를 수정하거나 IP LIF에 할당된 서비스 정책을 변경할 수 있습니다.
+
FC LIF에서 사용되는 데이터 프로토콜을 수정하려면 LIF를 삭제하고 다시 생성해야 합니다. IP LIF에서 서비스 정책을 변경하기 위해 업데이트를 수행하는 동안 잠시 중단이 발생합니다.

* 노드 범위 관리 LIF의 홈 노드 또는 현재 노드를 수정할 수 없습니다.
* 서브넷을 사용하여 LIF의 IP 주소 및 네트워크 마스크 값을 변경할 경우, IP 주소는 지정된 서브넷에서 할당됩니다. LIF의 이전 IP 주소가 다른 서브넷에 있는 경우 IP 주소는 해당 서브넷으로 반환됩니다.
* LIF의 주소 제품군을 IPv4에서 IPv6로 수정하려면 IPv6 주소에 대한 콜론 표기법을 사용하고 '-netmask-length' 매개 변수에 새 값을 추가해야 합니다.
* 자동 구성된 링크 로컬 IPv6 주소는 수정할 수 없습니다.
* LIF가 수정되어 LIF에 유효한 페일오버 타겟이 없게 되면 경고 메시지가 표시됩니다.
+
유효한 페일오버 목표가 없는 LIF가 페일오버를 시도하면 운영 중단이 발생할 수 있습니다.

* ONTAP 9.5부터 LIF와 연결된 서비스 정책을 수정할 수 있습니다.
+
ONTAP 9.5에서는 서비스 정책이 인터클러스터 및 BGP 피어 서비스에 대해서만 지원됩니다. ONTAP 9.6에서는 여러 데이터 및 관리 서비스에 대한 서비스 정책을 작성할 수 있습니다.

* ONTAP 9.11.1부터 iSCSI LIF 페일오버 기능은 모든 SAN 어레이(ASA) 플랫폼에서 사용할 수 있습니다.
+
기존 iSCSI LIF의 경우, 즉 9.11.1 이상으로 업그레이드하기 전에 생성된 LIF의 경우 페일오버 정책을 수정하여 iSCSI LIF 페일오버 기능을 사용하도록 설정할 수 있습니다.

+
link:../san-admin/asa-iscsi-lif-fo-task.html["ASA 플랫폼의 iSCSI LIF 페일오버"]



.단계
. "network interface modify" 명령을 사용하여 LIF의 특성을 수정합니다.
+
다음 예에서는 서브넷 client1_sub의 IP 주소와 네트워크 마스크 값을 사용하여 LIF datalif2의 IP 주소와 네트워크 마스크를 수정하는 방법을 보여 줍니다.

+
....
network interface modify -vserver vs1 -lif datalif2 -subnet-name client1_sub
....
+
다음 예에서는 LIF의 서비스 정책을 수정하는 방법을 보여 줍니다.

+
....
network interface modify -vserver siteA -lif node1_inter1 -service-policy example
....
. IP 주소에 연결할 수 있는지 확인합니다.
+
|===


| 사용 중인 경우... | 그 다음에... 


 a| 
IPv4 주소
 a| 
네트워크 핑



 a| 
IPv6 주소
 a| 
네트워크 핑6

|===

