---
sidebar: sidebar 
permalink: networking/monitor_the_health_of_network_ports.html 
keywords: monitor, monitoring, manage, managing, automatic, health, port, monitor the health of network ports, automatic health monitoring and a set of health monitors help you identify network ports that might not be suitable for hosting lifs, network options port-health-monitor modify 
summary: 자동 상태 모니터링과 상태 모니터 세트를 사용하면 LIF 호스팅에 적합하지 않을 수 있는 네트워크 포트를 식별할 수 있습니다 
---
= 네트워크 포트의 상태를 모니터링합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ONTAP의 네트워크 포트 관리에는 자동 상태 모니터링 및 LIF 호스팅에 적합하지 않은 네트워크 포트를 식별하는 데 도움이 되는 상태 모니터링 세트가 포함됩니다.

상태 모니터에서 네트워크 포트가 정상 상태가 아닌 것으로 확인되면 EMS 메시지를 통해 관리자에게 경고를 표시하거나 해당 포트를 성능 저하로 표시합니다. ONTAP는 해당 LIF에 대한 정상적인 대체 페일오버 대상이 있을 경우 성능이 저하된 네트워크 포트에서 LIF를 호스팅하지 않습니다. 링크 플래핑(링크가 위아래로 빠르게 튀어 나며 튀어 나며 튀어 나오는 경우) 또는 네트워크 파티셔닝과 같은 소프트 장애 이벤트로 인해 포트의 성능이 저하될 수 있습니다.

* 클러스터 IPspace의 네트워크 포트는 브로드캐스트 도메인의 다른 네트워크 포트에 대한 링크 플래핑 또는 L2(계층 2) 재연결이 끊어지면 성능이 저하된 것으로 표시됩니다.
* 클러스터 이외의 IPspace의 네트워크 포트는 링크 플래핑 기능이 있을 때 성능이 저하된 것으로 표시됩니다.


성능이 저하된 포트의 다음과 같은 동작을 알고 있어야 합니다.

* 성능이 저하된 포트는 VLAN 또는 인터페이스 그룹에 포함될 수 없습니다.
+
인터페이스 그룹의 구성원 포트가 성능 저하로 표시되어 있지만 인터페이스 그룹이 계속 정상 상태로 표시되어 있는 경우 해당 인터페이스 그룹에서 LIF를 호스팅할 수 있습니다.

* LIF는 성능이 저하된 포트에서 정상 포트로 자동 마이그레이션됩니다.
* 페일오버 이벤트 중에 성능 저하된 포트는 페일오버 타겟으로 간주되지 않습니다. 정상 상태의 포트를 사용할 수 없는 경우 성능이 저하된 포트 호스트 LIF는 일반 페일오버 정책에 따라 작동합니다.
* LIF를 생성, 마이그레이션 또는 성능이 저하된 포트로 되돌릴 수 없습니다.
+
네트워크 포트의 '상태 무시' 설정을 '참'으로 수정할 수 있습니다. 그런 다음 양호한 포트에서 LIF를 호스팅할 수 있습니다.



.단계
. 고급 권한 모드로 로그인합니다.
+
....
set -privilege advanced
....
. 네트워크 포트 상태 모니터링을 위해 활성화된 상태 모니터를 확인합니다.
+
....
network options port-health-monitor show
....
+
포트의 상태는 상태 모니터의 값에 의해 결정됩니다.

+
ONTAP에서는 기본적으로 다음 상태 모니터를 사용할 수 있으며 사용하도록 설정되어 있습니다.

+
** 링크 플래핑 상태 모니터: 링크 플래핑 모니터링
+
포트에 5분 내에 두 번 이상 링크 플래핑이 있는 경우 이 포트는 성능 저하로 표시됩니다.

** L2 연결 상태 모니터: 동일한 브로드캐스트 도메인에 구성된 모든 포트가 서로 L2 연결 가능 여부를 모니터링합니다
+
이 상태 모니터는 모든 IPspace에서 L2 도달 가능성 문제를 보고하지만 클러스터 IPspace의 포트만 성능 저하로 표시합니다.

** CRC 모니터: 포트에서 CRC 통계를 모니터링합니다
+
이 상태 모니터는 포트를 성능 저하로 표시하지 않지만 매우 높은 CRC 실패율이 관찰되면 EMS 메시지를 생성합니다.



. 'network options port-health-monitor modify' 명령을 사용하여 원하는 대로 IPspace에 대한 상태 모니터를 사용하거나 사용하지 않도록 설정합니다.
. 포트의 세부 상태를 봅니다.
+
....
network port show -health
....


명령 출력에는 포트의 상태, '상태 무시' 설정 및 포트가 성능 저하로 표시된 이유 목록이 표시됩니다.

항만 건강상태는 건강하거나 등급이 매겨질 수 있다.

상태 무시 설정이 참이면 항만 상태가 평가됨에서 건강으로 변경되었음을 나타냅니다.

상태 무시 설정이 false이면 포트 상태는 시스템에 의해 자동으로 결정됩니다.
