---
sidebar: sidebar 
permalink: networking/move_broadcast_domains.html 
keywords: move, moving, broadcast, domain, ipspace, move broadcast domains into ipspaces, move the system created broadcast domains into the ipspaces you created 
summary: 시스템에서 생성한 브로드캐스트 도메인을 생성한 IPspace로 이동합니다 
---
= 브로드캐스트 도메인을 IPspaces로 이동(ONTAP 9.8 이상)
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
2계층 내 도달 가능성을 기반으로 생성된 브로드캐스트 도메인을 생성한 IPspace로 이동합니다.

브로드캐스트 도메인을 이동하기 전에 브로드캐스트 도메인의 포트 도달 가능 여부를 확인해야 합니다.

포트의 자동 스캐닝은 서로 연결할 수 있는 포트를 확인하여 동일한 브로드캐스트 도메인에 배치할 수 있지만 이 스캐닝에서 적절한 IPspace를 확인할 수 없습니다. 브로드캐스트 도메인이 기본 IPspace에 속한 경우 이 섹션의 단계를 사용하여 수동으로 이동해야 합니다.

.시작하기 전에
브로드캐스트 도메인은 클러스터 생성 및 연결 작업의 일부로 자동으로 구성됩니다. ONTAP는 "기본" 브로드캐스트 도메인을 "클러스터에서 생성된 첫 번째 노드의 관리 인터페이스 홈 포트에 대한 계층 2 연결이 있는 포트 세트로 정의합니다. 필요한 경우 다른 브로드캐스트 도메인이 생성되고 이름이 * Default-1 *, * Default-2 * 등으로 지정됩니다.

노드가 기존 클러스터에 연결되면 해당 네트워크 포트는 계층 2 도달 가능 여부에 따라 기존 브로드캐스트 도메인에 자동으로 연결됩니다. 기존 브로드캐스트 도메인에 대한 도달 기능이 없는 경우 포트가 하나 이상의 새 브로드캐스트 도메인에 배치됩니다.

.이 작업에 대해
* 클러스터 LIF가 있는 포트는 "클러스터" IPspace에 자동으로 배치되며
* 노드 관리 LIF의 홈 포트에 대한 연결 기능이 있는 포트는 "기본" 브로드캐스트 도메인에 배치됩니다.
* 다른 브로드캐스트 도메인은 클러스터 생성 또는 연결 작업의 일부로 ONTAP에 의해 자동으로 생성됩니다.
* VLAN 및 인터페이스 그룹을 추가하면 생성된 후 약 1분 후에 해당 브로드캐스트 도메인에 자동으로 배치됩니다.


.단계
. 브로드캐스트 도메인의 포트 도달 가능 여부를 확인합니다. ONTAP는 레이어 2 내 상태를 자동으로 모니터링합니다. 다음 명령을 사용하여 각 포트가 브로드캐스트 도메인에 추가되고 "확인" 기능이 있는지 확인합니다.
+
네트워크 포트 도달 가능성 세부 정보

. 필요한 경우 브로드캐스트 도메인을 다른 IPspace로 이동:
+
네트워크 포트 브로드캐스트 도메인 이동

+
예를 들어 브로드캐스트 도메인을 "기본값"에서 "IPS1"으로 이동하려면:

+
네트워크 포트 브로드캐스트-도메인 이동-IPSpace 기본-브로드캐스트-도메인 기본-IPSpace IPS1


