---
sidebar: sidebar 
permalink: networking/standard_properties_of_ipspaces.html 
keywords: standard, property, properties, ipspace, special, ipspaces, svm, cluster, default, understanding, cluster, initialization, initialized, introducing, introduction, overview, standard properties of ipspaces, introducing the default and cluster ipspaces created during cluster initialization, default ipspace, cluster ipspace, system svm 
summary: 클러스터 초기화 중에 생성되는 기본 및 클러스터 IPspace를 소개합니다 
---
= IPspace의 표준 속성
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
특수 IPspace는 클러스터를 처음 생성할 때 기본적으로 생성됩니다. 또한 IPspace별로 특수 스토리지 가상 머신(SVM)을 생성합니다.

2개의 IPspace가 클러스터 초기화 시 자동으로 생성됨:

* "기본" IPspace
+
이 IPspace는 포트, 서브넷 및 SVM에서 데이터를 제공하는 컨테이너입니다. 클라이언트에 대해 별도의 IPspace가 필요 없는 경우 이 IPspace에서 모든 SVM을 생성할 수 있습니다. 이 IPspace는 클러스터 관리 및 노드 관리 포트도 포함합니다.

* "클러스터" IPspace
+
이 IPspace는 클러스터 내의 모든 노드에 있는 클러스터 포트를 모두 포함하고 있습니다. 이 생성된 클러스터는 클러스터 생성 시 자동으로 생성됩니다. 내부 프라이빗 클러스터 네트워크에 대한 연결을 제공합니다. 추가 노드가 클러스터에 추가될 때 해당 노드의 클러스터 포트가 "클러스터" IPspace에 추가됩니다.



IPspace별로 존재하는 "시스템" SVM IPspace를 생성하는 경우 동일한 이름의 기본 시스템 SVM이 생성됩니다.

* 내부 프라이빗 클러스터 네트워크에서 클러스터 노드 간에 클러스터 트래픽을 전달하는 "클러스터" IPspace용 시스템 SVM
+
클러스터 관리자가 관리하며 "Cluster"라는 이름이 있습니다.

* 클러스터 간 트래픽을 포함하여 클러스터 및 노드에 대한 관리 트래픽을 전달하는 "기본" IPspace용 시스템 SVM
+
클러스터 관리자가 관리하며 클러스터와 동일한 이름을 사용합니다.

* 생성한 사용자 지정 IPspace용 시스템 SVM은 해당 SVM에 대한 관리 트래픽을 전달
+
클러스터 관리자가 관리하며 IPspace와 동일한 이름을 사용합니다.



IPspace에 클라이언트용 SVM이 하나 이상 존재할 수 있습니다. 각 클라이언트 SVM은 자체 데이터 볼륨 및 구성을 제공하며 다른 SVM과 독립적으로 관리됩니다.
