---
sidebar: sidebar 
permalink: networking/task_testing_snmp_polling.html 
keywords: configure, snmp, verify, poll, cluster, test, test snmp poll 
summary: SNMP를 구성한 후에는 클러스터를 폴링할 수 있는지 확인해야 합니다. 
---
= SNMP 폴링을 테스트합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SNMP를 구성한 후에는 클러스터를 폴링할 수 있는지 확인해야 합니다.

.이 작업에 대해
클러스터를 폴링하려면 과 같은 타사 명령을 사용해야 합니다 `snmpwalk`.

.단계
. SNMP 명령을 전송하여 다른 클러스터에서 클러스터를 폴링합니다.
+
SNMPv1을 실행하는 시스템의 경우 CLI 명령을 사용합니다 `snmpwalk -v version -c community_stringip_address_or_host_name system` MIB(Management Information Base)의 내용을 검색합니다.

+
이 예제에서 폴링할 클러스터 관리 LIF의 IP 주소는 10.11.12.123입니다. 명령은 MIB에서 요청된 정보를 표시합니다.

+
[listing]
----
C:\Windows\System32>snmpwalk -v 1 -c public 10.11.12.123 system

SNMPv1-MIB::sysDescr.0 = STRING: NetApp Release 8.3.0
            Cluster-Mode: Tue Apr 22 16:24:48 EDT 2014
SNMPv1-MIB::sysObjectID.0 = OID: SNMPv1-SMI::enterprises.789.2.5
DISMAN-EVENT-MIB::sysUpTimeInstance = Timeticks: (162644448) 18 days, 19:47:24.48
SNMPv1-MIB::sysContact.0 = STRING:
SNMPv1-MIB::sysName.0 = STRING: systemname.testlabs.com
SNMPv1-MIB::sysLocation.0 = STRING: Floor 2 Row B Cab 2
SNMPv1-MIB::sysServices.0 = INTEGER: 72
----
+
SNMPv2c를 실행하는 시스템의 경우 CLI 명령을 사용합니다 `snmpwalk -v version -c community_stringip_address_or_host_name system` MIB(Management Information Base)의 내용을 검색합니다.

+
이 예제에서 폴링할 클러스터 관리 LIF의 IP 주소는 10.11.12.123입니다. 명령은 MIB에서 요청된 정보를 표시합니다.

+
[listing]
----
C:\Windows\System32>snmpwalk -v 2c -c public 10.11.12.123 system

SNMPv2-MIB::sysDescr.0 = STRING: NetApp Release 8.3.0
            Cluster-Mode: Tue Apr 22 16:24:48 EDT 2014
SNMPv2-MIB::sysObjectID.0 = OID: SNMPv2-SMI::enterprises.789.2.5
DISMAN-EVENT-MIB::sysUpTimeInstance = Timeticks: (162635772) 18 days, 19:45:57.72
SNMPv2-MIB::sysContact.0 = STRING:
SNMPv2-MIB::sysName.0 = STRING: systemname.testlabs.com
SNMPv2-MIB::sysLocation.0 = STRING: Floor 2 Row B Cab 2
SNMPv2-MIB::sysServices.0 = INTEGER: 72
----
+
SNMPv3를 실행하는 시스템의 경우 CLI 명령을 사용합니다 `snmpwalk -v 3 -a MD5 or SHA -l authnopriv -u username -A passwordip_address_or_host_name system` MIB(Management Information Base)의 내용을 검색합니다.

+
이 예제에서 폴링할 클러스터 관리 LIF의 IP 주소는 10.11.12.123입니다. 명령은 MIB에서 요청된 정보를 표시합니다.

+
[listing]
----
C:\Windows\System32>snmpwalk -v 3 -a MD5 -l authnopriv -u snmpv3
       -A password123 10.11.12.123 system

SNMPv3-MIB::sysDescr.0 = STRING: NetApp Release 8.3.0
       Cluster-Mode: Tue Apr 22 16:24:48 EDT 2014
SNMPv3-MIB::sysObjectID.0 = OID: SNMPv3-SMI::enterprises.789.2.5
DISMAN-EVENT-MIB::sysUpTimeInstance = Timeticks: (162666569) 18 days, 19:51:05.69
SNMPv3-MIB::sysContact.0 = STRING:
SNMPv3-MIB::sysName.0 = STRING: systemname.testlabs.com
SNMPv3-MIB::sysLocation.0 = STRING: Floor 2 Row B Cab 2
SNMPv3-MIB::sysServices.0 = INTEGER: 72
----

