---
sidebar: sidebar 
permalink: multi-admin-verify/request-operation-task.html 
keywords: ontap, mav, multi, admin, multi admin verify, verification, administrator, protected, operation, rules, request, cluster, approve, rbac 
summary: 'MAV(Multi-admin verification)를 사용하도록 설정된 클러스터에서 보호 작업을 시작하면 ONTAP가 자동으로 작업을 인터셉트하여 MAV 승인 그룹(MAV 관리자)에서 하나 이상의 관리자가 승인해야 하는 요청을 생성하도록 요청합니다.' 
---
= 보호된 작업의 실행을 요청합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
MAV(Multi-admin verification)를 사용하도록 설정된 클러스터에서 보호 작업 또는 명령을 시작하면 ONTAP가 자동으로 작업을 인터셉트하여 MAV 승인 그룹(MAV 관리자)의 한 명 이상의 관리자가 승인해야 하는 요청을 생성하도록 요청합니다. 또는 대화 상자 없이 MAV 요청을 만들 수 있습니다.

요청이 승인되면 쿼리에 응답하여 요청 만료 기간 내에 작업을 완료해야 합니다. 거부되거나 요청 또는 만료 기간이 초과된 경우 요청을 삭제하고 다시 제출해야 합니다.

MAV 기능은 기존 RBAC 설정을 그대로 사용합니다. 즉, 관리자 역할에 MAV 설정과 관계없이 보호된 작업을 실행할 수 있는 충분한 권한이 있어야 합니다. link:https://docs.netapp.com/us-en/ontap/authentication/create-svm-user-accounts-task.html["RBAC에 대해 자세히 알아보십시오"].

MAV 관리자인 경우 보호된 작업을 실행하기 위한 요청도 MAV 관리자의 승인을 받아야 합니다.



== System Manager 절차

사용자가 메뉴 항목을 클릭하여 작업을 시작하고 작업을 보호하는 경우 승인 요청이 생성되고 다음과 유사한 알림이 사용자에게 표시됩니다.

[listing]
----
Approval request to delete the volume was sent.
Track the request ID 356 from Events & Jobs > Multi-Admin Requests.
----
MAV가 활성화된 경우 사용자의 로그인 ID 및 MAV 역할(승인자 여부)에 따라 보류 중인 요청을 표시하는 * 다중 관리자 요청 * 창을 사용할 수 있습니다. 보류 중인 각 요청에 대해 다음 필드가 표시됩니다.

* 작동
* 색인(숫자)
* 상태(보류, 승인됨, 거부됨, 실행됨 또는 만료됨)
+
한 승인자가 요청을 거부하면 추가 작업이 불가능합니다.

* 쿼리(요청된 작업의 매개 변수 또는 값)
* 사용자를 요청하는 중입니다
* 요청이 에 만료됩니다
* (수) 보류 중인 승인자
* (수) 잠재적 승인자


요청이 승인되면 요청 사용자는 만료 기간 내에 작업을 다시 시도할 수 있습니다.

사용자가 승인 없이 작업을 재시도하면 다음과 유사한 알림이 표시됩니다.

[listing]
----
Request to perform delete operation is pending approval.
Retry the operation after request is approved.
----


== CLI 절차

. 보호된 작업을 직접 입력하거나 MAV 요청 명령을 사용합니다.
+
* 예제 – 볼륨을 삭제하려면 다음 명령 중 하나를 입력합니다. *

+
** '볼륨 삭제'
+
[listing]
----
cluster-1::*> volume delete -volume vol1 -vserver vs0

Warning: This operation requires multi-admin verification. To create a
         verification request use "security multi-admin-verify request
         create".

         Would you like to create a request for this operation?
          {y|n}: y

Error: command failed: The security multi-admin-verify request (index 3) is
       auto-generated and requires approval.
----
** 보안 다중 관리 - 확인 요청은 "볼륨 삭제"를 생성합니다
+
[listing]
----
Error: command failed: The security multi-admin-verify request (index 3)
       requires approval.
----


. 요청의 상태를 확인하고 MAV 통지에 응답합니다.
+
.. 요청이 승인되면 CLI 메시지에 응답하여 작업을 완료합니다.
+
* 예: *

+
[listing]
----
cluster-1::> security multi-admin-verify request show 3

     Request Index: 3
         Operation: volume delete
             Query: -vserver vs0 -volume vol1
             State: approved
Required Approvers: 1
 Pending Approvers: 0
   Approval Expiry: 2/25/2022 14:32:03
  Execution Expiry: 2/25/2022 14:35:36
         Approvals: admin2
       User Vetoed: -
           Vserver: cluster-1
    User Requested: admin
      Time Created: 2/25/2022 13:32:03
     Time Approved: 2/25/2022 13:35:36
           Comment: -
   Users Permitted: -

cluster-1::*> volume delete -volume vol1 -vserver vs0

Info: Volume "vol1" in Vserver "vs0" will be marked as deleted and placed in the volume recovery queue. The space used by the volume will be recovered only after the retention period of 12 hours has completed. To recover the space immediately, get the volume name using (privilege:advanced) "volume recovery-queue show vol1_*" and then "volume recovery-queue purge -vserver vs0 -volume <volume_name>" command. To recover the volume use the (privilege:advanced) "volume recovery-queue recover -vserver vs0       -volume <volume_name>" command.

Warning: Are you sure you want to delete volume "vol1" in Vserver "vs0" ?
{y|n}: y
----
.. 요청이 거부되거나 만료 기간이 지난 경우 요청을 삭제하고 다시 제출하거나 MAV 관리자에게 문의하십시오.
+
* 예: *

+
[listing]
----
cluster-1::> security multi-admin-verify request show 3

     Request Index: 3
         Operation: volume delete
             Query: -vserver vs0 -volume vol1
             State: vetoed
Required Approvers: 1
 Pending Approvers: 1
   Approval Expiry: 2/25/2022 14:38:47
  Execution Expiry: -
         Approvals: -
       User Vetoed: admin2
           Vserver: cluster-1
    User Requested: admin
      Time Created: 2/25/2022 13:38:47
     Time Approved: -
           Comment: -
   Users Permitted: -

cluster-1::*> volume delete -volume vol1 -vserver vs0

Error: command failed: The security multi-admin-verify request (index 3) hasbeen vetoed. You must delete it and create a new verification request.
To delete, run "security multi-admin-verify request delete 3".
----



