---
permalink: concepts/application-aware-data-management-concept.html 
sidebar: sidebar 
keywords: application aware data management 
summary: 'AppDM(Application Aware Data Management)을 사용하면 스토리지 용어가 아닌 애플리케이션 측면에서 ONTAP를 통해 배포하려는 애플리케이션을 설명할 수 있습니다. System Manager 및 REST API를 사용하여 최소한의 입력만으로 애플리케이션을 구성하여 데이터를 빠르게 제공할 수 있습니다.' 
---
= 애플리케이션 인식 데이터 관리
:icons: font
:imagesdir: ../media/


[role="lead"]
AppDM(Application Aware Data Management)을 사용하면 스토리지 용어가 아닌 애플리케이션 측면에서 ONTAP를 통해 배포하려는 애플리케이션을 설명할 수 있습니다. System Manager 및 REST API를 사용하여 최소한의 입력만으로 애플리케이션을 구성하여 데이터를 빠르게 제공할 수 있습니다.

애플리케이션 인식 데이터 관리 기능을 사용하면 개별 애플리케이션 수준에서 스토리지를 설정, 관리 및 모니터링할 수 있습니다. 이 기능은 관련 ONTAP 모범 사례를 통합하여 애플리케이션을 최적의 상태로 프로비저닝하며 원하는 성능 서비스 수준과 사용 가능한 시스템 리소스를 기반으로 스토리지 오브젝트를 균형 있게 배치합니다.

애플리케이션 인식 데이터 관리 기능에는 애플리케이션 템플릿 세트가 포함되어 있으며, 각 템플릿은 애플리케이션의 구성을 종합적으로 설명하는 일련의 매개 변수로 구성됩니다. 기본값으로 사전 설정되는 이러한 매개 변수는 애플리케이션 관리자가 ONTAP 시스템에서 스토리지 프로비저닝을 위해 지정할 수 있는 데이터베이스 크기, 서비스 수준, LIF와 같은 프로토콜 액세스 요소, 로컬 보호 기준 및 원격 보호 조건 등의 특성을 정의합니다. ONTAP는 지정된 매개 변수에 따라 LUN 및 볼륨과 같은 스토리지 엔터티를 애플리케이션에 적합한 크기 및 서비스 수준으로 구성합니다.

응용 프로그램에 대해 다음 작업을 수행할 수 있습니다.

* 응용 프로그램 템플릿을 사용하여 응용 프로그램을 만듭니다
* 애플리케이션과 연결된 스토리지를 관리합니다
* 응용 프로그램을 수정 또는 삭제합니다
* 응용 프로그램을 봅니다
* 애플리케이션의 스냅샷 복사본을 관리합니다
* 같은 볼륨 또는 다른 볼륨에서 여러 LUN을 선택하여 데이터 보호 기능을 제공하는 일관성 그룹을 생성합니다

