---
permalink: concepts/autosupport-active-iq-digital-advisor-concept.html 
sidebar: sidebar 
keywords: autosupport, active iq digital advisor, upgrade advisor 
summary: ONTAP는 웹 포털과 모바일 앱을 통해 인공 지능 기반의 시스템 모니터링 및 보고를 제공합니다. ONTAP의 AutoSupport 구성 요소는 Active IQ 디지털 어드바이저가 분석하는 원격 측정을 전송합니다. 
---
= AutoSupport 및 Active IQ 디지털 자문업체
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP는 웹 포털과 모바일 앱을 통해 인공 지능 기반의 시스템 모니터링 및 보고를 제공합니다. ONTAP의 AutoSupport 구성 요소는 Active IQ 디지털 어드바이저가 분석하는 원격 측정을 전송합니다.

Active IQ을 사용하면 클라우드 기반 포털 및 모바일 앱을 통해 실행 가능한 예측 분석과 능동적 지원을 제공하여 글로벌 하이브리드 클라우드 전반에서 데이터 인프라를 최적화할 수 있습니다. SupportEdge의 데이터 중심 인사이트와 권장사항은 Active IQ 계약이 체결된 모든 NetApp 고객(기능은 제품 및 지원 계층에 따라 다름)에게 제공됩니다.

다음은 Active IQ에서 수행할 수 있는 몇 가지 사항입니다.

* 업그레이드 계획 Active IQ는 사용자 환경에서 최신 버전의 ONTAP로 업그레이드하여 해결할 수 있는 문제를 식별하며, 업그레이드 관리자 구성 요소는 성공적인 업그레이드를 계획하는 데 도움이 됩니다.
* 시스템 상태 보기 Active IQ 대시보드에서 웰빙과 관련된 모든 문제를 보고하고 문제를 해결할 수 있습니다. 시스템 용량을 모니터링하여 스토리지 공간이 부족하지 않도록 하십시오.
* 성능 관리 Active IQ는 System Manager에서 볼 수 있는 것보다 더 오랜 기간 동안의 시스템 성능을 보여 줍니다. 성능에 영향을 주는 구성 및 시스템 문제를 식별합니다.
* 효율성 극대화 스토리지 효율성 메트릭을 확인하고 더 적은 공간에 더 많은 데이터를 저장하는 방법을 알아보십시오.
* 인벤토리 및 구성을 봅니다. Active IQ는 전체 인벤토리 및 소프트웨어 및 하드웨어 구성 정보를 표시합니다. 서비스 계약이 만료되는 시점을 확인하여 서비스 계약이 계속 보장되는지 확인합니다.


.관련 정보
https://["NetApp 설명서: Active IQ 디지털 자문업체"]

https://["Active IQ를 시작합니다"]

https://["SupportEdge 서비스"]
