---
sidebar: sidebar 
permalink: concepts/capacity-measurements-in-sm-concept.html 
keywords: capacity, measurement, physical, logical, storage, used storage, local tier capacity, aggregate capacity, block, capacity concern, add capacity, volume, used capacity, available capacity, total capacity, inactive capacity, static insights, dynamic insights, snapshot copy, snapshot copies, inactive data, overprovision, overflows, snapshot copy policy, snapshot copy reserves, reserves, policy, top volumes 
summary: 시스템 용량은 물리적 공간 또는 논리적 공간으로 측정할 수 있습니다. System Manager의 최신 버전에서는 물리적 용량과 논리적 용량을 모두 측정했습니다. 
---
= System Manager의 용량 측정
:allow-uri-read: 


[role="lead"]
시스템 용량은 물리적 공간 또는 논리적 공간으로 측정할 수 있습니다. System Manager의 최신 버전에서는 물리적 용량과 논리적 용량을 모두 측정했습니다.

두 측정 간의 차이점은 다음 설명에 설명되어 있습니다.

* * 물리적 용량 *: 물리적 공간은 볼륨 또는 로컬 계층에서 사용되는 스토리지의 물리적 블록을 의미합니다. 일반적으로 물리적 사용 용량의 값은 스토리지 효율성 기능(예: 중복제거, 압축)에서 데이터가 축소되기 때문에 논리적 사용 용량의 값보다 작습니다.
* * 논리적 용량 *: 논리적 공간은 볼륨 또는 로컬 계층의 사용 가능한 공간(논리적 블록)을 의미합니다. 논리적 공간은 중복제거 또는 압축 결과를 고려하지 않고 이론적 공간을 사용할 수 있는 방법을 나타냅니다. 사용된 논리적 공간의 값은 사용된 물리적 공간의 양과 함께 구성된 스토리지 효율성 기능(예: 중복제거 및 압축)의 절감액을 기준으로 도출됩니다. 이 측정치는 Snapshot 복사본, 클론 및 기타 구성 요소를 포함하므로 물리적 사용된 용량보다 더 크게 표시되는 경우가 많으며 데이터 압축 및 물리적 공간의 기타 감소는 반영되지 않습니다. 따라서 총 논리적 용량이 프로비저닝된 공간보다 클 수 있습니다.



NOTE: System Manager에서 용량 표현은 루트 스토리지 계층(애그리게이트) 용량을 고려하지 않습니다.

<<measurements-used-cap>>
<<cap-measurement-terms>>
<<cap-measurement-units>>

.추가 정보
System Manager에서 클러스터, 로컬 계층 및 볼륨의 용량을 모니터링할 수 있습니다. 을 참조하십시오 link:../task_admin_monitor_capacity_in_sm.html["System Manager에서 용량을 모니터링합니다"].



== 사용된 용량의 측정

사용된 용량의 측정값은 다음 표에 설명된 대로 사용 중인 System Manager 버전에 따라 다르게 표시됩니다.

[cols="30,30,40"]
|===


| System Manager의 버전입니다 | 용량에 사용되는 용어입니다 | 참조되는 용량 유형입니다 


 a| 
9.5 및 9.6(클래식 보기)
 a| 
사용됨
 a| 
사용된 물리적 공간입니다



 a| 
9.7 및 9.8
 a| 
사용됨
 a| 
사용된 논리적 공간(스토리지 효율성 설정이 사용된 경우)



 a| 
9.9.1 이상
 a| 
논리적 사용
 a| 
사용된 논리적 공간(스토리지 효율성 설정이 사용된 경우)

|===


== 용량 측정 용어

용량을 설명할 때 다음 용어가 사용됩니다.

* * Available * (사용 가능 *): 볼륨 프로비저닝에 사용할 수 있는 로컬 계층에서 사용 가능한 물리적 공간의 양입니다.
* * 클라이언트 데이터 *: 클라이언트 데이터가 사용하는 공간(물리적 또는 논리적)입니다.
* * Committed *: 로컬 계층에 대해 커밋된 용량의 양입니다.
* * 데이터 축소 *:
+
** * Overall *: 물리적 사용된 공간에 비해 모든 논리적 사용 공간의 비율입니다.
** * 스냅샷 복사본 및 클론 제외 *: 클라이언트 데이터만 사용하는 물리적 공간과 비교하여 클라이언트 데이터가 사용하는 논리적 공간의 비율입니다.


* * 논리적 사용 *: 스토리지 효율성 기능으로 절약되는 공간을 고려하지 않은 채 사용된 공간입니다.
* * Logical Used % *: 스냅샷 예약 공간을 제외하고 프로비저닝된 크기와 비교하여 현재 논리적 사용 용량의 비율입니다. 이 값에는 볼륨의 효율성 절약이 포함되어 있으므로 100%보다 클 수 있습니다.
* * 물리적 사용 *: 볼륨 또는 로컬 계층의 물리적 블록에 사용된 용량입니다.
* * 물리적 사용 % *: 프로비저닝된 크기에 비해 볼륨의 물리적 블록에 사용된 용량의 비율입니다.
* * 예약됨 *: 로컬 계층에서 이미 프로비저닝된 볼륨에 예약된 공간입니다.
* * 사용 및 예약 *: 물리적 사용 공간과 예약된 공간의 합계입니다.




== 용량 측정 단위

System Manager는 1024바이트(2^10^)바이트의 이진 단위를 기준으로 스토리지 용량을 계산합니다. ONTAP 9.10.0 이전 버전에서는 이러한 유닛이 시스템 관리자에 KB, MB, GB, TB 및 PB로 표시되었습니다. ONTAP 9.10.1부터는 시스템 관리자에 KiB, MiB, GiB, TiB 및 PiB로 표시됩니다.


NOTE: 시스템 관리자에서 처리량을 위해 사용되는 단위는 모든 ONTAP 릴리즈에서 KB/s, MB/s, GB/s, TB/s 및 PB/s입니다.

[cols="20,20,30,30"]
|===


| 용량 단위는 ONTAP 9.10.0 이하 버전에 대한 System Manager에 표시됩니다 | 용량 단위는 ONTAP 9.10.1 이상인 경우 시스템 관리자에 표시됩니다 | 계산 | 바이트 단위의 값입니다 


 a| 
KB를 클릭합니다
 a| 
KiB
 a| 
1024
 a| 
1024바이트



 a| 
MB
 a| 
MIB
 a| 
1024 * 1024
 a| 
1,048,576바이트



 a| 
GB
 a| 
GiB
 a| 
1024 * 1024 * 1024
 a| 
1,073,741,824바이트



 a| 
TB
 a| 
TiB
 a| 
1024 * 1024 * 1024
 a| 
1,099,511,627,776바이트



 a| 
PB
 a| 
PIB
 a| 
1024 * 1024 * 1024 * 1024
 a| 
1,125,898,010,834,824바이트

|===
.추가 정보:
link:../volumes/logical-space-reporting-enforcement-concept.html["볼륨에 대한 논리적 공간 보고 및 적용"]
