---
permalink: concepts/client-protocols-concept.html 
sidebar: sidebar 
keywords: client protocols 
summary: ONTAP는 NFS, SMB, FC, FCoE, iSCSI, iSCSI 등의 모든 주요 업계 표준 클라이언트 프로토콜을 NVMe/FC가 있습니다. 
---
= 클라이언트 프로토콜
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP는 NFS, SMB, FC, FCoE, iSCSI, iSCSI 등의 모든 주요 업계 표준 클라이언트 프로토콜을 NVMe/FC가 있습니다.



== NFS 를 참조하십시오

NFS는 UNIX 및 Linux 시스템을 위한 기존 파일 액세스 프로토콜입니다. 클라이언트는 NFSv3, NFSv4, NFSv4.1 및 pNFS 프로토콜을 사용하여 ONTAP 볼륨의 파일에 액세스할 수 있습니다. UNIX 스타일 사용 권한, NTFS 스타일 사용 권한 또는 이 두 가지를 혼합하여 파일 액세스를 제어할 수 있습니다.

클라이언트는 NFS 및 SMB 프로토콜을 모두 사용하여 동일한 파일에 액세스할 수 있습니다.



== 중소기업

SMB는 Windows 시스템을 위한 기존 파일 액세스 프로토콜입니다. 클라이언트는 SMB 2.0, SMB 2.1, SMB 3.0 및 SMB 3.1.1 프로토콜을 사용하여 ONTAP 볼륨의 파일에 액세스할 수 있습니다. NFS와 마찬가지로 사용 권한 스타일의 조합이 지원됩니다.

SMB 1.0은 사용 가능하지만 ONTAP 9.3 이상 릴리스에서 기본적으로 비활성화되어 있습니다.



== FC

Fibre Channel은 원래 네트워크 블록 프로토콜입니다. 블록 프로토콜은 파일 대신 전체 가상 디스크를 클라이언트에 제공합니다. 기존 FC 프로토콜은 전용 FC 스위치를 사용하는 전용 FC 네트워크를 사용하며, 클라이언트 컴퓨터에 FC 네트워크 인터페이스가 있어야 합니다.

LUN은 가상 디스크를 나타내고, 하나 이상의 LUN은 ONTAP 볼륨에 저장됩니다. FC, FCoE 및 iSCSI 프로토콜을 통해 동일한 LUN에 액세스할 수 있지만 여러 클라이언트가 쓰기 충돌을 방지하는 클러스터의 일부인 경우에만 동일한 LUN에 액세스할 수 있습니다.



== FCoE 를 참조하십시오

FCoE는 기본적으로 FC와 동일한 프로토콜이지만 기존 FC 전송 대신 데이터 센터급 이더넷 네트워크를 사용합니다. 클라이언트에는 여전히 FCoE 전용 네트워크 인터페이스가 필요합니다.



== iSCSI

iSCSI는 표준 이더넷 네트워크에서 실행할 수 있는 블록 프로토콜입니다. 대부분의 클라이언트 운영 체제는 표준 이더넷 포트를 통해 실행되는 소프트웨어 이니시에이터를 제공합니다. iSCSI는 특정 애플리케이션에 대한 블록 프로토콜이 필요하지만 전용 FC 네트워킹을 사용할 수 없는 경우에 적합합니다.



== NVMe/FC

최신 블록 프로토콜인 NVMe/FC는 플래시 기반 스토리지에서 작동하도록 특별히 설계되었습니다. 확장 가능한 세션, 지연 시간 대폭 감소, 병렬 처리 수 증가 등을 제공하므로 메모리 내 데이터베이스 및 분석과 같은 대기 시간이 짧고 처리량이 높은 애플리케이션에 적합합니다.

FC 및 iSCSI와 달리 NVMe는 LUN을 사용하지 않습니다. 대신 ONTAP 볼륨에 저장된 네임스페이스를 사용합니다. NVMe 네임스페이스는 NVMe 프로토콜을 통해서만 액세스할 수 있습니다.
