---
permalink: concepts/fabricpool-concept.html 
sidebar: sidebar 
keywords: netapp storage grid, fabricpool 
summary: 많은 NetApp 고객은 거의 액세스하지 않는 저장된 데이터의 양이 상당히 많습니다. 콜드 데이터를 그 추위로 부릅니다. 또한 고객들은 자주 액세스되는 데이터를 가지고 있으며 이를 핫 데이터라고 합니다. 가장 빠른 스토리지에 핫 데이터를 유지하여 최적의 성능을 발휘해야 합니다. 필요한 경우 즉시 사용 가능한 경우 콜드 데이터를 더 느린 스토리지로 이동할 수 있습니다. 하지만 데이터의 어떤 부분이 핫 데이터인지, 그리고 콜드 부품인지 어떻게 알 수 있을까요? 
---
= FabricPool
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
많은 NetApp 고객은 거의 액세스하지 않는 저장된 데이터의 양이 상당히 많습니다. 이를 _cold_data 라고 합니다. 또한 고객은 자주 액세스되는 데이터를 가지고 있으며, 이를 _ hot_data 라고 합니다. 가장 빠른 스토리지에 핫 데이터를 유지하여 최적의 성능을 발휘해야 합니다. 필요한 경우 즉시 사용 가능한 경우 콜드 데이터를 더 느린 스토리지로 이동할 수 있습니다. 하지만 데이터의 어떤 부분이 핫 데이터인지, 그리고 콜드 부품인지 어떻게 알 수 있을까요?

FabricPool는 액세스 패턴에 따라 고성능 로컬 계층(애그리게이트)과 클라우드 계층 간에 데이터를 자동으로 이동하는 ONTAP 기능입니다. 계층화는 클라우드에 있는 저비용 오브젝트 스토리지에서 콜드 데이터를 즉시 사용할 수 있도록 하면서 핫 데이터에 대한 값비싼 로컬 스토리지를 확보하게 됩니다. FabricPool는 데이터 액세스를 지속적으로 모니터링하고 계층 간에 데이터를 이동하여 최상의 성능과 최대 절감 효과를 제공합니다.

FabricPool를 사용하여 콜드 데이터를 클라우드에 계층화하면 클라우드 효율성을 확보하고 하이브리드 클라우드 구성을 생성하는 가장 쉬운 방법 중 하나가 됩니다. FabricPool는 스토리지 블록 레벨에서 작동하므로 파일 및 LUN 데이터 모두에서 작동합니다.

하지만 FabricPool는 사내 데이터를 클라우드로 계층화하는 것만이 아닙니다. 많은 고객이 Cloud Volumes ONTAP의 FabricPool를 사용하여 클라우드 공급자 내에서 비용이 높은 클라우드 스토리지의 콜드 데이터를 저렴한 오브젝트 스토리지로 계층화합니다. ONTAP 9.8부터 FabricPool 지원 볼륨에 대한 분석을 에서 캡처할 수 있습니다 link:../concept_nas_file_system_analytics_overview.html["파일 시스템 분석"] 또는 link:../volumes/enable-temperature-sensitive-efficiency-concept.html["온도에 민감한 스토리지 효율성"].

데이터를 사용하는 애플리케이션은 데이터가 계층화된다는 것을 알지 못하므로 애플리케이션을 변경할 필요가 없습니다. 계층화는 완전히 자동으로 이루어지므로 지속적인 관리가 필요하지 않습니다.

주요 클라우드 공급자 중 하나에서 오브젝트 스토리지에 콜드 데이터를 저장할 수 있습니다. 또는 NetApp StorageGRID를 선택하여 콜드 데이터를 자체 프라이빗 클라우드에 보관하면 최고의 성능과 완벽한 데이터 제어가 가능합니다.

.관련 정보
https://docs.netapp.com/us-en/ontap/concept_cloud_overview.html["FabricPool 시스템 관리자 문서"^]

https://cloud.netapp.com/cloud-tiering["BlueXP 계층화"^]

https://www.youtube.com/playlist?list=PLdXI3bZJEw7mcD3RnEcdqZckqKkttoUpS["NetApp TechComm TV의 FabricPool 재생 목록"^]
