---
permalink: concepts/introducing-ontap-interfaces-concept.html 
sidebar: sidebar 
keywords: ontap interfaces, interfaces, system manager, bluexp, cli, rest api, ontapi 
summary: ONTAP 데이터 관리 소프트웨어는 ONTAP로 보호되는 데이터를 관리하는 데 사용할 수 있는 다양한 인터페이스를 제공합니다. 
---
= ONTAP 사용자 인터페이스
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 데이터 관리 소프트웨어는 ONTAP 클러스터를 관리하는 데 사용할 수 있는 다양한 인터페이스를 제공합니다. 이러한 인터페이스 옵션은 다양한 수준의 액세스 및 기능을 제공하며 환경에 따라 ONTAP 클러스터를 적절하게 관리할 수 있는 유연성을 제공합니다.

이 인터페이스 중 하나를 사용하여 ONTAP 클러스터를 관리하고 데이터 관리 작업을 수행할 수 있습니다



== ONTAP 시스템 관리자

ONTAP System Manager는 웹 기반 사용자 인터페이스로, 클러스터를 관리하기 위한 간단하고 직관적인 방법을 제공합니다. 스토리지 구성, 데이터 보호, 네트워크 설정 및 관리 등의 일반 작업을 관리할 수 있습니다. 또한 System Manager는 위험 및 클러스터 성능 모니터링과 인사이트를 제공합니다. 이를 통해 클러스터 문제에 대응하고 문제가 발생하기 전에 미리 파악할 수 있습니다. link:../concept_administration_overview.html["자세한 정보"].

ONTAP 9.7은 ONTAP System Manager의 중요한 전환점을 표시했습니다. 이 릴리즈에서 NetApp은 두 가지 버전의 ONTAP System Manager를 제공했으며, ONTAP 9.7 이전 버전과 함께 더욱 간소화되고 직관적인 버전을 새롭게 설계했습니다. ONTAP 9.7 이후, ONTAP System Manager로 계속 재설계된 버전과 이전 버전은 System Manager Classic으로 이름이 바뀌었습니다. System Manager Classic은 마지막으로 ONTAP 9.7에서 출시되었습니다. 관련 문서를 사용할 수 https://docs.netapp.com/us-en/ontap-system-manager-classic/index.html["별로입니다"^]있습니다.



== BlueXP

ONTAP 9.12.1부터는 BlueXP 웹 기반 인터페이스를 사용하여 친숙한 System Manager 대시보드를 유지하면서 단일 제어 플레인에서 하이브리드 멀티 클라우드 인프라를 관리할 수 있습니다. BlueXP를 사용하면 클라우드 스토리지(예: Cloud Volumes ONTAP)를 생성 및 관리하고, NetApp의 데이터 서비스(예: Cloud Backup)를 사용하며, 다수의 사내 및 에지 스토리지 장치를 제어할 수 있습니다. 온프레미스 ONTAP 시스템을 BlueXP에 추가하면 모든 스토리지 및 데이터 자산을 단일 인터페이스에서 관리할 수 있습니다. https://docs.netapp.com/us-en/bluexp-family/["자세한 정보"^].



== ONTAP 명령줄 인터페이스입니다

를 클릭합니다 link:../system-admin/index.html["ONTAP CLI(명령줄 인터페이스)"] 는 를 사용하여 클러스터, 노드, SVM 및 기타 사용자와 상호 작용할 수 있는 텍스트 기반 인터페이스입니다 link:../concepts/manual-pages.html["명령"]. CLI 명령은 를 기반으로 사용할 수 있습니다 link:../system-admin/cluster-svm-administrators-concept.html["역할 유형"]. SSH 또는 클러스터의 노드에 대한 콘솔 연결을 통해 ONTAP CLI에 액세스할 수 있습니다.



== ONTAP REST API를 참조하십시오

ONTAP 9.6부터 RESTful API에 액세스하여 클러스터 운영을 프로그래밍 방식으로 관리 및 자동화할 수 있습니다. 이 API를 사용하여 볼륨, 스냅샷 및 애그리게이트 생성 및 관리와 같은 다양한 ONTAP 관리 작업은 물론 클러스터 성능 모니터링도 수행할 수 있습니다. curl과 같은 유틸리티를 사용하거나 Python, PowerShell, Java 등과 같은 REST 클라이언트를 지원하는 프로그래밍 언어를 사용하여 ONTAP REST API에 직접 액세스할 수 있습니다. https://docs.netapp.com/us-en/ontap-automation/get-started/ontap_automation_options.html["자세한 정보"^].


NOTE: ONTAPI는 ONTAP REST API보다 앞선 독점 ONTAP API입니다. 향후 버전의 ONTAP에서는 ONTAPI 인터페이스가 비활성화됩니다. ONTAPI를 사용하는 경우 를 계획해야 합니다 https://docs.netapp.com/us-en/ontap-automation/migrate/ontapi_disablement.html["ONTAP REST API로 마이그레이션"^].



== NetApp 툴킷 및 프레임워크

NetApp는 ONTAP REST API를 추상화하고 자동화 코드를 더 쉽게 작성할 수 있도록 특정 개발 언어 및 환경에 적합한 클라이언트 툴킷을 제공합니다.
https://docs.netapp.com/us-en/ontap-automation/get-started/ontap_automation_options.html#client-software-toolkits["자세한 정보"^].

이러한 툴킷 외에도 프레임워크를 사용하여 자동화 코드를 생성하고 배포할 수 있습니다. https://docs.netapp.com/us-en/ontap-automation/get-started/ontap_automation_options.html#automation-frameworks["자세한 정보"^].
