---
permalink: concepts/storage-efficiency-overview.html 
sidebar: sidebar 
keywords: storage efficiency, storage efficiencies, storage efficiency technologies, space utliziation, space savings, optimizing, space optimization, minimizing, wasted space, reducing, footprint, thin provisioning, deduplication, zero block, zero-block, inline, deduplication, backgroud deduplication, postprocessing, post-processing, compression, compaction, flex-clone technologies 
summary: 스토리지 효율성은 스토리지 리소스를 최적화하고, 낭비되는 공간을 최소화하고, 쓰인 데이터의 물리적 설치 공간을 줄임으로써 스토리지 시스템이 사용 가능한 공간을 얼마나 효과적으로 활용하는지 나타내는 척도입니다. 
---
= ONTAP 스토리지 효율성 개요
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
스토리지 효율성은 스토리지 리소스를 최적화하고, 낭비되는 공간을 최소화하고, 쓰인 데이터의 물리적 설치 공간을 줄임으로써 스토리지 시스템이 사용 가능한 공간을 얼마나 효과적으로 활용하는지 나타내는 척도입니다. 스토리지 효율성을 높이면 최소 공간 내에 최저 비용으로 최대한 많은 양의 데이터를 저장할 수 있습니다. 예를 들어, 중복 데이터 블록과 0으로 채워진 데이터 블록을 감지하여 제거하는 스토리지 효율적인 기술을 사용하면 필요한 전체 물리적 스토리지의 양을 줄이고 전체 비용을 절감할 수 있습니다.

ONTAP은 다양한 스토리지 효율성 기술을 제공하여 데이터에 사용되는 물리적 하드웨어 또는 클라우드 스토리지의 양을 줄이고, 데이터 읽기 속도 향상, 데이터 세트 복사 속도 향상, VM 프로비저닝 속도 향상 등 시스템 성능을 크게 개선합니다.

.ONTAP 스토리지 효율성 기술은 다음과 같습니다.
* * 씬 프로비저닝 *
+
xref:thin-provisioning-concept.html[씬 프로비저닝] 스토리지를 미리 예약하는 대신 필요한 만큼 볼륨 또는 LUN을 할당할 수 있습니다.  따라서 현재 사용되고 있지 않은 공간을 예약하지 않고 잠재적 사용량을 기반으로 볼륨 또는 LUN을 초과 할당할 수 있으므로 필요한 물리적 스토리지의 양이 줄어듭니다.

* * 데이터 중복 제거 *
+
xref:deduplication-concept.html[중복 제거] 볼륨에 필요한 물리적 스토리지의 양을 세 가지 방법으로 줄입니다.

+
** * 제로 블록 중복 제거 *
+
제로 블록 중복제거는 0으로 채워진 데이터 블록을 감지하여 제거하고 메타데이터만 업데이트합니다. 그런 다음 일반적으로 제로 블록에 사용되는 공간의 100% 절약  중복제거된 모든 볼륨에 대해 제로 블록 중복제거가 기본적으로 활성화됩니다.

** * 인라인 중복제거 *
+
인라인 중복제거는 중복 데이터 블록을 감지하여 데이터를 디스크에 쓰기 전에 고유한 공유 블록에 대한 참조로 대체합니다. 인라인 중복제거 기능으로 VM 프로비저닝 속도를 20~30% 높일 수 있습니다.  ONTAP의 버전과 플랫폼에 따라 볼륨 또는 애그리게이트 레벨에서 인라인 중복제거를 사용할 수 있습니다.  AFF 및 ASA 시스템에서는 기본적으로 사용하도록 설정되어 있습니다. FAS 시스템에서 인라인 중복제거를 수동으로 활성화해야 합니다.

** * 백그라운드 중복 제거 *
+
백그라운드 중복제거는 또한 중복 데이터 블록을 감지하여 고유한 공유 블록에 대한 참조로 교체하지만, 데이터를 디스크에 쓴 후 이를 통해 스토리지 효율성을 더욱 높여줍니다.  스토리지 시스템에서 특정 조건이 충족될 때 실행되도록 백그라운드 중복제거를 설정할 수 있습니다. 예를 들어, 볼륨이 10% 활용도에 도달할 때 백그라운드 중복 제거를 사용하도록 설정할 수 있습니다.  또한 백그라운드 중복제거를 수동으로 트리거하거나 특정 일정에 따라 실행되도록 설정할 수 있습니다. AFF 및 ASA 시스템에서는 기본적으로 사용하도록 설정되어 있습니다. FAS 시스템에서 백그라운드 중복제거를 수동으로 활성화해야 합니다.



+
중복제거는 애그리게이트 내의 볼륨 및 볼륨 전체에서 지원됩니다.  중복 제거된 데이터를 읽으면 일반적으로 성능 저하가 발생하지 않습니다.

* * 압축 *
+
xref:compression-concept.html[압축] 각각 단일 블록으로 저장되는 압축 그룹의 데이터 블록을 결합하여 볼륨에 필요한 물리적 스토리지 양을 줄입니다. 읽기 또는 덮어쓰기 요청을 받으면 전체 파일이 아닌 소규모 블록 그룹만 읽습니다. 따라서 이 프로세스에서는 읽기 및 덮어쓰기 성능이 최적화되며 압축하는 파일의 크기 면에서 더 나은 확장성을 제공합니다.

+
압축은 인라인으로 실행하거나 사후에 실행할 수 있습니다. 인라인 압축은 디스크에 쓰기 전에 메모리의 데이터를 압축하여 공간을 즉각적으로 절약해 줍니다. 사후 처리 압축은 먼저 블록을 압축되지 않은 상태로 디스크에 기록한 다음 예약된 시간에 데이터를 압축합니다. 이 솔루션은 AFA 시스템에서 기본적으로 활성화되어 있습니다. 다른 모든 시스템에서 압축을 수동으로 활성화해야 합니다.

* * 압축 *
+
컴팩션은 4KB 블록에 저장되지만 크기가 4KB 미만인 데이터 청크를 가져와 단일 블록으로 결합함으로써 볼륨에 필요한 물리적 스토리지의 양을 줄입니다. 컴팩션은 데이터가 메모리에 아직 있는 상태에서 수행되므로 디스크에서 불필요한 공간을 사용하지 않습니다.  AFF 및 ASA 시스템에서는 기본적으로 사용하도록 설정되어 있습니다. FAS 시스템에서 컴팩션을 수동으로 활성화해야 합니다.

* * FlexClone 볼륨, 파일 및 LUN *
+
xref:flexclone-volumes-files-luns-concept.html[FlexClone 기술] Snapshot 메타데이터를 활용하여 볼륨, 파일 또는 LUN에 대한 쓰기 가능한 시점 복사본을 생성합니다. 복사본은 데이터 블록을 부모와 공유하므로 복사본 또는 해당 부모에 변경 사항이 기록될 때까지 메타데이터에 필요한 것을 제외하고 스토리지를 소비하지 않습니다.  변경 사항이 기록되면 델타만 저장됩니다.

+
기존 데이터 세트 복사본을 생성하는 데 몇 분 또는 몇 시간이 걸릴 수 있습니다. FlexClone 기술을 사용하면 가장 큰 데이터 세트도 거의 즉시 복사할 수 있습니다.

* * 온도에 민감한 스토리지 효율성 *
+
ONTAP는 link:../volumes/enable-temperature-sensitive-efficiency-concept.html["온도에 민감한 스토리지 효율성"] 볼륨의 데이터에 액세스하는 빈도를 평가하고 해당 데이터에 적용되는 압축 수준에 해당 빈도를 매핑함으로써 이점을 제공합니다. 자주 액세스하지 않는 콜드 데이터의 경우 더 큰 데이터 블록이 압축됩니다. 자주 액세스하여 자주 덮어쓰는 핫 데이터의 경우 더 작은 데이터 블록이 압축되므로 프로세스 효율성이 향상됩니다.

+
ONTAP 9.8에 도입된 온도에 민감한 스토리지 효율성(TSSE)은 새로 생성된 씬 프로비저닝된 AFF 볼륨에서 자동으로 활성화됩니다. 하드웨어 오프로드 프로세서를 사용하는 ONTAP 9.15.1에 도입된 에서는 이 기능이 사용되지 link:builtin-storage-efficiency-concept.html["AFF A70, AFF A90 및 AFF A1K 플랫폼"] 않습니다.

* * CPU 또는 전용 오프로드 프로세서 스토리지 효율성 *
+
ONTAP 9.15.1부터 ONTAP는 link:builtin-storage-efficiency-concept.html["CPU 또는 전용 오프로드 프로세서 스토리지 효율성"]AFF A70, AFF A90, AFF A1K, FAS70, FAS90 플랫폼에 데이터 컴팩션을 제공합니다. AFF A70, AFF A90 및 AFF A1K 시스템에서는 스토리지 효율성이 자동으로 활성화되며 구성이 필요하지 않습니다.



최소한의 노력으로 일상적인 운영에서 이러한 기술의 이점을 실현할 수 있습니다.  예를 들어 5,000명의 사용자에게 홈 디렉토리에 대한 스토리지를 제공해야 하고, 모든 사용자에게 필요한 최대 공간이 1GB라고 가정할 수 있습니다. 잠재적인 총 스토리지 요구 사항을 충족하기 위해 5TB 애그리게이트를 미리 예약할 수 있습니다.  하지만 홈 디렉토리 용량 요구 사항은 조직 전반에 걸쳐 매우 다양합니다.  조직에 총 5TB의 공간을 예약하는 대신 2TB 애그리게이트를 생성할 수 있습니다.  그런 다음 씬 프로비저닝을 사용하여 각 사용자에게 1GB의 스토리지를 할당하지만 필요한 경우에만 스토리지를 할당할 수 있습니다.  시간에 따라 애그리게이트를 능동적으로 모니터링하고 필요에 따라 실제 물리적 크기를 늘릴 수 있습니다.

다른 예로, 가상 데스크톱 간에 많은 양의 중복 데이터가 있는 VDI(가상 데스크톱 인프라)를 사용한다고 가정합니다. 중복 제거는 VDI에서 중복된 정보 블록을 자동으로 제거하고 원래 블록에 대한 포인터로 대체하여 스토리지 사용량을 줄입니다. 사용자 개입 없이 압축과 같은 다른 ONTAP 스토리지 효율성 기술을 백그라운드에서 실행할 수 있습니다.

ONTAP 디스크 파티셔닝 기술을 통해 스토리지 효율성도 향상됩니다.  RAID DP 기술은 성능을 저하시키거나 디스크 미러링 오버헤드를 더하지 않고 이중 디스크 장애를 방지합니다. ONTAP 9의 고급 SSD 파티셔닝은 사용 가능한 용량을 20% 가까이 늘려 줍니다.

NetApp은 클라우드에서 사내 ONTAP와 동일한 스토리지 효율성 기능을 제공합니다. 온프레미스 ONTAP에서 클라우드로 데이터를 마이그레이션할 때 기존 스토리지 효율성이 유지됩니다. 예를 들어, 사내 시스템에서 클라우드로 이동하려는 비즈니스 크리티컬 데이터가 포함된 SQL 데이터베이스가 있다고 가정하겠습니다.  BlueXP에서 데이터 복제를 사용하여 데이터를 마이그레이션할 수 있으며, 마이그레이션 프로세스의 일부로 클라우드에서 스냅샷 복사본에 대한 최신 온프레미스 정책을 설정할 수 있습니다.
