---
permalink: concepts/thin-provisioning-concept.html 
sidebar: sidebar 
keywords: thin provision 
summary: 씬 프로비저닝된 볼륨 또는 LUN은 스토리지가 미리 예약되지 않은 볼륨입니다. 대신 필요에 따라 스토리지가 동적으로 할당됩니다. 볼륨 또는 LUN의 데이터가 삭제되면 사용 가능한 공간이 스토리지 시스템으로 다시 해제됩니다. 
---
= 씬 프로비저닝
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP은 Snapshot 복사본에 더해 다양한 스토리지 효율성 기술을 제공합니다. 주요 기술에는 씬 프로비저닝, 중복제거, 압축 및 FlexClone 볼륨, 파일, 및 LUN을 누릅니다. 스냅샷 복사본과 마찬가지로 모든 기능을 ONTAP의 WAFL(Write Anywhere File Layout)에 구축할 수 있습니다.

씬 프로비저닝된 볼륨 또는 LUN은 스토리지가 미리 예약되지 않은 볼륨입니다. 대신 필요에 따라 스토리지가 동적으로 할당됩니다. 볼륨 또는 LUN의 데이터가 삭제되면 사용 가능한 공간이 스토리지 시스템으로 다시 해제됩니다.

귀사에서 5,000명의 사용자에게 홈 디렉토리용 스토리지를 제공해야 한다고 가정합니다. 가장 큰 홈 디렉토리는 1GB의 공간을 차지할 것으로 예상됩니다.

이 경우 5TB 물리적 스토리지를 구입할 수 있습니다. 홈 디렉토리를 저장하는 각 볼륨에 대해, 가장 큰 소비자의 요구를 충족시킬 수 있는 충분한 공간을 확보하게 됩니다.

그러나 현실적으로 홈 디렉토리 용량 요구 사항은 지역마다 크게 다르다는 점도 알고 있습니다. 모든 대용량 스토리지 사용자에게는 공간을 거의 또는 전혀 사용하지 않는 10명의 스토리지 관리자가 있습니다.

씬 프로비저닝을 사용하면 사용하지 않을 수도 있는 스토리지를 구입하지 않고도 대규모 스토리지 소비자의 요구를 충족할 수 있습니다. 스토리지 공간은 소비될 때까지 할당되지 않으므로 공칭 할당 기준으로 애그리게이트에 포함된 5,000개 볼륨 각각에 1GB 크기를 할당하여 2TB 애그리게이트를 "오버 커밋"할 수 있습니다.

사용량이 많은 사용자에 대한 10:1 비율의 광량이 있고 애그리게이트의 여유 공간을 모니터링하는 데 적극적인 역할을 수행하는 한 공간 부족으로 인해 볼륨 쓰기가 실패하지 않을 수 있습니다.
