---
permalink: error-messages/configure-webhooks-event-notifications-task.html 
sidebar: sidebar 
keywords: configure, important, ems, events, receive, email, notifications, forward, rest, api, webhook 
summary: 중요한 이벤트 알림을 Webhook 애플리케이션에 전달하도록 ONTAP를 구성할 수 있습니다. 필요한 구성 단계는 선택한 보안 수준에 따라 다릅니다. 
---
= Webhook 애플리케이션에 알림을 전달하도록 중요한 EMS 이벤트를 구성합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
중요한 이벤트 알림을 Webhook 애플리케이션에 전달하도록 ONTAP를 구성할 수 있습니다. 필요한 구성 단계는 선택한 보안 수준에 따라 다릅니다.



== EMS 이벤트 전달을 구성할 준비를 합니다

이벤트 알림을 웹 후크 응용 프로그램으로 전달하도록 ONTAP를 구성하기 전에 고려해야 할 몇 가지 개념과 요구 사항이 있습니다.



=== Webhook 응용 프로그램

ONTAP 이벤트 알림을 받을 수 있는 웹 후크 응용 프로그램이 필요합니다. Webhook은 사용자가 정의한 콜백 루틴으로, 이 루틴이 실행되는 원격 응용 프로그램 또는 서버의 기능을 확장합니다. Webhook는 대상 URL로 HTTP 요청을 전송하여 클라이언트(이 경우 ONTAP)에 의해 호출되거나 활성화됩니다. 특히 ONTAP는 웹 후크 응용 프로그램을 호스팅하는 서버에 HTTP POST 요청을 보내고 XML로 포맷된 이벤트 알림 세부 정보를 보냅니다.



=== 보안 옵션

TLS(Transport Layer Security) 프로토콜을 사용하는 방법에 따라 몇 가지 보안 옵션을 사용할 수 있습니다. 선택한 옵션에 따라 필요한 ONTAP 구성이 결정됩니다.

[NOTE]
====
TLS는 인터넷에서 널리 사용되는 암호화 프로토콜입니다. 하나 이상의 공개 키 인증서를 사용하여 개인 정보 보호와 데이터 무결성 및 인증을 제공합니다. 인증서는 신뢰할 수 있는 인증 기관에서 발급합니다.

====
HTTP:: HTTP를 사용하여 이벤트 알림을 전송할 수 있습니다. 이 구성에서는 연결이 안전하지 않습니다. ONTAP 클라이언트 및 웹 후크 응용 프로그램의 ID가 확인되지 않습니다. 또한 네트워크 트래픽은 암호화되거나 보호되지 않습니다. 을 참조하십시오 link:configure-webhooks-event-notifications-task.html#configure-a-webhook-destination-to-use-http["HTTP를 사용하도록 웹 후크 대상을 구성합니다"] 를 참조하십시오.
HTTPS:: 추가 보안을 위해 Webhook 루틴을 호스팅하는 서버에 인증서를 설치할 수 있습니다. ONTAP는 HTTPS 프로토콜을 사용하여 웹 후크 응용 프로그램 서버의 ID와 네트워크 트래픽의 개인 정보 보호와 무결성을 보장합니다. 을 참조하십시오 link:configure-webhooks-event-notifications-task.html#configure-a-webhook-destination-to-use-https["HTTPS를 사용하도록 웹 후크 대상을 구성합니다"] 를 참조하십시오.
상호 인증을 사용하는 HTTPS:: 웹북 요청을 실행하는 ONTAP 시스템에 클라이언트 인증서를 설치하여 HTTPS 보안을 강화할 수 있습니다. webhook 응용 프로그램 서버의 ID를 확인하고 네트워크 트래픽을 보호하는 ONTAP 외에도 webhook 응용 프로그램은 ONTAP 클라이언트의 ID를 확인합니다. 이 양방향 피어 인증을 _Mutual TLS_라고 합니다. 을 참조하십시오 link:configure-webhooks-event-notifications-task.html#configure-a-webhook-destination-to-use-https-with-mutual-authentication["상호 인증과 함께 HTTPS를 사용하도록 웹 후크 대상을 구성합니다"] 를 참조하십시오.


.관련 정보
* https://["TLS(Transport Layer Security) 프로토콜 버전 1.3"^]




== HTTP를 사용하도록 웹 후크 대상을 구성합니다

HTTP를 사용하여 웹 후크 응용 프로그램에 이벤트 알림을 전달하도록 ONTAP를 구성할 수 있습니다. 이 옵션은 가장 안전하지는 않지만 가장 간단한 설치 방법입니다.

.단계
. 이벤트를 수신할 새 대상 'restapi-EMS'를 생성합니다.
+
이벤트 알림 목적지 create-name restapi-ems-rest-api-url\http://<webhook-application>`

+
위 명령에서 대상에 대해 * HTTP * 체계를 사용해야 합니다.

. 중요 이벤트 필터를 "restapi-EMS" 대상으로 연결하는 알림 생성:
+
이벤트 알림 create-filter-name important-events-destinations reapi-EMS





== HTTPS를 사용하도록 웹 후크 대상을 구성합니다

HTTPS를 사용하여 이벤트 알림을 웹 후크 응용 프로그램으로 전달하도록 ONTAP를 구성할 수 있습니다. ONTAP는 서버 인증서를 사용하여 웹 후크 응용 프로그램의 ID를 확인하고 네트워크 트래픽을 보호합니다.

.시작하기 전에
* Webhook 응용 프로그램 서버에 대한 개인 키와 인증서를 생성합니다
* ONTAP에 설치할 수 있는 루트 인증서를 가지고 있어야 합니다


.단계
. 웹 후크 응용 프로그램을 호스팅하는 서버에 적절한 서버 개인 키와 인증서를 설치합니다. 특정 구성 단계는 서버에 따라 다릅니다.
. ONTAP에 서버 루트 인증서 설치:
+
보안 인증서설치형 server-ca

+
명령이 인증서를 요청합니다.

. 이벤트를 수신할 'restapi-EMS' 대상을 생성합니다.
+
이벤트 알림 목적지 create-name restapi-ems-rest-api-url\https://<webhook-application>`

+
위의 명령에서 대상에 대해 * HTTPS * 구성표를 사용해야 합니다.

. 중요 이벤트 필터를 새 restapi-EMS 대상과 연결하는 알림을 생성합니다.
+
이벤트 알림 create-filter-name important-events-destinations reapi-EMS





== 상호 인증과 함께 HTTPS를 사용하도록 웹 후크 대상을 구성합니다

상호 인증을 사용하여 HTTPS를 사용하여 이벤트 알림을 웹 후크 응용 프로그램에 전달하도록 ONTAP를 구성할 수 있습니다. 이 구성에는 두 개의 인증서가 있습니다. ONTAP는 서버 인증서를 사용하여 webhook 응용 프로그램의 ID를 확인하고 네트워크 트래픽을 보호합니다. 또한 webhook를 호스팅하는 응용 프로그램은 클라이언트 인증서를 사용하여 ONTAP 클라이언트의 ID를 확인합니다.

.시작하기 전에
ONTAP를 구성하기 전에 다음을 수행해야 합니다.

* Webhook 응용 프로그램 서버에 대한 개인 키와 인증서를 생성합니다
* ONTAP에 설치할 수 있는 루트 인증서를 가지고 있어야 합니다
* ONTAP 클라이언트에 대한 개인 키와 인증서를 생성합니다


.단계
. 작업의 처음 두 단계를 수행합니다 link:configure-webhooks-event-notifications-task.html#configure-a-webhook-destination-to-use-https["HTTPS를 사용하도록 웹 후크 대상을 구성합니다"] ONTAP가 서버의 ID를 확인할 수 있도록 서버 인증서를 설치합니다.
. 웹 후크 응용 프로그램에 적절한 루트 및 중간 인증서를 설치하여 클라이언트 인증서를 확인합니다.
. ONTAP에 클라이언트 인증서 설치:
+
보안 인증서 설치형 클라이언트

+
명령에서 개인 키와 인증서를 요청합니다.

. 이벤트를 수신할 'restapi-EMS' 대상을 생성합니다.
+
'이벤트 알림 대상 create-name restapi-EMS-REST-API-URL\https://<webhook-application> - certificate-authority <클라이언트 인증서 발급자> - certificate-serial <클라이언트 인증서 직렬>'

+
위의 명령에서 대상에 대해 * HTTPS * 구성표를 사용해야 합니다.

. 중요 이벤트 필터를 새 restapi-EMS 대상과 연결하는 알림을 생성합니다.
+
이벤트 알림 create-filter-name important-events-destinations reapi-EMS


