---
permalink: error-messages/configure-ems-events-notifications-syslog-task.html 
sidebar: sidebar 
keywords: configuring, important, ems, events, forward, notifications, syslog, server 
summary: syslog 서버에서 가장 심각한 이벤트의 알림을 기록하려면 중요한 활동을 나타내는 이벤트에 대한 알림을 전달하도록 EMS를 구성해야 합니다. 
---
= syslog 서버로 알림을 전달하도록 중요한 EMS 이벤트 구성
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
syslog 서버에서 가장 심각한 이벤트의 알림을 기록하려면 중요한 활동을 나타내는 이벤트에 대한 알림을 전달하도록 EMS를 구성해야 합니다.

syslog 서버 이름을 확인하기 위해 클러스터에 DNS를 구성해야 합니다.

환경에 이벤트 알림에 대한 syslog 서버가 아직 포함되어 있지 않은 경우 먼저 syslog 서버를 생성해야 합니다. 사용자 환경에 다른 시스템의 이벤트를 로깅하기 위한 syslog 서버가 이미 포함되어 있는 경우 중요한 이벤트 알림에 이 서버를 사용할 수 있습니다.

ONTAP CLI에서 명령을 입력하여 클러스터가 실행 중일 때마다 이 작업을 수행할 수 있습니다.

ONTAP 9.12.1부터 EMS 이벤트는 TLS(Transport Layer Security) 프로토콜을 통해 원격 syslog 서버의 지정된 포트로 전송될 수 있습니다. 두 가지 새로운 매개 변수를 사용할 수 있습니다.

`tcp-encrypted`:: 시기 `tcp-encrypted` 에 대해 지정됩니다 `syslog-transport`, ONTAP 는 해당 인증서를 검증하여 대상 호스트의 ID를 확인합니다. 기본값은 입니다 `udp-unencrypted`.
`syslog-port`:: 기본값입니다 `syslog-port` 매개 변수는 의 설정에 따라 다릅니다 `syslog-transport` 매개 변수. If(경우 `syslog-transport` 가 로 설정되어 있습니다 `tcp-encrypted`, `syslog-port` 기본값은 6514입니다.


자세한 내용은 를 참조하십시오 `event notification destination create` Man 페이지.

.단계
. 중요한 이벤트에 대한 syslog 서버 대상을 생성합니다.
+
`event notification destination create -name _syslog-ems_ -syslog _syslog-server-address_ -syslog-transport {udp-unencrypted|tcp-unencrypted|tcp-encrypted}`

+
ONTAP 9.12.1부터 에 대해 다음 값을 지정할 수 있습니다 `syslog-transport`:

+
** `udp-unencrypted` 보안 기능이 없는 사용자 데이터그램 프로토콜
** `tcp-unencrypted` 보안 기능이 없는 전송 제어 프로토콜
** `tcp-encrypted` 전송 계층 보안(TLS)이 있는 전송 제어 프로토콜


+
기본 프로토콜은 입니다 `udp-unencrypted``.

. syslog 서버로 알림을 전달할 중요 이벤트를 구성합니다.
+
`event notification create -filter-name _important-events_ -destinations _syslog-ems_`


