---
permalink: nfs-admin/access-cache-parameters-work-concept.html 
sidebar: sidebar 
keywords: access, cache, parameter, work 
summary: 여러 매개 변수는 액세스 캐시의 항목에 대한 새로 고침 기간을 제어합니다. 이러한 매개 변수의 작동 방식을 이해하면 액세스 캐시를 조정하고 저장된 정보의 최근 성능과 균형을 유지하도록 매개 변수를 수정할 수 있습니다. 
---
= 액세스 캐시 매개 변수의 작동 방식
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
여러 매개 변수는 액세스 캐시의 항목에 대한 새로 고침 기간을 제어합니다. 이러한 매개 변수의 작동 방식을 이해하면 액세스 캐시를 조정하고 저장된 정보의 최근 성능과 균형을 유지하도록 매개 변수를 수정할 수 있습니다.

액세스 캐시는 볼륨 또는 qtree에 액세스하려는 클라이언트에 적용되는 하나 이상의 엑스포트 규칙으로 구성된 항목을 저장합니다. 이러한 항목은 새로 고쳐지기 전에 일정 시간 동안 저장됩니다. 새로 고침 시간은 액세스 캐시 매개 변수에 의해 결정되며 액세스 캐시 항목의 유형에 따라 달라집니다.

개별 SVM에 대한 액세스 캐시 매개 변수를 지정할 수 있습니다. 따라서 SVM 액세스 요구사항에 따라 매개 변수가 달라질 수 있습니다. 활성 상태로 사용되지 않는 액세스 캐시 항목은 새로 고쳐지지 않으므로 외부 이름 서비스와의 불필요한 소모적인 통신이 줄어듭니다.

[cols="30,40,30"]
|===


| 액세스 캐시 항목 유형입니다 | 설명 | 새로 고침 기간(초 


 a| 
양의 입력
 a| 
액세스 캐시 항목으로 인해 클라이언트에 대한 액세스 거부가 발생되지 않았습니다.
 a| 
최소: 300

최대: 86,400

기본값: 3,600



 a| 
음수 항목
 a| 
액세스 캐시 항목으로 인해 클라이언트에 대한 액세스 거부가 발생했습니다.
 a| 
최소: 60

최대: 86,400

기본값: 3,600

|===
.예
NFS 클라이언트가 클러스터의 볼륨에 액세스하려고 합니다. ONTAP는 클라이언트를 엑스포트 정책 규칙과 일치시키고 클라이언트가 엑스포트 정책 규칙 구성에 따라 액세스할 수 있는지 확인합니다. ONTAP는 액세스 캐시에 있는 내보내기 정책 규칙을 양의 항목으로 저장합니다. 기본적으로 ONTAP는 액세스 캐시의 양의 항목을 1시간(3,600초) 동안 유지한 다음 해당 항목을 자동으로 새로 고쳐 정보를 최신 상태로 유지합니다.

액세스 캐시가 불필요하게 가득 차는 것을 방지하기 위해 특정 기간 동안 사용하지 않은 기존 액세스 캐시 항목을 지우기 위한 추가 매개 변수가 있습니다. 이 '-하비스트-timeout' 매개 변수는 허용되는 범위는 60초에서 2,592,000초이며 기본 설정은 86,400초입니다.
