---
permalink: nfs-admin/configure-number-group-ids-allowed-nfs-users-task.html 
sidebar: sidebar 
keywords:  
summary: '기본적으로 ONTAP는 Kerberos\(RPCSEC_GSS\) 인증을 사용하여 NFS 사용자 자격 증명을 처리할 때 최대 32개의 그룹 ID를 지원합니다. AUTH_SYS 인증을 사용하는 경우 RFC 5531에 정의된 대로 기본 최대 그룹 ID 수는 16입니다. 기본 그룹 수보다 많은 그룹의 구성원인 사용자가 있는 경우 최대 1,024개까지 늘릴 수 있습니다.' 
---
= NFS 사용자에게 허용되는 그룹 ID 수를 구성합니다
:icons: font
:imagesdir: ../media/


[role="lead"]
기본적으로 ONTAP는 Kerberos(RPCSEC_GSS) 인증을 사용하여 NFS 사용자 자격 증명을 처리할 때 최대 32개의 그룹 ID를 지원합니다. AUTH_SYS 인증을 사용하는 경우 RFC 5531에 정의된 대로 기본 최대 그룹 ID 수는 16입니다. 기본 그룹 수보다 많은 그룹의 구성원인 사용자가 있는 경우 최대 1,024개까지 늘릴 수 있습니다.

사용자의 자격 증명에 기본 그룹 ID 수보다 많은 수의 그룹 ID가 있는 경우 나머지 그룹 ID가 잘리고 스토리지 시스템에서 파일을 액세스하려고 할 때 오류가 발생할 수 있습니다. SVM당 최대 그룹 수를 환경의 최대 그룹을 나타내는 숫자로 설정해야 합니다.

다음 표는 세 가지 샘플 구성에서 최대 그룹 ID 수를 결정하는 "vserver NFS modify" 명령의 두 가지 매개 변수를 보여 줍니다.

[cols="40,30,30"]
|===


| 매개 변수 | 설정 | 결과 그룹 ID 제한 


 a| 
'-확장-그룹-제한'

``auth-sys-extended-groups’’
 a| 
32인치

'비활성화'입니다

기본 설정입니다.
 a| 
RPCSEC_GSS:32

AUTH_SYS:16



 a| 
'-확장-그룹-제한'

``auth-sys-extended-groups’’
 a| 
256입니다

'비활성화'입니다
 a| 
RPCSEC_GSS:256

AUTH_SYS:16



 a| 
'-확장-그룹-제한'

``auth-sys-extended-groups’’
 a| 
512

"활성화됨"
 a| 
RPCSEC_GSS:512

AUTH_SYS:512

|===
[NOTE]
====
일부 이전 NFS 클라이언트는 AUTH_SYS 확장 그룹과 호환되지 않을 수 있습니다.

====
.단계
. 권한 수준을 고급으로 설정합니다.
+
세트 프리빌리지 고급

. 원하는 작업을 수행합니다.
+
|===


| 허용된 보조 그룹의 최대 수를 설정하려면... | 명령 입력... 


 a| 
RPCSEC_GSS에만 해당하고 AUTH_SYS는 기본값 16으로 설정된 상태로 둡니다
 a| 
'+vserver nfs modify -vserver vserver_name -extended-groups-limit{32-1024} -auth-sys-extended-groups disabled+'



 a| 
RPCSEC_GSS 및 AUTH_SYS의 경우
 a| 
'+vserver nfs modify -vserver vserver_name -extended-groups-limit{32-1024} -auth-sys-extended-groups enabled+'

|===
. '-extended-groups-limit' 값을 확인하고 AUTH_SYS가 확장된 그룹('vserver nfs show -vserver vserver_name -fields auth-sys-extended-groups, extended-groups-limit')을 사용하고 있는지 확인합니다
. 관리자 권한 레벨로 돌아갑니다.
+
'Set-Privilege admin'입니다



다음 예에서는 AUTH_SYS 인증에 대해 확장된 그룹을 활성화하고, AUTH_SYS 및 RPCSEC_GSS 인증에 대해 확장 그룹의 최대 수를 512로 설정합니다. 이러한 변경은 VS1 이라는 SVM에 액세스하는 클라이언트에만 적용됩니다.

[listing]
----
vs1::> set -privilege advanced
Warning: These advanced commands are potentially dangerous; use
         them only when directed to do so by NetApp personnel.
Do you want to continue? {y|n}: y

vs1::*> vserver nfs modify -vserver vs1 -auth-sys-extended-groups enabled -extended-groups-limit 512

vs1::*> vserver nfs show -vserver vs1 -fields auth-sys-extended-groups,extended-groups-limit
vserver auth-sys-extended-groups extended-groups-limit
------- ------------------------ ---------------------
vs1     enabled                  512

vs1::*> set -privilege admin
----