---
permalink: nfs-admin/configure-character-mappings-smb-file-translation-task.html 
sidebar: sidebar 
keywords: configure, character, mapping, smb, file, name, translation, volume 
summary: NFS 클라이언트는 SMB 클라이언트 및 특정 Windows 애플리케이션에 유효하지 않은 문자를 포함하는 파일 이름을 생성할 수 있습니다. SMB 클라이언트가 유효하지 않은 NFS 이름의 파일에 액세스할 수 있도록 볼륨의 파일 이름 변환에 대한 문자 매핑을 구성할 수 있습니다. 
---
= 볼륨에서 SMB 파일 이름 변환에 대한 문자 매핑을 구성합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NFS 클라이언트는 SMB 클라이언트 및 특정 Windows 애플리케이션에 유효하지 않은 문자를 포함하는 파일 이름을 생성할 수 있습니다. SMB 클라이언트가 유효하지 않은 NFS 이름의 파일에 액세스할 수 있도록 볼륨의 파일 이름 변환에 대한 문자 매핑을 구성할 수 있습니다.

.이 작업에 대해
NFS 클라이언트가 생성한 파일을 SMB 클라이언트가 액세스할 때 ONTAP는 파일 이름을 찾습니다. 이름이 유효한 SMB 파일 이름이 아닌 경우(예: 포함된 콜론 "":" 문자가 있는 경우) ONTAP는 각 파일에 대해 유지되는 8.3 파일 이름을 반환합니다. 그러나 이로 인해 중요한 정보를 긴 파일 이름으로 인코딩하는 응용 프로그램에 문제가 발생합니다.

따라서 다른 운영 체제의 클라이언트 간에 파일을 공유하는 경우 두 운영 체제 모두에서 유효한 파일 이름에 문자를 사용해야 합니다.

그러나 SMB 클라이언트에 대해 유효한 파일 이름이 아닌 문자를 포함하는 파일 이름을 생성하는 NFS 클라이언트가 있는 경우, 잘못된 NFS 문자를 SMB 및 특정 Windows 애플리케이션이 허용하는 유니코드 문자로 변환하는 맵을 정의할 수 있습니다. 예를 들어, 이 기능은 CATIA MCAD 및 Mathematica 응용 프로그램과 이 요구 사항이 있는 다른 응용 프로그램을 지원합니다.

볼륨별로 문자 매핑을 구성할 수 있습니다.

볼륨에 문자 매핑을 구성할 때 다음 사항을 염두에 두어야 합니다.

* 문자 매핑이 교차점에 적용되지 않습니다.
+
각 접합 볼륨에 대해 문자 매핑을 명시적으로 구성해야 합니다.

* 올바르지 않거나 잘못된 문자를 나타내는 데 사용되는 유니코드 문자가 파일 이름에 일반적으로 나타나지 않는 문자인지 확인해야 합니다. 그렇지 않으면 원치 않는 매핑이 발생합니다.
+
예를 들어 콜론(:)을 하이픈(-)에 매핑하려고 하지만 파일 이름에 하이픈(-)이 올바르게 사용된 경우 ""a-b""라는 파일에 액세스하려는 Windows 클라이언트의 요청이 ""a:b""(원하는 결과가 아님)의 NFS 이름에 매핑됩니다.

* 문자 매핑을 적용한 후에도 매핑에 여전히 잘못된 Windows 문자가 포함되어 있으면 ONTAP는 Windows 8.3 파일 이름으로 다시 돌아갑니다.
* FPolicy 알림, NAS 감사 로그, 보안 추적 메시지에 매핑된 파일 이름이 표시됩니다.
* DP 유형의 SnapMirror 관계가 생성될 때 소스 볼륨의 문자 매핑이 대상 DP 볼륨에 복제되지 않습니다.
* 대소문자 구분: 매핑된 Windows 이름이 NFS 이름으로 전환되기 때문에 이름 조회는 NFS 의미를 따릅니다. 여기에는 NFS 조회가 대/소문자를 구분한다는 사실도 포함됩니다. 즉, 매핑된 공유에 액세스하는 응용 프로그램이 대/소문자를 구분하지 않는 Windows 동작에 의존해서는 안 됩니다. 그러나 8.3 이름은 사용할 수 있으며 대/소문자를 구분하지 않습니다.
* 부분 매핑 또는 잘못된 매핑: 이름을 매핑하여 디렉터리 열거("dir")를 수행하는 클라이언트로 반환하면 결과 유니코드 이름이 Windows 유효성을 검사합니다. 이름에 여전히 잘못된 문자가 있거나 Windows에 유효하지 않은 경우(예: "." 또는 공백으로 끝나는 경우) 잘못된 이름 대신 8.3 이름이 반환됩니다.


.단계
. 문자 매핑 구성:
+
'+vserver cifs character-mapping create-vserver vserver_name-volume volume_name-mapping mapping_text,...+'

+
매핑은 "":"로 구분된 소스-타겟 문자 쌍 목록으로 구성됩니다. 문자는 16진수를 사용하여 입력한 유니코드 문자입니다. 예: 3C:E03C.

+
콜론으로 구분된 각 mapping_text 쌍의 첫 번째 값은 번역할 NFS 문자의 16진수 값이고 두 번째 값은 SMB가 사용하는 유니코드 값입니다. 매핑 쌍은 고유해야 합니다(일대일 매핑이 있어야 함).

+
** 소스 매핑
+
다음 표에서는 소스 매핑에 사용할 수 있는 유니코드 문자 집합을 보여 줍니다.

+
[cols="20,20,60"]
|===


| 유니코드 문자입니다 | 인쇄된 문자 | 설명 


 a| 
0x01-0x19
 a| 
해당 없음
 a| 
인쇄할 수 없는 제어 문자입니다



 a| 
0x5C
 a| 
\
 a| 
백슬래시



 a| 
0x3A
 a| 
:
 a| 
결장



 a| 
0x2A
 a| 
*
 a| 
별표



 a| 
0x3F
 a| 
?
 a| 
물음표



 a| 
0x22
 a| 
"
 a| 
인용 부호가 있습니다



 a| 
0x3C
 a| 
를 누릅니다
 a| 
보다 작음



 a| 
0x3E
 a| 
를 누릅니다
 a| 
보다 큼



 a| 
0x7C
 a| 
|
 a| 
세로선



 a| 
0xB1
 a| 
±
 a| 
더하기 - 빼기 기호

|===
** 타겟 매핑
+
U+E0000...U+F8FF 범위의 유니코드 "전용 용도 영역"에서 대상 문자를 지정할 수 있습니다.





.예
다음 명령을 실행하면 SVM(스토리지 가상 시스템) VS1 에서 "data"라는 이름의 볼륨에 대한 문자 매핑이 생성됩니다.

[listing]
----
cluster1::> vserver cifs character-mapping create -volume data -mapping 3c:e17c,3e:f17d,2a:f745
cluster1::> vserver cifs character-mapping show

Vserver         Volume Name  Character Mapping
--------------  -----------  ------------------------------------------
vs1             data         3c:e17c, 3e:f17d, 2a:f745
----