---
permalink: nfs-admin/control-root-user-access-ntfs-security-data-task.html 
sidebar: sidebar 
keywords: control, root, user, access, ntfs, security, style, data 
summary: 'NFS 클라이언트가 NTFS 보안 스타일 데이터에 액세스하고 NTFS 클라이언트가 NFS 보안 스타일 데이터에 액세스할 수 있도록 ONTAP를 구성할 수 있습니다. NFS 데이터 저장소에서 NTFS 보안 스타일을 사용하는 경우 루트 사용자가 액세스를 처리하는 방법을 결정하고 이에 따라 SVM(스토리지 가상 머신)을 구성해야 합니다.' 
---
= NTFS 보안 스타일 데이터에 대한 루트 사용자 액세스를 제어합니다
:icons: font
:imagesdir: ../media/


[role="lead"]
NFS 클라이언트가 NTFS 보안 스타일 데이터에 액세스하고 NTFS 클라이언트가 NFS 보안 스타일 데이터에 액세스할 수 있도록 ONTAP를 구성할 수 있습니다. NFS 데이터 저장소에서 NTFS 보안 스타일을 사용하는 경우 루트 사용자가 액세스를 처리하는 방법을 결정하고 이에 따라 SVM(스토리지 가상 머신)을 구성해야 합니다.

루트 사용자가 NTFS 보안 스타일 데이터에 액세스할 때 다음 두 가지 옵션이 있습니다.

* 다른 NFS 사용자와 마찬가지로 루트 사용자를 Windows 사용자에게 매핑하고 NTFS ACL에 따라 액세스를 관리합니다.
* NTFS ACL을 무시하고 루트에 대한 전체 액세스를 제공합니다.


.단계
. 권한 수준을 고급으로 설정합니다.
+
세트 프리빌리지 고급

. 원하는 작업을 수행합니다.
+
[cols="35,65"]
|===


| 루트 사용자가 다음을 수행할 수 있도록 하려면... | 명령 입력... 


 a| 
Windows 사용자에게 매핑되어야 합니다
 a| 
'vserver nfs modify -vserver vserver_name -ignore -nt-acl-for-root disabled'



 a| 
NT ACL 검사를 생략합니다
 a| 
'vserver nfs modify -vserver vserver_name -ignore -nt-acl-for-root enabled'

|===
+
기본적으로 이 매개 변수는 사용되지 않습니다.

+
이 매개 변수가 설정되어 있지만 루트 사용자에 대한 이름 매핑이 없는 경우 ONTAP에서는 감사를 위해 기본 SMB 관리자 자격 증명을 사용합니다.

. 관리자 권한 레벨로 돌아갑니다.
+
'Set-Privilege admin'입니다


