---
permalink: nfs-admin/enable-ldap-rfc2307bis-support-task.html 
sidebar: sidebar 
keywords: enable, ldap, rfc2307bis, support 
summary: LDAP를 사용하고 중첩된 그룹 구성원을 사용하는 추가 기능이 필요한 경우 ONTAP를 구성하여 LDAP RFC2307bis 지원을 활성화할 수 있습니다. 
---
= LDAP RFC2307bis 지원을 활성화합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
LDAP를 사용하고 중첩된 그룹 구성원을 사용하는 추가 기능이 필요한 경우 ONTAP를 구성하여 LDAP RFC2307bis 지원을 활성화할 수 있습니다.

.필요한 것
사용할 기본 LDAP 클라이언트 스키마 중 하나의 복사본을 만들어야 합니다.

.이 작업에 대해
LDAP 클라이언트 스키마에서 그룹 개체는 memberUid 특성을 사용합니다. 이 속성은 여러 값을 포함할 수 있으며 해당 그룹에 속한 사용자의 이름을 나열합니다. RFC2307bis가 활성화된 LDAP 클라이언트 스키마에서 그룹 객체는 uniqueMember 속성을 사용합니다. 이 속성은 LDAP 디렉토리에 있는 다른 개체의 전체 DN(고유 이름)을 포함할 수 있습니다. 이렇게 하면 그룹이 다른 그룹을 구성원으로 포함할 수 있으므로 중첩된 그룹을 사용할 수 있습니다.

사용자는 중첩된 그룹을 포함하여 256개 이상의 그룹의 구성원이 아니어야 합니다. ONTAP는 256 그룹 제한을 초과하는 모든 그룹을 무시합니다.

기본적으로 RFC2307bis 지원은 비활성화되어 있습니다.

[NOTE]
====
RFC2307bis 지원은 MS-AD-BIS 스키마를 사용하여 LDAP 클라이언트를 생성할 때 ONTAP에서 자동으로 활성화됩니다.

====
자세한 내용은 을 참조하십시오 https://["NetApp 기술 보고서 4835: ONTAP에서 LDAP를 구성하는 방법"].

.단계
. 권한 수준을 고급으로 설정합니다.
+
세트 프리빌리지 고급

. RFC2307 LDAP 클라이언트 스키마를 수정하여 RFC2307bis 지원을 활성화합니다.
+
'vserver services name-service ldap client schema modify -vserver vserver_name -schema schema -name -enable -rfc2307bis true'

. LDAP 서버에서 지원되는 객체 클래스와 일치하도록 스키마를 수정합니다.
+
'vserver services name-service ldap client schema modify -vserver vserver -name -schema schema_name -group-of-unique-names-object-class object_class'

. LDAP 서버에서 지원되는 속성 이름과 일치하도록 스키마를 수정합니다.
+
'vserver services name-service ldap client schema modify -vserver vserver -name -schema schema_name -unique-member-attribute attribute_name'

. 관리자 권한 레벨로 돌아갑니다.
+
'Set-Privilege admin'입니다


