---
permalink: nfs-admin/modify-credential-cache-time-to-live-reference.html 
sidebar: sidebar 
keywords: reason, modify, nfs, credential, cache, time, live 
summary: 'NFS 자격 증명 캐시 TTL(Time-to-Live)을 수정하면 문제를 해결하는 데 도움이 되는 몇 가지 시나리오가 있습니다. 이러한 시나리오가 무엇인지, 그리고 이러한 수정 결과로 초래되는 결과를 이해해야 합니다.' 
---
= NFS 자격 증명 캐시 라이브 시간 수정 이유
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP는 보다 빠른 액세스를 제공하고 성능을 향상시키기 위해 자격 증명 캐시를 사용하여 NFS 내보내기 액세스에 대한 사용자 인증에 필요한 정보를 저장합니다. 자격 증명 캐시에 정보가 저장되는 기간을 구성하여 사용자 환경에 맞게 정보를 사용자 지정할 수 있습니다.

NFS 자격 증명 캐시 TTL(Time-to-Live)을 수정하면 문제를 해결하는 데 도움이 되는 몇 가지 시나리오가 있습니다. 이러한 시나리오가 무엇인지, 그리고 이러한 수정 결과로 초래되는 결과를 이해해야 합니다.



== 이유

다음과 같은 경우 기본 TTL을 변경하십시오.

[cols="2*"]
|===
| 문제 | 구제 조치 


 a| 
사용자 환경의 네임 서버에서 ONTAP의 요청 로드가 높기 때문에 성능이 저하됩니다.
 a| 
캐시된 양의 자격 증명과 음의 자격 증명에 대한 TTL을 늘려 ONTAP에서 이름 서버로 보내는 요청 수를 줄입니다.



 a| 
이름 서버 관리자가 이전에 거부된 NFS 사용자에 대한 액세스를 허용하도록 변경되었습니다.
 a| 
캐시된 음수 자격 증명에 대한 TTL을 줄여 NFS 사용자가 외부 이름 서버에서 새 자격 증명을 요청할 때까지 ONTAP를 기다려야 하는 시간을 줄임으로써 액세스 권한을 얻을 수 있습니다.



 a| 
이름 서버 관리자가 이전에 허용된 NFS 사용자에 대한 액세스를 거부하도록 변경되었습니다.
 a| 
캐시된 양의 자격 증명에 대한 TTL을 줄여 ONTAP가 외부 이름 서버에서 새 자격 증명을 요청하는 시간을 줄임으로써 NFS 사용자가 액세스를 거부하도록 합니다.

|===


== 결과

양의 자격 증명과 음수 자격 증명을 캐시하기 위해 시간을 개별적으로 수정할 수 있습니다. 그러나 그렇게 할 때의 장단점을 모두 알아야 합니다.

[cols="3*"]
|===
| 만약... | 장점은... | 단점은... 


 a| 
양의 자격 증명 캐시 시간을 늘립니다
 a| 
ONTAP는 이름 서버에 자격 증명 요청을 덜 자주 전송하여 이름 서버의 부하를 줄입니다.
 a| 
이전에는 액세스가 허용되었지만 더 이상 허용되지 않았던 NFS 사용자에 대한 액세스를 거부하는 데 시간이 더 오래 걸립니다.



 a| 
양의 자격 증명 캐시 시간을 줄입니다
 a| 
이전에는 액세스가 허용되었지만 이제는 그렇지 않은 NFS 사용자에 대한 액세스를 거부하는 데 걸리는 시간이 더 적게 걸립니다.
 a| 
ONTAP는 이름 서버에 자격 증명 요청을 더 자주 전송하여 이름 서버의 로드를 증가시킵니다.



 a| 
부정적인 자격 증명 캐시 시간을 늘립니다
 a| 
ONTAP는 이름 서버에 자격 증명 요청을 덜 자주 전송하여 이름 서버의 부하를 줄입니다.
 a| 
이전에는 액세스가 허용되지 않았지만 지금은 NFS 사용자에게 액세스 권한을 부여하는 데 시간이 더 오래 걸립니다.



 a| 
부정적인 자격 증명 캐시 시간을 줄입니다
 a| 
이전에는 액세스가 허용되지 않았지만 지금은 NFS 사용자에게 액세스 권한을 부여하는 데 시간이 더 적게 걸립니다.
 a| 
ONTAP는 이름 서버에 자격 증명 요청을 더 자주 전송하여 이름 서버의 로드를 증가시킵니다.

|===