---
permalink: nfs-admin/nfsv3-nfsv4-performance-tcp-transfer-size-concept.html 
sidebar: sidebar 
keywords: nfsv3, nfsv4, performance, improvement, modify, tcp, transfer, size 
summary: TCP 최대 전송 크기를 수정하여 지연 시간이 긴 네트워크를 통해 스토리지 시스템에 접속하는 NFSv3 및 NFSv4 클라이언트의 성능을 향상시킬 수 있습니다. 
---
= TCP 전송 크기를 수정하여 NFSv3 및 NFSv4 성능 향상
:icons: font
:imagesdir: ../media/


[role="lead"]
TCP 최대 전송 크기를 수정하여 지연 시간이 긴 네트워크를 통해 스토리지 시스템에 접속하는 NFSv3 및 NFSv4 클라이언트의 성능을 향상시킬 수 있습니다.

클라이언트가 지연 시간이 10밀리초 이상 인 WAN(Wide Area Network) 또는 MAN(Metro Area Network)과 같이 지연 시간이 긴 네트워크를 통해 스토리지 시스템에 액세스하는 경우 TCP 최대 전송 크기를 수정하여 연결 성능을 향상시킬 수 있습니다. LAN(Local Area Network)과 같이 지연 시간이 짧은 네트워크에서 스토리지 시스템에 액세스하는 클라이언트는 이러한 매개 변수를 수정해도 거의 이점을 얻을 수 없습니다. 처리량 향상이 지연 시간에 미치는 영향을 상쇄하지 않는다면 이러한 매개 변수를 사용해서는 안 됩니다.

스토리지 환경에서 이러한 매개 변수를 수정하여 이점을 얻을 수 있는지 확인하려면 먼저 성능이 떨어지는 NFS 클라이언트에 대한 포괄적인 성능 평가를 수행해야 합니다. 낮은 성능이 클라이언트에 대한 과도한 라운드 트립 지연 및 작은 요청 때문인지 검토합니다. 이러한 조건에서는 클라이언트와 서버가 사용 가능한 대역폭을 완전히 사용할 수 없습니다. 왜냐하면 대부분의 듀티 사이클이 연결을 통해 전송되는 작은 요청과 응답을 대기하는 데 소비하기 때문입니다.

NFSv3 및 NFSv4 요청 크기를 늘리면 클라이언트 및 서버에서 사용 가능한 대역폭을 보다 효율적으로 사용하여 단위 시간당 더 많은 데이터를 이동할 수 있으므로 연결의 전반적인 효율성이 향상됩니다.

스토리지 시스템과 클라이언트 간의 구성은 달라질 수 있습니다. 스토리지 시스템과 클라이언트는 전송 작업에 대해 최대 1MB의 크기를 지원합니다. 그러나 스토리지 시스템이 1MB의 최대 전송 크기를 지원하도록 구성했지만 클라이언트가 64KB만 지원하는 경우 마운트 전송 크기는 64KB 이하로 제한됩니다.

이러한 매개변수를 수정하기 전에 대용량 응답을 조립하고 전송하는 데 필요한 기간 동안 스토리지 시스템에 메모리가 추가로 소비된다는 점을 염두에 두어야 합니다. 스토리지 시스템에 대한 대기 시간이 많을수록 추가 메모리 소비량이 증가합니다. 메모리 용량이 큰 스토리지 시스템은 이 변경으로 인해 거의 영향을 주지 않을 수 있습니다. 메모리 용량이 낮은 스토리지 시스템에서 눈에 띄는 성능 저하가 발생할 수 있습니다.

이 매개 변수를 사용하는 것은 클러스터의 여러 노드에서 데이터를 검색하는 기능에 달려 있습니다. 클러스터 네트워크의 지연으로 인해 전반적인 응답 시간이 길어질 수 있습니다. 이러한 매개 변수를 사용하면 전반적인 지연 시간이 증가하는 경향이 있습니다. 따라서 지연 시간에 민감한 워크로드에 부정적인 영향이 나타날 수 있습니다.
