---
permalink: nfs-admin/ontap-secures-file-directory-access-concept.html 
sidebar: sidebar 
keywords: file, restriction 
summary: ONTAP은 세 가지 보안 수준을 평가하여 엔티티가 SVM에 있는 파일 및 디렉토리에 대해 요청된 작업을 수행할 수 있는 권한이 있는지 확인합니다. 액세스는 세 가지 보안 수준을 평가한 후 유효한 권한에 의해 결정됩니다. 
---
= 파일 기반 제한 사항
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP은 세 가지 보안 수준을 평가하여 엔티티가 SVM에 있는 파일 및 디렉토리에 대해 요청된 작업을 수행할 수 있는 권한이 있는지 확인합니다. 액세스는 세 가지 보안 수준을 평가한 후 유효한 권한에 의해 결정됩니다.

모든 스토리지 객체에는 최대 3가지 유형의 보안 계층이 포함될 수 있습니다.

* 내보내기(NFS) 및 공유(SMB) 보안
+
내보내기 및 공유 보안은 지정된 NFS 내보내기 또는 SMB 공유에 대한 클라이언트 액세스에 적용됩니다. 관리 권한이 있는 사용자는 SMB 및 NFS 클라이언트의 내보내기 및 공유 수준 보안을 관리할 수 있습니다.

* 스토리지 레벨 Access Guard 파일 및 디렉토리 보안
+
스토리지 레벨 액세스 가드 보안은 SMB 및 NFS 클라이언트가 SVM 볼륨에 액세스하는 데 적용됩니다. NTFS 액세스 권한만 지원됩니다. ONTAP에서 UNIX 사용자에 대한 보안 검사를 수행하여 스토리지 수준 액세스 가드가 적용된 볼륨의 데이터에 액세스하려면 UNIX 사용자는 볼륨을 소유한 SVM에서 Windows 사용자에게 매핑해야 합니다.

+
[NOTE]
====
NFS 또는 SMB 클라이언트의 파일 또는 디렉토리에 대한 보안 설정을 볼 경우 Storage-Level Access Guard 보안이 표시되지 않습니다. 시스템(Windows 또는 UNIX) 관리자도 클라이언트에서 스토리지 수준 액세스 가드 보안을 취소할 수 없습니다.

====
* NTFS, UNIX 및 NFSv4 네이티브 파일 레벨 보안
+
네이티브 파일 레벨 보안은 스토리지 객체를 나타내는 파일 또는 디렉토리에 존재합니다. 클라이언트에서 파일 수준 보안을 설정할 수 있습니다. 파일 권한은 SMB 또는 NFS를 사용하여 데이터를 액세스하든 관계없이 유효합니다.


