---
permalink: nfs-admin/ontap-export-policy-caches-concept.html 
sidebar: sidebar 
keywords: ontap, use, export, policy, cache 
summary: 시스템 성능을 개선하기 위해 ONTAP는 로컬 캐시를 사용하여 호스트 이름 및 넷그룹과 같은 정보를 저장합니다. 이렇게 하면 ONTAP에서 외부 소스에서 정보를 검색하는 것보다 내보내기 정책 규칙을 더 빠르게 처리할 수 있습니다. 캐시의 정의 및 작업을 이해하면 클라이언트 액세스 문제를 해결하는 데 도움이 됩니다. 
---
= ONTAP에서 엑스포트 정책 캐시를 사용하는 방법
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
시스템 성능을 개선하기 위해 ONTAP는 로컬 캐시를 사용하여 호스트 이름 및 넷그룹과 같은 정보를 저장합니다. 이렇게 하면 ONTAP에서 외부 소스에서 정보를 검색하는 것보다 내보내기 정책 규칙을 더 빠르게 처리할 수 있습니다. 캐시의 정의 및 작업을 이해하면 클라이언트 액세스 문제를 해결하는 데 도움이 됩니다.

NFS 내보내기에 대한 클라이언트 액세스를 제어하기 위해 엑스포트 정책을 구성합니다. 각 엑스포트 정책에는 규칙이 포함되어 있으며, 각 규칙에는 액세스를 요청하는 클라이언트와 규칙을 일치시키는 매개 변수가 포함되어 있습니다. 이러한 매개 변수 중 일부는 도메인 이름, 호스트 이름 또는 넷그룹과 같은 개체를 확인하기 위해 ONTAP에서 DNS 또는 NIS 서버와 같은 외부 소스에 연결해야 합니다.

외부 소스와의 이러한 통신에는 약간의 시간이 소요됩니다. 성능을 높이기 위해 ONTAP는 여러 캐시의 각 노드에 정보를 로컬로 저장하여 엑스포트 정책 규칙 개체를 해결하는 데 걸리는 시간을 단축합니다.

[cols="2*"]
|===
| 캐시 이름입니다 | 저장된 정보의 유형입니다 


 a| 
액세스
 a| 
해당 엑스포트 정책에 대한 클라이언트 매핑



 a| 
이름
 a| 
UNIX 사용자 이름을 해당 UNIX 사용자 ID에 매핑



 a| 
ID입니다
 a| 
UNIX 사용자 ID와 해당 UNIX 사용자 ID 및 확장 UNIX 그룹 ID의 매핑



 a| 
호스트
 a| 
호스트 이름을 해당 IP 주소에 매핑



 a| 
넷그룹
 a| 
구성원의 해당 IP 주소에 대한 넷그룹 매핑



 a| 
쇼마운트
 a| 
SVM 네임스페이스에서 내보낸 디렉토리 목록입니다

|===
ONTAP에서 검색 및 로컬에 저장한 후 환경에 있는 외부 이름 서버의 정보를 변경하면 캐시에 오래된 정보가 포함될 수 있습니다. ONTAP를 새로 고치면 특정 기간이 지나면 자동으로 캐시가 새로 고쳐지지만 다른 캐시에 만료 및 새로 고침 시간과 알고리즘이 다릅니다.

캐시에 오래된 정보가 포함되는 또 다른 가능한 이유는 ONTAP가 캐시된 정보를 새로 고치려고 하지만 이름 서버와 통신하려고 할 때 오류가 발생하는 것입니다. 이 경우 ONTAP는 클라이언트 중단을 방지하기 위해 로컬 캐시에 현재 저장되어 있는 정보를 계속 사용합니다.

따라서 성공해야 하는 클라이언트 액세스 요청이 실패하고 실패해야 하는 클라이언트 액세스 요청이 성공할 수 있습니다. 이러한 클라이언트 액세스 문제를 해결할 때 일부 엑스포트 정책 캐시를 보고 수동으로 플러시할 수 있습니다.
