---
permalink: nfs-admin/ontap-support-nfsv42-concept.html 
sidebar: sidebar 
keywords: ontap, support, nfsv4.2, MAC-labelled NFS, extended attributes, xattrs 
summary: ONTAP 9.8부터 NFSv4.2 사용 클라이언트를 액세스할 수 있도록 NFSv4.2 프로토콜이 지원됩니다. 
---
= NFSv4.2에 대한 ONTAP 지원
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9.8부터 ONTAP는 NFSv4.2 사용 클라이언트에 대한 액세스를 허용하는 NFSv4.2 프로토콜을 지원합니다.

NFSv4.2는 ONTAP 9.9.1 이상에서 기본적으로 설정됩니다. ONTAP 9.8에서 을 지정하여 v4.2를 수동으로 활성화해야 합니다 `-v4.1` 옵션을 선택하고 로 설정합니다 `enabled` SVM(스토리지 가상 머신)에 NFS 서버를 생성할 때 또한 NFSv4.1을 활성화하면 클라이언트가 v4.2로 마운트된 상태에서 NFSv4.1 기능을 사용할 수 있습니다.

연속적인 ONTAP 릴리즈는 NFSv4.2 옵션 기능에 대한 지원을 확장합니다.

[cols="2*"]
|===
| 다음으로 시작... | NFSv4.2의 옵션 기능은 다음과 같습니다. 


| ONTAP 9.12.1  a| 
* NFS 확장 속성입니다
* Sparse 파일
* 공간 예약




| ONTAP 9.9.1 | MAC(Mandatory Access Control) 레이블 NFS 
|===


== NFS v4.2 보안 레이블

ONTAP 9.9.1부터 NFS 보안 레이블을 활성화할 수 있습니다. 기본적으로 비활성화되어 있습니다.

NFS v4.2 보안 레이블에서 ONTAP NFS 서버는 MAC(Mandatory Access Control)를 인식하여 클라이언트가 전송한 sec_label 특성을 저장 및 검색합니다.

자세한 내용은 을 참조하십시오 link:https://tools.ietf.org/html/rfc7204["RFC 7240"^].

ONTAP 9.12.1부터는 NDMP 덤프 작업에 NFS v4.2 보안 레이블이 지원됩니다. 이전 릴리즈의 파일 또는 디렉터리에서 보안 레이블이 발견되면 덤프가 실패합니다.

.단계
. 권한 설정을 고급으로 변경합니다.
+
[source, cli]
----
set -privilege advanced
----
. 보안 레이블 활성화:
+
[source, cli]
----
vserver nfs modify -vserver <svm_name> -v4.2-seclabel enabled
----




== NFS 확장 속성입니다

ONTAP 9.12.1부터 NFS 확장 특성(xattrs)이 기본적으로 사용하도록 설정됩니다.

확장 특성은 에 의해 정의된 표준 NFS 속성입니다 https://tools.ietf.org/html/rfc8276["RFC 8276"^] 최신 NFS 클라이언트에서 사용하도록 설정됩니다. 사용자 정의 메타데이터를 파일 시스템 객체에 연결하는 데 사용할 수 있으며 고급 보안 구축에 관심이 있습니다.

NFS 확장 속성은 현재 NDMP 덤프 작업에 지원되지 않습니다. 파일 또는 디렉토리에서 확장 속성이 발견되면 덤프는 진행되지만 해당 파일 또는 디렉토리의 확장 속성은 백업하지 않습니다.

확장 속성을 비활성화해야 하는 경우 를 사용하십시오 `vserver nfs modify -v4.2-xattrs disabled` 명령.
