---
permalink: nfs-admin/perform-access-check-netgroups-verify-domains-task.html 
sidebar: sidebar 
keywords: perform, strict, access, check, netgroup, verify, domain 
summary: '기본적으로 ONTAP는 넷그룹에 대한 클라이언트 액세스를 평가할 때 추가 검증을 수행합니다. 추가 검사를 통해 클라이언트 도메인이 SVM(스토리지 가상 시스템)의 도메인 구성과 일치하는지 확인합니다. 그렇지 않으면 ONTAP는 클라이언트 액세스를 거부합니다.' 
---
= 도메인을 확인하여 넷그룹에 대해 보다 엄격한 액세스 검사를 수행합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
기본적으로 ONTAP는 넷그룹에 대한 클라이언트 액세스를 평가할 때 추가 검증을 수행합니다. 추가 검사를 통해 클라이언트 도메인이 SVM(스토리지 가상 머신)의 도메인 구성과 일치하는지 확인합니다. 그렇지 않으면 ONTAP는 클라이언트 액세스를 거부합니다.

.이 작업에 대해
ONTAP에서 클라이언트 액세스에 대한 엑스포트 정책 규칙을 평가하고 엑스포트 정책 규칙에 넷그룹이 포함되어 있는 경우, ONTAP는 클라이언트의 IP 주소가 넷그룹에 속하는지 여부를 결정해야 합니다. 이를 위해 ONTAP는 DNS를 사용하여 클라이언트의 IP 주소를 호스트 이름으로 변환하고 FQDN(정규화된 도메인 이름)을 얻습니다.

넷그룹 파일에 호스트에 대한 짧은 이름만 나열되고 호스트에 대한 짧은 이름이 여러 도메인에 있는 경우 다른 도메인의 클라이언트가 이 검사 없이 액세스할 수 있습니다.

이를 방지하기 위해 ONTAP는 호스트의 DNS에서 반환된 도메인을 SVM용으로 구성된 DNS 도메인 이름 목록과 비교합니다. 일치하는 경우 액세스가 허용됩니다. 일치하지 않으면 액세스가 거부됩니다.

이 검증은 기본적으로 활성화되어 있습니다. 고급 권한 수준에서 사용할 수 있는 '-netgroup-dns-domain-search' 매개 변수를 수정하여 이 매개 변수를 관리할 수 있습니다.

.단계
. 권한 수준을 고급으로 설정합니다.
+
세트 프리빌리지 고급

. 원하는 작업을 수행합니다.
+
[cols="2*"]
|===
| 넷그룹에 대한 도메인 확인을 원할 경우... | 입력... 


 a| 
활성화됨
 a| 
'vserver nfs modify -vserver vserver_name -netgroup -dns -domain -search enabled'



 a| 
사용 안 함
 a| 
'vserver nfs modify -vserver vserver_name -netgroup -dns -domain -search disabled'

|===
. 권한 수준을 admin으로 설정합니다.
+
'Set-Privilege admin'입니다


