---
permalink: nfs-admin/verify-name-service-connections-task.html 
sidebar: sidebar 
keywords: verify, name, service, connection, dns, ldap, checker, check, configuration, configure 
summary: ONTAP 9.2부터는 DNS 및 LDAP 네임 서버가 ONTAP에 연결되어 있는지 확인할 수 있습니다. 이러한 명령은 admin 권한 수준에서 사용할 수 있습니다. 
---
= 네임 서비스 연결을 확인합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9.2부터는 DNS 및 LDAP 네임 서버가 ONTAP에 연결되어 있는지 확인할 수 있습니다. 이러한 명령은 admin 권한 수준에서 사용할 수 있습니다.

.이 작업에 대해
이름 서비스 구성 검사기를 사용하여 필요에 따라 유효한 DNS 또는 LDAP 네임 서비스 구성을 확인할 수 있습니다. 이러한 검증 검사는 명령줄 또는 System Manager에서 시작할 수 있습니다.

DNS 구성의 경우 모든 서버가 테스트되고 유효한 구성으로 간주되려면 해당 구성이 제대로 작동되어야 합니다. LDAP 구성의 경우 서버가 가동되는 한 구성이 유효합니다. 'ip-config-validation' 필드가 true(기본값 false)가 아닌 경우 이름 서비스 명령은 구성 검사기를 적용합니다.

.단계
. 적절한 명령을 사용하여 네임 서비스 구성을 확인합니다. UI는 구성된 서버의 상태를 표시합니다.
+
|===


| 확인하려면... | 이 명령 사용... 


 a| 
DNS 구성 상태입니다
 a| 
'vserver services name-service dns check'



 a| 
LDAP 구성 상태입니다
 a| 
'vserver services name-service ldap check'

|===
+
[listing]
----
cluster1::> vserver services name-service dns check -vserver vs0

Vserver         Name Server     Status  Status Details
--------------  --------------- ------- -------------------------
 vs0            10.11.12.13     up      Response time (msec): 55
 vs0            10.11.12.14     up      Response time (msec): 70
 vs0            10.11.12.15     down    Connection refused.
+---------------------------------------------------------------+
----
+
[listing]
----
cluster1::> vserver services name-service ldap check -vserver vs0

| Vserver: vs0                                                |
| Client Configuration Name: c1                               |
| LDAP Status: up                                             |
| LDAP Status Details: Successfully connected to LDAP server "10.11.12.13".                                              |
----
+
구성된 서버 중 하나(name-servers/ldap-servers)에 연결할 수 있고 서비스를 제공하는 경우 구성 검증이 성공적으로 수행됩니다. 일부 서버에 연결할 수 없는 경우 경고가 표시됩니다.


