---
sidebar: sidebar 
permalink: anti-ransomware/enable-task.html 
keywords: anti-ransomware overview, ransomware, security, introduce, autotonomous, protection, arp, detection, threat, attack, suspect, what ontap anti-ransomware detects, entropy, abnormal volume activity, extension conformity, how to recover data in after a ransomware attack, ransomware protection strategy 
summary: 자율적 랜섬웨어 방어는 학습 모드에서 활성화되어 워크로드 분석을 통해 정상 동작의 특성을 분석합니다. 활성 모드에서는 비정상적인 활동이 플래그 표시됩니다. 
---
= 자율주행 랜섬웨어 보호 활성화
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ONTAP 9.10.1.1부터 ARP(Autonomous 랜섬웨어Protection)는 새 볼륨이나 기존 볼륨에서 활성화할 수 있습니다. 먼저 학습 모드에서 ARP를 활성화하는데, 이 모드에서 시스템은 정상적인 동작을 특성화하기 위해 워크로드를 분석합니다. 기존 볼륨에서 ARP를 활성화하거나, 새 볼륨을 생성하고 ARP를 처음부터 활성화할 수 있습니다.

.이 작업에 대해
ARP는 항상 먼저 학습(또는 건식 실행) 모드에서 활성화해야 합니다. 활성 모드에서 시작하면 과도한 거짓 양성 보고서가 발생할 수 있습니다.

최소 30일 동안 ARP를 학습 모드로 실행하는 것이 좋습니다. ONTAP 9.13.1 부터 ARP는 최적의 학습 기간을 자동으로 결정하고 30일 이전에 발생할 수 있는 스위치를 자동화합니다. 자세한 내용은 을 참조하십시오 link:index.html#learning-and-active-modes["학습 및 활성 모드"].


NOTE: 기존 볼륨에서 학습 및 활성 모드는 볼륨의 기존 데이터가 아닌 새로 기록된 데이터에만 적용됩니다. ARP에 대해 볼륨이 활성화된 후 새 데이터를 기반으로 이전 일반 데이터 트래픽의 특성이 가정되기 때문에 기존 데이터는 스캔되고 분석되지 않습니다.

.시작하기 전에
* NFS나 SMB(또는 둘 다)에 대해 SVM(스토리지 VM)을 활성화해야 합니다.
* 를 클릭합니다 xref:index.html[올바른 라이센스입니다] ONTAP 버전용으로 설치해야 합니다.
* 클라이언트가 구성된 NAS 워크로드가 있어야 합니다.
* ARP를 설정하려는 볼륨은 보호되어야 하며 활성 상태여야 합니다 link:../concepts/namespaces-junction-points-concept.html["접합 경로"^].
* 볼륨이 100% 미만이어야 합니다.
* ARP 활동의 알림을 포함하는 e-메일 알림을 보내도록 EMS 시스템을 구성하는 것이 좋습니다. 자세한 내용은 을 참조하십시오 link:../error-messages/configure-ems-events-send-email-task.html["이메일 알림을 보내도록 EMS 이벤트를 구성합니다"^].
* ONTAP 9.13.1 부터는 ARP(Autonomous 랜섬웨어 보호) 구성에 2명 이상의 인증된 사용자 관리자가 필요할 수 있도록 MAV(Multi-admin verification)를 활성화하는 것이 좋습니다. 자세한 내용은 을 참조하십시오 link:../multi-admin-verify/enable-disable-task.html["다중 관리 검증을 활성화합니다"^].




== ARP를 활성화합니다

시스템 관리자 또는 ONTAP CLI를 사용하여 ARP를 사용하도록 설정할 수 있습니다.

[role="tabbed-block"]
====
.시스템 관리자
--
.단계
. 스토리지 > 볼륨 * 을 선택한 다음 보호할 볼륨을 선택합니다.
. 볼륨 * 개요의 * 보안 * 탭에서 * 상태 * 를 선택하여 * 안티 랜섬웨어 * 상자의 학습 모드에서 사용 안 함으로 전환합니다.
. 학습 기간이 끝나면 ARP를 활성 모드로 전환합니다.
+

NOTE: ONTAP 9.13.1 부터는 ARP가 최적의 학습 기간을 자동으로 결정하고 스위치를 자동화합니다. 가능합니다 link:../anti-ransomware/enable-default-task.html["연결된 스토리지 VM에서 이 설정을 해제합니다"] 학습 모드를 활성 모드로 제어하려면 수동으로 전환합니다.

+
.. 스토리지 > 볼륨 * 을 선택한 다음 활성 모드에 사용할 준비가 된 볼륨을 선택합니다.
.. 볼륨 * 개요의 * 보안 * 탭에서 * 랜섬웨어 방지 상자에서 * 활성 모드로 전환 * 을 선택합니다.


. Anti-랜섬웨어 * 상자에서 볼륨의 ARP 상태를 확인할 수 있습니다.
+
모든 볼륨에 대한 ARP 상태를 표시하려면 * Volumes * 창에서 * 표시/숨기기 * 를 선택한 다음 * Anti-랜섬웨어 * 상태가 선택되었는지 확인합니다.



--
.CLI를 참조하십시오
--
기존 볼륨과 새 볼륨에서 ARP를 활성화하는 경우 CLI를 사용하여 ARP를 활성화하는 프로세스가 다릅니다.

.기존 볼륨에서 ARP를 활성화합니다
. 학습 모드에서 랜섬웨어 보호를 활성화하려면 기존 볼륨을 수정하십시오.
+
'Security Anti-랜섬웨어 volume dry-run-volume_vol_name_-vserver_svm_name_'

+
ONTAP 9.13.1 이상을 실행 중인 경우 활성 상태로 자동 변경되도록 적응 학습이 활성화됩니다. 이 동작이 자동으로 활성화되지 않도록 하려면 모든 관련 볼륨에서 SVM 레벨에서 설정을 변경합니다.

+
`vserver modify _svm_name_ -anti-ransomware-auto-switch-from-learning-to-enabled false`

. 학습 기간이 끝나면 보호된 볼륨을 수정하여 아직 자동으로 실행되지 않은 경우 활성 모드로 전환합니다.
+
'Security Anti-랜섬웨어 volume enable-volume_vol_name_-vserver_svm_name_'

+
볼륨 수정 명령을 사용하여 활성 모드로 전환할 수도 있습니다.

+
'volume modify -volume_vol_name_-vserver_svm_name_-anti-랜섬웨어-state active

. 볼륨의 ARP 상태를 확인합니다.
+
'보안 안티 랜섬웨어 볼륨 쇼'



.새 볼륨에서 ARP를 활성화합니다
. 데이터를 프로비저닝하기 전에 랜섬웨어 방지 보호를 활성화한 상태로 새 볼륨을 생성하십시오.
+
'volume create-volume_vol_name_-vserver_svm_name_-aggregate_aggr_name_-size_nn_-anti-랜섬웨어-state dry-run-junction-path/_path_name_'

+
ONTAP 9.13.1 이상을 실행 중인 경우 활성 상태로 자동 변경되도록 적응 학습이 활성화됩니다. 이 동작이 자동으로 활성화되지 않도록 하려면 모든 관련 볼륨에서 SVM 레벨에서 설정을 변경합니다.

+
`vserver modify _svm_name_ -anti-ransomware-auto-switch-from-learning-to-enabled false`

. 학습 기간이 끝나면 보호된 볼륨을 수정하여 아직 자동으로 실행되지 않은 경우 활성 모드로 전환합니다.
+
'Security Anti-랜섬웨어 volume enable-volume_vol_name_-vserver_svm_name_'

+
볼륨 수정 명령을 사용하여 활성 모드로 전환할 수도 있습니다.

+
'volume modify -volume_vol_name_-vserver_svm_name_-anti-랜섬웨어-state active

. 볼륨의 ARP 상태를 확인합니다.
+
'보안 안티 랜섬웨어 볼륨 쇼'



--
====