---
sidebar: sidebar 
permalink: anti-ransomware/enable-task.html 
keywords: anti-ransomware overview, ransomware, security, introduce, protection, detection, threat, attack, suspect, what ontap anti-ransomware detects, entropy, abnormal volume activity, extension conformity, how to recover data in after a ransomware attack, ransomware protection strategy 
summary: 새로운 볼륨 또는 기존 볼륨에서 Anti-랜섬웨어를 활성화할 수 있습니다. 먼저 학습 모드에서 안티 랜섬웨어를 활성화하고 시스템이 워크로드를 분석하여 정상 동작을 특징화하는 다음, 비정상 작동이 평가를 위해 플래그 지정된 활성 모드로 전환합니다. 
---
= 랜섬웨어 방지 지원
:toc: macro
:hardbreaks:
:toclevels: 1
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
ONTAP 9.10.1.1부터는 새 볼륨이나 기존 볼륨에서 랜섬웨어 방지 보호를 활성화할 수 있습니다. 먼저 학습 모드에서 안티 랜섬웨어를 활성화하고 시스템이 워크로드를 분석하여 정상 동작을 특징화하는 다음, 비정상 작동이 평가를 위해 플래그 지정된 활성 모드로 전환합니다.

.무엇을 &#8217;필요로 할거야
* NFS 또는 SMB(또는 둘 다)에 대해 활성화된 스토리지 VM
* Multi-tenant Encryption Key Management(MT_EK_MGMT) 라이센스가 설치되었습니다.
* 클라이언트가 구성된 NAS 워크로드입니다.
* 보호할 볼륨에 활성 접합 경로가 있어야 합니다.
* 선택 사항이지만 권장됨: EMS 시스템은 랜섬웨어 방지 활동 알림을 포함한 이메일 알림을 보내도록 구성됩니다. 자세한 내용은 을 참조하십시오 link:../error-messages/configure-ems-events-send-email-task.html["이메일 알림을 보내도록 EMS 이벤트를 구성합니다"].


NetApp의 랜섬웨어 방지 기능은 초기 학습 기간("건식 실행"이라고도 함)을 포함하며, 이 경우 ONTAP 시스템은 유효한 파일 확장명을 학습하고 분석된 데이터를 사용하여 경고 프로필을 개발합니다. 학습 모드에서 안티 랜섬웨어를 충분히 실행하여 워크로드 특성을 평가한 후, 액티브 모드로 전환하고 데이터 보호를 시작할 수 있습니다. 안티 랜섬웨어는 지속적으로 데이터를 수집 및 분석하여 경고 프로필을 개선합니다.

학습 기간 동안 시스템은 구성된 볼륨의 워크로드 특성을 자동으로 학습하여 특수한 관찰 및 패턴 분석을 수행합니다.

30일의 학습 기간이 권장됩니다. 언제든지 학습에서 활성 모드로 전환할 수 있지만, 조기 전환으로 오탐률이 너무 많이 발생할 수 있습니다.

ONTAP CLI에서 security anti-랜섬웨어 volume workload-behavior show 명령을 사용하여 현재까지 감지된 파일 확장명을 표시할 수 있습니다. 그러나 이 도구를 사용하여 학습 기간을 단축해서는 안 됩니다.

기존 볼륨에서 랜섬웨어 보호를 활성화하거나 새 볼륨을 생성하고 처음부터 랜섬웨어 보호를 활성화할 수 있습니다.


NOTE: 기존 볼륨에서는 학습 및 활성 모드가 새로 작성된 데이터에만 적용되고 볼륨의 기존 데이터에는 적용되지 않습니다. 랜섬웨어 방지 기능을 활성화한 후 새 데이터를 기반으로 이전 일반 데이터 트래픽의 특성을 가정하기 때문에 기존 데이터는 스캔하고 분석되지 않습니다.

ONTAP CLI에서는 '보안 방지 랜섬웨어 볼륨'이라는 새로운 명령 제품군이 도입되었습니다. 또한 '-anti-랜섬웨어' 매개변수와 함께 'volume modify' 명령을 사용하여 이 기능을 관리할 수도 있습니다.



== System Manager 절차

. 스토리지 > 볼륨 * 을 클릭한 다음 보호할 볼륨을 선택합니다.
. 볼륨 개요의 보안 탭에서 * 상태 * 를 클릭하여 랜섬웨어 방지 상자의 학습 모드에서 사용 안 함 으로 전환합니다.
. 학습 기간이 끝나면 안티 랜섬웨어를 액티브 모드로 전환하십시오.
+
.. 스토리지 > 볼륨 * 을 클릭한 다음 활성 모드에 사용할 준비가 된 볼륨을 선택합니다.
.. 볼륨 개요의 보안 탭에서 * 랜섬웨어 방지 상자에서 * 활성 모드로 전환 * 을 클릭합니다.


. 언제든지 Anti-랜섬웨어 상자에서 볼륨의 안티 랜섬웨어 상태를 확인할 수 있습니다. 모든 볼륨의 랜섬웨어 방지 상태를 표시하려면 볼륨 창에서 * 표시/숨기기 * 를 클릭한 다음 랜섬웨어 방지 상태가 선택되었는지 확인합니다.




== CLI 절차

. 학습 모드에서 랜섬웨어 보호를 활성화하려면 기존 볼륨을 수정하십시오.
+
'Security Anti-랜섬웨어 volume dry-run-volume_vol_name_-vserver_svm_name_'

+
'volume modify' 명령을 사용하여 랜섬웨어도 활성화할 수 있습니다.

+
'volume modify -volume_vol_name_-vserver_svm_name_-anti-랜섬웨어-state dry-run

+
CLI에서 데이터를 프로비저닝하기 전에 랜섬웨어 방지 보호를 활성화한 상태로 새 볼륨을 생성할 수도 있습니다.

+
'volume create-volume_vol_name_-vserver_svm_name_-aggregate_aggr_name_-size_nn_-anti-랜섬웨어-state dry-run-junction-path/_path_name_'

+

NOTE: 처음에는 항상 건조한 상태에서 랜섬웨어를 활성화해야 합니다. 활성 상태부터 시작하여 과도한 거짓 양성 보고서로 이어질 수 있습니다.

. 학습 기간이 끝나면 보호된 볼륨을 수정하여 활성 모드로 전환합니다.
+
'Security Anti-랜섬웨어 volume enable-volume_vol_name_-vserver_svm_name_'

+
볼륨 수정 명령을 사용하여 활성 모드로 전환할 수도 있습니다.

+
'volume modify -volume_vol_name_-vserver_svm_name_-anti-랜섬웨어-state active

. 볼륨의 안티 랜섬웨어 상태를 확인하십시오.
+
'보안 안티 랜섬웨어 볼륨 쇼'


