---
sidebar: sidebar 
permalink: anti-ransomware/enable-task.html 
keywords: anti-ransomware overview, ransomware, security, introduce, autotonomous, protection, arp, detection, threat, attack, suspect, what ontap anti-ransomware detects, entropy, abnormal volume activity, extension conformity, how to recover data in after a ransomware attack, ransomware protection strategy 
summary: 'ARP(Autonomous 랜섬웨어 Protection)는 새 볼륨 또는 기존 볼륨에서 활성화할 수 있습니다. 먼저 학습 모드에서 ARP를 활성화하는데, 이 모드에서 시스템은 정상적인 동작을 특성화하기 위해 워크로드를 분석한 다음, 활성 모드로 전환하며, 이 모드에서 비정상적인 활동이 평가를 위해 플래그됩니다.' 
---
= 자율주행 랜섬웨어 보호 활성화
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
ONTAP 9.10.1.1부터 ARP(Autonomous 랜섬웨어Protection)는 새 볼륨이나 기존 볼륨에서 활성화할 수 있습니다. 먼저 학습 모드에서 ARP를 활성화하는데, 이 모드에서 시스템은 정상적인 동작을 특성화하기 위해 워크로드를 분석합니다. 그런 다음, 활성 모드로 전환하면 비정상 활동에 평가 플래그가 지정됩니다.

.필요한 것
* NFS 또는 SMB(또는 둘 다)에 대해 활성화된 스토리지 VM
* ONTAP 버전에 맞는 라이센스가 설치되어 있습니다.
+
[cols="2*"]
|===
| ONTAP 릴리스 | 라이센스 


 a| 
ONTAP 9.8-9.10.1
 a| 
Mt_EK_MGMT(멀티 테넌트 키 관리)



 a| 
ONTAP 9.11.1 이상
 a| 
안티 랜섬웨어

|===
* 클라이언트가 구성된 NAS 워크로드입니다.
* 보호할 볼륨에 활성 접합 경로가 있어야 합니다.
* 선택 사항이지만 권장됨: EMS 시스템은 ARP 활동의 알림을 포함하는 이메일 알림을 보내도록 구성됩니다. 자세한 내용은 을 참조하십시오 link:../error-messages/configure-ems-events-send-email-task.html["이메일 알림을 보내도록 EMS 이벤트를 구성합니다"].


.이 작업에 대해
NetApp ARP에는 ONTAP 시스템이 유효한 파일 확장명을 학습하고 분석된 데이터를 사용하여 경고 프로필을 개발하는 초기 학습 기간("건식 실행"이라고도 함)이 포함됩니다. 학습 모드에서 충분한 시간 동안 ARP를 실행하여 워크로드 특성을 평가한 후 활성 모드로 전환하고 데이터 보호를 시작할 수 있습니다. 활성 모드에서 파일 확장자가 비정상으로 플래그 지정되었지만 이를 평가하고 거짓 양성으로 표시하면 경고 프로필이 로 구체화되므로 이후 알림에서 확장자가 비정상으로 플래그 지정되지 않습니다.

언제든지 학습 모드에서 활성 모드로 전환할 수 있지만 30일의 학습 기간이 권장됩니다. 조기 전환으로 오탐률이 너무 많이 발생할 수 있습니다. ONTAP CLI에서 를 사용할 수 있습니다 `security anti-ransomware volume workload-behavior show` 현재까지 감지된 파일 확장자를 표시하는 명령입니다. 학습 기간을 단축하기 위해 이 도구를 사용하지 않는 것이 좋습니다.

기존 볼륨에서 ARP를 활성화하거나, 새 볼륨을 생성하고 ARP를 처음부터 활성화할 수 있습니다.


NOTE: 기존 볼륨에서는 학습 및 활성 모드가 새로 작성된 데이터에만 적용되고 볼륨의 기존 데이터에는 적용되지 않습니다. ARP에 대해 볼륨이 활성화된 후 새 데이터를 기반으로 이전 일반 데이터 트래픽의 특성이 가정되기 때문에 기존 데이터는 스캔되고 분석되지 않습니다.

ONTAP CLI에서 이 기능을 관리하려면 를 사용할 수 있습니다 `security anti-ransomware volume` 명령. 를 사용할 수도 있습니다 `volume modify` 명령과 함께 `-anti-ransomware` 매개 변수.

.단계
[role="tabbed-block"]
====
.시스템 관리자
--
. 스토리지 > 볼륨 * 을 클릭한 다음 보호할 볼륨을 선택합니다.
. 볼륨 * 개요의 * 보안 * 탭에서 * 상태 * 를 클릭하여 * 안티 랜섬웨어 * 상자의 학습 모드에서 사용 안 함 에서 사용으로 전환합니다.
. 학습 기간이 끝나면 ARP를 활성 모드로 전환합니다.
+
.. 스토리지 > 볼륨 * 을 클릭한 다음 활성 모드에 사용할 준비가 된 볼륨을 선택합니다.
.. 볼륨 * 개요의 * 보안 * 탭에서 * 랜섬웨어 방지 상자의 * 활성 모드로 전환 * 을 클릭합니다.


. 항상 * Anti-랜섬웨어 * 상자에서 볼륨의 ARP 상태를 확인할 수 있습니다. 모든 볼륨에 대한 ARP 상태를 표시하려면 * Volumes * 창에서 * 표시/숨기기 * 를 클릭한 다음 * Anti-랜섬웨어 * 상태가 선택되었는지 확인합니다.


--
.CLI를 참조하십시오
--
. 학습 모드에서 랜섬웨어 보호를 활성화하려면 기존 볼륨을 수정하십시오.
+
'Security Anti-랜섬웨어 volume dry-run-volume_vol_name_-vserver_svm_name_'

+
'volume modify' 명령을 사용하여 랜섬웨어도 활성화할 수 있습니다.

+
'volume modify -volume_vol_name_-vserver_svm_name_-anti-랜섬웨어-state dry-run

+
CLI에서 데이터를 프로비저닝하기 전에 랜섬웨어 방지 보호를 활성화한 상태로 새 볼륨을 생성할 수도 있습니다.

+
'volume create-volume_vol_name_-vserver_svm_name_-aggregate_aggr_name_-size_nn_-anti-랜섬웨어-state dry-run-junction-path/_path_name_'

+

NOTE: 처음에 항상 드라이 런 상태에서 ARP를 활성화해야 합니다. 활성 상태부터 시작하여 과도한 거짓 양성 보고서로 이어질 수 있습니다.

. 학습 기간이 끝나면 보호된 볼륨을 수정하여 활성 모드로 전환합니다.
+
'Security Anti-랜섬웨어 volume enable-volume_vol_name_-vserver_svm_name_'

+
볼륨 수정 명령을 사용하여 활성 모드로 전환할 수도 있습니다.

+
'volume modify -volume_vol_name_-vserver_svm_name_-anti-랜섬웨어-state active

. 볼륨의 ARP 상태를 확인합니다.
+
'보안 안티 랜섬웨어 볼륨 쇼'



--
====