---
sidebar: sidebar 
permalink: anti-ransomware/enable-task.html 
keywords: ransomware, arp, enable, set up, autonomous ransomware protection 
summary: 'ONTAP 9.10.1부터 신규 또는 기존 볼륨에서 ARP(자율적 랜섬웨어 방어)를 활성화할 수 있습니다.' 
---
= 자율주행 랜섬웨어 보호 활성화
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
ONTAP 9.10.1부터 기존 볼륨에서 ARP(자율적 랜섬웨어 방어)를 활성화하거나 새 볼륨을 생성한 후 처음부터 ARP를 활성화할 수 있습니다.

모든 새로운 볼륨이 기본적으로 자율적 랜섬웨어 방어(ARP)에 활성화되도록 ONTAP 클러스터를 구성하려면 다음을 참조하십시오.link:enable-default-task.html["관련 ARP 절차"]

.이 작업에 대해
* * ONTAP 9.10.1 ~ 9.15.1 및 FlexGroup 볼륨을 사용하는 ARP*의 경우 이러한 버전의 ONTAP에 대해 항상 (또는 "건식 실행" 모드)에서 ARP를 활성화해야 link:index.html#learning-and-active-modes["학습 모드"]합니다. 학습 모드에서 ARP를 처음 활성화하면 시스템이 워크로드를 분석하여 정상적인 동작을 특성화합니다. 활성 모드에서 시작하면 과도한 거짓 양성 보고서가 발생할 수 있습니다.
+
최소 30일 동안 ARP를 학습 모드로 실행하는 것이 좋습니다. ONTAP 9.13.1부터 ARP는 자동으로 최적의 학습 기간 간격을 결정하고 30일 이전에 발생할 수 있는 스위치를 자동화합니다.

* * ONTAP 9.16.1 이상의 경우 FlexVol 볼륨 * ARP를 활성화하면 ARP/AI 보호가 즉시 활성 모드에서 시작됩니다. 학습 기간은 필요하지 않습니다.



NOTE: 기존 볼륨에서 학습 및 활성 모드는 볼륨의 기존 데이터가 아닌 새로 기록된 데이터에만 적용됩니다. ARP에 대해 볼륨이 활성화된 후 새 데이터를 기반으로 이전 일반 데이터 트래픽의 특성이 가정되기 때문에 기존 데이터는 스캔되고 분석되지 않습니다.

.시작하기 전에
* NFS나 SMB(또는 둘 다)에 대해 SVM(스토리지 VM)을 활성화해야 합니다.
* ONTAP 버전용으로 이 xref:index.html#licenses-and-enablement[올바른 라이센스입니다]설치되어 있어야 합니다.
* 클라이언트가 구성된 NAS 워크로드가 있어야 합니다.
* ARP를 설정하려는 볼륨은 보호되고 활성 상태여야 link:../concepts/namespaces-junction-points-concept.html["접합 경로"]합니다.
* 볼륨이 100% 미만이어야 합니다.
* ARP 활동의 알림을 포함하는 e-메일 알림을 보내도록 EMS 시스템을 구성하는 것이 좋습니다. 자세한 내용은 을 link:../error-messages/configure-ems-events-send-email-task.html["이메일 알림을 보내도록 EMS 이벤트를 구성합니다"]참조하십시오.
* ONTAP 9.13.1 부터는 ARP(Autonomous 랜섬웨어 보호) 구성에 2명 이상의 인증된 사용자 관리자가 필요할 수 있도록 MAV(Multi-admin verification)를 활성화하는 것이 좋습니다. 자세한 내용은 을 link:../multi-admin-verify/enable-disable-task.html["다중 관리 검증을 활성화합니다"]참조하십시오.




== 새 볼륨이나 기존 볼륨에서 ARP를 활성화합니다

시스템 관리자 또는 ONTAP CLI를 사용하여 ARP를 사용하도록 설정할 수 있습니다.

[role="tabbed-block"]
====
.시스템 관리자
--
.단계
. 스토리지 > 볼륨 * 을 선택한 다음 보호할 볼륨을 선택합니다.
. 볼륨 * 개요의 * 보안 * 탭에서 * 상태 * 를 선택하여 비활성화에서 활성화로 전환합니다.
+
** ONTAP 9.15.1 이하 또는 ONTAP 9.16.1과 FlexGroup 볼륨을 함께 사용하는 경우 * 안티 랜섬웨어 * 상자에서 * 학습 모드에서 활성화 * 를 선택합니다.
+

NOTE: ONTAP 9.13.1 부터는 ARP가 최적의 학습 기간을 자동으로 결정하고 스위치를 자동화합니다. link:enable-default-task.html["연결된 스토리지 VM에서 이 설정을 해제합니다"]학습 모드를 활성 모드 전환으로 수동으로 제어하려는 경우

** ONTAP 9.16.1 이상의 FlexVol 볼륨에서 ARP를 사용하는 경우 ARP/AI 기능은 학습 기간이 필요하지 않으며 기본적으로 활성 모드가 선택됩니다.


. Anti-랜섬웨어 * 상자에서 볼륨의 ARP 상태를 확인할 수 있습니다.
+
모든 볼륨에 대한 ARP 상태를 표시하려면 * Volumes * 창에서 * Show/Hide * 를 선택한 다음 * Anti-Ransomware * 상태가 선택되어 있는지 확인합니다.



--
.CLI를 참조하십시오
--
기존 볼륨과 새 볼륨에서 ARP를 활성화하는 경우 CLI를 사용하여 ARP를 활성화하는 프로세스가 다릅니다.

.기존 볼륨에서 ARP를 활성화합니다
. 기존 볼륨을 수정하여 랜섬웨어 방지 지원:
+
** ONTAP 9.15.1 이하 및 FlexGroup 볼륨을 사용하는 ARP의 경우 볼륨 상태를 (학습 모드)로 설정합니다 `dry-run`.
+
`security anti-ransomware volume dry-run -volume <vol_name> -vserver <svm_name>`

** ARP/AI 및 FlexVol 볼륨이 있는 ONTAP 9.16.1 이상의 경우 볼륨 상태를 (활성 모드)로 설정합니다 `active`.
+
`security anti-ransomware volume active -volume <vol_name> -vserver <svm_name>`



. ONTAP 9.13.1 이상으로 업그레이드한 경우 ARP 기본 상태가 인 경우 `dry-run` 활성 상태로 자동 변경되도록 Adaptive Learning이 활성화됩니다. 이 동작이 자동으로 활성화되지 않도록 하려면 모든 관련 볼륨에서 SVM 레벨에서 설정을 변경합니다.
+
`vserver modify <svm_name> -anti-ransomware-auto-switch-from-learning-to-enabled false`

. 볼륨의 ARP 상태를 확인합니다.
+
'보안 안티 랜섬웨어 볼륨 쇼'



.새 볼륨에서 ARP를 활성화합니다
. 데이터를 프로비저닝하기 전에 ARP가 활성화된 새 볼륨을 생성합니다.
+
** ONTAP 9.15.1 이하 및 FlexGroup 볼륨을 사용하는 ARP의 경우 상태를 (학습 모드)로 설정합니다 `dry-run`.
+
`volume create -volume <vol_name> -vserver <svm_name> -aggregate <aggr_name> -size <nn> -anti-ransomware-state dry-run -junction-path </_path_name_>`

** ARP/AI 및 FlexVol 볼륨이 있는 ONTAP 9.16.1 이상의 경우 상태를 (활성 모드)로 설정합니다 `active`.
+
`volume create -volume <vol_name> -vserver <svm_name> -aggregate <aggr_name> -size <nn> -anti-ransomware-state active -junction-path </_path_name_>`



. ONTAP 9.13.1 이상으로 업그레이드한 경우 ARP 기본 상태가 인 경우 `dry-run` 활성 상태로 자동 변경되도록 Adaptive Learning이 활성화됩니다. 이 동작이 자동으로 활성화되지 않도록 하려면 모든 관련 볼륨에서 SVM 레벨에서 설정을 변경합니다.
+
`vserver modify <svm_name> -anti-ransomware-auto-switch-from-learning-to-enabled false`

. 볼륨의 ARP 상태를 확인합니다.
+
'보안 안티 랜섬웨어 볼륨 쇼'



--
====
.관련 정보
* link:switch-learning-to-active-mode.html["학습 기간 후 활성 모드로 전환합니다"]

