---
sidebar: sidebar 
permalink: anti-ransomware/index.html 
keywords: anti-ransomware overview, ransomware, security, introduce, protection, detect, detection, threat, attack, suspect, what ontap anti-ransomware detects, entropy, abnormal volume activity, ransomware, antiransomware, extension conformity, recover data after a ransomware attack, ransomware protection strategy 
summary: 'ONTAP 9.10.1부터 안티 랜섬웨어 기능은 NAS(NFS 및 SMB) 환경에서 워크로드 분석을 사용하여 랜섬웨어 공격을 나타낼 수 있는 비정상적인 활동을 사전에 감지하고 경고합니다.' 
---
= 랜섬웨어 방지 개요
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
ONTAP 9.10.1부터 안티 랜섬웨어 기능은 NAS(NFS 및 SMB) 환경에서 워크로드 분석을 사용하여 랜섬웨어 공격을 나타낼 수 있는 비정상적인 활동을 사전에 감지하고 경고합니다.

공격이 의심되면 안티 랜섬웨어도 예약된 Snapshot 복사본으로부터 기존 보호뿐만 아니라 새 Snapshot 백업도 생성합니다.

랜섬웨어 방지 기능은 다음 라이센스로 활성화됩니다.

[cols="2*"]
|===
| ONTAP 릴리스 | 라이센스 


 a| 
ONTAP 9.11.1 이상
 a| 
안티 랜섬웨어



 a| 
ONTAP 9.10.1
 a| 
Mt_EK_MGMT(멀티 테넌트 키 관리)

|===
* ONTAP 9.11.1 이상으로 업그레이드하고 랜섬웨어 방지 보호를 이미 시스템에 구성한 경우 새로운 Anti-랜섬웨어 라이센스를 구입할 필요가 없습니다. 새로운 랜섬웨어 방지 구성의 경우 새 라이센스가 필요합니다.
* ONTAP 9.11.1 이상에서 ONTAP 9.10.1로 되돌려고 안티랜섬웨어 라이센스를 사용하여 랜섬웨어 보호를 활성화한 경우 경고 메시지가 표시되고 랜섬웨어 방지 기능을 다시 구성해야 할 수 있습니다. link:../revert/anti-ransomware-license-task.html["랜섬웨어 방지 보호를 되돌리는 방법에 대해 알아보십시오"].


ONTAP System Manager 또는 ONTAP CLI(Command Line Interface)를 사용하여 볼륨별로 랜섬웨어 방지 보호를 구성할 수 있습니다.



== ONTAP 랜섬웨어 보호 전략

효과적인 랜섬웨어 탐지 전략에는 단일 이상의 보호 계층이 포함되어야 합니다.

예를 들어, 차량의 안전 기능을 들 수 있습니다. 안전 벨트와 같은 단일 기능에 의존하여 사고 시 사용자를 완벽하게 보호하고 싶지 않을 것입니다. 에어백, 안티 브레이크 및 전방 충돌 경고는 모두 추가적인 안전 기능으로 훨씬 더 나은 결과를 제공합니다. 랜섬웨어 보호는 동일한 방법으로 확인해야 합니다.

ONTAP에는 FPolicy, Snapshot 복사본, SnapLock, Active IQ 디지털 자문과 같은 기능이 포함되어 있어 랜섬웨어로부터 보호하지만, 다음 정보는 머신 러닝 기능을 갖춘 ONTAP 안티 랜섬웨어 온박스 기능에 초점을 맞춥니다.

ONTAP의 기타 랜섬웨어 방지 기능에 대한 자세한 내용은 다음을 참조하십시오. https://www.netapp.com/media/7334-tr4572.pdf["TR-4572: 랜섬웨어용 NetApp 솔루션"^]



== ONTAP의 랜섬웨어 차단 탐지 기능

랜섬웨어 공격에는 두 가지 유형이 있습니다.

. 데이터 암호화를 통한 파일 서비스 거부 공격자는 대가를 지불하지 않는 한 이 데이터에 대한 액세스를 보유합니다.
. 중요한 독점 데이터의 도난. 공격자는 대가를 지불하지 않는 한 이 데이터를 공개 도메인에 배포하겠다고 위협합니다.


ONTAP 랜섬웨어 차단 메커니즘은 다음과 같이 첫 번째 유형을 해결합니다.

. 들어오는 데이터를 암호화된 데이터 또는 일반 텍스트로 식별합니다.
. 탐지 분석
+
** 높은 data_엔트로피 _ (파일 내 데이터의 임의 평가)
** 데이터 암호화로 비정상적인 볼륨 활동이 급증합니다
** 일반 내선 번호에 맞지 않는 내선 번호





NOTE: 랜섬웨어 탐지 또는 방지 시스템이 랜섬웨어 공격에서 안전을 완벽하게 보장할 수는 없습니다. 공격은 감지되지 않을 수도 있지만 바이러스 백신 소프트웨어가 침입을 감지하지 못한 경우 NetApp 랜섬웨어 보호는 중요한 추가 방어 계층으로 작동합니다. Anti-랜섬웨어는 소수의 파일만 암호화한 후 대부분의 랜섬웨어 공격 확산을 감지하고 자동으로 조치를 취하여 데이터를 보호하고 의심스러운 공격이 발생하고 있음을 경고할 수 있습니다.



== 랜섬웨어 공격 후 ONTAP에서 데이터를 복구하는 방법

공격이 의심되면 해당 시점에 시스템에서 볼륨 Snapshot 복사본을 생성한 후 해당 복사본을 잠급니다. 나중에 공격이 확인되면 사전에 생성된 이 스냅샷으로 볼륨을 복원하여 데이터 손실을 최소화할 수 있습니다.

잠긴 스냅샷 복사본은 일반적인 방법으로 삭제할 수 없습니다. 그러나 나중에 이 공격을 가양성 공격으로 표시하기로 결정하면 잠긴 복사본이 삭제됩니다.

영향을 받는 파일과 공격 시간을 알고 있으면 전체 볼륨을 스냅샷 중 하나로 되돌리는 대신 다양한 Snapshot 복제본에서 영향을 받는 파일을 선택적으로 복구할 수 있습니다.

따라서 안티 랜섬웨어는 검증된 ONTAP 데이터 보호 및 재해 복구 기술을 기반으로 구축되며 랜섬웨어 공격에 대응합니다. 데이터 복구에 대한 자세한 내용은 다음 항목을 참조하십시오.

* link:../task_dp_recover_snapshot.html["Snapshot 복사본에서 복구(System Manager)"]
* link:../data-protection/restore-contents-volume-snapshot-task.html["스냅샷 복사본에서 파일 복원(CLI)"]
* link:https://www.netapp.com/blog/smart-ransomware-recovery["스마트 랜섬웨어 복구"^]

