---
sidebar: sidebar 
permalink: anti-ransomware/modify-automatic-snapshot-options-task.html 
keywords: anti-ransomware, automatic, snapshot, suspected attack, vserver options, autonomous ransomware protection, arp 
summary: 의심되는 랜섬웨어 공격에 대응하여 자동으로 생성되는 자율적 랜섬웨어 방어 스냅샷의 설정을 수정합니다. 
---
= 자동 스냅샷에 대한 옵션을 수정합니다
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
ONTAP 9.11.1부터 CLI를 사용하여 의심되는 랜섬웨어 공격에 대응하여 자동으로 생성되는 ARP(자율적 랜섬웨어 방어) 스냅샷의 보존 설정을 제어할 수 있습니다.

.시작하기 전에
노드 SVM에서는 ARP 스냅샷 옵션만 수정할 수 있습니다.

.단계
. 현재 ARP 스냅샷 설정을 모두 표시하려면 다음을 입력합니다.
`vserver options -vserver <svm_name> -option-name arw*`
+

NOTE: 를 클릭합니다 `vserver options` 명령은 숨겨진 명령입니다. man 페이지를 보려면 를 입력합니다 `man vserver options` ONTAP CLI에서

. 선택한 현재 ARP 스냅샷 설정을 표시하려면 다음을 입력합니다.
`vserver options -vserver <svm_name> -option-name <arw_setting_name>`
. ARP 스냅샷 설정을 수정하려면 다음을 입력합니다.
`vserver options -vserver <svm_name> -option-name <arw_setting_name> -option-value <arw_setting_value>`
+
다음 설정을 수정할 수 있습니다.

+
[cols="1,3"]
|===
| ARW 설정 | 설명 


| `arw.snap.max.count`  a| 
특정 시간에 볼륨에 존재할 수 있는 ARP 스냅샷의 최대 수를 지정합니다. ARP 스냅샷의 총 수가 이 지정된 한도 내에 있도록 이전 복제본이 삭제됩니다.  `-option-value`매개 변수에는 3과 8 사이의 정수를 사용할 수 있습니다. 기본값은 6입니다.



| `arw.snap.create.interval.hours`  a| 
ARP 스냅샷 간의 간격(시간)을 지정합니다. 새로운 ARP 스냅샷은 데이터 엔트로피 기반 공격이 의심되고 가장 최근에 생성된 ARP 스냅샷이 지정된 간격보다 오래된 경우에 생성됩니다.  `-option-value`매개 변수에는 1에서 48 사이의 정수를 사용할 수 있습니다. 기본값은 4입니다.



| `arw.snap.normal.retain.interval.hours`  a| 
ARP 스냅샷이 보존되는 지속 시간(시간)을 지정합니다. ARP 스냅샷이 보존 임계값에 도달하면 삭제되기 전에 생성된 다른 ARP 스냅샷 복사본이 생성됩니다. 보존 임계값보다 오래된 ARP 스냅샷은 둘 이상 존재할 수 없습니다.  `-option-value`매개 변수에는 4와 96 사이의 정수를 사용할 수 있습니다. 기본값은 48입니다.



| `arw.snap.max.retain.interval.days`  a| 
ARP 스냅샷을 보존할 수 있는 최대 지속 시간을 days_로 지정합니다. 이 기간보다 오래된 ARP 스냅샷은 볼륨에 보고된 공격이 없으면 삭제됩니다.


NOTE: ARP 스냅샷의 최대 보존 간격은 보통 위협이 감지된 경우 무시됩니다. 위협에 대한 응답으로 생성된 ARP 스냅샷은 사용자가 위협에 응답할 때까지 유지됩니다. 위협을 false positive로 표시하면 ONTAP는 볼륨에 대한 ARP 스냅샷을 삭제합니다.  `-option-value`매개 변수에는 1에서 365 사이의 정수를 사용할 수 있습니다. 기본값은 5입니다.



| `arw.snap.create.interval.hours.post.max.count`  a| 
볼륨에 이미 최대 ARP 스냅샷 수가 포함되어 있을 때 ARP 스냅샷 간의 간격(시간)을 지정합니다. 최대 수에 도달하면 ARP 스냅샷이 삭제되어 새 사본을 위한 공간을 만듭니다. 이 옵션을 사용하여 이전 사본을 유지하기 위해 새 ARP 스냅샷 생성 속도를 줄일 수 있습니다. 볼륨에 이미 최대 ARP 스냅샷 수가 포함되어 있는 경우 이 옵션에 지정된 간격이 다음 ARP 스냅샷 생성에 `arw.snap.create.interval.hours` 사용됩니다.  `-option-value`매개 변수에는 4와 48 사이의 정수를 사용할 수 있습니다. 기본값은 8입니다.



| `arw.surge.snap.interval.days`  a| 
IO 서지에 대한 응답으로 생성된 ARP 스냅샷 사이의 간격 _(일)을 지정합니다. ONTAP는 IO 트래픽에 과부하가 있고 마지막으로 생성된 ARP 스냅샷이 지정된 간격보다 오래된 경우 ARP 스냅샷 서지 복제본을 생성합니다. 또한 이 옵션은 ARP 서지 스냅숏에 대한 보존 기간을 day_로 지정합니다.  `-option-value`매개 변수에는 1에서 365 사이의 정수를 사용할 수 있습니다. 기본값은 5입니다.



| `arw.snap.new.extns.interval.hours`  a| 
이 옵션은 새 파일 확장자가 감지될 때 생성된 ARP 스냅샷 사이의 간격 _ 시간 _ 을(를) 지정합니다. 새 파일 확장자가 관찰될 때 새 ARP 스냅샷이 생성됩니다. 새 파일 확장자를 관찰할 때 생성된 이전 스냅샷이 지정된 간격보다 오래되었습니다. 새 파일 확장자를 자주 생성하는 작업 부하에서 이 간격은 ARP 스냅샷의 빈도를 제어하는 데 도움이 됩니다. 이 옵션은 데이터 엔트로피 기반 ARP 스냅샷의 간격을 지정하는 에 독립적입니다. `arw.snap.create.interval.hours`  `-option-value`매개 변수는 24에서 8760 사이의 정수를 사용할 수 있습니다. 기본값은 48입니다.

|===

