---
sidebar: sidebar 
permalink: anti-ransomware/pause-task.html 
keywords: anti-ransomware, ransomware, pause, autonomous, protection, arp 
summary: 비정상적인 워크로드 이벤트가 발생할 것으로 예상되는 경우 언제든지 Autonomous 랜섬웨어 Protection 분석을 일시적으로 중지하고 재개할 수 있습니다. 
---
= Autonomous 랜섬웨어 Protection을 일시 중지하여 워크로드 이벤트를 분석에서 제외합니다
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
비정상적인 워크로드 이벤트가 발생할 것으로 예상되는 경우 언제든지 ARP(Autonomous 랜섬웨어 보호) 분석을 일시 중지 및 재개할 수 있습니다.

ONTAP 9.13.1 부터는 다중 관리 확인(MAV)을 활성화하여 두 명 이상의 인증된 사용자 관리자가 ARP를 일시 중지해야 합니다. link:../multi-admin-verify/enable-disable-task.html["자세한 정보"^].

.이 작업에 대해
ARP 일시 중지 중에는 이벤트가 기록되지 않으며 새 쓰기에 대한 작업도 기록되지 않습니다. 그러나 백그라운드에서 이전 로그에 대한 분석 작업은 계속됩니다.


NOTE: ARP 비활성화 기능을 사용하여 분석을 일시 중지하지 마십시오. 이렇게 하면 볼륨에서 ARP가 비활성화되고 학습된 워크로드 동작에 대한 기존 정보가 모두 손실됩니다. 이 경우 학습 기간을 다시 시작해야 합니다.

.단계
시스템 관리자 또는 ONTAP CLI를 사용하여 ARP를 일시 중지할 수 있습니다.

[role="tabbed-block"]
====
.시스템 관리자
--
. 스토리지 > 볼륨 * 을 선택한 다음 ARP를 일시 중지할 볼륨을 선택합니다.
. 볼륨 개요의 ** 보안** 탭에서 * 안티 랜섬웨어 * 상자에서 * 안티 랜섬웨어 * 일시 중지 * 를 선택합니다.
+

NOTE: ONTAP 9.13.1 부터, ARP 설정을 보호하기 위해 MAV를 사용하는 경우, 일시 중지 작업은 하나 이상의 추가 관리자의 승인을 얻으라는 메시지를 표시합니다. link:../multi-admin-verify/request-operation-task.html["모든 관리자로부터 승인을 받아야 합니다"] MAV 승인 그룹과 연관되거나 작업이 실패합니다.



--
.CLI를 참조하십시오
--
. 볼륨에서 ARP 일시 중지:
+
'Security Anti-랜섬웨어 volume pause-vserver_svm_name_-volume_vol_name_'

. 처리를 재개하려면 를 사용합니다 `resume` 명령:
+
'Security Anti-랜섬웨어 volume resume - vserver_svm_name_-volume_vol_name_'

. * ARP 설정을 보호하기 위해 MAV(ONTAP 9.13.1로 시작하는 ARP에서 사용 가능)를 사용하는 경우 * 일시 중지 작업은 하나 이상의 추가 관리자의 승인을 얻도록 요청합니다. MAV 승인 그룹과 연결된 모든 관리자로부터 승인을 받아야 합니다. 그렇지 않으면 작업이 실패합니다.
+
MAV를 사용 중이고 예상 일시 중지 작업에 추가 승인이 필요한 경우 각 MAV 그룹 승인자는 다음을 수행합니다.

+
.. 요청 표시:
+
`security multi-admin-verify request show`

.. 요청 승인:
+
`security multi-admin-verify request approve -index[_number returned from show request_]`

+
마지막 그룹 승인자에 대한 응답은 볼륨이 수정되었고 ARP 상태가 일시 중지되었음을 나타냅니다.

+
MAV를 사용하고 있고 MAV 그룹 승인자인 경우 일시 중지 작업 요청을 거부할 수 있습니다.

+
`security multi-admin-verify request veto -index[_number returned from show request_]`





--
====