---
sidebar: sidebar 
permalink: anti-ransomware/respond-abnormal-task.html 
keywords: Respond to abnormal activity, anti-ransomware abnormal activity, data entropy, unusual file extensions, potential ransomware attack, false positive, suspected ransomware attack, abnormal activity notification, security, ransomware alert message, detected abnormal volume, suspected file types, attack report, anti-ransomware attack 
summary: Anti-랜섬웨어가 보호 볼륨에서 비정상적인 활동을 감지하면 경고를 표시합니다. 알림을 평가하여 작업이 예상되는지, 허용되는지, 공격이 진행 중인지 여부를 확인해야 합니다. 
---
= 비정상적인 활동에 응답합니다.
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
Anti-랜섬웨어가 보호 볼륨에서 비정상적인 활동을 감지하면 경고를 표시합니다. 알림을 평가하여 작업이 예상되는지, 허용되는지, 공격이 진행 중인지 여부를 확인해야 합니다.

.필요한 것
* 안티 랜섬웨어가 활성 모드에서 실행 중입니다.


Anti-랜섬웨어는 높은 데이터 엔트로피, 데이터 암호화를 통한 비정상적인 볼륨 작업, 비정상적인 파일 확장자가 검색될 때 의심되는 파일 목록을 표시합니다.

경고가 발생하면 다음 두 가지 방법 중 하나로 파일 활동을 표시하여 응답할 수 있습니다.

* 거짓 양성
+
식별된 파일 유형이 작업 부하에 필요합니다. 이 파일 유형은 무시해도 됩니다.

* 잠재적인 랜섬웨어 공격
+
식별된 파일 유형이 작업 부하에서 예기치 않은 유형이므로 잠재적 공격으로 간주해야 합니다.



두 경우 모두 알림을 업데이트 및 삭제한 후 정상적인 모니터링이 재개됩니다. 랜섬웨어 방지 기록은 평가를 기록하며 새로운 파일 유형으로 로그를 업데이트하고 향후 분석을 위해 사용합니다. 그러나 공격이 의심되는 경우에는 알림을 지우기 전에 공격이 공격인지 여부를 확인하고, 공격에 대한 대응 및 보호 데이터를 복원해야 합니다. 자세한 내용은 을 참조하십시오 link:index.html#how-to-recover-data-in-ontap-after-a-ransomware-attack["랜섬웨어 공격에서 복구하는 방법"].



== System Manager 절차

. "비정상적인 활동" 알림을 받으면 링크를 클릭하거나 볼륨 * 개요의 * 보안 * 탭으로 이동합니다.
+
경고는 이벤트 창의 개요 창에 표시됩니다.

. “Detected abnormal volume activity(비정상적인 볼륨 활동이 감지됨)” 메시지가 표시되면 의심되는 파일을 봅니다.
+
보안 * 탭에서 보기 * 의심되는 파일 형식 * 을 클릭합니다.

. 의심되는 파일 유형* 대화 상자에서 각 파일 유형을 조사하여 “거짓 긍정” 또는 “잠재적인 랜섬웨어 공격”으로 표시합니다.


[cols="25,75"]
|===


| 이 값을 선택한 경우... | 이 조치를 취하십시오… 


| 거짓 양성 | Update * 및 * Clear Suspect File Types * 를 클릭하여 결정 사항을 기록하고 일반적인 Anti-랜섬웨어 모니터링을 재개합니다. 


| 잠재적인 랜섬웨어 공격 | 공격에 대응하고 보호된 데이터를 복원합니다. 그런 다음 * 업데이트 * 및 * 의심스러운 파일 유형 지우기 * 를 클릭하여 결정을 기록하고 일반적인 랜섬웨어 방지 모니터링을 재개합니다. 
|===


== CLI 절차

. 랜섬웨어 공격이 의심되는 경우 다음 사항을 통지하여 공격의 시간 및 심각도를 확인하십시오.
+
'Security Anti-랜섬웨어 volume show -vserver_svm_name_-volume_vol_name_'

+
샘플 출력:

+
....
Vserver Name: vs0
Volume Name: vol1
State: enabled
Attack Probability: moderate
Attack Timeline: 9/14/2021 01:03:23
Number of Attacks: 1
....
+
EMS 메시지를 확인할 수도 있습니다.

+
이벤트 로그 show-message-name callhome.arw.activity.seen`

. 공격 보고서를 생성하고 출력 위치를 기록합니다.
+
'Security Anti-랜섬웨어 volume attack generate-report-volume_vol_name_-dest-path_file_location_/

+
샘플 출력:

+
"Report" report_file_vs0_vol1_14-09-2021_01-21-08" 경로 "vs0:vol1/" 에서 사용할 수 있습니다

. 관리 클라이언트 시스템에서 보고서를 봅니다. 예를 들면 다음과 같습니다.
+
....
[root@rhel8 mnt]# cat report_file_vs0_vol1_14-09-2021_01-21-08

19  "9/14/2021 01:03:23"   test_dir_1/test_file_1.jpg.lckd
20  "9/14/2021 01:03:46"   test_dir_2/test_file_2.jpg.lckd
21  "9/14/2021 01:03:46"   test_dir_3/test_file_3.png.lckd`
....
. 파일 확장명 평가에 따라 다음 작업 중 하나를 수행합니다.
+
** 거짓 양성
+
다음 명령을 입력하여 허용되는 항목 목록에 새 확장명을 추가하여 정상적인 랜섬웨어 방지 모니터링을 재개하십시오. 'Anti-랜섬웨어 volume attack clear-vserver_svm_name_-volume_vol_name_[_extension identifier_] - false-positive true

+
다음 매개 변수 중 하나를 사용하여 의심되는 목록에 있는 파일의 '[-seq-no_integer_]' 시퀀스 번호를 식별합니다. `[-extension_text_,… [-start-time_date_time_-end-time_date_time_]"" MM/DD/YYYY HH:MM:SS 형식으로 지울 파일 범위의 시작 및 종료 시간.

** 잠재적인 랜섬웨어 공격
+
공격에 대응하고 데이터를 복구합니다. 그런 다음 다음 다음 명령을 입력하여 결정 사항을 기록한 후 정상적인 랜섬웨어 방지 모니터링을 재개하십시오.

+
'안티 랜섬웨어 볼륨 공격 clear-suspect-vserver_svm_name_-volume_vol_name_[_extension identifier_]-false-positive false'

+
다음 매개 변수 중 하나를 사용하여 확장자가 무엇인지 확인하십시오. "[-seq-no_integer_]" 의심되는 목록에 있는 파일의 시퀀스 번호 [-extension_text_,… [-start-time_date_time_-end-time_date_time_]"" MM/DD/YYYY HH:MM:SS 형식으로 지울 파일 범위의 시작 및 종료 시간.




