---
sidebar: sidebar 
permalink: anti-ransomware/use-cases-restrictions-concept.html 
keywords: anti-ransomware use cases and restrictions, anti-ransomware performance and frequency considerations, anti-ransomware workloads, anti-ransomware volume requirements, anti-ransomware performance, volumes, anti-ransomware encryption, anti-ransomware system configurations 
summary: 현재 릴리스에서 랜섬웨어 보호는 NAS 환경에 가장 적합합니다. 다른 환경에 대한 지원은 향후 릴리즈에서 제공될 예정입니다. 
---
= 안티 랜섬웨어 사용 사례 및 고려사항
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
현재 릴리스에서 랜섬웨어 보호는 NAS 환경에 가장 적합합니다. 다른 환경에 대한 지원은 향후 릴리즈에서 제공될 예정입니다.

ONTAP 플랫폼 지원:

[cols="2*"]
|===
| 플랫폼 | 시작 가능... 


 a| 
ONTAP 온프레미스
 a| 
ONTAP 9.10.1



 a| 
Cloud Volumes ONTAP
 a| 
ONTAP 9.11.1



 a| 
AWS 및 Google Cloud용 Cloud Volume Services
 a| 
지원되지 않습니다



 a| 
Azure NetApp Files
 a| 
지원되지 않습니다



 a| 
ONTAP Select
 a| 
지원되지 않습니다

|===
적합한 워크로드:

* 데이터베이스를 NFS 스토리지에 저장합니다
* Windows 또는 Linux 홈 디렉토리
+
사용자가 학습 기간에 감지되지 않은 확장자로 파일을 생성할 수 있기 때문에 이 작업 부하에서 오탐이 발생할 가능성이 더 높습니다.

* 이미지 및 비디오
+
예: 의료 기록 및 전자 설계 자동화(EDA) 데이터



적합하지 않은 워크로드:

* 파일 생성 또는 삭제 빈도가 높은 워크로드(테스트/개발 워크로드 등 몇 초 이내에 수십만 개 파일)
* 랜섬웨어 방지 기능은 파일 생성 또는 삭제 활동에서 비정상적인 급증을 인식할 수 있는 기능에 따라 다릅니다. 애플리케이션 자체가 파일 활동의 소스인 경우 랜섬웨어 활동과 효과적으로 구분할 수 없습니다
* 애플리케이션 또는 호스트가 데이터를 암호화하는 워크로드 안티 랜섬웨어 기능은 수신되는 데이터를 암호화하거나 암호화되지 않은 것으로 구분하는 데 따라 달라집니다. 애플리케이션 자체에서 데이터를 암호화하면 기능의 효율성이 감소합니다. 그러나 이 기능은 파일 작업(생성, 삭제 및 덮어쓰기) 및 파일 유형에 따라 계속 작동할 수 있습니다.


지원되지 않는 시스템 구성:

* 알아보십시오
* ONTAP S3 환경
* NFS의 VMDK


볼륨 요구 사항:

* 100% 미만 차 있습니다
* 접합 경로가 활성 상태여야 합니다


지원되지 않는 볼륨 유형:

* 오프라인 볼륨
* 제한된 볼륨
* SnapLock 볼륨
* SnapLock 볼륨
* FlexGroup 볼륨
* FlexCache 볼륨(랜섬웨어 방지 기능은 원래 FlexVol 볼륨에서 지원되지만 캐시 볼륨에서는 지원되지 않음)
* SAN 전용 볼륨
* 중지된 스토리지 VM의 볼륨입니다
* 스토리지 VM의 루트 볼륨입니다
* 데이터 보호 볼륨




== 랜섬웨어 방지 성능 및 주파수 고려사항

랜섬웨어 방지 기능은 처리량과 최대 IOPS로 측정한 시스템 성능에 최소한의 영향을 미칠 수 있습니다. 랜섬웨어 방지 기능의 영향은 볼륨 워크로드에 따라 크게 달라집니다. 일반적인 워크로드 또는 일반적인 워크로드의 경우 다음과 같은 구성 제한이 권장됩니다.

* 워크로드가 읽기 집약적이거나 데이터를 압축할 수 있는 경우 노드당 볼륨 수가 50개를 넘지 않습니다.
* 워크로드가 쓰기 집약적이고 데이터를 압축할 수 없는 경우 노드당 볼륨 수가 20개를 넘지 않습니다.


랜섬웨어 방지 분석은 우선 순위가 지정된 순서대로 실행되므로 보호된 볼륨의 수가 증가하면 각 볼륨에서 더 자주 분석을 실행합니다.



== 랜섬웨어 탐지 시 자동 스냅샷 사본의 작동 방식

가능한 최상의 복구 지점을 얻기 위해 랜섬웨어 방지 기능은 비정상적인 파일 활동을 감지하는 즉시 자동 스냅샷 복사본을 생성합니다. 하지만 랜섬웨어 방지 기능은 경고에 즉시 플래그를 지정하는 것이 아니라, 분석을 실행하여 의심스러운 활동이 랜섬웨어 프로필과 일치하는지 확인해야 합니다. 이 프로세스는 최대 60분이 소요될 수 있습니다. 분석에서 의심스러운 활동이 아닌 것으로 확인되면 알림이 생성되지 않고 자동으로 생성된 스냅샷 복사본이 최소 2일 동안 파일 시스템에 남아 있습니다.

ONTAP 9.11.1부터, 랜섬웨어 공격이 의심되는 경우 자동으로 생성되는 랜섬웨어 방지 스냅샷 복사본의 수와 보존 기간을 제어할 수 있습니다. 자세한 내용을 알아보십시오 link:modify-automatic-shapshot-options-task.html["자동 스냅샷 복사본에 대한 옵션을 수정합니다"].
