---
sidebar: sidebar 
permalink: anti-ransomware/use-cases-restrictions-concept.html 
keywords: anti-ransomware workloads, anti-ransomware requirements, anti-ransomware performance, volumes, anti-ransomware encryption, anti-ransomware system configurations, arp 
summary: 현재 릴리스에서 랜섬웨어 보호는 NAS 환경에 가장 적합합니다. 다른 환경에 대한 지원은 향후 릴리즈에서 제공될 예정입니다. 
---
= 자율 랜섬웨어 보호 사용 사례 및 고려사항
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
자율 랜섬웨어 보호 기능의 가용성은 사용 중인 ONTAP 버전에 따라 다릅니다.



== 지원 구성 및 지원되지 않는 구성

ONTAP 플랫폼 지원:

* 자율 랜섬웨어 보호(ARP) 기능은 ONTAP 9.10.1부터 시작하는 모든 사내 ONTAP 시스템에서 사용할 수 있습니다.


적합한 워크로드:

* 데이터베이스를 NFS 스토리지에 저장합니다
* Windows 또는 Linux 홈 디렉토리
+
사용자가 학습 기간에 감지되지 않은 확장자로 파일을 생성할 수 있기 때문에 이 작업 부하에서 오탐이 발생할 가능성이 더 높습니다.

* 이미지 및 비디오
+
예: 의료 기록 및 전자 설계 자동화(EDA) 데이터



ONTAP 9.12.1부터 ARP는 다음 구성에서 사용할 수 있습니다.

* SnapMirror로 보호되는 볼륨
* SnapMirror로 SVM 보호
* 마이그레이션을 위해 SVM 지원(SVM 데이터 이동성)


적합하지 않은 워크로드:

* 파일 생성 또는 삭제 빈도가 높은 워크로드(테스트/개발 워크로드 등 몇 초 이내에 수십만 개 파일)
* ARP는 파일 생성, 이름 변경 또는 삭제 작업에서 비정상적인 급증을 인식하는 기능에 따라 달라집니다. 애플리케이션 자체가 파일 활동의 소스인 경우 랜섬웨어 활동과 효과적으로 구분할 수 없습니다
* 애플리케이션 또는 호스트가 데이터 ARP를 암호화하는 워크로드는 수신 데이터를 암호화 또는 암호화되지 않은 것으로 구분하는 데 따라 달라집니다. 애플리케이션 자체에서 데이터를 암호화하면 기능의 효율성이 감소합니다. 그러나 이 기능은 파일 작업(삭제, 덮어쓰기, 생성 또는 새 파일 확장명으로 생성 또는 이름 바꾸기)과 파일 유형에 따라 계속 작동할 수 있습니다.


지원되지 않는 시스템 구성:

* 알아보십시오
* ONTAP S3 환경
* NFS의 VMDK


볼륨 요구 사항:

* 100% 미만 차 있습니다
* 접합 경로가 활성 상태여야 합니다


지원되지 않는 볼륨 유형:

* 오프라인 볼륨
* 제한된 볼륨
* SnapLock 볼륨
* FlexGroup 볼륨(ONTAP 9.13.1 부터 FlexGroup 볼륨 지원)
* FlexCache 볼륨(ARP는 오리진 FlexVol 볼륨에서 지원되지만 캐시 볼륨에서는 지원되지 않음)
* SAN 전용 볼륨
* 중지된 스토리지 VM의 볼륨입니다
* 스토리지 VM의 루트 볼륨입니다




== SnapMirror 및 ARP 상호 운용성

ONTAP 9.12.1부터 ARP는 SnapMirror 대상 볼륨에서 지원됩니다. SnapMirror 소스 볼륨이 ARP가 활성화된 경우 SnapMirror 대상 볼륨은 자동으로 ARP 구성 상태(학습, 활성화 등), ARP 교육 데이터 및 소스 볼륨의 ARP 생성 스냅샷을 가져옵니다. 명시적 활성화가 필요하지 않습니다.

대상 볼륨이 읽기 전용(RO) 스냅샷 복사본으로 구성되어 있지만, 해당 데이터에 대한 ARP 처리는 수행되지 않습니다. 그러나 SnapMirror 대상 볼륨이 읽기-쓰기(RW)로 변환되면 ARP는 RW로 변환된 대상 볼륨에서 자동으로 활성화됩니다. 대상 볼륨에는 소스 볼륨에 이미 기록된 내용 외에 추가 학습 절차가 필요하지 않습니다.

ONTAP 9.10.1 및 9.11.1에서 SnapMirror는 ARP 구성 상태, 훈련 데이터 및 Snapshot 복사본을 소스에서 타겟 볼륨으로 전송하지 않습니다. 따라서 SnapMirror 대상 볼륨이 RW로 변환될 때 대상 볼륨의 ARP는 변환 후 학습 모드에서 명시적으로 활성화되어야 합니다.



== ARP 성능 및 주파수 고려 사항

ARP 기능은 처리량 및 피크 IOPS로 측정한 시스템 성능에 최소한의 영향을 미칠 수 있습니다. ARP 기능의 영향은 볼륨 작업 부하에 따라 크게 달라집니다. 일반적인 워크로드 또는 일반적인 워크로드의 경우 다음과 같은 구성 제한이 권장됩니다.

[cols="30,20,30"]
|===
| 워크로드 특성 | 노드당 권장 볼륨 제한입니다 | 노드당 볼륨 제한을 초과할 경우 성능 저하: [*] 


| 읽기 집약적 또는 데이터를 압축할 수 있습니다. | 150 | 최대 IOPS의 4% 


| 쓰기 집약적이고 데이터를 압축할 수 없습니다. | 60 | 최대 IOPS의 10% 
|===
통과: [*] 권장 한도를 초과하여 추가된 볼륨의 수에 관계없이 시스템 성능이 이 비율을 초과하여 저하되지 않습니다.

ARP 분석은 우선 순위가 지정된 순서대로 실행되기 때문에 보호된 볼륨의 수가 증가함에 따라 각 볼륨에서 분석 실행 빈도가 줄어듭니다.



== ARP(Autonomous 랜섬웨어 Protection)로 보호되는 볼륨으로 다중 관리 검증

ONTAP 9.13.1 부터는 ARP를 통한 추가 보안을 위해 MAV(Multi-admin verification)를 활성화할 수 있습니다. MAV를 사용하면 최소한 두 명 이상의 인증된 관리자가 ARP를 끄거나 ARP를 일시 중지하거나 의심스러운 공격을 보호된 볼륨에서 위양성(false positive)으로 표시해야 합니다. 자세한 내용을 알아보십시오 link:../multi-admin-verify/enable-disable-task.html["ARP 보호 볼륨에 대해 MAV를 활성화합니다"^].

MAV 그룹에 대한 관리자를 정의하고 에 대한 MAV 규칙을 만들어야 합니다 `security anti-ransomware volume disable`, `security anti-ransomware volume pause`, 및 `security anti-ransomware volume attack clear-suspect` 보호할 ARP 명령. MAV 그룹의 각 관리자는 각각의 새 규칙 요청 및 을 승인해야 합니다 link:../multi-admin-verify/enable-disable-task.html["MAV 규칙을 다시 추가합니다"^] MAV 설정 내.
