---
sidebar: sidebar 
permalink: snapmirror-active-sync/index.html 
keywords: SM-BC, SMBC, failover, terms, benefits, snapmirror active sync, TR-4878 
summary: SnapMirror 액티브 동기화를 사용하여 LUN이 있는 애플리케이션을 보호함으로써 애플리케이션이 투명하게 페일오버될 수 있도록 하여 재해 발생 시 비즈니스 연속성을 보장합니다. 
---
= SnapMirror Active Sync 개요
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
SnapMirror 액티브 동기화(SnapMirror Business Continuity_[SM-BC]_ 라고도 함)를 사용하면 전체 사이트 장애 시에도 비즈니스 서비스의 지속적인 운영을 유지할 수 있으며, 보조 복사본을 사용하여 애플리케이션을 투명하게 페일오버할 수 있습니다. SnapMirror 활성 동기화로 페일오버를 트리거하는 데 수동 개입이나 사용자 지정 스크립팅이 필요하지 않습니다.

ONTAP 9.9.1부터 사용 가능, SnapMirror 액티브 동기화는 AFF 클러스터, ASA(All Flash SAN Array) 클러스터 및 C-Series(AFF 또는 ASA)에서 지원됩니다. 운영 클러스터와 2차 클러스터의 유형은 ASA 또는 AFF 중 하나여야 합니다. SnapMirror 액티브 동기화는 iSCSI 또는 FCP LUN으로 애플리케이션을 보호합니다.

ONTAP 9.15.1부터 SnapMirror 액티브 동기화는 을 지원합니다 xref:architecture-concept.html[대칭적인 액티브/액티브 기능]는 양방향 동기식 복제를 사용하는 보호된 LUN의 두 복사본에서 읽기 및 쓰기 I/O 작업을 지원하므로 두 LUN 복사본 모두 로컬에서 I/O 작업을 수행할 수 있습니다. ONTAP 9.15.1 이전의 SnapMirror 활성 동기화는 보조 사이트의 데이터를 LUN에 프록시하는 비대칭 활성/활성 구성만 지원합니다.


NOTE: 2024년 7월부터 이전에 PDF로 게시된 기술 보고서의 콘텐츠가 ONTAP 제품 문서와 통합되었습니다. 이제 ONTAP SnapMirror 액티브 동기화 문서에 _TR-4878: SnapMirror active sync_의 콘텐츠가 포함되어 있습니다.



== 이점

SnapMirror 액티브 동기화는 다음과 같은 이점을 제공합니다.

* 비즈니스 크리티컬 애플리케이션을 위한 지속적인 가용성:
* 주요 애플리케이션을 운영 사이트와 보조 사이트에서 교대로 호스팅할 수 있습니다.
* 정합성 보장 그룹을 사용하여 애플리케이션 관리를 간소화하여 종속 쓰기 순서 정합성 보장
* 각 애플리케이션의 장애 조치를 테스트하는 기능
* 애플리케이션 가용성에 영향을 주지 않고 미러 클론을 즉시 생성
* 동일한 ONTAP 클러스터에 보호된 워크로드와 보호되지 않은 워크로드를 구축할 수 있습니다.
* LUN ID는 동일하게 유지되므로 애플리케이션은 이를 공유 가상 디바이스로 인식합니다.
* 2차 클러스터를 유연하게 재사용하여 애플리케이션 성능 또는 가용성에 영향을 주지 않고 개발 테스트, UAT 또는 보고용으로 애플리케이션 사용을 위한 즉각적인 클론을 생성할 수 있습니다.


SnapMirror 액티브 동기화를 사용하면 데이터 LUN을 보호할 수 있으므로 재해 시 비즈니스 연속성을 위해 애플리케이션을 투명하게 페일오버할 수 있습니다. 자세한 내용은 을 참조하십시오 link:use-cases-concept.html["사용 사례"].



== 주요 개념

SnapMirror 액티브 동기화는 일관성 그룹 및 ONTAP 중재자를 사용하여 재해 발생 시에도 데이터 복제 및 서비스를 보장합니다. SnapMirror 활성 동기화 배포를 계획할 때는 SnapMirror Active sync와 해당 아키텍처의 필수 개념을 이해하는 것이 중요합니다.

.비대칭 및 대칭
SnapMirror 액티브 동기화는 ONTAP 9.15.1부터 대칭 액티브/액티브 솔루션까지 비대칭 및 를 지원합니다. 이러한 옵션은 호스트가 스토리지 경로를 액세스하고 데이터를 쓰는 방식을 나타냅니다. 비대칭 구성에서는 보조 사이트의 데이터가 LUN에 프록시로 처리됩니다. 대칭 액티브/액티브 구성에서는 두 사이트가 액티브 I/O의 로컬 스토리지에 액세스할 수 있습니다

대칭 액티브/액티브는 VMware vMSC, SQL을 통한 Windows 페일오버 클러스터 및 Oracle RAC를 포함한 클러스터형 애플리케이션에 최적화되어 있습니다.

자세한 내용은 을 참조하십시오 xref:architecture-concept.html[SnapMirror 액티브 동기화 아키텍처].

.일관성 그룹
A link:../consistency-groups/index.html["일관성 그룹"] 는 비즈니스 연속성을 위해 보호해야 하는 애플리케이션 워크로드에 대한 일관성 보장을 제공하는 FlexVol 볼륨 모음입니다.

정합성 보장 그룹의 목적은 여러 볼륨의 스냅샷 이미지를 동시에 생성하여 특정 시점에 볼륨 컬렉션의 장애 발생 시 정합성이 보장되는 복제본을 보장하는 것입니다. 정합성 보장 그룹을 사용하면 데이터 세트의 모든 볼륨이 정지된 후 정확히 동일한 시점에 스냅됩니다. 데이터 세트를 지원하는 전체 볼륨에서 데이터 정합성이 보장되는 복원 지점을 제공합니다. 따라서 정합성 보장 그룹은 종속 쓰기 순서 일관성을 유지합니다. 비즈니스 연속성을 위해 애플리케이션을 보호하려는 경우 소스와 대상 일관성 그룹 간에 데이터 보호 관계가 설정되도록 이 애플리케이션에 해당하는 볼륨 그룹을 일관성 그룹에 추가해야 합니다. 소스 및 대상 정합성 보장에는 동일한 수의 볼륨 및 유형이 포함되어야 합니다.

.구성 요소
SnapMirror 활성 동기화 관계에서 보호되는 일관성 그룹의 일부인 개별 볼륨 또는 LUN

.ONTAP 중재자
를 클릭합니다 link:../mediator/index.html["ONTAP 중재자"] 피어링된 ONTAP 클러스터 및 노드에 대한 상태 정보를 수신하여 이 두 가지를 오케스트레이션하고 각 노드/클러스터가 정상 상태이고 실행 중인지 확인합니다. ONTAP mediator는 다음과 같은 상태 정보를 제공합니다.

* 피어 ONTAP 클러스터
* 피어 ONTAP 클러스터 노드입니다
* 일관성 그룹(SnapMirror 활성 동기화 관계에서 페일오버 유닛을 정의). 각 일관성 그룹에 대해 다음 정보가 제공됩니다.
+
** 복제 상태: 초기화되지 않음, 동기화 중 또는 동기화 중단
** 운영 복제본을 호스팅하는 클러스터
** 작업 컨텍스트(계획된 페일오버에 사용됨)




이 ONTAP 중재자 상태 정보를 통해 클러스터는 서로 다른 유형의 장애를 구별하고 자동 페일오버를 수행할지 여부를 결정할 수 있습니다. ONTAP mediator는 ONTAP 클러스터(기본 및 보조) 모두와 함께 SnapMirror 액티브 동기화 쿼럼의 세 가지 파티 중 하나입니다. 합의에 도달하기 위해서는 정족수 중 적어도 두 당사자가 일정한 운영에 합의하여야 한다.


NOTE: ONTAP 9.15.1부터는 System Manager에 두 클러스터의 SnapMirror 활성 동기화 관계 상태가 표시됩니다. System Manager의 두 클러스터 중 하나에서 ONTAP 중재자의 상태를 모니터링할 수도 있습니다. 이전 ONTAP 릴리즈에서는 소스 클러스터의 SnapMirror 활성 동기화 관계 상태가 System Manager에 표시됩니다.

.계획된 페일오버
SnapMirror 활성 동기화 관계에서 복사본의 역할을 변경하기 위한 수동 작업입니다. 운영 사이트는 2차 사이트가 되고 2차 사이트는 1차 사이트가 됩니다.

.1차 - 1차 및 1차 편향
SnapMirror 액티브 동기화는 네트워크 파티션 시 I/O를 제공하기 위해 기본 복사본을 우선적으로 사용하는 기본 원칙을 사용합니다.

Primary-bias는 SnapMirror Active Sync Protected 데이터 세트의 가용성을 개선하는 특별한 쿼럼 구현입니다. 운영 복사본을 사용할 수 있는 경우 두 클러스터 모두에서 ONTAP 중재자에 연결할 수 없을 때 운영 바이어스가 적용됩니다.

Primary-first 및 primary bias는 ONTAP 9.15.1부터 SnapMirror 액티브 동기화에서 지원됩니다. 1차 복사본은 System Manager에서 지정되고 REST API 및 CLI를 사용하여 출력됩니다.

.자동 비계획 페일오버(AUFO)
미러 복제본에 대한 페일오버를 수행하는 자동 작업입니다. 이 작업은 ONTAP 중재자의 도움을 받아 운영 복제본을 사용할 수 없음을 감지해야 합니다.

.동기화 중단(OOS)
응용 프로그램 입출력이 보조 스토리지 시스템으로 복제되지 않으면** 비동기 상태로 보고됩니다. 동기화 중단 상태는 보조 볼륨이 기본(소스)과 동기화되지 않았으며 SnapMirror 복제가 발생하지 않음을 의미합니다.

미러 상태가 인 경우 `Snapmirrored`, 지원되지 않는 작업으로 인한 전송 실패 또는 실패를 나타냅니다.

SnapMirror 액티브 동기화는 자동 재동기화를 지원하여 복사본이 InSync 상태로 돌아갈 수 있도록 합니다.

ONTAP 9.15.1부터 SnapMirror 액티브 동기화가 지원됩니다 link:interoperability-reference.html#fan-out-configurations["팬아웃 구성의 자동 재구성"].

.균일 및 비균일 설정
* ** 호스트 액세스 균일** 두 사이트의 호스트가 두 사이트의 스토리지 클러스터에 대한 모든 경로에 접속되어 있음을 의미합니다. 크로스 사이트 경로가 거리에 걸쳐 확장됩니다.
* ** 비균일 호스트 액세스** 각 사이트의 호스트가 동일한 사이트의 클러스터에만 연결되어 있음을 의미합니다. 사이트 간 경로 및 확장 경로가 연결되지 않았습니다.



NOTE: 모든 SnapMirror 액티브 동기식 배포에 대해 통일된 호스트 액세스가 지원되며, 비균일 호스트 액세스는 대칭 액티브/액티브 구축에만 지원됩니다.

.제로 RPO
RPO는 지정된 기간 동안 허용되는 데이터 손실량인 복구 시점 목표를 나타냅니다. RPO가 0이면 데이터 손실이 허용되지 않습니다.

.즉각적인 RTO
RTO는 복구 시간 목표를 나타냅니다. 이 시간은 운영 중단, 장애 또는 기타 데이터 손실 이벤트가 발생한 후 애플리케이션이 운영 중단 없이 정상 작업으로 돌아가도록 허용할 수 있는 시간입니다. RTO가 0이면 가동 중지 시간이 허용되지 않는다는 의미입니다.
