---
sidebar: sidebar 
permalink: snapmirror-active-sync/mediator-install-task.html 
keywords: SM-BC, SMBC, cluster, peering, ONTAP Mediator, initialize, snapmirror active sync 
summary: SnapMirror 활성 동기화를 사용하려면 ONTAP 중재자를 설치 및 초기화하고 적절한 클러스터 피어링을 확인해야 합니다. 
---
= 활성 동기화에 대해 ONTAP 중재자 및 클러스터를 구성합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
SnapMirror 액티브 동기화는 피어링된 클러스터를 사용하여 페일오버 시나리오 발생 시 데이터를 사용할 수 있도록 합니다. ONTAP 중재자가 비즈니스 연속성을 보장하고 각 클러스터의 상태를 모니터링하는 주요 리소스입니다. SnapMirror 액티브 동기화를 구성하려면 먼저 ONTAP 중재자를 설치하고 운영 및 2차 클러스터가 올바르게 구성되었는지 확인해야 합니다.

ONTAP 중재자를 설치하고 클러스터를 구성한 후에는 반드시 다음을 수행해야 합니다 <<initialize-the-ontap-mediator>> SnapMirror 활성 동기화에 사용되는 ONTAP 중재자 그러면 됩니다 xref:../protect-task.html[SnapMirror 활성 동기화에 대한 일관성 그룹을 생성, 초기화 및 매핑합니다].



== ONTAP 중재자

ONTAP 중재자는 SnapMirror 활성 동기화 관계에서 ONTAP 클러스터에 대한 쿼럼을 설정합니다. 장애가 감지되면 자동 페일오버를 조정하여 운영 클러스터가 어떤 클러스터에 작동하는지 결정하고 데이터가 올바른 대상 간에 제공되는지 확인합니다.

.ONTAP 중재자를 위한 필수 조건
* ONTAP 중재자에는 고유한 사전 요구 사항이 포함되어 있습니다. 중재자를 설치하기 전에 이러한 전제 조건을 충족해야 합니다.
+
자세한 내용은 을 참조하십시오 link:https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/task_configuring_the_ontap_mediator_service_from_a_metrocluster_ip_configuration.html["ONTAP 중재자 서비스 설치 준비"^].

* 기본적으로 ONTAP 중재자가 TCP 포트 31784를 통해 서비스를 제공합니다. ONTAP 클러스터와 중재자 사이에 포트 31784가 열려 있고 사용할 수 있는지 확인해야 합니다.




== ONTAP 중재자를 설치하고 클러스터 구성을 확인합니다

다음 각 단계를 진행합니다. 각 단계에 대해 특정 구성이 수행되었는지 확인해야 합니다. 필요한 경우 각 단계 다음에 포함된 링크를 사용하여 자세한 정보를 얻을 수 있습니다.

.단계
. 소스 및 대상 클러스터가 올바르게 구성되었는지 확인하기 전에 ONTAP 중재자 서비스를 설치합니다.
+
xref:../mediator/index.html[ONTAP 중재자 서비스를 설치하거나 업그레이드할 준비를 합니다]

. 클러스터 피어링 관계가 클러스터 간에 존재하는지 확인합니다.
+

NOTE: 클러스터 피어 관계를 위한 SnapMirror 액티브 동기화에 기본 IPspace가 필요합니다. 사용자 지정 IPspace는 지원되지 않습니다.

+
xref:../task_dp_prepare_mirror.html[피어 관계를 구성합니다]

. 스토리지 VM이 각 클러스터에 생성되었는지 확인합니다.
+
xref:../smb-config/create-svms-data-access-task.html[SVM 생성]

. 각 클러스터의 스토리지 VM 간에 피어 관계가 있는지 확인합니다.
+
xref:../peering/create-intercluster-svm-peer-relationship-93-later-task.html[SVM 피어링 관계 생성]

. LUN에 대한 볼륨이 있는지 확인합니다.
+
xref:../smb-config/create-volume-task.html[볼륨을 생성하는 중입니다]

. 클러스터의 각 노드에 하나 이상의 SAN LIF가 생성되었는지 확인합니다.
+
link:../san-admin/lifs-cluster-concept.html["클러스터 SAN 환경에서 LIF에 대한 고려 사항"]

+
link:https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-sanag/GUID-4B666C44-694A-48A3-B0A9-517FA7FD2502.html?cp=13_6_4_0["LIF 생성"^]

. 필요한 LUN이 생성되어 igroup에 매핑되어 있는지 확인합니다. igroup은 애플리케이션 호스트의 이니시에이터에 LUN을 매핑하는 데 사용됩니다.
+
xref:../san-admin/create-luns-mapping-igroups-task.html[LUN을 생성하고 igroup을 매핑합니다]

. 애플리케이션 호스트를 재검색하여 새 LUN을 검색합니다.




== SnapMirror 활성 동기화에 대한 ONTAP 중재자를 초기화합니다

ONTAP 중재자를 설치하고 클러스터 구성을 확인한 후에는 클러스터 모니터링을 위한 ONTAP 중재자를 초기화해야 합니다. System Manager 또는 ONTAP CLI를 사용하여 ONTAP 중재자를 초기화할 수 있습니다.

[role="tabbed-block"]
====
.시스템 관리자
--
System Manager를 사용하면 자동화된 페일오버를 위해 ONTAP 중재자 서버를 구성할 수 있습니다. 자체 서명된 SSL 및 CA를 타사 인증 SSL 인증서 및 CA로 대체할 수도 있습니다(아직 수행하지 않은 경우).


IMPORTANT: ONTAP 9.8에서 9.14.1까지 SnapMirror 액티브 동기화를 SM-BC(SnapMirror Business Continuity)라고 합니다.

.단계
. 보호 > 개요 > 중재자 > 구성 * 으로 이동합니다.
. 추가 * 를 선택하고 다음 ONTAP 중재자 서버 정보를 입력합니다.
+
** IPv4 주소입니다
** 사용자 이름
** 암호
** 인증서




--
.CLI를 참조하십시오
--
ONTAP CLI를 사용하여 운영 클러스터 또는 2차 클러스터에서 ONTAP 중재자를 초기화할 수 있습니다. 를 발행할 때 `mediator add` 한 클러스터에서 ONTAP 중재자가 다른 클러스터에 자동으로 추가됩니다.

.단계
. 클러스터 중 하나에서 중재자를 초기화합니다.
+
'sapmirror add-중재자 - address ip_address-peer-cluster cluster_name - username user_name'

+
* 예 *

+
....
cluster1::> snapmirror mediator add -mediator-address 192.168.10.1 -peer-cluster cluster2 -username mediatoradmin
Notice: Enter the mediator password.

Enter the password: ******
Enter the password again: ******
....
. 중재자 구성의 상태를 확인합니다.
+
스냅미러 중재자 쇼

+
....
Mediator Address Peer Cluster     Connection Status Quorum Status
---------------- ---------------- ----------------- -------------
192.168.10.1     cluster-2        connected         true
....
+
`Quorum Status` SnapMirror 일관성 그룹 관계가 중재자와의 동기화 여부, 즉 상태를 나타냅니다 `true` 동기화가 성공했음을 나타냅니다.



--
====