---
sidebar: sidebar 
permalink: snapmirror-active-sync/monitor-task.html 
keywords: SM-BC, SMBC, monitoring, Mediator status, EMS, errors, planned failover status, automatic unplanned failover status, , snapmirror active sync 
summary: 모니터링할 수 있는 SnapMirror 활성 동기화 구성 요소 및 작업이 몇 가지 있습니다. 
---
= SnapMirror 활성 동기화 작업 모니터링
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
다음 SnapMirror 활성 동기화 작업을 모니터링하여 SnapMirror 활성 동기화 구성의 상태를 확인할 수 있습니다.

* ONTAP 중재자
* 계획된 페일오버 작업
* 계획되지 않은 페일오버 작업을 자동으로 수행합니다
* SnapMirror 활성 동기화 가용성



NOTE: ONTAP 9.15.1부터는 System Manager에 두 클러스터의 SnapMirror 활성 동기화 관계 상태가 표시됩니다. System Manager의 두 클러스터 중 하나에서 ONTAP 중재자의 상태를 모니터링할 수도 있습니다.



== ONTAP 중재자

정상 작동 중에는 ONTAP 중재자 상태가 연결되어야 합니다. 다른 상태에 있는 경우 오류 상태를 나타낼 수 있습니다. 를 검토할 수 있습니다 link:https://docs.netapp.com/us-en/ontap-ems-9131/sm-mediator-events.html["EMS(이벤트 관리 시스템) 메시지"^] 오류 및 적절한 수정 조치를 확인합니다.



== 계획된 페일오버 작업

'napmirror failover show' 명령을 사용하여 계획된 페일오버 작업의 상태 및 진행률을 모니터링할 수 있습니다. 예를 들면 다음과 같습니다.

....
ClusterB::> snapmirror failover start -destination-path vs1:/cg/dcg1
....
페일오버 작업이 완료되면 새 대상 클러스터에서 SnapMirror 보호 상태를 모니터링할 수 있습니다. 예를 들면 다음과 같습니다.

....
ClusterA::> snapmirror show
....
을 참조하십시오 link:https://docs.netapp.com/us-en/ontap-ems-9131/smbc-pfo-events.html["EMS 참조"^] 이벤트 메시지 및 수정 조치에 대해 알아보십시오.



== 계획되지 않은 페일오버 작업을 자동으로 수행합니다

계획되지 않은 자동 페일오버 중에 를 사용하여 작업 상태를 모니터링할 수 있습니다 `snapmirror failover show` 명령.

....
ClusterB::> snapmirror failover show -instance
Start Time: 9/23/2020 22:03:29
         Source Path: vs1:/cg/scg3
    Destination Path: vs3:/cg/dcg3
     Failover Status: completed
        Error Reason:
            End Time: 9/23/2020 22:03:30
Primary Data Cluster: cluster-2
Last Progress Update: -
       Failover Type: unplanned
  Error Reason codes: -
....
을 참조하십시오 link:https://docs.netapp.com/us-en/ontap-ems-9131/smbc-aufo-events.html["EMS 참조"^] 이벤트 메시지 및 수정 조치에 대해 알아보십시오.



== SnapMirror 활성 동기화 가용성

운영 클러스터, 2차 클러스터 또는 둘 다에서 일련의 명령을 사용하여 SnapMirror 액티브 동기화 관계의 가용성을 확인할 수 있습니다.

사용하는 명령에는 1차 및 2차 클러스터 모두에 대한 'napmirror 중재자 표시' 명령을 사용하여 연결 및 쿼럼 상태, 'napmirror show' 명령 및 'volume show' 명령을 확인할 수 있습니다. 예를 들면 다음과 같습니다.

....
SMBC_A::*> snapmirror mediator show
Mediator Address Peer Cluster     Connection Status Quorum Status
---------------- ---------------- ----------------- -------------
10.236.172.86    SMBC_B           connected         true

SMBC_B::*> snapmirror mediator show
Mediator Address Peer Cluster     Connection Status Quorum Status
---------------- ---------------- ----------------- -------------
10.236.172.86    SMBC_A           connected         true

SMBC_B::*> snapmirror show -expand
                                                                       Progress
Source            Destination Mirror  Relationship   Total             Last
Path        Type  Path        State   Status         Progress  Healthy Updated
----------- ---- ------------ ------- -------------- --------- ------- --------
vs0:/cg/cg1 XDP  vs1:/cg/cg1_dp Snapmirrored Insync -         true    -
vs0:vol1    XDP  vs1:vol1_dp  Snapmirrored Insync   -         true    -
2 entries were displayed.

SMBC_A::*> volume show -fields is-smbc-master,smbc-consensus,is-smbc-failover-capable -volume vol1
vserver volume is-smbc-master is-smbc-failover-capable smbc-consensus
------- ------ -------------- ------------------------ --------------
vs0     vol1   true           false                    Consensus

SMBC_B::*> volume show -fields is-smbc-master,smbc-consensus,is-smbc-failover-capable -volume vol1_dp
vserver volume  is-smbc-master is-smbc-failover-capable smbc-consensus
------- ------- -------------- ------------------------ --------------
vs1     vol1_dp false          true                     No-consensus
....