---
sidebar: sidebar 
permalink: snapmirror-active-sync/planned-failover-task.html 
keywords: SM-BC, testing failover, planned failover, maintenance, quorum, snapmirror active sync 
summary: 계획된 페일오버를 수행하여 재해 복구 구성을 테스트하거나 운영 클러스터에 대한 유지 관리를 수행할 수 있습니다. 
---
= SnapMirror 활성 동기화 관계에서 클러스터의 계획된 페일오버를 수행합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
SnapMirror 액티브 동기화 관계에서 ONTAP 클러스터의 계획된 페일오버에서는 운영 및 2차 클러스터의 역할을 전환하여 2차 클러스터가 운영 클러스터에서 페일오버되도록 합니다. 페일오버 중에 보조 클러스터는 클라이언트 작업을 중단하지 않고 로컬에서 입력 및 출력 요청을 처리합니다.

계획된 페일오버를 수행하여 재해 복구 구성의 상태를 테스트하거나 운영 클러스터에 대한 유지 관리를 수행할 수 있습니다.

.이 작업에 대해
계획된 페일오버는 보조 클러스터의 관리자가 시작합니다. 이 작업을 수행하려면 운영 및 2차 역할을 전환하여 2차 클러스터가 운영 클러스터에서 대신 수행하게 해야 합니다. 그러면 새로운 운영 클러스터가 클라이언트 작업을 중단하지 않고 로컬에서 입력 및 출력 요청 처리를 시작할 수 있습니다.

.시작하기 전에
* SnapMirror 활성 동기화 관계가 동기화되어 있어야 합니다.
* 무중단 운영이 진행 중인 경우에는 계획된 페일오버를 시작할 수 없습니다. 무중단 운영에는 볼륨 이동, 애그리게이트 재배치, 스토리지 페일오버가 포함됩니다.
* ONTAP 중재자는 구성, 연결 및 쿼럼에 있어야 합니다.


.단계
ONTAP CLI 또는 System Manager를 사용하여 계획된 페일오버를 수행할 수 있습니다.

[role="tabbed-block"]
====
.시스템 관리자
--

IMPORTANT: ONTAP 9.8에서 9.14.1까지 SnapMirror 액티브 동기화를 SM-BC(SnapMirror Business Continuity)라고 합니다.

. System Manager에서** 보호 > 개요 > 관계** 를 선택합니다.
. 페일오버할 SnapMirror 활성 동기화 관계를 확인합니다. 이름 옆에 있는 을 선택합니다 `...` 관계의 이름 옆에 있는 ** 장애 조치** 를 선택합니다.
. 페일오버 상태를 모니터링하려면 를 사용합니다 `snapmirror failover show` ONTAP CLI에서


--
.CLI를 참조하십시오
--
. 대상 클러스터에서 페일오버 작업을 시작합니다.
+
대상 경로 VS1_DST:/CG/CG_DST'에 대한 오류 수정:::> SnapMirror 페일오버 시작 대상 경로 VS1_DST:/CG/CG_DST

. 페일오버 진행률을 모니터링합니다.
+
대상::> SnapMirror failover show'

. 페일오버 작업이 완료되면 대상에서 SnapMirror 동기식 보호 관계 상태를 모니터링할 수 있습니다.
+
목적지::> SnapMirror 쇼



--
====