---
sidebar: sidebar 
permalink: snapmirror-active-sync/upgrade-revert-task.html 
keywords: upgrade, revert, snapmirror active sync, SMBC, SM-BC 
summary: ONTAP의 업그레이드나 복귀는 특히 ONTAP 9.9.1 이상 또는 9.7 이전 버전으로 전환할 때 SnapMirror 액티브 동기화 관계에 영향을 미칩니다. 
---
= SnapMirror 활성 동기화로 ONTAP 업그레이드 및 되돌리기
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
SnapMirror 액티브 동기화는 ONTAP 9.9.1부터 지원됩니다. ONTAP 클러스터의 업그레이드와 되돌리기는 업그레이드하거나 되돌리려는 ONTAP 버전에 따라 SnapMirror 활성 동기화 관계에 영향을 미칩니다.



== SnapMirror 활성 동기화로 ONTAP 업그레이드

SnapMirror 액티브 동기화를 사용하려면 소스 및 대상 클러스터의 모든 노드에서 ONTAP 9.9.1 이상을 실행해야 합니다.

활성 SnapMirror 활성 동기화 관계를 사용하여 ONTAP를 업그레이드할 때는 를 사용해야 합니다 xref:../upgrade/automated-upgrade-task.html[자동 무중단 업그레이드(ANDU)]. ANDU를 사용하면 SnapMirror 활성 동기화 관계가 동기화되고 업그레이드 프로세스 중에 정상 상태가 됩니다.

ONTAP 업그레이드를 위해 SnapMirror 액티브 동기화 배포를 준비하기 위한 구성 단계가 없습니다. 그러나 업그레이드 전후에 다음 사항을 확인하는 것이 좋습니다.

* SnapMirror 활성 동기화 관계가 동기화됩니다.
* 이벤트 로그에 SnapMirror와 관련된 오류가 없습니다.
* 중재자는 온라인 상태이며 두 클러스터에서 모두 정상입니다.
* 모든 호스트는 LUN을 보호하기 위해 모든 경로를 올바르게 볼 수 있습니다.



NOTE: ONTAP 9.9.1 또는 9.9.1에서 ONTAP 9.10.1 이상으로 클러스터를 업그레이드하면 ONTAP에서 새로운 을 생성합니다 xref:../consistency-groups/index.html[정합성 보장 그룹] 소스 및 대상 클러스터 모두에서 System Manager를 사용하여 SnapMirror 활성 동기화 관계를 구성할 수 있습니다.


NOTE: 를 클릭합니다 `snapmirror quiesce` 및 `snampirror resume` SnapMirror 활성 동기화에서는 명령이 지원되지 않습니다.



== ONTAP 9.10.1에서 ONTAP 9.9.1로 되돌립니다

관계를 9.10.1에서 9.9.1로 되돌리려면 SnapMirror 활성 동기화 관계를 삭제한 다음 9.10.1 일관성 그룹 인스턴스를 따라야 합니다. 활성 SnapMirror 활성 동기화 관계가 있는 일관성 그룹은 삭제할 수 없습니다. 9.9.1 이전 버전에서 다른 스마트 컨테이너 또는 엔터프라이즈 앱과 이전에 연결된 9.10.1로 업그레이드된 FlexVol 볼륨은 더 이상 복원 시 연결되지 않습니다. 일관성 그룹을 삭제해도 구성 볼륨 또는 볼륨 세부 스냅샷은 삭제되지 않습니다. 을 참조하십시오 link:../consistency-groups/delete-task.html["일관성 그룹을 삭제합니다"] ONTAP 9.10.1 이상에서 이 작업에 대한 자세한 내용을 확인하십시오.



== ONTAP 9.1.1에서 되돌리기


NOTE: ONTAP 9.9.1 이전 릴리즈보다 SnapMirror 활성 동기화는 혼합 ONTAP 클러스터에 지원되지 않습니다.

ONTAP 9.1.1에서 이전 버전의 ONTAP으로 되돌리는 경우 다음에 대해 알아야 합니다.

* 클러스터가 SnapMirror 활성 동기화 대상을 호스팅하는 경우 관계가 끊어져 삭제될 때까지 ONTAP 9.8 이전 버전으로 되돌릴 수 없습니다.
* 클러스터가 SnapMirror 액티브 동기화 소스를 호스팅하는 경우 관계가 해제될 때까지 ONTAP 9.8 이하로 되돌릴 수 없습니다.
* 사용자가 생성한 모든 맞춤형 SnapMirror 활성 동기화 정책을 삭제한 후 ONTAP 9.8 이하로 되돌려야 합니다.


이러한 요구 사항을 충족하려면 를 참조하십시오 link:remove-configuration-task.html["SnapMirror 활성 동기화 구성을 제거합니다"].

.단계
. SnapMirror 활성 동기화 관계의 클러스터 중 하나에서 다음 명령을 입력하여 되돌릴 준비가 되었는지 확인합니다.
+
`cluster::> system node revert-to -version 9.7 -check-only`

+
다음 샘플 출력에서는 정리 명령으로 되돌릴 준비가 되지 않은 클러스터를 보여 줍니다.

+
[listing]
----
cluster::> system node revert-to -version 9.7 -check-only
Error: command failed: The revert check phase failed. The following issues must be resolved before revert can be completed. Bring the data LIFs down on running vservers. Command to list the running vservers: vserver show -admin-state running Command to list the data LIFs that are up: network interface show -role data -status-admin up Command to bring all data LIFs down: network interface modify {-role data} -status-admin down
Disable snapshot policies.
    Command to list snapshot policies: "snapshot policy show".
    Command to disable snapshot policies: "snapshot policy modify -vserver
   * -enabled false"

   Break off the initialized online data-protection (DP) volumes and delete
   Uninitialized online data-protection (DP) volumes present on the local
   node.
    Command to list all online data-protection volumes on the local node:
   volume show -type DP -state online -node <local-node-name>
    Before breaking off the initialized online data-protection volumes,
   quiesce and abort transfers on associated SnapMirror relationships and
   wait for the Relationship Status to be Quiesced.
    Command to quiesce a SnapMirror relationship: snapmirror quiesce
    Command to abort transfers on a SnapMirror relationship: snapmirror
   abort
    Command to see if the Relationship Status of a SnapMirror relationship
   is Quiesced: snapmirror show
    Command to break off a data-protection volume: snapmirror break
    Command to break off a data-protection volume which is the destination
   of a SnapMirror relationship with a policy of type "vault": snapmirror
   break -delete-snapshots
    Uninitialized data-protection volumes are reported by the "snapmirror
   break" command when applied on a DP volume.
    Command to delete volume: volume delete

   Delete current version snapshots in advanced privilege level.
    Command to list snapshots: "snapshot show -fs-version 9.9.1"
    Command to delete snapshots: "snapshot prepare-for-revert -node
   <nodename>"

   Delete all user-created policies of the type active-strict-sync-mirror
   and active-sync-mirror.
   The command to see all active-strict-sync-mirror and active-sync-mirror
   type policies is:
    snapmirror policy show -type
   active-strict-sync-mirror,active-sync-mirror
   The command to delete a policy is :
    snapmirror policy delete -vserver <SVM-name> -policy <policy-name>
----
. 복원 검사의 요구 사항을 충족하면 을 참조하십시오 link:../revert/index.html["ONTAP를 되돌립니다"].

