---
permalink: smb-hyper-v-sql/add-sesecurityprivilege-user-account-task.html 
sidebar: sidebar 
keywords: add, sesecurityprivilege, privilege, user, aacount, sql, server, smb, share 
summary: 'SQL Server 설치에 사용되는 도메인 사용자 계정에는 도메인 사용자에게 기본적으로 할당되지 않은 권한이 필요한 CIFS 서버에서 특정 작업을 수행하려면 "SeSecurityPrivilege" 권한이 할당되어야 합니다.' 
---
= sSecurityPrivilege 권한을 사용자 계정에 추가합니다(SMB 공유의 SQL Server에 해당).
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SQL Server 설치에 사용되는 도메인 사용자 계정에는 "'seSecurityPrivilege'" 권한이 할당되어 있어야 도메인 사용자에게 기본적으로 할당되지 않은 권한이 필요한 CIFS 서버에서 특정 작업을 수행할 수 있습니다.

SQL Server 설치에 사용되는 도메인 계정이 이미 있어야 합니다.

SQL Server 설치 관리자의 계정에 권한을 추가할 때 ONTAP는 도메인 컨트롤러에 연락하여 계정의 유효성을 검사할 수 있습니다. ONTAP가 도메인 컨트롤러에 연결할 수 없으면 명령이 실패할 수 있습니다.

.단계
. "seSecurityPrivilege" 권한 추가:
+
'* vserver cifs users-and-groups 권한 add-privilege-vserver_vserver_name_-user-or-group-name_account_name_-Privileges SeSecurityPrivilege*'

+
'-user-or-group-name' 매개 변수의 값은 SQL Server 설치에 사용되는 도메인 사용자 계정의 이름입니다.

. 계정에 권한이 적용되는지 확인합니다.
+
'* vserver cifs users-and-groups 권한 show -vserver_vserver_name_-user-or-group-name_account_name_*'



다음 명령을 실행하면 SVM(Storage Virtual Machine) VS1 예제 도메인의 SQL Server 설치 관리자 계정에 "seSecurityPrivilege" 권한이 추가됩니다.

[listing]
----
cluster1::> vserver cifs users-and-groups privilege add-privilege -vserver vs1 -user-or-group-name EXAMPLE\SQLinstaller -privileges SeSecurityPrivilege

cluster1::> vserver cifs users-and-groups privilege show -vserver vs1
Vserver   User or Group Name          Privileges
--------- ---------------------       ---------------
vs1       EXAMPLE\SQLinstaller        SeSecurityPrivilege
----