---
permalink: smb-hyper-v-sql/configure-shares-continuous-availability-task.html 
sidebar: sidebar 
keywords: configure, shares, continuous, availability, hyper, v, sql, server, virutal, machine, database, file 
summary: Hyper-V 및 SQL Server 애플리케이션 서버에서 Hyper-V 가상 머신 및 구성 파일, SQL Server 데이터베이스 파일에 중단 없이 액세스하는 데 사용하는 공유를 계속 사용할 수 있도록 기존 공유를 수정할 수 있습니다. 
---
= 지속적인 가용성을 위해 기존 공유를 구성합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Hyper-V 및 SQL Server 애플리케이션 서버에서 Hyper-V 가상 머신 및 구성 파일, SQL Server 데이터베이스 파일에 중단 없이 액세스하는 데 사용하는 공유를 계속 사용할 수 있도록 기존 공유를 수정할 수 있습니다.

공유에 다음과 같은 특성이 있는 경우 SMB를 통해 애플리케이션 서버와 무중단 운영을 위해 기존 공유를 지속적으로 사용할 수 있는 공유로 사용할 수 없습니다.

* 이 공유에 homedory 공유 속성이 설정되어 있으면
* 공유에 활성화된 symlink 또는 widelink가 포함된 경우
* 공유에 공유의 루트 아래에 접합된 볼륨이 포함되어 있는 경우


다음 두 공유 매개 변수가 올바르게 설정되었는지 확인해야 합니다.

* '-offline-files' 매개변수는 수동(기본값) 또는 없음(없음)으로 설정됩니다.
* Symlink를 비활성화해야 합니다.


다음 공유 속성을 구성해야 합니다.

* "계속 사용할 수 있습니다.
* oplocks


다음 공유 속성을 설정하지 않아야 합니다. 현재 공유 속성 목록에 있는 경우 지속적으로 사용 가능한 공유에서 제거해야 합니다.

* 'attributecache
* 브랜치캐시
* '액세스 기반 열거'


.단계
. 현재 공유 매개 변수 설정 및 구성된 공유 속성의 현재 목록을 표시합니다.
+
'* vserver cifs share show -vserver_vserver_name_-share-name_share_name_*'

. 필요한 경우 공유 매개 변수를 수정하여 'vserver cifs share properties modify' 명령을 사용하여 symlinks를 비활성화하고 오프라인 파일을 수동으로 설정합니다.
+
'-symlink' 매개 변수의 값을 ""로 설정하여 symlink를 비활성화할 수 있습니다.

+
** '-symlink' 매개 변수의 값을 ""로 설정하여 symlink를 비활성화할 수 있습니다.
** '-offline-files' 파라미터는 'Manual'을 지정하여 올바른 설정으로 설정할 수 있습니다.


. 지속적 사용 가능 공유 속성을 추가하고 필요한 경우 oplocks 공유 속성을 추가합니다.
+
'* vserver CIFS 공유 속성 add-vserver_vserver_name_-share-name_share_name_-share-properties Continuously-available[,oplock]*'

+
oplocks 공유 속성이 아직 설정되지 않은 경우 계속 사용 가능한 공유 속성과 함께 추가해야 합니다.

. 지속적으로 사용 가능한 공유에서 지원되지 않는 공유 속성을 제거합니다.
+
'* vserver cifs 공유 속성 제거 - vserver_vserver_name_-share-name_share_name_-share-properties 속성[,...] *

+
쉼표로 구분된 목록으로 공유 속성을 지정하여 하나 이상의 공유 속성을 제거할 수 있습니다.

. '-symlink' 및 '-offline-files' 매개 변수가 올바르게 설정되었는지 확인합니다.
+
'* vserver cifs share show -vserver_vserver_name_-share-name_share_name_-fields symlink-properties, offline-files *

. 구성된 공유 속성 목록이 올바른지 확인합니다.
+
'* vserver cifs 공유 속성 표시 - vserver_vserver_name_-share-name share_name*'



다음 예에서는 SMB를 통해 애플리케이션 서버를 사용하는 NDO를 위해 SVM(Storage Virtual Machine) VS1 에서 이름이 "share1"인 기존 공유를 구성하는 방법을 보여 줍니다.

* '-symlink' 매개 변수를 ""로 설정하여 공유에서 Symlink를 사용할 수 없습니다.
* '-offline-file' 파라미터가 수정되어 'manual'로 설정됩니다.
* 이 공유에 계속 이용 가능한 공유자산이 추가됩니다.
* oplocks 공유 속성은 이미 공유 속성 목록에 있으므로 추가할 필요가 없습니다.
* 이 지분에서는 attributecache 공유재산을 빼내기도 합니다.
* "탐색 가능" 공유 속성은 SMB를 통해 애플리케이션 서버와 NDO에 사용되는 지속적인 사용 가능 공유에 대한 선택 사항이며 공유 속성 중 하나로 유지됩니다.


[listing]
----
cluster1::> vserver cifs share show -vserver vs1 -share-name share1

                      Vserver: vs1
                        Share: share1
     CIFS Server NetBIOS Name: vs1
                         Path: /data
             Share Properties: oplocks
                               browsable
                               attributecache
           Symlink Properties: enable
      File Mode Creation Mask: -
 Directory Mode Creation Mask: -
                Share Comment: -
                    Share ACL: Everyone / Full Control
File Attribute Cache Lifetime: 10s
                  Volume Name: data
                Offline Files: documents
Vscan File-Operations Profile: standard

cluster1::> vserver cifs share modify -vserver vs1 -share-name share1 -offline-file manual -symlink ""

cluster1::> vserver cifs share properties add -vserver vs1 -share-name share1 -share-properties continuously-available

cluster1::> vserver cifs share properties remove -vserver vs1 -share-name share1 -share-properties attributecache

cluster1::> vserver cifs share show -vserver vs1 -share-name share1 -fields symlink-properties,offline-files
vserver  share-name symlink-properties offline-files
-------- ---------- ------------------ -------------
vs1      share1    -                  manual

cluster1::> vserver cifs share properties show -vserver vs1 -share-name share1

         Vserver: vs1
           Share: share1
Share Properties: oplocks
                  browsable
                  continuously-available
----