---
permalink: smb-hyper-v-sql/continuously-available-share-sql-concept.html 
sidebar: sidebar 
keywords: continuously, share, requirements, considerations, sql, server, smb, nondisuptive 
summary: 무중단 운영을 지원하는 SMB 구성을 통해 SQL Server에 대해 지속적으로 사용 가능한 공유를 구성할 때 특정 요구사항과 고려 사항을 알고 있어야 합니다. 
---
= SMB를 통한 SQL Server의 지속적인 가용성 공유 요구 사항 및 고려 사항
:icons: font
:imagesdir: ../media/


[role="lead"]
무중단 운영을 지원하는 SMB 구성을 통해 SQL Server에 대해 지속적으로 사용 가능한 공유를 구성할 때 특정 요구사항과 고려 사항을 알고 있어야 합니다.



== 공유 요구 사항

* 가상 머신 파일을 저장하는 데 사용되는 볼륨은 NTFS 보안 스타일 볼륨으로 만들어야 합니다.
+
지속적으로 사용 가능한 SMB 연결을 통해 애플리케이션 서버에 무중단 운영을 제공하려면 공유를 포함하는 볼륨이 NTFS 볼륨이어야 합니다. 또한 항상 NTFS 볼륨이어야 합니다. 혼합 보안 스타일 볼륨 또는 UNIX 보안 스타일 볼륨을 NTFS 보안 스타일 볼륨으로 변경하고 SMB 공유를 통한 무중단 운영에 직접 사용할 수는 없습니다. 혼합 보안 스타일 볼륨을 NTFS 보안 스타일 볼륨으로 변경하고 SMB 공유를 통한 무중단 작업에 사용하려면 ACL을 볼륨 상단에 수동으로 배치하고 해당 ACL을 포함된 모든 파일 및 폴더에 전파해야 합니다. 그렇지 않으면 소스 또는 대상 볼륨이 처음에 혼합 또는 UNIX 보안 스타일 볼륨으로 생성된 후 나중에 NTFS 보안 스타일로 변경된 경우 가상 머신 마이그레이션 또는 데이터베이스 파일 내보내기 및 가져오기가 다른 볼륨으로 이동될 수 있습니다.

* 응용 프로그램 서버에서 사용하는 공유는 지속적으로 사용 가능한 속성 집합을 사용하여 구성해야 합니다.
+
지속적으로 사용 가능한 공유에 연결되는 애플리케이션 서버에는 SMB 공유에 중단 없이 다시 연결할 수 있는 영구 핸들이 제공되며, 테이크오버, 반환, 애그리게이트 재배치와 같은 운영 중단 이벤트가 발생한 후 파일 잠금을 재확보할 수 있습니다.

* 데이터베이스 파일이 포함된 볼륨에는 접합부가 포함될 수 있지만 SQL Server는 데이터베이스 디렉토리 구조를 생성할 때 접합을 교차하지 않습니다.
* Microsoft SQL Server용 SnapManager 백업 작업이 성공하려면 볼륨에 충분한 공간이 있어야 합니다.
+
SQL Server 데이터베이스 파일이 있는 볼륨은 데이터베이스 디렉토리 구조와 공유 내에 있는 모든 포함된 파일을 저장할 수 있을 만큼 커야 합니다.

* 애플리케이션 서버에서 계속 사용 가능한 공유에 대해 다음 공유 속성을 설정하지 않아야 합니다.
+
** 더 높여 줍니다
** 특성 캐싱
** BranchCache입니다
** 액세스 기반 열거






== 공유 고려 사항

* 할당량은 지속적으로 사용 가능한 공유에서 지원됩니다.
* SMB를 통한 SQL Server 구성에서는 다음 기능이 지원되지 않습니다.
+
** 감사
** FPolicy를 참조하십시오


* 지속적으로 사용 가능한 공유 자산이 설정된 SMB 공유에서는 바이러스 검사가 수행되지 않습니다.

