---
permalink: smb-hyper-v-sql/display-open-smb-files-task.html 
sidebar: sidebar 
keywords: display, information, open, smb, file, session, id, nondisruptive, protection, level 
summary: SMB 연결 및 세션 ID, 호스팅 볼륨, 공유 이름 및 공유 경로를 포함하여 열려 있는 SMB 파일에 대한 정보를 표시할 수 있습니다. 또한 파일의 지속적으로 사용 가능한 보호 수준에 대한 정보를 표시할 수도 있습니다. 이 정보는 열려 있는 파일이 무중단 작업을 지원하는 상태에 있는지 여부를 확인하는 데 유용합니다. 
---
= 열려 있는 SMB 파일에 대한 정보를 표시합니다
:icons: font
:imagesdir: ../media/


[role="lead"]
SMB 연결 및 세션 ID, 호스팅 볼륨, 공유 이름 및 공유 경로를 포함하여 열려 있는 SMB 파일에 대한 정보를 표시할 수 있습니다. 또한 파일의 지속적으로 사용 가능한 보호 수준에 대한 정보를 표시할 수도 있습니다. 이 정보는 열려 있는 파일이 무중단 작업을 지원하는 상태에 있는지 여부를 확인하는 데 유용합니다.

설정된 SMB 세션에서 열린 파일에 대한 정보를 표시할 수 있습니다. 표시된 정보는 SMB 세션 내의 특정 파일에 대한 SMB 세션 정보를 확인해야 할 때 유용합니다.

예를 들어, 열린 파일 중 일부가 지속적으로 사용 가능한 보호 기능을 통해 열려 있고 일부는 지속적으로 사용 가능한 보호 기능을 통해 열려 있지 않은 SMB 세션이 있는 경우(vserver cifs session show 명령의 출력 값이 부분(Partial)인 경우), 이 명령을 사용하여 계속 사용할 수 없는 파일을 확인할 수 있습니다.

선택적 매개 변수 없이 'vserver cifs session file show' 명령을 사용하면 SVM(스토리지 가상 시스템)에서 설정된 SMB 세션의 모든 열려 있는 파일에 대한 정보를 요약 형식으로 표시할 수 있습니다.

그러나 대부분의 경우 반환되는 출력량이 큽니다. 선택적 매개 변수를 지정하여 출력에 표시되는 정보를 사용자 지정할 수 있습니다. 이 기능은 열려 있는 파일의 작은 하위 집합에 대한 정보만 보려는 경우에 유용합니다.

* 옵션 '-fields' 매개변수를 사용하여 선택한 필드에 출력을 표시할 수 있습니다.
+
이 매개 변수는 단독으로 사용하거나 다른 선택적 매개 변수와 함께 사용할 수 있습니다.

* '-instance' 매개 변수를 사용하여 열려 있는 SMB 파일에 대한 자세한 정보를 표시할 수 있습니다.
+
이 매개 변수는 단독으로 사용하거나 다른 선택적 매개 변수와 함께 사용할 수 있습니다.



.단계
. 다음 작업 중 하나를 수행합니다.
+
|===
| 열려 있는 SMB 파일을 표시하려면... | 다음 명령을 입력합니다... 


 a| 
SVM에 대해 요약 형식으로 표시됩니다
 a| 
'* vserver cifs 세션 파일 표시 - vserver_vserver_name_*'



 a| 
지정된 노드에서
 a| 
'* vserver CIFS 세션 파일 show -vserver_vserver_name_-node{node_name | local} *



 a| 
지정된 파일 ID에 있습니다
 a| 
'* vserver cifs 세션 파일 표시 - vserver_vserver_name_-file-id integer*'



 a| 
지정된 SMB 연결 ID에서
 a| 
'* vserver cifs 세션 파일 표시 - vserver_vserver_name_-connection-id integer*'



 a| 
지정된 SMB 세션 ID에서
 a| 
'* vserver cifs 세션 파일 표시 - vserver_vserver_name_-session-id integer*'



 a| 
지정된 호스팅 집계에서
 a| 
'* vserver cifs 세션 파일 표시 - vserver_vserver_name_-hosting-aggregate_aggregate_name_*'



 a| 
지정된 볼륨에서
 a| 
'* vserver cifs 세션 파일 표시 - vserver_vserver_name_-hosting-volume_volume_name_*'



 a| 
지정된 SMB 공유에서
 a| 
'* vserver CIFS 세션 파일 표시 - vserver_vserver_name_-share_share_name_*'



 a| 
지정된 SMB 경로에 있어야 합니다
 a| 
'* vserver CIFS 세션 파일 표시 - vserver_vserver_name_-path_path_*'



 a| 
지속적으로 사용 가능한 보호 수준을 지정합니다
 a| 
'* vserver cifs 세션 파일 표시 - vserver_vserver_name_-Continuously-available_Continuously_available_status_ *

'-연속 사용 가능'의 값은 다음 중 하나일 수 있습니다.

** 아니
** 네
+
[NOTE]
====
계속 사용 가능한 상태가 '아니요'인 경우 열려 있는 파일은 Takeover와 Giveback에서 중단 없이 복구할 수 없습니다. 또한, 고가용성 관계에 있는 파트너 간의 일반 애그리게이트 재배치에서 복구할 수 없습니다.

====




 a| 
지정된 다시 연결된 상태에서
 a| 
'* vserver cifs 세션 파일 표시 - vserver_vserver_name_-다시 연결됨_다시 연결됨_상태_*'

'-Reconnected'의 값은 다음 중 하나일 수 있습니다.

** 아니
** 네
+
[NOTE]
====
다시 연결된 상태가 No인 경우 연결 해제 이벤트 후 열린 파일이 다시 연결되지 않습니다. 이는 파일 연결이 끊겼거나 파일 연결이 끊어지고 성공적으로 다시 연결되지 않음을 의미할 수 있습니다. 다시 연결된 상태가 Yes인 경우, 연결 해제 이벤트 후 열린 파일이 성공적으로 재연결되었음을 의미한다.

====


|===
+
출력 결과를 구체화하는 데 사용할 수 있는 추가 선택적 매개 변수가 있습니다. 자세한 내용은 man 페이지를 참조하십시오.



다음 예에서는 SVM VS1 에서 열린 파일에 대한 정보를 표시합니다.

[listing]
----
cluster1::> vserver cifs session file show -vserver vs1
Node:       node1
Vserver:    vs1
Connection: 3151274158
Session:    1
File    File      Open Hosting               Continuously
ID      Type      Mode Volume    Share       Available
------- --------- ---- --------- ----------- ------------
41      Regular   r    data      data        Yes
Path: \mytest.rtf
----
다음 예에서는 SVM VS1에서 파일 ID 82가 있는 개방형 SMB 파일에 대한 자세한 정보를 표시합니다.

[listing]
----
cluster1::> vserver cifs session file show -vserver vs1 -file-id 82 -instance

                  Node: node1
               Vserver: vs1
               File ID: 82
         Connection ID: 104617
            Session ID: 1
             File Type: Regular
             Open Mode: rw
Aggregate Hosting File: aggr1
   Volume Hosting File: data1
            CIFS Share: data1
  Path from CIFS Share: windows\win8\test\test.txt
            Share Mode: rw
           Range Locks: 1
Continuously Available: Yes
           Reconnected: No
----