---
permalink: smb-hyper-v-sql/nondisruptive-operations-glossary-concept.html 
sidebar: sidebar 
keywords: key, concepts, nondisruptive, operation, hyper, v, sql, server, smb, configure 
summary: 'SMB 솔루션을 통해 Hyper-V 또는 SQL Server를 구성하기 전에 알아야 하는 무중단 운영(NDO)에 대한 몇 가지 개념이 있습니다.' 
---
= SMB를 통한 Hyper-V 및 SQL Server의 무중단 운영에 대한 주요 개념입니다
:icons: font
:imagesdir: ../media/


[role="lead"]
SMB 솔루션을 통해 Hyper-V 또는 SQL Server를 구성하기 전에 알아야 하는 무중단 운영(NDO)에 대한 몇 가지 개념이 있습니다.

* * 지속적으로 사용 가능한 공유 *
+
지속적으로 사용 가능한 공유 속성이 설정된 SMB 3.0 공유입니다. 지속적으로 사용 가능한 공유를 통해 연결하는 클라이언트는 테이크오버, 반환 및 애그리게이트 재배치와 같은 운영 중단 이벤트를 견딜 수 있습니다.

* * 노드 *
+
클러스터의 구성원인 단일 컨트롤러입니다. SFO 쌍의 두 노드를 구별하기 위해 한 노드는 _ local node _ 라고도 하며 다른 노드는 _ partner node _ 또는 _ remote node _ 라고도 합니다. 스토리지의 기본 소유자는 로컬 노드입니다. 기본 소유자가 실패하는 경우 스토리지를 제어하는 보조 소유자가 파트너 노드입니다. 각 노드는 해당 스토리지의 기본 소유자이며 파트너의 스토리지를 위한 2차 소유자입니다.

* * 무중단 애그리게이트 재배치 *
+
클라이언트 애플리케이션을 중단하지 않고 클러스터에서 SFO 쌍 내의 파트너 노드 간에 애그리게이트를 이동할 수 있습니다.

* 무중단 페일오버 * 를 지원합니다
+
테이크오버를 참조하십시오.

* * 무중단 LIF 마이그레이션 *
+
LIF를 통해 클러스터에 연결된 클라이언트 애플리케이션을 중단하지 않고 LIF 마이그레이션을 수행할 수 있습니다. SMB 연결의 경우 SMB 2.0 이상을 사용하여 연결하는 클라이언트에만 가능합니다.

* 무중단 운영 *
+
주요 ONTAP 관리 및 업그레이드 작업을 수행할 뿐만 아니라 클라이언트 애플리케이션을 중단하지 않고 노드 장애를 견딜 수 있는 기능 이때 무중단 테이크오버, 무중단 업그레이드, 무중단 마이그레이션 기능이 전반적으로 사용됩니다.

* 무중단 업그레이드 *
+
애플리케이션 중단 없이 노드 하드웨어 또는 소프트웨어를 업그레이드할 수 있는 기능

* * 무중단 볼륨 이동 *
+
볼륨을 사용하는 애플리케이션을 중단하지 않고 클러스터 전체에서 볼륨을 자유롭게 이동할 수 있습니다. SMB 연결의 경우, 모든 버전의 SMB가 무중단 볼륨 이동을 지원합니다.

* * 영구 핸들 *
+
연결이 끊길 경우 지속적으로 사용 가능한 연결을 통해 CIFS 서버에 투명하게 다시 연결할 수 있도록 하는 SMB 3.0의 속성입니다. 내구성이 뛰어난 핸들과 마찬가지로 연결 클라이언트와의 통신이 끊긴 후 CIFS 서버가 일정 시간 동안 영구 핸들을 유지합니다. 그러나 지속적인 핸들은 내구성 있는 핸들보다 뛰어난 복원력을 제공합니다. 다시 연결한 후 60초 이내에 클라이언트에서 핸들을 다시 확보할 수 있는 기회를 제공할 뿐 아니라 CIFS 서버는 60초 동안 파일에 대한 액세스를 요청하는 다른 클라이언트에 대한 액세스를 거부합니다.

+
영구 핸들에 대한 정보는 SFO 파트너의 영구 스토리지에 미러링되므로, 영구 핸들이 분리된 클라이언트는 SFO 파트너가 노드 스토리지에 대한 소유권을 갖게 된 후 내구성 있는 핸들을 다시 확보할 수 있습니다. 지속적인 핸들은 LIF 이동 시 무중단 운영(내구성이 뛰어난 핸들 지원)을 제공할 뿐만 아니라 테이크오버, 반환 및 애그리게이트 재배치를 위한 무중단 운영을 제공합니다.

* SFO 반환 *
+
테이크오버 이벤트에서 복구할 때 애그리게이트를 홈 위치로 반환

* SFO 쌍 *
+
두 노드 중 하나가 작동을 중지할 경우 컨트롤러가 상호 데이터를 제공하도록 구성된 노드 쌍입니다. 시스템 모델에 따라 두 컨트롤러 모두 단일 섀시 내에 있거나 컨트롤러가 별도 섀시에 있을 수 있습니다. 2노드 클러스터에서 HA 쌍이라고 합니다.

* * 테이크오버 *
+
해당 스토리지의 기본 소유자가 실패한 경우 파트너가 스토리지를 제어하는 프로세스입니다. SFO 맥락에서 페일오버 및 테이크오버는 동의어입니다.


