---
permalink: smb-hyper-v-sql/remote-vss-considerations-concept.html 
sidebar: sidebar 
keywords: remote, vss, consideration, hyper, v, smb, configuration, backup, solution, automatic, recovery, shadow, copy 
summary: SMB를 통한 Hyper-V 구성에 대해 원격 VSS 지원 백업 솔루션을 사용할 때는 특정 고려 사항을 염두에 두어야 합니다. 
---
= SMB 구성을 통한 Hyper-V에 대한 원격 VSS 고려 사항
:icons: font
:imagesdir: ../media/


[role="lead"]
SMB를 통한 Hyper-V 구성에 대해 원격 VSS 지원 백업 솔루션을 사용할 때는 특정 고려 사항을 염두에 두어야 합니다.



== 일반 원격 VSS 고려 사항

* Microsoft 애플리케이션 서버당 최대 64개의 공유를 구성할 수 있습니다.
+
섀도우 복제본 세트에 64개 이상의 공유가 있는 경우 섀도우 복제본 작업이 실패합니다. 이는 Microsoft의 요구 사항입니다.

* CIFS 서버당 하나의 활성 섀도 복사본 세트만 허용됩니다.
+
동일한 CIFS 서버에 섀도우 복제본 작업이 진행 중인 경우 섀도우 복제본 작업이 실패합니다. 이는 Microsoft의 요구 사항입니다.

* 원격 VSS가 섀도우 복제본을 생성하는 디렉토리 구조 내에서는 접합을 수행할 수 없습니다.
+
** 자동 복구 사례에서는 공유를 이동하는 동안 분기점이 발생하면 섀도우 복제본 생성이 실패합니다.
** 비자동 복구 사례에서는 섀도우 복제본 생성이 실패하지 않지만 접합은 아무 것도 가리키지 않습니다.






== 자동 복구를 사용하는 섀도우 복제본에만 적용되는 원격 VSS 고려 사항

자동 복구를 사용하는 섀도 복사본에만 특정 제한사항이 적용됩니다.

* 섀도우 복제본 생성에는 하위 디렉토리 5개의 최대 디렉토리 수준이 허용됩니다.
+
섀도우 복제본 서비스가 섀도우 복제본 백업 세트를 생성하는 디렉토리 깊이입니다. 가상 머신 파일이 포함된 디렉토리가 5개 수준 이상 중첩되면 섀도우 복제본 생성이 실패합니다. 이는 공유를 복제할 때 디렉토리 트래버설을 제한하기 위한 것입니다. 최대 디렉토리 깊이는 CIFS 서버 옵션을 사용하여 변경할 수 있습니다.

* 볼륨의 사용 가능한 공간이 적절해야 합니다.
+
사용 가능한 공간은 섀도 복사본 백업 세트에 포함된 공유 내에 포함된 모든 파일, 디렉토리 및 하위 디렉토리에 사용되는 결합된 공간보다 최소한 크거나 같아야 합니다.

* 원격 VSS가 섀도우 복제본을 생성하는 디렉토리 구조 내에서 링크나 일반 파일이 허용되지 않습니다.
+
공유에 섀도 복사본에 대한 링크 또는 비정규 파일이 있는 경우 섀도 복사본 생성이 실패합니다. 클론 프로세스에서 이를 지원하지 않습니다.

* 디렉토리에는 NFSv4 ACL이 허용되지 않습니다.
+
섀도우 복제본 생성이 파일에 NFSv4 ACL을 유지하지만 디렉토리의 NFSv4 ACL이 손실됩니다.

* 섀도 복사본 세트를 생성할 수 있는 시간은 최대 60초입니다.
+
Microsoft 사양은 섀도 복사본 세트를 생성하는 데 최대 60초를 허용합니다. VSS 클라이언트가 이 시간 내에 섀도우 복제본 세트를 생성할 수 없는 경우 섀도우 복제본 작업이 실패하므로 섀도우 복제본 세트의 파일 수가 제한됩니다. 백업 세트에 포함될 수 있는 실제 파일 또는 가상 머신 수는 서로 다르며, 이 수는 여러 요인에 따라 달라지며 각 고객 환경에 따라 결정되어야 합니다.


