---
permalink: smb-hyper-v-sql/verify-security-style-svm-root-volume-ntfs-task.html 
sidebar: sidebar 
keywords: verify, security, style, svm, root, volume, ntfs, storage, virtual, machine 
summary: 'Hyper-V 및 SQL Server over SMB의 무중단 운영이 성공하려면 NTFS 보안 스타일로 볼륨을 만들어야 합니다. 루트 볼륨의 보안 스타일은 스토리지 가상 시스템(SVM)에서 생성된 볼륨에 기본적으로 적용되므로 루트 볼륨의 보안 스타일을 NTFS로 설정해야 합니다.' 
---
= SVM 루트 볼륨의 보안 스타일이 NTFS로 설정되어 있는지 확인합니다
:icons: font
:imagesdir: ../media/


[role="lead"]
Hyper-V 및 SQL Server over SMB의 무중단 운영이 성공하려면 NTFS 보안 스타일로 볼륨을 만들어야 합니다. 루트 볼륨의 보안 스타일은 SVM(스토리지 가상 머신)에서 생성된 볼륨에 기본적으로 적용되므로 루트 볼륨의 보안 스타일을 NTFS로 설정해야 합니다.

.이 작업에 대해
* SVM을 생성할 때 루트 볼륨 보안 스타일을 지정할 수 있습니다.
* 루트 볼륨이 NTFS 보안 스타일로 설정되어 있는 SVM이 생성되지 않으면 나중에 'volume modify' 명령을 사용하여 보안 스타일을 변경할 수 있습니다.


.단계
. SVM 루트 볼륨의 현재 보안 유형을 확인합니다.
+
'* volume show -vserver_vserver_name_- 필드 vserver, 볼륨, 보안 스타일 *

. 루트 볼륨이 NTFS 보안 스타일 볼륨이 아닌 경우 보안 스타일을 NTFS로 변경합니다.
+
'* volume modify -vserver_vserver_name_-volume root_volume_name -security-style NTFS * '

. SVM 루트 볼륨이 NTFS 보안 스타일로 설정되었는지 확인합니다.
+
'* volume show -vserver_vserver_name_- 필드 vserver, 볼륨, 보안 스타일 *



다음 명령은 SVM VS1 에서 루트 볼륨 보안 스타일이 NTFS인지 확인합니다.

[listing]
----
cluster1::> volume show -vserver vs1 -fields vserver,volume,security-style
vserver  volume     security-style
-------- ---------- --------------
vs1      vs1_root   unix

cluster1::> volume modify -vserver vs1 -volume vs1_root -security-style ntfs

cluster1::> volume show -vserver vs1 -fields vserver,volume,security-style
vserver  volume     security-style
-------- ---------- --------------
vs1      vs1_root   ntfs
----