---
permalink: smb-hyper-v-sql/witness-protocol-transparent-failover-concept.html 
sidebar: sidebar 
keywords: witness, protocol, transparent, failover, lif, ca, share, client, smb, recovery 
summary: 'Witness 프로토콜은 SMB 3.0에서 지속적으로 사용 가능한 공유(CA 공유)를 위한 향상된 클라이언트 페일오버 기능을 제공합니다. 입회자는 LIF 페일오버 복구 기간을 거치지 않으므로 더 빠른 페일오버를 촉진합니다. SMB 3.0 연결이 시간 초과될 때까지 기다리지 않고 노드를 사용할 수 없을 때 애플리케이션 서버에 알립니다.' 
---
= Witness 프로토콜이 투명한 장애 조치를 강화하기 위해 수행하는 조치
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Witness 프로토콜은 SMB 3.0에서 지속적으로 사용 가능한 공유(CA 공유)를 위한 향상된 클라이언트 페일오버 기능을 제공합니다. 입회자는 LIF 페일오버 복구 기간을 거치지 않으므로 더 빠른 페일오버를 촉진합니다. SMB 3.0 연결이 시간 초과될 때까지 기다리지 않고 노드를 사용할 수 없을 때 애플리케이션 서버에 알립니다.

클라이언트에서 실행 중인 애플리케이션이 페일오버가 발생했는지 알지 못하면서 페일오버가 원활하게 이루어집니다. Witness를 사용할 수 없는 경우에도 페일오버 작업은 성공적으로 수행되지만 Witness를 사용하지 않는 페일오버는 효율성이 떨어집니다.

다음 요구 사항이 충족되면 감시 강화 장애 조치가 가능합니다.

* SMB 3.0이 활성화된 SMB 3.0 지원 CIFS 서버에서만 사용할 수 있습니다.
* 공유는 지속적인 가용성 공유 속성 세트와 함께 SMB 3.0을 사용해야 합니다.
* 애플리케이션 서버가 연결되는 노드의 SFO 파트너는 애플리케이션 서버의 데이터를 호스팅하는 SVM(스토리지 가상 머신)에 적어도 하나의 운영 데이터 LIF가 할당되어 있어야 합니다.
+
[NOTE]
====
Witness 프로토콜은 SFO 쌍 사이에서 작동합니다. LIF가 클러스터 내의 노드로 마이그레이션할 수 있으므로 모든 노드가 SFO 파트너의 증인이 될 수 있습니다. 애플리케이션 서버용 데이터를 호스팅하는 SVM이 파트너 노드에 활성 데이터 LIF가 없는 경우 Witness 프로토콜은 특정 노드에서 SMB 연결을 빠르게 페일오버할 수 없습니다. 따라서 클러스터의 모든 노드는 이러한 구성 중 하나를 호스팅하는 각 SVM에 대해 적어도 하나의 데이터 LIF를 가져야 합니다.

====
* 애플리케이션 서버는 개별 LIF IP 주소를 사용하는 대신 DNS에 저장된 CIFS 서버 이름을 사용하여 CIFS 서버에 연결해야 합니다.

