---
permalink: file-system-analytics/activity-tracking-task.html 
sidebar: sidebar 
keywords: monitor, volume, ontap, FSA, File System Analytics, 
summary: 작업 추적 기능을 사용하면 핫 개체를 식별하고 CSV 파일로 다운로드할 수 있습니다. 
---
= 활동 추적을 활성화합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9.10.1부터 파일 시스템 분석에는 핫 객체를 식별하고 CSV 파일로 다운로드할 수 있는 활동 추적 기능이 포함되어 있습니다. ONTAP 9.11.1부터 활동 추적 기능이 SVM 범위로 확장됩니다. 또한 ONTAP 9.11.1부터 System Manager에서 활동 추적 타임라인을 제공하므로 활동 추적 데이터를 최대 5분 동안 살펴볼 수 있습니다.

Activity Tracking(활동 추적)을 사용하면 다음 네 가지 범주로 모니터링할 수 있습니다.

* 디렉토리
* 파일
* 클라이언트
* 사용자


모니터링되는 각 범주에 대해 작업 추적은 읽기 IOPS, 쓰기 IOPS, 읽기 처리량 및 쓰기 처리량을 표시합니다. 작업 추적에 대한 쿼리는 이전 5초 간격 동안 시스템에 표시되는 핫 스팟과 관련하여 10-15초마다 새로 고쳐집니다.

활동 추적 정보는 근사치이며, 데이터의 정확도는 수신되는 I/O 트래픽의 분포에 따라 달라집니다.

System Manager의 볼륨 레벨에서 활동 추적을 보면 확장된 볼륨의 메뉴만 활발하게 새로 고쳐집니다. 볼륨 보기가 축소되면 볼륨 표시가 확장될 때까지 볼륨이 새로 고쳐지지 않습니다. 새로 고침 일시 중지 * 버튼을 사용하여 새로 고침을 중지할 수 있습니다. 활동 데이터는 선택한 볼륨에 대해 캡처된 모든 시점 데이터를 표시하는 CSV 형식으로 다운로드할 수 있습니다.

ONTAP 9.11.1부터 일정 기능을 사용할 수 있으므로 볼륨 또는 SVM에서 핫스팟 활동 기록을 유지하고 약 5초마다 지속적으로 업데이트하며 이전 5분 동안의 데이터를 유지할 수 있습니다. 시간 표시 막대 데이터는 페이지의 표시 영역에 있는 필드에만 유지됩니다. 시간 표시 막대가 표시되지 않도록 추적 범주를 축소하거나 스크롤하면 시간 표시 막대가 데이터 수집을 중지합니다. 기본적으로 타임라인은 비활성화되어 있으며 활동 탭에서 멀리 이동하면 자동으로 비활성화됩니다.



== 단일 볼륨에 대해 활동 추적을 활성화합니다

ONTAP 시스템 관리자 또는 ONTAP CLI를 사용하여 활동 추적을 설정할 수 있습니다.

.이 작업에 대해
ONTAP REST API 또는 시스템 관리자와 함께 RBAC를 사용하는 경우 활동 추적에 대한 액세스를 관리하기 위해 사용자 지정 역할을 만들어야 합니다. 을 참조하십시오 xref:role-based-access-control-task.html[역할 기반 액세스 제어] 참조하십시오.

[role="tabbed-block"]
====
.시스템 관리자
--
.단계
. 스토리지 > 볼륨 * 을 선택합니다. 원하는 볼륨을 선택합니다. 개별 볼륨 메뉴에서 파일 시스템 을 선택한 다음 활동 탭을 선택합니다.
. 상위 디렉토리, 파일, 클라이언트 및 사용자에 대한 개별 보고서를 보려면 * Activity Tracking * 이 켜져 있어야 합니다.
. 새로 고침 없이 보다 깊이 있는 데이터를 분석하려면 * 새로 고침 일시 중지 * 를 선택합니다. 데이터를 다운로드하여 보고서의 CSV 레코드도 가질 수 있습니다.


--
.CLI를 참조하십시오
--
.단계
. 활동 추적 활성화:
+
'볼륨 활동 - vssverver_svm_name_-volume_volume_name_'

. 다음 명령을 사용하여 볼륨에 대한 활동 추적 상태가 ON 또는 OFF 상태인지 확인할 수 있습니다.
+
'volume activity-tracking show -vsverver_svm_name_-volume_volume_name_-state

. 활성화되면 ONTAP 시스템 관리자 또는 ONTAP REST API를 사용하여 활동 추적 데이터를 표시합니다.


--
====


== 여러 볼륨에 대해 활동 추적을 활성화합니다

System Manager에서 여러 볼륨에 대한 활동 추적을 한 번에 활성화할 수 있습니다.

.이 작업에 대해
ONTAP REST API 또는 시스템 관리자와 함께 RBAC를 사용하는 경우 활동 추적에 대한 액세스를 관리하기 위해 사용자 지정 역할을 만들어야 합니다. 을 참조하십시오 <<Role-based access control (RBAC) and Activity Tracking>> 참조하십시오.

[role="tabbed-block"]
====
.특정 볼륨에 대해
--
.단계
. 스토리지 > 볼륨 * 을 선택합니다. 원하는 볼륨을 선택합니다. 개별 볼륨 메뉴에서 파일 시스템 을 선택한 다음 활동 탭을 선택합니다.
. 활동 추적을 활성화할 볼륨을 선택합니다. 볼륨 목록 상단에서 * 추가 옵션 * 버튼을 선택합니다. 작업 추적 활성화 * 를 선택합니다.
. SVM 레벨에서 활동 추적을 보려면 * 스토리지 > 볼륨 * 에서 보려는 특정 SVM을 선택합니다. File System(파일 시스템) 탭, Activity(활동) 로 이동하면 Activity Tracking(활동 추적)이 활성화된 볼륨에 대한 데이터가 표시됩니다.


--
.SVM에서 모든 볼륨의 볼륨을 지원합니다
--
.단계
. 스토리지 > 볼륨 * 을 선택합니다. 메뉴에서 SVM을 선택합니다.
. File System * 탭으로 이동하고 * More * 탭을 선택하여 SVM의 모든 볼륨에서 활동 추적을 활성화합니다.


--
====