---
permalink: file-system-analytics/activity-tracking-task.html 
sidebar: sidebar 
keywords: monitor, volume, ontap, FSA, File System Analytics, 
summary: 작업 추적 을 사용하여 실시간 성능 문제 해결을 위해 지정된 볼륨에서 핫 파일, 디렉토리, 클라이언트 및 사용자를 봅니다 
---
= 활동 추적을 활성화합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9.10.1부터 파일 시스템 분석에는 활동 추적을 사용하여 핫 객체를 식별하고 CSV 파일로 다운로드할 수 있는 활동 추적 기능이 포함되어 있습니다.

Activity Tracking(활동 추적)을 사용하면 다음 네 가지 범주로 모니터링할 수 있습니다.

* 디렉토리
* 파일
* 클라이언트
* 사용자


모니터링되는 각 범주에 대해 작업 추적은 읽기 IOPS, 쓰기 IOPS, 읽기 처리량 및 쓰기 처리량을 표시합니다. 작업 추적에 대한 쿼리는 이전 5초 간격 동안 시스템에 표시되는 핫 스팟과 관련하여 10-15초마다 새로 고쳐집니다.

활동 추적 정보는 근사치이며, 데이터의 정확도는 수신되는 I/O 트래픽의 분포에 따라 달라집니다.

System Manager에서 활동 추적을 볼 때 확장된 볼륨의 메뉴만 활발하게 새로 고쳐집니다. 볼륨 보기가 축소되면 볼륨 표시가 확장될 때까지 볼륨이 새로 고쳐지지 않습니다. 새로 고침 일시 중지 * 버튼을 사용하여 새로 고침을 중지할 수 있습니다. 활동 데이터는 선택한 볼륨에 대해 캡처된 모든 시점 데이터를 표시하는 CSV 형식으로 다운로드할 수 있습니다.

ONTAP REST API 또는 시스템 관리자와 함께 RBAC를 사용하는 경우 활동 추적에 대한 액세스를 관리하기 위해 사용자 지정 역할을 만들어야 합니다. 을 참조하십시오 xref:considerations-concept.html#RBAC[파일 시스템 분석을 위한 고려 사항] 참조하십시오.



== 절차를 참조하십시오

ONTAP 시스템 관리자, ONTAP CLI 또는 ONTAP REST API를 사용하여 활동 추적을 설정할 수 있습니다.

[role="tabbed-block"]
====
.시스템 관리자
--
. 스토리지 > 볼륨 * 을 선택합니다. 원하는 볼륨을 선택합니다. 개별 볼륨 메뉴에서 파일 시스템 을 선택한 다음 활동 탭을 선택합니다.
. 상위 디렉토리, 파일, 클라이언트 및 사용자에 대한 개별 보고서를 보려면 * Activity Tracking * 이 켜져 있어야 합니다.
. 새로 고침 없이 보다 깊이 있는 데이터를 분석하려면 * 새로 고침 일시 중지 * 를 선택합니다. 데이터를 다운로드하여 보고서의 CSV 레코드도 가질 수 있습니다.


--
.CLI를 참조하십시오
--
. 활동 추적 활성화: + '볼륨 활동 - vssverver_svm_name_-volume_volume_name_'
. 볼륨에 대한 Activity Tracking 상태가 On 또는 Off 상태인지 확인하려면 + 'volume activity-tracking show -vsverver_svm_name_-volume_volume_name_-state' 명령을 사용합니다
. 활성화되면 ONTAP 시스템 관리자 또는 ONTAP REST API를 사용하여 활동 추적 데이터를 표시합니다.


--
====