---
sidebar: sidebar 
permalink: file-system-analytics/considerations-concept.html 
keywords: file system analytics, performance, SVM 
summary: File System Analytics는 활성 NAS 데이터가 있는 볼륨에 대한 가시성을 제공하도록 설계되었습니다. 사용 시 제한 및 제한 사항이 있습니다. 
---
= 파일 시스템 분석을 위한 고려 사항
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
File System Analytics 구축과 관련된 특정 사용량 제한 및 잠재적 성능 영향을 알고 있어야 합니다.



== SVM 보호 관계

SVM이 포함된 볼륨에서 파일 시스템 분석을 사용하도록 설정한 경우, 분석 데이터가 타겟 SVM에 복제되지 않습니다. 복구 작업에서 소스 SVM을 재동기화해야 하는 경우 복구 후 원하는 볼륨에 대한 분석을 수동으로 다시 활성화해야 합니다.



== 성능 고려 사항

경우에 따라 초기 메타데이터 수집 중에 파일 시스템 분석을 사용하도록 설정하면 성능에 부정적인 영향을 미칠 수 있습니다. 이는 일반적으로 최대 사용률이 있는 시스템에서 가장 많이 나타납니다. 이러한 시스템에 대한 분석을 사용하지 않으려면 ONTAP System Manager 성능 모니터링 툴을 사용하면 됩니다.

지연 시간이 현저하게 증가하는 경우 기술 자료 문서를 참조하십시오 link:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/High_or_fluctuating_latency_after_turning_on_NetApp_ONTAP_File_System_Analytics["NetApp ONTAP 파일 시스템 분석을 켠 후 지연 시간이 높거나 변동이 심한 경우"^].



== 스캔 고려 사항

용량 분석을 활성화하면 ONTAP에서 초기화 스캔을 수행합니다. 이 스캔은 용량 분석이 활성화된 볼륨의 모든 파일에 대한 메타데이터에 액세스합니다. 스캔 중에 파일 데이터가 읽혀지지 않습니다.

검색이 완료되면 파일 시스템이 변경됨에 따라 파일 시스템 분석이 실시간으로 계속 업데이트되므로 스캔을 다시 실행할 필요가 없습니다.

스캔에 필요한 시간은 볼륨의 디렉토리 및 파일 수에 비례합니다. 스캔은 메타데이터를 수집하므로 파일 크기는 스캔 시간에 영향을 주지 않습니다.

초기화 스캔에 대한 자세한 내용은 을 참조하십시오 link:https://www.netapp.com/pdf.html?item=/media/20707-tr-4867.pdf["TR-4867: 파일 시스템 분석을 위한 모범 사례 지침"^].



=== 모범 사례

애그리게이트를 공유하지 않는 볼륨에서 스캔을 시작해야 합니다. 명령을 사용하여 현재 어떤 애그리게이트가 어떤 볼륨을 호스팅하고 있는지 확인할 수 있습니다.

`volume show -volume _comma-separated-list_of_volumes_ -fields aggr-list`

검사가 실행되는 동안 볼륨은 계속해서 클라이언트 트래픽을 처리합니다. 클라이언트 트래픽이 낮을 것으로 예상되는 기간 동안 스캔을 시작하는 것이 좋습니다.

클라이언트 트래픽이 증가하면 시스템 리소스가 소모되고 스캔 시간이 길어집니다.

ONTAP 9.12.1부터 시스템 관리자 및 ONTAP CLI에서 데이터 수집을 일시 중지할 수 있습니다.

* ONTAP CLI를 사용하는 경우:
+
** 다음 명령을 사용하여 데이터 수집을 일시 중지할 수 있습니다. `volume analytics initialization pause -vserver _svm_name_ -volume _volume_name_`
** 클라이언트 트래픽이 느려지면 다음 명령을 사용하여 데이터 수집을 다시 시작할 수 있습니다. `volume analytics initialization resume -vserver _svm_name_ -volume _volume_name_`


* System Manager를 사용하는 경우 볼륨 메뉴의 * 탐색기 * 보기에서 * 데이터 수집 일시 중지 * 및 * 데이터 수집 다시 시작 * 버튼을 사용하여 스캔을 관리합니다.

