---
permalink: file-system-analytics/usage-size-task.html 
sidebar: sidebar 
keywords: large directories, system manager, file system analytics, usage, top directories 
summary: 작업 추적 을 사용하여 실시간 성능 문제 해결을 위해 지정된 볼륨에서 핫 파일, 디렉토리, 클라이언트 및 사용자를 봅니다 
---
= 사용 분석 지원
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9.12.1부터 사용 분석을 통해 볼륨 내에서 공간이 가장 많은 디렉토리를 볼 수 있습니다. 볼륨의 총 디렉토리 수 또는 볼륨의 총 파일 수를 볼 수 있습니다. 보고는 가장 많은 공간을 사용하는 25개 디렉토리로 제한됩니다.

대규모 디렉토리에 대한 분석 기능은 15분마다 업데이트됩니다. 페이지 맨 위에서 마지막으로 새로 고친 타임스탬프를 확인하여 가장 최근 새로 고침을 모니터링할 수 있습니다. 다운로드 단추를 클릭하여 Excel 통합 문서로 데이터를 다운로드할 수도 있습니다. 다운로드 작업은 백그라운드에서 실행되며 선택한 볼륨에 대해 가장 최근에 보고된 정보를 제공합니다. 검사가 결과 없이 반환되는 경우 볼륨이 온라인 상태인지 확인합니다. SnapRestore와 같은 이벤트로 인해 파일 시스템 분석 시 대규모 디렉토리 목록이 재구축됩니다.

.단계
. 스토리지 > 볼륨 * 을 선택합니다. 원하는 볼륨을 선택합니다.
. 개별 볼륨 메뉴에서 * 파일 시스템 * 을 선택합니다. 그런 다음 * Usage * 탭을 선택합니다.
. 분석 * 스위치를 전환하여 사용 분석을 활성화합니다.
. System Manager는 크기가 가장 큰 디렉토리를 내림차순으로 식별하는 막대 그래프를 표시합니다.
+

NOTE: 최상위 디렉토리 목록이 수집되는 동안 ONTAP는 부분 데이터를 표시하거나 데이터를 전혀 표시하지 않을 수 있습니다. 스캔 진행 상황은 스캔 중에 표시되는 * Usage * (사용 *) 탭에 있을 수 있습니다.



특정 디렉토리에 대한 더 많은 통찰력을 얻을 수 있습니다 xref:../task_nas_file_system_analytics_view.html[파일 시스템에 대한 작업을 봅니다].
