---
permalink: antivirus/apply-scanner-policy-pool-task.html 
sidebar: sidebar 
keywords: apply, scanner policy, single, cluster 
summary: 스캐너 정책은 스캐너 풀이 활성 상태인지 여부를 결정합니다. 스캐너 풀에 정의된 Vscan 서버가 SVM에 연결될 수 있으려면 먼저 스캐너 풀을 활성화해야 합니다. 
---
= 단일 클러스터에 스캐너 정책을 적용합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
스캐너 정책은 스캐너 풀이 활성 상태인지 여부를 결정합니다. 스캐너 풀에 정의된 Vscan 서버가 SVM에 연결될 수 있으려면 먼저 스캐너 풀을 활성화해야 합니다.

.이 작업에 대해
* 스캐너 풀에는 하나의 스캐너 정책만 적용할 수 있습니다.
* 클러스터에서 모든 SVM에 대해 스캐너 풀을 생성한 경우 각 SVM에 개별적으로 스캐너 정책을 적용해야 합니다.
* 재해 복구 및 MetroCluster 구성의 경우 로컬 클러스터 및 파트너 클러스터의 스캐너 풀에 스캐너 정책을 적용해야 합니다.
+
로컬 클러스터에 대해 생성한 정책에서 'cluster' 매개 변수에 로컬 클러스터를 지정해야 합니다. 파트너 클러스터에 대해 생성한 정책에서 'cluster' 매개 변수에 파트너 클러스터를 지정해야 합니다. 그러면 파트너 클러스터가 재해 발생 시 바이러스 검사 작업을 대신 수행할 수 있습니다.



.단계
. 스캐너 정책 적용:
+
'vserver vscan scanner -pool apply -policy -vserver data_SVM -scanner -pool scanner_pool -scanner -policy primary | secondary|idle -cluster cluster_to_apply_policy_on'

+
스캐너 정책은 다음 값 중 하나를 가질 수 있습니다.

+
** "기본"은 스캐너 풀이 활성화되도록 지정합니다.
** '2차'는 기본 스캐너 풀에 Vscan 서버가 연결되어 있지 않은 경우에만 스캐너 풀이 활성화되도록 지정합니다.
** "유휴"는 스캐너 풀이 비활성 상태라고 지정합니다.


+
다음 예에서는 "VS1" SVM에서 "P"라는 스캐너 풀이 활성 상태임을 보여줍니다.

+
[listing]
----
cluster1::> vserver vscan scanner-pool apply-policy -vserver vs1 -scanner-pool SP  -scanner-policy primary
----
. 스캐너 풀이 활성화되었는지 확인합니다.
+
'vserver vscan scanner -pool show -vserver data_SVM|cluster_admin_SVM-scanner -pool scanner_pool'

+
전체 옵션 목록은 명령에 대한 man 페이지를 참조하십시오.

+
다음 명령을 실행하면 'S' 스캐너 풀에 대한 세부 정보가 표시됩니다.

+
[listing]
----
cluster1::> vserver vscan scanner-pool show -vserver vs1 -scanner-pool SP

                                    Vserver: vs1
                               Scanner Pool: SP
                             Applied Policy: primary
                             Current Status: on
         Cluster on Which Policy Is Applied: cluster1
                  Scanner Pool Config Owner: vserver
       List of IPs of Allowed Vscan Servers: 1.1.1.1, 10.72.204.27
List of Host Names of Allowed Vscan Servers: 1.1.1.1, vmwin204-27.fsct.nb
                   List of Privileged Users: cifs\u1, cifs\u2
----
+
SVM에서 활성 스캐너 풀을 보려면 'vserver vscan scanner -pool show -active' 명령을 사용하십시오. 전체 명령 구문은 명령에 대한 man 페이지를 참조하십시오.


