---
permalink: antivirus/architecture-concept.html 
sidebar: sidebar 
keywords: antivirus, architecture 
summary: NetApp 바이러스 백신 아키텍처는 Vscan 서버와 일련의 ONTAP 구성 가능으로 구성됩니다. 
---
= 안티바이러스 아키텍처
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NetApp 바이러스 백신 아키텍처는 Vscan 서버와 일련의 ONTAP 구성 가능으로 구성됩니다.



== Vscan 서버 구성 요소

Vscan 서버에 다음 구성 요소를 설치해야 합니다.

* * ONTAP 안티바이러스 커넥터 *
+
NetApp에서 제공하는 ONTAP 바이러스 백신 커넥터는 ONTAP와 Vscan 서버 간의 통신을 처리합니다.

* * 안티바이러스 소프트웨어 *
+
ONTAP 호환 타사 바이러스 백신 소프트웨어는 파일에서 바이러스 또는 기타 악성 코드를 검사합니다. 소프트웨어를 구성할 때 감염된 파일에 대해 수행할 치료 조치를 지정합니다.





== ONTAP 구성 가능

NetApp 스토리지 시스템에서 다음 항목을 구성해야 합니다.

* * 스캐너 풀 *
+
스캐너 풀은 SVM에 연결할 수 있는 Vscan 서버 및 특별 권한 사용자를 정의합니다. 또한 스캔 요청 시간 초과 기간을 정의하며, 이 기간이 지나면 스캔 요청이 다른 Vscan 서버로 전송됩니다(사용 가능한 경우).

+
[NOTE]
====
Vscan 서버의 바이러스 백신 소프트웨어에서 스캐너 풀 요청 시간 초과 기간보다 5초 이내로 시간 초과 기간을 설정하는 것이 좋습니다. 소프트웨어의 시간 제한 기간이 스캔 요청의 시간 초과 기간보다 크기 때문에 파일 액세스가 모두 지연되거나 거부되는 상황을 방지하기 위해

====
* * 특별 권한 사용자 *
+
권한이 있는 사용자는 Vscan 서버에서 SVM에 연결하는 데 사용하는 도메인 사용자 계정입니다. 계정은 스캐너 풀에 정의된 권한이 있는 사용자 목록에 포함되어야 합니다.

* * 스캐너 정책 *
+
스캐너 정책은 스캐너 풀이 활성 상태인지 여부를 결정합니다. 스캐너 정책은 다음 값 중 하나를 가질 수 있습니다.

+
** "기본"은 스캐너 풀이 활성화되도록 지정합니다.
** '2차'는 기본 스캐너 풀에 Vscan 서버가 연결되어 있지 않은 경우에만 스캐너 풀이 활성화되도록 지정합니다.
** "유휴"는 스캐너 풀이 비활성 상태라고 지정합니다. 스캐너 정책은 시스템 정의입니다. 사용자 정의 스캐너 정책을 생성할 수 없습니다.


* * 액세스 시 정책 *
+
액세스 시 정책은 액세스 시 검사의 범위를 정의합니다. 스캔할 파일의 최대 크기, 스캔에 포함할 파일의 확장명, 스캔에서 제외할 파일의 확장명 및 경로를 지정할 수 있습니다.

+
기본적으로 읽기-쓰기 볼륨만 스캔됩니다. 읽기 전용 볼륨을 스캔할 수 있도록 하거나 실행 액세스 권한으로 연 파일로 스캔을 제한하는 필터를 지정할 수 있습니다.

+
** '스캔-볼륨'은 읽기 전용 볼륨을 스캔할 수 있게 해줍니다.
** '스캔 실행 액세스'는 실행 권한으로 연 파일로 스캔을 제한합니다.
+
[NOTE]
====
"접속 실행"은 "실행 권한"과 동일하지 않습니다. 특정 클라이언트는 파일이 "실행 의도"로 열린 경우에만 실행 파일에 "실행 액세스"를 가집니다.

====


+
바이러스 검사를 위해 Vscan 서버를 사용할 수 없는 경우 파일 액세스가 허용되도록 '스캔 필수' 옵션을 꺼짐으로 설정할 수 있습니다.

* * 온디맨드 작업 *
+
온디맨드 작업은 온디맨드 스캔의 범위를 정의합니다. 스캔할 파일의 최대 크기, 스캔에 포함할 파일의 확장명 및 경로, 스캔에서 제외할 파일의 확장명 및 경로를 지정할 수 있습니다. 하위 디렉터리의 파일은 기본적으로 스캔됩니다.

+
cron 일정을 사용하여 작업 실행 시간을 지정합니다. 'vserver vscan on-demand-task run' 명령을 사용하여 작업을 즉시 실행할 수 있습니다.

* * Vscan 파일 작업 프로필(액세스 시 스캔에만 해당) *
+
'vserver cifs share create' 명령의 '-vscan-filoop-profile' 매개변수는 SMB 공유에서 바이러스 스캔을 트리거할 수 있는 작업을 정의합니다. 기본적으로 매개 변수는 NetApp 모범 사례인 '표준'으로 설정됩니다.

+
SMB 공유를 생성하거나 수정할 때 필요에 따라 이 매개 변수를 조정할 수 있습니다.

+
** NO-SCAN은 공유에 대해 바이러스 검사가 트리거되지 않도록 지정합니다.
** '표준'은 열기, 닫기 및 이름 바꾸기 작업을 통해 바이러스 검사를 실행할 수 있음을 지정합니다.
** '중독'은 열기, 읽기, 닫기 및 이름 바꾸기 작업을 통해 바이러스 검사를 실행할 수 있음을 지정합니다.
+
이 '사전' 프로필은 여러 클라이언트가 동시에 파일에 액세스하는 상황에 대해 향상된 보안을 제공합니다. 한 클라이언트에서 바이러스를 작성한 후 파일을 닫고 두 번째 클라이언트에서 동일한 파일을 열어 둘 경우 두 번째 클라이언트에서 읽기 작업을 수행하면 파일이 닫히기 전에 검사가 트리거됩니다.

+
예상되는 파일이 포함된 공유로 '중독' 프로필을 제한해야 합니다. 프로파일이 다른 프로파일보다 많은 스캔 요청을 생성하므로 성능에 부정적인 영향을 미칠 수 있습니다.

** 쓰기 전용 은 수정된 파일이 닫힐 때만 바이러스 검사가 트리거되도록 지정합니다.
+
[NOTE]
====
클라이언트 응용 프로그램에서 이름 바꾸기 작업을 수행하면 파일이 새 이름으로 닫히고 스캔되지 않습니다. 이러한 작업이 환경에 보안 문제가 될 경우 '표준' 또는 '중독' 프로필을 사용해야 합니다.

====
+
쓰기 전용은 다른 프로파일(스캔 안 함 제외)보다 스캔 요청이 적으므로 일반적으로 성능이 향상됩니다.

+
그러나 공유에 이 프로필을 사용하는 경우 나중에 클라이언트가 액세스할 수 없도록 검사기는 복구할 수 없는 감염된 파일을 삭제하거나 격리하도록 구성해야 합니다. 예를 들어, 클라이언트가 바이러스에 감염된 후 파일을 닫고 파일이 복구, 삭제 또는 격리되지 않은 경우, 파일에 대한 _기록 없이_에 액세스하는 모든 클라이언트가 감염됩니다.




