---
permalink: antivirus/best-practices-configure-off-box-antivirus-functionality-concept.html 
sidebar: sidebar 
keywords: off-box, clustered ONTAP, antivirus, 
summary: Clustered ONTAP에서 바이러스 백신 기능을 오프박스 방식으로 구성하려면 다음 권장 사항을 고려하십시오. 
---
= clustered ONTAP에서 바이러스 백신 기능을 구성하는 모범 사례
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Clustered ONTAP에서 즉시 사용 가능한 기능을 구성하기 위한 다음과 같은 권장 사항을 고려하십시오.

* 권한이 있는 사용자를 바이러스 검사 작업으로 제한합니다. 정상적인 사용자는 에서 사용하지 않아야 합니다
권한이 있는 사용자 자격 증명 사용. 이 제한은 에 대한 로그인 권한을 해제하여 수행할 수 있습니다
Active Directory의 권한이 있는 사용자.
* 권한이 있는 사용자는 에서 많은 권한을 가진 사용자 그룹의 일부가 될 필요가 없습니다
administrators 그룹 또는 백업 운영자 그룹과 같은 도메인입니다. 권한이 있는 사용자는 이어야 합니다
Vscan 서버 연결 및 을 생성할 수 있도록 스토리지 시스템에서만 검증되었습니다
바이러스 검사를 위해 파일에 액세스합니다.
* Vscan 서버를 실행하는 컴퓨터는 바이러스 검사 목적으로만 사용하십시오. 일반적인 것을 방지하기 위해
이러한 컴퓨터에서 Windows 터미널 서비스 및 기타 원격 액세스 제공을 사용하지 않도록 설정합니다
또한 관리자에게만 이러한 컴퓨터에 새 소프트웨어를 설치할 수 있는 권한을 부여합니다.
* Vscan 서버를 바이러스 검사 전용으로 사용하고 백업과 같은 다른 작업에는 사용하지 마십시오.
Vscan 서버를 가상 머신(VM)으로 실행하기로 결정할 수 있습니다. 이 경우 확인하십시오
VM에 할당된 리소스가 공유되지 않으며 바이러스 검사를 수행하기에 충분합니다. 컨설팅
link:http://www.symantec.com/business/support/index?page=home["시만텍"^] 바이러스 백신 엔진 요구 사항에 대한 지침
* 리소스를 방지하기 위해 Vscan 서버에 적절한 CPU, 메모리 및 디스크 용량을 제공합니다
병목 현상. 대부분의 Vscan 서버는 여러 CPU 코어 서버를 사용하고 를 배포하도록 설계되었습니다
CPU 전반에 걸쳐 로드. 컨설팅 link:http://www.symantec.com/business/support/index?page=home["시만텍"^] 바이러스 백신 엔진 요구 사항에 대한 지침
* NetApp에서는 SVM과의 연결을 위해 전용 네트워크 및 전용 VLAN을 사용할 것을 권장합니다
스캔 트래픽이 다른 클라이언트 네트워크 트래픽의 영향을 받지 않도록 Vscan 서버로 전송합니다. 을 생성합니다
Vscan 서버의 바이러스 백신 VLAN 전용 NIC와 의 데이터 LIF 전용 NIC를 분리합니다
SVM 이 단계는 네트워크 문제가 발생할 경우 관리 및 문제 해결을 간소화합니다.
AV 트래픽은 사설 네트워크를 사용하여 분리해야 합니다. AV 서버를 로 구성해야 합니다
다음 방법 중 하나로 DC(도메인 컨트롤러) 및 clustered ONTAP과 통신합니다.
+
** DC는 트래픽을 분리하는 데 사용되는 사설 네트워크를 통해 AV 서버와 통신해야 합니다.
** DC 및 AV 서버는 앞서 언급한 개인 네트워크가 아닌 다른 네트워크를 통해 통신해야 합니다. 이는 CIFS 클라이언트 네트워크와 동일하지 않습니다.




Kerberos 인증이 AV 통신에 작동하려면 개인용 DNS 항목을 만듭니다
LIF 및 프라이빗에 대해 생성된 DNS 항목에 해당하는 DC의 서비스 주체 이름입니다
LIF: 이 이름은 AV 커넥터에 LIF를 추가할 때 사용합니다. DNS는 를 반환할 수 있어야 합니다
AV 커넥터에 연결된 각 프라이빗 LIF의 고유 이름입니다.


NOTE: 중요: Vscan 트래픽용 LIF가 클라이언트 트래픽용 LIF와 다른 포트에 구성된 경우 Vscan LIF가 이를 초과할 수 있습니다
포트 장애 발생 시 다른 노드로 페일오버 이 변경 사항을 통해 에서 Vscan 서버에 연결할 수 없게 됩니다
노드의 파일 작업에 대한 새 노드 및 스캔 알림이 실패합니다.
Vscan 서버가 스캔을 처리할 수 있도록 노드에 있는 하나 이상의 LIF를 통해 서버에 연결할 수 있는지 확인합니다
해당 노드에서 수행되는 파일 작업 요청입니다.

* 1GbE 네트워크 이상을 사용하여 NetApp 스토리지 시스템과 Vscan 서버를 연결합니다.
* Vscan 서버가 여러 대 있는 환경의 경우 유사한 고성능 서버가 있는 모든 서버를 연결합니다
네트워크 연결. Vscan 서버를 연결하면 부하 공유를 허용하여 성능이 향상됩니다.
* 원격 사이트 및 지사의 경우 NetApp는 가 아닌 로컬 Vscan 서버를 사용할 것을 권장합니다
원격 Vscan 서버는 전자가 지연 시간이 길기 때문에 완벽한 제품입니다. 비용이 요인인 경우 를 사용합니다
보통 수준의 바이러스 보호를 위한 랩톱 또는 PC. 정기적으로 전체 파일 시스템 검사를 예약할 수 있습니다
볼륨 또는 qtree를 공유하고 원격 사이트의 모든 시스템에서 스캔함으로써
* 여러 대의 Vscan 서버를 사용하여 SVM에서 데이터를 스캔하여 로드 밸런싱 및 중복성을 확보할 수 있습니다
목적. CIFS 워크로드 양과 그에 따른 바이러스 백신 트래픽은 SVM당 다릅니다. CIFS를 모니터링합니다
또한 스토리지 컨트롤러의 바이러스 검사 지연 시간을 사용할 수 있습니다. 시간 경과에 따른 결과 추세 분석 CIFS 지연 시간
또한 Vscan 서버의 CPU 또는 애플리케이션 병목 현상으로 인해 바이러스 검사 지연 시간이 늘어납니다
추세 임계값 외에 CIFS 클라이언트의 대기 시간이 오래 걸릴 수 있습니다. Vscan 서버를 추가합니다
하중을 분산시킵니다.
* 최신 버전의 Antivirus Connector를 설치합니다. 지원 가능성에 대한 자세한 내용은 를 참조하십시오
link:https://imt.netapp.com/matrix/#welcome["NetApp 상호 운용성 매트릭스 툴(IMT)"].
* 바이러스 백신 엔진과 정의를 최신 상태로 유지합니다. 컨설팅 link:https://login.broadcom.com/["시만텍"^] 업데이트에 대한 권장 사항을 참조하십시오
주파수.
* 다중 임차 환경에서는 스캐너 풀(Vscan 서버 풀)을 여러 대의 와 공유할 수 있습니다
SVM은 Vscan 서버와 SVM이 동일한 도메인 또는 신뢰할 수 있는 도메인의 일부일 경우에 제공됩니다
도메인.
* 감염된 파일에 대한 AV 소프트웨어 정책은 기본값인 삭제 또는 쿼런틴으로 설정해야 합니다
대부분의 AV 공급업체에서 설정한 값입니다. 의 경우 `vscan-fileop-profile` 가 로 설정되어 있습니다 `write_only`, 및 IF
감염된 파일이 발견되면 해당 파일이 공유 폴더에 남아 있으며 파일을 열지 않기 때문에 파일을 열 수 있습니다
스캔을 트리거합니다. AV 스캔은 파일을 닫은 후에만 트리거됩니다.
* 를 클릭합니다 `scan-engine timeout` 값은 보다 작아야 합니다 `scanner-pool request-timeout`.
더 높은 값으로 설정된 경우 파일에 대한 액세스가 지연되어 결국 시간이 초과될 수 있습니다.
이를 방지하려면 를 구성하십시오 `scan-engine timeout` 5초 이내로 를 누르십시오 `scanner-pool
request-timeout` 값. 에 대한 지침은 스캔 엔진 공급업체의 설명서를 참조하십시오
를 변경합니다 `scan-engine timeout` 설정. 를 클릭합니다 `scanner-pool timeout` 에 의해 변경될 수 있습니다
고급 모드에서 및 에 적절한 값을 제공하여 다음 명령을 사용합니다 `request-timeout` 매개 변수:
`vserver vscan scanner-pool modify`
* 액세스 시 스캔 작업량에 맞게 사이징되고 온디맨드 스캔을 사용해야 하는 환경의 경우 기존 AV 인프라에 대한 추가 부하를 피하기 위해 사용량이 적은 시간에 주문형 스캔 작업을 예약하는 것이 좋습니다.

