---
permalink: antivirus/commands-manage-scanner-pools-reference.html 
sidebar: sidebar 
keywords: commands, manage, scanner pools 
summary: 스캐너 풀을 수정 및 삭제하고, 스캐너 풀의 권한이 있는 사용자와 Vscan 서버를 관리할 수 있습니다. 스캐너 풀에 대한 요약 및 세부 정보를 볼 수 있습니다. 
---
= 스캐너 풀을 관리하는 명령입니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
스캐너 풀을 수정 및 삭제하고, 스캐너 풀의 권한이 있는 사용자와 Vscan 서버를 관리할 수 있습니다. 스캐너 풀에 대한 요약 및 세부 정보를 볼 수 있습니다.

|===


| 원하는 작업 | 다음 명령을 입력합니다... 


 a| 
스캐너 풀을 수정합니다
 a| 
'vserver vscan scanner-pool modify(가상 Vscan 스캐너 풀 수정)



 a| 
스캐너 풀을 삭제합니다
 a| 
'vserver vscan scanner -pool delete'(Vscan scanner -pool 삭제



 a| 
스캐너 풀에 권한이 있는 사용자를 추가합니다
 a| 
'vserver vscan scanner-pool privileged-users add'



 a| 
스캐너 풀에서 권한이 있는 사용자를 삭제합니다
 a| 
'vserver vscan scanner-pool privileged-users remove'(Vscan scanner-



 a| 
Vscan 서버를 스캐너 풀에 추가합니다
 a| 
'vserver vscan scanner-pool servers add'



 a| 
스캐너 풀에서 Vscan 서버를 삭제합니다
 a| 
'vserver vscan scanner-pool servers remove(Vscan scanner-pool 서버



 a| 
스캐너 풀에 대한 요약 및 세부 정보를 봅니다
 a| 
'vserver vscan scanner-pool show'



 a| 
스캐너 풀에 대한 권한이 있는 사용자를 봅니다
 a| 
'vserver vscan scanner-pool privileged-users show'(Vscan scanner-pool



 a| 
모든 스캐너 풀에 대한 Vscan 서버를 봅니다
 a| 
'vserver vscan scanner-pool servers show'

|===
이러한 명령에 대한 자세한 내용은 man 페이지를 참조하십시오.
