---
permalink: antivirus/create-on-access-policy-task.html 
sidebar: sidebar 
keywords: create, on-access, policy 
summary: 액세스 시 정책은 액세스 시 검사의 범위를 정의합니다. 개별 SVM 또는 클러스터의 모든 SVM에 대해 액세스 시 정책을 생성할 수 있습니다. 클러스터에서 모든 SVM에 대해 액세스 시 정책을 생성한 경우 각 SVM에 대해 개별적으로 정책을 활성화해야 합니다. 
---
= 액세스 시 정책을 생성합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
액세스 시 정책은 액세스 시 검사의 범위를 정의합니다. 개별 SVM 또는 클러스터의 모든 SVM에 대해 액세스 시 정책을 생성할 수 있습니다. 클러스터에서 모든 SVM에 대해 액세스 시 정책을 생성한 경우 각 SVM에 대해 개별적으로 정책을 활성화해야 합니다.

.이 작업에 대해
* 스캔할 최대 파일 크기, 스캔에 포함할 파일 확장명 및 경로, 스캔에서 제외할 파일 확장명 및 경로를 지정할 수 있습니다.
* 바이러스 검사를 위해 Vscan 서버를 사용할 수 없는 경우 파일 액세스가 허용되도록 '스캔 필수' 옵션을 꺼짐으로 설정할 수 있습니다.
* 기본적으로 ONTAP는 "default_cifs"라는 액세스 시 정책을 생성하고 클러스터에 있는 모든 SVM에 대해 활성화합니다.
* 에 따라 스캔 제외 대상이 되는 모든 파일 `paths-to-exclude`, `file-ext-to-exclude`, 또는 `max-file-size` 매개 변수는 에도 스캔 대상으로 고려되지 않습니다 `scan-mandatory` 옵션이 켜짐으로 설정되어 있습니다. (이것을 확인하십시오 link:vscan-server-connection-concept.html["문제 해결"] 과 관련된 연결 문제에 대한 섹션입니다 `scan-mandatory` 옵션)
* 기본적으로 읽기-쓰기 볼륨만 스캔됩니다. 읽기 전용 볼륨을 스캔할 수 있도록 하거나 실행 권한으로 연 파일로 스캔을 제한하는 필터를 지정할 수 있습니다.
* 지속적으로 사용 가능한 매개 변수가 Yes로 설정된 SMB 공유에서는 바이러스 검사가 수행되지 않습니다.
* 를 참조하십시오 link:architecture-concept.html["안티바이러스 아키텍처"] Vscan 파일 - 작업 프로필 _ 에 대한 자세한 내용은 섹션을 참조하십시오.
* SVM당 최대 10개의 액세스 정책을 생성할 수 있습니다. 그러나 한 번에 하나의 온액세스 정책만 활성화할 수 있습니다.
+
** 액세스 시 정책에서 바이러스 검사에서 최대 100개의 경로 및 파일 확장명을 제외할 수 있습니다.


* 일부 파일 제외 권장 사항:
+
** CIFS 사용자에 대한 응답 속도가 느려지거나 스캔 요청 시간 초과가 발생할 수 있으므로 바이러스 검사에서 큰 파일(파일 크기를 지정할 수 있음)을 제외하는 것이 좋습니다. 제외의 기본 파일 크기는 2GB입니다.
** 과 같은 파일 확장명을 제외하는 것이 좋습니다 `.vhd` 및 `.tmp` 이러한 확장자가 있는 파일은 스캔에 적합하지 않을 수 있기 때문입니다.
** 격리 디렉터리나 가상 하드 드라이브 또는 데이터베이스만 저장되는 경로와 같은 파일 경로를 제외하는 것이 좋습니다.
** 한 번에 하나의 정책만 활성화할 수 있으므로 모든 제외가 동일한 정책에 지정되어 있는지 확인합니다. NetApp는 바이러스 백신 엔진에 지정된 것과 동일한 제외 세트를 사용할 것을 적극 권장합니다.


* 의 경우 액세스 시 정책이 필요합니다 xref:create-on-demand-task-task.html[온디맨드 검사]. 에 대한 액세스 시 스캔을 방지하려면 을 설정해야 합니다 `-scan-files-with-no-ext` 버튼을 눌러 false로 이동하고 `-file-ext-to-exclude` 모든 확장자를 제외하려면 * 를 선택합니다.


.단계
. 액세스 시 정책 생성:
+
'vserver vscan on-access-policy create -vserver_data_SVM|cluster_admin_SVM_-policy -name_policy_name_-protocol cifs-max-file-size_max_size_of_files_to_scan_ – filters [scan-ro-volume,] [scan-execute-access] -file-ext-to-include_ext_ext_ext_ext_exclude_ext_ext_exclude_ext_ext_ext_ext_exclude_exclude_ext_ext_exclude_file_exclude_file_file_scan_exclude_exclude_exclude_file_file_file_file_file_file_file_max-max_max-max-max-max-max_

+
** 개별 SVM에 정의된 정책에 따라 데이터 SVM을 지정하고, 클러스터의 모든 SVM에 정의된 정책에 따라 클러스터 관리 SVM을 지정합니다.
** '-file-ext-to-exclude' 설정은 '-file-ext-to-include' 설정보다 우선합니다.
** 설정 `-scan-files-with-no-ext` 를 true로 설정하면 확장자가 없는 파일을 스캔할 수 있습니다.
다음 명령을 실행하면 이라는 온액세스 정책이 생성됩니다 `Policy1` 를 누릅니다 `vs1` SVM:


+
[listing]
----
cluster1::> vserver vscan on-access-policy create -vserver vs1 -policy-name Policy1 -protocol CIFS -filters scan-ro-volume -max-file-size 3GB -file-ext-to-include “mp*”,"tx*" -file-ext-to-exclude "mp3","txt" -scan-files-with-no-ext false -paths-to-exclude "\vol\a b\","\vol\a,b\"
----
. 다음과 같이 on-access 정책이 생성되었는지 확인합니다. `vserver vscan on-access-policy show -instance _data_SVM|cluster_admin_SVM_ -policy-name _name_`
+
전체 옵션 목록은 명령에 대한 man 페이지를 참조하십시오.

+
다음 명령을 실행하면 Policy1 정책에 대한 세부 정보가 표시됩니다.

+
[listing]
----
cluster1::> vserver vscan on-access-policy show -instance vs1 -policy-name Policy1

                           Vserver: vs1
                            Policy: Policy1
                     Policy Status: off
               Policy Config Owner: vserver
              File-Access Protocol: CIFS
                           Filters: scan-ro-volume
                    Mandatory Scan: on
Max File Size Allowed for Scanning: 3GB
            File Paths Not to Scan: \vol\a b\, \vol\a,b\
       File Extensions Not to Scan: mp3, txt
           File Extensions to Scan: mp*, tx*
      Scan Files with No Extension: false
----

