---
permalink: antivirus/create-scanner-pool-single-cluster-task.html 
sidebar: sidebar 
keywords: create, scanner pool, single cluster 
summary: 스캐너 풀은 SVM에 연결할 수 있는 Vscan 서버 및 특별 권한 사용자를 정의합니다. 개별 SVM 또는 클러스터의 모든 SVM에 대해 스캐너 풀을 생성할 수 있습니다. 
---
= 단일 클러스터에 스캐너 풀을 생성합니다
:icons: font
:imagesdir: ../media/


[role="lead"]
스캐너 풀은 SVM에 연결할 수 있는 Vscan 서버 및 특별 권한 사용자를 정의합니다. 개별 SVM 또는 클러스터의 모든 SVM에 대해 스캐너 풀을 생성할 수 있습니다.

.무엇을 &#8217;필요로 할거야
* SVM과 Vscan 서버는 동일한 도메인 또는 신뢰할 수 있는 도메인에 있어야 합니다.
* 개별 SVM용으로 정의된 스캐너 풀의 경우 ONTAP 바이러스 백신 커넥터를 SVM 관리 LIF 또는 SVM 데이터 LIF로 구성해야 합니다.
* 클러스터의 모든 SVM에 대해 정의된 스캐너 풀의 경우 클러스터 관리 LIF에서 ONTAP 바이러스 백신 커넥터를 구성해야 합니다.


권한이 있는 사용자 목록에는 Vscan 서버가 SVM에 연결하는 데 사용하는 도메인 사용자 계정이 포함되어야 합니다.

.단계
. 스캐너 풀 생성:
+
'vserver vscan scanner -pool create -vserver data_SVM|cluster_admin_SVM-scanner -pool scanner_pool -hostname vscan_server_hostname -privileged-users privileged_users'

+
** 개별 SVM용으로 정의된 풀에 대해 데이터 SVM을 지정하고, 클러스터의 모든 SVM에 대해 정의된 풀에 대해 클러스터 관리 SVM을 지정합니다.
** 각 Vscan 서버 호스트 이름에 대한 IP 주소 또는 FQDN을 지정합니다.
** 권한이 있는 각 사용자의 도메인 및 사용자 이름을 지정합니다. 전체 옵션 목록은 명령에 대한 man 페이지를 참조하십시오.


+
다음 명령을 실행하면 VS1 VM에 SP라는 스캐너 풀이 생성됩니다.

+
[listing]
----
cluster1::> vserver vscan scanner-pool create -vserver vs1 -scanner-pool SP -hostnames 1.1.1.1,vmwin204-27.fsct.nb -privileged-users cifs\u1,cifs\u2
----
. 스캐너 풀이 생성되었는지 확인합니다. 'vserver vscan scanner -pool show -vserver data_SVM|cluster_admin_SVM-scanner -pool scanner_pool'
+
전체 옵션 목록은 명령에 대한 man 페이지를 참조하십시오.

+
다음 명령을 실행하면 'S' 스캐너 풀에 대한 세부 정보가 표시됩니다.

+
[listing]
----
cluster1::> vserver vscan scanner-pool show -vserver vs1 -scanner-pool SP

                                    Vserver: vs1
                               Scanner Pool: SP
                             Applied Policy: idle
                             Current Status: off
         Cluster on Which Policy Is Applied: -
                  Scanner Pool Config Owner: vserver
       List of IPs of Allowed Vscan Servers: 1.1.1.1, 10.72.204.27
List of Host Names of Allowed Vscan Servers: 1.1.1.1, vmwin204-27.fsct.nb
                   List of Privileged Users: cifs\u1, cifs\u2
----
+
SVM에서 모든 스캐너 풀을 보려면 'vserver vscan scanner -pool show' 명령을 사용할 수도 있습니다. 전체 명령 구문은 명령에 대한 man 페이지를 참조하십시오.


