---
permalink: antivirus/create-on-access-policy-task.html 
sidebar: sidebar 
keywords: create, on-access, policy 
summary: 액세스 시 정책은 액세스 시 검사의 범위를 정의합니다. 스캔할 파일의 최대 크기, 스캔에 포함할 파일의 확장명, 스캔에서 제외할 파일의 확장명 및 경로를 지정할 수 있습니다. 개별 SVM 또는 클러스터의 모든 SVM에 대해 액세스 시 정책을 생성할 수 있습니다. 
---
= 액세스 시 정책을 생성합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
액세스 시 정책은 액세스 시 검사의 범위를 정의합니다. 스캔할 파일의 최대 크기, 스캔에 포함할 파일의 확장명, 스캔에서 제외할 파일의 확장명 및 경로를 지정할 수 있습니다. 개별 SVM 또는 클러스터의 모든 SVM에 대해 액세스 시 정책을 생성할 수 있습니다.

.이 작업에 대해
기본적으로 ONTAP는 "default_cifs"라는 액세스 시 정책을 생성하고 클러스터의 모든 SVM에 대해 이 정책을 사용하도록 설정합니다.

바이러스 검사를 위해 Vscan 서버를 사용할 수 없는 경우 파일 액세스가 허용되도록 '스캔 필수' 옵션을 꺼짐으로 설정할 수 있습니다. '제외 경로', '제외 파일' 또는 'ax-file-size' 매개 변수를 기준으로 스캔 제외 대상이 되는 모든 파일은 '필수' 옵션이 On으로 설정되어 있어도 스캔 대상으로 간주되지 않습니다.

[NOTE]
====
'필수' 옵션과 관련된 잠재적인 문제는 를 참조하십시오 xref:vscan-server-connection-concept.adoc[스캔 필수 옵션과 관련된 잠재적인 연결 문제].

====
기본적으로 읽기-쓰기 볼륨만 스캔됩니다. 읽기 전용 볼륨을 스캔할 수 있도록 하거나 실행 권한으로 연 파일로 스캔을 제한하는 필터를 지정할 수 있습니다.

.단계
. 액세스 시 정책 생성:
+
'vserver vscan on-access-policy create -vserver_data_SVM|cluster_admin_SVM_-policy -name_policy_name_-protocol cifs-max-file-size_max_size_of_files_to_scan_ – filters [scan-ro-volume,] [scan-execute-access] -file-ext-to-include_ext_ext_ext_ext_exclude_ext_ext_exclude_ext_ext_ext_ext_exclude_exclude_ext_ext_exclude_file_exclude_file_file_scan_exclude_exclude_exclude_file_file_file_file_file_file_file_max-max_max-max-max-max-max_

+
** 개별 SVM에 정의된 정책에 따라 데이터 SVM을 지정하고, 클러스터의 모든 SVM에 정의된 정책에 따라 클러스터 관리 SVM을 지정합니다.
** '-file-ext-to-exclude' 설정은 '-file-ext-to-include' 설정보다 우선합니다.
** 확장자가 없는 파일을 스캔하려면 '-scan-files-with-no-ext'를 true로 설정합니다. 다음 명령을 실행하면 VS1 VM에 Policy1 이라는 온액세스 정책이 생성됩니다.


+
[listing]
----
cluster1::> vserver vscan on-access-policy create -vserver vs1 -policy-name Policy1 -protocol CIFS -filters scan-ro-volume -max-file-size 3GB -file-ext-to-include “mp*”,"tx*" -file-ext-to-exclude "mp3","txt" -scan-files-with-no-ext false -paths-to-exclude "\vol\a b\","\vol\a,b\"
----
. 액세스 시 정책이 생성되었는지 확인합니다. 'vserver vscan on-access-policy show -instance_data_SVM|cluster_admin_SVM_-policy-name policy_name'
+
전체 옵션 목록은 명령에 대한 man 페이지를 참조하십시오.

+
다음 명령을 실행하면 Policy1 정책에 대한 세부 정보가 표시됩니다.

+
[listing]
----
cluster1::> vserver vscan on-access-policy show -instance vs1 -policy-name Policy1

                           Vserver: vs1
                            Policy: Policy1
                     Policy Status: off
               Policy Config Owner: vserver
              File-Access Protocol: CIFS
                           Filters: scan-ro-volume
                    Mandatory Scan: on
Max File Size Allowed for Scanning: 3GB
            File Paths Not to Scan: \vol\a b\, \vol\a,b\
       File Extensions Not to Scan: mp3, txt
           File Extensions to Scan: mp*, tx*
      Scan Files with No Extension: false
----

