---
permalink: antivirus/create-on-demand-task-task.html 
sidebar: sidebar 
keywords: create, on-demand, task, vserver vscan 
summary: 온디맨드 작업은 온디맨드 스캔의 범위를 정의합니다. 스캔할 파일의 최대 크기, 스캔에 포함할 파일의 확장명 및 경로, 스캔에서 제외할 파일의 확장명 및 경로를 지정할 수 있습니다. 
---
= 주문형 작업을 만듭니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
주문형 작업은 주문형 바이러스 검사의 범위를 정의합니다. 스캔할 파일의 최대 크기, 스캔에 포함할 파일의 확장명 및 경로, 스캔에서 제외할 파일의 확장명 및 경로를 지정할 수 있습니다. 하위 디렉터리의 파일은 기본적으로 스캔됩니다.

.이 작업에 대해
* 각 SVM에 대해 최대 10개의 온디맨드 작업이 존재할 수 있지만, 하나의 SVM만 활성화할 수 있습니다.
* 필요 시 작업에서는 스캔과 관련된 통계와 관련된 정보가 포함된 보고서를 생성합니다. 이 보고서는 명령을 사용하거나 정의된 위치에서 작업에 의해 생성된 보고서 파일을 다운로드하여 액세스할 수 있습니다.


.시작하기 전에
* 이(가) 있어야 합니다 xref:create-on-access-policy-task.html[액세스 시 정책을 생성했습니다]. 정책은 기본 정책이거나 사용자가 만든 정책일 수 있습니다. On-access 정책이 없으면 검사를 활성화할 수 없습니다.


.단계
. 필요 시 작업 만들기:
+
`vserver vscan on-demand-task create -vserver _data_SVM_ -task-name _task_name_ -scan-paths _paths_of_files_to_scan_ -report-directory _report_directory_path_ -report-expiry-time _expiration_time_for_report_ -schedule cron_schedule -max-file-size _max_size_of_files_to_scan_ -paths-to-exclude _paths_ -file-ext-to-exclude _file_extensions_ -file-ext-to-include _file_extensions_ -scan-files-with-no-ext true|false -directory-recursion true|false`

+
** '-file-ext-to-exclude' 설정은 '-file-ext-to-include' 설정보다 우선합니다.
** 설정 `-scan-files-with-no-ext` 를 true로 설정하면 확장자가 없는 파일을 스캔할 수 있습니다.
+
ONTAP 명령 참조에서 https://docs.NetApp.com/us-en/ONTAP-cli/vserver-vscan-on-demand-task-create.html] 명령에 대해 자세히[`vserver vscan on-demand-task create` 알아보십시오.



+
다음 명령을 실행하면 이라는 On-Demand 작업이 생성됩니다 `Task1` VS1의 VM에서:

+
[listing]
----
cluster1::> vserver vscan on-demand-task create -vserver vs1 -task-name Task1 -scan-paths "/vol1/","/vol2/cifs/" -report-directory "/report" -schedule daily -max-file-size 5GB -paths-to-exclude "/vol1/cold-files/" -file-ext-to-include "vmdk?","mp*" -file-ext-to-exclude "mp3","mp4" -scan-files-with-no-ext false
[Job 126]: Vscan On-Demand job is queued. Use the "job show -id 126" command to view the status.
----
+

NOTE: job show 명령을 사용하여 작업의 상태를 볼 수 있습니다. 작업 일시정지 및 작업 재개 명령을 사용하여 작업을 일시정지 및 재시작하거나 작업 중지 명령을 사용하여 작업을 종료할 수 있습니다.

. 주문형 작업이 생성되었는지 확인합니다.
+
`vserver vscan on-demand-task show -instance data_SVM -task-name task_name`

+
전체 옵션 목록은 명령에 대한 man 페이지를 참조하십시오.

+
다음 명령을 실행하면 'Task1' 작업에 대한 세부 정보가 표시됩니다.

+
[listing]
----
cluster1::> vserver vscan on-demand-task show -instance vs1 -task-name Task1

                           Vserver: vs1
                         Task Name: Task1
                List of Scan Paths: /vol1/, /vol2/cifs/
             Report Directory Path: /report
                      Job Schedule: daily
Max File Size Allowed for Scanning: 5GB
            File Paths Not to Scan: /vol1/cold-files/
       File Extensions Not to Scan: mp3, mp4
           File Extensions to Scan: vmdk?, mp*
      Scan Files with No Extension: false
           Request Service Timeout: 5m
                    Cross Junction: true
               Directory Recursion: true
                     Scan Priority: low
                  Report Log Level: info
        Expiration Time for Report: -
----


.작업을 마친 후
작업을 실행하도록 예약하기 전에 SVM에서 스캔을 활성화해야 합니다.
