---
permalink: antivirus/install-ontap-antivirus-connector-task.html 
sidebar: sidebar 
keywords: install, ontap, task, antivirus connector 
summary: Vscan 서버에 ONTAP 안티바이러스 커넥터를 설치하여 ONTAP를 실행하는 시스템과 Vscan 서버 간의 통신을 제공합니다. 
---
= ONTAP 안티바이러스 커넥터를 설치합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vscan 서버에 ONTAP 안티바이러스 커넥터를 설치하여 ONTAP를 실행하는 시스템과 Vscan 서버 간의 통신을 활성화합니다. ONTAP 안티바이러스 커넥터가 설치되면 안티바이러스 소프트웨어는 하나 이상의 SVM(스토리지 가상 머신)과 통신할 수 있습니다.

.이 작업에 대해
* link:../antivirus/vscan-partner-solutions.html["Vscan 파트너 솔루션"]지원되는 프로토콜, 안티바이러스 공급업체 소프트웨어 버전, ONTAP 버전, 상호 운용성 요구 사항 및 Windows 서버에 대한 자세한 내용은 페이지를 참조하십시오.
* NET 4.5.1 이상이 설치되어 있어야 합니다.
* ONTAP 안티바이러스 커넥터는 가상 머신에서 실행할 수 있습니다. 그러나 최상의 성능을 위해 NetApp에서는 바이러스 백신 검사에 전용 물리적 시스템을 사용할 것을 권장합니다.
* ONTAP 안티바이러스 커넥터를 설치하고 실행하는 Windows 서버에서 SMB 2.0을 활성화해야 합니다.


.시작하기 전에
* 지원 사이트에서 ONTAP 안티바이러스 커넥터 설치 파일을 다운로드하여 하드 드라이브의 디렉터리에 저장합니다.
* ONTAP 안티바이러스 커넥터를 설치하기 위한 요구 사항을 충족하는지 확인합니다.
* Antivirus Connector를 설치할 수 있는 관리자 권한이 있는지 확인합니다.


.단계
. 적절한 설치 파일을 실행하여 Antivirus Connector 설치 마법사를 시작합니다.
. 다음 _ 을(를) 선택합니다. 대상 폴더 대화 상자가 열립니다.
. 목록에 있는 폴더에 Antivirus Connector를 설치하려면 _Next_를 선택하고 다른 폴더에 설치하려면 _Change_를 선택하십시오.
. ONTAP AV 커넥터 Windows 서비스 자격 증명 대화 상자가 열립니다.
. Windows 서비스 자격 증명을 입력하거나 * 추가 * 를 선택하여 사용자를 선택합니다. ONTAP 시스템의 경우 이 사용자는 유효한 도메인 사용자여야 하며 SVM의 스캐너 풀 구성에 있어야 합니다.
. 다음 * 을 선택합니다. 프로그램 설치 준비 완료 대화 상자가 열립니다.
. 설치를 시작하려면 * 설치 * 를 선택하고 설정을 변경하려면 * 뒤로 * 를 선택하십시오.
상태 상자가 열리고 설치 진행률을 차트로 표시한 다음 InstallShield 마법사 완료 대화 상자가 나타납니다.
. ONTAP 관리 또는 데이터 LIF 구성을 계속하려면 ONTAP LIF 구성 확인란을 선택합니다.
이 Vscan 서버를 사용하려면 먼저 하나 이상의 ONTAP 관리 또는 데이터 LIF를 구성해야 합니다.
. 설치 로그를 보려면 * Windows Installer 로그 표시 * 확인란을 선택합니다.
. 설치를 종료하고 InstallShield 마법사를 닫으려면 * 마침 * 을 선택하십시오.
ONTAP LIF 구성 * 아이콘이 바탕 화면에 저장되어 ONTAP LIF를 구성합니다.
. 바이러스 백신 커넥터에 SVM을 추가합니다.
데이터 LIF 목록을 검색하기 위해 폴링되는 ONTAP 관리 LIF를 추가하거나 데이터 LIF 또는 LIF를 직접 구성하여 SVM을 바이러스 백신 커넥터에 추가할 수 있습니다.
ONTAP 관리 LIF가 구성된 경우 폴링 정보와 ONTAP 관리자 계정 자격 증명도 제공해야 합니다.
+
** 에 대해 관리 LIF 또는 SVM의 IP 주소가 활성화되었는지 확인합니다 `management-https`. 데이터 LIF만 구성하는 경우에는 이러한 변경이 필요하지 않습니다.
** HTTP 응용 프로그램에 대한 사용자 계정을 만들고 REST API에 대한 액세스(읽기 전용) 권한이 있는 역할을 할당했는지 확인합니다 `/api/network/ip/interfaces`.
** ONTAP 명령 참조에서 https://docs .NetApp.com/us-en/ONTAP-cli/security-login-role-create.html 및 link:https://docs .NetApp.com/us-en/ONTAP-cli/security-login-create.html[`security login create` [ ] 명령에 대해[`security login role create` 자세히 알아보십시오.





NOTE: 관리 SVM에 대한 인증 터널 SVM을 추가하여 도메인 사용자를 계정으로 사용할 수도 있습니다. ONTAP 명령 참조에서 https://docs .NetApp.com/us-en/ONTAP-cli/security-login-domain-tunnel-create.html 명령 링크에 대해 자세히[`security login domain-tunnel create` 알아보십시오.

.단계
. 안티바이러스 커넥터 설치를 완료하면 바탕 화면에 저장된 * ONTAP LIF 구성 * 아이콘을 마우스 오른쪽 단추로 클릭한 다음 * 관리자 권한으로 실행 * 을 선택합니다.
. ONTAP LIF 구성 대화 상자에서 기본 구성 유형을 선택하고 다음 작업을 수행합니다.
+
[cols="35,65"]
|===


| 이 유형의 LIF를 생성하려면... | 다음 단계를 수행합니다. 


 a| 
데이터 LIF
 a| 
.. "역할"을 "데이터"로 설정
.. "데이터 프로토콜"을 "CIFS"로 설정합니다.
.. "방화벽 정책"을 "데이터"로 설정합니다.
.. "서비스 정책"을 "default-data-files"로 설정합니다.




 a| 
관리 LIF
 a| 
.. "역할 * 을 "데이터"로 설정
.. "데이터 프로토콜"을 "없음"으로 설정합니다.
.. "방화벽 정책"을 "관리"로 설정
.. "서비스 정책"을 "default-management"로 설정합니다.


|===
+
에 대해 자세히 link:../networking/create_a_lif.html["LIF 생성"]알아보세요.

+
LIF를 생성한 후 추가하려는 SVM의 데이터 또는 관리 LIF 또는 IP 주소를 입력합니다. 클러스터 관리 LIF를 입력할 수도 있습니다. 클러스터 관리 LIF를 지정하면 SMB를 제공하는 클러스터 내의 모든 SVM이 Vscan 서버를 사용할 수 있습니다.

+
[NOTE]
====
Vscan 서버에 Kerberos 인증이 필요한 경우 각 SVM 데이터 LIF는 고유한 DNS 이름을 가져야 하며, Windows Active Directory에 SPN(Server Principal Name)으로 등록해야 합니다. 각 데이터 LIF에 대해 고유한 DNS 이름을 사용할 수 없거나 SPN으로 등록된 경우 Vscan 서버는 NT LAN Manager 메커니즘을 사용하여 인증을 수행합니다. Vscan 서버가 연결된 후 DNS 이름 및 SPN을 추가하거나 수정하는 경우 변경 사항을 적용하려면 Vscan 서버에서 Antivirus Connector 서비스를 다시 시작해야 합니다.

====
. 관리 LIF를 구성하려면 폴링 기간을 초 단위로 입력합니다. 폴링 기간은 Antivirus Connector가 SVM 또는 클러스터의 LIF 구성의 변경 사항을 확인하는 빈도입니다. 기본 폴링 간격은 60초입니다.
. 관리 LIF를 구성하려면 ONTAP admin 계정 이름 및 암호를 입력합니다.
. Test * 를 클릭하여 연결을 확인하고 인증을 확인합니다. 관리 LIF 구성에 대해서만 인증이 검증됩니다.
. 업데이트 * 를 클릭하여 폴링하거나 연결할 LIF 목록에 LIF를 추가합니다.
. 저장 * 을 클릭하여 레지스트리에 대한 연결을 저장합니다.
. 연결 목록을 레지스트리 가져오기 또는 레지스트리 내보내기 파일로 내보내려면 * 내보내기 * 를 클릭합니다. 여러 Vscan 서버가 동일한 관리 또는 데이터 LIF 세트를 사용하는 경우 이 기능이 유용합니다.


를 참조하십시오 link:configure-ontap-antivirus-connector-task.html["ONTAP 안티바이러스 커넥터 페이지를 구성합니다"] 를 클릭합니다.
