---
permalink: antivirus/troubleshoot-common-virus-scanning-issues-reference.html 
sidebar: sidebar 
keywords: troubleshooting, troubleshoot, virus scanning, vscan, monitoring, connection, connectivity 
summary: 일반적인 바이러스 검사 문제, 가능한 원인 및 해결 방법이 나열된 표. 
---
= 바이러스 검사 문제를 해결합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
일반적인 바이러스 검사 문제의 경우 가능한 원인과 해결 방법이 있습니다. 바이러스 검사는 Vscan이라고도 합니다.

|===


| 문제 | 해결 방법 


 a| 
Vscan 서버는 에 연결할 수 없습니다
clustered ONTAP 스토리지 시스템을 활용할 수 있습니다.
 a| 
스캐너 풀 구성에서 Vscan 서버 IP 주소를 지정하는지 확인합니다. 스캐너 풀 목록에서 허용된 권한이 있는 사용자가 활성 상태인지 확인합니다. 스캐너 풀을 확인하려면 를 실행합니다 `vserver vscan scanner-pool show` 스토리지 시스템 명령 프롬프트에서 명령을 입력합니다. 그래도 Vscan 서버에 연결할 수 없는 경우 네트워크에 문제가 있을 수 있습니다.



 a| 
클라이언트에서 높은 지연 시간을 관찰합니다.
 a| 
스캐너 풀에 Vscan 서버를 더 추가해야 할 때가 되었을 것입니다.



 a| 
너무 많은 스캔이 트리거되었습니다.
 a| 
의 값을 수정합니다 `vscan-fileop-profile` 바이러스 검사를 위해 모니터링되는 파일 작업의 수를 제한하는 매개 변수입니다.



 a| 
일부 파일이 스캔되지 않습니다.
 a| 
온액세스 정책을 확인합니다. 이러한 파일의 경로가 경로 제외 목록에 추가되었거나 파일 크기가 제외에 대해 구성된 값을 초과할 수 있습니다. On-access 정책을 확인하려면 를 실행합니다 `vserver vscan on-access-policy show` 스토리지 시스템 명령 프롬프트에서 명령을 입력합니다.



 a| 
파일 액세스가 거부되었습니다.
 a| 
정책 구성에 _scan-mandatory_setting이 지정되어 있는지 확인한다. 이 설정은 연결된 Vscan 서버가 없는 경우 데이터 액세스를 거부합니다. 필요에 따라 설정을 수정합니다.

|===