---
permalink: revert/concept_revert_process_considerations.html 
sidebar: sidebar 
keywords: ontap, revert, considerations 
summary: ONTAP 리버전을 시작하기 전에 복원 문제와 제한 사항을 고려해야 합니다. 
---
= 되돌리기 고려 사항
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 리버전을 시작하기 전에 복원 문제와 제한 사항을 고려해야 합니다.

* 되돌리기 - 중단이 발생합니다.
+
재버전 중에는 클라이언트 액세스가 발생하지 않습니다. 운영 클러스터를 되돌려주는 경우 계획에 이 운영 중단을 포함해야 합니다.

* 되돌리기 작업은 클러스터의 모든 노드에 영향을 미칩니다.
+
이 재버전은 클러스터의 모든 노드에 영향을 미치지만, 다른 HA 쌍을 되돌리기 전에 각 HA 쌍에서 재버전을 수행 및 완료해야 합니다.

* 모든 노드에서 새 타겟 릴리즈가 실행되고 있으면 재버전이 완료됩니다.
+
클러스터가 혼합 버전 상태인 경우, 재조정 요구사항을 충족하는 데 필요한 경우를 제외하고 클러스터 작업 또는 구성을 변경하는 명령을 입력할 수 없으며 모니터링 작업이 허용됩니다.

+

IMPORTANT: 어떤 이유로든 재버전을 완료할 수 없는 경우 기술 지원 부서에 즉시 문의하십시오. 모든 노드가 아닌 일부 노드를 되돌린 경우 클러스터를 소스 릴리즈로 다시 업그레이드하려고 시도하지 마십시오.

* 노드를 되돌리면 Flash Cache 모듈에 캐시된 데이터가 지워집니다.
+
Flash Cache 모듈에는 캐싱된 데이터가 없으므로, 노드가 디스크에서 초기 읽기 요청을 처리할 수 있으므로 이 기간 동안 읽기 성능이 저하됩니다. 노드가 읽기 요청을 처리할 때 캐시를 다시 채웁니다.

* ONTAP 9.x에서 실행 중인 테이프에 백업된 LUN은 이전 릴리즈가 아닌 9.x 이상 릴리즈에만 복원할 수 있습니다.
* 현재 버전의 ONTAP가 IBACP(In-Band ACP) 기능을 지원하고 IBACP를 지원하지 않는 ONTAP 버전으로 복원하면 디스크 쉘프의 대체 경로가 비활성화됩니다.
* SVM(스토리지 가상 시스템)에서 LDAP를 사용하는 경우, 다시 버전하기 전에 LDAP 조회를 비활성화해야 합니다.
* MetroCluster를 준수하지만 MetroCluster가 검증되지 않은 스위치를 사용하는 MetroCluster IP 시스템에서는 ONTAP 9.6 이하를 사용하는 시스템에 대한 지원이 없으므로 ONTAP 9.7에서 9.6으로 재버전이 변경됩니다.

