---
permalink: revert/concept_reversion_requirements_for_snapmirror_and_snapvault_relationships.html 
sidebar: sidebar 
keywords: ontap, revert, reverting, reversion, requirements, snapmirror, snapvault, relationships 
summary: 시스템 노드 되돌리기 명령은 재조정 프로세스를 완료하기 위해 삭제하거나 재구성해야 하는 SnapMirror 및 SnapVault 관계를 알려 줍니다. 그러나 재버전을 시작하기 전에 이러한 요구 사항을 알고 있어야 합니다. 
---
= SnapMirror 및 SnapVault 관계에 대한 되돌리기 요구 사항
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
시스템 노드 되돌리기 명령은 재조정 프로세스를 완료하기 위해 삭제하거나 재구성해야 하는 SnapMirror 및 SnapVault 관계를 알려 줍니다. 그러나 재버전을 시작하기 전에 이러한 요구 사항을 알고 있어야 합니다.

* 모든 SnapVault 및 데이터 보호 미러링 관계를 중지했다가 해제해야 합니다.
+
다시 버전이 완료된 후 공통 스냅샷 복사본이 있으면 이러한 관계를 다시 동기화하고 다시 시작할 수 있습니다.

* SnapVault 관계에는 다음 SnapMirror 정책 유형이 포함되지 않아야 합니다.
+
** 비동기식 - 미러
+
이 정책 유형을 사용하는 모든 관계를 삭제해야 합니다.

** MirrorAndVault를 선택합니다
+
이러한 관계가 있으면 SnapMirror 정책을 미러 볼트로 변경해야 합니다.



* 모든 로드 공유 미러 관계 및 대상 볼륨을 삭제해야 합니다.
* FlexClone 대상 볼륨과의 SnapMirror 관계를 삭제해야 합니다.
* 각 SnapMirror 정책에 대해 네트워크 압축을 해제해야 합니다.
* ALL_SOURCE_SNSHOT 규칙을 모든 비동기식 미러 유형 SnapMirror 정책에서 제거해야 합니다.
+

NOTE: 단일 파일 스냅샷 복원(SFSR) 및 부분 파일 스냅샷 복원(PFSR) 작업은 루트 볼륨에서 더 이상 사용되지 않습니다.

* 현재 실행 중인 단일 파일 및 스냅샷 복원 작업을 완료해야 버전을 계속할 수 있습니다.
+
복원 작업이 완료될 때까지 기다리거나 작업을 중단할 수 있습니다.

* 완료되지 않은 단일 파일 및 스냅샷 복원 작업은 SnapMirror 복원 명령을 사용하여 제거해야 합니다.

