---
permalink: revert/task_reverting_systems_with_deduplicated_volumes.html 
sidebar: sidebar 
keywords: ontap, revert, reverting, reversion, systems, deduplication, deduplicated, volumes 
summary: ONTAP 9 버전에서 되돌리기 전에 볼륨에 복원 작업을 위한 충분한 여유 공간이 있는지 확인해야 합니다. 
---
= 되돌리기 전에 중복 제거된 볼륨의 사용 가능한 공간이 충분한지 확인하십시오
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9 버전에서 되돌리기 전에 볼륨에 복원 작업을 위한 충분한 여유 공간이 있는지 확인해야 합니다.

이 볼륨에는 제로 블록의 인라인 감지를 통해 얻은 절약 공간을 수용할 수 있는 충분한 공간이 있어야 합니다. 기술 자료 문서를 참조하십시오 link:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/How_to_see_space_savings_from_deduplication%2C_compression%2C_and_compaction_in_ONTAP_9["ONTAP 9에서 중복제거, 압축, 컴팩션을 통한 공간 절약 효과를 확인하는 방법"].

되돌리려는 볼륨에서 중복제거 및 데이터 압축을 모두 사용하도록 설정한 경우, 중복제거를 되돌리기 전에 데이터 압축을 되돌려야 합니다.

. volume Efficiency show 명령을 -fields 옵션과 함께 사용하면 볼륨에서 실행 중인 효율성 작업의 진행률을 볼 수 있습니다.
+
다음 명령을 실행하면 효율성 작업의 진행률이 표시됩니다. '볼륨 효율성 표시 - 필드 vserver, volume, progress

. ALL 옵션과 함께 볼륨 효율성 STOP 명령을 사용하여 활성 및 대기열에 있는 모든 중복 제거 작업을 중지하십시오.
+
다음 명령을 실행하면 볼륨 VolA에서 활성 및 대기 중인 모든 중복 제거 작업이 중지됩니다. 'volume Efficiency stop-vserver vs1-volume VolA-ALL'

. set-privilege advanced 명령을 사용하여 고급 권한 레벨로 로그인합니다.
. 볼륨의 효율성 메타데이터를 특정 버전의 ONTAP로 다운그레이드하려면 volume Efficiency revert-to 명령을 -version 옵션과 함께 사용하십시오.
+
다음 명령을 실행하면 볼륨 VolA의 효율성 메타데이터가 ONTAP 9.x로 되돌아갑니다. '볼륨 효율성 복원 - vserver vs1 - 볼륨 VolA - 버전 9.x'

+

NOTE: 볼륨 효율성 되돌리기-to 명령은 이 명령이 실행되는 노드에 있는 볼륨을 되돌립니다. 이 명령은 노드 간에 볼륨을 되돌리지 않습니다.

. 다운그레이드 진행률을 모니터링하려면 -op-status 옵션과 함께 volume Efficiency show 명령을 사용하십시오.
+
다음 명령을 실행하면 '볼륨 효율성 표시 - vserver vs1-op-status 다운그레이드'가 모니터링되고 다운그레이드 상태가 표시됩니다

. 복원이 성공하지 못할 경우 -instance 옵션과 함께 volume Efficiency show 명령을 사용하여 되돌리기에 실패한 이유를 확인하십시오.
+
다음 명령을 실행하면 모든 필드에 대한 자세한 정보가 표시됩니다. ' 볼륨 효율성 표시 - vserver vs1-volume vol1-instance'

. 되돌리기 작업이 완료된 후 'Set-Privilege admin'이라는 admin 권한 수준으로 돌아갑니다
+
link:../volumes/index.html["논리적 스토리지 관리"]


