---
permalink: revert/task_things_to_verify_before_revert.html 
sidebar: sidebar 
keywords: ontap, revert, reversion, reverting, downgrade, downgrading, preparation, pre-revert, checks, verification, cluster health, storage health, system time, jobs 
summary: ONTAP를 되돌리기 전에 클러스터 상태, 스토리지 상태 및 시스템 시간을 확인해야 합니다. 또한 클러스터에서 실행 중인 작업이 없는지 확인해야 합니다. 
---
= ONTAP 클러스터를 되돌리기 전에 수행할 시스템 확인
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 클러스터를 되돌리려면 먼저 클러스터 상태, 스토리지 상태 및 시스템 시간을 확인해야 합니다. 또한 클러스터에서 실행 중인 작업이 없는지 확인해야 합니다.



== 클러스터 상태를 확인합니다

ONTAP 클러스터를 되돌리려면 먼저 노드가 정상 상태이고 클러스터에 참여할 자격이 있는지, 클러스터가 쿼럼에 있는지 확인해야 합니다.

.단계
. 클러스터의 노드가 온라인 상태이며 클러스터에 참여할 자격이 있는지 확인합니다.
+
[source, cli]
----
cluster show
----
+
이 예에서는 모든 노드가 정상 상태이며 클러스터에 참여할 수 있습니다.

+
[listing]
----
cluster1::> cluster show
Node                  Health  Eligibility
--------------------- ------- ------------
node0                 true    true
node1                 true    true
----
+
노드가 정상 상태가 아니거나 적합하지 않은 경우 EMS 로그에서 오류를 확인하고 수정 조치를 취합니다.

. 권한 수준을 고급으로 설정합니다.
+
[source, cli]
----
set -privilege advanced
----
+
계속하려면 y를 입력하십시오.

. 각 RDB 프로세스에 대한 구성 세부 정보를 확인합니다.
+
** 관계형 데이터베이스 epoch 및 데이터베이스 epoch는 각 노드에 대해 일치해야 합니다.
** 링당 쿼럼 마스터는 모든 노드에 대해 동일해야 합니다.
+
각 링에는 다른 쿼럼 마스터가 있을 수 있습니다.

+
[cols="2*"]
|===
| 이 RDB 프로세스를 표시하려면... | 이 명령을 입력하십시오... 


 a| 
기능과
 a| 
[source, cli]
----
cluster ring show -unitname mgmt
----


 a| 
볼륨 위치 데이터베이스
 a| 
[source, cli]
----
cluster ring show -unitname vldb
----


 a| 
Virtual-Interface Manager를 참조하십시오
 a| 
[source, cli]
----
cluster ring show -unitname vifmgr
----


 a| 
SAN 관리 데몬
 a| 
[source, cli]
----
cluster ring show -unitname bcomd
----
|===
+
이 예에서는 볼륨 위치 데이터베이스 프로세스를 보여 줍니다.

+
[listing]
----
cluster1::*> cluster ring show -unitname vldb
Node      UnitName Epoch    DB Epoch DB Trnxs Master    Online
--------- -------- -------- -------- -------- --------- ---------
node0     vldb     154      154      14847    node0     master
node1     vldb     154      154      14847    node0     secondary
node2     vldb     154      154      14847    node0     secondary
node3     vldb     154      154      14847    node0     secondary
4 entries were displayed.
----


. 관리자 권한 레벨로 돌아갑니다.
+
[source, cli]
----
set -privilege admin
----
. SAN 환경에서 작동 중인 경우 각 노드가 SAN 쿼럼에 있는지 확인합니다.
+
[source, cli]
----
event log show  -severity informational -message-name scsiblade.*
----
+
각 노드에 대한 가장 최근의 scsib블레이드 이벤트 메시지는 SCSI 블레이드가 quorum에 있음을 나타내야 합니다.

+
[listing]
----
cluster1::*> event log show  -severity informational -message-name scsiblade.*
Time             Node       Severity       Event
---------------  ---------- -------------- ---------------------------
MM/DD/YYYY TIME  node0      INFORMATIONAL  scsiblade.in.quorum: The scsi-blade ...
MM/DD/YYYY TIME  node1      INFORMATIONAL  scsiblade.in.quorum: The scsi-blade ...
----


.관련 정보
link:../system-admin/index.html["시스템 관리"]



== 스토리지 상태를 확인합니다

ONTAP 클러스터를 되돌리려면 먼저 디스크, 애그리게이트 및 볼륨의 상태를 확인해야 합니다.

.단계
. 디스크 상태 확인:
+
[cols="2*"]
|===
| 확인하려면... | 수행할 작업... 


 a| 
손상된 디스크
 a| 
.. 손상된 디스크를 표시합니다.
+
[source, cli]
----
storage disk show -state broken
----
.. 손상된 디스크를 제거하거나 교체합니다.




 a| 
유지보수 또는 재구성이 진행 중인 디스크
 a| 
.. 유지 보수, 보류 또는 재구성 상태의 디스크를 표시합니다.
+
[source, cli]
----
storage disk show -state maintenance|pending|reconstructing
----
.. 유지보수 또는 재구성 작업이 완료될 때까지 기다린 후 계속 진행하십시오.


|===
. 스토리지 애그리게이트를 포함하여 물리적 스토리지와 논리적 스토리지의 상태를 표시하여 모든 애그리게이트가 온라인 상태인지 확인합니다
+
[source, cli]
----
storage aggregate show -state !online
----
+
이 명령은 _not_online 인 애그리게이트를 표시합니다. 주요 업그레이드 또는 리버전을 수행하기 전과 후의 모든 애그리게이트는 온라인 상태여야 합니다.

+
[listing]
----
cluster1::> storage aggregate show -state !online
There are no entries matching your query.
----
. _NOT_ONLINE 상태인 볼륨을 표시하여 모든 볼륨이 온라인 상태인지 확인합니다.
+
[source, cli]
----
volume show -state !online
----
+
주요 업그레이드 또는 재버전을 수행하기 전과 후에 모든 볼륨이 온라인 상태여야 합니다.

+
[listing]
----
cluster1::> volume show -state !online
There are no entries matching your query.
----
. 일치하지 않는 볼륨이 없는지 확인합니다.
+
[source, cli]
----
volume show -is-inconsistent true
----
+
기술 자료 문서를 참조하십시오 link:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/Volume_Showing_WAFL_Inconsistent["WAFL가 일치하지 않는 볼륨으로 표시됩니다"] 정합성이 보장되지 않는 볼륨을 처리하는 방법에 대해 설명합니다.



.관련 정보
link:../disks-aggregates/index.html["디스크 및 애그리게이트 관리"]



== 시스템 시간을 확인합니다

ONTAP 클러스터를 되돌리려면 먼저 NTP가 구성되어 있고 클러스터 전체에서 시간이 동기화되는지 확인해야 합니다.

.단계
. 클러스터가 NTP 서버와 연결되어 있는지 확인합니다.
+
[source, cli]
----
cluster time-service ntp server show
----
. 각 노드의 날짜와 시간이 동일한지 확인합니다.
+
[source, cli]
----
cluster date show
----
+
[listing]
----
cluster1::> cluster date show
Node      Date                Timezone
--------- ------------------- -------------------------
node0     4/6/2013 20:54:38   GMT
node1     4/6/2013 20:54:38   GMT
node2     4/6/2013 20:54:38   GMT
node3     4/6/2013 20:54:38   GMT
4 entries were displayed.
----




== 실행 중인 작업이 없는지 확인합니다

ONTAP 클러스터를 되돌리려면 먼저 클러스터 작업의 상태를 확인해야 합니다. 집계, 볼륨, NDMP(덤프 또는 복원) 또는 스냅샷 작업(예: 생성, 삭제, 이동, 수정, 복제 및 마운트 작업)이 실행 중이거나 대기 중인 경우 작업이 성공적으로 완료되도록 허용하거나 대기 중인 항목을 중지해야 합니다.

.단계
. 실행 중이거나 대기열에 있는 집계, 볼륨 또는 스냅샷 작업의 목록을 검토합니다.
+
[source, cli]
----
job show
----
+
이 예에서는 대기열에 있는 두 개의 작업이 있습니다.

+
[listing]
----
cluster1::> job show
                            Owning
Job ID Name                 Vserver    Node           State
------ -------------------- ---------- -------------- ----------
8629   Vol Reaper           cluster1   -              Queued
       Description: Vol Reaper Job
8630   Certificate Expiry Check
                            cluster1   -              Queued
       Description: Certificate Expiry Check
----
. 실행 중이거나 대기열에 있는 애그리게이트, 볼륨 또는 스냅샷 복사본 작업을 삭제합니다.
+
[source, cli]
----
job delete -id <job_id>
----
. 집계, 볼륨 또는 스냅샷 작업이 실행되고 있지 않은지 또는 큐에 대기하고 있지 않은지 확인합니다.
+
[source, cli]
----
job show
----
+
이 예에서는 실행 중인 작업과 대기열에 있는 작업이 모두 삭제되었습니다.

+
[listing]
----
cluster1::> job show
                            Owning
Job ID Name                 Vserver    Node           State
------ -------------------- ---------- -------------- ----------
9944   SnapMirrorDaemon_7_2147484678
                            cluster1   node1          Dormant
       Description: Snapmirror Daemon for 7_2147484678
18377  SnapMirror Service Job
                            cluster1   node0          Dormant
       Description: SnapMirror Service Job
2 entries were displayed
----

