---
permalink: revert/task_verify_health.html 
sidebar: sidebar 
keywords: ontap, revert, reverting, reversion, downgrade, downgrading, verifying, verify, cluster, health 
summary: 클러스터를 되돌리거나 다운그레이드한 후에는 노드가 정상 상태이고 클러스터에 참여할 수 있으며 클러스터가 쿼럼에 있는지 확인해야 합니다. 
---
= 다운그레이드 또는 되돌리기 후 클러스터 및 스토리지 상태를 확인합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
클러스터를 다운그레이드하거나 되돌린 후에는 노드가 정상 상태이고 클러스터에 참여할 수 있으며 클러스터가 쿼럼에 있는지 확인해야 합니다. 또한 디스크, 애그리게이트 및 볼륨의 상태도 확인해야 합니다.



== 클러스터 상태를 확인합니다

. 클러스터의 노드가 온라인 상태이고 클러스터 쇼에 참여할 자격이 있는지 확인합니다
+
[listing]
----
cluster1::> cluster show
Node                  Health  Eligibility
--------------------- ------- ------------
node0                 true    true
node1                 true    true
----
+
노드가 정상 상태가 아니거나 적합하지 않은 경우 EMS 로그에서 오류를 확인하고 수정 조치를 취합니다.

. 권한 수준을 advanced:+'et-Privilege advanced로 설정합니다
+
계속하려면 y를 입력하십시오.

. 각 RDB 프로세스에 대한 구성 세부 정보를 확인합니다.
+
** 관계형 데이터베이스 epoch 및 데이터베이스 epoch는 각 노드에 대해 일치해야 합니다.
** 링당 쿼럼 마스터는 모든 노드에 대해 동일해야 합니다.
+
각 링에는 다른 쿼럼 마스터가 있을 수 있습니다.

+
[cols="2*"]
|===
| 이 RDB 프로세스를 표시하려면... | 이 명령을 입력하십시오... 


 a| 
기능과
 a| 
클러스터 링 쇼-unitname 관리



 a| 
볼륨 위치 데이터베이스
 a| 
클러스터 링 쇼-언이트네임 VLDB



 a| 
Virtual-Interface Manager를 참조하십시오
 a| 
클러스터 링 쇼-unitname vifmgr



 a| 
SAN 관리 데몬
 a| 
'클러스터 링 쇼-언이트네임 bcomd'

|===
+
이 예에서는 볼륨 위치 데이터베이스 프로세스를 보여 줍니다.



+
[listing]
----
cluster1::*> cluster ring show -unitname vldb
Node      UnitName Epoch    DB Epoch DB Trnxs Master    Online
--------- -------- -------- -------- -------- --------- ---------
node0     vldb     154      154      14847    node0     master
node1     vldb     154      154      14847    node0     secondary
node2     vldb     154      154      14847    node0     secondary
node3     vldb     154      154      14847    node0     secondary
4 entries were displayed.
----
. admin 권한 수준으로 복귀:'et-Privilege admin'입니다
. SAN 환경에서 작동 중인 경우 각 노드가 SAN quorum에 있는지 확인합니다. '이벤트 로그 show-severity Informational-message-name scsibeBlade. *
+
각 노드에 대한 가장 최근의 scsib블레이드 이벤트 메시지는 SCSI 블레이드가 quorum에 있음을 나타내야 합니다.

+
[listing]
----
cluster1::*> event log show  -severity informational -message-name scsiblade.*
Time             Node       Severity       Event
---------------  ---------- -------------- ---------------------------
MM/DD/YYYY TIME  node0      INFORMATIONAL  scsiblade.in.quorum: The scsi-blade ...
MM/DD/YYYY TIME  node1      INFORMATIONAL  scsiblade.in.quorum: The scsi-blade ...
----


.관련 정보
link:../system-admin/index.html["시스템 관리"]



== 스토리지 상태를 확인합니다

클러스터를 되돌리거나 다운그레이드한 후에는 디스크, 애그리게이트 및 볼륨의 상태를 확인해야 합니다.

. 디스크 상태 확인:
+
[cols="2*"]
|===
| 확인하려면... | 수행할 작업... 


 a| 
손상된 디스크
 a| 
.. 깨진 디스크를 표시합니다:'스토리지 디스크 표시 상태 파단'
.. 손상된 디스크를 제거하거나 교체합니다.




 a| 
유지보수 또는 재구성이 진행 중인 디스크
 a| 
.. 유지 보수, 보류 중 또는 재구성 상태의 디스크를 표시합니다. 스토리지 디스크 표시 상태 유지 관리 | 보류 중 | 재구성 중
.. 유지보수 또는 재구성 작업이 완료될 때까지 기다린 후 계속 진행하십시오.


|===
. 스토리지 Aggregate의 'Storage aggregate show-state! online'을 비롯한 물리적 스토리지와 논리적 스토리지의 상태를 표시하여 모든 애그리게이트가 온라인 상태인지 확인합니다
+
이 명령은 _not_online 인 애그리게이트를 표시합니다. 주요 업그레이드 또는 리버전을 수행하기 전과 후의 모든 애그리게이트는 온라인 상태여야 합니다.

+
[listing]
----
cluster1::> storage aggregate show -state !online
There are no entries matching your query.
----
. "volume show-state! online"이라는 볼륨을 표시하여 모든 볼륨이 온라인 상태인지 확인합니다
+
주요 업그레이드 또는 재버전을 수행하기 전과 후에 모든 볼륨이 온라인 상태여야 합니다.

+
[listing]
----
cluster1::> volume show -state !online
There are no entries matching your query.
----
. '볼륨 표시 - 불일치 true'라는 일관성 없는 볼륨이 없는지 확인합니다
+
기술 자료 문서를 참조하십시오 link:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/Volume_Showing_WAFL_Inconsistent["WAFL가 일치하지 않는 볼륨으로 표시됩니다"] 정합성이 보장되지 않는 볼륨을 처리하는 방법에 대해 설명합니다.



.관련 정보
link:../disks-aggregates/index.html["디스크 및 애그리게이트 관리"]
