---
permalink: revert/task_reverting_an_ontap_cluster.html 
sidebar: sidebar 
keywords: ontap, revert, reverting, reversion, cluster 
summary: 클러스터를 오프라인으로 전환하여 이전 ONTAP 릴리즈로 되돌리려면 스토리지 페일오버 및 데이터 LIF를 비활성화하고, 리버전 전제 조건을 해결하며, 노드에서 클러스터 및 파일 시스템 구성을 되돌린 다음 클러스터의 각 추가 노드에 대해 이 프로세스를 반복해야 합니다. 
---
= ONTAP 클러스터를 되돌립니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 클러스터를 되돌리는 것은 중단이 발생합니다. 재버전을 수행할 때는 클러스터를 오프라인으로 전환해야 합니다. 기술 지원의 도움 없이 운영 클러스터를 되돌리면 안 됩니다.

새 클러스터를 되돌리거나 테스트 클러스터를 되돌리려면 스토리지 페일오버 및 데이터 LIF와 주소 변환 사전 조건을 사용하지 않도록 설정해야 합니다. 그런 다음 클러스터의 각 노드에서 클러스터 및 파일 시스템 구성을 되돌려야 합니다.

.시작하기 전에.
* 를 완료했어야 link:task_things_to_verify_before_revert.html["복원 전 검증"]합니다.
* 필수 항목을 완료해야 link:concept_pre_revert_checks.html["특정 ONTAP 버전을 미리 확인합니다"]합니다.




== 1단계: 재버전을 위해 클러스터를 준비합니다

클러스터 노드를 되돌리려면 먼저 타겟 ONTAP 이미지가 설치되었는지 확인하고 클러스터에서 모든 데이터 LIF를 비활성화해야 합니다.

.단계
. 권한 수준을 고급으로 설정합니다.
+
[source, cli]
----
set -privilege advanced
----
+
계속하라는 메시지가 나타나면 * y * 를 입력합니다.

. 대상 ONTAP 소프트웨어가 설치되었는지 확인합니다.
+
[source, cli]
----
system image show
----
+
다음 예에서는 버전 9.13.1 이 두 노드에 대체 이미지로 설치되어 있음을 보여 줍니다.

+
[listing]
----
cluster1::*> system image show
                 Is      Is                 Install
Node     Image   Default Current Version    Date
-------- ------- ------- ------- --------   -------------------
node0
         image1  true    true    9.14.1      MM/DD/YYYY TIME
         image2  false   false   9.13.1      MM/DD/YYYY TIME
node1
         image1  true    true    9.14.1      MM/DD/YYYY TIME
         image2  false   false   9.13.1      MM/DD/YYYY TIME
4 entries were displayed.
----
. 클러스터의 모든 데이터 LIF를 비활성화합니다.
+
[source, cli]
----
network interface modify {-role data} -status-admin down
----
. 클러스터 간 FlexCache 관계가 있는지 확인:
+
[source, cli]
----
flexcache origin show-caches -relationship-type inter-cluster
----
. 클러스터 간 변통이 있는 경우 캐시 클러스터에서 데이터 리프터를 해제합니다.
+
[source, cli]
----
network interface modify -vserver <vserver_name> -lif <lif_name> -status-admin down
----




== 2단계: 클러스터 노드 되돌리기

클러스터를 되돌리려면 HA 페어의 첫 번째 노드를 되돌린 다음 파트너 노드를 되돌려야 합니다. 그런 다음 모든 노드가 되돌려질 때까지 클러스터의 각 HA 쌍에 대해 이 프로세스를 반복합니다. MetroCluster 구성이 있는 경우 구성의 두 클러스터에 대해 이러한 단계를 반복해야 합니다.

[role="tabbed-block"]
====
.4개 이상의 노드
--
.단계
. 되돌리려는 노드에 로그인합니다.
+
노드를 되돌리려면 노드의 노드 관리 LIF를 통해 클러스터에 로그인해야 합니다.

. HA Pair의 노드에 대해 스토리지 페일오버 비활성화:
+
[source, cli]
----
storage failover modify -node <nodename> -enabled false
----
+
HA 쌍에 대해 스토리지 페일오버를 한 번만 해제하면 됩니다. 노드에 대해 스토리지 페일오버를 해제하면 노드의 파트너에서도 스토리지 페일오버가 해제됩니다.

. 노드의 대상 ONTAP 소프트웨어 이미지를 기본 이미지로 설정합니다.
+
[source, cli]
----
system image modify -node <nodename> -image <target_image> -isdefault true
----
. 타겟 ONTAP 소프트웨어 이미지가 되돌리는 노드의 기본 이미지로 설정되어 있는지 확인합니다.
+
[source, cli]
----
system image show
----
+
다음 예에서는 Node0에서 버전 9.13.1 이 기본 이미지로 설정되어 있음을 보여 줍니다.

+
[listing]
----
cluster1::*> system image show
                 Is      Is                 Install
Node     Image   Default Current Version    Date
-------- ------- ------- ------- --------   -------------------
node0
         image1  false   true    9.14.1      MM/DD/YYYY TIME
         image2  true    false   9.13.1      MM/DD/YYYY TIME
node1
         image1  true    true    9.14.1      MM/DD/YYYY TIME
         image2  false   false   9.13.1      MM/DD/YYYY TIME
4 entries were displayed.
----
. 노드 재버전이 준비되었는지 확인합니다.
+
[source, cli]
----
system node revert-to -node <nodename> -check-only true -version 9.x
----
+
 `check-only`매개 변수는 스냅샷 정책을 사용하지 않도록 설정하거나 이후 ONTAP의 최신 버전으로 업그레이드한 후 생성된 스냅샷 복사본을 삭제하는 등 되돌리기 전에 해결해야 할 사전 조건을 식별합니다.

. 노드의 클러스터 구성을 되돌립니다.
+
[source, cli]
----
system node revert-to -node <nodename> -version 9.x
----
+
 `-version`옵션은 되돌리는 ONTAP 릴리즈를 나타냅니다. 예를 들어 9.14.1에서 9.13.1로 되돌리는 경우 올바른 `-version` 옵션 값은 9.13.1입니다.

+
클러스터 구성을 되돌린 다음 클러스터 쉘에서 로그아웃됩니다.

. 로그인 프롬프트가 표시될 때까지 기다린 다음 시스템 쉘에 로그인할지 묻는 메시지가 표시되면 * No * 를 입력합니다.
+
로그인 프롬프트가 나타나는 데 최대 30분 이상 걸릴 수 있습니다.

. admin 을 사용하여 클러스터 쉘에 로그인합니다.
. 노드 쉘로 전환:
+
[source, cli]
----
run -node <nodename>
----
+
클러스터 쉘에 다시 로그온한 후 노드 쉘을 수락하는 데 몇 분 정도 걸릴 수 있습니다. 따라서 명령이 실패하면 몇 분 정도 기다린 후 다시 시도하십시오.

. 노드의 파일 시스템 구성을 되돌립니다.
+
[source, cli]
----
revert_to 9.x
----
+
이 명령은 노드의 파일 시스템 구성을 되돌릴 준비가 되었는지 확인한 다음 되돌립니다. 전제 조건이 식별되는 경우 조건을 해결한 다음 명령을 다시 실행해야 `revert_to` 합니다.

+

NOTE: 시스템 콘솔을 사용하여 복원 프로세스를 모니터링하면 노드 쉘에서 볼 수 있는 것보다 더 자세한 정보가 표시됩니다.

+
명령이 완료되면 자동 부팅 기능이 ONTAP로 재부팅됩니다.

+
AUTOBOOT이 FALSE인 경우 명령이 완료되면 Loader 프롬프트가 표시됩니다. 를 `yes` 입력하여 되돌린 다음 를 사용하여 `boot_ontap` 노드를 수동으로 재부팅합니다.

. 노드가 재부팅된 후 새 소프트웨어가 실행 중인지 확인합니다.
+
[source, cli]
----
system node image show
----
+
다음 예제에서 image1은 새 ONTAP 버전이며 Node0에서 현재 버전으로 설정됩니다.

+
[listing]
----
cluster1::*> system node image show
                 Is      Is                 Install
Node     Image   Default Current Version    Date
-------- ------- ------- ------- --------   -------------------
node0
         image1  true    true    X.X.X       MM/DD/YYYY TIME
         image2  false   false   Y.Y.Y      MM/DD/YYYY TIME
node1
         image1  true    false   X.X.X      MM/DD/YYYY TIME
         image2  false   true    Y.Y.Y      MM/DD/YYYY TIME
4 entries were displayed.
----
. 노드의 복원 상태가 완료되었는지 확인합니다.
+
[source, cli]
----
system node upgrade-revert show -node <nodename>
----
+
상태는 "완료", "필요 없음" 또는 "반환된 테이블 항목이 없습니다."로 표시되어야 합니다.

. HA 쌍의 다른 노드에서 이러한 단계를 반복한 다음, 각 추가 HA 쌍에 대해 이 단계를 반복합니다.
+
MetroCluster 구성이 있는 경우 구성의 두 클러스터에서 이 단계를 반복해야 합니다

. 모든 노드를 되돌린 후 클러스터에 대해 고가용성을 다시 설정합니다.
+
[source, cli]
----
cluster ha modify -configured true
----


--
.2노드 클러스터
--
. 되돌리려는 노드에 로그인합니다.
+
노드를 되돌리려면 노드의 노드 관리 LIF를 통해 클러스터에 로그인해야 합니다.

. 클러스터 고가용성(HA) 비활성화:
+
[source, cli]
----
cluster ha modify -configured false
----
. 스토리지 페일오버 해제:
+
[source, cli]
----
storage failover modify -node <nodename> -enabled false
----
+
HA 쌍에 대해 스토리지 페일오버를 한 번만 해제하면 됩니다. 노드에 대해 스토리지 페일오버를 해제하면 노드의 파트너에서도 스토리지 페일오버가 해제됩니다.

. 노드의 대상 ONTAP 소프트웨어 이미지를 기본 이미지로 설정합니다.
+
[source, cli]
----
system image modify -node <nodename> -image <target_image> -isdefault true
----
. 타겟 ONTAP 소프트웨어 이미지가 되돌리는 노드의 기본 이미지로 설정되어 있는지 확인합니다.
+
[source, cli]
----
system image show
----
+
다음 예제에서는 버전 9.1이 Node0의 기본 이미지로 설정된 것을 보여 줍니다.

+
[listing]
----
cluster1::*> system image show
                 Is      Is                 Install
Node     Image   Default Current Version    Date
-------- ------- ------- ------- --------   -------------------
node0
         image1  false   true    9.2        MM/DD/YYYY TIME
         image2  true    false   9.1        MM/DD/YYYY TIME
node1
         image1  true    true    9.2        MM/DD/YYYY TIME
         image2  false   false   9.1        MM/DD/YYYY TIME
4 entries were displayed.
----
. 노드에 현재 epsilon이 있는지 확인합니다.
+
[source, cli]
----
cluster show -node <nodename>
----
+
다음 예는 노드가 epsilon를 보유하고 있음을 보여줍니다.

+
[listing]
----
cluster1::*> cluster show -node node1

          Node: node1
          UUID: 026efc12-ac1a-11e0-80ed-0f7eba8fc313
       Epsilon: true
   Eligibility: true
        Health: true
----
+
.. 노드에 epsilon이 있는 경우 노드에 epsilon을 FALSE로 표시하여 epsilon을 노드의 파트너로 전송할 수 있도록 합니다.
+
[source, cli]
----
cluster modify -node <nodename> -epsilon false
----
.. 파트너 노드에서 epsilon true를 표시하여 epsilon을 노드의 파트너로 전송합니다.
+
[source, cli]
----
cluster modify -node <node_partner_name> -epsilon true
----


. 노드 재버전이 준비되었는지 확인합니다.
+
[source, cli]
----
system node revert-to -node <nodename> -check-only true -version 9.x
----
+
 `check-only`매개 변수는 스냅샷 정책을 사용하지 않도록 설정하거나 이후 ONTAP의 최신 버전으로 업그레이드한 후 생성된 스냅샷 복사본을 삭제하는 등 되돌리기 전에 해결해야 할 모든 조건을 식별합니다.

. 노드의 클러스터 구성을 되돌립니다.
+
[source, cli]
----
system node revert-to -node <nodename> -version 9.x
----
+
 `-version`옵션은 되돌리는 ONTAP 릴리즈를 나타냅니다. 예를 들어 9.14.1에서 9.13.1로 되돌리는 경우 올바른 `-version` 옵션 값은 9.13.1입니다.

+
클러스터 구성을 되돌린 다음 클러스터 쉘에서 로그아웃됩니다.

. 로그인 프롬프트가 표시될 때까지 기다린 다음 시스템 쉘에 로그인할지 묻는 메시지가 나타나면 를 `No` 입력합니다.
+
로그인 프롬프트가 나타나는 데 최대 30분 이상 걸릴 수 있습니다.

. admin 을 사용하여 클러스터 쉘에 로그인합니다.
. 노드 쉘로 전환:
+
[source, cli]
----
run -node <nodename>
----
+
클러스터 쉘에 다시 로그온한 후 노드 쉘을 수락하는 데 몇 분 정도 걸릴 수 있습니다. 따라서 명령이 실패하면 몇 분 정도 기다린 후 다시 시도하십시오.

. 노드의 파일 시스템 구성을 되돌립니다.
+
[source, cli]
----
revert_to 9.x
----
+
이 명령은 노드의 파일 시스템 구성을 되돌릴 준비가 되었는지 확인한 다음 되돌립니다. 전제 조건이 식별되는 경우 조건을 해결한 다음 명령을 다시 실행해야 `revert_to` 합니다.

+

NOTE: 시스템 콘솔을 사용하여 복원 프로세스를 모니터링하면 노드 쉘에서 볼 수 있는 것보다 더 자세한 정보가 표시됩니다.

+
명령이 완료되면 자동 부팅 기능이 ONTAP로 재부팅됩니다.

+
autoboot가 false 이면 명령이 로더 프롬프트를 표시합니다. 되돌리려면 yes를 입력하고 노드를 수동으로 재부팅하려면 boot_ONTAP을 사용합니다.

. 노드가 재부팅된 후 새 소프트웨어가 실행 중인지 확인합니다.
+
[source, cli]
----
system node image show
----
+
다음 예제에서 image1은 새 ONTAP 버전이며 Node0에서 현재 버전으로 설정됩니다.

+
[listing]
----
cluster1::*> system node image show
                 Is      Is                 Install
Node     Image   Default Current Version    Date
-------- ------- ------- ------- --------   -------------------
node0
         image1  true    true    X.X.X       MM/DD/YYYY TIME
         image2  false   false   Y.Y.Y      MM/DD/YYYY TIME
node1
         image1  true    false   X.X.X      MM/DD/YYYY TIME
         image2  false   true    Y.Y.Y      MM/DD/YYYY TIME
4 entries were displayed.
----
. 노드에 대한 되돌리기 상태가 완료되었는지 확인합니다.
+
[source, cli]
----
system node upgrade-revert show -node <nodename>
----
+
상태는 "완료", "필요 없음" 또는 "반환된 테이블 항목이 없습니다."로 표시되어야 합니다.

. HA 쌍의 다른 노드에서 이 단계를 반복합니다.
. 두 노드를 모두 되돌린 후 클러스터에 대해 고가용성을 다시 설정합니다.
+
[source, cli]
----
cluster ha modify -configured true
----
. 두 노드에서 스토리지 페일오버 재활성화:
+
[source, cli]
----
storage failover modify -node <nodename> -enabled true
----


--
====