---
permalink: smb-admin/add-home-directory-share-task.html 
sidebar: sidebar 
keywords: smb, home, directory, feature, add, property, share, properties, property, add a home directory share 
summary: SMB 홈 디렉토리 기능을 사용하려면 공유 속성에 포함된 홈 디렉토리 속성에 공유를 하나 이상 추가해야 합니다. 
---
= 홈 디렉토리 공유를 추가합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SMB 홈 디렉토리 기능을 사용하려면 공유 속성에 포함된 홈 디렉토리 속성에 공유를 하나 이상 추가해야 합니다.

.이 작업에 대해
'vserver cifs share create' 명령을 사용하여 공유를 생성할 때 홈 디렉토리 공유를 생성하거나 'vserver cifs share modify' 명령을 사용하여 언제든지 기존 공유를 홈 디렉토리 공유로 변경할 수 있습니다.

홈 디렉토리 공유를 생성하려면 공유를 생성하거나 수정할 때 '-share-properties' 옵션에 homeddirectory 값을 포함해야 합니다. 사용자가 홈 디렉토리에 연결할 때 동적으로 확장되는 변수를 사용하여 공유 이름을 지정하고 경로를 공유할 수 있습니다. 경로에서 사용할 수 있는 변수는 각각 Windows 사용자 이름, 도메인 및 매핑된 UNIX 사용자 이름에 해당하는 "%w", "%d" 및 "%u"입니다.

.단계
. 홈 디렉토리 공유 추가: + 'vserver cifs share create -vserver_vserver_name_-share-name_share_name_-path_path_-share-properties homed디렉토리 [,...]'
+
'-vserver''vserver'는 검색 경로를 추가할 SVM(CIFS 지원 스토리지 가상 머신)을 지정합니다.

+
'-share-name_share-name_'은 홈 디렉토리 공유 이름을 지정합니다.

+
공유 이름에 리터럴 문자열 '%w', '%u' 또는 '%d' 중 하나가 포함된 경우 필수 변수 중 하나가 포함된 것 외에도 ONTAP가 리터럴 문자열을 변수(예: "%%w")로 취급하지 않도록 리터럴 문자열 앞에 %(percent) 문자를 입력해야 합니다.

+
** 공유 이름에는 '%w' 또는 '%u' 변수가 포함되어야 합니다.
** 공유 이름에는 "%d" 변수(예: "%d"/"%w") 또는 공유 이름의 정적 부분(예: home1_""%w")이 추가로 포함될 수 있습니다.
** 관리자가 공유를 사용하여 다른 사용자의 홈 디렉토리에 연결하거나 사용자가 다른 사용자의 홈 디렉토리에 연결할 수 있도록 허용하는 경우 동적 공유 이름 패턴 앞에는 물결표(~)가 와야 합니다.
+
vserver cifs home-directory modify는 '-is-home-dirs-access-for-admin-enabled' 옵션을 true로 설정하거나 고급 옵션 '-is-home-dirs-access-for-public-enabled'를 true로 설정하여 이 액세스를 활성화하는 데 사용됩니다.



+
path는 홈 디렉토리의 상대 경로를 지정합니다.



'-share-properties homed디렉토리[,...]'는 해당 공유의 공유 속성을 지정합니다. homedir 값을 지정해야 합니다. 쉼표로 구분된 목록을 사용하여 추가 공유 속성을 지정할 수 있습니다.

. 'vserver cifs share show' 명령을 사용하여 홈 디렉토리 공유를 성공적으로 추가했는지 확인하십시오.


.예
다음 명령을 실행하면 "%w"라는 홈 디렉토리 공유가 생성됩니다. oplocks, browable, changenotify 공유 속성은 homedir 공유 속성을 설정하는 것 외에도 설정됩니다.

[NOTE]
====
이 예에서는 SVM의 모든 공유에 대한 출력을 표시하지 않습니다. 출력이 잘립니다.

====
[listing]
----
cluster1::> vserver cifs share create -vserver vs1 -share-name %w -path %w -share-properties oplocks,browsable,changenotify,homedirectory

vs1::> vserver cifs share show -vserver vs1
Vserver    Share    Path         Properties     Comment  ACL
---------- -------- ------------ -------------- -------- -----------
vs1        %w       %w           oplocks        -        Everyone / Full Control
                                 browsable
                                 changenotify
                                 homedirectory
----
.관련 정보
xref:add-home-directory-search-path-task.adoc[홈 디렉토리 검색 경로 추가]

xref:requirements-automatic-node-referrals-concept.adoc[자동 노드 조회를 사용하기 위한 요구 사항 및 지침]

xref:manage-accessibility-users-home-directories-task.adoc[사용자의 홈 디렉터리에 대한 액세스 가능성 관리]
