---
permalink: smb-admin/add-home-directory-search-path-task.html 
sidebar: sidebar 
keywords: ontap, smb, directories, directory, add, path, add a home directory search path 
summary: ONTAP SMB 홈 디렉토리를 사용하려면 하나 이상의 홈 디렉토리 검색 경로를 추가해야 합니다. 
---
= 홈 디렉토리 검색 경로를 추가합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP SMB 홈 디렉토리를 사용하려면 하나 이상의 홈 디렉토리 검색 경로를 추가해야 합니다.

.이 작업에 대해
'vserver cifs home-directory search-path add' 명령을 사용하여 홈 디렉토리 검색 경로를 추가할 수 있습니다.

'vserver cifs home-directory search-path add' 명령은 명령 실행 중에 '-path' 옵션에 지정된 경로를 확인합니다. 지정한 경로가 없으면 명령을 실행하면 계속할 것인지 여부를 묻는 메시지가 생성됩니다. 당신은 'y'나 'n'을 선택합니다. 계속하려면 y를 선택하면 ONTAP가 검색 경로를 생성합니다. 그러나 홈 디렉토리 구성에서 검색 경로를 사용하려면 먼저 디렉토리 구조를 만들어야 합니다. 계속하지 않도록 선택하면 명령이 실패하고 검색 경로가 생성되지 않습니다. 그런 다음 경로 디렉토리 구조를 생성하고 'vserver cifs home-directory search-path add' 명령을 다시 실행할 수 있습니다.

.단계
. 홈 디렉토리 검색 경로 'vserver cifs home-directory search-path add-vserver vserver-path path path' 추가
. 'vserver cifs home-directory search-path show' 명령을 사용하여 검색 경로를 성공적으로 추가했는지 확인합니다.


.예
다음 예에서는 SVM VS1 홈 디렉토리 구성에 경로 '/home1'을 추가합니다.

[listing]
----
cluster::> vserver cifs home-directory search-path add -vserver vs1 -path /home1

vs1::> vserver cifs home-directory search-path show
Vserver     Position Path
----------- -------- -----------------
vs1         1        /home1
----
다음 예에서는 SVM VS1 홈 디렉토리 구성에 경로 '/home2'를 추가하려고 합니다. 경로가 존재하지 않습니다. 계속하지 않도록 선택할 수 있습니다.

[listing]
----
cluster::> vserver cifs home-directory search-path add -vserver vs1 -path /home2
Warning: The specified path "/home2" does not exist in the namespace
         belonging to Vserver "vs1".
Do you want to continue? {y|n}: n
----
.관련 정보
xref:add-home-directory-share-task.adoc[홈 디렉토리 공유를 추가하는 중입니다]
