---
permalink: smb-admin/add-privileges-local-domain-users-groups-task.html 
sidebar: sidebar 
keywords: manage, right, user, local, domain, add, privilege, override, default, object, enhance, customize, user, group, add privileges to local or domain users or groups 
summary: 권한을 추가하여 로컬 또는 도메인 사용자 또는 그룹의 사용자 권한을 관리할 수 있습니다. 추가된 권한은 이러한 개체에 할당된 기본 권한을 재정의합니다. 사용자 또는 그룹에 있는 권한을 사용자 지정할 수 있으므로 보안이 강화됩니다. 
---
= 로컬 또는 도메인 사용자 또는 그룹에 권한을 추가합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
권한을 추가하여 로컬 또는 도메인 사용자 또는 그룹의 사용자 권한을 관리할 수 있습니다. 추가된 권한은 이러한 개체에 할당된 기본 권한을 재정의합니다. 사용자 또는 그룹에 있는 권한을 사용자 지정할 수 있으므로 보안이 강화됩니다.

.시작하기 전에
권한을 추가할 로컬 또는 도메인 사용자 또는 그룹이 이미 있어야 합니다.

.이 작업에 대해
객체에 권한을 추가하면 해당 사용자 또는 그룹에 대한 기본 권한이 재정의됩니다. 권한을 추가해도 이전에 추가한 권한은 제거되지 않습니다.

로컬 또는 도메인 사용자 또는 그룹에 권한을 추가할 때는 다음 사항을 염두에 두어야 합니다.

* 하나 이상의 권한을 추가할 수 있습니다.
* 도메인 사용자 또는 그룹에 권한을 추가할 때 ONTAP는 도메인 컨트롤러에 문의하여 도메인 사용자 또는 그룹의 유효성을 검사할 수 있습니다.
+
ONTAP가 도메인 컨트롤러에 연결할 수 없는 경우 명령이 실패할 수 있습니다.



.단계
. 로컬 또는 도메인 사용자 또는 그룹에 하나 이상의 권한을 추가합니다. '+vserver cifs users-and-groups privilege add-privilege-vserver_name_-user-or-group-name name name-Privileges_Privilege_[,...]+'
. 원하는 권한이 객체에 적용되었는지 확인합니다. 'vserver cifs users-and-groups privilege show-vserver_name_-user-or-group-name_name_'


.예
다음 예에서는 스토리지 가상 머신(SVM, 이전 명칭 Vserver)의 사용자 " cifs_server\sue ""에 "'seTcbPrivilege'" 및 "'setTakeOwnershipPrivilege"" 권한을 추가합니다1.

[listing]
----
cluster1::> vserver cifs users-and-groups privilege add-privilege -vserver vs1 -user-or-group-name CIFS_SERVER\sue -privileges SeTcbPrivilege,SeTakeOwnershipPrivilege

cluster1::> vserver cifs users-and-groups privilege show -vserver vs1
Vserver   User or Group Name    Privileges
--------- --------------------- ---------------
vs1       CIFS_SERVER\sue       SeTcbPrivilege
                                SeTakeOwnershipPrivilege
----