---
permalink: smb-admin/choosing-hash-store-location-concept.html 
sidebar: sidebar 
keywords: configuring, configure, branchcache, store, hash, size, guideline, cids-enabled, svm, guidelines for choosing the hash store location 
summary: BranchCache를 구성할 때는 해시를 저장할 위치와 해시 저장소의 크기를 선택합니다. 해시 저장소 위치 및 크기를 선택할 때 지침을 이해하면 CIFS 지원 SVM에서 BranchCache 구성을 계획하는 데 도움이 됩니다. 
---
= 해시 저장 위치 선택 지침
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
BranchCache를 구성할 때는 해시를 저장할 위치와 해시 저장소의 크기를 선택합니다. 해시 저장소 위치 및 크기를 선택할 때 지침을 이해하면 CIFS 지원 SVM에서 BranchCache 구성을 계획하는 데 도움이 됩니다.

* atime 업데이트가 허용되는 볼륨에서 해시 저장소를 찾아야 합니다.
+
해시 파일의 액세스 시간은 자주 액세스하는 파일을 해시 저장소에 유지하는 데 사용됩니다. atime 업데이트가 비활성화된 경우 생성 시간이 이 용도로 사용됩니다. 자주 사용하는 파일을 추적하기 위해 atime을 사용하는 것이 좋습니다.

* SnapMirror 대상 및 SnapLock 볼륨과 같은 읽기 전용 파일 시스템에서는 해시를 저장할 수 없습니다.
* 해시 저장소의 최대 크기에 도달하면 새 해시를 위한 공간을 확보하기 위해 이전 해시가 플러시됩니다.
+
해시 저장소의 최대 크기를 늘려 캐시에서 플러시되는 해시의 양을 줄일 수 있습니다.

* 해시를 저장하는 볼륨을 사용할 수 없거나 꽉 찼거나 BranchCache 서비스에서 해시 정보를 검색할 수 없는 클러스터 내 통신에 문제가 있는 경우 BranchCache 서비스를 사용할 수 없습니다.
+
볼륨이 오프라인 상태이거나 스토리지 관리자가 해시 저장소에 대한 새 위치를 지정했기 때문에 볼륨을 사용할 수 없습니다.

+
이 경우 파일 액세스에 문제가 발생하지 않습니다. 해시 저장소에 대한 액세스가 방해를 받으면 ONTAP는 클라이언트에 Microsoft 정의 오류를 반환하여 클라이언트가 일반 SMB 읽기 요청을 사용하여 파일을 요청하게 합니다.



xref:configure-branchcache-task.adoc[CIFS 서버에서 BranchCache 구성]

xref:manage-monitor-branchcache-config-concept.adoc[BranchCache 구성 관리 및 모니터링]
