---
permalink: smb-admin/command-options-limit-client-resource-concept.html 
sidebar: sidebar 
keywords: option, vserver, cifs, modify, command, enable, control, resource, consumption, windows, client, bound, notify, request, command options to limit excessive windows client resource consumption 
summary: 'vserver cifs options modify 명령에 대한 옵션을 사용하면 Windows 클라이언트의 리소스 사용을 제어할 수 있습니다. 이 기능은 클라이언트가 리소스 사용의 정상적인 범위를 벗어난 경우(예: 열려 있는 파일의 수가 비정상적으로 많거나 세션이 열려 있거나 변경 알림 요청이 있는 경우) 유용합니다.' 
---
= 과도한 Windows 클라이언트 리소스 사용을 제한하는 명령 옵션입니다
:icons: font
:imagesdir: ../media/


[role="lead"]
'vserver cifs options modify' 명령 옵션을 사용하면 Windows 클라이언트의 리소스 사용을 제어할 수 있습니다. 이 기능은 클라이언트가 리소스 사용의 정상적인 범위를 벗어난 경우(예: 열려 있는 파일의 수가 비정상적으로 많거나 세션이 열려 있거나 변경 알림 요청이 있는 경우) 유용합니다.

Windows 클라이언트 리소스 사용을 제어하기 위해 'vserver cifs options modify' 명령에 대한 다음 옵션이 추가되었습니다. 이 옵션 중 최대값이 초과되면 요청이 거부되고 EMS 메시지가 전송됩니다. 이 옵션에 대해 구성된 제한값의 80%에 도달하면 EMS 경고 메시지도 전송됩니다.

* '-max-오픈-파일-트리 단위'
+
CIFS 트리당 동일한 파일에 대한 최대 열기 수입니다

* '-max-same-user-sessions-per-connection'
+
동일한 사용자가 접속당 연 최대 세션 수입니다

* '-max-same-tree-connect-per-session'
+
세션당 동일한 공유에 대한 최대 트리 연결 수입니다

* `-max-s워치-세트당-트리'
+
트리당 설정된 최대 시계 수(_CHANGE ALBERS_라고도 함)입니다



기본 제한 및 현재 구성을 표시하려면 man 페이지를 참조하십시오.

ONTAP 9.4부터 SMB 버전 2 이상을 실행하는 서버는 클라이언트가 SMB 연결을 통해 서버로 전송할 수 있는 미해결 요청(_smb 크레딧_) 수를 제한할 수 있습니다. SMB 크레딧의 관리는 클라이언트가 시작하고 서버에 의해 제어됩니다.

SMB 연결에서 허용할 수 있는 최대 요청 수는 '-max-credits' 옵션으로 제어됩니다. 이 옵션의 기본값은 128입니다.
