---
permalink: smb-admin/configure-apply-audit-policies-ntfs-files-folders-task.html 
sidebar: sidebar 
keywords: perform, apply, policies, policy, ntfs, file, folder, ontap, cli, security, descriptor, sacl, descriptor, create, storage, virtual, machine, svm, configure and apply audit policies to ntfs files and folders using the cli 
summary: 'ONTAP CLI를 사용할 때 NTFS 파일 및 폴더에 감사 정책을 적용하려면 몇 가지 단계를 수행해야 합니다. 먼저 NTFS 보안 설명자를 만들고 보안 설명자에 SACL을 추가합니다. 그런 다음 보안 정책을 만들고 정책 작업을 추가합니다. 그런 다음 SVM(스토리지 가상 시스템)에 보안 정책을 적용합니다.' 
---
= CLI 개요를 사용하여 NTFS 파일 및 폴더에 감사 정책을 구성하고 적용합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP CLI를 사용할 때 NTFS 파일 및 폴더에 감사 정책을 적용하려면 몇 가지 단계를 수행해야 합니다. 먼저 NTFS 보안 설명자를 만들고 보안 설명자에 SACL을 추가합니다. 그런 다음 보안 정책을 만들고 정책 작업을 추가합니다. 그런 다음 SVM(스토리지 가상 시스템)에 보안 정책을 적용합니다.

보안 정책을 적용한 후 보안 정책 작업을 모니터링하고 적용된 감사 정책의 설정을 확인할 수 있습니다.


NOTE: 감사 정책 및 관련 SACL이 적용되면 기존의 모든 DACL을 덮어씁니다. 새 보안 정책을 만들고 적용하기 전에 기존 보안 정책을 검토해야 합니다.

xref:secure-file-access-storage-level-access-guard-concept.adoc[Storage-Level Access Guard를 사용하여 파일 액세스 보호]

xref:limits-when-cli-set-file-folder-security-concept.adoc[CLI를 사용하여 파일 및 폴더 보안을 설정할 때의 제한 사항]

xref:security-descriptors-apply-file-folder-security-concept.adoc[보안 설명자를 사용하여 파일 및 폴더 보안을 적용하는 방법]

link:../nas-audit/index.html["SMB 및 NFS 감사 및 보안 추적"]

xref:create-ntfs-security-descriptor-file-task.adoc[CLI를 사용하여 NTFS 파일 및 폴더에 파일 보안을 구성하고 적용합니다]
