---
permalink: smb-admin/configure-unix-symbolic-link-support-shares-task.html 
sidebar: sidebar 
keywords: configure, unix, symbol, link, support, smb, share, share-property, setting, create, modify, exist, configure unix symbolic link support, on smb shares 
summary: SMB 공유를 생성할 때 또는 언제든지 기존 SMB 공유를 수정하여 심볼 링크 공유 속성 설정을 지정하여 SMB 공유에 대한 UNIX 심볼 링크 지원을 구성할 수 있습니다. UNIX 심볼 링크 지원은 기본적으로 활성화되어 있습니다. 공유에서 UNIX 심볼 링크 지원을 해제할 수도 있습니다. 
---
= SMB 공유에 대한 UNIX 심볼 링크 지원을 구성합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SMB 공유를 생성할 때 또는 언제든지 기존 SMB 공유를 수정하여 심볼 링크 공유 속성 설정을 지정하여 SMB 공유에 대한 UNIX 심볼 링크 지원을 구성할 수 있습니다. UNIX 심볼 링크 지원은 기본적으로 활성화되어 있습니다. 공유에서 UNIX 심볼 링크 지원을 해제할 수도 있습니다.

SMB 공유에 대한 UNIX 심볼 링크 지원을 구성할 때 다음 설정 중 하나를 선택할 수 있습니다.

|===
| 설정 | 설명 


 a| 
'enable'(사용되지 않음 *)
 a| 
심볼 링크가 읽기-쓰기 액세스를 사용하도록 설정되도록 지정합니다.



 a| 
READ_OVERY'(사용되지 않음 *)
 a| 
읽기 전용 액세스를 위해 symlink를 사용하도록 지정합니다. 이 설정은 Wodelink에는 적용되지 않습니다. Widelink 액세스는 항상 읽기-쓰기입니다.



 a| 
'hide'(사용되지 않음 *)
 a| 
SMB 클라이언트가 symlink를 볼 수 없도록 지정합니다.



 a| 
엄정한 보안 없음
 a| 
클라이언트가 공유 경계 외부의 symlink를 따르도록 지정합니다.



 a| 
'체조'입니다
 a| 
symlink가 읽기-쓰기 액세스를 위해 로컬로 설정되도록 지정합니다. CIFS 옵션 is-advertise-DFS-enabled가 true로 설정되어 있어도 DFS 광고는 생성되지 않습니다. 기본 설정입니다.



 a| 
'체임링크', '와이델링크'
 a| 
읽기-쓰기 액세스를 위해 로컬 symlink와 wizelink를 모두 지정합니다. CIFS 옵션 is-advertise-DFS-enabled가 false로 설정되어 있어도 로컬 symlink와 Wipelink 모두에 대해 DFS 광고가 생성됩니다.



 a| 
"할 수 없습니다
 a| 
symlinks 및 widelinks를 사용하지 않도록 지정합니다. CIFS 옵션 is-advertise-DFS-enabled가 true로 설정되어 있어도 DFS 광고는 생성되지 않습니다.



 a| 
""(null, 설정되지 않음)
 a| 
공유의 심볼 링크를 해제합니다.



 a| 
'-'(설정되지 않음)
 a| 
공유의 심볼 링크를 해제합니다.

|===
[NOTE]
====
* enable_, _hide_ 및 _read-only_parameters는 더 이상 사용되지 않으며 ONTAP의 향후 릴리스에서 제거될 수 있습니다.

====
.단계
. 심볼 링크 지원을 구성하거나 사용하지 않도록 설정:
+
|===
| 만약... | 입력... 


 a| 
새로운 SMB 공유
 a| 
'+vserver cifs share create-vserver vserver_name-share-name share-path-path-symlink-properties{enable|hide|read-only|""|-|symlinks|symlinks-and-wdelink|disable},...]+'



 a| 
기존 SMB 공유입니다
 a| 
'+vserver cifs share modify -vserver vserver_name -share-name share_name -symlink -properties{enable|hide|read-only|"|-|symlinks|symlinks-and-wifelink|disable},...]+'

|===
. SMB 공유 구성이 올바른지 확인합니다. 'vserver cifs share show -vserver vserver_name -share-name share_name -instance'


다음 명령을 실행하면 UNIX 심볼 링크 구성이 "enable"로 설정된 "data1"이라는 SMB 공유가 생성됩니다.

[listing]
----
cluster1::> vserver cifs share create -vserver vs1 -share-name data1 -path /data1 -symlink-properties enable

cluster1::> vserver cifs share show -vserver vs1 -share-name data1 -instance

                          Vserver: vs1
                            Share: data1
         CIFS Server NetBIOS Name: VS1
                             Path: /data1
                 Share Properties: oplocks
                                   browsable
                                   changenotify
               Symlink Properties: enable
          File Mode Creation Mask: -
     Directory Mode Creation Mask: -
                    Share Comment: -
                        Share ACL: Everyone / Full Control
    File Attribute Cache Lifetime: -
                      Volume Name: -
                    Offline Files: manual
    Vscan File-Operations Profile: standard
Maximum Tree Connections on Share: 4294967295
       UNIX Group for File Create: -
----
xref:create-symbolic-link-mappings-task.adoc[SMB 공유에 대한 심볼 링크 매핑 생성]
