---
permalink: smb-admin/configure-branchcache-task.html 
sidebar: sidebar 
keywords: configure, branchcache, service, per-share, basis, smb, share, configure branchcache on the cifs server 
summary: BranchCache를 구성하여 공유별로 BranchCache 서비스를 제공할 수 있습니다. 또는 BranchCache를 구성하여 모든 SMB 공유에서 캐싱을 자동으로 설정할 수 있습니다. 
---
= SMB 서버에서 BranchCache를 구성합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
BranchCache를 구성하여 공유별로 BranchCache 서비스를 제공할 수 있습니다. 또는 BranchCache를 구성하여 모든 SMB 공유에서 캐싱을 자동으로 설정할 수 있습니다.

SVM에서 BranchCache를 구성할 수 있습니다.

* CIFS 서버의 모든 SMB 공유 내에 포함된 모든 콘텐츠에 대해 캐싱 서비스를 제공하려는 경우 모든 공유 BranchCache 구성을 생성할 수 있습니다.
* CIFS 서버에서 선택한 SMB 공유 내에 포함된 콘텐츠에 대해 캐싱 서비스를 제공하려는 경우 공유당 BranchCache 구성을 생성할 수 있습니다.


BranchCache를 구성할 때는 다음 매개 변수를 지정해야 합니다.

|===
| 필수 매개변수 | 설명 


 a| 
_SVM 이름 _
 a| 
BranchCache는 SVM별로 구성됩니다. BranchCache 서비스를 구성할 CIFS 지원 SVM을 지정해야 합니다.



 a| 
해시 스토어에 대한 경로 _
 a| 
BranchCache 해시는 SVM 볼륨의 일반 파일에 저장됩니다. ONTAP에서 해시 데이터를 저장할 기존 디렉터리의 경로를 지정해야 합니다. BranchCache 해시 경로는 읽기/쓰기가 가능해야 합니다. 스냅샷 디렉토리와 같은 읽기 전용 경로는 허용되지 않습니다. 해시 데이터는 다른 데이터가 포함된 볼륨에 저장하거나 해시 데이터를 저장하기 위한 별도의 볼륨을 생성할 수 있습니다.

SVM이 SVM 재해 복구 소스인 경우 해시 경로가 루트 볼륨에 있을 수 없습니다. 루트 볼륨이 재해 복구 대상에 복제되지 않기 때문입니다.

해시 경로에는 공백과 유효한 파일 이름 문자가 포함될 수 있습니다.

|===
필요에 따라 다음 매개 변수를 지정할 수 있습니다.

|===
| 선택적 매개 변수입니다 | 설명 


 a| 
_지원되는 버전 _
 a| 
ONTAP는 BranchCache 1 및 2를 지원합니다. 버전 1, 버전 2 또는 두 버전을 모두 사용할 수 있습니다. 기본값은 두 버전을 모두 사용하는 것입니다.



 a| 
_ 해시 저장소의 최대 크기 _
 a| 
해시 데이터 저장소에 사용할 크기를 지정할 수 있습니다. 해시 데이터가 이 값을 초과하면 ONTAP는 이전 해시를 삭제하여 새 해시를 위한 공간을 만듭니다. 해시 저장소의 기본 크기는 1GB입니다. BranchCache는 해시가 지나치게 공격적인 방식으로 폐기되지 않을 경우 보다 효율적으로 성능을 발휘합니다. 해시 저장소가 꽉 찼기 때문에 해시가 자주 삭제되는 경우 BranchCache 구성을 수정하여 해시 저장소 크기를 늘릴 수 있습니다.



 a| 
_서버 키 _
 a| 
BranchCache 서비스가 클라이언트가 BranchCache 서버를 가장하지 못하도록 하는 데 사용하는 서버 키를 지정할 수 있습니다. 서버 키를 지정하지 않으면 BranchCache 구성을 만들 때 서버 키가 임의로 생성됩니다. 여러 서버가 동일한 파일에 BranchCache 데이터를 제공하는 경우 클라이언트는 동일한 서버 키를 사용하는 모든 서버의 해시를 사용할 수 있도록 서버 키를 특정 값으로 설정할 수 있습니다. 서버 키에 공백이 있으면 서버 키를 따옴표로 묶어야 합니다.



 a| 
_작동 모드 _
 a| 
기본 설정은 공유별로 BranchCache를 사용하는 것입니다.

* BranchCache 구성을 생성하여 공유별로 BranchCache를 사용하도록 설정하려면 이 선택적 매개 변수를 지정하지 않거나 "공유당"을 지정할 수 있습니다.
* 모든 공유에서 BranchCache를 자동으로 활성화하려면 운영 모드를 '모든 공유'로 설정해야 합니다.


|===
.단계
. 필요에 따라 SMB 2.1 및 3.0 활성화:
+
.. 권한 수준을 Advanced:'Set-Privilege advanced'로 설정합니다
.. 구성된 SVM SMB 설정을 확인하여 필요한 모든 SMB 버전이 활성화되었는지 확인합니다. 'vserver cifs options show -vserver_vserver_name_'
.. 필요한 경우 SMB 2.1:'vserver cifs options modify -vserver_vserver_name_-SMB2-enabled true'를 설정합니다
+
이 명령을 사용하면 SMB 2.0 및 SMB 2.1이 모두 설정됩니다.

.. 필요한 경우 SMB 3.0:'vserver cifs options modify -vserver_vserver_name_-SMB3-enabled true'를 설정합니다
.. admin 권한 수준으로 복귀:'et-Privilege admin'입니다


. BranchCache 구성:'vserver cifs BranchCache create-vserver_name_-hash-store-path path path [-hash-store-max-size{integer[KB|MB|GB|TB|PB]} [-versions{v1-enable|v2-enable|enable-all][-server-key text] - operating-mode{per-share|all-share}}
+
지정된 해시 스토리지 경로가 있어야 하며 SVM에서 관리하는 볼륨에 상주해야 합니다. 경로는 읽기 쓰기 가능 볼륨에도 있어야 합니다. 경로가 읽기 전용이거나 존재하지 않으면 명령이 실패합니다.

+
SVM BranchCache 구성을 추가할 때 동일한 서버 키를 사용하려면 서버 키에 대해 입력한 값을 기록합니다. BranchCache 구성에 대한 정보를 표시할 때는 서버 키가 나타나지 않습니다.

. BranchCache 구성이 올바른지 확인합니다. 'vserver cifs BranchCache show -vserver_vserver_name_'


다음 명령을 실행하면 SMB 2.1과 3.0이 모두 활성화되어 있고 SVM VS1의 모든 SMB 공유에서 캐싱이 자동으로 활성화되도록 BranchCache가 구성됩니다.

[listing]
----
cluster1::> set -privilege advanced
Warning: These advanced commands are potentially dangerous; use them
only when directed to do so by technical support personnel.
Do you wish to continue? (y or n): y

cluster1::*> vserver cifs options show -vserver vs1 -fields smb2-enabled,smb3-enabled
vserver smb2-enabled smb3-enabled
------- ------------ ------------
vs1     true         true


cluster1::*> set -privilege admin

cluster1::> vserver cifs branchcache create -vserver vs1 -hash-store-path /hash_data -hash-store-max-size 20GB -versions enable-all -server-key "my server key" -operating-mode all-shares

cluster1::> vserver cifs branchcache show -vserver vs1

                                 Vserver: vs1
          Supported BranchCache Versions: enable_all
                      Path to Hash Store: /hash_data
          Maximum Size of the Hash Store: 20GB
Encryption Key Used to Secure the Hashes: -
        CIFS BranchCache Operating Modes: all_shares
----
다음 명령은 SMB 2.1과 3.0이 모두 활성화되어 있는지 확인하고, SVM VS1 기반 공유별로 캐싱이 가능하도록 BranchCache를 구성하고, BranchCache 구성을 확인합니다.

[listing]
----
cluster1::> set -privilege advanced
Warning: These advanced commands are potentially dangerous; use them
only when directed to do so by technical support personnel.
Do you wish to continue? (y or n): y

cluster1::*> vserver cifs options show -vserver vs1 -fields smb2-enabled,smb3-enabled
vserver smb2-enabled smb3-enabled
------- ------------ ------------
vs1     true         true

cluster1::*> set -privilege admin

cluster1::> vserver cifs branchcache create -vserver vs1 -hash-store-path /hash_data -hash-store-max-size 20GB -versions enable-all -server-key "my server key"

cluster1::> vserver cifs branchcache show -vserver vs1

                                 Vserver: vs1
          Supported BranchCache Versions: enable_all
                      Path to Hash Store: /hash_data
          Maximum Size of the Hash Store: 20GB
Encryption Key Used to Secure the Hashes: -
        CIFS BranchCache Operating Modes: per_share
----
xref:requirements-guidelines-concept.adoc[요구사항 및 지침]

xref:configure-branchcache-remote-office-concept.adoc[원격 사무소에서 BranchCache 구성에 대한 정보를 찾을 수 있는 위치]

xref:create-branchcache-enabled-share-task.adoc[BranchCache 지원 SMB 공유 생성]

xref:enable-branchcache-existing-share-task.adoc[기존 SMB 공유에서 BranchCache를 사용하도록 설정합니다]

xref:manage-monitor-branchcache-config-concept.adoc[BranchCache 구성 관리 및 모니터링]

xref:disable-enable-branchcache-svm-concept.adoc[SVM에서 BranchCache를 사용하지 않도록 설정하거나 사용하도록 설정합니다]

xref:delete-branchcache-config-svms-concept.adoc[SVM에서 BranchCache 구성을 삭제합니다]
