---
permalink: smb-admin/create-home-directory-config-w-d-variables-task.html 
sidebar: sidebar 
keywords: 'create, home, directory, configuration, variable, user, connect, share, dynamic, create, share, %w, %d, create a home directory configuration using the %w and %d variables' 
summary: '%w 및 %d 변수를 사용하여 홈 디렉토리 구성을 생성할 수 있습니다. 사용자는 동적으로 생성된 공유를 사용하여 홈 공유에 연결할 수 있습니다.' 
---
= %w 및 %d 변수를 사용하여 홈 디렉토리 설정을 작성합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
"%w" 및 "%d" 변수를 사용하여 홈 디렉토리 설정을 작성할 수 있습니다. 사용자는 동적으로 생성된 공유를 사용하여 홈 공유에 연결할 수 있습니다.

.단계
. 사용자의 홈 디렉토리를 포함할 qtree를 생성합니다: 'volume qtree create-vserver vserver_name-qtree-path qtree_path'
. qtree가 올바른 보안 유형인 'volume qtree show'를 사용하는지 확인합니다
. Qtree에서 원하는 보안 스타일을 사용하지 않는 경우 'volume qtree security' 명령을 사용하여 보안 스타일을 변경하십시오.
. 홈 디렉토리 공유 추가: "+vserver cifs share create-vserver vserver-share-name %w-path %d/%w-share-properties homed디렉토리\[,...\]+"
+
'-vserver''vserver'는 검색 경로를 추가할 SVM(CIFS 지원 스토리지 가상 머신)을 지정합니다.

+
'-share-name '%w'는 홈 디렉토리 공유 이름을 지정합니다. ONTAP는 각 사용자가 홈 디렉토리에 접속할 때 동적으로 공유 이름을 생성합니다. 공유 이름은 _WINDOWS_USER_NAME_ 형식입니다.

+
'-path '%d/%w'는 홈 디렉토리의 상대 경로를 지정합니다. 상대 경로는 각 사용자가 자신의 홈 디렉토리에 접속할 때 동적으로 생성되며 _domain/windows_user_name_ 형식이 됩니다.

+
'-share-properties homed디렉토리 [,...]+'는 해당 공유의 공유 속성을 지정합니다. homedir 값을 지정해야 합니다. 쉼표로 구분된 목록을 사용하여 추가 공유 속성을 지정할 수 있습니다.

. 'vserver cifs share show' 명령을 사용하여 공유에 원하는 구성이 있는지 확인합니다.
. 홈 디렉토리 검색 경로 'vserver cifs home-directory search-path add-vserver vserver-path path path' 추가
+
'-vserver_vserver-name_'은 검색 경로를 추가할 CIFS 지원 SVM을 지정합니다.

+
'-path_path_'는 검색 경로에 대한 절대 디렉토리 경로를 지정합니다.

. 'vserver cifs home-directory search-path show' 명령을 사용하여 검색 경로를 성공적으로 추가했는지 확인합니다.
. 홈 디렉토리가 있는 사용자의 경우 홈 디렉토리를 포함하도록 지정된 qtree 또는 볼륨에 해당 디렉토리를 생성합니다.
+
예를 들어, '/vol/vol1/users' 경로와 생성할 디렉토리가 mydomain\user1인 사용자 이름으로 qtree를 생성한 경우 '/vol/vol1/users/mydomain/user1' 경로를 사용하여 디렉토리를 생성합니다.

+
/home1 에 마운트된 ""home1" 볼륨을 생성한 경우 "/home1/mydomain/user1" 경로를 사용하여 디렉토리를 생성합니다.

. 드라이브를 매핑하거나 UNC 경로를 사용하여 연결하여 사용자가 홈 공유에 성공적으로 연결할 수 있는지 확인합니다.
+
예를 들어, mydomain\user1 사용자가 SVM VS1 에 있는 8단계에서 생성한 디렉토리에 연결하려는 경우 user1은 UNC 경로 "\\VS1\user1"을 사용하여 연결됩니다.



다음 예제의 명령은 다음과 같은 설정으로 홈 디렉토리 구성을 만듭니다.

* 공유 이름은 %W입니다
* 상대 홈 디렉토리 경로는 %d/%W입니다
* 홈 디렉토리 /home1 을 포함하는 데 사용되는 검색 경로는 NTFS 보안 스타일로 구성된 볼륨입니다.
* SVM VS1 에서 구성이 생성됩니다.


사용자가 Windows 호스트에서 홈 디렉토리에 액세스할 때 이 유형의 홈 디렉토리 구성을 사용할 수 있습니다. 또한 사용자가 Windows 및 UNIX 호스트에서 홈 디렉토리를 액세스할 때 이 유형의 구성을 사용할 수 있으며 파일 시스템 관리자는 Windows 기반 사용자 및 그룹을 사용하여 파일 시스템에 대한 액세스를 제어할 수 있습니다.

[listing]
----
cluster::> vserver cifs share create -vserver vs1 -share-name %w -path %d/%w -share-properties oplocks,browsable,changenotify,homedirectory

cluster::> vserver cifs share show -vserver vs1 -share-name %w

                      Vserver: vs1
                        Share: %w
     CIFS Server NetBIOS Name: VS1
                         Path: %d/%w
             Share Properties: oplocks
                               browsable
                               changenotify
                               homedirectory
           Symlink Properties: enable
      File Mode Creation Mask: -
 Directory Mode Creation Mask: -
                Share Comment: -
                    Share ACL: Everyone / Full Control
File Attribute Cache Lifetime: -
                  Volume Name: -
                Offline Files: manual
Vscan File-Operations Profile: standard

cluster::> vserver cifs home-directory search-path add -vserver vs1 ‑path /home1

cluster::> vserver cifs home-directory search-path show
Vserver     Position Path
----------- -------- -----------------
vs1         1        /home1
----
xref:configure-home-directories-u-variable-task.adoc[%u 변수를 사용하여 홈 디렉토리를 구성하는 중입니다]

xref:home-directory-config-concept.adoc[추가 홈 디렉토리 구성]

xref:display-user-home-directory-path-task.adoc[SMB 사용자의 홈 디렉토리 경로에 대한 정보 표시]
