---
permalink: smb-admin/create-ntfs-security-descriptor-audit-task.html 
sidebar: sidebar 
keywords: create, creating, ntfs, security, descriptor, audit, policy, configure, configuring, apply, access, control, list, acl, file, residing, reside, svm, associate, folder, policy, task, create an ntfs security descriptor 
summary: 'NTFS 보안 설명자 감사 정책을 생성하는 것은 SVM에 상주하는 파일 및 폴더에 NTFS ACL(액세스 제어 목록)을 구성 및 적용하는 첫 번째 단계입니다. 보안 설명자를 정책 작업의 파일 또는 폴더 경로에 연결합니다.' 
---
= NTFS 보안 설명자를 만듭니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NTFS 보안 설명자 감사 정책을 생성하는 것은 SVM에 상주하는 파일 및 폴더에 NTFS ACL(액세스 제어 목록)을 구성 및 적용하는 첫 번째 단계입니다. 보안 설명자를 정책 작업의 파일 또는 폴더 경로에 연결합니다.

.이 작업에 대해
NTFS 보안 스타일 볼륨 내에 있는 파일 및 폴더 또는 혼합 보안 스타일 볼륨에 상주하는 파일 및 폴더에 대한 NTFS 보안 설명자를 만들 수 있습니다.

기본적으로 보안 설명자가 만들어지면 네 개의 DACL(임의 액세스 제어 목록) ACE(액세스 제어 항목)가 해당 보안 설명자에 추가됩니다. 네 가지 기본 ACE는 다음과 같습니다.

|===
| 오브젝트 | 액세스 유형입니다 | 액세스 권한 | 사용 권한을 적용할 위치입니다 


 a| 
BUILTIN\Administrators입니다
 a| 
허용
 a| 
모든 권한
 a| 
폴더, 하위 폴더, 파일



 a| 
BUILTIN\사용자
 a| 
허용
 a| 
모든 권한
 a| 
폴더, 하위 폴더, 파일



 a| 
작성자 소유자
 a| 
허용
 a| 
모든 권한
 a| 
폴더, 하위 폴더, 파일



 a| 
NT AUTHORITY\SYSTEM
 a| 
허용
 a| 
모든 권한
 a| 
폴더, 하위 폴더, 파일

|===
다음 선택적 매개 변수를 사용하여 보안 설명자 구성을 사용자 지정할 수 있습니다.

* 보안 설명자의 소유자입니다
* 소유자의 기본 그룹입니다
* 원시 제어 플래그


선택적 매개 변수의 값은 Storage-Level Access Guard에서 무시됩니다. 자세한 내용은 man 페이지를 참조하십시오.

.단계
. 고급 매개 변수를 사용하려면 권한 수준을 고급:'Set-Privilege Advanced'로 설정합니다
. 보안 설명자:'vserver security file-directory NTFS create-vserver vserver_name-NTFS-SD sd_nameoptional_parameters'를 생성합니다
+
'vserver security file-directory NTFS create-NTFS-SD SD1-vserver vs1-owner domain\joe'

. 보안 설명자 구성이 올바른지 확인합니다. 'vserver security file-directory NTFS show -vserver vserver_name -NTFS-SD sd_name'
+
[listing]
----
vserver security file-directory ntfs show -vserver vs1 -ntfs-sd sd1
----
+
[listing]
----
                                     Vserver: vs1
                           Security Descriptor Name: sd1
                   Owner of the Security Descriptor: DOMAIN\joe
----
. 고급 권한 수준인 경우 'Set-Privilege admin'으로 돌아갑니다

