---
permalink: smb-admin/create-symbolic-link-mappings-task.html 
sidebar: sidebar 
keywords: create, mapping, unix, symbolic, link, smb, share, relative, symbol, refer, file, folder, relative, parent, absolute, create symbolic link mappings for smb shares 
summary: SMB 공유에 대한 UNIX 심볼 링크 매핑을 생성할 수 있습니다. 상위 폴더에 상대적인 파일이나 폴더를 참조하는 상대 심볼 링크를 만들거나 절대 경로를 사용하여 파일 또는 폴더를 참조하는 절대 심볼 링크를 만들 수 있습니다. 
---
= SMB 공유에 대한 심볼 링크 매핑을 생성합니다
:icons: font
:imagesdir: ../media/


[role="lead"]
SMB 공유에 대한 UNIX 심볼 링크 매핑을 생성할 수 있습니다. 상위 폴더에 상대적인 파일이나 폴더를 참조하는 상대 심볼 링크를 만들거나 절대 경로를 사용하여 파일 또는 폴더를 참조하는 절대 심볼 링크를 만들 수 있습니다.

SMB 2.x를 사용하는 경우 Mac OS X 클라이언트에서 Widelink에 액세스할 수 없습니다 사용자가 Mac OS X 클라이언트의 widelink를 사용하여 공유에 연결하려고 하면 시도가 실패합니다. 그러나 SMB 1을 사용하는 경우 Mac OS X 클라이언트에서 Wistelink를 사용할 수 있습니다.

.단계
. SMB 공유에 대한 심볼 링크 매핑을 생성하려면 다음을 수행합니다. "vserver cifs symlink create -vserver virtual_server_name -unix-path path path path -share-name share_name -cifs-path path path path[-cifs-server server_name][-locality{local|free|wdelink}][-home-directory{true|false}]"
+
'-vserver''virtual_server_name'은 SVM(Storage Virtual Machine) 이름을 지정합니다.

+
'-unix-path' path는 UNIX 경로를 지정합니다. UNIX 경로는 슬래시("/")로 시작해야 하며 슬래시("/")로 끝나야 합니다.

+
'-share-name''share_name'은 매핑할 SMB 공유의 이름을 지정합니다.

+
'-cifs-path' path는 CIFS 경로를 지정합니다. CIFS 경로는 슬래시("/")로 시작해야 하며 슬래시("/")로 끝나야 합니다.

+
'-cifs-server ''server_name'은 CIFS 서버 이름을 지정합니다. CIFS 서버 이름은 DNS 이름(예: mynetwork.cifs.server.com), IP 주소 또는 NetBIOS 이름으로 지정할 수 있습니다. NetBIOS 이름은 'vserver cifs show' 명령을 사용하여 확인할 수 있습니다. 이 선택적 매개 변수를 지정하지 않으면 로컬 CIFS 서버의 NetBIOS 이름이 기본값이 됩니다.

+
``지역성’{'local'|'free'|'wdelink'}은 로컬 링크, 무료 링크 또는 넓은 심볼 링크 생성 여부를 지정합니다. 로컬 심볼 링크는 로컬 SMB 공유에 매핑됩니다. 무료 심볼 링크는 로컬 SMB 서버의 어느 위치에나 매핑할 수 있습니다. 넓은 심볼 링크는 네트워크의 모든 SMB 공유에 매핑됩니다. 이 선택적 매개 변수를 지정하지 않으면 기본값은 "local"입니다.

+
'-home-directory'{'true'|'false'}는 타겟 공유가 홈 디렉토리인지 여부를 지정합니다. 이 매개 변수는 선택 사항이지만 타겟 공유가 홈 디렉토리로 구성될 때 이 매개 변수를 "true"로 설정해야 합니다. 기본값은 false 입니다.



다음 명령을 실행하면 이름이 VS1 인 SVM에 심볼 링크 매핑이 생성됩니다. UNIX 경로인 /src/, SMB 공유 이름 "소스", CIFS 경로, /mycompany/source/", CIFS 서버 IP 주소 123.123.123.123 등이 있으며, 이는 wizelink입니다.

[listing]
----
cluster1::> vserver cifs symlink create -vserver vs1 -unix-path /src/ -share-name SOURCE -cifs-path "/mycompany/source/" -cifs-server 123.123.123.123 -locality widelink
----
xref:configure-unix-symbolic-link-support-shares-task.adoc[SMB 공유에서 UNIX 심볼 링크 지원 구성]
