---
permalink: smb-admin/delete-local-group-task.html 
sidebar: sidebar 
keywords: delete, local, group, storage, virtual, machine, svm, determine, determining, access, right, data, associate, assign, user, privilege, member, delete a local group 
summary: 'SVM(스토리지 가상 시스템)에서 로컬 그룹을 삭제하여 해당 SVM과 관련된 데이터에 대한 액세스 권한을 결정하거나 SVM 사용자 권한(권한)을 그룹 멤버에 할당할 필요가 없는 경우 해당 로컬 그룹을 삭제할 수 있습니다.' 
---
= 로컬 그룹을 삭제합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SVM(스토리지 가상 시스템)에서 로컬 그룹을 삭제하여 해당 SVM과 관련된 데이터에 대한 액세스 권한을 결정하거나 SVM 사용자 권한(권한)을 그룹 멤버에 할당할 필요가 없는 경우 해당 로컬 그룹을 삭제할 수 있습니다.

로컬 그룹을 삭제할 때 다음 사항에 유의하십시오.

* 파일 시스템이 변경되지 않았습니다.
+
이 그룹을 참조하는 파일 및 디렉토리의 Windows 보안 설명자는 조정되지 않습니다.

* 그룹이 없으면 오류가 반환됩니다.
* special_everyone_group은 삭제할 수 없습니다.
* BUILTIN\Administrators__BUILTIN\Users_와 같은 기본 제공 그룹은 삭제할 수 없습니다.


.단계
. SVM에 로컬 그룹 목록을 표시하여 삭제할 로컬 그룹의 이름을 확인합니다. 'vserver cifs users-and-groups local-group show -vserver vserver_name'
. 로컬 그룹 'vserver cifs users-and-groups local-group delete -vserver_vserver_name_‑group-name_group_name_'을 삭제합니다
. 그룹이 삭제되었는지 확인합니다. 'vserver cifs users-and-groups local-user show -vserver_vserver_name_'


다음 예에서는 SVM VS1 관련 로컬 그룹 ""cifs_server\sales""를 삭제합니다.

[listing]
----
cluster1::> vserver cifs users-and-groups local-group show -vserver vs1
Vserver   Group Name                   Description
--------- ---------------------------- ----------------------------
vs1       BUILTIN\Administrators       Built-in Administrators group
vs1       BUILTIN\Backup Operators     Backup Operators group
vs1       BUILTIN\Power Users          Restricted administrative privileges
vs1       BUILTIN\Users                All users
vs1       CIFS_SERVER\engineering
vs1       CIFS_SERVER\sales

cluster1::> vserver cifs users-and-groups local-group delete -vserver vs1 -group-name CIFS_SERVER\sales

cluster1::> vserver cifs users-and-groups local-group show -vserver vs1
Vserver   Group Name                   Description
--------- ---------------------------- ----------------------------
vs1       BUILTIN\Administrators       Built-in Administrators group
vs1       BUILTIN\Backup Operators     Backup Operators group
vs1       BUILTIN\Power Users          Restricted administrative privileges
vs1       BUILTIN\Users                All users
vs1       CIFS_SERVER\engineering
----