---
permalink: smb-admin/disallow-users-groups-bypass-directory-traverse-task.html 
sidebar: sidebar 
keywords: user, traverse, directories, directory, path, file, permission, sechangenotifyprivilege, privilege, local, smb, group, storage, virtual, machine, svm, disallow users or groups from bypassing directory traverse checking 
summary: '사용자가 이동 중인 디렉토리에 대한 권한이 없기 때문에 경로 내의 모든 디렉토리를 사용자에게 이동하지 않도록 하려면 SVM(Storage Virtual Machine)의 로컬 SMB 사용자 또는 그룹에서 SeChangeNotifyPrivilege 권한을 제거할 수 있습니다.' 
---
= 디렉토리 통과 확인을 거치지 않고 사용자 또는 그룹을 허용하지 않습니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
사용자가 이동 중인 디렉토리에 대한 권한이 없기 때문에 경로 내의 모든 디렉토리를 이동하지 않으려면 SVM(Storage Virtual Machine)의 로컬 SMB 사용자 또는 그룹에서 'seChangeNotifyPrivilege' 권한을 제거할 수 있습니다.

권한을 제거할 로컬 또는 도메인 사용자 또는 그룹이 이미 있어야 합니다.

도메인 사용자 또는 그룹에서 권한을 제거할 때 ONTAP는 도메인 컨트롤러에 문의하여 도메인 사용자 또는 그룹의 유효성을 검사할 수 있습니다. ONTAP가 도메인 컨트롤러에 연결할 수 없으면 명령이 실패할 수 있습니다.

.단계
. 통과 확인 무시 허용 안 함: 'vserver cifs users-and-groups privilege remove-privilege-vserver_vserver_name_-user-or-group-name_name_-Privileges SeChangeNotifyPrivilege'
+
이 명령은 '-user-or-group-name_name_' 매개 변수 값으로 지정한 로컬 또는 도메인 사용자 또는 그룹에서 'seChangeNotifyPrivilege' 권한을 제거합니다.

. 지정된 사용자 또는 그룹이 통과 확인을 사용하지 않도록 설정했는지 확인합니다. 'vserver cifs users-and-groups privilege show-vserver_name_-user-or-group-name_name_'


다음 명령을 실행하면 디렉토리 트래버스 검사를 거치지 않고 "'example\eng'" 그룹에 속한 사용자가 사용할 수 없습니다.

[listing]
----
cluster1::> vserver cifs users-and-groups privilege show -vserver vs1
Vserver   User or Group Name    Privileges
--------- --------------------- -----------------------
vs1       EXAMPLE\eng           SeChangeNotifyPrivilege

cluster1::> vserver cifs users-and-groups privilege remove-privilege -vserver vs1 -user-or-group-name EXAMPLE\eng -privileges SeChangeNotifyPrivilege

cluster1::> vserver cifs users-and-groups privilege show -vserver vs1
Vserver   User or Group Name    Privileges
--------- --------------------- -----------------------
vs1       EXAMPLE\eng           -
----
xref:allow-users-groups-bypass-directory-traverse-task.adoc[사용자 또는 그룹이 디렉토리 통과 확인을 생략하도록 허용합니다]
