---
permalink: smb-admin/display-dynamic-access-control-security-task.html 
sidebar: sidebar 
keywords: display, information, dynamic, access, control, dac, security, ntfs, volume, data, effective, security, mix, security-stle, volume, conditional, ace, resource, central, access, policy, display information about dynamic access control security 
summary: 'DAC(Dynamic Access Control) 보안에 대한 정보를 NTFS 볼륨과 NTFS 유효 보안 데이터가 혼합된 보안 스타일 볼륨에서 표시할 수 있습니다. 여기에는 조건부 ACE, 리소스 ACE 및 중앙 액세스 정책 ACE에 대한 정보가 포함됩니다. 결과를 사용하여 보안 구성을 확인하거나 파일 액세스 문제를 해결할 수 있습니다.' 
---
= 동적 액세스 제어 보안에 대한 정보를 표시합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
DAC(Dynamic Access Control) 보안에 대한 정보를 NTFS 볼륨과 NTFS 유효 보안 데이터가 혼합된 보안 스타일 볼륨에서 표시할 수 있습니다. 여기에는 조건부 ACE, 리소스 ACE 및 중앙 액세스 정책 ACE에 대한 정보가 포함됩니다. 결과를 사용하여 보안 구성을 확인하거나 파일 액세스 문제를 해결할 수 있습니다.

.이 작업에 대해
SVM(스토리지 가상 시스템)의 이름과 파일 또는 폴더 보안 정보를 표시할 데이터의 경로를 제공해야 합니다. 출력을 요약 양식 또는 상세 목록으로 표시할 수 있습니다.

.단계
. 파일 및 디렉터리 보안 설정을 원하는 수준으로 표시합니다.
+
|===
| 정보를 표시하려면... | 다음 명령을 입력합니다... 


 a| 
요약 양식
 a| 
'vserver security file-directory show -vserver vserver_name -path path path'



 a| 
세부 정보가 확장됩니다
 a| 
'vserver security file-directory show -vserver vserver_name -path path path -expand-mask true'



 a| 
여기서 출력은 그룹 및 사용자 SID와 함께 표시됩니다
 a| 
'vserver security file-directory show -vserver vserver_name -path path -lookup-names false'



 a| 
16진수 비트 마스크가 텍스트 형식으로 변환되는 파일과 디렉토리의 파일 및 디렉토리 보안에 대해 설명합니다
 a| 
'vserver security file-directory show -vserver vserver_name -path path path -텍스트 마스크 true'

|===


.예
다음 예제는 SVM VS1 경로의 동적 액세스 제어 보안 정보 /vol1 을 보여줍니다.

[listing]
----
cluster1::> vserver security file-directory show -vserver vs1 -path /vol1
                           Vserver: vs1
                         File Path: /vol1
                 File Inode Number: 112
                    Security Style: mixed
                   Effective Style: ntfs
                    DOS Attributes: 10
            DOS Attributes in Text: ----D---
            Expanded Dos Attribute: -
                      Unix User Id: 0
                     Unix Group Id: 1
                    Unix Mode Bits: 777
            Unix Mode Bits in Text: rwxrwxrwx
                              ACLs: NTFS Security Descriptor
                                    Control:0xbf14
                                    Owner:CIFS1\Administrator
                                    Group:CIFS1\Domain Admins
                                    SACL - ACEs
                                       ALL-Everyone-0xf01ff-OI|CI|SA|FA
                                       RESOURCE ATTRIBUTE-Everyone-0x0
                                         ("Department_MS",TS,0x10020,"Finance")
                                       POLICY ID-All resources - No Write-0x0-OI|CI
                                    DACL - ACEs
                                       ALLOW-CIFS1\Administrator-0x1f01ff-OI|CI
                                       ALLOW-Everyone-0x1f01ff-OI|CI
                                       ALLOW CALLBACK-DAC\user1-0x1200a9-OI|CI
                                         ((@User.department==@Resource.Department_MS&&@Resource.Impact_MS>1000)&&@Device.department==@Resource.Department_MS)
----
.관련 정보
xref:display-gpo-config-task.adoc[GPO 구성에 대한 정보 표시]

xref:display-central-access-policies-task.adoc[중앙 액세스 정책에 대한 정보 표시]

xref:display-central-access-policy-rules-task.adoc[중앙 액세스 정책 규칙에 대한 정보 표시]
