---
permalink: smb-admin/display-restricted-group-gpos-task.html 
sidebar: sidebar 
keywords: display, detail, information, restrict, group, define, group, policy, object, gpo, active, directory, applied, apply, cifs, server, display detailed information about restricted group gpos 
summary: 'Active Directory에서 GPO(그룹 정책 개체)로 정의되고 CIFS 서버에 적용되는 제한된 그룹에 대한 자세한 정보를 표시할 수 있습니다.' 
---
= 제한된 그룹 GPO에 대한 자세한 정보를 표시합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Active Directory에서 GPO(그룹 정책 개체)로 정의되고 CIFS 서버에 적용되는 제한된 그룹에 대한 자세한 정보를 표시할 수 있습니다.

.이 작업에 대해
기본적으로 다음 정보가 표시됩니다.

* 그룹 정책 이름입니다
* 그룹 정책 버전입니다
* 링크
+
그룹 정책이 구성되는 수준을 지정합니다. 가능한 출력 값은 다음과 같습니다.

+
** ONTAP에서 그룹 정책이 구성되면 Local이 됩니다
** 도메인 컨트롤러의 사이트 수준에서 그룹 정책이 구성되면 '사이트'입니다
** 도메인 컨트롤러의 도메인 수준에서 그룹 정책이 구성되면 "domain"입니다
** 조직 단위(OrganizationalUnit) - 도메인 컨트롤러의 조직 단위(OU) 수준에서 그룹 정책이 구성된 경우
** 다양한 수준에서 정의된 모든 그룹 정책에서 파생된 정책의 결과 집합에 대한 RSoP


* 제한된 그룹 이름입니다
* 제한된 그룹에 속하고 속하지 않는 사용자 및 그룹
* 제한된 그룹이 추가되는 그룹의 목록입니다
+
그룹은 여기에 나열된 그룹 이외의 그룹의 구성원이 될 수 있습니다.



.단계
. 다음 작업 중 하나를 수행하여 모든 제한된 그룹 GPO에 대한 정보를 표시합니다.
+
|===
| 모든 제한된 그룹 GPO에 대한 정보를 표시하려면... | 명령 입력... 


 a| 
Active Directory에 정의되어 있습니다
 a| 
'vserver cifs group-policy restricted-group show-defined-vserver vserver_name'



 a| 
CIFS 서버에 적용됩니다
 a| 
'vserver cifs group-policy restricted-group show-applied-vserver vserver_name'

|===


.예
다음 예에서는 VS1 이라는 CIFS 지원 SVM이 속한 Active Directory 도메인에 정의된 제한된 그룹 GPO에 대한 정보를 표시합니다.

[listing]
----
cluster1::> vserver cifs group-policy restricted-group show-defined -vserver vs1

Vserver: vs1
-------------

     Group Policy Name: gpo1
               Version: 16
                  Link: OrganizationalUnit
            Group Name: group1
               Members: user1
              MemberOf: EXAMPLE\group9

     Group Policy Name: Resultant Set of Policy
               Version: 0
                  Link: RSOP
            Group Name: group1
               Members: user1
              MemberOf: EXAMPLE\group9
----
다음 예에서는 CIFS 지원 SVM VS1 에 적용된 제한된 그룹 GPO에 대한 정보를 표시합니다.

[listing]
----
cluster1::> vserver cifs group-policy restricted-group show-applied -vserver vs1

Vserver: vs1
-------------

     Group Policy Name: gpo1
               Version: 16
                  Link: OrganizationalUnit
            Group Name: group1
               Members: user1
              MemberOf: EXAMPLE\group9

     Group Policy Name: Resultant Set of Policy
               Version: 0
                  Link: RSOP
            Group Name: group1
               Members: user1
              MemberOf: EXAMPLE\group9
----
.관련 정보
xref:display-gpo-config-task.adoc[GPO 구성에 대한 정보 표시]
