---
permalink: smb-admin/display-session-task.html 
sidebar: sidebar 
keywords: display, information, establish, smb, session, connection, session, id, ip, address, workstation, protection, level, nondisruptive, operation, display smb session information 
summary: SMB 연결 및 세션 ID와 세션을 사용하는 워크스테이션의 IP 주소를 포함하여 설정된 SMB 세션에 대한 정보를 표시할 수 있습니다. 세션의 SMB 프로토콜 버전 및 지속적으로 사용 가능한 보호 수준에 대한 정보를 표시하여 세션이 무중단 운영을 지원하는지 여부를 확인할 수 있습니다. 
---
= SMB 세션 정보를 표시합니다
:icons: font
:imagesdir: ../media/


[role="lead"]
SMB 연결 및 세션 ID와 세션을 사용하는 워크스테이션의 IP 주소를 포함하여 설정된 SMB 세션에 대한 정보를 표시할 수 있습니다. 세션의 SMB 프로토콜 버전 및 지속적으로 사용 가능한 보호 수준에 대한 정보를 표시하여 세션이 무중단 운영을 지원하는지 여부를 확인할 수 있습니다.

SVM의 모든 세션에 대한 정보를 요약 형식으로 표시할 수 있습니다. 그러나 대부분의 경우 반환되는 출력량이 큽니다. 옵션 매개 변수를 지정하여 출력에 표시되는 정보를 사용자 지정할 수 있습니다.

* 옵션 '-fields' 매개변수를 사용하여 선택한 필드에 대한 출력을 표시할 수 있습니다.
+
필드를 입력할 수 있습니다 사용할 수 있는 필드를 결정합니다.

* '-instance' 매개 변수를 사용하면 설정된 SMB 세션에 대한 자세한 정보를 표시할 수 있습니다.
* '-fields' 매개 변수 또는 '-instance' 매개 변수를 단독으로 사용하거나 다른 선택적 매개 변수와 함께 사용할 수 있습니다.


.단계
. 다음 작업 중 하나를 수행합니다.
+
|===
| SMB 세션 정보를 표시하려면... | 다음 명령을 입력합니다... 


 a| 
SVM의 모든 세션에 대해 요약 양식을 작성합니다
 a| 
'vserver cifs session show -vserver vserver_name'을 선택합니다



 a| 
지정된 연결 ID에 있습니다
 a| 
'vserver cifs session show -vserver vserver_name -connection -id integer'를 선택합니다



 a| 
지정된 워크스테이션 IP 주소에서
 a| 
'vserver cifs session show -vserver vserver_name -address workstation_ip_address'



 a| 
지정된 LIF IP 주소입니다
 a| 
'vserver cifs session show -vserver vserver_name -lif-address LIF_ip_address'



 a| 
지정된 노드에서
 a| 
'vserver cifs session show -vserver vserver_name -node{node_name | local}'



 a| 
지정된 Windows 사용자로부터
 a| 
'vserver cifs session show -vserver vserver_name -windows-user domain_name\\user_name'



 a| 
지정된 인증 메커니즘을 사용합니다
 a| 
'vserver cifs session show -vserver vserver_name -auth-mechanism{NTLMv1|NTLMv2|Kerberos|Anonymous}'



 a| 
지정된 프로토콜 버전을 사용하여
 a| 
'vserver cifs session show -vserver vserver_name -protocol -version{SMB1|SMB2|SMB2_1|SMB3|SMB3_1}'을 선택합니다

[NOTE]
====
지속적으로 사용 가능한 보호 기능과 SMB 멀티 채널은 SMB 3.0 이상 세션에서만 사용할 수 있습니다. 모든 적격 세션에서 해당 상태를 보려면 이 매개 변수를 'MB3' 이상으로 설정한 값으로 지정해야 합니다.

====


 a| 
지속적으로 사용 가능한 보호 수준을 지정합니다
 a| 
'vserver cifs session show -vserver vserver_name -Continuously-available{No|Yes|Partial}'

[NOTE]
====
계속 사용 가능한 상태가 "부분"인 경우 세션에 하나 이상의 열려 있는 연속 사용 가능한 파일이 포함되어 있지만 세션에 계속 사용 가능한 보호 기능이 있는 일부 파일이 열려 있지 않은 것입니다. 'vserver cifs sessions file show' 명령을 사용하여 설정된 세션에서 계속 사용 가능한 보호 기능을 사용하여 열려 있지 않은 파일을 확인할 수 있습니다.

====


 a| 
지정된 SMB 서명 세션 상태
 a| 
'vserver cifs session show -vserver vserver_name -is-session -signed{true|false}'

|===


다음 명령을 실행하면 IP 주소가 10.1.1.1인 워크스테이션에서 설정된 SVM VS1 세션의 세션 정보가 표시됩니다.

[listing]
----
cluster1::> vserver cifs session show -address 10.1.1.1
Node:    node1
Vserver: vs1
Connection Session                                    Open         Idle
ID          ID      Workstation      Windows User    Files         Time
----------  ------- ---------------- ------------- ------- ------------
3151272279,
3151272280,
3151272281  1       10.1.1.1         DOMAIN\joe          2          23s
----
다음 명령을 실행하면 SVM VS1 에서 지속적으로 사용 가능한 보호 기능을 지원하는 세션에 대한 자세한 세션 정보가 표시됩니다. 도메인 계정을 사용하여 연결을 만들었습니다.

[listing]
----
cluster1::> vserver cifs session show -instance -continuously-available Yes

                        Node: node1
                     Vserver: vs1
                  Session ID: 1
               Connection ID: 3151274158
Incoming Data LIF IP Address: 10.2.1.1
      Workstation IP address: 10.1.1.2
    Authentication Mechanism: Kerberos
                Windows User: DOMAIN\SERVER1$
                   UNIX User: pcuser
                 Open Shares: 1
                  Open Files: 1
                  Open Other: 0
              Connected Time: 10m 43s
                   Idle Time: 1m 19s
            Protocol Version: SMB3
      Continuously Available: Yes
           Is Session Signed: false
       User Authenticated as: domain-user
                NetBIOS Name: -
       SMB Encryption Status: Unencrypted
----
다음 명령을 실행하면 SVM VS1 기반 SMB 3.0 및 SMB 멀티 채널을 사용하는 세션에 대한 세션 정보가 표시됩니다. 이 예에서 사용자는 LIF IP 주소를 사용하여 SMB 3.0 지원 클라이언트에서 이 공유에 연결했습니다. 따라서 인증 메커니즘은 NTLMv2로 기본값입니다. 지속적으로 사용 가능한 보호 기능을 사용하여 연결하려면 Kerberos 인증을 사용하여 연결해야 합니다.

[listing]
----
cluster1::> vserver cifs session show -instance -protocol-version SMB3

                        Node: node1
                     Vserver: vs1
                  Session ID: 1
              **Connection IDs: 3151272607,31512726078,3151272609
            Connection Count: 3**
Incoming Data LIF IP Address: 10.2.1.2
      Workstation IP address: 10.1.1.3
    Authentication Mechanism: NTLMv2
                Windows User: DOMAIN\administrator
                   UNIX User: pcuser
                 Open Shares: 1
                  Open Files: 0
                  Open Other: 0
              Connected Time: 6m 22s
                   Idle Time: 5m 42s
            Protocol Version: SMB3
      Continuously Available: No
           Is Session Signed: false
       User Authenticated as: domain-user
                NetBIOS Name: -
       SMB Encryption Status: Unencrypted
----
xref:display-open-files-task.adoc[열려 있는 SMB 파일에 대한 정보 표시]
