---
permalink: smb-admin/dynamic-home-directories-concept.html 
sidebar: sidebar 
keywords: ontap, home, directories, directory, configure, smb, share, map, base, connect, set, variable, creating, create, separate, share, user, define, home, relationship, entry, point, svm, how ontap enables dynamic home directories 
summary: 'ONTAP 홈 디렉터리를 사용하면 연결된 사용자와 변수 집합을 기반으로 서로 다른 디렉터리에 매핑되는 SMB 공유를 구성할 수 있습니다. 각 사용자에 대해 별도의 공유를 생성하는 대신 몇 가지 홈 디렉토리 매개 변수를 사용하여 하나의 공유를 구성하여 진입점(공유)과 홈 디렉토리(SVM의 디렉토리) 간의 사용자 관계를 정의할 수 있습니다.' 
---
= ONTAP에서 동적 홈 디렉터리를 활성화하는 방법
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 홈 디렉터리를 사용하면 연결된 사용자와 변수 집합을 기반으로 서로 다른 디렉터리에 매핑되는 SMB 공유를 구성할 수 있습니다. 각 사용자에 대해 별도의 공유를 생성하는 대신 몇 가지 홈 디렉토리 매개 변수를 사용하여 하나의 공유를 구성하여 진입점(공유)과 홈 디렉토리(SVM의 디렉토리) 간의 사용자 관계를 정의할 수 있습니다.

게스트 사용자로 로그인한 사용자는 홈 디렉토리가 없으며 다른 사용자의 홈 디렉토리에 액세스할 수 없습니다. 사용자가 디렉토리에 매핑되는 방식을 결정하는 변수는 네 가지입니다.

* * 공유 이름 *
+
사용자가 연결하는 공유의 이름입니다. 이 공유에 대한 홈 디렉토리 속성을 설정해야 합니다.

+
공유 이름에는 다음 동적 이름을 사용할 수 있습니다.

+
** '%w'(사용자의 Windows 사용자 이름)
** '%d'(사용자의 Windows 도메인 이름)
** '%u'(사용자가 매핑한 UNIX 사용자 이름)공유 이름을 모든 홈 디렉토리에 고유하도록 하려면 공유 이름에 '%w' 또는 '%u' 변수가 포함되어야 합니다. 공유 이름에는 "%d"와 "%w" 변수(예: "%d"/"%w")가 모두 포함될 수 있으며, 공유 이름에는 정적 부분과 변수 부분(예: home_""%w")이 포함될 수 있습니다.


* * 공유 경로 *
+
이 경로는 공유에 의해 정의되고 공유 이름 중 하나와 연관되며, SVM의 루트에서 사용자의 전체 홈 디렉토리 경로를 생성하기 위해 각 검색 경로에 추가됩니다. 정적(예: "home"), 동적(예: "%w") 또는 두 가지 조합(예: "eng/%w")일 수 있습니다.

* * 검색 경로 *
+
ONTAP에서 홈 디렉토리를 검색하도록 지정하는 SVM 루트의 절대 경로 세트입니다. 'vserver cifs home-directory search-path add' 명령을 사용하여 하나 이상의 검색 경로를 지정할 수 있습니다. 여러 개의 검색 경로를 지정하면 ONTAP는 유효한 경로를 찾을 때까지 지정된 순서대로 경로를 시도합니다.

* * 디렉토리 *
+
사용자를 위해 생성한 사용자의 홈 디렉토리입니다. 디렉터리 이름은 일반적으로 사용자의 이름입니다. 검색 경로로 정의된 디렉토리 중 하나에 홈 디렉토리를 생성해야 합니다.



예를 들어, 다음 설정을 고려합니다.

* 사용자: John Smith
* 사용자 도메인: Acme
* 사용자 이름: jsmith
* SVM 이름: vs1
* 홈 디렉토리 공유 이름 #1: home_"%w" - 공유 경로: "%w"
* 홈 디렉토리 공유 이름 #2:"%w" - 공유 경로: "%d/%w"
* 검색 경로 #1:'/vol0home/home'
* 검색 경로 #2:'/vol1home/home'
* 검색 경로 #3:'/vol2home/home'
* 홈 디렉토리: `/vol1home/home/jsmith'


시나리오 1: 사용자가 '\\VS1\home_jsmith'에 연결합니다. 첫 번째 홈 디렉토리 공유 이름과 일치하고 상대 경로 jsmith를 생성합니다. ONTAP는 이제 각 검색 경로를 순서대로 확인하여 jsmith라는 디렉토리를 검색합니다.

* '/vol0home/home/jsmith'가 존재하지 않아 2번 검색경로로 이동함.
* '/vol1home/home/jsmith'가 존재하므로 검색 경로 #3이 확인되지 않고 사용자가 홈 디렉토리에 연결되어 있습니다.


시나리오 2: 사용자가 '\\VS1\jsmith'에 연결합니다. 두 번째 홈 디렉토리 공유 이름과 일치하고 상대 경로 Acme/jsmith를 생성합니다. ONTAP는 이제 각 검색 경로를 순서대로 확인하여 "Acme/jsmith"라는 디렉토리를 검색합니다.

* '/vol0home/home/acme/jsmith'가 존재하지 않고 검색 경로 #2로 이동합니다.
* '/vol1home/home/acme/jsmith'가 존재하지 않고 검색 경로 #3으로 이동합니다.
* '/vol2home/home/acme/jsmith'가 존재하지 않아 홈 디렉토리가 존재하지 않아 연결이 실패합니다.

