---
permalink: smb-admin/enable-disable-export-policies-task.html 
sidebar: sidebar 
keywords: enable, disable, export, policies, policy, smb, access, storage, virtual, machine, svm, control, resource, enable or disable export policies for smb access 
summary: 'SVM(스토리지 가상 머신)에서 SMB 액세스에 대한 엑스포트 정책을 설정하거나 해제할 수 있습니다. 내보내기 정책을 사용하여 리소스에 대한 SMB 액세스를 제어하는 것은 선택 사항입니다.' 
---
= SMB 액세스에 대한 엑스포트 정책을 설정하거나 해제합니다
:icons: font
:imagesdir: ../media/


[role="lead"]
SVM(스토리지 가상 머신)에서 SMB 액세스에 대한 엑스포트 정책을 설정하거나 해제할 수 있습니다. 내보내기 정책을 사용하여 리소스에 대한 SMB 액세스를 제어하는 것은 선택 사항입니다.

다음은 SMB에 대한 엑스포트 정책을 설정하기 위한 요구 사항입니다.

* 클라이언트에 대한 내보내기 규칙을 만들기 전에 클라이언트가 DNS에 ""PTR"" 레코드를 가지고 있어야 합니다.
* SVM이 NFS 클라이언트에 대한 액세스를 제공하고 NFS 액세스에 사용할 호스트 이름이 CIFS 서버 이름과 다른 경우 호스트 이름에 대한 ""a" 및 ""PTR"" 레코드 세트가 추가로 필요합니다.


SVM에서 새 CIFS 서버를 설정할 때 SMB 액세스에 대한 엑스포트 정책을 사용하는 것은 기본적으로 해제되어 있습니다. 인증 프로토콜 또는 클라이언트 IP 주소 또는 호스트 이름을 기반으로 액세스를 제어하려는 경우 SMB 액세스에 대한 엑스포트 정책을 설정할 수 있습니다. 언제든지 SMB 액세스에 대한 엑스포트 정책을 설정하거나 해제할 수 있습니다.

.단계
. 권한 수준을 Advanced:'Set-Privilege advanced'로 설정합니다
. 엑스포트 정책 활성화 또는 비활성화:
+
** 내보내기 정책 활성화: 'vserver cifs options modify -vserver_vserver_name_-is-exportpolicy -enabled true'
** 엑스포트 정책 비활성화: 'vserver cifs options modify -vserver_vserver_name_-is-exportpolicy -enabled false


. admin 권한 수준으로 복귀:'et-Privilege admin'입니다


다음 예에서는 엑스포트 정책을 사용하여 SVM VS1 기반 리소스에 대한 SMB 클라이언트 액세스를 제어할 수 있습니다.

[listing]
----
cluster1::> set -privilege advanced
Warning: These advanced commands are potentially dangerous; use them
only when directed to do so by technical support personnel.
Do you wish to continue? (y or n): y

cluster1::*> vserver cifs options modify -vserver vs1 -is-exportpolicy-enabled true

cluster1::*> set -privilege admin
----