---
permalink: smb-admin/enable-disable-password-complexity-local-users-task.html 
sidebar: sidebar 
keywords: password, complex, enhance, security, local, smb, user, storage, virtual, machine, svm, reenable, enable, disable, enable or disable required password complexity for local smb users 
summary: '필수 비밀번호 복잡성은 스토리지 가상 시스템(SVM)의 로컬 SMB 사용자를 위해 향상된 보안을 제공합니다. 필요한 암호 복잡성 기능은 기본적으로 활성화되어 있습니다. 이 기능을 사용하지 않도록 설정하고 언제든지 다시 사용하도록 설정할 수 있습니다.' 
---
= 로컬 SMB 사용자에 대해 필요한 암호 복잡성을 설정하거나 해제합니다
:icons: font
:imagesdir: ../media/


[role="lead"]
필수 비밀번호 복잡성은 스토리지 가상 시스템(SVM)의 로컬 SMB 사용자를 위해 향상된 보안을 제공합니다. 필요한 암호 복잡성 기능은 기본적으로 활성화되어 있습니다. 이 기능을 사용하지 않도록 설정하고 언제든지 다시 사용하도록 설정할 수 있습니다.

CIFS 서버에서 로컬 사용자, 로컬 그룹 및 로컬 사용자 인증을 설정해야 합니다.

[NOTE]
.이 작업에 대해
====
일부 옵션이 유효하지 않으므로 워크그룹 모드에서 CIFS 서버에 대해 "vserver cifs security modify" 명령을 사용하면 안 됩니다.

====
.단계
. 다음 작업 중 하나를 수행합니다.
+
|===
| 로컬 SMB 사용자에 대한 암호 복잡성에 필요한 경우... | 명령 입력... 


 a| 
활성화됨
 a| 
'vserver cifs security modify -vserver_vserver_name_-is-password-Complexity-required true'



 a| 
사용 안 함
 a| 
'vserver cifs security modify -vserver_vserver_name_-is-password-Complexity-required false'

|===
. 필요한 암호 복잡성에 대한 보안 설정을 확인합니다. 'vserver cifs security show -vserver_vserver_name_'


다음 예에서는 SVM VS1 용 로컬 SMB 사용자에 대해 필요한 암호 복잡성이 활성화된 것을 보여 줍니다.

[listing]
----
cluster1::> vserver cifs security modify -vserver vs1 -is-password-complexity-required true

cluster1::> vserver cifs security show -vserver vs1 -fields is-password-complexity-required
vserver is-password-complexity-required
------- -------------------------------
vs1     true
----
xref:display-server-security-settings-task.adoc[CIFS 서버 보안 설정에 대한 정보를 표시합니다]

xref:local-users-groups-authentication-authorization-concept.adoc[로컬 사용자 및 그룹을 인증 및 인증에 사용합니다]

xref:requirements-local-user-passwords-concept.adoc[로컬 사용자 암호 요구 사항]

xref:change-local-user-account-passwords-task.adoc[로컬 사용자 계정 암호 변경]
