---
permalink: smb-admin/enable-disable-multidomain-name-mapping-searches-task.html 
sidebar: sidebar 
keywords: multidomain, name, mapping, search, wild, card, domain, portion, windows, configure, configuring, unix, user, bidirectional, enable, disable, enable or disable multidomain name mapping searches 
summary: '다중 도메인 이름 매핑 검색을 사용하면 UNIX 사용자를 Windows 사용자 이름 매핑에 구성할 때 Windows 이름의 도메인 부분에서 와일드 카드(*)를 사용할 수 있습니다. 이름의 도메인 부분에서 와일드카드(*)를 사용하면 ONTAP에서 CIFS 서버의 컴퓨터 계정이 포함된 도메인과 양방향 트러스트가 있는 모든 도메인을 검색할 수 있습니다.' 
---
= 다중 도메인 이름 매핑 검색을 사용하거나 사용하지 않도록 설정합니다
:icons: font
:imagesdir: ../media/


[role="lead"]
다중 도메인 이름 매핑 검색을 사용하면 UNIX 사용자를 Windows 사용자 이름 매핑에 구성할 때 Windows 이름의 도메인 부분에서 와일드 카드(\ *)를 사용할 수 있습니다. 이름의 도메인 부분에서 와일드카드(*)를 사용하면 ONTAP에서 CIFS 서버의 컴퓨터 계정이 포함된 도메인과 양방향 트러스트가 있는 모든 도메인을 검색할 수 있습니다.

양방향으로 신뢰할 수 있는 모든 도메인을 검색하는 대신 선호하는 신뢰할 수 있는 도메인 목록을 구성할 수 있습니다. 선호하는 신뢰할 수 있는 도메인 목록이 구성되면 ONTAP는 검색된 양방향으로 신뢰할 수 있는 도메인 대신 선호하는 신뢰할 수 있는 도메인 목록을 사용하여 다중 도메인 이름 매핑 검색을 수행합니다.

* 다중 도메인 이름 매핑 검색은 기본적으로 사용하도록 설정됩니다.
* 이 옵션은 고급 권한 수준에서 사용할 수 있습니다.


.단계
. 권한 수준을 Advanced:'Set-Privilege advanced'로 설정합니다
. 다음 작업 중 하나를 수행합니다.
+
|===
| 다중 도메인 이름 매핑 검색을 사용하려는 경우... | 명령 입력... 


 a| 
활성화됨
 a| 
'vserver cifs options modify -vserver_vserver_name_-is-trusted-domain-enum-search-enabled true'



 a| 
사용 안 함
 a| 
'vserver cifs options modify -vserver_vserver_name_-is-trusted-domain-enum-search-enabled false'

|===
. admin 권한 수준으로 복귀:'et-Privilege admin'입니다


xref:server-options-reference.adoc[사용 가능한 SMB 서버 옵션]
