---
permalink: smb-admin/enable-disable-oplocks-existing-shares-task.html 
sidebar: sidebar 
keywords: oplock, enable, smb, share, storage, virtual, machine, svm, default, circumstance, disable, alternative, enable or disable oplocks on existing smb shares 
summary: 'oplocks는 기본적으로 스토리지 가상 시스템(SVM)의 SMB 공유에 설정됩니다. 경우에 따라 oplocks를 해제할 수도 있습니다. 이전에 공유에서 oplocks를 해제한 경우에는 oplocks를 다시 설정할 수도 있습니다.' 
---
= 기존 SMB 공유에서 oplocks를 설정하거나 해제합니다
:icons: font
:imagesdir: ../media/


[role="lead"]
oplocks는 기본적으로 스토리지 가상 시스템(SVM)의 SMB 공유에 설정됩니다. 경우에 따라 oplocks를 해제할 수도 있습니다. 이전에 공유에서 oplocks를 해제한 경우에는 oplocks를 다시 설정할 수도 있습니다.

공유가 포함된 볼륨에 oplocks가 설정되어 있지만 해당 공유에 대한 oplock 공유 속성이 비활성화되어 있으면 해당 공유에 대해 oplocks가 비활성화됩니다. 공유에 oplocks를 사용하지 않도록 설정하면 볼륨에서 oplocks를 설정하는 것이 우선합니다. 공유에서 oplocks를 비활성화하면 임시 oplocks와 리스 oplocks가 모두 비활성화됩니다. 언제든지 기존 공유에 oplocks를 설정하거나 해제할 수 있습니다.

.단계
. 해당 작업을 수행합니다.
+
|===
| 원하는 작업 | 그러면... 


 a| 
기존 공유를 수정하여 공유에 oplocks를 설정합니다
 a| 
'vserver cifs share properties add -vserver_vserver_name_-share-name share_name-share-properties oplocks' 명령을 입력합니다

[NOTE]
====
쉼표로 구분된 목록을 사용하여 추가할 추가 공유 속성을 지정할 수 있습니다.

====
새로 추가된 속성은 기존 공유 속성 목록에 추가됩니다. 이전에 지정한 공유 속성은 그대로 유지됩니다.



 a| 
기존 공유를 수정하여 공유에 oplocks를 사용하지 않도록 설정합니다
 a| 
'vserver cifs share properties remove-vserver_vserver_name_-share-name_share_name_-share-properties oplocks' 명령을 입력합니다

[NOTE]
====
쉼표로 구분된 목록을 사용하여 제거할 추가 공유 속성을 지정할 수 있습니다.

====
제거한 공유 속성은 기존 공유 속성 목록에서 삭제되지만 이전에 구성한 공유 속성은 제거하지 않습니다.

|===


다음 명령을 실행하면 스토리지 가상 시스템(SVM, 이전 명칭 Vserver) VS1 에서 ""Engineering""이라는 이름의 공유에 대한 oplocks가 설정됩니다.

[listing]
----
cluster1::> vserver cifs share properties add -vserver vs1 -share-name Engineering -share-properties oplocks

cluster1::> vserver cifs share properties show
Vserver          Share            Properties
---------------- ---------------- -----------------
vs1              Engineering      oplocks
                                  browsable
                                  changenotify
                                  showsnapshot
----
다음 명령을 실행하면 SVM VS1 에서 ""Engineering""이라는 이름의 공유에 대한 oplocks가 해제됩니다.

[listing]
----
cluster1::> vserver cifs share properties remove -vserver vs1 -share-name Engineering -share-properties oplocks

cluster1::> vserver cifs share properties show
Vserver          Share            Properties
---------------- ---------------- -----------------
vs1              Engineering      browsable
                                  changenotify
                                  showsnapshot
----
xref:enable-disable-oplocks-when-creating-shares-task.adoc[SMB 공유를 생성할 때 oplocks를 설정하거나 해제합니다]

xref:monitor-oplock-status-task.adoc[oplock 상태 모니터링]

xref:add-remove-share-properties-eexisting-share-task.adoc[기존 SMB 공유에서 공유 속성 추가 또는 제거]
