---
permalink: smb-admin/enable-branchcache-existing-share-task.html 
sidebar: sidebar 
keywords: enable, branchcache, exist, smb, share, add, share, property, exist, list, enable branchcache on an existing smb share 
summary: 기존 SMB 공유에서 BranchCache 공유 속성을 기존 공유 속성 목록에 추가하여 BranchCache를 설정할 수 있습니다. 
---
= 기존 SMB 공유에서 BranchCache를 사용하도록 설정합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
기존 공유 속성 목록에 'BranchCache' 공유 속성을 추가하여 기존 SMB 공유에서 BranchCache를 사용하도록 설정할 수 있습니다.

.이 작업에 대해
* SMB 공유에 BranchCache가 설정되어 있으면 공유에 수동 캐싱으로 설정된 오프라인 파일 구성이 있어야 합니다.
+
기존 공유의 오프라인 파일 설정이 수동 캐싱으로 설정되어 있지 않으면 공유를 수정하여 구성해야 합니다.

* BranchCache가 SVM(스토리지 가상 시스템)에서 구성 및 설정되지 않은 경우에도 공유에 "BranchCache" 속성을 설정할 수 있습니다.
+
그러나 공유 폴더에 캐시된 콘텐츠가 제공되도록 하려면 SVM에서 BranchCache를 구성하고 사용하도록 설정해야 합니다.

* 공유에 "BranchCache" 공유 속성을 추가하면 기존 공유 설정과 공유 속성이 유지됩니다.
+
BranchCache 공유 속성이 기존 공유 속성 목록에 추가됩니다. 'vserver cifs share properties add' 명령 사용에 대한 자세한 내용은 man 페이지를 참조하십시오.



.단계
. 필요한 경우 수동 캐싱에 대한 오프라인 파일 공유 설정을 구성합니다.
+
.. 'vserver cifs share show' 명령을 사용하여 오프라인 파일 공유 설정을 확인합니다.
.. 오프라인 파일 공유 설정이 manual로 설정되어 있지 않으면 필요한 값('vserver cifs share modify -vserver vserver_name -share-name share-name share_name -offline-files manual')으로 변경합니다


. 기존 SMB 공유에서 BranchCache를 사용하도록 설정합니다. 'vserver cifs share properties add-vserver vserver_name -share-name share_name-share-properties BranchCache'
. SMB 공유에서 BranchCache 공유 속성이 설정되어 있는지 확인합니다. 'vserver cifs share show -vserver vserver_name -share-name share_name'


다음 명령을 실행하면 SVM VS1 에서 " data2 " 라는 기존 SMB 공유에서 "/data2 " 경로를 사용하여 BranchCache를 사용할 수 있습니다.

[listing]
----
cluster1::> vserver cifs share show -vserver vs1 -share-name data2

                      Vserver: vs1
                        Share: data2
     CIFS Server NetBIOS Name: VS1
                         Path: /data2
             Share Properties: oplocks
                               browsable
                               changenotify
                               showsnapshot
           Symlink Properties: -
      File Mode Creation Mask: -
 Directory Mode Creation Mask: -
                Share Comment: -
                    Share ACL: Everyone / Full Control
File Attribute Cache Lifetime: 10s
                  Volume Name: -
                Offline Files: manual
Vscan File-Operations Profile: standard

cluster1::> vserver cifs share properties add  -vserver vs1 -share-name data2 -share-properties branchcache

cluster1::> vserver cifs share show -vserver vs1 -share-name data2

                      Vserver: vs1
                        Share: data2
     CIFS Server NetBIOS Name: VS1
                         Path: /data2
             Share Properties: oplocks
                               browsable
                               showsnapshot
                               changenotify
                               branchcache
           Symlink Properties: -
      File Mode Creation Mask: -
 Directory Mode Creation Mask: -
                Share Comment: -
                    Share ACL: Everyone / Full Control
File Attribute Cache Lifetime: 10s
                  Volume Name: -
                Offline Files: manual
Vscan File-Operations Profile: standard
----
xref:add-remove-share-properties-eexisting-share-task.adoc[기존 SMB 공유에서 공유 속성 추가 또는 제거]

xref:disable-branchcache-single-share-task.adoc[단일 SMB 공유에서 BranchCache를 사용하지 않도록 설정합니다]
