---
permalink: smb-admin/examples-export-policy-rules-reference.html 
sidebar: sidebar 
keywords: create, export, policy, rule, restrict, allow, access, smb, svm, enable, examples of export policy rules that restrict or allow access over smb 
summary: 이 예에서는 SMB 액세스에 대한 엑스포트 정책이 설정된 SVM에서 SMB를 통한 액세스를 제한 또는 허용하는 엑스포트 정책 규칙을 생성하는 방법을 보여줍니다. 
---
= SMB를 통한 액세스를 제한하거나 허용하는 엑스포트 정책 규칙의 예
:icons: font
:imagesdir: ../media/


[role="lead"]
이 예에서는 SMB 액세스에 대한 엑스포트 정책이 설정된 SVM에서 SMB를 통한 액세스를 제한 또는 허용하는 엑스포트 정책 규칙을 생성하는 방법을 보여줍니다.

SMB 액세스에 대한 엑스포트 정책은 기본적으로 비활성화되어 있습니다. SMB 액세스에 대한 엑스포트 정책을 설정한 경우에만 SMB 액세스를 제한하거나 허용하는 엑스포트 정책 규칙을 구성해야 합니다.



== SMB 액세스에 대한 엑스포트 규칙입니다

다음 명령을 실행하면 다음 구성을 가진 ""VS1"" SVM에 대한 엑스포트 규칙이 생성됩니다.

* 정책 이름: cifs1
* 색인 번호: 1
* 클라이언트 일치: 192.168.1.0/24 네트워크의 클라이언트만 일치시킵니다
* 프로토콜: SMB 액세스만 지원합니다
* 읽기 전용 액세스: NTLM 또는 Kerberos 인증을 사용하는 클라이언트에 대한 액세스
* 읽기-쓰기 액세스: Kerberos 인증을 사용하는 클라이언트에 대한 액세스


[listing]
----
cluster1::> vserver export-policy rule create -vserver vs1 -policyname cifs1 ‑ruleindex 1 -protocol cifs -clientmatch 192.168.1.0/255.255.255.0 -rorule krb5,ntlm -rwrule krb5
----


== SMB 및 NFS 액세스에 대한 엑스포트 규칙

다음 명령을 실행하면 다음 구성을 가진 ""VS1"" SVM에 대한 엑스포트 규칙이 생성됩니다.

* 정책 이름: cifsnfs1
* 색인 번호: 2
* 클라이언트 일치: 모든 클라이언트를 일치시킵니다
* 프로토콜: SMB 및 NFS 액세스
* 읽기 전용 액세스: 모든 클라이언트에 대해
* 읽기-쓰기 액세스: Kerberos(NFS 및 SMB) 또는 NTLM 인증(SMB)을 사용하는 클라이언트에 대한 액세스
* UNIX 사용자 ID 0(영)에 대한 매핑: 사용자 ID 65534에 매핑됨(일반적으로 사용자 이름에 매핑되지 않음)
* SUID 및 SGID 액세스: 허용


[listing]
----
cluster1::> vserver export-policy rule create -vserver vs1 -policyname cifsnfs1 ‑ruleindex 2 -protocol cifs,nfs -clientmatch 0.0.0.0/0 -rorule any -rwrule krb5,ntlm -anon 65534 -allow-suid true
----


== NTLM을 사용한 SMB 액세스에 대한 내보내기 규칙입니다

다음 명령을 실행하면 다음 구성을 가진 ""VS1"" SVM에 대한 엑스포트 규칙이 생성됩니다.

* 정책 이름: ntlm1
* 색인 번호: 1
* 클라이언트 일치: 모든 클라이언트를 일치시킵니다
* 프로토콜: SMB 액세스만 지원합니다
* 읽기 전용 액세스: NTLM을 사용하는 클라이언트에만 해당됩니다
* 읽기-쓰기 액세스: NTLM을 사용하는 클라이언트에만 해당됩니다


[NOTE]
====
NTLM 전용 액세스에 대해 읽기 전용 옵션 또는 읽기/쓰기 옵션을 구성하는 경우 클라이언트 일치 옵션에서 IP 주소 기반 항목을 사용해야 합니다. 그렇지 않으면 "액세스 거부" 오류가 발생합니다. 이는 ONTAP가 호스트 이름을 사용하여 클라이언트의 액세스 권한을 확인할 때 Kerberos SPN(서비스 사용자 이름)을 사용하기 때문입니다. NTLM 인증은 SPN 이름을 지원하지 않습니다.

====
[listing]
----
cluster1::> vserver export-policy rule create -vserver vs1 -policyname ntlm1 ‑ruleindex 1 -protocol cifs -clientmatch 0.0.0.0/0 -rorule ntlm -rwrule ntlm
----