---
permalink: smb-admin/export-policies-access-concept.html 
sidebar: sidebar 
keywords: export, policies, policy, smb, access, enable, cifs, server, control, svm, volume, client, data, associate, how export policies are used with smb access 
summary: SMB 서버에서 SMB 액세스에 대한 엑스포트 정책을 사용하는 경우, SMB 클라이언트에서 SVM 볼륨에 대한 액세스를 제어할 때 엑스포트 정책이 사용됩니다. 데이터에 액세스하려면 SMB 액세스를 허용하는 엑스포트 정책을 생성한 다음, SMB 공유를 포함하는 볼륨과 정책을 연결할 수 있습니다. 
---
= SMB 액세스에 엑스포트 정책을 사용하는 방법
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SMB 서버에서 SMB 액세스에 대한 엑스포트 정책을 사용하는 경우, SMB 클라이언트에서 SVM 볼륨에 대한 액세스를 제어할 때 엑스포트 정책이 사용됩니다. 데이터에 액세스하려면 SMB 액세스를 허용하는 엑스포트 정책을 생성한 다음, SMB 공유를 포함하는 볼륨과 정책을 연결할 수 있습니다.

내보내기 정책에는 데이터에 대한 액세스가 허용되는 클라이언트와 읽기 전용 및 읽기-쓰기 액세스에 지원되는 인증 프로토콜을 지정하는 하나 이상의 규칙이 적용됩니다. 모든 클라이언트, 클라이언트 서브넷 또는 특정 클라이언트에 대한 SMB 액세스를 허용하고 Kerberos 인증, NTLM 인증 또는 데이터에 대한 읽기 전용 및 읽기-쓰기 액세스를 결정할 때 Kerberos 및 NTLM 인증을 사용하여 인증을 허용하도록 내보내기 정책을 구성할 수 있습니다.

내보내기 정책에 적용된 모든 내보내기 규칙을 처리한 후 ONTAP는 클라이언트에 액세스 권한이 부여되었는지 여부와 허용되는 액세스 수준을 결정할 수 있습니다. 내보내기 규칙은 Windows 사용자 및 그룹이 아니라 클라이언트 컴퓨터에 적용됩니다. 내보내기 규칙은 Windows 사용자 및 그룹 기반 인증 및 권한 부여를 대체하지 않습니다. 내보내기 규칙은 공유 및 파일 액세스 권한 외에도 액세스 보안의 또 다른 계층을 제공합니다.

볼륨에 대한 클라이언트 액세스를 구성하기 위해 각 볼륨에 정확히 하나의 엑스포트 정책을 연결합니다. 각 SVM에는 여러 엑스포트 정책이 포함될 수 있습니다. 따라서 여러 볼륨이 있는 SVM에 대해 다음을 수행할 수 있습니다.

* SVM의 각 볼륨에 서로 다른 엑스포트 정책을 지정하여 개별 클라이언트 액세스 제어를 SVM의 각 볼륨에 할당
* 각 볼륨에 대해 새로운 엑스포트 정책을 생성할 필요 없이 동일한 클라이언트 액세스 제어를 위해 SVM의 여러 볼륨에 동일한 엑스포트 정책을 할당합니다.


각 SVM에는 규칙이 없는 "기본값"이라는 엑스포트 정책이 하나 이상 있습니다. 이 엑스포트 정책을 삭제할 수는 없지만 이름을 바꾸거나 수정할 수는 있습니다. 기본적으로 SVM의 각 볼륨은 기본 엑스포트 정책과 연결됩니다. SVM에서 SMB 액세스에 대한 엑스포트 정책을 사용하지 않도록 설정한 경우, "기본값" 엑스포트 정책은 SMB 액세스에 영향을 미치지 않습니다.

NFS 및 SMB 호스트 모두에 대한 액세스를 제공하는 규칙을 구성하고 이 규칙을 엑스포트 정책에 연결할 수 있습니다. 그런 다음, NFS 및 SMB 호스트 모두에 액세스해야 하는 데이터가 포함된 볼륨에 연결할 수 있습니다. 또는 SMB 클라이언트만 액세스해야 하는 일부 볼륨이 있는 경우, SMB 프로토콜을 사용해서만 액세스를 허용하고 읽기 전용 및 쓰기 액세스에 Kerberos 또는 NTLM(또는 둘 다)만 사용하는 규칙을 사용하여 엑스포트 정책을 구성할 수 있습니다. 그러면 엑스포트 정책이 SMB 액세스만 원하는 볼륨에 연결됩니다.

SMB에 대한 엑스포트 정책이 설정되어 있고 클라이언트가 해당 엑스포트 정책에서 허용하지 않는 액세스 요청을 하는 경우, 요청이 실패하고 권한 거부 메시지가 표시됩니다. 클라이언트가 볼륨의 엑스포트 정책에 있는 규칙과 일치하지 않으면 액세스가 거부됩니다. 내보내기 정책이 비어 있으면 모든 액세스가 암시적으로 거부됩니다. 공유 및 파일 권한이 액세스를 허용하는 경우에도 마찬가지입니다. 즉, SMB 공유가 포함된 볼륨에서 다음을 최소한으로 허용하도록 엑스포트 정책을 구성해야 합니다.

* 모든 클라이언트 또는 적절한 클라이언트 하위 집합에 대한 액세스를 허용합니다
* SMB를 통한 액세스를 허용합니다
* Kerberos 또는 NTLM 인증(또는 둘 다)을 사용하여 적절한 읽기 전용 및 쓰기 액세스 허용


에 대해 자세히 알아보십시오 link:../nfs-config/export-policies-concept.html["엑스포트 정책 구성 및 관리"].
