---
permalink: smb-admin/improve-microsoft-remote-copy-performance-concept.html 
sidebar: sidebar 
keywords: microsoft, offload, data, transfer, odx, copy, offload, enable, direct, compatible, computer, improve microsoft remote copy performance 
summary: '복사 오프로드로 알려진 Microsoft ODX(Offloaded Data Transfer)를 사용하면 호스트 컴퓨터를 통해 데이터를 전송하지 않고도 호환되는 스토리지 장치 내부 또는 간에 데이터를 직접 전송할 수 있습니다.' 
---
= Microsoft 원격 복제 성능 개요 개선
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Microsoft ODX(Offloaded Data Transfer)는 _copy offload_라고도 하며 호스트 컴퓨터를 통해 데이터를 전송하지 않고도 호환되는 스토리지 장치 내부 또는 간에 데이터를 직접 전송할 수 있습니다.

ONTAP은 SMB 및 SAN 프로토콜을 모두 지원하는 ODX를 지원합니다. 소스는 CIFS 서버 또는 LUN일 수 있으며 대상은 CIFS 서버 또는 LUN일 수 있습니다.

ODX가 아닌 파일을 전송하면 소스에서 데이터를 읽어 네트워크를 통해 클라이언트 컴퓨터로 전송합니다. 클라이언트 컴퓨터는 네트워크를 통해 데이터를 대상으로 다시 전송합니다. 요약하면 클라이언트 컴퓨터는 소스에서 데이터를 읽고 대상에 씁니다. ODX 파일 전송을 사용하면 데이터가 소스에서 타겟으로 직접 복사됩니다.

오프로드 복사본은 소스 및 타겟 스토리지 간에 직접 수행되므로 성능이 크게 향상됩니다. 소스 및 대상 간의 복제 시간 단축, 클라이언트의 리소스 활용률(CPU, 메모리) 감소, 네트워크 I/O 대역폭 사용률 감소 등의 성능 이점을 얻을 수 있습니다.

SMB 환경의 경우 이 기능은 클라이언트와 스토리지 서버가 모두 SMB 3.0 및 ODX 기능을 지원하는 경우에만 사용할 수 있습니다. SAN 환경의 경우 이 기능은 클라이언트와 스토리지 서버가 ODX 기능을 모두 지원하는 경우에만 사용할 수 있습니다. ODX를 지원하고 ODX를 사용하는 클라이언트 컴퓨터는 파일을 이동하거나 복사할 때 오프로드된 파일 전송을 자동으로 투명하게 사용합니다. ODX는 Windows 탐색기를 통해 파일을 끌어서 놓을지, 명령줄 파일 복사 명령을 사용하는지, 클라이언트 애플리케이션이 파일 복사 요청을 시작하는지 여부와 관계없이 사용됩니다.

.관련 정보
xref:improve-client-response-node-referrals-concept.adoc[자동 위치를 사용하여 SMB 자동 노드 조회를 제공하여 클라이언트 응답 시간을 단축합니다]

link:../smb-hyper-v-sql/index.html["Microsoft Hyper-V 및 SQL Server를 위한 SMB 구성"]
