---
permalink: smb-admin/improve-client-response-node-referrals-concept.html 
sidebar: sidebar 
keywords: auto, location, smb, automatic, node, referral, increase, client, performance, storage, virtual, machine, svm, request, host, response, improve, improve client response time by providing smb automatic node referrals with auto location 
summary: '자동 위치에서는 SMB 자동 노드 조회를 사용하여 스토리지 가상 시스템(SVM)에서 SMB 클라이언트 성능을 높입니다. 자동 노드 조수는 요청 클라이언트를 데이터가 상주하는 볼륨을 호스팅하는 노드 SVM의 LIF로 자동으로 리디렉션하여 클라이언트 응답 시간을 향상할 수 있습니다.' 
---
= 자동 위치 개요를 통해 SMB 자동 노드 조회를 제공하여 클라이언트 응답 시간을 단축합니다
:icons: font
:imagesdir: ../media/


[role="lead"]
자동 위치에서는 SMB 자동 노드 조회를 사용하여 스토리지 가상 시스템(SVM)에서 SMB 클라이언트 성능을 높입니다. 자동 노드 조수는 요청 클라이언트를 데이터가 상주하는 볼륨을 호스팅하는 노드 SVM의 LIF로 자동으로 리디렉션하여 클라이언트 응답 시간을 향상할 수 있습니다.

SMB 클라이언트가 SVM에서 호스팅된 SMB 공유에 연결할 경우, 요청된 데이터를 소유하지 않은 노드에 있는 LIF를 사용하여 연결할 수 있습니다. 클라이언트가 연결된 노드는 클러스터 네트워크를 사용하여 다른 노드가 소유한 데이터에 액세스합니다. SMB 연결이 요청된 데이터를 포함하고 있는 노드에 있는 LIF를 사용하면 클라이언트에서 더 빠른 응답 시간을 경험할 수 있습니다.

* ONTAP는 Microsoft DFS 조회를 사용하여 SMB 클라이언트에 네임스페이스에서 요청된 파일 또는 폴더가 다른 곳에 호스팅된다는 사실을 알리는 이 기능을 제공합니다.
+
노드가 데이터를 포함하는 노드에 SVM LIF가 있다고 판단하면 노드를 전문의에게 의뢰합니다.

* IPv4 및 IPv6 LIF IP 주소에 대해 자동 노드 조회가 지원됩니다.
* 조인은 클라이언트가 연결되는 공유 루트의 위치를 기반으로 합니다.
* SMB 협상 중에 불합격입니다.
+
연결이 설정되기 전에 의뢰합니다. ONTAP가 SMB 클라이언트를 타겟 노드로 참조하면 연결이 연결되고 클라이언트는 해당 시점부터 참조된 LIF 경로를 통해 데이터에 액세스합니다. 이렇게 하면 클라이언트가 데이터에 더 빠르게 액세스할 수 있고 추가 클러스터 통신을 피할 수 있습니다.

+
[NOTE]
====
공유가 여러 연결 지점을 거치는 경우 일부 접합부가 다른 노드에 포함된 볼륨에 연결되는 경우 공유 내의 데이터가 여러 노드로 분산됩니다. ONTAP는 공유의 루트에 대해 로컬인 조회를 제공하므로 ONTAP는 이러한 비 로컬 볼륨에 포함된 데이터를 검색하기 위해 클러스터 네트워크를 사용해야 합니다. 이러한 유형의 네임스페이스 아키텍처를 사용하면 자동 노드 조회가 성능에 큰 이점을 제공하지 않을 수 있습니다.

====


데이터를 호스팅하는 노드에 사용 가능한 LIF가 없는 경우 ONTAP은 클라이언트가 선택한 LIF를 사용하여 연결을 설정합니다. SMB 클라이언트가 파일을 연 후에는 동일한 참조 연결을 통해 계속 파일에 액세스합니다.

어떤 이유로든 CIFS 서버가 조회를 수행할 수 없는 경우 SMB 서비스가 중단되지 않습니다. SMB 연결은 자동 노드 조회가 활성화되지 않은 것처럼 설정됩니다.

xref:improve-microsoft-remote-copy-performance-concept.adoc[Microsoft 원격 복제 성능 향상]
