---
permalink: smb-admin/manage-local-group-membership-task.html 
sidebar: sidebar 
keywords: manage, local, group, membership, add, removing, remove, local, domain, user, domain, group, control, access, place, privilege, associate, manage local group membership 
summary: 로컬 또는 도메인 사용자를 추가 및 제거하거나 도메인 그룹을 추가 및 제거하여 로컬 그룹 구성원 자격을 관리할 수 있습니다. 이 기능은 그룹에 배치된 액세스 제어를 기반으로 데이터에 대한 액세스를 제어하려는 경우 또는 사용자에게 해당 그룹에 연결된 권한을 부여하려는 경우에 유용합니다. 
---
= 로컬 그룹 구성원 자격을 관리합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
로컬 또는 도메인 사용자를 추가 및 제거하거나 도메인 그룹을 추가 및 제거하여 로컬 그룹 구성원 자격을 관리할 수 있습니다. 이 기능은 그룹에 배치된 액세스 제어를 기반으로 데이터에 대한 액세스를 제어하려는 경우 또는 사용자에게 해당 그룹에 연결된 권한을 부여하려는 경우에 유용합니다.

로컬 그룹에 구성원을 추가하기 위한 지침:

* special_everyone_group에 사용자를 추가할 수 없습니다.
* 사용자를 추가하려면 로컬 그룹이 있어야 합니다.
* 사용자를 로컬 그룹에 추가하려면 사용자가 있어야 합니다.
* 로컬 그룹을 다른 로컬 그룹에 추가할 수 없습니다.
* 도메인 사용자 또는 그룹을 로컬 그룹에 추가하려면 Data ONTAP에서 SID에 대한 이름을 확인할 수 있어야 합니다.


로컬 그룹에서 구성원을 제거하는 지침:

* special_everyone_group에서 구성원을 제거할 수 없습니다.
* 구성원을 제거할 그룹이 있어야 합니다.
* ONTAP는 그룹에서 제거하려는 구성원 이름을 해당 SID로 확인할 수 있어야 합니다.


.단계
. 그룹에서 구성원을 추가 또는 제거합니다.
+
|===
| 원하는 작업 | 그런 다음 명령을 사용합니다... 


 a| 
그룹에 구성원을 추가합니다
 a| 
'+vserver cifs users-and-groups local-group add-member-vserver_name_-group-name_group_name_-member-names name[,...]+'지정된 로컬 그룹에 추가할 쉼표로 구분된 로컬 사용자, 도메인 사용자 또는 도메인 그룹의 목록을 지정할 수 있습니다.



 a| 
그룹에서 구성원을 제거합니다
 a| 
'+vserver cifs users-and-groups local-group remove-memers-vserver_name_-group-name_group_name_-member-names name[,...]+'지정된 로컬 그룹에서 제거할 로컬 사용자, 도메인 사용자 또는 도메인 그룹의 쉼표로 구분된 목록을 지정할 수 있습니다.

|===
+
다음 예에서는 SVM VS1 상의 로컬 그룹 "sMB_server\sue"와 도메인 그룹 "AD_DOM\DOM_ENG"를 로컬 그룹 "sMB_server\engineering"에 추가합니다.

+
[listing]
----
cluster1::> vserver cifs users-and-groups local-group add-members -vserver vs1 -group-name SMB_SERVER\engineering -member-names SMB_SERVER\sue,AD_DOMAIN\dom_eng
----
+
다음 예에서는 SVM VS1 로컬 그룹 "sMB_server\sue"와 "sMB_server\james"를 SVM VS1 로컬 그룹 "sMB_server\engineering"에서 제거합니다.

+
[listing]
----
cluster1::> vserver cifs users-and-groups local-group remove-members -vserver vs1 -group-name SMB_SERVER\engineering -member-names SMB_SERVER\sue,SMB_SERVER\james
----


xref:display-members-local-groups-task.adoc[로컬 그룹 구성원에 대한 정보 표시]
