---
permalink: smb-admin/manage-accessibility-users-home-directories-task.html 
sidebar: sidebar 
keywords: 'default, user, home, directory, access, dynamic, name, share, precede, enable, disable, windows, administrator, public, access, manage accessibility to users" home directories' 
summary: '기본적으로 사용자의 홈 디렉토리는 해당 사용자만 액세스할 수 있습니다. 공유의 동적 이름 앞에 물결표({tilde})가 있는 공유의 경우 Windows 관리자 또는 다른 사용자(공용 액세스)가 사용자의 홈 디렉토리에 대한 액세스를 설정하거나 해제할 수 있습니다.' 
---
= 사용자의 홈 디렉터리에 대한 액세스 권한을 관리합니다
:icons: font
:imagesdir: ../media/


[role="lead"]
기본적으로 사용자의 홈 디렉토리는 해당 사용자만 액세스할 수 있습니다. 공유의 동적 이름 앞에 물결표({tilde})가 있는 공유의 경우 Windows 관리자 또는 다른 사용자(공용 액세스)가 사용자의 홈 디렉토리에 대한 액세스를 설정하거나 해제할 수 있습니다.

SVM(스토리지 가상 머신)의 홈 디렉토리 공유는 앞에 물결표({tilde})가 오는 동적 공유 이름으로 구성해야 합니다. 다음 사례는 공유 명명 요구 사항을 보여 줍니다.

|===
| 홈 디렉토리 공유 이름입니다 | 공유에 연결하는 명령의 예 


 a| 
{tilde} %d{tilde} %w
 a| 
'net use * {백슬래시} {백슬래시}IPaddress{백슬래시} {tilde}domain{tilde}user/u:credentials'을 사용하십시오



 a| 
{tilde} %w
 a| 
'net use * {백슬래시} {백슬래시}IPaddress{백슬래시} {tilde}user/u:credentials'를 사용하십시오



 a| 
{tilde}abc{tilde} %w
 a| 
'net use * {백슬래시} {백슬래시}IPaddress{백슬래시}abc{tilde}user/u:credentials'를 사용하십시오

|===
.단계
. 적절한 작업을 수행합니다.
+
|===
| 사용자의 홈 디렉토리에 대한 액세스를 설정하거나 해제하려면... | 다음을 입력하십시오. 


| Windows 관리자 | 'vserver cifs home-directory modify -vserver_vserver_name_-is-home-dirs-access-for-admin-enabled{true{vbar}false}' 기본값은 'true'입니다. 


| 모든 사용자(공용 액세스)  a| 
.. 권한 수준을 advanced:+'et-Privilege advanced로 설정합니다
.. 액세스 설정 또는 해제:'vserver cifs home-directory modify -vserver_vserver_name_-is-home-dirs-access-for-public-enabled{true|false}'+ 기본값은 'false'입니다.
.. 관리자 권한 수준으로 돌아가기: + 'Set-Privilege admin


|===


다음 예에서는 사용자의 홈 디렉토리에 대한 공용 액세스를 활성화합니다. + 'Set-Privilege advanced' + 'vserver cifs home-directory modify -vserver vs1-is-home-dirs-access-for-public-enabled true' + 'Set-Privilege admin'

xref:display-user-home-directory-path-task.adoc[SMB 사용자의 홈 디렉토리 경로에 대한 정보 표시]
