---
permalink: smb-admin/modify-servers-task.html 
sidebar: sidebar 
keywords: move, smb, server, workgroup, active, directory, domain, vserver, cifs, modify, command, modify smb servers 
summary: vserver cifs modify 명령을 사용하여 작업 그룹에서 Active Directory 도메인으로, 작업 그룹에서 다른 작업 그룹으로 또는 Active Directory 도메인에서 작업 그룹으로 SMB 서버를 이동할 수 있습니다. 
---
= SMB 서버를 수정합니다
:icons: font
:imagesdir: ../media/


[role="lead"]
"vserver cifs modify" 명령을 사용하여 작업 그룹에서 Active Directory 도메인으로, 작업 그룹에서 다른 작업 그룹으로 또는 Active Directory 도메인에서 작업 그룹으로 SMB 서버를 이동할 수 있습니다.

SMB 서버 이름 및 관리 상태와 같은 SMB 서버의 다른 속성을 수정할 수도 있습니다. 자세한 내용은 man 페이지를 참조하십시오.

.선택
* 작업 그룹에서 Active Directory 도메인으로 SMB 서버 이동:
+
.. SMB 서버의 관리 상태를 'down'으로 설정합니다.
+
[listing]
----
Cluster1::>vserver cifs modify -vserver vs1 -status-admin down
----
.. 작업 그룹에서 Active Directory 도메인으로 SMB 서버를 이동합니다: ' vsserver cifs modify -vserver_vserver_name_-domain_domain_name_'
+
[listing]
----
Cluster1::>vserver cifs modify -vserver vs1 -domain example.com
----
+
SMB 서버에 대한 Active Directory 컴퓨터 계정을 만들려면 '_example_'.com 도메인 내의 'ou=_example_ou' 컨테이너에 컴퓨터를 추가할 수 있는 충분한 권한이 있는 Windows 계정의 이름과 암호를 제공해야 합니다.

+
ONTAP 9.7부터 AD 관리자는 권한이 있는 Windows 계정에 이름과 암호를 제공하는 대신 keytab 파일에 대한 URI를 제공할 수 있습니다. URI를 받으면 '-keytab-Uri' 매개 변수에 vserver cifs' 명령을 포함하여 포함시키십시오.



* 작업 그룹에서 다른 작업 그룹으로 SMB 서버 이동:
+
.. SMB 서버의 관리 상태를 'down'으로 설정합니다.
+
[listing]
----
Cluster1::>vserver cifs modify -vserver vs1 -status-admin down
----
.. SMB 서버의 워크그룹을 수정합니다. 'vserver cifs modify -vserver_vserver_name_-workgroup_new_workgroup_name_'
+
[listing]
----
Cluster1::>vserver cifs modify -vserver vs1 -workgroup workgroup2
----


* Active Directory 도메인에서 작업 그룹으로 SMB 서버 이동:
+
.. SMB 서버의 관리 상태를 'down'으로 설정합니다.
+
[listing]
----
Cluster1::>vserver cifs modify -vserver vs1 -status-admin down
----
.. SMB 서버를 Active Directory 도메인에서 작업 그룹('vserver cifs modify -vserver_vserver_name_-workgroup_workgroup_name_')으로 이동합니다
+
[listing]
----
cluster1::> vserver cifs modify -vserver vs1 -workgroup workgroup1
----
+
[NOTE]
====
워크그룹 모드로 전환하려면 모든 도메인 기반 기능을 사용하지 않도록 설정하고 지속적으로 사용 가능한 공유, 섀도우 복제본 및 AES를 포함하여 시스템에서 해당 구성을 자동으로 제거해야 합니다. 그러나 "EXAMPLE.COM\userName" 같은 도메인 구성 공유 ACL은 제대로 작동하지 않지만 ONTAP에서는 제거할 수 없습니다. 명령이 완료된 후 외부 툴을 사용하여 가능한 한 빨리 이러한 공유 ACL을 제거합니다. AES가 활성화된 경우 "example.com" 도메인에서 Windows 계정을 비활성화할 수 있는 충분한 권한이 있는 Windows 계정의 이름과 암호를 입력하라는 메시지가 표시될 수 있습니다.

====
+
*** 'vserver cifs modify' 명령의 적절한 매개 변수를 사용하여 다른 속성을 수정합니다.





