---
permalink: smb-admin/modify-local-user-accounts-reference.html 
sidebar: sidebar 
keywords: modify, local, user, account, change, exist, name, description, enable, disable, rename, compromise, administrative, modify local user accounts 
summary: 기존 사용자의 전체 이름 또는 설명을 변경하고 사용자 계정을 활성화 또는 비활성화하려는 경우 로컬 사용자 계정을 수정할 수 있습니다. 사용자 이름이 손상되었거나 관리를 위해 이름 변경이 필요한 경우 로컬 사용자 계정의 이름을 바꿀 수도 있습니다. 
---
= 로컬 사용자 계정을 수정합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
기존 사용자의 전체 이름 또는 설명을 변경하고 사용자 계정을 활성화하거나 비활성화하려면 로컬 사용자 계정을 수정할 수 있습니다. 사용자 이름이 손상되었거나 관리를 위해 이름 변경이 필요한 경우 로컬 사용자 계정의 이름을 바꿀 수도 있습니다.

|===
| 원하는 작업 | 명령 입력... 


 a| 
로컬 사용자의 전체 이름을 수정합니다
 a| 
'vserver cifs users-and-groups local-user modify -vserver_vserver_name_-user-name_user_name_‑full-name text' 전체 이름에 공백이 포함되어 있으면 큰따옴표로 묶어야 합니다.



 a| 
로컬 사용자의 설명을 수정합니다
 a| 
'vserver cifs users-and-groups local-user modify -vserver_vserver_name_-user-name_user_name_‑description text' 설명에 공백이 포함된 경우 큰따옴표로 묶어야 합니다.



 a| 
로컬 사용자 계정을 활성화하거나 비활성화합니다
 a| 
'vserver cifs users-and-groups local-user modify -vserver_vserver_name_-user-name_user_name_-is-account-disabled{true|false}'



 a| 
로컬 사용자 계정의 이름을 바꿉니다
 a| 
'vserver cifs users-and-groups local-user rename-vserver_name_-user-name_user_name_-new-user-name_new_user_name_' 로컬 사용자의 이름을 바꿀 때 새 사용자 이름은 이전 사용자 이름과 동일한 CIFS 서버와 연결된 상태로 유지되어야 합니다.

|===
다음 예에서는 스토리지 가상 머신(SVM, 이전 명칭 Vserver)의 로컬 사용자 "'cifs_server\sue""를 "'cifs_server\sue_new""로 바꿉니다.1

[listing]
----
cluster1::> vserver cifs users-and-groups local-user rename -user-name CIFS_SERVER\sue -new-user-name CIFS_SERVER\sue_new -vserver vs1
----