---
permalink: smb-admin/monitor-oplock-status-task.html 
sidebar: sidebar 
keywords: monitor, display, information, oplock, status, file, state, leasing, lease, determine, manual, monitor oplock status 
summary: oplock 상태에 대한 정보를 모니터링하고 표시할 수 있습니다. 이 정보를 사용하여 oplocks가 있는 파일, oplock 레벨 및 oplock 상태 수준이 무엇인지, oplock 리스가 사용되는지 여부를 확인할 수 있습니다. 수동으로 해제해야 하는 잠금에 대한 정보를 확인할 수도 있습니다. 
---
= oplock 상태를 모니터링합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
oplock 상태에 대한 정보를 모니터링하고 표시할 수 있습니다. 이 정보를 사용하여 oplocks가 있는 파일, oplock 레벨 및 oplock 상태 수준이 무엇인지, oplock 리스가 사용되는지 여부를 확인할 수 있습니다. 수동으로 해제해야 하는 잠금에 대한 정보를 확인할 수도 있습니다.

모든 oplocks에 대한 정보를 요약 양식 또는 세부 목록 양식에 표시할 수 있습니다. 선택적 매개 변수를 사용하여 기존 잠금의 하위 집합에 대한 정보를 표시할 수도 있습니다. 예를 들어, 지정된 클라이언트 IP 주소 또는 지정된 경로를 사용하여 출력 반환만 잠그도록 지정할 수 있습니다.

기존 및 리스 oplocks에 대한 다음 정보를 표시할 수 있습니다.

* oplock이 설정된 SVM, 노드, 볼륨 및 LIF입니다
* UUID를 잠급니다
* oplock을 사용하는 클라이언트의 IP 주소입니다
* oplock이 설정된 경로입니다
* 잠금 프로토콜(SMB) 및 유형(oplock)
* 잠금 상태
* oplock 레벨
* 연결 상태 및 SMB 만료 시간입니다
* 임대 oplock이 부여된 경우 그룹 ID를 엽니다


각 매개변수에 대한 자세한 설명은 'vserver oplocks show' man 페이지를 참조하십시오.

.단계
. 'vserver lock show' 명령을 사용하여 oplock 상태를 표시합니다.


다음 명령을 실행하면 모든 잠금에 대한 기본 정보가 표시됩니다. 표시된 파일의 oplock은 "임시 배치" oplock 레벨로 허가됩니다.

[listing]
----
cluster1::> vserver locks show

Vserver: vs0
Volume   Object Path        LIF         Protocol  Lock Type   Client
-------- ------------------ ----------- --------- ----------- ----------
vol1     /vol1/notes.txt    node1_data1
                                        cifs      share-level 192.168.1.5
         Sharelock Mode: read_write-deny_delete
                                                  op-lock     192.168.1.5
         Oplock Level: read-batch
----
다음 예제는 경로 '/data2/data2_2/intro.pptx'를 사용하여 파일의 잠금에 대한 자세한 정보를 표시합니다. IP 주소가 10.3.1.3 인 클라이언트에 배치 oplock 레벨이 있는 파일에 리스 oplock이 부여됩니다.

[NOTE]
====
자세한 정보를 표시할 때 이 명령은 oplock 및 sharelock 정보에 대한 별도의 출력을 제공합니다. 이 예제는 oplock 섹션의 출력만 보여 줍니다.

====
[listing]
----
cluster1::> vserver lock show -instance -path /data2/data2_2/intro.pptx

                   Vserver: vs1
                    Volume: data2_2
         Logical Interface: lif2
               Object Path: /data2/data2_2/intro.pptx
                 Lock UUID: ff1cbf29-bfef-4d91-ae06-062bf69212c3
             Lock Protocol: cifs
                 Lock Type: op-lock
   Node Holding Lock State: node3
                Lock State: granted
  Bytelock Starting Offset: -
    Number of Bytes Locked: -
     Bytelock is Mandatory: -
     Bytelock is Exclusive: -
     Bytelock is Superlock: -
          Bytelock is Soft: -
              Oplock Level: batch
   Shared Lock Access Mode: -
       Shared Lock is Soft: -
           Delegation Type: -
            Client Address: 10.3.1.3
             SMB Open Type: -
         SMB Connect State: connected
SMB Expiration Time (Secs): -
         SMB Open Group ID: 78a90c59d45ae211998100059a3c7a00a007f70da0f8ffffcd445b0300000000
----
xref:enable-disable-oplocks-when-creating-shares-task.adoc[SMB 공유를 생성할 때 oplocks를 설정하거나 해제합니다]

xref:enable-disable-oplocks-existing-shares-task.adoc[기존 SMB 공유에서 oplocks 설정 또는 해제]

xref:commands-oplocks-volumes-qtrees-reference.adoc[볼륨 및 qtree에서 oplocks를 설정하거나 해제하는 명령입니다]
