---
permalink: smb-admin/monitor-signed-session-statistics-task.html 
sidebar: sidebar 
keywords: monitor, smb, session, statistic, establish, sign, monitor smb signed session statistics 
summary: SMB 세션 통계를 모니터링하고 서명된 설정된 세션과 그렇지 않은 세션을 확인할 수 있습니다. 
---
= SMB 서명 세션 통계를 모니터링합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SMB 세션 통계를 모니터링하고 서명된 설정된 세션과 그렇지 않은 세션을 확인할 수 있습니다.

고급 권한 레벨의 '통계' 명령은 서명된 SMB 세션 수를 모니터링하는 데 사용할 수 있는 'signed_sessions' 카운터를 제공합니다. 'Signed_sessions' 카운터는 다음과 같은 통계 객체와 함께 사용할 수 있습니다.

* 'CIFS'를 사용하면 모든 SMB 세션에 대해 SMB 서명을 모니터링할 수 있습니다.
* 'MB1'을 사용하면 SMB 1.0 세션에 대한 SMB 서명을 모니터링할 수 있습니다.
* 'MB2'를 사용하면 SMB 2.x 및 SMB 3.0 세션에 대한 SMB 서명을 모니터링할 수 있습니다.
+
[NOTE]
====
SMB 3.0 통계는 'MB2' 객체의 출력에 포함됩니다.

====


서명된 세션의 수를 총 세션 수와 비교하려면 'signed_sessions' 카운터의 출력을 '설정된_sessions' 카운터의 출력과 비교할 수 있습니다.

결과 데이터를 보려면 먼저 통계 샘플 수집을 시작해야 합니다. 데이터 수집을 중지하지 않으면 샘플의 데이터를 볼 수 있습니다. 데이터 수집을 중지하면 고정된 샘플이 제공됩니다. 데이터 수집을 중지하지 않으면 이전 쿼리와 비교하는 데 사용할 수 있는 업데이트된 데이터를 가져올 수 있습니다. 비교를 통해 추세를 파악할 수 있습니다.

.단계
. 권한 수준을 Advanced:'Set-Privilege advanced'로 설정합니다
. 데이터 수집을 시작합니다. 'tortistics start-object{cifs|SMB1|SMB2} - instance-sample-id_sample_ID_[-node_node_name_]'
+
'-sample-id' 매개 변수를 지정하지 않으면 명령이 샘플 식별자를 생성하고 이 샘플을 CLI 세션의 기본 샘플로 정의합니다. '-sample-id'의 값은 텍스트 문자열입니다. 동일한 CLI 세션에서 이 명령을 실행하고 '-sample-id' 매개 변수를 지정하지 않으면 명령이 이전 기본 샘플을 덮어씁니다.

+
선택적으로 통계를 수집할 노드를 지정할 수 있습니다. 노드를 지정하지 않으면 이 샘플에서 클러스터의 모든 노드에 대한 통계를 수집합니다.

. 'tortistics stop' 명령어를 이용하여 시료에 대한 데이터 수집을 중단한다.
. SMB 서명 통계 보기:
+
|===
| 에 대한 정보를 보려면... | 입력... 


 a| 
서명된 세션
 a| 
shope-sample-id sample_ID-counter signed_sessions|_node_name_[-node_node_name_]'



 a| 
서명된 세션 및 설정된 세션
 a| 
shope-sample-id_sample_ID_-counter signed_sessions|ESTANCE_SECURIONS|_NODE_NAME_[-NODE NODE_NAME]'

|===
+
단일 노드에 대한 정보만 표시하려면 옵션 '-node' 매개 변수를 지정합니다.

. admin 권한 수준으로 복귀:'et-Privilege admin'입니다


다음 예에서는 SVM(Storage Virtual Machine) VS1 에서 SMB 2.x 및 SMB 3.0 서명 통계를 모니터링하는 방법을 보여 줍니다.

다음 명령을 실행하면 고급 권한 레벨로 이동합니다.

[listing]
----
cluster1::> set -privilege advanced

Warning: These advanced commands are potentially dangerous; use them only when directed to do so by support personnel.
Do you want to continue? {y|n}: y
----
다음 명령을 실행하면 새 샘플의 데이터 수집이 시작됩니다.

[listing]
----
cluster1::*> statistics start -object smb2 -sample-id smbsigning_sample -vserver vs1
Statistics collection is being started for Sample-id: smbsigning_sample
----
다음 명령을 실행하면 샘플의 데이터 수집이 중지됩니다.

[listing]
----
cluster1::*> statistics stop -sample-id smbsigning_sample
Statistics collection is being stopped for Sample-id: smbsigning_sample
----
다음 명령을 실행하면 서명된 SMB 세션과 샘플의 노드별 설정된 SMB 세션이 표시됩니다.

[listing]
----
cluster1::*> statistics show -sample-id smbsigning_sample -counter signed_sessions|established_sessions|node_name

Object: smb2
Instance: vs1
Start-time: 2/6/2013 01:00:00
End-time: 2/6/2013 01:03:04
Cluster: cluster1

    Counter                                              Value
    -------------------------------- -------------------------
    established_sessions                                     0
    node_name                                           node1
    signed_sessions                                          0
    established_sessions                                     1
    node_name                                           node2
    signed_sessions                                          1
    established_sessions                                     0
    node_name                                           node3
    signed_sessions                                          0
    established_sessions                                     0
    node_name                                           node4
    signed_sessions                                          0
----
다음 명령을 실행하면 샘플에서 노드 2에 대해 서명된 SMB 세션이 표시됩니다.

[listing]
----
cluster1::*> statistics show -sample-id smbsigning_sample -counter signed_sessions|node_name -node node2

Object: smb2
Instance: vs1
Start-time: 2/6/2013 01:00:00
End-time: 2/6/2013 01:22:43
Cluster: cluster1

    Counter                                              Value
    -------------------------------- -------------------------
    node_name                                            node2
    signed_sessions                                          1
----
다음 명령을 실행하면 admin 권한 레벨로 다시 이동됩니다.

[listing]
----
cluster1::*> set -privilege admin
----
xref:determine-sessions-signed-task.adoc[SMB 세션이 서명되었는지 확인]

link:../performance-config/index.html["성능 모니터링 고속 설정"]
