---
permalink: smb-admin/monitor-encryption-statistics-task.html 
sidebar: sidebar 
keywords: monitor, smb, encryption, statistics, determine, establish, session, share, connection, encrypt, monitor smb encryption statistics 
summary: SMB 암호화 통계를 모니터링하고 설정된 세션 및 공유 연결이 암호화되고 암호화되지 않은 세션을 확인할 수 있습니다. 
---
= SMB 암호화 통계를 모니터링합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SMB 암호화 통계를 모니터링하고 설정된 세션 및 공유 연결이 암호화되고 암호화되지 않은 세션을 확인할 수 있습니다.

.이 작업에 대해
고급 권한 레벨의 '통계' 명령은 다음 카운터를 제공하며, 이 카운터를 사용하여 암호화된 SMB 세션 수를 모니터링하고 연결을 공유할 수 있습니다.

|===
| 카운터 이름 | 설명 


 a| 
'암호화 세션'
 a| 
암호화된 SMB 3.0 세션의 수를 제공합니다



 a| 
'암호화_공유_연결'
 a| 
트리 연결이 발생한 암호화된 공유 수를 제공합니다



 a| 
"암호화되지 않은 세션"이 끼어들었습니다
 a| 
에서는 클라이언트 암호화 기능이 부족하여 거부된 세션 설정 수를 제공합니다



 a| 
"암호화되지 않은_공유"가 있습니다
 a| 
에서는 클라이언트 암호화 기능이 없어 거부된 공유 매핑 수를 제공합니다

|===
이러한 카운터는 다음 통계 개체에서 사용할 수 있습니다.

* 'CIFS'를 사용하면 모든 SMB 3.0 세션에 대해 SMB 암호화를 모니터링할 수 있습니다.
+
SMB 3.0 통계는 'CIFS' 객체의 출력에 포함됩니다. 암호화된 세션의 수를 총 세션 수와 비교하려면 "encrypted_sessions" 카운터의 출력과 "encrypted_sessions" 카운터의 출력을 비교할 수 있습니다.

+
암호화된 공유 연결 수와 총 공유 연결 수를 비교하려면 에 대한 출력을 비교할 수 있습니다 `encrypted_share_connections` 에 대한 출력이 있는 카운터 `connected_shares` 카운터.

* reped_cencrypted_sessions는 SMB 암호화를 지원하지 않는 클라이언트로부터 암호화를 요구하는 SMB 세션을 설정하려고 시도한 횟수를 제공합니다.
* refened_cencrypted_share는 SMB 암호화를 지원하지 않는 클라이언트의 암호화가 필요한 SMB 공유에 연결하려고 시도한 횟수를 제공합니다.


결과 데이터를 보려면 먼저 통계 샘플 수집을 시작해야 합니다. 데이터 수집을 중지하지 않으면 샘플의 데이터를 볼 수 있습니다. 데이터 수집을 중지하면 고정된 샘플이 제공됩니다. 데이터 수집을 중지하지 않으면 이전 쿼리와 비교하는 데 사용할 수 있는 업데이트된 데이터를 가져올 수 있습니다. 비교를 통해 추세를 파악할 수 있습니다.

.단계
. 권한 수준을 advanced:+'et-Privilege advanced로 설정합니다
. 데이터 수집 시작: +
`statistics start -object {cifs|smb1|smb2} -instance _instance_ -sample-id _sample_ID_ [-node _node_name_]`
+
'-sample-id' 매개 변수를 지정하지 않으면 명령이 샘플 식별자를 생성하고 이 샘플을 CLI 세션의 기본 샘플로 정의합니다. '-sample-id'의 값은 텍스트 문자열입니다. 동일한 CLI 세션에서 이 명령을 실행하고 '-sample-id' 매개 변수를 지정하지 않으면 명령이 이전 기본 샘플을 덮어씁니다.

+
선택적으로 통계를 수집할 노드를 지정할 수 있습니다. 노드를 지정하지 않으면 이 샘플에서 클러스터의 모든 노드에 대한 통계를 수집합니다.

. 'tortistics stop' 명령어를 이용하여 시료에 대한 데이터 수집을 중단한다.
. SMB 암호화 통계 보기:
+
|===
| 에 대한 정보를 보려면... | 입력... 


 a| 
암호화된 세션
 a| 
'shope-sample-id_sample_ID_-counter encrypted_sessions|_node_name_[-node_node_name_]'



 a| 
암호화된 세션 및 설정된 세션
 a| 
shope-sample-id_sample_ID_-counter encrypted_sessions | encrypted_sessions | _node_name_[-node_node_name_]'



 a| 
암호화된 공유 연결
 a| 
'shope-sample-id_sample_ID_-counter encrypted_share_connections|_node_name_[-node_node_name_]'



 a| 
암호화된 공유 연결 및 연결된 공유
 a| 
'sHow-sample-id_sample_ID_-counter encrypted_share_connections|Connected_share|_node_name_[-node_node_name_]'



 a| 
암호화되지 않은 세션이 거부되었습니다
 a| 
shope-sample-id_sample_ID_-counter rejected_sencrypted_sessions|_node_name_[-node_node_name_]'



 a| 
암호화되지 않은 공유 연결이 거부되었습니다
 a| 
'shd-sample-id_sample_ID_-counter rejected_sencrypted_share|_node_name_[-node_node_name_]'

|===
+
단일 노드에 대해서만 정보를 표시하려면 옵션 '-node' 매개 변수를 지정합니다.

. 관리자 권한 수준으로 돌아가기: + 'Set-Privilege admin


.예
[%collapsible]
====
다음 예에서는 SVM(Storage Virtual Machine) VS1 에서 SMB 3.0 암호화 통계를 모니터링하는 방법을 보여 줍니다.

다음 명령을 실행하면 고급 권한 레벨로 이동합니다.

[listing]
----
cluster1::> set -privilege advanced

Warning: These advanced commands are potentially dangerous; use them only when directed to do so by support personnel.
Do you want to continue? {y|n}: y
----
다음 명령을 실행하면 새 샘플의 데이터 수집이 시작됩니다.

[listing]
----
cluster1::*> statistics start -object cifs -sample-id smbencryption_sample -vserver vs1
Statistics collection is being started for Sample-id: smbencryption_sample
----
다음 명령을 실행하면 해당 샘플의 데이터 수집이 중지됩니다.

[listing]
----
cluster1::*> statistics stop -sample-id smbencryption_sample
Statistics collection is being stopped for Sample-id: smbencryption_sample
----
다음 명령을 실행하면 암호화된 SMB 세션 및 샘플의 노드에 의해 설정된 SMB 세션이 표시됩니다.

[listing]
----
cluster2::*> statistics show -object cifs -counter established_sessions|encrypted_sessions|node_name –node node_name

Object: cifs
Instance: [proto_ctx:003]
Start-time: 4/12/2016 11:17:45
End-time: 4/12/2016 11:21:45
Scope: vsim2

    Counter                               Value
    ----------------------------  ----------------------
    established_sessions                     1
    encrypted_sessions                       1

2 entries were displayed
----
다음 명령을 실행하면 샘플에서 노드에서 암호화되지 않은 암호화되지 않은 SMB 세션이 거부된 수가 표시됩니다.

[listing]
----
clus-2::*> statistics show -object cifs -counter rejected_unencrypted_sessions –node node_name

Object: cifs
Instance: [proto_ctx:003]
Start-time: 4/12/2016 11:17:45
End-time: 4/12/2016 11:21:51
Scope: vsim2

    Counter                                    Value
    ----------------------------    ----------------------
    rejected_unencrypted_sessions                1

1 entry was displayed.
----
다음 명령을 실행하면 샘플의 노드에 의해 연결된 SMB 공유 및 암호화된 SMB 공유의 수가 표시됩니다.

[listing]
----
clus-2::*> statistics show -object cifs -counter connected_shares|encrypted_share_connections|node_name –node node_name

Object: cifs
Instance: [proto_ctx:003]
Start-time: 4/12/2016 10:41:38
End-time: 4/12/2016 10:41:43
Scope: vsim2

    Counter                                     Value
    ----------------------------    ----------------------
    connected_shares                              2
    encrypted_share_connections                   1

2 entries were displayed.
----
다음 명령을 실행하면 샘플에서 노드에서 암호화되지 않은 암호화되지 않은 SMB 공유 연결이 거부된 수가 표시됩니다.

[listing]
----
clus-2::*> statistics show -object cifs -counter rejected_unencrypted_shares –node node_name

Object: cifs
Instance: [proto_ctx:003]
Start-time: 4/12/2016 10:41:38
End-time: 4/12/2016 10:42:06
Scope: vsim2

    Counter                                     Value
    --------------------------------    ----------------------
    rejected_unencrypted_shares                   1

1 entry was displayed.
----
====
.관련 정보
xref:determine-statistics-objects-counters-available-task.adoc[사용할 수 있는 통계 개체 및 카운터 결정]

link:../performance-admin/index.html["성능 모니터링 및 관리 개요"]
