---
permalink: smb-admin/offline-files-allow-caching-concept.html 
sidebar: sidebar 
keywords: ontap, support, microsoft, offline, file, feature, client-side, caching, cache, file, local, host, offline, disconnect, network, use offline files to allow caching of files for offline use 
summary: ONTAP는 Microsoft 오프라인 파일 기능 또는 클라이언트측 캐싱을 지원하므로 파일을 로컬 호스트에 캐싱하여 오프라인으로 사용할 수 있습니다. 사용자는 오프라인 파일 기능을 사용하여 네트워크에서 연결이 끊어진 경우에도 파일 작업을 계속할 수 있습니다. 
---
= 오프라인 파일을 사용하여 오프라인 사용을 위한 파일 캐싱 개요
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP는 오프라인 사용을 위해 파일을 로컬 호스트에 캐시할 수 있는 Microsoft 오프라인 파일 기능 또는 _클라이언트측 캐싱_을 지원합니다. 사용자는 오프라인 파일 기능을 사용하여 네트워크에서 연결이 끊어진 경우에도 파일 작업을 계속할 수 있습니다.

Windows 사용자 문서 및 프로그램이 자동으로 공유에서 캐시되는지 아니면 파일을 수동으로 캐시하도록 선택해야 하는지 여부를 지정할 수 있습니다. 수동 캐싱은 새 공유에 대해 기본적으로 설정됩니다. 오프라인으로 사용할 수 있는 파일은 Windows 클라이언트의 로컬 디스크와 동기화됩니다. 동기화는 특정 스토리지 시스템 공유에 대한 네트워크 접속이 복구되는 경우에 발생합니다.

오프라인 파일 및 폴더는 CIFS 서버에 저장된 파일 및 폴더의 버전과 동일한 액세스 권한을 유지하므로 오프라인 파일 및 폴더에 대한 작업을 수행하려면 CIFS 서버에 저장된 파일 및 폴더에 대한 충분한 권한이 있어야 합니다.

사용자 및 네트워크의 다른 사용자가 동일한 파일을 변경한 경우 사용자는 파일의 로컬 버전을 네트워크에 저장하거나 다른 버전을 유지하거나 둘 다 저장할 수 있습니다. 사용자가 두 버전을 모두 유지할 경우 로컬 사용자의 변경 내용이 있는 새 파일이 로컬에 저장되고 캐시된 파일은 CIFS 서버에 저장된 파일 버전의 변경 내용으로 덮어쓰입니다.

공유 구성 설정을 사용하여 공유 단위로 오프라인 파일을 구성할 수 있습니다. 공유를 만들거나 수정할 때 네 개의 오프라인 폴더 구성 중 하나를 선택할 수 있습니다.

* 캐싱이 없습니다
+
공유에 대한 클라이언트 측 캐시를 해제합니다. 파일과 폴더는 클라이언트에 로컬로 자동으로 캐시되지 않으며 사용자는 파일 또는 폴더를 로컬로 캐시하도록 선택할 수 없습니다.

* 수동 캐싱
+
공유에 캐시할 파일을 수동으로 선택할 수 있습니다. 기본 설정입니다. 기본적으로 파일 또는 폴더는 로컬 클라이언트에 캐시되지 않습니다. 사용자는 오프라인 사용을 위해 로컬로 캐시할 파일과 폴더를 선택할 수 있습니다.

* 자동 문서 캐싱
+
사용자 문서를 공유에 자동으로 캐시할 수 있습니다. 액세스한 파일 및 폴더만 로컬로 캐시됩니다.

* 자동 프로그램 캐싱
+
프로그램 및 사용자 문서를 자동으로 공유에 캐시할 수 있습니다. 액세스한 파일, 폴더 및 프로그램만 로컬로 캐시됩니다. 또한 이 설정을 사용하면 클라이언트가 네트워크에 연결되어 있는 경우에도 로컬로 캐시된 실행 파일을 실행할 수 있습니다.



Windows 서버 및 클라이언트에서 오프라인 파일을 구성하는 방법에 대한 자세한 내용은 Microsoft TechNet 라이브러리를 참조하십시오.

.관련 정보
xref:roaming-profiles-store-user-profiles-concept.adoc[로밍 프로필을 사용하여 SVM과 연결된 CIFS 서버에 사용자 프로필을 중앙에서 저장합니다]

xref:folder-redirection-store-data-concept.adoc[폴더 리디렉션을 사용하여 CIFS 서버에 데이터를 저장합니다]

xref:branchcache-cache-share-content-branch-office-concept.adoc[BranchCache를 사용하여 지사에 SMB 공유 콘텐츠를 캐싱합니다]

http://["Microsoft TechNet 라이브러리: technet.microsoft.com/en-us/library/"]
