---
permalink: smb-admin/optimize-user-access-force-group-share-concept.html 
sidebar: sidebar 
keywords: create, share, ontap, command, line, data, unix, effective, security, smb, user, group, force-group, predefined, database, force-group, access, how to optimize smb user access with the force-group share setting 
summary: ONTAP 명령줄에서 UNIX 효과적인 보안이 설정된 데이터에 대한 공유를 생성할 때 해당 공유의 SMB 사용자가 생성한 모든 파일이 UNIX 그룹 데이터베이스에서 미리 정의된 그룹인 force-group이라는 동일한 그룹에 속하도록 지정할 수 있습니다. force-group을 사용하면 다양한 그룹에 속한 SMB 사용자가 파일에 쉽게 액세스할 수 있습니다. 
---
= force-group 공유 설정을 사용하여 SMB 사용자 액세스를 최적화합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 명령줄에서 UNIX 효과적인 보안이 설정된 데이터에 대한 공유를 생성할 때 해당 공유의 SMB 사용자가 생성한 모든 파일이 UNIX 그룹 데이터베이스에서 미리 정의된 그룹이어야 하는 _force-group_이라는 동일한 그룹에 속하도록 지정할 수 있습니다. force-group을 사용하면 다양한 그룹에 속한 SMB 사용자가 파일에 쉽게 액세스할 수 있습니다.

강제 그룹 지정은 공유가 UNIX 또는 혼합 qtree에 있는 경우에만 의미가 있습니다. 이러한 공유의 파일에 대한 액세스는 UNIX GID가 아닌 Windows 권한에 의해 결정되므로 NTFS 볼륨이나 qtree의 공유에 대해 강제 그룹을 설정할 필요가 없습니다.

공유에 대해 force-group이 지정된 경우 공유의 다음 내용이 적용됩니다.

* 이 공유에 액세스하는 force-group의 SMB 사용자는 force-group의 GID로 일시적으로 변경됩니다.
+
이 GID를 사용하면 주 GID 또는 UID로 정상적으로 액세스할 수 없는 이 공유의 파일에 액세스할 수 있습니다.

* SMB 사용자가 생성한 이 공유의 모든 파일은 파일 소유자의 기본 GID에 관계없이 동일한 강제 그룹에 속합니다.


SMB 사용자가 NFS에서 생성된 파일에 액세스하려고 하면 SMB 사용자의 기본 GID가 액세스 권한을 결정합니다.

force-group은 NFS 사용자가 이 공유의 파일에 액세스하는 방법에 영향을 주지 않습니다. NFS에서 생성된 파일은 파일 소유자로부터 GID를 가져옵니다. 액세스 권한 결정은 파일에 액세스하려는 NFS 사용자의 UID 및 기본 GID를 기반으로 합니다.

force-group을 사용하면 다양한 그룹에 속한 SMB 사용자가 파일에 쉽게 액세스할 수 있습니다. 예를 들어 회사 웹 페이지를 저장하고 엔지니어링 및 마케팅 부서의 사용자에게 쓰기 권한을 부여하기 위해 공유를 만들고 ""webgroup1"" 그룹에 쓰기 권한을 부여할 수 있습니다. 강제 그룹 때문에 이 공유에 있는 SMB 사용자가 만든 모든 파일은 ""webgroup1"" 그룹의 소유입니다. 또한 공유에 액세스할 때 ""webgroup1"" 그룹의 GID가 자동으로 할당됩니다. 따라서 엔지니어링 및 마케팅 부서에서 사용자의 액세스 권한을 관리할 필요 없이 모든 사용자가 이 공유에 쓸 수 있습니다.

xref:create-share-force-group-setting-task.adoc[그룹 강제 공유 설정을 사용하여 SMB 공유를 생성합니다]
