---
permalink: smb-admin/requirements-automatic-node-referrals-concept.html 
sidebar: sidebar 
keywords: smb, automatic, node, referral, autolocation, aware, requirement, version, ontap, feature, support, guideline, requirement, requirements and guidelines for using automatic node referrals 
summary: 자동 위치정보 라고도 하는 SMB 자동 노드 조회를 사용하려면 해당 기능을 지원하는 ONTAP 버전을 비롯한 특정 요구 사항을 알고 있어야 합니다. 또한 지원되는 SMB 프로토콜 버전 및 기타 특정 특별 지침에 대해서도 알아야 합니다. 
---
= 자동 노드 조회를 사용하기 위한 요구 사항 및 지침
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SMB 자동 노드 조회를 사용하려면 _ autolocation _ 이라고도 하며, 이 기능을 지원하는 ONTAP 버전을 비롯한 특정 요구 사항을 알고 있어야 합니다. 또한 지원되는 SMB 프로토콜 버전 및 기타 특정 특별 지침에 대해서도 알아야 합니다.



== ONTAP 버전 및 라이센스 요구 사항

* 클러스터의 모든 노드는 자동 노드 조회를 지원하는 ONTAP 버전을 실행하고 있어야 합니다.
* 자동 위치 정보를 사용하려면 SMB 공유에서 Widelink를 활성화해야 합니다.
* CIFS에 대한 라이센스가 있어야 하며 SMB 서버가 SVM에 있어야 합니다.




== SMB 프로토콜 버전 요구 사항

* SVM의 경우 ONTAP는 모든 SMB 버전에서 자동 노드 조회를 지원합니다.




== SMB 클라이언트 요구 사항

ONTAP에서 지원하는 모든 Microsoft 클라이언트는 SMB 자동 노드 조회를 지원합니다.

상호 운용성 매트릭스에는 ONTAP에서 지원하는 Windows 클라이언트에 대한 최신 정보가 포함되어 있습니다.

link:http://mysupport.netapp.com/matrix["NetApp 상호 운용성 매트릭스 툴"^]



== 데이터 LIF 요구사항

데이터 LIF를 SMB 클라이언트를 위한 잠재 고객으로 사용하려면 NFS와 CIFS를 모두 사용하도록 설정된 데이터 LIF를 생성해야 합니다.

타겟 노드에 NFS 프로토콜에만 사용하도록 설정된 데이터 LIF가 있거나 SMB 프로토콜에 대해서만 사용하도록 설정된 데이터 LIF가 있는 경우 자동 노드 조회가 작동하지 않을 수 있습니다.

이 요구 사항이 충족되지 않으면 데이터 액세스가 영향을 받지 않습니다. SMB 클라이언트는 클라이언트가 SVM에 연결할 때 사용한 원래 LIF를 사용하여 공유를 매핑합니다.



== 참조된 SMB 연결을 만들 때 NTLM 인증 요구 사항

NTLM 인증은 CIFS 서버가 포함된 도메인 및 자동 노드 조회를 사용하려는 클라이언트가 포함된 도메인에서 허용되어야 합니다.

SMB 서버는 조회를 수행할 때 Windows 클라이언트에 대한 IP 주소를 참조합니다. NTLM 인증은 IP 주소를 사용하여 연결할 때 사용되므로 Kerberos 인증은 참조된 연결에 대해 수행되지 않습니다.

이는 Kerberos(service/netbios name, service/FQDN) 형태의 서비스 주체 이름을 Windows 클라이언트가 생성할 수 없기 때문에 클라이언트가 Kerberos 티켓을 서비스에 요청할 수 없다는 뜻입니다.



== 홈 디렉토리 기능과 함께 자동 노드 조회를 사용하는 지침

공유가 홈 디렉토리 공유 속성을 사용하여 구성된 경우 홈 디렉토리 구성에 대해 하나 이상의 홈 디렉토리 검색 경로가 구성될 수 있습니다. 검색 경로는 SVM 볼륨을 포함하는 각 노드에 포함된 볼륨을 가리킬 수 있습니다. 클라이언트는 추천을 받으며 액티브 로컬 데이터 LIF가 사용 가능한 경우 홈 사용자의 홈 디렉토리에 로컬로 연결된 참조된 LIF를 통해 연결됩니다.

SMB 1.0 클라이언트가 자동 노드 조회가 설정된 동적 홈 디렉토리에 액세스하는 경우 지침이 있습니다. 이는 SMB 1.0 클라이언트가 인증을 받기 전에 자동 노드 조회를 필요로 하기 때문입니다. 이는 SMB 서버가 사용자 이름을 가지기 전입니다. 그러나 SMB 1.0 클라이언트에서 SMB 홈 디렉토리 액세스가 올바르게 작동하는 경우는 다음과 같습니다.

* SMB 홈 디렉토리는 ""%w"(Windows 사용자 이름) 또는 ""%u"(매핑된 UNIX 사용자 이름)와 같은 단순 이름을 사용하도록 구성되어 있으며 ""%d\%w"(domain-name\user-name)와 같은 도메인 이름 스타일 이름은 사용하지 않습니다.
* 홈 디렉토리 공유를 생성할 때 CIFS 홈 디렉토리 공유 이름은 ""home""과 같은 정적 이름이 아니라 변수(""%w" 또는 ""%u")로 구성됩니다.


SMB 2.x 및 SMB 3.0 클라이언트의 경우 자동 노드 조회를 사용하여 홈 디렉토리에 액세스할 때 특별한 지침이 없습니다.



== 기존에 연결된 연결이 있는 CIFS 서버에서 자동 노드 조회를 해제하는 지침입니다

이 옵션이 설정된 후 자동 노드 조회를 사용하지 않도록 설정하면 현재 참조된 LIF에 연결된 클라이언트가 계속 연결된 상태로 유지됩니다. ONTAP는 DFS 조회를 SMB 자동 노드 조정의 메커니즘으로 사용하므로, 클라이언트의 캐시된 DFS 참조 시간이 초과될 때까지 이 옵션을 비활성화한 후에 클라이언트가 참조된 LIF에 다시 연결할 수도 있습니다. 자동 노드 조회를 지원하지 않는 ONTAP 버전으로 되돌리는 경우에도 마찬가지입니다. 클라이언트는 클라이언트의 캐시에서 DFS 참조 시간이 초과될 때까지 계속 조회를 사용합니다.

Autolocation은 SMB 자동 노드 조회를 사용하여 SVM의 데이터 볼륨을 소유하는 노드의 LIF에 클라이언트를 위탁하여 SMB 클라이언트의 성능을 높입니다. SMB 클라이언트가 SVM에서 호스팅되는 SMB 공유에 연결할 경우, 요청된 데이터를 소유하지 않고 클러스터 인터커넥트 네트워크를 사용하여 데이터를 검색하는 노드에서 LIF를 사용하여 연결할 수 있습니다. SMB 연결이 요청된 데이터를 포함하고 있는 노드에 있는 LIF를 사용하는 경우 클라이언트는 더 빠른 응답 시간을 경험할 수 있습니다.

ONTAP는 Microsoft DFS(분산 파일 시스템) 조회를 사용하여 SMB 클라이언트에 네임스페이스에서 요청된 파일 또는 폴더가 다른 곳에 호스팅된다는 사실을 알려 주는 이 기능을 제공합니다. 노드가 데이터를 포함하는 노드에 SVM LIF가 있다고 판단하면 노드를 전문의에게 의뢰합니다. 조인은 클라이언트가 연결되는 공유 루트의 위치를 기반으로 합니다.

SMB 협상 중에 불합격입니다. 연결이 설정되기 전에 의뢰합니다. ONTAP가 SMB 클라이언트를 타겟 노드로 참조하면 연결이 연결되고 클라이언트는 해당 시점부터 참조된 LIF 경로를 통해 데이터에 액세스합니다. 이렇게 하면 클라이언트가 데이터에 더 빠르게 액세스할 수 있고 추가 클러스터 통신을 피할 수 있습니다.



== Mac OS 클라이언트에서 자동 노드 조회를 사용하는 방법에 대한 지침입니다

Mac OS X 클라이언트는 Microsoft의 DFS(Distributed File System)를 지원하지만 SMB 자동 노드 조회를 지원하지 않습니다. Windows 클라이언트는 SMB 공유에 연결하기 전에 DFS 참조 요청을 합니다. ONTAP는 요청된 데이터를 호스팅하는 동일한 노드에 있는 데이터 LIF를 지칭하여 클라이언트 응답 시간을 개선합니다. Mac OS는 DFS를 지원하지만 Mac OS 클라이언트는 이 영역의 Windows 클라이언트와 정확히 작동하지 않습니다.

.관련 정보
xref:dynamic-home-directories-concept.html[ONTAP에서 동적 홈 디렉터리를 활성화하는 방법]

link:../networking/index.html["네트워크 관리"]

https://mysupport.netapp.com/NOW/products/interoperability["NetApp 상호 운용성 매트릭스 툴"^]
