---
permalink: smb-admin/security-styles-their-effects-concept.html 
sidebar: sidebar 
keywords: unix, ntfs, mixed, unified, security, style, effect, permission, handle, data, what the security styles and their effects are 
summary: UNIX, NTFS, 혼합 및 통합 등 네 가지 보안 유형이 있습니다. 각 보안 스타일은 데이터에 대한 사용 권한이 처리되는 방식에 다른 영향을 줍니다. 용도에 맞는 적절한 보안 스타일을 선택할 수 있도록 다양한 효과를 이해해야 합니다. 
---
= 보안 스타일과 그 효과는 무엇입니까
:icons: font
:imagesdir: ../media/


[role="lead"]
UNIX, NTFS, 혼합 및 통합 등 네 가지 보안 유형이 있습니다. 각 보안 스타일은 데이터에 대한 사용 권한이 처리되는 방식에 다른 영향을 줍니다. 용도에 맞는 적절한 보안 스타일을 선택할 수 있도록 다양한 효과를 이해해야 합니다.

보안 스타일은 클라이언트 유형이 데이터에 액세스할 수 있거나 액세스할 수 없는 형식을 결정하지 않는다는 점을 이해하는 것이 중요합니다. 보안 스타일은 ONTAP에서 데이터 액세스를 제어하는 데 사용하는 권한 유형과 이러한 권한을 수정할 수 있는 클라이언트 유형만 결정합니다.

예를 들어, 볼륨이 UNIX 보안 스타일을 사용하는 경우에도 SMB 클라이언트는 ONTAP의 멀티 프로토콜 특성으로 인해 데이터에 액세스(적절하게 인증 및 승인)할 수 있습니다. 그러나 ONTAP에서는 UNIX 클라이언트만 기본 툴을 사용하여 수정할 수 있는 UNIX 권한을 사용합니다.

|===
| 보안 스타일 | 사용 권한을 수정할 수 있는 클라이언트입니다 | 클라이언트가 사용할 수 있는 권한 | 결과적으로 효율적인 보안 스타일을 제공합니다 | 파일에 액세스할 수 있는 클라이언트입니다 


 a| 
Unix
 a| 
NFS 를 참조하십시오
 a| 
NFSv3 모드 비트
 a| 
Unix
 a| 
NFS 및 SMB



 a| 
NFSv4.x ACL
 a| 
Unix



 a| 
NTFS입니다
 a| 
중소기업
 a| 
NTFS ACL
 a| 
NTFS입니다



 a| 
혼합
 a| 
NFS 또는 SMB
 a| 
NFSv3 모드 비트
 a| 
Unix



 a| 
NFSv4.x ACL
 a| 
Unix



 a| 
NTFS ACL
 a| 
NTFS입니다
 a| 
통합
 a| 
NFS 또는 SMB



 a| 
NFSv3 모드 비트
 a| 
Unix



 a| 
NFSv4.1 ACL
 a| 
Unix
 a| 
NTFS ACL
 a| 
NTFS입니다



.3+| 통합(ONTAP 9.4 및 이전 릴리즈에서 무한 확장 볼륨에만 해당) .3+| NFS 또는 SMB | NFSv3 모드 비트 .2+| Unix 


| NFSv4.1 ACL | NTFS ACL 
|===
FlexVol 볼륨은 UNIX, NTFS 및 혼합 보안 스타일을 지원합니다. 보안 스타일이 혼합 또는 통합된 경우 사용자가 보안 스타일을 개별적으로 설정하므로 사용자가 마지막으로 권한을 수정한 클라이언트 유형에 따라 유효 사용 권한이 달라집니다. 권한을 수정한 마지막 클라이언트가 NFSv3 클라이언트인 경우 사용 권한은 UNIX NFSv3 모드 비트입니다. 마지막 클라이언트가 NFSv4 클라이언트인 경우 사용 권한은 NFSv4 ACL입니다. 마지막 클라이언트가 SMB 클라이언트인 경우 사용 권한은 Windows NTFS ACL입니다.

통합 보안 스타일은 ONTAP 9.5 이상 릴리스에서 더 이상 지원되지 않는 무한 볼륨에서만 사용할 수 있습니다. 자세한 내용은 을 참조하십시오 link:..flexgroup/index.html["FlexGroup 볼륨 관리 개요"].

ONTAP 9.2부터 vserver security file-directory 명령에 대한 'show-Effective-permissions' 매개 변수를 사용하면 지정된 파일 또는 폴더 경로에서 Windows 또는 UNIX 사용자에게 부여된 유효한 권한을 표시할 수 있습니다. 또한 선택적 매개 변수 '-share-name'을 사용하면 유효 공유 권한을 표시할 수 있습니다.

[NOTE]
====
ONTAP는 처음에 일부 기본 파일 권한을 설정합니다. 기본적으로 UNIX, 혼합 및 통합 보안 스타일 볼륨의 모든 데이터에 대한 효과적인 보안 스타일은 UNIX이고, 기본 보안 스타일에 의해 허용되는 대로 클라이언트에 의해 구성될 때까지 유효 사용 권한 유형은 UNIX 모드 비트(별도로 지정하지 않는 경우 0755)입니다. 기본적으로 NTFS 보안 스타일 볼륨의 모든 데이터에 대한 효과적인 보안 스타일은 NTFS이며 ACL을 통해 모든 사람에게 모든 권한을 제공할 수 있습니다.

====
2021년 12월 9일, Burt 1443623
