---
permalink: smb-admin/security-descriptors-apply-file-folder-security-concept.html 
sidebar: sidebar 
keywords: security, descriptor, contain, access, control, list, file, folder, audit, user, how security descriptors are used to apply file and folder security 
summary: 보안 설명자는 사용자가 파일 및 폴더에 대해 수행할 수 있는 작업과 사용자가 파일 및 폴더에 액세스할 때 감사할 작업을 결정하는 액세스 제어 목록을 포함합니다. 
---
= 보안 설명자를 사용하여 파일 및 폴더 보안을 적용하는 방법
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
보안 설명자는 사용자가 파일 및 폴더에 대해 수행할 수 있는 작업과 사용자가 파일 및 폴더에 액세스할 때 감사할 작업을 결정하는 액세스 제어 목록을 포함합니다.

* * 권한 *
+
권한은 개체의 소유자가 허용하거나 거부하고 개체(사용자, 그룹 또는 컴퓨터 개체)가 지정된 파일이나 폴더에서 수행할 수 있는 작업을 결정합니다.

* * 보안 설명자 *
+
보안 설명자는 파일 또는 폴더와 관련된 권한을 정의하는 보안 정보가 포함된 데이터 구조입니다.

* * ACL(액세스 제어 목록) *
+
액세스 제어 목록은 보안 설명자가 적용된 파일 또는 폴더에서 사용자, 그룹 또는 컴퓨터 개체가 수행할 수 있는 작업에 대한 정보를 포함하는 보안 설명자에 포함된 목록입니다. 보안 설명자는 다음 두 가지 유형의 ACL을 포함할 수 있습니다.

+
** DACL(임의 액세스 제어 목록)
** 시스템 액세스 제어 목록(SACL)


* * DACL(임의 액세스 제어 목록) *
+
DACL에는 파일 또는 폴더에 대한 작업을 수행할 수 있는 액세스가 허용 또는 거부된 사용자, 그룹 및 컴퓨터 개체에 대한 SIDS 목록이 포함되어 있습니다. DACL에는 ACE(액세스 제어 항목)가 0개 이상 포함되어 있습니다.

* * 시스템 액세스 제어 목록(SACL) *
+
SACL에는 성공 또는 실패 감사 이벤트가 기록되는 사용자, 그룹 및 컴퓨터 개체에 대한 SIDS 목록이 포함되어 있습니다. SACL에는 ACE(액세스 제어 항목)가 0개 이상 포함되어 있습니다.

* * ACE(액세스 제어 항목) *
+
ACE는 DACL 또는 SACL의 개별 항목입니다.

+
** DACL 액세스 제어 항목은 특정 사용자, 그룹 또는 컴퓨터 개체에 대해 허용 또는 거부된 액세스 권한을 지정합니다.
** SACL 액세스 제어 항목은 특정 사용자, 그룹 또는 컴퓨터 개체에서 수행하는 지정된 작업을 감사할 때 기록할 성공 또는 실패 이벤트를 지정합니다.


* * 사용 권한 상속 *
+
권한 상속에서는 보안 설명자에 정의된 권한이 부모 개체에서 개체로 전파되는 방법을 설명합니다. 상속 가능한 권한만 자식 개체에서 상속합니다. 상위 객체에 대한 권한을 설정할 때 폴더, 하위 폴더, 파일이 이 폴더에 적용, 하위 폴더, 파일 등을 통해 해당 항목을 상속할 수 있는지 여부를 결정할 수 있습니다.



xref:../nas-audit/create-ntfs-security-descriptor-file-task.adoc[CLI를 사용하여 NTFS 파일 및 폴더에 파일 보안을 구성하고 적용합니다]

link:../nas-audit/index.html["SMB 및 NFS 감사 및 보안 추적"]

xref:configure-apply-audit-policies-ntfs-files-folders-task.adoc[CLI를 사용하여 NTFS 파일 및 폴더에 감사 정책 구성 및 적용]
