---
permalink: smb-admin/share-properties-concept.html 
sidebar: sidebar 
keywords: customize, properties, property, smb, share, how to use smb share properties 
summary: SMB 공유의 속성을 사용자 지정할 수 있습니다. 
---
= SMB 공유 속성 개요 사용
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SMB 공유의 속성을 사용자 지정할 수 있습니다.

사용 가능한 공유 속성은 다음과 같습니다.

|===
| 공유 속성 | 설명 


 a| 
oplocks
 a| 
이 속성은 공유에서 클라이언트 측 캐시라고도 하는 편의적 잠금을 사용하도록 지정합니다.



 a| 
"탐색 가능"
 a| 
이 속성을 사용하면 Windows 클라이언트가 공유를 탐색할 수 있습니다.



 a| 
'하울스냅샷'
 a| 
이 속성은 클라이언트가 스냅샷 복사본을 보고 이동할 수 있도록 지정합니다.



 a| 
'변상강화하는'
 a| 
이 속성은 공유에서 변경 통지 요청을 지원하도록 지정합니다. SVM에서 공유하면 기본 초기 속성이 됩니다.



 a| 
'attributecache
 a| 
이 속성을 사용하면 SMB 공유의 파일 속성 캐싱을 통해 속성에 더 빠르게 액세스할 수 있습니다. 기본값은 특성 캐싱을 사용하지 않는 것입니다. 이 속성은 SMB 1.0을 통해 공유에 연결하는 클라이언트가 있는 경우에만 사용해야 합니다. 클라이언트가 SMB 2.x 또는 SMB 3.0을 통해 공유에 연결하는 경우에는 이 공유 속성을 사용할 수 없습니다.



 a| 
"계속 사용할 수 있습니다.
 a| 
이 속성을 사용하면 SMB 클라이언트가 지속적으로 파일을 열 수 있습니다. 이렇게 열린 파일은 페일오버 및 반환과 같은 운영 중단 이벤트로부터 보호됩니다.



 a| 
브랜치캐시
 a| 
이 속성은 클라이언트가 이 공유 내의 파일에 대해 BranchCache 해시를 요청할 수 있도록 공유를 지정합니다. 이 옵션은 CIFS BranchCache 구성에서 ""공유당""을 운영 모드로 지정한 경우에만 유용합니다.



 a| 
'액세스 기반 열거'
 a| 
이 속성은 이 공유에서 _Access 기반 열거_(ABE)를 사용하도록 지정합니다. 개별 사용자의 액세스 권한에 따라 사용자가 ABE로 필터링된 공유 폴더를 볼 수 있으므로 사용자에게 액세스 권한이 없는 폴더 또는 기타 공유 리소스를 표시할 수 없습니다.



 a| 
네임스페이스-캐싱
 a| 
이 속성은 이 공유에 연결하는 SMB 클라이언트가 CIFS 서버가 반환하는 디렉터리 열거 결과를 캐시할 수 있도록 지정함으로써 성능을 향상시킬 수 있습니다. 기본적으로 SMB 1 클라이언트는 디렉터리 열거 결과를 캐시하지 않습니다. SMB 2 및 SMB 3 클라이언트는 기본적으로 캐시 디렉토리 열거 결과를 제공하므로 이 공유 속성을 지정하면 SMB 1 클라이언트 연결에만 성능 이점이 있습니다.



 a| 
'암호화-데이터'
 a| 
이 속성은 이 공유에 액세스할 때 SMB 암호화를 사용하도록 지정합니다. SMB 데이터에 액세스할 때 암호화를 지원하지 않는 SMB 클라이언트는 이 공유에 액세스할 수 없습니다.

|===