---
permalink: smb-admin/supported-dynamic-access-control-reference.html 
sidebar: sidebar 
keywords: dynamic, access, control, dac, cifs, server, understand, ontap, support, functionality, active, directory, environment, supported dynamic access control functionality 
summary: 'CIFS 서버에서 DAC(동적 액세스 제어)를 사용하려면 ONTAP가 Active Directory 환경에서 동적 액세스 제어 기능을 지원하는 방법을 이해해야 합니다.' 
---
= 지원되는 동적 액세스 제어 기능
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
CIFS 서버에서 DAC(동적 액세스 제어)를 사용하려면 ONTAP가 Active Directory 환경에서 동적 액세스 제어 기능을 지원하는 방법을 이해해야 합니다.



== 동적 액세스 제어에 지원됩니다

ONTAP는 CIFS 서버에서 동적 액세스 제어가 설정된 경우 다음 기능을 지원합니다.

|===
| 기능 | 설명 


 a| 
파일 시스템에 대한 클레임입니다
 a| 
청구는 사용자에 대한 일부 진실을 나타내는 간단한 이름 및 값 쌍입니다. 이제 사용자 자격 증명에 클레임 정보가 포함되며, 파일의 보안 설명자는 클레임 확인이 포함된 액세스 검사를 수행할 수 있습니다. 따라서 관리자는 파일에 액세스할 수 있는 사용자를 보다 세밀하게 제어할 수 있습니다.



 a| 
파일 액세스 검사에 대한 조건식입니다
 a| 
이제 파일의 보안 매개 변수를 수정할 때 파일의 보안 설명자에 임의로 복잡한 조건식을 추가할 수 있습니다. 조건부 표현식에는 클레임 확인이 포함될 수 있습니다.



 a| 
중앙 액세스 정책을 통해 파일 액세스를 중앙 집중식으로 제어
 a| 
중앙 액세스 정책은 파일에 태그를 지정할 수 있는 Active Directory에 저장된 일종의 ACL입니다. 디스크에 있는 보안 설명자와 태그가 지정된 중앙 액세스 정책 모두의 액세스 검사가 액세스를 허용하는 경우에만 파일에 대한 액세스가 부여됩니다. 따라서 관리자는 디스크의 보안 설명자를 수정하지 않고도 중앙 위치(AD)에서 파일에 대한 액세스를 제어할 수 있습니다.



 a| 
중앙 액세스 정책 스테이징
 a| 
중앙 액세스 정책의 "변경"을 통해 실제 파일 액세스에 영향을 주지 않고 보안 변경 사항을 시도하는 기능을 추가하고 감사 보고서에서 변경 효과를 확인할 수 있습니다.



 a| 
ONTAP CLI를 사용하여 중앙 액세스 정책 보안에 대한 정보 표시 지원
 a| 
'vserver security file-directory show' 명령을 확장하여 적용된 중앙 액세스 정책에 대한 정보를 표시합니다.



 a| 
중앙 액세스 정책을 포함하는 보안 추적
 a| 
적용된 중앙 액세스 정책에 대한 정보가 포함된 결과를 표시하도록 'vserver security trace' 명령 제품군을 확장합니다.

|===


== 동적 액세스 제어에 지원되지 않습니다

CIFS 서버에서 동적 액세스 제어가 설정된 경우 ONTAP는 다음 기능을 지원하지 않습니다.

|===
| 기능 | 설명 


 a| 
NTFS 파일 시스템 객체의 자동 분류
 a| 
이 확장명은 ONTAP에서 지원되지 않는 Windows 파일 분류 인프라스트럭처의 확장입니다.



 a| 
중앙 액세스 정책 스테이징 이외의 고급 감사
 a| 
고급 감사를 위해 중앙 액세스 정책 스테이징만 지원됩니다.

|===