---
permalink: smb-admin/support-ipv6-concept.html 
sidebar: sidebar 
keywords: ipv6, cifs, server, ontap, smb, network, communication, service, support for ipv6 with smb access and cifs services 
summary: CIFS 서버에서 IPv6를 사용하려면 ONTAP가 CIFS 서비스에 대한 SMB 액세스 및 네트워크 통신을 위해 IPv6를 지원하는 방법을 알고 있어야 합니다. 
---
= SMB 액세스 및 CIFS 서비스를 통해 IPv6를 지원합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
CIFS 서버에서 IPv6를 사용하려면 ONTAP가 CIFS 서비스에 대한 SMB 액세스 및 네트워크 통신을 위해 IPv6를 지원하는 방법을 알고 있어야 합니다.



== Windows 클라이언트 및 서버 지원

ONTAP는 IPv6를 지원하는 Windows 서버 및 클라이언트를 지원합니다. 다음은 Microsoft Windows 클라이언트 및 서버 IPv6 지원에 대한 설명입니다.

* Windows 7, Windows 8, Windows Server 2008, Windows Server 2012 이상에서는 DNS, LDAP, CLDAP 및 Kerberos 서비스를 포함한 SMB 파일 공유 및 Active Directory 서비스에 대해 IPv6를 지원합니다.
+
IPv6 주소가 구성된 경우 Windows 7 및 Windows Server 2008 이상 릴리즈에서는 Active Directory 서비스에 대해 기본적으로 IPv6을 사용합니다. IPv6 연결을 통한 NTLM 및 Kerberos 인증이 모두 지원됩니다.

+
ONTAP에서 지원하는 모든 Windows 클라이언트는 IPv6 주소를 사용하여 SMB 공유에 연결할 수 있습니다.



ONTAP가 지원하는 Windows 클라이언트에 대한 최신 정보는 를 참조하십시오 link:https://mysupport.netapp.com/matrix["상호 운용성 매트릭스"].

[NOTE]
====
NT 도메인은 IPv6에서 지원되지 않습니다.

====


== 추가 CIFS 서비스 지원

ONTAP는 SMB 파일 공유 및 Active Directory 서비스에 대한 IPv6 지원 외에도 다음에 대한 IPv6 지원을 제공합니다.

* 오프라인 폴더, 로밍 프로필, 폴더 리디렉션 및 이전 버전을 포함한 클라이언트측 서비스입니다
* 동적 홈 디렉토리(홈 디렉토리 기능), symlink 및 Widelink, BranchCache, ODX 복사 오프로드, 자동 노드 추천 등의 서버 측 서비스 및 이전 버전
* Windows 로컬 사용자 및 그룹을 사용하여 액세스 제어 및 권한 관리, CLI를 사용한 파일 권한 및 감사 정책 설정, 보안 추적, 파일 잠금 관리, SMB 작업 모니터링 등의 파일 액세스 관리 서비스입니다
* NAS 멀티 프로토콜 감사
* FPolicy를 참조하십시오
* 지속적으로 사용 가능한 공유, Witness 프로토콜 및 원격 VSS(SMB 구성 기반 Hyper-V에 사용)




== 네임 서비스 및 인증 서비스 지원

IPv6에서는 다음 이름 서비스와의 통신이 지원됩니다.

* 도메인 컨트롤러
* DNS 서버
* LDAP 서버
* KDC 서버
* NIS 서버

