---
sidebar: sidebar 
permalink: smb-admin/windows-backup-symlinks.html 
keywords: windows, windows server, backup, backup application, symbolic link, symlink, unix, unix-style 
summary: 'Windows에서 실행 중인 백업 응용 프로그램이 Unix 스타일의 심볼 링크(symlink)를 발견하면 링크가 팔로우되고 데이터가 백업됩니다. ONTAP 9.15.1부터 데이터 대신 symlink를 백업할 수 있습니다. 이 기능은 ONTAP FlexGroups 및 FlexVols에서 완벽하게 지원됩니다.' 
---
= Windows 백업 애플리케이션 및 Unix 스타일 symlink
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Windows에서 실행 중인 백업 응용 프로그램이 Unix 스타일의 심볼 링크(symlink)를 발견하면 링크가 팔로우되고 데이터가 백업됩니다. ONTAP 9.15.1부터 데이터 대신 symlink를 백업할 수 있습니다. 이 기능은 ONTAP FlexGroups 및 FlexVols에서 완벽하게 지원됩니다.



== 개요

Windows 백업 작업 중에 ONTAP가 symlink를 처리하는 방식을 변경하기 전에 이점, 주요 개념 및 구성 옵션을 숙지해야 합니다.



=== 이점

이 기능을 비활성화하거나 사용할 수 없는 경우 각 symlink가 통과하고 링크되는 데이터가 백업됩니다. 이로 인해 불필요한 데이터가 백업될 수 있으며 특정 상황에서는 응용 프로그램이 루프로 끝날 수 있습니다. 대신 symlink를 백업하면 이러한 문제가 발생하지 않습니다. 또한 대부분의 경우 symlink 파일은 데이터에 비해 매우 작기 때문에 백업을 완료하는 데 걸리는 시간이 줄어듭니다. IO 작업이 감소하여 클러스터의 전반적인 성능도 향상됩니다.



=== Windows 서버 환경

이 기능은 Windows에서 실행되는 백업 응용 프로그램에 대해 지원됩니다. 환경을 사용하기 전에 환경의 기술적 측면을 이해해야 합니다.

.확장 속성
Windows는 파일과 선택적으로 연결되는 추가 메타데이터를 집합적으로 형성하는 EA(확장 특성)를 지원합니다. 이러한 속성은 에 설명된 대로 Linux용 Windows 하위 시스템과 같은 다양한 응용 프로그램에서 https://learn.microsoft.com/en-us/windows/wsl/file-permissions["WSL에 대한 파일 권한"^]사용됩니다. 응용 프로그램은 ONTAP에서 데이터를 읽을 때 각 파일에 대해 확장 속성을 요청할 수 있습니다.

이 기능이 설정되면 symlink가 확장 속성에서 반환됩니다. 따라서 백업 애플리케이션은 메타데이터를 저장하는 데 사용되는 표준 EA 지원을 제공해야 합니다. 일부 Windows 유틸리티는 확장 속성을 지원하고 유지합니다. 그러나 백업 소프트웨어가 확장 속성의 백업 및 복구를 지원하지 않는 경우 각 파일과 연결된 메타데이터가 보존되지 않으며 symlink를 제대로 처리하지 못합니다.

.Windows 구성
Microsoft Windows 서버에서 실행되는 백업 응용 프로그램에는 일반 파일 보안을 우회할 수 있는 특별한 권한이 부여될 수 있습니다. 이 작업은 일반적으로 Backup Operators 그룹에 응용 프로그램을 추가하여 수행합니다. 그런 다음 앱은 필요에 따라 파일을 백업 및 복원할 수 있을 뿐만 아니라 다른 관련 시스템 작업을 수행할 수 있습니다. 백업 애플리케이션에서 사용하는 SMB 프로토콜은 ONTAP에서 데이터를 읽고 쓸 때 감지할 수 있는 것처럼 약간만 변경되었습니다.



=== 요구 사항

symlink 백업 기능에는 다음과 같은 몇 가지 요구 사항이 있습니다.

* 클러스터에서 ONTAP 9.15.1 이상이 실행되고 있습니다.
* 특수 백업 권한이 부여된 Windows 백업 응용 프로그램입니다.
* 또한 백업 애플리케이션은 확장 속성을 지원하고 백업 작업 중에 이를 요청해야 합니다.
* ONTAP symlink 백업 기능은 해당 데이터 SVM에 대해 활성화됩니다.




=== 구성 옵션

ONTAP CLI 외에도 REST API를 사용하여 이 기능을 관리할 수 있습니다. 자세한 내용은 을 https://docs.netapp.com/us-en/ontap-automation/whats-new.html["ONTAP REST API 및 자동화의 새로운 기능"^] 참조하십시오. ONTAP가 Unix 스타일 심링크를 처리하는 방식을 결정하는 구성은 SVM별로 별도로 수행해야 합니다.



== ONTAP에서 symlink 백업 기능을 활성화합니다

ONTAP 9.15.1을 사용하는 기존 CLI 명령에 구성 옵션이 도입되었습니다. 이 옵션을 사용하여 Unix 스타일의 symlink 처리를 활성화하거나 비활성화할 수 있습니다.

.시작하기 전에
기본을 <<요구 사항>>검토합니다. 추가 사항:

* CLI 권한을 고급 수준으로 높일 수 있습니다.
* 수정할 데이터 SVM을 결정합니다. SVM `vs1` 은 예 명령에 사용됩니다.


.단계
. advanced 권한 수준을 설정합니다.
+
[source, cli]
----
set privilege advanced
----
. symlink 파일 백업을 활성화합니다.
+
[source, cli]
----
vserver cifs options modify -vserver vs1 -is-backup-symlink-enabled true
----

