---
permalink: mediator/enable-access-repos-task.html 
sidebar: sidebar 
keywords: mediator, new, release, update, install, 
summary: ONTAP 중재자가 설치 프로세스 중에 필요한 패키지에 액세스할 수 있도록 리포지토리에 대한 액세스를 활성화합니다. 
---
= 리포지토리에 대한 액세스를 활성화합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 중재자가 설치 프로세스 중에 필요한 패키지에 액세스할 수 있도록 저장소에 대한 액세스를 활성화해야 합니다

.단계
. 다음 표와 같이 액세스해야 하는 리포지토리를 결정합니다.
+
[cols="35,65"]
|===


| 운영 체제가... | 이러한 리포지토리에 대한 액세스를 제공해야 합니다... 


 a| 
RHEL 7.x를 참조하십시오
 a| 
** RHEL-7-server-optional-rpms




 a| 
RHEL 8.x를 참조하십시오
 a| 
** RHEL-8-for-x86_64-baseos-rpms
** RHEL-8-for-x86_64-appstream-rpms




 a| 
RHEL 9.x를 참조하십시오
 a| 
** RHEL-9-for-x86_64-baseos-rpms
** RHEL-9-for-x86_64-appstream-rpms




 a| 
CentOS 7.x
 a| 
** C7.6.1810 - 기본 리포지토리입니다




 a| 
Rocky Linux 8
 a| 
** 애플리케이션 스트림
** 베이스코스




 a| 
록키 리눅스 9
 a| 
** 애플리케이션 스트림
** 베이스코스


|===
. 다음 절차 중 하나를 사용하여 위에 나열된 리포지토리에 액세스할 수 있으므로 ONTAP 중재자가 설치 프로세스 중에 필요한 패키지에 액세스할 수 있습니다.



NOTE: ONTAP mediator가 "추가" 및 "옵션" 리포지토리에 있는 Python 모듈에 종속성이 있는 경우 에 액세스해야 할 수 있습니다 `rhel-X-for-x86_64-extras-rpms` 및 `rhel-X-for-x86_64-optional-rpms` 파일.

.RHEL 7.x 운영 체제에 대한 절차
[#rhel7x%collapsible]
====
운영 체제가 * RHEL 7.x * 인 경우 다음 절차를 사용하여 리포지토리에 액세스할 수 있습니다.

.단계
. 필요한 리포지토리 구독:
+
'Subscription-manager Repos - -enable rhel-7-server-optional-rpms'

+
다음 예제에서는 이 명령의 실행을 보여 줍니다.

+
[listing]
----
[root@localhost ~]# subscription-manager repos --enable rhel-7-server-optional-rpms
Repository 'rhel-7-server-optional-rpms' is enabled for this system.
----
. yum repolist 명령을 실행합니다.
+
다음 예제에서는 이 명령의 실행을 보여 줍니다. "rhel-7-server-optional-rpms" 리포지토리가 목록에 나타나야 합니다.

+
[listing]
----
[root@localhost ~]# yum repolist
Loaded plugins: product-id, search-disabled-repos, subscription-manager
rhel-7-server-optional-rpms | 3.2 kB  00:00:00
rhel-7-server-rpms | 3.5 kB  00:00:00
(1/3): rhel-7-server-optional-rpms/7Server/x86_64/group              |  26 kB  00:00:00
(2/3): rhel-7-server-optional-rpms/7Server/x86_64/updateinfo         | 2.5 MB  00:00:00
(3/3): rhel-7-server-optional-rpms/7Server/x86_64/primary_db         | 8.3 MB  00:00:01
repo id                                      repo name                                             status
rhel-7-server-optional-rpms/7Server/x86_64   Red Hat Enterprise Linux 7 Server - Optional (RPMs)   19,447
rhel-7-server-rpms/7Server/x86_64            Red Hat Enterprise Linux 7 Server (RPMs)              26,758
repolist: 46,205
[root@localhost ~]#
----


====
.RHEL 8.x 운영 체제에 대한 절차
[#rhel8x%collapsible]
====
운영 체제가 * RHEL 8.x * 인 경우 다음 절차를 사용하여 리포지토리에 액세스할 수 있습니다.

.단계
. 필요한 리포지토리 구독:
+
'Subscription-manager Repos -- rhel-8-for-x86_64-baseos-rpms'를 활성화합니다

+
'Subscription-manager Repos - -enable rhel-8-for-x86_64-appstream-rpms'

+
다음 예제에서는 이 명령의 실행을 보여 줍니다.

+
[listing]
----
[root@localhost ~]# subscription-manager repos --enable rhel-8-for-x86_64-baseos-rpms
Repository 'rhel-8-for-x86_64-baseos-rpms' is enabled for this system.
[root@localhost ~]# subscription-manager repos --enable rhel-8-for-x86_64-appstream-rpms
Repository 'rhel-8-for-x86_64-appstream-rpms' is enabled for this system.
----
. yum repolist 명령을 실행합니다.
+
새로 가입된 리포지토리가 목록에 나타납니다.



====
.RHEL 9.x 운영 체제에 대한 절차
[#rhel9x%collapsible]
====
운영 체제가 * RHEL 9.x * 인 경우 다음 절차를 사용하여 리포지토리에 액세스할 수 있습니다.

.단계
. 필요한 리포지토리 구독:
+
`subscription-manager repos --enable rhel-9-for-x86_64-baseos-rpms`

+
`subscription-manager repos --enable rhel-9-for-x86_64-appstream-rpms`

+
다음 예제에서는 이 명령의 실행을 보여 줍니다.

+
[listing]
----
[root@localhost ~]# subscription-manager repos --enable rhel-9-for-x86_64-baseos-rpms
Repository 'rhel-9-for-x86_64-baseos-rpms' is enabled for this system.
[root@localhost ~]# subscription-manager repos --enable rhel-9-for-x86_64-appstream-rpms
Repository 'rhel-9-for-x86_64-appstream-rpms' is enabled for this system.
----
. yum repolist 명령을 실행합니다.
+
새로 가입된 리포지토리가 목록에 나타납니다.



====
.CentOS 7.x 운영 체제에 대한 절차
[#centos7x%collapsible]
====
운영 체제가 * CentOS 7.x * 인 경우 리포지토리에 대한 액세스를 활성화하려면 다음 절차를 따르십시오.


NOTE: 다음 예는 CentOS 7.6의 리포지토리를 보여 주고 있으며 다른 CentOS 버전에서는 작동하지 않을 수 있습니다. 사용 중인 CentOS 버전에 대한 기본 리포지토리를 사용합니다.

.단계
. C7.6.1810-Base 리포지토리를 추가합니다. C7.6.1810 - 기본 볼트 리포지토리에는 ONTAP 중재자를 위해 필요한 "kernel-devel" 패키지가 포함되어 있습니다.
. /etc/yum.repos.d/CentOS-Vault.repo에 다음 줄을 추가합니다.
+
[listing]
----
[C7.6.1810-base]
name=CentOS-7.6.1810 - Base
baseurl=http://vault.centos.org/7.6.1810/os/$basearch/
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
enabled=1
----
. yum repolist 명령을 실행합니다.
+
다음 예제에서는 이 명령의 실행을 보여 줍니다. CentOS-7.6.1810-기본 리포지토리가 목록에 나타나야 합니다.

+
[listing]
----
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: distro.ibiblio.org
 * extras: distro.ibiblio.org
 * updates: ewr.edge.kernel.org
C7.6.1810-base                                 | 3.6 kB  00:00:00
(1/2): C7.6.1810-base/x86_64/group_gz          | 166 kB  00:00:00
(2/2): C7.6.1810-base/x86_64/primary_db        | 6.0 MB  00:00:04
repo id                      repo name               status
C7.6.1810-base/x86_64        CentOS-7.6.1810 - Base  10,019
base/7/x86_64                CentOS-7 - Base         10,097
extras/7/x86_64              CentOS-7 - Extras       307
updates/7/x86_64             CentOS-7 - Updates      1,010
repolist: 21,433
[root@localhost ~]#
----


====
.Rocky Linux 8 또는 9 운영 체제에 대한 절차
[#rocky-linux-8-9%collapsible]
====
운영 체제가 * Rocky Linux 8 * 또는 * Rocky Linux 9 * 인 경우 다음 절차를 사용하여 리포지토리에 액세스할 수 있습니다.

.단계
. 필요한 리포지토리 구독:
+
`dnf config-manager --set-enabled baseos`

+
`dnf config-manager --set-enabled appstream`

. 을 수행합니다 `clean` 작동:
+
`dnf clean all`

. 리포지토리 목록을 확인합니다.
+
`dnf repolist`



....
[root@localhost ~]# dnf config-manager --set-enabled baseos
[root@localhost ~]# dnf config-manager --set-enabled appstream
[root@localhost ~]# dnf clean all
[root@localhost ~]# dnf repolist
repo id                        repo name
appstream                      Rocky Linux 8 - AppStream
baseos                         Rocky Linux 8 - BaseOS
[root@localhost ~]#
....
....
[root@localhost ~]# dnf config-manager --set-enabled baseos
[root@localhost ~]# dnf config-manager --set-enabled appstream
[root@localhost ~]# dnf clean all
[root@localhost ~]# dnf repolist
repo id                        repo name
appstream                      Rocky Linux 9 - AppStream
baseos                         Rocky Linux 9 - BaseOS
[root@localhost ~]#
....
====