---
permalink: mediator/host-maintenance-task.html 
sidebar: sidebar 
keywords: mediator, maintain, host, maintenance, package update, kernal upgrade, change hostname, change IP, self-signed certificate, self signed certificate 
summary: 최적의 성능을 위해 ONTAP 중재자를 위한 호스트 OD를 정기적으로 유지해야 합니다. 
---
= ONTAP 중재자를 위한 OS 호스트 유지
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
최적의 성능을 위해서는 ONTAP 중재자를 위한 호스트 OS를 정기적으로 유지 관리해야 합니다.



== 호스트를 재부팅합니다

클러스터가 정상 상태일 때 호스트를 재부팅합니다. ONTAP 중재자가 오프라인 상태인 경우 클러스터가 실패에 적절히 대응하지 못할 위험이 있습니다. 재부팅이 필요한 경우 서비스 창을 사용하는 것이 좋습니다.

ONTAP 중재자는 재부팅 중에 자동으로 재개되며 이전에 ONTAP 클러스터로 구성된 관계를 다시 시작합니다.



== 호스트 패키지 업데이트

모든 라이브러리 또는 yum 패키지(커널 제외)는 안전하게 업데이트할 수 있지만 재부팅해야 적용됩니다. 재부팅이 필요한 경우 서비스 창을 사용하는 것이 좋습니다.

를 설치하는 경우 `yum-utils` 패키지를 사용하려면 를 사용합니다 `needs-restarting` 명령을 사용하여 패키지 변경 사항을 탐지하려면 재부팅해야 합니다.

ONTAP 중재 종속성이 업데이트되면 실행 중인 프로세스에 즉시 영향을 미치지 않으므로 재부팅해야 합니다.



== 호스트 OS 부 커널 업그레이드

사용 중인 커널에 대해 SCST를 컴파일해야 합니다. OS를 업데이트하려면 유지 관리 기간이 필요합니다.

.단계
호스트 OS 커널을 업그레이드하려면 다음 단계를 수행하십시오.

. ONTAP 중재자를 중지합니다
. SCST 패키지를 제거합니다. (SCST는 업그레이드 메커니즘을 제공하지 않습니다.)
. OS를 업그레이드하고 재부팅합니다.
. SCST 패키지를 다시 설치합니다.
. ONTAP 중재자 서비스를 다시 활성화합니다.




== 호스트가 호스트 이름 또는 IP로 변경됩니다

.이 작업에 대해
* ONTAP 중재자 서비스가 설치된 Linux 호스트에서 이 작업을 수행합니다.
* ONTAP 중재자를 설치한 후 호스트의 호스트 이름 또는 IP 주소가 변경되어 생성된 자체 서명된 인증서가 사용되지 않는 경우에만 이 작업을 수행할 수 있습니다.
* 임시 자체 서명된 인증서가 신뢰할 수 있는 타사 인증서로 대체되면 이 작업을 사용하여 인증서를 다시 생성합니다.  자체 서명된 인증서가 없으면 이 절차가 실패합니다.


.단계
현재 호스트에 대해 자체 서명된 새 임시 인증서를 다시 생성하려면 다음 단계를 수행하십시오.

. ONTAP 중재자 다시 시작:
+
`./make_self_signed_certs.sh overwrite`

+
[listing]
----
[root@xyz000123456 ~]# cd /opt/netapp/lib/ontap_mediator/ontap_mediator/server_config
[root@xyz000123456 server_config]# ./make_self_signed_certs.sh overwrite

Adding Subject Alternative Names to the self-signed server certificate
#
# OpenSSL example configuration file.
Generating self-signed certificates
Generating RSA private key, 4096 bit long modulus (2 primes)
..................................................................................................................................................................++++
........................................................++++
e is 65537 (0x010001)
Generating a RSA private key
................................................++++
.............................................................................................................................................++++
writing new private key to 'ontap_mediator_server.key'
-----
Signature ok
subject=C = US, ST = California, L = San Jose, O = "NetApp, Inc.", OU = ONTAP Core Software, CN = ONTAP Mediator, emailAddress = support@netapp.com
Getting CA Private Key

[root@xyz000123456 server_config]# systemctl restart ontap_mediator
----

