---
permalink: mediator/index.html 
sidebar: sidebar 
keywords: ontap mediator service, install requirements, mediator requirements 
summary: ONTAP 중재자 서비스를 설치하려면 모든 필수 구성 요소가 충족되었는지 확인하고 설치 패키지를 얻고 호스트에서 설치 관리자를 실행해야 합니다. 
---
= ONTAP 중재자 서비스를 설치하거나 업그레이드할 준비를 합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 중재자 서비스를 설치하려면 모든 필수 구성 요소가 충족되었는지 확인하고 설치 패키지를 가져와 호스트에서 설치 관리자를 실행해야 합니다. 이 절차는 기존 설치의 설치 또는 업그레이드에 사용됩니다.

* ONTAP 9.7부터 모든 버전의 ONTAP 중재자를 사용하여 MetroCluster IP 구성을 모니터링할 수 있습니다.
* ONTAP 9.8부터는 모든 버전의 ONTAP Mediator를 사용하여 SnapMirror 활성 동기화 관계를 모니터링할 수 있습니다.




== 설치 및 업그레이드 고려 사항

ONTAP 중재자를 업그레이드 또는 설치하기 전에 다음 고려 사항을 검토하십시오.


CAUTION: ONTAP mediator 1.8 및 이전 버전은 Red Hat Enterprise Linux FIPS 모드와 호환되지 않으므로 설치가 실패합니다. 명령을 사용하여 FIPS 모드가 활성화되어 있는지 확인할 수 `fips-mode-setup --check` 있습니다. 명령을 사용하여 FIPS 모드를 사용하지 않도록 설정할 수 `fips-modesetup --disable` 있습니다. ONTAP mediator 1.8 이하를 성공적으로 설치하려면 FIPS 모드를 비활성화한 후 재부팅합니다.

* ONTAP mediator를 사용 가능한 최신 버전으로 업그레이드해야 합니다. 이전 버전의 ONTAP Mediator는 모든 ONTAP 버전과 역호환성을 유지하지만 최신 버전에는 모든 타사 요소에 대한 보안 패치가 포함되어 있습니다.
* 새 ONTAP 중재자 버전으로 업그레이드할 때 더 높은 버전을 사용할 수 없는 경우 설치 관리자는 자동으로 권장 SCST 버전으로 업그레이드합니다. 더 높은 SCST 버전을 수동으로 설치하는 방법은 을 참조하십시오link:manage-task.html["중재자 서비스를 관리합니다"]. 지원되는 버전은 를 link:whats-new-concept.html#scst-support-matrix["SCST 지원 매트릭스"]참조하십시오.
+

CAUTION: 설치에 실패하면 최신 버전의 ONTAP Mediator로 업그레이드해야 할 수 있습니다.

* 를 설치하는 경우 `yum-utils` 패키지를 사용하면 을 사용할 수 있습니다 `needs-restarting` 명령.




=== OS 요구 사항

운영 체제는 다음 요구 사항을 충족해야 합니다.

* 64비트 물리적 설치 또는 가상 머신
* 8GB RAM
* 1GB 디스크 공간(응용 프로그램 설치, 서버 로그 및 데이터베이스에 사용됨)
* 사용자: 루트 액세스


다음 표는 각 ONTAP 중재자 버전에 대해 지원되는 운영 체제를 보여줍니다.

[cols="30,70"]
|===


| ONTAP 중재자 버전 | 지원되는 Linux 버전 


 a| 
1.9
 a| 
* Red Hat Enterprise Linux
+
** 호환되는 버전: 8.4, 8.5, 8.6, 8.7, 8.9, 9.1 및 9.3 1
** 권장: 8.8, 8.10, 9.0, 9.2, 9.4 및 9.5


* Rocky Linux 8 및 9




 a| 
1.8
 a| 
* Red Hat Enterprise Linux: 8.4, 8.5, 8.6, 8.7, 8.8, 8.9, 8.10, 9.0, 9.1, 9.2, 9.3 및 9.4
* Rocky Linux 8 및 9




 a| 
1.7
 a| 
* Red Hat Enterprise Linux: 8.4, 8.5, 8.6, 8.7, 8.8, 8.9, 9.0, 9.1, 9.2 및 9.3
* Rocky Linux 8 및 9




 a| 
1.6
 a| 
* Red Hat Enterprise Linux: 8.4, 8.5, 8.6, 8.7, 8.8, 9.0, 9.1, 9.2
* Rocky Linux 8 및 9




 a| 
1.5
 a| 
* Red Hat Enterprise Linux: 7.6, 7.7, 7.8, 7.9, 8.0, 8.1, 8.2, 8.3, 8.4, 8.5
* CentOS: 7.6, 7.7, 7.8, 7.9




 a| 
1.4
 a| 
* Red Hat Enterprise Linux: 7.6, 7.7, 7.8, 7.9, 8.0, 8.1, 8.2, 8.3, 8.4, 8.5
* CentOS: 7.6, 7.7, 7.8, 7.9




 a| 
1.3
 a| 
* Red Hat Enterprise Linux: 7.6, 7.7, 7.8, 7.9, 8.0, 8.1, 8.2, 8.3
* CentOS: 7.6, 7.7, 7.8, 7.9




 a| 
1.2
 a| 
* Red Hat Enterprise Linux: 7.6, 7.7, 7.8, 7.9, 8.0, 8.1
* CentOS: 7.6, 7.7, 7.8, 7.9


|===
. 호환되는 것은 RHEL이 더 이상 이 버전을 지원하지 않지만 ONTAP mediator는 계속 설치할 수 있다는 의미입니다.




=== OS 업그레이드 고려 사항 및 커널 호환성

* 커널을 제외한 모든 라이브러리 패키지는 안전하게 업데이트할 수 있지만 ONTAP 중재자 응용 프로그램 내에서 변경 사항을 적용하려면 재부팅해야 할 수 있습니다. 재부팅이 필요한 경우 서비스 창을 사용하는 것이 좋습니다.
* OS 커널을 최신 상태로 유지해야 합니다. 커널 코어는 에서 지원되는 버전으로 업그레이드할 수 link:whats-new-concept.html#scst-support-matrix["ONTAP 중재자 버전 매트릭스"]있습니다. 재부팅은 반드시 필요하므로 운영 중단을 위한 유지보수 창을 계획해야 합니다.
+
** 재부팅하기 전에 SCST 커널 모듈을 제거한 후 다시 설치해야 합니다.
** 커널 OS 업그레이드를 시작하기 전에 지원되는 버전의 SCST를 재설치할 준비가 되어 있어야 합니다.




[NOTE]
====
* 커널 버전이 운영 체제 버전과 일치해야 합니다.
* 특정 ONTAP mediator 릴리스에 대해 지원되는 OS 릴리스 이후에 커널로 업그레이드하는 것은 지원되지 않습니다. (이는 테스트된 SCST 모듈이 컴파일되지 않음을 의미할 수 있습니다).


====


== UEFI 보안 부팅이 활성화된 경우 보안 키를 등록합니다

UEFI 보안 부팅이 활성화된 ONTAP 중재자를 설치하려면 서비스를 시작하기 전에 보안 키를 등록해야 합니다. 이 키는 SCST 설치의 컴파일 단계 중에 생성되며 컴퓨터에 개인 공개 키 쌍으로 저장됩니다. 유틸리티를 사용하여 `mokutil` 공개 키를 UEFI 펌웨어에 컴퓨터 소유자 키(Mok)로 추가하여 시스템이 서명된 모듈을 신뢰하고 로드할 수 있도록 합니다.  `mokutil`Mok를 활성화하기 위해 시스템을 재부팅할 때 필요하므로 암호를 안전한 위치에 저장합니다.

시스템이 UEFI를 사용하고 보안 부팅이 켜져 있는지 확인하려면 다음 단계를 수행하십시오.

.단계
. 이 설치되어 있지 않으면 `mokutil` 다음 명령을 실행합니다.
+
`yum install mokutil`

. 시스템에서 UEFI 보안 부팅이 활성화되어 있는지 확인합니다.
+
`mokutil --sb-state`

+
결과는 이 시스템에서 UEFI 보안 부팅이 활성화되었는지 여부를 나타냅니다.

+
[NOTE]
====
** 보안 위치에 저장해야 하는 암호를 만들라는 메시지가 표시됩니다. UEFI 부팅 관리자에서 키를 활성화하려면 이 암호가 필요합니다.
** ONTAP 중재자 1.2.0 및 이전 버전은 이 모드를 지원하지 않습니다.


====
. Mok 목록에 공개 키를 추가합니다.
+
`mokutil --import /opt/netapp/lib/ontap_mediator/ontap_mediator/SCST_mod_keys/scst_module_key.der`

+

NOTE: 개인 키를 기본 위치에 두거나 안전한 위치로 이동할 수 있습니다. 그러나 공개 키는 부팅 관리자에서 사용할 수 있도록 기존 위치에 유지되어야 합니다. 자세한 내용은 다음 README.module-signing 파일을 참조하십시오.

+
`[root@hostname ~]# ls /opt/netapp/lib/ontap_mediator/ontap_mediator/SCST_mod_keys/
README.module-signing  scst_module_key.der  scst_module_key.priv`

. 호스트를 재부팅하고 장치의 UEFI 부팅 관리자를 사용하여 새 Mok을 승인합니다. 2단계에서 에 대해 제공된 암호가 `mokutil` 필요합니다.




== UEFI 보안 부팅을 비활성화합니다

ONTAP mediator를 설치하기 전에 UEFI 보안 부팅을 비활성화하도록 선택할 수도 있습니다.

.단계
. 물리적 시스템 BIOS 설정에서 "UEFI 보안 부팅" 옵션을 비활성화합니다.
. VM에 대한 VMware 설정에서 vSphere 6.x에 대한 "Safe Start" 옵션 또는 vSphere 7.x에 대한 "Secure Boot" 옵션을 비활성화합니다

