---
permalink: mediator/index.html 
sidebar: sidebar 
keywords: ontap mediator service, install requirements, mediator requirements 
summary: ONTAP 중재자 서비스를 설치하려면 모든 필수 구성 요소가 충족되었는지 확인하고 설치 패키지를 얻고 호스트에서 설치 관리자를 실행해야 합니다. 
---
= ONTAP 중재자 서비스를 설치하거나 업그레이드할 준비를 합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 중재자 서비스를 설치하려면 모든 필수 구성 요소가 충족되었는지 확인하고 설치 패키지를 얻고 호스트에서 설치 관리자를 실행해야 합니다. 이 절차는 기존 설치의 설치 또는 업그레이드에 사용됩니다.

* ONTAP 9.7부터 모든 버전의 ONTAP 중재자를 사용하여 MetroCluster IP 구성을 모니터링할 수 있습니다.
* ONTAP 9.8부터는 모든 버전의 ONTAP 중재자를 사용하여 SM-BC 관계를 모니터링할 수 있습니다.


.시작하기 전에
다음 필수 조건을 충족해야 합니다.

[cols="30,70"]
|===


| ONTAP 중재자 버전 | 지원되는 Linux 버전 


 a| 
1.6
 a| 
* Red Hat Enterprise Linux: 8.4, 8.5, 8.6, 8.7, 8.8, 9.0, 9.1, 9.2
* Rocky Linux 8 및 9




 a| 
1.5
 a| 
* Red Hat Enterprise Linux: 7.6, 7.7, 7.8, 7.9, 8.1, 8.2, 8.3, 8.4, 8.5
* CentOS: 7.6, 7.7, 7.8, 7.9




 a| 
1.4
 a| 
* Red Hat Enterprise Linux: 7.6, 7.7, 7.8, 7.9, 8.1, 8.2, 8.3, 8.4, 8.5
* CentOS: 7.6, 7.7, 7.8, 7.9




 a| 
1.3
 a| 
* Red Hat Enterprise Linux: 7.6, 7.7, 7.8, 7.9, 8.1, 8.2, 8.3
* CentOS: 7.6, 7.7, 7.8, 7.9




 a| 
1.2
 a| 
* Red Hat Enterprise Linux: 7.6, 7.7, 7.8, 8.1
* CentOS: 7.6, 7.7, 7.8


|===

NOTE: 커널 버전이 운영 체제 버전과 일치해야 합니다.

* 64비트 물리적 설치 또는 가상 머신
* 8GB RAM
* 사용자: 루트 액세스


커널을 제외한 모든 라이브러리 패키지는 안전하게 업데이트할 수 있지만 ONTAP 중재자 응용 프로그램 내에서 영향을 받기 위해 재부팅이 필요할 수 있습니다. 재부팅이 필요한 경우 서비스 창을 사용하는 것이 좋습니다.

를 설치하는 경우 `yum-utils` 패키지를 사용하면 을 사용할 수 있습니다 `needs-restarting` 명령.

커널 코어는 ONTAP 중재자 버전 매트릭스에서 지원하는 버전으로 업데이트할 경우 업데이트할 수 있습니다. 재부팅이 필수이므로 서비스 기간이 필요합니다.

재부팅 전에 SCST 커널 모듈을 제거한 다음 재부팅 후 다시 설치해야 합니다.


NOTE: 특정 ONTAP 중재자 릴리스에 대해 지원되는 OS 릴리스 이외의 커널로 업그레이드하는 것은 지원되지 않습니다. (이는 테스트된 SCST 모듈이 컴파일되지 않는다는 의미일 수 있습니다.)
