---
permalink: mediator/manage-task.html 
sidebar: sidebar 
keywords: mediator, username, password, change, uninstall 
summary: ONTAP 중재자 서비스를 설치한 후 사용자 이름 또는 암호를 변경할 수 있습니다. ONTAP 중재자 서비스를 제거할 수도 있습니다. 
---
= ONTAP 중재자 서비스를 관리합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 중재자 서비스를 설치한 후 사용자 이름 또는 암호를 변경할 수 있습니다. ONTAP 중재자 서비스를 제거할 수도 있습니다.



== 사용자 이름을 변경합니다

.수행할 수 있습니다
이러한 작업은 ONTAP 중재자 서비스가 설치된 Linux 호스트에서 수행됩니다.

이 명령에 액세스할 수 없는 경우 다음 예에 표시된 대로 전체 경로를 사용하여 명령을 실행해야 할 수 있습니다.

'/usr/local/bin/중재자_username'

.절차를 참조하십시오
다음 옵션 중 하나를 선택하여 사용자 이름을 변경합니다.

* 다음 예제와 같이 중재자_change_user 명령을 실행하고 프롬프트에 응답합니다.
+
....
 [root@mediator-host ~]# mediator_change_user
 Modify the Mediator API username by entering the following values:
     Mediator API User Name: mediatoradmin
                   Password:
 New Mediator API User Name: mediator
 The account username has been modified successfully.
 [root@mediator-host ~]#
....
* 다음 명령을 실행합니다.
+
MDIATOR_USERNAME=중재자_PASSWORD=mediator2 MEDIATOR_NEW_USERNAME=mediatoradmin 중재자_CHANGE_USER

+
....
 [root@mediator-host ~]# MEDIATOR_USERNAME= mediator MEDIATOR_PASSWORD='mediator2' MEDIATOR_NEW_USERNAME= mediatoradmin mediator_change_user
 The account username has been modified successfully.
 [root@mediator-host ~]#
....




== 암호를 변경합니다

.이 작업에 대해
이 작업은 ONTAP 중재자 서비스가 설치된 Linux 호스트에서 수행됩니다.

이 명령에 액세스할 수 없는 경우 다음 예에 표시된 대로 전체 경로를 사용하여 명령을 실행해야 할 수 있습니다.

'/usr/local/bin/중재자_change_password'

.절차를 참조하십시오
다음 옵션 중 하나를 선택하여 암호를 변경합니다.

* 'edator_change_password' 명령어를 실행하여 다음 예와 같이 프롬프트에 응답한다.
+
....
 [root@mediator-host ~]# mediator_change_password
 Change the Mediator API password by entering the following values:
    Mediator API User Name: mediatoradmin
              Old Password:
              New Password:
          Confirm Password:
 The password has been updated successfully.
 [root@mediator-host ~]#
....
* 다음 명령을 실행합니다.
+
MDIATOR_USERNAME=mediatoradmin MEDIA_PASSWORD=mediator1 MEDIATOR_NEW_PASSWORD=mediator2 MEDIATOR_CHANGE_PASSWORD"

+
이 예제에서는 암호가 "mediator1"에서 "mediator2"로 변경되었음을 보여 줍니다.

+
....
 [root@mediator-host ~]# MEDIATOR_USERNAME=mediatoradmin MEDIATOR_PASSWORD=mediator1 MEDIATOR_NEW_PASSWORD=mediator2 mediator_change_password
 The password has been updated successfully.
 [root@mediator-host ~]#
....




== ONTAP 중재자 서비스를 중지합니다

ONTAP 중재자 서비스를 중지하려면 다음 단계를 수행하십시오.

.단계
. ONTAP 중재자를 중지합니다.
+
`systemctl stop ontap_mediator`

. SCST를 중지합니다.
+
`systemctl stop mediator-scst`

. ONTAP 중재자 및 SCST를 비활성화합니다.
+
`systemctl diable ontap_mediator mediator-scst`





== ONTAP 중재자 서비스를 다시 활성화합니다

ONTAP 중재자 서비스를 다시 활성화하려면 다음 단계를 수행하십시오.

.단계
. ONTAP 중재자 및 SCST를 활성화합니다.
+
`systemctl enable ontap_mediator mediator-scst`

. SCST를 시작합니다.
+
`systemctl start mediator-scst`

. ONTAP 중재자 시작
+
`systemctl start ontap_mediator`





== ONTAP 중재자가 양호한 상태인지 확인합니다

ONTAP 중재자를 설치한 후에는 ONTAP 중재자 서비스가 실행 중인지 확인해야 합니다.

.단계
. ONTAP 중재자 서비스 상태 보기:
+
.. `systemctl status ontap_mediator`
+
[listing]
----
[root@scspr1915530002 ~]# systemctl status ontap_mediator

 ontap_mediator.service - ONTAP Mediator
Loaded: loaded (/etc/systemd/system/ontap_mediator.service; enabled; vendor preset: disabled)
Active: active (running) since Mon 2022-04-18 10:41:49 EDT; 1 weeks 0 days ago
Process: 286710 ExecStop=/bin/kill -s INT $MAINPID (code=exited, status=0/SUCCESS)
Main PID: 286712 (uwsgi)
Status: "uWSGI is ready"
Tasks: 3 (limit: 49473)
Memory: 139.2M
CGroup: /system.slice/ontap_mediator.service
      ├─286712 /opt/netapp/lib/ontap_mediator/pyenv/bin/uwsgi --ini /opt/netapp/lib/ontap_mediator/uwsgi/ontap_mediator.ini
      ├─286716 /opt/netapp/lib/ontap_mediator/pyenv/bin/uwsgi --ini /opt/netapp/lib/ontap_mediator/uwsgi/ontap_mediator.ini
      └─286717 /opt/netapp/lib/ontap_mediator/pyenv/bin/uwsgi --ini /opt/netapp/lib/ontap_mediator/uwsgi/ontap_mediator.ini

[root@scspr1915530002 ~]#
----
.. `systemctl status mediator-scst`
+
[listing]
----
[root@scspr1915530002 ~]# systemctl status mediator-scst
   Loaded: loaded (/etc/systemd/system/mediator-scst.service; enabled; vendor preset: disabled)
   Active: active (running) since Mon 2022-04-18 10:41:47 EDT; 1 weeks 0 days ago
  Process: 286595 ExecStart=/etc/init.d/scst start (code=exited, status=0/SUCCESS)
 Main PID: 286662 (iscsi-scstd)
    Tasks: 1 (limit: 49473)
   Memory: 1.2M
   CGroup: /system.slice/mediator-scst.service
           └─286662 /usr/local/sbin/iscsi-scstd

[root@scspr1915530002 ~]#
----


. ONTAP 중재자 서비스에서 사용하는 포트를 확인합니다.
+
`netstat`

+
[listing]
----
[root@scspr1905507001 ~]# netstat -anlt | grep -E '3260|31784'

         tcp   0   0 0.0.0.0:31784   0.0.0.0:*      LISTEN

         tcp   0   0 0.0.0.0:3260    0.0.0.0:*      LISTEN

         tcp6  0   0 :::3260         :::*           LISTEN
----




== 호스트 유지 관리를 수행하려면 SCST를 수동으로 제거합니다

SCST를 제거하려면 설치된 ONTAP 중재자 버전에 사용되는 SCST tar 번들이 필요합니다.

.단계
. 다음 표와 같이 적절한 SCST 번들을 다운로드하여 압축을 풉니다.
+
[cols="50,50"]
|===


| 이 버전의 경우... | 이 tar 번들을 사용합니다... 


 a| 
ONTAP 중재자 1.0
 a| 
scst - 3.3.0.tar.bz2



 a| 
ONTAP 중재자 1.1
 a| 
scst - 3.4.0.tar.bz2



 a| 
ONTAP 중재자 1.2
 a| 
scst - 3.4.0.tar.bz2



 a| 
ONTAP 중재자 1.3
 a| 
scst - 3.5.0.tar.bz2



 a| 
ONTAP 중재자 1.4
 a| 
scst - 3.6.0.tar.bz2



 a| 
ONTAP 중재자 1.5
 a| 
scst - 3.6.0.tar.bz2



 a| 
ONTAP 중재자 1.6
 a| 
scst - 3.7.0.tar.bz2

|===
. "scst" 디렉토리에서 다음 명령을 실행합니다.
+
.. `systemctl stop mediator-scst`
.. `make scstadm_uninstall`
.. `make iscsi_uninstall`
.. `make usr_uninstall`
.. `make scst_uninstall`
.. `depmod`






== SCST를 수동으로 설치하여 호스트 유지 관리를 수행합니다

SCST를 수동으로 설치하려면 설치된 ONTAP 중재자 버전에 사용되는 SCST tar 번들이 필요합니다( 참조) <<scst-bundle-table,위 표>>)를 클릭합니다.

. "scst" 디렉토리에서 다음 명령을 실행합니다.
+
.. `make 2release`
.. `make scst_install`
.. `make usr_install`
.. `make iscsi_install`
.. `make scstadm_install`
.. `depmod`
.. `cp scst/src/certs/scst_module_key.der /opt/netapp/lib/ontap_mediator/ontap_mediator/SCST_mod_keys/.`
.. `cp scst/src/certs/scst_module_key.der /opt/netapp/lib/ontap_mediator/ontap_mediator/SCST_mod_keys/.`
.. `patch /etc/init.d/scst < /opt/netapp/lib/ontap_mediator/systemd/scst.patch`


. (선택 사항) 보안 부팅이 활성화된 경우 재부팅하기 전에 다음 단계를 수행하십시오.
+
.. "scst_vdisk", "scst" 및 "iscsi_scst" 모듈의 각 파일 이름을 확인합니다.
+
....
`[root@localhost ~]# modinfo -n scst_vdisk`
`[root@localhost ~]# modinfo -n scst`
`[root@localhost ~]# modinfo -n iscst_scst_vdisk`
....
.. 커널 릴리스를 확인합니다.
+
....
[root@localhost ~]# uname -r
....
.. 커널로 각 파일에 서명합니다.
+
....
[root@localhost ~]# /usr/src/kernels/<KERNEL-RELEASE>/scripts/sign-file \sha256 \
/opt/netapp/lib/ontap_mediator/ontap_mediator/SCST_mod_keys/scst_module_key.priv \
/opt/netapp/lib/ontap_mediator/ontap_mediator/SCST_mod_keys/scst_module_key.der \
_module-filename_
....
.. UEFI 펌웨어와 올바른 키를 설치합니다.
+
UEFI 키 설치 지침은 다음 웹 사이트에서 확인할 수 있습니다.

+
`/opt/netapp/lib/ontap_mediator/ontap_mediator/SCST_mod_keys/README.module-signing`

+
생성된 UEFI 키는 다음 위치에 있습니다.

+
`/opt/netapp/lib/ontap_mediator/ontap_mediator/SCST_mod_keys/scst_module_key.der`



. 재부팅을 수행합니다.
+
`reboot`





== ONTAP 중재자 서비스를 제거합니다

.시작하기 전에
필요한 경우 ONTAP 중재자 서비스를 제거할 수 있습니다. 중재자 서비스를 제거하기 전에 중재자를 ONTAP에서 분리해야 합니다.

.이 작업에 대해
이 작업은 ONTAP 중재자 서비스가 설치된 Linux 호스트에서 수행됩니다.

이 명령에 액세스할 수 없는 경우 다음 예에 표시된 대로 전체 경로를 사용하여 명령을 실행해야 할 수 있습니다.

'/usr/local/bin/uninstall_ontap_중재자'

.단계
. ONTAP 중재자 서비스를 제거합니다.
+
uninstall_ontap_중재자

+
....
 [root@mediator-host ~]# uninstall_ontap_mediator

 ONTAP Mediator: Self Extracting Uninstaller

 + Removing ONTAP Mediator. (Log: /tmp/ontap_mediator.GmRGdA/uninstall_ontap_mediator/remove.log)
 + Remove successful.
 [root@mediator-host ~]#
....

