---
permalink: mediator/mediator-overview-concept.html 
sidebar: sidebar 
keywords: ontap mediator service, install requirements, mediator requirements 
summary: ONTAP 중재자가 ONTAP 기능을 위한 몇 가지 기능을 제공합니다. 
---
= ONTAP 중재자 개요
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 중재자가 ONTAP 기능을 위한 몇 가지 기능을 제공합니다.

* HA 메타데이터에 대한 영구적이고 울타리 저장소를 제공합니다.
* 컨트롤러 활성을 위한 핑 프록시 역할을 합니다.
* quorum 결정에 도움이 되는 동기 노드 상태 쿼리 기능을 제공합니다.


ONTAP 중재자가 두 가지 추가 시스템 서비스를 제공합니다.

* *`ontap_mediator.service`*
+
ONAP 관계를 관리하기 위한 REST API 서버를 유지 관리합니다.

* *`mediator-scst.service`*
+
SCST(iSCSI 모듈)의 시작 및 종료를 제어합니다.





== 시스템 관리자를 위해 제공되는 도구

시스템 관리자를 위해 제공되는 도구:

* *`/usr/local/bin/mediator_change_password`*
+
현재 API 사용자 이름과 암호를 제공할 때 새 API 암호를 설정합니다.

* *`/usr/local/bin/mediator_change_user`*
+
현재 API 사용자 이름 및 암호를 제공할 때 새 API 사용자 이름을 설정합니다.

* *`/usr/local/bin/mediator_generate_support_bundle`*
+
NetApp 고객 지원 커뮤니케이션하기 위해 필요한 모든 유용한 지원 정보를 포함하는 로컬 tgz 파일을 생성합니다. 여기에는 애플리케이션 구성, 로그 및 일부 시스템 정보가 포함됩니다. 번들은 로컬 디스크에 생성되고 필요에 따라 수동으로 전송할 수 있습니다. 스토리지 위치:/opt/netapp/data/support_bundle/

* *`/usr/local/bin/uninstall_ontap_mediator`*
+
ONTAP 중재자 패키지와 SCST 커널 모듈을 제거합니다. 여기에는 모든 구성, 로그 및 메일박스 데이터가 포함됩니다.

* *`/usr/local/bin/mediator_unlock_user`*
+
인증 재시도 한도에 도달하면 API 사용자 계정의 잠금을 해제합니다. 이 기능은 무차별 암호 대입(brute force password derivation)을 방지하는 데 사용됩니다. 사용자에게 올바른 사용자 이름과 암호를 묻는 메시지가 표시됩니다.

* *`/usr/local/bin/mediator_add_user`*
+
(지원만 해당) 설치 시 API 사용자를 추가하는 데 사용됩니다.





== 특별 참고 사항

ONTAP 중재자가 SCST를 사용하여 iSCSI를 제공합니다(참조). 이 패키지는 커널 전용으로 설치하는 동안 컴파일되는 커널 모듈입니다. 커널에 대한 업데이트를 수행하려면 SCST를 다시 설치해야 할 수 있습니다. 또는 ONTAP 중재자를 제거한 후 다시 설치한 다음 ONTAP 관계를 다시 구성하십시오.


NOTE: 서버 OS 커널에 대한 모든 업데이트는 ONTAP의 유지 관리 창과 조율되어야 합니다.
