---
permalink: data-protection/convert-type-snapmirror-task.html 
sidebar: sidebar 
keywords: convert, snapmirror, relationship, asynchronous, synchronous, baseline, convert 
summary: ONTAP 9.5부터 SnapMirror Synchronous가 지원됩니다. 기본 전송을 수행하지 않고도 비동기식 SnapMirror 관계를 SnapMirror Synchronous 관계로 또는 그 반대로 변환할 수 있습니다. 
---
= SnapMirror 관계의 유형을 변환합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9.5부터 SnapMirror Synchronous가 지원됩니다. 기본 전송을 수행하지 않고도 비동기식 SnapMirror 관계를 SnapMirror Synchronous 관계로 또는 그 반대로 변환할 수 있습니다.

.이 작업에 대해
SnapMirror 정책을 변경하여 비동기식 SnapMirror 관계를 SnapMirror Synchronous 관계로 또는 그 반대로 변환할 수 없습니다

.단계
* * 비동기식 SnapMirror 관계를 SnapMirror Synchronous 관계 * 로 변환
+
.. 대상 클러스터에서 비동기식 SnapMirror 관계를 삭제합니다.
+
'스냅샷 삭제 대상 - path_SVM:volume_'

+
[listing]
----
cluster2::>snapmirror delete -destination-path vs1_dr:vol1
----
.. 소스 클러스터에서 공통 스냅샷 복사본을 삭제하지 않고 SnapMirror 관계를 놓습니다.
+
'스냅샷 해제-관계-정보 전용 실제-대상-경로_dest_SVM:dest_volume_'

+
[listing]
----
cluster1::>snapmirror release -relationship-info-only true -destination-path vs1_dr:vol1
----
.. 대상 클러스터에서 SnapMirror Synchronous 관계를 생성합니다.
+
'스냅샷 생성 - 소스 경로 - src_src_SVM: src_volume_-destination-path_dest_SVM: dest_volume_-policy sync-mirror'

+
[listing]
----
cluster2::>snapmirror create -source-path vs1:vol1 -destination-path vs1_dr:vol1 -policy sync
----
.. SnapMirror Synchronous 관계를 재동기화합니다.
+
'스냅샷 미러 재동기화 - 대상 - path_dest_SVM: dest_volume_'

+
[listing]
----
cluster2::>snapmirror resync -destination-path vs1_dr:vol1
----


* * SnapMirror Synchronous 관계를 비동기식 SnapMirror 관계 * 로 변환
+
.. 대상 클러스터에서 기존 SnapMirror Synchronous 관계를 중지합니다.
+
'스냅샷 중지 - 대상 경로 dest_SVM: dest_volume'

+
[listing]
----
cluster2::> snapmirror quiesce -destination-path vs1_dr:vol1
----
.. 대상 클러스터에서 비동기식 SnapMirror 관계를 삭제합니다.
+
'스냅샷 삭제 대상 - path_SVM:volume_'

+
[listing]
----
cluster2::>snapmirror delete -destination-path vs1_dr:vol1
----
.. 소스 클러스터에서 공통 스냅샷 복사본을 삭제하지 않고 SnapMirror 관계를 놓습니다.
+
'스냅샷 해제-관계-정보 전용 실제-대상-경로_dest_SVM:dest_volume_'

+
[listing]
----
cluster1::>snapmirror release -relationship-info-only true -destination-path vs1_dr:vol1
----
.. 대상 클러스터에서 비동기식 SnapMirror 관계를 생성합니다.
+
'스냅샷 생성 - 소스 경로 - src_src_SVM: src_volume_-destination-path_dest_SVM: dest_volume_-policy MirrorAllSnapshots'

+
[listing]
----
cluster2::>snapmirror create -source-path vs1:vol1 -destination-path vs1_dr:vol1 -policy sync
----
.. SnapMirror Synchronous 관계를 재동기화합니다.
+
'스냅샷 미러 재동기화 - 대상 - path_dest_SVM: dest_volume_'

+
[listing]
----
cluster2::>snapmirror resync -destination-path vs1_dr:vol1
----



