---
permalink: data-protection/convert-type-snapmirror-task.html 
sidebar: sidebar 
keywords: convert, snapmirror, relationship, asynchronous, synchronous, baseline, convert 
summary: ONTAP 9.5부터 SnapMirror Synchronous가 지원됩니다. 기본 전송을 수행하지 않고도 SnapMirror 비동기식 관계를 SnapMirror 동기식 관계로 변환하거나 그 반대로 전환할 수 있습니다. 
---
= SnapMirror 관계의 유형을 변환합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9.5부터 SnapMirror Synchronous가 지원됩니다. 기본 전송을 수행하지 않고도 SnapMirror 비동기식 관계를 SnapMirror 동기식 관계로 변환하거나 그 반대로 전환할 수 있습니다.

.이 작업에 대해
SnapMirror 정책을 변경하여 SnapMirror 비동기식 관계를 SnapMirror 동기식 관계로 변환하거나 그 반대로 변환할 수 없습니다

.단계
* * SnapMirror 비동기 관계를 SnapMirror 동기 관계로 변환 *
+
.. 대상 클러스터에서 SnapMirror 비동기식 관계를 삭제합니다.
+
`snapmirror delete -destination-path <SVM:volume>`

+
[listing]
----
cluster2::>snapmirror delete -destination-path vs1_dr:vol1
----
.. 소스 클러스터에서 공통 스냅샷 복사본을 삭제하지 않고 SnapMirror 관계를 놓습니다.
+
`snapmirror release -relationship-info-only true -destination-path <destination_SVM>:<destination_volume>`

+
[listing]
----
cluster1::>snapmirror release -relationship-info-only true -destination-path vs1_dr:vol1
----
.. 대상 클러스터에서 SnapMirror 동기식 관계를 생성합니다.
+
`snapmirror create -source-path _src_SVM:src_volume_ -destination-path <destination_SVM>:<destination_volume> -policy sync-mirror`

+
[listing]
----
cluster2::>snapmirror create -source-path vs1:vol1 -destination-path vs1_dr:vol1 -policy sync
----
.. SnapMirror 동기식 관계 재동기화:
+
`snapmirror resync -destination-path <destination_SVM:destination_volume>`

+
[listing]
----
cluster2::>snapmirror resync -destination-path vs1_dr:vol1
----


* * SnapMirror 동기식 관계를 SnapMirror 비동기식 관계로 변환 *
+
.. 대상 클러스터에서 기존 SnapMirror 동기식 관계를 중지합니다.
+
`snapmirror quiesce -destination-path <destination_SVM>:<destination_volume>`

+
[listing]
----
cluster2::> snapmirror quiesce -destination-path vs1_dr:vol1
----
.. 대상 클러스터에서 SnapMirror 비동기식 관계를 삭제합니다.
+
`snapmirror delete -destination-path <SVM:volume>`

+
[listing]
----
cluster2::>snapmirror delete -destination-path vs1_dr:vol1
----
.. 소스 클러스터에서 공통 스냅샷 복사본을 삭제하지 않고 SnapMirror 관계를 놓습니다.
+
`snapmirror release -relationship-info-only true -destination-path <destination_SVM:destination_volume>`

+
[listing]
----
cluster1::>snapmirror release -relationship-info-only true -destination-path vs1_dr:vol1
----
.. 대상 클러스터에서 SnapMirror 비동기식 관계를 생성합니다.
+
`snapmirror create -source-path _src_SVM:src_volume_ -destination-path <destination_SVM:destination_volume> -policy MirrorAllSnapshots`

+
[listing]
----
cluster2::>snapmirror create -source-path vs1:vol1 -destination-path vs1_dr:vol1 -policy sync
----
.. SnapMirror 동기식 관계 재동기화:
+
`snapmirror resync -destination-path <destination_SVM:destination_volume>`

+
[listing]
----
cluster2::>snapmirror resync -destination-path vs1_dr:vol1
----



