---
permalink: data-protection/convert-snapmirror-version-flexible-task.html 
sidebar: sidebar 
keywords: convert, exist, dp-type, relationship, xdp 
summary: 기존 DP 유형 관계를 XDP로 쉽게 변환하여 버전에 상관없이 유연한 SnapMirror를 활용할 수 있습니다. 
---
= 기존 DP 유형 관계를 XDP로 변환합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9.12.1 이상으로 업그레이드하는 경우 업그레이드하기 전에 DP 유형 관계를 XDP로 변환해야 합니다. ONTAP 9.12.1 이상은 DP 유형 관계를 지원하지 않습니다. 기존 DP 유형 관계를 XDP로 쉽게 변환하여 버전에 상관없이 유연한 SnapMirror를 활용할 수 있습니다.

.이 작업에 대해
* SnapMirror는 기존 DP 유형 관계를 XDP로 자동 변환하지 않습니다. 관계를 변환하려면 기존 관계를 분리 및 삭제하고 새로운 XDP 관계를 생성한 다음 관계를 다시 동기화해야 합니다. 배경 정보는 을 참조하십시오 link:version-flexible-snapmirror-default-concept.html["XDP는 DP를 SnapMirror 기본값으로 바꿉니다"].
* 전환을 계획할 때는 XDP SnapMirror 관계의 백그라운드 준비 및 데이터 웨어하우징 단계에 시간이 오래 걸릴 수 있습니다. SnapMirror 관계가 오랫동안 "준비 중" 상태를 보고하는 것을 보면 흔히 볼 수 있습니다.


[NOTE]
====
SnapMirror 관계 유형을 DP에서 XDP로 변환한 후에는 자동 크기 조정 및 공간 보장과 같은 공간 관련 설정이 더 이상 대상에 복제되지 않습니다.

====
.단계
. 대상 클러스터에서 SnapMirror 관계가 DP 유형이고, 미러 상태가 SnapMired 상태이고, 관계 상태가 Idle 상태이고, 관계가 정상 상태인지 확인합니다.
+
이 명령을 실행하기 전에 꺾쇠 괄호 안의 변수를 필수 값으로 바꾸어야 합니다.

+
[source, cli]
----
snapmirror show -destination-path <SVM:volume>
----
+
다음 예제는 'napmirror show' 명령의 출력을 보여줍니다.

+
[listing]
----
cluster_dst::>snapmirror show -destination-path svm_backup:volA_dst

Source Path: svm1:volA
Destination Path: svm_backup:volA_dst
Relationship Type: DP
SnapMirror Schedule: -
Tries Limit: -
Throttle (KB/sec): unlimited
Mirror State: Snapmirrored
Relationship Status: Idle
Transfer Snapshot: -
Snapshot Progress: -
Total Progress: -
Snapshot Checkpoint: -
Newest Snapshot: snapmirror.10af643c-32d1-11e3-954b-123478563412_2147484682.2014-06-27_100026
Newest Snapshot Timestamp: 06/27 10:00:55
Exported Snapshot: snapmirror.10af643c-32d1-11e3-954b-123478563412_2147484682.2014-06-27_100026
Exported Snapshot Timestamp: 06/27 10:00:55
Healthy: true
----
+
[NOTE]
====
관계 설정의 기존 상태를 추적하기 위해 'napmirror show' 명령 출력의 복사본을 유지하는 것이 유용할 수 있습니다.

====
. 소스 볼륨과 타겟 볼륨에서 두 볼륨 모두에 공통 스냅샷 복사본이 있는지 확인합니다.
+
이 명령을 실행하기 전에 꺾쇠 괄호 안의 변수를 필수 값으로 바꾸어야 합니다.

+
[source, cli]
----
volume snapshot show -vserver <SVM> -volume <volume>
----
+
다음 예에서는 를 보여 줍니다 `volume snapshot show` 소스 및 대상 볼륨의 출력:

+
[listing]
----
cluster_src:> volume snapshot show -vserver vsm1 -volume volA
---Blocks---
Vserver Volume Snapshot State Size Total% Used%
-------- ------- ------------------------------- -------- -------- ------ -----
svm1 volA
weekly.2014-06-09_0736 valid 76KB 0% 28%
weekly.2014-06-16_1305 valid 80KB 0% 29%
daily.2014-06-26_0842 valid 76KB 0% 28%
hourly.2014-06-26_1205 valid 72KB 0% 27%
hourly.2014-06-26_1305 valid 72KB 0% 27%
hourly.2014-06-26_1405 valid 76KB 0% 28%
hourly.2014-06-26_1505 valid 72KB 0% 27%
hourly.2014-06-26_1605 valid 72KB 0% 27%
daily.2014-06-27_0921 valid 60KB 0% 24%
hourly.2014-06-27_0921 valid 76KB 0% 28%
snapmirror.10af643c-32d1-11e3-954b-123478563412_2147484682.2014-06-27_100026
valid 44KB 0% 19%
11 entries were displayed.


cluster_dest:> volume snapshot show -vserver svm_backup -volume volA_dst
---Blocks---
Vserver Volume Snapshot State Size Total% Used%
-------- ------- ------------------------------- -------- -------- ------ -----
svm_backup volA_dst
weekly.2014-06-09_0736 valid 76KB 0% 30%
weekly.2014-06-16_1305 valid 80KB 0% 31%
daily.2014-06-26_0842 valid 76KB 0% 30%
hourly.2014-06-26_1205 valid 72KB 0% 29%
hourly.2014-06-26_1305 valid 72KB 0% 29%
hourly.2014-06-26_1405 valid 76KB 0% 30%
hourly.2014-06-26_1505 valid 72KB 0% 29%
hourly.2014-06-26_1605 valid 72KB 0% 29%
daily.2014-06-27_0921 valid 60KB 0% 25%
hourly.2014-06-27_0921 valid 76KB 0% 30%
snapmirror.10af643c-32d1-11e3-954b-123478563412_2147484682.2014-06-27_100026
----
. 변환 중에 예약된 업데이트가 실행되지 않도록 하려면 기존 DP 유형 관계를 중지합니다.
+
이 명령을 실행하기 전에 꺾쇠 괄호 안의 변수를 필수 값으로 바꾸어야 합니다.

+
[source, cli]
----
snapmirror quiesce -source-path <SVM:volume> -destination-path <SVM:volume>
----
+
전체 명령 구문은 을 참조하십시오 link:https://docs.netapp.com/us-en/ontap-cli-9131//snapmirror-quiesce.html["Man 페이지"^].

+
[NOTE]
====
이 명령은 타겟 SVM 또는 타겟 클러스터에서 실행해야 합니다.

====
+
다음 예에서는 svm1의 소스 볼륨 VolA와 sm_backup의 대상 볼륨 VolA_dst 간의 관계를 설정합니다.

+
[listing]
----
cluster_dst::> snapmirror quiesce -destination-path svm_backup:volA_dst
----
. 기존 DP 유형 관계 끊기:
+
이 명령을 실행하기 전에 꺾쇠 괄호 안의 변수를 필수 값으로 바꾸어야 합니다.

+
[source, cli]
----
snapmirror break -destination-path <SVM:volume>
----
+
전체 명령 구문은 을 참조하십시오 link:https://docs.netapp.com/us-en/ontap-cli-9131//snapmirror-break.html["Man 페이지"^].

+
[NOTE]
====
이 명령은 타겟 SVM 또는 타겟 클러스터에서 실행해야 합니다.

====
+
다음 예에서는 svm1의 소스 볼륨 VolA와 sm_backup의 대상 볼륨 VolA_dst의 관계를 나눕니다.

+
[listing]
----
cluster_dst::> snapmirror break -destination-path svm_backup:volA_dst
----
. 타겟 볼륨에서 스냅샷 복사본 자동 삭제가 활성화되어 있는 경우 다음을 수행하십시오.
+
'볼륨 스냅샷 자동 삭제 수정 - vserver_SVM_-volume_volume_-enabled false'

+
다음 예에서는 대상 볼륨 'VolA_DST'에서 스냅샷 복사본 자동 삭제를 사용하지 않도록 설정합니다.

+
[listing]
----
cluster_dst::> volume snapshot autodelete modify -vserver svm_backup -volume volA_dst -enabled false
----
. 기존 DP 유형 관계 삭제:
+
이 명령을 실행하기 전에 꺾쇠 괄호 안의 변수를 필수 값으로 바꾸어야 합니다.

+
[source, cli]
----
snapmirror delete -destination-path <SVM:volume>
----
+
전체 명령 구문은 을 참조하십시오 link:https://docs.netapp.com/us-en/ontap-cli-9131//snapmirror-delete.html["Man 페이지"^].

+
[NOTE]
====
이 명령은 타겟 SVM 또는 타겟 클러스터에서 실행해야 합니다.

====
+
다음 예에서는 svm1의 소스 볼륨 VolA와 sm_backup의 대상 볼륨 VolA_dst 간의 관계를 삭제합니다.

+
[listing]
----
cluster_dst::> snapmirror delete -destination-path svm_backup:volA_dst
----
. 'napmirror show' 명령에서 보존한 출력을 사용하여 새로운 XDP 유형 관계를 생성할 수 있습니다.
+
이 명령을 실행하기 전에 꺾쇠 괄호 안의 변수를 필수 값으로 바꾸어야 합니다.

+
[source, cli]
----
snapmirror create -source-path <SVM:volume> -destination-path <SVM:volume>  -type XDP -schedule <schedule> -policy <policy>
----
+
새 관계는 동일한 소스 볼륨과 타겟 볼륨을 사용해야 합니다. 전체 명령 구문은 man 페이지를 참조하십시오.

+
[NOTE]
====
이 명령은 타겟 SVM 또는 타겟 클러스터에서 실행해야 합니다.

====
+
다음 예에서는 기본 MirorAllSnapshots 정책을 사용하여 svm1의 소스 볼륨 "VolA"와 sVM_backup의 대상 볼륨 "VolA_DST" 간에 SnapMirror DR 관계를 생성합니다.

+
[listing]
----
cluster_dst::> snapmirror create -source-path svm1:volA -destination-path svm_backup:volA_dst
-type XDP -schedule my_daily -policy MirrorAllSnapshots
----
. 소스 및 대상 볼륨 재동기화:
+
이 명령을 실행하기 전에 꺾쇠 괄호 안의 변수를 필수 값으로 바꾸어야 합니다.

+
[source, cli]
----
snapmirror resync -source-path <SVM:volume> -destination-path <SVM:volume>
----
+
재동기화 시간을 개선하려면 을 사용합니다 `-quick-resync` 단, 스토리지 효율성 절약 효과는 손실될 수 있다는 점을 알아야 합니다. 전체 명령 구문은 man 페이지를 참조하십시오. link:https://docs.netapp.com/us-en/ontap-cli-9131/snapmirror-resync.html#parameters.html["SnapMirror 재동기화 명령"^].

+
[NOTE]
====
이 명령은 타겟 SVM 또는 타겟 클러스터에서 실행해야 합니다. 재동기화에는 기본 전송이 필요하지 않지만 시간이 오래 걸릴 수 있습니다. 사용량이 적은 시간에 재동기화를 실행할 수 있습니다.

====
+
다음 예에서는 svm1의 소스 볼륨 VolA와 sm_backup의 대상 볼륨 VolA_dst 간의 관계를 재동기화한다.

+
[listing]
----
cluster_dst::> snapmirror resync -source-path svm1:volA -destination-path svm_backup:volA_dst
----
. 스냅샷 복사본의 자동 삭제를 사용하지 않도록 설정한 경우 다음을 다시 사용하도록 설정합니다.
+
이 명령을 실행하기 전에 꺾쇠 괄호 안의 변수를 필수 값으로 바꾸어야 합니다.

+
[source, cli]
----
volume snapshot autodelete modify -vserver <SVM> -volume <volume> -enabled true
----


.작업을 마친 후
. 를 사용합니다 `snapmirror show` 명령을 사용하여 SnapMirror 관계가 생성되었는지 확인합니다.
. SnapMirror XDP 대상 볼륨이 SnapMirror 정책에 정의된 대로 스냅샷 복사본의 업데이트를 시작하면 의 출력을 사용합니다 `snapmirror list-destinations` 소스 클러스터의 명령을 사용하여 새로운 SnapMirror XDP 관계를 표시합니다.

