---
permalink: data-protection/create-snapshot-policy-task.html 
sidebar: sidebar 
keywords: create, snapshot, policy 
summary: '스냅샷 정책은 스냅샷 복사본을 생성할 시기, 유지할 복사본 수 및 이름을 지정하는 방법을 지정합니다. 예를 들어, 시스템이 매일 오전 12:10에 스냅샷 복사본을 하나 생성하고 가장 최근의 복사본 두 개를 보존한 다음 이름을 "daily.timestamp"로 지정할 수 있습니다. 스냅샷 정책에는 최대 5개의 작업 일정이 포함될 수 있습니다.' 
---
= 스냅샷 정책을 생성합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
스냅샷 정책은 스냅샷 복사본을 생성할 시기, 유지할 복사본 수 및 이름을 지정하는 방법을 지정합니다. 예를 들어, 시스템이 매일 오전 12시 10분에 스냅샷 복사본 하나를 생성하고 가장 최근의 복사본 2개를 보존한 다음 "daily."_timestamp_"로 이름을 지정할 수 있습니다. 스냅샷 정책에는 최대 5개의 작업 일정이 포함될 수 있습니다.

기본적으로 ONTAP는 작업 일정 이름에 타임스탬프를 추가하여 스냅샷 복사본의 이름을 구성합니다.

[listing]
----
daily.2017-05-14_0013/              hourly.2017-05-15_1106/
daily.2017-05-15_0012/              hourly.2017-05-15_1206/
hourly.2017-05-15_1006/             hourly.2017-05-15_1306/
----
원하는 경우 작업 스케줄 이름의 접두사를 대체할 수 있습니다.

'스냅샷 레이블' 옵션은 SnapMirror 복제용 옵션입니다. 자세한 내용은 을 참조하십시오 link:define-rule-policy-task.html["정책 규칙 정의"].

.단계
. 스냅샷 정책 생성:
+
'볼륨 스냅샷 정책 생성 - vserver_SVM_-policy_policy_name_-enabled true|false-schedule1_schedule1_name_-count1_copies_to_retain_-prefix1_snapshot_prefix_-SnapMirror-label1_snapshot_label_... -schedule1_schedule5_name_-count5_copies_to_retain_-prefix5_snapshot_prefix_-snapmirror-label5_snapshot_label_'

+
다음 예에서는 일별 스케줄로 실행되는 'snap_policy_daily'라는 스냅샷 정책을 생성합니다. 정책에는 각각 daily * 라는 이름의 최대 5개의 스냅샷 복사본이 있습니다. _ timestamp _ * 와 SnapMirror label daily:

+
[listing]
----
cluster1::> volume snapshot policy create -vserver vs0 -policy snap_policy_daily -schedule1 daily -count1 5 -snapmirror-label1 daily
----

