---
permalink: data-protection/dpo-systems-feature-enhancements-reference.html 
sidebar: sidebar 
keywords: dpo, systems, feature, enhancements, snapmirror, dp optimized, optimised, backoff, back off, deduplication, deduplicate, snapshot blocks, donors, compact, flexvol, license 
summary: 'ONTAP 9.6부터는 DP_Optimized(DPO) 라이센스가 설치될 때 지원되는 최대 FlexVol 볼륨 수가 증가합니다. ONTAP 9.4부터 DPO 라이센스가 있는 시스템은 SnapMirror 백 오프, 볼륨 간 백그라운드 중복제거, Snapshot 블록을 기증자로 사용 및 컴팩션을 지원합니다.' 
---
= DPO 시스템의 향상된 기능
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9.6부터는 DP_Optimized(DPO) 라이센스가 설치될 때 지원되는 최대 FlexVol 볼륨 수가 증가합니다. ONTAP 9.4부터 DPO 라이센스가 있는 시스템은 SnapMirror 백 오프, 볼륨 간 백그라운드 중복제거, Snapshot 블록을 기증자로 사용 및 컴팩션을 지원합니다.

ONTAP 9.6부터 보조 또는 데이터 보호 시스템에서 지원되는 최대 FlexVol 볼륨 수가 증가하여 노드당 최대 2,500개의 FlexVol 볼륨 또는 페일오버 모드에서 최대 5,000개까지 확장할 수 있습니다. FlexVol 볼륨의 증가는 DP_Optimized(DPO) 라이센스로 활성화됩니다. 소스 노드와 대상 노드 모두에서 SnapMirror 라이센스가 필요합니다.

ONTAP 9.4부터는 DPO 시스템에 다음과 같은 기능이 향상되었습니다.

* SnapMirror 백 오프: DPO 시스템에서 복제 트래픽은 클라이언트 워크로드가 제공하는 것과 동일한 우선순위를 갖습니다.
+
DPO 시스템에서는 SnapMirror 백오프가 기본적으로 사용되지 않습니다.

* 볼륨 백그라운드 중복제거 및 볼륨 간 백그라운드 중복제거: DPO 시스템에서 볼륨 백그라운드 중복제거 및 볼륨 간 백그라운드 중복제거가 활성화됩니다.
+
'Storage aggregate Efficiency cross-volume-dedupe start-aggregate_aggregate_name_-scan-old-data true' 명령을 실행하여 기존 데이터를 중복 제거할 수 있습니다. 가장 좋은 방법은 사용량이 적은 시간에 명령을 실행하여 성능에 미치는 영향을 줄이는 것입니다.

* 기부자로 스냅샷 블록을 사용하여 절감 확대: 액티브 파일 시스템에서 사용할 수 없지만 스냅샷 복사본에 갇혀 있는 데이터 블록이 볼륨 중복 제거를 위해 기증자로 사용됩니다.
+
새 데이터는 스냅샷 복사본에 포함된 데이터로 중복제거할 수 있으므로 스냅샷 블록도 효과적으로 공유할 수 있습니다. 도너 공간이 많을수록 특히 볼륨에 많은 수의 스냅샷 복사본이 있는 경우에 더 많은 공간을 절약할 수 있습니다.

* 컴팩션: DPO 볼륨에서는 데이터 컴팩션이 기본적으로 사용됩니다.

