---
permalink: data-protection/install-snapmirror-cloud-license-task.html 
sidebar: sidebar 
keywords: install, snapmirror, cloud, license, asynchronous, replicate, replication, snapshot 
summary: ONTAP 9.8부터 SnapMirror Cloud는 ONTAP에서 오브젝트 스토리지 엔드포인트로 비동기 Snapshot 복사본 복제를 제공합니다. SnapMirror 클라우드 관계는 사전 검증된 타사 백업 애플리케이션을 사용해서만 구성할 수 있습니다. ONTAP를 오브젝트 스토리지 복제로 구성하려면 오브젝트 저장소 끝점에 복제하도록 구성된 ONTAP 소스 클러스터에 SnapMirror 및 SnapMirror 클라우드 라이센스가 모두 필요합니다. 
---
= SnapMirror Cloud 라이센스를 설치합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9.8부터 SnapMirror Cloud는 ONTAP에서 오브젝트 스토리지 엔드포인트로 비동기식 스냅샷 복제를 제공합니다. SnapMirror 클라우드 관계는 사전 검증된 타사 백업 애플리케이션을 사용해서만 구성할 수 있습니다. ONTAP를 오브젝트 스토리지 복제로 구성하려면 오브젝트 저장소 끝점에 복제하도록 구성된 ONTAP 소스 클러스터에 SnapMirror 및 SnapMirror 클라우드 라이센스가 모두 필요합니다.

.이 작업에 대해
SnapMirror Cloud 라이센스는 단일 인스턴스 클러스터 전체 라이센스이며, 따라서 클러스터의 모든 노드에 설치할 필요가 없습니다. 용어 기반 라이센스이며, 이 경우 용어 및 백업 용량이 모두 적용됩니다. 이 최종 사용자 라이센스 외에도 SnapMirror Cloud에는 복제를 위해 ONTAP API를 구성 및 호출하기 위해 인증 및 승인된 백업 애플리케이션이 필요합니다. SnapMirror 클라우드 복제를 활용하려면 SnapMirror Cloud 최종 사용자 라이센스와 인증된 앱이 모두 필요합니다.

SnapMirror 클라우드 라이센스는 하이브리드 클라우드 번들 구입 시 구입되며 1TB 단위로 1~3년 단위로 구입할 수 있습니다. 하이브리드 클라우드 번들에는 SnapMirror Cloud의 라이센스가 포함되어 있습니다. 각 사용권에는 고유한 일련 번호가 있습니다. 하이브리드 클라우드 번들을 구매할 경우 용량을 기준으로 하며, 여기서 하이브리드 클라우드 번들의 구매한 용량을 SnapMirror 클라우드 라이센스에 적용합니다.

ONTAP 명령줄 또는 System Manager를 사용하여 클러스터에 SnapMirror 클라우드 라이센스를 설치할 수 있습니다.

.단계
. NetApp Support 사이트에서 SnapMirror Cloud용 NLF(NetApp 라이센스 파일) 2개를 다운로드하십시오.
+
https://mysupport.netapp.com/site/global/dashboard["NetApp 지원"]

. System Manager를 사용하여 SnapMirror Cloud NLF 파일을 클러스터에 업로드합니다.
+
.. Configuration * > * Licenses * 를 클릭합니다.
.. Cluster Settings * 창에서 * Licenses * 를 클릭합니다.
.. 패키지 * 창에서 * 추가 * 를 클릭합니다.
.. 라이센스 패키지 추가 * 대화 상자에서 * 파일 선택 * 을 클릭하여 다운로드한 NLF를 선택한 다음 * 추가 * 를 클릭하여 클러스터에 파일을 업로드합니다.




.관련 정보
http://mysupport.netapp.com/licenses["NetApp 소프트웨어 라이센스 검색"]
