---
permalink: data-protection/manage-storage-efficiency-task.html 
sidebar: sidebar 
keywords: manage, storage, efficiency, snapmirror, snap mirror, compression, compress, postporcess, update relationship, volume 
summary: SnapMirror는 대상에서 사후 처리 데이터 압축이 활성화된 경우를 제외하고 소스 및 타겟 볼륨의 스토리지 효율성을 유지합니다. 이 경우 대상에서 모든 스토리지 효율성이 손실됩니다. 이 문제를 해결하려면 대상에서 사후 처리 압축을 비활성화하고 관계를 수동으로 업데이트하며 스토리지 효율성을 다시 활성화해야 합니다. 
---
= 스토리지 효율성 관리
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapMirror는 대상에서 사후 처리 데이터 압축이 활성화된 경우를 제외하고 소스 및 타겟 볼륨의 스토리지 효율성을 유지합니다. 이 경우 대상에서 모든 스토리지 효율성이 손실됩니다. 이 문제를 해결하려면 대상에서 사후 처리 압축을 비활성화하고 관계를 수동으로 업데이트하며 스토리지 효율성을 다시 활성화해야 합니다.

.필요한 것
* 소스 및 타겟 클러스터와 SVM을 피어링해야 합니다.
+
https://docs.netapp.com/us-en/ontap-sm-classic/peering/index.html["클러스터 및 SVM 피어링"]

* 대상에서 사후 처리 압축을 비활성화해야 합니다.


.이 작업에 대해
'volume Efficiency show' 명령을 사용하면 볼륨에 대한 효율성이 활성화되어 있는지 확인할 수 있습니다. 자세한 내용은 man 페이지를 참조하십시오.

SnapMirror 감사 로그를 보고 전송 설명을 찾아 SnapMirror에서 스토리지 효율성이 유지되는지 확인할 수 있습니다. 전송 설명에 'transfer_desc=Logical Transfer'가 표시되면 SnapMirror가 스토리지 효율성을 유지하지 못하고 있는 것입니다. 전송 설명에 "transfer_desc = Logical Transfer with Storage Efficiency"가 표시되면 SnapMirror는 스토리지 효율성을 유지하고 있는 것입니다. 예를 들면 다음과 같습니다.

[listing]
----
Fri May 22 02:13:02 CDT 2020 ScheduledUpdate[May 22 02:12:00]:cc0fbc29-b665-11e5-a626-00a09860c273 Operation-Uuid=39fbcf48-550a-4282-a906-df35632c73a1 Group=none Operation-Cookie=0 action=End source=<sourcepath> destination=<destpath> status=Success bytes_transferred=117080571 network_compression_ratio=1.0:1 transfer_desc=Logical Transfer - Optimized Directory Mode
----
스토리지와 함께 논리적 전송

ONTAP 9.3부터는 스토리지 효율성을 수동으로 업데이트할 필요가 없습니다. SnapMirror에서 사후 처리 압축이 비활성화되었다고 감지하면 다음 예약 업데이트에서 스토리지 효율성을 자동으로 다시 활성화합니다. 소스와 대상 모두 ONTAP 9.3을 실행해야 합니다.

ONTAP 9.3부터 AFF 시스템은 타겟 볼륨을 쓰기 가능한 상태로 만든 후 FAS 시스템과 다른 방식으로 스토리지 효율성 설정을 관리합니다.

* 'napmirror break' 명령을 사용하여 대상 볼륨을 쓰기 가능하게 만든 후 볼륨의 캐싱 정책은 자동으로 ""auto"(기본값)로 설정됩니다.
+
[NOTE]
====
이 동작은 FlexVol 볼륨에만 적용되며 FlexGroup 볼륨에는 적용되지 않습니다.

====
* 재동기화 시 캐싱 정책은 자동으로 ""없음""으로 설정되고 원래 설정에 관계없이 중복 제거 및 인라인 압축이 자동으로 비활성화됩니다. 필요에 따라 설정을 수동으로 수정해야 합니다.


[NOTE]
====
스토리지 효율성을 활성화한 수동 업데이트는 시간이 오래 걸릴 수 있습니다. 사용량이 적은 시간에 작업을 실행할 수 있습니다.

====
.단계
. 복제 관계를 업데이트하고 스토리지 효율성을 다시 설정합니다.
+
'스냅샷 업데이트 - 소스 경로_SVM: volume_|_cluster://SVM/volume_,... -destination-path_SVM:volume_|_cluster://SVM/volume_,... -enable-storage-Efficiency true

+
전체 명령 구문은 man 페이지를 참조하십시오.

+
[NOTE]
====
이 명령은 타겟 SVM 또는 타겟 클러스터에서 실행해야 합니다. 소스 및 타겟에 공통 스냅샷 복사본이 존재하지 않으면 명령이 실패합니다. '스냅샷 초기화'를 사용하여 관계를 다시 초기화합니다.

====
+
다음 예에서는 svm1의 소스 볼륨 VolA와 sm_backup의 대상 볼륨 VolA_dst 간의 관계를 업데이트하고 스토리지 효율성을 다시 활성화합니다.

+
[listing]
----
cluster_dst::> snapmirror update -source-path svm1:volA -destination-path svm_backup:volA_dst -enable-storage-efficiency true
----

