---
permalink: data-protection/snapmirror-svm-replication-concept.html 
sidebar: sidebar 
keywords: understand, snapmirror, svm, replication, SVM disaster recovery storage limits 
summary: SnapMirror를 사용하여 SVM 간에 데이터 보호 관계를 생성할 수 있습니다. 이러한 유형의 데이터 보호 관계에서는 SVM이 소유한 볼륨의 데이터뿐만 아니라 NFS 엑스포트 및 SMB 공유에서 RBAC에 이르는 SVM 구성 전체 또는 일부를 복제합니다. 
---
= SnapMirror SVM 복제에 대해 알아보십시오
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapMirror를 사용하여 SVM 간에 데이터 보호 관계를 생성할 수 있습니다. 이러한 유형의 데이터 보호 관계에서 NFS 엑스포트, SMB 공유에서 RBAC에 이르는 SVM 구성의 전체 또는 일부를 복제할 뿐만 아니라 SVM이 소유한 볼륨의 데이터도 복제됩니다.



== 지원되는 관계 유형

데이터를 지원하는 SVM만 복제할 수 있습니다. 지원되는 데이터 보호 관계 유형은 다음과 같습니다.

* _SnapMirror DR_ 대상에서 현재 소스에 있는 스냅샷 복사본만 일반적으로 포함됩니다.
+
ONTAP 9.9.1부터 이 동작은 미러 볼트 정책을 사용할 때 변경됩니다. ONTAP 9.9.1부터 소스 및 대상에 서로 다른 스냅샷 정책을 생성할 수 있으며, 소스의 스냅샷 복사본으로 대상에 있는 스냅샷 복사본을 덮어쓰지 않음:

+
** 정상적인 예약 작업, 업데이트 및 재동기화 중에 소스에서 타겟으로 덮어써지지 않습니다
** 분리 작업 중에는 삭제되지 않습니다.
** 플립 재동기화 작업 중에는 삭제되지 않습니다.
ONTAP 9.9.1 이상을 사용하여 미러 소산 정책을 사용하여 SVM 재해 관계를 구성하면 정책은 다음과 같이 작동합니다.
** 소스의 사용자 정의 스냅샷 복사본 정책이 타겟으로 복제되지 않습니다.
** 시스템 정의 스냅샷 복사본 정책이 타겟으로 복사되지 않습니다.
** 사용자 및 시스템 정의 스냅샷 정책과의 볼륨 연결은 대상에 복사되지 않습니다. SVM.


* ONTAP 9.2,_SnapMirror 통합 복제(_에서 시작)부터 DR 및 장기 보존에 대해 대상이 구성됩니다.


SnapMirror 통합 복제에 대한 자세한 내용은 을 참조하십시오 link:snapmirror-unified-replication-concept.html["SnapMirror 통합 복제 기본 사항"].

복제 정책의 _policy type_은 이 정책이 지원하는 관계 유형을 결정합니다. 다음 표에는 사용 가능한 정책 유형이 나와 있습니다.

[cols="2*"]
|===


| 정책 유형입니다 | 관계 유형 


 a| 
비동기식 - 미러
 a| 
SnapMirror DR



 a| 
대칭 복사 - 볼트
 a| 
통합 복제

|===


== XDP는 ONTAP 9.4에서 SVM 복제 기본값으로 DP를 대체합니다

ONTAP 9.4부터 SVM 데이터 보호 관계는 기본적으로 XDP 모드로 설정됩니다. SVM 데이터 보호 관계는 ONTAP 9.3 및 이전 버전에서 DP 모드로 계속 기본값입니다.

기존 관계는 새 기본값의 영향을 받지 않습니다. 관계가 이미 DP 유형인 경우 DP 유형이 됩니다. 다음 표에서는 예상할 수 있는 동작을 보여 줍니다.

[cols="3*"]
|===


| 지정하는 경우... | 유형은... | 기본 정책(정책을 지정하지 않은 경우)은... 


 a| 
DP
 a| 
XDP
 a| 
MirrorAllSnapshots(SnapMirror DR)



 a| 
아무것도 없습니다
 a| 
XDP
 a| 
MirrorAllSnapshots(SnapMirror DR)



 a| 
XDP
 a| 
XDP
 a| 
MirrorAndVault(통합 복제)

|===
기본 변경 사항에 대한 자세한 내용은 다음 참조: link:version-flexible-snapmirror-default-concept.html["XDP는 DP를 SnapMirror 기본값으로 바꿉니다"].

[NOTE]
====
SVM 복제에서는 버전에 상관없이 지원되지 않습니다. SVM 재해 복구 구성에서 페일오버 및 페일백 작업을 지원하려면 타겟 SVM이 소스 SVM 클러스터와 동일한 ONTAP 버전을 실행 중인 클러스터에 있어야 합니다.

====
link:compatible-ontap-versions-snapmirror-concept.html["SnapMirror 관계에 대한 호환 ONTAP 버전"]



== SVM 구성을 복제하는 방법

SVM 복제 관계의 내용은 다음 필드의 상호 작용에 의해 결정됩니다.

* 'napMirror create' 명령의 '-identity-preserve true' 옵션은 전체 SVM 구성을 복제합니다.
+
를 클릭합니다 `-identity-preserve false` 옵션은 SVM의 볼륨, 인증 및 권한 부여 구성과 에 나와 있는 프로토콜 및 이름 서비스 설정만 복제합니다 link:snapmirror-svm-replication-concept.html#configurations-replicated-in-svm-disaster-recovery-relationships["SVM 재해 복구 관계에 복제된 구성"].

* 'napMirror policy create' 명령의 '-discard-configs network' 옵션은 소스 및 대상 SVM이 서로 다른 서브넷에 있는 경우에 사용하기 위해 SVM 복제에서 LIF 및 관련 네트워크 설정을 제외합니다.
* 볼륨 수정 명령의 '-vserver-dr-protection protected' 옵션은 SVM 복제에서 지정된 볼륨을 제외합니다.


그렇지 않으면 SVM 복제가 볼륨 복제와 거의 동일합니다. 볼륨 복제에 사용하는 것과 동일한 워크플로우를 SVM 복제에 사용할 수 있습니다.



== 지원 세부 정보

다음 표에서는 SnapMirror SVM 복제에 대한 지원 정보를 보여 줍니다.

[cols="2*"]
|===


| 리소스 또는 기능 | 지원 세부 정보 


 a| 
배포 유형
 a| 
* 단일 소스에서 단일 대상으로
* ONTAP 9.4, 팬아웃. 두 개의 대상으로만 팬아웃할 수 있습니다.
+
기본적으로 소스 SVM당 하나의 ID만 보존되며 진정한 관계는 유지됩니다.





 a| 
관계 유형
 a| 
* SnapMirror 재해 복구
* ONTAP 9.2부터 SnapMirror 통합 복제




 a| 
복제 범위
 a| 
인터클러스터 전용 동일한 클러스터에서 SVM을 복제할 수 없습니다.



 a| 
자율 랜섬웨어 보호
 a| 
* ONTAP 9.12.1부터 지원됩니다. 자세한 내용은 을 link:../anti-ransomware/index.html["자율 랜섬웨어 보호"]참조하십시오.




 a| 
정합성 보장 그룹 비동기식 지원
 a| 
ONTAP 9.14.1부터 일관성 그룹이 있을 경우 최대 32개의 SVM 재해 복구 관계가 지원됩니다. 을 참조하십시오 link:../consistency-groups/protect-task.html["일관성 그룹 보호"] 및 link:../consistency-groups/limits.html["정합성 보장 그룹 제한"] 를 참조하십시오.



 a| 
FabricPool
 a| 
ONTAP 9.6부터 SnapMirror SVM 복제는 FabricPools에서 지원됩니다.



 a| 
MetroCluster
 a| 
ONTAP 9.11.1부터 MetroCluster 구성 내 SVM 재해 복구 관계의 양측이 추가 SVM 재해 복구 구성의 소스 역할을 할 수 있습니다.

ONTAP 9.5부터 MetroCluster 구성에서 SnapMirror SVM 복제가 지원됩니다.

* ONTAP 9.10.X 이전 릴리즈에서는 MetroCluster 구성이 SVM 재해 복구 관계의 대상이 될 수 없습니다.
* ONTAP 9.10.1 이상 릴리즈에서 MetroCluster 구성은 마이그레이션 목적으로만 SVM 재해 복구 관계의 대상이 될 수 있으며 에 설명된 모든 필수 요구사항을 충족해야 합니다 https://www.netapp.com/pdf.html?item=/media/83785-tr-4966.pdf["TR-4966: SVM을 MetroCluster 솔루션으로 마이그레이션"^].
* MetroCluster 구성 내의 활성 SVM만 SVM 재해 복구 관계의 소스가 될 수 있습니다.
+
전환 전 동기화 소스 SVM이나 전환 후 동기화 대상 SVM이 소스가 될 수 있습니다.

* MetroCluster 구성이 안정적인 상태인 경우 볼륨이 온라인 상태가 아니기 때문에 MetroCluster 동기화 대상 SVM이 SVM 재해 복구 관계의 소스가 될 수 없습니다.
* 동기식 소스 SVM이 SVM 재해 복구 관계의 소스인 경우 소스 SVM 재해 복구 관계 정보가 MetroCluster 파트너에게 복제됩니다.
* 스위치오버 및 스위치백 프로세스 중에 SVM 재해 복구 대상으로의 복제가 실패할 수 있습니다.
+
그러나 스위치오버 또는 스위치백 프로세스가 완료된 후에는 다음 SVM 재해 복구 예정된 업데이트가 성공적으로 수행됩니다.





 a| 
일관성 그룹
 a| 
ONTAP 9.14.1부터 지원됩니다. 자세한 내용은 을 참조하십시오 xref:../consistency-groups/protect-task.html[일관성 그룹 보호].



 a| 
ONTAP S3
 a| 
SVM 재해 복구는 지원되지 않습니다.



 a| 
SnapMirror Synchronous
 a| 
SVM 재해 복구는 지원되지 않습니다.



 a| 
버전 독립적
 a| 
지원되지 않습니다.



 a| 
볼륨 암호화
 a| 
* 소스의 암호화된 볼륨은 대상에서 암호화됩니다.
* 온보드 키 관리자 또는 KMIP 서버를 타겟에 구성해야 합니다.
* 대상에서 새 암호화 키가 생성됩니다.
* 대상에 volume.encryption을 지원하는 노드가 없으면 복제가 성공하지만 대상 볼륨은 암호화되지 않습니다.


|===


== SVM 재해 복구 관계에 복제된 구성

다음 표에서는 의 상호 작용을 보여 줍니다 `snapmirror create -identity-preserve` 옵션과 `snapmirror policy create -discard-configs network` 옵션:

[cols="5*"]
|===


2+| 구성이 복제되었습니다 2+| '*‑identity‑preserve true*' | '*‑identity‑preserve false*' 


|  |  | '-discard-configs 네트워크'가 설정되지 않은 정책 * | * '-discard-configs 네트워크'가 설정된 정책 * |  


 a| 
네트워크
 a| 
NAS LIF
 a| 
예
 a| 
아니요
 a| 
아니요



 a| 
LIF Kerberos 구성
 a| 
예
 a| 
아니요
 a| 
아니요



 a| 
SAN LIF
 a| 
아니요
 a| 
아니요
 a| 
아니요



 a| 
방화벽 정책
 a| 
예
 a| 
예
 a| 
아니요



 a| 
서비스 정책
 a| 
예
 a| 
예
 a| 
아니요



 a| 
루트
 a| 
예
 a| 
아니요
 a| 
아니요



 a| 
브로드캐스트 도메인
 a| 
아니요
 a| 
아니요
 a| 
아니요



 a| 
서브넷
 a| 
아니요
 a| 
아니요
 a| 
아니요



 a| 
IPspace
 a| 
아니요
 a| 
아니요
 a| 
아니요



 a| 
중소기업
 a| 
SMB 서버
 a| 
예
 a| 
예
 a| 
아니요



 a| 
로컬 그룹 및 로컬 사용자
 a| 
예
 a| 
예
 a| 
예



 a| 
권한
 a| 
예
 a| 
예
 a| 
예



 a| 
섀도 복사본
 a| 
예
 a| 
예
 a| 
예



 a| 
BranchCache입니다
 a| 
예
 a| 
예
 a| 
예



 a| 
서버 옵션
 a| 
예
 a| 
예
 a| 
예



 a| 
서버 보안
 a| 
예
 a| 
예
 a| 
아니요



 a| 
더 높여 줍니다
 a| 
예
 a| 
예
 a| 
예



 a| 
symlink
 a| 
예
 a| 
예
 a| 
예



 a| 
FPolicy 정책, Fsecurity 정책 및 Fsecurity NTFS입니다
 a| 
예
 a| 
예
 a| 
예



 a| 
이름 매핑 및 그룹 매핑
 a| 
예
 a| 
예
 a| 
예



 a| 
감사 정보
 a| 
예
 a| 
예
 a| 
예



 a| 
NFS 를 참조하십시오
 a| 
엑스포트 정책
 a| 
예
 a| 
예
 a| 
아니요



 a| 
엑스포트 정책 규칙
 a| 
예
 a| 
예
 a| 
아니요



 a| 
NFS 서버
 a| 
예
 a| 
예
 a| 
아니요



 a| 
RBAC
 a| 
보안 인증서
 a| 
예
 a| 
예
 a| 
아니요



 a| 
로그인 사용자, 공개 키, 역할 및 역할 구성
 a| 
예
 a| 
예
 a| 
예



 a| 
SSL
 a| 
예
 a| 
예
 a| 
아니요



 a| 
네임 서비스
 a| 
DNS 및 DNS 호스트
 a| 
예
 a| 
예
 a| 
아니요



 a| 
Unix 사용자 및 UNIX 그룹
 a| 
예
 a| 
예
 a| 
예



 a| 
Kerberos 영역 및 Kerberos 키 블록
 a| 
예
 a| 
예
 a| 
아니요



 a| 
LDAP 및 LDAP 클라이언트
 a| 
예
 a| 
예
 a| 
아니요



 a| 
넷그룹
 a| 
예
 a| 
예
 a| 
아니요



 a| 
NIS를 선택합니다
 a| 
예
 a| 
예
 a| 
아니요



 a| 
웹 및 웹 액세스
 a| 
예
 a| 
예
 a| 
아니요



 a| 
볼륨
 a| 
오브젝트
 a| 
예
 a| 
예
 a| 
예



 a| 
Snapshot 복사본 및 스냅샷 정책
 a| 
예
 a| 
예
 a| 
예



 a| 
자동 삭제 정책
 a| 
아니요
 a| 
아니요
 a| 
아니요



 a| 
효율성 정책
 a| 
예
 a| 
예
 a| 
예



 a| 
할당량 정책 및 할당량 정책 규칙입니다
 a| 
예
 a| 
예
 a| 
예



 a| 
복구 대기열
 a| 
예
 a| 
예
 a| 
예



 a| 
루트 볼륨
 a| 
네임스페이스
 a| 
예
 a| 
예
 a| 
예



 a| 
사용자 데이터
 a| 
아니요
 a| 
아니요
 a| 
아니요



 a| 
Qtree
 a| 
아니요
 a| 
아니요
 a| 
아니요



 a| 
할당량
 a| 
아니요
 a| 
아니요
 a| 
아니요



 a| 
파일 레벨 QoS
 a| 
아니요
 a| 
아니요
 a| 
아니요



 a| 
속성: 루트 볼륨 상태, 공간 보장, 크기, 크기 조정 및 총 파일 수입니다
 a| 
아니요
 a| 
아니요
 a| 
아니요



 a| 
스토리지 QoS
 a| 
QoS 정책 그룹
 a| 
예
 a| 
예
 a| 
예



 a| 
파이버 채널(FC)
 a| 
아니요
 a| 
아니요
 a| 
아니요



 a| 
iSCSI
 a| 
아니요
 a| 
아니요
 a| 
아니요



 a| 
LUN을 클릭합니다
 a| 
오브젝트
 a| 
예
 a| 
예
 a| 
예



 a| 
Igroup
 a| 
아니요
 a| 
아니요
 a| 
아니요



 a| 
포트 세트
 a| 
아니요
 a| 
아니요
 a| 
아니요



 a| 
일련 번호
 a| 
아니요
 a| 
아니요
 a| 
아니요



 a| 
SNMP를 선택합니다
 a| 
V3 사용자
 a| 
예
 a| 
예
 a| 
아니요

|===


== SVM 재해 복구 스토리지 제한

다음 표는 스토리지 오브젝트당 지원되는 최대 볼륨 수 및 SVM 재해 복구 관계의 권장 최대 수를 보여줍니다. 제한 사항은 플랫폼에 따라 다를 수 있습니다. 을 참조하십시오 link:https://hwu.netapp.com/["Hardware Universe"^] 특정 구성에 대한 제한 사항을 알아봅니다.

[cols="2*"]
|===


| 스토리지 객체 | 제한 


 a| 
SVM
 a| 
300개의 유연한 볼륨



 a| 
HA 쌍
 a| 
1,000개의 유연한 볼륨



 a| 
클러스터
 a| 
128개의 SVM 재해 관계

|===