---
permalink: data-protection/snapmirror-licensing-concept.html 
sidebar: sidebar 
keywords: snapmirror, licensing, snapvault, vault, mirror, relationship, replication, backup, back up, disaster recovery, dr 
summary: ONTAP 9.3부터 ONTAP 인스턴스 간 복제를 위한 라이센스가 간소화되었습니다. ONTAP 9 릴리즈에서는 SnapMirror 라이센스가 볼트와 미러 관계를 모두 지원합니다. 이제 사용자는 SnapMirror 라이센스를 구매하여 백업 및 재해 복구 사용 사례에 대해 ONTAP 복제를 지원할 수 있습니다. 
---
= SnapMirror 라이센스 개요
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9.3부터 ONTAP 인스턴스 간 복제를 위한 라이센스가 간소화되었습니다. ONTAP 9 릴리즈에서는 SnapMirror 라이센스가 볼트와 미러 관계를 모두 지원합니다. SnapMirror 라이센스를 사용하여 백업 및 재해 복구 사용 사례 모두에 대해 ONTAP 복제를 지원할 수 있습니다.

ONTAP 9.3 릴리즈 이전에는 ONTAP 인스턴스 간에 _vault_관계를 구성하기 위해 별도의 SnapVault 라이센스가 필요했습니다. 이때 DP 인스턴스가 더 많은 수의 Snapshot 복사본을 유지하여 보존 시간이 더 긴 백업 사용 사례를 지원할 수 있었습니다. 그리고 ONTAP 인스턴스 간에 _MIRROR_관계를 구성하려면 SnapMirror 라이센스가 필요합니다. 각 ONTAP 인스턴스가 재해 복구 사용 사례를 지원하기 위해 동일한 수의 스냅샷 복사본(즉, _MIRROR_IMAGE)을 유지해야 합니다. SnapMirror 및 SnapVault 라이센스는 모두 ONTAP 8.x 및 9.x 릴리즈에 대해 계속 사용 및 지원됩니다.

SnapVault 사용권은 계속 작동하고 ONTAP 8.x 및 9.x 릴리즈 모두에서 지원되지만, SnapVault 사용권 대신 SnapMirror 사용권을 사용할 수 있으며 미러 및 볼트 구성에 모두 사용할 수 있습니다.

ONTAP 비동기식 복제의 경우 ONTAP 9.3부터 단일 통합 복제 엔진을 사용하여 확장된 데이터 보호 모드(XDP) 정책을 구성합니다. 이때 미러 정책, 볼트(Vault) 정책 또는 미러 볼트(Mirror-Vault) 정책에 대해 SnapMirror 라이센스를 구성할 수 있습니다. 소스 및 타겟 클러스터 모두에 SnapMirror 라이센스가 필요합니다. SnapMirror 라이센스가 이미 설치되어 있는 경우에는 SnapVault 라이센스가 필요하지 않습니다. SnapMirror 비동기 영구 라이센스는 새로운 AFF 및 FAS 시스템에 설치된 ONTAP One 소프트웨어 제품군에 포함됩니다.

데이터 보호 구성 제한은 ONTAP 버전, 하드웨어 플랫폼 및 설치된 라이센스를 비롯한 여러 요소를 사용하여 결정됩니다. 자세한 내용은 을 참조하십시오 https://hwu.netapp.com/["Hardware Universe"^].



== SnapMirror 동기식 라이센스

ONTAP 9.5부터 SnapMirror 동기식 관계가 지원됩니다. SnapMirror 동기식 관계를 생성하려면 다음 라이센스가 필요합니다.

* 소스 클러스터와 대상 클러스터 모두에 SnapMirror 동기식 라이센스가 필요합니다.
+
SnapMirror 동기식 라이센스는 의 link:../system-admin/manage-licenses-concept.html["ONTAP One 라이센스 제품군"]일부입니다.

+
2019년 6월 이전에 프리미엄 또는 플래시 번들과 함께 시스템을 구매하신 경우, NetApp 마스터 키를 다운로드하여 NetApp 지원 사이트 에서 필요한 SnapMirror 동기식 라이센스를 얻을 수 있습니다 https://mysupport.netapp.com/NOW/knowledge/docs/olio/guides/master_lickey/["마스터 라이센스 키"^].

* 소스 클러스터와 대상 클러스터 모두에 SnapMirror 라이센스가 필요합니다.




== SnapMirror 클라우드 라이센스

ONTAP 9.8부터 SnapMirror 클라우드 라이센스는 ONTAP 인스턴스에서 오브젝트 스토리지 엔드포인트에 이르는 스냅샷 복사본의 비동기 복제를 제공합니다. 복제 대상은 사내 오브젝트 저장소뿐만 아니라 S3 및 S3 호환 퍼블릭 클라우드 오브젝트 스토리지 서비스를 사용하여 구성할 수 있습니다. SnapMirror 클라우드 관계는 ONTAP 시스템에서 사전 검증된 오브젝트 스토리지 대상까지 지원됩니다.

SnapMirror 클라우드는 독립 실행형 라이센스로 사용할 수 없습니다. ONTAP 클러스터당 하나의 라이센스만 필요합니다. SnapMirror 클라우드 라이센스 외에 SnapMirror 비동기식 라이센스도 필요합니다.

SnapMirror 클라우드 관계를 생성하려면 다음 라이센스가 필요합니다.

* 오브젝트 저장소 엔드포인트로 직접 복제하기 위한 SnapMirror 라이센스와 SnapMirror 클라우드 라이센스 모두
* 다중 정책 복제 워크플로우(예: 디스크-디스크-클라우드)를 구성할 경우 모든 ONTAP 인스턴스에 SnapMirror 라이센스가 필요하며, SnapMirror 클라우드 라이센스는 오브젝트 스토리지 엔드포인트로 직접 복제되는 소스 클러스터에 대해서만 필요합니다.


ONTAP 9.9.1부터 다음을 수행할 수 https://docs.netapp.com/us-en/ontap/task_dp_back_up_to_cloud.html["SnapMirror 클라우드 복제에 System Manager를 사용하십시오"]있습니다.

공인 SnapMirror 클라우드 타사 애플리케이션 목록이 NetApp 웹 사이트에 게시됩니다.



== 데이터 보호 최적화 라이센스

DPO(Data Protection Optimized) 라이센스는 더 이상 판매되지 않으며 DPO는 현재 플랫폼에서 지원되지 않습니다. 그러나 지원되는 플랫폼에 DPO 라이센스가 설치되어 있는 경우 NetApp은 해당 플랫폼의 가용성이 끝날 때까지 계속해서 지원을 제공합니다.

DPO는 ONTAP One 라이센스 번들에 포함되지 않으며, DPO 라이센스가 시스템에 설치되어 있는 경우 ONTAP One 라이센스 번들로 업그레이드할 수 없습니다.

지원되는 플랫폼에 대한 자세한 내용은 을 참조하십시오 https://hwu.netapp.com/["Hardware Universe"^].
