---
permalink: data-protection/snapmirror-licensing-concept.html 
sidebar: sidebar 
keywords: snapmirror, licensing, snapvault, vault, mirror, relationship, replication, backup, back up, disaster recovery, dr 
summary: ONTAP 9.3부터 ONTAP 인스턴스 간 복제를 위한 라이센스가 간소화되었습니다. ONTAP 9 릴리즈에서는 SnapMirror 라이센스가 볼트와 미러 관계를 모두 지원합니다. 이제 사용자는 SnapMirror 라이센스를 구매하여 백업 및 재해 복구 사용 사례에 대해 ONTAP 복제를 지원할 수 있습니다. 
---
= SnapMirror 라이센스 개요
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9.3부터 ONTAP 인스턴스 간 복제를 위한 라이센스가 간소화되었습니다. ONTAP 9 릴리즈에서는 SnapMirror 라이센스가 볼트와 미러 관계를 모두 지원합니다. 이제 사용자는 SnapMirror 라이센스를 구매하여 백업 및 재해 복구 사용 사례에 대해 ONTAP 복제를 지원할 수 있습니다.

ONTAP 9.3 릴리즈 이전에는 서로 다른 복제 사용 사례를 지원하기 위해 두 개의 라이센스가 있었습니다. ONTAP 라이센스는 SnapVault 인스턴스 간에_vault_instances를 구성해야 하는데, 여기서 DP 인스턴스는 더 많은 수의 Snapshot 복사본을 유지하여 보존 시간이 긴 백업 사용 사례를 지원할 수 있습니다. ONTAP 인스턴스 간에 _mirror_instances를 구성하기 위해 SnapMirror 라이센스가 필요했으며, 여기서 각 ONTAP 인스턴스는 클러스터 페일오버가 가능할 수 있는 재해 복구 사용 사례를 지원하기 위해 동일한 수의 스냅샷 복사본(즉, _mirror_image)을 유지합니다. SnapMirror 및 SnapVault 라이센스는 ONTAP 8.x 및 9.x 릴리즈에 대해 계속 사용할 수 있습니다.

SnapVault 라이센스는 계속 작동하며 ONTAP 8.x 및 9.x 릴리스에 모두 지원되지만 더 이상 판매되지 않습니다. SnapMirror 라이센스는 계속 제공되며 SnapVault 대신 사용할 수 있으며 미러 구성과 소산 구성 모두에 사용할 수 있습니다.

ONTAP 비동기식 복제의 경우 ONTAP 9.3부터 단일 통합 복제 엔진을 사용하여 확장된 데이터 보호 모드(XDP) 정책을 구성합니다. 이때 미러 정책, 볼트(Vault) 정책 또는 미러 볼트(Mirror-Vault) 정책에 대해 SnapMirror 라이센스를 구성할 수 있습니다. 소스 및 타겟 클러스터 모두에 SnapMirror 라이센스가 필요합니다. SnapMirror 라이센스가 이미 설치되어 있는 경우에는 SnapVault 라이센스가 필요하지 않습니다.

데이터 보호 구성 제한은 ONTAP 버전, 하드웨어 플랫폼 및 설치된 라이센스를 비롯한 여러 요소를 사용하여 결정됩니다. 자세한 내용은 을 참조하십시오 https://hwu.netapp.com/["Hardware Universe"].



== SnapMirror Synchronous 라이센스

ONTAP 9.5부터는 SnapMirror Synchronous 관계가 지원됩니다. SnapMirror Synchronous 관계를 생성하려면 다음 라이센스가 필요합니다.

* 소스 클러스터와 대상 클러스터 모두에 SnapMirror Synchronous 라이센스가 필요합니다.
+
SnapMirror Synchronous 라이센스는 프리미엄 번들 또는 데이터 보호 번들을 지원합니다.

+
2019년 6월 이전에 프리미엄 또는 플래시 번들과 함께 시스템을 구입한 경우, NetApp 마스터 키를 다운로드하여 NetApp Support 사이트에서 필요한 SnapMirror Synchronous 라이센스를 받으십시오. https://mysupport.netapp.com/NOW/knowledge/docs/olio/guides/master_lickey/["마스터 라이센스 키"]

* 소스 클러스터와 대상 클러스터 모두에 SnapMirror 라이센스가 필요합니다.




== SnapMirror Cloud 라이센스

ONTAP 9.8부터 SnapMirror 클라우드 라이센스는 ONTAP 인스턴스에서 오브젝트 스토리지 엔드포인트로 Snapshot 복사본을 비동기식으로 복제합니다. 복제 대상은 사내 오브젝트 저장소뿐만 아니라 S3 및 S3 호환 퍼블릭 클라우드 오브젝트 스토리지 서비스를 사용하여 구성할 수 있습니다. SnapMirror 클라우드 관계는 ONTAP 시스템에서 사전 검증된 오브젝트 스토리지 타겟까지 지원됩니다. ONTAP 9.8에서 승인한 오브젝트 스토리지 타겟에는 ONTAP S3, StorageGRID, AWS S3 Standard, S3 Standard-IA, S3 One Zone-IA, Microsoft Azure Blob Premium, 핫 및 쿨, GCP Standard 및 Nearline 스토리지가 포함됩니다.

SnapMirror Cloud는 독립 실행형 라이센스로 제공되지 않으며 하이브리드 클라우드 번들을 구입한 경우에만 사용할 수 있습니다. ONTAP 9.8부터 하이브리드 클라우드 번들에는 SnapMirror Cloud와 FabricPool 모두에 대한 라이센스가 포함되어 있습니다. 마찬가지로 SnapMirror 라이센스는 독립 실행형 라이센스로 제공되지 않으며 데이터 보호 번들을 구입한 경우에만 사용할 수 있습니다.

SnapMirror 클라우드 관계를 생성하려면 다음 라이센스가 필요합니다.

* SnapMirror 라이센스(데이터 보호 번들 또는 프리미엄 번들을 통해 구매)와 SnapMirror 클라우드 라이센스(하이브리드 클라우드 번들을 통해 구매)는 모두 오브젝트 저장소 끝점에 직접 복제해야 합니다.
* 다중 정책 복제 워크플로우(예: D2D(Disk-to-Disk-to-Cloud) 구성 시 모든 ONTAP 인스턴스에 SnapMirror 라이센스가 필요하고, SnapMirror 클라우드 라이센스는 오브젝트 스토리지 엔드포인트로 직접 복제되는 소스 클러스터에만 필요합니다.


SnapMirror Cloud는 NetApp 또는 승인된 NetApp 리셀러 파트너를 통해 구입할 수 있는 최종 사용자 라이센스입니다. SnapMirror 클라우드 라이센스는 최종 사용자에게 사용 권한을 제공하지만 비동기식 ONTAP에서 오브젝트 스토리지 복제를 사용할 수 없습니다. SnapMirror 클라우드에 대한 ONTAP API를 호출하려면 인증된 프로그램에서 고유한 API 키가 필요합니다. SnapMirror 클라우드 복제를 오케스트레이션하는 데 사용 허가를 받고 승인된 애플리케이션에는 System Manager가 포함되어 있으며, 여러 타사 애플리케이션 공급자에서도 사용할 수 있습니다. 이러한 권한이 부여된 응용 프로그램은 ONTAP API를 호출하는 고유한 API 키를 포함합니다. SnapMirror 클라우드 복제를 조정하고 활성화하기 위해 SnapMirror Cloud 최종 사용자 라이센스와 인증된 타사 백업 애플리케이션을 함께 사용해야 합니다.

ONTAP 9.9.1부터 SnapMirror 클라우드 복제에 System Manager를 사용할 수 있습니다. 자세한 내용은 을 참조하십시오 https://docs.netapp.com/us-en/ontap/task_dp_back_up_to_cloud.html["클라우드에 백업"].

공인 SnapMirror Cloud 타사 애플리케이션 목록은 NetApp 웹 사이트에 게시됩니다.



== 데이터 보호 번들

ONTAP 9.1부터 데이터 보호 번들이라는 솔루션의 일부로 FAS8200과 함께 새로운 ONTAP 데이터 보호 기능이 패키지로 제공됩니다. 이 새로운 하드웨어 및 소프트웨어 번들에는 보조 워크로드에 고유한 ONTAP 기능을 제공하는 새로운 DPO(DP_Optimized) 라이센스가 포함되어 있습니다. ONTAP 9.3을 도입한 DPO 라이센스는 노드당 볼륨 수를 1,000개에서 1,500개로 늘렸습니다. 또한 ONTAP 9.3에는 FAS2620 구성을 기반으로 한 데이터 보호 번들의 새로운 구성이 도입되었습니다.

DPO 라이센스는 SnapMirror 복제를 위한 2차 타겟으로 지정된 ONTAP 클러스터를 위해 특별히 설계되었습니다. DPO 라이센스는 DPO 컨트롤러에서 노드당 최대 볼륨을 늘리는 것 외에도 컨트롤러 QoS 설정을 수정하여 애플리케이션 I/O를 희생하여 더 큰 복제 트래픽을 지원합니다 이러한 이유로 DPO 라이센스는 응용 프로그램 I/O를 지원하는 클러스터에 설치해서는 안 됩니다. 응용 프로그램 성능에 영향을 줄 수 있습니다. 이후 FAS8200과 FAS2620을 기반으로 한 데이터 보호 번들은 고객 환경을 기반으로 프로그래밍 방식으로 무료 라이센스를 제공했습니다. 솔루션 번들을 구매할 때 DPO 2차 클러스터에 복제된 특정 이전 클러스터에 대해 무료 SnapMirror 라이센스가 제공됩니다. 데이터 보호 솔루션 클러스터에 DPO 라이센스가 필요하지만, 다음 플랫폼 목록에 있는 기본 클러스터에는 무료 SnapMirror 라이센스가 제공됩니다. 이 목록에 포함되지 않은 운영 클러스터는 SnapMirror 라이센스를 구입해야 합니다.

* FAS2200 시리즈
* FAS3000 시리즈
* FAS6000 시리즈
* FAS8000 시리즈




== DPO(Data Protection Optimized) 라이센스

ONTAP 9.1 및 9.3에 도입된 데이터 보호 하드웨어 및 소프트웨어 솔루션 번들은 FAS8200 및 FAS2620을 기반으로 했습니다. 이러한 플랫폼이 완성되고 새 플랫폼이 도입되면서 보조 복제 활용 사례에 대한 ONTAP 기능을 지원하기 위한 새로운 요청이 추가되었습니다. 그 결과, ONTAP 9.5 릴리스와 함께 2018년 11월에 새로운 독립형 DPO 라이센스가 도입되었습니다.

독립형 DPO 라이센스는 FAS 및 AFF 플랫폼 모두에서 지원되었으며, 새 클러스터로 사전 구성되거나 배포된 클러스터에 현장에서 소프트웨어 업그레이드로 추가될 수 있습니다. 이러한 새로운 DPO 라이센스는 하드웨어 및 소프트웨어 솔루션 번들의 일부가 아니므로 기본 클러스터에 대한 무료 SnapMirror 라이센스가 제공되지 않았습니다. 맞춤형 DPO 라이센스로 구성된 2차 클러스터도 SnapMirror 라이센스를 구입해야 하며, DPO 2차 클러스터로 복제하는 모든 1차 클러스터는 SnapMirror 라이센스를 구입해야 합니다.

여러 ONTAP 릴리스에서 DPO와 함께 추가 ONTAP 기능이 제공되었습니다.

[cols="6*"]
|===


| 피처 | 9.3 | 9.4 | 9.5 | 9.6 | 9.7 이상 


| 최대 볼륨/노드 수  a| 
1500
 a| 
1500
 a| 
1500
 a| 
2500명~1500명
 a| 
2500명~1500명



 a| 
최대 동시 복제 세션 수
 a| 
100
 a| 
200
 a| 
200
 a| 
200
 a| 
200



 a| 
워크로드 편향 *
 a| 
클라이언트 애플리케이션
 a| 
앱/SM
 a| 
SnapMirror를 참조하십시오
 a| 
SnapMirror를 참조하십시오
 a| 
SnapMirror를 참조하십시오



 a| 
HDD의 볼륨 애그리게이트 중복제거
 a| 
아니요
 a| 
예
 a| 
예
 a| 
예
 a| 
예

|===
* SnapMirror 백 오프(워크로드 바이어스) 기능의 우선 순위에 대한 자세한 내용:
* 클라이언트: 클러스터 I/O 우선 순위는 SnapMirror 트래픽이 아닌 클라이언트 워크로드(운영 애플리케이션)로 설정됩니다.
* 같음: SnapMirror 복제 요청은 운영 애플리케이션의 I/O와 우선순위가 동일합니다.
* SnapMirror: 모든 SnapMirror I/O 요청은 운영 애플리케이션의 I/O 우선 순위가 높습니다.


* 표 1: ONTAP 릴리스 전반의 노드당 최대 FlexVolumes *

[cols="7*"]
|===


|  | DPO가 없는 경우 9.3--9.5 | DPO가 있는 경우 9.3--9.5 | 9.6 DPO 미적용 | DPO 포함 9.6 | 9.7--9.9.1(DPO 제외) | 9.7 - 9..9.1(DPO 포함) 


 a| 
FAS2620
 a| 
1000입니다
 a| 
1500
 a| 
1000입니다
 a| 
1500
 a| 
1000입니다
 a| 
1500



 a| 
FAS2650
 a| 
1000입니다
 a| 
1500
 a| 
1000입니다
 a| 
1500
 a| 
1000입니다
 a| 
1500



 a| 
FAS2720
 a| 
1000입니다
 a| 
1500
 a| 
1000입니다
 a| 
1500
 a| 
1000입니다
 a| 
1500



 a| 
FAS2750
 a| 
1000입니다
 a| 
1500
 a| 
1000입니다
 a| 
1500
 a| 
1000입니다
 a| 
1500



 a| 
A200
 a| 
1000입니다
 a| 
1500
 a| 
1000입니다
 a| 
1500
 a| 
1000입니다
 a| 
1500



 a| 
A220
 a| 
1000입니다
 a| 
1500
 a| 
1000입니다
 a| 
1500
 a| 
1000입니다
 a| 
1500



 a| 
FAS8200/8300
 a| 
1000입니다
 a| 
1500
 a| 
1000입니다
 a| 
2500
 a| 
1000입니다
 a| 
2500



 a| 
A300
 a| 
1000입니다
 a| 
1500
 a| 
1000입니다
 a| 
2500
 a| 
2500
 a| 
2500



 a| 
A400
 a| 
1000입니다
 a| 
1500
 a| 
1000입니다
 a| 
2500
 a| 
2500
 a| 
2500



 a| 
FAS8700/9000
 a| 
1000입니다
 a| 
1500
 a| 
1000입니다
 a| 
2500
 a| 
1000입니다
 a| 
2500



 a| 
A700
 a| 
1000입니다
 a| 
1500
 a| 
1000입니다
 a| 
2500
 a| 
2500
 a| 
2500



 a| 
A700s를 참조하십시오
 a| 
1000입니다
 a| 
1500
 a| 
1000입니다
 a| 
2500
 a| 
2500
 a| 
2500



 a| 
A800
 a| 
1000입니다
 a| 
1500
 a| 
1000입니다
 a| 
2500
 a| 
2500
 a| 
2500

|===
구성에 대한 최신 최대 FlexVol 볼륨 지원에 대한 자세한 내용은 을 참조하십시오 https://hwu.netapp.com/["Hardware Universe"].



== 모든 새 DPO 설치에 대한 고려 사항

* DPO 라이센스 기능을 활성화한 후에는 이 기능을 비활성화하거나 실행 취소할 수 없습니다.
* DPO 라이센스를 설치하려면 ONTAP를 다시 부팅하거나 대체 작동을 활성화해야 합니다.
* DPO 솔루션은 보조 스토리지 워크로드를 위한 것으로 DPO 클러스터의 애플리케이션 워크로드 성능에 영향을 줄 수 있습니다
* DPO 라이센스는 NetApp 스토리지 플랫폼 모델의 일부 목록에서 지원됩니다.
* DPO 기능은 ONTAP 릴리즈마다 다릅니다. 호환성 표를 참조하십시오.

