---
permalink: release-notes/release-support-reference.html 
sidebar: sidebar 
keywords: release notes, release support, support levels 
summary: ONTAP 9에서 제공되는 새로운 기능에 대해 알아보십시오. 
---
= ONTAP 9 릴리스 지원
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9.8 릴리스부터 NetApp는 매년 두 번 ONTAP 릴리스를 제공합니다. 이 계획은 변경될 수 있지만 매년 2/4분기에 새로운 ONTAP 릴리즈를 제공하려는 것입니다. 최신 ONTAP 릴리즈를 활용할 수 있도록 업그레이드 기간을 계획하려면 이 정보를 사용하십시오.

[cols="50,50"]
|===
| 버전 | 출시일 


 a| 
9.15.1
 a| 
2024년 5월



 a| 
9.14.1
 a| 
2024년 1월



 a| 
9.13.1
 a| 
2023년 6월



 a| 
9.12.1
 a| 
2023년 2월



 a| 
9.11.1
 a| 
2022년 7월



 a| 
9.10.1
 a| 
2022년 1월



 a| 
9.9.1
 a| 
2021년 6월



 a| 

NOTE: 9.9.1 이전 버전의 ONTAP를 실행하는 경우 제한된 지원 또는 셀프 서비스 지원일 가능성이 높습니다. 전체 지원이 제공되는 버전으로 업그레이드하는 것을 고려해 보십시오. 에서 사용 중인 ONTAP 버전에 대한 지원 수준을 확인할 수 있습니다 https://mysupport.netapp.com/site/info/version-support#ontap_svst["NetApp Support 사이트"^].

|===


== 지원 수준

특정 버전의 ONTAP에 사용할 수 있는 지원 수준은 소프트웨어가 출시된 시기에 따라 다릅니다.

[cols="20,10,10,10,10,10,10,10,10"]
|===
| 지원 레벨 3+| 완벽한 지원 2+| 제한된 지원 3+| 셀프서비스 지원 


 a| 
년
 a| 
1
 a| 
2
 a| 
3
 a| 
4
 a| 
5
 a| 
6
 a| 
7
 a| 
8



 a| 
온라인 설명서 액세스
 a| 
예
 a| 
예
 a| 
예
 a| 
예
 a| 
예
 a| 
예
 a| 
예
 a| 
예



 a| 
기술 지원
 a| 
예
 a| 
예
 a| 
예
 a| 
예
 a| 
예
 a| 
 a| 
 a| 



 a| 
근본 원인 분석
 a| 
예
 a| 
예
 a| 
예
 a| 
예
 a| 
예
 a| 
 a| 
 a| 



 a| 
소프트웨어 다운로드
 a| 
예
 a| 
예
 a| 
예
 a| 
예
 a| 
예
 a| 
 a| 
 a| 



 a| 
서비스 업데이트(패치 릴리스 [P-releases])
 a| 
예
 a| 
예
 a| 
예
 a| 
 a| 
 a| 
 a| 
 a| 



 a| 
취약점에 대한 경고
 a| 
예
 a| 
예
 a| 
예
 a| 
 a| 
 a| 
 a| 
 a| 

|===
ONTAP의 최신 릴리즈로 업그레이드하려면 를 참조하십시오 xref:../upgrade/prepare.html[ONTAP의 최신 버전으로 업그레이드하십시오] 및 xref:../upgrade/when-to-upgrade.html[언제 ONTAP를 업그레이드해야 합니까?]
