---
permalink: fabricpool/assign-new-tag-volume-creation-task.html 
sidebar: sidebar 
keywords: assigning, new tag, volume creation 
summary: 새로 만든 볼륨에서 계층화된 새 개체에 하나 이상의 태그를 할당하려는 경우 새 개체 태그를 만들 수 있습니다. 
---
= 볼륨을 생성하는 동안 새 태그를 할당합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
새로 만든 볼륨에서 계층화된 새 개체에 하나 이상의 태그를 할당하려는 경우 새 개체 태그를 만들 수 있습니다. 태그를 사용하여 계층화 객체를 분류하고 정렬하면 데이터를 보다 쉽게 관리할 수 있습니다. ONTAP 9.8부터는 System Manager를 사용하여 개체 태그를 만들 수 있습니다.

.이 작업에 대해
FabricPool에 연결된 StorageGRID 볼륨에서만 태그를 설정할 수 있습니다. 이러한 태그는 볼륨 이동 중에 유지됩니다.

* 볼륨당 최대 4개의 태그가 허용됩니다
* CLI에서 각 개체 태그는 등호("")로 구분된 키 값 쌍이어야 합니다.
* CLI에서 여러 태그는 쉼표("")로 구분해야 합니다.
* 각 태그 값은 최대 127자를 포함할 수 있습니다
* 각 태그 키는 영문자 또는 밑줄로 시작해야 합니다.
+
키에는 영숫자와 밑줄만 포함되어야 하며 허용되는 최대 문자 수는 127입니다.





== 절차를 참조하십시오

ONTAP 시스템 관리자 또는 ONTAP CLI를 사용하여 오브젝트 태그를 할당할 수 있습니다.

[role="tabbed-block"]
====
.시스템 관리자
--
. Storage > Tiers * 로 이동합니다.
. 태그를 지정할 볼륨이 있는 스토리지 계층을 찾습니다.
. 볼륨 * 탭을 클릭합니다.
. 태그를 지정할 볼륨을 찾고 * 개체 태그 * 열에서 * 태그를 입력하려면 클릭 * 을 선택합니다.
. 키와 값을 입력합니다.
. 적용 * 을 클릭합니다.


--
.CLI를 참조하십시오
--
. '-Tiering-object-tags' 옵션과 함께 'volume create' 명령을 사용하여 지정된 태그로 새 볼륨을 생성합니다. 쉼표로 구분된 쌍으로 여러 태그를 지정할 수 있습니다.
+
[listing]
----
volume create [ -vserver <vserver name> ] -volume <volume_name> -tiering-object-tags <key1=value1> [
    ,<key2=value2>,<key3=value3>,<key4=value4> ]
----
+
다음 예에서는 개체 태그가 3개인 fp_volume1 볼륨을 생성합니다.

+
[listing]
----
vol create -volume fp_volume1 -vserver vs0 -tiering-object-tags project=fabricpool,type=abc,content=data
----


--
====