---
permalink: fabricpool/attach-cloud-tier-aggregate-task.html 
sidebar: sidebar 
keywords: attaching, cloud, tier, aggregate 
summary: 오브젝트 저장소를 클라우드 계층으로 설정한 후 FabricPool에 연결하여 사용할 애그리게이트를 지정합니다. ONTAP 9.5 이상에서는 검증된 FlexGroup 볼륨 구성요소가 포함된 애그리게이트를 연결할 수 있습니다. 
---
= 클라우드 계층을 Aggregate에 연결합니다
:icons: font
:imagesdir: ../media/


[role="lead"]
오브젝트 저장소를 클라우드 계층으로 설정한 후 FabricPool에 연결하여 사용할 애그리게이트를 지정합니다. ONTAP 9.5 이상에서는 검증된 FlexGroup 볼륨 구성요소가 포함된 애그리게이트를 연결할 수 있습니다.

ONTAP CLI를 사용하여 FabricPool용 애그리게이트를 설정할 경우, 애그리게이트가 이미 존재해야 합니다.

[NOTE]
====
System Manager를 사용하여 FabricPool용 애그리게이트를 설정할 경우, 애그리게이트를 생성하여 FabricPool에 사용하도록 설정할 수 있습니다.

====
.단계
. * 선택 사항 *: 볼륨의 데이터 양이 비활성 상태인지 확인하려면 의 단계를 따르십시오 link:determine-data-inactive-reporting-task.html["비활성 데이터 보고를 사용하여 볼륨의 비활성 데이터 양을 결정합니다"].
+
볼륨의 비활성 데이터 양을 보면 FabricPool에 사용할 애그리게이트를 결정할 수 있습니다.

. 'Storage aggregate object-store attach' 명령을 사용하여 오브젝트 저장소를 Aggregate에 연결합니다.
+
Aggregate가 FabricPool에 사용되지 않고 기존 볼륨이 포함되어 있는 경우 볼륨에 기본 '스냅샷 전용' 계층화 정책이 할당됩니다.

+
[listing]
----
cluster1::> storage aggregate object-store attach -aggregate myaggr
-object-store-name Amazon01B1
----
+
"allow-flexgroup" "true" 옵션을 사용하면 FlexGroup 볼륨 구성요소를 포함하는 애그리게이트를 연결할 수 있습니다.

. 오브젝트 저장소 정보를 표시하고 'storage aggregate object-store show' 명령을 사용하여 연결된 오브젝트 저장소를 사용할 수 있는지 확인합니다.
+
[listing]
----
cluster1::> storage aggregate object-store show

Aggregate    Object Store Name    Availability State
---------    -----------------    ------------------
myaggr       Amazon01B1           available
----

