---
permalink: fabricpool/benefits-storage-tiers-concept.html 
sidebar: sidebar 
keywords: benefits, storage, tiers, using, fabricpool 
summary: FabricPool를 사용하도록 애그리게이트를 구성하면 스토리지 계층을 사용할 수 있습니다. 스토리지 시스템의 성능과 비용을 효율적으로 조정하고, 공간 사용률을 모니터링 및 최적화하고, 스토리지 계층 간에 정책 기반 데이터 이동을 수행할 수 있습니다. 
---
= FabricPool를 사용하여 스토리지 계층의 이점 실현
:icons: font
:imagesdir: ../media/


[role="lead"]
FabricPool를 사용하도록 애그리게이트를 구성하면 스토리지 계층을 사용할 수 있습니다. 스토리지 시스템의 성능과 비용을 효율적으로 조정하고, 공간 사용률을 모니터링 및 최적화하고, 스토리지 계층 간에 정책 기반 데이터 이동을 수행할 수 있습니다.

* 데이터의 액세스 빈도 여부에 따라 데이터를 계층에 저장하여 스토리지 성능을 최적화하고 스토리지 비용을 절감할 수 있습니다.
+
** 자주 액세스되는(""핫") 데이터는 _ 성능 계층에 저장됩니다.
+
성능 계층에서는 스토리지 시스템의 All-Flash(All-SSD) 애그리게이트와 같은 고성능 운영 스토리지를 사용합니다.

** 자주 액세스하지 않는("'콜드') 데이터는 _ 클라우드 계층 _ 에 저장되며, 이를 _ 용량 계층 _ 이라고도 합니다.
+
클라우드 계층은 더 적은 비용으로 높은 성능을 요구하지 않는 오브젝트 저장소를 사용합니다.



* 데이터를 저장할 계층을 유연하게 지정할 수 있습니다.
+
볼륨 레벨에서 지원되는 계층화 정책 옵션 중 하나를 지정할 수 있습니다. 핫 또는 콜드 데이터가 될 때 계층 간에 데이터를 효율적으로 이동할 수 있는 옵션을 제공합니다.

+
link:tiering-policies-concept.html#types-of-fabricpool-tiering-policies["FabricPool 계층화 정책의 유형입니다"]

* FabricPool의 클라우드 계층으로 사용할 지원 오브젝트 저장소 중 하나를 선택할 수 있습니다.
* FabricPool 지원 애그리게이트에서 공간 활용률을 모니터링할 수 있습니다.
* 비활성 데이터 보고를 사용하여 볼륨의 비활성 데이터 양을 확인할 수 있습니다.
* 스토리지 시스템의 사내 설치 공간을 줄일 수 있습니다.
+
클라우드 계층에 클라우드 기반 오브젝트 저장소를 사용하면 물리적 공간을 절약할 수 있습니다.


