---
permalink: fabricpool/create-volume-task.html 
sidebar: sidebar 
keywords: creating, volume, fabricpool, tiering, policy, policies, create, snap shot, snapshot, aggregate, flexgroup, cloud retrieval 
summary: FabricPool용 볼륨을 생성할 때 계층화 정책을 지정할 수 있습니다. 계층화 정책을 지정하지 않으면 생성된 볼륨은 기본 스냅샷 전용 계층화 정책을 사용합니다. 스냅샷 전용 또는 자동 계층화 정책이 있는 볼륨의 경우 계층화 최소 냉각 기간을 지정할 수도 있습니다. 
---
= FabricPool용 볼륨을 생성합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
FabricPool 지원 애그리게이트에서 직접 새 볼륨을 생성하거나 기존 볼륨을 다른 애그리게이트에서 FabricPool 지원 애그리게이트로 이동하여 FabricPool에 볼륨을 추가할 수 있습니다.

FabricPool용 볼륨을 생성할 때 계층화 정책을 지정할 수 있습니다. 계층화 정책을 지정하지 않으면 생성된 볼륨은 기본 '스냅샷 전용' 계층화 정책을 사용합니다. '스냅샷 전용' 또는 '자동' 계층화 정책을 사용하는 볼륨의 경우 계층화 최소 냉각 기간을 지정할 수도 있습니다.

.필요한 것
* '자동' 계층화 정책을 사용하도록 볼륨을 설정하거나 계층화 최소 냉각 기간을 지정하려면 ONTAP 9.4 이상이 필요합니다.
* FlexGroup 볼륨을 사용하려면 ONTAP 9.5 이상이 필요합니다.
* 모든 계층화 정책을 사용하도록 볼륨을 설정하려면 ONTAP 9.6 이상이 필요합니다.
* '-cloud-retrieval-policy' 파라미터를 사용하도록 볼륨을 설정하려면 ONTAP 9.8 이상이 필요합니다.


.단계
. 'volume create' 명령을 사용하여 FabricPool에 대한 새 볼륨을 생성합니다.
+
** '-Tiering-policy' 선택적 매개 변수를 사용하면 볼륨에 대한 계층화 정책을 지정할 수 있습니다.
+
다음 계층화 정책 중 하나를 지정할 수 있습니다.

+
*** '스냅샷 전용'(기본값)
*** 자동
*** 모두
*** 'backup'(사용 안 함)
*** "없음"
+
link:tiering-policies-concept.html#types-of-fabricpool-tiering-policies["FabricPool 계층화 정책의 유형입니다"]



** '-cloud-retrieval-policy' 선택적 매개 변수를 사용하면 고급 권한 수준을 가진 클러스터 관리자가 계층화 정책에 의해 제어되는 기본 클라우드 마이그레이션 또는 검색 동작을 재정의할 수 있습니다.
+
다음 클라우드 검색 정책 중 하나를 지정할 수 있습니다.

+
*** "기본"입니다
+
계층화 정책은 어떤 데이터를 다시 가져오는지 결정하므로 '기본' 클라우드 검색 정책을 사용하면 클라우드 데이터 검색에 대한 변경 사항은 없습니다. 즉, 이 동작은 ONTAP 9.8 이전 버전과 동일합니다.

+
**** 계층화 정책이 "없음" 또는 "스냅샷 전용"인 경우 "기본값"은 모든 클라이언트 기반 데이터 읽기가 클라우드 계층에서 성능 계층으로 풀링됨을 의미합니다.
**** 계층화 정책이 "자동"인 경우 모든 클라이언트 기반 랜덤 읽기는 풀링되지만 순차적 읽기는 풀링되지 않습니다.
**** 계층화 정책이 "ALL"인 경우 클라우드 계층에서 클라이언트 기반 데이터를 추출하지 않습니다.


*** "읽기"
+
모든 클라이언트 기반 데이터 읽기는 클라우드 계층에서 성능 계층으로 가져옵니다.

*** "안 돼.
+
클라우드 계층에서 성능 계층으로 클라이언트 기반 데이터를 끌어오는 기능은 없습니다

*** "홍보"
+
**** 계층화 정책이 "없음"인 경우 모든 클라우드 데이터가 클라우드 계층에서 성능 계층으로 풀링됩니다
**** 계층화 정책 '스냅샷 전용'의 경우 모든 활성 파일 시스템 데이터가 클라우드 계층에서 성능 계층으로 풀링됩니다.




** 고급 권한 레벨의 '-Tiering-Minimum-Cooling-Days' 선택적 매개 변수를 사용하면 '스냅샷 전용' 또는 '자동' 계층화 정책을 사용하는 볼륨에 대한 계층화 최소 냉각 기간을 지정할 수 있습니다.
+
ONTAP 9.8부터 계층화 최소 냉각 시간을 2에서 183 사이의 값으로 지정할 수 있습니다. 9.8 이전 버전의 ONTAP를 사용하는 경우 계층화 최소 냉각 요일에 대해 2 - 63 사이의 값을 지정할 수 있습니다.





.FabricPool에 대한 볼륨 생성 예
다음 예에서는 "myFabricPool" FabricPool 지원 애그리게이트에서 "mvol1"이라는 볼륨을 생성합니다. 계층화 정책은 'auto'로 설정되고 계층화 최소 냉각 기간은 45일로 설정됩니다.

[listing]
----
cluster1::*> volume create -vserver myVS -aggregate myFabricPool
-volume myvol1 -tiering-policy auto -tiering-minimum-cooling-days 45
----
.관련 정보
link:../flexgroup/index.html["FlexGroup 볼륨 관리"]
