---
permalink: fabricpool/create-mirror-task.html 
sidebar: sidebar 
keywords: creating, fabricpool, mirror 
summary: FabricPool 미러를 생성하려면 두 개의 오브젝트 저장소를 단일 FabricPool에 연결합니다. 두 번째 개체 저장소를 기존 단일 개체 저장소 FabricPool 구성에 연결하여 FabricPool 미러를 만들거나, 새 단일 개체 저장소 FabricPool 구성을 만든 다음 두 번째 개체 저장소를 연결할 수 있습니다. MetroCluster 구성에서 FabricPool 미러를 생성할 수도 있습니다. 
---
= FabricPool 미러를 생성합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
FabricPool 미러를 생성하려면 두 개의 오브젝트 저장소를 단일 FabricPool에 연결합니다. 두 번째 개체 저장소를 기존 단일 개체 저장소 FabricPool 구성에 연결하여 FabricPool 미러를 만들거나, 새 단일 개체 저장소 FabricPool 구성을 만든 다음 두 번째 개체 저장소를 연결할 수 있습니다. MetroCluster 구성에서 FabricPool 미러를 생성할 수도 있습니다.

.필요한 것
* 'Storage aggregate object-store config' 명령을 사용하여 이미 두 개의 오브젝트 저장소를 만들어야 합니다.
* MetroCluster 구성에서 FabricPool 미러를 생성하는 경우
+
** MetroCluster를 이미 설정하고 구성해야 합니다
** 선택한 클러스터에 오브젝트 저장소 구성을 생성해야 합니다.
+
MetroCluster 구성에서 두 클러스터에 모두 FabricPool 미러를 생성하는 경우 두 클러스터 모두에서 오브젝트 저장소 구성을 생성해야 합니다.

** MetroCluster 구성에 온-프레미스 개체 저장소를 사용하지 않는 경우 다음 시나리오 중 하나가 있는지 확인해야 합니다.
+
*** 오브젝트 저장소는 다른 가용성 영역에 있습니다
*** 오브젝트 저장소는 오브젝트의 복사본을 여러 가용성 영역에 보관하도록 구성됩니다
+
link:setup-object-stores-mcc-task.html["MetroCluster 구성에서 FabricPool에 대한 오브젝트 저장소 설정"]







.이 작업에 대해
FabricPool 미러에 사용하는 오브젝트 저장소는 운영 오브젝트 저장소와 달라야 합니다.

FabricPool 미러를 생성하는 절차는 MetroCluster 구성과 비 MetroCluster 구성 모두에서 동일합니다.

.단계
. 기존 FabricPool 구성을 사용하지 않는 경우 'Storage aggregate object-store attach' 명령을 사용하여 오브젝트 저장소를 Aggregate에 연결하여 새 구성을 생성합니다.
+
이 예제에서는 개체 저장소를 Aggregate에 연결하여 새 FabricPool 를 만듭니다.

+
[listing]
----
cluster1::> storage aggregate object-store attach -aggregate aggr1 -name my-store-1
----
. 'Storage aggregate object-store mirror' 명령을 사용하여 두 번째 오브젝트 저장소를 Aggregate에 연결합니다.
+
이 예제에서는 두 번째 개체 저장소를 Aggregate에 연결하여 FabricPool 미러를 만듭니다.

+
[listing]
----
cluster1::> storage aggregate object-store mirror -aggregate aggr1 -name my-store-2
----

