---
permalink: fabricpool/enable-disable-aggressive-read-ahead-task.html 
sidebar: sidebar 
keywords: creating, volume, fabricpool, aggressive read ahead, enable, on prem, on premises, disable 
summary: ONTAP 9.14.1부터는 영화 스트리밍 워크로드 등과 같은 미디어 및 엔터테인먼트를 지원하는 FabricPools의 볼륨에 대해 공격적인 미리 읽기 모드를 사용하거나 사용하지 않도록 설정할 수 있습니다. 
---
= FabricPool에서 ONTAP 볼륨을 활성화하여 적극적인 읽기-헤드를 수행할 수 있습니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9.14.1부터는 FabricPools의 볼륨에 대해 공격적인 미리 읽기 모드를 활성화하거나 비활성화할 수 있습니다. FabricPool를 지원하는 모든 온프레미스 플랫폼의 ONTAP 9.14.1에서 공격적인 미리 읽기 모드를 사용할 수 있습니다. 이 기능은 기본적으로 비활성화되어 있습니다.

적극적인 미리 읽기 가 _disabled_인 경우 FabricPool는 클라이언트 응용 프로그램에 필요한 파일 블록만 읽습니다. 전체 파일을 읽을 필요가 없습니다. 이로 인해 네트워크 트래픽, 특히 대용량 GB 및 TB 크기의 파일이 감소할 수 있습니다. _enabling_aggressive read-ahead는 볼륨에서 이 기능을 끄고 FabricPool는 객체 저장소에서 전체 파일을 순차적으로 읽으므로 처리량을 높이고 파일에 대한 클라이언트 읽기 대기 시간을 줄입니다. 기본적으로 계층화된 데이터를 순차적으로 읽으면 콜드 데이터가 로컬 계층에 기록되지 않고

공격적인 미리 읽기 거래 네트워크 효율성을 통해 계층화된 데이터의 성능을 향상시킵니다.

.이 작업에 대해
를 클릭합니다 `aggressive-readahead-mode` 명령에는 두 가지 옵션이 있습니다.

* `none`: 미리 읽기를 사용할 수 없습니다.
* `file_prefetch`: 시스템은 클라이언트 응용 프로그램의 앞에 전체 파일을 메모리로 읽어들입니다.


.시작하기 전에
* 클러스터 또는 SVM 관리자여야 합니다.
* advanced 권한 수준이어야 합니다.




== 볼륨을 생성하는 동안 적극적인 미리 읽기 모드를 활성화합니다

.단계
. 권한 수준을 고급으로 설정합니다.
+
[source, cli]
----
set -privilege advanced
----
. 볼륨을 생성하고 적극적인 미리 읽기 모드를 활성화합니다.
+
[source, cli]
----
volume create -volume <volume name>  -aggressive-readahead-mode <none|file_prefetch>
----
+
다음 예에서는 file_prefetch 옵션을 사용하여 적극적인 read-ahead를 사용하도록 설정한 vol1이라는 볼륨을 생성합니다.

+
[listing]
----
volume create -volume vol1 -aggressive-readahead-mode file_prefetch
----




== 적극적인 미리 읽기 모드를 비활성화합니다

.단계
. 권한 수준을 고급으로 설정합니다.
+
[source, cli]
----
set -privilege advanced
----
. 적극적인 미리 읽기 모드 비활성화:
+
[source, cli]
----
volume modify -volume <volume name>  -aggressive-readahead-mode none
----
+
다음 예에서는 vol1이라는 볼륨을 수정하여 적극적인 미리 읽기 모드를 비활성화합니다.

+
[listing]
----
volume modify -volume vol1 -aggressive-readahead-mode none
----




== 볼륨에 대해 적극적인 미리 읽기 모드를 봅니다

.단계
. 권한 수준을 고급으로 설정합니다.
+
[source, cli]
----
set -privilege advanced
----
. 공격적인 미리 읽기 모드 보기:
+
[source, cli]
----
volume show -fields aggressive-readahead-mode
----

