---
permalink: fabricpool/install-license-aws-azure-ibm-task.html 
sidebar: sidebar 
keywords: installing, fabricpool, license 
summary: '새로 주문한 AFF 시스템에는 사용자가 선택하는 경우 FabricPool에서 타사 오브젝트 저장소(AWS S3, Azure Blob Storage, IBM Cloud Object Storage, Alibaba Cloud Object Storage 또는 Google Cloud Storage)를 사용할 수 있는 10TB 용량 기간 기반 라이센스가 무료로 제공됩니다. AFF 시스템에서 추가 용량이 필요하거나, 비-AFF 시스템에서 타사 오브젝트 저장소를 사용하려는 경우 또는 기존 클러스터에서 업그레이드할 경우 FabricPool 라이센스가 필요합니다.' 
---
= FabricPool 라이센스를 설치합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
새로 주문한 AFF 시스템에는 사용자가 선택하는 경우 FabricPool에서 타사 오브젝트 저장소(AWS S3, Azure Blob Storage, IBM Cloud Object Storage, Alibaba Cloud Object Storage 또는 Google Cloud Storage)를 사용할 수 있는 10TB 용량 기간 기반 라이센스가 무료로 제공됩니다. AFF 시스템에서 추가 용량이 필요하거나, 비-AFF 시스템에서 타사 오브젝트 저장소를 사용하려는 경우 또는 기존 클러스터에서 업그레이드할 경우 FabricPool 라이센스가 필요합니다.

FabricPool 라이센스는 클러스터 차원의 라이센스입니다. 여기에는 AWS S3, Azure Blob Storage 또는 IBM Cloud Object Storage, Alibaba Cloud Object Storage 또는 클러스터의 FabricPool와 연결된 Google Cloud Storage 클라우드 계층에 대해 구입한 사용 제한이 포함됩니다. 클러스터 전체의 사용량이 사용 제한 용량을 초과해서는 안 됩니다. 라이센스의 사용 한도를 늘려야 하는 경우 영업 담당자에게 문의하십시오.

FabricPool 라이센스는 영구 또는 기간 기반, 1년 또는 3년 형식으로 제공됩니다.

기존 클러스터에 대해 처음으로 FabricPool를 주문할 경우 10TB의 가용 용량을 가진 용어 기반 FabricPool 라이센스가 제공됩니다. 영구 라이센스에는 여유 용량을 사용할 수 없습니다.

클라우드 계층에 NetApp StorageGRID 또는 ONTAP S3를 사용하는 경우에는 라이센스가 필요하지 않습니다. 사용 중인 공급자에 관계없이 Cloud Volumes ONTAP에는 FabricPool 라이센스가 필요하지 않습니다.

이 작업은 System Manager를 사용하여 클러스터에 라이센스 파일을 업로드하는 경우에만 지원됩니다.

.단계
. NetApp Support 사이트에서 FabricPool 라이센스에 대한 NetApp 라이센스 파일(NLF)을 다운로드하십시오.
+
https://mysupport.netapp.com/site/global/dashboard["NetApp 지원"]

. System Manager를 사용하여 FabricPool 라이센스를 클러스터에 업로드합니다.
+
.. 스토리지 시스템에서 실행 중인 ONTAP 릴리즈에 따라 다음 작업을 수행합니다.
+
|===


| 실행 중인 경우... | 다음 작업을 수행합니다. 


 a| 
ONTAP 9.4 이하
 a| 
Configuration * > * Licenses * 를 클릭합니다.



 a| 
ONTAP 9.5 이상
 a| 
구성 * > * 클러스터 * > * 라이센스 * 를 클릭합니다.

|===
.. Cluster Settings * 창에서 * Licenses * 를 클릭합니다.
.. 패키지 * 창에서 * 추가 * 를 클릭합니다.
.. 라이센스 패키지 추가 * 대화 상자에서 * 파일 선택 * 을 클릭하여 다운로드한 NLF를 선택한 다음 * 추가 * 를 클릭하여 클러스터에 파일을 업로드합니다.




https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/ONTAP_FabricPool_(FP)_Licensing_Overview["FP(ONTAP FabricPool) 라이센스 개요"]

http://mysupport.netapp.com/licenses["NetApp 소프트웨어 라이센스 검색"]
