---
permalink: fabricpool/requirements-concept.html 
sidebar: sidebar 
keywords: considerations, requirements, using, fabricpool 
summary: FabricPool 구성을 최적화하려면 FabricPool 사용에 대한 몇 가지 고려 사항과 요구 사항을 숙지해야 합니다. 
---
= FabricPool 사용에 대한 고려 사항 및 요구 사항
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
FabricPool 구성을 최적화하려면 FabricPool 사용에 대한 몇 가지 고려 사항과 요구 사항을 숙지해야 합니다.



== 일반 고려 사항 및 요구 사항



=== ONTAP 9.2

ONTAP 9.2 이상의 FabricPool를 실행 중이어야 합니다.



=== ONTAP 9.4

* 다음 FabricPool 기능을 사용하려면 ONTAP 9.4 이상 릴리스를 실행해야 합니다.
+
** 를 클릭합니다 `auto` link:tiering-policies-concept.html#types-of-fabricpool-tiering-policies["계층화 정책"]
** 계층화 최소 냉각 기간 지정
** 비활성 데이터 보고(IDR)
** 클라우드에 Microsoft Azure Blob Storage를 FabricPool의 클라우드 계층으로 사용
** ONTAP Select와 함께 FabricPool 사용






=== ONTAP 9.5

* 다음 FabricPool 기능을 사용하려면 ONTAP 9.5 이상의 릴리스를 실행해야 합니다.
+
** 계층화 충만 임계값 지정
** IBM 클라우드 오브젝트 스토리지를 FabricPool의 클라우드 계층으로 사용
** 기본적으로 활성화되어 있는 클라우드 계층의 NetApp Volume Encryption(NVE)






=== ONTAP 9.6

* 다음 FabricPool 기능을 사용하려면 ONTAP 9.6 이상 버전을 실행해야 합니다.
+
** 모든 계층화 정책
** 비활성 데이터 보고는 HDD 애그리게이트에서 수동으로 활성화됩니다
** ONTAP 9.6으로 업그레이드하고 시점에 애그리게이트를 생성할 때, SSD 애그리게이트에 대해 비활성 데이터 보고가 자동으로 활성화됩니다. 단, CPU가 4개 미만이거나 RAM이 6GB 미만인 로우엔드 시스템 또는 WAFL 버퍼 캐시 크기가 3GB 미만인 경우는 예외입니다.
+
ONTAP는 시스템 로드를 모니터링하며, 로드가 4분 동안 계속 높게 유지되면 IDR이 비활성화되고 자동으로 활성화되지 않습니다. IDR을 수동으로 다시 활성화할 수 있지만 수동으로 활성화된 IDR은 자동으로 비활성화되지 않습니다.

** Alibaba 클라우드 오브젝트 스토리지를 FabricPool의 클라우드 계층으로 사용
** Google Cloud Platform을 FabricPool의 클라우드 계층으로 사용
** 클라우드 계층 데이터 복사본 없이 볼륨 이동






=== ONTAP 9.7

* 다음 FabricPool 기능을 사용하려면 ONTAP 9.7 이상 릴리즈를 실행 중이어야 합니다.
+
** 화이트리스트된 액세스 포인트에만 액세스하고 감사 및 보고 기능을 제공하는 비투명 HTTP 및 HTTPS 프록시.
** FabricPool 미러링을 통해 콜드 데이터를 2개의 오브젝트 저장소에 동시에 계층화합니다
** MetroCluster 구성의 FabricPool 미러
** FabricPool 연결 애그리게이트에는 NDMP 덤프 및 복구가 기본적으로 설정됩니다.
+
[NOTE]
====
백업 애플리케이션이 NFS 또는 SMB와 같은 NDMP 이외의 프로토콜을 사용하는 경우 성능 계층에서 백업되는 모든 데이터가 핫 상태가 되고 해당 데이터를 클라우드 계층으로 계층화하는 데 영향을 미칠 수 있습니다. 비 NDMP 읽기로 인해 클라우드 계층에서 성능 계층으로 데이터가 다시 마이그레이션할 수 있습니다.

====
+
https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/NDMP_Backup_and_Restore_supported_for_FabricPool%3F["FabricPool에 대한 NDMP 백업 및 복구 지원"]







=== ONTAP 9.8

* 다음 FabricPool 기능을 사용하려면 ONTAP 9.8 이상을 실행해야 합니다.
+
** 클라우드 검색
** SnapLock 엔터프라이즈 및 FabricPool SnapLock Enterprise를 지원하는 FabricPool에는 FPVR(Feature Product Variance Request)이 필요합니다. FPVR을 생성하려면 영업 팀에 문의하십시오.
** 최소 냉각 기간은 최대 183일입니다
** 사용자가 만든 사용자 지정 태그를 사용하여 개체 태그 지정
** HDD FabricPool 애그리게이트로 전환 가능
+
HDD FabricPools는 SAS, FSA, BSAS 및 mSATA 디스크와 함께 지원되며 CPU 코어가 6개 이상인 시스템에서만 지원됩니다.

+
확인합니다 https://hwu.netapp.com/Home/Index["Hardware Universe"^] 를 참조하십시오.







=== ONTAP 9.10.1

* 다음 FabricPool 기능을 사용하려면 ONTAP 9.10.1 이상을 실행해야 합니다.
+
** 스로틀링
** 온도에 민감한 저장 효율성(TSSE).






=== ONTAP 9.12.1

* 다음 FabricPool 기능을 사용하려면 ONTAP 9.12.1 이상을 실행해야 합니다.
+
** SVM 마이그레이션
** FabricPool, FlexGroup 및 SVM-DR 지원 협력 (9.12.1 이전에는 이 두 가지 기능이 함께 작동했지만 세 가지 기능이 모두 함께 작동되지는 않았습니다.)






=== ONTAP 9.14.1

* 다음 FabricPool 기능을 사용하려면 ONTAP 9.14.1 이상을 실행해야 합니다.
+
** 클라우드 쓰기
** 적극적인 미리 읽기






== 로컬 계층(애그리게이트)

FabricPool는 다음과 같은 애그리게이트 유형을 지원합니다.

* AFF 시스템에서는 FabricPool에 대해 SSD 애그리게이트만 사용할 수 있습니다.
* FAS 시스템에서는 FabricPool에 SSD 또는 HDD 애그리게이트를 사용할 수 있습니다.
* Cloud Volumes ONTAP 및 ONTAP Select에서는 FabricPool에 SSD 또는 HDD 애그리게이트를 사용할 수 있습니다. SSD 애그리게이트를 사용하는 것이 좋습니다.


[NOTE]
====
SSD와 HDD를 모두 포함하는 Flash Pool 애그리게이트는 지원되지 않습니다.

====


== 계층에서 실현해 보십시오

FabricPool은 다음과 같은 오브젝트 저장소를 클라우드 계층으로 사용할 수 있도록 지원합니다.

* Alibaba Cloud Object Storage Service(Standard, Infrequent Access)
* Amazon S3(표준, Standard-IA, One Zone-IA, 지능형 계층화, Glacier Instant Retrieval)
* Amazon Commercial Cloud Services(C2S)
* Google Cloud 스토리지(Multi-Regional, Regional, Nearline, Coldline, 아카이브)
* IBM Cloud Object Storage(Standard, Vault, Cold Vault, Flex)
* Microsoft Azure Blob 스토리지(핫 및 쿨)
* NetApp ONTAP S3(ONTAP 9.8 이상)
* NetApp StorageGRID(StorageGRID 10.3 이상)


[NOTE]
====
Glacier Flexible Retrieval 및 Glacier Deep Archive는 지원되지 않습니다.

====
* 사용하려는 오브젝트 저장소 ""버킷""(컨테이너)이 이미 설정되어 있어야 하고, 최소 10GB의 저장 공간이 있어야 하며, 이름을 바꿀 수 없습니다.
* FabricPool를 사용하는 HA 쌍에서는 오브젝트 저장소와 통신하기 위해 인터클러스터 LIF가 필요합니다.
* 클라우드 계층이 연결된 후에는 로컬 계층에서 분리할 수 없지만 를 사용할 수 있습니다 link:create-mirror-task.html["FabricPool 미러"] 로컬 계층을 다른 클라우드 계층에 연결합니다.




== ONTAP 스토리지 효율성

데이터를 클라우드 계층으로 이동할 때 압축, 중복제거, 컴팩션과 같은 스토리지 효율성이 유지되므로 필요한 오브젝트 스토리지 용량 및 전송 비용이 줄어듭니다.


NOTE: ONTAP 9.15.1부터 FabricPool는 보다 공격적이고 뛰어난 성능의 스토리지 효율성을 제공하는 인텔 QuickAssist 기술(QAT4)을 지원합니다.

애그리게이트 인라인 중복제거는 로컬 계층에서 지원되지만 관련 스토리지 효율성이 클라우드 계층에 저장된 오브젝트로 이전되지 않습니다.

모든 볼륨 계층화 정책을 사용하면 추가 스토리지 효율성을 적용하기 전에 데이터를 계층화할 수 있기 때문에 백그라운드 중복제거 프로세스와 관련된 스토리지 효율성이 감소할 수 있습니다.



== BlueXP 계층화 라이센스

FabricPool을 사용하려면 타사 오브젝트 스토리지 공급자(예: Amazon S3)를 AFF 및 FAS 시스템용 클라우드 계층으로 연결할 때 용량 기반 라이센스가 필요합니다. StorageGRID 또는 ONTAP S3를 클라우드 계층으로 사용하거나 Cloud Volumes ONTAP, Amazon FSx for NetApp ONTAP 또는 Azure NetApp Files를 통해 계층화할 때는 BlueXP Tiering 라이센스가 필요하지 않습니다.

BlueXP 라이센스(기존 FabricPool 라이센스의 애드온 또는 확장 기능 포함)는 에서 활성화됩니다 link:https://docs.netapp.com/us-en/bluexp-tiering/concept-cloud-tiering.html["BlueXP 디지털 지갑"^].



== StorageGRID 일관성 제어

StorageGRID의 일관성 제어는 StorageGRID이 오브젝트를 추적하는 데 사용하는 메타데이터의 방식에 영향을 줍니다
노드 간에 분산되고 클라이언트 요청에 대해 개체의 가용성이 보장됩니다. NetApp에서는 을 사용할 것을 권장합니다
FabricPool 타겟으로 사용되는 버킷에 대한 새로운 쓰기 후 읽기, 정합성 보장 기본 제어


NOTE: FabricPool 대상으로 사용되는 버킷에 대해 사용 가능한 정합성 보장 제어를 사용하지 마십시오.



== SAN 프로토콜에서 액세스하는 데이터를 계층화하기 위한 추가 고려 사항

SAN 프로토콜에서 액세스하는 데이터를 계층화할 때 NetApp은 연결 고려사항으로 인해 ONTAP S3 또는 StorageGRID와 같은 프라이빗 클라우드를 사용할 것을 권장합니다.


IMPORTANT: Windows 호스트가 있는 SAN 환경에서 FabricPool를 사용할 때 데이터를 클라우드로 계층화할 때 오브젝트 스토리지를 장기간 사용할 수 없게 될 경우 Windows 호스트의 NetApp LUN에 있는 파일에 액세스할 수 없거나 파일이 사라질 수 있습니다. 기술 자료 문서를 참조하십시오 link:https://kb.netapp.com/onprem/ontap/os/During_FabricPool_S3_object_store_unavailable_Windows_SAN_host_reported_filesystem_corruption["FabricPool S3 오브젝트 저장소를 사용할 수 없는 동안 Windows SAN 호스트가 파일 시스템 손상을 보고했습니다"^].



== 서비스 품질

* 처리량 수준(QoS Min)을 사용하는 경우, FabricPool에 애그리게이트를 연결하기 전에 볼륨에 대한 계층화 정책을 "없음"으로 설정해야 합니다.
+
다른 계층화 정책을 사용하면 애그리게이트는 FabricPool에 연결되지 않습니다. QoS 정책은 FabricPool가 활성화된 경우 처리량 플로어를 적용하지 않습니다.





== FabricPool에서 지원하지 않는 기능 또는 기능입니다

* WORM 지원 및 오브젝트 버전 관리가 활성화된 오브젝트 저장소
* 오브젝트 저장소 버킷에 적용되는 ILM(정보 라이프사이클 관리) 정책
+
FabricPool는 데이터 복제 및 삭제 코딩에 대해서만 StorageGRID의 정보 수명 주기 관리 정책을 지원하여 클라우드 계층 데이터를 장애로부터 보호합니다. 그러나 FabricPool는 사용자 메타데이터 또는 태그에 기반한 필터링과 같은 고급 ILM 규칙을 _NOT_지원합니다. ILM에는 일반적으로 다양한 이동 및 삭제 정책이 포함됩니다. 이러한 정책은 FabricPool의 클라우드 계층에 있는 데이터에 영향을 줄 수 있습니다. 오브젝트 저장소에 구성된 ILM 정책에 FabricPool을 사용하면 데이터 손실이 발생할 수 있습니다.

* ONTAP CLI 명령 또는 7-Mode 전환 툴을 사용하여 7-Mode 데이터 전환
* FlexArray 가상화
* RAID SyncMirror(MetroCluster 구성 제외
* ONTAP 9.7 이하 릴리즈를 사용할 때 SnapLock 볼륨
* FabricPool 지원 애그리게이트용 SMTape를 사용한 테이프 백업
* 자동 균형 조정 기능
* '없음' 이외의 공간을 사용하는 볼륨
+
루트 SVM 볼륨 및 CIFS 감사 스테이징 볼륨을 제외하고 FabricPool은 공간 보장이 아닌 다른 공간을 사용하는 볼륨이 포함된 애그리게이트에 클라우드 계층을 연결할 수 없습니다 `none`. 예를 들어, 의 공간 보장을 사용하는 볼륨입니다 `volume` (`-space-guarantee` `volume`)는 지원되지 않습니다.

* 와 클러스터 link:../data-protection/snapmirror-licensing-concept.html#data-protection-optimized-license["DP_Optimized 라이센스"]
* Flash Pool 애그리게이트로 전환 가능

