---
permalink: fabricpool/setup-ontap-s3-cloud-tier-task.html 
sidebar: sidebar 
keywords: setting up, ontap s3, cloud tier 
summary: ONTAP 9.8 이상을 실행 중인 경우 ONTAP S3를 FabricPool의 클라우드 계층으로 설정할 수 있습니다. 
---
= ONTAP S3를 클라우드 계층으로 설정합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9.8 이상을 실행 중인 경우 ONTAP S3를 FabricPool의 클라우드 계층으로 설정할 수 있습니다.

.필요한 것
원격 클러스터에 연결된 LIF의 ONTAP S3 서버 이름과 IP 주소가 있어야 합니다.

로컬 클러스터와 원격 클러스터에 모두 인터클러스터 LIF가 있어야 합니다.

https://docs.netapp.com/ontap-9/topic/com.netapp.doc.pow-s3-cg/GUID-47BBD9BF-7C3A-4902-8E41-88E54A0FDB44.html["원격 FabricPool 계층화를 위한 인터클러스터 LIF 만들기"]

.이 작업에 대해
ONTAP 9.8 이상에서 ONTAP S3 서버에 대해 로드 밸런싱이 활성화됩니다. 서버의 호스트 이름이 둘 이상의 IP 주소로 확인되는 경우 ONTAP는 반환된 모든 IP 주소(최대 16개의 IP 주소)를 사용하여 클라이언트 연결을 설정합니다. 연결이 설정되면 IP 주소가 라운드 로빈 방식으로 선택됩니다.

.절차를 참조하십시오
ONTAP System Manager 또는 ONTAP CLI를 사용하여 ONTAP S3를 FabricPool용 클라우드 계층으로 설정할 수 있습니다.

[role="tabbed-block"]
====
.시스템 관리자
--
. 스토리지 > 계층 > 클라우드 계층 추가 * 를 클릭하고 오브젝트 저장소 공급자로 ONTAP S3를 선택합니다.
. 요청된 정보를 완료합니다.
. 클라우드 미러를 생성하려면 * FabricPool 미러로 추가 * 를 클릭합니다.


FabricPool 미러는 데이터 저장소를 원활하게 대체할 수 있는 방법을 제공하므로 재해 발생 시 데이터를 사용할 수 있습니다.

--
.CLI를 참조하십시오
--
. S3 서버 및 LIF에 대한 항목을 DNS 서버에 추가합니다.
+
|===


| 옵션을 선택합니다 | 설명 


 a| 
* 외부 DNS 서버를 사용하는 경우 *
 a| 
DNS 서버 관리자에게 S3 서버 이름 및 IP 주소를 지정합니다.



 a| 
* 로컬 시스템의 DNS 호스트 테이블을 사용하는 경우 *
 a| 
다음 명령을 입력합니다.

dns host create -vserver svm_name -address ip_address -hostname s3_server_name"을 선택합니다

|===
. '-provider-type ''ontap_s3' 파라미터를 사용하여 'storage aggregate object-store config create' 명령을 사용하여 ONTAP S3 구성 정보를 지정합니다.
+
** 로컬 ONTAP 시스템이 제공된 정보로 ONTAP S3 서버에 액세스할 수 없으면 'Storage aggregate object-store config create' 명령이 실패합니다.
** '-access-key' 매개 변수를 사용하여 ONTAP S3 서버에 요청을 승인하는 데 필요한 액세스 키를 지정할 수 있습니다.
** '-secret-password' 매개변수를 사용하여 ONTAP S3 서버에 대한 요청을 인증하는 암호(비밀 액세스 키)를 지정합니다.
** ONTAP S3 서버 암호가 변경되면 로컬 ONTAP 시스템에 저장된 해당 암호를 즉시 업데이트해야 합니다.
+
이렇게 하면 ONTAP S3 오브젝트 저장소에서 중단 없이 데이터에 액세스할 수 있습니다.

** '-is-certificate-validation-enabled' 매개 변수를 'false'로 설정하면 ONTAP S3에 대한 인증서 검사가 비활성화됩니다.


+
[listing]
----
cluster1::> storage aggregate object-store config create
-object-store-name myS3 -provider-type ONTAP_S3 -server myS3server
-container-name myS3container -access-key myS3key
-secret-password myS3pass
----
. 'Storage aggregate object-store config show' 명령을 사용하여 ONTAP_S3 구성 정보를 표시하고 확인합니다.
+
'Storage aggregate object-store config modify' 명령을 사용하면 FabricPool의 'ontap_s3' 구성 정보를 수정할 수 있습니다.



--
====