---
permalink: fabricpool/setup-alibaba-object-storage-cloud-tier-task.html 
sidebar: sidebar 
keywords: setting, up, alibaba cloud object, storage, cloud tier 
summary: ONTAP 9.6 이상을 실행하는 경우 Alibaba 클라우드 오브젝트 스토리지를 FabricPool의 클라우드 계층으로 설정할 수 있습니다. 
---
= Alibaba Cloud Object Storage를 클라우드 계층으로 설정합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9.6 이상을 실행하는 경우 Alibaba 클라우드 오브젝트 스토리지를 FabricPool의 클라우드 계층으로 설정할 수 있습니다.

.Alibaba 클라우드 개체 스토리지를 FabricPool와 함께 사용할 때의 고려 사항
* Alibaba Cloud Object Storage로 계층화할 때는 A가 link:https://bluexp.netapp.com/cloud-tiering["BlueXP 계층화 라이센스"]필요합니다.
* AFF 및 FAS 시스템과 ONTAP Select에서 FabricPool는 다음 Alibaba 개체 스토리지 서비스 클래스를 지원합니다.
+
** Alibaba 개체 스토리지 서비스 표준
** Alibaba Object Storage Service 낮은 액세스 빈도
+
https://www.alibabacloud.com/help/doc-detail/51374.htm["Alibaba Cloud: 스토리지 클래스 소개"^]





목록에 없는 스토리지 클래스에 대한 자세한 내용은 NetApp 세일즈 담당자에게 문의하십시오.

.단계
. '-provider-type ' AliCloud' 매개 변수를 사용하여 'storage aggregate object-store config create' 명령을 사용하여 Alibaba Cloud Object Storage 구성 정보를 지정합니다.
+
** ONTAP가 제공된 정보로 Alibaba 클라우드 개체 스토리지에 액세스할 수 없으면 'Storage aggregate object-store config create' 명령이 실패합니다.
** '-access-key' 매개 변수를 사용하여 Alibaba Cloud Object Storage 개체 저장소에 대한 요청 권한 부여에 대한 액세스 키를 지정합니다.
** Alibaba 클라우드 개체 스토리지 암호가 변경되면 ONTAP에 저장된 해당 암호를 즉시 업데이트해야 합니다.
+
이렇게 하면 ONTAP가 Alibaba 클라우드 개체 스토리지의 데이터에 중단 없이 액세스할 수 있습니다.



+
[listing]
----
storage aggregate object-store config create my_ali_oss_store_1
-provider-type AliCloud -server oss-us-east-1.aliyuncs.com
-container-name my-ali-oss-bucket -access-key DXJRXHPXHYXA9X31X3JX
----
. 'Storage aggregate object-store config show' 명령을 사용하여 Alibaba Cloud Object Storage 구성 정보를 표시하고 확인합니다.
+
'Storage aggregate object-store config modify' 명령을 사용하면 FabricPool에 대한 Alibaba 클라우드 개체 스토리지 구성 정보를 수정할 수 있습니다.


