---
permalink: fabricpool/setup-storagegrid-cloud-tier-task.html 
sidebar: sidebar 
keywords: setting up, storagegrid, cloud tier 
summary: ONTAP 9.2 이상을 실행 중인 경우 FabricPool를 StorageGRID의 클라우드 계층으로 설정할 수 있습니다. 
---
= StorageGRID를 클라우드 계층으로 설정합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9.2 이상을 실행 중인 경우 FabricPool를 StorageGRID의 클라우드 계층으로 설정할 수 있습니다. SAN 프로토콜에서 액세스하는 데이터를 계층화할 경우 연결 고려사항으로 인해 StorageGRID와 같은 프라이빗 클라우드를 사용하는 것이 좋습니다.

.FabricPool와 함께 StorageGRID를 사용하기 위한 고려 사항
* 인증서 확인을 명시적으로 해제하지 않는 한 StorageGRID용 CA 인증서를 설치해야 합니다.
* 오브젝트 저장소 버킷에서 StorageGRID 오브젝트 버전 관리를 사용하도록 설정하면 안 됩니다.
* FabricPool 라이센스는 필요하지 않습니다.
* StorageGRID 노드가 NetApp AFF 시스템에서 할당된 스토리지가 있는 가상 머신에 구축된 경우 해당 볼륨에 FabricPool 계층화 정책이 활성화되어 있지 않은지 확인하십시오.
+
StorageGRID 노드와 함께 사용되는 볼륨에 대해 FabricPool 계층화를 사용하지 않도록 설정하면 문제 해결과 스토리지 작업이 간소화됩니다.

+
[NOTE]
====
FabricPool를 사용하여 StorageGRID 관련 데이터를 StorageGRID 자체로 계층화하지 마십시오. StorageGRID 데이터를 StorageGRID로 다시 계층화하면 문제 해결과 운영 복잡성이 늘어납니다.

====


.이 작업에 대해
StorageGRID 9.8 이상에서는 ONTAP에 대해 로드 밸런싱이 활성화됩니다. 서버의 호스트 이름이 둘 이상의 IP 주소로 확인되는 경우 ONTAP는 반환된 모든 IP 주소(최대 16개의 IP 주소)를 사용하여 클라이언트 연결을 설정합니다. 연결이 설정되면 IP 주소가 라운드 로빈 방식으로 선택됩니다.

.절차를 참조하십시오
ONTAP System Manager 또는 ONTAP CLI를 사용하여 StorageGRID를 FabricPool의 클라우드 계층으로 설정할 수 있습니다.

[role="tabbed-block"]
====
.시스템 관리자
--
. 스토리지 > 계층 > 클라우드 계층 추가 * 를 클릭하고 오브젝트 저장소 공급자로 StorageGRID를 선택합니다.
. 요청된 정보를 완료합니다.
. 클라우드 미러를 생성하려면 * FabricPool 미러로 추가 * 를 클릭합니다.


FabricPool 미러는 데이터 저장소를 원활하게 대체할 수 있는 방법을 제공하므로 재해 발생 시 데이터를 사용할 수 있습니다.

--
.CLI를 참조하십시오
--
. '-provider-type ''sgws' 파라미터를 이용하여 'storage aggregate object-store config create' 명령어를 이용하여 StorageGRID 설정 정보를 지정한다.
+
** StorageGRID가 제공된 정보로 ONTAP에 액세스할 수 없는 경우 'Storage aggregate object-store config create' 명령이 실패합니다.
** '-access-key' 매개 변수를 사용하여 StorageGRID 개체 저장소에 대한 요청을 승인하는 액세스 키를 지정할 수 있습니다.
** '-secret-password' 매개 변수를 사용하여 StorageGRID 개체 저장소에 대한 요청을 인증하는 암호(암호 액세스 키)를 지정합니다.
** StorageGRID 암호가 변경된 경우 ONTAP에 저장된 해당 암호를 즉시 업데이트해야 합니다.
+
이렇게 하면 ONTAP에서 StorageGRID의 데이터에 중단 없이 액세스할 수 있습니다.

** 매개 변수를 로 `false` 설정하면 `-is-certificate-validation-enabled` StorageGRID에 대한 인증서 검사가 비활성화됩니다. (`-is-certificate-validation-enabled true`타사 인증 기관에서 서명한 인증서를 사용하는 것이 좋습니다.


+
[listing]
----
cluster1::> storage aggregate object-store config create
-object-store-name mySGWS -provider-type SGWS -server mySGWSserver
-container-name mySGWScontainer -access-key mySGWSkey
-secret-password mySGWSpass
----
. 'Storage aggregate object-store config show' 명령을 사용하여 StorageGRID 구성 정보를 표시하고 확인합니다.
+
'Storage aggregate object-store config modify' 명령을 사용하면 FabricPool에 대한 StorageGRID 구성 정보를 수정할 수 있습니다.



--
====