---
permalink: fabricpool/setup-azure-blob-storage-cloud-tier-task.html 
sidebar: sidebar 
keywords: setting up, azure blob storage, cloud, cloud tier 
summary: ONTAP 9.4 이상을 실행 중인 경우 클라우드용 Azure Blob 스토리지를 FabricPool용 클라우드 계층으로 설정할 수 있습니다. 
---
= 클라우드용 Azure Blob Storage를 클라우드 계층으로 설정
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9.4 이상을 실행 중인 경우 클라우드용 Azure Blob 스토리지를 FabricPool용 클라우드 계층으로 설정할 수 있습니다.

.FabricPool와 함께 Microsoft Azure Blob Storage를 사용할 때의 고려 사항
* FabricPool 라이센스가 필요할 수 있습니다.
+
새로 주문한 AFF 시스템에는 FabricPool를 사용할 수 있는 10TB의 여유 용량이 제공됩니다. AFF 시스템에서 추가 용량이 필요하거나, 비 AFF 시스템에서 Azure Blob Storage를 사용하거나, 기존 클러스터에서 업그레이드하는 경우 FabricPool 라이센스가 필요합니다.

+
기존 클러스터에 대해 FabricPool를 처음으로 주문하는 경우 가용 용량이 10TB인 FabricPool 라이센스를 사용할 수 있습니다.

* Cloud Volumes ONTAP와 함께 Azure Blob Storage를 사용하는 경우 FabricPool 라이센스가 필요하지 않습니다.
* ONTAP가 Azure Blob 스토리지 오브젝트 서버에 연결하는 데 사용하는 LIF는 10Gbps 포트에 있어야 합니다.
* FabricPool은 현재 온프레미스 Azure 서비스인 Azure 스택을 지원하지 않습니다.
* Microsoft Azure Blob Storage의 계정 수준에서 FabricPool는 핫 및 쿨 스토리지 계층만 지원합니다.
+
FabricPool는 BLOB 레벨 계층화를 지원하지 않습니다. 또한 Azure의 아카이브 스토리지 계층화도 지원하지 않습니다.



.이 작업에 대해
FabricPool은 현재 온프레미스 Azure 서비스인 Azure 스택을 지원하지 않습니다.

.단계
. '-provider-type ''Azure_Cloud' 매개 변수를 사용하여 'storage aggregate object-store config create' 명령을 사용하여 Azure Blob Storage 구성 정보를 지정합니다.
+
** ONTAP가 제공된 정보로 Azure Blob Storage에 액세스할 수 없으면 'STOATE OGATE OBJECT-STORE config create' 명령이 실패합니다.
** '-Azure-account' 매개 변수를 사용하여 Azure Blob 저장소 계정을 지정합니다.
** '-Azure-private-key' 매개 변수를 사용하여 Azure Blob 저장소에 대한 요청을 인증하는 액세스 키를 지정할 수 있습니다.
** Azure Blob 저장소 암호가 변경된 경우 ONTAP에 저장된 해당 암호를 즉시 업데이트해야 합니다.
+
이렇게 하면 ONTAP가 Azure Blob 스토리지의 데이터에 중단 없이 액세스할 수 있습니다.



+
[listing]
----
cluster1::> storage aggregate object-store config create
-object-store-name MyAzure -provider-type Azure_Cloud
-server blob.core.windows.net -container-name myAzureContainer
-azure-account myAzureAcct -azure-private-key myAzureKey
----
. 'Storage aggregate object-store config show' 명령을 사용하여 Azure Blob Storage 구성 정보를 표시하고 확인합니다.
+
'Storage aggregate object-store config modify' 명령을 사용하면 FabricPool의 Azure Blob 저장소 구성 정보를 수정할 수 있습니다.


