---
permalink: fabricpool/setup-aws-s3-cloud-tier-task.html 
sidebar: sidebar 
keywords: setting up, aws, s3, cloud tier 
summary: 'ONTAP 9.2 이상을 실행 중인 경우 Amazon S3를 FabricPool의 클라우드 계층으로 설정할 수 있습니다. ONTAP 9.5 이상을 실행 중인 경우 FabricPool용 C2S(Amazon Commercial Cloud Services)를 설정할 수 있습니다.' 
---
= Amazon S3를 클라우드 계층으로 설정합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9.2 이상을 실행 중인 경우 Amazon S3를 FabricPool의 클라우드 계층으로 설정할 수 있습니다. ONTAP 9.5 이상을 실행 중인 경우 FabricPool용 C2S(Amazon Commercial Cloud Services)를 설정할 수 있습니다.

.FabricPool에서 Amazon S3를 사용하기 위한 고려 사항
* FabricPool 라이센스가 필요할 수 있습니다.
+
** 새로 주문한 AFF 시스템에는 FabricPool를 사용할 수 있는 10TB의 여유 용량이 제공됩니다.
+
AFF 시스템에서 추가 용량이 필요하거나, 비 AFF 시스템에서 Amazon S3를 사용하거나, 기존 클러스터에서 업그레이드하는 경우 FabricPool 라이센스가 필요합니다.

+
기존 클러스터에 대해 FabricPool를 처음으로 주문하는 경우 가용 용량이 10TB인 FabricPool 라이센스를 사용할 수 있습니다.



* ONTAP에서 Amazon S3 오브젝트 서버에 연결하는 데 사용하는 LIF는 10Gbps 포트에 연결하는 것이 좋습니다.
* AFF 및 FAS 시스템과 ONTAP Select에서 FabricPool은 다음과 같은 Amazon S3 스토리지 클래스를 지원합니다.
+
** Amazon S3 Standard
** Amazon S3 Standard - 낮은 액세스 빈도(Standard-IA)
** Amazon S3 ONE Zone - 낮은 액세스 빈도(Zone-IA 1개)
** Amazon S3 지능형 계층화
** Amazon 상용 클라우드 서비스
** ONTAP 9.11.1부터 Amazon S3 Glacier 인스턴트 검색(FabricPool는 Glacier Flexible Retrieval 또는 Glacier Deep Archive를 지원하지 않음)
+
https://aws.amazon.com/s3/storage-classes/["Amazon Web Services 문서: Amazon S3 스토리지 클래스"]



+
목록에 없는 스토리지 클래스에 대한 자세한 내용은 영업 담당자에게 문의하십시오.

* Cloud Volumes ONTAP에서 FabricPool는 EBS(Elastic Block Store)의 GP2(General Purpose SSD) 및 st1(Throughput Optimized HDD) 볼륨의 계층화를 지원합니다.


.단계
. 를 사용하여 Amazon S3 구성 정보를 지정합니다 `storage aggregate object-store config create` 명령과 함께 `-provider-type` `AWS_S3` 매개 변수.
+
** C2S 액세스에 대한 자격 증명을 얻으려면 '-auth-type ''cap' 매개 변수를 사용합니다.
+
auth-type의 cap 매개 변수를 사용할 때는 '-cap-url' 매개 변수를 사용하여 C2S 액세스에 대한 임시 자격 증명을 요청하기 위한 전체 URL을 지정해야 합니다.

** 를 클릭합니다 `storage aggregate object-store config create` ONTAP가 제공된 정보로 Amazon S3에 액세스할 수 없는 경우 명령이 실패합니다.
** 를 사용합니다 `-access-key` Amazon S3 오브젝트 저장소 요청 승인을 위한 액세스 키를 지정하는 매개 변수입니다.
** 를 사용합니다 `-secret-password` Amazon S3 오브젝트 저장소 요청을 인증하는 데 사용되는 암호(암호 액세스 키)를 지정하는 매개 변수입니다.
** Amazon S3 암호가 변경된 경우 ONTAP에 저장된 해당 암호를 즉시 업데이트해야 합니다.
+
이렇게 하면 ONTAP에서 Amazon S3의 데이터에 중단 없이 액세스할 수 있습니다.

+
[listing]
----
cluster1::> storage aggregate object-store config create
-object-store-name my_aws_store -provider-type AWS_S3
-server s3.amazonaws.com -container-name my-aws-bucket
-access-key DXJRXHPXHYXA9X31X3JX
----
+
[listing]
----
cluster1::> storage aggregate object-store config create -object-store-name my_c2s_store -provider-type AWS_S3 -auth-type CAP -cap-url https://123.45.67.89/api/v1/credentials?agency=XYZ&mission=TESTACCT&role=S3FULLACCESS -server my-c2s-s3server-fqdn -container my-c2s-s3-bucket
----


. 를 사용하여 Amazon S3 구성 정보를 표시하고 확인합니다 `storage aggregate object-store config show` 명령.
+
를 클릭합니다 `storage aggregate object-store config modify` 명령을 사용하면 FabricPool의 Amazon S3 구성 정보를 수정할 수 있습니다.


