---
permalink: fabricpool/setup-azure-blob-storage-cloud-tier-task.html 
sidebar: sidebar 
keywords: setting up, azure blob storage, cloud, cloud tier 
summary: ONTAP 9.4 이상을 실행 중인 경우 클라우드용 Azure Blob 스토리지를 FabricPool용 클라우드 계층으로 설정할 수 있습니다. 
---
= 클라우드용 Azure Blob Storage를 클라우드 계층으로 설정
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9.4 이상을 실행 중인 경우 클라우드용 Azure Blob 스토리지를 FabricPool용 클라우드 계층으로 설정할 수 있습니다.

FabricPool은 현재 온프레미스 Azure 서비스인 Azure 스택을 지원하지 않습니다.

.단계
. '-provider-type ''Azure_Cloud' 매개 변수를 사용하여 'storage aggregate object-store config create' 명령을 사용하여 Azure Blob Storage 구성 정보를 지정합니다.
+
** ONTAP가 제공된 정보로 Azure Blob Storage에 액세스할 수 없으면 'STOATE OGATE OBJECT-STORE config create' 명령이 실패합니다.
** '-Azure-account' 매개 변수를 사용하여 Azure Blob 저장소 계정을 지정합니다.
** '-Azure-private-key' 매개 변수를 사용하여 Azure Blob 저장소에 대한 요청을 인증하는 액세스 키를 지정할 수 있습니다.
** Azure Blob 저장소 암호가 변경된 경우 ONTAP에 저장된 해당 암호를 즉시 업데이트해야 합니다.
+
이렇게 하면 ONTAP가 Azure Blob 스토리지의 데이터에 중단 없이 액세스할 수 있습니다.



+
[listing]
----
cluster1::> storage aggregate object-store config create
-object-store-name MyAzure -provider-type Azure_Cloud
-server blob.core.windows.net -container-name myAzureContainer
-azure-account myAzureAcct -azure-private-key myAzureKey
----
. 'Storage aggregate object-store config show' 명령을 사용하여 Azure Blob Storage 구성 정보를 표시하고 확인합니다.
+
'Storage aggregate object-store config modify' 명령을 사용하면 FabricPool의 Azure Blob 저장소 구성 정보를 수정할 수 있습니다.


