---
permalink: nfs-config/additional-information-reference.html 
sidebar: sidebar 
keywords: additional, information, nfs, configuration, networking, san protocol, root volume, protection 
summary: 'NFS 클라이언트 액세스를 성공적으로 테스트한 후 추가 NFS 구성을 수행하거나 SAN 액세스를 추가할 수 있습니다. 프로토콜 액세스가 완료되면 SVM(스토리지 가상 머신)의 루트 볼륨을 보호해야 합니다.' 
---
= 추가 정보를 찾을 수 있는 위치
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NFS 클라이언트 액세스를 성공적으로 테스트한 후 추가 NFS 구성을 수행하거나 SAN 액세스를 추가할 수 있습니다. 프로토콜 액세스가 완료되면 SVM(스토리지 가상 머신)의 루트 볼륨을 보호해야 합니다.



== NFS 구성

다음 정보 및 기술 보고서를 사용하여 NFS 액세스를 추가로 구성할 수 있습니다.

* link:../nfs-admin/index.html["NFS 관리"]
+
NFS를 사용하여 파일 액세스를 구성 및 관리하는 방법에 대한 설명은 에 나와 있습니다.

* http://["NetApp 기술 보고서 4067: NFS 모범 사례 및 구축 가이드"^]
+
NFSv3 및 NFSv4 운영 가이드 역할을 하며 NFSv4를 중심으로 ONTAP 운영 체제에 대한 개요를 제공합니다.

* http://["NetApp 기술 보고서 4073: 안전한 통합 인증"]
+
NFS 스토리지 인증을 위한 UNIX 기반 Kerberos 버전 5(krb5) 서버 및 Windows Server Active Directory(AD)를 KDC 및 LDAP(Lightweight Directory Access Protocol) ID 공급자로 사용하도록 ONTAP를 구성하는 방법은 에 나와 있습니다.

* http://["NetApp 기술 보고서 3580: NFSv4 향상 및 모범 사례 가이드 Data ONTAP 구축"]
+
에서는 ONTAP를 실행하는 시스템에 접속된 AIX, Linux 또는 Solaris 클라이언트에서 NFSv4 구성 요소를 구축하는 동안 따라야 하는 Best Practice를 설명합니다.





== 네트워킹 구성

다음 정보 및 기술 보고서를 사용하여 네트워킹 기능 및 이름 서비스를 추가로 구성할 수 있습니다.

* link:../nfs-admin/index.html["NFS 관리"]
+
에서는 ONTAP 네트워킹을 구성하고 관리하는 방법에 대해 설명합니다.

* http://["NetApp 기술 보고서 4182: 이더넷 스토리지 설계 고려사항 및 clustered Data ONTAP 구성에 대한 모범 사례"]
+
ONTAP 네트워크 구성의 구현을 설명하고 일반적인 네트워크 배포 시나리오 및 모범 사례 권장 사항을 제공합니다.

* https://["NetApp 기술 보고서 4668: 이름 서비스 모범 사례 가이드"^]
+
인증을 위해 LDAP, NIS, DNS 및 로컬 파일 구성을 구성하는 방법은 에 나와 있습니다.





== SAN 프로토콜 구성

새 SVM에 대한 SAN 액세스를 제공하거나 수정하려는 경우 여러 호스트 운영 체제에서 사용할 수 있는 FC 또는 iSCSI 구성 정보를 사용할 수 있습니다.



== 루트 볼륨 보호

SVM에서 프로토콜을 구성한 후에는 루트 볼륨이 보호되는지 확인해야 합니다.

* link:../data-protection/index.html["데이터 보호"]
+
NAS 지원 SVM에 대한 NetApp의 모범 사례인 SVM 루트 볼륨을 보호하기 위해 로드 공유 미러를 생성하는 방법에 대해 설명합니다. 또한, 로드 공유 미러에서 SVM 루트 볼륨을 프로모션하여 볼륨 장애 또는 손실로부터 빠르게 복구하는 방법을 설명합니다.


