---
permalink: nfs-config/configure-name-service-switch-table-task.html 
sidebar: sidebar 
keywords: configue, name, service, switch, table 
summary: ONTAP가 로컬 또는 외부 이름 서비스에 문의하여 호스트, 사용자, 그룹, 넷그룹 또는 이름 매핑 정보를 검색할 수 있도록 이름 서비스 스위치 테이블을 올바르게 구성해야 합니다. 
---
= 이름 서비스 스위치 테이블을 구성합니다
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP가 로컬 또는 외부 이름 서비스에 문의하여 호스트, 사용자, 그룹, 넷그룹 또는 이름 매핑 정보를 검색할 수 있도록 이름 서비스 스위치 테이블을 올바르게 구성해야 합니다.

사용자 환경에 적용할 수 있는 호스트, 사용자, 그룹, 넷그룹 또는 이름 매핑에 사용할 이름 서비스를 결정해야 합니다.

넷그룹을 사용할 계획이라면 RFC 5952에 지정된 대로 넷그룹에 지정된 모든 IPv6 주소를 단축하고 압축해야 합니다.

사용하지 않는 정보 소스는 포함하지 마십시오. 예를 들어 NIS가 사용자 환경에서 사용되지 않는 경우 '-Sources NIS' 옵션을 지정하지 마십시오.

.단계
. 이름 서비스 스위치 테이블에 필요한 항목을 추가합니다.
+
'vserver services name-service ns-switch create-vserver_vserver_name_-database_database_name_-sources_source_names_'

. 이름 서비스 스위치 테이블에 원하는 순서대로 필요한 항목이 포함되어 있는지 확인합니다.
+
'vserver services name-service ns-switch show -vserver_vserver_name_'

+
수정하려면 'vserver services name-service ns-switch modify' 또는 'vserver services name-service ns-switch delete' 명령을 사용해야 합니다.



다음 예에서는 SVM VS1 에서 로컬 넷그룹 파일을 사용할 수 있도록 이름 서비스 스위치 테이블에 새 항목을 생성하고 외부 NIS 서버에서 넷그룹 정보를 순서대로 찾습니다.

[listing]
----
cluster::> vserver services name-service ns-switch create -vserver vs1 -database netgroup -sources files,nis
----
.작업을 마친 후
* 데이터 액세스를 제공하려면 SVM에 지정한 이름 서비스를 구성해야 합니다.
* SVM에 대한 네임 서비스를 삭제할 경우 네임 서비스 스위치 테이블에서 해당 서비스를 제거해야 합니다.
+
이름 서비스 스위치 테이블에서 이름 서비스를 삭제하지 않으면 스토리지 시스템에 대한 클라이언트 액세스가 예상대로 작동하지 않을 수 있습니다.


