---
permalink: nfs-config/create-server-task.html 
sidebar: sidebar 
keywords: create, nfs, server 
summary: 클러스터에서 NFS 라이센스가 등록되었는지 확인한 후 vserver NFS create 명령을 사용하여 SVM에 NFS 서버를 생성하고 이 서버에서 지원하는 NFS 버전을 지정할 수 있습니다. 
---
= NFS 서버를 생성합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
클러스터에서 NFS 라이센스가 등록되었는지 확인한 후 "vserver NFS create" 명령을 사용하여 SVM에 NFS 서버를 생성하고 해당 명령이 지원하는 NFS 버전을 지정할 수 있습니다.

.필요한 것
SVM은 NFS 프로토콜을 허용하도록 구성해야 합니다.

.이 작업에 대해
SVM은 하나 이상의 NFS 버전을 지원하도록 구성할 수 있습니다. NFSv4 이상을 지원하는 경우:

* NFSv4 사용자 ID 매핑 도메인 이름은 NFSv4 서버 및 타겟 클라이언트에서 동일해야 합니다.
+
NFSv4 서버와 클라이언트가 동일한 이름을 사용하는 한 LDAP 또는 NIS 도메인 이름과 같을 필요는 없습니다.

* 타겟 클라이언트는 NFSv4 숫자 ID 설정을 지원해야 합니다.
* 보안을 위해 NFSv4 구축에서는 이름 서비스에 LDAP를 사용해야 합니다.


.단계
. NFS 라이센스가 클러스터에서 라이센스되었는지 확인합니다.
+
'system license show-package nfs'

+
그렇지 않은 경우 영업 담당자에게 문의하십시오.

. NFS 서버 생성:
+
'vserver NFS create -vserver_vserver_name_-v3{enabled | disabled} -v4.0{enabled | disabled} -v4-id-domain_NFSv4_id_domain_-v4-numeric-ids{enabled | disabled} -v4.1{enabled | disabled | pNFS{enabled | disabled}'를 선택합니다

+
NFS 버전의 조합을 사용하도록 선택할 수 있습니다. pNFS를 지원하려면 '-v4.1'과 '-v4.1-pNFS' 옵션을 모두 사용해야 합니다.

+
v4 이상을 사용하는 경우 다음 옵션도 올바르게 설정되어 있어야 합니다.

+
** '-v4-id-domain'
+
이 선택적 매개 변수는 NFSv4 프로토콜에서 정의된 사용자 및 그룹 이름의 문자열 형식 도메인 부분을 지정합니다. 기본적으로 ONTAP는 NIS 도메인이 설정되어 있는 경우 NIS 도메인을 사용하고, 설정되어 있지 않으면 DNS 도메인이 사용됩니다. 대상 클라이언트가 사용하는 도메인 이름과 일치하는 값을 입력해야 합니다.

** '-v4-numeric-ids'
+
이 선택적 매개 변수는 NFSv4 소유자 속성에서 숫자 문자열 식별자를 지원하도록 설정되었는지 여부를 지정합니다. 기본 설정은 활성화되지만 타겟 클라이언트가 이 설정을 지원하는지 확인해야 합니다.



+
나중에 'vserver nfs modify' 명령을 사용하여 추가 NFS 기능을 활성화할 수 있습니다.

. NFS가 실행 중인지 확인합니다.
+
'vserver NFS status-vserver_vserver_name_'

. NFS가 원하는 대로 구성되었는지 확인합니다.
+
'vserver nfs show -vserver_vserver_name_'



.예
다음 명령을 실행하면 NFSv3 및 NFSv4.0이 설정된 VS1 이라는 SVM에 NFS 서버가 생성됩니다.

[listing]
----
vs1::> vserver nfs create -vserver vs1 -v3 enabled -v4.0 enabled -v4-id-domain my_domain.com
----
다음 명령을 실행하면 이름이 VS1 인 새 NFS 서버의 상태와 구성 값이 검증됩니다.

[listing]
----
vs1::> vserver nfs status -vserver vs1
The NFS server is running on Vserver "vs1".

vs1::> vserver nfs show -vserver vs1

                            Vserver: vs1
                 General NFS Access: true
                             NFS v3: enabled
                           NFS v4.0: enabled
                       UDP Protocol: enabled
                       TCP Protocol: enabled
               Default Windows User: -
                NFSv4.0 ACL Support: disabled
    NFSv4.0 Read Delegation Support: disabled
   NFSv4.0 Write Delegation Support: disabled
            NFSv4 ID Mapping Domain: my_domain.com
...
----