---
permalink: nfs-config/create-volume-task.html 
sidebar: sidebar 
keywords: create, volume 
summary: 볼륨 생성 명령을 사용하여 볼륨을 생성하고 해당 접합 지점 및 기타 속성을 지정할 수 있습니다. 
---
= 볼륨을 생성합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
볼륨을 생성하고 "volume create" 명령을 사용하여 해당 접합 지점 및 기타 속성을 지정할 수 있습니다.

.필요한 것
SVM 보안 스타일은 UNIX여야 하며 NFS를 설정하고 실행해야 합니다.

.이 작업에 대해
클라이언트에서 데이터를 사용할 수 있도록 하려면 볼륨에 _junction path_가 포함되어야 합니다. 새 볼륨을 생성할 때 접합 경로를 지정할 수 있습니다. 접합 경로를 지정하지 않고 볼륨을 생성하는 경우, "volume mount" 명령을 사용하여 SVM 네임스페이스에서 볼륨을 _mount_해야 합니다.

.단계
. 교차점으로 볼륨을 생성합니다.
+
''볼륨 작성 - vserver_vserver_name_-volume_volume_name_-aggregate_aggregate_name_-size {_integer_[KB|MB|GB|TB|PB]} - security-style unix-user_name_or_number_-group_name_or_number_-junction-path_export_policy_name'

+
'-junction-path'의 선택 항목은 다음과 같습니다.

+
** 루트 바로 아래, 예: '/_new_vol_'
+
새 볼륨을 생성하고 SVM 루트 볼륨에 직접 마운트하도록 지정할 수 있습니다.

** 기존 디렉토리 아래에, 예: "/_existing_dir/new_vol_"
+
새 볼륨을 생성하고 기존 계층 구조에서 기존 볼륨에 마운트하도록 지정할 수 있습니다. 이 볼륨은 디렉토리로 표시됩니다.



+
새 볼륨 아래의 새 계층 구조에서 "_/new_dir/new_vol_"와 같은 새 디렉토리에 볼륨을 생성하려면 먼저 SVM 루트 볼륨에 대한 분기인 새 상위 볼륨을 생성해야 합니다. 그런 다음 새 상위 볼륨(새 디렉토리)의 접합 경로에 새 하위 볼륨을 생성합니다.

+
+ 기존 엑스포트 정책을 사용하려는 경우 볼륨을 생성할 때 지정할 수 있습니다. 나중에 볼륨 수정 명령을 사용하여 내보내기 정책을 추가할 수도 있습니다.

. 볼륨이 원하는 접합 지점으로 생성되었는지 확인합니다.
+
'volume show -vserver_vserver_name_-volume_volume_name_-junction'



.예
다음 명령을 실행하면 SVM vs1.example.com 및 애그리게이트 aggr1에 user1이라는 새 볼륨이 생성됩니다. 새 볼륨은 '/users'에서 사용할 수 있습니다. 볼륨의 크기는 750GB이고 볼륨 유형은 볼륨 유형입니다(기본값).

[listing]
----
cluster1::> volume create -vserver vs1.example.com -volume users -aggregate aggr1 -size 750g -junction-path /users
[Job 1642] Job succeeded: Successful

cluster1::> volume show -vserver vs1.example.com -volume users -junction
                          Junction                 Junction
Vserver           Volume  Active   Junction Path   Path Source
----------------- ------- -------- --------------- -----------
vs1.example.com   users1  true     /users          RW_volume
----
다음 명령을 실행하면 SVM "vs1.example.com" 및 애그리게이트 "aggr1"에 "home4"라는 새 볼륨이 생성됩니다. VS1 SVM은 이름 공간에 /ENG/ 디렉토리가 이미 있으며, '/ENG/' 네임스페이스의 홈 디렉토리가 되는 '/ENG/HOME'에서 새 볼륨을 사용할 수 있습니다. 볼륨 크기는 750GB이고 볼륨 보장은 볼륨 유형입니다(기본값).

[listing]
----
cluster1::> volume create -vserver vs1.example.com -volume home4 -aggregate aggr1 -size 750g -junction-path /eng/home
[Job 1642] Job succeeded: Successful

cluster1::> volume show -vserver vs1.example.com -volume home4 -junction
                         Junction                 Junction
Vserver          Volume  Active   Junction Path   Path Source
---------------- ------- -------- --------------- -----------
vs1.example.com  home4   true     /eng/home       RW_volume
----