---
permalink: nfs-config/create-new-ldap-client-schema-task.html 
sidebar: sidebar 
keywords: create, new, ldap, client, schema 
summary: 사용자 환경의 LDAP 스키마가 ONTAP 기본값과 다른 경우 LDAP 클라이언트 구성을 생성하기 전에 ONTAP에 대한 새 LDAP 클라이언트 스키마를 만들어야 합니다. 
---
= 새 LDAP 클라이언트 스키마를 생성합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
사용자 환경의 LDAP 스키마가 ONTAP 기본값과 다른 경우 LDAP 클라이언트 구성을 생성하기 전에 ONTAP에 대한 새 LDAP 클라이언트 스키마를 만들어야 합니다.

.이 작업에 대해
대부분의 LDAP 서버는 ONTAP에서 제공하는 기본 스키마를 사용할 수 있습니다.

* MS-AD-BIS(대부분의 Windows 2012 이상 AD 서버에 대한 기본 스키마)
* AD-IDMU(Windows 2008, Windows 2012 이상 AD 서버)
* AD-SFU(Windows 2003 및 이전 AD 서버)
* RFC-2307(UNIX LDAP 서버)


기본값이 아닌 LDAP 스키마를 사용해야 하는 경우 LDAP 클라이언트 구성을 생성하기 전에 만들어야 합니다. 새 스키마를 만들기 전에 LDAP 관리자에게 문의하십시오.

ONTAP에서 제공하는 기본 LDAP 스키마는 수정할 수 없습니다. 새 스키마를 만들려면 복사본을 만든 다음 복사본을 적절하게 수정합니다.

.단계
. 기존 LDAP 클라이언트 스키마 템플릿을 표시하여 복사할 템플릿을 식별합니다.
+
'vserver services name-service ldap client schema show'를 참조하십시오

. 권한 수준을 고급으로 설정합니다.
+
세트 프리빌리지 고급

. 기존 LDAP 클라이언트 스키마의 복사본을 만듭니다.
+
'vserver services name-service LDAP 클라이언트 스키마 복사 - vserver_vserver_name_-schema_existing_schema_name_-new-schema-name_new_schema_name_'

. 새 스키마를 수정하고 사용자 환경에 맞게 사용자 지정합니다.
+
'vserver services name-service LDAP 클라이언트 스키마 수정

. 관리자 권한 레벨로 돌아갑니다.
+
'Set-Privilege admin'입니다


