---
permalink: nfs-config/index.html 
sidebar: sidebar 
keywords: NFS, configuration, overview 
summary: ONTAP 9 CLI 명령을 사용하여 새 스토리지 가상 머신 또는 기존 스토리지 가상 머신에서 새 볼륨 또는 qtree에 포함된 파일에 대한 NFS 클라이언트 액세스를 구성할 수 있습니다. 
---
= CLI를 사용한 NFS 구성 개요
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9 CLI 명령을 사용하여 새 SVM(스토리지 가상 머신) 또는 기존 SVM(스토리지 가상 머신)에서 새 볼륨 또는 qtree에 포함된 파일에 대한 NFS 클라이언트 액세스를 구성할 수 있습니다.

다음과 같은 방법으로 볼륨 또는 qtree에 대한 액세스를 구성하려면 다음 절차를 사용하십시오.

* 현재 ONTAP에서 지원하는 모든 버전의 NFS, NFSv3, NFSv4, NFSv4.1, NFSv4.2 또는 pNFS를 사용하는 NFSv4.1을 사용하려고 합니다.
* System Manager나 자동화된 스크립팅 도구가 아니라 CLI(Command-Line Interface)를 사용하려는 경우
+
System Manager를 사용하여 NAS 멀티 프로토콜 액세스를 구성하려면 를 참조하십시오link:../task_nas_provision_nfs_and_smb.html["NFS와 SMB를 모두 사용하여 Windows 및 Linux 모두에 대해 NAS 스토리지를 프로비저닝합니다"].

* 사용 가능한 모든 옵션을 탐색하는 것이 아니라 모범 사례를 사용하려고 합니다.
+
명령 구문에 대한 자세한 내용은 CLI 도움말 및 ONTAP man 페이지를 참조하십시오.

* 새 볼륨의 보안을 위해 UNIX 파일 권한이 사용됩니다.
* SVM 관리자 권한이 아닌 클러스터 관리자 권한이 있습니다.


ONTAP NFS 프로토콜 기능의 범위에 대한 자세한 내용은 를 참조하십시오 link:../nfs-admin/index.html["NFS 참조 개요"].



== ONTAP에서 이 작업을 수행하는 다른 방법

|===


| 에서 이러한 작업을 수행하려면... | 자세한 내용은... 


| 재설계된 System Manager(ONTAP 9.7 이상에서 사용 가능) | link:../task_nas_provision_linux_nfs.html["NFS를 사용하여 Linux 서버용 NAS 스토리지 용량 할당"] 


| System Manager Classic(ONTAP 9.7 이하에서 사용 가능 | link:https://docs.netapp.com/us-en/ontap-system-manager-classic/nfs-config/index.html["NFS 구성 개요"^] 
|===