---
permalink: nfs-config/load-netgroups-svms-task.html 
sidebar: sidebar 
keywords: load, netgroups, svms 
summary: '내보내기 정책 규칙에서 클라이언트를 일치시키는 데 사용할 수 있는 방법 중 하나는 netgroup에 나열된 호스트를 사용하는 것입니다. 외부 이름 서버에 저장된 넷그룹을 사용하는 대신 URI(Uniform Resource Identifier)에서 SVM으로 넷그룹을 로드할 수 있습니다(SVM 서비스 이름 - 서비스 넷그룹 로드).' 
---
= 넷그룹을 SVM에 로드
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
내보내기 정책 규칙에서 클라이언트를 일치시키는 데 사용할 수 있는 방법 중 하나는 netgroup에 나열된 호스트를 사용하는 것입니다. 외부 이름 서버에 저장된 넷그룹을 사용하는 대신 URI(Uniform Resource Identifier)에서 SVM으로 넷그룹을 로드할 수 있습니다('vserver services name-service netgroup load').

.필요한 것
넷그룹 파일은 SVM에 로드되기 전에 다음 요구 사항을 충족해야 합니다.

* 파일은 NIS를 채우는 데 사용되는 것과 동일한 적절한 넷그룹 텍스트 파일 형식을 사용해야 합니다.
+
ONTAP는 넷그룹 텍스트 파일 형식을 로드하기 전에 검사합니다. 파일에 오류가 있으면 로드되지 않고 파일에서 수행해야 하는 수정 사항을 나타내는 메시지가 표시됩니다. 오류를 해결한 후 Netgroup 파일을 지정된 SVM에 다시 로드할 수 있습니다.

* 넷그룹 파일의 호스트 이름에 있는 모든 영문자는 소문자여야 합니다.
* 지원되는 최대 파일 크기는 5MB입니다.
* 네스팅 넷그룹에 대해 지원되는 최대 수준은 1000입니다.
* 넷그룹 파일에 호스트 이름을 정의할 때는 운영 DNS 호스트 이름만 사용할 수 있습니다.
+
내보내기 액세스 문제를 방지하려면 DNS CNAME 또는 라운드 로빈 레코드를 사용하여 호스트 이름을 정의하면 안 됩니다.

* 넷그룹 파일에서 3중 그룹의 사용자 및 도메인 부분은 ONTAP에서 지원하지 않으므로 비워 두어야 합니다.
+
호스트/IP 부분만 지원됩니다.



.이 작업에 대해
ONTAP는 로컬 넷그룹 파일에 대한 호스트 별 검색을 지원합니다. 넷그룹 파일을 로드하면 ONTAP에서 자동으로 netgroup.byhost 맵을 생성하여 넷그룹 기준 호스트 검색을 설정합니다. 이렇게 하면 내보내기 정책 규칙을 처리하여 클라이언트 액세스를 평가할 때 로컬 넷그룹 검색 속도를 크게 높일 수 있습니다.

.단계
. URI를 통해 넷그룹을 SVM에 로드:
+
'vserver services name-service netgroup load-vserver_vserver_name_-source{ftp|http|FTPS|https}://_Uri_'

+
넷그룹 파일을 로드하고 넷그룹을 생성합니다. byhost 맵은 몇 분 정도 걸릴 수 있습니다.

+
넷그룹을 업데이트하려면 파일을 편집하고 업데이트된 넷그룹 파일을 SVM에 로드할 수 있습니다.



.예
다음 명령을 실행하면 HTTP URL '+http://intranet/downloads/corp-netgroup+`: 에서 이름이 VS1 인 SVM에 넷그룹 정의가 로드됩니다

[listing]
----
vs1::> vserver services name-service netgroup load -vserver vs1
-source http://intranet/downloads/corp-netgroup
----