---
permalink: nfs-config/load-local-unix-groups-uri-task.html 
sidebar: sidebar 
keywords: load, local, unix, groups, uri 
summary: '개별 로컬 UNIX 그룹을 수동으로 생성하는 대신 vserver services name-service unix-group load-from-Uri 명령을 사용하여 URI(Uniform Resource Identifier)에서 SVM으로 로컬 UNIX 그룹 목록을 로드할 수 있습니다.' 
---
= URI에서 로컬 UNIX 그룹을 로드합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
개별 로컬 UNIX 그룹을 수동으로 생성하는 대신 'vserver services name-service unix-group load-from-Uri' 명령을 사용하여 URI(Uniform Resource Identifier)에서 SVM으로 로컬 UNIX 그룹 목록을 로드할 수 있습니다.

.단계
. 로드할 로컬 UNIX 그룹 목록이 포함된 파일을 생성합니다.
+
파일은 UNIX '/etc/group' 형식의 그룹 정보를 포함해야 합니다.

+
'_group_name:password:group_ID:comma_separated_list_of_users_'

+
이 명령어는 '_PASSWORD_' 필드의 값을 삭제한다.

+
지원되는 최대 파일 크기는 1MB입니다.

+
그룹 파일에서 각 줄의 최대 길이는 32,768자입니다.

. 목록에 중복 정보가 없는지 확인합니다.
+
목록에 중복 항목이 없어야 합니다. 그렇지 않으면 목록을 로드하지 못합니다. SVM에 이미 있는 항목이 있으면 "-overwrite" 매개 변수를 "true"로 설정하여 모든 기존 항목을 새 파일로 덮어쓰거나 새 파일에 기존 항목을 복제하는 항목이 없는지 확인해야 합니다.

. 파일을 서버에 복사합니다.
+
스토리지 시스템에서 HTTP, HTTPS, FTP 또는 FTPS를 통해 서버에 연결할 수 있어야 합니다.

. 파일의 URI를 확인합니다.
+
URI는 파일이 있는 위치를 나타내기 위해 스토리지 시스템에 제공하는 주소입니다.

. 로컬 UNIX 그룹 목록이 포함된 파일을 URI에서 SVM으로 로드합니다.
+
'vserver services name-service unix-group load-from-Uri-vserver_vserver_name_-Uri{ftp|http|FTPS|https}://_Uri_-overwrite{true|false}'

+
'-overwrite'{'true'|'false'}는 엔트리를 덮어쓸지 여부를 지정합니다. 기본값은 false 입니다. 이 매개 변수를 "true"로 지정하면 ONTAP는 지정된 SVM의 기존 로컬 UNIX 그룹 데이터베이스 전체를 로드하는 파일의 항목으로 바꿉니다.



다음 명령을 실행하면 URI '+ftp://ftp.example.com/group+` 에서 VS1 이라는 SVM으로 로컬 UNIX 그룹 목록이 로드됩니다. SVM의 기존 그룹은 URI의 정보로 덮어써지지 않습니다.

[listing]
----
vs1::> vserver services name-service unix-group load-from-uri -vserver vs1
-uri ftp://ftp.example.com/group -overwrite false
----