---
permalink: nfs-config/test-access-client-systems-task.html 
sidebar: sidebar 
keywords: testing, nfs, access, client, systems 
summary: 새 스토리지 개체에 대한 NFS 액세스를 검증한 후 NFS 관리 호스트에 로그인하고 SVM에서 데이터를 읽고 쓰는 방법으로 구성을 테스트해야 합니다. 그런 다음 클라이언트 시스템에서 루트 이외의 사용자로 프로세스를 반복해야 합니다. 
---
= 클라이언트 시스템에서 NFS 액세스를 테스트합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
새 스토리지 개체에 대한 NFS 액세스를 검증한 후 NFS 관리 호스트에 로그인하고 SVM에서 데이터를 읽고 쓰는 방법으로 구성을 테스트해야 합니다. 그런 다음 클라이언트 시스템에서 루트 이외의 사용자로 프로세스를 반복해야 합니다.

.무엇을 &#8217;필요로 할거야
* 클라이언트 시스템에는 이전에 지정한 내보내기 규칙에서 허용하는 IP 주소가 있어야 합니다.
* 루트 사용자에 대한 로그인 정보가 있어야 합니다.


.단계
. 클러스터에서 새 볼륨을 호스팅하는 LIF의 IP 주소를 확인합니다.
+
'network interface show –vserver_svm_name_'

. 관리 호스트 클라이언트 시스템에 루트 사용자로 로그인합니다.
. 디렉토리를 마운트 폴더로 변경합니다.
+
"cd /mnt/"

. SVM의 IP 주소를 사용하여 새 폴더를 생성하고 마운트합니다.
+
.. 새 폴더: + mkdir /mnt/_folder_'를 만듭니다
.. 이 새 디렉토리에 새 볼륨을 마운트합니다. + mount -t nfs -o hard_IPAddress_:/_volume_name_/mnt/_folder_'
.. 디렉터리를 새 폴더 + 'cd_folder_'로 변경합니다
+
다음 명령을 실행하면 test1이라는 폴더가 생성됩니다. test1 마운트 폴더의 192.0.2.130 IP 주소에 vol1 볼륨을 마운트하고 새 test1 디렉토리로 변경합니다.

+
[listing]
----
host# mkdir /mnt/test1
host# mount -t nfs -o hard 192.0.2.130:/vol1 /mnt/test1
host# cd /mnt/test1
----


. 새 파일을 만들고 파일이 있는지 확인한 후 다음 파일에 텍스트를 씁니다.
+
.. 테스트 파일을 만듭니다. + "touch_filename_"
.. 파일이 있는지 확인합니다.: + "ls -l_filename_"
.. cat>_filename_'을 입력합니다
+
텍스트를 입력하고 Ctrl+D를 눌러 테스트 파일에 텍스트를 씁니다.

.. 테스트 파일의 내용을 표시합니다. "cat_filename_"
.. 테스트 파일: + "rm_filename_"을 제거합니다
.. 상위 디렉토리로 돌아가기: + "cd...
+
[listing]
----
host# touch myfile1
host# ls -l myfile1
-rw-r--r-- 1 root root 0 Sep 18 15:58 myfile1
host# cat >myfile1
This text inside the first file
host# cat myfile1
This text inside the first file
host# rm -r myfile1
host# cd ..
----


. 루트로 마운트된 볼륨에 대해 원하는 UNIX 소유권 및 권한을 설정합니다.
. 내보내기 규칙에서 식별된 UNIX 클라이언트 시스템에서 이제 새 볼륨에 액세스할 수 있는 권한이 있는 사용자 중 하나로 로그인하고 3-5단계의 절차를 반복하여 볼륨을 마운트하고 파일을 생성할 수 있는지 확인합니다.

