---
permalink: nfs-config/verify-permissions-kerberos-config-task.html 
sidebar: sidebar 
keywords: verify, permissions, kerberos, configuration 
summary: Kerberos를 사용하려면 SVM 루트 볼륨 및 로컬 사용자 및 그룹에 대해 특정 UNIX 사용 권한을 설정해야 합니다. 
---
= Kerberos 구성에 대한 권한을 확인합니다
:icons: font
:imagesdir: ../media/


[role="lead"]
Kerberos를 사용하려면 SVM 루트 볼륨 및 로컬 사용자 및 그룹에 대해 특정 UNIX 사용 권한을 설정해야 합니다.

.단계
. SVM 루트 볼륨에 대한 관련 권한을 표시합니다.
+
'volume show-volume_root_vol_name_-fields user, group, unix-permissions

+
SVM의 루트 볼륨에는 다음 구성이 있어야 합니다.

+
|===
| 이름... | 설정 중... 


 a| 
UID
 a| 
루트 또는 ID 0



 a| 
GID
 a| 
루트 또는 ID 0



 a| 
Unix 사용 권한
 a| 
755

|===
+
이 값이 표시되지 않으면 볼륨 수정 명령을 사용하여 값을 업데이트합니다.

. 로컬 UNIX 사용자를 표시합니다.
+
'vserver services name-service unix-user show -vserver_vserver_name_'

+
SVM에는 다음과 같은 UNIX 사용자가 구성되어 있어야 합니다.

+
|===
| 사용자 이름입니다 | 사용자 ID입니다 | 기본 그룹 ID입니다 | 설명 


 a| 
NFS 를 참조하십시오
 a| 
500입니다
 a| 
0
 a| 
GSS INIT 단계에 필요함.

NFS 클라이언트 사용자 SPN의 첫 번째 구성 요소가 사용자로 사용됩니다.

NFS 클라이언트 사용자의 SPN에 대한 Kerberos-UNIX 이름 매핑이 있는 경우 NFS 사용자는 필요하지 않습니다.



 a| 
루트
 a| 
0
 a| 
0
 a| 
마운팅에 필요합니다.

|===
+
이러한 값이 표시되지 않으면 'vserver services name-service unix-user modify' 명령을 사용하여 해당 값을 업데이트할 수 있습니다.

. 로컬 UNIX 그룹을 표시합니다.
+
'vserver services name-service unix-group show -vserver_vserver__name'

+
SVM에는 다음과 같은 UNIX 그룹이 구성되어 있어야 합니다.

+
|===
| 그룹 이름 | 그룹 ID입니다 


 a| 
데몬
 a| 
1



 a| 
루트
 a| 
0

|===
+
이러한 값이 표시되지 않으면 'vserver services name-service unix-group modify' 명령을 사용하여 해당 값을 업데이트할 수 있습니다.


