---
permalink: nfs-config/work-netgroups-task.html 
sidebar: sidebar 
keywords: work, netgroups 
summary: '사용자 인증 및 내보내기 정책 규칙의 클라이언트와 일치시키기 위해 넷그룹을 사용할 수 있습니다. 외부 이름 서버(LDAP 또는 NIS)에서 넷그룹에 대한 액세스를 제공하거나, 가상 서비스 이름 서비스 넷그룹 로드 명령을 사용하여 URI(Uniform Resource Identifier)에서 SVM으로 넷그룹을 로드할 수 있습니다.' 
---
= 넷그룹 작업 개요
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
사용자 인증 및 내보내기 정책 규칙의 클라이언트와 일치시키기 위해 넷그룹을 사용할 수 있습니다. 외부 이름 서버(LDAP 또는 NIS)에서 넷그룹에 대한 액세스를 제공하거나, 'vserver services name-service netgroup load' 명령을 사용하여 URI(Uniform Resource Identifier)에서 SVM으로 넷그룹을 로드할 수 있습니다.

넷그룹을 사용하기 전에 다음 조건이 충족되는지 확인해야 합니다.

* 소스(NIS, LDAP 또는 로컬 파일)에 관계없이 넷그룹의 모든 호스트는 순방향 및 역방향 DNS 조회를 일관되게 제공하기 위해 정방향(A) 및 역방향(PTR) DNS 레코드를 모두 포함해야 합니다.
+
또한 클라이언트의 IP 주소에 PTR 레코드가 여러 개 있는 경우 이러한 모든 호스트 이름은 넷그룹의 구성원이어야 하며 해당 레코드가 있어야 합니다.

* 소스(NIS, LDAP 또는 로컬 파일)에 관계없이 넷그룹에 있는 모든 호스트의 이름은 철자가 올바르고 올바른 대소문자를 사용해야 합니다. 넷그룹에서 사용되는 호스트 이름의 대/소문자 불일치로 인해 내보내기 검사 실패와 같은 예기치 않은 동작이 발생할 수 있습니다.
* 넷그룹에 지정된 모든 IPv6 주소는 RFC 5952에 지정된 대로 단축되고 압축되어야 합니다.
+
예를 들어 2011:hu9:0:0:0:0:3:1은 2011:hu9:3:1로 단축되어야 합니다.



넷그룹으로 작업하는 경우 다음 작업을 수행할 수 있습니다.

* 'vserver export-policy netgroup check-membership' 명령을 사용하여 클라이언트 IP가 특정 넷그룹의 구성원인지 여부를 확인할 수 있습니다.
* 'vserver services name-service getxxbyy netgrp' 명령을 사용하여 클라이언트가 넷그룹에 속하는지 확인할 수 있습니다.
+
조회를 수행하는 기본 서비스는 구성된 이름 서비스 스위치 순서에 따라 선택됩니다.


