---
permalink: system-admin/access-cluster-telnet-task.html 
sidebar: sidebar 
keywords: access, cluster, telnet, administrative, tasks, disbale, default 
summary: 클러스터에 텔넷 요청을 실행하여 관리 작업을 수행할 수 있습니다. 텔넷은 기본적으로 비활성화되어 있습니다. 
---
= 텔넷을 사용하여 클러스터에 액세스합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
클러스터에 텔넷 요청을 실행하여 관리 작업을 수행할 수 있습니다. 텔넷은 기본적으로 비활성화되어 있습니다.

.필요한 것
텔넷을 사용하여 클러스터에 액세스하려면 다음 조건이 충족되어야 합니다.

* 텔넷을 액세스 방법으로 사용하도록 구성된 클러스터 로컬 사용자 계정이 있어야 합니다.
+
'보안 로그인' 명령어의 '-application' 파라미터는 사용자 계정에 대한 접속 방식을 지정한다. 자세한 내용은 보안 로그인 man 페이지를 참조하십시오.



.이 작업에 대해
* 텔넷은 보안 프로토콜이 아닙니다.
+
SSH를 사용하여 클러스터에 액세스하는 것을 고려해야 합니다. SSH는 보안 원격 셸 및 대화형 네트워크 세션을 제공합니다.

* ONTAP는 노드당 최대 50개의 동시 텔넷 세션을 지원합니다.
+
클러스터 관리 LIF가 노드에 상주하는 경우 이 제한을 노드 관리 LIF와 공유합니다.

+
들어오는 연결의 비율이 초당 10보다 높을 경우 서비스가 60초 동안 일시적으로 비활성화됩니다.

* Windows 호스트에서 ONTAP CLI에 액세스하려는 경우 PuTTY와 같은 타사 유틸리티를 사용할 수 있습니다.
* RSH 명령에는 고급 권한이 필요합니다.


.단계
. 텔넷 보안 프로토콜이 활성화되어 있는지 확인합니다.
+
`security protocol show`

+
.. 텔넷 보안 프로토콜이 활성화된 경우 다음 단계를 계속합니다.
.. 텔넷 보안 프로토콜이 활성화되지 않은 경우 다음 명령을 사용하여 활성화하십시오.
+
`security protocol modify -application telnet -enabled true`



. 관리 LIF에 서비스가 있는지 `management-telnet-server` 확인합니다.
+
`network interface show -services management-telnet-server`

+
.. 서비스가 있는 경우 `management-telnet-server` 다음 단계를 계속 진행하십시오.
.. 서비스가 없는 경우 `management-telnet-server` 다음 명령을 사용하여 서비스를 추가합니다.
+
`network interface service-policy add-service -vserver cluster1 -policy default-management -service management-telnet-server`





.텔넷 요청의 예
다음 예에서는 텔넷 액세스를 사용하여 설정된 ""Joe""라는 사용자가 클러스터 관리 LIF가 10.72.137.28인 클러스터에 액세스하기 위한 텔넷 요청을 실행할 수 있는 방법을 보여줍니다.

[listing]
----
admin_host$ telnet 10.72.137.28
Data ONTAP
login: joe
Password:
cluster1::>
----