---
permalink: system-admin/access-system-console-node-task.html 
sidebar: sidebar 
keywords: access, system, console, node, serial, ssh, sp, boot 
summary: '부팅 메뉴 또는 부팅 환경 프롬프트에 노드가 있는 경우 시스템 콘솔(시리얼 콘솔이라고도 함)을 통해서만 액세스할 수 있습니다. 노드의 SP 또는 클러스터에 대한 SSH 연결에서 노드의 시스템 콘솔에 액세스할 수 있습니다.' 
---
= 노드의 시스템 콘솔에 액세스합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
부팅 메뉴 또는 부팅 환경 프롬프트에 노드가 있는 경우 시스템 콘솔(_serial console_이라고도 함)을 통해서만 액세스할 수 있습니다. 노드의 SP 또는 클러스터에 대한 SSH 연결로부터 노드의 시스템 콘솔에 액세스할 수 있습니다.

SP와 ONTAP는 모두 시스템 콘솔에 액세스할 수 있는 명령을 제공합니다. 그러나 SP에서는 자체 노드의 시스템 콘솔에만 액세스할 수 있습니다. 클러스터에서 클러스터에 있는 모든 노드의 시스템 콘솔에 액세스할 수 있습니다.

.단계
. 노드의 시스템 콘솔에 액세스합니다.
+
|===
| 에 있는 경우... | 이 명령을 입력하십시오... 


 a| 
노드의 SP CLI입니다
 a| 
시스템 콘솔



 a| 
ONTAP CLI를 참조하십시오
 a| 
'시스템 노드 실행 콘솔

|===
. 시스템 콘솔에 로그인하라는 메시지가 표시되면 로그인합니다.
. 시스템 콘솔을 종료하려면 Ctrl-D를 누릅니다


다음 예제는 'S node2' 프롬프트에서 'system console' 명령어를 입력한 결과를 보여준다. 시스템 콘솔에 부팅 환경 프롬프트에서 node2가 멈추는 것으로 표시됩니다. 노드를 ONTAP로 부팅하려면 콘솔에서 boot_ontap 명령을 입력합니다. 그런 다음 Ctrl+D를 눌러 콘솔을 종료하고 SP로 돌아갑니다.

[listing]
----
SP node2> system console
Type Ctrl-D to exit.

LOADER>
LOADER> boot_ontap
...
*******************************
*                             *
* Press Ctrl-C for Boot Menu. *
*                             *
*******************************
...
----
(시스템 콘솔을 종료하려면 Ctrl+D를 누릅니다.)

[listing]
----

Connection to 123.12.123.12 closed.
SP node2>
----
다음 예제는 ONTAP에서 System node run-console 명령을 입력하여 부팅 환경 프롬프트에 있는 node2의 시스템 콘솔에 액세스하는 결과를 보여 줍니다. 콘솔에서 boot_ontap 명령을 입력하여 node2를 ONTAP로 부팅합니다. 그런 다음 Ctrl-D를 눌러 콘솔을 종료하고 ONTAP로 돌아갑니다.

[listing]
----
cluster1::> system node run-console -node node2
Pressing Ctrl-D will end this session and any further sessions you might open on top of this session.
Type Ctrl-D to exit.

LOADER>
LOADER> boot_ontap
...
*******************************
*                             *
* Press Ctrl-C for Boot Menu. *
*                             *
*******************************
...
----
(시스템 콘솔을 종료하려면 Ctrl+D를 누릅니다.)

[listing]
----

Connection to 123.12.123.12 closed.
cluster1::>
----