---
permalink: system-admin/access-cluster-telnet-task.html 
sidebar: sidebar 
keywords: access, cluster, telnet, administrative, tasks, disbale, default 
summary: 클러스터에 텔넷 요청을 실행하여 관리 작업을 수행할 수 있습니다. 텔넷은 기본적으로 비활성화되어 있습니다. 
---
= 텔넷을 사용하여 클러스터에 액세스합니다
:icons: font
:imagesdir: ../media/


[role="lead"]
클러스터에 텔넷 요청을 실행하여 관리 작업을 수행할 수 있습니다. 텔넷은 기본적으로 비활성화되어 있습니다.

텔넷을 사용하여 클러스터에 액세스하려면 다음 조건이 충족되어야 합니다.

* 텔넷을 액세스 방법으로 사용하도록 구성된 클러스터 로컬 사용자 계정이 있어야 합니다.
+
'보안 로그인' 명령어의 '-application' 파라미터는 사용자 계정에 대한 접속 방식을 지정한다. 자세한 내용은 보안 로그인 man 페이지를 참조하십시오.

* Telnet 요청이 방화벽을 통과할 수 있도록 클러스터나 노드 관리 LIF에서 사용하는 관리 방화벽 정책에서 텔넷이 이미 활성화되어 있어야 합니다.
+
기본적으로 텔넷은 비활성화되어 있습니다. 시스템 서비스 방화벽 정책 show 명령을 -service telnet 매개변수와 함께 실행하면 텔넷이 방화벽 정책에서 활성화되었는지의 여부가 표시됩니다. 자세한 내용은 시스템 서비스 방화벽 정책 man 페이지를 참조하십시오.

* IPv6 연결을 사용하는 경우 IPv6가 이미 클러스터에서 구성 및 활성화되어 있어야 하며, 방화벽 정책이 이미 IPv6 주소로 구성되어 있어야 합니다.
+
network options ipv6 show 명령을 실행하면 IPv6의 활성화 여부가 표시됩니다. 'system services firewall policy show' 명령은 방화벽 정책을 표시합니다.



.이 작업에 대해
* 텔넷은 보안 프로토콜이 아닙니다.
+
SSH를 사용하여 클러스터에 액세스하는 것을 고려해야 합니다. SSH는 보안 원격 셸 및 대화형 네트워크 세션을 제공합니다.

* ONTAP는 노드당 최대 50개의 동시 텔넷 세션을 지원합니다.
+
클러스터 관리 LIF가 노드에 상주하는 경우 이 제한을 노드 관리 LIF와 공유합니다.

+
들어오는 연결의 비율이 초당 10보다 높을 경우 서비스가 60초 동안 일시적으로 비활성화됩니다.

* Windows 호스트에서 ONTAP CLI에 액세스하려는 경우 PuTTY와 같은 타사 유틸리티를 사용할 수 있습니다.


.단계
. 관리 호스트에서 다음 명령을 입력합니다.
+
'* telnet_hostname_or_ip_ * '

+
'_hostname_or_ip_'은 클러스터 관리 LIF 또는 노드 관리 LIF의 호스트 이름 또는 IP 주소입니다. 클러스터 관리 LIF를 사용하는 것이 좋습니다. IPv4 또는 IPv6 주소를 사용할 수 있습니다.



다음 예에서는 텔넷 액세스를 사용하여 설정된 ""Joe""라는 사용자가 클러스터 관리 LIF가 10.72.137.28인 클러스터에 액세스하기 위한 텔넷 요청을 실행할 수 있는 방법을 보여줍니다.

[listing]
----
admin_host$ telnet 10.72.137.28
Data ONTAP
login: joe
Password:
cluster1::>
----