---
permalink: system-admin/add-nodes-cluster-concept.html 
sidebar: sidebar 
keywords: add, node, cluster, create, expand 
summary: 클러스터가 생성된 후 노드를 추가하여 클러스터를 확장할 수 있습니다. 노드를 한 번에 하나만 추가할 수 있습니다. 
---
= 클러스터에 노드를 추가합니다
:icons: font
:imagesdir: ../media/


[role="lead"]
클러스터가 생성된 후 노드를 추가하여 클러스터를 확장할 수 있습니다. 노드를 한 번에 하나만 추가할 수 있습니다.

.무엇을 &#8217;필요로 할거야
* 다중 노드 클러스터에 노드를 추가하는 경우 클러스터의 기존 노드 중 절반 이상이 정상 상태여야 합니다('cluster show'로 표시됨).
* 스위치가 없는 2노드 클러스터에 노드를 추가하는 경우 노드를 추가하기 전에 클러스터 관리 및 인터커넥트 스위치를 설치하고 구성해야 합니다.
+
스위치가 없는 클러스터 기능은 2노드 클러스터에서만 지원됩니다.

+
클러스터에 노드가 2개 이상 있거나 노드가 있을 경우 클러스터 HA가 필요하지 않고 자동으로 비활성화됩니다.

* 단일 노드 클러스터에 두 번째 노드를 추가하는 경우 두 번째 노드가 설치되었고 클러스터 네트워크를 구성해야 합니다.
* 클러스터에 SP 자동 구성이 설정된 경우 SP에서 사용하도록 지정된 서브넷에 참여 노드에 사용할 수 있는 리소스가 있어야 합니다.
+
클러스터를 결합하는 노드는 지정된 서브넷을 사용하여 SP에 대한 자동 구성을 수행합니다.

* 새 노드의 노드 관리 LIF에 대해 다음 정보를 수집해야 합니다.
+
** 포트
** IP 주소입니다
** 넷마스크
** 기본 게이트웨이




노드는 HA Pair를 구성할 수 있도록 짝수여야 합니다. 클러스터에 노드를 추가하기 시작한 후 프로세스를 완료해야 합니다. 다른 노드를 추가하기 전에 노드가 클러스터의 일부여야 합니다.

.단계
. 클러스터에 추가할 노드의 전원을 켭니다.
+
노드가 부팅되고 노드 설정 마법사가 콘솔에서 시작됩니다.

+
[listing]
----
Welcome to node setup.

You can enter the following commands at any time:
  "help" or "?" - if you want to have a question clarified,
  "back" - if you want to change previously answered questions, and
  "exit" or "quit" - if you want to quit the setup wizard.
     Any changes you made before quitting will be saved.

To accept a default or omit a question, do not enter a value.

Enter the node management interface port [e0c]:
----
. 노드 설정 마법사를 종료합니다
+
노드 설정 마법사가 종료되고 설치 작업을 완료하지 않았다는 로그인 프롬프트가 나타납니다.

. admin 사용자 이름을 사용하여 admin 계정에 로그인합니다.
. 클러스터 설정 마법사를 시작합니다.
+
'* 클러스터 설정 * '

+
[listing]
----
::> cluster setup

Welcome to the cluster setup wizard.

You can enter the following commands at any time:
 "help" or "?" - if you want to have a question clarified,
 "back" - if you want to change previously answered questions, and
 "exit" or "quit" - if you want to quit the cluster setup wizard.
 Any changes you made before quitting will be saved.

You can return to cluster setup at any time by typing "cluster setup".
To accept a default or omit a question, do not enter a value....

Use your web browser to complete cluster setup by accessing
https://10.63.11.29

Otherwise, press Enter to complete cluster setup using the
command line interface:
----
+
[NOTE]
====
설정 GUI를 사용하여 클러스터를 설정하는 방법에 대한 자세한 내용은 를 참조하십시오 link:https://docs.netapp.com/us-en/ontap/task_admin_add_nodes_to_cluster.html["시스템 관리자"] 온라인 도움말.

====
. Enter 키를 눌러 CLI를 사용하여 이 작업을 완료합니다. 새 클러스터를 생성하거나 기존 클러스터에 가입하라는 메시지가 표시되면 ' * join * '을 입력합니다.
+
[listing]
----
Do you want to create a new cluster or join an existing cluster? {create, join}:
join
----
. 프롬프트에 따라 노드를 설정하고 클러스터에 연결합니다.
+
** 프롬프트의 기본값을 그대로 사용하려면 Enter 키를 누릅니다.
** 프롬프트에 대한 값을 직접 입력하려면 값을 입력한 다음 Enter 키를 누릅니다.


. 추가할 각 추가 노드에 대해 위의 단계를 반복합니다.


클러스터에 노드를 추가한 후에는 각 HA 쌍에 대해 스토리지 페일오버를 설정해야 합니다.
