---
permalink: system-admin/audit-display-log-contents-task.html 
sidebar: sidebar 
keywords: audit, log, cluster, display 
summary: ONTAP CLI, System Manager 또는 웹 브라우저를 사용하여 /mroot/etc/log/mlog/audit.log 파일의 내용을 표시할 수 있습니다. 
---
= 감사 로그 내용을 표시합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP CLI, System Manager 또는 웹 브라우저를 사용하여 클러스터의 `/mroot/etc/log/mlog/audit.log' 파일의 내용을 표시할 수 있습니다.

클러스터의 로그 파일 항목은 다음과 같습니다.

시간:: 로그 항목 타임 스탬프입니다.
응용 프로그램:: 클러스터에 연결하는 데 사용되는 애플리케이션입니다. 가능한 값의 예는 `internal` , `console`, `ssh`, `http`, , `ontapi`, 입니다. `snmp` `rsh`, , , `telnet` 및 `service-processor`.
사용자:: 원격 사용자의 사용자 이름입니다.
상태:: 감사 요청의 현재 상태는, `pending` 또는 일 수 있습니다 `success`. `error`
메시지:: 명령 상태에 대한 오류 또는 추가 정보를 포함할 수 있는 선택적 필드입니다.
세션 ID입니다:: 요청이 수신된 세션 ID입니다. 각 SSH_SESSION_에는 세션 ID가 할당되고 각 HTTP, ONTAPI 또는 SNMP_REQUEST_에는 고유한 세션 ID가 할당됩니다.
스토리지 VM:: 사용자가 연결하는 데 사용되는 SVM.
범위:: 데이터 스토리지 VM에 요청이 있으면 'VM'을 표시하고, 그렇지 않으면 '클러스터'를 표시합니다.
명령 ID입니다:: CLI 세션에서 수신한 각 명령의 ID입니다. 이렇게 하면 요청과 응답을 서로 연관시킬 수 있습니다. ZAPI, HTTP 및 SNMP 요청에는 명령 ID가 없습니다.


웹 브라우저에서 ONTAP CLI의 클러스터의 로그 항목을 표시하고 시스템 관리자에서 ONTAP 9.11.1로 시작할 수 있습니다.

[role="tabbed-block"]
====
.시스템 관리자
--
* 인벤토리를 표시하려면 * 이벤트 및 작업 > 감사 로그 * 를 선택합니다. + 각 열에는 필터링, 정렬, 검색, 표시 및 인벤토리 범주를 제어하는 컨트롤이 있습니다. 재고 세부 정보는 Excel 통합 문서로 다운로드할 수 있습니다.
* 필터를 설정하려면 오른쪽 위에 있는 * Filter * (필터 *) 버튼을 클릭하고 원하는 필드를 선택합니다. +세션 ID 링크를 클릭하여 장애가 발생한 세션에서 실행된 모든 명령을 볼 수도 있습니다.


--
.CLI를 참조하십시오
--
클러스터의 여러 노드에서 병합된 감사 항목을 표시하려면 + 를 입력합니다
`security audit log show <[parameters]>`

'security audit log show' 명령을 사용하면 개별 노드의 감사 항목을 표시하거나 클러스터의 여러 노드에서 병합한 감사 항목을 표시할 수 있습니다. 웹 브라우저를 사용하여 단일 노드에 '/mroot/etc/log/mlog' 디렉토리의 컨텐츠를 표시할 수도 있습니다. 자세한 내용은 man 페이지를 참조하십시오.

--
.웹 브라우저
--
웹 브라우저를 사용하여 단일 노드에 '/mroot/etc/log/mlog' 디렉토리의 내용을 표시할 수 있습니다. link:accessg-node-log-core-dump-mib-files-task.html["웹 브라우저를 사용하여 노드의 로그, 코어 덤프 및 MIB 파일에 액세스하는 방법에 대해 알아보십시오"].

--
====