---
permalink: system-admin/autosupport-creates-sends-event-messages-concept.html 
sidebar: sidebar 
keywords: autosupport, event, triggered, messages, ems, data, example 
summary: AutoSupport는 EMS가 트리거 이벤트를 처리할 때 이벤트 트리거 AutoSupport 메시지를 생성합니다. 이벤트가 트리거된 AutoSupport 메시지는 수신자에게 수정 조치가 필요한 문제를 경고하고 문제와 관련된 정보만 포함합니다. 포함할 콘텐츠 및 메시지를 받는 사람을 사용자 지정할 수 있습니다. 
---
= AutoSupport에서 이벤트 트리거 메시지를 만들고 보내는 방법
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
AutoSupport는 EMS가 트리거 이벤트를 처리할 때 이벤트 트리거 AutoSupport 메시지를 생성합니다. 이벤트가 트리거된 AutoSupport 메시지는 수신자에게 수정 조치가 필요한 문제를 경고하고 문제와 관련된 정보만 포함합니다. 포함할 콘텐츠 및 메시지를 받는 사람을 사용자 지정할 수 있습니다.

AutoSupport는 다음 프로세스를 사용하여 이벤트 트리거 AutoSupport 메시지를 만들고 보냅니다.

. EMS가 trigger event를 처리할 때, EMS는 AutoSupport에게 request를 보낸다.
+
트리거 이벤트는 AutoSupport 대상 및 이름이 callhome으로 시작하는 EMS 이벤트입니다.

. AutoSupport에서 이벤트 트리거 AutoSupport 메시지를 생성합니다.
+
AutoSupport는 트리거와 연결된 하위 시스템으로부터 기본 및 문제 해결 정보를 수집하여 트리거 이벤트와 관련된 정보만 포함된 메시지를 생성합니다.

+
기본 하위 시스템 세트는 각 트리거와 연결됩니다. 그러나 'system node AutoSupport trigger modify' 명령을 사용하여 추가 서브시스템을 트리거에 연결할 수 있습니다.

. AutoSupport는 시스템 노드 AutoSupport modify 명령에 의해 정의된 수신자에게 -to, -noteto, -partner-address, -support 매개 변수를 사용하여 이벤트 트리거 AutoSupport 메시지를 보냅니다.
+
'-to' 및 '-noteto' 매개 변수를 사용하여 'system node AutoSupport trigger modify' 명령을 사용하여 특정 트리거에 대한 AutoSupport 메시지 전달을 활성화 또는 비활성화할 수 있습니다.



.특정 이벤트에 대해 전송된 데이터의 예
Storage shelf PSU failed EMS 이벤트는 Mandatory, Log Files, Storage, RAID, HA의 기본 데이터가 포함된 메시지를 플랫폼, 네트워킹 하위 시스템 및 필수, 로그 파일 및 스토리지 하위 시스템의 데이터 문제 해결

향후 '스토리지 셸프 PSU 실패' 이벤트에 대한 응답으로 전송된 AutoSupport 메시지에 NFS에 대한 데이터를 포함시키기로 결정합니다. callhome.shlf.ps.fault 이벤트에 대해 NFS에 대한 문제 해결 수준 데이터를 활성화하려면 다음 명령을 입력합니다.

[listing]
----

        cluster1::\>
        system node autosupport trigger modify -node node1 -autosupport-message shlf.ps.fault -troubleshooting-additional nfs
----
'system node AutoSupport trigger' 명령어를 사용하거나 CLI에서 AutoSupport 및 EMS 이벤트가 참조할 때 callhome.shlf.ps.fault 이벤트에서 callhome. 접두사가 삭제된다.
