---
permalink: system-admin/commands-manage-jobs-reference.html 
sidebar: sidebar 
keywords: command, manage, jobs, queue, cluster, resources 
summary: 작업이 작업 대기열에 배치되어 자원을 사용할 수 있을 때 백그라운드에서 실행됩니다. 작업이 클러스터 리소스를 너무 많이 사용하는 경우, 클러스터에 대한 수요가 적어질 때까지 작업을 중지하거나 일시 중지할 수 있습니다. 작업을 모니터링하고 다시 시작할 수도 있습니다. 
---
= 작업 관리를 위한 명령입니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
작업이 작업 대기열에 배치되어 자원을 사용할 수 있을 때 백그라운드에서 실행됩니다. 작업이 클러스터 리소스를 너무 많이 사용하는 경우, 클러스터에 대한 수요가 적어질 때까지 작업을 중지하거나 일시 중지할 수 있습니다. 작업을 모니터링하고 다시 시작할 수도 있습니다.

작업을 호출하는 명령을 입력하면 일반적으로 명령은 작업이 대기열에 있음을 알려 주는 다음 CLI 명령 프롬프트로 돌아갑니다. 그러나 일부 명령은 작업 진행률을 보고하고 작업이 완료될 때까지 CLI 명령 프롬프트로 돌아가지 않습니다. 이러한 경우 Ctrl+C를 눌러 작업을 백그라운드로 이동할 수 있습니다.

|===
| 원하는 작업 | 이 명령 사용... 


 a| 
모든 작업에 대한 정보를 표시합니다
 a| 
일자리 쇼



 a| 
노드 단위로 작업에 대한 정보를 표시합니다
 a| 
'job show bynode'



 a| 
클러스터 관련 작업에 대한 정보를 표시합니다
 a| 
잡쇼 클러스터



 a| 
완료된 작업에 대한 정보를 표시합니다
 a| 
일자리 보이기 완료



 a| 
작업 기록에 대한 정보를 표시합니다
 a| 
직업 연혁 쇼

클러스터의 각 노드에 대해 최대 25,000개의 작업 레코드가 저장됩니다. 따라서 전체 작업 기록을 표시하려고 하면 시간이 오래 걸릴 수 있습니다. 대기 시간이 오래 걸릴 수 있으므로 노드, SVM(스토리지 가상 머신) 또는 레코드 ID별로 작업을 표시해야 합니다.



 a| 
개인 작업 목록을 표시합니다
 a| 
잡사쇼(고급특권)



 a| 
완료된 개인 작업에 대한 정보를 표시합니다
 a| 
취직 사적 공연 완료(고급 특권 수준)



 a| 
작업 관리자의 초기화 상태에 대한 정보를 표시합니다
 a| 
'job initstate show'(고급 권한 수준)



 a| 
작업의 진행 상황을 모니터링합니다
 a| 
직업감시-진척도



 a| 
개인 작업의 진행 상황을 모니터링합니다
 a| 
취직사감시-진전(고급특권)



 a| 
작업을 일시정지합니다
 a| 
"작업 일시정지"



 a| 
개인 작업을 일시 중지합니다
 a| 
작업 비공개 일시 중지(고급 권한 수준)



 a| 
일시 중지된 작업을 다시 시작합니다
 a| 
일자리 재개다



 a| 
일시 중지된 개인 작업을 다시 시작합니다
 a| 
일자리 민영(Advanced Privilege)



 a| 
작업을 중지합니다
 a| 
잡지중지



 a| 
개인 작업을 중지합니다
 a| 
일자리 전용 경유지고(고급 특권 수준)



 a| 
작업을 삭제합니다
 a| 
일자리 삭제



 a| 
개인 작업을 삭제합니다
 a| 
'job private delete'(고급 권한 수준)



 a| 
클러스터 관련 작업을 해당 작업을 소유하는 사용 불가능한 노드와 연결을 끊는 경우 다른 노드가 해당 작업의 소유권을 가질 수 있습니다
 a| 
잡무청구(Advanced Privilege Level)

|===
[NOTE]
====
이벤트 로그 표시 명령을 사용하여 완료된 작업의 결과를 확인할 수 있습니다.

====
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-cmpr/GUID-5CB10C70-AC11-41C0-8C16-B4D0DF916E9B.html["ONTAP 9 명령"^]
