---
permalink: system-admin/commands-manage-autosupport-reference.html 
sidebar: sidebar 
keywords: command, manage, autosupport, node, message, send, resend, cancel, configure, display, information 
summary: 시스템 노드 AutoSupport 명령을 사용하여 AutoSupport 구성을 변경하거나 보고, 이전 AutoSupport 메시지에 대한 정보를 표시하고, AutoSupport 메시지를 전송, 다시 보내기 또는 취소할 수 있습니다. 
---
= AutoSupport 관리를 위한 명령입니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
'시스템 노드 AutoSupport' 명령어를 이용하여 AutoSupport 설정을 변경, 조회, 이전 AutoSupport 메시지 정보 표시, AutoSupport 메시지 전송, 재전송, 취소 등을 할 수 있다.



== AutoSupport를 구성합니다

|===
| 원하는 작업 | 이 명령 사용... 


 a| 
AutoSupport 메시지 전송 여부를 제어합니다
 a| 
'system node AutoSupport modify'는 -state 매개 변수를 사용합니다



 a| 
AutoSupport 메시지가 기술 지원 부서에 전송되는지 여부를 제어합니다
 a| 
system node AutoSupport modify with the '-support' parameter



 a| 
AutoSupport를 설정하거나 AutoSupport의 구성을 수정합니다
 a| 
'시스템 노드 AutoSupport 수정



 a| 
개별 트리거 이벤트에 대해 내부 지원 조직에 AutoSupport 메시지를 활성화 및 비활성화하고 개별 트리거 이벤트에 대한 응답으로 전송된 메시지에 포함할 추가 하위 시스템 보고서를 지정합니다
 a| 
'시스템 노드 AutoSupport trigger modify

|===


== AutoSupport 구성에 대한 정보를 표시합니다

|===
| 원하는 작업 | 이 명령 사용... 


 a| 
AutoSupport 설정을 표시합니다
 a| 
'system node AutoSupport show'와 '-node' 매개 변수를 함께 사용합니다



 a| 
AutoSupport 메시지를 수신하는 모든 주소 및 URL의 요약을 봅니다
 a| 
'System node AutoSupport destinations show'가 나타납니다



 a| 
개별 트리거 이벤트에 대해 내부 지원 조직에 전송되는 AutoSupport 메시지를 표시합니다
 a| 
'시스템 노드 AutoSupport trigger show'



 a| 
AutoSupport 구성 상태 및 다양한 대상에 대한 전송 상태를 표시합니다
 a| 
'시스템 노드 AutoSupport check show'



 a| 
AutoSupport 구성의 세부 상태와 다양한 대상에 대한 전송을 표시합니다
 a| 
'시스템 노드 AutoSupport check show-details

|===


== 지난 AutoSupport 메시지에 대한 정보를 표시합니다

|===
| 원하는 작업 | 이 명령 사용... 


 a| 
최근 50개 AutoSupport 메시지 중 하나 이상에 대한 정보를 표시합니다
 a| 
'시스템 노드 AutoSupport history show'



 a| 
코어 덤프 또는 성능 아카이브 파일을 기술 지원 사이트나 지정된 URI에 업로드하기 위해 생성된 최근 AutoSupport 메시지에 대한 정보를 표시합니다
 a| 
'시스템 노드 AutoSupport history show-upload-details'



 a| 
메시지에 대해 수집된 각 파일의 이름과 크기를 비롯한 AutoSupport 메시지의 정보를 오류 메시지와 함께 확인합니다
 a| 
'System node AutoSupport manifest show'

|===


== AutoSupport 메시지 보내기, 다시 보내기 또는 취소

|===
| 원하는 작업 | 이 명령 사용... 


 a| 
AutoSupport 시퀀스 번호로 식별되는 로컬에 저장된 AutoSupport 메시지를 다시 전송합니다

[NOTE]
====
AutoSupport 메시지를 다시 전송하고 해당 메시지를 이미 수신한 경우 지원 시스템에서 중복 케이스를 생성하지 않습니다. 반면에 지원부서에서 해당 메시지를 받지 못한 경우 AutoSupport 시스템은 메시지를 분석하고 필요한 경우 케이스를 생성합니다.

==== a| 
시스템 노드 AutoSupport history retransmit



 a| 
AutoSupport 메시지 생성 및 전송 -- 예를 들어, 테스트용으로 사용합니다
 a| 
'시스템 노드 AutoSupport 호출'

[NOTE]
====
AutoSupport가 비활성화되었더라도 '-force' 매개 변수를 사용하여 메시지를 보냅니다. 구성된 대상 대신 지정한 대상으로 메시지를 보내려면 '-Uri' 매개 변수를 사용합니다.

====


 a| 
AutoSupport 메시지를 취소합니다
 a| 
'시스템 노드 AutoSupport history cancel

|===
.관련 정보
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-cmpr/GUID-5CB10C70-AC11-41C0-8C16-B4D0DF916E9B.html["ONTAP 9 명령"^]
