---
permalink: system-admin/commands-monitor-health-system-reference.html 
sidebar: sidebar 
keywords: command, monitor, health, system, display, status, cli, software, version, switches, alert 
summary: 시스템 상태 명령을 사용하여 시스템 리소스 상태에 대한 정보를 표시하고, 알림에 응답하고, 향후 알림을 구성할 수 있습니다. CLI 명령을 사용하면 상태 모니터링 구성 방법에 대한 자세한 정보를 볼 수 있습니다. 명령에 대한 man 페이지에는 자세한 정보가 포함되어 있습니다. 
---
= 시스템 상태를 모니터링하는 명령입니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
시스템 상태 명령을 사용하여 시스템 리소스 상태에 대한 정보를 표시하고, 알림에 응답하고, 향후 경고를 구성할 수 있습니다. CLI 명령을 사용하면 상태 모니터링 구성 방법에 대한 자세한 정보를 볼 수 있습니다. 명령에 대한 man 페이지에는 자세한 정보가 포함되어 있습니다.



== 시스템 상태의 상태를 표시합니다

|===
| 원하는 작업 | 이 명령 사용... 


 a| 
개별 상태 모니터의 전체 상태를 반영하는 시스템의 상태를 표시합니다
 a| 
'시스템 상태 표시



 a| 
상태 모니터링을 사용할 수 있는 서브시스템의 상태를 표시합니다
 a| 
시스템 상태 하위 시스템이 표시됩니다

|===


== 노드 접속 상태를 표시합니다

|===
| 원하는 작업 | 이 명령 사용... 


 a| 
포트 정보, HBA 포트 속도, I/O 처리량, 초당 I/O 작업 속도 등 노드에서 스토리지 셸프로의 접속에 대한 세부 정보를 표시합니다
 a| 
'Storage shelf show-connectivity

'-instance' 매개 변수를 사용하여 각 쉘프에 대한 자세한 정보를 표시합니다.



 a| 
사용 가능한 공간, 쉘프 및 베이 번호, 소유 노드 이름 등의 드라이브 및 어레이 LUN에 대한 정보를 표시합니다
 a| 
스토리지 디스크 쇼

각 드라이브에 대한 자세한 정보를 표시하려면 '-instance' 매개 변수를 사용하십시오.



 a| 
포트 유형, 속도 및 상태를 포함한 스토리지 쉘프 포트에 대한 자세한 정보를 표시합니다
 a| 
'Storage port show'

각 어댑터에 대한 자세한 정보를 표시하려면 '-instance' 매개 변수를 사용하십시오.

|===


== 클러스터 및 관리 네트워크 스위치의 검색 관리

|===
| 원하는 작업 | 이 명령 사용... 


 a| 
클러스터에서 모니터링하는 스위치를 표시합니다
 a| 
'system cluster-switch show'



 a| 
명령 출력의 Reason 열에 표시된 스위치를 비롯하여 클러스터에서 현재 모니터링하는 스위치와 클러스터 및 관리 네트워크 스위치에 대한 네트워크 액세스에 필요한 구성 정보를 표시합니다.

이 명령은 고급 권한 수준에서 사용할 수 있습니다.
 a| 
'system cluster-switch show-all'



 a| 
검색되지 않은 스위치의 검색을 구성합니다
 a| 
'system cluster-switch create



 a| 
클러스터에서 모니터링하는 스위치에 대한 정보 수정(예: 장치 이름, IP 주소, SNMP 버전 및 커뮤니티 문자열)
 a| 
'시스템 클러스터 스위치 수정



 a| 
스위치 모니터링을 비활성화합니다
 a| 
'system cluster-switch modify-disable-monitoring



 a| 
스위치 검색 및 모니터링을 비활성화하고 스위치 구성 정보를 삭제합니다
 a| 
'system cluster-switch delete



 a| 
데이터베이스에 저장된 스위치 구성 정보를 영구적으로 제거합니다(이렇게 하면 스위치의 자동 검색이 다시 활성화됩니다).
 a| 
'system cluster-switch delete-force'를 선택합니다



 a| 
AutoSupport 메시지와 함께 보내려면 자동 로깅을 활성화합니다.

이 명령은 고급 권한 수준에서 사용할 수 있습니다.
 a| 
'시스템 클러스터-스위치 로그

|===


== 생성된 알림에 응답합니다

|===
| 원하는 작업 | 이 명령 사용... 


 a| 
알림이 트리거된 리소스 및 노드, 알림의 심각도 및 추정 원인과 같이 생성된 알림에 대한 정보를 표시합니다
 a| 
'시스템 상태 경고 표시



 a| 
생성된 각 알림에 대한 정보를 표시합니다
 a| 
'시스템 상태 경고 표시 - 인스턴스'



 a| 
다른 사용자가 알림을 작업 중임을 나타냅니다
 a| 
시스템 상태 알림 수정



 a| 
알림을 확인합니다
 a| 
'시스템 상태 경고 수정 - 확인'



 a| 
하위 시스템의 상태에 영향을 주지 않도록 후속 경고를 표시하지 않습니다
 a| 
'시스템 상태 경고 수정 - 억제'



 a| 
자동으로 지워지지 않은 알림을 삭제합니다
 a| 
'시스템 상태 경고 삭제



 a| 
예를 들어, 알림이 AutoSupport 메시지를 트리거했는지 여부와 같이 지난 주 내에 트리거된 알림을 표시하는 AutoSupport 메시지에 대한 정보를 표시합니다
 a| 
'시스템 상태 AutoSupport 트리거 기록 표시

|===


== 향후 알림을 구성합니다

|===
| 원하는 작업 | 이 명령 사용... 


 a| 
특정 리소스 상태가 특정 경고를 발생시키는지 여부를 제어하는 정책을 사용하거나 사용하지 않도록 설정합니다
 a| 
'시스템 상태 정책 정의 수정

|===


== 상태 모니터링 구성 방법에 대한 정보를 표시합니다

|===
| 원하는 작업 | 이 명령 사용... 


 a| 
노드, 이름, 하위 시스템 및 상태와 같은 상태 모니터에 대한 정보를 표시합니다
 a| 
'시스템 상태 구성 쇼'

[NOTE]
====
각 상태 모니터에 대한 세부 정보를 표시하려면 '-instance' 매개 변수를 사용합니다.

====


 a| 
상태 모니터에서 잠재적으로 생성할 수 있는 알림에 대한 정보를 표시합니다
 a| 
시스템 상태 경고 정의가 표시됩니다

[NOTE]
====
각 경고 정의에 대한 자세한 정보를 표시하려면 '-instance' 매개 변수를 사용합니다.

====


 a| 
알림이 발생하는 시기를 결정하는 상태 모니터링 정책에 대한 정보를 표시합니다
 a| 
시스템 상태 정책 정의가 표시됩니다

[NOTE]
====
각 정책에 대한 세부 정보를 표시하려면 '-instance' 매개 변수를 사용합니다. 다른 매개 변수를 사용하여 알림 목록을 정책 상태(사용 여부), 상태 모니터, 알림 등으로 필터링할 수 있습니다.

====
|===


== 부 릴리스 간에 소프트웨어 버전을 다운그레이드합니다

|===
| 원하는 작업 | 이 명령 사용... 


 a| 
소프트웨어 버전 명령을 다운그레이드합니다
 a| 
'시스템 클러스터-스위치 준비-다운그레이드

|===