---
permalink: system-admin/commands-manage-system-time-reference.html 
sidebar: sidebar 
keywords: command, manage, cluster, time, ntp, server, date, ntp, time, manually 
summary: 클러스터 시간 서비스 NTP 서버 명령을 사용하여 클러스터의 NTP 서버를 관리합니다. 클러스터 날짜 명령을 사용하여 수동으로 클러스터 시간을 관리합니다. 
---
= 클러스터 시간을 관리하는 명령입니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
클러스터의 NTP 서버를 관리하기 위해 'cluster time-service ntp server' 명령어를 사용한다. 클러스터 날짜 명령을 사용하여 수동으로 클러스터 시간을 관리할 수 있습니다.

ONTAP 9.5부터 대칭 인증을 사용하여 NTP 서버를 구성할 수 있습니다.

다음 명령을 사용하여 클러스터의 NTP 서버를 관리할 수 있습니다.

|===
| 원하는 작업 | 이 명령 사용... 


 a| 
대칭 인증 없이 클러스터를 외부 NTP 서버에 연결합니다
 a| 
'cluster time-service ntp server create-server server_name



 a| 
클러스터를 외부 NTP 서버와 ONTAP 9.5 이상에서 사용할 수 있는 대칭 인증으로 연결합니다
 a| 
'cluster time-service ntp server create-server_ip_address-key-id key_id

[NOTE]
====
'key_id'는 ''cluster time-service ntp key'로 설정된 기존 공유 키를 참조해야 합니다.

====


 a| 
기존 NTP 서버에 대칭 인증 사용 기존 NTP 서버는 필요한 키 ID를 추가하여 인증을 사용하도록 수정할 수 있습니다

ONTAP 9.5 이상에서 사용할 수 있습니다
 a| 
'cluster time-service ntp server modify -server server_name -key-id key_id



 a| 
대칭 인증을 사용하지 않도록 설정합니다
 a| 
'cluster time-service ntp server modify -server server_name -authentication disabled'



 a| 
공유 NTP 키를 구성합니다
 a| 
'cluster time-service ntp key create-id shared_key_id-type shared_key_type-value shared_key_value'

[NOTE]
====
공유 키는 ID로 참조됩니다. ID, 유형 및 값은 노드와 NTP 서버 모두에서 동일해야 합니다

====


 a| 
클러스터와 연결된 NTP 서버에 대한 정보를 표시합니다
 a| 
클러스터 시간 서비스 NTP 서버가 표시됩니다



 a| 
클러스터와 연결된 외부 NTP 서버의 구성을 수정합니다
 a| 
클러스터 시간 서비스 NTP 서버 수정



 a| 
클러스터에서 NTP 서버를 해제합니다
 a| 
클러스터 시간 서비스 NTP 서버 삭제



 a| 
클러스터와의 모든 외부 NTP 서버 연결을 선택 취소하여 구성을 재설정합니다
 a| 
클러스터 시간 서비스 NTP 서버 리셋

[NOTE]
====
이 명령을 사용하려면 고급 권한 수준이 필요합니다.

====
|===
다음 명령을 사용하면 클러스터 시간을 수동으로 관리할 수 있습니다.

|===
| 원하는 작업 | 이 명령 사용... 


 a| 
시간대, 날짜 및 시간을 설정하거나 수정합니다
 a| 
클러스터 날짜 수정



 a| 
클러스터의 시간대, 날짜 및 시간 설정을 표시합니다
 a| 
'클러스터 날짜 표시'

|===
.관련 정보
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-cmpr/GUID-5CB10C70-AC11-41C0-8C16-B4D0DF916E9B.html["ONTAP 9 명령"^]
