---
permalink: system-admin/commands-manage-node-remotely-reference.html 
sidebar: sidebar 
keywords: command, manage, node, remotely, sp, cli, cluster 
summary: SP에 액세스한 후 SP CLI 명령을 실행하여 노드 관리 작업을 수행하여 노드를 원격으로 관리할 수 있습니다. 일반적으로 수행되는 여러 원격 노드 관리 작업의 경우, 클러스터의 다른 노드에서 ONTAP 명령을 사용할 수도 있습니다. 일부 SP 명령은 플랫폼별로 다르며 플랫폼으로는 사용하지 못할 수도 있습니다. 
---
= 노드를 원격으로 관리하는 명령입니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SP에 액세스한 후 SP CLI 명령을 실행하여 노드 관리 작업을 수행하여 노드를 원격으로 관리할 수 있습니다. 일반적으로 수행되는 여러 원격 노드 관리 작업의 경우, 클러스터의 다른 노드에서 ONTAP 명령을 사용할 수도 있습니다. 일부 SP 명령은 플랫폼별로 다르며 플랫폼으로는 사용하지 못할 수도 있습니다.

|===
| 원하는 작업 | 이 SP 명령 사용... | 이 BMC 명령 사용... | 또는 이 ONTAP 명령... 


 a| 
지정된 SP 명령의 사용 가능한 SP 명령 또는 하위 명령을 표시합니다
 a| 
도움말 ['명령']
 a| 
 a| 



 a| 
SP CLI의 현재 권한 수준을 표시합니다
 a| 
'한자 쇼'
 a| 
 a| 



 a| 
SP CLI에 대해 지정된 모드에 액세스할 수 있도록 권한 수준을 설정합니다
 a| 
'어퍼셋'{'admin'|'advanced'|'dIAG'}
 a| 
 a| 



 a| 
시스템 날짜 및 시간을 표시합니다
 a| 
다
 a| 
 a| 
다



 a| 
SP에 의해 기록되는 이벤트를 표시합니다
 a| 
이벤트{'all'|'info'|'fest''number'|'가장 오래된 숫자'|'search keyword'}
 a| 
 a| 



 a| 
SP 상태 및 네트워크 구성 정보를 표시합니다
 a| 
Sp 상태 '['-v'|'-d']

'-v' 옵션은 SP 통계를 자세한 정보 형식으로 표시합니다. '-d' 옵션은 SP 디버그 로그를 디스플레이에 추가합니다.
 a| 
'BMC status'['-v'|'-d']

'-v' 옵션은 SP 통계를 자세한 정보 형식으로 표시합니다. '-d' 옵션은 SP 디버그 로그를 디스플레이에 추가합니다.
 a| 
'시스템 서비스 프로세서 쇼'



 a| 
SP가 가동된 시간과 마지막 1, 5 및 15분 동안 실행 대기열의 평균 작업 수를 표시합니다
 a| 
'가동 시간'
 a| 
BMC 가동 시간
 a| 



 a| 
시스템 콘솔 로그를 표시합니다
 a| 
'시스템 로그'
 a| 
 a| 



 a| 
SP 로그 아카이브 또는 아카이브의 파일을 표시합니다
 a| 
Sp log history show `['-archive'{'latest'|'all'|'archive-name'}]['-dump'{'all'|'file-name'}]
 a| 
[BMC 로그 히스토리 쇼]['-archive'{'latest'|'all'|'archive-name'}]['-dump'{'all'|'file-name'}]
 a| 



 a| 
노드의 컨트롤러에 대한 전원 상태를 표시합니다
 a| 
시스템 전원 상태
 a| 
 a| 
'시스템 노드 파워쇼



 a| 
배터리 정보를 표시합니다
 a| 
'시스템 배터리 쇼'
 a| 
 a| 



 a| 
ACP 정보 또는 확장기 센서의 상태를 표시합니다
 a| 
'시스템 ACP'['show'|'sensors show']
 a| 
 a| 



 a| 
모든 시스템 FRU 및 해당 ID를 나열합니다
 a| 
'시스템 FRU 목록'
 a| 
 a| 



 a| 
지정된 FRU에 대한 제품 정보를 표시합니다
 a| 
시스템 FRU 쇼 FRU_id
 a| 
 a| 



 a| 
FRU 데이터 기록 로그를 표시합니다
 a| 
'시스템 FRU 로그 표시'(고급 권한 수준)
 a| 
 a| 



 a| 
환경 센서의 상태 및 현재 값을 포함한 상태를 표시합니다
 a| 
'시스템 센서'나 '시스템 센서'가 표시됩니다
 a| 
 a| 
시스템 노드 환경 센서가 표시됩니다



 a| 
지정된 센서의 상태 및 세부 정보를 표시합니다
 a| 
'시스템 센서에는 'sensor_name'이 있습니다

'system sensors' 또는 'system sensors show' 명령을 사용하면 'sensor_name'을 얻을 수 있습니다.
 a| 
 a| 



 a| 
SP 펌웨어 버전 정보를 표시합니다
 a| 
'내전'
 a| 
 a| 
'시스템 서비스 프로세서 이미지 쇼'



 a| 
SP 명령 기록을 표시합니다
 a| 
'p log audit'(고급 권한 수준)
 a| 
BMC 로그 감사
 a| 



 a| 
SP 디버그 정보를 표시합니다
 a| 
's log debug'(고급 권한 수준)
 a| 
'bmc log debug'(고급 권한 수준)
 a| 



 a| 
SP 메시지 파일을 표시합니다
 a| 
's log messages'(고급 권한 수준)
 a| 
'BMC 로그 메시지'(고급 권한 수준)
 a| 



 a| 
감시 재설정 이벤트에서 시스템 조사 정보를 수집하거나, 감시 재설정 이벤트 중에 수집된 시스템 조사 정보를 표시하거나, 수집된 시스템 조사 정보를 지우는 설정을 표시합니다
 a| 
시스템 법의학 ['방법'|'로그 덤프'|'로그 지우기']
 a| 
 a| 



 a| 
시스템 콘솔에 로그인합니다
 a| 
시스템 콘솔
 a| 
 a| 
'시스템 노드 실행 콘솔



 a| 
시스템 콘솔 세션을 종료하려면 Ctrl+D를 눌러야 합니다.



 a| 
노드 켜기/끄기 또는 전원 끄기(전원 끄기 후 다시 켜기)
 a| 
'시스템 파워' 켜기
 a| 
 a| 
'시스템 노드 전원 켜기'(고급 권한 수준)



 a| 
'시스템 전원' OFF
 a| 
 a| 



 a| 
'시스템 파워' 사이클
 a| 
 a| 



 a| 
SP를 중단 없이 계속 실행하기 위해 대기 전원이 계속 켜져 있습니다. 전원을 껐다 켜는 동안 전원이 다시 켜지기 전에 잠시 멈춥니다.

[NOTE]
====
이러한 명령을 사용하여 노드를 끄거나 전원을 껐다 켜면 노드가 부적절하게 종료될 수 있으며(_dirty shutdown_ 이라고도 함) ONTAP 'system node halt' 명령을 사용하여 정상적인 종료를 대신할 수 없습니다.

====


 a| 
코어 덤프를 생성하고 노드를 재설정합니다
 a| 
'시스템 코어'['-f']

'-f' 옵션은 코어 덤프의 생성과 노드 재설정을 강제합니다.
 a| 
 a| 
시스템 노드 코어 덤프 트리거

(고급 권한 레벨)



 a| 
이러한 명령은 노드의 NMI(Non-Maskable Interrupt) 단추를 눌러 노드를 중단할 때 노드가 비정상적으로 종료되고 코어 파일의 덤프를 수행하는 것과 동일한 효과를 가집니다. 이러한 명령은 노드의 ONTAP가 중단되거나 '시스템 노드 종료' 같은 명령에 응답하지 않는 경우에 유용합니다. 생성된 core dump 파일은 system node coredump show 명령의 출력에 출력된다. SP는 노드에 대한 입력 전원이 중단되지 않는 한 작동 가능한 상태를 유지합니다.



 a| 
선택적으로 지정된 BIOS 펌웨어 이미지(기본, 백업 또는 현재)를 사용하여 노드를 재부팅하여 노드 부팅 장치의 손상된 이미지와 같은 문제를 복구합니다
 a| 
'시스템 재설정'{'운영'|'백업'|'현재'}
 a| 
 a| 
'-firmware'{'primary'|'backup'|'current'} 파라미터(고급 권한 레벨)로 시스템 노드 리셋

'시스템 노드 리셋



 a| 
[NOTE]
====
이 작업으로 인해 노드가 비정상 종료됩니다.

====
BIOS 펌웨어 이미지를 지정하지 않으면 현재 이미지가 재부팅에 사용됩니다. SP는 노드에 대한 입력 전원이 중단되지 않는 한 작동 가능한 상태를 유지합니다.



 a| 
배터리 펌웨어 자동 업데이트의 상태를 표시하거나, 다음 SP 부팅 시 배터리 펌웨어 자동 업데이트를 사용하거나 사용하지 않도록 설정합니다
 a| 
'시스템 배터리 자동 업데이트' ['상태'|'활성화'|'비활성화']

(고급 권한 레벨)
 a| 
 a| 



 a| 
현재 배터리 펌웨어 이미지를 지정된 펌웨어 이미지와 비교합니다
 a| 
'시스템 배터리 확인'['IMAGE_URL']

(고급 권한 레벨)

IMAGE_URL을 지정하지 않으면 기본 배터리 펌웨어 이미지가 비교용으로 사용됩니다.
 a| 
 a| 



 a| 
지정된 위치의 이미지에서 배터리 펌웨어를 업데이트합니다
 a| 
'시스템 배터리 플래시' 'image_url

(고급 권한 레벨)

어떤 이유로 자동 배터리 펌웨어 업그레이드 프로세스가 실패한 경우 이 명령을 사용합니다.
 a| 
 a| 



 a| 
지정된 위치의 이미지를 사용하여 SP 펌웨어를 업데이트합니다
 a| 
'S update''image_url image_url'는 200자를 초과할 수 없습니다.
 a| 
'bmc update' image_url image_url'는 200자를 초과할 수 없습니다.
 a| 
'시스템 서비스 프로세서 이미지 업데이트



 a| 
SP를 재부팅합니다
 a| 
'재부팅'
 a| 
 a| 
'시스템 서비스 프로세서 재부팅 - SP'



 a| 
[NOTE]
====
백업 이미지에서 SP를 부팅하지 않아야 합니다. 백업 이미지에서 부팅은 문제 해결 및 복구용으로만 예약되어 있습니다. 권장 설정이 아닌 SP 자동 펌웨어 업데이트를 비활성화해야 할 수 있습니다. 백업 이미지에서 SP를 부팅하기 전에 기술 지원 부서에 문의해야 합니다.

====


 a| 
NVRAM 플래시 콘텐츠를 지웁니다
 a| 
'시스템 NVRAM 플래시 지우기'(고급 권한 수준)

컨트롤러 전원이 꺼진 경우('시스템 전원 꺼짐') 이 명령을 시작할 수 없습니다.
 a| 
 a| 



 a| 
SP CLI를 종료합니다
 a| 
종료
 a| 
 a| 

|===