---
permalink: system-admin/commands-manage-job-schedules-reference.html 
sidebar: sidebar 
keywords: command, manage, job, schedule, volume, snapshot, copy, cron, interval 
summary: '볼륨 스냅샷 복사본과 같은 다양한 작업을 특정 일정에 따라 실행하도록 구성할 수 있습니다. 특정 시간에 실행되는 스케줄을 cron 스케줄이라고 합니다(UNIX cron 일정과 유사). 일정 간격으로 실행되는 일정을 간격 일정이라고 합니다. 작업 스케줄 명령을 사용하여 작업 스케줄을 관리할 수 있습니다.' 
---
= 작업 스케줄 관리를 위한 명령입니다
:icons: font
:imagesdir: ../media/


[role="lead"]
예를 들어 볼륨 스냅샷 복사본 같은 많은 작업은 지정된 스케줄에 따라 실행되도록 구성할 수 있습니다. 특정 시간에 실행되는 스케줄은 _cron_schedules (UNIX의 "cron" 스케줄과 유사)입니다. 일정 간격으로 실행되는 스케줄을 _INTERVAL_schedules 라고 합니다. 작업 일정을 관리하려면 '작업 일정' 명령을 사용합니다.

작업 일정은 클러스터 날짜 및 시간의 수동 변경에 맞게 조정되지 않습니다. 이러한 작업은 작업이 생성된 현재 클러스터 시간 또는 가장 최근에 실행된 작업을 기준으로 실행되도록 예약되어 있습니다. 따라서 클러스터 날짜 또는 시간을 수동으로 변경하는 경우 "job show" 및 "job history show" 명령을 사용하여 예약된 모든 작업이 요구 사항에 따라 대기열에 추가되고 완료되었는지 확인해야 합니다.

클러스터가 MetroCluster 구성에 포함된 경우 두 클러스터의 작업 일정이 동일해야 합니다. 따라서 작업 스케줄을 생성, 수정 또는 삭제하는 경우 원격 클러스터에서 동일한 작업을 수행해야 합니다.

|===
| 원하는 작업 | 이 명령 사용... 


 a| 
모든 스케줄에 대한 정보를 표시합니다
 a| 
일자리스케줄 쇼



 a| 
일정별로 작업 목록을 표시합니다
 a| 
일자리일정=일자리다



 a| 
cron 일정에 대한 정보를 표시합니다
 a| 
작업 스케줄 cron 쇼



 a| 
간격 일정에 대한 정보를 표시합니다
 a| 
작업 일정 간격 표시



 a| 
cron 일정 ^1^을(를) 생성합니다
 a| 
작업 스케줄 cron 생성



 a| 
간격 일정을 만듭니다
 a| 
작업 일정 간격 만들기

일, 시간, 분, 초 중 하나 이상의 매개 변수를 지정해야 합니다.



 a| 
cron 일정을 수정합니다
 a| 
작업 스케줄 cron 수정



 a| 
간격 일정을 수정합니다
 a| 
작업 일정 간격 수정



 a| 
스케줄을 삭제합니다
 a| 
작업 일정 삭제



 a| 
cron 일정을 삭제합니다
 a| 
작업 스케줄 cron 삭제



 a| 
간격 일정을 삭제합니다
 a| 
작업 일정 간격 삭제

|===
^1^ ONTAP 9.10.1부터, 'job schedule cron create' 명령을 사용하여 작업 스케줄을 생성할 때 작업 스케줄의 SVM을 포함할 수 있습니다.

http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-cmpr/GUID-5CB10C70-AC11-41C0-8C16-B4D0DF916E9B.html["ONTAP 9 명령"]
