---
permalink: system-admin/commands-manage-sp-from-ontap-reference.html 
sidebar: sidebar 
keywords: command, manage, sp, ontap, network, configuration, firmware, image, ssh 
summary: ONTAP에서는 SP 네트워크 구성, SP 펌웨어 이미지, SP에 대한 SSH 액세스, 일반 SP 관리를 비롯한 SP 관리를 위한 명령을 제공합니다. 
---
= ONTAP에서 SP를 관리하는 명령입니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP에서는 SP 네트워크 구성, SP 펌웨어 이미지, SP에 대한 SSH 액세스, 일반 SP 관리를 비롯한 SP 관리를 위한 명령을 제공합니다.



== SP 네트워크 구성을 관리하는 명령입니다

|===
| 원하는 작업 | 이 ONTAP 명령 실행... 


 a| 
SP에서 지정된 서브넷의 IPv4 또는 IPv6 주소 제품군을 사용할 수 있도록 SP의 자동 네트워크 구성을 설정합니다
 a| 
'시스템 서비스 프로세서 네트워크 자동 구성 활성화



 a| 
SP에 대해 지정된 서브넷의 IPv4 또는 IPv6 주소 제품군에 대한 SP 자동 네트워크 구성을 해제합니다
 a| 
'시스템 서비스 프로세서 네트워크 자동 구성 비활성화



 a| 
SP의 자동 네트워크 구성을 표시합니다
 a| 
'시스템 서비스 프로세서 네트워크 자동 구성 표시



 a| 
다음을 포함하여 노드에 대해 SP 네트워크를 수동으로 구성합니다.

* IP 주소 제품군(IPv4 또는 IPv6)
* 지정된 IP 주소 제품군의 네트워크 인터페이스를 사용할지 여부를 나타냅니다
* IPv4를 사용하는 경우 DHCP 서버의 네트워크 구성을 사용할지 또는 지정하는 네트워크 주소를 사용할지 여부를 지정합니다
* SP의 공용 IP 주소입니다
* SP의 넷마스크(IPv4를 사용하는 경우)
* SP에 대한 서브넷 마스크의 네트워크 접두사-길이(IPv6를 사용하는 경우)
* SP의 게이트웨이 IP 주소입니다

 a| 
'시스템 서비스 프로세서 네트워크 수정



 a| 
다음을 포함하여 SP 네트워크 구성을 표시합니다.

* 구성된 주소 패밀리(IPv4 또는 IPv6) 및 설정 여부
* 원격 관리 장치 유형입니다
* 현재 SP 상태 및 링크 상태입니다
* IP 주소, MAC 주소, 넷마스크, 서브넷 마스크의 접두사-길이, 라우터 할당 IP 주소, 링크 로컬 IP 주소 및 게이트웨이 IP 주소와 같은 네트워크 구성
* SP가 마지막으로 업데이트된 시간입니다
* SP 자동 구성에 사용되는 서브넷의 이름입니다
* IPv6 라우터 할당 IP 주소의 활성화 여부이다
* SP 네트워크 설정 상태입니다
* SP 네트워크 설정 실패 이유

 a| 
'시스템 서비스 프로세서 네트워크 쇼'

SP 네트워크 세부 정보를 모두 표시하려면 '-instance' 매개 변수가 필요합니다.



 a| 
다음을 포함하여 SP API 서비스 구성을 수정합니다.

* SP API 서비스에서 사용하는 포트를 변경하는 중입니다
* SP API 서비스 설정 또는 해제

 a| 
'시스템 서비스 프로세서 API 서비스 수정

(고급 권한 레벨)



 a| 
SP API 서비스 구성을 표시합니다
 a| 
'시스템 서비스 프로세서 API 서비스 쇼'

(고급 권한 레벨)



 a| 
내부 통신을 위해 SP API 서비스에서 사용하는 SSL 및 SSH 인증서를 갱신합니다
 a| 
* ONTAP 9.5 이상: '시스템 서비스 - 프로세서 API - 서비스 갱신 - 내부 - 인증서
* ONTAP 9.4 이하: '시스템 서비스 - 프로세서 API - 서비스 갱신 - 인증서'
+
(고급 권한 레벨)



|===


== SP 펌웨어 이미지를 관리하는 명령입니다

|===
| 원하는 작업 | 이 ONTAP 명령 실행... 


 a| 
다음을 포함하여 현재 설치된 SP 펌웨어 이미지의 세부 정보를 표시합니다.

* 원격 관리 장치 유형입니다
* SP가 부팅되는 이미지(운영 또는 백업), 상태 및 펌웨어 버전
* 펌웨어 자동 업데이트의 활성화 여부와 마지막 업데이트 상태

 a| 
'시스템 서비스 프로세서 이미지 쇼'

'-is-current' 매개 변수는 설치된 펌웨어 버전이 최신 버전이 아닌 현재 SP가 부팅된 이미지(운영 또는 백업)를 나타냅니다.



 a| 
SP 자동 펌웨어 업데이트를 사용하거나 사용하지 않도록 설정합니다
 a| 
'시스템 서비스 프로세서 이미지 수정

기본적으로 SP 펌웨어는 ONTAP를 업데이트하거나 새로운 버전의 SP 펌웨어를 수동으로 다운로드할 때 자동으로 업데이트됩니다. 자동 업데이트를 사용하지 않도록 설정하면 ONTAP 이미지와 SP 펌웨어 이미지 간에 최적화되지 않은 또는 비정규화된 조합이 발생할 수 있으므로 사용하지 않는 것이 좋습니다.



 a| 
노드에서 SP 펌웨어 이미지를 수동으로 다운로드합니다
 a| 
'시스템 노드 이미지 가져오기'

[NOTE]
====
'system node image' 명령어를 실행하기 전에, 진행하라는 메시지가 나타나면, 권한 수준을 advanced('set-Privilege advanced')로 설정하고, * y * 를 입력해야 한다.

====
SP 펌웨어 이미지는 ONTAP와 함께 패키지로 제공됩니다. ONTAP와 함께 제공된 것과 다른 SP 펌웨어 버전을 사용하려는 경우가 아니라면 SP 펌웨어를 수동으로 다운로드할 필요가 없습니다.



 a| 
다음 정보를 포함하여 ONTAP에서 트리거된 최신 SP 펌웨어 업데이트의 상태를 표시합니다.

* 최신 SP 펌웨어 업데이트의 시작 및 종료 시간입니다
* 업데이트가 진행 중인지 여부 및 완료율을 나타냅니다

 a| 
'시스템 서비스 프로세서 이미지 업데이트 - 진행률 표시

|===


== SP에 대한 SSH 액세스를 관리하는 명령입니다

|===
| 원하는 작업 | 이 ONTAP 명령 실행... 


 a| 
지정된 IP 주소에만 SP 액세스 권한을 부여합니다
 a| 
'시스템 서비스 프로세서 ssh add-allowed-address'



 a| 
지정된 IP 주소가 SP에 액세스하지 못하도록 차단합니다
 a| 
'시스템 서비스 프로세서 ssh remove-allowed-address'



 a| 
SP에 액세스할 수 있는 IP 주소를 표시합니다
 a| 
'시스템 서비스 프로세서 ssh show'

|===


== 일반 SP 관리를 위한 명령입니다

|===
| 원하는 작업 | 이 ONTAP 명령 실행... 


 a| 
다음을 비롯한 일반 SP 정보를 표시합니다.

* 원격 관리 장치 유형입니다
* 현재 SP 상태입니다
* SP 네트워크가 구성되었는지 여부를 나타냅니다
* 공용 IP 주소 및 MAC 주소와 같은 네트워크 정보
* SP 펌웨어 버전과 IPMI(Intelligent Platform Management Interface) 버전입니다
* SP 펌웨어 자동 업데이트가 설정되었는지 여부를 나타냅니다

 a| 
'system service-processor show' SP의 전체 정보를 표시하려면 -instance 매개변수가 필요합니다.



 a| 
노드에서 SP를 재부팅합니다
 a| 
'시스템 서비스 프로세서 재부팅 - SP'



 a| 
지정된 노드에서 수집된 SP 로그 파일을 포함하는 AutoSupport 메시지를 생성하고 전송합니다
 a| 
'시스템 노드 AutoSupport invoke-splog'



 a| 
각 수집 노드에 있는 SP 로그 파일의 시퀀스 번호를 포함하여 클러스터에서 수집된 SP 로그 파일의 할당 맵을 표시합니다
 a| 
'시스템 서비스 프로세서 로그 show-allocaiton

|===
.관련 정보
http://["ONTAP 9 명령"^]
