---
permalink: system-admin/configure-saml-authentication-task.html 
sidebar: sidebar 
keywords: tdp, ldap, identity, provider, saml, security, assertion, markup, lanaguage, active, directory, disable, authentication, idp, active directory, troubleshoot, repair 
summary: 'ONTAP 9.3부터 웹 서비스에 대한 SAML(Security Assertion Markup Language) 인증을 구성할 수 있습니다. SAML 인증이 구성 및 설정되면 사용자는 Active Directory 및 LDAP와 같은 디렉터리 서비스 공급자 대신 외부 ID 공급자(IDP)에 의해 인증됩니다. SAML 인증이 비활성화되면 Active Directory 및 LDAP와 같이 구성된 디렉터리 서비스 공급자가 인증에 사용됩니다.' 
---
= SAML 인증을 구성합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9.3부터 웹 서비스에 대한 SAML(Security Assertion Markup Language) 인증을 구성할 수 있습니다. SAML 인증이 구성 및 설정되면 사용자는 Active Directory 및 LDAP와 같은 디렉터리 서비스 공급자 대신 외부 ID 공급자(IDP)에 의해 인증됩니다.

.필요한 것
* SAML 인증을 위해 IDP를 구성해야 합니다.
* IDP URI가 있어야 합니다.


.이 작업에 대해
* SAML 인증은 'http' 및 'ontapi' 애플리케이션에만 적용됩니다.
+
http와 ontapi 애플리케이션은 서비스 프로세서 인프라, ONTAP API, System Manager 등의 웹 서비스에서 사용됩니다.

* SAML 인증은 관리 SVM에 액세스하는 경우에만 적용됩니다.


다음 IdP는 System Manager에서 검증되었습니다.

* Active Directory 페더레이션 서비스
* Cisco Duo(다음 ONTAP 버전에서 검증:)
+
** 9.7P21 이상 9.7 릴리즈(참조 https://docs.netapp.com/us-en/ontap-sm-classic/online-help-96-97/task_setting_up_saml_authentication.html["System Manager Classic 설명서"^])
** 9.8P17 이상 9.8 릴리스
** 9.9.1P13 이상 9.9 릴리스
** 9.10.1P9 이상 9.10 릴리스
** 9.11.1P4 이상 9.11 릴리즈
** 9.12.1 이상 릴리즈


* 시바볼레스


.단계
. SAML 구성을 생성하여 ONTAP가 IDP 메타데이터에 액세스할 수 있도록 합니다.
+
'* security SAML-SP create-IDP-Uri_IDP_Uri_-sp-host_ontap_host_name_ * '

+
IDP_Uri는 IDP 메타데이터를 다운로드할 수 있는 IDP 호스트의 FTP 또는 HTTP 주소입니다.

+
'ontap_host_name'은 SAML 서비스 공급자 호스트의 호스트 이름 또는 IP 주소이며, 이 경우 ONTAP 시스템입니다. 기본적으로 클러스터 관리 LIF의 IP 주소가 사용됩니다.

+
ONTAP 서버 인증서 정보를 선택적으로 제공할 수 있습니다. 기본적으로 ONTAP 웹 서버 인증서 정보가 사용됩니다.

+
[listing]
----
cluster_12::> security saml-sp create -idp-uri https://scspr0235321001.gdl.englab.netapp.com/idp/shibboleth -verify-metadata-server false

Warning: This restarts the web server. Any HTTP/S connections that are active
         will be disrupted.
Do you want to continue? {y|n}: y
[Job 179] Job succeeded: Access the SAML SP metadata using the URL:
https://10.63.56.150/saml-sp/Metadata

Configure the IdP and Data ONTAP users for the same directory server domain to ensure that users are the same for different authentication methods. See the "security login show" command for the Data ONTAP user configuration.
----
+
ONTAP 호스트 메타데이터에 액세스할 수 있는 URL이 표시됩니다.

. IDP 호스트에서 ONTAP 호스트 메타데이터를 사용하여 IDP를 구성합니다.
+
IDP 구성에 대한 자세한 내용은 IDP 설명서를 참조하십시오.

. SAML 구성 활성화:
+
'* security SAML-SP modify -is-enabled true*'

+
'http' 또는 'ontapi' 애플리케이션에 액세스하는 기존 사용자는 자동으로 SAML 인증을 위해 구성됩니다.

. SAML이 구성된 후 'http' 또는 'ontapi' 애플리케이션에 대한 사용자를 생성하려면 SAML을 새 사용자의 인증 방법으로 지정합니다.
+
.. SAML 인증을 사용하여 새 사용자에 대한 로그인 방법을 생성합니다. + `* 보안 로그인 create-user-or-group-name_user_name_-application [http|ontapi] -authentication-method SAML-vserver_svm_name_ * '
+
[listing]
----
cluster_12::> security login create -user-or-group-name admin1 -application http -authentication-method saml -vserver  cluster_12
----
.. 사용자 항목이 생성되었는지 확인합니다.
+
'* 보안 로그인 쇼 * '

+
[listing]
----
cluster_12::> security login show

Vserver: cluster_12
                                                                 Second
User/Group                 Authentication                 Acct   Authentication
Name           Application Method        Role Name        Locked Method
-------------- ----------- ------------- ---------------- ------ --------------
admin          console     password      admin            no     none
admin          http        password      admin            no     none
admin          http        saml          admin            -      none
admin          ontapi      password      admin            no     none
admin          ontapi      saml          admin            -      none
admin          service-processor
                           password      admin            no     none
admin          ssh         password      admin            no     none
admin1         http        password      backup           no     none
**admin1       http        saml          backup           -      none**
----






== SAML 인증을 비활성화합니다

외부 ID 공급자(IDP)를 사용하여 웹 사용자 인증을 중지하려면 SAML 인증을 사용하지 않도록 설정할 수 있습니다. SAML 인증이 비활성화되면 Active Directory 및 LDAP와 같이 구성된 디렉터리 서비스 공급자가 인증에 사용됩니다.

.필요한 것
콘솔에서 로그인해야 합니다.

.단계
. SAML 인증 비활성화:
+
'* security SAML-SP modify -is-enabled false * '

. SAML 인증을 더 이상 사용하지 않거나 IDP를 수정하려는 경우 SAML 구성을 삭제합니다.
+
'* 보안 SAML-SP 삭제 * '





== SAML 구성 관련 문제를 해결합니다

SAML(Security Assertion Markup Language) 인증을 구성하지 못한 경우 SAML 구성이 실패한 각 노드를 수동으로 복구하고 장애를 복구할 수 있습니다. 복구 프로세스 중에 웹 서버가 다시 시작되고 활성 HTTP 연결 또는 HTTPS 연결이 중단됩니다.

.이 작업에 대해
SAML 인증을 구성할 경우 ONTAP는 노드별로 SAML 구성을 적용합니다. SAML 인증을 설정하면 구성 문제가 있는 경우 ONTAP에서 자동으로 각 노드를 복구하려고 시도합니다. 노드에서 SAML 구성에 문제가 있는 경우 SAML 인증을 비활성화한 다음 SAML 인증을 다시 활성화할 수 있습니다. SAML 인증을 다시 설정한 후에도 하나 이상의 노드에 SAML 구성이 적용되지 않는 경우가 있을 수 있습니다. SAML 구성이 실패한 노드를 확인한 다음 해당 노드를 수동으로 복구할 수 있습니다.

.단계
. 고급 권한 레벨에 로그인합니다.
+
' * set-Privilege advanced * '

. SAML 구성이 실패한 노드 식별:
+
' * security SAML-SP status show-instance * '

+
[listing]
----
cluster_12::*> security saml-sp status show -instance

                         Node: node1
                Update Status: config-success
               Database Epoch: 9
   Database Transaction Count: 997
                   Error Text:
SAML Service Provider Enabled: false
        ID of SAML Config Job: 179

                         Node: node2
                Update Status: config-failed
               Database Epoch: 9
   Database Transaction Count: 997
                   Error Text: SAML job failed, Reason: Internal error. Failed to receive the SAML IDP Metadata file.
SAML Service Provider Enabled: false
        ID of SAML Config Job: 180
2 entries were displayed.
----
. 장애가 발생한 노드에서 SAML 구성을 복구합니다.
+
'* security SAML-SP repair-node_node_name_ * '

+
[listing]
----
cluster_12::*> security saml-sp repair -node node2

Warning: This restarts the web server. Any HTTP/S connections that are active
         will be disrupted.
Do you want to continue? {y|n}: y
[Job 181] Job is running.
[Job 181] Job success.
----
+
웹 서버가 다시 시작되고 활성화된 HTTP 연결 또는 HTTPS 연결이 모두 중단됩니다.

. 모든 노드에서 SAML이 구성되었는지 확인합니다.
+
' * security SAML-SP status show-instance * '

+
[listing]
----
cluster_12::*> security saml-sp status show -instance

                         Node: node1
                Update Status: config-success
               Database Epoch: 9
   Database Transaction Count: 997
                   Error Text:
SAML Service Provider Enabled: false
        ID of SAML Config Job: 179

                         Node: node2
                Update Status: **config-success**
               Database Epoch: 9
   Database Transaction Count: 997
                   Error Text:
SAML Service Provider Enabled: false
        ID of SAML Config Job: 180
2 entries were displayed.
----


.관련 정보
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-cmpr/GUID-5CB10C70-AC11-41C0-8C16-B4D0DF916E9B.html["ONTAP 9 명령"^]
