---
permalink: system-admin/configure-discovery-cluster-management-switches-task.html 
sidebar: sidebar 
keywords: configuring, discovery, cluster, management, network, switches, cisco, discovery, protocol, cdp, switch, health 
summary: '클러스터 스위치 상태 모니터는 CDP(Cisco Discovery Protocol)를 사용하여 클러스터 및 관리 네트워크 스위치를 자동으로 검색합니다. 스위치를 자동으로 검색할 수 없거나 자동 검색에 CDP를 사용하지 않으려는 경우 상태 모니터를 구성해야 합니다.' 
---
= 클러스터 및 관리 네트워크 스위치 검색을 구성합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
클러스터 스위치 상태 모니터는 CDP(Cisco Discovery Protocol)를 사용하여 클러스터 및 관리 네트워크 스위치를 자동으로 검색합니다. 스위치를 자동으로 검색할 수 없거나 자동 검색에 CDP를 사용하지 않으려는 경우 상태 모니터를 구성해야 합니다.

'system cluster-switch show' 명령은 상태 모니터가 검색한 스위치를 나열합니다. 목록에 표시할 스위치가 없는 경우 상태 모니터에서 스위치를 자동으로 검색할 수 없습니다.

.단계
. 자동 검색에 CDP를 사용하려면 다음을 수행합니다. 그렇지 않으면 단계로 이동합니다 ,2:
+
.. 스위치에서 CDP(Cisco Discovery Protocol)가 활성화되어 있는지 확인합니다.
+
자세한 내용은 스위치 설명서를 참조하십시오.

.. 클러스터의 각 노드에서 다음 명령을 실행하여 CDP가 설정되어 있는지 여부를 확인합니다.
+
'* run-node_node_name_ - 명령 옵션 CDPD.enable *

+
CDP가 활성화된 경우 d 단계로 이동합니다 CDP가 비활성화되어 있으면 c 단계로 이동합니다

.. CDP를 사용하도록 설정하려면 다음 명령을 실행합니다.
+
' * run-node_node_name_ - 명령 옵션 CDPD.enable on * '

+
5분 정도 기다린 후 다음 단계로 이동합니다.

.. 'system cluster-switch show' 명령을 사용하여 ONTAP가 이제 스위치를 자동으로 검색할 수 있는지 확인합니다.


. 상태 모니터가 스위치를 자동으로 검색할 수 없는 경우 'system cluster-switch create' 명령을 사용하여 스위치 검색을 구성합니다.
+
[listing]
----
cluster1::> system cluster-switch create -device switch1 -address 192.0.2.250 -snmp-version SNMPv2c -community cshm1! -model NX5020 -type cluster-network
----
+
5분 정도 기다린 후 다음 단계로 이동합니다.

. 'system cluster-switch show' 명령을 사용하여 ONTAP에서 정보를 추가한 스위치를 검색할 수 있는지 확인합니다.


상태 모니터에서 스위치를 모니터링할 수 있는지 확인합니다.
