---
permalink: system-admin/create-motd-task.html 
sidebar: sidebar 
keywords: create, motd, cli, user, clustershell, ssh, session, cluster, access, message, day 
summary: 'MOTD(오늘의 메시지)를 생성하여 인증된 CLI 사용자에게 정보를 전달할 수 있습니다. MOTD는 사용자를 인증한 후 클러스터 셸 프롬프트가 나타나기 전에 콘솔 세션(클러스터 액세스만 해당) 또는 SSH 세션(클러스터 또는 SVM 액세스용)에 표시됩니다.' 
---
= MOTD를 생성합니다
:icons: font
:imagesdir: ../media/


[role="lead"]
MOTD(오늘의 메시지)를 생성하여 인증된 CLI 사용자에게 정보를 전달할 수 있습니다. MOTD는 사용자를 인증한 후 클러스터 셸 프롬프트가 나타나기 전에 콘솔 세션(클러스터 액세스만 해당) 또는 SSH 세션(클러스터 또는 SVM 액세스용)에 표시됩니다.

.단계
. 'security login mtd modify' 명령을 사용하여 클러스터 또는 SVM에 대한 MOTD를 생성합니다.
+
|===
| 원하는 작업 | 그러면... 


 a| 
한 줄인 메시지를 지정합니다
 a| 
텍스트를 지정하려면 "- message "[.code]""text"" 매개 변수를 사용합니다.



 a| 
줄 바꿈 포함(줄 끝이라고도 함)
 a| 
MOTD 편집을 위한 대화형 모드를 실행하려면 '-message' 또는 '-Uri' 매개 변수 없이 명령을 사용합니다.



 a| 
MOTD에 사용할 위치에서 콘텐츠를 업로드합니다
 a| 
'-Uri' 매개 변수를 사용하여 콘텐츠의 FTP 또는 HTTP 위치를 지정합니다.

|===
+
MOTD의 최대 크기는 새 행을 포함하여 2,048바이트입니다.

+
'보안 로그인 모트 수정' man 페이지는 MOTD가 동적으로 생성된 컨텐츠를 표시할 수 있도록 하는 데 사용할 수 있는 이스케이프 시퀀스를 설명합니다.

+
'-Uri' 파라미터를 사용하여 만든 MOTD는 정적입니다. 소스 콘텐츠의 후속 변경 사항을 반영하기 위해 자동으로 새로 고쳐지지 않습니다.

+
클러스터를 위해 생성된 MOTD는 기본적으로 모든 SVM 로그인을 위해 표시되며, SVM 레벨의 MOTD를 통해 특정 SVM에 대해 별도로 생성할 수 있습니다. SVM에 대해 '-is-cluster-message-enabled' 매개 변수를 'false'로 설정하면 해당 SVM에 대해 클러스터 레벨 MOTD가 표시되지 않습니다.

. MOTD를 'security login mott show' 명령으로 출력하여 생성했는지 확인한다.
+
빈 문자열(""")로 '-message' 매개 변수를 지정하면 구성되지 않았거나 내용이 없는 MOD가 표시됩니다.

+
를 참조하십시오 https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-cmpr-980/security%5F%5Flogin%5F%5Fmotd%5F%5Fmodify.html["보안 로그인 motd 수정"] MOTD에서 동적으로 생성된 콘텐츠를 표시하는 데 사용할 매개 변수 목록을 표시하는 명령 맨 페이지입니다. ONTAP 버전에 해당하는 man 페이지를 확인하십시오.



다음 예제에서는 비대화형 모드를 사용하여 ""cluster1" 클러스터에 대한 MOTD를 만듭니다.

[listing]
----
cluster1::> security login motd modify -message "Greetings!"
----
다음 예에서는 대화형 모드를 사용하여 탈출 시퀀스를 사용하여 동적으로 생성된 컨텐츠를 표시하는 "스vm1" SVM에 MOTD를 생성합니다.

[listing]
----
cluster1::> security login motd modify -vserver svm1

Enter the message of the day for Vserver "svm1".
Max size: 2048. Enter a blank line to terminate input. Press Ctrl-C to abort.
0        1         2         3         4         5         6         7         8
12345678901234567890123456789012345678901234567890123456789012345678901234567890
Welcome to the \n SVM.  Your user ID is '\N'. Your last successful login was \L.
----
다음 예는 생성된 MOD를 표시합니다.

[listing]
----
cluster1::> security login motd show
Vserver: cluster1
Is the Cluster MOTD Displayed?: true
Message
-----------------------------------------------------------------------------
Greetings!

Vserver: svm1
Is the Cluster MOTD Displayed?: true
Message
-----------------------------------------------------------------------------
Welcome to the \n SVM.  Your user ID is '\N'. Your last successful login was \L.

2 entries were displayed.
----