---
permalink: system-admin/enable-telnet-rsh-access-cluster-task.html 
sidebar: sidebar 
keywords: enable, telnet, rsh, access, cluster, mgmt, management, service, policy 
summary: 보안 모범 사례로 Telnet 및 RSH는 기본적으로 비활성화되어 있습니다. 클러스터가 텔넷 또는 RSH 요청을 수락하도록 하려면 기본 관리 서비스 정책에서 서비스를 사용하도록 설정해야 합니다. 
---
= 클러스터에 대한 Telnet 또는 RSH 액세스를 활성화합니다
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
보안 모범 사례로 Telnet 및 RSH는 기본적으로 비활성화되어 있습니다. 클러스터가 텔넷 또는 RSH 요청을 수락하도록 하려면 기본 관리 서비스 정책에서 서비스를 사용하도록 설정해야 합니다.

.이 작업에 대해
* RSH는 보안 프로토콜이 아닙니다.
+
SSH를 사용하여 클러스터에 액세스하는 것을 고려해야 합니다. SSH는 보안 원격 셸 및 대화형 네트워크 세션을 제공합니다.

* ONTAP는 노드당 최대 50개의 동시 RSH 세션을 지원한다.
+
클러스터 관리 LIF가 노드에 상주하는 경우 이 제한을 노드 관리 LIF와 공유합니다.

+
들어오는 연결의 비율이 초당 10보다 높을 경우 서비스가 60초 동안 일시적으로 비활성화됩니다.

* RSH 명령에는 고급 권한이 필요합니다.


.단계
. RSH 또는 텔넷 보안 프로토콜이 활성화되어 있는지 확인합니다.
+
`security protocol show`

+
.. RSH 또는 텔넷 보안 프로토콜이 활성화된 경우 다음 단계를 계속 진행하십시오.
.. RSH 또는 텔넷 보안 프로토콜이 활성화되지 않은 경우 다음 명령을 사용하여 활성화하십시오.
+
`security protocol modify -application <rsh/telnet> -enabled true`



. 관리 LIF에 또는 서비스가 있는지 확인 `management-rsh-server` `management-telnet-server` :
+
`network interface show -services management-rsh-server`

+
또는

+
`network interface show -services management-telnet-server`

+
.. 또는 서비스가 있는 경우 `management-rsh-server` `management-telnet-server` 다음 단계를 계속합니다.
.. 또는 서비스가 없는 경우 `management-rsh-server` `management-telnet-server` 다음 명령을 사용하여 서비스를 추가합니다.
+
`network interface service-policy add-service -vserver cluster1 -policy default-management -service management-rsh-server`

+
`network interface service-policy add-service -vserver cluster1 -policy default-management -service management-telnet-server`




