---
permalink: system-admin/enable-telnet-rsh-access-cluster-task.html 
sidebar: sidebar 
keywords: enable, telnet, rsh, access, cluster, mgmt, management, firewall, policy 
summary: '최선의 보안 방법으로, 텔넷 및 RSH는 미리 정의된 관리 방화벽 정책(관리)에서 비활성화됩니다. 클러스터가 텔넷 또는 RSH 요청을 수락하도록 설정하려면 텔넷 또는 RSH가 설정된 새 관리 방화벽 정책을 생성한 다음 새 정책을 클러스터 관리 LIF와 연결해야 합니다.' 
---
= 클러스터에 대한 Telnet 또는 RSH 액세스를 활성화합니다
:icons: font
:imagesdir: ../media/


[role="lead"]
최선의 보안 방법으로, Telnet과 RSH는 미리 정의된 관리 방화벽 정책(mGMT)에서 비활성화됩니다. 클러스터가 텔넷 또는 RSH 요청을 수락하도록 설정하려면 텔넷 또는 RSH가 설정된 새 관리 방화벽 정책을 생성한 다음 새 정책을 클러스터 관리 LIF와 연결해야 합니다.

ONTAP는 미리 정의된 방화벽 정책을 변경하지 못하도록 하지만 미리 정의된 "GMT" 관리 방화벽 정책을 복제한 다음 새 정책에서 텔넷 또는 RSH를 활성화하여 새 정책을 만들 수 있습니다. 그러나 Telnet과 RSH는 보안 프로토콜이 아니므로 SSH를 사용하여 클러스터에 액세스하는 것을 고려해야 합니다. SSH는 보안 원격 셸 및 대화형 네트워크 세션을 제공합니다.

클러스터에 대한 텔넷 또는 RSH 액세스를 활성화하려면 다음 단계를 수행하십시오.

.단계
. 고급 권한 모드로 들어갑니다.
+
' * SET ADVANCED * '

. 보안 프로토콜 활성화(RSH 또는 Telnet):
+
'* 보안 프로토콜 수정 - application_security_protocol_-enabled true*'

. "GMT" 관리 방화벽 정책을 기반으로 새 관리 방화벽 정책을 생성합니다.
+
'* 시스템 서비스 방화벽 정책 클론-정책 관리-새-정책-이름_정책-이름_*'

. 새 관리 방화벽 정책에서 텔넷 또는 RSH를 활성화합니다.
+
'* 시스템 서비스 방화벽 정책 create-policy_policy-name_-service_security_protocol_-action allow-ip-list_ip_address/netmask_*'

+
모든 IP 주소를 허용하려면 '-ip-list 0.0.0.0/0'을 지정해야 합니다

. 새 정책을 클러스터 관리 LIF와 연결합니다.
+
'* 네트워크 인터페이스 수정 - vserver_cluster_management_LIF_-lif cluster_mgmt-firewall-policy_policy-name_ *


