---
permalink: system-admin/find-config-recover-cluster-task.html 
sidebar: sidebar 
keywords: cluster, configuration, recover, node, backup, file 
summary: 클러스터의 노드 또는 클러스터 구성 백업 파일의 구성을 사용하여 클러스터를 복구할 수 있습니다. 
---
= 클러스터 복구에 사용할 구성을 찾습니다
:icons: font
:imagesdir: ../media/


[role="lead"]
클러스터의 노드 또는 클러스터 구성 백업 파일의 구성을 사용하여 클러스터를 복구할 수 있습니다.

.단계
. 클러스터를 복구할 구성 유형을 선택합니다.
+
** 클러스터의 노드
+
클러스터가 둘 이상의 노드로 구성되어 있고 노드 중 하나에 클러스터가 원하는 구성에 있을 때의 클러스터 구성이 있는 경우, 해당 노드에 저장된 구성을 사용하여 클러스터를 복구할 수 있습니다.

+
대부분의 경우 가장 최근의 트랜잭션 ID가 있는 복제 링이 포함된 노드는 클러스터 구성을 복구하는 데 가장 적합한 노드입니다. 고급 권한 레벨의 'cluster ring show' 명령을 사용하면 클러스터의 각 노드에서 사용할 수 있는 복제된 링 목록을 볼 수 있습니다.

** 클러스터 구성 백업 파일
+
올바른 클러스터 구성의 노드를 식별할 수 없거나 클러스터가 단일 노드로 구성된 경우 클러스터 구성 백업 파일을 사용하여 클러스터를 복구할 수 있습니다.

+
구성 백업 파일에서 클러스터를 복구하려면 복구 노드에 있는 백업과 클러스터 구성 간의 불일치를 해결하기 위해 진단 도구를 사용해야 할 수 있습니다. 따라서 구성 백업 파일을 사용하는 경우 기술 지원 부서에 문의해야 합니다.



. 클러스터 구성 백업 파일을 사용하도록 선택한 경우, 클러스터 복구에 사용할 노드에서 해당 파일을 사용할 수 있도록 설정합니다.
+
|===
| 구성 백업 파일이 있는 경우... | 그러면... 


 a| 
원격 URL에서
 a| 
고급 권한 레벨의 '시스템 구성 백업 다운로드' 명령을 사용하여 복구 노드로 다운로드합니다.



 a| 
클러스터에 있는 노드
 a| 
.. 고급 권한 레벨의 'system configuration backup show' 명령을 사용하여 클러스터가 원하는 구성에 있을 때 생성된 클러스터 구성 백업 파일을 찾습니다.
.. 클러스터 구성 백업 파일이 클러스터 복구에 사용할 노드에 없으면 'system configuration backup copy' 명령을 사용하여 복구 노드에 복사합니다.


|===

