---
permalink: system-admin/health-monitors-concept.html 
sidebar: sidebar 
keywords: available, cluster, health, monitors, errors, detect, events, alerts, delete 
summary: 클러스터의 여러 부분을 모니터링하는 상태 모니터가 여러 개 있습니다. 상태 모니터는 이벤트를 감지하고, 사용자에게 경고를 보내고, 이벤트를 삭제하여 ONTAP 시스템 내의 오류를 복구할 수 있도록 도와줍니다. 
---
= 사용 가능한 클러스터 상태 모니터
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
클러스터의 여러 부분을 모니터링하는 상태 모니터가 여러 개 있습니다. 상태 모니터는 이벤트를 감지하고, 사용자에게 경고를 보내고, 이벤트를 삭제하여 ONTAP 시스템 내의 오류를 복구할 수 있도록 도와줍니다.

|===
| 상태 모니터 이름(식별자) | 하위 시스템 이름(식별자) | 목적 


 a| 
클러스터 스위치(클러스터 스위치)
 a| 
스위치(스위치 - 상태)
 a| 
클러스터 네트워크 스위치 및 관리 네트워크 스위치에서 온도, 사용률, 인터페이스 구성, 이중화(클러스터 네트워크 스위치만 해당) 및 팬 및 전원 공급 장치 작동을 모니터링합니다. 클러스터 스위치 상태 모니터는 SNMP를 통해 스위치와 통신합니다. SNMPv2c가 기본 설정입니다.

[NOTE]
====
ONTAP 9.2부터는 이 모니터가 마지막 폴링 기간 이후 클러스터 스위치가 재부팅된 경우를 감지하여 보고할 수 있습니다.

====


 a| 
MetroCluster 패브릭
 a| 
스위치
 a| 
MetroCluster 구성 백엔드 Fabric 토폴로지를 모니터링하고 잘못된 케이블 연결 및 조닝, ISL 장애 등의 잘못된 구성을 감지합니다.



 a| 
MetroCluster 상태
 a| 
상호 연결, RAID 및 스토리지
 a| 
FC-VI 어댑터, FC 이니시에이터 어댑터, 좌측 애그리게이트 및 디스크, 클러스터 간 포트를 모니터링합니다



 a| 
노드 연결(노드 연결)
 a| 
CIFS 무중단 운영(CIFS-NDO)
 a| 
SMB 연결을 모니터링하여 Hyper-V 애플리케이션의 무중단 운영을 지원합니다.



 a| 
스토리지(SAS-connect)
 a| 
노드 레벨에서 쉘프, 디스크, 어댑터를 모니터링하여 적절한 경로와 연결을 설정합니다.



 a| 
시스템
 a| 
해당 없음
 a| 
다른 상태 모니터의 정보를 집계합니다.



 a| 
시스템 연결(시스템 연결)
 a| 
스토리지(SAS-connect)
 a| 
2개의 HA 클러스터 노드에 대한 적절한 경로에 대해 클러스터 레벨의 쉘프를 모니터링합니다.

|===