---
permalink: system-admin/install-ca-signed-server-certificate-cluster-task.html 
sidebar: sidebar 
keywords: install, ca, signed, server, certificate, cluster, ssl, svm, sotrage, virtual, machine, administrator 
summary: 'SSL 서버에서 클러스터 또는 SVM(Storage Virtual Machine)을 SSL 클라이언트로 인증할 수 있도록 하려면 클러스터 또는 SVM에 클라이언트 유형과 함께 디지털 인증서를 설치합니다. 그런 다음 서버에 설치하기 위해 SSL 서버 관리자에게 클라이언트-CA 인증서를 제공합니다.' 
---
= 클러스터에 대한 CA 서명 서버 인증서를 설치합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SSL 서버에서 클러스터 또는 SVM(Storage Virtual Machine)을 SSL 클라이언트로 인증할 수 있도록 하려면 클러스터 또는 SVM에 클라이언트 유형과 함께 디지털 인증서를 설치합니다. 그런 다음 서버에 설치하기 위해 SSL 서버 관리자에게 클라이언트-CA 인증서를 제공합니다.

.필요한 것
SSL 서버의 루트 인증서를 이미 클러스터 또는 SVM에 'server-ca' 인증서 유형으로 설치해야 합니다.

.단계
. 클라이언트 인증에 자체 서명된 디지털 인증서를 사용하려면 type client 매개 변수를 사용하여 Security certificate create 명령을 사용합니다.
. 클라이언트 인증에 CA 서명 디지털 인증서를 사용하려면 다음 단계를 수행하십시오.
+
.. 보안 인증서 'generate-csr' 명령을 사용하여 디지털 인증서 서명 요청(CSR)을 생성합니다.
+
ONTAP는 인증서 요청과 개인 키가 포함된 CSR 출력을 표시하고 나중에 참조할 수 있도록 출력을 파일로 복사하도록 알려 줍니다.

.. 전자 양식(예: 전자 메일)으로 CSR 출력에서 인증서 요청을 신뢰할 수 있는 CA로 보내 서명합니다.
+
나중에 참조할 수 있도록 개인 키와 CA 서명 인증서의 복사본을 유지해야 합니다.

+
요청을 처리한 후 CA는 서명된 디지털 인증서를 보냅니다.

.. '-type client' 매개 변수와 함께 보안 인증서 설치 명령을 사용하여 CA 서명 인증서를 설치합니다.
.. 메시지가 표시되면 인증서와 개인 키를 입력한 다음 * Enter * 키를 누릅니다.
.. 메시지가 표시되면 추가 루트 또는 중간 인증서를 입력하고 * Enter * 를 누릅니다.
+
신뢰할 수 있는 루트 CA에서 시작하고 사용자에게 발급된 SSL 인증서로 끝나는 인증서 체인이 중간 인증서를 누락하는 경우 클러스터나 SVM에 중간 인증서를 설치합니다. 중간 인증서는 최종 엔터티 서버 인증서를 발급하기 위해 신뢰할 수 있는 루트에서 발급하는 하위 인증서입니다. 그 결과 신뢰할 수 있는 루트 CA에서 시작하여 중간 인증서를 거쳐 사용자에게 발급된 SSL 인증서로 끝나는 인증서 체인이 만들어집니다.



. 서버에 설치하기 위해 SSL 서버 관리자에게 클러스터 또는 SVM의 '클라이언트-CA' 인증서를 제공합니다.
+
인스턴스, 클라이언트-CA 형식의 매개 변수를 가진 보안 인증서 표시 명령은 클라이언트-CA 인증서 정보를 표시합니다.


