---
permalink: system-admin/keyboard-shortcuts-edit-cli-commands-reference.html 
sidebar: sidebar 
keywords: keyboard, shortcuts, edit, cli, commands, unix, tcsh, shell, emacs, editor, active 
summary: 현재 명령 프롬프트에 있는 명령은 활성 명령입니다. 바로 가기 키를 사용하면 활성 명령을 빠르게 편집할 수 있습니다. 이러한 바로 가기 키는 UNIX tcsh 셸 및 Emacs 편집기의 바로 가기와 유사합니다. 
---
= CLI 명령 편집을 위한 바로 가기 키
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
현재 명령 프롬프트에 있는 명령은 활성 명령입니다. 바로 가기 키를 사용하면 활성 명령을 빠르게 편집할 수 있습니다. 이러한 바로 가기 키는 UNIX tcsh 셸 및 Emacs 편집기의 바로 가기와 유사합니다.

다음 표에는 CLI 명령 편집을 위한 바로 가기 키가 나와 있습니다. ""Ctrl-""은 Ctrl 키를 누른 채 그 뒤에 지정된 문자를 입력함을 나타냅니다. "'Esc-'"는 Esc 키를 눌렀다 놓은 다음 그 뒤에 지정된 문자를 입력함을 나타냅니다.

|===
| 원하는 작업 | 다음 바로 가기 키 사용... 


 a| 
커서를 한 문자씩 뒤로 이동합니다
 a| 
Ctrl+B를 누릅니다



 a| 
뒤로 화살표



 a| 
커서를 한 문자씩 앞으로 이동합니다
 a| 
Ctrl + F



 a| 
앞으로 화살표



 a| 
커서를 한 단어씩 뒤로 이동합니다
 a| 
Esc-B를 누릅니다



 a| 
커서를 한 단어씩 앞으로 이동합니다
 a| 
Esc - F



 a| 
커서를 줄의 시작 부분으로 이동합니다
 a| 
Ctrl-A를 누릅니다



 a| 
커서를 줄의 끝으로 이동합니다
 a| 
Ctrl-E



 a| 
줄의 시작 부분에서 커서까지의 명령줄 내용을 제거하고 잘라낸 버퍼에 저장합니다. 잘라내기 버퍼는 일부 프로그램에서 _clipboard_라고 하는 것과 유사한 임시 메모리처럼 작동합니다.
 a| 
Ctrl+U



 a| 
커서에서 줄의 끝까지 명령줄의 내용을 제거하고 절단 버퍼에 저장합니다
 a| 
Ctrl+K를 누릅니다



 a| 
커서에서 다음 단어의 끝까지 명령줄 내용을 제거하고 절단 버퍼에 저장합니다
 a| 
Esc-D 를 누릅니다



 a| 
커서 앞에 있는 단어를 제거하고 잘라낸 버퍼에 저장합니다
 a| 
Ctrl+W



 a| 
절단 버퍼의 내용을 뱅킹하고 커서의 명령줄에 밀어 넣습니다
 a| 
Ctrl+Y



 a| 
커서 앞의 문자를 삭제합니다
 a| 
Ctrl + H



 a| 
백스페이스



 a| 
커서가 있는 문자를 삭제합니다
 a| 
Ctrl+D를 누릅니다



 a| 
선을 지웁니다
 a| 
Ctrl+C



 a| 
화면을 지웁니다
 a| 
Ctrl+L



 a| 
명령줄의 현재 내용을 기록 목록의 이전 항목으로 바꿉니다.

키보드 단축키를 반복할 때마다 기록 커서가 이전 항목으로 이동합니다.
 a| 
Ctrl+P



 a| 
Esc-P



 a| 
위쪽 화살표



 a| 
명령줄의 현재 내용을 기록 목록의 다음 항목으로 바꿉니다. 키보드 단축키를 반복할 때마다 기록 커서가 다음 항목으로 이동합니다.
 a| 
Ctrl+N



 a| 
Esc-N



 a| 
아래쪽 화살표



 a| 
부분적으로 입력한 명령을 확장하거나 현재 편집 위치에서 유효한 입력을 나열합니다
 a| 
탭을 클릭합니다



 a| 
Ctrl+I



 a| 
상황에 맞는 도움말을 표시합니다
 a| 
?



 a| 
물음표("?")에 대한 특별한 매핑 탈출 문자. 예를 들어, 명령 인수에 물음표를 입력하려면 Esc 키를 누른 다음 ""?""를 누르십시오. 문자.
 a| 
Esc-?



 a| 
TTY 출력을 시작합니다
 a| 
Ctrl-Q를 누릅니다



 a| 
TTY 출력을 중지합니다
 a| 
Ctrl+S

|===