---
permalink: system-admin/license-types-licensed-method-concept.html 
sidebar: sidebar 
keywords: license, types, method, cluster, manage, install, add, nlf 
summary: 라이센스 유형과 라이센스 방법을 이해하면 클러스터의 라이센스를 관리하는 데 도움이 됩니다. 
---
= 라이센스 유형 및 라이센스 방식
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
라이센스 유형과 라이센스 방법을 이해하면 클러스터의 라이센스를 관리하는 데 도움이 됩니다.



== 사용권 유형

패키지에는 다음 라이센스 유형 중 하나 이상이 클러스터에 설치될 수 있습니다. 'system license show' 명령은 설치된 패키지 라이센스 유형 또는 유형을 표시합니다.

* Standard 라이선스('라이선스')
+
표준 라이센스는 노드 잠김 라이센스입니다. 특정 시스템 일련 번호(_controller 일련 번호 _ 라고도 함)가 있는 노드에 대해 발행됩니다. 표준 라이센스는 일련 번호가 일치하는 노드에 대해서만 유효합니다.

+
표준 노드 잠금 라이센스를 설치하면 노드에 라이센스가 부여된 기능이 부여됩니다. 클러스터에 라이센스가 부여된 기능을 사용하려면 해당 기능에 대해 하나 이상의 노드에 라이센스가 있어야 합니다. 기능에 대한 사용 권한이 없는 노드에서 라이센스가 부여된 기능을 사용하지 못할 수 있습니다.

* 사이트 라이선스('사이트')
+
사이트 라이센스는 특정 시스템 일련 번호에 연결되지 않습니다. 사이트 라이센스를 설치하면 클러스터의 모든 노드에 라이센스가 부여된 기능이 부여됩니다. 'system license show' 명령은 클러스터 일련 번호 아래에 사이트 라이센스를 표시합니다.

+
클러스터에 사이트 라이센스가 있고 클러스터에서 노드를 제거할 경우 노드에 사이트 라이센스가 포함되지 않으며 라이센스가 부여된 기능을 더 이상 사용할 수 없습니다. 사이트 라이센스가 있는 클러스터에 노드를 추가하면 해당 노드는 사이트 라이센스에 의해 부여된 기능을 자동으로 사용할 수 있습니다.

* 평가판 라이센스(데모)
+
평가판은 일정 기간(system license show 명령으로 표시됨) 이후에 만료되는 임시 라이선스입니다. 이 기능을 사용하면 사용 권한을 구입하지 않고도 특정 소프트웨어 기능을 사용할 수 있습니다. 클러스터 전체 라이센스이며 노드의 특정 일련 번호에 연결되지 않습니다.

+
클러스터에 패키지에 대한 평가 라이센스가 있고 클러스터에서 노드를 제거하는 경우 노드에 평가판 라이센스가 포함되지 않습니다.





== 라이센스 방식

클러스터 전체 라이선스(사이트)와 노드 잠금 라이선스(라이선스 유형)를 모두 설치할 수 있다. 따라서 설치된 패키지에 클러스터에 여러 라이센스 유형이 있을 수 있습니다. 그러나 클러스터에는 패키지에 대해 하나의 _licensed 메소드_만 있습니다. system license status show 명령의 'licensed method' 필드에 패키지에 사용되는 권한이 표시됩니다. 명령은 다음과 같이 라이센스가 부여된 방법을 결정합니다.

* 패키지에 클러스터에 하나의 라이센스 유형만 설치되어 있는 경우 설치된 라이센스 유형이 라이센스 방식입니다.
* 패키지에 클러스터에 설치된 라이센스가 없는 경우 라이센스 부여 방법은 "없음"입니다.
* 패키지에 클러스터에 여러 개의 사용권 유형이 설치되어 있는 경우 사용권 유형은 '사이트', '사용권', '데모' 순으로 결정됩니다.
+
예를 들면 다음과 같습니다.

+
** 사이트 라이센스, 표준 라이센스 및 패키지 평가 라이센스가 있는 경우 클러스터의 패키지에 대한 라이센스 부여 방법은 '사이트'입니다.
** 패키지에 대한 표준 라이센스와 평가판 라이센스가 있는 경우 클러스터의 패키지에 대한 라이센스 방법은 "라이센스"입니다.
** 패키지에 대한 평가판 라이선스만 있는 경우 클러스터의 패키지에 대한 라이선스 방식은 '데모'입니다.



