---
permalink: system-admin/manage-web-services-concept.html 
sidebar: sidebar 
keywords: manage, web, services, svm, storage, virtual, machine, cluster, controler, user 
summary: '클러스터 또는 SVM(Storage Virtual Machine)에 대한 웹 서비스를 설정 또는 해제하고, 웹 서비스 설정을 표시하고, 역할 사용자가 웹 서비스에 액세스할 수 있는지 여부를 제어할 수 있습니다.' 
---
= 웹 서비스 관리 개요
:icons: font
:imagesdir: ../media/


[role="lead"]
클러스터 또는 SVM(Storage Virtual Machine)에 대한 웹 서비스를 설정 또는 해제하고, 웹 서비스 설정을 표시하고, 역할 사용자가 웹 서비스에 액세스할 수 있는지 여부를 제어할 수 있습니다.

다음과 같은 방법으로 클러스터 또는 SVM을 위한 웹 서비스를 관리할 수 있습니다.

* 특정 웹 서비스 활성화 또는 비활성화
* 웹 서비스에 대한 액세스가 암호화된 HTTP(SSL)로만 제한되는지 여부 지정
* 웹 서비스의 사용 가능 여부를 표시합니다
* 역할의 사용자가 웹 서비스에 액세스할 수 있도록 허용 또는 허용하지 않습니다
* 웹 서비스에 액세스할 수 있는 역할을 표시합니다


사용자가 웹 서비스에 액세스하려면 다음 조건을 모두 충족해야 합니다.

* 사용자를 인증해야 합니다.
+
예를 들어 웹 서비스에서 사용자 이름과 암호를 묻는 메시지가 표시될 수 있습니다. 사용자의 응답은 유효한 계정과 일치해야 합니다.

* 사용자는 올바른 액세스 방법을 사용하여 설정해야 합니다.
+
지정된 웹 서비스에 대해 올바른 액세스 방법을 사용하는 사용자에게만 인증이 성공합니다. ONTAP API 웹 서비스('ontapi')의 경우 사용자에게 "ontapi" 액세스 방법이 있어야 합니다. 다른 모든 웹 서비스의 경우 사용자는 http 액세스 방법을 가지고 있어야 합니다.

+
[NOTE]
====
'보안 로그인' 명령을 사용하여 사용자의 액세스 방법과 인증 방법을 관리할 수 있습니다.

====
* 사용자의 액세스 제어 역할을 허용하도록 웹 서비스를 구성해야 합니다.
+
[NOTE]
====
'vserver services web access' 명령을 사용하여 웹 서비스에 대한 역할의 액세스를 제어합니다.

====


방화벽이 설정된 경우 웹 서비스에 사용할 LIF의 방화벽 정책을 HTTP 또는 HTTPS를 허용하도록 설정해야 합니다.

웹 서비스 액세스에 HTTPS를 사용하는 경우, 웹 서비스를 제공하는 클러스터 또는 SVM에 SSL도 사용하도록 설정해야 하며 클러스터 또는 SVM에 대한 디지털 인증서를 제공해야 합니다.
