---
permalink: system-admin/manage-access-web-services-concept.html 
sidebar: sidebar 
keywords: 'manage, access, web, service, http, https, cluster, administrator, web, protocol, engine, ssl, role, api, ontapi, disco, supdiag, sysmgr, fw, bmc, docs, "docs_api", fud, ontapmsg, portal, rest, saml, backup, back up, security, csrf' 
summary: 웹 서비스는 사용자가 HTTP 또는 HTTPS를 사용하여 액세스할 수 있는 응용 프로그램입니다. 클러스터 관리자는 웹 프로토콜 엔진을 설정하고, SSL을 구성하고, 웹 서비스를 활성화하고, 역할의 사용자가 웹 서비스에 액세스할 수 있도록 할 수 있습니다. 
---
= 웹 서비스에 대한 액세스를 관리합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
웹 서비스는 사용자가 HTTP 또는 HTTPS를 사용하여 액세스할 수 있는 응용 프로그램입니다. 클러스터 관리자는 웹 프로토콜 엔진을 설정하고, SSL을 구성하고, 웹 서비스를 활성화하고, 역할의 사용자가 웹 서비스에 액세스할 수 있도록 할 수 있습니다.

ONTAP 9.6부터는 다음과 같은 웹 서비스가 지원됩니다.

* 서비스 프로세서 인프라('pi')
+
이 서비스에서는 클러스터 관리 LIF 또는 노드 관리 LIF를 통해 노드의 로그, 코어 덤프 및 MIB 파일을 HTTP 또는 HTTPS 액세스에 사용할 수 있습니다. 기본 설정은 "사용"입니다.

+
노드의 로그 파일 또는 코어 덤프 파일에 대한 액세스 요청이 있을 경우 'pi' 웹 서비스는 자동으로 노드에서 파일이 상주하는 다른 노드의 루트 볼륨으로 마운트 지점을 만듭니다. 마운트 지점을 수동으로 생성할 필요는 없습니다. "

* ONTAP API('ontapi')
+
이 서비스를 사용하면 ONTAP API를 실행하여 원격 프로그램으로 관리 기능을 실행할 수 있습니다. 기본 설정은 "사용"입니다.

+
일부 외부 관리 도구에 이 서비스가 필요할 수 있습니다. 예를 들어, System Manager를 사용하는 경우 이 서비스를 활성 상태로 유지해야 합니다.

* Data ONTAP 디스커버리(disco)
+
이 서비스를 사용하면 오프 박스 관리 애플리케이션이 네트워크에서 클러스터를 검색할 수 있습니다. 기본 설정은 "사용"입니다.

* 지원 진단('Support')
+
이 서비스는 시스템의 특별 권한 환경에 대한 액세스를 제어하여 문제 분석 및 해결을 지원합니다. 기본 설정은 사용 안 함 입니다. 기술 지원 부서의 지시가 있을 때만 이 서비스를 활성화해야 합니다.

* System Manager('smmgr')
+
이 서비스는 ONTAP에 포함된 System Manager의 가용성을 제어합니다. 기본 설정은 "사용"입니다. 이 서비스는 클러스터에서만 지원됩니다.

* 펌웨어 베이스보드 관리 컨트롤러(BMC) 업데이트('FW_BMC')
+
이 서비스를 사용하여 BMC 펌웨어 파일을 다운로드할 수 있습니다. 기본 설정은 "사용"입니다.

* ONTAP 문서(dOCS)
+
이 서비스를 통해 ONTAP 설명서에 액세스할 수 있습니다. 기본 설정은 "사용"입니다.

* ONTAP RESTful API(DOCS_API)
+
이 서비스를 통해 ONTAP RESTful API 설명서에 액세스할 수 있습니다. 기본 설정은 "사용"입니다.

* 파일 업로드 및 다운로드('FUD')
+
이 서비스는 파일 업로드 및 다운로드를 제공합니다. 기본 설정은 "사용"입니다.

* ONTAP 메시징('ontapmsg')
+
이 서비스는 이벤트에 등록할 수 있는 게시 및 구독 인터페이스를 지원합니다. 기본 설정은 "사용"입니다.

* ONTAP 포털('포털')
+
이 서비스는 게이트웨이를 가상 서버에 구현합니다. 기본 설정은 "사용"입니다.

* ONTAP Restful Interface(재차)
+
이 서비스는 클러스터 인프라의 모든 요소를 원격으로 관리하는 데 사용되는 RESTful 인터페이스를 지원합니다. 기본 설정은 "사용"입니다.

* SAML(Security Assertion Markup Language) 서비스 공급자 지원(SAML)
+
이 서비스는 SAML 서비스 공급자를 지원하는 리소스를 제공합니다. 기본 설정은 "사용"입니다.

* SAML 서비스 공급자(SML-SP)
+
이 서비스는 SP 메타데이터 및 어설션 소비자 서비스와 같은 서비스를 서비스 공급자에게 제공합니다. 기본 설정은 "사용"입니다.



ONTAP 9.7부터는 다음과 같은 추가 서비스가 지원됩니다.

* 구성 백업 파일('백업')
+
이 서비스를 사용하면 구성 백업 파일을 다운로드할 수 있습니다. 기본 설정은 "사용"입니다.

* ONTAP 보안('보안')
+
이 서비스는 향상된 인증을 위해 CSRF 토큰 관리를 지원합니다. 기본 설정은 "사용"입니다.


