---
permalink: system-admin/manage-node-root-volumes-aggregates-task.html 
sidebar: sidebar 
keywords: node, governing, root, volume, aggregate, files, special, directories, free, space, full, delete, file, core, dump 
summary: 노드의 루트 볼륨은 공장 출하 시 또는 설치 소프트웨어에 의해 설치되는 FlexVol 볼륨입니다. 
---
= 노드 루트 볼륨 및 루트 애그리게이트 관리
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
노드의 루트 볼륨은 공장 출하 시 또는 설치 소프트웨어에 의해 설치되는 FlexVol 볼륨입니다. 시스템 파일, 로그 파일 및 코어 파일용으로 예약되어 있습니다. 디렉토리 이름은 '/mroot'로, 시스템 셸을 통해서만 기술 지원 부서에서 액세스할 수 있습니다. 노드 루트 볼륨의 최소 크기는 플랫폼 모델에 따라 다릅니다.



== 노드 루트 볼륨 및 루트 애그리게이트 개요를 제어하는 규칙

노드의 루트 볼륨에는 해당 노드에 대한 특수 디렉토리와 파일이 포함되어 있습니다. 루트 Aggregate는 루트 볼륨을 포함합니다. 노드의 루트 볼륨 및 루트 애그리게이트에 대한 몇 가지 규칙이 적용됩니다.

* 다음 규칙은 노드의 루트 볼륨에 적용됩니다.
+
** 기술 지원 부서에서 지시하지 않는 한 루트 볼륨의 구성 또는 콘텐츠를 수정하지 마십시오.
** 루트 볼륨에 사용자 데이터를 저장하지 마십시오.
+
사용자 데이터를 루트 볼륨에 저장하면 HA 쌍의 노드 간 스토리지 반환 시간이 늘어납니다.

** 루트 볼륨을 다른 애그리게이트로 이동할 수 있습니다.  을 참조하십시오 <<relocate-root>>.


* 루트 애그리게이트는 노드의 루트 볼륨에만 사용됩니다.
+
ONTAP을 사용하면 루트 애그리게이트에 다른 볼륨을 생성할 수 없습니다.



https://hwu.netapp.com["NetApp Hardware Universe를 참조하십시오"^]



== 노드의 루트 볼륨에서 공간을 확보합니다

노드의 루트 볼륨이 꽉 찼거나 거의 꽉 찼을 때 경고 메시지가 나타납니다. 루트 볼륨이 꽉 찼을 때 노드가 제대로 작동하지 않습니다. 코어 덤프 파일, 패킷 추적 파일 및 루트 볼륨 스냅샷 복사본을 삭제하여 노드의 루트 볼륨에서 공간을 확보할 수 있습니다.

.단계
. 노드의 코어 덤프 파일과 해당 이름을 표시합니다.
+
'시스템 노드 코어 덤프 표시'

. 노드에서 필요 없는 코어 덤프 파일을 삭제합니다.
+
시스템 노드 코어 덤프 삭제

. 노데스 액세스:
+
'* 시스템 노드 run-node_nodename_*'

+
'_nodename_'은 루트 볼륨 공간을 확보하려는 노드의 이름입니다.

. 노드 쉘에서 노드 고급 권한 레벨로 전환합니다.
+
``한자 세트 어드밴스드 *’’

. 노드 패킷 추적 파일을 노드 쉘을 통해 표시 및 삭제:
+
.. 노드의 루트 볼륨에 있는 모든 파일을 표시합니다.
+
' * ls /etc * '

.. 노드의 루트 볼륨에 패킷 추적 파일('*.trc')이 있으면 개별적으로 삭제합니다.
+
' * rm/etc/log/packet_trace/_file_name.trc_ *'



. 노드 루트 볼륨 스냅샷 복사본을 식별하여 노드 쉘을 통해 삭제:
+
.. 루트 볼륨 이름 확인:
+
' * vol status * '

+
루트 볼륨은 "vol status" 명령 출력의 "Options" 열에 "root"라는 단어가 표시됩니다.

+
다음 예에서는 루트 볼륨이 "vol0"입니다.

+
[listing]
----
node1*> vol status

         Volume State           Status            Options
           vol0 online          raid_dp, flex     root, nvfail=on
                                64-bit
----
.. 루트 볼륨 스냅샷 복사본 표시:
+
'* 스냅 목록 root_vol_name*'

.. 필요 없는 루트 볼륨 스냅샷 복사본 삭제:
+
' * snap delete root_vol_namesnapshot_name * '



. 노드 쉘을 종료하고 클러스터 쉘로 돌아갑니다.
+
' * exit * '





== 루트 볼륨을 새 애그리게이트로 재배치

루트 교체 절차는 운영 중단 없이 현재 루트 애그리게이트를 다른 디스크 세트로 마이그레이션합니다.

.이 작업에 대해
루트 볼륨을 재배치하려면 스토리지 페일오버가 활성화되어 있어야 합니다. 'storage failover modify -node_nodename_ -enable true' 명령을 사용하여 페일오버를 활성화할 수 있습니다.

다음 시나리오에서 루트 볼륨의 위치를 새 애그리게이트로 변경할 수 있습니다.

* 루트 애그리게이트가 원하는 디스크에 없을 경우
* 노드에 연결된 디스크를 재정렬하려는 경우
* EOS 디스크 쉘프의 쉘프 교체를 수행할 때


.단계
. 권한 수준을 고급으로 설정합니다.
+
'* 권한 고급 설정 * '

. 루트 애그리게이트 재배치:
+
'* 시스템 노드 migrate-root-node_nodename_-disklist_disklist_-raid-type_raid-type_*'

+
** * -노드 *
+
마이그레이션할 루트 애그리게이트를 소유하는 노드를 지정합니다.

** * -디스크 목록 *
+
새 루트 애그리게이트를 생성할 디스크 목록을 지정합니다. 모든 디스크가 동일한 노드에서 소유하고 있어야 합니다. 필요한 최소 디스크 수는 RAID 유형에 따라 다릅니다.

** * -RAID-유형 *
+
루트 애그리게이트의 RAID 유형을 지정합니다. 기본값은 "RAID-DP"입니다.



. 작업 진행 상황 모니터링:
+
'* job show-id_jobid_-instance*'



.결과
모든 사전 검사가 성공하면 명령이 루트 볼륨 교체 작업을 시작하고 종료됩니다. 노드가 다시 시작될 것으로 예상합니다.
