---
permalink: system-admin/manage-cli-sessions.html 
sidebar: sidebar 
keywords: record, cli, script, start, stop, session 
summary: CLI 세션을 지정된 이름 및 크기 제한이 있는 파일에 기록한 다음 파일을 FTP 또는 HTTP 대상으로 업로드할 수 있습니다. 
---
= CLI 세션을 관리합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


CLI 세션을 지정된 이름 및 크기 제한이 있는 파일에 기록한 다음 파일을 FTP 또는 HTTP 대상으로 업로드할 수 있습니다. 이전에 CLI 세션을 기록한 파일을 표시하거나 삭제할 수도 있습니다.



== CLI 세션을 기록합니다

CLI 세션의 레코드는 녹화를 중지하거나 CLI 세션을 종료할 때 또는 파일이 지정된 크기 제한에 도달할 때 끝납니다. 기본 파일 크기 제한은 1MB입니다. 최대 파일 크기 제한은 2GB입니다.

예를 들어, 문제를 해결하고 상세 정보를 저장하려는 경우 또는 특정 시점에 공간 사용에 대한 영구 기록을 작성하려는 경우 CLI 세션을 기록하는 것이 유용합니다.

.단계
. 파일에 현재 CLI 세션 녹화를 시작합니다.
+
[source, cli]
----
system script start
----
+
'system script start' 명령어를 사용하는 방법에 대한 자세한 내용은 man 페이지를 참고한다.

+
ONTAP가 CLI 세션을 지정된 파일에 기록하기 시작합니다.

. CLI 세션을 진행합니다.
. 완료되면 세션 녹화를 중지합니다.
+
[source, cli]
----
system script stop
----
+
'system script stop' 명령어 사용에 대한 자세한 내용은 man 페이지를 참조한다.

+
ONTAP는 CLI 세션 녹화를 중지합니다.





== CLI 세션의 레코드를 관리하는 명령입니다

'system script' 명령어를 이용하여 CLI 세션 기록을 관리한다.

|===
| 원하는 작업 | 이 명령 사용... 


 a| 
지정된 파일에 현재 CLI 세션 녹화를 시작합니다
 a| 
'시스템 스크립트 시작



 a| 
현재 CLI 세션 녹화를 중지합니다
 a| 
'시스템 스크립트 중지'



 a| 
CLI 세션 레코드에 대한 정보를 표시합니다
 a| 
'시스템 스크립트 쇼'



 a| 
CLI 세션의 레코드를 FTP 또는 HTTP 대상으로 업로드합니다
 a| 
'시스템 스크립트 업로드'



 a| 
CLI 세션의 레코드를 삭제합니다
 a| 
'시스템 스크립트 삭제

|===
.관련 정보
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-cmpr/GUID-5CB10C70-AC11-41C0-8C16-B4D0DF916E9B.html["ONTAP 9 명령"^]



== CLI session의 자동 timeout 기간을 관리하는 명령어

timeout 값은 CLI 세션이 자동으로 종료되기 전까지 유휴 상태로 유지되는 시간을 지정합니다. CLI 시간 초과 값은 클러스터 전체에 적용됩니다. 즉, 클러스터의 모든 노드에서 동일한 CLI 시간 초과 값을 사용합니다.

기본적으로 CLI 세션의 자동 제한 시간은 30분입니다.

'system timeout' 명령어를 이용하여 CLI session의 자동 timeout 기간을 관리한다.

|===
| 원하는 작업 | 이 명령 사용... 


 a| 
CLI 세션의 자동 제한 시간을 표시합니다
 a| 
'시스템 시간 초과 표시'



 a| 
CLI 세션의 자동 시간 제한 기간을 수정합니다
 a| 
'시스템 시간 제한 수정'

|===
.관련 정보
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-cmpr/GUID-5CB10C70-AC11-41C0-8C16-B4D0DF916E9B.html["ONTAP 9 명령"^]
