---
permalink: system-admin/manage-web-protocol-engine-concept.html 
sidebar: sidebar 
keywords: manage, web, protocol, engine, ssl, access, configuration, settings 
summary: 웹 액세스가 허용되는지 여부와 사용할 수 있는 SSL 버전을 제어하도록 클러스터의 웹 프로토콜 엔진을 구성할 수 있습니다. 웹 프로토콜 엔진에 대한 구성 설정을 표시할 수도 있습니다. 
---
= 웹 프로토콜 엔진을 관리합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
웹 액세스가 허용되는지 여부와 사용할 수 있는 SSL 버전을 제어하도록 클러스터의 웹 프로토콜 엔진을 구성할 수 있습니다. 웹 프로토콜 엔진에 대한 구성 설정을 표시할 수도 있습니다.

다음과 같은 방법으로 클러스터 수준에서 웹 프로토콜 엔진을 관리할 수 있습니다.

* '-external' 파라미터를 가진 'system services web modify' 명령어를 이용하여 원격 클라이언트가 HTTP나 HTTPS를 이용하여 웹 서비스 컨텐츠에 액세스할 수 있는지 여부를 지정할 수 있다.
* '-supported-protocol' 파라미터를 가진 '보안 설정 수정' 명령어를 이용하여 SSLv3을 안전한 웹 액세스에 사용할지 여부를 지정할 수 있다.
+
기본적으로 SSLv3은 비활성화되어 있습니다. 전송 계층 보안 1.0(TLSv1.0)이 활성화되어 있으며 필요한 경우 비활성화할 수 있습니다.

* FIPS(Federal Information Processing Standard) 140-2 규정 준수 모드를 사용하여 클러스터 전체의 컨트롤 플레인 웹 서비스 인터페이스를 구현할 수 있습니다.
+
[NOTE]
====
기본적으로 FIPS 140-2 규정 준수 모드는 비활성화되어 있습니다.

====
+
** * FIPS 140-2 규정 준수 모드가 비활성화된 경우 *
+
'보안 구성 수정' 명령에 대해 'is-FIPS-enabled' 매개 변수를 'true'로 설정한 다음 'ecurity config show' 명령을 사용하여 온라인 상태를 확인하면 FIPS 140-2 규정 준수 모드를 사용할 수 있습니다.

** * FIPS 140-2 규정 준수 모드가 활성화된 경우 *
+
TLSv1 및 SSLv3은 모두 비활성화되며 TLSv1.1 및 TLSv1.2만 활성화됩니다. ONTAP를 사용하면 FIPS 140-2 규정 준수 모드가 활성화된 경우 TLSv1 및 SSLv3을 모두 사용할 수 없습니다. FIPS 140-2 규정 준수 모드를 활성화한 후 나중에 비활성화하면 TLSv1 및 SSLv3은 비활성화 상태로 유지되지만 TLSv1.2 또는 TLSv1.1 및 TLSv1.2는 이전 구성에 따라 모두 활성화됩니다.



* 'system security config show' 명령을 사용하여 클러스터 차원의 보안 구성을 표시할 수 있습니다.


방화벽이 설정된 경우 웹 서비스에 사용할 논리 인터페이스(LIF)의 방화벽 정책을 HTTP 또는 HTTPS 액세스를 허용하도록 설정해야 합니다.

웹 서비스 액세스에 HTTPS를 사용하는 경우, 웹 서비스를 제공하는 클러스터 또는 SVM(스토리지 가상 머신)에 SSL도 사용하도록 설정해야 하며 클러스터 또는 SVM에 디지털 인증서를 제공해야 합니다.

MetroCluster 구성에서는 클러스터의 웹 프로토콜 엔진에 대해 변경한 설정이 파트너 클러스터에 복제되지 않습니다.
