---
permalink: system-admin/manage-cluster-time-concept.html 
sidebar: sidebar 
keywords: manage, cluster, time, administrator, ntp, network, time, protocol, zone 
summary: '클러스터 시간이 정확하지 않을 수 있습니다. ONTAP를 사용하여 클러스터에서 표준 시간대, 날짜 및 시간을 수동으로 설정할 수 있지만 클러스터 시간을 동기화하도록 NTP(네트워크 시간 프로토콜) 서버를 구성해야 합니다.' 
---
= 클러스터 시간 관리(클러스터 관리자만 해당)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
클러스터 시간이 정확하지 않을 수 있습니다. ONTAP를 사용하여 클러스터에서 표준 시간대, 날짜 및 시간을 수동으로 설정할 수 있지만 클러스터 시간을 동기화하도록 NTP(네트워크 시간 프로토콜) 서버를 구성해야 합니다.

ONTAP 9.5부터 대칭 인증을 사용하여 NTP 서버를 구성할 수 있습니다.

NTP는 항상 활성화되어 있습니다. 하지만 클러스터가 외부 시간 소스와 동기화하기 위해서는 구성이 여전히 필요합니다. ONTAP를 사용하면 다음과 같은 방법으로 클러스터의 NTP 구성을 관리할 수 있습니다.

* 최대 10개의 외부 NTP 서버를 클러스터에 연결할 수 있습니다('클러스터 시간 서비스 NTP 서버 생성').
+
** 시간 서비스의 이중화 및 품질을 위해 최소 3개의 외부 NTP 서버를 클러스터에 연결해야 합니다.
** IPv4 또는 IPv6 주소 또는 정규화된 호스트 이름을 사용하여 NTP 서버를 지정할 수 있습니다.
** 사용할 NTP 버전(v3 또는 v4)을 수동으로 지정할 수 있습니다.
+
기본적으로 ONTAP는 지정된 외부 NTP 서버에 지원되는 NTP 버전을 자동으로 선택합니다.

+
지정한 NTP 버전이 NTP 서버에 지원되지 않으면 시간 교환이 불가능합니다.

** 고급 권한 수준에서는 클러스터와 연결된 외부 NTP 서버를 클러스터 시간을 수정 및 조정하기 위한 기본 시간 소스로 지정할 수 있습니다.


* 클러스터와 연결된 NTP 서버를 표시할 수 있습니다('cluster time-service ntp server show').
* 클러스터의 NTP 구성을 수정할 수 있습니다('cluster time-service NTP server modify').
* 외부 NTP 서버에서 클러스터를 연결 해제할 수 있습니다('클러스터 시간 서비스 NTP 서버 삭제').
* 고급 권한 수준에서는 클러스터와 연결된 모든 외부 NTP 서버('클러스터 시간 서비스 NTP 서버 재설정')를 지워 구성을 재설정할 수 있습니다.


클러스터를 결합하는 노드는 클러스터의 NTP 구성을 자동으로 채택합니다.

ONTAP에서는 NTP를 사용할 뿐만 아니라 클러스터 시간도 수동으로 관리할 수 있습니다. 이 기능은 오류가 있는 시간을 수정해야 하는 경우(예: 재부팅 후 노드의 시간이 크게 올바르지 않음) 유용합니다. 이 경우 NTP가 외부 시간 서버와 동기화될 때까지 클러스터에 대한 대략적인 시간을 지정할 수 있습니다. 수동으로 설정하는 시간은 클러스터의 모든 노드에 적용됩니다.

다음과 같은 방법으로 클러스터 시간을 수동으로 관리할 수 있습니다.

* 클러스터에서 시간대, 날짜 및 시간을 설정하거나 수정할 수 있습니다('클러스터 날짜 수정').
* 클러스터의 현재 시간대, 날짜 및 시간 설정을 표시할 수 있습니다('클러스터 날짜 표시').


[NOTE]
====
작업 일정이 수동 클러스터 날짜 및 시간 변경에 맞게 조정되지 않습니다. 이러한 작업은 작업이 생성된 현재 클러스터 시간 또는 가장 최근에 실행된 작업을 기준으로 실행되도록 예약되어 있습니다. 따라서 클러스터 날짜 또는 시간을 수동으로 변경하는 경우 "job show" 및 "job history show" 명령을 사용하여 예약된 모든 작업이 요구 사항에 따라 대기열에 추가되고 완료되었는지 확인해야 합니다.

====


== 클러스터 시간을 관리하는 명령입니다

클러스터의 NTP 서버를 관리하기 위해 'cluster time-service ntp server' 명령어를 사용한다. 클러스터 날짜 명령을 사용하여 수동으로 클러스터 시간을 관리할 수 있습니다.

ONTAP 9.5부터 대칭 인증을 사용하여 NTP 서버를 구성할 수 있습니다.

다음 명령을 사용하여 클러스터의 NTP 서버를 관리할 수 있습니다.

|===
| 원하는 작업 | 이 명령 사용... 


 a| 
대칭 인증 없이 클러스터를 외부 NTP 서버에 연결합니다
 a| 
'cluster time-service ntp server create-server server_name



 a| 
클러스터를 외부 NTP 서버와 ONTAP 9.5 이상에서 사용할 수 있는 대칭 인증으로 연결합니다
 a| 
'cluster time-service ntp server create-server_ip_address-key-id key_id

[NOTE]
====
'key_id'는 ''cluster time-service ntp key'로 설정된 기존 공유 키를 참조해야 합니다.

====


 a| 
기존 NTP 서버에 대칭 인증 사용 기존 NTP 서버는 필요한 키 ID를 추가하여 인증을 사용하도록 수정할 수 있습니다

ONTAP 9.5 이상에서 사용할 수 있습니다
 a| 
'cluster time-service ntp server modify -server server_name -key-id key_id



 a| 
대칭 인증을 사용하지 않도록 설정합니다
 a| 
`cluster time-service ntp server modify -server server_name -is-authentication-enabled false`



 a| 
공유 NTP 키를 구성합니다
 a| 
'cluster time-service ntp key create-id shared_key_id-type shared_key_type-value shared_key_value'

[NOTE]
====
공유 키는 ID로 참조됩니다. ID, 유형 및 값은 노드와 NTP 서버 모두에서 동일해야 합니다

====


 a| 
클러스터와 연결된 NTP 서버에 대한 정보를 표시합니다
 a| 
클러스터 시간 서비스 NTP 서버가 표시됩니다



 a| 
클러스터와 연결된 외부 NTP 서버의 구성을 수정합니다
 a| 
클러스터 시간 서비스 NTP 서버 수정



 a| 
클러스터에서 NTP 서버를 해제합니다
 a| 
클러스터 시간 서비스 NTP 서버 삭제



 a| 
클러스터와의 모든 외부 NTP 서버 연결을 선택 취소하여 구성을 재설정합니다
 a| 
클러스터 시간 서비스 NTP 서버 리셋

[NOTE]
====
이 명령을 사용하려면 고급 권한 수준이 필요합니다.

====
|===
다음 명령을 사용하면 클러스터 시간을 수동으로 관리할 수 있습니다.

|===
| 원하는 작업 | 이 명령 사용... 


 a| 
시간대, 날짜 및 시간을 설정하거나 수정합니다
 a| 
클러스터 날짜 수정



 a| 
클러스터의 시간대, 날짜 및 시간 설정을 표시합니다
 a| 
'클러스터 날짜 표시'

|===
.관련 정보
link:../concepts/manual-pages.html["ONTAP 명령 참조입니다"]
