---
permalink: system-admin/methods-manage-sp-bmc-firmware-updates-concept.html 
sidebar: sidebar 
keywords: methods, manage, sp, bmc, firmware, update, image, baseline, download 
summary: ONTAP에는 기본 이미지라고 하는 SP 펌웨어 이미지가 포함되어 있습니다. 이후에 새로운 버전의 SP 펌웨어를 사용할 수 있게 되면 ONTAP 버전을 업그레이드하지 않고 SP 펌웨어를 다운로드하여 다운로드한 버전으로 업데이트할 수 있습니다. 
---
= SP/BMC 펌웨어 업데이트를 관리하는 방법
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP에는 _baseline image_라고 하는 SP 펌웨어 이미지가 포함되어 있습니다. 이후에 새로운 버전의 SP 펌웨어를 사용할 수 있게 되면 ONTAP 버전을 업그레이드하지 않고 SP 펌웨어를 다운로드하여 다운로드한 버전으로 업데이트할 수 있습니다.

[NOTE]
====
이 항목은 SP와 BMC 모두에 적용됩니다.

====
ONTAP에서는 SP 펌웨어 업데이트를 관리하는 다음과 같은 방법을 제공합니다.

* SP 자동 업데이트 기능은 기본적으로 활성화되어 다음과 같은 경우 SP 펌웨어가 자동으로 업데이트됩니다.
+
** 새 버전의 ONTAP로 업그레이드하는 경우
+
ONTAP 업그레이드 프로세스에는 SP 펌웨어 업데이트가 자동으로 포함됩니다. 단, ONTAP와 함께 번들로 제공되는 SP 펌웨어 버전이 노드에서 실행 중인 SP 버전보다 최신이어야 합니다.

+
[NOTE]
====
ONTAP는 장애가 발생한 SP 자동 업데이트를 감지하고 수정 조치를 트리거하여 SP 자동 업데이트를 최대 3배까지 재시도하십시오. 세 번 재시도 모두 실패하면 기술 문서 링크 https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/Health_Monitor_SPAutoUpgradeFailedMajorAlert__SP_upgrade_fails_-_AutoSupport_Message[Health SPAutoUpgradeFailedMajorAlert SP 업그레이드 실패 - AutoSupport 메시지]를 참조하십시오.

====
** NetApp Support 사이트에서 SP 펌웨어 버전을 다운로드하고 다운로드한 버전이 현재 SP에서 실행 중인 버전보다 최신입니다
** 이전 버전의 ONTAP로 다운그레이드하거나 되돌릴 때
+
SP 펌웨어는 이전 또는 다운그레이드한 ONTAP 버전에서 지원하는 최신 호환 버전으로 자동 업데이트됩니다. 수동 SP 펌웨어 업데이트는 필요하지 않습니다.



+
'system service-processor image modify' 명령을 사용하여 SP 자동 업데이트 기능을 비활성화할 수 있습니다. 그러나 이 기능을 활성 상태로 두는 것이 좋습니다. 이 기능을 사용하지 않도록 설정하면 ONTAP 이미지와 SP 펌웨어 이미지 간에 최적화되지 않은 또는 비정규화된 조합이 발생할 수 있습니다.

* ONTAP를 사용하면 수동으로 SP 업데이트를 트리거하고 'system service-processor image update' 명령을 사용하여 업데이트 방법을 지정할 수 있습니다.
+
다음 옵션을 지정할 수 있습니다.

+
** 사용할 SP 펌웨어 패키지('-package')
+
패키지 파일 이름을 지정하여 SP 펌웨어를 다운로드한 패키지로 업데이트할 수 있습니다. advance 'system image package show' 명령어는 노드에서 사용할 수 있는 모든 패키지 파일(SP 펌웨어 패키지의 파일 포함)을 출력한다.

** SP 업데이트에 기본 SP 펌웨어 패키지를 사용할지 여부('-baseline')
+
현재 실행 중인 ONTAP 버전에 번들로 제공되는 기본 버전으로 SP 펌웨어를 업데이트할 수 있습니다.



+
[NOTE]
====
고급 업데이트 옵션 또는 매개 변수 중 일부를 사용하는 경우 BMC의 구성 설정이 일시적으로 지워질 수 있습니다. 재부팅 후 ONTAP가 BMC 구성을 복원하는 데 최대 10분이 걸릴 수 있습니다.

====
* ONTAP를 사용하면 'system service-processor image update-progress show' 명령을 사용하여 ONTAP에서 트리거된 최신 SP 펌웨어 업데이트의 상태를 표시할 수 있습니다.


SP 펌웨어를 업데이트하는 동안 SP에 대한 기존 연결이 모두 종료됩니다. 이는 SP 펌웨어 업데이트가 자동으로 수행되는지 아니면 수동으로 실행되는지 여부입니다.

https://mysupport.netapp.com/site/downloads/firmware/system-firmware-diagnostics["NetApp 다운로드: 시스템 펌웨어 및 진단"]
