---
permalink: system-admin/modify-sp-api-service-config-task.html 
sidebar: sidebar 
keywords: modify, sp, api, service, configuration, network 
summary: SP API는 ONTAP가 네트워크를 통해 SP와 통신할 수 있도록 지원하는 보안 네트워크 API입니다. SP API 서비스에 사용되는 포트를 변경하거나, 서비스가 내부 통신에 사용하는 인증서를 갱신하거나, 서비스를 완전히 해제할 수 있습니다. 드문 경우에만 구성을 수정해야 합니다. 
---
= SP API 서비스 구성을 수정합니다
:icons: font
:imagesdir: ../media/


[role="lead"]
SP API는 ONTAP가 네트워크를 통해 SP와 통신할 수 있도록 지원하는 보안 네트워크 API입니다. SP API 서비스에 사용되는 포트를 변경하거나, 서비스가 내부 통신에 사용하는 인증서를 갱신하거나, 서비스를 완전히 해제할 수 있습니다. 드문 경우에만 구성을 수정해야 합니다.

.이 작업에 대해
* SP API 서비스는 기본적으로 포트 50000을 사용합니다.
+
예를 들어 다른 네트워킹 응용 프로그램의 통신에 포트 '50000'이 사용되는 네트워크 설정에 있거나 다른 응용 프로그램과 SP API 서비스에서 생성된 트래픽을 구별하려는 경우 포트 값을 변경할 수 있습니다.

* SP API 서비스에서 사용하는 SSL 및 SSH 인증서는 클러스터 내부에 있으며 외부에 배포되지 않습니다.
+
드물지만 인증서가 손상된 경우 인증서를 갱신할 수 있습니다.

* SP API 서비스는 기본적으로 사용하도록 설정됩니다.
+
SP가 구성되어 있지 않거나 사용되지 않고 서비스를 해제하려는 전용 LAN과 같은 드문 경우에만 SP API 서비스를 사용하지 않도록 설정해야 합니다.

+
SP API 서비스가 해제되어 있으면 API는 들어오는 연결을 허용하지 않습니다. 또한 네트워크 기반 SP 펌웨어 업데이트 및 네트워크 기반 SP "자체 시스템" 로그 수집 등의 기능을 사용할 수 없게 됩니다. 시스템이 직렬 인터페이스를 사용하여 로 전환됩니다.



.단계
. Set-Privilege advanced 명령을 사용하여 고급 권한 레벨로 전환합니다.
. SP API 서비스 구성을 수정합니다.
+
|===
| 원하는 작업 | 다음 명령을 사용합니다... 


 a| 
SP API 서비스에서 사용하는 포트를 변경합니다
 a| 
'-port'{'49152'....65535' 매개변수를 사용하여 시스템 서비스 프로세서 API 서비스를 수정합니다



 a| 
내부 통신을 위해 SP API 서비스에서 사용하는 SSL 및 SSH 인증서를 갱신합니다
 a| 
** ONTAP 9.5 이상의 경우 'system service-processor api-service renew-internal-certificate'를 사용한다
** ONTAP 9.4 및 그 이전 버전의 경우
** '시스템 서비스 - 프로세서 API - 서비스 갱신 - 인증서'
+
매개 변수를 지정하지 않으면 호스트 인증서(클라이언트 및 서버 인증서 포함)만 갱신됩니다.

+
'-renew-all true' 매개 변수가 지정된 경우 호스트 인증서와 루트 CA 인증서가 모두 갱신됩니다.





 a| 
통신
 a| 



 a| 
SP API 서비스를 사용하지 않도록 설정하거나 다시 설정합니다
 a| 
'-is-enabled'{'true'|'false'} 매개 변수를 사용하여 시스템 서비스 프로세서 API 서비스 수정

|===
. 'system service-processor api-service show' 명령을 사용하여 SP API 서비스 구성을 표시합니다.

