---
permalink: system-admin/remov-nodes-cluster-concept.html 
sidebar: sidebar 
keywords: remove, node, cluster, failover, partner, erase, inaccessible 
summary: 클러스터에서 필요 없는 노드를 한 번에 하나씩 제거할 수 있습니다. 노드를 제거한 후에는 해당 페일오버 파트너도 제거해야 합니다. 노드를 제거하면 해당 데이터에 액세스할 수 없거나 데이터가 지워집니다. 
---
= 클러스터에서 노드를 제거합니다
:icons: font
:imagesdir: ../media/


[role="lead"]
클러스터에서 필요 없는 노드를 한 번에 하나씩 제거할 수 있습니다. 노드를 제거한 후에는 해당 페일오버 파트너도 제거해야 합니다. 노드를 제거하면 해당 데이터에 액세스할 수 없거나 데이터가 지워집니다.

.무엇을 &#8217;필요로 할거야
* 클러스터 내 노드의 절반 이상이 정상 상태여야 합니다.
* 제거하려는 노드의 모든 데이터가 비워져야 합니다.
* 모든 인터클러스터 LIF가 제거되었어야 합니다.
+
[NOTE]
====
인터클러스터 LIF를 제거하면 무시할 수 있는 경고가 표시됩니다.

자동화된 ONTAP 업그레이드가 진행 중일 때는 클러스터 remove-node, cluster unjoin, node rename 등의 작업을 수행해서는 안 됩니다.

====


혼합 버전 클러스터를 실행 중인 경우 ONTAP 9.3으로 시작하는 고급 권한 명령 중 하나를 사용하여 마지막 하위 버전 노드를 제거할 수 있습니다.

* ONTAP 9.3: 클러스터 unjoin-skip-last-low-version-node-check
* ONTAP 9.4 이상: cluster remove-node-skip-last-low-version-node-check


[NOTE]
====
클러스터에서 노드를 제거하기 전에 노드에 연결된 디스크의 모든 시스템 및 사용자 데이터를 사용자가 액세스할 수 없도록 해야 합니다. 클러스터에서 노드를 제거한 후 노드를 다시 같은 클러스터에 연결해야 하는 경우 기술 지원 부서에 데이터 복원에 대한 지원을 문의하십시오.

====
.단계
. 권한 수준을 고급으로 변경합니다.
+
' * set-Privilege advanced * '

. 클러스터에서 스토리지 암호화가 활성화되고 SED(자체 암호화 디스크)가 작동하는 경우 데이터 ID 키를 0x0으로 설정해야 합니다.
+
.. data-id-key를 0x0으로 설정합니다.
+
'* 스토리지 암호화 디스크 수정 - 디스크\[_DISK_PATH_NAME_\] - DATA-KEY-id 0x0 * '

.. 선택 사항: 스토리지 암호화가 활성화되고 SED가 FIPS(Federal Information Processing Standard) 준수 모드로 작동하는 경우 데이터 ID 키를 설정하는 것 외에도 FIPS 준수 모드도 비활성화해야 합니다.
+
따라서 노드에 연결된 디스크가 클러스터에서 노드를 제거한 후 삭제 및 재활용될 수 있습니다.

+
*** 현재 FIPS 준수 모드에 있는 SED를 표시합니다.
+
'* 스토리지 암호화 디스크 show-FIPS * '

*** FIPS 규정 준수 모드를 사용하지 않도록 설정합니다.
+
"* 스토리지 암호화 디스크 수정 디스크 [_DISK_PATH_NAME_] - FIPS-KEY-id 0x0 * "

*** 수정된 SED가 더 이상 FIPS 준수 모드에 있지 않은지 확인합니다.
+
'* 스토리지 암호화 디스크 show-FIPS * '





. 제거하려는 노드가 현재 마스터 노드인 경우 마스터 노드의 클러스터 자격을 "false"로 변경하여 클러스터의 다른 노드를 마스터 노드로 선택합니다.
+
' * 클러스터 수정 – 자격 오류 *'

+
마스터 노드는 "mGMT", "VLDB", "vifmgr", "bcomd", "CRS" 등의 프로세스를 보유하는 노드입니다. cluster ring show 고급 명령은 현재 마스터 노드를 표시합니다.

+
[listing]
----
cluster::*> cluster modify -node node1 -eligibility false
----
. 클러스터에서 노드를 제거합니다.
+
|===
| 이 ONTAP 버전의 경우... | 이 명령 사용... 


 a| 
ONTAP 9.3
 a| 
'* 클러스터 연결 해제 * '



 a| 
ONTAP 9.4 이상
 a| 
'* 클러스터 제거 노드 * '

|===
+
혼합 버전 클러스터가 있고 마지막 하위 버전 노드를 제거하는 경우 이 명령과 함께 '-skip-last-low-version-node-check' 매개 변수를 사용합니다.

+
시스템에서 다음 정보를 알려줍니다.

+
** 또한 클러스터의 페일오버 파트너도 제거해야 합니다.
** 노드를 제거한 후 클러스터에 다시 참가하려면 부팅 메뉴 옵션(4) 구성 정리 및 모든 디스크 초기화 또는 옵션(9) 고급 드라이브 파티셔닝 구성(Configure Advanced Drive Partitioning)을 사용하여 노드 구성을 지우고 모든 디스크를 초기화해야 합니다.
+
노드를 제거하기 전에 해결해야 하는 조건이 있는 경우 실패 메시지가 생성됩니다. 예를 들어, 메시지에서 제거해야 하는 공유 리소스가 노드에 포함되어 있거나 해당 노드가 반드시 해제해야 하는 클러스터 HA 구성 또는 스토리지 페일오버 구성에 포함되어 있음을 나타낼 수 있습니다.

+
노드가 쿼럼 마스터인 경우 클러스터가 잠시 손실되었다가 쿼럼으로 돌아갑니다. 이 쿼럼 손실은 일시적이며 데이터 작업에 영향을 주지 않습니다.



. 오류 메시지에 오류 상태가 표시되면 해당 조건을 해결하고 클러스터 remove-node 또는 cluster unjoin 명령을 다시 실행합니다.
+
노드가 클러스터에서 성공적으로 제거된 후 자동으로 재부팅됩니다.

. 노드를 용도 변경할 경우 노드 구성을 지우고 모든 디스크를 초기화합니다.
+
.. 부팅 프로세스 중에 부팅 메뉴가 표시되면 Ctrl-C를 눌러 부팅 메뉴를 표시합니다.
.. 부팅 메뉴 옵션 * (4) 구성 정리 및 모든 디스크 초기화 * 를 선택합니다.


. 관리자 권한 레벨로 돌아가기:
+
' * set-privilege admin * '

. 클러스터에서 페일오버 파트너를 제거하려면 위의 단계를 반복합니다.


단일 노드 클러스터가 필요한 노드를 제거한 경우 클러스터 포트를 데이터 포트로 수정하여 데이터 트래픽을 처리하도록 한 다음 데이터 포트에 데이터 LIF를 생성해야 합니다.
