---
permalink: system-admin/requirements-autosupport-reference.html 
sidebar: sidebar 
keywords: requirements, autosupport, messages, http, smtp, https, configuration, support, protocols 
summary: 최상의 보안을 제공하고 모든 최신 AutoSupport 기능을 지원하려면 AutoSupport 메시지 전달에 HTTPS를 사용해야 합니다. AutoSupport는 AutoSupport 메시지 전달을 위해 HTTP 및 SMTP를 지원하지만 HTTPS를 사용하는 것이 좋습니다. 
---
= AutoSupport 사용에 대한 요구 사항
:icons: font
:imagesdir: ../media/


[role="lead"]
최상의 보안을 제공하고 모든 최신 AutoSupport 기능을 지원하려면 AutoSupport 메시지 전달에 HTTPS를 사용해야 합니다. AutoSupport는 AutoSupport 메시지 전달을 위해 HTTP 및 SMTP를 지원하지만 HTTPS를 사용하는 것이 좋습니다.



== 지원되는 프로토콜

이러한 모든 프로토콜은 이름이 확인되는 주소 패밀리를 기반으로 IPv4 또는 IPv6에서 실행됩니다.

|===
| 프로토콜 및 포트 | 설명 


 a| 
포트 443의 HTTPS
 a| 
기본 프로토콜입니다. 가능한 경우 이 기능을 사용해야 합니다.

이 프로토콜은 AutoSupport OnDemand 및 대용량 파일 업로드를 지원합니다.

유효성 검사를 사용하지 않는 한 원격 서버의 인증서는 루트 인증서에 대해 유효성이 검사됩니다.

전송 시 HTTP PUT 요청이 사용됩니다. PUT를 사용하면 전송 중에 요청이 실패하면 요청이 중지된 위치에서 다시 시작됩니다. 요청을 수신하는 서버가 PUT를 지원하지 않는 경우, 전송은 HTTP POST 요청을 사용합니다.



 a| 
포트 80의 HTTP
 a| 
이 프로토콜은 SMTP를 사용하는 것이 좋습니다.

이 프로토콜은 대용량 파일 업로드를 지원하지만 AutoSupport OnDemand는 지원하지 않습니다.

전송 시 HTTP PUT 요청이 사용됩니다. PUT를 사용하면 전송 중에 요청이 실패하면 요청이 중지된 위치에서 다시 시작됩니다. 요청을 수신하는 서버가 PUT를 지원하지 않는 경우, 전송은 HTTP POST 요청을 사용합니다.



 a| 
포트 25 또는 다른 포트의 SMTP
 a| 
네트워크 연결이 HTTPS 또는 HTTP를 허용하지 않는 경우에만 이 프로토콜을 사용해야 합니다.

기본 포트 값은 25이지만 다른 포트를 사용하도록 AutoSupport를 구성할 수 있습니다.

SMTP 사용 시 다음 제한 사항을 염두에 두십시오.

* AutoSupport OnDemand 및 대용량 파일 업로드는 지원되지 않습니다.
* 데이터가 암호화되지 않았습니다.
+
SMTP는 데이터를 일반 텍스트로 전송하므로 AutoSupport 메시지의 텍스트를 쉽게 가로채고 읽을 수 있습니다.

* 메시지 길이 및 줄 길이에 대한 제한을 도입할 수 있습니다.


|===
내부 지원 조직 또는 지원 파트너 조직에 대해 특정 전자 메일 주소로 AutoSupport를 구성하는 경우 이러한 메시지는 항상 SMTP를 통해 전송됩니다.

예를 들어 권장 프로토콜을 사용하여 기술 지원 부서에 메시지를 보내고 내부 지원 조직에 메시지를 보내려는 경우 메시지는 각각 HTTPS 및 SMTP를 사용하여 전송됩니다.

AutoSupport는 각 프로토콜의 최대 파일 크기를 제한합니다. HTTP 및 HTTPS 전송의 기본 설정은 25MB입니다. SMTP 전송의 기본 설정은 5MB입니다. AutoSupport 메시지의 크기가 구성된 제한을 초과하면 AutoSupport는 최대한 많은 메시지를 전달합니다. AutoSupport 설정을 수정하여 최대 크기를 편집할 수 있습니다. 자세한 내용은 '시스템 노드 AutoSupport 수정' man 페이지를 참조하십시오.

[NOTE]
====
AutoSupport는 코어 덤프 또는 성능 아카이브 파일을 NetApp 지원 사이트 또는 지정된 URI로 업로드하는 AutoSupport 메시지를 생성하고 전송할 때 HTTPS 및 HTTP 프로토콜의 최대 파일 크기 제한을 자동으로 재정의합니다. 자동 재정의는 'system node AutoSupport invoke-core-upload' 또는 'system node AutoSupport invoke-performance-archive' 명령을 사용하여 파일을 업로드할 때만 적용됩니다.

====


== 구성 요구 사항

네트워크 구성에 따라 HTTP 또는 HTTPS 프로토콜을 사용하려면 프록시 URL을 추가로 구성해야 할 수 있습니다. HTTP 또는 HTTPS를 사용하여 AutoSupport 메시지를 기술 지원 부서에 보내고 프록시가 있는 경우 해당 프록시의 URL을 식별해야 합니다. 프록시에서 기본 포트(3128)가 아닌 다른 포트를 사용하는 경우 해당 프록시의 포트를 지정할 수 있습니다. 프록시 인증을 위해 사용자 이름과 암호를 지정할 수도 있습니다.

SMTP를 사용하여 AutoSupport 메시지를 내부 지원 조직 또는 기술 지원 부서에 보내는 경우 외부 메일 서버를 구성해야 합니다. 스토리지 시스템이 메일 서버로 작동하지 않으므로 메일을 보내려면 사이트에 외부 메일 서버가 필요합니다. 메일 서버는 SMTP 포트(25) 또는 다른 포트에서 수신 대기하는 호스트여야 하며 8비트 MIME(Multipurpose Internet Mail Extensions) 인코딩을 보내고 받도록 구성해야 합니다. 메일 호스트의 예로는 sendmail 프로그램과 같은 SMTP 서버를 실행하는 UNIX 호스트와 Microsoft Exchange 서버를 실행하는 Windows 서버가 있습니다. 하나 이상의 메일 호스트를 가질 수 있습니다.
