---
permalink: system-admin/restore-cluster-config-from-existing-task.html 
sidebar: sidebar 
keywords: restore, cluster, configuration, existing, configuration, failure, recovering, node, rejoin, cluster 
summary: 클러스터 장애 후 기존 구성에서 클러스터 구성을 복원하려면 선택한 클러스터 구성을 사용하여 클러스터를 다시 생성한 다음 복구 노드에 사용할 수 있도록 설정한 다음 각 추가 노드를 새 클러스터에 다시 연결합니다. 
---
= 기존 구성에서 클러스터 구성을 복원합니다
:icons: font
:imagesdir: ../media/


[role="lead"]
클러스터 장애 후 기존 구성에서 클러스터 구성을 복원하려면 선택한 클러스터 구성을 사용하여 클러스터를 다시 생성한 다음 복구 노드에 사용할 수 있도록 설정한 다음 각 추가 노드를 새 클러스터에 다시 연결합니다.

이 작업은 클러스터의 구성 손실을 초래한 재해에서 복구하려는 경우에만 수행해야 합니다.

[NOTE]
====
구성 백업 파일에서 클러스터를 다시 생성하는 경우 기술 지원 부서에 문의하여 구성 백업 파일과 클러스터에 있는 구성 간의 불일치 문제를 해결해야 합니다.

====
.단계
. 각 HA 쌍에 대해 스토리지 페일오버 해제:
+
' * storage failover modify -node_node_name _ -enabled false * '

+
각 HA 쌍에 대해 스토리지 페일오버를 한 번만 해제하면 됩니다. 노드에 대해 스토리지 페일오버를 해제하면 노드의 파트너에서도 스토리지 페일오버가 해제됩니다.

. 복구 노드를 제외하고 각 노드를 중단합니다.
+
"* 시스템 노드 halt-node_node_name_ - 이유 "text" * "

+
[listing]
----
cluster1::*> system node halt -node node0 -reason "recovering cluster"

Warning: Are you sure you want to halt the node? {y|n}: y
----
. 권한 수준을 고급으로 설정합니다.
+
' * set-Privilege advanced * '

. 복구 노드에서 ' * system configuration recovery cluster recreate * ' 명령을 사용하여 클러스터를 다시 생성합니다.
+
이 예에서는 복구 노드에 저장된 구성 정보를 사용하여 클러스터를 다시 생성합니다.

+
[listing]
----
cluster1::*> configuration recovery cluster recreate -from node

Warning: This command will destroy your existing cluster. It will
         rebuild a new single-node cluster consisting of this node
         and its current configuration. This feature should only be
         used to recover from a disaster. Do not perform any other
         recovery operations while this operation is in progress.
Do you want to continue? {y|n}: y
----
+
복구 노드에 새 클러스터가 생성됩니다.

. 구성 백업 파일에서 클러스터를 다시 생성하는 경우 클러스터 복구가 진행 중인지 확인합니다.
+
'* 시스템 구성 복구 클러스터 표시 * '

+
정상적인 노드에서 클러스터를 다시 생성하는 경우에는 클러스터 복구 상태를 확인할 필요가 없습니다.

+
[listing]
----
cluster1::*> system configuration recovery cluster show
 Recovery Status: in-progress
 Is Recovery Status Persisted: false
----
. 재생성된 클러스터에 다시 결합해야 하는 각 노드를 부팅합니다.
+
노드를 한 번에 하나씩 재부팅해야 합니다.

. 재생성된 클러스터에 결합해야 하는 각 노드에 대해 다음을 수행합니다.
+
.. 다시 생성된 클러스터의 정상 노드에서 타겟 노드를 다시 연결합니다.
+
'* 시스템 구성 복구 클러스터가 다시 참가합니다 - node_node_name_ *

+
이 예에서는 ""node2"" 타겟 노드를 다시 생성된 클러스터에 다시 연결합니다.

+
[listing]
----
cluster1::*> system configuration recovery cluster rejoin -node node2

Warning: This command will rejoin node "node2" into the local
         cluster, potentially overwriting critical cluster
         configuration files. This command should only be used
         to recover from a disaster. Do not perform any other
         recovery operations while this operation is in progress.
         This command will cause node "node2" to reboot.
Do you want to continue? {y|n}: y
----
+
타겟 노드가 재부팅된 다음 클러스터에 추가됩니다.

.. 대상 노드가 정상이고 클러스터의 나머지 노드와 함께 쿼럼을 형성했는지 확인합니다.
+
`* 클러스터 표시 - 자격 True*'

+
다른 노드를 다시 참가하려면 타겟 노드가 다시 생성된 클러스터에 다시 참가해야 합니다.

+
[listing]
----
cluster1::*> cluster show -eligibility true
Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  ------------
node0                true    true          false
node1                true    true          false
2 entries were displayed.
----


. 구성 백업 파일에서 클러스터를 다시 생성한 경우 복구 상태를 완료로 설정합니다.
+
'* 시스템 구성 복구 클러스터 수정-복구-상태 완료 * '

. 관리자 권한 레벨로 돌아갑니다.
+
' * set-privilege admin * '

. 클러스터가 2개의 노드로만 구성된 경우, 클러스터 HA를 다시 활성화하려면 ' * cluster ha modify * ' 명령을 사용하십시오.
. 각 HA 쌍의 스토리지 페일오버를 다시 설정하려면 ' * storage failover modify * ' 명령을 사용합니다.


클러스터에 SnapMirror 피어 관계가 있는 경우 이러한 관계도 다시 생성해야 합니다. 자세한 내용은 을 참조하십시오 link:../data-protection/index.html["데이터 보호"].
