---
permalink: system-admin/rules-specifying-values-concept.html 
sidebar: sidebar 
keywords: rules, specifying, values, cli, parameters, required, optional 
summary: 대부분의 명령에는 하나 이상의 필수 매개 변수 또는 선택적 매개 변수가 포함됩니다. 많은 매개 변수는 값을 지정해야 합니다. CLI에서 값을 지정할 때 적용되는 몇 가지 규칙이 있습니다. 
---
= CLI에서 값을 지정하는 규칙입니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
대부분의 명령에는 하나 이상의 필수 매개 변수 또는 선택적 매개 변수가 포함됩니다. 많은 매개 변수는 값을 지정해야 합니다. CLI에서 값을 지정할 때 적용되는 몇 가지 규칙이 있습니다.

* 값은 숫자, 부울 지정자 또는 텍스트 문자열이거나 사전 정의된 값의 열거 목록 중 한 값을 선택하여 사용할 수 있습니다.
+
일부 매개 변수에는 둘 이상의 값을 쉼표로 구분하여 지정할 수 있습니다. 쉼표로 구분된 값 목록은 따옴표(" ")에 있을 필요가 없습니다. 텍스트, 공백 또는 쿼리 문자(보다 작음 또는 보다 큰 기호로 시작하는 텍스트나 쿼리가 아닌 경우)를 지정할 때는 항상 엔티티를 따옴표로 묶어야 합니다.

* CLI는 물음표(""?")를 해석합니다. 명령을 사용하여 특정 명령에 대한 도움말 정보를 표시합니다.
* 명령 이름, 매개 변수 및 특정 값과 같이 CLI에서 입력하는 일부 텍스트는 대/소문자를 구분하지 않습니다.
+
예를 들어, 'vserver cifs' 명령에 대한 매개 변수 값을 입력하면 대문자 표시가 무시됩니다. 하지만 노드 이름, SVM(스토리지 가상 머신), 애그리게이트, 볼륨, 논리 인터페이스 등과 같은 대부분의 매개 변수 값은 대/소문자를 구분합니다.

* 문자열이나 목록을 사용하는 매개 변수 값을 지우려면 빈 따옴표("") 또는 대시("-")를 지정합니다.
* 파운드 기호로 알려진 해시 기호("#")는 명령줄 입력에 대한 설명을 나타냅니다. 사용된 경우 명령줄의 마지막 매개 변수 뒤에 나타나야 합니다.
+
CLI는 ""#"과 줄 끝 사이의 텍스트를 무시합니다.



다음 예에서는 텍스트 코멘트로 SVM을 작성합니다. 그런 다음 SVM이 수정되어 설명을 삭제합니다.

[listing]
----
cluster1::> vserver create -vserver vs0 -subtype default -rootvolume root_vs0
-aggregate aggr1 -rootvolume-security-style unix -language C.UTF-8 -is-repository false -ipspace ipspaceA -comment "My SVM"
cluster1::> vserver modify -vserver vs0 -comment ""
----
다음 예제에서 ""#" 기호를 사용하는 명령줄 설명은 명령이 수행하는 작업을 나타냅니다.

[listing]
----
cluster1::> security login create -vserver vs0 -user-or-group-name new-admin
-application ssh -authmethod password #This command creates a new user account
----