---
permalink: system-admin/setup-autosupport-task.html 
sidebar: sidebar 
keywords: set, up, autosupport, technical, support, organization, internal, configuration, test 
summary: AutoSupport 정보가 기술 지원 부서 및 내부 지원 조직에 전송되는지 여부와 그 방법을 제어하고 구성이 올바른지 테스트할 수 있습니다. 
---
= AutoSupport를 설정합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
AutoSupport 정보가 기술 지원 부서 및 내부 지원 조직에 전송되는지 여부와 그 방법을 제어하고 구성이 올바른지 테스트할 수 있습니다.

.이 작업에 대해
ONTAP 9.5 이상 릴리즈에서는 AutoSupport를 사용하도록 설정하고 클러스터의 모든 노드에서 해당 구성을 동시에 수정할 수 있습니다. 새 노드가 클러스터에 추가되면 노드가 AutoSupport 클러스터 구성을 자동으로 상속합니다. 각 노드의 구성은 별도로 업데이트할 필요가 없습니다.

[NOTE]
====
ONTAP 9.5부터 system node AutoSupport modify 명령의 범위는 클러스터 전체에 적용됩니다. AutoSupport 구성은 '-node' 옵션이 지정된 경우에도 클러스터의 모든 노드에서 수정됩니다. 이 옵션은 무시되지만 CLI 이전 버전과의 호환성을 위해 유지되었습니다.

ONTAP 9.4 및 이전 릴리스에서 의 범위입니다 `system node autosupport modify` 명령은 노드에 따라 다릅니다. AutoSupport 구성은 클러스터의 각 노드에서 수정해야 합니다.

====
기본적으로 AutoSupport는 각 노드에서 HTTPS 전송 프로토콜을 사용하여 기술 지원 부서에 메시지를 보내도록 설정됩니다.

최상의 보안을 제공하고 모든 최신 AutoSupport 기능을 지원하려면 TLSv1.2와 함께 HTTPS를 사용하거나 AutoSupport 메시지를 안전하게 전달하는 SMTP를 사용해야 합니다.

.단계
. AutoSupport가 활성화되어 있는지 확인합니다.
+
[listing]
----
system node autosupport modify -state enable
----
. 기술 지원 부서에서 AutoSupport 메시지를 받으려면 다음 명령을 사용하십시오.
+
[listing]
----
system node autosupport modify -support enable
----
+
AutoSupport를 AutoSupport OnDemand와 함께 사용하도록 설정하거나 코어 덤프 및 성능 아카이브 파일과 같은 대용량 파일을 기술 지원 또는 지정된 URL에 업로드하려면 이 옵션을 활성화해야 합니다.

. 기술 지원 부서에서 AutoSupport 메시지를 수신할 수 있는 경우 메시지에 사용할 전송 프로토콜을 지정합니다.
+
다음 옵션 중에서 선택할 수 있습니다.

+
|===


| 원하는 작업 | 그런 다음 'system node AutoSupport modify' 명령어의 다음 파라미터를 설정한다... 


 a| 
기본 HTTPS 프로토콜을 사용합니다
 a| 
.. '-transport'를 'https'로 설정합니다.
.. 프록시를 사용하는 경우 프록시 URL로 -proxy-url을 설정합니다. 이 구성은 AutoSupport OnDemand와의 통신 및 대용량 파일 업로드를 지원합니다.




 a| 
SMTP를 사용합니다
 a| 
'-transport'를 'MTP'로 설정합니다.

이 구성은 AutoSupport OnDemand 또는 대용량 파일 업로드를 지원하지 않습니다.

|===
. 내부 지원 조직 또는 지원 파트너가 AutoSupport 메시지를 받도록 하려면 다음 작업을 수행합니다.
+
.. 'system node AutoSupport modify' 명령의 다음 매개 변수를 설정하여 조직의 수신자를 식별합니다.
+
|===


| 이 매개 변수 설정... | 이거면... 


 a| 
'-to'
 a| 
내부 지원 조직에서 주요 AutoSupport 메시지를 받을 최대 5개의 쉼표로 구분된 개별 이메일 주소 또는 배포 목록



 a| 
'-noteto'
 a| 
내부 지원 조직에서 최대 5개의 쉼표로 구분된 개별 이메일 주소 또는 배포 목록을 통해 휴대폰과 기타 모바일 장치용으로 설계된 주요 AutoSupport 메시지의 축약된 버전을 받을 수 있습니다



 a| 
파트너 주소
 a| 
지원 파트너 조직에서 모든 AutoSupport 메시지를 쉼표로 구분하여 최대 5개의 개별 이메일 주소 또는 배포 목록을 받을 수 있습니다

|===
.. 'system node AutoSupport destinations show' 명령을 사용하여 대상을 나열하여 주소가 올바르게 구성되었는지 확인합니다.


. 내부 지원 조직에 메시지를 보내거나 기술 지원 메시지에 대해 SMTP 전송을 선택한 경우 'system node AutoSupport modify' 명령의 다음 매개 변수를 설정하여 SMTP를 구성합니다.
+
** 메일 호스트를 쉼표로 구분하여 하나 이상의 메일 호스트로 설정합니다.
+
최대 5개까지 설정할 수 있습니다.

+
메일 호스트 이름 뒤에 콜론과 포트 번호를 지정하여 각 메일 호스트에 대한 포트 값을 구성할 수 있습니다. 예를 들어, mymailhost.example.com:5678`, 여기서 5678은 메일 호스트의 포트입니다.

** AutoSupport 메시지를 보내는 e-메일 주소로 '-from'을 설정합니다.


. DNS를 구성합니다.
. 필요에 따라 특정 설정을 변경하려면 명령 옵션을 추가합니다.
+
|===


| 이 작업을 수행하려면... | 그런 다음 'system node AutoSupport modify' 명령어의 다음 파라미터를 설정한다... 


 a| 
메시지에서 중요한 데이터를 제거, 마스킹 또는 인코딩하여 개인 데이터를 숨깁니다
 a| 
설정 `-remove-private-data` 를 선택합니다 `true`. 에서 변경한 경우 `false` 를 선택합니다 `true`모든 AutoSupport 기록 및 모든 관련 파일이 삭제됩니다.



 a| 
Periodic AutoSupport 메시지로 성능 데이터 전송을 중지합니다
 a| 
-perf를 false로 설정합니다.

|===
. 'system node AutoSupport show' 명령을 '-node' 매개변수와 함께 사용하여 전체 설정을 확인한다.
. 'system node AutoSupport check show' 명령어를 사용해 AutoSupport 작동을 확인한다.
+
문제가 보고되면 'system node AutoSupport check show-details' 명령어를 사용하여 더 많은 정보를 볼 수 있다.

. AutoSupport 메시지가 전송 및 수신되고 있는지 테스트합니다.
+
.. 'test'로 설정된 '-type' 매개 변수를 사용하여 'system node AutoSupport invoke' 명령을 사용합니다.
+
[listing]
----
cluster1::> system node autosupport invoke -type test -node node1
----
.. NetApp에서 AutoSupport 메시지를 수신하는지 확인합니다.
+
시스템 노드 AutoSupport history show-node local

+
최근 나가는 AutoSupport 메시지의 상태는 모든 해당 프로토콜 대상에 대해 '성공적으로 완료'로 변경되어야 합니다.

.. (선택 사항) 에 대해 구성한 주소의 이메일을 확인하여 AutoSupport 메시지가 내부 지원 조직 또는 지원 파트너에게 전송되도록 합니다 `-to`, `-noteto`, 또는 `-partner-address`  의 매개 변수 `system node autosupport modify` 명령.



