---
permalink: system-admin/sp-bmc-network-config-concept.html 
sidebar: sidebar 
keywords: consideration, sp, bmc, network, configuration, cluster, level, disable, configuration 
summary: 'SP에 대해 클러스터 레벨의 자동 네트워크 구성을 설정할 수 있습니다(권장). 또한 SP 자동 네트워크 구성을 기본값인 사용하지 않도록 설정하고 SP 네트워크 구성을 노드 레벨에서 수동으로 관리할 수도 있습니다. 각 사례별로 몇 가지 고려 사항이 있습니다.' 
---
= SP/BMC 네트워크 구성에 대한 고려 사항
:icons: font
:imagesdir: ../media/


[role="lead"]
SP에 대해 클러스터 레벨의 자동 네트워크 구성을 설정할 수 있습니다(권장). 또한 SP 자동 네트워크 구성을 기본값인 사용하지 않도록 설정하고 SP 네트워크 구성을 노드 레벨에서 수동으로 관리할 수도 있습니다. 각 사례별로 몇 가지 고려 사항이 있습니다.

[NOTE]
====
이 항목은 SP와 BMC 모두에 적용됩니다.

====
SP의 자동 네트워크 구성을 사용하면 SP가 지정된 서브넷의 주소 리소스(IP 주소, 서브넷 마스크 및 게이트웨이 주소 포함)를 사용하여 네트워크를 자동으로 설정할 수 있습니다. SP 자동 네트워크 구성을 사용하면 각 노드의 SP에 IP 주소를 수동으로 할당할 필요가 없습니다. 기본적으로 SP 자동 네트워크 구성은 비활성화되어 있습니다. 구성을 활성화하려면 먼저 클러스터에서 구성에 사용할 서브넷을 정의해야 하기 때문입니다.

SP 자동 네트워크 구성을 사용하도록 설정하면 다음과 같은 시나리오와 고려 사항이 적용됩니다.

* SP를 구성한 적이 없을 경우 SP 자동 네트워크 구성에 지정된 서브넷에 따라 SP 네트워크가 자동으로 구성됩니다.
* 이전에 SP를 수동으로 구성했거나 기존 SP 네트워크 구성이 다른 서브넷을 기반으로 한 경우, 클러스터에 있는 모든 노드의 SP 네트워크는 SP 자동 네트워크 구성에 지정한 서브넷에 따라 재구성됩니다.
+
재구성을 수행하면 SP에 다른 주소가 할당되며, 이는 DNS 구성과 SP 호스트 이름 확인 기능에 영향을 줄 수 있습니다. 따라서 DNS 구성을 업데이트해야 할 수 있습니다.

* 클러스터를 연결하는 노드는 지정된 서브넷을 사용하여 SP 네트워크를 자동으로 구성합니다.
* 'system service-processor network modify' 명령을 사용해도 SP IP 주소를 변경할 수 없습니다.
+
SP 자동 네트워크 구성이 설정된 경우 명령을 사용하면 SP 네트워크 인터페이스를 설정 또는 해제할 수만 있습니다.

+
** SP 자동 네트워크 구성이 이전에 설정된 경우 SP 네트워크 인터페이스를 해제하면 할당된 주소 리소스가 해제되고 서브넷에 반환됩니다.
** SP 네트워크 인터페이스를 해제한 다음 다시 설정하는 경우 SP를 다른 주소로 재구성할 수 있습니다.




SP 자동 네트워크 구성이 비활성화되어 있는 경우(기본값), 다음과 같은 시나리오 및 고려 사항이 적용됩니다.

* SP를 구성되지 않은 경우 SP IPv4 네트워크 구성의 기본값은 IPv4 DHCP를 사용하고 IPv6은 사용되지 않도록 설정됩니다.
+
클러스터에 연결된 노드는 기본적으로 SP 네트워크 구성에 IPv4 DHCP도 사용합니다.

* 'system service-processor network modify' 명령을 사용하면 노드의 SP IP 주소를 구성할 수 있습니다.
+
서브넷에 할당된 주소를 사용하여 SP 네트워크를 수동으로 구성하려고 하면 경고 메시지가 표시됩니다. 경고를 무시하고 수동으로 주소를 할당하면 중복된 주소가 있는 시나리오가 발생할 수 있습니다.



이전에 SP 자동 네트워크 구성을 사용하도록 설정한 후 SP 자동 네트워크 구성을 사용하지 않도록 설정한 경우 다음과 같은 시나리오 및 고려 사항이 적용됩니다.

* SP의 자동 네트워크 구성에 IPv4 주소 제품군이 비활성화되어 있으면 SP IPv4 네트워크는 기본적으로 DHCP를 사용합니다. 또한 'system service-processor network modify' 명령을 사용하면 개별 노드의 SP IPv4 구성을 수정할 수 있습니다.
* SP의 자동 네트워크 구성에 IPv6 주소 제품군이 비활성화되어 있으면 SP IPv6 네트워크도 비활성화되고, 'system service-processor network modify' 명령을 사용하면 개별 노드에 대해 SP IPv6 구성을 설정 및 수정할 수 있습니다.

