---
permalink: system-admin/sp-cli-system-console-sessions-concept.html 
sidebar: sidebar 
keywords: relationship, sp, cli, console, system, sessions, shell, environment, login, authentication 
summary: SP CLI 세션을 열어 노드를 원격으로 관리하고 별도의 SP 콘솔 세션을 열어 노드 콘솔에 액세스할 수 있습니다. SP 콘솔 세션은 동시 시스템 콘솔 세션에 표시되는 출력을 미러링합니다. SP와 시스템 콘솔에는 독립 로그인 인증이 있는 독립 셸 환경이 있습니다. 
---
= SP CLI, SP 콘솔 및 시스템 콘솔 세션의 관계
:icons: font
:imagesdir: ../media/


[role="lead"]
SP CLI 세션을 열어 노드를 원격으로 관리하고 별도의 SP 콘솔 세션을 열어 노드 콘솔에 액세스할 수 있습니다. SP 콘솔 세션은 동시 시스템 콘솔 세션에 표시되는 출력을 미러링합니다. SP와 시스템 콘솔에는 독립 로그인 인증이 있는 독립 셸 환경이 있습니다.

SP CLI, SP 콘솔 및 시스템 콘솔 세션의 연결 방식을 이해하면 노드를 원격으로 관리하는 데 도움이 됩니다. 다음은 세션 간의 관계에 대해 설명합니다.

* 한 번에 하나의 관리자만 SP CLI 세션에 로그인할 수 있지만 SP를 사용하면 SP CLI 세션과 별도의 SP 콘솔 세션을 동시에 열 수 있습니다.
+
SP CLI는 SP 프롬프트('S>')로 표시됩니다. SP CLI 세션에서 SP의 system console 명령을 사용하여 SP 콘솔 세션을 시작할 수 있습니다. 동시에 SSH를 통해 별도의 SP CLI 세션을 시작할 수 있습니다. Ctrl+D를 눌러 SP 콘솔 세션을 종료하면 SP CLI 세션으로 자동으로 돌아갑니다. SP CLI 세션이 이미 있는 경우 기존 SP CLI 세션을 종료할지 묻는 메시지가 표시됩니다. ""y""를 입력하면 기존 SP CLI 세션이 종료되므로 SP 콘솔에서 SP CLI로 돌아갈 수 있습니다. 이 작업은 SP 이벤트 로그에 기록됩니다.

+
SSH를 통해 연결된 ONTAP CLI 세션에서 다른 노드의 ONTAP 'system node run-console' 명령을 실행하여 노드의 시스템 콘솔로 전환할 수 있습니다.

* 보안상의 이유로 SP CLI 세션과 시스템 콘솔 세션에는 서로 독립적인 로그인 인증이 있습니다.
+
SP CLI에서 SP 콘솔 세션을 시작할 때(SP의 'system console' 명령 사용) 시스템 콘솔 자격 증명을 묻는 메시지가 표시됩니다. Ctrl+G를 눌러 시스템 콘솔 세션에서 SP CLI에 액세스하면 SP CLI 자격 증명을 묻는 메시지가 표시됩니다.

* SP 콘솔 세션과 시스템 콘솔 세션에는 독립적인 셸 환경이 있습니다.
+
SP 콘솔 세션은 동시 시스템 콘솔 세션에 표시되는 출력을 미러링합니다. 하지만 동시 시스템 콘솔 세션은 SP 콘솔 세션을 미러링하지 않습니다.

+
SP 콘솔 세션은 동시 SSH 세션의 출력을 미러링하지 않습니다.


