---
permalink: system-admin/troubleshoot-web-access-problems-concept.html 
sidebar: sidebar 
keywords: troubleshoot, web, services, access, problems, lif, firewall, policy, protocol, engin, digital, certificate, user, access, authorization 
summary: 구성 오류로 인해 웹 서비스 액세스 문제가 발생합니다. LIF, 방화벽 정책, 웹 프로토콜 엔진, 웹 서비스, 디지털 인증서를 확인하여 오류를 해결할 수 있습니다. 사용자 액세스 권한이 모두 올바르게 구성되어 있습니다. 
---
= 웹 서비스 액세스 문제를 해결합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
구성 오류로 인해 웹 서비스 액세스 문제가 발생합니다. LIF, 방화벽 정책, 웹 프로토콜 엔진, 웹 서비스, 디지털 인증서를 확인하여 오류를 해결할 수 있습니다. 사용자 액세스 권한이 모두 올바르게 구성되어 있습니다.

다음 표는 웹 서비스 구성 오류를 식별하고 해결하는 데 도움이 됩니다.

|===
| 이 액세스 문제는... | 이 구성 오류로 인해 발생합니다. | 오류를 해결하려면... 


 a| 
웹 서비스에 액세스하려고 하면 웹 브라우저에서 "연결할 수 없음" 또는 "연결 실패" 오류가 반환됩니다.
 a| 
LIF가 잘못 구성될 수 있습니다.
 a| 
웹 서비스를 제공하는 LIF를 ping할 수 있는지 확인합니다.

[NOTE]
====
LIF를 ping하는 데 'network ping' 명령을 사용합니다. 네트워크 구성에 대한 자세한 내용은 _Network Management Guide_를 참조하십시오.

====


 a| 
방화벽이 잘못 구성되었을 수 있습니다.
 a| 
HTTP 또는 HTTPS를 지원하도록 방화벽 정책을 설정하고 웹 서비스를 제공하는 LIF에 정책이 할당되도록 합니다.

[NOTE]
====
'시스템 서비스 방화벽 정책' 명령을 사용하여 방화벽 정책을 관리합니다. 'network interface modify' 명령을 '-firewall-policy' 매개 변수와 함께 사용하여 정책을 LIF와 연결합니다.

====


 a| 
웹 프로토콜 엔진이 비활성화되었을 수 있습니다.
 a| 
웹 서비스에 액세스할 수 있도록 웹 프로토콜 엔진이 활성화되어 있는지 확인합니다.

[NOTE]
====
'시스템 서비스 웹' 명령을 사용하여 클러스터의 웹 프로토콜 엔진을 관리합니다.

====


 a| 
웹 서비스에 액세스하려고 하면 웹 브라우저에서 "찾을 수 없음" 오류가 반환됩니다.
 a| 
웹 서비스가 비활성화되었을 수 있습니다.
 a| 
액세스를 허용할 각 웹 서비스가 개별적으로 설정되어 있는지 확인합니다.

[NOTE]
====
'vserver services web modify' 명령을 사용하여 액세스를 위한 웹 서비스를 활성화할 수 있습니다.

====


 a| 
웹 브라우저가 사용자의 계정 이름 및 암호를 사용하여 웹 서비스에 로그인하지 못합니다.
 a| 
사용자를 인증할 수 없거나, 액세스 방법이 올바르지 않거나, 사용자가 웹 서비스에 액세스할 수 있는 권한이 없습니다.
 a| 
사용자 계정이 존재하고 올바른 액세스 방법 및 인증 방법으로 구성되었는지 확인합니다. 또한 사용자의 역할이 웹 서비스에 액세스할 수 있는 권한이 있는지 확인합니다.

[NOTE]
====
'보안 로그인' 명령어를 이용하여 사용자 계정과 접속 방법 및 인증 방식을 관리할 수 있다. ONTAP API 웹 서비스에 액세스하려면 "ontapi" 액세스 방법이 필요합니다. 다른 모든 웹 서비스에 액세스하려면 http 접근 방식이 필요합니다. 'vserver services web access' 명령을 사용하여 웹 서비스에 대한 역할의 액세스를 관리합니다.

====


 a| 
HTTPS를 사용하여 웹 서비스에 연결하면 웹 브라우저에서 연결이 중단되었음을 나타냅니다.
 a| 
웹 서비스를 제공하는 클러스터 또는 SVM(스토리지 가상 머신)에서 SSL을 사용하지 못할 수 있습니다.
 a| 
클러스터 또는 SVM에 SSL이 활성화되어 있고 디지털 인증서가 유효한지 확인합니다.

[NOTE]
====
'Security SSL' 명령어를 이용하여 HTTP 서버의 SSL 설정을 관리하고 'Security certificate show' 명령어를 이용하여 디지털 인증서 정보를 출력한다.

====


 a| 
HTTPS를 사용하여 웹 서비스에 연결하면 웹 브라우저에서 연결을 신뢰할 수 없음을 나타냅니다.
 a| 
자체 서명된 디지털 인증서를 사용 중일 수 있습니다.
 a| 
클러스터 또는 SVM과 관련된 디지털 인증서가 신뢰할 수 있는 CA에 서명되었는지 확인합니다.

[NOTE]
====
'Security certificate generate -csr' 명령어를 이용하여 디지털 인증서 서명 요청과 'security certificate install' 명령어를 이용하여 CA 서명 디지털 인증서를 설치한다. 웹 서비스를 제공하는 클러스터 또는 SVM의 SSL 구성을 관리하려면 '보안 SSL' 명령을 사용합니다.

====
|===