---
permalink: system-admin/troubleshoot-autosupport-http-https-task.html 
sidebar: sidebar 
keywords: troubleshoot, autosupport, message, delivery, http, https, check, settings, resolve, problem 
summary: 시스템에서 예상된 AutoSupport 메시지를 전송하지 않고 HTTP 또는 HTTPS를 사용하는 경우 여러 설정을 확인하여 문제를 해결할 수 있습니다. 
---
= HTTP 또는 HTTPS를 통한 AutoSupport 메시지 전송 문제를 해결합니다
:icons: font
:imagesdir: ../media/


[role="lead"]
시스템이 예상 AutoSupport 메시지를 전송하지 않고 HTTP 또는 HTTPS를 사용하고 있거나 자동 업데이트 기능이 작동하지 않는 경우 여러 설정을 확인하여 문제를 해결할 수 있습니다.

기본 네트워크 연결 및 DNS 조회를 확인해야 합니다.

* 노드 관리 LIF가 운영 및 관리 상태이어야 합니다.
* 클러스터 관리 LIF(노드의 LIF가 아님)에서 동일한 서브넷에 있는 기능 호스트를 ping할 수 있어야 합니다.
* 클러스터 관리 LIF에서 서브넷 외부의 기능 호스트를 Ping할 수 있어야 합니다.
* IP 주소가 아닌 호스트의 이름을 사용하여 클러스터 관리 LIF에서 서브넷 외부의 기능 호스트를 Ping할 수 있어야 합니다.


이러한 단계는 AutoSupport가 메시지를 생성할 수 있지만 HTTP 또는 HTTPS를 통해 메시지를 전달할 수 없는 경우에 적용됩니다.

오류가 발생하거나 이 절차의 단계를 완료할 수 없는 경우 다음 단계로 진행하기 전에 문제를 확인하고 해결하십시오.

.단계
. AutoSupport 하위 시스템의 세부 상태를 표시합니다.
+
'시스템 노드 AutoSupport check show-details

+
여기에는 테스트 메시지를 전송하고 AutoSupport 구성 설정에서 발생할 수 있는 오류 목록을 제공하여 AutoSupport 대상에 대한 연결을 확인하는 작업이 포함됩니다.

. 노드 관리 LIF의 상태를 확인합니다.
+
'network interface show-home-node local-role node-mgmt-fields vserver, lif, status-oper, status-admin, address, role'

+
'돌격대'와 '상태-관리자' 필드는 '위로'가 되어야 합니다.

. 나중에 사용할 수 있도록 SVM 이름, LIF 이름 및 LIF IP 주소를 기록합니다.
. DNS가 올바르게 설정 및 구성되었는지 확인합니다.
+
'vserver services name-service dns show'

. AutoSupport 메시지가 반환한 모든 오류를 해결합니다.
+
'System node AutoSupport history show -node * -fields node, seq -num, destination, last-update, status, error'

+
오류가 디지털 인증서 관련 문제를 나타내는 경우 기술 지원 부서에 문의하십시오.

. 클러스터가 필요한 서버와 인터넷에 모두 액세스할 수 있는지 확인합니다.
+
.. 'network traceroute-lif node-management_LIF-destination DNS server
.. 네트워크 traceroute-lif node_management_LIF-destination support.netapp.com`
+
[NOTE]
====
주소인 upport.netapp.com` 자체는 ping/traceroute에 응답하지 않지만, per-hop 정보는 가치가 있다.

====
.. '시스템 노드 AutoSupport show-fields proxy-url
.. 'network traceroute-node_management_LIF-destination proxy_url


+
이러한 경로 중 하나라도 작동하지 않는 경우, 대부분의 타사 네트워크 클라이언트에 있는 ""traceroute"" 또는 ""tracert""" 유틸리티를 사용하여 클러스터와 동일한 서브넷의 작동 호스트에서 동일한 경로를 시도해 보십시오. 이렇게 하면 문제가 네트워크 구성에 있는지 또는 클러스터 구성에 있는지 여부를 확인할 수 있습니다.

. AutoSupport 전송 프로토콜에 HTTPS를 사용하는 경우 HTTPS 트래픽이 네트워크를 종료할 수 있는지 확인합니다.
+
.. 클러스터 관리 LIF와 동일한 서브넷에 있는 웹 클라이언트를 구성합니다.
+
동일한 프록시 서버, 사용자 이름, 암호 및 포트 사용을 포함하여 모든 구성 매개 변수가 AutoSupport 구성과 동일한 값인지 확인합니다.

.. 웹 클라이언트를 사용하여 '+https://support.netapp.com+` 액세스합니다.
+
액세스가 성공적으로 이루어져야 합니다. 그렇지 않은 경우 모든 방화벽이 HTTPS 및 DNS 트래픽을 허용하도록 올바르게 구성되어 있고 프록시 서버가 올바르게 구성되어 있는지 확인하십시오. support.netapp.com 에 대한 정적 이름 확인을 구성하는 방법에 대한 자세한 내용은 문서 를 참조하십시오 https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/How_would_a_HOST_entry_be_added_in_ONTAP_for_support.netapp.com%3F["ONTAP for support.netapp.com? 에서 호스트 항목을 추가하는 방법은"].



. ONTAP 9.10.1부터 자동 업데이트 기능을 활성화한 경우 다음 추가 URL에 HTTPS 연결이 있는지 확인합니다.
+
** https://support-sg-emea.netapp.com 으로 문의하십시오
** https://support-sg-naeast.netapp.com 으로 문의하십시오
** https://support-sg-nawest.netapp.com 으로 문의하십시오



