---
permalink: authentication/configure-ldap-server-access-task.html 
sidebar: sidebar 
keywords: configure, ldap, server access 
summary: LDAP 계정이 SVM에 액세스하려면 SVM에 대한 LDAP 서버 액세스를 구성해야 합니다. SVM services name-service LDAP client create 명령을 사용하여 SVM에 LDAP 클라이언트 구성을 생성할 수 있습니다. 그런 다음 vserver services name-service ldap create 명령을 사용하여 LDAP 클라이언트 구성을 SVM과 연결할 수 있습니다. 
---
= LDAP 서버 액세스를 구성합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
LDAP 계정이 SVM에 액세스하려면 SVM에 대한 LDAP 서버 액세스를 구성해야 합니다. SVM에서 'vserver services name-service ldap client create' 명령을 사용하여 LDAP 클라이언트 구성을 생성할 수 있습니다. 그런 다음 "vserver services name-service ldap create" 명령을 사용하여 LDAP 클라이언트 구성을 SVM과 연결할 수 있습니다.

.필요한 것
* 을(를) 설치해야 합니다 link:install-ca-signed-server-digital-certificate-task.html["CA 서명 서버 디지털 인증서"] SVM에서.
* 이 작업을 수행하려면 클러스터 또는 SVM 관리자여야 합니다.


.이 작업에 대해
대부분의 LDAP 서버는 ONTAP에서 제공하는 기본 스키마를 사용할 수 있습니다.

* MS-AD-BIS(대부분의 Windows 2012 이상 AD 서버에 대한 기본 스키마)
* AD-IDMU(Windows 2008, Windows 2012 이상 AD 서버)
* AD-SFU(Windows 2003 및 이전 AD 서버)
* RFC-2307(UNIX LDAP 서버)


그렇지 않으면 기본 스키마를 사용하는 것이 가장 좋습니다. 이 경우 기본 스키마를 복사하고 복사본을 수정하여 고유한 스키마를 만들 수 있습니다. 자세한 내용은 다음 문서를 참조하십시오.

* link:../nfs-config/index.html["NFS 구성"]
* https://["NetApp 기술 보고서 4835: ONTAP에서 LDAP를 구성하는 방법"^]


.단계
. SVM에서 LDAP 클라이언트 구성을 생성합니다. 'vserver services name-service LDAP client create-vserver SVM_name-client-config client_configuration-servers ldap_server_IPs-schema schema-use-start-tls true|false'
+
[NOTE]
====
시작 TLS는 데이터 SVM에 대한 액세스에만 지원됩니다. 관리 SVM에 대한 액세스는 지원되지 않습니다.

====
+
전체 명령 구문은 을 참조하십시오 link:config-worksheets-reference.html["워크시트"].

+
다음 명령을 실행하면 SVM 'engData'에 corp라는 LDAP 클라이언트 구성이 생성됩니다. 클라이언트는 IP 주소 172.160.0.100과 172.16.0.101로 LDAP 서버에 익명으로 바인딩합니다. 클라이언트는 RFC-2307 스키마를 사용하여 LDAP 쿼리를 만듭니다. 클라이언트와 서버 간의 통신은 시작 TLS를 사용하여 암호화됩니다.

+
[listing]
----
cluster1::>vserver services name-service ldap client create
-vserver engData -client-config corp -servers 172.16.0.100,172.16.0.101 -schema RFC-2307 -use-start-tls true
----
+
[NOTE]
====
ONTAP 9.2부터 -ldap-servers 필드가 -servers 필드를 대체합니다. 이 새 필드는 LDAP 서버의 호스트 이름 또는 IP 주소를 사용할 수 있습니다.

====
. LDAP 클라이언트 구성을 SVM과 연결합니다. 'vserver services name-service ldap create-vserver SVM_name-client-config client_configuration-client-enabled true|false'
+
전체 명령 구문은 을 참조하십시오 link:config-worksheets-reference.html["워크시트"].

+
다음 명령은 LDAP 클라이언트 구성 Corp를 SVM "engData"와 연결하고 SVM에서 LDAP 클라이언트를 활성화합니다.

+
[listing]
----
cluster1::>vserver services name-service ldap create -vserver engData -client-config corp -client-enabled true
----
+
[NOTE]
====
ONTAP 9.2부터 'vserver services name-service ldap create' 명령은 자동 구성 검증을 수행하고 ONTAP가 이름 서버에 연결할 수 없는 경우 오류 메시지를 보고합니다.

====
. vserver services name-service ldap check 명령을 사용하여 이름 서버의 상태를 확인합니다.
+
다음 명령을 실행하면 SVM vs0에서 LDAP 서버를 검증합니다.

+
[listing]
----
cluster1::> vserver services name-service ldap check -vserver vs0

| Vserver: vs0                                                |
| Client Configuration Name: c1                               |
| LDAP Status: up                                             |
| LDAP Status Details: Successfully connected to LDAP server "10.11.12.13".                                              |
----
+
이름 서비스 확인 명령은 ONTAP 9.2부터 사용할 수 있습니다.


