---
permalink: authentication/configure-saml-authentication-task.html 
sidebar: sidebar 
keywords: configure, saml authentication 
summary: 'ONTAP 9.3부터 웹 서비스에 대한 SAML(Security Assertion Markup Language) 인증을 구성할 수 있습니다. SAML 인증이 구성 및 설정되면 사용자는 Active Directory 및 LDAP와 같은 디렉터리 서비스 공급자 대신 외부 ID 공급자(IDP)에 의해 인증됩니다.' 
---
= SAML 인증을 구성합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9.3부터 웹 서비스에 대한 SAML(Security Assertion Markup Language) 인증을 구성할 수 있습니다. SAML 인증이 구성 및 설정되면 사용자는 Active Directory 및 LDAP와 같은 디렉터리 서비스 공급자 대신 외부 ID 공급자(IDP)에 의해 인증됩니다.

.무엇을 &#8217;필요로 할거야
* SAML 인증을 위해 IDP를 구성해야 합니다.
* IDP URI가 있어야 합니다.


.이 작업에 대해
* SAML 인증은 'http' 및 'ontapi' 애플리케이션에만 적용됩니다.
+
http와 ontapi 애플리케이션은 서비스 프로세서 인프라, ONTAP API, System Manager 등의 웹 서비스에서 사용됩니다.

* SAML 인증은 관리 SVM에 액세스하는 경우에만 적용됩니다.


.단계
. SAML 구성을 생성하여 ONTAP가 IDP 메타데이터에 액세스할 수 있도록 합니다.
+
SECURN SAML-SP CREATE-IDP-Uri IDP_Uri-SP-HOST ONTAP_HOST_NAME'

+
IDP_Uri는 IDP 메타데이터를 다운로드할 수 있는 IDP 호스트의 FTP 또는 HTTP 주소입니다.

+
'ontap_host_name'은 SAML 서비스 공급자 호스트의 호스트 이름 또는 IP 주소이며, 이 경우 ONTAP 시스템입니다. 기본적으로 클러스터 관리 LIF의 IP 주소가 사용됩니다.

+
ONTAP 서버 인증서 정보를 선택적으로 제공할 수 있습니다. 기본적으로 ONTAP 웹 서버 인증서 정보가 사용됩니다.

+
[listing]
----
cluster_12::> security saml-sp create -idp-uri https://scspr0235321001.gdl.englab.netapp.com/idp/shibboleth -verify-metadata-server false

Warning: This restarts the web server. Any HTTP/S connections that are active
         will be disrupted.
Do you want to continue? {y|n}: y
[Job 179] Job succeeded: Access the SAML SP metadata using the URL:
https://10.63.56.150/saml-sp/Metadata

Configure the IdP and Data ONTAP users for the same directory server domain to ensure that users are the same for different authentication methods. See the "security login show" command for the Data ONTAP user configuration.
----
+
ONTAP 호스트 메타데이터에 액세스할 수 있는 URL이 표시됩니다.

. IDP 호스트에서 ONTAP 호스트 메타데이터를 사용하여 IDP를 구성합니다.
+
IDP 구성에 대한 자세한 내용은 IDP 설명서를 참조하십시오.

. SAML 구성 활성화:
+
'SAML-SP 수정-활성화 true'

+
'http' 또는 'ontapi' 애플리케이션에 액세스하는 기존 사용자는 자동으로 SAML 인증을 위해 구성됩니다.

. SAML이 구성된 후 'http' 또는 'ontapi' 애플리케이션에 대한 사용자를 생성하려면 SAML을 새 사용자의 인증 방법으로 지정합니다.
+
.. SAML 인증을 사용하여 새 사용자에 대한 로그인 방법을 생성합니다. '보안 로그인 생성 - 사용자 - 또는 - 그룹 - 이름 user_name - application [http|ontapi] - authentication - method SAML - vserver svm_name'
+
[listing]
----
cluster_12::> security login create -user-or-group-name admin1 -application http -authentication-method saml -vserver  cluster_12
----
.. 사용자 항목이 생성되었는지 확인합니다: + '보안 로그인 표시'
+
[listing]
----
cluster_12::> security login show

Vserver: cluster_12
                                                                 Second
User/Group                 Authentication                 Acct   Authentication
Name           Application Method        Role Name        Locked Method
-------------- ----------- ------------- ---------------- ------ --------------
admin          console     password      admin            no     none
admin          http        password      admin            no     none
admin          http        saml          admin            -      none
admin          ontapi      password      admin            no     none
admin          ontapi      saml          admin            -      none
admin          service-processor
                           password      admin            no     none
admin          ssh         password      admin            no     none
admin1         http        password      backup           no     none
**admin1         http        saml          backup           -      none**
----




http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-cmpr/GUID-5CB10C70-AC11-41C0-8C16-B4D0DF916E9B.html["ONTAP 9 명령"]
