---
permalink: authentication/create-svm-user-accounts-task.html 
sidebar: sidebar 
keywords: create, login accounts 
summary: 로컬 또는 원격 클러스터 및 SVM 관리자 계정을 활성화할 수 있습니다. 로컬 계정은 계정 정보, 공개 키 또는 보안 인증서가 스토리지 시스템에 상주하는 계정입니다. AD 계정 정보는 도메인 컨트롤러에 저장됩니다. LDAP 및 NIS 계정은 LDAP 및 NIS 서버에 상주합니다. 
---
= 로그인 계정 생성 개요
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
로컬 또는 원격 클러스터 및 SVM 관리자 계정을 활성화할 수 있습니다. 로컬 계정은 계정 정보, 공개 키 또는 보안 인증서가 스토리지 시스템에 상주하는 계정입니다. AD 계정 정보는 도메인 컨트롤러에 저장됩니다. LDAP 및 NIS 계정은 LDAP 및 NIS 서버에 상주합니다.



== 클러스터 및 SVM 관리자

클러스터 관리자는 _ 클러스터에 대한 admin SVM에 액세스합니다. 클러스터 설정 시 admin이라는 예약 이름의 클러스터 관리자와 SVM 관리자가 자동으로 생성됩니다.

기본 'admin' 역할을 가진 클러스터 관리자는 전체 클러스터와 리소스를 관리할 수 있습니다. 클러스터 관리자는 필요에 따라 서로 다른 역할을 가진 추가 클러스터 관리자를 생성할 수 있습니다.

SVM 관리자는 _ 데이터 SVM에 액세스합니다. 클러스터 관리자가 필요에 따라 데이터 SVM 및 SVM 관리자를 생성합니다.

SVM 관리자는 기본적으로 'vsadmin' 역할이 할당됩니다. 클러스터 관리자는 필요에 따라 SVM 관리자에게 다양한 역할을 할당할 수 있습니다.



=== 명명 규칙

다음 일반 이름은 원격 클러스터 및 SVM 관리자 계정에 사용할 수 없습니다.

* "아담"
* "출력함"
* "CLI"
* "데몬"
* "FTP"
* "게임"
* "중지"
* "lp"
* "메일"
* "남자"
* "나루트"
* "NetApp"
* "뉴스"
* "없음"
* "연산자"
* "루트"
* "종료"
* "sshd"
* "동기화"
* "시스템"
* "우프"
* "www"




== 병합된 역할

동일한 사용자에 대해 여러 원격 계정을 사용하도록 설정하면 계정에 지정된 모든 역할의 조합이 사용자에게 할당됩니다. 즉, LDAP 또는 NIS 계정에 vsadmin 역할이 할당되고 같은 사용자의 AD 그룹 계정에 vsadmin-volume 역할이 할당되면 AD 사용자는 보다 포괄적인 vsadmin 기능으로 로그인합니다. 역할은 _ 병합 _ 이라고 합니다.
