---
permalink: authentication/dynamic-authorization-overview.html 
sidebar: sidebar 
keywords: dynamic, authorization, framework, security, login, ssh 
summary: 동적 권한 부여 프레임워크를 구성하여 SSH 로그인의 보안을 강화하고 의심스러운 상황에서 특정 명령의 실행을 제한합니다. 
---
= 동적 인증 개요
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9.15.1부터 관리자는 동적 권한 부여를 구성 및 활성화하여 ONTAP에 대한 원격 액세스의 보안을 강화하는 한편 악의적인 행위자로 인해 발생할 수 있는 잠재적인 손상을 완화할 수 있습니다. ONTAP 9.15.1에서는 동적 권한 부여가 사용자에게 보안 점수를 할당하는 초기 프레임워크를 제공하며, 사용자의 활동이 의심스러운 경우 추가 권한 검사를 통해 사용자에게 문제를 주거나 작업을 완전히 거부할 수 있습니다. 관리자는 규칙을 만들고 신뢰 점수를 할당하며 제한 명령을 사용하여 특정 작업이 허용되거나 거부되는 시기를 결정할 수 있습니다. 관리자는 클러스터 전체 또는 개별 스토리지 VM에 대해 동적 권한 부여를 활성화할 수 있습니다.



== 동적 권한 부여 작동 방식

동적 권한 부여는 신뢰 점수 부여 시스템을 사용하여 권한 부여 정책에 따라 사용자에게 다른 신뢰 수준을 할당합니다. 사용자의 신뢰 수준에 따라 사용자가 수행하는 작업을 허용 또는 거부하거나 추가 인증을 요구하는 메시지가 표시될 수 있습니다.

link:configure-dynamic-authorization.html["동적 권한 부여를 사용자 지정합니다"]기준 점수 가중치 및 기타 동적 권한 부여 속성을 구성하는 방법에 대한 자세한 내용은 을 참조하십시오.



=== 신뢰할 수 있는 장치

동적 권한 부여가 사용 중인 경우 신뢰할 수 있는 장치의 정의는 사용자가 인증 방법 중 하나로 공개 키 인증을 사용하여 ONTAP에 로그인하는 데 사용하는 장치입니다. 해당 사용자만 해당 개인 키를 소유하므로 장치를 신뢰할 수 있습니다.



=== 동적 권한 부여의 예입니다

볼륨을 삭제하려고 하는 세 명의 다른 사용자의 예를 들어 보십시오. 작업을 수행하려고 하면 각 사용자에 대한 위험 등급이 검사됩니다.

* 첫 번째 사용자는 이전 인증 실패가 거의 없는 신뢰할 수 있는 장치에서 로그인하므로 위험 등급이 낮아지며 추가 인증 없이 작업이 허용됩니다.
* 두 번째 사용자는 이전 인증 실패의 비율이 보통인 신뢰할 수 있는 장치에서 로그인하므로 위험 등급이 보통입니다. 작업을 허용하기 전에 추가 인증을 요청하는 메시지가 표시됩니다.
* 세 번째 사용자는 이전 인증 실패의 비율이 높은 신뢰할 수 없는 장치에서 로그인하므로 위험 등급이 높으므로 작업이 허용되지 않습니다.


.다음 단계
* link:enable-disable-dynamic-authorization.html["동적 권한 부여를 사용하거나 사용하지 않습니다"]
* link:configure-dynamic-authorization.html["동적 권한 부여를 사용자 지정합니다"]

