---
permalink: authentication/enable-ad-users-groups-access-cluster-svm-task.html 
sidebar: sidebar 
keywords: configure, active directory, domain, controller access, authentication tunnel, SMB server, create, svm, computer, account, domain, cifs server 
summary: AD 계정이 SVM에 액세스하려면 먼저 클러스터 또는 SVM에 대한 AD 도메인 컨트롤러 액세스를 구성해야 합니다. 데이터 SVM을 위해 SMB 서버를 이미 구성한 경우, SVM을 클러스터에 대한 AD 액세스를 위한 게이트웨이 또는 터널로 구성할 수 있습니다. SMB 서버를 구성하지 않은 경우 AD 도메인에서 SVM에 대한 컴퓨터 계정을 생성할 수 있습니다. 
---
= Active Directory 도메인 컨트롤러 액세스 개요 구성
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
AD 계정이 SVM에 액세스하려면 먼저 클러스터 또는 SVM에 대한 AD 도메인 컨트롤러 액세스를 구성해야 합니다. 데이터 SVM을 위해 SMB 서버를 이미 구성한 경우, SVM을 클러스터에 대한 AD 액세스를 위한 게이트웨이 또는 _tunnel_로 구성할 수 있습니다. SMB 서버를 구성하지 않은 경우 AD 도메인에서 SVM에 대한 컴퓨터 계정을 생성할 수 있습니다.

ONTAP는 다음과 같은 도메인 컨트롤러 인증 서비스를 지원합니다.

* Kerberos
* LDAP를 지원합니다
* Netlogon
* 로컬 보안 기관(LSA)


ONTAP는 보안 Netlogon 연결을 위해 다음 세션 키 알고리즘을 지원합니다.

|===


| 세션 키 알고리즘입니다 | 에서 사용 가능... 


| HMAC-SHA256, AES(Advanced Encryption Standard) 기반 | ONTAP 9.10.1 이상 


| Des 및 HMAC-MD5(강력한 키가 설정된 경우) | 모든 ONTAP 9 릴리스 
|===
ONTAP 9.10.1 이상에서 Netlogon 보안 채널 설정 중에 AES 세션 키를 사용하려면 다음 명령을 사용하여 해당 키를 활성화해야 합니다.

'cifs security modify -vserver vs1-aes-enabled-for-netlogon-channel true'

기본값은 ""false""입니다.

9.10.1 이전의 ONTAP 릴리스에서 도메인 컨트롤러가 보안 Netlogon 서비스에 AES를 적용할 경우 연결이 실패합니다. 도메인 컨트롤러는 이러한 릴리스에서 ONTAP과 강력한 키 연결을 허용하도록 구성해야 합니다.



== 인증 터널을 구성합니다

데이터 SVM을 위해 SMB 서버를 이미 구성한 경우 'security login domain-tunnel create' 명령을 사용하여 SVM을 게이트웨이로 구성하거나, AD에서 클러스터에 액세스하도록 _tunnel_을 사용할 수 있습니다.

.시작하기 전에
* 데이터 SVM을 위해 SMB 서버를 구성해야 합니다.
* 클러스터의 admin SVM에 액세스하려면 AD 도메인 사용자 계정을 활성화해야 합니다.
* 이 작업을 수행하려면 클러스터 관리자여야 합니다.


ONTAP 9.10.1부터 AD 액세스를 위한 SVM 게이트웨이(도메인 터널)가 있는 경우 AD 도메인에서 NTLM을 비활성화한 경우 관리자 인증에 Kerberos를 사용할 수 있습니다. 이전 릴리즈에서는 SVM 게이트웨이에 대한 관리자 인증을 사용하여 Kerberos를 지원하지 않았습니다. 이 기능은 기본적으로 사용할 수 있으며 구성이 필요하지 않습니다.


NOTE: Kerberos 인증은 항상 먼저 시도됩니다. 오류가 발생하면 NTLM 인증이 시도됩니다.

.단계
. 클러스터에 대한 AD 도메인 컨트롤러 액세스를 위한 인증 터널로 SMB 지원 데이터 SVM 구성:
+
`security login domain-tunnel create -vserver _svm_name_`

+
전체 명령 구문은 을 참조하십시오 link:config-worksheets-reference.html["워크시트"].

+
[NOTE]
====
사용자가 인증을 받으려면 SVM이 실행 중이어야 합니다.

====
+
다음 명령은 SMB 지원 데이터 SVM ""engData""를 인증 터널로 구성합니다.

+
[listing]
----
cluster1::>security login domain-tunnel create -vserver engData
----




== 도메인에서 SVM 컴퓨터 계정을 생성합니다

데이터 SVM용으로 SMB 서버를 구성하지 않은 경우 'vserver active-directory create' 명령을 사용하여 도메인의 SVM에 대한 컴퓨터 계정을 생성할 수 있습니다.

.이 작업에 대해
'vserver active-directory create' 명령을 입력하면 도메인의 지정된 조직 단위에 컴퓨터를 추가할 수 있는 충분한 권한이 있는 AD 사용자 계정에 대한 자격 증명을 제공하라는 메시지가 표시됩니다. 계정의 암호는 비워둘 수 없습니다.

.시작하기 전에
이 작업을 수행하려면 클러스터 또는 SVM 관리자여야 합니다.

.단계
. AD 도메인에서 SVM을 위한 컴퓨터 계정을 생성합니다.
+
'vserver active-directory create-vserver_SVM_name_-account-name_NetBIOS_account_name_-domain_domain_-ou_조직_unit_'

+
전체 명령 구문은 을 참조하십시오 link:config-worksheets-reference.html["워크시트"].

+
다음 명령을 실행하면 SVM ""engData"" 도메인인 ""example.com`"""ADSERVER1""이라는 컴퓨터 계정이 생성됩니다. 명령을 입력한 후 AD 사용자 계정 자격 증명을 입력하라는 메시지가 표시됩니다.

+
[listing]
----
cluster1::>vserver active-directory create -vserver engData -account-name ADSERVER1 -domain example.com

In order to create an Active Directory machine account, you must supply the name and password of a Windows account with sufficient privileges to add computers to the "CN=Computers" container within the "example.com" domain.

Enter the user name: Administrator

Enter the password:
----

