---
permalink: authentication/enable-ssh-public-key-accounts-task.html 
sidebar: sidebar 
keywords: enable, ssh, public key, accounts 
summary: 보안 로그인 create 명령을 사용하여 관리자 계정이 SSH 공개 키로 admin 또는 data SVM에 액세스할 수 있도록 할 수 있습니다. 
---
= SSH 공개 키 계정을 활성화합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
'Security login create' 명령을 사용하면 관리자 계정이 SSH 공개 키로 admin 또는 data SVM에 액세스할 수 있습니다.

.필요한 것
이 작업을 수행하려면 클러스터 관리자여야 합니다.

.이 작업에 대해
* 계정이 SVM에 액세스하려면 먼저 공개 키를 계정에 연결해야 합니다.
+
xref:manage-public-key-authentication-concept.adoc[공개 키를 사용자 계정과 연결]

+
계정 액세스를 활성화하기 전이나 후에 이 작업을 수행할 수 있습니다.

* 로그인 계정에 할당할 액세스 제어 역할을 잘 모르는 경우 '보안 로그인 수정' 명령을 사용하여 나중에 역할을 추가할 수 있습니다.


클러스터에서 FIPS 모드를 활성화하려면 지원되는 키 알고리즘이 없는 기존 SSH 공개 키 계정을 지원되는 키 유형으로 재구성해야 합니다. FIPS를 사용하도록 설정하기 전에 계정을 다시 구성해야 하며 그렇지 않으면 관리자 인증이 실패합니다.

다음 표에는 ONTAP SSH 연결에 지원되는 호스트 키 유형 알고리즘이 나와 있습니다. 이러한 키 유형은 SSH 공개 인증 구성에 적용되지 않습니다.

[cols="30,30,30"]
|===


| ONTAP 릴리즈 | FIPS 모드에서 지원되는 키 유형입니다 | FIPS 이외의 모드에서 지원되는 키 유형입니다 


 a| 
9.11.1 이상
 a| 
ECDSA-SHA2-nistp256
 a| 
ECDSA-SHA2-nistp256+RSA-SHA2-512+RSA-SHA2-256+ssh-ed25519+ssh-dss+ssh-ssh-rsa



 a| 
9.10.1 이하
 a| 
ECDSA-SHA2-nistp256+ssh-ed25519
 a| 
ECDSA-SHA2-nistp256+ssh-ed25519+ssh-dss+ssh-rsa

|===

NOTE: SSH-ed25519 호스트 키 알고리즘 지원은 9.11.1에서 제거됩니다

자세한 내용은 을 참조하십시오 link:../networking/configure_network_security_using_federal_information_processing_standards_@fips@.html["FIPS를 사용하여 네트워크 보안을 구성합니다"].

.단계
. 로컬 관리자 계정이 SSH 공개 키를 사용하여 SVM에 액세스할 수 있도록 합니다.
+
'보안 로그인 생성 - vserver_SVM_name_-user-or-group-name user_or_group_name-application_application_-AuthMethod_authentication_method_-role_role_-comment_comment_'

+
전체 명령 구문은 을 참조하십시오 link:config-worksheets-reference.html["워크시트"].

+
다음 명령을 실행하면 SSH 공개 키를 사용하여 SVM "engData1"에 액세스할 수 있도록 사전 정의된 "vsadmin-volume" 역할이 있는 SVM 관리자 계정의 vmadmin1이 활성화됩니다.

+
[listing]
----
cluster1::>security login create -vserver engData1 -user-or-group-name svmadmin1 -application ssh -authmethod publickey -role vsadmin-volume
----


.작업을 마친 후
공개 키를 관리자 계정에 연결하지 않은 경우, 계정이 SVM에 액세스하려면 먼저 연결해야 합니다.

xref:manage-public-key-authentication-concept.adoc[공개 키를 사용자 계정과 연결]
