---
permalink: authentication/grant-access-active-directory-users-groups-task.html 
sidebar: sidebar 
keywords: enable, active directory, account access 
summary: '보안 로그인 create 명령을 사용하여 AD(Active Directory) 사용자 또는 그룹 계정을 활성화하여 admin 또는 data SVM에 액세스할 수 있습니다. AD 그룹의 모든 사용자는 그룹에 할당된 역할을 통해 SVM에 액세스할 수 있습니다.' 
---
= Active Directory 계정 액세스를 설정합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
'보안 로그인 생성' 명령을 사용하여 AD(Active Directory) 사용자 또는 그룹 계정을 활성화하여 admin 또는 data SVM에 액세스할 수 있습니다. AD 그룹의 모든 사용자는 그룹에 할당된 역할을 통해 SVM에 액세스할 수 있습니다.

.무엇을 &#8217;필요로 할거야
* 클러스터 시간은 AD 도메인 컨트롤러에서 5분 이내에 에 동기화되어야 합니다.
* 이 작업을 수행하려면 클러스터 관리자여야 합니다.


.이 작업에 대해
* 계정이 SVM에 액세스하려면 먼저 클러스터 또는 SVM에 대한 AD 도메인 컨트롤러 액세스를 구성해야 합니다.
+
xref:enable-ad-users-groups-access-cluster-svm-task.adoc[Active Directory 도메인 컨트롤러 액세스 구성]

+
계정 액세스를 활성화하기 전이나 후에 이 작업을 수행할 수 있습니다.

* ONTAP 9.11.1부터 를 사용할 수 있습니다 link:../nfs-admin/ldap-fast-bind-nsswitch-authentication-task.html["nsswitch 인증을 위한 LDAP 빠른 바인딩"] AD LDAP 서버에서 지원하는 경우
* 로그인 계정에 할당할 액세스 제어 역할을 잘 모르는 경우 '보안 로그인 수정' 명령을 사용하여 나중에 역할을 추가할 수 있습니다.
+
xref:modify-role-assigned-administrator-task.adoc[관리자에게 할당된 역할 수정]



[NOTE]
====
AD 그룹 계정 액세스는 'SH' 및 'ontapi' 애플리케이션에서만 지원됩니다.

====
.단계
. AD 사용자 또는 그룹 관리자 계정을 사용하여 SVM에 액세스:
+
'보안 로그인 생성 - vserver SVM_name -user -or -group -name user_or_group_name -application application application -AuthMethod domain -role role role -comment comment comment[-is-ldap-fastbind true]'

+
전체 명령 구문은 을 참조하십시오 link:config-worksheets-reference.html["워크시트"].

+
link:config-worksheets-reference.html["로그인 계정 생성 또는 수정"]

+
다음 명령을 실행하면 AD 클러스터 관리자 계정 DOMAIN1\guest1에 미리 정의된 "백업" 역할을 사용하여 admin SVM "engCluster"에 액세스할 수 있습니다.

+
[listing]
----
cluster1::>security login create -vserver engCluster -user-or-group-name DOMAIN1\guest1 -application ssh -authmethod domain -role backup
----
+
다음 명령을 사용하면 AD 그룹 계정 DOMAIN1\adgroup의 SVM 관리자 계정을 미리 정의된 "vsadmin-volume" 역할로 사용하여 SVM "engData"에 액세스할 수 있습니다.

+
[listing]
----
cluster1::>security login create -vserver engData -user-or-group-name DOMAIN1\adgroup -application ssh -authmethod domain -role vsadmin-volume
----


AD 도메인 컨트롤러를 클러스터 또는 SVM에 액세스하도록 구성하지 않은 경우 계정이 SVM에 액세스하려면 먼저 액세스 권한을 구성해야 합니다.

xref:enable-ad-users-groups-access-cluster-svm-task.adoc[Active Directory 도메인 컨트롤러 액세스 구성]
