---
sidebar: sidebar 
permalink: authentication/oauth2-deploy-ontap.html 
keywords: certificate, install certificate, enable, enable oauth2 
summary: 핵심 OAuth 2.0 기능을 배포하려면 세 가지 기본 단계가 필요합니다. 
---
= ONTAP에 OAuth 2.0 배포
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
핵심 OAuth 2.0 기능을 배포하려면 세 가지 기본 단계가 필요합니다.



== 시작하기 전에

ONTAP를 구성하기 전에 OAuth 2.0 배포를 준비해야 합니다. 예를 들어 인증서의 서명 방법 및 방화벽 뒤에 있는지 등 인증 서버를 평가해야 합니다. 을 참조하십시오 link:../authentication/oauth2-prepare.html["ONTAP와 함께 OAuth 2.0을 배포할 준비를 하십시오"] 를 참조하십시오.



== 1단계: 인증 서버 인증서를 설치합니다

ONTAP에는 미리 설치된 루트 CA 인증서가 다수 포함되어 있습니다. 따라서 대부분의 경우 추가 구성 없이 ONTAP에서 인증 서버의 인증서를 즉시 인식합니다. 그러나 인증 서버 인증서 서명 방법에 따라 루트 CA 인증서와 중간 인증서를 설치해야 할 수도 있습니다.

필요한 경우 아래 제공된 지침에 따라 인증서를 설치합니다. 필요한 모든 인증서를 클러스터 수준에서 설치해야 합니다.

ONTAP 액세스 방법에 따라 올바른 절차를 선택합니다.

.단계
[role="tabbed-block"]
====
.시스템 관리자
--
. System Manager에서 * 클러스터 * > * 설정 * 을 선택합니다.
. 아래로 스크롤하여 * 보안 * 섹션으로 이동합니다.
. Certificates * 옆에 있는 * -> * 를 클릭합니다.
. 신뢰할 수 있는 인증 기관 * 탭에서 * 추가 * 를 클릭합니다.
. 가져오기 * 를 클릭하고 인증서 파일을 선택합니다.
. 사용자 환경에 대한 구성 매개 변수를 입력합니다.
. 추가 * 를 클릭합니다.


--
.CLI를 참조하십시오
--
. 설치를 시작합니다.
+
보안 인증서설치형 server-ca

. 다음 콘솔 메시지를 찾습니다.
+
`Please enter Certificate: Press <Enter> when done`

. 텍스트 편집기로 인증서 파일을 엽니다.
. 다음 행을 포함하여 전체 인증서를 복사합니다.
+
`-----BEGIN CERTIFICATE-----`

+
`-----END CERTIFICATE-----`

. 명령 프롬프트 후 터미널에 인증서를 붙여 넣습니다.
. Enter * 키를 눌러 설치를 완료합니다.
. 다음 중 하나를 사용하여 인증서가 설치되었는지 확인합니다.
+
`security certificate show-user-installed`

+
`security certificate show`



--
====


== 2단계: 인증 서버를 구성합니다

ONTAP에 하나 이상의 인증 서버를 정의해야 합니다. 구성 및 배포 계획에 따라 매개 변수 값을 선택해야 합니다. 검토 link:../authentication/oauth2-deployment-scenarios.html["OAuth2 배포 시나리오"] 구성에 필요한 정확한 매개 변수를 결정합니다.


TIP: 권한 부여 서버 정의를 수정하려면 기존 정의를 삭제하고 새 정의를 만듭니다.

아래에 제공된 예는 의 첫 번째 간단한 배포 시나리오를 기반으로 합니다 link:../authentication/oauth2-deployment-scenarios.html#local-validation["로컬 검증"]. 독립 실행형 범위는 프록시 없이 사용됩니다.

ONTAP 액세스 방법에 따라 올바른 절차를 선택합니다. CLI 절차에서는 명령을 실행하기 전에 교체해야 하는 기호 변수를 사용합니다.

.단계
[role="tabbed-block"]
====
.시스템 관리자
--
. System Manager에서 * 클러스터 * > * 설정 * 을 선택합니다.
. 아래로 스크롤하여 * 보안 * 섹션으로 이동합니다.
. OAuth 2.0 권한 부여 * 옆에 있는 * + * 를 클릭합니다.
. 추가 옵션 * 을 선택합니다.
. 다음과 같이 배포에 필요한 값을 제공합니다.
+
** 이름
** 응용 프로그램(http)
** 공급자 JWKS URI입니다
** 발급자 URI입니다


. 추가 * 를 클릭합니다.


--
.CLI를 참조하십시오
--
. 정의를 다시 만듭니다.
+
[source, cli]
----
security oauth2 client create -config-name <NAME> -provider-jwks-uri <URI_JWKS> -application http -issuer <URI_ISSUER>
----
+
예를 들면 다음과 같습니다.

+
[listing]
----
security oauth2 client create \
-config-name auth0 \
-provider-jwks-uri https://superzap.dev.netapp.com:8443/realms/my-realm/protocol/openid-connect/certs \
-application http \
-issuer https://superzap.dev.netapp.com:8443/realms/my-realm
----


--
====


== 3단계: OAuth 2.0을 활성화합니다

마지막 단계는 OAuth 2.0을 활성화하는 것입니다. ONTAP 클러스터에 대한 전역 설정입니다.


CAUTION: ONTAP, 인증 서버 및 지원 서비스가 모두 올바르게 구성되었는지 확인하기 전까지는 OAuth 2.0 처리를 활성화하지 마십시오.

ONTAP 액세스 방법에 따라 올바른 절차를 선택합니다.

.단계
[role="tabbed-block"]
====
.시스템 관리자
--
. System Manager에서 * 클러스터 * > * 설정 * 을 선택합니다.
. 아래로 스크롤하여 * 보안 섹션 * 을 찾습니다.
. OAuth 2.0 권한 부여 * 옆에 있는 * -> * 를 클릭합니다.
. OAuth 2.0 권한 부여 * 를 활성화합니다.


--
.CLI를 참조하십시오
--
. OAuth 2.0 활성화:
+
`security oauth2 modify -enabled true`

. OAuth 2.0이 활성화되어 있는지 확인합니다.
+
[listing]
----
security oauth2 show
Is OAuth 2.0 Enabled: true
----


--
====